### ISSUE TITLE
avatar rendering issue causes layout issue in commit form 

### ISSUE THREAD

**Issue by crontab** [desktop/desktop#5671] opened 2018-09-18 10:38 UTC
<img width="367" alt="screen shot 2018-09-18 at 12 10 48 pm" src="https://user-images.githubusercontent.com/1698529/45682021-66648e80-bb3f-11e8-9308-29aed2615919.png">

A few updates back I started experiencing this (see attached screenshot). The pixelated part is my full name and my email address. The summary input box became very small and difficult to use. I think a few times it fixed itself but most of the time I'm seeing this layout.

**Comment by tierninho** [comment] 2018-09-18 15:34
@crontab I am curious why your avatar is missing and why your name/email is in its place.

This is how it should look:
<img width="250" alt="screen shot 2018-09-18 at 8 32 03 am" src="https://user-images.githubusercontent.com/14828183/45698656-589e1180-bb1d-11e8-8580-17fe022c02a4.png">

What version of Desktop are you using? Which OS are you using? Thanks.

**Comment by crontab** [comment] 2018-09-18 15:40
@tierninho, apologies, forgot to mention in my report:

MacOS 10.13.6
GitHub Desktop 1.4.0

**Comment by crontab** [comment] 2018-09-18 15:43
Some additional info: in GitHub Desktop Preferences, under the Accounts tab my avatar is not showing, there's a broken picture icon instead. I do have an avatar picture on GitHub as you can see. I tried to log out and log in again, no luck: I'm seeing the same thing in the UI.

**Comment by tierninho** [comment] 2018-09-18 16:53
@crontab thanks for the added color. Once we resolve the broken avatar situation, the name+email should revert to your default avatar. Are you using GitHub Enterprise by chance? 

You can try clearing out your cache under View > Toggle Developer Tools. Uncheck everything but cache:

<img width="746" alt="screen shot 2018-09-18 at 9 49 24 am" src="https://user-images.githubusercontent.com/14828183/45703174-62794200-bb28-11e8-9f14-d09cbcfaed6d.png">

**Comment by crontab** [comment] 2018-09-18 17:01
@tierninho thanks for your suggestions!

Nope, nothing helped. When I sign out of my account and restart the app it becomes normal with some default avatar, but once I sign in it becomes the name/email thing again. Clearing the cache didn't help, I even tried the Application cache option too.

No enterprise accounts, no.

**Comment by tierninho** [comment] 2018-09-18 17:03
Ok, gonna label this a bug for now, and wait for another team member to chime in. Thanks for waiting.

**Comment by shiftkey** [comment] 2018-09-18 19:36
@crontab thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

Also, are there any errors in the dev tools (red indicator in the top-right of the window)? That might be a clue to understanding what's failing.

> but once I sign in it becomes the name/email thing again

This feels like the `title` text that we associate with the image:

https://github.com/desktop/desktop/blob/e3bde86f16ecd6820d16d28edb15e611f6ba78be/app/src/ui/changes/commit-message.tsx#L284-L286

Another theory that I have, but am not able to prove easily currently, is that we're requesting the avatar URL and getting a weird HTTP response back, that we try and use here instead of gracefully degrading to Hubot's avatar.

**Comment by billygriffin** [comment] 2018-09-24 17:27
Removing `bug` because we haven't been able to reproduce and haven't seen this before. @desktop/support any ideas on what might be happening here?

**Comment by crontab** [comment] 2018-09-24 17:35
@billygriffin how is this not a bug? As I understand it, it fails to display my avatar and on top of that it breaks the layout by displaying the img alt text and making the summary box difficult to use. So there are two problems at once and in fact it started a few updates ago, though can't say which exactly.

**Comment by billygriffin** [comment] 2018-09-24 17:41
@crontab Sorry, definitions of bug differ, but basically if it's specific to your configuration or not reproduceable, we don't consider it a bug. This doesn't mean it's not an issue worth looking into and certainly not intended to diminish your experience, just wanted to clarify terminology. The intent here is that any engineer on our team or in our community can pick up a bug and understand how to reproduce it, and this doesn't yet meet that criteria.

**Comment by shiftkey** [comment] 2018-09-24 17:53
@crontab we need more information to understand the issue, as I've not seen or heard about this behaviour from other users.

> I searched for http requests in the logs, all of them are for `https://github.com/login/oauth/authorize`, nothing related to the avatar as far as I can tell.

We don't log the details for the image requests, but I was wondering if there were any errors that look related to making HTTP requests.The Dev Tools **Network** tab might also show you this if it's running when the app tries to download the avatar.

It's interesting to see the DOM show this for the image  source - `blob:file:///6f5f43a8-38eb-431c-beba-aae847951097`. This is a way for us to avoid caching images to disk, and will correspond to an entry under the **Sources** tab  in the Dev Tools.

If you expand the **(no domain)** section in the left sidebar you should see an entry at the bottom of the list matching this GUID:

<img width="367" src="https://user-images.githubusercontent.com/359239/45969051-fd7e8a00-c008-11e8-8671-bdcb2c50492d.png">

<img width="265" src="https://user-images.githubusercontent.com/359239/45969062-053e2e80-c009-11e8-9d2f-507da5e9d87e.png">

On my machine, this looks like my avatar - what do you see for this blob?

<img width="755" alt="screen shot 2018-09-24 at 2 49 50 pm" src="https://user-images.githubusercontent.com/359239/45969105-230b9380-c009-11e8-96a3-b5fb39e46f83.png">

**Comment by crontab** [comment] 2018-09-24 19:48
@shiftkey thanks a lot for taking the time to respond!

Strangely my GitHub Desktop has just fixed itself: I had an issue with my WiFi connection for a moment and when the connection recovered suddenly I got my avatar back for the first time in a few months.

Which means this is likely an issue with a corrupt cache file. However like I said clearing application caches didn't help. Also I think having an alt for that image is probably not very useful (there's the title attribute that will be displayed as a tooltip).

**Comment by shiftkey** [comment] 2018-09-26 14:43
> Also I think having an alt for that image is probably not very useful (there's the title attribute that will be displayed as a tooltip).

In theory we have our default Hubot avatar that we show as a placeholder, and if we can identify the error that you were seeing maybe we can revert to showing that again, but it's not clear to me _how we can detect that situation currently if we're using a cached image_.

**Comment by crontab** [comment] 2018-09-26 14:50
@shiftkey I understand, I think the best theory here is that if you have a cached avatar image but it's damaged then you will get a layout screw up. The file exists but the GUI refuses to display it therefore you see the `alt` text instead.

I think it should be possible to reproduce the problem by corrupting the cached file e.g. by making it zero length, except I'm not sure where the files are kept to try it myself.

**Comment by tierninho** [comment] 2018-10-30 17:43
As other users ☝️ are experiencing this issue, re-adding the `bug` label. 

cc @billygriffin

**Comment by rusty595** [comment] 2018-10-31 09:36
I am also experiencing this issue. This is what I see for the blob it is using for the image source: 
![image](https://user-images.githubusercontent.com/10696825/47779151-528c7a80-dcf0-11e8-9ff3-e36a9f38f08f.png)

**Comment by shiftkey** [comment] 2019-07-30 17:48
I've dropped the `investigation-needed` here because it's been challenging to reproduce (and it often comes good after a . while), but if someone wants to have a look at this there's two areas that look interesting:

 - that last screenshot shows the avatar is downloaded as a valid PNG, but it's 0x0 pixels (and 0 bytes)
 - if someone is able to hack the development build to render an PNG for their avatar that looks like this do we see the same behaviour?

**Comment by niik** [comment] 2022-07-01 12:53
We have a fallback mechanism to display a default avatar as of https://github.com/desktop/desktop/pull/13719 which should have solved this issue. Given that we haven't had any activity here in a while I'm going to assume that's the case and close this out.

**Closed by niik** 2022-07-01 12:53 UTC
Labels: bug, priority-3
