### ISSUE TITLE
GitHub Desktop does not launch from Microsoft Edge or IE

### ISSUE THREAD

**Issue by shllybkwrm** [desktop/desktop#5087] opened 2018-07-03 16:08 UTC
## Description

When using Microsoft Edge (or Internet Explorer) and trying to clone a repo in GitHub Desktop, the link takes me to the Desktop download page rather than opening in the program on my computer.  When I do the same in Chrome, GitHub Desktop opens correctly.  (I use my work GitHub account in Edge, and my personal in Chrome, for those that wonder why I even use Edge ;).)

## Version

* GitHub Desktop:  1.2.6

* Operating system:  Microsoft Windows [Version 10.0.16299.125]

## Steps to Reproduce

1.  Navigate to desired repo in Microsoft Edge (or Internet Explorer)
2.  Click the green "Clone or download" menu
3.  Click the "Open in Desktop" link.

### Expected Behavior

GitHub Desktop opens and brings up the dialog to clone the repo (as it does when I use Chrome)

### Actual Behavior

Browser takes me to https://desktop.github.com/

**Comment by shiftkey** [comment] 2018-07-03 16:44
@shllybkwrm thanks for the report. I'm not aware of any recent changes to this area, but I'm trying to find an earlier discussion where we made some changes to how this area worked to see if it was also applied to IE and Edge.

@steveward have you encountered any similar reports about this recently for IE or Edge? I don't have access to Windows VMs at the moment, and it'd be nice to confirm this behaviour.

**Comment by steveward** [comment] 2018-07-03 17:52
@shllybkwrm @shiftkey I tested two scenarios out on my Windows 10 machine:

- logged in to GitHub Desktop and GitHub with the same account using Edge
- logged in to GitHub Desktop and GitHub with different accounts using Edge

Unfortunately I wasn't able to reproduce this issue in either case. One question @shllybkwrm -- if you log in to your personal GitHub account in Edge are you able to reproduce this issue?

**Comment by shiftkey** [comment] 2018-07-03 18:03
> I'm trying to find an earlier discussion where we made some changes to how this area worked to see if it was also applied to IE and Edge.

Aha, found it: https://github.com/desktop/desktop/issues/4231#issuecomment-372476740

The issue was reported against macOS, but I checked the changes to GitHub The Website and I couldn't spot any browser-specific hacks that might have affected IE/Edge.

**Comment by shllybkwrm** [comment] 2018-07-05 15:49
@steveward Good catch, my personal account is able to launch Desktop in Edge as expected.  My work account @sbagchi7 runs into the error on both Edge and Chrome.  I took a look through the account settings but didn't see anything that seemed applicable...

**Comment by shiftkey** [comment] 2018-07-06 11:17
> Is it possible the issue is that I'm logged into GitHub Desktop with @shllybkwrm?

@shllybkwrm I believe that is what is happening here.

When you sign into GitHub Desktop we set a flag to indicate that you have the tools installed and that we can show the right protocol handler to launch Desktop, rather than fallback to the download link. This is to prevent a confusing error when you try and clone a repository and don't have an app to handle it.

**Comment by shiftkey** [comment] 2018-07-10 12:55
I'm going to close this out because @shllybkwrm gave the last comment a 👍, but feel free to reply if there's anything further to add to the issue.

**Closed by shiftkey** 2018-07-10 12:55 UTC
Labels: more-information-needed, website

**Comment by LarryKlugerDS** [comment] 2018-10-10 11:14
I just had this problem on Windows.

Solution: I was already logged in on Github Desktop. But I was receiving the "Download Github Desktop" splash page from github.com

**Solution**

After I logged into github.com on IE, downloads to Github Desktop worked.

The puzzler is that this was with a public repo. Why should I have to login to github.com??

**Comment by aminya** [comment] 2020-06-10 09:26
I have this issue in the Edge chromium. Is there a solution?
