### ISSUE TITLE
Delete charactor in the IME cause charactor in the input gets delete

### ISSUE THREAD

**Issue by linonetwo** [desktop/desktop#12496] opened 2021-06-23 09:42 UTC
### Describe the bug

When pressing backspace with Chinese IME open, things inside input will be deleted too.

### Version & OS

MacOS 14.4 

Version 2.9.0 (x64)

### Steps to reproduce the behavior

1. type some thing
2. type with IME open
3. try delete some char in the IME window, see things get deleted in the input

### Expected behavior

Input won't delete anything, when we delete char in the IME window

### Actual behavior

Input delete a char, when we delete a char in the IME window

### Screenshots

https://user-images.githubusercontent.com/3746270/123074403-d4a1b280-d449-11eb-81a9-33e8c06cc161.mov

### Logs

I think we don't need this?

### Additional context

I'm using sougou pinyin Mac latest

**Comment by steveward** [comment] 2021-06-24 14:18
Thanks for the report @linonetwo. I tested out using Apple's built-in Pinyin Keyboard and was not able to reproduce this. My recommendation would be to use the built-in option or to report this to Sougou to see if they have an idea of what may be causing this. I'm going to close this out.

**Closed as completed by steveward** 2021-06-24 14:18 UTC

**Comment by linonetwo** [comment] 2021-06-25 08:38
I thought this difference is cause by their different implementation:

Built-in IME create char in the input too:
<img width="130" alt="截屏2021-06-25 下午4 31 59" src="https://user-images.githubusercontent.com/3746270/123395641-03976000-d5d3-11eb-8563-ae1483d5b738.png">

While Sougou and other modern Chinese IME keeps its internal state:
<img width="167" alt="截屏2021-06-25 下午4 31 39" src="https://user-images.githubusercontent.com/3746270/123395693-127e1280-d5d3-11eb-9886-13b334635794.png">


But, Strangely, in the Browser Sougou will create char in the input too, which is different to the behavior in the Desktop. I have my own Electron app, and Sougou will create char too:

<img width="563" alt="截屏2021-06-25 下午4 36 50" src="https://user-images.githubusercontent.com/3746270/123396270-b2d43700-d5d3-11eb-9660-5b2eca654361.png">

So I think this may need to be addressed on Desktop's side.

1. I would suggest listen on https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event and prevent deleting char in the input.
2. Otherwise, there must be some difference between the native input element and the commit input component of Desktop, that difference cause some IME can't create char in the input, which may be a problem to address

So could you reopen this issue @steveward ?
