### ISSUE TITLE
Can't disable auto-update.

### ISSUE THREAD

**Issue by M-SS-NGNUMB-R** [desktop/desktop#16227] opened 2023-02-28 21:59 UTC
### The problem

I can't close the program without potentially breaking my installation, but I don't have time to leave it running. I wasn't asked if I'm in a position to update, and I can't disable doing so automatically, which makes this a risky piece of software to use.

### Release version

3.1.7

### Operating system

Windows 10

### Steps to reproduce the behavior

Use GitHub Desktop at a time when you can't afford to start an update.

**Comment by sergiou87** [comment] 2023-03-01 08:51
Hello!

Disabling auto-update is not in our roadmap, sorry 😕 But updating it after closing the app should be pretty quick, specially on Windows where you get the "quit & restart" banner when the update is basically already installed (IIRC how Squirrel, the auto-update system Electron uses, works). How do you know if it takes long to install on your computer?

In any case I'd recommend you to react with 👍 and subscribe to #3410 so you will get notified if we finally decided to implement this. I'm closing this issue in favor of #3410, but I'm happy to follow up with your reply!

**Closed as completed by sergiou87** 2023-03-01 08:51 UTC

**Comment by DannyCarlton** [comment] 2024-01-13 14:57
I use GitHub Desktop on several computers, keeping the intranet on each consistent. However, my Win8.2 box can only run versions 3.2.1 or earlier. For now I have to install GitHub Desktop, update repos, then uninstall GitHub Desktop, otherwise is will update and break. Disabling autoupdate would make it much easier. Even a hack that would simply prevent it from accessing the update would work.

**Comment by robdplatt** [comment] 2024-01-30 16:56
> I use GitHub Desktop on several computers, keeping the intranet on each consistent. However, my Win8.2 box can only run versions 3.2.1 or earlier. For now I have to install GitHub Desktop, update repos, then uninstall GitHub Desktop, otherwise is will update and break. Disabling autoupdate would make it much easier. Even a hack that would simply prevent it from accessing the update would work.

As mentioned in https://github.com/desktop/desktop/issues/3410#issuecomment-507786136, rename Update.exe and it will break the auto-update process.

**Comment by DannyCarlton** [comment] 2024-03-27 13:16
> > I use GitHub Desktop on several computers, keeping the intranet on each consistent. However, my Win8.2 box can only run versions 3.2.1 or earlier. For now I have to install GitHub Desktop, update repos, then uninstall GitHub Desktop, otherwise is will update and break. Disabling autoupdate would make it much easier. Even a hack that would simply prevent it from accessing the update would work.
> 
> As mentioned in [#3410 (comment)](https://github.com/desktop/desktop/issues/3410#issuecomment-507786136), rename Update.exe and it will break the auto-update process.

That's the idea. Did you not read the initial question?

**Comment by darvi-sh** [comment] 2024-10-28 10:28
Auto update does not honor **Low Data mode**.

**Comment by agustinov** [comment] 2025-08-27 17:08
AutoUpdate BREAKS the current installed version and after closing current version new version doesn't start (even when trying to start manually). Just give users option to turn-off this f**bugging autoupdate.

**Comment by JeremySH** [comment] 2025-12-28 00:09
I think an improvement to auto update would be: first check if the new version of Desktop will be incompatible with the user's OS. If so, overwrite the executable file with random bytes, bricking it. This would save on bandwidth.

**Comment by DoomyDwyer** [comment] 2026-01-07 00:46
On my Mac, running Big Sur and with no plans to update, coz who knows what that could break in my build toolchain, autoupdating to the latest version, which won't run on Big Sur, is really crippling and extremely annoying. Each time I restart GitHub Desktop, or even just restart my Mac, renders GitHub Desktop inoperable, so I have to reinstall with an older version each time, just to continue working. Not happy, especially with this statement that you have no intention to even add a simple preference to opt out of autoupdates.

**Comment by DoomyDwyer** [comment] 2026-01-12 01:15
Such a simple thing and you can't be bothered to do it.

**Comment by JeremySH** [comment] 2026-01-22 20:05
I've since switched to SourceTree and use a personal access token. It works pretty well for my needs but YMMV. 

The issue is I need to develop on older systems, and I'm OK with using older software. But I can't work with software that bricks itself (obviously).
