### ISSUE TITLE
Pull requests are only listed for the first instance of a repository

### ISSUE THREAD

**Issue by bdenhollander** [desktop/desktop#8632] opened 2019-11-14 15:48 UTC
### Describe the bug

When the same repository is cloned twice, GitHub Desktop only lists the Pull Requests for the repository on one of the instances.

### Version & OS

2.2.3 on Windows 10

### Steps to reproduce the behavior

1. Clone a repository that has open PRs
2. Clone the repository again to another folder
3. Go to the first instance and click the branch picker. Pull requests are listed.
4. Go to the second instance and click the branch picker. Pull requests is empty.

### Expected behavior

Pull requests should be listed on both instances.

### Actual behavior

Pull requests are only listed on the first instance

### Additional context

This is not new and has been an issue since PRs were added to GitHub Desktop.

**Comment by tierninho** [comment] 2019-11-14 19:36
@bdenhollander Thanks for this report. I can confirm that this is happening in v 2.2.3 and I am labeling it as a bug for now. However I am unsure if this is intended behavior or not.

**Comment by kuychaco** [comment] 2019-11-14 22:22
I would say that this is a bug, and is not intended behavior. Thanks for the report @bdenhollander!

**Comment by outofambit** [comment] 2020-02-04 00:40
this was fixed in #8858, which shipped in GitHub Desktop v2.3 🎉!

**Closed by outofambit** 2020-02-04 00:40 UTC
Labels: bug, priority-3
