### ISSUE TITLE
Add GUI support for git's "stash store" and "stash apply" commands

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2304] opened 2017-07-23 17:04 UTC
### Description

As nice as GitHub Desktop's "magic stash" was it didn't cover all my git stash use cases… I still found myself using command line git too often (to store/apply stashes)… and I still do…

So… having "Store Stash" and "Restore Stash" buttons would be awesome…

Having a "stash list" popup menu would be gravy. ;-)

### Version

**GitHub Desktop version:** Deer Types (222)
**OS version:** 10.12.6

**Comment by shiftkey** [comment] 2017-07-24 13:33
@geowar1 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our
[current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out,
so that we don't get overwhelmed with our backlog! We'll revisit these as part
of our next planning session.

**Closed by shiftkey** 2017-07-24 13:33 UTC
Labels: enhancement, future-proposal

**Comment by shiftkey** [comment] 2017-11-20 23:32
A suggested workflow from @smilecs was proposed in #3379:

> **Expected behavior:**
> 1. Have stash button on app bar.
> 2. Click button, then a dialog comes up asking to name the stash
> 3. After naming the stash,  all uncommited changes are stashed with name.
> 4. Stashed items are found on side navigation.

**Comment by XedinUnknown** [comment] 2018-02-28 08:58
How about the "apply" flow? Can we choose whether to pop or apply? Can we also choose _which_ part of the stash to apply? That would be awesome!

Just want to mention that I am a long time Git CLI user, and have no problems with it, and love the granularity and so on. But GH desktop can really save some time, and is especially useful to me for not only quick peeks at projects, but also for interactive staging. Being able to apply a stash interactively would also be really beneficial, because doing that from CLI is inconvenient.

**Comment by surdu** [comment] 2018-03-20 13:29
Would PRs from the community be accepted regarding this feature?

**Comment by adamreisnz** [comment] 2018-05-28 02:16
I am also in favour of this feature. Stashing is a very frequent operation, and it is currently one of the few commands I still have to leave Github desktop and go into the command line for. It'd be great to have a simple, intuitive GUI for simple stash/unstash operations.

**Comment by shacker** [comment] 2018-05-28 07:03
I moved from Atlassian SourceTree to Github Desktop because SourceTree was becoming slow, and GHD feels "just right," but the absence of manual stash support is a serious ding to the workflow - the one thing for which I have to return to the shell several times per day. Thumbs up to this feature!

**Comment by shiftkey** [comment] 2018-05-28 23:30
@surdu

> Would PRs from the community be accepted regarding this feature?

It'd be nice to be able to sketch out how this feature would work from the UI/UX perspective, so that we can think about the flow of the feature as well as think about potential corner cases. We've got a fair idea of the Git plumbing that's needed for a feature like this, but **understanding how stashes are presented to the user and how this feature could be used to store and apply stashes will help rally people behind it**.

Personally speaking, I'd love to see a simple UI walkthrough for stashing some changes, switching branches, and restoring them, that answers these questions:

 - how does the user initiate stashing changes when there are changes in the working directory?
 - when stashes are available for the current repository, how does the user notice this in the UI?
 - how does the user apply a stash to the repository from the UI?

I also think this feature depends on us making Desktop better at handling the merge conflicts that may arise from applying stashes. That's on [our roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md#17---conflict-resolution), but we can cover the other parts of this feature request in the meantime.

**Comment by surdu** [comment] 2018-07-13 12:51
I see it as a tab named `Stash` next to `Changes` and `History` tabs. It will list you stashes in the same manner as History lists commits.

When you right-click an entry, it will display a pop-up with `Apply` and `Delete` entries.

Clicking `Apply` will display a confirmation window that shows the usual "Are you sure" message and three buttons: `Apply`, `Apply & Delete`, `Cancel`

To stash current changes, there could be a button somewhere next to the Commit button, but frankly, for minimal UX impact and low effort, a menu entry in Repository I believe will suffice.

**Comment by dillydadally** [comment] 2018-07-18 02:09
I've got to add my support to magic stashing as well - whether in the old form or some new form.

I'm trying to transition a group of programmers to git that have little experience in source control. The problem is, the _current_ functionality is _horrible_ and much worse than the problems listed above with magic stashing. It's like choosing to keep a _huge_ issue because you don't want to address a significantly smaller issue the solution would create.

You want to talk about confusing new users? How about bringing changes over from one branch to a new one silently so they accidentally commit unfinished changes to the wrong branch!? This has already happened _on our first day!__ I know this is how git works by default, but in my opinion it's one of the core deficiencies with git, and every other git gui I've ever used prompts you to stash before every checkout to circumvent that. 

Either there needs to be a magic stash or a manual stash with a prompt to stash every time you switch branches whether git errors or not. This is the bare minimum. It seems to me some sort of stash is a core feature required to even use git, so I'm not sure what other features would be more important to add first. As it is right now, I have to tell people to make sure they commit before checking out another branch every single time, which is going to pollute our history, but there's no way I can get the entire team that's already reluctant to use proper source control to use a terminal just to stash before every checkout. The current functionality is the core problem with the current version in my opinion and makes it pretty unusable.

**Comment by billygriffin** [comment] 2018-07-18 14:22
Really appreciate you laying out how this breaks down @dillydadally. We’re kicking off a round of research to look into problems related to merge conflicts, and we’ll be doing a portion of that with beginners, so I’m hoping we can see how this happens first-hand and evaluate possible solutions.

**Comment by j-f1** [comment] 2018-07-18 19:32
@dillydadally For the merging issue, once 1.3.0 comes out (you can use the beta to get the feature now) the “History” tab will change to a “Compare” tab where you can merge by picking another branch and clicking the merge button.

**Comment by surdu** [comment] 2018-07-19 07:01
@j-f1 Where can one get the beta from ?

**Comment by billygriffin** [comment] 2018-07-19 14:50
Re: @j-f1's last comment, if you'd like to use the beta version, you can download it here: https://github.com/desktop/desktop#beta-channel

**Comment by barbara-sfx** [comment] 2018-08-24 23:32
Looks like all the issues related to stashing are closed. Can anyone confirm that means we just have to pray that the old version never stops working? The new version makes it TOO EASY to apply changes in one branch to a different branch, as others have noted, which can wreak havoc on live sites. Talk about confusing new users! Is there no hope for resolution of any kind?

**Comment by billygriffin** [comment] 2018-08-25 00:01
Hi @barbara-sfx, thanks for the feedback. We agree that GitHub Desktop should have an improved experience to handle the two major cases where stashing seems to be common:

1. When you want to bring your changes from one branch to another
2. When you want to switch to another branch to do some other task, but don't want to lose your changes and retain them for when you come back to the current branch

So while this is not prioritized for the next couple months, it is definitely something we're interested in supporting, and I apologize that it's such a pain for you. In this issue (https://github.com/desktop/desktop/issues/5398) we're working through how we're communicating our priorities and hopefully enabling the community to better introduce features that we think should be in place but don't have the resources to prioritize immediately. Thanks again!

**Comment by billygriffin** [comment] 2018-10-12 13:28
@vnvbsudhakar A few of the above posts are referring to the classic version of Desktop, which has not been supported for more than a year and we have no intention to do so. I also know this is a much-desired feature and we're actively discussing where it fits in prioritization, and I'm sorry that it's not there at present.

**Comment by billygriffin** [comment] 2018-11-15 17:36
Since we're looking at this in the context of #6107 I'm removing the `future-proposal` label here.

**Comment by w3debugger** [comment] 2020-01-16 10:46
I still can't see this feature. 😔When are we planning to release it? 🤔

**Comment by billygriffin** [comment] 2020-01-16 19:41
@w3debugger Our implementation of stashing appears when people switch branches with uncommitted changes, as we found that that's by far the largest use case for when people need to stash. We also know that some folks prefer to stash for various reasons while on a given branch, but we don't think it's a large enough use case at this point to prioritize. We're not wedded to that stance though and might potentially consider a separate more manual stashing option down the road.

**Comment by adamreisnz** [comment] 2020-01-16 20:47
I do love the approach you've taken with this, and covers pretty much all our needs and use cases 👍

**Comment by w3debugger** [comment] 2020-01-22 21:10
@billygriffin yay 🎉 found the GUI for stash 👍thanks 

Actually, I'm doing a lot of experiments while developing any feature, so I use stash too much. **SourceTree** is showing the **Stash List** and that's really helpful 👇 

<img width="98" alt="sourceTree-stash" src="https://user-images.githubusercontent.com/6707482/72933755-cb577680-3d7b-11ea-8970-f102478233c8.png"> 

but sourceTree is really slow as compared to GitHub Desktop so I was looking forward to see this feature.
