### ISSUE TITLE
App window size minimum now constrained to 1320px

### ISSUE THREAD

**Issue by AshSimmonds** [desktop/desktop#13940] opened 2022-02-18 06:38 UTC
### Describe the bug
Up until today'ish update I've been able to use the W10 app on my second vertical monitor (1080x1920), but now it doesn't fit on the screen any more.

### Version & OS

Windows 10
V 2.9.9 (x64)

### Steps to reproduce the behavior

1. Open the app
2. Try to resize it less than 1320px or maximise it on a screen <1320px
3. Critical stuff on the right is now obfuscated and unusable

### Expected behavior

It was working fine yesterday being able to fit within the 1080px wide bounds without affecting the integrity of the application.

### Actual behavior

As title.

### Screenshots

See screenshot - anything in the red zone is now unusable.

![screenshot_20220218-170602](https://user-images.githubusercontent.com/9034041/154631006-984a15ac-5583-40e4-b6c6-10966f3df14e.png)

### Logs

N/A

### Additional context

None.

**Comment by AshSimmonds** [comment] 2022-02-18 06:40
Previous issue was closed ( https://github.com/desktop/desktop/issues/8923 ), but this is a new seemingly unnecessary constraint introduced which disrupts workflow.

**Comment by sergiou87** [comment] 2022-02-18 08:18
Thanks for your report @AshSimmonds!! ❤️ 

I just tried that and I was able to resize the app to around 960x660. Does it change anything if you close the app and open it again?

**Comment by AshSimmonds** [comment] 2022-02-18 08:47
Nope, same issue. Clean restart. Can see behaviour in this vid with how my monitors are set up:

 - https://youtu.be/PHzPnbP_twQ

**Comment by sergiou87** [comment] 2022-02-18 09:28
Interesting, thanks for that video! Is your interface scaled maybe? Have you tried on another machine? I also wonder if using it with multiple monitors has anything to do with it 🤔 

Just for clarity, we haven't changed anything around that minimum. However, in the last 3 releases (2.9.7-2.9.9) we have upgraded Electron twice, which could cause this sort of issues, so I'm trying to pinpoint reasons for this to happen 😅

**Comment by AshSimmonds** [comment] 2022-02-18 09:41
It could well be to do with scaling as I use 125% on those two monitors, but my third (not in vid) is 100% scale at 1920x1080 and it's same there - so guess if it's scaling then 125% would override, for whatever reason.

Point being though this was a sudden flip - as in I was using the app as usual (squished to 1080px wide), got the update available thingy so let it do that, and less than 30 seconds later this new restriction was there.

Can make another vid switching settings if necessary, just didn't feel like resetting all my window placements etc (Powertools) again.

**Comment by sergiou87** [comment] 2022-02-18 10:28
Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from the day where you experienced the issue for the first time.

**Comment by AshSimmonds** [comment] 2022-02-18 10:45
There's a bunch of logs but only latest has refs to update. I think the app had been open 2-3 days before I clicked the update link, was on 2.9.6 then as soon as I updated to 2.9.7 the 2.9.9 release came through.

[2022-02-18.desktop.production.log](https://github.com/desktop/desktop/files/8096416/2022-02-18.desktop.production.log)

![screenshot_20220218-211258](https://user-images.githubusercontent.com/9034041/154667999-0b3afcde-3d60-4dea-ba68-fd5ad58c7278.png)

**Comment by sergiou87** [comment] 2022-02-18 10:49
That's perfect, thanks 😄  Do you know which one exactly broke this for you? Was it 2.9.7 or 2.9.9?

**Comment by AshSimmonds** [comment] 2022-02-18 10:55
I'm pretty sure the app did a double update - as in I clicked the update link and it closed and re-opened, but the update link was still there so I clicked it again, so guessing that's where it was. However I don't recall doing anything actively in 2.9.7, just straight to update.

**Comment by sergiou87** [comment] 2022-02-18 11:16
Ohhh ok, so you can't tell if it was already broken on 2.9.7, right?

**Comment by AshSimmonds** [comment] 2022-02-18 11:19
Yes I can't.

**Comment by mateeni-dev** [comment] 2022-02-18 12:13
Hi,

I am experiencing a similar issue on a windows 10 machine with version 2.9.9 which was not there on previous version (from log file) ==> `launching: 2.9.8 (Windows 10.0.19044)`

For me the problem is that the github app (when maximized) hides the windows taskbar at the bottom, which was not the case up-to v2.9.8

About size, I have never tried changing app window size before as I have always used the app in maximized mode so not sure if that is a new thing, but I can't change the size of app to fit the screen height on my monitor in v2.9.9 (i.e., when app is not maximized). By default app height is bigger than my screen resolution `1366 x 768`

I am using a single monitor with 125% scale. Haven't tried scaling down yet

![gh-issue](https://user-images.githubusercontent.com/36093197/154680922-be7ef0ac-a474-4d78-b072-0e564b3c2c7f.jpg)

**Comment by sergiou87** [comment] 2022-02-18 12:36
I cannot repro that issue with the taskbar either. Please, give it a try and set the scale to 100% and let me know if that helps. For clarity, I'm not saying that is the way to fix it, I just want to know if the screen scale has anything to do with this new weird behavior 😅

**Comment by AshSimmonds** [comment] 2022-02-18 12:53
Ok, can confirm it's to do with scaling:

 - https://www.youtube.com/watch?v=prYu1znfhdQ

**Comment by sergiou87** [comment] 2022-02-18 13:01
Thank you for confirming that!

It has to be a change in Electron's behavior, we're setting the min size like this: https://github.com/desktop/desktop/blob/c65bb415a16ce58d4e40a941d8b86ca0f9dbe957/app/src/main-process/app-window.ts#L32-L52

**Comment by AshSimmonds** [comment] 2022-02-18 13:03
Ok thanks, at least I know I wasn't bonkers - well, on this issue at any rate. Not a difficult work-around until it's sussed out.

**Comment by mateeni-dev** [comment] 2022-02-19 13:20
Scaling down to windows default `100%` fixed it for me as well.

![gh-issue](https://user-images.githubusercontent.com/36093197/154802460-05f14070-7c3e-4d5b-97bb-c59c2f07ad5a.jpg)

**Comment by placoderm** [comment] 2022-04-13 10:37
I am also having a similar problem. Can confirm that when setting the display to 100% it is not a problem. But at 175% the bottom is cut off. 1920X1080

**Comment by tsvetilian-ty** [comment] 2022-05-14 16:31
It looks like the issue is fixed for Electron 17.2.0 and above https://github.com/electron/electron/pull/33231

**Comment by AshSimmonds** [comment] 2022-06-26 00:55
This issue has regressed again.

**Comment by tsvetilian-ty** [comment] 2022-06-26 19:15
👋 @AshSimmonds the fix should be available in the [beta track](https://desktop.github.com/release-notes/?env=beta), and it'll be in the production channel next week. You can follow https://github.com/desktop/desktop/pull/14861

**Comment by sergiou87** [comment] 2022-09-06 15:20
Closing this as it will be finally fixed with the Electron upgrade to v19 in 3.0.8. See https://github.com/desktop/desktop/pull/15239

**Closed as completed by sergiou87** 2022-09-06 15:20 UTC
Labels: bug, windows, electron, priority-3

**Comment by DoctorDerek** [comment] 2026-03-18 22:32
Still a problem
