### ISSUE TITLE
Hidden taskbar does not unhide when in maximized window

### ISSUE THREAD

**Issue by kitsorfan** [desktop/desktop#14150] opened 2022-03-11 12:11 UTC
### Describe the bug
I have selected from Windows settings to automatically hide the taskbar in desktop mode. In every other window when I place the cursor on the bottom of the screen, the taskbar will automatically show up again; but when I am in GitHub Desktop (maximized window) the taskbar will remain hidden. Such behavior is expected in full-screen mode, not on maximized window.

### Version & OS

Windows 10 Home x64, GitHub Desktop Version 2.9.11 (x64)

### Steps to reproduce the behavior

1. Change taskbar settings to automatically hide
2. Open GitHub desktop and maximize window
3. Move the cursor on the bottom of your screen (or where you have your taskbar)
4. See error, the taskbar won't show up.

### Expected behavior

The taskbar should show up when cursor is placed on the bottom of the screen, when in maximized window.

### Actual behavior

The taskbar won't show up.

## Screenshot 
Red line shows position of the cursor
![Screenshot (85)](https://user-images.githubusercontent.com/16962623/157864609-943c9886-3812-4eae-b30b-cc64c20e2bb3.png)

**Comment by tsvetilian-ty** [comment] 2022-03-11 14:16
@kitsorfan, the issue is already reported #14009.

**Comment by steveward** [comment] 2022-03-11 15:15
Thanks for the issue @kitsorfan, closing this as a duplicate of #14009.

**Closed as not planned by steveward** 2022-03-11 15:15 UTC
