### ISSUE TITLE
Default Branch does not Update

### ISSUE THREAD

**Issue by alburdette619** [desktop/desktop#5709] opened 2018-09-21 19:47 UTC
## Description
Upon updating the default branch in my private GitHub repo, Desktop does not update.  The old branch is still marked as default and used by default for new branches.

## Version
* GitHub Desktop: 1.4.0

* Operating system: macOS High Sierra V 10.13.6

## Steps to Reproduce
1. Have a private GitHub repo with a default branch `dev`
2. Create another branch named `develop`
3. Change the settings of the branch such that `develop` is the default.
4. Go back to GitHub Desktop, restart, do whatever, and observe that the default branch remains `dev`

### Expected Behavior
On the next fetch or at least upon restarting the app, the default branch would update accordingly to `develop`

### Actual Behavior
The default branch remains the previous default branch.

## Additional Information
<img width="758" alt="screen shot 2018-09-21 at 3 40 05 pm" src="https://user-images.githubusercontent.com/22638838/45902516-b1d3a280-bdb4-11e8-80c8-dd7d102a86cf.png">
<img width="282" alt="screen shot 2018-09-21 at 3 40 15 pm" src="https://user-images.githubusercontent.com/22638838/45902518-b1d3a280-bdb4-11e8-9e58-4212e20e2d4f.png">

### Logs
It happened one of these days based off history.  I don't see anything relating to `default`, but maybe they'll be useful.

[2018-09-13.desktop.production.log](https://github.com/desktop/desktop/files/2406783/2018-09-13.desktop.production.log)
[2018-09-14.desktop.production.log](https://github.com/desktop/desktop/files/2406784/2018-09-14.desktop.production.log)

**Comment by billygriffin** [comment] 2018-09-21 21:52
I was able to reproduce this just now with a private repo *and* a public repo. Since we sort the default branch separately from the others and call it out specifically, I'm going to categorize this as a bug. But if I'm missing something, others feel free to weigh in.

**Comment by tierninho** [comment] 2018-09-21 22:00
Seems like a regression: https://github.com/desktop/desktop/pull/1336

**Comment by alburdette619** [comment] 2018-09-25 13:10
@tierninho agreed, I saw the old issues too and since . it's not specific to a private repo it's not a new case.  Also, you're welcome @billygriffin 😄

**Comment by njbmartin** [comment] 2019-01-21 11:44
Just updated one of my repos to switch the default branch. Desktop is still referencing the old default.

Looking at DevTools, when you fetch, it makes a call to `https://api.github.com/repos/*/*` and the new default branch is returned correctly, but it seems to be ignored.

**Comment by spkapil123** [comment] 2019-04-19 09:44
I am using Github version 1.6.5, I am facing the same issue.
After updating the default branch in github, the same is not updating on Github desktop application.
The workaround suggested in #6857 suggests to clone the repository all over again. 
Can we have a fix in such way that the application updates the default branch?

**Comment by billygriffin** [comment] 2019-04-19 19:40
@spkapil123 We totally agree that it's not a great solution - the fix for this issue should indeed do what you described, but we haven't had an opportunity to work on it yet and I can't promise that it'll be right around the corner, but `priority 2` does indicate that we recognize that it's a meaningful bug. Thanks for sharing how it impacted you.

**Comment by EasonApolo** [comment] 2019-05-07 11:59
I met the same problem. I just remove the repository from Github Desktop then add it again and the default branch is updated.

**Comment by naveenila1221** [comment] 2019-07-04 06:08
I am also facing same issue

**Comment by aleerezaee** [comment] 2019-07-18 14:05
I'm also facing the same issue.

**Comment by iAmWillShepherd** [comment] 2019-07-19 14:54
@alburdette619 ,

I've attempted to reproduce this in the latest version of Desktop and was unable to do so and I created [this video](https://youtu.be/j-3F6RfcGKc) to explain why this may have seemed like a bug. In short, the default branch won't be updated in Desktop unless you reload the repository. 

Since this doesn't seem to be an issue in the latest version of Desktop, I'm going to close this out.

@naveenila1221 @aleerezaee could you try testing this out again to see if it's still an issue after repeating the steps I did in my video?

**Closed by iAmWillShepherd** 2019-07-19 14:54 UTC
Labels: bug, priority-2

**Comment by tierninho** [comment] 2019-07-19 18:20
I concur with @iAmWillShepherd that is is fixed, and I agree there is a slight lag in seeing the actual switch on Desktop.

**Comment by Timawg** [comment] 2019-08-22 10:23
This is still an issue for me in the latest version

**Comment by outofambit** [comment] 2019-08-22 14:56
@timawg, even after reloading the repository? (as mentioned in https://github.com/notifications/v2/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDM4MjkzMTYxNjo5NjQ5MTI=#issuecomment-513260416)

**Comment by celloworld** [comment] 2019-08-23 19:29
@Timawg Click the Current Repository dropdown in the top-left corner and select the already selected repo to reload it, which will re-sync the default branch.
<img width="289" alt="Screen Shot 2019-08-23 at 12 24 53 PM" src="https://user-images.githubusercontent.com/3270144/63618660-767fbc00-c5a1-11e9-9623-9db4301e725a.png">

**Comment by Timawg** [comment] 2019-09-03 10:54
@celloworld That did the trick, thank you!

**Comment by charles01pd2018** [comment] 2020-10-18 00:40
@celloworld MANY MANY THANKS

**Comment by mertkura** [comment] 2021-02-23 15:02
I can still reproduce this problem when i clone local repository at my local git server with github desktop app.

Steps:
- Install local git server with https access (Gitlab ce, vanilla git, local bitbucket [tested on these options])
   * You may use gitlab online to reproduce. Because of it is not listed in "Clone a repository" menu.
- Install lastest github desktop application and follow substeps of : "File->Clone a Repository" then in popup menu "URL -> https://mylovelydomain.babygitserver.com/foo/bar/unluckyrepo.git"
   * Example for gitlab, fork this in your gitlab account then test with your fork : "https://gitlab.com/gitlab-org/gitlab.git" - Default branch : master
- Clone it.
- Commit and push something to keep origin updated. 
- Create new branch, develop in my case.
- Change default branch to develop.
- My server keeps updated data (develop : default branch), but github desktop app keep telling me my default branch is master.
Example image from creating new branch.
![resim](https://user-images.githubusercontent.com/20698762/108861544-61ee0b00-7600-11eb-97aa-3601f89f1501.png)
Example image from my gitlab repo example, samething happens in every repo which cloned via URL reference. (Gitlab example in image)
![resim](https://user-images.githubusercontent.com/20698762/108861803-aa0d2d80-7600-11eb-9a5d-3720b5a21dda.png)

This may not be a bug due to URL reference(which is not linking application with target repo/server, but i think you should now this.

Note: If someone encounter this problem, you may use workaround solutions such as ;
- To create new branch from develop, checkout develop then select 2nd option in Create a branch popup when creating new branch.
![resim](https://user-images.githubusercontent.com/20698762/108862307-299afc80-7601-11eb-8f90-66497a9df77f.png)

- To Update new branch from default, manually rebase from git cmd or via merging with temp merge branch.

**Comment by jorycadence** [comment] 2021-09-02 18:58
I got around this by deleting the GitHub Desktop app and the `~/Library/Application Support/GitHub Desktop` directory, then re-installing the app and re-adding the repos to the app.

**Comment by RaddadZ** [comment] 2021-09-27 14:48
if anyone still facing this problem:

-  try running this command in your repo folder: `git symbolic-ref refs/remotes/origin/HEAD`
![image](https://user-images.githubusercontent.com/10570707/154636641-f4d4745b-b6ff-4881-ad24-0be854e98614.png)
- if you get the old default branch name, then go to **\<your repo folder\>/.git/refs/remotes/origin/HEAD** and change its value to your real default branch
![image](https://user-images.githubusercontent.com/10570707/154636580-6511789c-9df6-40cb-ab45-f7dee7a5918e.png)
- restart Github Desktop, that's it! it should recognize the real default branch in creating, rebase, and everywhere else.
![image](https://user-images.githubusercontent.com/10570707/134931904-aadea4f6-f7af-4fcb-9b3a-a09688f3e6fe.png)

**Comment by drakebyte** [comment] 2021-12-10 21:40
[THIS ](https://github.com/desktop/desktop/issues/5709#issuecomment-927948403 )comment is the answer, and it worked. too bad it isn't fixed yet.

**Comment by angelsk** [comment] 2021-12-13 11:43
Still getting this issue Version 2.9.5 (x64) - I have done the symbolic refs and updated. Restarted the app. It's still not detecting the correct branch as default; and keeps offering to do a PR with no changes. Very frustrating.

<img width="848" alt="Screenshot 2021-12-13 at 11 43 03" src="https://user-images.githubusercontent.com/606510/145806280-c0fb3e89-5c52-4c79-a791-78ea4ada1a95.png">

![Screenshot 2021-12-13 at 11 43 19](https://user-images.githubusercontent.com/606510/145806324-fab6966a-d7c6-40ec-a984-d02acbe8a823.png)

**Comment by RaddadZ** [comment] 2021-12-23 23:25
> Still getting this issue Version 2.9.5 (x64) - I have done the symbolic refs and updated. Restarted the app. It's still not detecting the correct branch as default; and keeps offering to do a PR with no changes. Very frustrating.
> 
> <img alt="Screenshot 2021-12-13 at 11 43 03" width="848" src="https://user-images.githubusercontent.com/606510/145806280-c0fb3e89-5c52-4c79-a791-78ea4ada1a95.png">
> 
> ![Screenshot 2021-12-13 at 11 43 19](https://user-images.githubusercontent.com/606510/145806324-fab6966a-d7c6-40ec-a984-d02acbe8a823.png)

dont forget the second step, it's the real solution, inside your repo folder you have .git directory 
`go to .git/refs/remotes/origin/HEAD and change it's value to your real default branch`

**Comment by staabm** [comment] 2022-03-27 06:48
also having this problem today.. it seems this issue should still be open

**Comment by jacksonhuether** [comment] 2022-04-04 19:49
I had the same issue. Fixed by deleting the GitHub Desktop folder from Application Support and the app from the Applications folders, re-downloading, and re-adding the local repositories on my M1 Mac.

**Comment by antondim** [comment] 2022-06-08 07:56
Had the exact same issued. 

Surprisingly all I had to do was to clone my repository on different path. 
After doing this, default branch was the intended (the one that is shown on github web), and also 
Branch->Update from "default branch",  option was working too. 

Then removed the repo that had just created.
 On my old branch the default branch is the correct one and Branch->Update from "default branch" option was working there too .

**Comment by dwilt** [comment] 2022-07-14 21:34
I just removed the repo and re-cloned it and it fixed itself
