### ISSUE TITLE
Specific file history among different commits

### ISSUE THREAD

**Issue by MohamedElbar** [desktop/desktop#12338] opened 2021-06-02 09:33 UTC
**I can't check the history for a specific file among all commits** 

I need to right-click on a specific file -> show history .. so the application shows all the commits that include this file and I can compare between the file versions in different commits and the current version.

**Comment by billygriffin** [comment] 2021-06-02 20:24
Thanks for the idea! Closing as a duplicate of #11990 so please feel free to weigh in there. 😄

**Closed as completed by billygriffin** 2021-06-02 20:24 UTC
Labels: enhancement
