### ISSUE TITLE
Feature request: discard line/hunk

### ISSUE THREAD

**Issue by francisrath** [desktop/desktop#3225] opened 2017-11-03 08:58 UTC
### Description
I am very much missing the discard line/ discard hunk feature of SourceTree. Is there any way we could have a similar feature in GitHub Desktop?

### Version
**GitHub Desktop version:** 1.0.6
**OS version:** Microsoft Windows [Version 10.0.16299.19]

### Steps to Reproduce
For example a library update in a project overwrites the example bootstrap file, and you have lost your changes, but don't want to roll back entirely because of changes from the new version that should be kept.

**Expected behavior:** Ability to revert/discard changes to line(s) of code, not just entire file.

**Actual behavior:** Only able to stage/unstage line(s) and revert whole file.

**Reproduces how often:** 100%

**Comment by shiftkey** [comment] 2017-11-05 23:05
@francisrath thanks for the suggestion. I thought we already had something similar to this reported but couldn't find it.

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Closed by shiftkey** 2017-11-05 23:05 UTC
Labels: future-proposal

**Comment by billygriffin** [comment] 2018-11-21 00:00
This appears to be a duplicate of #2402 so I'm going to remove the `future-proposal` label. Thanks for the suggestion!
