### ISSUE TITLE
Display the current branch for each repository next to the repository's name in the dropdown

### ISSUE THREAD

**Issue by nicoroy2561** [desktop/desktop#13136] opened 2021-10-16 10:10 UTC
### Describe the feature or problem you’d like to solve

In the Repository dropdown topleft, display the current branch for each repository next to the repository's name.

### Proposed solution

It would be very nice to be able to check which branch is currently active for each of the repositories from that drop-down without having to manually switch to each of them.
It could be displayed in a slightly dimmed color font to distinguish it better from the repository name next to it.

**Comment by niik** [comment] 2021-10-18 08:18
Hi @nicoroy2561, thanks for reaching out! This was previously requested in https://github.com/desktop/desktop/issues/8158 so I'll close this issue in favor of that. I see that the issue is closed due to it not being a prioritized feature for us at the moment but please add a 👍 reaction to the issue body. This issue will be cross-referenced and also used as one of several metrics to gauge interest in such a feature.

**Closed as completed by niik** 2021-10-18 08:18 UTC

**Comment by nicoroy2561** [comment] 2021-10-18 08:21
@niik alright, thanks!
