### ISSUE TITLE
Handle opening a file in a PR

### ISSUE THREAD

**Issue by j-f1** [desktop/desktop#2505] opened 2017-08-19 12:04 UTC
### Description

Currently, PRs have a 🖥 icon next to each file, which should open the file in Desktop. The URL is of the form `x-github-client://openRepo/:repo_name?branch=pr%2F:pr_number&filepath=:file_path&pr=:pr_number`.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** macOS 10.12.3 (16D32)

### Steps to Reproduce

1. Go to a PR’s “Files” tab
1. Click on the :desktop_computer: icon

**Expected behavior:** The Desktop app switches to the appropriate branch and opens my editor to that file

**Actual behavior:** It asked me to clone the original repository

**Reproduces how often:** 100%

**Comment by shiftkey** [comment] 2017-08-20 03:45
@j-f1 good spot. This is a regression from the classic apps, so I'll put this in the 1.0 milestone.

**Comment by iAmWillShepherd** [comment] 2017-08-23 04:59
> It asked me to clone the original repository

Could you clarify here?

**Comment by j-f1** [comment] 2017-08-23 10:44
> Could you clarify here?

It opened a dialog asking me to clone desktop/desktop instead of my fork, which was the source of the PR.

**Comment by shiftkey** [comment] 2017-08-24 04:59
@j-f1 can you confirm the repository (not your fork) wasn't present in Desktop when you initiated the "Open File in Desktop" flow?

> It opened a dialog asking me to clone desktop/desktop instead of my fork, which was the source of the PR.

The "Open in Desktop" experience isn't that clever - it'll either checkout the branch if the PR is based on a local branch, or [add a `pr/XXX` refspec](https://github.com/desktop/desktop/blob/f382c46ea7a2450e6199a120a41258b3f122cd42/app/src/lib/dispatcher/dispatcher.ts#L865) to the local repository so it can keep the changes up to date.

**Comment by j-f1** [comment] 2017-08-24 10:53
> @j-f1 can you confirm the repository (not your fork) wasn't present in Desktop when you initiated the "Open File in Desktop" flow?

That is correct.

**Comment by shiftkey** [comment] 2017-08-24 23:28
@j-f1 thanks for confirming. So I retested this on `0.8.0` on Windows with these two scenarios:

 - **matching** repository is cloned locally before clicking "Open file in Desktop" link
 - **matching** repository is not cloned locally before clicking "Open file in Desktop" link

Both of these scenarios will checkout the branch and open Finder/Explorer to the directory containing the file.

Now, your scenario is interesting because you want to use your fork rather than create a new clone PR. This feels like it might fit in with the [1.1](https://github.com/desktop/desktop/blob/ad592671b82aec9f3a0b358f7814a127bb77de1b/docs/process/roadmap.md#11) milestone, but I'd probably need some input from @desktop/core as well as estimating the work required.

A couple of reasons why I'm hesistant:

 - while we do distinguish between source/fork repositories, the underlying data is tricky to manage and correlate correctly. #1277 is an example of this.
 - we don't currently have a cache of pull requests to lookup and identify whether an PR came from a fork or a source repository 
 - we fetch our issue and pull request data _after_ cloning down a repository, so checking early in the workflow might not be possible

**Comment by shiftkey** [comment] 2017-08-29 09:02
Adding the `future-proposal` label to this issue and closing it out to revisit this in our next planning session.

**Closed by shiftkey** 2017-08-29 09:02 UTC
Labels: enhancement, future-proposal
