### ISSUE TITLE
No feedback when pushing to remote origin 

### ISSUE THREAD

**Issue by tambakoo** [desktop/desktop#7917] opened 2019-07-04 11:00 UTC
While pushing to a remote origin I don't receive any feedback from the button. If I switch applications then a roller comes up as a feedback. This works as expected when pulling code from remote origin.
I have attached a video for more clarity 
https://www.loom.com/share/94fe528c2d624ad2a4a8ebaa8cea4535

* GitHub Desktop: 2.1.0
* Operating system: Mac OS Mojave 10.14
* Steps to reproduce 
 1. Click the push to origin button. 
 2. When you don't receive any feedback move to a different application and then move back to github desktop. 
 3. The issue should be observed now.

**Comment by tierninho** [comment] 2019-07-05 17:38
@tambakoo I am not sure I understand fully what is wrong as you are moving away from Desktop to your browser. 

It appears the `push origin` button is not working but at the end of the video the button turns to a `fetch` button, which tells me the push worked. 

Can you take another video and stay on Desktop? Also, please attach your logs -- see the Help menu. Thank you!

**Comment by tambakoo** [comment] 2019-07-06 13:59
> @tambakoo I am not sure I understand fully what is wrong as you are moving away from Desktop to your browser.
> 
> It appears the `push origin` button is not working but at the end of the video the button turns to a `fetch` button, which tells me the push worked.
> 
> Can you take another video and stay on Desktop? Also, please attach your logs -- see the Help menu. Thank you!

The button does respond when I click it. If I move to a different application (any application) and then come back to github-desktop the requested action has already been performed (here the code has been pushed) and the button has changed state. 
The expected behaviour is the button shows a loading state when clicked and changes state when action is complete (code is pushed in this case). I'll get back with another video and logs.

**Comment by tierninho** [comment] 2019-07-18 00:44
I think I see what is happening now. It appears to be a lag when you clicked the `Push` button or the first attempt at clicking the `Push` button did not work. It appears the second attempt was successful.

Please also include your logs --- see the Help menu in Desktop. Thanks!

**Comment by tambakoo** [comment] 2019-07-18 07:49
@tierninho I'm not able to replicate this issue now. 😐 . But I dug up old logs and found this 

`Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.837s)
2019-07-04T16:28:45.520Z - warn: [ui] fetchRepository: an error occurred for 'commutatus/intellecap-caif-api'
Error: Bad credentials
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:4)
2019-07-04T16:28:45.520Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: intellecap-caif-api - tambakoo (has token)
2019-07-04T16:28:48.141Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.606s)
2019-07-04T16:28:48.394Z - info: [ui] Background fetch for 2 repositories took 7.510sec`

there's a bad credentials error which occurs sporadically and works without any input from me. Later logs don't have an error like this and I immediately get a feedback. But I haven't updated anything in this context (the application or credentials). So this could still be a problem ?

**Comment by tierninho** [comment] 2019-07-18 18:47
Thanks for sharing the logs. I am still not 100% on the root cause, but glad it not happening anymore. 

It may have been caused by a lag in the api 🤷‍♂ 

Gonna close this issue for now, and if it occurs again from any user, I will be happy to reopen and investigate further!

**Closed by tierninho** 2019-07-18 18:47 UTC
Labels: more-info-needed
