### ISSUE TITLE
error occured when switch to same-name branch (in origin and remote repo)

### ISSUE THREAD

**Issue by CradelLau** [desktop/desktop#8615] opened 2019-11-12 06:00 UTC
### Describe the bug

error occured when switch to same-name branch (in origin and remote repo)

### Version & OS

2.2.3
win10

### Steps to reproduce the behavior

git remote add pb https://github.com/paulboone/ticgit
git push pb master
then open desktop
there are one master branch and one pb/master branch
switch to pb/master
"Error: A branch with that name already exists."

### Expected behavior

same-name branch should be able to coexist in origin and remote repo
it's practicable when using bash

**Comment by kuychaco** [comment] 2019-11-13 21:36
Hi @CradelLau thanks for the report! I _believe_ this is a duplicate of #4527 so I'm going to close it out. If you feel otherwise, please don't hesitate to re-open!

**Closed by kuychaco** 2019-11-13 21:36 UTC
