### ISSUE TITLE
Discard changes without removing files

### ISSUE THREAD

**Issue by saschanaz** [desktop/desktop#1682] opened 2017-05-21 11:57 UTC
### Description

Discarding changes on current GitHub Desktop causes removing files, and it again causes closing them on code editors e.g. VSCode. The previous GitHub for Windows didn't remove them.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Open a file and change it on VSCode
1. Discard change on GitHub Desktop

**Expected behaviour:** The file should not be closed on VSCode

**Actual behaviour:** The file gets closed

**Reproduces how often:** 100%

**Comment by niik** [comment] 2017-05-22 06:53
Hey @SaschaNaz. As far as I can tell we're not doing discards any differently in the old client and the new. In both cases (assuming this is a file that's tracked by git) we run `git checkout HEAD -- filename`.

I tried following your reproduction steps but I couldn't get VSCode to close the file. Can you confirm that you're seeing this behavior with files tracked by Git as opposed to new files not yet tracked by Git?

**Comment by SaschaNaz** [comment] 2017-05-22 07:36
Hi @niik. Yes, this is what I'm seeing:

![github-removing](https://cloud.githubusercontent.com/assets/3396686/26297191/c2f0f9d2-3f0c-11e7-8f42-8609946ccfec.gif)

**Comment by joshaber** [comment] 2017-05-22 18:00
Maybe caused by moving them to the Recycle Bin? I don't know if the Window Classic app did that.

**Comment by SaschaNaz** [comment] 2017-05-22 19:14
I don't think previous Windows app did the Recycle Bin thing.

**Comment by niik** [comment] 2017-05-23 08:04
> Maybe caused by moving them to the Recycle Bin? I don't know that the Window Classic app did that.

You're right, we didn't. That still doesn't explain why I'm not able to reproduce this with VS Code locally.

![discard-changes-vs-code](https://cloud.githubusercontent.com/assets/634063/26344072/a403f6ea-3f9e-11e7-8716-84709d5efa3f.gif)

Perhaps it's a race condition where the delete + checkout on my machine is fast enough that VS Code doesn't see the delete?

**Comment by SaschaNaz** [comment] 2017-05-23 10:00
>Perhaps it's a race condition where the delete + checkout on my machine is fast enough that VS Code doesn't see the delete?

Maybe, what SSD do you use? Mine is Sandisk Ultra II.

**Comment by sdwebguy** [comment] 2017-09-13 21:34
I get the same issue -- nothing to do with VS Code. I can make changes to a TXT file and discarding changes deletes the file from disk instead of just undoing the change.

**Comment by gboss911** [comment] 2017-09-14 05:50
Sent from my Samsung device over Bell's LTE network.

-------- Original message --------

**Comment by SaschaNaz** [comment] 2017-09-29 00:06
Can we instead create a backup file (say list.tsx.bak when list.tsx) and then move it into the recycle bin?

**Comment by shiftkey** [comment] 2018-03-26 06:39
I've been able to trace this behaviour to this VSCode setting:

```js
 // Controls if editors showing a file should close automatically when the 
 // file is deleted or renamed by some other process. Disabling this will
 // keep the editor open as dirty on such an event. Note that deleting from
 // within the application will always close the editor and that dirty files
 // will never close to preserve your data.
  "workbench.editor.closeOnFileDelete": true,
```

As part of our Discard changes flow, we'll move all new and modified changes to the trash:

https://github.com/desktop/desktop/blob/d73112a9fc9ca4a953697ae471d3942ae8e07d7b/app/src/lib/stores/git-store.ts#L1070-L1077

This is likely where VSCode is getting confused and removing the tab, before we've had a chance to restore the old version.

If you set `workbench.editor.closeOnFileDelete` to `false`, you'll see the tab refresh behind the scenes, without the tab being dropped.

**Comment by shiftkey** [comment] 2018-03-26 06:40
I'm going to close this out as we're not planning to change the discard changes flow back to the old behaviour, and we're aware of a workaround for this specific issue.

**Closed by shiftkey** 2018-03-26 06:40 UTC
Labels: enhancement
