### ISSUE TITLE
Bug: execute commit error report

### ISSUE THREAD

**Issue by zhangmo8** [desktop/desktop#14891] opened 2022-06-30 01:48 UTC
### The problem

![image](https://user-images.githubusercontent.com/43628500/176574189-4b57c4d4-3456-4f4c-8657-7e52e511ce0a.png)

For some reason I uninstalled my pnpm@7.4.0 and then reinstalled pnpm@6.24.3, after which I clicked the commit button and than throw out this error, as shown in the figure.

I think maybe it's because my local pnpm, but I don't know how to fix it.

### Release version

GitHub Desktop's Version 3.0.3 (x64)

### Operating system

Windows 11 Insider Preview 25151.1000 (rs_prerelease)

### Steps to reproduce the behavior

I'm not sure if I can really recreate it.

1. ```npm uninstall pnpm -g```
2. ```npm install pnpm@6.24.3 -g```
3. updated and restart this program

### Log files

[2022-06-30.desktop.production.log](https://github.com/desktop/desktop/files/9015717/2022-06-30.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/43628500/176574189-4b57c4d4-3456-4f4c-8657-7e52e511ce0a.png)

### Additional context

There's nothing.

**Comment by zhangmo8** [comment] 2022-06-30 01:56
I tried to upgrade my pnpm version to 7.4.0, but it didn't work.

**Comment by tsvetilian-ty** [comment] 2022-07-01 07:47
👋 @wegi8 thanks for the report. 

Your issue is a duplicate of https://github.com/desktop/desktop/issues/10326. I will close this issue in favor of the original report.

**Closed as not planned by tsvetilian-ty** 2022-07-01 07:47 UTC
