### ISSUE TITLE
"Couldn't parse author identity for" alert

### ISSUE THREAD

**Issue by taeun0** [desktop/desktop#11197] opened 2020-12-08 05:51 UTC
### Describe the bug

- There is a commit message that is not ASCII code in my commit history. And the alert window steadily pops up. I can't see the history tab.

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

- mac os : 10.15.6
<img width="487" alt="스크린샷 2020-12-08 오후 2 42 30" src="https://user-images.githubusercontent.com/59632881/101444794-a18f4a00-3963-11eb-9d86-894dae176db5.png">

### Expected behavior

- Non-ASCII code values ​​should be handled normally

### Actual behavior

A clear and concise description of what actually happened.
- The alert window steadily pops up. I can't see the history tab.

### Screenshots

Add screenshots to help explain your problem, if applicable.

<img width="628" alt="스크린샷 2020-12-08 오후 2 39 12" src="https://user-images.githubusercontent.com/59632881/101445242-7e18cf00-3964-11eb-87b6-f8dd5a349f46.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
- [2020-12-08.desktop.production.log](https://github.com/desktop/desktop/files/5657125/2020-12-08.desktop.production.log)

**Comment by niik** [comment] 2020-12-08 08:16
Hey @taeun0, thanks for opening this, and I'm sorry to hear you're having problems. I believe this is the same as https://github.com/desktop/desktop/issues/10314 which was unfortunately closed without being confirmed as a bug. I've been able to reproduce this locally by inserting the unit separator character (0xF1) into a commit message.

Our prioritization scheme doesn't quite map well to this problem as it's preventing core functions but doesn't affect a lot of users. I'm tentatively labeling this as a priority 2 bug.

**Comment by taeun0** [comment] 2020-12-08 10:38
@niik 
Thank you for answer. The GitHub desktop is so light and easy to use.

Pushed an old commit to the origin branch, and it is quite difficult to change the commit message with force push.

Everything is perfect but it is inconvenient because of only commit message.
Hope the bug is resolved. :)

**Comment by sergiou87** [comment] 2021-01-07 11:55
This seems to be the same problem as #6836 too.

**Comment by niik** [comment] 2021-01-07 12:39
@sergiou87 Yup, you're right, and that issue contains even more details than this so I'm going to close this in favor of #6863.

@taeun0 Please subscribe to #6836 to follow along with any developments in resolving this bug.

**Closed as completed by niik** 2021-01-07 12:39 UTC
Labels: bug, priority-2
