### ISSUE TITLE
Local repos with same name should have their parent directory in the Repositories dropdown

### ISSUE THREAD

**Issue by oguzyildiz1991** [desktop/desktop#7641] opened 2019-05-28 21:30 UTC
**Please describe the problem you think should be solved**
When there are more than 1 repositories with the same name, dropdown menu shows them identically.

Example:

> I want to duplicate the same repo locally and use them in github desktop, but all of them having exactly same name causes confusion. In my specific case, one of them is actually a submodule of another repo. But they point to the same exact repo.

**[Optional] Do you have any potential solutions in mind?**
It would be nice to put their parent directory names (the lowest level of parents that resolve conflict)

**Comment by tierninho** [comment] 2019-05-28 21:41
@oguzyildiz1991 Thanks for filing. Going to close this issue as it is a duplicate of similar issues being addressed in #6460 Please follow along there.

**Closed by tierninho** 2019-05-28 21:41 UTC
