### ISSUE TITLE
Clicking Fetch does not respond on macOS on some repos

### ISSUE THREAD

**Issue by codyhazelwood** [desktop/desktop#10690] opened 2020-09-29 19:34 UTC
### Describe the bug

Clicking Fetch does not respond on macOS.  There used to be an animation, and then the list of changes would update.  Now, clicking the button does nothing in the UI (although in the terminal it appears it actually _did_ fetch).

This happens on the current version and the previous version.  I also tried removing the app (and preference files) and reinstalling it with no change.

### Version & OS

GitHub Desktop Version 2.5.6
macOS 10.15.6

### Steps to reproduce the behavior

1. Open a repository
2. Click Fetch origin

### Expected behavior

Refresh icon should start spinning and then the UI should refresh with the newly fetched changes.

### Actual behavior

No response to clicking the button.  Changes appear to be fetched most of the time when viewing the repo with the terminal.

### Screenshots

N/A

### Logs

```
2020-09-29T19:21:41.514Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Not Found
    at Ne (/webpack:/app/src/lib/http.ts:170:11)
    at it.fetchPushControl (/webpack:/app/src/lib/api.ts:910:7)
    at Object.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:940:41)
    at /webpack:/app/src/lib/stores/app-store.ts:3951:45
    at Object.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3832:5)
2020-09-29T19:22:06.265Z - warn: [ui] fetchRepository: '/**PRIVATE ORG NAME**/**PRIVATE REPO NAME**' returned a 404
2020-09-29T19:22:10.410Z - warn: [ui] fetchRepository: '/**PRIVATE ORG NAME**/**PRIVATE REPO NAME**' returned a 404
2020-09-29T19:22:10.419Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: **PRIVATE REPO NAME** - codyhazelwood (has token)
2020-09-29T19:22:10.567Z - warn: [ui] Unable to fetch issues for /**PRIVATE ORG NAME**/**PRIVATE REPO NAME**
Error: Need a GitHubRepository that's been inserted into the database
    at Nu (/webpack:/app/src/lib/stores/issues-store.ts:229:11)
    at Mb.constructor.getLatestUpdatedAt (/webpack:/app/src/lib/stores/issues-store.ts:47:5)
    at Mb.constructor.refreshIssues (/webpack:/app/src/lib/stores/issues-store.ts:71:38)
    at Object._refreshIssues (/webpack:/app/src/lib/stores/app-store.ts:1652:30)
    at /webpack:/app/src/lib/stores/app-store.ts:4263:18
    at Object.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:3832:5)
    at Object.performFetch (/webpack:/app/src/lib/stores/app-store.ts:4206:5)
2020-09-29T19:27:52.584Z - info: [ui] [BranchPruner] No branches to prune.
2020-09-29T19:28:00.849Z - info: [ui] No submodules found. Skipping "git submodule status"
```

### Additional context

The repos that are having issues are also showing up in the 'Other' list instead of under the organization name in the repo dropdown.  All repos are working via the command line.  All repos were cloned with `git clone git@github.com:OrgName/Repo.git`.  They were added to the app by dragging the folders into the desktop app (26 repos all at once - only 5 show up in other).

**Comment by steveward** [comment] 2020-09-30 01:18
Thanks for the report @codyhazelwood. I'd be curious if switching the repository to use HTTPS instead of SSH resolves the issue. You can try to fix the repositories being listed as `Other` by following these steps:

1. Go to the menu in GitHub Desktop and select `View` > `Toggle Developer Tools`
2. Go to `Storage` > `IndexedDB` > `Database`
3. Select `Delete database`
4. Close and restart GitHub Desktop

You will need to add your repositories again. Let me know if that helps.

**Comment by codyhazelwood** [comment] 2020-10-01 22:25
Unfortunately, I don't think I can use HTTPS because I have 2FA enabled.

I tried deleting the database and reimporting, and the same 5 repos went back to the 'Other' list.

I did find the issue though (still might be a bug since the repo works fine in the command line - not sure).  It was due to a leading `/` in the origin URL in the git config.

.git/config for one of the broken repos:
```
[remote "origin"]
	url = git@github.com:/*** ORG ***/*** REPO ***.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

Changing it to this fixed it (removing the `/` before the Organization:
```
[remote "origin"]
	url = git@github.com:*** ORG ***/*** REPO ***.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```

**Comment by steveaylwin** [comment] 2020-10-20 08:47
I can verify this has been happening for several months (at least, may be over a year) and I've always used SSH - I just updated it one time and the UI animation just stopped. Sometimes I also find that I have to Cmd + Tab to a different app and then come back for the UI to update to say that fetch was just done.

This may well be because of a delay rather than a focus change issue, but thought I should mention it just in case.

**Comment by steveward** [comment] 2020-12-18 20:08
@codyhazelwood I tried recreating this test case by cloning a repo via SSH with a leading `/`, but I wasn't able to reproduce this issue. It did create the repository under a `/steveward` grouping in the repository list instead of `steveward`. Since you seem to have resolved this issue I'm going to close this out. Let me know if you encounter further problems.

**Closed by steveward** 2020-12-18 20:08 UTC
