### ISSUE TITLE
Allow discarding changes with multiple files selected

### ISSUE THREAD

**Issue by mikeabiezzi** [desktop/desktop#2401] opened 2017-08-05 00:26 UTC
### Description

Currently, you can only discard one file at a time. It would be convenient to select multiple files and discard the set at one time.

### Version

**GitHub Desktop version:** 0.7.2

**OS version:** macOS 10.12.6

**Comment by joshaber** [comment] 2017-08-07 15:05
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/2248. Please follow that issue for further updates.

**Closed by joshaber** 2017-08-07 15:05 UTC
