### ISSUE TITLE
Diff scrolling gets weird

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1380] opened 2017-05-05 14:01 UTC
This is something I've observed off and on for a bit. _Sometimes_ diff scrolling gets a bit funny. It's hard explain what exactly funny means... it's like scrolling down sometimes scrolls up for a moment before scroll down? And sometimes scrolling up scrolls down for a moment before scrolling up?

It doesn't always happen. It seems to get worse the more diffs I view.

I _suspect_ it's a problem with re-using the same CodeMirror instance or DOM elements.

**Comment by feross** [comment] 2017-05-16 17:49
Just noticed this happening in 0.5.3.

**Comment by joshaber** [comment] 2017-05-16 17:52
@feross have you noticed if you can reproduce it reliably?

**Comment by jstanden** [comment] 2017-05-16 18:08
I also just experienced this issue on my first run of GitHub Desktop Beta 0.5.3 in macOS Sierra 10.12.4 using a 1st gen Magic Trackpad.

Scrolling in the right-side diff pane was really jittery, and it moved in an inverted direction for a short distance before rapidly alternating.

I restarted GitHub Desktop and it has been working fine again.

I had recently done a refactor, so I had ~160 changed files in my working copy.  I was in the middle of reviewing partial commits when the jitter started.

If it happens again, I'll see if I can sort out the steps to reproduce it.

**Comment by joshaber** [comment] 2017-05-16 18:20
Moving this to M5 to spend some time investigating again.

**Comment by joshaber** [comment] 2017-05-25 20:28
I can never reproduce this when I want to 😞 

Just from poking around in the CodeMirror source, my current theory is that it's related to have a `dx` component to the scroll event. That's really easy to do accidentally if you're using a trackpad. But I'm still having a hard time reproducing it :hurtrealbad:

**Comment by thoralf-gutierrez** [comment] 2017-06-09 14:01
I'm getting the same thing on 0.6.0 with macOS 10.12.5.
My track pad direction is scroll direction is "Natural" (Preferences > Trackpad > Scroll & Zoom > Scroll direction: Natural).
I have enabled scrolling with inertia (Preferences > Accessibility > Mouse & Trackpad > Trackpad Options... > Scrolling with inertia)

Here's what happens:
* When I move my fingers up on the trackpad, I now move up in the file, which is not the "Natural" scroll direction!
* When I release my fingers, the scroll inertia takes over and now the scroll is moving me down in the file, like it was supposed too from the start.

It's this inversion of direction between when I have my fingers on the trackpad and when I remove my fingers from the pad (i.e. when the "inertia" takes over) that gives you the "jittery" effect.

**Comment by joshaber** [comment] 2017-06-09 14:19
@thoralf-gutierrez Thanks! Have you noticed if you can reproduce it reliably? Does it go away after you restart the app?

**Comment by thoralf-gutierrez** [comment] 2017-06-09 14:38
Indeed - This seems to get fixed once I restart the app and I cannot reproduce :-/

**Comment by feross** [comment] 2017-06-11 07:56
I switched back to the native version of the app for now so I can't test this theory, but I suspect this may happen when the trackpad is used *and* an external mouse is connected to the Macbook.

**Comment by thoralf-gutierrez** [comment] 2017-06-11 15:17
@feross: I did not have an external mouse (or keyboard) connected. Just the basic trackpad.

**Comment by guido4000** [comment] 2017-07-04 21:51
Just experienced the issue with Sierra and version 0.6.2.

**Comment by simonlast** [comment] 2017-09-01 17:25
Experienced the issue in Sierra, 0.8.1-beta2. Using a regular trackpad.

**Comment by jonator** [comment] 2018-03-07 03:42
Same issue scrolling large diffs with a trackpad on v1.1.0. Windows 10 Pro v1709. The scrolling is very laggy

**Comment by iAmWillShepherd** [comment] 2018-03-07 16:15
@jonator, we've had trouble reproducing this in the past and I have never observed this behavior. Could you attach a gif or small video of the behavior please, just so we have it documented.

**Comment by lnikkila** [comment] 2018-04-03 05:56
I managed to reproduce this again today, after I switched to another repo using the repo dropdown. The diff viewer was visible in both as I had changes in both repos, but the scrolling bug didn’t start until I switched repos. Again, restarting fixed it.

This was using v1.1.1, there’s more info about my environment and a screen recording in #4297.

**Comment by iAmWillShepherd** [comment] 2018-04-03 16:01
@lnikkila are you able to reproduce this consistently? I just tried and had no luck. So, I'm curious if this could have something to do with how large a diff is..

**Comment by mikew** [comment] 2018-04-04 22:24
I've experienced this a few times. It's very strange. Not sure if there's anything I can add.

- It doesn't happen in the left-hand scroll view (Changes / History)
- When it happens, horizontal scrolling, at least on a trackpad, also does vertical scrolling.

**Comment by vanyakosmos** [comment] 2018-12-03 14:42
Got similar (or maybe even worse) issue in v1.5.0 osx and it never happened before.

- most severe dragging occurs when scroll slowly
- dragging happens even after reaching viewport limit

Check out gif (it's too tall for showing it in comments, better to open it in a separate window). 

**On this gif I only scroll down:**
https://user-images.githubusercontent.com/16745500/49379917-0f6f5e00-f719-11e8-81a0-28d383ffb3c8.gif

**Comment by eranshmil** [comment] 2018-12-19 18:41
I'm also having this issue on and off.

**Comment by eranshmil** [comment] 2018-12-19 19:06
Also having this issue on and off.

I'm not quite sure if it's helping, but I recorded a performance profile of one scroll down using the touchpad.

[Profile-20181219T210236.json.txt](https://github.com/desktop/desktop/files/2696189/Profile-20181219T210236.json.txt)

```
macOS: v10.13.6
Github Desktop: v1.5.1
```

**Comment by justanotherfoundry** [comment] 2018-12-28 10:37
I also noticed that scrolling in the diffs view is a bit “twitchy”. MacOS 10.14.2, GitHub Desktop 1.5.1, and a Microsoft mouse with a scroll wheel.

I’d appreciate if the diff view scrolled line-by-line like some text editors ((imo, the good ones) do. I’d expect that using the scroll wheel scrolls the view by exactly one line per wheel “notch”, and not showing half cut-off lines at the top of the view. Would that be possible?

**Comment by danpalmer** [comment] 2019-02-16 13:05
Hi all, just to add to this, I'm seeing this issue regularly (daily to hourly, sometimes reproduced almost immediately).

As far as I can tell, the issue is that:
- Scroll direction is not respected, it only scrolls in the "traditional" direction (i.e. not the macOS default).
- The inertial movement _does_ happen in the system specified direction.

macOS: 10.14.3
GitHub Desktop: 1.6.2

**Comment by hughbe** [comment] 2019-06-25 11:22
Example: https://vimeo.com/344295150

**Comment by tustin2121** [comment] 2019-08-15 22:15
I'm experiencing this with the latest update. (v2.1.1) It feels like it's trying to fight my Mac settings. I have my trackpad scroll reversed from default (slide down to go down the list) and it feels like it's trying to scroll in the default manner (slide up to push the list up).

**Comment by elliotcm** [comment] 2019-12-30 14:24
Another +1 from me on 10.15.2 (19C57) / 2.2.4.  Also fixed when restarting github desktop.

When it happened just now I could scroll only upwards (using a two-finger upward swipe on the built-in trackpad) and the diff would scroll up to the top, then down to the bottom, then back up again, cycling back and forth.  This is with a small diff size.

**Comment by mikew** [comment] 2020-06-08 15:38
Still happening in 2.5.2

**Comment by sergiou87** [comment] 2021-04-14 11:54
I haven't seen this issue since December 2020, and I can't reproduce it at all right now. Is this still a problem for someone?

**Comment by elliotcm** [comment] 2021-04-14 12:38
> I haven't seen this issue since December 2020, and I can't reproduce it at all right now. Is this still a problem for someone?

I switched to Sublime Merge.

**Comment by jstanden** [comment] 2021-04-14 13:51
> I haven't seen this issue since December 2020, and I can't reproduce it at all right now. Is this still a problem for someone?

I switched to the visual diff tool in my IDE. +1 on closing the issue.

**Comment by tustin2121** [comment] 2021-04-14 14:50
> I haven't seen this issue since December 2020, and I can't reproduce it at all right now. Is this still a problem for someone?

Negative. I haven't seen the problem at all recently. 

Tried it just now on my mac and it scrolls as expected. There's a few visual glitches, like it can't seem to render the diff fast enough to not display a blank area in the scroll direction for a frame or two if I scroll past the loaded section, but the experience (which is what this bug was about) is smooth as silk. I'd call this fixed.

**Comment by dmitshur** [comment] 2021-04-14 14:59
I used to run into this fairly regularly (at least once every few months), but don't recall running into it anytime recently.

**Comment by sergiou87** [comment] 2021-04-14 15:03
Thank you all for your responses! ❤️   I'm gonna close it for now, we can reopen it if the problem occurs again.

**Closed by sergiou87** 2021-04-14 15:03 UTC
Labels: bug, codemirror, macOS, priority-3
