### ISSUE TITLE
fatal: cannot use ~/.gitignore_global as an exclude file

### ISSUE THREAD

**Issue by SeanMcMillan** [desktop/desktop#3617] opened 2017-12-15 21:09 UTC
### Description

After a recent update, when I look at my repository, I get a popup that says `fatal: cannot use ~/.gitignore_global as an exclude file` (except with the full path). Sometimes it pops up twice. After I dismiss it, The application does not show pending changes in the "changes" view.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

This happened automatically as soon as I switched to the Github Desktop application.

**Expected behavior:** I expected it to respect the setting in my .gitignore_global file

**Actual behavior:** I got a popup saying it couldn't use that file.

**Reproduces how often:** 100%

#### Additional Information

This was working in the previous version (unknown what that number was, sorry.) It did ignore the things I had listed to ignore in ~/.gitignore_global.

My .gitconfig contains this line: `	excludesfile = ~/.gitignore_global`
My .gitconfig and .gitignore_global both have LF line endings.
My .gitconfig and .gitignore_global are both NTFS symlinks to another directory.

Command line git does not have this error when run (using the command from the logs.)
```
$ git status --untracked-files=all --branch --porcelain=2 -z
# branch.oid 86bf7aa1aa287a76555746d7e0d72e14f08ac981# branch.head master
```

**Comment by SeanMcMillan** [comment] 2017-12-15 21:09
[2017-12-15.desktop.production.log](https://github.com/desktop/desktop/files/1564006/2017-12-15.desktop.production.log)

**Comment by joshaber** [comment] 2017-12-16 02:57
Huh, that's odd. Could you paste your gitignore in here so we can try to reproduce it?

**Comment by shiftkey** [comment] 2017-12-16 03:03
Seems to be [a known error case](https://github.com/git/git/blob/master/dir.c#L874-L875) with Git:

```
if (add_excludes(fname, "", 0, el, NULL, sha1_stat) < 0)
    die("cannot use %s as an exclude file", fname);
```

Are you able to open the repository in a shell and see the same error when you `git status`? We should be able to enable some tracing and see if we can understand _why_ it's erroring...

**Comment by SeanMcMillan** [comment] 2017-12-18 16:25
I don't see an error from the command line

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   TVQueryBuilder/Classes/Helpers/RunHelper.cs

no changes added to commit (use "git add" and/or "git commit -a")
```

I have command line git installed.

```
$ git --version
git version 2.15.0.windows.1

```

I also have Visual Studio Code installed, and it doesn't have a problem either. (I actually made a commit in there when Github desktop stopped working.

**Comment by SeanMcMillan** [comment] 2017-12-18 16:28
Looks like I can't upload a file called `.gitignore_global` here.
The contents of .gitignore_global are:
```
# VIM Swap files
.*.swp
# MacOS Metadata
.DS_Store*

# Isniff files
.errfiles
.newerrs
.olderrs

#push tempfiles
.thefiles
.thefiles.bak

#Other
node_modules
.sass-cache

# .NET Projects
bin
obj
*.suo
.vs

```

**Comment by SeanMcMillan** [comment] 2017-12-18 16:35
I replaced the symlink with a copy of the file, and it started working again. So the problem is related to it being a symlink.

Having it as a symlink works fine in console git an VS Code, and in the older version of Github Desktop.

**Comment by shiftkey** [comment] 2017-12-18 23:13
> I replaced the symlink with a copy of the file, and it started working again. So the problem is related to it being a symlink.
> 
> Having it as a symlink works fine in console git and VS Code, and in the older version of Github Desktop.

Thanks for the extra details. GitHub Desktop is running Git 2.15.1, so maybe something has been introduced which regressed this area. I'll leave this open to see if we can isolate where this has been introduced in Git.

**Comment by shiftkey** [comment] 2017-12-19 08:04
I've found https://github.com/git-for-windows/git/issues/1392 which seems to be the same issue as this.

**Comment by jeffhostetler** [comment] 2017-12-19 17:14
See https://github.com/git-for-windows/git/pull/1407

**Comment by shiftkey** [comment] 2018-01-18 17:10
Git 2.16.0 has just been announced - I'll update our embedded Git over the next day or so to close this out!

**Closed** 2018-01-24 00:40 UTC
Labels: bug

**Comment by karnavkumar** [comment] 2018-01-30 11:36
i just used this `git config --global core.excludesfile ~/.gitignore` 
and after that this error occurs `fatal: cannot use /Users/indianic/ as an exclude file` 
please help some one what i do to get old  `core.excludesfile` file

**Comment by shiftkey** [comment] 2018-01-30 21:49
@karnavkumar please open a new issue with details about your setup
