### ISSUE TITLE
Nonenglish ascii text display error

### ISSUE THREAD

**Issue by MaksimKuz** [desktop/desktop#14924] opened 2022-07-07 18:33 UTC
![image](https://user-images.githubusercontent.com/70633742/177844513-744eca19-08f1-40f9-b303-55912e2c36fe.png)

**Comment by tsvetilian-ty** [comment] 2022-07-07 20:54
@MaksimKuz thanks for the report! We are aware of the issue. You can check https://github.com/desktop/desktop/issues/3923 for more information. 

TLDR: We are using UTF-8 as default encoding when reading the diff file, which is the cause of the problem. 

I will close this issue in favor of https://github.com/desktop/desktop/issues/3923

**Closed as completed by tsvetilian-ty** 2022-07-07 20:54 UTC
