### ISSUE TITLE
Remember window position on startup

### ISSUE THREAD

**Issue by aateeque** [desktop/desktop#14624] opened 2022-05-17 17:55 UTC
### The problem

I love GitHub Desktop & I've been using it everyday for a long time. Since the beginning there has been this problem with it not remembering it's up position on my multi-screen setup. It just decides to start at the top of the main screen. And my first act is to move it where I want it. I do this at least once every week when my PC reboots. I was hoping that at some point someone will come & fix this. Now I am giving up & looking to sort this out. So in that spirit filing this here to see if there's any support/traction for making it remember where it last was:

- has this been looked into already?
- would this a userful feature?
- happy to help, so any tips/pointers where one should start at

Thanks for an awesome git client ❤️ 

### Release version

3.0.0 (x64)

### Operating system

Windows 11 Home

### Steps to reproduce the behavior

1. Start GitHub Desktop
2. Drag the app to a new location 
3. Close the app
4. Start the app again
5. It starts in a _default_ position; not where it was closed

### Screenshots

1. At startup
![image](https://user-images.githubusercontent.com/319157/168878318-6514913c-8199-4d9c-8778-0fe749a21062.png)

2. Repositioned bottom-left of the screen
![image](https://user-images.githubusercontent.com/319157/168878437-49de879b-5fc2-4ed2-9fe9-5cd3904278d5.png)

3. Closed & reopened app - restores to a _default_ location as in 1 above
![image](https://user-images.githubusercontent.com/319157/168878742-0d157a0d-9032-4658-97d2-e8c8324e3c46.png)

**Comment by steveward** [comment] 2022-05-19 17:50
Thanks for the issue @aateeque. There have been some recent issues reported around multi-monitor setups (see https://github.com/desktop/desktop/issues/14017), but I don't believe this specific issue has been reported. I'll mark this as a bug for 👀 .

**Comment by tsvetilian-ty** [comment] 2022-09-28 15:02
Hey @aateeque 👋 

I could not reproduce the issue 😞 If you're still expressing the case, could you share your current GitHub Desktop version? The latest version of GitHub Desktop uses an updated version of Electron that might fix the issue for you.

**Comment by alkorlos** [comment] 2023-06-01 11:04
Hello

I am using
Windows 10 22H2
Installed the latest version of GitHub Desktop in February 2023, now it 3.2.3.

I have the same issue, from February to today, the last time I encountered this issue today, that's why I decided to write about it. After seeing the comment @tsvetilian-ty I decided to check under what conditions it appears and could not reproduce this issue, after PC reboots and etc. all fine.

I can’t say for sure whether this bug disappeared the first time or not, but I definitely saw it much more than I would like.

P.S.
There is another bug - when dragging a GitHub Desktop window from one screen to another (this is necessary just when the initial bug occurs), sometimes it does not work right away, the window returns to the original screen. Unfortunately, as far as I know, Windows does not have a normal built-in ability to record several screens at once, I can’t show it.

**Comment by niik** [comment] 2024-09-18 13:02
:wave: Since neither you ore we are able to reproduce this I'm going to close this out. For the second issue you mentioned I suggest checking if any of the issues we've already got related to Window dragging matches and if not open a new issue with reproduction steps, here's a few examples:

https://github.com/desktop/desktop/issues/17371
https://github.com/desktop/desktop/issues/15434

**Closed as completed by niik** 2024-09-18 13:02 UTC
Labels: bug, priority-3

**Comment by ParadoxV5** [comment] 2024-09-18 19:40
I can reproduce on Version 3.4.6-beta1 (x64).

This issue only occurs when the window is moved and/or resized so that any one of the edges are outside of the *main* display.
* It still counts if that edge lands on a second display.
* While the app doesn’t let us clip it out of the top edge of the display, configuring a second monitor above the main one lets us access the space above.

This is not a multi-monitor issue – I have checked both with a second display connected and disconnected.
