### ISSUE TITLE
GitHub Desktop cannot locate repo with too many active changes

### ISSUE THREAD

**Issue by lukezdz** [desktop/desktop#9855] opened 2020-05-24 11:16 UTC
### Describe the bug

While working on one of my projects I had to move a lot of files to a subfolder (around 230,000 files). After doing this GitHub Desktop was unable to locate my repo (I tried locating it several times with no success), even though git CLI was working fine.  

I realized that this is caused by too many changes when git extension for VS Code showed a message 'Too many active changes in the repository. Some git features are unavailable'. After committing most of the changes from git CLI, GitHub Desktop started working once again and I was able to push the commit.

### Version & OS

GitHub Desktop: version 2.5.0
OS: Windows 10 Pro 1909

### Steps to reproduce the behavior

Have A LOT of untracked active changes.

### Expected behavior

I think that the problem is not that GitHub Desktop didn't work for so many changes - it is understandable, but I expect the message it gave to be more informative. It should say something along the lines of what the VS Code git extension did.

### Actual behavior

Instead of informing about too many active changes GitHub Desktop behaved like the repo was broken or missing, which was not the case.

### Logs

```
2020-05-24T00:02:43.670Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.309s)
2020-05-24T00:02:43.670Z - error: [ui] 'git status' emitted 38915436 bytes, which is beyond the supported threshold of 20000000 bytes
```

**Comment by tierninho** [comment] 2020-05-26 18:06
Thanks for the issue and suggestion @lukezdz and glad all is working again! I think you have a valid point as some of the error messages are rather vague and leaving you in such a state is not ideal in any way. 

To sum it the request:
- Add a "Too many active changes in the repository. Some git features are unavailable." message when Desktop fails to show the outcome of moving too many files, which causes the repo to appear as broken or missing. 

I also suggest we include a tip on how to recover the repo gracefully.

**Comment by steveward** [comment] 2024-10-17 12:45
Closing as a duplicate of https://github.com/desktop/desktop/issues/6230.

**Closed by steveward** 2024-10-17 12:45 UTC
Labels: enhancement, not-planned
