### ISSUE TITLE
fonts are sometimes blurred on macOS Catalina

### ISSUE THREAD

**Issue by zeke** [desktop/desktop#9541] opened 2020-04-16 18:04 UTC
I’ve noticed that sometimes my fonts get blurry in Desktop on macOS Catalina. Quitting and restarting the app takes care of it.

Note that in the blurry screenshot below, there's a banner at the top of the Window about a new Desktop version. I am unsure whether that is a factor in making the window blurry, but I will follow up when and if I see this again.

Environment: macOS Catalina

---

Blurry:

<img width="1904" alt="blurry" src="https://user-images.githubusercontent.com/2289/79490328-8ab17700-7fd1-11ea-8b89-2a65bb218724.png">

---

Crisp: 

<img width="1904" alt="crisp" src="https://user-images.githubusercontent.com/2289/79490316-86855980-7fd1-11ea-8ce6-297c31d2fbf5.png">

**Comment by rafeca** [comment] 2020-04-17 11:22
Thanks for the report @zeke !! Based on the screenshot it looks that not only the fonts but also the SVGs and even the images are blurry (your avatar also looks blurry right?).

I have no idea what could be happening here, but it may be electron related. Does it happen often?

If you get to experience the issue again can you open the Dev tools (<kbd>Cmd + Opt + I</kbd>) and check if the window is zoomed? (whether `window.devicePixelRatio` returns something different than `2` for a retina display).

**Comment by zeke** [comment] 2020-04-17 20:44
> Does it happen often?

I've noticed it three times in the last month.

**Comment by zeke** [comment] 2020-04-22 02:41
Update: I see a new version banner atop my GitHub Desktop window, but it has NOT caused any blurring, so that is likely ruled out as a possible cause of the issue:

<img width="1904" alt="Screen Shot 2020-04-21 at 7 39 27 PM" src="https://user-images.githubusercontent.com/2289/79934640-dd42c700-8407-11ea-9433-9c0b9f441802.png">

**Comment by zeke** [comment] 2020-04-28 19:28
It happened again. I think it may occur when I disconnect my running MacBook Pro from my Thunderbolt display.

**Comment by zeke** [comment] 2020-04-28 19:29
Oh and quitting and restarting the app resolved the issue.

**Comment by tierninho** [comment] 2020-04-28 19:55
Look like this will be fixed in v7.1.11 per here https://github.com/electron/electron/issues/21393. We are on 7.1.8, per here https://github.com/desktop/desktop/blob/development/package.json#L170

**Comment by adamreisnz** [comment] 2020-06-03 05:01
I can confirm that this happens when disconnecting a thunderbolt USB-C attached display. The whole app becomes blurry (not just fonts):

![image](https://user-images.githubusercontent.com/490562/83597613-d937c680-a5bb-11ea-898b-e18f23b7baa3.png)

Restarting app fixes it.

**Comment by steveward** [comment] 2024-04-05 15:20
I'm going to close this out as stale since it's 4 years old, but if this is still an issue for anyone we can reopen and investigate.

**Closed by steveward** 2024-04-05 15:20 UTC
Labels: bug, macOS, electron, priority-3
