### ISSUE TITLE
Account's picture is shown as broken images with GitHub Enterprise account

### ISSUE THREAD

**Issue by drod66** [desktop/desktop#2844] opened 2017-09-22 18:09 UTC
### Description

Account's picture is shown as broken images with GitHub Enterprise account.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Connect with a GitHub Enterprise account.
1. Your picture (image) will be displayed as a broken image icon.
1. Out-of-the-box avatars are being displayed properly.

**Expected behavior:** User's picture should be displayed properly

**Actual behavior:** User's picture is shown as a broken image icon.

**Reproduces how often:** All the time

#### Additional Information
I also verified by toggling the developer tools and check the &lt;img&gt; element tag. The url is valid and working in a regular browser window. It looks like the app prevented the access to our GitHub Enterprise site for displaying image resources.

**Comment by j-f1** [comment] 2017-09-22 18:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #821. Please follow that issue for further updates.

**Closed** 2017-09-22 19:17 UTC
