### ISSUE TITLE
"Open in GitHub Desktop" does not checkout requested branch

### ISSUE THREAD

**Issue by kylefox** [desktop/desktop#12215] opened 2021-05-14 16:30 UTC
### Describe the bug

The "Open in GitHub Desktop" links do not checkout the requested branch. The app always opens to whatever branch was previously checked out.

https://user-images.githubusercontent.com/37838/118300548-4aa41880-b49f-11eb-8fde-80199b03ecb5.mp4

### Version & OS

- Github Desktop 2.8.1
- macOS Big Sur 11.2.3 (20D91)

I have tried Safari, Brave, and Firefox — all exhibit the same behaviour, so the problem does not appear to be browser specific.

### Steps to reproduce the behavior

1. Checkout the `main` branch of any local repo
2. Navigate to a PR or non-`main` branch on the GitHub.com repo
3. Click the "Open in GitHub Desktop"
4. Note that GitHub Desktop does open _but your local repo did not change from `main`_

### Expected behavior

1. I currently have `branch-1` checked out
1. I navigate to a PR on GitHub (`branch-2`)
2. I click "Open in GitHub Desktop"
3. GitHub Desktop opens and switches from `branch-1` to `branch-2`

### Actual behavior

1. I currently have `branch-1` checked out
1. I navigate to a PR on GitHub (`branch-2`)
2. I click "Open in GitHub Desktop"
3. ⛔️ GitHub Desktop opens and remains on `branch-1` ⛔️

### Screenshots

I would expect the button below to open to the `patch-1` branch, but it opens to the `master` branch:

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/37838/118298782-25aea600-b49d-11eb-9e6b-8741e208aebc.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/37838/118298811-3101d180-b49d-11eb-922f-347c78907a9e.png">

### Logs

I'm not sure if it's helpful, but this is the log file that's generated when I click "Open in GitHub Desktop" (without having GitHub Desktop already running):

[2021-05-14.desktop.production.log](https://github.com/desktop/desktop/files/6479944/2021-05-14.desktop.production.log)

**Comment by billygriffin** [comment] 2021-05-14 18:19
Thanks @kylefox! I initially thought it might just be on branches that are from forks, but I was able to reproduce this across the board, so that seems to be a regression. Thanks so much for spotting it and including so much detail in your issue!

**Comment by kylefox** [comment] 2021-05-14 18:52
@billygriffin No problem, let me know if there's any additional detail I can provide 👍

**Comment by zeke** [comment] 2021-05-24 16:07
I'm experiencing this too. Let me know if you need a tester! 💛

**Comment by sergiou87** [comment] 2021-05-26 07:12
Quickly fixed by @dzader, thank you!! ❤️

**Closed as completed by sergiou87** 2021-05-26 07:12 UTC
Labels: bug, priority-2
