### ISSUE TITLE
Keyboard navigation in search results

### ISSUE THREAD

**Issue by dy** [desktop/desktop#12058] opened 2021-04-26 09:30 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/300067/116060547-f8b26480-a64f-11eb-8332-711dc8cb0536.png)

Open "Current repository" dropdown, enter search term, try navigating with keyboard ↑/↓.
It moves selection highlight up/down but then in a moment reverts it to initial selected repository.

### Version & OS

gh desktop 2.7.2, win10

### Logs

No logs, that's seems to be UI issue

**Comment by steveward** [comment] 2021-04-28 18:48
Thanks for the report @dy. This looks like a duplicate of https://github.com/desktop/desktop/issues/11750 so I am going to close this issue out.

**Closed as completed by steveward** 2021-04-28 18:48 UTC
