### ISSUE TITLE
The New Feature for Alerting User When Base Branch Moves Ahead of Current is Inconsistent

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#5293] opened 2018-07-31 04:39 UTC
## Description
The new feature "Notification displayed in History tab when the base branch moves ahead of the current branch" seems inconsisent.  If I take a base branch, make a commit to it, flip to a new branch and move to the history tab, I would expect to see the alert jump out at me, but instead, I don't see anything.  I don't even see the blue dot on the history tab when in the changes tab.  I only trigger the alert the first time if I click the text box that lets us choose the branch to compare, then I immediately get the alert.  After the first time the alert is triggered, it then begins to work as expected.  If I flip back to a base branch that has the newer commit to it, then back to the non-base branch, the history tab has a blue indicator and clicking on the history tab immediately shows the alert.

## Version
* GitHub Desktop: v1.3.1
* Operating system: macOS 10.13.6

## Steps to Reproduce
1. Using a test repo with just a master branch, make a new branch
2. Add a commit to this new branch
3. Flip back to the master and add a commit to the master
4. Flip back to new branch and expect to see the alert showing that the new branch is behind master (but no alert shows)
5. Click text box to compare and compare with master, alert may show up now
6. Clear the text box for comparing a branch to another
7. Flip back to master, then back to new branch and see that alert pops up now as I would expect.

### Expected Behavior
I'd expect that the alert would show up in the same manner that it shows up during step 7: As soon as I flip to a branch that is behind a base branch, the blue dot should appear in the history tab and flipping to the history tab, the alert should show up without having to play around with the comparison text box.

### Actual Behavior
I get two different ways that the alert is triggered.  The first time it is triggered, which calls for clicking the comparison box and flipping back and forth on the changes and history tab, and every time after the first, which is it automatically coming up as I think it should.

Sorry if this is vague or unclear, it is hard to describe.  I will try to explain better if it is still not understood.

## Additional Information
![branch bug](https://user-images.githubusercontent.com/19867440/43438023-2183e5c4-945a-11e8-98d2-08cf44b77a01.gif)

**Comment by billygriffin** [comment] 2019-03-06 22:29
At the time, it seems like we thought this was relatively minor, but my read after further consideration is that this inconsistency is actually preventing people from being informed about this state the vast majority of the time. I wrote up some thoughts in #6875, but this feels like something worth buttoning up before we iterate on how to surface this information since it seems like it never worked as intended.

**Comment by rafeca** [comment] 2020-04-08 10:04
Closing since this has been already fixed (the fix will be available on the next release!)

**Closed by rafeca** 2020-04-08 10:04 UTC
Labels: bug, priority-2
