### ISSUE TITLE
Feature Request: Show running git commands

### ISSUE THREAD

**Issue by alrz** [desktop/desktop#1570] opened 2017-05-17 17:35 UTC
Extremely useful for users on any level to learn git or just to see what's happening under-the-hood.

**SmartGit** has something like this today.

**Comment by shiftkey** [comment] 2017-05-18 00:03
Not sure how I feel about this, for a couple of reasons:

 - [some of our commands are pretty crazy, and might confuse people if we show them as-is](https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/lib/git/log.ts#L12-L33)
 - we want our Git operations to be fast, and putting them in front of people feels contradictory to this goal somewhat

But feel free to convince me otherwise with ideas and suggestions!

**Comment by rlabrecque** [comment] 2017-05-18 01:42
SourceTree sort of has this too, just for long running blocking commands though.

Here's what it looks like in SourceTree:
http://i.imgur.com/UqpC01O.png

Something related that could be interesting though is a git console. You could pull it down with ctrl+`, it would display the complete command history and output [probably] with the exception of automatic refreshes. Then from there you could provide access to git commands right in the GUI if ever you need to do anything more advanced. Moved this over here: #1586

**Comment by niik** [comment] 2017-05-18 08:37
> Extremely useful for users on any level to learn git or just to see what's happening under-the-hood.

I agree with @shiftkey here. There are much better tools for learning git than looking at our cray executions. This idea has been brought up a number of times in the classic apps and we've never been sold on the idea.

**Comment by rlabrecque** [comment] 2017-05-18 08:48
I think the most common use case for me is trying to perform a similar operation that a GUI is performing, and then learning why it does X.
It's definitely something that shouldn't be highly visible though, a user should only see it if they actively want to, which is why I like the idea of hiding it behind a console dialog if that's something that could/would ever happen.

And you know what... It already does that! :) In the standard webkit console (Ctrl+Shift+I)

**Comment by shiftkey** [comment] 2017-05-18 08:51
> In the standard webkit console (Ctrl+Shift+I)

For those who are curious what we're doing, the just switch on debug tracing in the Chrome Dev Tools:

<img width="1149" src="https://cloud.githubusercontent.com/assets/359239/26194203/f796f62e-3bfa-11e7-8985-99b38a350fb4.png">

**Comment by niik** [comment] 2017-05-18 08:54
> For those who are curious what we're doing, the just switch on debug tracing in the Chrome Dev Tools:

@shiftkey Those only show for long-running commands tho right?

**Comment by shiftkey** [comment] 2017-05-18 08:56
> Those only show for long-running commands tho right?

Oops, yes. Only any operation [above 100ms](https://github.com/desktop/desktop/blob/master/app/src/lib/git/core.ts#L114-L120) gets logged.

**Comment by niik** [comment] 2017-05-29 15:20
I think we should close this out. We're not going to add an interactive log for purposes of learning as the commands we run are rarely something that a user would ever run. If someone would like to add a debug log statement for all our Git commands I think that is something we'd consider but not until we've gotten a bit further in our ability to filter out log items.

**Closed by niik** 2017-05-29 15:20 UTC
Labels: enhancement, future-work

**Comment by alrz** [comment] 2018-04-03 00:39
>I think we should close this out. We're not going to add an interactive log for purposes of learning

Just wanted to add, that's not the only purpose. this will be useful to keep the user informed on what is happening under the hood.

**Comment by Peaj** [comment] 2020-09-23 11:00
I still think this is usefull. Not for learning git but especially for debugging.
I appreciate the simplicity of GitHub Desktop and would like to use it for our team but
this is the reason why I always fall back to Tortoise Git eventually. It always displays whats going on.

Simplicity is only great as long as long it works as intended.
If it doesnt there is no way for me to figure out why.

I am currently implementing a commit-msg hook which worked in bash but not in any of the GUIs.
Tortoise logged a charset error though so I could fix the issue (for toroise)
GitHub Desktop still ingores my hook and I have no means of figuring out why.
Maybe it is even using "--no-verify"?

There is no way to figure out as the logs don't even log anything on commit.

An optional log would really help when sth. does not work as intended or takes unusually long.

**Comment by steveward** [comment] 2021-07-26 18:47
From #12665 

>The app, although abstracts the Git commands (which is pretty much the point of a visual Git client), can make it difficult for new devs to understand how things are working behind the app.
Considering the amount of folks who use GitHub Desktop to learn and start using Git, I think the tool can also be used in reverse to help understand the Git commands used instead of wrapping and abstracting it away for all users.

**Comment by german-drulyk** [comment] 2022-07-29 15:30
I would love to see this feature come to light. I don't care how crazy the commands are; it's not like I'm going to run them with reckless abandon.

Learning by examining what people smarter than me are doing is one of my favorite ways to learn.

Don't make this front-and-center; just give me a checkbox to enable a console or something.

**Comment by steveward** [comment] 2022-11-17 14:55
Requested in https://github.com/desktop/desktop/issues/15634.
