### ISSUE TITLE
There was an error with the installation

### ISSUE THREAD

**Issue by BG7ZDQ** [desktop/desktop#17935] opened 2023-12-28 15:36 UTC
### The problem

![msi error](https://github.com/desktop/desktop/assets/118874898/424da178-75fa-4afa-a65c-0f86a322d0d7)
![exe error](https://github.com/desktop/desktop/assets/118874898/ee6aa16e-1f36-42a3-bfb1-c7f9464a301c)
I clicked install and I got an error. A review of the logs reveals that it appears to be related to Microsoft Office Teams components.
I used both the exe installation package and the msi installation package, and I got an error on both sides. Later, I copied them to a virtual machine (also Windows 10 22H2 Professional Workstation Edition) and I still got the same error.

我点击安装，然后就出现了报错。查阅日志发现似乎和微软Office Teams组件有关。
我使用了exe安装包和msi安装包，均出现了报错。后来我把它们拷贝到虚拟机（同样是Windows 10 22H2 专业工作站版），照样出现了相同的报错

### Release version

3.3.6.0

### Operating system

Windows 10 22H2 Workstation

### Steps to reproduce the behavior

1.Double-click to run
2.see error

### Log files

[SquirrelSetup.log](https://github.com/desktop/desktop/files/13787722/SquirrelSetup.log)

### Screenshots

![msi error](https://github.com/desktop/desktop/assets/118874898/424da178-75fa-4afa-a65c-0f86a322d0d7)
![exe error](https://github.com/desktop/desktop/assets/118874898/ee6aa16e-1f36-42a3-bfb1-c7f9464a301c)

**Comment by steveward** [comment] 2023-12-28 20:33
Thanks for the report @X-MQSI. The .cab error looks like it's specific to the .msi installation, and a search seems to indicate this can be caused by a variety of issues. Are you behind a proxy or firewall that could be interfering with the installation?

**Comment by BG7ZDQ** [comment] 2023-12-28 23:44
> Thanks for the report @X-MQSI. The .cab error looks like it's specific to the .msi installation, and a search seems to indicate this can be caused by a variety of issues. Are you behind a proxy or firewall that could be interfering with the installation?

Thank for your help. 

But it not only error in the .MSI file, but also error in .EXE file, Even though I used other computers or virtual machines, it still reported an error. And when I read the install log, I noticed that have many error like about The _Microsoft Office Team_ you can read the log file. 

About network proxy, yes I used it, we might be very difficult to use github without it in China. But I think the  network proxy should be no impact，I don't think it's the reason that install error. However, I will try to take proxy off and install again later.

Thank for your help again!

**Comment by steveward** [comment] 2024-01-12 19:05
@X-MQSI were you able to have success installing GitHub Desktop? Unfortunately there ins't much we can do about installation issues caused by network problems. 

I'm going to close this out, but let me know if you were able to get things working.

**Closed as completed by steveward** 2024-01-12 19:05 UTC
