### ISSUE TITLE
Default branch setting ignored after publishing repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#10293] opened 2020-07-30 16:45 UTC
There is an existing bug where the the user sets a default branch, but a secondary branch ends up being the default branch when the repo is published on Github.com. Fixing this seems more relevant as we roll out the default branch setting in https://github.com/desktop/desktop/pull/10262. In short, the currently selected becomes the default branch when the repo is published.

Repro steps:
- Create new repo
- See naming of default branch (based on #10262)
- Create new branch and stay on that branch
- Publish repo 
- Go to github.com and see that default branch is current branch, not based the setting

Expected result: all settings are honored and all branches are pushed when a repo is published. 

<img width="1077" alt="Screen Shot 2020-07-29 at 1 12 23 PM" src="https://user-images.githubusercontent.com/14828183/88950281-06ba8c80-d25a-11ea-83a1-f8742ccc1ab2.png">

**Comment by rafeca** [comment] 2020-08-03 09:05
Thanks for filling this up @tierninho ! 

It looks like this is caused by dotcom setting the default branch of a new repository to the first branch that gets pushed.

When publishing a repository, Desktop will push the currently checked out branch after the repo gets created via the API, causing the wrong behaviour.

We can fix that by making sure that we use the default repository branch on the first push after creating the repository in dotcom, I'm going to check how easy is to do that.

**Comment by tahunus** [comment] 2023-09-12 02:56
Still happening on ver 3.3.1 (x64) on Windows 11 Home 22H2

**Comment by steveward** [comment] 2024-10-07 19:05
Resolved by https://github.com/desktop/desktop/pull/19151.

**Closed by steveward** 2024-10-07 19:05 UTC
Labels: bug, priority-2
