### ISSUE TITLE
Strange "changes" show up for all the files in the repo, without any file changes.

### ISSUE THREAD

**Issue by engineerpassion** [desktop/desktop#15059] opened 2022-08-01 09:33 UTC
### The problem

The changes section in the GHE Desktop shows all the files as changed, every time.

### Release version

3.0.5 (x64)

### Operating system

Mac OS Big Sur 11.6.6

### Steps to reproduce the behavior

1. It shows up when you change repositories or every time when you pull origin.

**Comment by steveward** [comment] 2022-08-01 15:09
@engineerpassion thanks for the issue. Usually this is caused by line-ending or file mode changes. You can try running `git config core.fileMode false` to see if ignoring file mode changes helps in this instance, and I would also recommend normalizing your line-endings if you are using Windows and macOS. See [this guide](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings) for how to do that. 

It'd also be helpful if you could share the output of `git config --list --show-origin` to verify there aren't any configuration issues that could be causing this.

**Comment by engineerpassion** [comment] 2022-08-02 07:42
@steveward Thanks for the suggestions, I've applied them and will post, if I see the issue again.

The output for `git config --list --show-origin` is as follows:

```
file:/Library/Developer/CommandLineTools/usr/share/git-core/gitconfig   credential.helper=osxkeychain
file:/Users/prateekgoyal/.gitconfig     filter.lfs.smudge=git-lfs smudge -- %f
file:/Users/prateekgoyal/.gitconfig     filter.lfs.process=git-lfs filter-process
file:/Users/prateekgoyal/.gitconfig     filter.lfs.required=true
file:/Users/prateekgoyal/.gitconfig     filter.lfs.clean=git-lfs clean -- %f
file:/Users/prateekgoyal/.gitconfig     user.name=Prateek Goyal
file:/Users/prateekgoyal/.gitconfig     user.email=pgoyal89@in.ibm.com
file:/Users/prateekgoyal/.gitconfig     core.autocrlf=input
```

**Comment by steveward** [comment] 2022-09-12 20:31
@engineerpassion I'm going to close this out, but let me know if you are still having issues with this.

**Closed as completed by steveward** 2022-09-12 20:31 UTC
