### ISSUE TITLE
[Feature Request] SSH Clone

### ISSUE THREAD

**Issue by gperdomor** [desktop/desktop#3506] opened 2017-12-05 12:43 UTC
### Description

Please add an option to clone repositories using ssh instead https from the `Github.com` tab 

<img width="482" alt="screen shot 2017-12-05 at 9 42 10 am" src="https://user-images.githubusercontent.com/371939/33607683-a647809c-d9a0-11e7-8345-6a19894e5730.png">

### Version
1.0.9

**Comment by j-f1** [comment] 2017-12-05 12:49
@gperdomor Why do you prefer SSH cloning instead of HTTPS?

**Comment by gperdomor** [comment] 2017-12-05 12:54
@j-f1 personal preference, but apart of that, the client should can handle both methods since github and any git platform support both methods. I suggest put a checkbox or something similar in the preference panel to configure the default method for cloning repositories

**Comment by iAmWillShepherd** [comment] 2017-12-05 16:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2579. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2017-12-05 16:58 UTC
Labels: enhancement
