### ISSUE TITLE
A bugged folder I created with github that has a point at the end can't be deleted

### ISSUE THREAD

**Issue by Jeison37** [desktop/desktop#19193] opened 2024-09-03 02:49 UTC
### The problem

A bugged folder I created with github that has a point at the end (I put that period by mistake bc i copy-pasted the name and forgot to erase the point) is literally called "-Replica-of-the-Netflix-main-page." It won't let me delete that folder, it says it can't find its location, the weird thing is that when I try to create another folder with the same name "-Replica-of-the-Netflix-main-page." it creates the folder without the point, and when I enter the bugged folder and put something in it, it's as if I entered and manipulated the other folder I just created.

### Release version

Version 3.4.3 (x64)

### Operating system

Windows 10

### Log files

2024-09-01T18:15:11.666Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-09-01T18:15:26.869Z - info: [ui] [AppStore] loading 9 repositories from store
2024-09-01T18:15:26.875Z - info: [ui] [AppStore] found account: Jeison37 (Jeison37)
2024-09-01T18:15:27.359Z - info: [ui] launching: 3.4.3 (Windows 10.0.19045)
2024-09-01T18:15:27.361Z - info: [ui] execPath: 'C:\Users\IMPORTEDNA\AppData\Local\GitHubDesktop\app-3.4.3\GitHubDesktop.exe'
2024-09-01T18:15:27.719Z - info: [ui] Subscribed 'Jeison37' to Alive channel
2024-09-01T18:15:28.081Z - info: [ui] Stats reported.
2024-09-01T18:15:29.084Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.318s)
2024-09-01T18:19:41.837Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-09-01T18:19:44.013Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 5.556s)
2024-09-01T18:19:44.843Z - info: [ui] credential-helper: found GitHub credential for https://github.com/ in store
2024-09-01T18:19:45.366Z - info: [ui] Executing updateRemoteHEAD: git remote set-head -a origin (took 1.352s)
2024-09-01T18:19:47.111Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 8 repositories took 13.1s of which 0.0s paused, total 13.1s
2024-09-01T18:19:49.115Z - error: [ui] createRepository: unable to initialize a Git repository at C:\Users\IMPORTEDNA\Documents\GitHub\-Replica-de-la-pagina-principal-de-Netflix.
Error: Git could not be found at the expected path: 'C:\Users\IMPORTEDNA\AppData\Local\GitHubDesktop\app-3.4.3\resources\app\git\cmd\git.exe'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at C:\Users\IMPORTEDNA\AppData\Local\GitHubDesktop\app-3.4.3\webpack:\app\node_modules\dugite\build\lib\git-process.js:135:39
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
2024-09-01T18:20:01.370Z - info: [ui] [AppStore] adding repository at C:\Users\IMPORTEDNA\Documents\GitHub\-Replica-de-la-pagina-principal-de-Netflix to store
2024-09-01T18:20:02.772Z - info: [ui] Executing isUsingLFS: git lfs track (took 1.308s)
2024-09-01T19:00:45.386Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 3.8s of which 290.0s paused, total 293.8s
2024-09-01T19:22:57.451Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 10 repositories took 8.3s of which 38.3s paused, total 46.6s

### Additional context

When I try to delete the bugged folder, I get a message window that tells me that the folder can't be found and Error 0x80004005.

**Comment by sergiou87** [comment] 2024-09-04 11:15
Closing as duplicate of #19194

**Closed as completed by sergiou87** 2024-09-04 11:15 UTC
