### ISSUE TITLE
Publish button being shown for branch that exists on remote

### ISSUE THREAD

**Issue by jonabc** [desktop/desktop#12034] opened 2021-04-21 16:55 UTC
### Describe the bug

`Publish branch` is displayed for a branch that already exists on the remote.

### Version & OS

2.7.3-beta3 on macOS Catalina 10.15.7

### Steps to reproduce the behavior

I'm not sure how to reproduce, the button properly displayed fetch or push based on the local branch state last night.  When I started working on my computer this morning it was showing the incorrect prompt.

### Expected behavior

The application is aware of the branch existing on the remote and displays the appropriate fetch/push options.

### Actual behavior

The application is showing `Publish` for an already published branch.

### Screenshots

![Screen Shot 2021-04-21 at 9 46 38 AM](https://user-images.githubusercontent.com/5263772/115591693-3b0e2700-a287-11eb-9982-144283a4c2c4.png)

![Screen Shot 2021-04-21 at 9 47 10 AM](https://user-images.githubusercontent.com/5263772/115591697-3e091780-a287-11eb-9724-2a0a62e3b123.png)

### Logs

My log files reference some private repositories that I'd rather not put up in public.

### Additional context

Looking at the log files ☝️ , I don't see any references to pushing the branch to github.  I did find a bunch of statements for failures fetching a repo that I no longer have access to though.  Perhaps that was causing the branches to not be updated for other repos, leading to this bug?

After pressing `publish` things appear to be working again.

**Comment by steveward** [comment] 2021-04-21 17:30
Thanks for the report @jonabc. We've had similar reports in https://github.com/desktop/desktop/issues/8214 and https://github.com/desktop/desktop/issues/10736. Unfortunately these types of issues can be difficult to reproduce, and I've yet to see this behavior myself. Since this was resolved by clicking `Publish` again I'm going to close this out, but let me know if you continue to run into this or have possible reproduction steps.

**Closed as completed by steveward** 2021-04-21 17:30 UTC
