### ISSUE TITLE
 There is an error in recognizing the folder name.

### ISSUE THREAD

**Issue by Ethan-Na** [desktop/desktop#13518] opened 2021-12-13 08:20 UTC
### Describe the bug

Folder name error
The SB_ADMIN2 folder is marked as SSB_ADMIN2 and the contents of the folder cannot be found.

### Version & OS

![image](https://user-images.githubusercontent.com/85219875/145776199-04fdb465-631d-4ced-a72d-8e0c8bd3b036.png)

### Steps to reproduce the behavior

Add a new folder inside the project folder. (ex> ..\Content\CustomTheme\) 

### Expected behavior

If **SB_ADMIN2** folder is added, Git hub desktop recognizes it as _**SSB_ADMIN2**_ folder.

### Actual behavior

Add a folder. (SB_ADMIN2)
Even if you change the name to another name, the situation is the same.

### Screenshots

![image](https://user-images.githubusercontent.com/85219875/145774525-154ed4db-35c7-4758-9f97-e96cc7cb382d.png)
![image](https://user-images.githubusercontent.com/85219875/145774684-48dbc067-1f8c-48b5-9650-61b7bbd6cae7.png)

### Logs

[2021-12-13.desktop.production.log](https://github.com/desktop/desktop/files/7701990/2021-12-13.desktop.production.log)

### Additional context

-

**Comment by niik** [comment] 2021-12-13 09:45
Hey @Ethan-Na, it looks like maybe GitHub Desktop is having problems parsing the path to that directory. Likely this has something to do with the language of your operating system which makes it hard for me to debug this remotely.

Would you be able to run the following command in a console?

Start by clicking on the Repository menu and then on "Open in Command Prompt", then run the following command:

```
git status --untracked-files=all --branch --porcelain=2 -z > status.txt
```

That should create a file called `status.txt`. Please attach that to this issue and we'll investigate further. Thanks!

**Comment by Ethan-Na** [comment] 2021-12-15 04:47
> 
Thanks for the guide I have attached the file you requested. Thanks,

[status.txt](https://github.com/desktop/desktop/files/7716512/status.txt)

**Comment by niik** [comment] 2021-12-15 10:03
Hey @Ethan-Na, thanks for that status file. Unfortunately it didn't help us understand where the issue is coming from. In your earlier screenshots the path includes a strike-through W character

![image](https://user-images.githubusercontent.com/634063/146165670-de906f08-1d1d-41ff-8fc7-160650a3e2d1.png)

I would expect this to read `Crystal5DWManager\Content\CustomTheme\SB_ADMIN2`. Does that character show up for all files in your repository? Could you look at a previous commit in the history tab and see if the path looks the same there?

**Comment by Ethan-Na** [comment] 2021-12-15 10:12
![image](https://user-images.githubusercontent.com/85219875/146167088-826c7f18-50d1-40b6-9598-ec70d629c69d.png)

You will see it in the attached image.
Not yet committed. This is the newly created folder.
In addition, the name and contents of the folder cannot be read.

==============================================
I solved it by creating a new folder.
Perhaps it is a phenomenon caused by pasting a sub-project.

![image](https://user-images.githubusercontent.com/85219875/146171339-ececdda9-7da2-4081-8682-340840be8a43.png)

**Comment by steveward** [comment] 2021-12-16 21:37
I think this is the same as https://github.com/desktop/desktop/issues/12314, since @Ethan-Na seems to have worked around this I am going to close this out and reference this in #12314.

**Closed as completed by steveward** 2021-12-16 21:37 UTC

**Comment by raoalihassan228** [comment] 2023-12-25 09:09
I'm finding the same issue, when I opens the folder in GitHub desktop, the file have no content , how would it resolve
