### ISSUE TITLE
Flickering branch selector blocks branch switching until repo is removed

### ISSUE THREAD

**Issue by CliffWMiller** [desktop/desktop#10733] opened 2020-10-05 18:09 UTC
### Describe the bug

Intermittently when I switch branches the switch will get stuck in a flickering state.

### Version & OS

Version 2.5.6
macOS Catalina 10.15.6

### Steps to reproduce the behavior

1. Open the branch dropdown
2. Select another branch

### Expected behavior

The branch switches.

### Actual behavior

The branch selector flickers until I close the application. Reopening the application stops the flickering but attempting to switch branches again will recreate the issue. The only way I've found to resolve the issue is to remove the repo and re-clone it.

### Screenshots

![Screen Recording 2020-10-05 at 10 50 24 AM](https://user-images.githubusercontent.com/3608623/95115389-425e5080-06fa-11eb-9f23-32a177b02c31.gif)

### Logs

```
2020-10-05T00:17:45.089Z - info: [ui] [BranchPruner] Last prune took place in a few seconds - skipping
2020-10-05T00:20:58.296Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.292s)
2020-10-05T00:52:56.647Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.342s)
2020-10-05T01:24:08.343Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.002s)
2020-10-05T03:31:10.513Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.042s)
2020-10-05T04:02:49.810Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.240s)
2020-10-05T04:17:54.220Z - info: [ui] [BranchPruner] Pruning 0 branches that have been merged into the default branch, master (a02011ac31deb2626f8d770575f65f1212d3e23f), from 'backtowork
2020-10-05T04:17:54.314Z - info: [ui] Stats reported.
2020-10-05T04:33:41.407Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.340s)
2020-10-05T05:05:02.510Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.190s)
2020-10-05T05:37:20.729Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.096s)
2020-10-05T06:40:50.862Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.111s)
2020-10-05T07:43:33.849Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.019s)
2020-10-05T08:15:26.600Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.266s)
2020-10-05T08:18:09.077Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2020-10-05T09:18:44.926Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.047s)
2020-10-05T09:51:12.401Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.294s)
2020-10-05T10:53:36.888Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.333s)
2020-10-05T12:17:44.734Z - info: [ui] [BranchPruner] Last prune took place in 16 hours - skipping
2020-10-05T12:28:02.737Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.678s)
2020-10-05T12:59:15.816Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.698s)
2020-10-05T13:30:45.686Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.280s)
2020-10-05T14:02:58.505Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.301s)
2020-10-05T14:34:25.613Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.306s)
2020-10-05T15:06:07.445Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.338s)
2020-10-05T15:37:09.804Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.331s)
2020-10-05T16:06:54.001Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.3s of which 0.0s paused, total 0.3s
2020-10-05T16:06:56.001Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T16:06:56.203Z - info: [ui] [Timing] Action 'checkout branch from list' for 'backtowork-app/backtowork' took 0.199s
2020-10-05T16:08:47.738Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.175s)
2020-10-05T16:10:24.056Z - info: [ui] No submodules found. Skipping "git submodule status"
2020-10-05T16:10:41.596Z - info: [ui] [Timing] Action 'create commit' for 'backtowork-app/backtowork' took 0.315s
2020-10-05T16:10:43.438Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T16:10:47.278Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin BTW-856/latestuserstatuses-additional-actions:BTW-856/latestuserstatuses-additional-actions --progress (took 3.811s)
2020-10-05T16:11:16.763Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T16:11:16.947Z - info: [ui] [Timing] Action 'checkout branch from list' for 'backtowork-app/backtowork' took 0.177s
2020-10-05T16:12:23.118Z - info: [ui] [Timing] Action 'checkout branch from list' for 'backtowork-app/backtowork' took 0.000s
2020-10-05T16:12:25.266Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T16:12:25.598Z - info: [ui] [Timing] Action 'stash and checkout' for 'backtowork-app/backtowork' took 0.415s
2020-10-05T16:17:45.437Z - info: [ui] [BranchPruner] Last prune took place in 12 hours - skipping
2020-10-05T16:36:10.582Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.3s of which 0.0s paused, total 0.3s
2020-10-05T16:44:07.615Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.405s)
2020-10-05T17:14:32.133Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.170s)
2020-10-05T17:41:35.069Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.3s of which 0.0s paused, total 0.3s
2020-10-05T17:41:36.822Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:41:41.220Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin BTW-856/latestuserstatuses-additional-actions:BTW-856/latestuserstatuses-additional-actions --progress (took 4.355s)
2020-10-05T17:41:42.314Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.073s)
2020-10-05T17:42:07.388Z - info: [ui] [Timing] Action 'create commit' for 'backtowork-app/backtowork' took 0.247s
2020-10-05T17:42:09.135Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:42:12.821Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin BTW-856/latestuserstatuses-additional-actions:BTW-856/latestuserstatuses-additional-actions --progress (took 3.675s)
2020-10-05T17:46:28.752Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:46:28.805Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress BTW-917/current-status-from-latestuserstatus --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	packages/btw-organization-request/functions/.npmrc
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2020-10-05T17:46:28.846Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:46:28.897Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress BTW-917/current-status-from-latestuserstatus --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	packages/btw-organization-request/functions/.npmrc
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2020-10-05T17:46:28.954Z - info: [ui] [Timing] Action 'checkout branch from list' for 'backtowork-app/backtowork' took 0.184s
2020-10-05T17:46:28.954Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:46:29.018Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress BTW-917/current-status-from-latestuserstatus --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	packages/btw-organization-request/functions/.npmrc
Please commit your changes or stash them before you switch branches.
Aborting

...[many duplicates of the above error removed, see attached log if needed]...

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2020-10-05T17:50:50.224Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: backtowork - CliffWMiller (has token)
2020-10-05T17:50:53.534Z - info: [ui] [AppStore] loading 1 repositories from store
2020-10-05T17:50:53.535Z - info: [ui] [AppStore] found account: CliffWMiller (Cliff Miller)
2020-10-05T17:50:54.261Z - info: [ui] launching: 2.5.6 (Mac OS 10.15.6)
2020-10-05T17:50:54.262Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2020-10-05T17:50:54.277Z - info: [ui] [BranchPruner] Pruning 0 branches that have been merged into the default branch, master (28f707ce7d3621142e451eac7adfa8371e6c83f2), from 'backtowork
2020-10-05T17:54:53.620Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 0.3s of which 0.0s paused, total 0.3s
```

### Additional context

Looking at the logs I see that there is a looping error that there are changes that need to be stashed. When this happened again today, this shouldn't be accurate to my recollection. I had committed then I was going to switch branches. The changes it seems to refer to should be git-ignored.

[2020-10-05.desktop.production.log](https://github.com/desktop/desktop/files/5329281/2020-10-05.desktop.production.log)

**Comment by steveward** [comment] 2020-10-06 21:28
Thanks for the report @CliffWMiller -- could you run a `git status` from the command line on your `BTW-917/current-status-from-latestuserstatus` branch and let me know the output?

>The only way I've found to resolve the issue is to remove the repo and re-clone it.

Have you been able to consistently reproduce this issue even after re-cloning?

**Comment by steveward** [comment] 2020-10-07 14:02
This actually looks like a duplicate of https://github.com/desktop/desktop/issues/10733 -- I'm going to add the details from here to that issue. You can follow along there for updates.

**Closed by steveward** 2020-10-07 14:02 UTC
Labels: more-info-needed
