### ISSUE TITLE
`Enter` key should be consistent for dialogues/modals?

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3629] opened 2017-12-18 19:57 UTC
Hitting `enter` on some of the dialogues/modals results in an action, while other nothing happens. There should be consistency.

For instance:
- hit `enter` on the `Install Command Line Tool...` dialogue and the `OK` is triggered
- hit  `enter` after selecting a repo on the Clone Repo modal and the `Clone` is *not* triggered
- hit `enter` on git lock dialogue and `Close` is not triggered

<img width="475" alt="screen shot 2017-12-18 at 11 45 59 am" src="https://user-images.githubusercontent.com/14828183/34125252-801e870e-e3ea-11e7-8cc0-087c1eff73f3.png">
<img width="599" alt="screen shot 2017-12-18 at 11 55 15 am" src="https://user-images.githubusercontent.com/14828183/34125255-822c0a1c-e3ea-11e7-98b1-2a070445ff49.png">

Build v1.0.12-beta0. mac

**Comment by http-request** [comment] 2017-12-19 15:57
About `Install Command Line Tool`, If you click inside dialog and `ok` button has lost focus then `enter` is not triggered. Do you want to set focus on buttons by default (and lose trigger when button lost focus) or add keyPress handler to components?

**Comment by koenpunt** [comment] 2018-01-11 00:11
Consistent <kbd>Enter</kbd>, but also a consistent <kbd>Space</kbd> would be nice; on macOS most dialogs with more than 1 action, have the primary action respond to <kbd>Enter</kbd>, and highlight the secondary option to respond to <kbd>Space</kbd>. By hitting <kbd>Tab</kbd> one could move the action for <kbd>Space</kbd> to another option.

For example the empty trash confirmation dialog:

![image](https://user-images.githubusercontent.com/351038/34802015-ba734352-f66b-11e7-9a60-b1b85d31d4ba.png)

Primary action is blue, so can be chosen by hitting <kbd>Enter</kbd>, the cancel option is highlighted by a blue outline, which indicates it can be chosen by hitting <kbd>Space</kbd>.

Then when I hit <kbd>Tab</kbd> once, it looks like this:

![image](https://user-images.githubusercontent.com/351038/34802074-ee79b7b2-f66b-11e7-8f0c-a03b3a34e1d5.png)

Now I can confirm with both <kbd>Space</kbd> and <kbd>Enter</kbd>.

**Comment by agisilaos** [comment] 2018-02-01 23:00
Hey @iAmWillShepherd I started digging into this and I observed how the `ok` is triggered on the `Install Command Line Tool...` but when I try to follow the same pattern to the clone repo modal I really hit a wall. Let me explain.

In the command line tool modal the dialogue with the Ok button is triggered because of this line of code:

https://github.com/desktop/desktop/blob/d0dab86468054dd7ffa42ba3cd26c31c5dfaacfd/app/src/ui/cli-installed/cli-installed.tsx#L23

But when I try to do something simillar for the Clone Repo modal, the "on Submit" line of code looks like that:

https://github.com/desktop/desktop/blob/d0dab86468054dd7ffa42ba3cd26c31c5dfaacfd/app/src/ui/clone-repository/clone-repository.tsx#L96

I tried to create a 2nd onSubmit but that was a mistake and got an error from it. Any ideas how should I add the `onSubmit={this.props.onDismissed} ` in the clone repo modal?

I want to continue and work on the rest of the modals in this issue but this is an intro question that I have regarding this issue. Thanks in advance.

P.s Also I would love to know if my approach finding what needs to be fixed and how is the "correct" one or if I need to think about it differently.

**Comment by iAmWillShepherd** [comment] 2018-03-05 18:25
@agisilaos, so sorry I'm getting to this so late. I think the issue is about consistency with actions. In your second example, the correct action to take on enter is to Clone, not dismiss the dialog. Maybe we can make <kbd>esc</kbd> the default key to close a modal?

**Comment by agisilaos** [comment] 2018-03-06 10:37
Makes total sense, thank you for getting back to me with that info. Will work on that and I will let you know if I have any questions etc. @iAmWillShepherd!

**Comment by iAmWillShepherd** [comment] 2018-03-06 17:31
@agisilaos, I'm sure you know by now, but could you add `Fixes #3629` at the top of your PR body when you open it?

**Comment by agisilaos** [comment] 2018-03-13 12:02
@iAmWillShepherd The current issue that we have here is that when you press enter after you selected a repo to clone nothing happens. If you press esc the dialog dismiss just fine. I'm trying to achieve what @tierninho mentioned in the issue description:

> hit enter after selecting a repo on the Clone Repo modal and the Clone is not triggered. 

How I make the clone to be triggered? That's why I followed up with my question above. Sorry if that didn't make sense in the first place.

**Comment by gingerbeardman** [comment] 2018-03-19 12:26
macOS Human Interface Guidelines

https://developer.apple.com/macos/human-interface-guidelines/buttons/push-buttons/

> Configure a push button the user is highly likely to select as the default. A default push button is prominent in appearance and automatically performs its action when the user presses Return. There can only be a single default button in a view.

**Comment by billygriffin** [comment] 2018-10-02 15:02
@gingerbeardman Where do you see that "default is always rightmost" in the macOS guidelines? I couldn't find that anywhere, and a quick check of deleting something in my trash runs counter to that.

<img width="384" alt="screen shot 2018-10-02 at 9 00 35 am" src="https://user-images.githubusercontent.com/5091167/46357303-cb30e600-c621-11e8-91b4-9d02af199c62.png">

**Comment by koenpunt** [comment] 2018-10-02 15:08
What @billygriffin says is true. 

And it's also not true that the secondary item is always focussed. If you do CMD+ALT+BACKSPACE on a file, you'll get an dialog that has the `Cancel` button as primary, which is also the focussed button;

![image](https://user-images.githubusercontent.com/351038/46357647-9b0b3680-c665-11e8-859f-a1fd0052cb57.png)

**Comment by gingerbeardman** [comment] 2018-10-02 15:11
https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/

> **Place buttons where people expect them.** In general, the button people are most likely to choose should be on the right. The default button should always be on the right. Cancel buttons are typically on the left.

In full...

> ## Alert Buttons
> **Generally, use two-button alerts.** Two-button alerts provide an easy choice between two alternatives. Single-button alerts inform, but give no control over the situation. Alerts with three or more buttons create complexity.
> 
> **Give alert buttons succinct, logical titles.** The best button titles consist of one or two words that describe the result of clicking the button. As with all button titles, use title-style capitalization and no ending punctuation. To the extent possible, use verbs and verb phrases that relate directly to the alert title and message—for example, View All, Reply, or Ignore. Use OK for simple acceptance. Avoid using Yes and No.
> 
> **Ensure that the default button title reflects the action the button performs.** Avoid using OK for the default button unless the alert is purely informational. The meaning of OK can be unclear even in alerts that ask if the user is sure they want to do something. For example, does OK mean “OK, I want to complete the action” or “OK, I now understand the negative results my action would have caused”? A specific button title like Erase, Convert, Clear, or Delete helps the user understand the action they’re taking.
> 
> **Place buttons where people expect them.** In general, the button people are most likely to choose should be on the right. The default button should always be on the right. Cancel buttons are typically on the left.
> 
> **Label cancellation buttons appropriately.** A button that cancels an alert’s action should always be labeled Cancel.
> 
> **Include a Cancel button when there’s a destructive button.** A Cancel button provides a clear, safe way to opt out of a destructive action. Consider making the Cancel button the default button too, requiring the user to intentionally click a button to continue with the destructive action.
> 
> **Allow the Esc (Escape) key and Command-Period (.) keyboard shortcut to cancel alerts.** Pressing Esc or Command-Period while an alert is visible should produce the same effect as clicking the Cancel button—that is, the alert is dismissed without performing any action. If your alert doesn’t have a Cancel button, consider implementing a cancel action in your code that runs when Esc or Command-Period is pressed.
> 
> **Consider offering time-saving keyboard shortcuts for all buttons.** For example, you could let people activate a Print button by pressing the P key, or a Don't Save button by pressing the D or Delete key.

**Comment by j-f1** [comment] 2018-10-02 15:18
It seems like Cancel should be the default when the action is destructive, and the destructive action should be on the right since that’s the most common action.

**Comment by gingerbeardman** [comment] 2018-10-02 15:19
@j-f1 indeed, see point 6 in the list (and my edit above)

**Comment by koenpunt** [comment] 2018-10-02 15:22
> It seems like Cancel should be the default when the action is destructive, and the destructive action should be on the right since that’s the most common action.

Btw, moving a file to the trash is not seen as destructive apparently, because there the cancel button is not the default.

**Comment by gingerbeardman** [comment] 2018-10-02 15:33
@koenpunt the default button is the blue one

**Comment by koenpunt** [comment] 2018-10-02 15:36
Oh I meant emptying the trash;

![image](https://user-images.githubusercontent.com/351038/46359517-b7a96d80-c669-11e8-8a6b-7182c492cdc3.png)

**Comment by gingerbeardman** [comment] 2018-10-02 15:50
Interesting. 

So immediate deletion is seen as destructive, but emptying the Trash is not. 

I could only guess at the reasoning.

**Comment by ruggi99** [comment] 2020-06-08 18:12
@tierninho could you update this issue if you have the time?

**Comment by sergiou87** [comment] 2024-09-24 10:34
This was fixed in recent accessibility work

**Closed by sergiou87** 2024-09-24 10:34 UTC
Labels: enhancement, not-planned

**Comment by gingerbeardman** [comment] 2024-09-24 11:40
Praise be!

Only 7 years, some sort of record I imagine.

All the more confusing to have "not-planned" label.
