### ISSUE TITLE
When publishing a repository, other branches don't get published.

### ISSUE THREAD

**Issue by REMInvizer** [desktop/desktop#17205] opened 2023-08-10 17:52 UTC
### The problem

When publishing a repository, only the current branch gets published, and the current branch becomes default.

### Release version

Version 3.2.7 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a new repository
2. Create a new branch
3. Click on "Publish repository"

### Screenshots

https://github.com/desktop/desktop/assets/141772529/c917a80f-fc8e-434d-87aa-2be76a269464

**Comment by RowanFuture** [comment] 2023-10-05 19:42
To me this seems like expected behaviour, as you can still publish the branches separately.
Is it necessary to make the publish repository button publish every local branch?
Or should the publish repository button just switch the branch to the default branch and then publish?

**Comment by steveward** [comment] 2023-10-26 18:37
I'm going to close this out because the expected behavior is that each branch needs to be published separately.

However, the issue with the wrong default branch getting selected is a known bug that is being tracked in https://github.com/desktop/desktop/issues/10293.  You can follow along there to track this bug.

**Closed as completed by steveward** 2023-10-26 18:37 UTC
Labels: bug
