### ISSUE TITLE
Discard changes no longer works

### ISSUE THREAD

**Issue by jainsamyak** [desktop/desktop#11099] opened 2020-11-23 06:03 UTC
### Describe the bug

The discard changes option available in the context menu no longer works, both for single changes and "discard all" functionality

### Version & OS

OS: Windows 10 v20H2
Version 2.6.0

### Steps to reproduce the behavior

1. Go to any repository which has unstaged changes
2. Right click on any changed file and choose discard changes
3. It does not have any affect

### Expected behavior

It should discard the selected change.

### Actual behavior

No affect on clicking discard changes.

### Screenshots

![image](https://user-images.githubusercontent.com/33225811/99932974-ac50b900-2d7f-11eb-9140-08d351f9f8ba.png)

### Current Workaround
1. Stash necessary changes
2. Select discard all from stash

### Logs
NA

### Additional context
NA

**Comment by niik** [comment] 2020-11-23 11:14
Hi @jainsamyak, sorry to hear you're having problem. I'm unable to reproduce this on my Windows 10 machine, and this is the first report we've gotten that it might not be working so I'm afraid I'm at a bit of a loss trying to understand why it doesn't work for you.

Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

Thanks!

**Comment by jainsamyak** [comment] 2020-11-23 12:08
Hi @niik,
On further analysis, I find that it is specific to my WSL Distro (Ubuntu 20.04) on Windows. The git folder is on WSL mounted directory.

Unfortunately, for logs, I don't see anything being generated specific to the issue. I cleared the logs directory and reproduced the issue, but no logs found.
For more detail, please see attached GIF:
![NmBNWihH31](https://user-images.githubusercontent.com/33225811/99960421-b50eb280-2db2-11eb-898c-29e817664e88.gif)


Please let me know how I can assist in reproducing further.

Thanks.

**Comment by NinoFoxx** [comment] 2020-11-24 03:29
Could you please explain what do you mean by "The git folder is on WSL mounted directory"?

I'll try reproducing the issue but I need more info on how the directory was mounted.

Was it mounted from within WSL? What's the filesystem of the underlying drive ?

**Comment by jainsamyak** [comment] 2020-11-24 06:17
> Could you please explain what do you mean by "The git folder is on WSL mounted directory"?
> 
> I'll try reproducing the issue but I need more info on how the directory was mounted.
> 
> Was it mounted from within WSL? What's the filesystem of the underlying drive ?

What I mean is that the folder is simply created under the home directory of Windows Subsystem for Linux.
 
I've mapped the root WSL directory as a network drive on Windows **(U:\)** and the location that Github Desktop is referring to is `U:\home\samyak\<git-repo-name>`

**Comment by Anthropic** [comment] 2021-03-30 11:34
I assume this is a duplicate of this issue [GitHub Desktop gets confused on file permissions (x-bit) in WSL #9443](9443) ?

**Comment by jainsamyak** [comment] 2021-03-31 02:43
> I assume this is a duplicate of this issue [GitHub Desktop gets confused on file permissions (x-bit) in WSL #9443](9443) ?

Unable to open the link shared..

**Comment by jainsamyak** [comment] 2021-03-31 02:44
But I believe this was fixed in the latest version, I'm not facing this issue anymore.

**Closed as completed** 2021-03-31 02:44 UTC
