### ISSUE TITLE
GitHub Desktop Deleting Stashed Files

### ISSUE THREAD

**Issue by dlichti** [desktop/desktop#10703] opened 2020-10-01 13:05 UTC
### Describe the bug

Since updating my desktop client two days ago, whenever I click 'Restore' to bring back stashed code, it is just discarded. I have been recovering using steps provided [here](https://gist.github.com/joseluisq/7f0f1402f05c45bac10814a9e38f81bf).

### Version & OS

Version 2.5.6
Win10 Pro version 1909 build 18363.1082

### Steps to reproduce the behavior

1. Switch to a different branch and stash the existing updates. (specifically I have been switching away from the master branch)
2. Navigate back to the original branch with the stashed files
3. Click on the Stashed Files above the Summary input.
4. Click 'Restore' 

### Expected behavior

Normally the files would be restored and shown on the changes tab.

### Actual behavior

The files just disappear and have to be restored manually.

**Comment by niik** [comment] 2020-10-01 13:08
Hi @dlichti, thanks for opening this. I'm unable to reproduce this and this is the first we've heard of it. Does this happen on all repositories or just a specific repository?

Thanks for the report! Could you upload a log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. 

Thanks!

**Comment by niik** [comment] 2020-10-12 09:04
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2020-10-12 09:04 UTC
Labels: more-info-needed
