### ISSUE TITLE
Add a folder option in the sidebar.

### ISSUE THREAD

**Issue by xioto** [desktop/desktop#12487] opened 2021-06-20 17:24 UTC
### Describe the feature or problem you’d like to solve

Add a folder option in the sidebar, so you can organize your repositories.

![image](https://user-images.githubusercontent.com/72493732/122683003-7c25a780-d1f4-11eb-8dfa-e3dd3aa33d0d.png)

As I normally have a "main" repository and a "testing" repository for all my large projects, it would be nice to be able to have them separated.

**Comment by tidy-dev** [comment] 2021-06-21 11:48
Thanks for the feedback @AsierArizti. This is close to a duplicate of #12254. As we stated there, we don't have any plans to allow for custom group names since we already group repositories by user/org/recent/other. Repository list reordering is something we may look into in the future, and is being tracked in issues like #8183 and #11608. I'm going to close this out since we're tracking repository list improvements in multiple issues.

**Closed as completed by tidy-dev** 2021-06-21 11:48 UTC
