### ISSUE TITLE
Opens a new chrome tab on ]

### ISSUE THREAD

**Issue by Tusky** [desktop/desktop#2607] opened 2017-09-04 00:27 UTC
### Description

With hungarian layout pressing the `]` character is done with altgr+G which the Github application catches as ctrl+alt+g which opens a chrome tab.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Press alt gr+G

**Expected behavior:** It does not open a chrome tab.

**Actual behavior:** Opens a chrome tab.

**Reproduces how often:** Every time :)

**Comment by shiftkey** [comment] 2017-09-04 00:55
@Tusky thanks for the details and the repro steps. I was able to recreate this on Windows 10 using the onscreen keyboard set to Hungarian.

> Opens a chrome tab.

For a moment I was worried about what this was opening, but it's opening the current repository on GitHub as it currently maps to <kbd>Ctrl + Alt + G</kbd>.

It looks like this accelerator is correctly correctly:

https://github.com/desktop/desktop/blob/d5b56b9d3a9a00bb85a40e2f6a0a636724edcb90/app/src/main-process/menu/build-default-menu.ts#L218

The [documentation](https://electron.atom.io/docs/api/accelerator/#available-modifiers) suggests that `Alt` and `AltGr` can be declared as separate menu accelerators, but perhaps it's invoking the incorrect shortcut.

I suspect this is something that needs to be fixed in Electron, unless it's already been addressed in the 1.7.x series (we're on 1.6.x currently).

**Comment by Tusky** [comment] 2017-09-04 00:59
Yes, I understand that must be something underlying issue, but it's really annyoing I have to close the tab it opens (not to mention it switches focus) because we use `[issue id] - description` syntax. I was looking for a hotkey changing option because that would have been the simplest solution to just disable that hotkey since I do need that especially like this, but currently there is no option to change hotkeys as far as I know within the github client.

**Comment by shiftkey** [comment] 2017-09-04 01:10
@Tusky I wasn't able to reproduce this on the `1.7.x` PR I'm working on in #2582 (it's inserting `]` into the commit details as expected).

**Comment by Tusky** [comment] 2017-09-04 02:51
yes it is inserting `]` the character but opens the chrome tab also. But I'm glad if that is fixed on the 1.7.x ! Can't wait for you to have that deployed :)

**Comment by Tusky** [comment] 2017-09-10 23:09
Using the newest 0.8.1 version it still reproduces :(

**Comment by shiftkey** [comment] 2017-09-10 23:41
@Tusky I guess I missed something with my repro steps. Apologies, I'll try and get this reproducible against Electron itself (to confirm it's not a Desktop-specific issue).

**Comment by shiftkey** [comment] 2017-09-11 00:03
I've got a repro here that shows the issue, but it's reproducible on the 1.8.0 beta of Electron still: https://github.com/shiftkey/electron-hungarian-keyboard-shortcut

Trying to isolate where this problem lives before I log it upstream - hoping its an easy fix!

**Comment by shiftkey** [comment] 2017-09-11 00:19
Looks like this is a Windows Intended Behaviour, and our choice of shortcut here isn't helpful. From Raymond Chen's [blog](https://blogs.msdn.microsoft.com/oldnewthing/20040329-00/?p=40003/):

> You may have noticed that Windows doesn't use Ctrl+Alt as a keyboard shortcut anywhere. (Or at least it shouldn't.) **If a chorded modifier is needed, it's usually Ctrl+Shift.**
>
> That's because Ctrl+Alt has special meaning on many keyboards. The combination Ctrl+Alt is also known as AltGr, and it acts as an alternate shift key. For example, consider the German keyboard layout. Notice that there are three keyboard shift states (Normal, Shift, and AltGr), whereas on U.S. keyboards there are only two (Normal and Shift). For example, to type the @ character on a German keyboard, you would type AltGr+Q = Ctrl+Alt+Q. (Some languages, like Swedish, have a fourth state: Shift+AltGr. And then of course, there's the Japanese keyboard...)

@desktop/core I think we should change this to be <kbd>Ctrl + Shift + G</kbd> to align with all our other shortcuts. I don't think this clashes with an existing shortcut, but I'll confirm as part of the PR process.

**Comment by lee-dohm** [comment] 2017-09-11 02:59
We had to move away from `Ctrl+Alt` shortcuts for the same reason.

**Closed** 2017-09-11 20:33 UTC
Labels: bug
