### ISSUE TITLE
GitHub stuck on pushing to origin

### ISSUE THREAD

**Issue by GreyZar37** [desktop/desktop#15617] opened 2022-11-14 08:00 UTC
### The problem

When I am trying to push to origin, my GitHub gets stuck on "Pushing to origin". I cannot push anything to the origin any more. I have tried to push on every repository I had, but no luck. 

### Release version

3.1.2 

### Operating system

Windows 11 

### Steps to reproduce the behavior

- Commit
- Press Push

### Log files

[2022-11-14.desktop.production.log](https://github.com/desktop/desktop/files/10000774/2022-11-14.desktop.production.log)

### Screenshots

![Skærmbillede 2022-11-14 085933](https://user-images.githubusercontent.com/52458016/201606147-3edf1564-5509-4606-8b7a-e6e0f184b8a3.png)

**Comment by steveward** [comment] 2022-11-14 18:56
Thanks for the report @GreyZar37. I'm seeing a few things in the log file. The first error is `ECONNRESET` which indicates that something is closing the TCP connection that's created for authentication:

```
2022-11-14T07:54:51.983Z - error: [ui] Trampoline client error
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

Is there any security software on your machine or network that could be causing this?

**Comment by GreyZar37** [comment] 2022-11-14 19:41
I have not installed new security system. I use the same as before when
GitHub worked for me. On my other computer, GitHub is working fine on the
same internet.

Den man. 14. nov. 2022 kl. 19.56 skrev Steve Ward ***@***.***

**Comment by steveward** [comment] 2022-11-14 21:35
Thanks for the update. Have you tried resetting your machine to see if that helps?

I'd also be curious to know if anything shows up in the Developer Tools that may give a better idea of what's happening. Can you go to `View` > `Toggle Developer Tools` and see if anything interesting is shown in the `Console` or `Network` tab when you click `Push origin`?

**Comment by GreyZar37** [comment] 2022-11-15 06:54
I do get errors. I have not tried to reset my laptop, and I do not think I
will do it. It is my work laptop and I do not want to risk loosing any of
my work.
 [image: image.png]

Den man. 14. nov. 2022 kl. 22.35 skrev Steve Ward ***@***.***

**Comment by steveward** [comment] 2022-11-15 14:13
Apologies, I meant a simple reset (not reinstalling Windows). Can you share the screenshot directly in this issue? Sending images as attachments via email reply does not work unfortunately.

**Comment by GreyZar37** [comment] 2022-11-17 12:52
![image](https://user-images.githubusercontent.com/52458016/202451459-519caf84-840b-44d8-9ae7-5731dd6be944.png)
I apologize, here is the image I sent.

**Comment by GreyZar37** [comment] 2022-11-22 14:50
I sent you the image :)

Den tir. 15. nov. 2022 kl. 15.13 skrev Steve Ward ***@***.***

**Comment by steveward** [comment] 2022-12-20 17:39
@GreyZar37 are you still encountering this issue? https://github.com/desktop/desktop/issues/11696 is a similar previous issue, and we could try similar steps to debug this.

**Comment by GreyZar37** [comment] 2023-01-05 16:04
Hello, I did not have time to answer before, but now I do. I still have the
issue with GitHub Desktop, but Gitkraken does work for me

Den tir. 20. dec. 2022 kl. 18.39 skrev Steve Ward ***@***.***

**Comment by sergiou87** [comment] 2023-01-05 17:10
As @steveward mentioned, that error seems like something that would be caused by an antivirus or a firewall. Since it's a work laptop, maybe your IT admin pushed some new security setup that could affect GitHub Desktop like this?

**Comment by GreyZar37** [comment] 2023-01-05 18:04
It is my own laptop. I only have windows antivirus. I tried to run GitHub
as administrator, and make that program bypass firewall

Den tor. 5. jan. 2023 kl. 18.10 skrev Sergio Padrino <
***@***.***>:

**Comment by sergiou87** [comment] 2023-01-09 09:38
@GreyZar37 did you bypass it for `C:\Users\<your-username>\AppData\Local\GitHubDesktop\app-3.1.3\resources\app\desktop-trampoline\desktop-trampoline.exe` too? That's the helper program used by GitHub Desktop to provide your credentials to Git via TCP socket.

Just in case, if possible I'd recommend to **temporarily** disable both firewall and antivirus completely and see if that gets it working, at least to narrow down where the issue is (or is not).

**Closed as completed** 2023-01-16 10:09 UTC
Labels: more-info-needed
