### ISSUE TITLE
Squash Commit Message dialog does not close

### ISSUE THREAD

**Issue by yasuking0304** [desktop/desktop#16693] opened 2023-05-14 09:49 UTC
### The problem
Squash Commit Message dialog does not close.

### Release version

3.2.3

### Operating system

Windows10, Mac OS Monterey

### Steps to reproduce the behavior

1. Click the "History" tab in the left pane
2. Drag and drop the items you want to summarize
3. Select "Squath N commits..." from the right-click menu
4. Click "Squath N Commits" button on "Squash N Commits" dialog
5. Click "Cancel" button on "Squash will require force push" dialog

### Screenshots

https://github.com/desktop/desktop/assets/111163564/b3f03563-f1ed-4a12-91c5-ab483883b103

### Additional context

I haven't tested it in detail, but shouldn't I explicitly include the process of closing the Popup?

https://github.com/desktop/desktop/blob/development/app/src/ui/history/compare.tsx#L657-L664
Now
```TypeScript
      onSubmitCommitMessage: async (context: ICommitContext) => {
        this.props.dispatcher.squash(
          this.props.repository,
          toSquashSansSquashOnto,
          squashOnto,
          lastRetainedCommitRef,
          context
        )
        return true
      },
```
After
```TypeScript
      onSubmitCommitMessage: async (context: ICommitContext) => {
        this.props.dispatcher.closePopup(PopupType.CommitMessage)
        this.props.dispatcher.squash(
          this.props.repository,
          toSquashSansSquashOnto,
          squashOnto,
          lastRetainedCommitRef,
          context
        )
        return true
      },
```

**Comment by tidy-dev** [comment] 2023-05-15 11:05
Duplicate of https://github.com/desktop/desktop/issues/16605

**Closed as completed by tidy-dev** 2023-05-15 11:05 UTC
