### ISSUE TITLE
Keep getting error message 'Remote has disconnected'

### ISSUE THREAD

**Issue by l0stb0y** [desktop/desktop#2545] opened 2017-08-25 14:03 UTC
### Description

I upgraded the app to v.8, and every push to the remote end with a 'remote has disconnected' error  

### Version

**GitHub Desktop version:** [0.8.0]

**OS version:** [OSX 10.12.6]

### Steps to Reproduce

Commit to local
Click the push to origin

**Expected behavior:** [Push to finish loading to remote]

**Actual behavior:** [failure
![screen shot 2017-08-25 at 9 54 57 am](https://user-images.githubusercontent.com/1054677/29716989-7f67c8e4-897b-11e7-8924-e906481a701c.png)
]

**Reproduces how often:** [100%]

**Comment by iAmWillShepherd** [comment] 2017-08-25 16:07
Hi, @l0stb0y 

Sorry, you are having trouble using the app. I just need some additional info.

* Do you have a stable internet connection?
* Are you behind a proxy or company firewall?
* Is your repo hosted on GitHub?

In addition to that, could you please send along your logs or try upgrading to the latest version of the app and let me know if the problem persists?

**Comment by l0stb0y** [comment] 2017-08-25 16:27
Hi,

Thanks for the quick follow up. The app is the latest version for Mac. I didn't have the issues until I upgraded last week. 

We are :
- not behind a proxy
- have stable internet
- not behind a firewall

I'll look for the logs. The note in the big report did not list the correct path to the logs for the latest OSX

Thanks,

Bastien

**Comment by iAmWillShepherd** [comment] 2017-08-25 16:39
To get logs click **Help** -> **Show Logs in Finder**

**Comment by l0stb0y** [comment] 2017-08-28 13:12
Hi Will,


Here are some log file examples


2017-08-28T01:27:03.993Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.229s)
2017-08-28T01:27:04.157Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.033s)
2017-08-28T05:31:25.680Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.585s)
2017-08-28T10:35:40.820Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 8.923s)
2017-08-28T10:35:41.066Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/PinnacleCommunications/Natixis.git/': Resolving timed out after 3596997 milliseconds

2017-08-28T12:43:00.904Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.748s)
2017-08-28T12:49:51.698Z - info: [ui] Stats reported.




Writing objects:  79% (27306/34527), 1.99 GiB | 1.07 MiB/s
Writing objects:  79% (27337/34527), 2.00 GiB | 1.07 MiB/s
error: RPC failed; curl 55 SSLWrite() returned error -9805
fatal: The remote end hung up unexpectedly
Writing objects:  80% (27622/34527), 2.00 GiB | 1.00 MiB/s
Writing objects:  81% (27967/34527), 2.00 GiB | 1.00 MiB/s
Writing objects:  81% (28169/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  82% (28313/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  83% (28658/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  84% (29003/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  85% (29348/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  86% (29694/34527), 2.06 GiB | 13.89 MiB/s
Writing objects:  87% (30039/34527), 2.10 GiB | 22.21 MiB/s
Writing objects:  88% (30384/34527), 2.10 GiB | 22.21 MiB/s
Writing objects:  88% (30713/34527), 2.16 GiB | 34.57 MiB/s
Writing objects:  89% (30730/34527), 2.16 GiB | 34.57 MiB/s
Writing objects:  90% (31075/34527), 2.16 GiB | 34.57 MiB/s
Writing objects:  91% (31420/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  92% (31766/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  93% (32111/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  94% (32456/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  95% (32801/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  96% (33146/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  97% (33492/34527), 2.20 GiB | 44.64 MiB/s
Writing objects:  97% (33796/34527), 2.23 GiB | 49.88 MiB/s
Writing objects:  98% (33838/34527), 2.23 GiB | 49.88 MiB/s
Writing objects:  99% (34182/34527), 2.29 GiB | 62.75 MiB/s
Writing objects:  99% (34218/34527), 2.35 GiB | 76.14 MiB/s
Writing objects:  99% (34504/34527), 2.48 GiB | 110.07 MiB/s
Writing objects:  99% (34515/34527), 2.61 GiB | 115.87 MiB/s
Writing objects: 100% (34527/34527), 2.61 GiB | 115.87 MiB/s
Writing objects: 100% (34527/34527), 2.65 GiB | 1.43 MiB/s, done.
Total 34527 (delta 6681), reused 31170 (delta 6440)
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)


________________________________

**Comment by tierninho** [comment] 2017-08-28 15:46
After doing a little digging, just want to point out a few things that could be the cause as seen in the logs:

- `fatal: unable to access 'https://github.com/PinnacleCommunications/Natixis.git/': Resolving timed out after 3596997 milliseconds` equates to 59.94 minutes, meaning there might be a 1hr (3600 seconds) timeout issue set somewhere?
- `error: RPC failed; curl 55 SSLWrite() returned error -9805` looks like it has to do with capping of file sizes set by GitHub?

**Comment by shiftkey** [comment] 2017-08-28 23:23
@l0stb0y thanks for the logs, those are very helpful!

@tierninho I'm less worried about the timeout issue, but it looks like our error handling is correctly mapping the second error and serving that up to the user:

https://github.com/desktop/dugite/blob/2b947074fccd3dd9a3d41b7eb04653ad4cd6dcdc/lib/errors.ts#L49

```
error: RPC failed; curl 55 SSLWrite() returned error -9805
```

The `curl 55` part is just a generic message from libcurl (see [docs](https://curl.haxx.se/libcurl/c/libcurl-errors.html)) about failing to send the data. The `-9805` bit is probably the real valuable bit, but unfortunately [`SSLWrite`](https://developer.apple.com/documentation/security/1400864-sslwrite?language=objc) is part of macOS and the [error code](https://developer.apple.com/documentation/security/1542001-security_framework_result_codes?language=objc) listings don't provide the specific numbers. Hrm 🤔

**Comment by shiftkey** [comment] 2017-08-29 00:05
@l0stb0y one thing to try would be push the repository from the command line with tracing enabled (I'm not sure of the additional arguments to `push` which trigger this - it was trimmed in the output but should be there in the logs):

```
$ GIT_CURL_VERBOSE=1 git push [other args here?]
```

You might need to authenticate, but that should yield more information if it fails as expected. If it succeeds, then it might be something tied to the version of Git we're using, but I don't expect it to pass.

**Comment by j-f1** [comment] 2017-08-31 21:35
@shiftkey 

> The -9805 bit is probably the real valuable bit, but unfortunately SSLWrite is part of macOS and the error code listings don't provide the specific numbers.

```swift
import Security
SecCopyErrorMessageString(-9805, nil)
// => "connection closed gracefully"
```

**Comment by TLGustav** [comment] 2017-09-08 08:36
Having the exact same issue. The process gets to varying percentages of completion before giving up.

As in l0stb0ys example, we have a relatively big repository (total 2Gb) with quite a few larger binary files that we would prefer to store together with the project.

**Comment by TLGustav** [comment] 2017-09-08 13:51
Tried installing git and gitbash, same situation:

![bilde](https://user-images.githubusercontent.com/29923007/30214668-8f7b98fe-94ad-11e7-834a-531f5e0acb50.png)

**Comment by joshaber** [comment] 2017-09-13 18:35
If this is happening with git itself then it sounds like the bug lies there, instead of in GitHub Desktop. You might try contacting support to see if they have any experience debugging these sorts of issues: https://github.com/support

**Closed by joshaber** 2017-09-13 18:35 UTC
Labels: bug, needs-reproduction

**Comment by californiaimage** [comment] 2017-10-10 19:53
I have the same issue. Stable internet connection, larger repositories choke out when cloning or on first push.

**Comment by shiftkey** [comment] 2017-10-11 09:36
@californiaimage can you share a log file which contains the clone error message?

**Comment by wmassag** [comment] 2017-10-16 09:30
Same issue, same kind of error in the log, tried removing, re-adding and re-downloading to Github client, no change. Also: stable  connection, no proxy, no firewall (worked before, stopped working around Oct. 15th).

```
2017-10-16T08:41:21.764Z - info: [ui] launching: 1.0.3 (Mac OS 10.13.0)
2017-10-16T08:41:22.274Z - info: [ui] Stats reported.
2017-10-16T08:42:35.560Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 36.597s)
2017-10-16T08:42:35.562Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects:  25% (1/4)   
Compressing objects:  50% (2/4)   
Compressing objects:  75% (3/4)   
Compressing objects: 100% (4/4)   
Compressing objects: 100% (4/4), done.
Writing objects:  25% (1/4)   
Writing objects:  50% (2/4)   
Writing objects:  75% (3/4)   
Writing objects: 100% (4/4)   
Writing objects: 100% (4/4), 520 bytes | 520.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2017-10-16T08:43:17.978Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 36.558s)
2017-10-16T08:43:17.978Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects:  25% (1/4)   
Compressing objects:  50% (2/4)   
Compressing objects:  75% (3/4)   
Compressing objects: 100% (4/4)   
Compressing objects: 100% (4/4), done.
Writing objects:  25% (1/4)   
Writing objects:  50% (2/4)   
Writing objects:  75% (3/4)   
Writing objects: 100% (4/4)   
Writing objects: 100% (4/4), 520 bytes | 520.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2017-10-16T08:47:06.002Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 30.064s)
2017-10-16T08:47:06.004Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access 'https://github.com/wmassag/The-Heist.git/': Could not resolve host: github.com

2017-10-16T08:47:36.037Z - warn: [ui] getFetchPollInterval: failed for wmassag/The-Heist
TypeError: Failed to fetch
2017-10-16T08:48:43.984Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 36.582s)
2017-10-16T08:48:43.985Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects:  25% (1/4)   
Compressing objects:  50% (2/4)   
Compressing objects:  75% (3/4)   
Compressing objects: 100% (4/4)   
Compressing objects: 100% (4/4), done.
Writing objects:  25% (1/4)   
Writing objects:  50% (2/4)   
Writing objects:  75% (3/4)   
Writing objects: 100% (4/4)   
Writing objects: 100% (4/4), 520 bytes | 520.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2017-10-16T08:48:50.794Z - info: [ui] [AppStore] loading 2 repositories from store
2017-10-16T08:48:50.795Z - info: [ui] [AppStore] found account: wmassag (Wenzel Massag)
2017-10-16T08:48:51.187Z - info: [ui] launching: 1.0.4 (Mac OS 10.13.0)
2017-10-16T08:48:56.264Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: The-Heist - wmassag (has token)
2017-10-16T08:49:32.837Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 36.563s)
2017-10-16T08:49:32.838Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects:  25% (1/4)   
Compressing objects:  50% (2/4)   
Compressing objects:  75% (3/4)   
Compressing objects: 100% (4/4)   
Compressing objects: 100% (4/4), done.
Writing objects:  25% (1/4)   
Writing objects:  50% (2/4)   
Writing objects:  75% (3/4)   
Writing objects: 100% (4/4)   
Writing objects: 100% (4/4), 520 bytes | 520.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2017-10-16T08:53:13.116Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/wmassag/The-Heist.git - wmassag (has token)
2017-10-16T08:54:09.993Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/wmassag/The-Heist.git /Users/wmassag/Daten/Studium/Spiele Entwicklung/Studioprojekt 1/The-Heist (took 56.876s)
2017-10-16T08:54:09.999Z - info: [ui] [AppStore] adding repository at /Users/wmassag/Daten/Studium/Spiele Entwicklung/Studioprojekt 1/The-Heist to store
2017-10-16T08:54:13.787Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.576s)
2017-10-16T08:56:49.962Z - info: [ui] [AppStore] loading 2 repositories from store
2017-10-16T08:56:49.963Z - info: [ui] [AppStore] found account: wmassag (Wenzel Massag)
2017-10-16T08:56:50.319Z - info: [ui] launching: 1.0.4 (Mac OS 10.13.0)
2017-10-16T09:13:12.491Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.594s)
2017-10-16T09:18:36.035Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.556s)
2017-10-16T09:22:07.716Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: The-Heist - wmassag (has token)
2017-10-16T09:22:27.270Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 19.546s)
2017-10-16T09:22:27.271Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 1.
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects:  33% (1/3)   
Compressing objects:  66% (2/3)   
Compressing objects: 100% (3/3)   
Compressing objects: 100% (3/3), done.
Writing objects:  33% (1/3)   
Writing objects:  66% (2/3)   
Writing objects: 100% (3/3)   
Writing objects: 100% (3/3), 375 bytes | 375.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
2017-10-16T09:23:58.689Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 6.555s)
```

**Comment by californiaimage** [comment] 2017-10-16 20:22
5.62 GiB | 44.11 MiB/s
Writing objects: 100% (101113/101113), 5.65 GiB | 44.23 MiB/s
Writing objects: 100% (101113/101113), 5.67 GiB | 1.33 MiB/s, done.
Total 101113 (delta 565), reused 101072 (delta 524)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
error: RPC failed; curl 55 Send failure: Connection was aborted
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet
connection and try again.)
2017-10-16T17:21:27.479Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 6.552s)
2017-10-16T17:21:35.841Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 8.346s)
2017-10-16T17:26:43.028Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.092s)
2017-10-16T17:26:47.879Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.851s)
2017-10-16T17:31:54.952Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.030s)
2017-10-16T17:31:59.507Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.555s)
2017-10-16T17:37:12.773Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.881s)
2017-10-16T17:42:20.269Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.341s)
2017-10-16T17:42:25.480Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.195s)
2017-10-16T17:47:37.482Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.571s)
2017-10-16T17:52:49.727Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.805s)
2017-10-16T17:57:57.370Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.373s)
2017-10-16T17:58:02.113Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.743s)
2017-10-16T18:03:13.883Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.070s)
2017-10-16T18:08:26.007Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.101s)
2017-10-16T18:13:37.548Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.664s)
2017-10-16T18:18:44.951Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.030s)
2017-10-16T18:18:49.930Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.980s)
2017-10-16T18:23:57.295Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.357s)
2017-10-16T18:24:02.537Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.258s)
2017-10-16T18:29:10.151Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.232s)
2017-10-16T18:29:15.097Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.946s)
2017-10-16T18:34:26.611Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.774s)
2017-10-16T18:39:38.751Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.883s)
2017-10-16T18:44:50.517Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.634s)
2017-10-16T18:49:59.097Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 2.169s)
2017-10-16T18:50:04.604Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.507s)
2017-10-16T18:55:16.821Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.945s)
2017-10-16T19:00:28.728Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.883s)
2017-10-16T19:05:40.571Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.711s)
2017-10-16T19:10:52.465Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.602s)
2017-10-16T19:15:59.936Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.014s)
2017-10-16T19:16:04.683Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.747s)
2017-10-16T19:21:16.323Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.446s)
2017-10-16T19:26:27.632Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.758s)
2017-10-16T19:31:39.569Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.696s)
2017-10-16T19:36:51.597Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.773s)
2017-10-16T19:41:59.041Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.123s)
2017-10-16T19:42:03.643Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.602s)
2017-10-16T19:47:15.562Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.711s)
2017-10-16T19:52:27.342Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.534s)
2017-10-16T19:57:39.004Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.070s)
2017-10-16T20:02:50.627Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 4.723s)
2017-10-16T20:07:58.462Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.544s)
2017-10-16T20:08:04.359Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.897s)
2017-10-16T20:13:10.931Z - info: [ui] Executing fetch: git -c
credential.helper= fetch --progress --prune origin (took 1.014s)
2017-10-16T20:13:17.624Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 6.693s)
2017-10-16T20:15:03.541Z - info: [ui] Executing getBranches: git
for-each-ref
--format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F
refs/heads refs/remotes (took 2.164s)
2017-10-16T20:15:03.545Z - info: [ui] Executing getRecentBranches: git log
-g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.140s)
2017-10-16T20:15:06.364Z - info: [ui] Executing getStatus: git status
--untracked-files=all --branch --porcelain=2 -z (took 5.011s)

**Comment by dealercrm** [comment] 2017-11-01 00:04
Is there a fix for this yet?
I am running into the same issue.

Writing objects:  84% (267/317), 2.08 GiB | 14.77 MiB/s   Writing objects:  84% (267/317), 2.09 GiB | 14.63 MiB/s   Writing objects:  84% (269/317), 2.12 GiB | 16.08 MiB/s   Writing objects:  85% (270/317), 2.12 GiB | 16.08 MiB/s   Writing objects:  85% (271/317), 2.12 GiB | 16.08 MiB/s   Writing objects:  85% (272/317), 2.14 GiB | 17.93 MiB/s   Writing objects:  86% (273/317), 2.14 GiB | 17.93 MiB/s   Writing objects:  86% (273/317), 2.16 GiB | 15.04 MiB/s   Writing objects:  86% (274/317), 2.16 GiB | 15.04 MiB/s   Writing objects:  86% (275/317), 2.21 GiB | 19.76 MiB/s   Writing objects:  87% (276/317), 2.21 GiB | 19.76 MiB/s   Writing objects:  87% (278/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  88% (279/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  89% (284/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  90% (286/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  91% (289/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  92% (294/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  93% (295/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  94% (298/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  95% (302/317), 2.22 GiB | 19.56 MiB/s   Writing objects:  96% (305/317), 2.24 GiB | 20.44 MiB/s   Writing objects:  96% (307/317), 2.25 GiB | 21.31 MiB/s   Writing objects:  97% (308/317), 2.25 GiB | 21.31 MiB/s   Writing objects:  97% (310/317), 2.25 GiB | 19.43 MiB/s   Writing objects:  98% (311/317), 2.25 GiB | 19.43 MiB/s   Writing objects:  98% (311/317), 2.27 GiB | 16.14 MiB/s   Writing objects:  98% (313/317), 2.28 GiB | 14.74 MiB/s   Writing objects:  99% (314/317), 2.28 GiB | 14.74 MiB/s   Writing objects: 100% (317/317), 2.28 GiB | 14.74 MiB/s   Writing objects: 100% (317/317), 2.31 GiB | 5.34 MiB/s, done.
Total 317 (delta 24), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
**error: RPC failed; curl 55 Send failure: Connection was aborted**
Everything up-to-date

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)

**Comment by niik** [comment] 2017-11-01 12:29
As has been said earlier in this thread we don't believe this issue is related to GitHub Desktop. **There is a hard limit of 2GB for pushes to GitHub.com** which is enforced server-side and I suspect that's what most of you are hitting here. Additionally [there's a soft limit](https://help.github.com/articles/what-is-my-disk-quota/) or recommendation of keeping your repositories under 1Gb.

You can try breaking up your pushes into smaller chunks by pushing a subset of your commits but a better solution would be to use [Git Large File Storage](https://help.github.com/articles/about-git-large-file-storage/) which is designed to support these scenarios. See also [Working With Large Files](https://help.github.com/articles/working-with-large-files/) in our help documentation.

For people having problems pushing repositories well under the 2GB limit we recommend you contact our support team at [github.com/support](https://github.com/support) as they can help you debug any network interference that may be present in between you and our data centers.

> We've experimented with reducing the upload size (just temporarily moving big files out), but no luck.

Note that due to the way Git stores files in perpetuity it's not straightforward to reduce the size of a repository. Have a look at some of the tooling that's available such as [BFG](https://rtyley.github.io/bfg-repo-cleaner/) but be aware that rewriting your repository should be done with utmost care and caution and with backups readily available.

**Comment by TLGustav** [comment] 2017-11-01 16:49
Thanks for clearing up Markus.

I "knew" this, but I wanted to ask because I considered this answer so
unlikely.

I hate to state the obvious, but if you develop on media projects, 2Gb+ is
standard, and binary files are a natural part of your IDE workflow.

With regards to Git not supporting 2GB, that leaves the following options
for projects like this:

a) Git + another overlapping sync/cloud solution (high maintenance and
messy - not happening)
b) No versioning (nope - need that versioning)
c) Another versioning software.

a) and b) are out of the question. Thus c) is the only viable option.

As a paying customer hoping to go full Git, I'm disappointed (and a bit
shocked) that Git doesn't support big projects out of the box, and I'm very
annoyed that Git deals with the problem by just running for hours before
crashing with an ambiguous message.
This is pretty much the worst case scenario in terms of wasting users'
time, and also contributes to the confusion of thinking "I can get this to
work.. right?".

It's now almost two months since I wrote about this.



*Gustav C. Tresselt*
TenkLabs AS
+47 98447222

**Comment by j-f1** [comment] 2017-11-01 17:46
@TLGustav Have you tried [Git LFS](https://git-lfs.github.com/)? It’s designed for tracking changes to large binary files. There’s even a [`git lfs migrate` command](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn) that will rewrite your history to use LFS, significantly decreasing your repo’s size. You get 1 GB for free, and you can [upgrade](https://github.com/account/billing/data/upgrade) to get 50GB for $5/month.

**Comment by TLGustav** [comment] 2017-11-01 19:12
I seem to remember giving it a spin back then, don't remember what made me
drop it, but it does seem like something that should be an integral part of
Git.

I will try LFS again when we are ready to test out Git again. Thanks for
the input.

*Gustav C. Tresselt*
TenkLabs AS
+47 98447222

**Comment by HitEmUp** [comment] 2018-01-30 01:13
Still now news here? Have the crash as well and thougt i can fix this, but its not a bug, its a missing message... Hope they go with the time and upgrade the limit to something usable.

**Comment by glenndevenish** [comment] 2018-02-13 07:19
Temporary fix: upload the files with `https://github.com/[username]/[repo]/upload/[branch]`. It works for me with several binary pngs that needed uploading.

**Comment by cilmon** [comment] 2018-02-13 17:01
I had the same problem and I think it is related to the files size of your repository.
I fixed the problem by running this on console in your git's folder:

git config http.postBuffer 524288000

I hope it can help you

**Comment by corsair** [comment] 2022-09-02 11:16
> I had the same problem and I think it is related to the files size of your repository. I fixed the problem by running this on console in your git's folder:
> 
> git config http.postBuffer 524288000
> 
> I hope it can help you

It's been quite a few years since this was reported, but I ran into this same issue trying to push changes to a repo hosted on Github.com. Using that command seemingly resolved the issue for me.

**Comment by Suavevillain** [comment] 2023-05-22 20:26
> > I had the same problem and I think it is related to the files size of your repository. I fixed the problem by running this on console in your git's folder:
> > git config http.postBuffer 524288000
> > I hope it can help you
> 
> It's been quite a few years since this was reported, but I ran into this same issue trying to push changes to a repo hosted on Github.com. Using that command seemingly resolved the issue for me.

This worked for me. Thank you.

**Comment by datasciencesystems** [comment] 2023-06-11 01:52
I have the same problem. The above recommended solution did not work for me
