### ISSUE TITLE
Focusing github desktop jumps to top of git history and loses focus of selected old issue

### ISSUE THREAD

**Issue by mastef** [desktop/desktop#5470] opened 2018-08-25 12:07 UTC
## Description
While going through a git repositories' historical changes, refocusing github desktop will scroll up to the first history page. This is annoying when you're trying to summarize older changes, or are comparing them with code in another window.

Ideally when focusing github desktop, the "History" list should stay where it is, and not jump to the first page again. It should also not lose focus of a selected issue that's older than the issues on the first page.

## Version
* GitHub Desktop: Latest, 1.3.4
* Operating system: Mac

## Steps to Reproduce
1. Scroll through a github's history that has more than 50-100 commits
2. Select an old issue from below
3. Now switch to any other window - e.g. Chrome, or an editor
4. Switch back to Github Desktop

### Expected Behavior
4. The selected issue in 2. should still be selected. The history list should still be where it was when tabbing away from the window

### Actual Behavior
4. The history list jumps up to the first page. The selected issue is the latest commit in the history

## Additional Information
Please note : This doesn't happen for the first 100 or so recent changes in the git history. It starts happening somewhere after 100 or 200 issues.

GIF of the behaviour : 
![output](https://user-images.githubusercontent.com/762297/44618107-fe04f300-a899-11e8-9d31-567113331c42.gif)

**Comment by outofambit** [comment] 2018-08-25 21:41
@mastef thanks for filing this! The steps to reproduce this are very clear so I'm gonna mark this for verification (and as a bug). Is the repo in the gif https://github.com/openfl/openfl ?

**Comment by aryyya** [comment] 2018-08-27 04:40
I can reproduce this.

Whenever selecting a commit in the history past the first 100, unfocusing and refocusing the window, the view jumps back up to the end of the first loaded batch of commits, and the commit that was previously selected is no longer selected.

It seems to be related to `CommitBatchSize` in `git-store.js`:

https://github.com/desktop/desktop/blob/cf8f2fcc54cab00ca749028f6c5ae01ada7cedc0/app/src/lib/stores/git-store.ts#L74

I tried changing this value to `1000`. The bug still persists, but the behavior occurs when selecting a commit past the first 1000 instead of the first 100.

I don't fully understand this part of the code base, but I think that something like `commitsToGet = () => commitBatchSize * commitBatchesLoaded`, where `commitBatchSize` is `100` and `commitBatchesLoaded` is a count of how many batches have already been loaded up to this point, then use that as the `--max-count` argument to `git()` whenever loading local commits from the log (where `CommitBatchSize` is used in `git-log.js`).

**Comment by mastef** [comment] 2018-08-27 06:16
@outofambit I think so - the repo doesn't matter in any case. Any git repo that has more than 100 commits should do

@aryyya Nice investigation! I can see why having a repo refresh on re-focus would make sense. Maybe only refreshing the repo if a "first page issue" is selected would be better. Or not refreshing if the list is in a scrolled state.

**Comment by tierninho** [comment] 2018-09-18 22:59
Verifying this bug is reproducible and the described steps are accurate.

Perhaps we can squash this Issue too with the fix? https://github.com/desktop/desktop/issues/5177 as the underlying fix is "remember when I left off".

**Comment by outofambit** [comment] 2018-10-12 17:54
#5875 ensured that the commit list was not reloaded, but doesn't address the scroll position

**Comment by shiftkey** [comment] 2018-10-13 12:32
I'm going to close this out because https://github.com/desktop/desktop/pull/5875#issuecomment-429465211 suggests what was being seen is already tracked in #5177.

**Closed by shiftkey** 2018-10-13 12:32 UTC
Labels: bug, priority-3
