### ISSUE TITLE
Dragging maximized caption snaps back to top on release

### ISSUE THREAD

**Issue by smoorke** [desktop/desktop#17905] opened 2023-12-23 15:35 UTC
### The problem

Dragging maximized caption snaps back to top on release of mousebutton

### Release version

3.3.6 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Maximize GitHub
2. Drag Caption
3. Release Left Mouse Button
4. Window Snaps back to Top in a normal state

**Comment by smoorke** [comment] 2023-12-23 15:38
just noticed if you stop the drag on a different screen it snaps back to the top of original screen

**Comment by tidy-dev** [comment] 2023-12-25 15:14
@smoorke Thank you for the report. I believe this is a duplicate of #15624. I am going to close this in favor of tracking it there.

**Closed as completed by tidy-dev** 2023-12-25 15:14 UTC
