### ISSUE TITLE
Authentication Failed - not saving my new token permanently

### ISSUE THREAD

**Issue by nunoperalta** [desktop/desktop#9579] opened 2020-04-20 20:43 UTC
### Describe the bug

I use self-hosted Gitea ( go-gitea/gitea ) as my git host.
I have several repositories (all in the same host) added to GitHub Desktop.

GitHub Desktop has been working perfectly for me so far, while I was using a pure Username and Password (the same I use to log into Gitea).

As I have recently enabled 2FA, I have created a Token so that I can authenticate through Desktop.

When pushing to the repositories, as expected, the authentication failed and I have input my Username and the Token. The push succeeds.
I've done this for a few other repositories where I had to push commits to.

However, countless times, for repositories that I had corrected the password already, I keep being asked for the password ("Authentication Failed"). It doesn't always fail, but at least once I day, I guess this error.
Fetching the repos don't have this problem.

How can I **permanently** change the password/token for all repositories, and why is GitHub Desktop not doing that for me?

### Version & OS

Version 2.4.2-beta1
Windows 10 Pro

### Expected behavior

When "Authentication Failed" and I input the new Password/Token for the account, it should be saved permanently.
Ideally, replace all occurrences of the previous password cached for all repos, but at least should not ask me anymore for this repo I've just changed.

### Actual behavior

I keep getting the "Authentication Failed" when I push new commits later (not always, but frequently).

### Screenshots

![image](https://user-images.githubusercontent.com/487079/79794448-2cc2bd80-834a-11ea-903c-895916bb6b59.png)

### Logs

I see I'm getting loads of these, even for those repos I'm not actively committing to:

> 2020-04-20T20:15:54.202Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
> stderr:
> remote: Users with two-factor authentication enabled cannot perform HTTP/HTTPS operations via plain username and password. Please create and use a personal access token on the user settings page
> fatal: Authentication failed for 'XXXXXXXXXXXXXXXXXXXXXXX'
> 
> (The error was parsed as 3: Authentication failed. Some common reasons include:
> 
> - You are not logged in to your account: see File > Options.
> - You may need to log out and log back in to refresh your token.
> - You do not have permission to access this repository.
> - The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
> - If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

(probably related to the auto-fetching, even though I'm not getting the "Authentication Failed" popups)

***NOTE*** - I cannot really "log out" and "log back in" under Options, as this is not a GitHub account. It's a self-hosted Gitea account.
I am currently logged into GitHub in there (same username, by the way), but that account isn't used for any of the repositories.

There is no place in Options where I can manage my login to a host other than GitHub.

**Comment by rafeca** [comment] 2020-04-21 10:06
Thanks for filing this issue @nunoperalta ! GitHub Desktop stores the git credentials on the operating system keychain. On Windows, this is the Credential Manager.

Normally, Desktop should override the stored password with the new one you supply via the authentication failed dialog, I wonder why is this not working for you...

Can you try opening the Credential Manager app and look for "Generic Credentials" that start with "GitHub Desktop" and check that the URLs that appear there match the ones that you see on the authentication failed dialog?

![image](https://user-images.githubusercontent.com/408035/79852879-91702d80-83c7-11ea-8fc7-a84c37d34665.png)

(deleting the Desktop entries from the Credentials Manager willprobably fix the issue, but I'd like to know why they are not getting updated because there may be an underlying issue).

**Comment by nunoperalta** [comment] 2020-04-21 21:21
Update:

1) I see that the "mydomain.com" credential is actually used by Visual Studio Code (it just asked me for that token, after I removed it from the Credentials Manager).
The "mydomain.com/user1" format is used by GitHub Desktop.

2) Since I removed all the credentials and re-added through "Authentication Failed", I'm not getting this problem anymore.

So, the problem seems to be that GitHub Desktop adds the credentials, but does not update them.

**Comment by rafeca** [comment] 2020-04-22 08:58
Thanks for digging into this @nunoperalta ! That was very helpful!

I haven't been able to reproduce the issue with a bitbucket repository (the behaviour should be the same as with a Gitea repo).

I've done the following:

1. Clone a bitbucket repository with the correct user/password info.
2. Go to the credentials manager and manually change the password, entering an incorrect one.
3. Go back to Desktop and try to push.
4. When I see the modal, enter the correct user/password.
5. The credentials manager gets updated since from that point I don't need to enter user/password again to push.

Since your credentials were created in November with an older Desktop version my current hypothesis is that these credentials were created in a way that they cannot get modified with the current version.

We use the `keytar` npm package to interact with the credentials manager service, and we recently upgraded to v5, I wonder if that could have caused the issues.

**Comment by rafeca** [comment] 2020-04-22 09:12
@nunoperalta ok, I'm pretty sure that the issue you experienced is caused by https://github.com/atom/node-keytar/issues/259, thanks again for your detailed information ✨ 

You can confirm that things work fine now that you have the credentials created with the latest Desktop version by trying the repro steps in https://github.com/desktop/desktop/issues/9579#issuecomment-617648428 .

I'm going to close this issue but if you still experience issues when testing https://github.com/desktop/desktop/issues/9579#issuecomment-617648428 please reopen it!

If we see more people stumbling across this problem we can add it in the [known issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md).

**Comment by nunoperalta** [comment] 2020-10-24 16:59
@rafeca -- This exact issue is now happening on my work environment, where we use Azure DevOps (instead of Gitea which is what I was reported on this thread).

The credentials expired now (after 1 year), and I keep getting these popups very frequently, like if GitHub Desktop cannot remember that I've already inserted the NEW token... This happens for both Pulls and Pushes.
It works well for a few minutes/hours, but then it will ask for the token again. It's just so annoying!

![image](https://user-images.githubusercontent.com/487079/97087467-6a1e4580-1622-11eb-84ce-f3d75e7bb7e8.png)


Not only that, I have 20+ repositories, and they ALL use the same username + token.
For ALL of them, I have to keep constantly copying the token to paste into the popup. That's because the credentials are per repository, rather than re-using for the same username/token pair. I understand this might not be easy to handle (as different repos could have different usernames/tokens), but it would be nice to somehow try to re-use.

![image](https://user-images.githubusercontent.com/487079/97087497-92a63f80-1622-11eb-8464-4392200f0c08.png)

**Comment by steveward** [comment] 2022-01-13 15:09
Going to close this out in favor of #13537, which is a more recent report. @nunoperalta let us know if you are still having this issue.

**Closed by steveward** 2022-01-13 15:09 UTC

**Comment by nunoperalta** [comment] 2022-01-13 15:33
> Going to close this out in favor of #13537, which is a more recent report. @nunoperalta let us know if you are still having this issue.

No problem. Not sure if I have recently attempted to update my tokens, but I'll let you know if I struggle with this again in the future.
Thanks!
