### ISSUE TITLE
Add GIT Version information to Help -> About  Githubt Desktop 

### ISSUE THREAD

**Issue by asjones987** [desktop/desktop#6834] opened 2019-02-12 20:43 UTC
It would be helpful in debugging if menu item Help -> About GitHub Desktop window had a section or a button that also said what version of GIT the desktop was using (and maybe the path).

On Windows I have noticed over time that I have multiple GIT.EXE files (all under the GitHub Desktop folder) not sure how it happened. In searching for information related i noticed several people wanted to know the GIT version and/or related paths.  A button with this extra information could be helpful to many people.

**Comment by shiftkey** [comment] 2019-02-12 20:51
@asjones987 thanks for the feedback!

The Git that is embedded in Desktop is not designed to be called from the command line, and I'm hesitant to put this context into the app because it shouldn't matter.

> It would be helpful in debugging if menu item Help

Can you elaborate on this? We aim to be running a recent version of Git (`2.19.2` was our last update in #6270, but `2.20.1` is available to update) and I'm not sure why this important to users to surface.

> On Windows I have noticed over time that I have multiple GIT.EXE files (all under the GitHub Desktop folder) not sure how it happened

This can sometimes happen as part of an update, but it shouldn't hang around for long. After an update the previous version of the app is kept around (just in case something went wrong) but it should eventually be cleaned up.

**Comment by asjones987** [comment] 2019-02-13 02:01
There were two parts to my request. The first part just for better clarification documenting what version of GIT came with an install thus  Help -> About GitHub Desktop. listing. I am one that likes to see the details and noticed in some searches others had also asked.

I think you clarified the 2nd on why i saw more than one instancee.

In digging again it looks like in my case I have 4 instances of GIT.exe on set in the app-1.6.1 folder (\cmd\ 
and \mingw64\bin) and the other set in 1.6.0 (same sub folders).

thanks for the help and clarification.

**Comment by shiftkey** [comment] 2019-02-13 11:13
> I am one that likes to see the details and noticed in some searches others had also asked.

Can you link to some issues for reference? I'm trying to find older discussions about this but it's a tricky phrase to search for.

> In digging again it looks like in my case I have 4 instances of GIT.exe on set in the app-1.6.1 folder (\cmd\ and \mingw64\bin) and the other set in 1.6.0 (same sub folders).

This is an artifact of how Git for Windows is packaged and distributed (the `cmd/git.exe` is the entry point to the rest of the Git distribution). But I'm also glad that you've only got two installs of the app, which is the expected behaviour.

**Comment by asjones987** [comment] 2019-02-13 19:29
Here were a few references.... they may not apply to what you where truly after but...

https://stackoverflow.com/questions/34565238/where-does-github-desktop-install-command-line-version-of-git

https://stackoverflow.com/questions/11928561/where-is-git-exe-located
(referenced GitHub desktop in the middle)

https://github.com/desktop/desktop/issues/2408

I think there was another stackoverflow or Quora page, but don't see it just yet.

**Comment by shiftkey** [comment] 2019-02-13 20:36
@asjones987 thanks for the links.

Those all seem to be about wanting to use the version of Git which is distributed within GitHub Desktop, which is not supported and something we actively discourage. We had the exact same problem with the classic GitHub for Windows application where users would use the version of Git inside the app, and after we deliver an update (which changes the path on disk) their usage would break.

Instead I want to refer people to the [Git for Windows](https://gitforwindows.org/) project if you need to use a command line version of Git.

**Comment by shiftkey** [comment] 2019-02-13 20:54
I'm going to close this out as "by design" because the embedded Git is supposed to be internal to Desktop and is subject to change between updates, and any external usage is not supported.

**Closed by shiftkey** 2019-02-13 20:54 UTC
Labels: more-information-needed
