### ISSUE TITLE
Cannot use "Pull Origin" in Desktop after change made from GitHub web UI

### ISSUE THREAD

**Issue by Move2win** [desktop/desktop#15301] opened 2022-09-17 07:02 UTC
### The problem

Degree of the problem: critical
Reproducibility: always
Repo related to this issue: https://github.com/Move2win/FS22_ModManagerCore
File related to this issue: https://github.com/Move2win/FS22_ModManagerCore/blob/main/README.md

I made a change for README.md using GitHub web UI. After that change has been committed, I cannot sync that change to my local PC repo using GitHub Desktop by clicking the "Pull Origin" button.
I cannot commit any change made on my local PC to GitHub either, as the last commit (README.md, the one that cannot be synced) didn't on my local repo yet.

I got this message from Desktop:
```
Error
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve
```

To recover from this issue, I have to remove my local PC repo, which means **all uncommitted changes on my local will be lost**. Then, re-clone the same repo from GitHub, which successfully syncs that "un-sycnable" change.

As this issue is up, I cannot change any file using the GitHub web UI as it can cause that "unable to pull origin" problem.

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 10 Pro 21H2/19044.1889

### Steps to reproduce the behavior

1. Clone a GitHub repo on a local PC using the Desktop app.
2. Use GitHub web page UI to make any change to a README.md file in that repo and commit that change using the web page.
3. Open the Desktop and "Fetch origin."
4. Click the blue "Pull Origin" button after fetch.
5. Got error message:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

### Log files

2022-09-16T09:55:03.384Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T09:55:03.696Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-16T09:55:03.697Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-16T09:55:03.984Z - info: [ui] launching: 3.0.7 (Windows 10.0.19044)
2022-09-16T09:55:03.984Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.7\GitHubDesktop.exe'
2022-09-16T09:55:04.058Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:55:04.096Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:55:04.655Z - info: [ui] Subscribed 'Move2win' to Alive channel
2022-09-16T09:55:12.187Z - info: [main] opening in browser: https://desktop.github.com/release-notes/
2022-09-16T09:55:23.080Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:55:23.931Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.044s)
2022-09-16T09:55:27.154Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:55:46.651Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:56:17.389Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:56:19.017Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:56:36.485Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:56:50.501Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:57:09.018Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:57:21.022Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T09:57:25.487Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 2.8s of which 0.0s paused, total 2.8s
2022-09-16T10:01:57.866Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:02:07.571Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:02:29.842Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:02:44.218Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:02:45.900Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:02:59.653Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T10:07:47.734Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:07:49.419Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T10:07:49.718Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-16T10:07:49.718Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-16T10:07:49.733Z - info: [ui] [BranchPruner] Last prune took place 13 minutes ago - skipping
2022-09-16T10:07:49.852Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-16T10:07:49.854Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-16T10:07:50.075Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:07:50.114Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:07:50.623Z - info: [ui] Subscribed 'Move2win' to Alive channel
2022-09-16T10:08:16.951Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T10:08:17.244Z - info: [ui] Subscribed 'Move2win' to Alive channel
2022-09-16T10:08:17.248Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-16T10:08:17.249Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-16T10:08:17.264Z - info: [ui] [BranchPruner] Last prune took place 13 minutes ago - skipping
2022-09-16T10:08:17.388Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-16T10:08:17.390Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-16T10:08:17.649Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:08:17.670Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:08:20.611Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:08:46.982Z - info: [ui] Unubscribed 'Move2win' from Alive channel
2022-09-16T10:09:14.863Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T10:09:21.796Z - info: [main] opening in browser: https://desktop.github.com/beta
2022-09-16T10:10:54.042Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:31:53.950Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T16:31:54.320Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-16T16:31:54.320Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-16T16:31:54.389Z - info: [ui] [BranchPruner] Last prune took place 7 hours ago - skipping
2022-09-16T16:31:54.660Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-16T16:31:54.661Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-16T16:31:54.728Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:31:54.752Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:32:01.464Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:32:01.515Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:32:19.844Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 7 repositories took 2.6s of which 0.0s paused, total 2.6s
2022-09-16T16:32:59.661Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:33:27.275Z - info: [ui] [Timing] Action 'create commit' for 'Move2win/FS22_ModManagerCore' took 0.311s
2022-09-16T16:33:27.506Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:33:30.175Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:33:32.183Z - info: [ui] Executing push: git -c credential.helper= push origin main:main --progress (took 2.005s)
2022-09-16T16:33:33.191Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.007s)
2022-09-16T16:33:34.769Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:39.345Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-16T16:47:39.647Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-16T16:47:39.647Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-16T16:47:39.661Z - info: [ui] [BranchPruner] Last prune took place 16 minutes ago - skipping
2022-09-16T16:47:39.773Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-16T16:47:39.776Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-16T16:47:39.973Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:39.996Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:42.534Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:47:43.996Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.458s)
2022-09-16T16:47:45.252Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:46.622Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:47:46.757Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-16T16:47:47.924Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:49.807Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:47:49.932Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-16T16:47:51.110Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:47:55.275Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:47:55.403Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-16T16:47:56.604Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-16T16:48:09.062Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-16T16:48:09.188Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-16T16:48:10.363Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:19.938Z - info: [main] Using toast activator CLSID {XXXXX}
2022-09-17T06:19:20.251Z - info: [ui] [AppStore] loading 7 repositories from store
2022-09-17T06:19:20.251Z - info: [ui] [AppStore] found account: Move2win (Zero-Point-Three Mach)
2022-09-17T06:19:20.266Z - info: [ui] [BranchPruner] Last prune took place 14 hours ago - skipping
2022-09-17T06:19:20.370Z - info: [ui] launching: 3.0.8 (Windows 10.0.19044)
2022-09-17T06:19:20.371Z - info: [ui] execPath: 'C:\Users\UserName\AppData\Local\GitHubDesktop\app-3.0.8\GitHubDesktop.exe'
2022-09-17T06:19:21.121Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:21.133Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:21.408Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.044s)
2022-09-17T06:19:23.062Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:19:23.193Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:19:24.314Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.120s)
2022-09-17T06:19:24.527Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:30.208Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:19:30.334Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:19:31.491Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:37.856Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.011s)
2022-09-17T06:19:39.573Z - info: [ui] Executing updateRemoteHEAD: git -c credential.helper= remote set-head -a origin (took 1.717s)
2022-09-17T06:19:39.863Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:42.619Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:19:48.475Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:19:48.613Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:19:49.811Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:20:02.918Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:20:03.841Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:20:03.973Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:20:05.158Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:20:49.797Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:21:14.541Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:21:15.613Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:21:15.749Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:21:17.314Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:21:22.965Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:21:39.749Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 2.9s of which 0.0s paused, total 2.9s
2022-09-17T06:21:49.159Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:06.162Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:10.463Z - info: [ui] [Timing] Action 'create commit' for 'Move2win/FS22_ModManagerCore' took 0.298s
2022-09-17T06:22:10.634Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:12.119Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:22:12.295Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:22:13.512Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:15.459Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:22:15.588Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:22:16.742Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:18.541Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:22:18.669Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:22:20.197Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:36.674Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:22:52.206Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-09-17T06:22:52.507Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:23:45.575Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:23:47.600Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:23:47.733Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:23:49.288Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:23:50.217Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:24:22.823Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:24:23.504Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:24:23.638Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:24:24.820Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:24:26.735Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:24:26.863Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:24:28.038Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:24:53.714Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:26:22.357Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:01.607Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:02.892Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:03.699Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.027s)
2022-09-17T06:27:04.936Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:43.518Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Move2win/FS22_ModManagerCore.git - Move2win (has token)
2022-09-17T06:27:46.591Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Move2win/FS22_ModManagerCore.git C:\Users\UserName\Desktop\Project\FS22_ModManagerCore (took 3.071s)
2022-09-17T06:27:46.641Z - info: [ui] [AppStore] adding repository at C:\Users\Username\Desktop\Project\FS22_ModManagerCore to store
2022-09-17T06:27:46.681Z - info: [ui] [BranchPruner] Last prune took place 44 seconds ago - skipping
2022-09-17T06:27:46.856Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:47.218Z - info: [ui] [BranchPruner] Last prune took place 14 hours ago - skipping
2022-09-17T06:27:47.448Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:47.490Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:27:49.361Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:27:50.378Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.014s)
2022-09-17T06:27:51.965Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:28:18.930Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:28:20.208Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:28:21.573Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.361s)
2022-09-17T06:28:22.829Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:28:24.064Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:28:24.204Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:28:25.389Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:28:37.976Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:30:09.201Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:30:23.678Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:30:25.254Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:30:25.390Z - error: [ui] `git -c credential.helper= -c rebase.backend=merge pull --ff --progress origin` exited with an unexpected code: 128.
stderr:
error: preserve: 'preserve' superseded by 'merges'
fatal: Invalid value for pull.rebase: preserve

2022-09-17T06:30:26.958Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:30:54.232Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:30:59.917Z - info: [ui] [BranchPruner] Last prune took place 4 minutes ago - skipping
2022-09-17T06:31:00.107Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:19.770Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:39.833Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/Move2win/FS22_ModManagerCore.git - Move2win (has token)
2022-09-17T06:31:42.481Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- https://github.com/Move2win/FS22_ModManagerCore.git C:\Users\UserName\Desktop\Project\FS22_ModManagerCore (took 2.638s)
2022-09-17T06:31:42.531Z - info: [ui] [AppStore] adding repository at C:\Users\UserName\Desktop\Project\FS22_ModManagerCore to store
2022-09-17T06:31:42.573Z - info: [ui] [BranchPruner] Last prune took place 5 minutes ago - skipping
2022-09-17T06:31:42.778Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:43.166Z - info: [ui] [BranchPruner] Last prune took place 14 hours ago - skipping
2022-09-17T06:31:43.399Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:43.416Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:44.342Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: FS22_ModManagerCore - Move2win (has token)
2022-09-17T06:31:47.019Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:31:56.515Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:32:00.525Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:32:09.092Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:48:51.413Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:49:02.204Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:49:03.492Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 7 repositories took 3.0s of which 9.3s paused, total 12.3s
2022-09-17T06:52:18.390Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:52:30.277Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:55:01.450Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:56:30.490Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:56:35.358Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'
2022-09-17T06:56:41.585Z - warn: [ui] Unexpected value found for pull.rebase in config: 'preserve'

### Screenshots

![屏幕截图(903)](https://user-images.githubusercontent.com/45490638/190844926-8f631bb9-a4c0-49fd-8144-62807c0e3d5b.png)

**Comment by niik** [comment] 2022-09-19 09:21
Hey @Move2win, thanks for reaching out and sorry to hear you're having problems using GitHub Desktop.

The error message you're seeing is coming directly from Git and is letting you know that you have a Git configuration variable (`pull.rebase`) set to an invalid value (`preserve`). This particular configuration variable isn't something that GitHub Desktop ever sets so I have to assume that it was set by the command line or by some other tool in the past.

This also explains why deleting the repository and re-cloning it solved your issue. If you encounter this problem with any of your other repositories you can fix this without deleting and re-cloning by running `git config pull.rebase merges` in the repository which is experiencing the problem (or by manually editing the `.git/config` file in your editor).

Without more detail it's impossible to say but it's also possible that you've got this faulty configuration value set in your global Git config (in the .gitconfig file in your home directory). You can run `git config -l --show-origin` to inspect your Git config and if it is set in your global config you can update it by running `git config --global pull.rebase merges`.

Hope that helps! I'm going to close this out as the problem is due to the local environment and not Desktop itself.

**Closed as completed by niik** 2022-09-19 09:21 UTC

**Comment by Move2win** [comment] 2022-09-19 09:36
@niik Thank you, help a lot. It turns out that Visual Studio options set the pull.rebase as "preserve," I have changed it back to merge, and it works fine. Again, thank you.
