### ISSUE TITLE
in the form of folder tree

### ISSUE THREAD

**Issue by syxcools** [desktop/desktop#8626] opened 2019-11-13 07:07 UTC
Now the way to submit is file list. I want to use file tree to submit. Because, I have a large number of project files, and there will be many changes, dozens or even hundreds of them in one submission.

For example: the options in source tree are flat list and tree view (in the form of folder tree)

I can submit changes in a folder at once, which I think is a very useful function. Because many of our functions are based on folders to divide source files.
I mentioned this document last time, but I feel you have misunderstood it, so I'd like to mention it again this time.

Vscode's git function was originally just a file list mode, but now it also supports the folder view mode
There are several pictures you can take a look at (if the uploaded pictures are not successful)
GitHub
http://www.syxcools.com/0.png
http://www.syxcools.com/1.png
Sourcetree
http://www.syxcools.com/2.png
http://www.syxcools.com/3.png
Vscode
http://www.syxcools.com/4.png
http://www.syxcools.com/5.png

Of course, Xcode comes with it, and it also supports the way of folders.
Sourcetree is very useful, but if the project is relatively large, the number of files is relatively large, there are many bugs, and the software efficiency is not as good as GitHub

**Comment by tierninho** [comment] 2019-11-13 19:25
@syxcools To clarify, you are asking for Desktop to support file tree to submit files? We are tracking this in https://github.com/desktop/desktop/issues/1634. Is this what you are referring to?

**Comment by kuychaco** [comment] 2019-11-13 22:45
Thanks for the feedback @syxcools. I _believe_ this is a duplicate of #2417 so I'm going to close this out so that we can keep #2417 as the main tracking issue on this topic. Your feedback will now be tied to that issue. If you would like to elaborate further please comment over there.

**Closed by kuychaco** 2019-11-13 22:45 UTC
Labels: more-info-needed
