### ISSUE TITLE
Purge Old Installers

### ISSUE THREAD

**Issue by hl2guide** [desktop/desktop#11745] opened 2021-03-09 02:10 UTC
### Describe the bug

Old installers are not appropriately purged.

### Version & OS

Windows 10, latest stable version of GitHub Desktop.

### Expected behavior

Old installers are automatically purged, respecting the user's disk space.

### Actual behavior

Old installers pile up taking up space.

(For me the **SquirrelTemp** folder is taking up 1.72GB. e.g. C:\Users\Dean\AppData\Local\SquirrelTemp)

**Comment by sergiou87** [comment] 2021-03-09 08:33
Hello @hl2guide! I'm sorry about this issue…

According to the authors of Squirrel (the tool we use to create the installer) in https://github.com/Squirrel/Squirrel.Windows/issues/1195 and https://github.com/Squirrel/Squirrel.Windows/issues/577, that folder should clean itself except, maybe, if you had many failed installations.

Since this seems to be the expected behavior of that tool, and you can safely delete that folder entirely, I'm gonna close this issue, sorry 😅

**Closed as completed by sergiou87** 2021-03-09 08:33 UTC

**Comment by hl2guide** [comment] 2021-05-07 08:11
Continues to be an issue. About 5GB of wasted space on C Drive and 5GB of internet usage per month.

Is there any way I can just disable auto updates for GitHub Desktop?

Please bolster your product.

**Comment by Whathecode** [comment] 2021-10-26 10:08
@sergiou87 It may be expected behavior when the installation fails, but the question remains why Squirrel then should believe _all_ of the GitHub desktop installations/upgrades should have failed.

![image](https://user-images.githubusercontent.com/778006/138857373-3fed6135-c21b-4f3b-8105-abcae5eaac70.png)


[My folder was 13 GB](https://github.com/Squirrel/Squirrel.Windows/issues/1195#issuecomment-939125106), and I don't recall the installer ever _visually_ failing. And, I've always been happy with the new rolled out changes in updates, which definitely did not fail to install.

I suggest to reopen this issue.

**Comment by dheijl** [comment] 2022-03-25 18:46
It has nothing to do with failed installations. When an update is pending but you close Github Desktop before the update prompt appears and you install the update, this causes a "lost" Squirreltemp tempx folder to be left.
And each time you restart Github desktop afterwards you are treated to a brand new tempx folder instance until you finally install the update, but this deletes only the last tempx folder used by the install, leaving all the rest.
Have you considered using a decent installer like InnoSetup? It seems good enough for VSCode.
