### ISSUE TITLE
LFS dialogue appears on wrong repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6444] opened 2018-12-17 23:45 UTC
After pushing a LFS commit, the dialogue that ultimately appears and says it was too big, will even appear while interacting with another repo with no reference to the original repo.

Reproduce:
- Push up a LFS file
- Switch repos and wait it out, about 3 minutes
- Error dialogue message appears and is too generic

<img width="991" alt="screen shot 2018-12-17 at 3 41 02 pm" src="https://user-images.githubusercontent.com/14828183/50122614-401fbf00-0212-11e9-91ed-0f4ef981c90b.png">

https://github.com/desktop/desktop/blob/development/app/src/lib/git/core.ts#L238

Perhaps we can reference the original repo in the message? "The push operation in `XXXXX` repository includes..." ?

1.5.1-beta5, mac

**Comment by billygriffin** [comment] 2018-12-18 00:39
@tierninho Thanks for calling this out, and agreed that any error message or warning should be repo-specific. I think I'm not quite clear on your use of "LFS" here. When you say "push up an LFS file" is the repro step to "push up a file > 100MB"? Or are you saying to push up a file that's being tracked in Git LFS?

Also, is this impacted at all by https://github.com/desktop/desktop/pull/6013 from @Daniel-McCarthy?

**Comment by Daniel-McCarthy** [comment] 2018-12-18 04:15
@billygriffin 
My understanding is that the reproduction steps for "Push up a LFS file" would be to create a commit that includes a >100 MB file that is not tracked by Git LFS, then attempt to push that commit.

This would result in that error dialog as shown in the screenshot for this Issue.
___
Regarding whether or not this relates to #6013, it should not.
#6013 displays a dialog that allows the user to cancel or commit anyways. If the user chooses to commit anyways without setting up Git LFS, they will still run into the error dialog as shown above like they normally would.

The changes in #6013 don't effect the error that displays when a commit that contains an oversized & un-tracked file is being pushed. It relates to the creation of a commit that contains an oversized file, but does not change anything regarding pushing such a commit once it has been created.

**Comment by tierninho** [comment] 2018-12-18 15:04
@billygriffin That would be correct ⬇️ 

> My understanding is that the reproduction steps for "Push up a LFS file" would be to create a commit that includes a >100 MB file that is not tracked by Git LFS, then attempt to push that commit.

> This would result in that error dialog as shown in the screenshot for this Issue.

**Comment by billygriffin** [comment] 2018-12-18 16:45
Great, thanks y'all! Seems like #6013 just makes this less likely to be *a thing*™️. I'm 👍 on updating the error message here to contain the repo name that wasn't able to be pushed. I'm going to add `help wanted`, and if others think this might be a `good first issue`, please add that as well (I'm not certain how tricky the logic is for repo detection in the error state).

**Comment by billygriffin** [comment] 2019-03-25 21:29
Since we merged #6013 we haven't seen people struggling with pushing files > 100MB anymore (🎉), so until we hear this as a problem, this feels a bit small to implement anything for. I'm going to close it until that's the case.

**Closed by billygriffin** 2019-03-25 21:29 UTC
Labels: bug, help wanted, priority-3
