### ISSUE TITLE
Documentation on install switches for the Windows exe installer

### ISSUE THREAD

**Issue by o-l-a-v** [desktop/desktop#9408] opened 2020-03-30 10:49 UTC
## Main issue

Please provide som documentation for installation switches/ parameters for the Windows EXE installer.

The only switch I've found so far is "-s" for silent install, this installs GitHub Desktop in user context/ to %localappdata%.

* Any more swtiches?
* Can the exe be installed in system context/ for all users?

### Don't trigger an install with "/?" and similar
Please, please, do not trigger an installation when trying to get information about install switches from command line. "/?" for instance triggered GitHub Desktop to install.

Scenarios you should block install for:

* /?
* /h
* /help
* -?
* -h
* -help
* --?
* --h
* --help

### Return available switches if "/?" or similar is defined

Also, please view available switches for one or multiple of the examples above.

**Comment by rafeca** [comment] 2020-03-30 14:18
Hey @o-l-a-v ! Thanks for the report!

GitHub Desktop currently uses `Squirrel.Windows` to generate the Windows installers. As far as I know there's no specific installation switches for Desktop apart from the ones that `Squirrel.Windows` provides (and it's very possible that the lack of documentation on the installation switches is also caused by squirrel).

Another related limitation is that squirrel doesn't handle well machine-wide installations (see [this doc](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/machine-wide-installs.md#machine-wide-installs)). Basically the .msi can only install Desktop per-user after the user logs in.

What other switches would you expect to have on the installer? What kind of customizations do you need to do when installing?

(there's some discussion about addressing some of the issues of the Windows installer [in this issue](https://github.com/desktop/desktop/issues/1086))

**Comment by o-l-a-v** [comment] 2020-03-30 15:23
> Hey @o-l-a-v ! Thanks for the report!
> 
> GitHub Desktop currently uses `Squirrel.Windows` to generate the Windows installers. As far as I know there's no specific installation switches for Desktop apart from the ones that `Squirrel.Windows` provides (and it's very possible that the lack of documentation on the installation switches is also caused by squirrel).
> 
> Another related limitation is that squirrel doesn't handle well machine-wide installations (see [this doc](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/machine-wide-installs.md#machine-wide-installs)). Basically the .msi can only install Desktop per-user after the user logs in.
> 
> What other switches would you expect to have on the installer? What kind of customizations do you need to do when installing?
> 
> (there's some discussion about addressing some of the issues of the Windows installer [in this issue](https://github.com/desktop/desktop/issues/1086))

Thanks for the clearification. Squirrel.Windows is not really well designed to work with client management and application distribution. Same thing with Teams installer and Yammer I guess. Would be great if Squirrel.Windows added functionality to work in system context, on not use that jank setup that requires users to login gain, and sometimes out and in again, in order for stuff to get installed.

The only other parameter I'd like really is a "-allusers" or something like that to install for all users/ system context. But if thats up to Squirrel.Windows to add... I guess that won't happen any time soon.

For now though, please document the "-s" switch. And please look into if you can do anything when it comes to not running the installer if passing common parameters used for getting install switches.

**Comment by rafeca** [comment] 2020-03-31 11:42
Thanks for creating the related issues! I'm gonna close this one since we already have the ones in squirrel and https://github.com/desktop/desktop/issues/1086

**Closed by rafeca** 2020-03-31 11:42 UTC
Labels: more-info-needed

**Comment by Coldblackice** [comment] 2020-11-27 07:16
I also agree, it would be useful if helper switches didn't activate the installer regardless, and instead displayed what switches are available. Common switches include silent installation, changing of install folder, passive/no input, no dialogs, no restart, install logging (or not), whether to install system-wide or for current user (ProgramFiles vs. Roaming\AppData), etc.

**Comment by Lewis-Brown-NHS** [comment] 2022-03-02 12:14
@echo Off
REM script to install GitHub Desktop

REM Installs the machine-wide installer
msiexec.exe /i "%~dp0GitHubDesktopSetup-x64.msi" /qn

REM Wait for install to complete
PING -n 10 127.0.0.1>nul

REM Change directory to install folder and run exe
CD "%ProgramFiles(x86)%\GitHub Desktop Deployment\" && "GitHubDesktopDeploymentTool.exe" -s

REM Delete desktop shortcut
Del /f "C:\Users\%username%\Desktop\GitHub Desktop.lnk"

**Comment by zberkowitz** [comment] 2022-07-19 20:05
> @echo Off REM script to install GitHub Desktop
> 
> REM Installs the machine-wide installer msiexec.exe /i "%~dp0GitHubDesktopSetup-x64.msi" /qn
> 
> REM Wait for install to complete PING -n 10 127.0.0.1>nul
> 
> REM Change directory to install folder and run exe CD "%ProgramFiles(x86)%\GitHub Desktop Deployment" && "GitHubDesktopDeploymentTool.exe" -s
> 
> REM Delete desktop shortcut Del /f "C:\Users%username%\Desktop\GitHub Desktop.lnk"

The actual behavior of the MSI installer is as @Lewis-Brown-NHS shows in this script that it puts "GitHubDesktopDeploymentTool.exe" in "%ProgramFiles(x86)%\GitHub Desktop Deployment" (at least in the current version as of writing (3.0.5) ).

**But it also registers it as a startup application**.  I think it's unnecessary to run the rest of the script past the installation of the MSI.  What the Deployment Tool does is trigger an install of GitHub Desktop in %localappdata%\GitHubDesktop for each new user that logs into the machine.  So it's still a per-user install but is automatically triggered when the user logs in as long as the "GitHub Desktop Deployment Tool" is installed and enabled as a startup app.

Handy, but not documented that I can find!
