### ISSUE TITLE
Group repositories by organisation

### ISSUE THREAD

**Issue by KierenB** [desktop/desktop#5023] opened 2018-06-25 15:16 UTC
I work with multiple organisations. It would be beneficial to view the repo list grouped by organisation, as sometimes repos from different orgs have the same name and it's hard to know what's what without this context.

**Comment by iAmWillShepherd** [comment] 2018-06-25 15:20
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1533. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-06-25 15:20 UTC
