### ISSUE TITLE
Need graphic view for branch

### ISSUE THREAD

**Issue by pluwen** [desktop/desktop#4905] opened 2018-06-09 16:49 UTC
![image](https://user-images.githubusercontent.com/555720/41194029-ffd5524e-6c47-11e8-9f66-8f54c9e75b00.png)

Just like SourceTree or other git client.

**Comment by jaketyo** [comment] 2018-06-14 20:41
This would be a huge improvement.

I'm waiting for this to be implemented so I can switch away from GitKraken.

**Comment by nerdneha** [comment] 2018-06-15 04:39
hi @pluwen and @jaketyo, thanks for the feedback and taking the time to contribute!

We noticed that this is a duplicate of #1634. Please follow that issue for further updates.

**Closed by nerdneha** 2018-06-15 04:39 UTC
