### ISSUE TITLE
Github Client 3.0.1 Not Opening on macOS High Sierra

### ISSUE THREAD

**Issue by Amazonys** [desktop/desktop#14712] opened 2022-06-01 18:14 UTC
### The problem

Automatically updated GitHub Desktop client  to 3.0.1.
Application opens, then closes instantly. 
Restarting computer does not change anything.
Reverted to 2.9.15, and client opens and works normally.
As long as I do not restart the client and update to 3.0.1, I can continue to work as normal.

### Release version

3.0.1

### Operating system

macOS High Sierra (10.13.6)

**Comment by tsvetilian-ty** [comment] 2022-06-01 18:24
@Amazonys High Sierra is no longer supported https://github.com/desktop/desktop/issues/14707#issuecomment-1143597430

**Comment by adrianbj** [comment] 2022-06-01 18:29
@tsvetilian-ty - thanks for letting us know, but then why did it automatically update to the new version?

**Comment by adrianbj** [comment] 2022-06-01 18:31
@Amazonys - where did you get the old version from? Do we need to compile from the source, or are their MacOS packages somewhere? Thanks!

**Comment by tsvetilian-ty** [comment] 2022-06-01 18:56
Even if you download one of the previous versions of GitHub Desktop, it will automatically update to the latest, based on the channel you're using. Also, the "Auto-Update Services" are part of the [term and conditions](https://desktop.github.com/terms/). Currently, there is no option to disable it.

**Comment by adrianbj** [comment] 2022-06-01 18:59
Yeah, I found a working old version. I guess I'll just have to keep replacing the app file when it updates. Either that, or start using a different git GUI client.

**Comment by steveward** [comment] 2022-06-01 19:44
@adrianbj I'm going to close this out, we're tracking opting out of auto-updates in https://github.com/desktop/desktop/issues/3410 if you'd like to follow along there.

**Comment by splorp** [comment] 2022-06-01 22:53
> High Sierra is no longer supported https://github.com/desktop/desktop/issues/14707#issuecomment-1143597430

It would have been nice to be notified about this in the release notes for 3.0.1.

Since I manual updated my client, I would have avoided doing that had I seen any sort of notification that High Sierra support had been dropped.

Not a very considerate move, if you ask me.

**Comment by sergiou87** [comment] 2022-06-02 07:24
@splorp while it's true High Sierra is not officially supported, I don't think we did anything that would stop the app from working on it.

Could you provide the app logs so I can take a look? You can find them in `~/Library/Application Support/GitHub Desktop/logs`
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

I'm gonna reopen this until I'm confident enough about what the problem is 🤞 But it might be related to the new notifications. Could you try version 3.0.0 from https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.0-b9edf655/GitHubDesktop-x64.zip ? It might make a difference 🤔

**Comment by sergiou87** [comment] 2022-06-02 07:29
@rodlie thanks for your other report. You say 3.0.0 worked fine? If it did, maybe the reason is [some of the notifications API used in desktop-notifications](https://github.com/desktop/desktop-notifications/tree/main/src/mac) are not available in those older versions of macOS. We'll need to add checks for them.

**Comment by rodlie** [comment] 2022-06-02 07:33
Yes, v3.0.0 works just fine.

**Comment by sergiou87** [comment] 2022-06-02 07:54
Thank you, I'm gonna make a few changes and see if I can prevent this issue for older versions of macOS. I'll provide a test build soon-ish (hopefully today) so you can confirm it works 🤞

**Comment by splorp** [comment] 2022-06-02 14:54
> Could you provide the app logs so I can take a look?
> The log files are created daily -- please upload a log file as
> as an attachment from a day where you experienced the issue.

Here you go.

This is yesterday’s log file … when I was notified there was an update and I tried relaunching the app to apply it.

Note that later in the log you’ll see that I went back and started using an older version of the app as well.

[2022-06-01.desktop.production.log](https://github.com/desktop/desktop/files/8825020/2022-06-01.desktop.production.log)

**Comment by pychheda** [comment] 2022-06-02 14:56
I am facing the same problem too. How do you go back to the older version of the app?
I don't have an option to upgrade the OS.

**Comment by sergiou87** [comment] 2022-06-02 15:43
@pychheda @splorp @rodlie @Amazonys could you try this test build? https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.2-test1-caf934c7/GitHubDesktop-x64.zip

It's v3.0.2-test1 and includes the changes from https://github.com/desktop/desktop-notifications/pull/18, so it should be safe to run on High Sierra 🤞 Please let me know if it works.

**Comment by sergiou87** [comment] 2022-06-02 15:44
@pankiale please see the message above ☝️ 🙏

**Comment by rodlie** [comment] 2022-06-02 15:50
v3.0.2-test1 works here 👍

**Comment by pychheda** [comment] 2022-06-02 15:52
v3.0.2-test1 worked for me. Thanks a lot, @sergiou87 for providing a fix!!
Appreciate the quick turnaround.

**Comment by sergiou87** [comment] 2022-06-02 15:53
Yay!! Thank you all for trying it and also for your patience 🙇‍♂️ I'll try to get the fix reviewed and merged ASAP!

**Comment by adrianbj** [comment] 2022-06-02 15:57
Thanks @sergiou87 - working here too, much appreciated!

**Closed as completed** 2022-06-02 16:35 UTC

**Comment by sergiou87** [comment] 2022-06-03 07:23
We just deployed 3.0.2-beta2 with the fix if you don't want to use a test build 😄 

You can download it from https://desktop.github.com/beta

**Comment by byaparentdesign** [comment] 2022-06-03 07:50
Thank you!  This works on os10.12.6!

**Comment by markseuffert** [comment] 2022-06-03 18:39
I did run into exactly the same problem, client stopped working after automatic update today, manually downloading 3.0.2-beta2 did fix the problem.

**Comment by Dao-Surfclubb** [comment] 2022-06-04 21:10
Thanks for your job. 10.13.6 works

**Comment by leftCoast** [comment] 2022-06-05 19:09
Same issue here, commenting to get this into my notifications list.

**Comment by francescocortese** [comment] 2022-06-06 08:13
> We just deployed 3.0.2-beta2 with the fix if you don't want to use a test build 😄
> 
> You can download it from https://desktop.github.com/beta

Beta it works! Thanks!

**Comment by jdaw1** [comment] 2022-06-06 12:44
FYI, MacBooks ≤2014, and iMacs ≤2011, cannot be upgraded past High Sierra 10.13.6. (Per [system requirements for the next macOS = Mojave = 10.14](https://en.wikipedia.org/wiki/MacOS_Mojave#System_requirements).)

**Comment by leftCoast** [comment] 2022-06-06 23:35
> FYI, MacBooks ≤2014, and iMacs ≤2011, cannot be upgraded past High Sierra 10.13.6. (Per [system requirements for the next macOS = Mojave = 10.14](https://en.wikipedia.org/wiki/MacOS_Mojave#System_requirements).)

Meaning Updates can cost older Mac users $1,000s of dollars.

BUT!! This Beta version linked above seems to solve the issue.

THANK YOU!!!

I live and breath at least one more day..

-jim lee

**Comment by jdaw1** [comment] 2022-06-07 07:28
> Meaning Updates can cost older Mac users $1,000s of dollars.

I am a Mac user _of a certain age_, so welcome the new beta. Indeed, thank you.

**Comment by sergiou87** [comment] 2022-06-13 10:08
You can now download the latest production build v3.0.2 from https://desktop.github.com which contains the fix.

Thank you for your patience and sorry for any inconvenience we have caused you 🙇‍♂️

**Comment by Hgseof** [comment] 2022-11-12 07:23
> ### The problem
> Automatically updated GitHub Desktop client to 3.0.1. Application opens, then closes instantly. Restarting computer does not change anything. Reverted to 2.9.15, and client opens and works normally. As long as I do not restart the client and update to 3.0.1, I can continue to work as normal.
> 
> ### Release version
> 3.0.1
> 
> ### Operating system
> macOS High Sierra (10.13.6)
> 
> ### Steps to reproduce the behavior
> _No response_
> 
> ### Log files
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_

Bkk

**Comment by Bayboyga** [comment] 2022-12-28 02:35
lol

**Comment by rickymunizjr** [comment] 2024-10-13 00:46
> You can now download the latest production build v3.0.2 from https://desktop.github.com which contains the fix.
> 
> Thank you for your patience and sorry for any inconvenience we have caused you 🙇‍♂️

Many thanks, working on High Sierra 10.13.6. I had to use the releases link as the home page link does not have any reference to download this version:

https://github.com/desktop/desktop/releases/tag/release-3.0.2

It seems that is broken again in new versions (at least tried in 3.4.6 and did not worked), do we know what is the latest version working for macOS High Sierra 10.13.6?

Thanks for the support!
