### ISSUE TITLE
Pull requests from CSSEGISandData/COVID-19.git  broken?

### ISSUE THREAD

**Issue by yaneziii** [desktop/desktop#14465] opened 2022-04-27 20:19 UTC
### The problem

Attempting a pull from CSSEGISandData/COVID-19.git and receive a pop-up window that reads,

_Error

remote: Enumerating objects: 6261, done.        
remote: Counting objects: 100% (4949/4949), done.        
remote: Compressing objects: 100% (14/14), done.        
remote: Total 6261 (delta 4935), reused 4946 (delta 4935), pack-reused 1312        
Receiving objects: 100% (6261/6261), 98.61 MiB | 48.11 MiB/s, done.
Resolving deltas: 100% (5711/5711), completed with 1434 local objects.
fatal: bad object refs/heads/master 2
error: https://github.com/CSSEGISandData/COVID-19.git did not send all necessary objects

Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log
Automatic cleanup will not be performed until the file is removed.

fatal: bad object refs/heads/master 2
fatal: failed to run repack_

I've been downloading these data for > 1 year, almost daily.  If you can help me resolve this I would greatly appreciate it. Thank you.

David

### Release version

Latest version (Version 3.0.0 (x64))

### Operating system

macOS Monterey (ver. 12.3)

### Steps to reproduce the behavior

1. Make a fetch.

### Log files

remote: Enumerating objects: 6261, done.        
remote: Counting objects: 100% (4949/4949), done.        
remote: Compressing objects: 100% (14/14), done.        
remote: Total 6261 (delta 4935), reused 4946 (delta 4935), pack-reused 1312        
Receiving objects: 100% (6261/6261), 98.61 MiB | 37.76 MiB/s, done.
Resolving deltas: 100% (5711/5711), completed with 1434 local objects.
fatal: bad object refs/heads/master 2
error: https://github.com/CSSEGISandData/COVID-19.git did not send all necessary objects

Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
warning: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log
Automatic cleanup will not be performed until the file is removed.

fatal: bad object refs/heads/master 2
fatal: failed to run repack

### Screenshots

![Screen Shot 2022-04-27 at 4 12 17 PM](https://user-images.githubusercontent.com/19375240/165624086-81ab6f77-900d-4c3e-9508-421bd9cd548d.png)

### Additional context

Thank you.

**Comment by sergiou87** [comment] 2022-04-28 07:48
Hi @yaneziii !

That error message mentions a file `.git/gc.log` inside your repository. Could you upload it? You might need to delete it before you download the changes from that repository.

**Comment by yaneziii** [comment] 2022-04-28 12:08
Hello, Sergio,

Thank you for your email. Yes, I was looking for that log file and have not
been able to find it. I thought it would reside in the .git folder on my
GitHub folder tree here:

/Users/dyanez/Documents/GitHub/COVID-19/.git

but I had no such luck. I also went through several of its subfolders,
including a /logs subfolder, but it was not present. If you have any
suggestions where to find it, please let me know. Thank you again for your
assistance and kindness.

Best regards,
David

PS: I was searching using "ls -a" so I could see the hidden files.

**Comment by sergiou87** [comment] 2022-04-28 13:39
That's unexpected! 🤯  Maybe you have some kind of global `.git` folder? I'd look at `/Users/dyanez/.git` or `/Users/dyanez/.config/git`

Otherwise you can just run `find /Users/dyanez -name gc.log` which will look for that file in your whole user folder. It has to be somewhere… 🤔

**Comment by pboling** [comment] 2022-05-01 12:40
@sergiou87 @yaneziii `fatal: bad object refs/heads/master 2` is caused by iCloud making copies of files for its internal sync / backup processes, and then sometimes failing to clean up those files, and sometimes that failure can leak into other things, and corrupt stuff.  This is a problem that can only happen on a Mac.

Bottom line is you literally have a file with a `(space) 2` appended to the end.  When you have one, you usually have many.  It can be a PITA to clean up, and actually that's how I found this issue.  I'm looking for a way to clean up this exact problem on a different project.

Moving the files out of an iCloud area on the drive will not fix it.  The files are in the file system, and are no longer being tracked by iCloud, so they are stuck.

**Comment by pboling** [comment] 2022-05-01 12:41
Checking the project out fresh *does solve the problem* - just hope you don't have any important changes in your working copy.

**Comment by pboling** [comment] 2022-05-01 12:43
Here's my corrupted `.git` directory... See the file with an extra ` 2` at the end?
<img width="1082" alt="Screen Shot 2022-05-01 at 5 43 24 AM" src="https://user-images.githubusercontent.com/19505/166146525-0c2ea971-90c2-4efb-a07c-e46258ffb2e6.png">

**Comment by pboling** [comment] 2022-05-01 12:48
```
rm -rf .git/index\ 2
rm -rf .git/refs/heads/master\ 2
rm -rf .git/refs/remotes/origin/HEAD\ 2
```
The commands above fixed it for me, but I only knew which things to delete by inspecting the directories in `.git` with `ls`, and also running the command over and over to see what file ending in ` 2` it was dying on, deleting that file, and then trying again.

Fixed!

Also note that you can't fix this by `cd .git`... you have to run the `rm` commands outside the actual `.git` directory.  If you don't you'll get `fatal: this operation must be run in a work tree`.

Also, there is zero chance you "need" what is in the ` 2` files.  They are always, and only ever, copies of the real thing.  All your changes, if any, are still in the "real" files.

**Comment by pboling** [comment] 2022-05-01 12:52
Also worth noting, this is not an error that has anything to do with Desktop.  It is a low level problem on the computer that manifests this way after it happens. No relation to this repo / project.

**Comment by yaneziii** [comment] 2022-05-01 15:04
Thank you, Peter,

The solution worked after a bit more investigation. Removing the files
ending with "2" was the start, but I also had like files that ended in "3"
as well.

The one thing I could not figure out was why I still had the same error
after the files had been removed.

Funny thing was that I had used two different mac computers, sequentially,
both with the same work username. That caused another problem and
made the root cause of the problem hard to find. Let me explain...

The first computer (a retired macbook pro) was used when I created the
GitHub directory in my Documents folder. When I linked my account to my
current mac pro computer a year later, it created a new Documents
sub-folder inside my iCloud's Documents folder (i.e., "Documents/*Documents
- **Serial_number_of_new_mac*") and also created a new GitHub directory
where these files reside.

I didn't know that had happened until now. I missed it. It still worked
when I made the transition to the new computer and I didn't notice.

Thank you for your help. All systems go!

Best regards,
David

**Comment by pboling** [comment] 2022-05-01 15:22
There's layers to this *ish, man

🤣

**Comment by niik** [comment] 2022-05-02 06:36
As @pboling notes this doesn't appear to be an issue with GitHub Desktop itself so I'm going to close this issue. We recommend avoiding storing repositories on cloud-synced services such as ICloud/Dropbox, we see plenty of issues arising from synchronization failures like this. Feel free to keep discussing in here though or try our [community forums](https://github.community/).

**Comment by yaneziii** [comment] 2022-05-02 11:56
Thank you, Markus,

Yes, please let’s close this case. I very much appreciate you all helping me to resolve this issue.

With best regards,
David

**Comment by yaneziii** [comment] 2022-10-11 08:59
Thank you, Peter. I'll work on it. Much appreciated. -david

**Closed as completed** 2022-10-11 09:12 UTC
