### ISSUE TITLE
ENOENT error on Mac

### ISSUE THREAD

**Issue by doomlab** [desktop/desktop#3779] opened 2018-01-12 15:28 UTC
### Description

I am getting an error message using github desktop on my mac (High Sierra 10.13.2). Any time I click fetch origin or push origin, I get the following error:

ENOENT: no such file or directory, mkdtemp '/private/var/folders/wn/9qmmzlcj7gjfy01xzlfb7f400000gn/T/Cleanup At Startup/GitHubDesktop-lfs-progress-6YOmvE'

I checked the other issues by searching enoent, but didn't find a good mac answer. 

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** High Sierra 10.13.2

### Steps to Reproduce

1. Click fetch origin

OR

1. Make changes --> commit to master
2. Click push origin

**Expected behavior:** The repository to push (doomlab/jeff-meta is a specific example but it's happening on all of of them)

**Actual behavior:** Error message seen above. 

**Reproduces how often:** Every time I click the button (didn't happen yesterday). 

### Logs

[2018-01-12.desktop.production.log](https://github.com/desktop/desktop/files/1626497/2018-01-12.desktop.production.log)

**Comment by shiftkey** [comment] 2018-01-12 15:29
We've had a couple of reports of this on Windows (like #3747) which were due to the `TEMP` or `TMP` environment variable being set to contain multiple paths, but this looks different to that.

**Comment by doomlab** [comment] 2018-01-12 15:42
I tried to use some of those errors to help troubleshoot the issue - but I don't really see anything in the logs that I could use to figure out where the problem lies. I can also provide the logs to a specific folder if that would help.

**Comment by iAmWillShepherd** [comment] 2018-01-12 16:01
After going through the logs you've submitted, I can't see anything out of the ordinary. Can you confirm that the location `/private/var/folders/wn/9qmmzlcj7gjfy01xzlfb7f400000gn/T/Cleanup At Startup/GitHubDesktop-lfs-progress-6YOmvE'` indeed does not exist?

**Comment by doomlab** [comment] 2018-01-12 16:06
Sure. Hopefully this picture is readable. 

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/27783894/34883709-5baa05b8-f788-11e7-9e3c-5d26867745f2.png">

I also checked the temporary directory and tried to find this directory in terminal:
Last login: Fri Jan 12 11:00:24 on ttys000
BuchanaMacBook3:~ buchanan$ echo $TMPDIR
/private/var/folders/wn/9qmmzlcj7gjfy01xzlfb7f400000gn/T/Cleanup At Startup
BuchanaMacBook3:~ buchanan$ cd /private/var/folders/wn/9qmmzlcj7gjfy01xzlfb7f400000gn/T/Cleanup At Startup
-bash: cd: /private/var/folders/wn/9qmmzlcj7gjfy01xzlfb7f400000gn/T/Cleanup: No such file or directory
BuchanaMacBook3:~ buchanan$

**Comment by doomlab** [comment] 2018-01-12 16:50
I tried googling this, but am missing how to change that variable. I tried looking in .profile but not seeing it. I would test changing it if I could figure out how :|.

**Comment by shiftkey** [comment] 2018-01-12 17:24
@doomlab I'm glad you were able to workaround this issue. I'm going to leave this open to see if we can reproduce this - my gut feeling is that we need to handle that path better within the app.

**Comment by doomlab** [comment] 2018-01-12 17:41
Thanks for your help! I'll be glad to answer any questions if I can.

**Comment by shiftkey** [comment] 2018-01-13 13:52
I wasn't able to reproduce this with a path containing spaces:

<img width="637" src="https://user-images.githubusercontent.com/359239/34906566-65d6175c-f846-11e7-8f85-7e38ad217a0f.png">

After a bit more digging, I found [this link](http://www.westwind.com/reference/OS-X/invisibles.html) which mentions that the `Cleanup at Startup` directory is a macOS "invisible folder" which contains "files created by Mac OS 9 applications and installers that need to be deleted the next time OS 9 starts up". I'm not 100% sure why/how this has been set to `TMPDIR`, but given that it eventually reverted to something that could be written to, I'm going to close this out as an external issue. 

@doomlab thanks for working through this with us!

**Closed by shiftkey** 2018-01-13 13:52 UTC
Labels: needs-reproduction
