### ISSUE TITLE
Feature: Import multiple Git repos at once

### ISSUE THREAD

**Issue by aryanprince** [desktop/desktop#19309] opened 2024-09-26 03:14 UTC
# Summary

We need a way to import multiple Git repos in one go to GitHub Desktop. Currently we can only do it one by one.

## Issue

Currently we can click on "Add" > "Add existing repository" > and select a path to a **single Git repository** to be added to GitHub Desktop. 

How about if I want to add **all my repositories under my `Code` folder** so everything shows up under GitHub Desktop?

## Goal

The goal would be that GitHub Desktop now becomes my single source of truth for all repos on my computer in 'one go'. Right now, I always have to manually import each of my Git repos **one by one**.

## Proposed Solutions

1. We could either have another option under the "Add" dropdown like "Add multiple existing repositories"

2. Once you click on "Add existing repository", on the dialog box there could be another option that let's you import an entire directory that contains multiple different Git repos.

I'm not sure how else to showcase this feature to the user in terms of UX.

**Comment by sergiou87** [comment] 2024-09-26 07:36
Duplicate of #2978 

Please, subscribe to that issue to track any updates on it!

And just FYI, you can add multiple repos at once by selecting them from Finder/Windows Explorer and dragging them onto GitHub Desktop, that should add all of them.

**Closed as not planned by sergiou87** 2024-09-26 07:36 UTC
Labels: enhancement, not-planned

**Comment by aryanprince** [comment] 2024-09-28 07:02
> And just FYI, you can add multiple repos at once by selecting them from Finder/Windows Explorer and dragging them onto GitHub Desktop, that should add all of them.

Appreciate it, this is a good enough workaround for myself (at least for now)
