### ISSUE TITLE
Proposed Feature: Double click to open file in External Editor

### ISSUE THREAD

**Issue by mountainash** [desktop/desktop#10039] opened 2020-06-18 20:22 UTC
### Describe the feature or problem you’d like to solve

It would be a big time saver if double-clicking on a file name in the "changed files" list (under the "Changes" or "History" tabs) opened the chosen file in the set External Editor

### Proposed solution

When file name is double-click (two single clicks in rapid succession) the local file of the displayed file name is opened in the application set as the "External Editor" in GitHub Desktops preferences.

**Comment by tierninho** [comment] 2020-06-18 21:12
@mountainash Thanks for the suggestion. This is a dupe of https://github.com/desktop/desktop/issues/2620 so please follow along there for any future updates.

**Closed by tierninho** 2020-06-18 21:12 UTC

**Comment by mountainash** [comment] 2020-06-18 22:02
Thanks @tierninho - I tried a bunch of searches of the issue, thinking this is such an obvious "missing" feature and didn't find anything.... because it's closed! (that and Github search ... well needs improving...).

Turns out I'm not alone though - these are all duplicates:
#3276
#4019
#4727
#4539
#4541 

... and also all closed 😢

**Comment by tierninho** [comment] 2020-06-18 22:24
Apologies for the confusion. We keep future proposals closed until we are ready to work on them. 

Your points are valid and we will take your feedback (and others) into consideration. Thanks again!
