### ISSUE TITLE
fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by domclass** [desktop/desktop#4168] opened 2018-03-04 13:20 UTC
### Description

while publish a branch, come with that <fatal: Unable to find remote helper for 'https'> erro. 

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** Microsoft Windows [版本 6.1.7601]

### Steps to Reproduce

1. click on the publish or fetch origin

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by iAmWillShepherd** [comment] 2018-03-04 20:33
Thanks for taking the time to open an issue! 🙇 

@domclass , could you take a moment to expand on what the problem is? I cannot reproduce your issue using your reproduction steps.

**Comment by shiftkey** [comment] 2018-03-05 21:58
@iAmWillShepherd @domclass also, the log file would help here to understand what's happening underneath.  The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day.

**Comment by Assamdiapak** [comment] 2018-03-06 12:48
CopyrightsCopyrightsAuthorshipWhat Can Be Copyrighted?What Cannot Be Copyrighted?Securing Copyright ProtectionPublicationCopyright NoticeDuration of ProtectionTransfer of Copyright OwnershipInternational Copyright ProtectionFiling for A Copyright RegistrationEffective Date of RegistrationWho Can FileCopyrightCopyright is a form of protection provided by the laws of the United States (title 17, U.S. Code) to the authors of “original works of authorship,” including literary, dramatic, musical, artistic, and certain other intellectual works. Copyright protection is available to both published and unpublished works.Section 106 of the 1976 Copyright Act generally provides to the owner of a copyright the exclusive right to do and to authorize others to do the following:To reproduce the work in copies or phonorecords;To prepare derivative works based upon the work;To distribute copies or phonorecords of the work to the public by sale or other transfer of ownership, or by rental, lease, or lending;To perform the work publicly, in the case of literary, musical, dramatic, and choreographic works, pantomimes, and motion pictures and other audiovisual works;To display the copyrighted work publicly, in the case of literary, musical, dramatic, and choreographic works, pantomimes, and pictorial, graphic, or sculptural works, including the individual images of a motion picture or other audiovisual work; andIn the case of sound recordings, to perform the work publicly by means of a digital audio transmission.In addition, under the Visual Artists Rights Act (VARA), certain authors of works of visual art have the rights of attribution and integrity as described in section 106A of the 1976 Copyright Act.It is illegal for anyone to violate any of the rights provided by the copyright law to the owner of copyright. These rights, however, are not unlimited in scope. Sections 107 through 121 of the 1976 Copyright Act establish limitations on these rights. In some cases, these limitations are specified exemptions from copyright liability.One major limitation is the doctrine of "fair use", which is given a statutory basis in section 107 of the 1976 Copyright Act. In other instances, the limitation takes the form of a "compulsory license" under which certain limited uses of copyrighted works are permitted upon payment of specified royalties and compliance with statutory conditionsImportantly, mere ownership of a book, manuscript, painting, or any other copy or phonorecord does not give the possessor the copyright. Specifically, the United States Copyright Law provides that transfer of ownership of any material object that embodies a protected work does not of itself convey any rights in the copyright. For example, merely owning a computer diskette, compact disc, or digital versitile disc does not provide the owner with ownership over any copyrighted material fixed in the computer diskette, compact disc, or digital versitile disc.AuthorshipCopyright protection arises at the time the work is "fixed in a tangible medium". In consequence, the copyright in the work of authorship immediately becomes the property of the author who created the work.Only the author or those deriving their rights through the author can rightfully claim copyright.In the case of works made for hire, the employer and not the employee is considered to be the author. Section 101 of the copyright law defines a "work made for hire" as:a work prepared by an employee within the scope of his or her employment; ora work specially ordered or commissioned for use asa contribution to a collective worka part of a motion picture or other audiovisual worka translationa supplementary worka compilationan instructional texta testanswer material for a testa sound recordingan atlasif the parties expressly agree in a written instrument signed by them that the work shall be considered a work made for hire.The authors of a joint work are co-owners of the copyright in the work, unless there is an agreement to the contrary.Copyright in each separate contribution to a periodical or other collective work is distinct from copyright in the collective work as a whole and vests initially with the author of the contribution.What Can Be Copyrighted?Copyright protection protects "original works of authorship" that are fixed in a tangible form of expression. The fixation need not be directly perceptible so long as it may be communicated with the aid of a machine or device.Copyrightable works include the following categories:literary works;musical works, including any accompanying wordsdramatic works, including any accompanying musicpantomimes and choreographic workspictorial, graphic, and sculptural worksmotion pictures and other audiovisual workssound recordingsarchitectural worksThese categories should be viewed broadly. For example, computer programs and most "compilations" may be registered as "literary works"; maps and architectural plans may be registered as "pictorial, graphic, and sculptural works."What Cannot Be Copyrighted?Several categories of material are generally not eligible for federal copyright protection. These categories include among others:Works that have not been fixed in a tangible form of expression (for example, choreographic works that have not been notated or recorded, or improvisational speeches or performances that have not been written or recorded)Titles, names, short phrases, and slogans; familiar symbols or designs; mere variations of typographic ornamentation, lettering, or coloring; mere listings of ingredients or contentsIdeas, procedures, methods, systems, processes, concepts, principles, discoveries, or devices, as distinguished from a description, explanation, or illustrationWorks consisting entirely of information that is common property and containing no original authorship (for example: standard calendars, height and weight charts, tape measures and rulers, and lists or tables taken from public documents or other common sources)Securing Copyright ProtectionNo publication or registration or other action in the United States Copyright Office is required to secure copyright protection. There are, however, certain definite advantages to registration.A copyright is secured automatically when the work is created (fixed in a copy or phonorecord for the first time). "Copies" are material objects from which a work can be read or visually perceived either directly or with the aid of a machine or device, such as books, manuscripts, sheet music, film, videotape, or microfilm. "Phonorecords" are material objects embodying fixations of sounds (excluding, by statutory definition, motion picture soundtracks), such as cassette tapes, CDs, or LPs. Thus, for example, a song (the "work") can be fixed in sheet music (" copies") or in phonograph disks (" phonorecords"), or both.If a work is prepared over a period of time, the part of the work that is fixed on a particular date constitutes the created work as of that date.PublicationThe 1976 Copyright Act defines publication as follows:"Publication" is the distribution of copies or phonorecords of a work to the public by sale or other transfer of ownership, or by rental, lease, or lending. The offering to distribute copies or phonorecords to a group of persons for purposes of further distribution, public performance, or public display constitutes publication. A public performance or display of a work does not of itself constitute publication.Publication is an important concept in the copyright law for several reasons:Works that are published in the United States are subject to mandatory deposit with the Library of Congress.Publication of a work can affect the limitations on the exclusive rights of the copyright owner.The year of publication may determine the duration of copyright protection for anonymous and pseudonymous works (when the author's identity is not revealed in the records of the Copyright Office) and for works made for hire.Deposit requirements for registration of published works differ from those for registration of unpublished works.When a work is published, it may bear a notice of copyright to identify the year of publication and the name of the copyright owner and to inform the public that the work is protected by copyright. Copies of works published before March 1, 1989, must bear the notice or risk loss of copyright protection.Copyright NoticeThe use of a copyright notice is not required under U. S. law, although copyright notice often can be beneficial.Use of the copyright notice may be important because the copyright notice informs the public that the work is protected by copyright, identifies the copyright owner, and shows the year of first publication.Furthermore, in the event that a work is infringed, if a proper notice of copyright appears on the published copy or copies to which a defendant in a copyright infringement suit had access, then no weight shall be given to such a defense based on innocent infringement in mitigation of actual or statutory damages. "Innocent infringement" occurs when the infringer did not realize that the work was protected.The use of the copyright notice is the responsibility of the copyright owner and does not require advance permission from, or registration with, the Copyright Office.The notice for visually perceptible copies should contain all the following three elements:The symbol © (the letter C in a circle), or the word "Copyright," or the abbreviation "Copr."; andThe year of first publication of the work. In the case of compilations or derivative works incorporating previously published material, the year date of first publication of the compilation or derivative work is sufficient. The year date may be omitted where a pictorial, graphic, or sculptural work, with accompanying textual matter, if any, is reproduced in or on greeting cards, postcards, stationery, jewelry, dolls, toys, or any useful article; andThe name of the owner of copyright in the work, or an abbreviation by which the name can be recognized, or a generally known alternative designation of the owner.Example: © 2000 John DoeThe "C in a circle" notice is used only on "visually perceptible copies." Certain kinds of works--for example, musical, dramatic, and literary works--may be fixed not in "copies" but by means of sound in an audio recording. Since audio recordings such as audio tapes and phonograph disks are "phonorecords" and not "copies," the "C in a circle" notice is not used to indicate protection of the underlying musical, dramatic, or literary work that is recorded.Sound recordings are defined in the law as "works that result from the fixation of a series of musical, spoken, or other sounds, but not including the sounds accompanying a motion picture or other audiovisual work." Common examples include recordings of music, drama, or lectures. A sound recording is not the same as a phonorecord. A phonorecord is the physical object in which works of authorship are embodied. The word "phonorecord" includes cassette tapes, CDs, LPs, 45 rpm disks, as well as other formats.The notice for phonorecords embodying a sound recording should contain all the following three elements:The symbol (the letter P in a circle); andThe year of first publication of the sound recording; andThe name of the owner of copyright in the sound recording, or an abbreviation by which the name can be recognized, or a generally known alternative designation of the owner. If the producer of the sound recording is named on the phonorecord label or container and if no other name appears in conjunction with the notice, the producer's name shall be considered a part of the notice.Example: 2000 A. B. C. Records Inc.The copyright notice should be affixed to copies or phonorecords in such a way as to "give reasonable notice of the claim of copyright." The three elements of the notice should ordinarily appear together on the copies or phonorecords or on the phonorecord label or container. The Copyright Office has issued regulations concerning the form and position of the copyright notice in the Code of Federal Regulations (37 CFR Section 201.20).Works by the U. S. Government (for example the document upon which this tutorial is based) are not eligible for U.S. copyright protection.Duration of ProtectionA work that was created on or after January 1, 1978, is automatically protected from the moment of its creation and is ordinarily given a term enduring for the author's life plus an additional 70 years after the author's death.In the case of "a joint work prepared by two or more authors who did not work for hire," the term lasts for 70 years after the last surviving author's death.For works made for hire, and for anonymous and pseudonymous works (unless the author's identity is revealed in Copyright Office records), the duration of copyright will be 95 years from publication or 120 years from creation, whichever is shorter.Transfer of Copyright OwnershipAny or all of the copyright owner's exclusive rights or any subdivision of those rights may be transferred, but the transfer of exclusive rights is not valid unless that transfer is in writing and signed by the owner of the rights conveyed or such owner's duly authorized agent. Transfer of a right on a nonexclusive basis does not require a written agreement.A copyright may also be conveyed by operation of law and may be bequeathed by will or pass as personal property by the applicable laws of intestate succession.Copyright is a personal property right, and it is subject to the various state laws and regulations that govern the ownership, inheritance, or transfer of personal property as well as terms of contracts or conduct of business.Transfers of copyright are normally made by contract. In addition, the Copyright Office can record such transfers of copyright ownership. Although recordation is not required to make a valid transfer between the parties, recordation does provide certain legal advantages and may be required to validate the transfer as against third parties.Presently, albeit not historically and certainly not in regard to all copyrighted works, the U.S. Copyright Law permits termination of a transfer of rights in a copyright after 35 years under certain conditions by serving written notice on the transferee within specified time limits. Notwithstanding, substantial limitations on the right of termination exist for those works subject to renewal requirements.International Copyright ProtectionThere is no such thing as an "international copyright" that will automatically protect an author's writings throughout the entire world.Protection against unauthorized use in a particular country depends, basically, on the national laws of that country. However, most countries do offer protection to foreign works under certain conditions, and these conditions have been greatly simplified by international copyright treaties and conventions.Filing for A Copyright RegistrationIn general, copyright registration is a legal formality intended to make a public record of the basic facts of a particular copyright. However, registration is not a condition of copyright protection.Even though registration is not a requirement for protection, the copyright law provides several inducements or advantages to encourage copyright owners to make registration. Among these advantages are the following:Registration establishes a public record of the copyright claim.Before an infringement suit may be filed in court, registration is necessary for works of U.S. origin.If made before or within 5 years of publication, registration will establish prima facie evidence in court of the validity of the copyright and of the facts stated in the certificate.If registration is made within 3 months after publication of the work or prior to an infringement of the work, statutory damages and attorney's fees will be available to the copyright owner in court actions. Otherwise, only an award of actual damages and profits is available to the copyright owner.Registration allows the owner of the copyright to record the registration with the U. S. Customs Service for protection against the importation of infringing copies.Registration may be made at any time within the life of the copyright.When a work has been registered in unpublished form, it is not necessary to make another registration when the work becomes published, although the copyright owner may register the published edition, if desired.Formal Filing RequirementsA properly completed application form.A nonrefundable filing fee of $30 (effective through June 30, 2002) for each application.A nonreturnable deposit of the work being registered.The deposit requirements vary in particular situations.The general requirements follow.If the work was first published in the United States on or after January 1, 1978, two complete copies or phonorecords of the best edition.If the work was first published in the United States before January 1, 1978, two complete copies or phonorecords of the work as first published.If the work was first published outside the United States, one complete copy or phonorecord of the work as first published.If sending multiple works, all applications, deposits, and fees should be sent in the same package. If possible, applications should be attached to the appropriate deposit. Whenever possible, number each package (e. g., 1 of 3, 2 of 4) to facilitate processing.Applications and fees received without appropriate copies, phonorecords, or identifying material will not be processed and ordinarily will be returned.Unpublished deposits without applications or fees ordinarily will be returned, also. In most cases, published deposits received without applications and fees can be immediately transferred to the collections of the Library of Congress. After the deposit is received and transferred to another service unit of the Library for its collections or other disposition, it is no longer available to the Copyright Office. If you wish to register the work, you must deposit additional copies or phonorecords with your application and fee.Specific Deposit RequirementsSpecial deposit requirements exist for many types of works. The following are prominent examples of exceptions to the general deposit requirements:If the work is a motion picture, the deposit requirement is one complete copy of the unpublished or published motion picture and a separate written description of its contents, such as a continuity, press book, or synopsis.If the work is a literary, dramatic, or musical work published only in a phonorecord, the deposit requirement is one complete phonorecord.If the work is an unpublished or published computer program, the deposit requirement is one visually perceptible copy in source code of the first 25 and last 25 pages of the program. For a program of fewer than 50 pages, the deposit is a copy of the entire program. Alternative deposit requirements exist for computer programs containing trade secrets.If the work is in a CD-ROM format, the deposit requirement is one complete copy of the material, that is, the CD-ROM, the operating software, and any manual(s) accompanying it. If registration is sought for the computer program on the CD-ROM, the deposit should also include a printout of the first 25 and last 25 pages of source code for the program.In the case of works reproduced in three-dimensional copies, identifying material such as photographs or drawings is ordinarily required.Other examples of special deposit requirements (but by no means an exhaustive list) include many works of the visual arts such as greeting cards, toys, fabrics, oversized materials; video games and other machine-readable audiovisual works; automated databases; and contributions to collective works.Effective Date of RegistrationA copyright registration is effective on the date the Copyright Office receives all the required elements in acceptable form, regardless of how long it then takes to process the application and mail the certificate of registration.The time the Copyright Office requires to process an application varies, depending on the amount of material the Office is receiving. Presently, the Copyright Office is experiencing an 8 to 10 month lag-time in processing applications.Who Can File?The following persons are legally entitled to submit an application form:The author. This is either the person who actually created the work or, if the work was made for hire, the employer or other person for whom the work was prepared.The copyright claimant. The copyright claimant is defined in Copyright Office regulations as either the author of the work or a person or organization that has obtained ownership of all the rights under the copyright initially belonging to the author. This category includes a person or organization who has obtained by contract the right to claim legal title to the copyright in an application for copyright registration.The owner of exclusive right(s). Under the law, any of the exclusive rights that make up a copyright and any subdivision of them can be transferred and owned separately, even though the transfer may be limited in time or place of effect. The term "copyright owner" with respect to any one of the exclusive rights contained in a copyright refers to the owner of that particular right. Any owner of an exclusive right may apply for registration of a claim in the work.The duly authorized agent of such author, other copyright claimant, or owner of exclusive right(s). Any person authorized to act on behalf of the author, other copyright claimant, or owner of exclusive rights may apply for registration.There is no requirement that applications be prepared or filed by an attorney. |  
-- | --

**Comment by shiftkey** [comment] 2018-03-19 05:47
Closing due to inactivity.

@domclass if you're able to answer the questions above we're happy to revisit this issue.

**Closed by shiftkey** 2018-03-19 05:47 UTC
Labels: more-information-needed
