### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'getOption' of null

### ISSUE THREAD

**Issue by HashimotoYT** [desktop/desktop#6970] opened 2019-02-27 19:44 UTC
## Description

When fastly switching between files in History tab, Uncaught TypeError shows in the console.

## Version

* GitHub Desktop: 0ff5f83831

* Operating system: Microsoft Windows [Version 10.0.17763.316], macOS Mojave 10.14

## Steps to Reproduce
1. Open History tab.
2. Open any commit with 2 or more files.
3. Fastly switch between files.

### Expected Behavior

Nothing errors in console.

### Actual Behavior

Uncaught TypeError which does not affect anything

## Additional Information

Error Stack:

```
Uncaught (in promise) TypeError: Cannot read property 'getOption' of null
    at TextDiff.initDiffSyntaxMode (text-diff.tsx:232)
    at process._tickCallback (internal/process/next_tick.js:68)
```

**Comment by shiftkey** [comment] 2019-02-27 19:52
@HashimotoYT thanks for the report! Given this might be related to the upcoming diff changes in `1.6.3` release I'm going to add it to that milestone.

If it's not easy to reproduce or it's unrelated to the things upcoming for `1.6.3` we might defer it to later.

**Comment by shiftkey** [comment] 2019-02-27 20:12
For reference, this is the problem code (which was added in #6707):

https://github.com/desktop/desktop/blob/0ff5f8383150328523a933655238d05e1773f549/app/src/ui/diff/text-diff.tsx#L232

But there is an earlier check for `this.codeMirror` being defined:

https://github.com/desktop/desktop/blob/0ff5f8383150328523a933655238d05e1773f549/app/src/ui/diff/text-diff.tsx#L216-L218

And in between this is `await`-ed which might take some time:

https://github.com/desktop/desktop/blob/0ff5f8383150328523a933655238d05e1773f549/app/src/ui/diff/text-diff.tsx#L226

**Comment by HashimotoYT** [comment] 2019-02-27 20:27
One more reproducible steps:

1. Open History tab.
2.  Fastly switch commits.

Reproduced very strange and not always, also very rare you can see an error with setOption.

https://github.com/desktop/desktop/blob/0ff5f8383150328523a933655238d05e1773f549/app/src/ui/diff/text-diff.tsx#L248

**Comment by tierninho** [comment] 2019-02-27 20:36
Gif is here:

![image](https://user-images.githubusercontent.com/14828183/53521155-7cc22f00-3a7b-11e9-89e3-d2767b402326.png)

**Comment by shiftkey** [comment] 2019-02-27 20:42
@tierninho thanks for the detailed repro!

Moving to `bug` and I'll ask one of @desktop/engineering who has been involved with the diff changes to size up the impact and whether it's worth keeping in scope for `1.6.3`.

**Comment by HashimotoYT** [comment] 2019-02-27 20:48
When moving check below fixes that. If need, I can open PR with this change.

```diff
diff --git a/app/src/ui/diff/text-diff.tsx b/app/src/ui/diff/text-diff.tsx
index b865021a5..e43aa72a8 100644
--- a/app/src/ui/diff/text-diff.tsx
+++ b/app/src/ui/diff/text-diff.tsx
@@ -213,10 +213,6 @@ export class TextDiff extends React.Component<ITextDiffProps, {}> {
   private async initDiffSyntaxMode() {
     const { file, hunks, repository } = this.props
 
-    if (!this.codeMirror) {
-      return
-    }
-
     // Store the current props to that we can see if anything
     // changes from underneath us as we're making asynchronous
     // operations that makes our data stale or useless.
@@ -229,6 +225,10 @@ export class TextDiff extends React.Component<ITextDiffProps, {}> {
       return
     }
 
+    if (!this.codeMirror) {
+      return
+    }
+
     const tsOpt = this.codeMirror.getOption('tabSize')
     const tabSize = typeof tsOpt === 'number' ? tsOpt : 4
 

```

**Comment by shiftkey** [comment] 2019-02-27 21:22
> If need, I can open PR with this change.

Lets give @desktop/engineering a chance to investigate.

**Comment by outofambit** [comment] 2019-02-27 23:25
@HashimotoYT thanks for the bug report and potential fix. I tried it out and it seemed to reduce occurrences but did not prevent the errors entirely for me.

I am relatively sure this is caused by triggering `initDiffSyntaxMode()` (via `TextDiff.onSwapDoc()`) while another run of this is already in progress. I think the ideal solution would be to "abort" the last `TextDiff.onSwapDoc()` whenever another is started.

Going to mark this as priority 3 since its only visible in the console and doesn't seem to effect the UI.

**Closed** 2019-04-18 12:19 UTC
Labels: bug, codemirror, priority-3
