### ISSUE TITLE
Cloning repo with lfs files results in modifications to all lfs-tracked files

### ISSUE THREAD

**Issue by zvinless** [desktop/desktop#3153] opened 2017-10-25 02:53 UTC
### Description
After cloning a repository with lfs-tracked files, GitHub Desktop shows that all lfs-tracked files are modified, even though the repo was freshly cloned. I _believe_ this is the same behavior as cloning an lfs repo without lfs globally installed.

### Version
**GitHub Desktop version:** 1.0.4
**OS version:** macOS High Sierra 10.13

### Steps to Reproduce

1. Click `File -> Clone Repository...` in GitHub Desktop
1. Go to the `URL` tab
1. Type in `zvinless/large-files` into the `URL or username/repository` field
1. Click `Clone`
1. Observe the `Initialize Git LFS` popup
    1. Also observe that behind this popup, there are a bunch of modified files
1. Click `Initialize Git LFS`
1. Observe that all lfs-tracked files still show as modified

<img width="957" alt="clone" src="https://user-images.githubusercontent.com/24303763/31978074-8057b950-b8f4-11e7-819d-b89377149e5c.png">

**Expected behavior:** The repository should have no changes

**Actual behavior:** There are changes in the repository

**Reproduces how often:** 100%

### Logs

[2017-10-25.desktop.production.log](https://github.com/desktop/desktop/files/1413114/2017-10-25.desktop.production.log)

(ignore the part near the end that says `fatal: repository 'zvinless.large-files' does not exist`; I messed up typing in the URL once)

**Comment by tierninho** [comment] 2017-10-25 09:09
Can reproduce.

Logs for mine here:
```2017-10-25T09:05:00.215Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/zvinless/large-files.git - tierninho-tester (has token)
2017-10-25T09:05:05.452Z - info: [ui] Executing clone: git -c credential.helper= lfs clone --recursive --skip-repo --progress -- https://github.com/zvinless/large-files.git /Users/tierninho/Documents/testing/tesdsdsdsdsd/large-files (took 5.234s)
2017-10-25T09:05:05.464Z - info: [ui] [AppStore] adding repository at /Users/tierninho/Documents/testing/tesdsdsdsdsd/large-files to store
2017-10-25T09:05:06.811Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.275s)
 
<img width="954" alt="screen shot 2017-10-25 at 11 09 20 am" src="https://user-images.githubusercontent.com/14828183/31990297-fd01aaa8-b974-11e7-8bba-9492c7f1ccd3.png">

**Comment by joshaber** [comment] 2017-10-25 12:06
I believe this is a known LFS bug, is that correct @technoweenie?

**Comment by joshaber** [comment] 2017-10-25 12:10
Ah, it looks like this was fixed in https://github.com/git-lfs/git-lfs/pull/2647, which should be included in the next GitHub Desktop update.

**Comment by joshaber** [comment] 2017-10-25 12:14
Verified this is fixed in `master` 👍

**Closed by joshaber** 2017-10-25 12:14 UTC
Labels: bug
