### ISSUE TITLE
GitHub menu bar obstructed by Windows Taskbar positioned to top of window

### ISSUE THREAD

**Issue by tdriver** [desktop/desktop#10315] opened 2020-08-03 18:16 UTC
### Describe the bug

When I open GitHub Desktop, the menu bar is obstructed by my windows 10 taskbar.  I have my taskbar fixed to the top of my window, not the bottom.
### Version & OS

GitHub Desktop version 2.5.3, on Windows 10 Pro, build 10.0.18363

### Steps to reproduce the behavior

Move your task bar in Windows from the bottom to the top (see taskbar settings)
Start GitHub Desktop
(it looks like this only occurs when stored app screen coordinates are not present)

### Expected behavior

GitHub Desktop should notice the correct screen coordinates for the task bar and place itself correctly, so it is not obstructed.

### Actual behavior
Once started, notice that you cannot move, exit or click any menu items on GitHub Desktop - they are all obstructed by the taskbar.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment] 2020-08-03 19:59
@tdriver thanks for filing this. It looks to be a duplicate of https://github.com/desktop/desktop/issues/8983, so please follow along there.

**Closed by tierninho** 2020-08-03 19:59 UTC

**Comment by shreyash618** [comment] 2024-01-30 01:20
I have a similar problem on github.com on google chrome while using a macbook. When I click on "Your Profile", and then switch to one of my profile tabs (e.g., "projects"), the menu bar shift up and to the right, until its behind my google search bar. From then on, I can't exit the page since some of the buttons are hidden ("Overview, "Projects, "Packages", "Stars", as well the buttons on the top right area get cut off and hidden by the URL bar). The only way to get out of this page for me is to click back. I've already tried disabling all my chrome extensions but sadly it did not make a difference.
