### ISSUE TITLE
Show user guides opens an old url that doesn't work.

### ISSUE THREAD

**Issue by sebastiendecraene** [desktop/desktop#2806] opened 2017-09-20 22:03 UTC
### Description
When you click the "Show User Guides" it opens a webpage with this [https://help.github.com/desktop-beta/guides/](https://help.github.com/desktop-beta/guides/), which is supposed to be [https://help.github.com/desktop/guides/](https://help.github.com/desktop/guides/) I think.
### Version

**GitHub Desktop version:** 1.0.0
**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Click on  "Show User Guides"

**Expected behavior:** Opening the new link [https://help.github.com/desktop-beta/guides/](https://help.github.com/desktop/guides/)

**Actual behavior:** Opens old link [https://help.github.com/desktop-beta/guides/](https://help.github.com/desktop-beta/guides/)

**Reproduces how often:** Always

**Comment by j-f1** [comment] 2017-09-20 22:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2792. Please follow that issue for further updates.

**Comment by sebastiendecraene** [comment] 2017-09-20 22:14
Okay, sorry for the duplicate.

**Closed** 2017-09-20 23:10 UTC
