### ISSUE TITLE
Changing repo address change it only for push

### ISSUE THREAD

**Issue by firleju** [desktop/desktop#10586] opened 2020-09-16 07:47 UTC
### Describe the bug

After change of repo address app changes config only for pull. Push still aims to old one.

### Version & OS

Version 2.5.5, Win 10 64bit

### Steps to reproduce the behavior

1. Go to 'Repository settings'
2. Change repo primary address
3. Open config file in .git folder
4. Push address didn't change

**Comment by steveward** [comment] 2020-09-16 15:11
@firleju thanks for the report. I was unable to reproduce this on my machine. The output of `git remote -v` shows the correctly changed remote URLs. Are you able to consistently reproduce this?

**Comment by firleju** [comment] 2020-09-16 15:22
I realize, that it happens when you initialize repo from another git client. Then in config you can have:
url=new_address nad pushurl=old_address.

**Comment by steveward** [comment] 2020-09-17 20:09
I looked into this and it seems that Git doesn't update the `pushurl` when it's been explicitly configured (running `git remote set-url <remote> <url>` has the same behavior as GitHub Desktop). Since GitHub Desktop mirrors the same behavior as Git I'm going to throw an `enhancement` label on this and close it out for the time being. My guess is that a different app like Sourcetree allows for setting multiple pushurls which could cause this issue.

If we get enough feedback about this it may be worth reopening and considering better ways to handle these scenarios. Also see https://github.com/desktop/desktop/issues/3894 for some discussion about current issues with having multiple pushurls set. Thanks again for reporting this @firleju.

**Closed by steveward** 2020-09-17 20:09 UTC
Labels: enhancement
