### ISSUE TITLE
HELP！

### ISSUE THREAD

**Issue by ycmbcd** [desktop/desktop#3293] opened 2017-11-10 08:28 UTC
Error: Mode github-diff-syntax failed to advance stream.
    at at (app/node_modules/codemirror/lib/codemirror.js:1639:1)
    at dt (app/node_modules/codemirror/lib/codemirror.js:1693:1)
    at tt (app/node_modules/codemirror/lib/codemirror.js:1539:1)
    at /webpack:/app/node_modules/codemirror/lib/codemirror.js:4063:24
    at Jr.iterN (app/node_modules/codemirror/lib/codemirror.js:5539:8)
    at Bs.iterN (app/node_modules/codemirror/lib/codemirror.js:5651:41)
    at Bs.iter (app/node_modules/codemirror/lib/codemirror.js:6047:14)
    at Do (app/node_modules/codemirror/lib/codemirror.js:4058:1)
    at /webpack:/app/node_modules/codemirror/lib/codemirror.js:148:21

Version: 1.0.7
OS: Mac OS 10.11.6

**Comment by j-f1** [comment] 2017-11-10 11:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3249. There’s a [comment](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) over there with instructions on how to update.

**Closed** 2017-11-10 22:47 UTC

**Comment by mkf85** [comment] 2017-11-10 23:58
Mute

Em 10 de nov de 2017 7:47 PM, Brendan Forster <notifications@github.com> escreveu:

Closed #3293<https://github.com/desktop/desktop/issues/3293>.
