### ISSUE TITLE
[PopOS] Commits/merges taking very long, until you click another GUI element

### ISSUE THREAD

**Issue by GDM95** [desktop/desktop#12372] opened 2021-06-05 00:23 UTC
Description:

Commits and pushes take a very long time to process, UNLESS I click on a GUI element such as the "Changes" or "History", then they go through immediately. Kind of interesting. Deleting local changes is very annoying because you can't click out of the modal and it takes >1.5 mins to process.

Steps to replicate bug:

1. change some local code
2. click commit to master
3. wait
4. click between "History" and "Changes"

**Comment by robertohein** [comment] 2021-06-05 04:33
in kubuntu i just change the size of the window and the load ends. But i dont think they will address this issue since its not supposed to have linux support :(

**Comment by Mrlinkwii** [comment] 2021-06-05 11:03
For the linux version use   https://github.com/shiftkey/desktop/issues  to post issues

**Comment by shiftkey** [comment] 2021-07-06 19:33
If you were using a version before `release-2.8.1-linux3` then you likely didn't have this fix https://github.com/shiftkey/desktop/pull/506 which seemed to address it for making commits at least.

The discussion about why pushes take so long is ongoing in https://github.com/shiftkey/desktop/issues/508, and I suspect it's a similar fix but I'm not sure of the root cause. 

Closing this out to encourage the discussion is happening elsewhere.

**Closed as completed by shiftkey** 2021-07-06 19:33 UTC
