### ISSUE TITLE
Mode github-diff-syntax failed to advance stream.

### ISSUE THREAD

**Issue by OzanKurt** [desktop/desktop#3259] opened 2017-11-07 19:50 UTC
### Description

I have no idea why this happens. It used to work 15 minutes ago.

```
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\Ozan-PC\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\Ozan-PC\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.15063
```

**Comment by ShonM** [comment] 2017-11-07 19:55
Same as above. Updated, now any time it displays a diff it crashes.

```
Error: Mode github-diff-syntax failed to advance stream.
    at at (app/node_modules/codemirror/lib/codemirror.js:1639:1)
    at dt (app/node_modules/codemirror/lib/codemirror.js:1693:1)
    at tt (app/node_modules/codemirror/lib/codemirror.js:1539:1)
    at /webpack:/app/node_modules/codemirror/lib/codemirror.js:4063:24
    at Jr.iterN (app/node_modules/codemirror/lib/codemirror.js:5539:8)
    at Bs.iterN (app/node_modules/codemirror/lib/codemirror.js:5651:41)
    at Bs.iter (app/node_modules/codemirror/lib/codemirror.js:6047:14)
    at Do (app/node_modules/codemirror/lib/codemirror.js:4058:1)
    at /webpack:/app/node_modules/codemirror/lib/codemirror.js:148:21

Version: 1.0.7
OS: Mac OS 10.12.6
```

**Comment by j-f1** [comment] 2017-11-07 19:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3249. Please follow that issue for further updates.

We’re working on getting the fix for this out ASAP.

**Closed** 2017-11-07 20:12 UTC
