### ISSUE TITLE
Discard All changes its not working

### ISSUE THREAD

**Issue by DenisVargas** [desktop/desktop#7779] opened 2019-06-12 16:00 UTC
Right clic over Changed Files does not work, this mean that if i want to discard all the changes, i have to right clic on each change and clic "Discard changes...", or shift select from begining to end all the changes, wich is a big problem when you have 600 or more changes that you dont want to commit and delete them all at the same time.
I dont know if its a bug or intentional, so i send it here.

**Comment by billygriffin** [comment] 2019-06-12 16:03
Hi @DenisVargas, this looks like a duplicate of #7696 and should be fixed in 2.0.4, thanks for the issue. Let us know if it's still not working for you after the latest update.

**Closed by billygriffin** 2019-06-12 16:03 UTC
