### ISSUE TITLE
Crash on Failed Attempt To Publish Test Project 1 -  

### ISSUE THREAD

**Issue by DMWR** [desktop/desktop#2742] opened 2017-09-15 12:41 UTC
TypeError: e.map is not a function
    at a.renderItems (app\src\ui\tab-bar.tsx:88:24)
    at a.render (app\src\ui\tab-bar.tsx:44:4)
    at h._renderValidatedComponentWithoutOwnerOrContext (app\~\react-dom\lib\ReactCompositeComponent.js:810:1)
    at h._renderValidatedComponent (app\~\react-dom\lib\ReactCompositeComponent.js:822:1)
    at h.performInitialMount (app\~\react-dom\lib\ReactCompositeComponent.js:364:1)
    at h.mountComponent (app\~\react-dom\lib\ReactCompositeComponent.js:260:1)
    at Object.mountComponent (app\~\react-dom\lib\ReactReconciler.js:46:1)
    at g.mountChildren (app\~\react-dom\lib\ReactMultiChild.js:232:1)
    at g._createInitialChildren (app\~\react-dom\lib\ReactDOMComponent.js:704:1)
    at g.mountComponent (app\~\react-dom\lib\ReactDOMComponent.js:523:1)

Version: 0.8.1-beta0

OS: Windows 10.0.14393

### Version: 0.8.1-beta0

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

--> 
**GitHub Desktop version:** [0.82]

**OS version:** [Windows 10.0.14393]

### Steps to Reproduce

1. [Open Welover Desktop App ]
1. [Enter "Test Project 1" as project title]
1. [Press the Publish Repository button.]

**Expected behavior:** [To publish my blank test repository online.]

**Actual behavior:** [ Desktop App crashed with error code:

TypeError: e.map is not a function
    at a.renderItems (app\src\ui\tab-bar.tsx:88:24)
    at a.render (app\src\ui\tab-bar.tsx:44:4)
    at h._renderValidatedComponentWithoutOwnerOrContext (app\~\react-dom\lib\ReactCompositeComponent.js:810:1)
    at h._renderValidatedComponent (app\~\react-dom\lib\ReactCompositeComponent.js:822:1)
    at h.performInitialMount (app\~\react-dom\lib\ReactCompositeComponent.js:364:1)
    at h.mountComponent (app\~\react-dom\lib\ReactCompositeComponent.js:260:1)
    at Object.mountComponent (app\~\react-dom\lib\ReactReconciler.js:46:1)
    at g.mountChildren (app\~\react-dom\lib\ReactMultiChild.js:232:1)
    at g._createInitialChildren (app\~\react-dom\lib\ReactDOMComponent.js:704:1)
    at g.mountComponent (app\~\react-dom\lib\ReactDOMComponent.js:523:1)

Version: 0.8.1-beta0
OS: Windows 10.0.14393

]

**Reproduces how often:** [ 100% so far... ]

**Comment by joshaber** [comment] 2017-09-15 14:40
Hi @DMWR! I can't reproduce this and it looks like you're a few versions behind the latest. Try updating to see if that fixes it.

**Comment by joshaber** [comment] 2017-10-10 14:47
I'm going to close this but don't hesitate to reach out if the issue is still happening.

**Closed by joshaber** 2017-10-10 14:47 UTC
Labels: bug, needs-reproduction
