### ISSUE TITLE
"Bringing change to branch" with casing-only rename causes infinite loop

### ISSUE THREAD

**Issue by jorisw** [desktop/desktop#11106] opened 2020-11-23 10:08 UTC
### Describe the bug

When switching to a branch in which a file's filename casing was changed, and choosing to 'bring changes' to the branch, the app is sent into an infinite loop of switching between branches. See video.

### Version & OS

- GitHub Desktop 2.6.0
- macOS Big Sur 11.0.1

### Steps to reproduce the behavior

1. Add a local repo to GitHub desktop
2. Rename `readme.md` to `README.md` and commit
3. Add another change to the file without committing
4. Select another branch that doesn't have the file rename, to switch to
5. Answer "bring my changes" in the dialog box
4. Watch as the app goes into a loop of switching between the two branches

### Expected behavior

The app should not get confused about filename casing and use the filename casing as used in the branch that was switched to

### Actual behavior

App is sent into a loop of switching between branches and redrawing the changed files.

### Screenshots

![foo](https://user-images.githubusercontent.com/30017/99949861-02bbf880-2d7c-11eb-99a9-1ea36ea06311.gif)

**Comment by niik** [comment] 2020-11-23 11:28
Hi @jorisw, thanks for opening this. I believe this is the same issue as https://github.com/desktop/desktop/issues/9297 albeit manifested slightly differently. It'll hopefully be  solved in https://github.com/desktop/desktop/pull/10957. I did a quick try and I couldn't reproduce it but I'm sure I missed some subtlety in the reproduction steps.

I'm gonna try to ship #10957 to our beta channel this week. Would you be up for trying it out once I do and see if you're still able to reproduce it? You can find instructions on how to install the beta channel in our [README](https://github.com/desktop/desktop#beta-channel)

**Comment by niik** [comment] 2020-11-25 12:47
Hi @jorisw, we shipped an update to our beta channel yesterday which includes a change which we believe will fix the issue you've been seeing. Would you be able to try it out and see if you're still able to reproduce the problem on your machine?

**Comment by niik** [comment] 2020-11-27 10:37
I'm almost certain this is the exact same issue as https://github.com/desktop/desktop/issues/11130 and I believe both were "solved" (in so far that we won't trigger an infinite loop any more) in #10957 so I'm going to close this out. If you do get a chance to test the beta channel out please let us know how that went!

**Closed as completed by niik** 2020-11-27 10:37 UTC
Labels: investigation-needed
