### ISSUE TITLE
branch selector is not enabled for unborn repository

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#2760] opened 2017-09-18 03:52 UTC
### Description

A confusing corner case I've just encountered - when you have no branches on the repository, the button doesn't work to expand the branch list. This seems like a defensive maneuver but might confuse people, particularly when it sees "master" mentioned in the branch button.

### Version

**GitHub Desktop version:** `1.0.0-beta3`

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Create a new local repository
1. Undo the first commit
1. Click the branch button

**Expected behavior:** branch list expands, but makes it clear there are no branches

**Actual behavior:** branch list doesn't show expander icon, does nothing when clicked

**Reproduces how often:** 100%

This is what the branch button looks like when there are no branches:

<img width="491" src="https://user-images.githubusercontent.com/359239/30528632-32ba4070-9c78-11e7-8805-1fab27b91128.png">

And this is what you get when you have a valid branch:

<img width="487"  src="https://user-images.githubusercontent.com/359239/30528644-49cb26bc-9c78-11e7-86fc-24367bfa8992.png">

@desktop/core any feels on this experience?

**Comment by joshaber** [comment] 2017-09-18 14:10
I agree, it should show the list 👍 

This looks like a dupe of https://github.com/desktop/desktop/issues/2121 though, so I'ma close it.

**Closed by joshaber** 2017-09-18 14:10 UTC
