### ISSUE TITLE
Improve Options documentation

### ISSUE THREAD

**Issue by SetTrend** [desktop/desktop#13736] opened 2022-01-24 20:13 UTC
After installing *GitHub Desktop* I couldn't fail to notice that there are two input boxes in *Options > Git* that are not getting explained nor are they self-explanatory:

![GitHub Desktop options](https://user-images.githubusercontent.com/9283914/150856636-f6615d53-50d4-46c0-9088-67c5ffbe7a6b.png)

As a user, I wonder: what is supposed to be entered into these two input fields?

Is it, for example:

```
First name

Surname
```

… or …

```
Repository name

Subtitle
```

Please clarify.

### Proposed solution

I propose to add placeholder text to the two text input elements.

Moreover, I suggest do add a documentation web page for each of the Options tabs on GitHub. (Next to [this documentation page](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-and-customizing-github-desktop/setting-a-theme-for-github-desktop).)

**Comment by tidy-dev** [comment] 2022-01-25 13:27
@SetTrend Thank you for the bug report! At first I was unable to reproduce this as I uninstalled it and reinstalled it and during open then app I logged into my github account. Thus, this screen appropriately shows Name = tidy-dev and the second box had the label of Email and was dropdown showing my accounts emails.

Then I realized if you didn't have a name there, it must mean you are not signed in to an account. If you go up to the accounts tab and sign in and then come back to the Git tab, the boxes will be labeled appropriately.

However, I am still labeling this as a bug, as we should have a better UX when person is not logged in (I believe before a recent change, the second input displayed "Email" as the label)

**Comment by SetTrend** [comment] 2022-01-25 13:31
Thank you for your valuable efforts, @tidy-dev!

Yes, your observation is right. I'm currently preparing a VM image for myself, to be cloned and used with different clients of mine. So I cannot log in yet.

**Comment by Joshua698** [comment] 2022-02-01 15:39
Yeh

**Comment by sergiou87** [comment] 2022-07-27 14:32
This was fixed by @andymckay in https://github.com/desktop/desktop/pull/15011 and the fix will be available soon in beta builds 😄 

Thanks for your patience!

**Closed as completed by sergiou87** 2022-07-27 14:32 UTC
Labels: bug, priority-3
