### ISSUE TITLE
Buttons inconsistency on dialogs

### ISSUE THREAD

**Issue by omzy** [desktop/desktop#8640] opened 2019-11-15 17:02 UTC
### Describe the bug

On most dialogs in GitHub Desktop the primary action button is on the left and in blue, and the cancel button is on the right and in light grey - see below:

![image](https://user-images.githubusercontent.com/8927010/68959293-a962d600-07c5-11ea-8fcd-7998f0e0d4f9.png)

![image](https://user-images.githubusercontent.com/8927010/68959384-d2836680-07c5-11ea-9582-2a052cdf0a18.png)

However on the "Remove Repository" and "Delete Branch" dialogs, the order and colour of these buttons is reversed - see below:

![image](https://user-images.githubusercontent.com/8927010/68959609-4160bf80-07c6-11ea-828f-444d9bdef425.png)

![image](https://user-images.githubusercontent.com/8927010/68959646-58071680-07c6-11ea-995e-9b8b86db3448.png)

This can result in users mistakenly clicking the remove/delete button when they intend to press cancel, especially once you have become accustomed to seeing the cancel button on the right.

The buttons should appear consistently, that is the primary action button should always appear on the left and in blue and the cancel button on the right and in light grey.

However I also think any button which performs a "destructive" action should really be in red, as users are normally aware that red signifies danger and will be more cautious before clicking that button.

### Version & OS

2.2.3
Windows 10

**Comment by billygriffin** [comment] 2019-11-15 17:06
Hi @omzy, thanks for the issue! We agree it could be clearer, and we have a PR in review currently that should address some of what you mention here, but not quite your suggested implementation of destructive dialog coloring. I think regardless it'll be a good improvement over what's there today and this is a duplicate of the issues referenced there, so I'm going to close this. Glad we're working on something that should improve this!

**Closed by billygriffin** 2019-11-15 17:06 UTC
