### ISSUE TITLE
Presented with spurious dialog after rebasing

### ISSUE THREAD

**Issue by JeroenBos** [desktop/desktop#16679] opened 2023-05-11 11:11 UTC
### The problem

The normal/expected workflow for a rebase (e.g. a squash) is that you drag a commit onto another in the git history, are presented with a dialog where you enter a description (prefilled with the commit messages aleady), and after clicking "Squash 2 commit" -assuming there are no merge conflict- you return back to the main GitHub Desktop view.

However, what happens instead since (3.2.2 or 3.2.3) is that you're presented with another dialog in which you can enter a description, and this time it is not prefilled with any commit messages.

If you enter a description in that extraneous dialog, and click "Squash 2 commits", then the dialog is presented _again_ and you're in an infinite loop.

### Release version

3.2.3

### Operating system

Windows 10

### Steps to reproduce the behavior

- Assume a linear git history.
- Create a file `./.git/hooks/post-checkout` with the contents `#!/bin/bash` (nothing else)
- Drag the latest commit over the second latest commit (to initiate a squash).
- Click "Squash 2 commits"
- Assume no merge conflicts
- Wait for the squash to finish

### Screenshots

The extraneous dialog:

![image](https://github.com/desktop/desktop/assets/15310631/0b62d51d-25c5-4851-902a-001c090d9e94)

### Additional context

The workaround is simple: after your first rebase just dismiss the second pop-up. But it's a regression nonetheless.

**Comment by sergiou87** [comment] 2023-05-11 12:29
Duplicate of https://github.com/desktop/desktop/issues/16605, fixed in https://github.com/desktop/desktop/pull/16632

Thanks for your report anyway!

**Closed as completed by sergiou87** 2023-05-11 12:29 UTC
