### ISSUE TITLE
Able to stash selected files

### ISSUE THREAD

**Issue by lekhasy** [desktop/desktop#12528] opened 2021-06-28 07:01 UTC
### Describe the feature or problem you’d like to solve

I'm working on a UI project which has some git hook setup. Those hooks will not let anyone commit unless some test passes.
The thing is sometimes working on a feature **X**, I found a bug that already exists and fixes it.
So, I want to commit only the bug fix, not the feature.
But I can't do so because some test for feature X is breaking and it's not easy to fix soon.

So I have a workaround: Comment all failing tests and commit only the part that I want to. But to me it's like a hack and there is a big chance that my commit will break on CI.

Another way around is to stash all files that I don't want to commit => commit => restore the stash => continue to work on feature **X**.

But I'm not the git command guy, that's why I use Github desktop, and this thing happens to me pretty frequently so I don't want to spend the next 5-minute type those commands.

### Proposed solution

So my proposal is to add an option called 'Stash Changes ... ' right below to 'Discard Changes ... ' when you right click on selected files.

This would help me a lot.

**Comment by Matzee** [comment] 2021-06-29 01:20
jo

**Comment by pedropsi** [comment] 2021-07-15 08:55
I've come across a few situations where having this feature would be useful.
So here's a mockup: 
![image](https://user-images.githubusercontent.com/36260325/125759536-1a2f4965-190f-4f74-bc81-5b0ddc6ed679.png)

**Comment by pedropsi** [comment] 2021-07-15 09:14
adding the previous option would align the previous menu with this one, making the whole experience more coherent:
![image](https://user-images.githubusercontent.com/36260325/125762567-30b1765d-672e-4ccc-97f0-74b2e6e1c798.png)

**Comment by felipedrumond** [comment] 2022-03-09 22:39
This would be extremely useful in some scenarios - I'm often stashing all changes that I can't commit but need them locally or need to stash a single file to assess how the software was behaving before my current change on that file.

Unfortunately, I have to do the stash and pop manually, since Git Desktop doesn't handle this scenario.

git stash push -- filename

Now imagine you have modified 15 files but need to stash 5... you need to run this command 5 times!

**Comment by tidy-dev** [comment] 2023-01-24 12:24
Requested in #15988,

**The feature request**
Stash only single files instead of all the changes you have

**Proposed solution**
Right click on single file (that was changed has option to stash only this file)

**Comment by tidy-dev** [comment] 2023-01-24 12:27
Not a real solution to this issue. But a workaround that I use, I will select the changes I want to keep, commit them, then stash the rest of my changes. Then, undo the commit I just made to put the changes I want to keep but not commit yet back into the changed files list.

**Comment by samuelko123** [comment] 2023-05-12 09:15
@tidy-dev Can I give it a try?

**Comment by samuelko123** [comment] 2023-05-12 09:20
Nevermind, I think it is duplicate of #11531.

**Comment by tidy-dev** [comment] 2023-05-12 11:06
Good catch on the duplicate. I will close this one in favor tracking the feedback on that first one.

**Closed as completed by tidy-dev** 2023-05-12 11:06 UTC
Labels: enhancement
