### ISSUE TITLE
Copying the commit message can include more than intended

### ISSUE THREAD

**Issue by NiklasBr** [desktop/desktop#4382] opened 2018-04-03 12:25 UTC
## Description
When selecting and copying the text from a selected commit in the History view the copied text will sometimes also include the [Author part](https://github.com/desktop/desktop/blob/master/app/src/ui/history/commit-summary.tsx#L295).

## Version
* GitHub Desktop: 1.1.1
* Operating system: macOS 10.12.6

## Steps to Reproduce
 1. Select the entire commit message, either by clicking and dragging, or triple-clicking.
 2. Copy (⌘C) the message.
 3. Paste the message somewhere.

### Expected Behaviour
Only copy the selected text. Or make sure that all selected text is shown as selected.

### Actual Behaviour
More text than selected is copied. Or less than is actually selected is shown as selected.

## Additional Information
![2018-04-03 14 21 48](https://user-images.githubusercontent.com/279826/38249015-8ee51cc2-374a-11e8-8de0-2ee4dff7b6d3.gif)

**Comment by iAmWillShepherd** [comment] 2018-04-03 15:53
Thanks for taking the time to open an issue! 🙇          g

**Comment by shiftkey** [comment] 2018-05-02 04:46
There's an interesting quirk here if you decide to keep selecting text below the title:

![](https://user-images.githubusercontent.com/359239/39505468-caeff5de-4e15-11e8-977e-d60c48c11a34.gif)

It looks like what happening here is that you can continue dragging the cursor to select text elements, even if `user-select: none` is set on those elements.

Not sure of the best way to manage this, probably needs someone more familiar with this part of the CSS spec who knows what's possible here.

**Comment by j-f1** [comment] 2018-05-02 10:04
Putting all selectable text in a borderless, readonly `<input>` might help. Selections there are constrained to the bounds of the input.

**Comment by iAmWillShepherd** [comment] 2018-05-02 20:05
I actually tried tackling this and used the `user-select: none` property with no luck.
Also, thanks for the tip @j-f1 👍

**Comment by shiftkey** [comment] 2018-05-09 23:30
Adding `help wanted` because the steps are easy enough to reproduce - it just needs someone with some CSS chops who can figure out the solution.

**Comment by AndreiMaga** [comment] 2020-02-11 19:26
Is this still an issue? I can't reproduce it on Windows.

**Comment by outofambit** [comment] 2020-02-11 21:48
@AndreiMaga thanks for the ping! i was able to reproduce this on mac by triple-clicking, but not by clicking and dragging (unless i dragged down past the author field). i think this means the 90% case is fixed. going to close this issue for now.

**Closed by outofambit** 2020-02-11 21:48 UTC
Labels: bug, help wanted, priority-3
