### ISSUE TITLE
Desktop does not use OpenSSH on Windows if running, favours embedded SSH

### ISSUE THREAD

**Issue by richardbushell** [desktop/desktop#5641] opened 2018-09-14 08:32 UTC
There seems to be no support for the Native Windows 10 Authorisation using the built-in ssh-agent.

Windows 10 now provides it's own built-in implementation of openssh. And it provides its own ssh-agent as a Windows Service for storing PassPhrases.

BUT I cannot get GitHub Desktop to work using the Keys setup with the Windows ssh-agent, so Pushing always fails to any private repositories on servers when using SSH.

When will the NATIVE Windows ssh-agent service be supported in GitHub Desktop application?

**Comment by shiftkey** [comment] 2018-09-14 14:07
@richardbushell thanks for the report! It's not clear to me how you've configured your `ssh-agent` setup, and I'm pretty sure a vanilla `ssh-agent` setup with passphrases works fine with Desktop, so could you clarify a couple of things:

 - is the Git operation failing because it needs a passphrase and is failing to look it up? Could you share an example of the error from the log files (open **Help** | **Show Logs in Explorer**)?
 - I've not had a chance to look at the latest OpenSSH work that's gone into Windows 10 - can you point me to some details about how this Windows Service works to remember your passphrase?

**Comment by richardbushell** [comment] 2018-09-14 14:45
Windows 10 (Spring 2018) added a direct implementation of openssh into Windows.
It therefore supports all of the openssh commands directly on the Windows command-line, and makes PuTTY and Pageant obsolete.

You run ssh-agent and ssh-add as normal but these run the built-in Windows executables.
Windows runs ssh-agent as a SERVICE, which can be enabled to run Manually, or Automatically on Windows startup (it is set to Disabled by default).

But it then uses the Windows ssh-agent service to provide PassPhrase responses automatically. There is no need for PuTTY+Pageant or a separate Bash ssh-agent any more. Just need to let Windows handle this NATIVELY.

**Comment by shiftkey** [comment] 2018-09-16 17:38
I was able to reproduce this issue, and it comes down to Desktop choosing to use it's internal `ssh` program (which doesn't know about the `ssh-agent` service associated with OpenSSH on Windows which runs as a Windows Service) over anything that might be defined on `PATH`.

The workaround for this is to change your global configuration to use the OpenSSH for Windows build of SSH:

```
git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
```

Or in your `~/.gitconfig`:

```
[core]
	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
```

**Comment by richardbushell** [comment] 2018-09-16 20:40
@shiftkey Thanks, that workaround works perfectly to bypass the embedded SSH. It should be a relatively simple fix to get into a subsequent release too asap. Obviously most users will switch to the native Windows SSH service as word spreads and they realise it's now built in without bash or third-party plugins.

**Comment by killroy42** [comment] 2018-11-04 18:56
I'm still struggling. I can get git in WSL to work, and git in windows. But Github desktop still fails. Is there anything else it's doing different than git.exe on the command line?

**Comment by yehudamakarov** [comment] 2019-03-20 18:49
> I was able to reproduce this issue, and it comes down to Desktop choosing to use it's internal `ssh` program (which doesn't know about the `ssh-agent` service associated with OpenSSH on Windows which runs as a Windows Service) over anything that might be defined on `PATH`.
> 
> The workaround for this is to change your global configuration to use the OpenSSH for Windows build of SSH:
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> ```
> Or in your `~/.gitconfig`:
> 
> ```
> [core]
> 	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
> ```

@shiftkey I just tried this, and now any time I try to push or pull from github desktop or vs code, the loading spinner spins indefinitely, and the push/pull never finish. any ideas?

**Comment by yehudamakarov** [comment] 2019-03-20 19:03
I undid the change, and removed my passphrase from the key. I'm finally free.

**Comment by steveward** [comment] 2019-03-21 17:33
@yehudamakarov would you be willing to upload the log file from GitHub Desktop so I could take a look at what might have happened there? I've tested this a bit to confirm it works, so I want to be sure there is not something I am missing.

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by yehudamakarov** [comment] 2019-03-21 19:08
I can do that. But not right this second. Tomorrow at work I should be able to.


Yehuda Makarov

**Comment by nsgamezz** [comment] 2019-03-25 00:22
I don't know if this will help everyone, but what I did is just signed out and signed back into GitHub Desktop, and it fixed the problem. Such a simple fix.

**Comment by srianbury** [comment] 2019-03-31 19:43
How do you undo `git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"` ?

**Comment by yehudamakarov** [comment] 2019-03-31 19:49
You can `git config —list` or something similar to list all the settings. One of these should be core.sshCommand, and it should point to a value.

Google the values for core.sshCommand and set your setting to the default value.


Yehuda Makarov

**Comment by srianbury** [comment] 2019-03-31 20:08
I was unable to find the default value to replace `C:\Windows\System32\OpenSSH\ssh.exe`  with so I just opened the config file in a text editor and deleted that line.  Everything went back to normal.

**Comment by yehudamakarov** [comment] 2019-03-31 20:23
If you delete the line it will use the default value as far as I know. So good job.


Yehuda Makarov

**Comment by b0810** [comment] 2019-04-01 04:39
Bonjour mon ami, Vous savez si vous acheter ce site de builderall qui peut vous faire gagner vos premiers millions dans les trois qui suivent, personne ne le saura, ne soyez pas coincé vous êtes libre de faire ce que vous voulez non alors pourquoi attendre cliquez sur ce lien  https://checkout-fr-44.location-builderall.com/?slug=builderall-eur-commercial-44&sd=checkout-fr-44   Faites le si vous êtes un homme digne de ce nom et vous serez riche comme un crésus, le voulez vous devenir riche oui ou non ? Merci pour votre décision, qui sera bonne j'espère !BORATH YUN

  Le 31 mars 2019 à 21:43, Brian Sunbury <notifications@github.com> a écrit :
 
 
 How do you undo git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'" ?

**Comment by lsalex133** [comment] 2019-06-17 10:48
> I was able to reproduce this issue, and it comes down to Desktop choosing to use it's internal `ssh` program (which doesn't know about the `ssh-agent` service associated with OpenSSH on Windows which runs as a Windows Service) over anything that might be defined on `PATH`.
> 
> The workaround for this is to change your global configuration to use the OpenSSH for Windows build of SSH:
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> ```
> 
> Or in your `~/.gitconfig`:
> 
> ```
> [core]
> 	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
> ```


How and where i can run the code?
p.s. I never work with github code

**Comment by shawnz** [comment] 2019-06-17 12:15
Type it in any terminal. For example, right click the Start button, click Windows Powershell, and type it there

**Comment by steveward** [comment] 2019-06-17 14:08
@lsalex133 you can find the `.gitconfig` file in your `User` directory (C:\Users\<Your_User\.gitconfig) or you go to GitHub Desktop and select `Repository` > `Open in command prompt` and run the `git config` command from the command line. Let me know if you run into any problems.

**Comment by Convincible** [comment] 2019-08-29 16:32
I managed to get GitHub Desktop to use Windows' native OpenSSL following advice above, setting `sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'` in `~/.gitconfig`, after enabling the built-in OpenSSL service.

I have been able to load and work with a repo, however when it finally came to push it back to origin, I got the error:
```
warning: agent returned different signature type ssh-rsa (expected: rsa-sha2-512)
error: couldn't set 'refs/remotes/origin/_____'
```

Some snooping online suggests this may be the result of the built in Windows OpenSSL being out of date, but upgrading it manually will be a very dodgy process (and I'm not even sure this is really the issue).

Can anyone shed any light?

**Comment by Convincible** [comment] 2019-08-29 21:37
Ignore me. The real error appeared to be what followed:
```
unable to update local ref
```
Which was resolved by: https://stackoverflow.com/a/27278221/8792532
```
git gc --prune=now
```
In short I've got this 100% working!

**Comment by lazyJoon** [comment] 2021-03-27 21:34
> @shiftkey 
> I was able to reproduce this issue, and it comes down to Desktop choosing to use it's internal `ssh` program (which doesn't know about the `ssh-agent` service associated with OpenSSH on Windows which runs as a Windows Service) over anything that might be defined on `PATH`.
> 
> The workaround for this is to change your global configuration to use the OpenSSH for Windows build of SSH:
> 
> ```
> git config --global core.sshCommand "'C:\Windows\System32\OpenSSH\ssh.exe'"
> ```
> 
> Or in your `~/.gitconfig`:
> 
> ```
> [core]
> 	sshCommand = 'C:\\Windows\\System32\\OpenSSH\\ssh.exe'
> ```
---
## I tried this but I failed...

- github desktop log

> 2021-03-27T21:13:40.436Z - info: [ui] [AppStore] loading 6 repositories from store
> 2021-03-27T21:13:40.648Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
> 2021-03-27T21:13:40.706Z - info: [ui] launching: 2.6.6 (Windows 10.0.18363)
> 2021-03-27T21:13:40.706Z - info: [ui] execPath: 'C:\Users\DJ\AppData\Local\GitHubDesktop\app-2.6.6\GitHubDesktop.exe'
---
- git bash or powershell (or command propt)

> $ git push
> fatal: The current branch main has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin main

> $ git pull
> CreateProcessW failed error:193
> ssh_askpass: posix_spawn: Unknown error
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
---

And, when I try to push or pull from github desktop or vs code, the loading spinner spins indefinitely, and the push/pull never finish.
Please let me solve this :(

**Closed** 2021-08-11 08:29 UTC
Labels: bug, windows, priority-2
