### ISSUE TITLE
Can't clone repository (unable to check certificate)

### ISSUE THREAD

**Issue by FrostedB** [desktop/desktop#6372] opened 2018-12-08 16:10 UTC
## Description

Any attempt to clone a repository is denied, including repositories I uploaded to the website myself and have the source code for. I even tried reinstalling the Git for Desktop. No luck. Hasn't worked since I installed it. 
![image](https://user-images.githubusercontent.com/17092399/49687976-4064df80-fad9-11e8-9a84-499992d5e8f9.png)

## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment] 2018-12-08 17:59
Thanks for contributing @FrostedB!

This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

We also have seen cases where this error has been caused by certain antivirus software like Kaspersky. If you are running Kaspersky or another brand of antivirus software I would recommend trying to temporarily disable it to see if that resolves this issue.

I'm going to close this issue out since we have a known workaround, but please let me know if you are unable to resolve this.

**Closed by steveward** 2018-12-08 17:59 UTC

**Comment by Codedevlo** [comment] 2018-12-13 17:40
A fix is to replace http://* or https://* to git://*
