### ISSUE TITLE
EOL Always defaults to CRLF

### ISSUE THREAD

**Issue by hgdagon** [desktop/desktop#14308] opened 2022-04-08 11:34 UTC
### The problem

Every time I clone a new repository, I need to manually turn off AutoCRLF and set EOL to LF. Even if  `.gitattributes` file is present, my local copy defaults to CRLF.

### Release version

2.9.12 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Clone a reposity.
2. Check EOL

**Comment by steveward** [comment] 2022-04-08 15:10
@hgdagon can you share the output of `git config --list --show-origin`?

**Comment by hgdagon** [comment] 2022-04-08 15:55
Here's the log. Since I'm working in this repo now, I have already set it to LF:

```bash
$ git config --list --show-origin
file:/etc/gitconfig     core.eol=lf
file:/etc/gitconfig     core.autocrlf=false
file:/home/George/.gitconfig    core.autocrlf=false
file:/home/George/.gitconfig    core.eol=lf
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/hgdagon/assimp.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        remote.upstream.url=https://github.com/assimp/assimp.git
file:.git/config        remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
```

The commands I'm running after cloning new repos are as follows:

```bash
git config --global core.eol lf
git config --global core.autocrlf false
git reset --hard
```

And in Repository settings in GH Desktop I have it set to use my global config for all my repos.

**Comment by steveward** [comment] 2022-04-12 17:46
@hgdagon is there anything in your `.gitattributes` that could be overriding the config? It's generally recommended to use the `.gitattributes` file to manage line endings since it ensures consistency.

**Comment by hgdagon** [comment] 2022-04-12 21:04
The repos I'm working with either don't have a `.gitattributes` file or the file explicitly sets all file types to lf. Yet after cloning my local copies are converted to crlf.

**Comment by steveward** [comment] 2022-09-13 13:14
@hgdagon is this still an issue you are encountering? This isn't something that should be caused by GitHub Desktop, since it respects your Git configuration settings. Have you tried cloning via the command line to see if you hit the issue there as well?

I'm going to close this out, but let me know if I can help with any further questions.

**Closed as completed by steveward** 2022-09-13 13:14 UTC
