### ISSUE TITLE
Cannot clone from githu

### ISSUE THREAD

**Issue by ruoyu0411** [desktop/desktop#2906] opened 2017-09-29 06:27 UTC
### Description

During clone printout the issue:
![image](https://user-images.githubusercontent.com/32382341/31003423-3791d470-a522-11e7-8eec-7a4f29aa1ffa.png)

### Version
![image](https://user-images.githubusercontent.com/32382341/31003442-4cc55d08-a522-11e7-9795-65ee368ae7f0.png)

**GitHub Desktop version:** [version here]

**OS version:
![image](https://user-images.githubusercontent.com/32382341/31003474-766c2efc-a522-11e7-8e15-449ab31c8c24.png)

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment] 2017-09-29 06:58
@ruoyu0411 thanks for the report. This is a duplicate of #2897 which should be fixed in the next update.

**Closed by shiftkey** 2017-09-29 06:58 UTC
