### ISSUE TITLE
Window is offscreen, won't come back on monitor

### ISSUE THREAD

**Issue by aleccaputo** [desktop/desktop#2893] opened 2017-09-27 14:17 UTC
### Description

Had the new github desktop open, unplugged a monitor at some point and it must have been open on that one. Now when I try to open the window, it seems to open off-screen. Now i can't get it back onto any of my other monitors (tried windows key + arrow keys, shift right clicking the icon on the taskbar doesn't show the "move" option. Tried uninstalling and re-installing, still happens). I think the main problem here is the shift+right click on the icon doesn't bring up any options. 

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Windows 10

### Steps to Reproduce

1. Have 2 1440p monitors connected
2. unplug one, plug in a 1080p monitor 
NOTE: both of these steps i'm pretty sure was the initial issue, though I can't try again since I can't get the window to come back. 
3. Github desktop is now "off the screen" (this isn't abnormal for windows).
4. try all "window moving" tricks on windows (cascade, alt+tab, windows key+arrow keys) None work.
5. Try shift+right clicking the icon to "move", notice the windows dropdown doesn't appear (also doesn't show up on co-workers "working" github window).
6. Uninstall/re-install
7. Problem persists. 
8. NOTE: Old version of Github was installed (and working) this whole time.

**Expected behavior:** Window should open and be visible when I click the icon.

**Actual behavior:** Window seems to appear off-screen, but I can't use any of the windows troubleshooting methods to get it back on-screen 

**Reproduces how often:** Once, since I can't get the window to show up on the screen even after uninstall/restart/

**Comment by aleccaputo** [comment] 2017-09-27 14:30
Well, fixed my own issue. 
1. Hit Alt+M to bring up the menu I couldn't with shift+right click.
2. Press 'M' to make it move
3. now moving your mouse will have the window attached to it. Move it wherever until it shows up.

Still strange that Uninstalling the program and reinstalling didn't default it to opening on one of my two active monitors.

**Comment by NassirAlawar** [comment] 2017-09-28 15:57
Alt+M Did not work for me.
Solved by going into %APPDATA%\GitHub Desktop\window-state.json and changing the window position.

**Comment by aleccaputo** [comment] 2017-09-28 20:05
Make sure that the window was "open" and selected before doing it?

**Comment by NassirAlawar** [comment] 2017-09-28 20:14
Yeah, I also tried to move the window when I got it back in view and Alt+M also didn't work. I right clicked the github icon and selected move and even then I couldn't move the window though the usually 4 direction pointer finally showed up. The only way I'm able to move the window is by clicking on the bar at the top with the normal pointer.

Same as you the Windows key + arrow years didn't respond when the window was off screen

**Comment by BertLamb** [comment] 2017-10-03 00:25
>Try shift+right clicking the icon to "move", notice the windows dropdown doesn't appear (also doesn't show up on co-workers "working" github window).
To me, this seems potentially the easiest part to fix (knowing absolutely nothing about why it is broken 😄).  I have had issues before with other apps ending up off screen and have used this right click menu trick to get them back.  It is unclear *why* GitHub desktop is missing this right click menu.  It should have it though, and that should be fixed.

**Comment by BertLamb** [comment] 2017-10-03 00:26
>Try shift+right clicking the icon to "move", notice the windows dropdown doesn't appear (also doesn't show up on co-workers "working" github window).

To me, this seems potentially the easiest part to fix (knowing absolutely nothing about why it is broken :smile:). I have had issues before with other apps ending up off screen and have used this right click menu trick to get them back. It is unclear why GitHub desktop is missing this right click menu. It should have it though, and that should be fixed.

**Comment by joshaber** [comment] 2017-10-10 14:49
This looks like a duplicate of https://github.com/desktop/desktop/issues/2107, so we'll continue to track it over there. Feel free to follow along!

**Closed by joshaber** 2017-10-10 14:49 UTC
Labels: bug

**Comment by pale2hall** [comment] 2018-02-21 19:23
@aleccaputo,

It's Alt+Space.

I was also able to fix it by right clicking the launcher, choosing Launch Full-Screen, and re-launching it.

**Comment by JasonStapley** [comment] 2018-05-09 09:47
Following the advise of NassirAlawar with a little modification for the lazy like me I closed Git client and deleted the file
%APPDATA%\GitHub Desktop\window-state.json

This did the trick!!

**Comment by tengbao** [comment] 2018-05-16 04:01
A little easier than editing the AppData JSON file, this also worked for me: 

1. Right-click the GitLab Desktop shortcut, click Properties, go to the Shortcut tab
2. Set Run to "Maximized", like this:

![The Library of Babel](https://www.computerhope.com/tips/images/maximized.jpg)

(from https://www.computerhope.com/tips/tip201.htm)

**Comment by laurenth-unity** [comment] 2018-10-03 07:58
I checked the json and I had it at -32000 -32000, I believe I cannot have set this myself :)

**Comment by ddowling-act** [comment] 2018-10-10 14:20
Still an issue. Happens after undocking my laptop having had the app on another screen. Should be able to shift+right click the taskbar icon but this does nothing. Edited the window pos json and got it back.

**Comment by mikependon** [comment] 2018-11-09 16:02
> Alt+M Did not work for me.
> Solved by going into %APPDATA%\GitHub Desktop\window-state.json and changing the window position.

Thanks for this man. This helps!

**Comment by ooojustin** [comment] 2018-11-29 15:07
Just delete the window-state.json file. It'll reset the location.
If I'm being entirely honest, I'm not sure why it's necessary to save the location.
Even so, it should store the number of monitors and their resolutions in window-state and reset if either of those change.

**Comment by c-snipe** [comment] 2019-01-01 22:31
This is still an issue.

**Comment by sterlingfire** [comment] 2019-01-07 18:45
> Alt+M Did not work for me.
> Solved by going into %APPDATA%\GitHub Desktop\window-state.json and changing the window position.

You are a hero!

**Comment by idebtor** [comment] 2019-01-12 11:09
This should still be an issue.  

1. A simple solution is to remove the following file ('user' in my case).
    C:\Users\user\AppData\Roaming\GitHub Desktop\window-state.json
2. Restart GitHub Desktop.
<><

**Comment by amjad** [comment] 2019-02-28 01:08
> @aleccaputo,
> 
> It's Alt+Space.
> 
> I was also able to fix it by right clicking the launcher, choosing Launch Full-Screen, and re-launching it.

This worked for me. Thank you!

**Comment by pjlasl** [comment] 2019-05-11 01:09
> Alt+M Did not work for me.
> Solved by going into %APPDATA%\GitHub Desktop\window-state.json and changing the window position.

%APPDATA%\**roaming**\GitHub Desktop\window-state.json

**Comment by trevren11** [comment] 2019-05-22 20:06
Still an issue

**Comment by shiftkey** [comment] 2019-05-22 21:31
@trevren11 we believe this has been fixed in #7541 and will be available with the upcoming `1.7.0` release. It'll also be available on our beta channel after the next update (aiming for later this week).

**Comment by NicsonMartinez** [comment] 2019-05-31 22:52
I had the same issue:
Going to C:\Users\username\AppData\Roaming\GitHub Desktop\window-state.json
and deleting that 'window-state.json' file fixed the problem! :D

**Comment by kerihobo** [comment] 2020-02-29 05:01
> Following the advise of NassirAlawar with a little modification for the lazy like me I closed Git client and deleted the file
> %APPDATA%\GitHub Desktop\window-state.json
> 
> This did the trick!!

Licecap was off-screen for me despite win+tab or shift+cClick+move. This fixed it for me in the appdata, cheers!

**Comment by treysis** [comment] 2020-04-06 17:42
> Yeah, I also tried to move the window when I got it back in view and Alt+M also didn't work. I right clicked the github icon and selected move and even then I couldn't move the window though the usually 4 direction pointer finally showed up. The only way I'm able to move the window is by clicking on the bar at the top with the normal pointer.
> 
> Same as you the Windows key + arrow years didn't respond when the window was off screen

After clicking "Move", you need to press one of the arrow keys, and only that! Not Win+Arrow, just one arrow key! Then it will "snap" to the mouse cursor and can be moved.
