### ISSUE TITLE
unable to stash on protected branch v2.2.4

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#8803] opened 2019-12-17 04:29 UTC
### Describe the bug

unable to stash changes on protected branch

### Version & OS

Windows 10 (v2.2.4)

### Steps to reproduce the behavior

1. Go to a protected branch
2. make some changes 
3. trying to switch to another branch

### Expected behavior

I should be able to stash changes on the current protected branch

### Actual behavior

desktop brings all changes to the new branch 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by Rexogamer** [comment] 2019-12-17 16:44
We auto-stash changes on protected branches without prompting due to #8714, so IIRC your changes will go to the branch you select.

**Comment by tierninho** [comment] 2019-12-17 17:48
@Justin-JHG I am confirming this is intended behavior. Please share any thoughts (if any) on the need to stash files on a protected branch. We are curious if you have a situation we didn't consider. Thanks!

Closing this issue for now.

**Comment by Justin-JHG** [comment] 2019-12-17 21:30
hi @tierninho 
normally we deleting local feature branches after PR merged. some of the changes we don't want to commit but is useful so prior to 2.2.4 we switch back to development branch and stash them and then switch back to feature branch to delete the feature branch. 

Now there is no way to stash the changes to development branch to be used for new feature branches created off development branch. 

hope you can bring this feature back, even make it as a switch so that users want it can enable it

Thanks

**Comment by tierninho** [comment] 2019-12-17 22:08
@Justin-JHG appreciate the feedback on this issue.  Give us some time to circle back due to the holidays.

cc @billygriffin for 👀

**Comment by Justin-JHG** [comment] 2019-12-17 22:12
thank you @tierninho 
Desktop is a great tool for use. thank you for all the work you guys have done. 

just wondering how can we make sure this issue being looked after once holiday is over. as it is closed, I'm worried it will be forgotten. 

Thanks

**Comment by Justin-JHG** [comment] 2019-12-18 00:03
Thank you for re-open it

**Comment by billygriffin** [comment] 2019-12-20 18:40
Hi @Justin-JHG, thank you for so clearly describing your workflow. We made a call to disable the stashing modal when you're leaving a protected branch because we're trying to balance the friction it causes with giving people the choice as much as possible. This is intended behavior, and we didn't anticipate your workflow. Given the tradeoffs we're trying to balance, I'm going to close this for now because we think for the vast majority of people our direction is still the right choice. However, as with all decisions we make, if we continue to see evidence that it's causing more widespread problems, we are certainly open to revisiting. I know that's not what you want to hear and I'm sorry that it's making the product less useful for you. Thank you again for the clear report.

**Closed by billygriffin** 2019-12-20 18:40 UTC
Labels: enhancement

**Comment by Justin-JHG** [comment] 2020-02-16 21:39
hi @billygriffin, @tierninho, @Rexogamer 

Thank you for the comments you made. 

this is still a pain for our devs currently. I mean Desktop still allows users to commit to a protected branch at local. I just can't understand why commit is allowed but stash is not 

Please reconsider to add it back, at least make it an option so that users can choose to use it or not. 

Thanks
Justin

**Comment by Justin-JHG** [comment] 2020-02-16 23:30
![image](https://user-images.githubusercontent.com/41654878/74614932-3e33f180-5170-11ea-8679-d73bdff28543.png)

![image](https://user-images.githubusercontent.com/41654878/74614939-5146c180-5170-11ea-9619-22a19fed4e5a.png)

FYI - for whoever having the same issue, I just realised we can use Commit as Stash on protected branches. 
And you can undo the commit after as applying the stash without leaving a commit trail on the branch
