### ISSUE TITLE
[Stashing] New files not supported in stash diff view

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7282] opened 2019-04-12 19:43 UTC
This issue came back from @desktop/quality-assurance while testing https://github.com/desktop/desktop/pull/7210#issuecomment-482394496

Try stashing a picture and viewing the diff of the stashed file.

**Comment by tierninho** [comment] 2019-04-12 20:11
Also, empty files and new files do not appear to be rendering in the diff view.

**Comment by outofambit** [comment] 2019-04-12 22:10
@tierninho could you add to the description above with some reproduction steps? I've seen stashed images in the diff viewer so it would be great to see how you're getting there.

**Comment by tierninho** [comment] 2019-04-12 23:13
Based on 3353652b40 I think I isolated the root of the problem down to and stashing any new files with or without changed or deleted files. It doesn't matter because in the end any new files won't show in the stash.

Repro:
- Create new file
- Stash it

Before stash:
<img width="443" alt="Screen Shot 2019-04-12 at 1 12 23 PM" src="https://user-images.githubusercontent.com/14828183/56070643-b3e75980-5d24-11e9-9885-f258efe7b464.png">

After stash:
<img width="439" alt="Screen Shot 2019-04-12 at 1 12 34 PM" src="https://user-images.githubusercontent.com/14828183/56070644-b47ff000-5d24-11e9-9035-fa72d2e1a3bf.png">

Related to this, the placeholder text needs some padding ⬆️

**Comment by outofambit** [comment] 2019-04-15 15:58
thanks @tierninho! closing this in favor of #7287, since its the same thing. Can you file a new issue for "Related to this, the placeholder text needs some padding ⬆️"? thank you!

**Closed by outofambit** 2019-04-15 15:58 UTC
