### ISSUE TITLE
GHE avatars are not loading anymore

### ISSUE THREAD

**Issue by zalewskise** [desktop/desktop#18034] opened 2024-01-17 21:13 UTC
### The problem

As the title says, GHE avatars are not loading anymore. Instead of actual avatar, it keeps showing placeholder icon.

### Release version

3.3.7-beta3

### Operating system

MacOS

### Screenshots

![Screenshot 2024-01-17](https://github.com/desktop/desktop/assets/49704887/ede55031-5d0f-4ccd-bcae-024a0e14b6f6)

**Comment by steveward** [comment] 2024-01-17 21:38
Thanks for the report @zalewskise, just confirmed this is an issue as well. I was on v3.3.7-beta2 and updating to 3.3.7-beta3 broke avatars. Going to loop in @niik on this since https://github.com/desktop/desktop/pull/17991 was merged last week.

**Comment by niik** [comment] 2024-01-18 06:57
Yeah this is my bad! And to make matters worse this snuck into the 3.3.7 production release as well which is currently partially rolled out. I've opened https://github.com/desktop/desktop/pull/18036 which will address this and I'll discuss with the team when we could ship an updated version to resolve this.

**Closed as completed** 2024-01-18 11:48 UTC
Labels: bug, priority-3

**Comment by tidy-dev** [comment] 2024-01-18 14:02
@zalewskise Release 3.3.8 is out with the fix.

Note: We do staggered auto update rollouts so it is possible that if you hit "Check for updates" in the about dialog, it will not show yet. If so, you can download the latest (3.3.8) from desktop.github.com or wait till the rollouts reach your machine.

**Comment by zalewskise** [comment] 2024-01-18 20:49
Thank you for quick fix! Works like a charm now :)

**Comment by Chinczyk666** [comment] 2024-03-07 16:33
$ gpg --list-secret-keys --keyid-format=long
/Users/hubot/.gnupg/secring.gpg
------------------------------------
sec   4096R/3AA5C34371567BD2 2016-03-10 [expires: 2017-03-10]
uid                          Hubot <hubot@example.com>
ssb   4096R/4BB6D45482678BE3 2016-03-10
