### ISSUE TITLE
Rebase does not work when it would be a fast-forward

### ISSUE THREAD

**Issue by ruddzw** [desktop/desktop#9226] opened 2020-03-05 15:25 UTC
### Describe the bug

I have two branches, Branch A and Branch B. Branch B was made off of Branch A in the past. I did some work on branch B in my working directory, but have not made any commits. Others have worked on Branch A and it now has newer commits that are not on Branch B yet. Before committing my work on Branch B, I want to bring it back up to match Branch A. It would be a fast-forward, so a merge would work. But my general workflow is to use rebase whenever it wouldn't affect anyone else. I go to rebase on top of Branch A but GitHub Desktop tells me "This branch is up to date with Branch A". If I head to the terminal and type "git rebase branch-a" it works as expected, and fast-forwards Branch B to match Branch A.

### Version & OS

Version 2.3.1, macOS Catalina (10.15.3)

### Steps to reproduce the behavior

1. Go to Branch -> Rebase Current Branch
2. Click on desired branch (Branch A)
3. See erroneous "up to date" message

### Expected behavior

I am able to fast-forward rebase, as in the CLI version.

### Actual behavior

A message stops me from being able to initiate the rebase.

### Screenshots

<img width="450" alt="Screen Shot 2020-03-05 at 10 22 03 AM" src="https://user-images.githubusercontent.com/52619/75996191-7dca3f80-5ecb-11ea-850e-0e2312326d46.png">

### Logs

N/A

### Additional context

N/A

**Comment by kuychaco** [comment] 2020-03-06 01:37
@ruddzw if I'm understanding your description correctly, I believe you're unable to rebase because you have not yet made any commits. 

>  did some work on branch B in my working directory, but have not made any commits.

While it's true that you have changes, sine you haven't committed them to BranchB it is still up to date with BranchA. 

Command line doesn't allow rebases with working directory changes:
```
➜  test-repo git:(branchB) ✗ git rebase branchA
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```

In order to rebase, you could commit your changes to branchB, rebase onto branchA, and then hit the "Undo" button to put your changes back into the working directory. 

I'm going to close this issue for now since I believe the behavior you are experiencing is as expected / by design, but if I'm misunderstanding or if my response doesn't seem to address your issue please feel free to re-poen it.

**Closed by kuychaco** 2020-03-06 01:37 UTC

**Comment by ruddzw** [comment] 2020-03-06 21:54
@kuychaco

> Command line doesn't allow rebases with working directory changes

Sorry, I forgot that I had actually stashed them rather than left them in my working directory. However, the issue remains regardless of whether any work has been stashed on the branch or in the working directory. It should be possible to take branch B and rebase it on branch A to bring it up to match branch A. Here's an example:

```
(master) $ git branch
* master
(master) $ git branch branchB
(master) $ git add -A
(master) $ git commit -m "change"
[master 482e152] change
 1 file changed, 1 insertion(+), 1 deletion(-)
(master) $ git branch branchA
(master) $ git checkout branchB
Switched to branch 'branchB'
(branchB) $ git rebase branchA
First, rewinding head to replay your work on top of it...
Fast-forwarded branchB to branchA.
```

**Comment by ruddzw** [comment] 2020-03-06 21:57
I don't have permission to re-open this issue but I have updated the issue text to remove the bits about the working directory as it was irrelevant/wrong.
