### ISSUE TITLE
Cloning message using folder name instead of repository name

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#3938] opened 2018-02-05 21:09 UTC
### Description
When cloning a new repository, a large header is displayed which says something along the lines of "Cloning <name>" along with the progress.

I noticed however that it uses the name of the folder that you're cloning into as the "name" of the repository, which probably should be the repository name instead.

E.g. my repository was called `foo-bar`, but I cloned this into `/Sites/foo/bar` locally.
Github desktop reported this as "Cloning bar" instead of "Cloning foo-bar".

Minor issue, but thought I'd report it.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** OS X

### Steps to Reproduce
1. Clone a repository `foo` into a folder called `bar`

**Expected behavior:** [What you expected to happen]
The message should say "Cloning foo"

**Actual behavior:** [What actually happened]
The message says "Cloning bar"

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% from what I could see but haven't tested extensively

**Comment by shiftkey** [comment] 2018-02-05 21:46
I think this is because we favour using the GitHub repository name in the UI over the physical folder location whenever possible - the same behaviour occurs in the repository list when we detect a repository is from GitHub or GitHub Enterprise.

**Comment by adamreisnz** [comment] 2018-02-05 21:56
Do you mean the opposite?

The problem is that the physical folder name is displayed -- not the GitHub repository name.

**Comment by shiftkey** [comment] 2018-02-05 22:00
@adamreisnz oops, I did misread it. The message you're looking at is from here: 

https://github.com/desktop/desktop/blob/b6431e6e0a782e1cde78b7fcdb5a56e872596e62/app/src/ui/cloning-repository.tsx#L25-L28

I think we kept this choice here because you can clone from an arbitrary URL, and we probably haven't refreshed the repository information from the API at this point in the process.

**Comment by shiftkey** [comment] 2018-02-05 22:16
Marking this as `help wanted` for someone to look into this further. Here's the situation:

 - when we clone a repository, we track these in the `CloningRepositoriesStore` 
 - this only cares about the `path` (where to clone to) and `url` (where the remote repository is)
 - we do some probing in `clone-repository.tsx` to lookup the repository information from the API to grab the right `clone_url`:

https://github.com/desktop/desktop/blob/master/app/src/ui/clone-repository/clone-repository.tsx#L323-L330

For an experiment, I'd like to see how hard it would be to flow this API information (it should be optional, as you can clone from other remotes here) from [`resolveCloneURL`](https://github.com/desktop/desktop/blob/master/app/src/ui/clone-repository/clone-repository.tsx#L311) through these parts (I think):

 - [`Dispatcher.clone`](https://github.com/desktop/desktop/blob/master/app/src/lib/dispatcher/dispatcher.ts#L383-L387) method
 - [`CloningRepositoriesStore.clone`](https://github.com/desktop/desktop/blob/update-prettier-for-stylesheets/app/src/lib/stores/cloning-repositories-store.ts#L18-L22)
 - [`CloningRepository.constructor`](https://github.com/desktop/desktop/blob/update-prettier-for-stylesheets/app/src/models/cloning-repository.ts#L11)
 
So we could enhance the message in `cloning-repository.tsx` to look like this:

```tsx
<div className="title">Cloning {this.props.repository.remoteName || this.props.repository.name}</div>
```

**Comment by MagicMarvMan** [comment] 2018-03-30 08:35
If the issue is still available, I would like to work on it :octocat:

**Comment by MagicMarvMan** [comment] 2018-03-30 19:07
I solved it in #4364 . 👍

**Comment by MagicMarvMan** [comment] 2018-03-30 19:08
Just waiting for approval...

**Comment by shiftkey** [comment] 2018-05-28 23:11
We made some progress on this in #4364 but had to put it aside - feel free to refer to that code if someone else wants to take a shot at it.

**Comment by lisavogtsf** [comment] 2018-08-03 19:59
It looks like #4364 is complete except for some variable names--which have suggestions in the PR. That PR has been locked due to inactivity. I am going to try to resurrect this work in a new branch/PR.
![image](https://user-images.githubusercontent.com/7121497/43662158-f64df3fa-9732-11e8-8da0-32e38670d359.png)
FYI @outofambit

**Closed** 2018-08-23 15:43 UTC
Labels: enhancement, help wanted
