### ISSUE TITLE
Selecting Code On Right Side of History List Deselects History Item.

### ISSUE THREAD

**Issue by alancoler** [desktop/desktop#13500] opened 2021-12-10 18:52 UTC
### Describe the bug
When I use the GitHub desktop and select the History tab and then select one of the items. Then after I select the code on the right, it deselects the item in the history list so I don't know which one I am looking at. This is important when I want to see what changes happened when or before and after other items. I am totally lost when this happens.

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

I expect the history to be still selected even when selecting code on right side of History item

### Actual behavior

The item in History list deselects so none are selected.
<img width="1515" alt="Screen Shot 2021-12-10 at 1 51 46 PM" src="https://user-images.githubusercontent.com/12138500/145626455-31099ebc-263e-4442-9046-4dc86569734f.png">

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tidy-dev** [comment] 2021-12-10 18:57
Hi! Curious which version you are running. This was a regression that was resolved in version 2.9.5.

**Comment by niik** [comment] 2021-12-14 11:12
Hey @alancoler, as @tidy-dev mentioned we believe that the issue you're seeing has been fixed in the latest version of GitHub Deskop. Please make sure you're running at least version 2.9.5 by clicking on the `GitHub Desktop` -> `About GitHub Desktop` menu item. I'll close this issue for now but please let us know if you're still experiencing the problem after ensuring you're on the latest version.

**Comment by alancoler** [comment] 2021-12-14 13:20
I have version Version 2.9.4 (x64) and don't see it updating past this as it goes into an infinite "check for updates" wait.

Is there a bug report for this updating problem?

<img width="895" alt="Screen Shot 2021-12-14 at 8 19 29 AM" src="https://user-images.githubusercontent.com/12138500/146006251-58f1b890-c3ef-489f-9b84-f4fb0b7595ca.png">

________________________________

**Comment by niik** [comment] 2021-12-15 10:16
Hi @alancoler, updates can sometimes take a very long time on Windows if you've fallen behind several versions. One alternative approach is to uninstall GitHub Desktop and install it again from https://desktop.github.com. If that doesn't work feel free to open a new issue and we'll take a look at it but for now I'm going to close this issue since we believe it's resolved in the latest version.

**Closed as completed by niik** 2021-12-15 10:16 UTC
