### ISSUE TITLE
Distinguish between repository name

### ISSUE THREAD

**Issue by PJonHar** [desktop/desktop#10535] opened 2020-09-09 14:30 UTC
When cloning (URL) repositories with the same title from different organizations they cannot be easily identified to which organization they belong to.

![image](https://user-images.githubusercontent.com/1200267/92611890-2d380280-f2b1-11ea-928e-12b5d3fa2491.png)

If they are cloned from Enterprise, they can be distinguished easily.

![image](https://user-images.githubusercontent.com/1200267/92611971-43de5980-f2b1-11ea-8bbe-b019ce0d8db8.png)

Can the way the 'Other' repositories are displayed be made the same way 'Enterprise' repositories are displayed.
Thanks.

**Comment by steveward** [comment] 2020-09-09 14:42
@PJonHar thanks for filing this issue. This sounds like a duplicate of https://github.com/desktop/desktop/issues/8175 and https://github.com/desktop/desktop/issues/8175, both which were included in https://github.com/desktop/desktop/issues/6460. See https://github.com/desktop/desktop/issues/8158#issuecomment-524644986 specifically for the current thinking on this. Thanks!

**Closed by steveward** 2020-09-09 14:42 UTC
