### ISSUE TITLE
Just loading on sign in via browser

### ISSUE THREAD

**Issue by zekageri** [desktop/desktop#17029] opened 2023-07-05 09:23 UTC
### The problem

I want to log out to an other account. I signed out from browser and github desktop.
I clicked sign in via browser, browser showed up i allowed to open github desktop and nothing happens.
Its just loading indefinitly.

![image](https://github.com/desktop/desktop/assets/37899881/e8b2e0d7-e562-4660-b9c7-6a9367f83f92)
![image](https://github.com/desktop/desktop/assets/37899881/dbe6b9be-d49f-4db9-8551-71529151437f)

I can't click cancel or Continue with browser buttons. Only X works.

### Release version

Version 3.2.6 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

1. Sign out from github in the browser
2. Sign out from github desktop
3. Click sign in in github desktop
4. Allow browser to open github desktop
5. Wait for an eternity

### Log files

[2023-07-05.desktop.production.log](https://github.com/desktop/desktop/files/11956203/2023-07-05.desktop.production.log)

**Comment by tidy-dev** [comment] 2023-07-06 11:13
👋 @zekageri Sorry for your troubles. This appears to be a duplicate of https://github.com/desktop/desktop/issues/11410
. I am going to close it in favor tracking the issue there. 

Unfortunately, we have not been able to replicate and therefore haven't nailed down a reason this sometimes happens; tho, seemingly an environmental factor. Some users have been able to resolve theirs by uninstalling and reinstalling GitHub Desktop. Other have seen that if they wait a few minutes and click the button in the browser again it works. Another user has seen that their machine was blocking (antivirus/firewall) the first authenticated network call. Hopefully that helps with debugging. If you happen to figure out a reason, please let us know so we can help other users. 

Other notes: I am going to investigate why the cancel button doesn't work but the x button does that should be unrelated and likely just not wired right since that is a very unused button in general.

**Closed as completed by tidy-dev** 2023-07-06 11:13 UTC

**Comment by zekageri** [comment] 2023-07-06 11:38
Thank you very much for the response.
In the end i just closed two of my browsers ( opera developer and chrome ) closed github desktop, opened again and it worked. My default browser is chrome and i was  logged in with a different account on opera.

**Comment by NoBrainer91** [comment] 2025-12-14 13:51
Was a solution to this ever found? I've installed multiple browsers, Chrome and Firefox included, and tried setting them as my default browser in my system settings but Github Desktop refuses to launch them.
