### ISSUE TITLE
Add an update confirmation

### ISSUE THREAD

**Issue by HackcatDev** [desktop/desktop#7067] opened 2019-03-12 09:01 UTC
It will be nice to add a switch that allows user to select install updates automatically or not. All the programs I know have some kind of this switch so please add it. I have a limited internet access plan so I can't afford downloading new version without my confirmation when current version is working smoothly. Thanks

**Comment by billygriffin** [comment] 2019-03-12 13:29
Hi @HackcatDev, thanks for the issue and sorry to hear the auto-update is causing issues for you. This appears to be a duplicate of #3410, so I'm going to close this, but please follow along there.

**Closed by billygriffin** 2019-03-12 13:29 UTC
