### ISSUE TITLE
After copying new .fyw file (file that is generated by my app), GitHubDesktop freezes and processor usage jumps to 70%

### ISSUE THREAD

**Issue by SoptikHa2** [desktop/desktop#2856] opened 2017-09-23 15:38 UTC
### Description

I have project and an app, that generates .fyw save files (created via serialization). I saved those files to another directory (not loaded by GitHub), but then, I wanted to add one of them to the project to GitHub. After copying to the folder, GitHub desktop realized something changed, showed that one new file is there and freezed (couldn't click on anything within the app). So I opened task manager and noticed, its processor usage is between 60-70% (all the time, not only one spike), so I killed it. After turning GitHub dekstop on again, the same happened. Still frozen and processor usage is between 60-70%.

When I kill GitHub desktop, move the file away and turn GitHub desktop on again, everything is OK again.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** Windows 10.0.15063

### Logs

When GitHub starts and the file is included (so it freezes), NO NEW LOG is there (last changed date remains the same when there was no problem).

#### Additional Information

The file that makes GitHub freeze is [here](http://leteckaposta.cz/208443360) (cannot attach, not supported file type) (download: click the blue link with text "Platforms.fyw" below ad)

**Comment by shiftkey** [comment] 2017-09-23 23:15
@SoptikHa2 thanks for the report! This is a duplicate of #1686 and is related to the rendering of diffs with really long lines.

Please keep an eye on #2596 as this will help mitigate the problem in the short-term.

**Closed by shiftkey** 2017-09-23 23:15 UTC
