### ISSUE TITLE
Created undeletable folder

### ISSUE THREAD

**Issue by 990xan** [desktop/desktop#10659] opened 2020-09-26 02:06 UTC
### Describe the bug

I noticed that I had accidentially created my repo in the wrong folder, so I planned to delete it and change the folder to the correct one and replace the existing repo with the contents of the new folder, so I exited github desktop and attempted to delete the folder but it said it required permission from computername/currentusername, I then attempted to remove it using github desktop, but this also did not remove the folder. 

### Version & OS
2.5.5  Windows 10 Home 64 Bit

### Steps to reproduce the behavior

Create repo (I did this with a directory I thought existed but it decided to create a new one)
Attempt to delete repo folder.

### Expected behavior

The folder to be deleted

### Actual behavior

Folder did not delete and required permission from user deleting, even though user was admin and the one trying to delete the folder in the first place

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by niik** [comment] 2020-09-28 09:55
Hi @990xan, does this happen every time you create a repository? I'm not able to reproduce this and it's not something we've heard before so I suspect it has something to do with your environment. Do you use any anti-virus solutions or other software that could interfere?

**Comment by 990xan** [comment] 2020-09-28 10:04
I didn't attempt to recreate the issue but a system restart allowed me to delete the folder, so it may have been a one off thing.

**Comment by niik** [comment] 2020-09-28 10:12
Okay, if it happens again feel free to open another issue or comment  on this one but since it doesn't appear to be a general problem with Desktop I'm going to close this issue out!

**Closed by niik** 2020-09-28 10:12 UTC
Labels: more-info-needed
