### ISSUE TITLE
Support Signing Commits

### ISSUE THREAD

**Issue by say25** [desktop/desktop#2294] opened 2017-07-21 04:03 UTC
### Description

It would be awesome if this was supported in the new version of desktop. https://help.github.com/articles/signing-commits-using-gpg/

Not entirely sure how it would look/feel but maybe a checkbox to sign a commit in Desktop? Maybe an option to sign commits by default. And if no gpg key is found it would create one for you?

### Version

0.7.0 Mac

**OS version:** macOS 10.12.6

**Expected behavior:** The ability to sign commits.

**Comment by j-f1** [comment] 2017-07-21 11:33
It would be even better if the app integrated with [Keybase](https://keybase.io) so it could automatically obtain the GPG key.

**Comment by joshaber** [comment] 2017-07-21 13:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/78. Please follow that issue for further updates.

**Closed by joshaber** 2017-07-21 13:38 UTC
