### ISSUE TITLE
Cloning template repository fails

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#11196] opened 2020-12-07 18:22 UTC
### Describe the bug

Cloning a template-based repository from Github.com fails. It pulls the template, rather than the new repository, but places it in a directory named after the new repository.

### Version & OS

2.6.0 on Windows 7

### Steps to reproduce the behavior

1. Create a new repository on Github.com based on a template
2. Go to Github Desktop and clone the new repository to your local machine
3. Observe "cloning template" message, and then new repository created with TEMPLATE contents instead of new repo contents.

### Expected behavior

The new repository should be a clone of the associated Github.com repository

### Actual behavior

The new repository is a clone of the template repository

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment] 2020-12-07 18:36
Thanks for the report @dbe-fremantle. I just tested this out and was unable to reproduce the issue. Are you able to consistently reproduce this issue?

Could you also upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by ghost** [comment] 2020-12-07 18:39
See below. It is consistently just pulling the template, despite me cloning the "new".

`2020-12-07T18:35:38.300Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2020-12-07T18:35:58.897Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/dbe-fremantle/template.git - dbe-fremantle (has token)
2020-12-07T18:36:00.786Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/dbe-fremantle/template.git C:\Users\Documents\GitHub\new (took 1.784s)
2020-12-07T18:36:00.814Z - info: [ui] [AppStore] adding repository at C:\Users\Documents\GitHub\new to store
2020-12-07T18:36:00.995Z - info: [ui] [BranchPruner] No branches to prune.
2020-12-07T18:36:06.489Z - info: [ui] Executing isUsingLFS: git lfs track (took 5.598s)
2020-12-07T18:36:09.760Z - info: [ui] [BranchPruner] No branches to prune.
2020-12-07T18:36:10.756Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.053s)
2020-12-07T18:36:49.706Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
`

**Comment by ghost** [comment] 2020-12-07 18:42
So actually it is worse than I thought. I can clearly see all my repositories, but when I clone  the "new" repo (based on the template) it is just pulling the template git and placing it in a directory called "new".

**Comment by ghost** [comment] 2020-12-07 18:53
I even manually entered the URL for the "new" repository and it overrode it with the template URL!

**Comment by ghost** [comment] 2020-12-07 19:02
If I rename the "new" repository and then clone it again, it works. But if I change the name back to "new", it reverts to the old behavior. It's annoying because in this instance I need the "new" name. I am wondering if this is because the template repository at one point was named "new", i.e. I went like this:

Create new repository: **New**
Rename **New** to **Template** and convert to template repository
Create new repository **New** from **Template**
Clone **New** => FAIL
Rename **New** to **New-2**, Clone **New-2** => SUCCESS
Rename **New-2** back to **New**, Clone **New** => FAIL

**Comment by ghost** [comment] 2020-12-07 19:17
Cleared all local storage via developer tools and still failing.

**Comment by steveward** [comment] 2020-12-07 20:56
Thanks for the extra details @dbe-fremantle. This sounds like similar behavior to what has been reported in https://github.com/desktop/desktop/issues/3855. You should be able to resolve this issue by closing GitHub Desktop, clearing out `C:\Users\ <your_user> \AppData\Roaming\GitHub Desktop\Cache`, and then launching the app again. 

Since we're tracking this issue I'm going to close this out, but let me know if clearing out the cache doesn't get things working.

**Closed as completed by steveward** 2020-12-07 20:56 UTC
