### ISSUE TITLE
Githb Desktop will not clone any more

### ISSUE THREAD

**Issue by K2AAE** [desktop/desktop#14028] opened 2022-03-01 05:32 UTC
### Describe the bug
I always click Code -> Open with Github Desktop which use to open on my local git D:\git - in that location I have all the 'git' clones for the last few years. Now starting last week, every time I Click Code -> Open with Github Desktop it tells me it will not clone to a folder with files?
 
2.9.10 X64 Windows 11 (kind of)

1. Go to Git web site https://github.com/sparkfun/SparkFun_Artemis
2. Click on Code
3. Scroll down to Open with Github Desktop and Click
4. try to clone to an existing git storage area dies now (there is no .git or .github in that (D:\git) directory)
5. See error
This folder contains files. Git can only clone to empty folders.

### Expected behavior
clone the repo
Write a clear and concise description of what you expected to happen.

**Comment by sergiou87** [comment] 2022-03-01 08:20
Thanks for your report @K2AAE !! 

I'm sorry you're experiencing this issue. I think this might be the same as #13971, is that possible? If it is, that bug is being addressed in #13980.

I'll close this assuming it's a duplicate of #13971 , but let me know if I'm wrong and I'll be more than happy to reopen this.

**Closed as completed by sergiou87** 2022-03-01 08:20 UTC
