### ISSUE TITLE
capital changes of file names not detected

### ISSUE THREAD

**Issue by jonadv** [desktop/desktop#12365] opened 2021-06-04 11:12 UTC
### Describe the bug

Changing filename from File.txt to file.txt has no effect. Github Desktop does not detect this.

### Version & OS

Version 2.8.3 (x64)
On Windows 10 Pro, Version 2004, Build 19041.985 

### Steps to reproduce the behavior

1. Go to GitHub Desktop, select respository top left, choose 'Show in Explorer'
2. In Windows Explorer rename a file and change 1 capital letter to a lower case letter, or vice versa
3. Go back to GitHub Desktop. Notice how nothing happens.
4. To check, in Windows Explorer rename a file by adding a nr (for example Filename.txt to Filename1.txt)
5. Go back to GitHub Desktop. Notice how this is picked up (immediately) as a change.

### Logs

Adjusting files does nothing with the Log files. 

### Additional context

Found a similar problem which was solved in 2017. https://github.com/desktop/desktop/issues/3314

**Comment by jonadv** [comment] 2021-06-04 11:25
video showing the bug
https://user-images.githubusercontent.com/10421216/120794205-34d2c200-c538-11eb-85bb-7f41572da6c7.mp4

**Comment by jonadv** [comment] 2021-06-04 11:27
![image](https://user-images.githubusercontent.com/10421216/120794454-8bd89700-c538-11eb-9148-2888538371db.png)

**Comment by jonadv** [comment] 2021-06-04 11:30
Sidenote: I noticed this with somebody who does not have Github Desktop installed (I assume he pushes Git from within React), meaning the problem probably lies a bit deeper then just the GitHub Desktop app. 

![image](https://user-images.githubusercontent.com/10421216/120794899-191beb80-c539-11eb-865c-f3443c0b34e7.png)

**Comment by steveward** [comment] 2021-06-04 13:18
@jonadv thanks for the report. By default Git sets the `core.ignorecase` value to `true` inside a repository created on Windows. See [this explanation](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490) along with [this follow up comment](https://github.com/desktop/desktop/issues/2672#issuecomment-338171399) for some further details.

Since this is the expected behavior I am going to close this out, but let me know if you have any further questions about this.

**Closed as completed by steveward** 2021-06-04 13:18 UTC
