### ISSUE TITLE
Commit misattribution popover shouldn't be showing

### ISSUE THREAD

**Issue by BrayFlex** [desktop/desktop#13153] opened 2021-10-19 18:16 UTC
### Describe the bug

Today at some point GitHub Desktop starting showing me an error popover telling me my commit will be misattributed because my email doesn't match, however the email did match my github account's email so I was confused by this. 

### Version & OS

GitHub Desktop: Version 2.9.4 (x64)

![image](https://user-images.githubusercontent.com/33260515/137966667-a174ae15-6048-431d-83c4-52b7b9564adc.png)
![image](https://user-images.githubusercontent.com/33260515/137966540-3b05b95d-6518-4ff3-ae07-030934801886.png)

### Steps to reproduce the behavior

I can't reproduce after restarting the program

### Expected behavior

I wouldn't expect this to show as the email does match my github email

### Actual behavior

My commits seemed to commit with proper attribution but the indicator and popover still showed an issue

### Screenshots

![image](https://user-images.githubusercontent.com/33260515/137966360-4c7d20b8-886b-414d-b6a5-f89f943aebb6.png)

**Comment by steveward** [comment] 2021-10-19 19:44
Thanks for the report @BrayFlex. I tested out the commit attribution behavior and was unable to reproduce any issues. Since this issue resolved itself I'm going to close this out, but let us know if you run into this again and we can dig into it further.

**Closed as completed by steveward** 2021-10-19 19:44 UTC
