### ISSUE TITLE
Reset current branch to this commit in context menu

### ISSUE THREAD

**Issue by strafe** [desktop/desktop#3152] opened 2017-10-25 02:32 UTC
I'm going to avoid using the template as this is more of feature request than a bug report, also my apologies if this is a duplicate, I couldn't find anything after searching a few keywords.

![1](https://user-images.githubusercontent.com/15663890/31977399-9b8ead4c-b934-11e7-8e8c-3320c8015a7f.png)
![2](https://user-images.githubusercontent.com/15663890/31977417-b7a6bf10-b934-11e7-8a7c-df6e3a5abb5d.png)
Currently I constantly find myself opening Git Bash to run `git reset` as I can't do it through the UI, I think this feature is pretty useful for inexperienced people such as myself who constantly commit mistakes and don't want to ruin their repo's commit history by reverting the commit itself.

**Comment by shiftkey** [comment] 2017-10-25 02:36
@strafe can you tell me a bit more about _why_ you would like to reset to an arbitrary commit? What's the workflow you're doing here?

We will happily let you undo your commits when they haven't been published to the remote (I think it's by doing a mixed reset), but we won't let you go further than that and touch commits that exist on the remote ( because force-pushing is a great way to make enemies fast).

**Comment by strafe** [comment] 2017-10-25 02:45
@shiftkey forgive me if I don't answer your question correctly, as I mentioned I'm very inexperienced with the whole _"flow"_ concept...

I'm mainly referring to situations where a commit I've made (usually the latest commit) has a mistake in it such as a typo and instead of correcting it in a following commit I want to do a soft reset to the previous commit, amend my mistake and commit it again.

force-pushing is my favourite pastime... but I think it being present in SourceTree means a somewhat significant amount of people like having this available.

**Comment by shiftkey** [comment] 2017-10-25 03:19
@strafe no problem, I can tell you a bit more about the equivalent behaviour in Desktop.

Let's say I've got a branch off `master` that I've not yet published that has two commits in it.

<img width="525"  src="https://user-images.githubusercontent.com/359239/31978810-e42fff56-b98e-11e7-8660-b788a65b40b4.png">

Oops, that top commit has a typo in it.

If you switch back to the commit form, you'll see below the option to undo that last commit:

<img width="267" src="https://user-images.githubusercontent.com/359239/31978818-f78ae4e4-b98e-11e7-87f8-69880d2cb9ff.png">

If you click `Undo` we'll do a mixed reset, so the files are back in your working directory along with the commit message.

<img width="508" src="https://user-images.githubusercontent.com/359239/31978833-13cd1b7c-b98f-11e7-93c3-81ec0b3a225b.png">

Does that help with your use case?

**Comment by strafe** [comment] 2017-10-25 03:46
Ah very nice, I presumed that using Undo would revert the commit instead of doing a reset, my bad for not testing that out first. I suppose that does cover the majority of my `Reset current branch to this commit` usage.

A couple things I'm still wondering though;
1. Does that little notification stick around forever as long as the last commit is only local?
2. It's a little out of scope for this issue but if I make a typo in the commit message a few commits back, SourceTree allows you to use the `Rebase children of id interactively` in the same menu mentioned previously to reword commit messages before it, does GitHub desktop have an option to do this?

**Comment by shiftkey** [comment] 2017-10-25 04:08
@strafe

> Does that little notification stick around forever as long as the last commit is only local?

Yes

> It's a little out of scope for this issue but if I make a typo in the commit message a few commits back, SourceTree allows you to use the `Rebase children of id interactively` in the same menu mentioned previously to reword commit messages before it, does GitHub desktop have an option to do this?

Not currently. The closest similar request I can find is #1652 - feel free to add your suggestion to that issue.

**Comment by shiftkey** [comment] 2017-12-26 10:48
I'm going to close this out as resolved, but please open a new issue if there's any extra suggestions for "moving between commits on the same branch" workflows.

**Closed by shiftkey** 2017-12-26 10:48 UTC
Labels: enhancement

**Comment by leotm** [comment] 2019-12-12 11:16
I was going to raise this but fortunately just found this.
I'd like to echo @strafe and would definitely love this feature.

Why? I'm reviewing a colleague's PR and spotted a regression introduced in this PR branch.
I'd like to identify which commit caused this to yield a clue, as opposed to simply fixing the regression blind to which commit introduced it.
I'm tackling this by `git reset`'ing (bisect'ing) in a binary search manner.

I don't think it would be too hard to enable a context menu option in the setting to `Reset this Commit`.

Let me know if I should create a separate issue titled `Feature request: reset` 👍

**Comment by tierninho** [comment] 2019-12-12 17:57
@leotm 

> Let me know if I should create a separate issue titled Feature request: reset

That would be great. Thanks!

**Comment by thomaschampagne** [comment] 2023-03-08 19:16
> I was going to raise this but fortunately just found this. I'd like to echo @strafe and would definitely love this feature.
> 
> Why? I'm reviewing a colleague's PR and spotted a regression introduced in this PR branch. I'd like to identify which commit caused this to yield a clue, as opposed to simply fixing the regression blind to which commit introduced it. I'm tackling this by `git reset`'ing (bisect'ing) in a binary search manner.
> 
> I don't think it would be too hard to enable a context menu option in the setting to `Reset this Commit`.
> 
> Let me know if I should create a separate issue titled `Feature request: reset` 👍

Any plan about this feature in 2023?
