### ISSUE TITLE
Select Branch to Compare Bugs

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#10473] opened 2020-08-29 16:55 UTC
### Describe the bug

There seem to be bugs associated with Select Branch to Compare.  I have attached a GIF that shows a few of them.  In the video, I try to compare my `master` branch with a remote branch `main` in the [Nushell](https://github.com/nushell/nushell) project.  When I go to select the `main` branch, it filters out some branches, but still shows a few others, instead of just directly going into the comparison view of `master` and `main`.  Then, I try clicking the `main` branch, and it won't let me.

### Version & OS

macOS 10.15.6
GitHub Desktop v2.5.4

### Steps to reproduce the behavior

See attached GIF

### Expected behavior

I expected that the first time I click on a branch to compare, that it goes directly to the comparison view between that branch and the currently checked out one.

### Actual behavior

Some branches are filtered out, while some are not.

### Screenshots

Add screenshots to help explain your problem, if applicable.

![Select Branch to Compare Bugs](https://user-images.githubusercontent.com/19867440/91642122-bbc99b80-e9f6-11ea-9868-5f096c964bba.gif)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I reported some other bug with Select Branch to Compare previously [here](https://github.com/desktop/desktop/issues/9971); I wonder if this is a regression or if these are bugs that are related to that fix.

**Comment by dhunmoon** [comment] 2020-08-29 18:39
@JosephTLyons Yes, it does happen, If you single-click the list will not respond you should try double-clicking that will select the branch every time. Regardless that is an Issue and should not happen.

Other than that it's showing some other branches even if there is `main` in the filter because string `main` might be a substring in other branch names(that's my guess).

**Comment by niik** [comment] 2020-09-10 15:10
Hi @JosephTLyons, thanks for opening this. I _believe_ this was fixed by #10485 which we shipped in yesterday's patch release (GitHub Desktop 2.5.5). I'd really appreciate it if you could upgrade to the latest version of GitHub Desktop and let us know if you're still able to reproduce this. In the meantime I'm going to assume it's fixed and close this but let us know if it isn't and we'll reopen.

**Closed by niik** 2020-09-10 15:10 UTC

**Comment by JosephTLyons** [comment] 2020-09-11 00:48
> Hi @JosephTLyons, thanks for opening this. I _believe_ this was fixed by #10485 which we shipped in yesterday's patch release (GitHub Desktop 2.5.5). I'd really appreciate it if you could upgrade to the latest version of GitHub Desktop and let us know if you're still able to reproduce this. In the meantime I'm going to assume it's fixed and close this but let us know if it isn't and we'll reopen.

Seems to be fixed on my end in 2.5.5.  Thanks for the quick work guys!
