### ISSUE TITLE
Pull Request Still Being Shown on Pc

### ISSUE THREAD

**Issue by rag4214** [desktop/desktop#4140] opened 2018-03-01 05:49 UTC
### Description
I merged a pull request with my main branch on my PC. The pull request is still in my pull request tab despite being completed and the branch being deleted.

### Version

**GitHub Desktop version:** 1.1.0 - Windows, Mac

**OS version:** 10.13.3
Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

1. Open Pull Request
1. Write review
1. Merge
1. Pull request goes away on Mac, not on windows

**Expected behavior:** Pull Request to disappear on both 

**Actual behavior:** Disappears on mac, not on windows

**Reproduces how often:** First time?

#### Additional Information

![screen shot 2018-03-01 at 12 48 25 am](https://user-images.githubusercontent.com/35985028/36828864-4ca31fa0-1cea-11e8-8f5d-19b73ca50800.png)

![screen shot 2018-03-01 at 12 48 02 am](https://user-images.githubusercontent.com/35985028/36828868-4ff05222-1cea-11e8-896e-e5c608539fc2.png)

**Comment by iAmWillShepherd** [comment] 2018-03-01 18:32
Thanks for taking the time to open an issue! 🙇 

How long does the merged PR stay in the Pull Requests List? I'm asking because we update PRs at a set interval, so you may not notice changes occur at the same time across two instances of the app (timers start on app start).

**Comment by rag4214** [comment] 2018-03-01 18:38
It's still there 13 hours later

**Comment by iAmWillShepherd** [comment] 2018-03-01 18:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4122. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-03-01 18:54 UTC
