### ISSUE TITLE
Failure to login to a GitHub enterprise account on MacOS

### ISSUE THREAD

**Issue by adamenagy** [desktop/desktop#4010] opened 2018-02-14 11:47 UTC
### Description

Failure to login to a GitHub enterprise account on MacOS

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** MacOS High Sierra 10.13.3

### Steps to Reproduce

1. Open GitHub Desktop
1. Open "Preferences..."
1. Under "Accounts" >> "Enterprise" click "Sign In"
1. Provide the company git URL
1. Provide credentials 

**Expected behavior:** Successful login

**Actual behavior:** Getting an error message saying "The user name or passphrase you entered is not correct."

**Reproduces how often:** 100%

### Logs

[2018-02-14.desktop.production.log](https://github.com/desktop/desktop/files/1723721/2018-02-14.desktop.production.log)

#### Additional Information

Here is the error message dialog I'm getting:

![githuberror](https://user-images.githubusercontent.com/2300154/36201892-8253b06e-1179-11e8-80a0-da3a46091d5d.png)

Using the exact same Enterprise account URL and credentials I can successfully log in using the old GitHub Desktop version 223  

![oldgithubdesktop](https://user-images.githubusercontent.com/2300154/36201813-3c6f5102-1179-11e8-83db-57779cacc0df.png)

**Comment by iAmWillShepherd** [comment] 2018-02-14 17:31
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3263. Please follow that issue
for further updates.

Try following the steps in [this comment](https://github.com/desktop/desktop/issues/3263#issuecomment-344590213) and let me know if that resolves your issue.

**Comment by adamenagy** [comment] 2018-02-14 17:47
OMG, yes that solved it! Thanks! :)

**Closed** 2018-02-14 17:48 UTC
Labels: more-information-needed
