### ISSUE TITLE
Submission Tags not updating/syncing properly - GITHUB DESKTOP

### ISSUE THREAD

**Issue by PanyaOu** [desktop/desktop#16032] opened 2023-01-29 23:00 UTC
### The problem

Removed and Updated tags on the web do not correspond to the actual tags on Github Desktop

### Release version

Version 3.1.5 (x64)

### Operating system

Windows 

### Screenshots

![image](https://user-images.githubusercontent.com/75552913/215360581-2b2caddb-8072-4ac0-8d82-726c9cf265d5.png)
![image](https://user-images.githubusercontent.com/75552913/215360596-a6f41e23-2ad3-4042-9715-7f639564a60f.png)
it is outdated

**Comment by niik** [comment] 2023-01-30 09:02
Hi @PanyaOu, thanks for reaching out. Unfortunately this is by design. Git itself will not ever automatically delete a tag that's been fetched from the upstream without the user explicitly telling it to do so. See https://git-scm.com/docs/git-tag#_on_re_tagging for more information about why this is the case.

In order to get rid of the deleted tag you currently have to manually execute `git tag -d TAGNAME` locally.

I'm closing this as GitHub Desktop relies on the underlying functionality of Git here so there's nothing for us to do. For supporting deleting tags from GitHub Desktop please see https://github.com/desktop/desktop/issues/9938

**Closed as completed by niik** 2023-01-30 09:02 UTC
