### ISSUE TITLE
Cannot stash changes after a conflict is resolved

### ISSUE THREAD

**Issue by Nuthouse01** [desktop/desktop#12738] opened 2021-08-06 22:03 UTC
### Describe the bug
Cannot stash changes after a conflict is resolved

### Version & OS

2.9.0 (x64), Windows 10 64 bit.

### Steps to reproduce the behavior

1. Make changes to a tracked file
2. Commit those changes
3. Make more changes to the same file
4. STASH those changes
5. Make more changes that conflict with 3
6. Commit those changes
7. Use drag-and-drop to squash the commits from 2 and 6
8. Restore the stash from step 4, should see a ! triangle next to the file name indicating that there is a confilct
9. Manually resolve the conflict with a text editor, NOT by using any shortcuts included in Github Desktop
10. Notice that the ! triangle has been replaced with a checkmark
11. Notice that the menu item Branch > Stash all changes is now greyed out and disabled, and the "commit" button doesn't work either

### Expected behavior

I should be prevented from using "stash all changes" or "commit" for as long as there is a conflict, and I should be able to regain use of the "stash all changes"/"commit" functions once the system detects that the conflict is gone.

### Actual behavior

Whatever widget is controlling the ! triangle vs checkmark is able to succesfully deduce when I have resolved the conflict. However, that verdict hasn't been passed to whatever is controlling the other menus. I am still unable to stash/commit my changes.
Edit: after restarting the app several times and resetting my changes (copy all modified files to a different location, delete all changes on branch, copy the modified files back onto the branch), I have regained the ability to stash my changes **but the commit button still does not work.**
Edit2: after deleting the local copy of the branch & redownloading from origin, I **still** am unable to commit my changes.
Edit3: after making a small commit on a file unrelated to those I was stashing & conflicting before, I was still unable to commit my changes on the once-conflicted files. After **undoing** that small commit, I regained the ability to commit my once-conflicted files. I have attached the log that includes all my attempts to fix this problem.

### Screenshots

no thanks

### Logs

latest log is attached
[2021-08-06.desktop.production.log](https://github.com/desktop/desktop/files/6948109/2021-08-06.desktop.production.log)
[2021-08-06.desktop.production.log](https://github.com/desktop/desktop/files/6948161/2021-08-06.desktop.production.log)

### Additional context

no thanks

**Comment by ms609** [comment] 2021-08-09 08:50
I also encounter this behaviour when switching between branches and taking changes with me.  Logs of this case [attached](https://github.com/desktop/desktop/files/6953092/2021-08-09.desktop.production.log).

**Comment by steveward** [comment] 2021-10-07 20:33
@Nuthouse01 thanks for the report, and apologies for not getting back to you.

I was unable to reproduce any issues with committing after resolving conflicts from restoring a stash. Stashing not working is expected after resolving conflicts. Running a `git stash` from the command line will show a `needs merge` error as well and not allow you to stash until the resolved conflict is committed.

The committing issue is unusual -- if you are able to still reproduce this please let me know and we can try and dig into this further.

@ms609 -- are you seeing the stash option disabled, or the commit issue? Are you hitting conflicts when switching branches and bringing your changes?

**Closed as completed** 2021-10-14 21:21 UTC
Labels: more-info-needed

**Comment by 2shipEcom** [comment] 2022-05-17 13:31
I also have the same issue, I have a file that is resolved(after a conflict)  and cannot stash all changes. 
What other info do you need?

**Comment by 2shipEcom** [comment] 2022-05-17 14:37
I found a workaround, save the resolved file somewhere, discard the original one and recopy the modified one.

**Comment by HughWarrington** [comment] 2024-01-25 23:23
I have just had the same experience and ended up finding this ticket.

I agree with the expected vs actual behaviour. Specifically:

> Whatever widget is controlling the ! triangle vs checkmark is able to succesfully deduce when I have resolved the conflict. However, that verdict hasn't been passed to whatever is controlling the other menus. I am still unable to stash/commit my changes.

If after the repro steps I look at the situation from the command line, I see something like this:

```
C:\Users\hwarrington\Documents\GitHub\myrepo>git status
On branch MyBranch
Your branch is ahead of 'origin/MyBranch' by 7 commits.
  (use "git push" to publish your local commits)

Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add <file>..." to mark resolution)
        both modified:   Path/To/SomeFile.cs
```

Even though GitHub Desktop shows a green checkmark next to SomeFile.cs, the 'Stash all changes' menu item is greyed out and git is saying there's more to do.

@steveward said:

> Stashing not working is expected after resolving conflicts. Running a `git stash` from the command line will show a `needs merge` error as well and not allow you to stash until the resolved conflict is committed.

I don't think stashing not working is "as expected", since GitHub Desktop marks the file with a tick, and also provides no way to get out of this situation except possibly committing which I don't want to do.

Also "not allow you to stash until the resolved conflict is committed" isn't quite right -- you only need to `git add` the conflicted file, then `git stash` will work again. The problem is there appears to be no way to issue the `git add` command from the GUI in this situation.

I hope that answers the more-info-needed label @steveward. Let me know if I can help with more details.

**Comment by FelixMittermeier** [comment] 2025-02-28 16:58
`git add .` did the trick for me.

**Comment by bryanparadis** [comment] 2025-07-29 04:46
Having the same issue right now. Workaround above is gold
