### ISSUE TITLE
Cloning repository with submodules hangs

### ISSUE THREAD

**Issue by A-Dunstan** [desktop/desktop#18852] opened 2024-06-21 03:54 UTC
### The problem

Trying to clone a repository with a submodule successfully clones the main repo, then hangs after registering the submodule.
The submodule repository is public / accessible.

### Release version

3.4.1 (x64)

### Operating system

Windows 11 ARM

### Steps to reproduce the behavior

1. Clone repository using URL `https://github.com/A-Dunstan/teensy4_usbhost`
2. Observe progress stalls at submodule registration

### Log files

No information in desktop.production.log regarding the clone operation.

### Additional context

Issue #3242 looks similar but concerns cloning failing when the submodule is inaccessible. For this issue the submodule is a public github repository, and the cloning process is stalling rather than failing.

**Comment by niik** [comment] 2024-06-24 10:24
Hey @A-Dunstan, thanks for reaching out. I was unable to reproduce the stall using the latest [beta version](https://desktop.github.com/beta/). I did note that the submodule is set up to clone over ssh rather than https. Could you try changing the submodule url to use the https-url instead and see if that's still causing problems?

**Comment by A-Dunstan** [comment] 2024-06-24 19:44
I had already tried 3.4.2-beta3 with the same result, but changing the submodule URL to https has indeed fixed the hanging.

**Comment by niik** [comment] 2024-06-25 09:19
@A-Dunstan thanks for reporting back! I suspect then that something is going on with your SSH setup. Are you using any special ssh-agent (1password?) or custom ssh passphrase ui? Regardless I'm happy to hear you've got it working. I'm gonna close this out since I believe the origin of the problem resides within your environment rather than being a bug in Desktop. Cheers!

**Closed as completed by niik** 2024-06-25 09:19 UTC

**Comment by A-Dunstan** [comment] 2024-06-25 10:38
I was testing on a clean machine with nothing else installed on it besides github desktop.
If I had to guess, I would say the UI was stalling because somewhere in the background the git process was asking to confirm github's ssh fingerprint.
