### ISSUE TITLE
Bring back the "Tree" to show history branches

### ISSUE THREAD

**Issue by BettyBei** [desktop/desktop#5468] opened 2018-08-24 23:24 UTC
Please bring the "Tree view" back, like the following picture in the previous version.
![tree](https://user-images.githubusercontent.com/10226359/44612061-bed09680-a7f4-11e8-878c-af69cc9ae7b1.png)

**Comment by billygriffin** [comment] 2018-08-25 00:35
Thanks for the request @BettyBei. This is a duplicate of https://github.com/desktop/desktop/issues/1634, and this is how we're thinking about improving our product-level communication going forward: https://github.com/desktop/desktop/issues/5398

Please follow along in #1634, and thanks again.

**Closed by billygriffin** 2018-08-25 00:35 UTC

**Comment by WencaiZheng** [comment] 2021-01-05 15:31
Now what?

**Comment by Bilalmirza** [comment] 2021-01-12 06:13
Bring the tree back please!

**Comment by WencaiZheng** [comment] 2021-01-12 13:19
GitKaren does that but charge

**Comment by HongJheLi** [comment] 2021-01-14 00:28
> GitKaren does that but charge

GitKraken？

I just move to [fork ](https://git-fork.com/)since GitKraken did not work with self-hosted repositories for free acount.

**Comment by WencaiZheng** [comment] 2021-01-14 02:29
yes charge ~$30/user/year I find it's fine.

**Comment by WencaiZheng** [comment] 2021-01-14 02:30
Maybe gitk will split the money with github who knows

**Comment by FelipeSchneider** [comment] 2021-09-16 09:09
I also would like to have this back... I've been using SourceTree for a while, but with the recent changes in Github security policies it became pretty hard to work with external apps

**Comment by cj-marius-duna** [comment] 2022-02-04 07:20
We need this back

**Comment by JGroxz** [comment] 2022-05-18 00:16
Would be very useful

**Comment by hostfully** [comment] 2022-11-10 16:29
still a very much needed feature, 4 years later.

**Comment by unikoca** [comment] 2022-11-20 21:41
looks like a small feature but it's very useful... come on MIcrosoft, give us or tree back!

**Comment by DinhHaoIT** [comment] 2023-01-04 06:57
I would like it back

**Comment by anasahmed142** [comment] 2023-01-12 05:54
for the tree view i have to use atlassian bitbucket

**Comment by the-nemz** [comment] 2023-02-01 08:04
Is this in the plan? I'd really love to have a tree view on an official GitHub client. Ideally something like what SourceTree has. I don't enjoy SourceTree very much but I'm forced to use it for the simple purpose of viewing different branches in a GUI. I just installed GH Desktop on a new computer assuming this had been added, but alas.

**Comment by alockwood05** [comment] 2025-02-27 23:12
PLEASE!
