### ISSUE TITLE
Desktop forcing pull request from same branch.

### ISSUE THREAD

**Issue by Flohhhhh** [desktop/desktop#14615] opened 2022-05-14 11:30 UTC
### The problem

I only have one branch on my newly created repository, "master". However, when trying to push changes from the desktop app, it asks me to create a pull request to merge master with master.

The other thing I noticed is that on web view, it shows that master is the default branch, but on desktop it is listed under "Other Branches".

Apologies if this is just user error :D 

### Release version

Version 3.0.0

### Operating system

Windows 10

### Steps to reproduce the behavior

Create new repository
Create commit and push

### Log files

[2022-05-14.desktop.production.log](https://github.com/desktop/desktop/files/8692823/2022-05-14.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/48927090/168423770-1892902f-8952-4592-b2c1-da81c6015d45.png)
![image](https://user-images.githubusercontent.com/48927090/168423944-40a28251-3eb0-48b8-9c60-9780ef2d615f.png)

### Additional context

I created the repository using Unreal Engine 5

**Comment by steveward** [comment] 2022-05-19 18:47
@Flohhhhh thanks for the report. This issue likely is due to the branch not being picked up as the default. Have you tried clicking `Fetch origin` to see if that helps with this issue?

**Comment by Flohhhhh** [comment] 2022-05-27 17:36
That screenshot was from a repo where I just forced it to commit, but the issue persisted after.

Today I created a new repository, and the same issue occurred. I also uninstalled the desktop app, and both app data folders before reinstalling it.

This is a new repository with no commits.
![image](https://user-images.githubusercontent.com/48927090/170762488-e5bf27b1-22c2-41d0-8c74-fffdfc893dd0.png)

More info:
config file:
```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	symlinks = false
	ignorecase = true
[lfs]
	repositoryformatversion = 0
[remote "origin"]
	url = https://github.com/Flohhhhh/PhalanxPrototype.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
head file:
```
ref: refs/heads/master
```

**Comment by Flohhhhh** [comment] 2022-06-10 14:05
Ummm.... yes I tried clicking fetch origin...

**Comment by steveward** [comment] 2022-08-11 15:08
@Flohhhhh I was unable to reproduce this issue. Are you still experiencing this issue?

**Comment by Flohhhhh** [comment] 2022-08-11 19:15
Yup, any repository I create from within Unreal Engine 5 has this issue.

**Comment by niik** [comment] 2024-09-18 13:10
Hey @Flohhhhh, doing some triaging of old stale issues here. Is this still a problem you're encountering?

It would appear as if your local `master` branch is not set up to track the remote `master` branch. I suspect this has something to do with how Unity creates repositories but I have no experience with Unity so I can't say for sure.

Either way it should be pretty easy to solve by running the command `git branch -u origin/master` to set up the tracking

**Comment by niik** [comment] 2024-09-18 13:12
Given that this doesn't happen when creating repositories from within Desktop I'm going to treat this as not a bug and close it out but let us know if you have other information that would indicate this being a bug within Desktop.

**Comment by Flohhhhh** [comment] 2024-09-18 13:12
I do still encounter this issue once in a while. I'll try to reproduce again. 

This may just be an issue for Unreal Engine to fix on their end the way it creates repos.

Edit: didn't see this was closed while I was typing, you can close again!

If I find an issue related to this is directly caused by desktop itself I'll open a new issue 👍

**Closed as completed** 2024-09-18 13:16 UTC
