### ISSUE TITLE
Unable to commit any changes

### ISSUE THREAD

**Issue by JesseFoote** [desktop/desktop#4629] opened 2018-05-07 20:43 UTC
## Description
I am trying to commit changes with GitHub Desktop.  Even if I try to commit only one small change to a single file, I get the following error, along with literally hundreds of supposed style errors listed below that.  The code is working on my computer just fine, and none of the style errors were actually changes that were made, or even relate to the specific files that I am trying to commit.  I've tried running 'Standard --fix' as suggested in the error message, and gotten nothing.

![errormessage](https://user-images.githubusercontent.com/26234473/39723961-9cf28d16-5204-11e8-869a-f97d2a9c5d55.jpg)

## Version
* GitHub Desktop: 1.1.1
* Operating system: 10.12.6

## Steps to Reproduce
Simply clicking "Commit to master" on my GitHub Desktop

### Expected Behavior
I expected the changes to commit, as they have before!

### Actual Behavior
"Commit failed - exit code 1 received", and the changes do not commit.

## Additional Information
None

### Logs
There is no log of this that I can find.

**Comment by j-f1** [comment] 2018-05-07 21:13
It looks like this is caused by a pre-commit hook that is failing.

**Comment by shiftkey** [comment] 2018-05-07 22:05
As part of committing, Git seems to be running a `pre-commit` hook defined in this repository and `standard` is raising errors with the codebase.

> The code is working on my computer just fine, and none of the style errors were actually changes that were made, or even relate to the specific files that I am trying to commit. I've tried running 'Standard --fix' as suggested in the error message, and gotten nothing.

Yeah, tools like `standard` will scan all the matching files in the repository. I'd hope that `standard --fix` would update those files, but without poking at the repository I can't really help out further.

You _could_ bypass the commit hook by removing the `.git/hooks/pre-commit` file, which should let you commit the changes, but I suspect you might get in trouble with the other collaborators for bypassing the checks (even if it looks like others put the repository into this state).

**Comment by cyberhck** [comment] 2018-05-08 07:07
Hi, thanks for PR, before you commit, you need to fix the code style which you're using. Bypassing that and having style issues, and sending a PR to this repo will piss people off, and won't get merged as build will fail anyway, I suggest you change the code style.

To do that, go to `AlertMessage.js` and use single quotes for strings, remove extra semicolons, and when you're calling a function on line: 7, I think? add a space. When you fix all this, you'll be able to commit.

Also enabling lint on your editor will show you where the problem exactly is.

**Comment by iAmWillShepherd** [comment] 2018-05-08 16:42
@cyberhck, I think you posted to the wrong repo...

**Comment by cyberhck** [comment] 2018-05-09 00:31
are you sure? because I just mentioned where are the linting errors, isn't it?6

**Comment by shiftkey** [comment] 2018-05-16 02:18
Closing this out as the underlying issue (Git hooks blocking the commit) is the expected Git behaviour that Desktop is propagating to the user, and a couple of workarounds have been suggested.

@JesseFoote I'd recommend reaching out to the maintainers of that project to see if they can help with your situation.

**Closed by shiftkey** 2018-05-16 02:18 UTC
Labels: more-information-needed

**Comment by GuptaStuti** [comment] 2023-03-13 09:41
I am trying to commit changes using Git desktop but its giving me an error.
Below is the screenshot of the error:-
![Screenshot 2023-03-13 150757](https://user-images.githubusercontent.com/98029663/224663952-45e04155-37fa-4f9c-a761-fe4e78ab4e16.png)

I have tried to make changes to the file and then commiting it but its not working, can you please suggest what is the issue here and how can I fix this.

**Comment by steveward** [comment] 2023-03-13 18:37
@GuptaStuti can you upload the log file from GitHub Desktop?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.
