### ISSUE TITLE
Troubleshooting: The file ~(....) has been deleted or moved

### ISSUE THREAD

**Issue by JohannaWentges** [desktop/desktop#16696] opened 2023-05-15 10:14 UTC
### The problem

When I try to open an R project through Github Desktop, I keep getting the error message: 
"The file ~(....) has been deleted or moved. Do you want to close this file now?"

The same happens when I access the files through R Studio directly and try to save the progress.

The file however exists and is located in the stated filepath. I have deleted and re-downloaded both R studio and Github desktop, but the issue did not solve.

### Release version

Version 3.2.3 (arm64).

### Operating system

macOS Monterey, Version 12.5 (21G72).

### Steps to reproduce the behavior

1. right click in github desktop: "open in R Studio"
2. then the error message appears

### Log files

2023-05-15T01:12:26.428Z - info: [ui] Stats reported.
2023-05-15T02:01:59.453Z - info: [ui] [BranchPruner] No branches to prune.
2023-05-15T07:04:58.273Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:05:01.248Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:05:04.781Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:05:09.598Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:05:18.848Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:12:54.636Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:13:40.911Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:28:52.612Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2023-05-15T07:29:06.502Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/JohannaWentges/Master_Thesis_GHG.git/': Could not resolve host: github.com

2023-05-15T07:29:06.549Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
    at It (/webpack:/app/src/lib/http.ts:152:10)
    at Sn.request (/webpack:/app/src/lib/api.ts:1603:28)
    at Sn.fetchPushControl (/webpack:/app/src/lib/api.ts:1519:35)
    at ir.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:1147:37)
    at /webpack:/app/src/lib/stores/app-store.ts:4857:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ir.withPushPullFetch (/webpack:/app/src/lib/stores/app-store.ts:4367:5)
    at ir.performFetch (/webpack:/app/src/lib/stores/app-store.ts:4808:5)
    at Mo.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:102:7)
2023-05-15T07:29:06.641Z - warn: [ui] getFetchPollInterval: failed for JohannaWentges/Master_Thesis_GHG
TypeError: Failed to fetch
    at It (/webpack:/app/src/lib/http.ts:152:10)
    at Sn.request (/webpack:/app/src/lib/api.ts:1603:28)
    at Sn.getFetchPollInterval (/webpack:/app/src/lib/api.ts:1641:35)
    at Mo.getFetchInterval (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:136:38)
    at Mo.performAndScheduleFetch (/webpack:/app/src/lib/stores/helpers/background-fetcher.ts:117:33)
2023-05-15T08:53:08.945Z - info: [ui] [BranchPruner] Last prune took place 7 hours ago - skipping
2023-05-15T08:53:10.139Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.2s of which 0.0s paused, total 1.2s
2023-05-15T09:03:19.894Z - info: [ui] [AppStore] loading 2 repositories from store
2023-05-15T09:03:19.911Z - info: [ui] [AppStore] found account: JohannaWentges (JohannaWentges)
2023-05-15T09:03:19.955Z - info: [ui] [BranchPruner] Last prune took place 7 hours ago - skipping
2023-05-15T09:03:20.258Z - info: [ui] launching: 3.2.3 (Mac OS 12.5.0)
2023-05-15T09:03:20.277Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2023-05-15T09:03:20.303Z - info: [ui] Subscribed 'JohannaWentges' to Alive channel
2023-05-15T09:10:06.018Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.4s of which 0.0s paused, total 1.4s
2023-05-15T09:13:42.249Z - info: [main] Processing protocol url
2023-05-15T09:13:42.285Z - info: [ui] [BranchPruner] Last prune took place 7 hours ago - skipping
2023-05-15T09:33:30.810Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Master_Thesis_GHG - JohannaWentges (has token)
2023-05-15T09:33:33.606Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping
2023-05-15T09:40:29.614Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.5s of which 0.0s paused, total 1.5s
2023-05-15T09:57:25.800Z - info: [ui] [AppStore] loading 2 repositories from store
2023-05-15T09:57:25.804Z - info: [ui] [AppStore] found account: JohannaWentges (JohannaWentges)
2023-05-15T09:57:25.841Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping
2023-05-15T09:57:26.164Z - info: [ui] launching: 3.2.3 (Mac OS 12.5.0)
2023-05-15T09:57:26.177Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2023-05-15T09:57:26.185Z - info: [ui] Subscribed 'JohannaWentges' to Alive channel
2023-05-15T10:00:06.557Z - info: [ui] [AppStore] loading 2 repositories from store
2023-05-15T10:00:06.574Z - info: [ui] [AppStore] found account: JohannaWentges (JohannaWentges)
2023-05-15T10:00:06.596Z - info: [ui] [BranchPruner] Last prune took place 8 hours ago - skipping
2023-05-15T10:00:06.925Z - info: [ui] launching: 3.2.3 (Mac OS 12.5.0)
2023-05-15T10:00:06.926Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2023-05-15T10:00:06.927Z - info: [ui] Subscribed 'JohannaWentges' to Alive channel
2023-05-15T10:02:13.308Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 1 repositories took 1.3s of which 0.0s paused, total 1.3s

### Screenshots

<img width="248" alt="Screenshot 2023-05-15 at 12 03 05" src="https://github.com/desktop/desktop/assets/115477907/32b3f876-b5d4-40ac-b90d-0113fd3a3b01">

<img width="242" alt="image" src="https://github.com/desktop/desktop/assets/115477907/57009ab2-a538-469b-bb3c-4f2115209112">

### Additional context

No additional comments.

**Comment by tidy-dev** [comment] 2023-05-15 12:03
👋 Sorry for your troubles. I installed RStudio and tested this scenario out with a simple file and was unable to reproduce. Your errors seem to be from RStudio and if I understood you correctly "The same happens when I access the files through R Studio directly and try to save the progress." This does not appear to be an error with GitHub Desktop.  My assumption is the file you are trying to access is corrupted, and therefore cannot be opened by RStudio. Are there any other reproduction steps that would indicate  this is an issue with GitHub Desktop?

**Comment by michelleg06** [comment] 2023-10-31 13:55
I seem to be experiencing the same issue. My Github Desktop version is 3.3.4 (arm64), and it is connected to R version 4.3.1 (2023-06-16) and Rstudio version ‘2023.9.1.494’.  When I open GitHub Desktop and try to open a project via Rstudio, the automatic response is The file ~(....) has been deleted or moved. However, if I open the file directly from the local Github folder, and then GitHub desktop, I can update, and make commits and push to github. This only started happening when I updated my Rstudio version (was previously working with version ‘2022.7.2.576’). Any help on how to resolve this issue is appreciated!

**Comment by steveward** [comment] 2023-10-31 15:35
@michelleg06 thanks for the update. I downloaded RStudio 2023.09.1  and was also able to reproduce this issue. Unfortunately the RStudio logs aren't showing anything, so I'm not sure what is causing this. I tried modifying a few settings as well, but was unable to resolve the issue. I'll try reaching out to RStudio support to see if we can figure out what's going on here.

**Comment by FLaignelot** [comment] 2023-10-31 18:06
Hello ! 
As i'm completely new to RStudio and GitHub, i would not know hot to explain or describe it precisely, but i'm having the same issue.
I'm working on an M1 MacBook Pro, R version 4.3.1 "Beagle Scouts", RStudio version 2023.09.1+494 | Released: 2023-10-17 and GitHub Desktop version 3.3.5. 
I just tried to open a new repository on R through GitHub Desktop, and it does not work, displaying the same message as @JohannaWentges.
I hope there is a solution somewhere to be found,
Thanks ! :)

**Comment by steveward** [comment] 2023-11-06 20:38
The Posit team opened up an issue to track this if you'd like to follow along for updates: https://github.com/rstudio/rstudio/issues/13893

**Comment by steveward** [comment] 2024-10-18 14:49
It looks like there was some progress in looking to this on the RStudio side, so I'm going to close this out as it's external to Desktop.

**Closed as completed by steveward** 2024-10-18 14:49 UTC
Labels: integrations
