### ISSUE TITLE
Request for elastic scrolling in macOS

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#3772] opened 2018-01-11 22:26 UTC
There's a similar issue for Atom (https://github.com/atom/atom/issues/345). Since Electron is Chrome and GH Desktop is arguably much simpler than Atom, it will be great if elastic scrolling can be added. This will hopefully allow Atom to support elastic scrolling in the future too.

Glad that I still have the old client...

**Comment by shiftkey** [comment] 2018-01-11 22:30
@danqing I see https://github.com/atomiks/elastic-scroll is mentioned as a library option to mimic this. It'd be cool if someone tried to plug it into Desktop and see how it felt.

**Comment by niik** [comment] 2018-01-11 22:38
In principle I'm all for this idea, it's a native convention and if we can replicate it without too much fuzz it'd be great.

> It'd be cool if someone tried to plug it into Desktop and see how it felt.

I've tried that library and unfortunately it doesn't replicate the experience 100%. It does a great job of matching the easings but when you're in the elastic band effect you're stuck there until the transition is completely meaning that you can't scroll during that time. It feels really weird if you flick up and then scroll stops working and it's exacerbated by the fact that the easing is really slow at the very end of the transition so you're not necessarily seeing the transition.

**Comment by joshaber** [comment] 2018-01-12 13:35
This is being tracked in Chromium's bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=546520

I _doubt_ we can replicate this but I'd love to be surprised 😄

**Comment by atomiks** [comment] 2018-01-13 08:44
The problem is the native "stretching" ability when you're already at the top/bottom is impossible to implement with the web APIs. I'm not sure about mouse-based macs, but you need to know when the trackpad is let go, which (correct me if I'm wrong) there is no event for.

There's actually a benefit to it and that's subpixel translation (the current native implementation uses full 1px values which looks choppy on retina displays)

overflow-x direction also needs to be possible but both at the same time might be tricky

> It feels really weird if you flick up and then scroll stops working

I'm not experiencing this though, you can scroll no matter what stage the transition is at?

**Comment by danqing** [comment] 2018-01-17 21:08
I wonder if the trackpad release event can be (is?) exposed via Electron, so that @atomiks' cool library can be used at least for Electron-based apps.

**Comment by billygriffin** [comment] 2019-10-16 18:12
Given that we haven't seen this come up since the original issue, I'm going to close this out. If someone is really interested in seeing this get into Desktop, I want to make sure @niik's feedback https://github.com/desktop/desktop/issues/3772#issuecomment-357084770 is addressed to ensure it doesn't have unintended consequences.

**Closed by billygriffin** 2019-10-16 18:12 UTC
Labels: enhancement, help wanted, macOS
