### ISSUE TITLE
Not showing differences, unable to commit and discard

### ISSUE THREAD

**Issue by svejnohatomas** [desktop/desktop#9161] opened 2020-02-22 21:09 UTC
### Describe the bug
- GitHub Desktop is not showing differences in the files.
  - Changes are registered by git when using Git Bash.
- Discarding changes has no effect (keeps file).
- Committing changes does not work.
  - Error: **_Commit failed - exit code 1 received_**
  - Committing changes using Git Bash works

### Version & OS
- Version: 2.3.1
- OS: Windows 10 (10.0.18363 Build 18363)

### Steps to reproduce the behavior
- Unknown

### Expected behavior
- Should be able to see, commit, and discart changes

### Actual behavior
- See "_Describe the bug_"

### Screenshots
- Diff
![image](https://user-images.githubusercontent.com/16503291/75099074-5dd67a00-55b5-11ea-8d6e-005186c1350b.png)
![image](https://user-images.githubusercontent.com/16503291/75099079-6a5ad280-55b5-11ea-9232-a832c800b838.png)

- Trying to commit
![image](https://user-images.githubusercontent.com/16503291/75099034-e7d21300-55b4-11ea-8100-2c754053e855.png)

### Logs
[2020-02-22.desktop.production.log](https://github.com/desktop/desktop/files/4239952/2020-02-22.desktop.production.log)

**Comment by svejnohatomas** [comment] 2020-02-23 11:17
Removing and adding the repository solved the problem.
Other repositories were working normally.

**Comment by billygriffin** [comment] 2020-02-24 15:49
@svejnohatomas I'm glad you got it figured out! Would you mind sharing whether there was something specific about this particular repo that was different than others? Was it renamed, or moved at some point recently? Just trying to dig into what might've caused the problem. Thanks!

**Comment by svejnohatomas** [comment] 2020-02-24 16:05
@billygriffin Thank you for your response.

I didn't do anything to the repo. It worked perfectly couple of hours before the bug occured.

The application displayed names of the changed files correctly, just the commit, discard, and diff were not working. No idea why.

**Comment by billygriffin** [comment] 2020-02-24 17:57
@svejnohatomas Agh, that's a bummer, thank you. I'm sorry that you were dealing with that. I'll defer to @steveward for a final call, but given that it's now resolved and we don't know how to reproduce it, I think we'll likely have to close the issue. 😞

**Comment by steveward** [comment] 2020-02-24 19:16
@svejnohatomas thanks for sharing those details -- since this isn't reproducible on your end I'm going to close this out, but please let us know if you run into this issue again.

**Closed by steveward** 2020-02-24 19:16 UTC
Labels: more-info-needed

**Comment by svejnohatomas** [comment] 2020-02-24 19:38
@steveward @billygriffin Thank you. I will let you know if I manage to reproduce the bug.

**Comment by svejnohatomas** [comment] 2020-02-29 00:46
@steveward @billygriffin I somehow reproduced the error. I will have a look at the log in the morning (UK time).
