### ISSUE TITLE
Squash Commits form does not get closed after a squash

### ISSUE THREAD

**Issue by notxcain** [desktop/desktop#16782] opened 2023-05-25 15:02 UTC
### The problem

The `Squash Commits` form does not get closed after the squash. 

### Release version

3.2.3

### Operating system

Mac OS 12.6.3

### Steps to reproduce the behavior

1. Drag one commit onto another
2. Click `Squash 2 Commits` button
3. The form resets but does not get closed

**Comment by steveward** [comment] 2023-05-26 13:18
Thanks for the report @notxcain, I was able to reproduce this as well and will mark it as a bug for the team to investigate.

**Comment by sergiou87** [comment] 2023-05-26 13:31
Hey @notxcain ! I think this is a duplicate of https://github.com/desktop/desktop/issues/16605, which was fixed in https://github.com/desktop/desktop/pull/16632 so it can be closed.

We'll try to release the fix soon 🤞 Thank you for your report anyway! 💖

**Closed as completed by sergiou87** 2023-05-26 13:31 UTC
Labels: bug, priority-3
