### ISSUE TITLE
GitHub Desktop authentication breaks when a cloned GitHub repo has it's remotes changed.

### ISSUE THREAD

**Issue by SteelPhase** [desktop/desktop#6415] opened 2018-12-13 21:12 UTC
## Description

Authentication fails when a repository that was previously cloned from GitHub, has its remotes changed to point to a location other than GitHub. When attempting to push or fetch I receive an `Authentication failed` message box. If you remove the repo, and add it with `Add Local Repository...` GitHub Desktop will ask for credentials. Is there some way that GitHub desktop could detect this situation, and remedy it?

## Version

* GitHub Desktop: Version 1.5.0

* Operating system: macOS 10.14

## Steps to Reproduce

1. Click `Fetch origin` or click `Push`

### Expected Behavior

Fetch or push complete as expected

### Actual Behavior

Receive `Authentication failed` message box

## Additional Information

It appears that the logic associated with this issue is located in `gitAuthenticationErrorHandler`.
The error handler would return the error without spawning the `promptForGenericGitAuthentication` dialog because GitHub Desktop still thinks the repo is a GitHub repo.

**Comment by tierninho** [comment] 2018-12-13 22:09
@SteelPhase Thanks for filing this issue.

This is a partial duplicate of https://github.com/desktop/desktop/issues/2521 which never resulted in us adding the capability to Desktop. (Note this was for *new* repos. I am not sure if we treat your repo as "new" because it is non-GitHub.)

Did you change the remote in Desktop or via the command line? 

Instructions for both:
https://help.github.com/articles/changing-a-remote-s-url/
https://help.github.com/desktop/guides/contributing-to-projects/changing-a-remote-s-url-from-github-desktop/

**Comment by SteelPhase** [comment] 2018-12-13 22:23
In this instance, I instructed the person affected to change the remote via the command line.

**Comment by SteelPhase** [comment] 2018-12-14 01:44
@tierninho #2521 doesn't appear to actually relate to this issue, except for the fact that I changed remotes.

This issue seems to be related to the Metadata about the repository stored in `GitStore`. If there was a method to refresh that metadata, I would assume this error could be solved without removing the repository from GitHub Desktop, and re-added.

**Comment by tierninho** [comment] 2018-12-14 16:14
@SteelPhase reopening for further investigation.

**Comment by outofambit** [comment] 2018-12-14 16:42
Hi @SteelPhase this is an interesting case. What kind of remote did you change to? Was it a GitHub Enterprise instance or another kind of git server entirely?

**Comment by SteelPhase** [comment] 2018-12-14 17:04
The new remote is just a vanity proxy in front of our new GitHub Enterprise service. We switched between two GitHub Enterprise instances at my company. Since a significant quantity of our projects were written in golang, we were required to change all our import paths during the conversion. We decided to go with the vanity proxy to prevent another rewrite if the company ever decided to change the GitHub enterprise domain in the future.

Outside of this oddity, it really hasn't been an issue. This was definitely an unexpected consequence of the change.

**Comment by outofambit** [comment] 2018-12-14 17:12
@SteelPhase that's totally understandable and I'm sorry you encountered this! Thanks for the extra context. I agree we should have logic to handle this case and you've correctly identified the place we should handle it:

https://github.com/desktop/desktop/blob/8fe1c9b43a0c0a24c74675b71ba5bde178e3d77f/app/src/lib/dispatcher/error-handlers.ts#L155-L160

I believe the solution is to add some logic here to prompt the user for their credentials for the new remote when the authentication fails. Does that sound right to you?

**Comment by SteelPhase** [comment] 2018-12-14 17:14
That sounds like it would solve the problem nicely, I wasn't sure it there was enough metadata currently stored to tell if the remote had been changed or not.

**Comment by outofambit** [comment] 2018-12-14 17:17
Awesome! We store the URL of the github repository at https://github.com/desktop/desktop/blob/8fe1c9b43a0c0a24c74675b71ba5bde178e3d77f/app/src/models/github-repository.ts#L16

so I think we can validate if the repository URL has changed by checking the remote against that. Thanks again for filing this! It will be a nice improvement.

**Comment by sergiou87** [comment] 2024-09-19 08:50
This seems to be fixed now, many changes around the authentication logic happened recently! ✨

**Closed by sergiou87** 2024-09-19 08:50 UTC
Labels: enhancement, help wanted, not-planned
