### ISSUE TITLE
Fixed width of file list obscures too much when paths are long

### ISSUE THREAD

**Issue by sambrown3** [desktop/desktop#4560] opened 2018-04-30 17:45 UTC
## Description
The fixed width of the filename list in a commit view is really frustrating, being able to drag to expand this like the list of commits would be great.

See attached, this is basically unusable. Hovering over file names to see what they are isn't ideal and there is no other reference to the full path + filename.

![screen shot 2018-04-30 at 1 38 47 pm](https://user-images.githubusercontent.com/1663250/39441644-9d3537f2-4c7c-11e8-8e77-8432dd685d44.png)

## Version
* GitHub Desktop: 1.1.1
* Operating system: High Sierra 10.13.4

## Steps to Reproduce
1. Click History
2. Select a commit
3. Try and figure out what file you are looking at from the list of files
4. :sob:

### Expected Behavior
Being able to expand the width of the subview would be great.

### Actual Behavior
Confusion.

## Additional Information
See attached.

### Logs
N/A

**Comment by iAmWillShepherd** [comment] 2018-04-30 18:32
Thanks for taking the time to open an issue! 🙇 

Desktop currently gives you the ability to resize this window as shown in the gif below 👇 
![2018-04-30 13 30 54](https://user-images.githubusercontent.com/1715082/39443646-e33713f8-4c7a-11e8-9709-2cc92fa873a9.gif)

**Comment by sambrown3** [comment] 2018-04-30 18:41
Correct, however, the max-width doesn't allow for situations where the path is long. The only way to see what file I'm looking at is hovering over each individually and waiting for the tooltip. See gif below: 

![2018-04-30 14_40_28](https://user-images.githubusercontent.com/1663250/39444096-8726db0c-4c84-11e8-9e82-b4d46e9d86c1.gif)

**Comment by iAmWillShepherd** [comment] 2018-05-01 15:37
Ahh, I see you meant the max-width. We constrain the width of each resizable component to ensure that our UI remains usable. 

We are using a fixed max-width regardless of window size, but maybe we can have the max-width be a function of the window size.

cc, @desktop/design for thoughts.

**Comment by niik** [comment] 2018-05-02 12:07
Hey @sambrown3, thanks for opening this.

I wrote up some our reasoning about this in https://github.com/desktop/desktop/issues/1588#issuecomment-329405096.

I feel like the problem is adequately captured in https://github.com/desktop/desktop/issues/2745 so I'm going to close this out and ask that you follow along in that issue for updates!

**Closed by niik** 2018-05-02 12:07 UTC
Labels: enhancement

**Comment by nicholaswright** [comment] 2019-06-27 09:49
> Ahh, I see you meant the max-width. We constrain the width of each resizable component to ensure that our UI remains usable.

I'd argue that constraining the width makes the UI unusable. I'd suggest you leave it to the user to decide. I work on a large screen and the width restriction is totally unnecessary and makes it impossible to review a list of long file names.
