### ISSUE TITLE
switching branches for large repository hangs from desktop, works find from git bash

### ISSUE THREAD

**Issue by TheWitness** [desktop/desktop#11429] opened 2021-01-20 21:22 UTC
### Describe the bug

We recently made a change where a number of files (hundreds) were moved to a new directory as we were adopting composer in order to support Github Actions.  Now, when we switch branches from 'develop' to '1.2.x' Git Desktop will randomly hang, and the Git Desktop looses track of the change showing thousands of files having changed states.

The repo can be found here: https://github.com/cacti/cacti.git

**So, it's pretty easy to reproduce.**  If I do the following from Git Bash, no issue,  and I've been going back and forth and can not get it to hang.

```
git checkout develop
git checkout 1.2.x
git checkout develop
...
```

### Version & OS

Windows 10, Desktop 2.6.2

### Steps to reproduce the behavior

See the notes above.

### Expected behavior

Git Desktop should be as reliable as the CLI client.

**Comment by TheWitness** [comment] 2021-01-20 21:26
This works perfectly.

```bash
thewitness@hostname MINGW64 ~/Documents/GitHub/cacti (develop)
$ git checkout 1.2.x
Updating files: 100% (7351/7351), done.
Switched to a new branch '1.2.x'
Branch '1.2.x' set up to track remote branch '1.2.x' from 'origin'.

thewitness@hostname  MINGW64 ~/Documents/GitHub/cacti (1.2.x)
$ git checkout develop
Updating files: 100% (7351/7351), done.
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.

thewitness@hostname  MINGW64 ~/Documents/GitHub/cacti (develop)
$ git checkout 1.2.x
Updating files: 100% (7351/7351), done.
Switched to branch '1.2.x'
Your branch is up to date with 'origin/1.2.x'.

thewitness@hostname  MINGW64 ~/Documents/GitHub/cacti (1.2.x)
$ git checkout develop
Updating files: 100% (7351/7351), done.
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.

thewitness@hostname MINGW64 ~/Documents/GitHub/cacti (develop)
$ git checkout 1.2.x
Updating files: 100% (7351/7351), done.
Switched to branch '1.2.x'
Your branch is up to date with 'origin/1.2.x'.

thewitness@hostname MINGW64 ~/Documents/GitHub/cacti (1.2.x)
$ git checkout develop
Updating files: 100% (7351/7351), done.
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
```

**Comment by steveward** [comment] 2021-01-20 22:12
Thanks for the report @TheWitness. I'll work on reproducing this. Would you mind sharing the log file so I could take a closer look at the performance statistics available there?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by TheWitness** [comment] 2021-01-20 22:17
[logs.zip](https://github.com/desktop/desktop/files/5845615/logs.zip)

**Comment by TheWitness** [comment] 2021-01-20 22:18
There you go.

**Comment by TheWitness** [comment] 2021-01-20 22:19
This is what is left after attempting to switch branches after it times out or crashes.

![image](https://user-images.githubusercontent.com/1439914/105247944-95420380-5b43-11eb-9adb-14372c71dadb.png)

**Comment by TheWitness** [comment] 2021-01-20 22:25
I think I've got a fresh case.  Going to wait until it clears to get you a single clean log file.

**Comment by TheWitness** [comment] 2021-01-20 22:36
Okay, it's byork'd again.  Here is what the screen look like.  The log looks empty.  I'm going to reboot to flush out the process that is likely still hung out there.

![image](https://user-images.githubusercontent.com/1439914/105249343-f9fe5d80-5b45-11eb-8b01-389cd5c36a3c.png)

**Comment by TheWitness** [comment] 2021-01-20 22:40
[2021-01-20.desktop.production.log](https://github.com/desktop/desktop/files/5845706/2021-01-20.desktop.production.log)

Latest log file after window timed out, backend process was hung, rebooted, and then restarted Git Desktop.

**Comment by TheWitness** [comment] 2021-01-20 22:41
Looks pretty clean.  Let me check the Windows Application log.

**Comment by TheWitness** [comment] 2021-01-20 22:47
Just some DCOM permission Issues with a CLSID.  Don't think that would be your guys stuff.

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user WORKGROUP\localhost SID (-redacted-) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

**Comment by steveward** [comment] 2021-01-21 14:30
@TheWitness thanks for sharing your logs. It looks like since you have a large number of repositories the background fetching that GitHub Desktop is doing for each repository is taking between 20-30 seconds. I'd like for you to try disabling background fetching to see if that helps with this issue. To do this you can go to `File` > `Options` > `Advanced` and uncheck the `Periodically fetch and refresh status of all repositories`.

Let me know if that seems to fix the issue for you.

**Comment by TheWitness** [comment] 2021-01-21 14:45
@steveward, I'll check, but I have two working environments, one with 5 repos, and the other with 20 or so.  It breaks on both.  I'll do some more testing on the 5 repo case with the setting though.

**Comment by steveward** [comment] 2021-01-21 15:07
@TheWitness thanks for the update. I was wondering if you were hitting lockups when background fetching was still occurring while trying to switch branches, but if it's consistent across both environments then that is likely not the cause of the issue.

**Comment by TheWitness** [comment] 2021-01-21 18:59
I disabled things and so far have not been able to cause it to lockup.  So, I think that you have discovered a workaround.

**Comment by TheWitness** [comment] 2021-01-22 12:07
Well I'll be doing a complicated merge this weekend with backup updates disabled.  It that works, then it point to just that feature.

**Comment by TheWitness** [comment] 2021-01-23 15:39
I've tried to switch branches on php-src, and the desktop right now is totally unreliable.  The php-src has almost 700k deltas.  So, Houston we have a problem.

**Comment by steveward** [comment] 2024-09-18 19:01
@TheWitness are you still seeing this issue when switching branches in GitHub Desktop? We're going through old issues and trying to close out any that are stale.

**Comment by TheWitness** [comment] 2024-09-18 21:31
@steveward, we are not using that branch any longer.  I'll test and let you know.

**Comment by TheWitness** [comment] 2024-09-18 21:37
It's not locking up at all right now everything's fine.

**Comment by steveward** [comment] 2024-09-19 14:56
Thanks, appreciate the follow up! I'll close this out.

**Closed as completed by steveward** 2024-09-19 14:56 UTC
