### ISSUE TITLE
Credentials are not stored consistently and github auth tends to break

### ISSUE THREAD

**Issue by xPaw** [desktop/desktop#2254] opened 2017-07-16 16:36 UTC
**GitHub Desktop version:** 0.6.2
**OS version:** Windows 10 16241

It seems to me that authentication with GitHub tends to break if I push from different CLIs (e.g. open from inside github or file explorer), and requires me to authenticate again, which I already did multiple times while using the desktop beta.

Latest log when I tried to push from the UI today:
```
2017-07-16T16:31:17.940Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 1.135s)
2017-07-16T16:31:49.036Z - warn: [shared] fetchAccount: failed with endpoint https://api.github.com
undefined: Requires authentication
```

 I opened the CLI from within the UI and did a `git push` which worked and pushed to GitHub successfully.

I don't know the exact steps to make it lose authentication, as I have not yet hit this consistently.

**Comment by joshaber** [comment] 2017-07-17 15:14
Thanks for opening this @xPaw! That's really curious.

If you go to Preferences and log out and then back in again, does it stick?

**Comment by xPaw** [comment] 2017-07-17 18:03
@joshaber I have tried re-logging in from preferences once before, which did work, but then it mysteriously broke again.

**Comment by joshaber** [comment] 2017-07-17 19:33
Well huh. I'm having a hard time coming up with any theories about what's happening. I'm not sure how/why the CLI would effect the credentials stored in the app 🤔 

@desktop/core Anyone have any theories?

**Comment by shiftkey** [comment] 2017-07-26 12:32
@joshaber some theories off the top of my head:

 - credential backing store isn't persisting credentials due to the account name containing unicode characters - this could be #189 but the fact it's occurring randomly makes me think it's not this
 - an external tool is overwriting the credentials for the Desktop app (accidentally or otherwise) - this shouldn't be the case, but would fit with being hard to reproduce

There's other, more convoluted theories about the how Git will clear credentials on failure but I don't think they're relevant here because we're using `GIT_ASKPASS` which doesn't support that (I think?).

@xPaw the next time this happens to you, let's check the state of the two places we check to stitch together your account information:

 - Open **View** | **Toggle developer tools** and navigate to the local storage for the app. Here's the click order:

<img width="944" src="https://user-images.githubusercontent.com/359239/28620682-5ae08af0-71e4-11e7-851d-f145f74d8c0e.png">

If there's no `users` element here, that's a sign that something in the app has corrupted things.

 - From the start menu, launch **Manage Windows Credentials** and see if there is an entry for `GitHub - https://api.github.com/{account}` - here's mine:

<img width="825" src="https://user-images.githubusercontent.com/359239/28620780-d751e642-71e4-11e7-957b-066d11a4d623.png">

If that's not there (and I think this is more likely) then we need to look into related tools that might be clobbering this value.

**Comment by shiftkey** [comment] 2017-07-26 12:33
> GitHub tends to break if I push from different CLIs (e.g. open from inside github or file explorer)

@xPaw could you tell me more about the other tools you have installed and might be using to trigger this issue?

**Comment by xPaw** [comment] 2017-07-26 12:41
@shiftkey I only have git (2.13.0.windows.1) installed from the official site, and `hub` (2.3.0-pre9).

**Comment by xPaw** [comment] 2017-07-26 12:44
In windows credential storage, I have two GitHub related entries: 
![26-124345091](https://user-images.githubusercontent.com/613331/28621312-32268e4a-7219-11e7-88c0-8138227c540f.png)

In localStorage I have the `users` object, but `token` inside of it appears to be empty:
![26-124417246](https://user-images.githubusercontent.com/613331/28621341-48e7a10a-7219-11e7-9843-b33601ca858b.png)

I have tried doing `git pull`, `hub sync` in every CLI and Desktop, it currently appears to work everywhere. I will make sure to check the storage after (if) it breaks again.

**Comment by shiftkey** [comment] 2017-07-26 12:47
> In localStorage I have the `users` object, but token inside of it appears to be empty:

This is by design - the token is stored in the credential store and cleared before storing the user information in local storage.

**Comment by shiftkey** [comment] 2017-07-26 12:48
@xPaw Git for Windows has it's own credential manager and backing store (that's the `git:` entry) but I'm not familiar with what `hub` uses for it's credential store. I can go investigating the next time you spot this issue.

**Comment by xPaw** [comment] 2017-07-26 12:53
Another thing I forgot about, this seemed to happen when interacting with non-github.com repositories. I have yet to see this issue as I have moved these repositories to github.com. Could be related?

**Comment by shiftkey** [comment] 2017-07-26 12:58
> Another thing I forgot about, this seemed to happen when interacting with non-github.com repositories.

We need to support authentication for non-GitHub remotes, so that not working seems to be the expected behaviour currently - #1552 is the tracking issue and #2335 was just opened.

**Comment by xPaw** [comment] 2017-07-26 12:59
Login into non-github remotes is possible when using CLI, but that most likely was the cause of breaking github.com login. I no longer have a different git server to test this theory.

**Comment by shiftkey** [comment] 2017-07-26 13:25
@xPaw I can explain the current behaviour for non-GitHub remotes in the Desktop GUI, and see how that lines up with what you were seeing before.

If you were to try and push/pull to a non-GitHub repository from in the app, you'd get this error:

![](https://user-images.githubusercontent.com/12808002/27126808-3ceed85a-512b-11e7-8628-4c8d1a66542a.png)

This isn't an accurate message, because of how Desktop sets itself up to handle credentials if Git prompts. 

The TL;DR of this is:

 - we set `GIT_ASKPASS` to refer to ourselves to serve credentials **if you're signed into GitHub and it's a GitHub repository**
 - to ensure we don't accidentally use a credential helper, we disable that for network operations
 - we also set `GIT_TERMINAL_PROMPT` environment variable to`0` to ensure Git doesn't prompt for credentials as a fallback (if we don't, Git may hang waiting for user input in the background)

It's this combination of things that means authentication won't work for non-GitHub remotes currently.

**Comment by xPaw** [comment] 2017-07-26 13:27
@shiftkey Sure, that message appeared. The problem is that it would also appear for GitHub repos (hence the auth breakage in initial issue report).

**Comment by shiftkey** [comment] 2017-07-26 13:28
> The problem is that it would also appear for GitHub repos (hence the auth breakage in initial issue report).

:thumbsup: I'll leave this open and let's see if you can trigger it again.

**Comment by xPaw** [comment] 2017-08-08 19:49
So I just managed to get this issue. I just updated github desktop, and the auth is broken again. localStorage has `users` as expected, however Windows credentials are gone, both git and github ones. As to why they are gone, that's a good question.

**Comment by shiftkey** [comment] 2017-08-14 02:36
> however Windows credentials are gone, both git and github ones. As to why they are gone, that's a good question.

This is very interesting, and I'm not sure what might be causing **both** sets of credentials to be removed from the OS. Are there _any_ credentials left over under the Generic group? Maybe some rogue program is trying to be too clever and is accidentally removing these.

**Comment by xPaw** [comment] 2017-08-16 10:25
@shiftkey I see `virtualapp/didlogical` in there which is at least month old.

Today my git(hub) credentials were nuked again, I certainly do not understand why that happens.

**Comment by joshaber** [comment] 2017-09-11 14:30
I'm gonna close this. Until we get more reports or reproduction steps, there's not much we can do 😞

**Closed by joshaber** 2017-09-11 14:30 UTC
Labels: needs-reproduction

**Comment by xPaw** [comment] 2017-09-11 18:37
@joshaber This issue sounds rather familiar, could be related: https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/58
