### ISSUE TITLE
macOS: can't close window in fullscreen

### ISSUE THREAD

**Issue by OliverKersting** [desktop/desktop#8077] opened 2019-08-07 18:05 UTC
## Description

When being in fullscreen mode. I can not close the application with the read icon 'x' in the top left corner.

## Version

* GitHub Desktop: 2.1.0

* Operating system: macOS Mojave Version 10.14.6 (18G87)

## Steps to Reproduce

1. install GitHubDesktop for macOS
2. go fullscreen (view->toggle fullscreen or green icon in top left corner)
3. try to close window via red icon in top left corner
### Expected Behavior
Application should close

### Actual Behavior
Nothing happens. Sometimes the screen switches to another running application (like safari). But GitHub Desktop is still opened. 

## Additional Information

This bug was already reported (macOS: can't close window while fullscreen #5287). It has been 'fixed', but I still have the same problem.

### Logs

[2019-08-07.desktop.production.log](https://github.com/desktop/desktop/files/3478331/2019-08-07.desktop.production.log)

**Comment by tierninho** [comment] 2019-08-07 18:53
@OliverKersting Thanks for filing this issue.

Looks like it might be an Electron issue as reported here: https://github.com/electron/electron/issues/18842

However, I can not reproduce it despite having the same builds. 

Let's see what we can find and hopefully a fix will come soon.

**Comment by tierninho** [comment] 2019-11-01 01:43
Going to close this issue has it has not been reported by anyone else. Happy to reopen if it resurfaces.

**Closed by tierninho** 2019-11-01 01:43 UTC
Labels: investigation-needed
