### ISSUE TITLE
ENOENT error when publishing new repository

### ISSUE THREAD

**Issue by snorepion** [desktop/desktop#3747] opened 2018-01-09 03:22 UTC
### Description

When attempting to publish a new repository, I receive this error:

    ENOENT: no such file or directory, mkdtemp 'C:\Users\[name]\AppData\Local\Temp;C:\MinGW\bin\GitHubDesktop-lfs-progress-XXXXXX'

The problem with this is that both of those directories exist and GitHub is running in administrator mode so it should be able to access those. I uninstalled GitHub and deleted all correlated files and registry keys to no avail.

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Windows 6.3.9600

### Steps to Reproduce

1. I wrote the code and used GitHub Desktop to create a new repository in the folder containing all of my code files.

2. I clicked the 'Publish' button and received this error.

3. I tried "soft" reinstalling GitHub Desktop by using Programs and Features to remove it. 

4. Once this didn't work, I reinstalled it and used Revo Uninstaller to locate all related files and registry entries, deleting every one.

5. I tried again and it still didn't work, so I deleted the content of C:/Users/[me]/AppData/Local/Temp and double-checked the permissions to make sure it could write to it.

6. I rebooted my PC (this really should've been an earlier step). Still nothing.

**Expected behavior:** Publishing my repository without errors.

**Actual behavior:** Did not publish, received ENOENT instead.

**Reproduces how often:** 100% of the time

### Logs

It appears that the log is mostly full of information about being unable to fetch my account picture (that's happening as well), but that's a much less important issue to me. I don't know which pieces exactly are relevant. It can be found [here](https://pastebin.com/7tPjbH75) for the sake of making this issue concise.

**Comment by shiftkey** [comment] 2018-01-09 11:12
This is a duplicate of #3072 - your `TEMP` or `TMP` environment variable contains multiple paths - you should update the environment variable so it only contains one path.

**Closed by shiftkey** 2018-01-09 11:12 UTC
Labels: Windows

**Comment by snorepion** [comment] 2018-01-09 22:03
Thank you and sorry for posting a duplicate. I searched for some key terms but couldn't find anything.

**Comment by piotrrybinski88** [comment] 2018-04-12 22:54
ENOENT: no such file or directory, mkdtemp 'C:\Users\piotr\AppData\Local\Temp;\GitHubDesktop-lfs-progress-XXXXXX'
I updated my TEMP and TMP environment variable to : 
TEMP : %USERPROFILE%\AppData\Local\Temp
TMP : %USERPROFILE%\AppData\Local\Temp 
I reinstalled github and rebooted my computer. 
What can i do next ?

**Comment by shiftkey** [comment] 2018-04-12 23:48
@piotrrybinski88 ensure you don't have a trailing `;` on the path for both environment variables, as that seems to have been the issue here.

**Comment by piotrrybinski88** [comment] 2018-04-13 10:11
Ohhh, so easy. 
Thank you very much for your help.

**Comment by sostenesapollo12** [comment] 2019-04-11 19:16
> environment

This worked for me
