### ISSUE TITLE
Window dragging does not work

### ISSUE THREAD

**Issue by radRoy** [desktop/desktop#17371] opened 2023-09-11 09:49 UTC
### The problem

When trying to drag the GitHub Desktop window from one screen to another, or from maximised to one side of the same screen, it does not work and snaps back to the window size from when it was first opened. This continues unless I hold the mouse button while not moving the window for a while, or unless I just do the window moving by keyboard shortcuts.

This is annoying but does not affect the working of the program.

Might be noteworthy that I have 3 screens with different resolutions and refresh rates, one connected to the motherboard and two to the graphics card.

### Release version

Version 3.3.1 (x64)

### Operating system

Windows 10 Pro 22H2

### Steps to reproduce the behavior

1. Open the program
2. Maximise the window
3. Drag the window with the mouse to another screen or wherever.
4. To get the white bar on top of the window (image below), from step 2, drag it to another screen to directly maximise it.

### Screenshots

![bug report GitHub Desktop](https://github.com/desktop/desktop/assets/91153524/89563514-c996-4ec1-941c-b95787f3edcc)

### Additional context

notice the weird white boarder on top of the window, and it's a bit cut off.

**Comment by tidy-dev** [comment] 2023-09-11 11:53
Thank you for the report @radRoy. I believe this is a duplicate of https://github.com/desktop/desktop/issues/16498 and I am going to close in favor of tracking it there.

**Closed as completed by tidy-dev** 2023-09-11 11:53 UTC
