### ISSUE TITLE
White screen unresponsive after changing Account password

### ISSUE THREAD

**Issue by amostajo** [desktop/desktop#8065] opened 2019-08-02 20:20 UTC
This might be related to other tasks.

I recently changed my GitHub password, and upon restarting the App it went completely white, had to follow the next steps to fix it but in the process had to map again all my working repos:
https://github.com/desktop/desktop/issues/3478

Looks like the app does not log out the user upon failed authentication, and instead of requesting the user for new credentials it goes white screen and produces fatal errors.

Hope this helps fix related issues, regards.

**Comment by tierninho** [comment] 2019-08-02 20:46
@amostajo Many thanks for the details. I will attempt to reproduce this and file a bug if necessary. 

Closing the issue for as it was self-resolved.

**Comment by tierninho** [comment] 2019-08-03 00:25
Attempted to reproduce this error and was unsuccessful on Windows 10. 

@amostajo If you still have the logs from that day, please send over. See the Help menu to find them. Thanks.

**Comment by richielee888** [comment] 2019-08-05 04:15
how do I get this to open files without coding. im a preschooler with this stuff

**Comment by tierninho** [comment] 2019-08-05 18:06
@richielee888 Not sure what you are referring to. Please file a new issue [here](https://github.com/desktop/desktop/issues/new/choose)

**Comment by tierninho** [comment] 2019-08-09 18:20
Closing this out due to inactivity.

**Closed by tierninho** 2019-08-09 18:20 UTC
Labels: more-info-needed

**Comment by HAMZA6669** [comment] 2022-03-07 20:10
white screen problem 
please help,me?
