### ISSUE TITLE
Hashtag number is turned into an issue link even if the issue doesn't exist

### ISSUE THREAD

**Issue by karimbenammar** [desktop/desktop#2663] opened 2017-09-09 20:13 UTC
### Description

Hi, I just made a commit named "Huge update #2"
Then when I check the commits history I click on the commit to check the description and in the title of the commit I find that the "#2" is blue (contains a link) , and redirects me to this link:
https://github.com/my_username/project_name/issues/2
And of course it's a 404 Error
I don't think it's the behaviour you would like to have in the software ^_^

### Version

**GitHub Desktop version:** 0.8.1-beta4

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Name a commit: [anything_here] + [#] + [any_number_here]
Example: "first commit #25"
2. Check the title of the commit in the right window
3. The [any_number_here] field takes you to the number of issue

**Expected behavior:** Title shows up without any links

**Actual behavior:** Title takes you to a page that doesn't exist

**Reproduces how often:** 100%

**Comment by shiftkey** [comment] 2017-09-10 21:32
@karimbenammar a couple of related questions:

 - is the repository private? If so, are you signed into the browser when it launches?
 - is the repository a fork? If so, this feels like it's a duplicate of #1277

**Comment by j-f1** [comment] 2017-09-10 21:41
@shiftkey I think @karimbenammar is saying that any issue number will be linked, even if that issue hasn’t been opened yet.

**Comment by shiftkey** [comment] 2017-09-10 21:49
@j-f1 yeah, we don't do any validation of issue references (that's #1277) but for completeness I'd like some more information about the repository at least.

**Closed** 2018-02-03 12:59 UTC
Labels: bug
