### ISSUE TITLE
Branch created on 27th but in Github desktop it is showing 5 days ago...

### ISSUE THREAD

**Issue by santoshgadagamma** [desktop/desktop#10675] opened 2020-09-28 13:58 UTC
### Windows 10

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

In visual studio i have created a branch on 27th september but in the github desktop it is showing 5 days and no changes were found or recorded in the corresponding branch.

So please request your team to restore the changes in local git.

**Comment by niik** [comment] 2020-09-28 14:01
Hi @santoshgadagamma, thanks for opening this.

Branches in Git doesn't have creation dates or any other metadata like that. Therefore GitHub Desktop uses the commit date of the last commit on a branch as the date displayed alongside the branch in the branch list. Most of the time that date makes the most sense to use for feature branches but there are cases, like the one you're describing where it can be counterintuitive.

I hope that helps explain the discrepancy. Since this is the intended behavior I'm going to go ahead and close this issue. Thanks!

**Closed by niik** 2020-09-28 14:01 UTC
