### ISSUE TITLE
Show diff for text files that contain special characters

### ISSUE THREAD

**Issue by kocsismate** [desktop/desktop#9023] opened 2020-01-31 19:18 UTC
I'd like to see the diff for text files that contain special characters.

Currently, GitHub Desktop fails to render the diff for example for this file: https://github.com/php/php-src/blob/master/ext/standard/tests/strings/strstr.phpt in this commit: https://github.com/php/php-src/commit/8b36be268d2ac2ab77162ed540db6aab9c819a83

**Comment by tierninho** [comment] 2020-01-31 19:49
@kocsismate Thanks for filing. I am confirming I see the same thing.

![Screen Shot 2020-01-31 at 9 46 42 AM](https://user-images.githubusercontent.com/14828183/73569489-9fd52b80-440e-11ea-8795-e8de109313c1.png)

Is this issue a feature request or do you believe this to be a bug? I spotted this existing issue, which may be related: https://github.com/desktop/desktop/issues/3923

**Comment by kocsismate** [comment] 2020-01-31 20:03
@tierninho Thanks for the fast response!

I think it is a bug because the diff can be rendered correctly both by using command-line git diff and PHPStorm.

I am not sure the linked issue is really related because I faced the issue on the changes and history tab as well. Additionally, in our case, we don't really have locale-dependent characters, but rather control characters.

**Comment by tierninho** [comment] 2020-01-31 20:26
Thanks for the update.

Can someone from @desktop/core verify the intended diff rendering or add some color?

**Comment by outofambit** [comment] 2020-02-07 23:08
Yes I agree this is a bug, and unfortunately what looks to be among many text encoding related issues we have. I would consider this a duplicate of #3923. I'm going to close this issue and continue further discussion in #3923. @kocsismate if you could add something about your use case and impacts of this problem to that issue that would help us think through prioritization more. Thank you!

**Closed by outofambit** 2020-02-07 23:08 UTC
Labels: more-info-needed
