### ISSUE TITLE
Diff pane scrolling changes directions randomly on macOS after updating to 1.1.0

### ISSUE THREAD

**Issue by lnikkila** [desktop/desktop#4297] opened 2018-03-21 19:07 UTC
## Description

After updating to 1.1.0 (I think), the scroll direction in the diff pane changes randomly while I scroll using my track pad. Often once I’ve scrolled to the bottom, it’s impossible to scroll back up again and I need to drag the scroll bar.

The direction seems to change once I lift my fingers from the touch pad while the “momentum” scrolling keeps going in the original direction. I have natural scrolling enabled on macOS, but disabling it doesn’t seem to affect this. Scrolling the “changed files“ pane seems to work normally.

## Version

* GitHub Desktop: 1.1.0

* Operating system: macOS High Sierra 10.13.2 (17C88)

## Steps to Reproduce

1. Make lots of changes to some file
2. Select that file and scroll up and down in the diff pane

### Expected Behavior

Content should scroll normally.

### Actual Behavior

Scrolling changes directions randomly.

## Additional Information

Video:
https://streamable.com/39ugl

In the video I’m only scrolling down/up until the end is reached, then I change directions.

### Logs

Nothing relevant in there.

**Comment by iAmWillShepherd** [comment] 2018-03-22 17:44
Thanks for taking the time to open an issue! 🙇 

Unfortunately, I am unable to produce this on my machine. Are there any additional details you can provide about your machine's configuration?

**Comment by lnikkila** [comment] 2018-03-22 23:26
Hmm, I restarted the app and it stopped doing that. Usually I keep it running all the time and only restart it to update. It was doing that for the whole time after installing the latest update, even after a day or two of use. I was switching between files and projects and closing/reopening the window.

Unfortunately I don’t have any further clues into how it started happening. In case it helps, I’m using a MacBook Pro (Retina, 15-inch, Late 2013) with the built-in touch pad, no peripherals.

I don’t think I have anything installed that would affect mouse inputs. The only somewhat relevant thing I can think of is <https://spectacleapp.com> which resizes windows with keyboard shortcuts, I sometimes use it with the GitHub window as well.

**Comment by esayre-um** [comment] 2018-03-26 21:00
Had the same issue. Restarting the app corrected it for me too. Not sure what caused it but will try to keep an eye out. I had just updated to 1.1.1 and am uncertain of the version I was previously running.

**Comment by iAmWillShepherd** [comment] 2018-03-27 21:12
@lnikkila @esayre-um , does this behavior happen in any other apps? I'm curious if this is an underlying OS issue or something we may be doing.

**Comment by lnikkila** [comment] 2018-03-27 21:36
No, I haven’t seen this in any other app. I’m running several Electron apps, e.g. Slack and React Native Debugger.

**Comment by esayre-um** [comment] 2018-03-27 22:27
@iAmWillShepherd I've only noticed it the one time in Github… been using it extensively all day without incident.

**Comment by iAmWillShepherd** [comment] 2018-03-28 17:40
Hmm, I used that same track pad in addition to the one on a 2015 MBP, 2017 MBP, and a Logi MX Master. Coulnd't reproduce on any.

**Comment by iAmWillShepherd** [comment] 2018-03-28 18:39
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1380. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-03-28 18:39 UTC
Labels: more-information-needed, reviewer-needs-to-reproduce
