### ISSUE TITLE
github desktop does not solicit a path for install

### ISSUE THREAD

**Issue by diplomaticENTERTAINMENT** [desktop/desktop#10370] opened 2020-08-12 15:24 UTC
Hey so !

This is a really, really, really big bug. It makes me think that no one uses GitHub anymore, likely they already finished.
Projects done, nothing new to do. No ideas.

So yeah. Apparently nobody is using GitHub Desktop if this is still a problem.

The version is 2.5.3 and when you download it, which is convenient - its stated where it is located in the Unreal Engine seminar.

Then when you execute it, oh yeh it installs "freestyle" like it owns the world or something and even says it'll launch when its done.

I mean - is this a pirate operation? You're not even using the regular windows related installation stuff
This is likely because you are "UNIX GEEKS" (boomers) and "dont like bill gates because he doesnt wear tighty whities'

so you're suicidal essentially for avoiding the, well let's just say The Right Way To Do Things.

Literally right now, Unreal Engine doesn't even have a clue where GitHub desktop is installed
So I have to tell it manually.

AND SURPRISE SURPRISE ITS NO WHERE TO BE FOUND.

i'm guessing you don't like the fact that I have not only 10 partitions but a file server, two M.2 drives, a whole array of SSDs striped

operating system separate from applications, application volume set to 1MB clusters, separated paging partition
literally have a caching one in addition to the paging one for apps

and that's not even the file server

this is a problem for you? being smart?

**Comment by Mr1262** [comment] 2020-08-12 15:38
Thanks sir

**Comment by diplomaticENTERTAINMENT** [comment] 2020-08-12 15:42
am i mistaken in believing that i have to install GIT before installing GITDESKTOP ?
to use with unreal engine --- the seminar says to download gitdesktop, then when he goes into the SOURCE CONTROL part of unreal engine
(this guy is not a great docs guy honestly i think hes like $30K salary guy)

his stuff is already set up from before because he didnt do a clean install - so

like
i did what he did and im pretty sure i have to install git?
in addition to gitdesktop

**Comment by lee-dohm** [comment] 2020-08-12 16:16
This is a duplicate of [a previous issue](https://github.com/github/desktop/issues/485). Since this is a duplicate, I'm going to close this. You may wish to continue the conversation there.

**However,** @diplomaticENTERTAINMENT your comments are in violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md) as they are insulting or derogatory. You may consider this an official warning. Any further violations will result in being blocked from participation here.

**Closed by lee-dohm** 2020-08-12 16:16 UTC

**Comment by diplomaticENTERTAINMENT** [comment] 2020-08-12 17:18
what? its a violation of the constitution to break any speech into any kind of part of speech
what you're saying, if you're not violating federal law, is that my speech is speech and you're good with it

right.

**Comment by diplomaticENTERTAINMENT** [comment] 2020-08-12 17:22
yeh and i already have another bug this is what i figured
i deleted the repository off github and its still there so gitdesktop wont let me re-commit
