### ISSUE TITLE
TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#1520] opened 2017-05-16 21:30 UTC
Not a terribly helpful stack trace:

```
at EventEmitter.X.ipcRenderer.once (file:///app/renderer.js:1:41820)
    at Object.onceWrapper (events.js:290:19)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
```

https://haystack.githubapp.com/desktop/needles/539CpTjMKZ2e9sBF750QnQ

**Comment by shiftkey** [comment] 2017-05-16 21:33
Could this be menu-related (e.g. https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/ui/changes/changed-file.tsx#L86) ?

**Comment by shiftkey** [comment] 2017-05-17 02:36
The minified string around this code gives it away:

```
I.showContextualMenu=function(J){X.ipcRenderer.once('contextual-menu-action',(Q,Z)=>{const ee=
```

It's here https://github.com/desktop/desktop/blob/3dc8738e711131047f9973398a5dac08e2cd206e/app/src/ui/main-process-proxy.ts#L66. Putting together a fix and some tracing.

**Comment by niik** [comment] 2017-05-17 06:53
I accidentally opened a duplicate of this in #1532 but that now has more context so I'm gonna close this and refer to #1532

**Closed by niik** 2017-05-17 06:53 UTC
Labels: bug, needs-reproduction
