### ISSUE TITLE
Where is the 'Roll Back to this Commit' menu?

### ISSUE THREAD

**Issue by liyuhang1997** [desktop/desktop#2347] opened 2017-07-27 13:47 UTC
### Description

Where is the 'Roll Back to this Commit' menu?

### Version

**GitHub Desktop version:** 3.3.4.0

**OS version:** Microsoft Windows [版本 10.0.15063]

### Steps to Reproduce

1. commit: Added .gitattributes"
1. commit: add hello
1. commit: add good morning
1. commit: Revert "add good morning"
1. Select commit: Added .gitattributes"

**Expected behavior:** find 'Roll Back to this Commit' menu

**Actual behavior:** nothing

**Reproduces how often:**

**Comment by shiftkey** [comment] 2017-07-27 14:03
@liyuhang1997 "Roll Back to this Commit" was a feature of the earlier GitHub for Mac apps that we decided to deprecate as part of the Desktop unification for a couple of reasons:

 - it wasn't implemented on the GitHub for Windows app
 - we found various corner cases where the behaviour was buggy, especially when merge commits were involved
 - we didn't really get much feedback on the feature, even when it was removed there

I'm not sure we'll bring it back at this stage, because it really doesn't have an equivalent action in the underlying Git CLI (`reset --hard` is probably the closest I can think of, but that's really destructive and not something we want to encourage).

Could you tell me a bit about your workflow and why you think it is useful?

**Comment by Eliijahh** [comment] 2017-07-27 23:23
Wouldn't this be a duplicate of this issue #752 ?

**Comment by shiftkey** [comment] 2017-07-27 23:31
@Eliijahh afraid not - "Revert Commit" would add a new commit on top of the current branch. "Rollback" was intended to go back in history and throw away the commits after a certain point in time.

> Also, question from me: as in GitHub browser you can revert a merged request, is there any plan to implement that in GitHub Desktop as well?

You could do this in the client by reverting the merge commit, which is #752.

**Comment by liyuhang1997** [comment] 2017-07-29 13:52
@shiftkey I was GitHub beginners, i was watching a GitHub teaching video, but i did not find this menu so i was puzzled and now i understand. Thx!

**Closed** 2017-07-29 13:53 UTC
Labels: enhancement

**Comment by clearsitedesigns** [comment] 2020-11-24 15:39
Still seems like this should be a pretty basic feautre, why would I nee dto go to command line for this? This is not good user experience.
