### ISSUE TITLE
Does not load, shows white screen

### ISSUE THREAD

**Issue by miyasudokoro** [desktop/desktop#13922] opened 2022-02-16 17:35 UTC
### Describe the bug
I clicked on the "update and restart" link this morning, and now it loads only a white screen. I was using the app normally prior to that point.

I have uninstalled and reinstalled via a fresh download and that did not resolve the issue.

### Version & OS

Windows 10
It's currently whatever version you could download at 2/16/2022 10:13am MDT -- maybe 2.9.7?. Because there is no menu, I can't see the version.

### Steps to reproduce the behavior

1. Choose the option of "update and restart"

### Expected behavior

1. It restarts itself automatically
2. It loads its UI

### Actual behavior

1. Does not automatically restart after the update
2. If the app is started manually, shows an unmovable white rectangle

### Screenshots

![image](https://user-images.githubusercontent.com/7283837/154321554-dafa3f57-82f1-440d-b5cc-183bacc06b1a.png)

### Logs

Please tell me where to find the logs so I can upload them. As I said, there is no menu, only a big white rectangle.

### Additional context

I have been using Github Desktop for at least a couple years and never had any issues before. I have 50+ repositories checked out, most from a private Gitlab repo, and one from a Github repo. The private Gitlab recently moved and I have not yet gotten around to fixing the URLs of every local repo.

**Comment by tidy-dev** [comment] 2022-02-16 18:20
@miyasudokoro This appears to be a duplicate of #13906. I am closing this one in favor of tracking it there.

**Closed as completed by tidy-dev** 2022-02-16 18:20 UTC
