### ISSUE TITLE
Github cant push or pull or even clone, but if I try using command line, it works just fine

### ISSUE THREAD

**Issue by bladegalaxy** [desktop/desktop#17849] opened 2023-12-09 15:50 UTC
### The problem

When trying to clone, or pull or push to github. It stays loading with no logs or anything. It just hangs there forever. If I tried using the command line it works just fine.

![Screenshot 2023-12-09 234548](https://github.com/desktop/desktop/assets/83349914/c737b5dc-14c6-474f-b931-f9c261b5cd40)

### Release version

3.3.7-beta1

### Operating system

Windows 11

### Steps to reproduce the behavior

Committing anything.

### Log files

[2023-12-09.desktop.beta.log](https://github.com/desktop/desktop/files/13624595/2023-12-09.desktop.beta.log)
The logs show me trying to commit using the command line but no logs on what the GitHub desktop is doing

### Additional context

I am using a new PC so I was trying to move my projects to this PC. So i freshly installed desktop along with downloading git. i have switched between the beta version and release version and both seem to have this issue.

**Comment by steveward** [comment] 2023-12-11 14:37
Thanks for the report @bladegalaxy. Normally there's fetch/clone operation in the log showing an extended delay, but I'm not seeing that here like you said. Are there any other logs we could take a look at?

Also, are you running any antivirus software or behind a firewall? Security software is a common cause of Git operations being slow.

**Comment by bladegalaxy** [comment] 2024-01-01 09:48
@steveward sorry for the late reply, all the logs are the same, with different versions of GitHub desktop. I don't have any antivirus installed, what do you mean by behind a firewall? Is there a rule that is blocking Github desktop? 
because normal git functions don't have this hanging issue in the command line

**Comment by steveward** [comment] 2024-01-02 19:51
@bladegalaxy we've seen specific instances where GitHub Desktop is blocked even if command line Git operations succeed, since firewall/antivirus can often block specific applications from performing network operations.

**Comment by bladegalaxy** [comment] 2024-01-04 15:55
I am not sure if I am doing the right way to check this issue, but I have tried turning off my firewall completely to check if GitHub can push and it still has the same behavior. Pushing makes no progress, loads there forever, same with pulling
I have tried the production build of GitHub desktop.
[2024-01-04.desktop.production.log](https://github.com/desktop/desktop/files/13832345/2024-01-04.desktop.production.log)

**Comment by Mergpijp** [comment] 2024-01-17 22:13
Hi, i got the same issue here is the log.
[2024-01-17.desktop.production.log](https://github.com/desktop/desktop/files/13969266/2024-01-17.desktop.production.log)

**Comment by MikeSchulze** [comment] 2024-04-10 08:22
I run into the same issue. It always hangs after fetch, push, pull.
This error occurs only for new added repositories to the app, my old existing/added repositories have no issues. 
So it can't be a firewall issue, the previous added repositories still work.
![image](https://github.com/desktop/desktop/assets/347037/89f9ba5f-521d-4424-9321-c0492defa588)

Version 3.3.13 (x64)

Form the logs is see no errors.
```
2024-04-10T07:50:54.585Z - info: [ui] [AppStore] adding repository at D:\development\workspace\gdUnit4Net to store
2024-04-10T08:01:26.451Z - info: [ui] [Timing] Action 'create commit' for 'MikeSchulze/gdUnit4Net' took 0.371s
2024-04-10T08:01:40.036Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-04-10T08:01:40.231Z - info: [ui] [AppStore] loading 6 repositories from store
2024-04-10T08:01:40.231Z - info: [ui] [AppStore] found account: MikeSchulze (Nullpointer)
2024-04-10T08:01:40.241Z - info: [ui] [BranchPruner] Last prune took place 11 minutes ago - skipping
2024-04-10T08:01:40.332Z - info: [ui] launching: 3.3.13 (Windows 10.0.22631)
2024-04-10T08:01:40.332Z - info: [ui] execPath: 'C:\Users\mikes\AppData\Local\GitHubDesktop\app-3.3.13\GitHubDesktop.exe'
2024-04-10T08:01:40.567Z - info: [ui] Subscribed 'MikeSchulze' to Alive channel
2024-04-10T08:01:47.074Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: gdUnit4Net - MikeSchulze (has token)
2024-04-10T08:03:27.969Z - info: [main] opening in browser: https://github.com/MikeSchulze/gdUnit4Net/pull/new/master...GD-80

```
## Update
I played around clone/fetch/pull and find the issue

This bug only occurs when do a manual git clone of a repository and add it later as a reference.
When using the clone repository from the desktop app it works, i able to fetch without hanging.

For manual git clone I used the Windows `Git Bash` (mingw64)

### Steps to reproduce

* open Windows `Git Bash` (mingw64) console
* navigate to your favorite folder
* use `git clone  <your repository url>`
* open the GitHub Desktop Version 3.3.13 (x64)
* using `add existing repository` and add
* press the 'fetch origin` button
It hangs

**Comment by steveward** [comment] 2024-04-11 20:35
@MikeSchulze are you using SSH or HTTPS?

**Comment by MikeSchulze** [comment] 2024-04-12 05:58
> @MikeSchulze are you using SSH or HTTPS?

To authenticate and clone is use SSH

**Comment by steveward** [comment] 2024-04-12 14:50
@MikeSchulze can you see if you have `Use system OpenSSH` selected under `File` > `Options` > `Advanced`? Try changing that option to see if it gets things working for you.

**Comment by MikeSchulze** [comment] 2024-04-12 16:11
> @MikeSchulze can you see if you have `Use system OpenSSH` selected under `File` > `Options` > `Advanced`? Try changing that option to see if it gets things working for you.

When I disable `OpenSSH` and enter the password and checkmark the remember checkbox, it works. 👍

**Comment by JPZV** [comment] 2024-07-15 15:46
I have exactly the same issue as @MikeSchulze (Cloned SSH rep from GitLab and then added manually in GitHub Desktop). Changing the OpenSSH option doesn't works as it stays in "Pushing to Origin... Hang on" state for ever.

Logs doesn't shows anything also. And pushing manually through PowerShell works perfectly (almost instantly).

Also note that the SSH Key has a passphrase, which in GitHub Desktop for Ubuntu works fine (it asks me the passphrare), but in Windows it doesn't ask anything, just hanging it there.

**Comment by steveward** [comment] 2024-07-15 19:34
@JPZV try closing out GitHub Desktop (and ending any lingering processes), then uncheck `Use system OpenSSH` and try cloning again.

**Closed as completed by steveward** 2024-07-15 19:34 UTC

**Comment by JPZV** [comment] 2024-07-15 20:25
I tried closing and opening GitHub many times, rebooting, and nothing. On Windows it fails when using SSH instead of HTTPS. But in Ubuntu it works perfectly with the exact same Repo.

Logs from Windows (Please note how many times I tried reopening the app):

```
2024-07-15T15:38:09.733Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T15:38:10.159Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T15:38:10.159Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T15:38:10.382Z - info: [ui] launching: 3.4.1 (Windows 10.0.22631)
2024-07-15T15:38:10.383Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.1\GitHubDesktop.exe'
2024-07-15T15:38:10.970Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T15:43:06.701Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T15:43:07.277Z - info: [main] Received possible protocol arguments: 2
2024-07-15T15:43:07.295Z - error: [main] Malformed launch arguments received: C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe,--squirrel-firstrun
2024-07-15T15:43:07.295Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T15:43:07.611Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T15:43:07.612Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T15:43:07.837Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T15:43:07.837Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-15T15:43:08.409Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T15:43:59.999Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T15:44:00.260Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T15:44:00.267Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T15:44:00.267Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T15:44:00.455Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T15:44:00.455Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-15T20:06:47.154Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T20:06:47.770Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T20:06:47.771Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T20:06:47.959Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T20:06:47.960Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-15T20:06:48.801Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T20:07:17.592Z - info: [ui] [Timing] Action 'create commit' for 'WebAccess' took 0.602s
2024-07-15T20:12:13.989Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T20:12:14.245Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T20:12:14.245Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T20:12:14.384Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T20:12:14.387Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-15T20:12:15.030Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T20:13:57.096Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T20:13:57.353Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T20:13:57.354Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T20:13:57.547Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T20:13:57.548Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
2024-07-15T20:13:58.132Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T20:14:29.690Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-07-15T20:14:29.934Z - info: [ui] Subscribed 'JPZV' to Alive channel
2024-07-15T20:14:29.943Z - info: [ui] [AppStore] loading 49 repositories from store
2024-07-15T20:14:29.944Z - info: [ui] [AppStore] found account: JPZV (JPZV)
2024-07-15T20:14:30.159Z - info: [ui] launching: 3.4.2 (Windows 10.0.22631)
2024-07-15T20:14:30.160Z - info: [ui] execPath: 'C:\Users\juanp\AppData\Local\GitHubDesktop\app-3.4.2\GitHubDesktop.exe'
```

Logs from Ubuntu (same repo, just cloning):

```
2024-07-15T20:18:04.029Z - info: [ui] [AppStore] loading 0 repositories from store
2024-07-15T20:18:04.138Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-07-15T20:18:04.550Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-07-15T20:18:04.651Z - info: [ui] Opt in reported.
2024-07-15T20:18:05.091Z - info: [ui] launching: 3.3.12-linux2 (Linux 6.8.0-36-generic)
2024-07-15T20:18:05.093Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2024-07-15T20:18:05.166Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-07-15T20:18:07.483Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-07-15T20:18:07.510Z - info: [ui] [Welcome] no sign in step found. ignoring...
2024-07-15T20:18:10.048Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2024-07-15T20:19:05.896Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'git@gitlab.com:kitraaccess/software/web/webaccess.git'
2024-07-15T20:19:08.497Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- git@gitlab.com:[redacted].git /home/juanp/Documents/GitHub/[Redacted] (took 2.551s)
2024-07-15T20:19:08.504Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- git@gitlab.com:[redacted] /home/juanp/Documents/GitHub/[Redacted]` exited with an unexpected code: 128.
stderr:
Cloning into '/home/juanp/Documents/GitHub/[Redacted]'...
Warning: Permanently added 'gitlab.com' (ED25519) to the list of known hosts.
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

### Added the pub key to GitLab. -JPZV ###

2024-07-15T20:21:44.171Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'git@gitlab.com:[redacted]'
2024-07-15T20:21:51.836Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=main clone --recursive --progress -- git@gitlab.com:[redacted] /home/juanp/Documents/GitHub/[Redacted] (took 7.608s)
2024-07-15T20:21:51.872Z - info: [ui] [AppStore] adding repository at /home/juanp/Documents/GitHub/[Redacted] to store
```

So this issue should be reopen, as the problem persists

**Comment by PiklioBezGashti** [comment] 2025-09-04 12:06
i have same problem like @MikeSchulze 

> > [@MikeSchulze](https://github.com/MikeSchulze) can you see if you have `Use system OpenSSH` selected under `File` > `Options` > `Advanced`? Try changing that option to see if it gets things working for you.
> 
> When I disable `OpenSSH` and enter the password and checkmark the remember checkbox, it works. 👍

but this do not exist anymore in last version 3.5.2
