### ISSUE TITLE
Version 2.1.0 github desktop app is not creating the branch it is taking more time to create branch

### ISSUE THREAD

**Issue by MobackChetanKumar** [desktop/desktop#8106] opened 2019-08-14 10:06 UTC
## Description

Version 2.1.0 GitHub desktop app is not creating the branch it is taking more time to create a branch and I have to close the create branch popup and again create multiple times

## Version

* GitHub Desktop:

* Operating system:

## Steps to Reproduce
List the steps to reproduce your issue **below** this comment
ex,
1. In the Master branch making some changes and that is reflected in the Github desktop app
2. Now trying to create a branch from it and the branch creation will be infinite
3. if we close the branch creation popup and go and check for the branch there will be a branch with the same name with some random timing

### Expected Behavior
The branch has to create immediately

### Actual Behavior
Branch creation will be infinite

## Additional Information

Place any additional information, configuration, or data that might be necessary to reproduce the issue **below** this comment
1) Windows 10 
2) Github desktop version 2.1.0
3) 
![image](https://user-images.githubusercontent.com/49486326/63027665-fa171a00-beca-11e9-838c-5bc1fa0670c0.png)

**Comment by billygriffin** [comment] 2019-08-14 13:49
@MobackChetanKumar Would you mind filling out the bug report template to help us diagnose the issue? I'm editing your original issue with that template so all you have to do is fill in the information there, and then respond so we get notified. Thanks!

**Comment by MobackChetanKumar** [comment] 2019-08-14 14:12
@billygriffin ,

Updated issue reproducible scenario and configuration

**Comment by tierninho** [comment] 2019-08-14 18:23
@MobackChetanKumar I believe the reason for the failure of the branch creation is that you are using a `/` in the new branch and there is already a branch with a similar name. For instance you have branch `zzz` and you attempt to create branch `zzz/123` it will fail due to this error:

```
install.ts:23 `git branch abc/123 master` exited with an unexpected code: 128.
stderr:
fatal: cannot lock ref 'refs/heads/abc/123': 'refs/heads/abc' exists; cannot create 'refs/heads/abc/123'

error @ install.ts:23
08:10:17.061 install.ts:23 createBranch failed
GitError: fatal: cannot lock ref 'refs/heads/abc/123': 'refs/heads/abc' exists; cannot create 'refs/heads/abc/123'

    at Object.t.git (/webpack:/app/src/lib/git/core.ts:176:2)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Do you already have a `feature` branch?

@desktop/core Is this intended? At minimum we might want to consider some validation or error messaging here?

v2.1.1, mac

**Comment by tierninho** [comment] 2019-08-15 00:53
Actually, closing this issue out as it is a duplicate of https://github.com/desktop/desktop/issues/5997

Please follow along there.

**Closed by tierninho** 2019-08-15 00:53 UTC
Labels: more-info-needed
