### ISSUE TITLE
Wrong Default Icon Everywhere

### ISSUE THREAD

**Issue by rei-vilo** [desktop/desktop#1687] opened 2017-05-22 13:31 UTC
The same default icon appears everywhere, on Windows and macOS as well.

![capture 2017-05-22 a 15 33 22](https://cloud.githubusercontent.com/assets/951776/26311346/46f80fd0-3f04-11e7-8139-f6a4dd9d42c1.png)

* Github version 0.5.5
* Windows 10 Pro 1703 15063.296
* macOS 10.12.5

Thank you!

**Comment by zhuowei** [comment] 2017-05-22 14:39
I think this is a duplicate of #1621.

**Comment by shiftkey** [comment] 2017-05-22 14:51
@rei-vilo is this repository available publicly? It'd be nice to see why the commit information isn't aligning with what you're expecting...

**Comment by rei-vilo** [comment] 2017-05-22 15:01
Yes, it is. See https://github.com/rei-vilo/Galaxia_Library

I am not sure whether it is a duplicate, as some icons may signal status or action instead of avatar. In case it is a duplicate, please feel free to close it. Thank you!

**Comment by George35mk** [comment] 2017-05-22 17:47
i have the same

**Comment by rlabrecque** [comment] 2017-05-23 06:25
This frequently happens with after a first launch on Windows, part of it is may also be due to #1679.  Restarting often seems to fix it.

**Comment by tierninho** [comment] 2017-05-23 13:20
@rei-vilo So this is the issue:
https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/

Looks like your account and git are using both hotmail and yahoo emails you have. Hotmail on your public profile, and Yahoo in git settings seen in Desktop:
<img width="701" alt="screen shot 2017-05-23 at 9 06 16 am" src="https://cloud.githubusercontent.com/assets/14828183/26355991/99df1b0a-3f98-11e7-8aee-73732ade4dac.png">

**Comment by tierninho** [comment] 2017-05-23 13:22
@shiftkey ok to close this?

**Closed** 2017-05-23 13:25 UTC

**Comment by shiftkey** [comment] 2017-05-23 13:28
@tierninho the only gap in this theory is that the commit history does show the correct avatar: https://github.com/rei-vilo/Galaxia_Library/commits/master.

It looks like @rei-vilo has closed this out :metal:

**Comment by rei-vilo** [comment] 2017-05-23 13:34
I did change my primary GitHub e-mail address but, even when I enter the full e-mail address as credential instead of the screen-name, I'm still having the [hubot.png](https://avatars2.githubusercontent.com/u/480938?v=3) icon.

![480938](https://avatars2.githubusercontent.com/u/480938?v=3)

So it may not be an issue with the Desktop app, but rather with the website.

**Comment by tierninho** [comment] 2017-05-23 14:54
@rei-vilo looks like your gravtar email is your yahoo one. I can change to your hotmail if needed.

<img width="765" alt="screen shot 2017-05-23 at 10 52 50 am" src="https://cloud.githubusercontent.com/assets/14828183/26360479/2d8a9386-3fa6-11e7-8ef8-9b2e09aac799.png">

**Comment by rei-vilo** [comment] 2017-05-23 15:03
Thank you for the tip!
