### ISSUE TITLE
error on launch: "git version >= [X] is required for Git LFS, your version: [blank]"

### ISSUE THREAD

**Issue by robdew** [desktop/desktop#5247] opened 2018-07-25 14:35 UTC
## Description

Error on launch about invalid version of Git LFS

## Version

* GitHub Desktop: 1.2.6

* Operating system: Microsoft Windows [Version 10.0.16299.547]

## Steps to Reproduce

Unsure what changes to the app or my environment may have occurred to cause this to occur.  It happens on app launch every time now.
### Expected Behavior

No error should occur, this issue is new; have been using app for 6 mos on same system with same repos without a problem.
### Actual Behavior

Error message about required version of Git LFS not installed.
It will not recognize any of my remote repositories if you click the Close button.  It treats all my repos as local only and wants me to publish them.
Logs say:
````
2018-07-25T14:23:15.361Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
git version >= 1.8.2 is required for Git LFS, your version: 
````
that log line isn't cutoff (log file below).  It's not reporting a version.
## Additional Information

````powershell
PS C:\Program Files\Git\mingw64\bin> .\git-lfs.exe version
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
````
![gitlfserror](https://user-images.githubusercontent.com/3137089/43207287-5b96f42a-8fed-11e8-9da7-c458bc516f85.png)

### Logs

[2018-07-25.desktop.production.log](https://github.com/desktop/desktop/files/2228256/2018-07-25.desktop.production.log)

**Comment by shiftkey** [comment] 2018-07-25 14:47
@robdew thanks for the report!

We're using a bundled version of Git LFS but that's also version `2.4.2` so I'm puzzled about this issue. Two extra things I need to help troubleshoot this issue further:

 - which version of Git for Windows do you have installed?
 - what does your current PATH look like?

**Comment by shiftkey** [comment] 2018-07-25 15:14
@robdew it's interesting that you don't have `C:\Program Files\Git\cmd` on your path - that is an option when installing.

Can you check what the outputs of these commands are (CMD is fine)?

```
> where git
```

For context: this is the problem check that we're encountering:

```go
func requireGitVersion() {
	minimumGit := "1.8.2"


	if !git.IsGitVersionAtLeast(minimumGit) {
		gitver, err := git.Version()
		if err != nil {
			Exit("Error getting git version: %s", err)
		}
		Exit("git version >= %s is required for Git LFS, your version: %s", minimumGit, gitver)
	}
}
```

My theory here is that something else on your PATH happens to be named `git.exe` and it is being used instead of the one that comes with Desktop, and it returns an empty output when responding to `git version`:


```go
func Version() (string, error) {
	gitVersionMu.Lock()
	defer gitVersionMu.Unlock()


	if gitVersion == nil {
		v, err := subprocess.SimpleExec("git", "version")
		gitVersion = &v
		return v, err
	}


	return *gitVersion, nil
}
```

**Comment by robdew** [comment] 2018-07-25 15:22
````
C:\Program Files\Git>where git
INFO: Could not find files for the given pattern(s).
````

**Comment by mpauser** [comment] 2018-08-13 00:32
I've hit this issue today as well and have been unable to resolve it. Our company did do a Git upgrade over the weekend -- but on 2 of 3 dev boxes I do not hit this issue. Of course, on the primary (aka good) box I do~

GitHub Desktop error message:
![image](https://user-images.githubusercontent.com/17074910/44008169-1aee49ac-9e55-11e8-94d5-00578f7964ca.png)

I re-installed both Git and GitHub Desktop -- even though I was already at these versions. In reading the above chain, I moved git\cmd and githubdesktop\bin towards the front of the system PATH -- but still hit this issue.

```
Path=C:\windows;C:\windows\system32;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\SysWOW64;c:\util;c:\java\jre\bin;C:\PROGRA~1\Git\cmd;C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\bin; ...
```

```
git --version
git version 2.18.0.windows.1

which git
C:/PROGRA~1/Git/cmd/git.exe
```

```
git-lfs --version
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)

which git-lfs
C:/PROGRA~1/Git/cmd/git-lfs.exe
```

```
ver
Microsoft Windows [Version 6.1.7601]
```

```
dir c:\git.exe /s/l/b
c:\program files\git\bin\git.exe
c:\program files\git\cmd\git.exe
c:\program files\git\mingw64\bin\git.exe
c:\program files\git\mingw64\libexec\git-core\git.exe
c:\users\ibm_admin\appdata\local\atom\app-1.28.2\resources\app.asar.unpacked\node_modules\dugite\git\cmd\git.exe
c:\users\ibm_admin\appdata\local\atom\app-1.28.2\resources\app.asar.unpacked\node_modules\dugite\git\mingw64\bin\git.exe
c:\users\ibm_admin\appdata\local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\dugite\git\cmd\git.exe
c:\users\ibm_admin\appdata\local\atom\app-1.29.0\resources\app.asar.unpacked\node_modules\dugite\git\mingw64\bin\git.exe
c:\users\ibm_admin\appdata\local\github\portablegit_f02737a78695063deace08e96d5042710d3e32db\cmd\git.exe
c:\users\ibm_admin\appdata\local\github\portablegit_f02737a78695063deace08e96d5042710d3e32db\mingw32\bin\git.exe
c:\users\ibm_admin\appdata\local\github\portablegit_f02737a78695063deace08e96d5042710d3e32db\mingw32\libexec\git-core\git.exe
c:\users\ibm_admin\appdata\local\githubdesktop\app-1.3.2\resources\app\git\cmd\git.exe
c:\users\ibm_admin\appdata\local\githubdesktop\app-1.3.2\resources\app\git\mingw64\bin\git.exe
c:\users\ibm_admin\appdata\local\squirreltemp\tempb\lib\net45\resources\app\git\cmd\git.exe
c:\users\ibm_admin\appdata\local\squirreltemp\tempb\lib\net45\resources\app\git\mingw64\bin\git.exe
```

I had also tried installing git-lfs directly, but as you said it's already part of Git Desktop. If you need any additional information, please let me know. Thank you @shiftkey

**Comment by mz2017** [comment] 2018-08-13 03:52
I ran into this problem today. Don't think anything in my computer changed between last night (when it worked fine) and this morning (when the error message complaining about the Git version showed up). I checked what people mentioned here, nothing stands out. This is frustrating.

**Comment by shiftkey** [comment] 2018-08-13 11:43
Hey @ttaylorr any thoughts on how we can troubleshoot what the root cause of this issue is? Nothing is really standing out from the typical stuff I've checked with users.

**Comment by mpauser** [comment] 2018-08-13 15:53
I signed out of Git Desktop, uninstalled Git + Git Desktop, cleaned registry, rebooted and re-installed Git Desktop. Same error. From the Git Desktop log, there is an error
``2018-08-13T15:51:16.328Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
git version >= 1.8.2 is required for Git LFS, your version: ``

```
2018-08-13T15:51:15.468Z - info: [ui] [AppStore] loading 1 repositories from store
2018-08-13T15:51:15.469Z - info: [ui] [AppStore] found account: pauser (pauser)
2018-08-13T15:51:15.768Z - info: [ui] launching: 1.3.2 (Windows 6.1.7601)
2018-08-13T15:51:15.769Z - info: [ui] execPath: 'C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.3.2\GitHubDesktop.exe'
2018-08-13T15:51:16.196Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pauser - pauser (has token)
2018-08-13T15:51:16.328Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
git version >= 1.8.2 is required for Git LFS, your version: 

2018-08-13T15:51:17.107Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pauser - pauser (has token)
2018-08-13T15:51:17.141Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pauser - pauser (has token)
```

**Comment by mpauser** [comment] 2018-08-13 16:02
I ran ``git lfs env`` and the GIT_LFS_PATH pointed to a directory that did not exist -- ``C:\Program Files\Git LFS``. I did a ``set GIT_LFS_PATH=c:\program files\git\cmd\`` but the same error. Attaching the output:

```
C:\Program Files>git lfs env
git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)


Error: Failed to call git rev-parse --git-dir --show-toplevel: ""
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDir=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/PROGRA~1/Git/mingw64/libexec/git-core
GIT_LFS_PATH=c:\program files\git\cmd\
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Comment by mpauser** [comment] 2018-08-13 20:40
I also have since reinstalled the latest Git 2.18.0.windows.1 and when I launched the Git GUI I got:
![image](https://user-images.githubusercontent.com/17074910/44056823-3d6e73c2-9efe-11e8-8cbd-a7ff414d99f9.png)

**Comment by mpauser** [comment] 2018-08-14 18:53
Thank you @shiftkey for your reponses. Slowly but surely, other developers here are encountering the same issue. I spent most of Monday looking at my system and it appears that our corporate office rolled out Carbon Black Defense on my system Sunday, and when I went to use it Monday git was borked. Can't be uninstalled, can't stop the services, can't stop the processes -- yet Control Panel > Programs shows the Carbon Black Defense. 

Today, other developers are reporting that git isn't working -- same issues as I reported -- and in checking their systems Carbon Black Defense was installed last night.

My guess is its treating the git processes as viruses and blocking them from accessing the registry to get the version information, etc. Just a hunch at this point. I'm going to have my box re-imaged and hopefully get to try Git Desktop once again before this CBD gets installed.

**Comment by shiftkey** [comment] 2018-08-14 19:48
> My guess is its treating the git processes as viruses and blocking them from accessing the registry to get the version information, etc. 

Two things:

 - the `git.exe` bundled in Desktop and Git for Windows should be signed - maybe the product needs to be configured to trust this signer/signature?

<img width="607" src="https://user-images.githubusercontent.com/359239/44114484-b20f0f96-9fe1-11e8-8caf-e51e688f9978.png">

 -  Git LFS does it's version check by spawning a child process for `git`:

```go
func Version() (string, error) {
	gitVersionMu.Lock()
	defer gitVersionMu.Unlock()


	if gitVersion == nil {
		v, err := subprocess.SimpleExec("git", "version")
		gitVersion = &v
		return v, err
	}


	return *gitVersion, nil
}
```

Something interfering with that would explain the cascading failures in Desktop, and Git GUI looks like it does the same thing:

```sh
// assigning "git version" output to _git_version
if {[catch {set _git_version [git --version]} err]} {
	catch {wm withdraw .}
	tk_messageBox \
		-icon error \
		-type ok \
		-title [mc "git-gui: fatal error"] \
		-message "Cannot determine Git version:
$err
[appname] requires Git 1.5.0 or later."
	exit 1
}
// the original call doesn't error, so check the output matches our expected format
if {![regsub {^git version } $_git_version {} _git_version]} {
	catch {wm withdraw .}
        // draw a message box with the contents of the output (an empty string?)
	tk_messageBox \
		-icon error \
		-type ok \
		-title [mc "git-gui: fatal error"] \
		-message [strcat [mc "Cannot parse Git version string:"] "\n\n$_git_version"]
	exit 1
}
```

**Comment by robdew** [comment] 2018-08-14 22:04
I also happen to be our Carbon Black admin and I don't see any git components or GitHubDesktop.exe being treated differently by our Cb policy rules.  I specifically looked all all events on my computer around the timeframe I reported this issue, and there are no failed or blocked events. So at least for my computer this is not the root cause.
Git is also not new to us so the underlying git executeables have never been affected by our Carbon Black protection policy rules outside of this problem.  That may not be the same for other orgs but it's not an issue for us.

**Comment by elimbaum** [comment] 2018-08-15 14:45
I've just reinstalled Github Desktop on Windows 7, but `C:\Program Files\Git` does not exist. I also have Carbon Black installed on my workstation. I had Git working for a while previously.

My `PATH` includes `C:\Users\[USER]\AppData\Local\GitHubDesktop\bin` but nothing else related to Git, so I cannot call `git` from the command prompt. I have tried uninstalling, reinstalling, etc.

**Comment by shiftkey** [comment] 2018-08-15 14:51
> My PATH includes `C:\Users\[USER]\AppData\Local\GitHubDesktop\bin` but nothing else related to Git, so I cannot call git from the command prompt. I have tried uninstalling, reinstalling, etc.

GitHub Desktop ships an embedded Git that isn't added to your PATH. You'll have to install [Git for Windows](https://gitforwindows.org/) if you want Git under `C:\Program Files` and accessible on your PATH.

**Comment by elimbaum** [comment] 2018-08-15 15:02
Ok, that's fine. But I'm still getting the LFS issue, and can't clone any repos.

**Comment by mpauser** [comment] 2018-08-15 19:10
@shiftkey Our CIO office confirmed that Carbon Black is the issue that is preventing Git from working correctly. They're rolling out a fix and I'm hopeful that it'll resolve the issue. Thanks again for your assistance. This issue can probably be closed.

**Comment by shiftkey** [comment] 2018-08-15 20:03
@mpauser that's excellent news!

Please report back if it resolves the issue and I'll leave this open for a bit to see if others in this thread can confirm whether they have Carbon Black on their machines that might also be suffering from the same issue.

cc @robdew @elimbaum

**Comment by ttaylorr** [comment] 2018-08-20 15:14
> Hey @ttaylorr any thoughts on how we can troubleshoot what the root
> cause of this issue is?

It sounds like the problem boils down to either (1) not having a valid
Git executable on your `$PATH`, or (2) another program munging with it.

Since just spawn "git" from Git LFS, I can't think of anything else
interesting on the Git LFS side that would be causing this.

**Comment by shiftkey** [comment] 2018-08-20 19:14
@ttaylorr 

> (2) another program munging with it.

Yeah, it's basically this. Sigh.

**Comment by robdew** [comment] 2018-08-23 02:33
I continue to use git from the command line and VS Code git integrations with no issues on the same system that still has the original problem. Please let me know what I can do to troubleshoot/determine what program is causing the problem.

**Comment by shiftkey** [comment] 2018-08-23 12:36
> I continue to use git from the command line and VS Code git integrations with no issues on the same system that still has the original problem.

I suspect these uses are fine because they don't touch Git LFS - Desktop uses `git lfs` to probe for whether your repository has Git LFS enabled.

> Please let me know what I can do to troubleshoot/determine what program is causing the problem.

I'm not sure at this point, but @mpauser earlier suggested that Carbon Black on their machine needed an update which was on it's way (but I'm not sure which versions work or don't work as I've not heard back in over a week). What version of Carbon Black do you have installed? Are there updates pending that might address it?

**Comment by mpauser** [comment] 2018-08-23 17:36
We have Carbon Black 3.2 installed. Our CIO office had to add some special rule to allow the git calls to go through, I don't know what the rule(s) were though. Once they did that, my Git Desktop is once again working. Thanks

**Comment by wangwan000** [comment] 2018-08-28 15:45
I also hit the same problem without any explicit change on my laptop.  When I view the certificate of C:\Users\IBM_ADMIN\AppData\Local\GitHubDesktop\app-1.3.4\resources\app\git\cmd\git.exe, it says "Valid from 6/11/2017 to 6/12/2018".  Though I successfully used github desktop after 6/12/2018, it stops working now.

**Comment by wangwan000** [comment] 2018-08-28 18:36
OK, I got it working by installing Git client and RESTART the computer.

**Comment by shiftkey** [comment] 2018-09-26 13:20
I'm going to close this out because I don't believe there's anything we can do in Desktop to address this, and it seems like updates to products like Carbon Black should resolve the issue eventually.

**Closed by shiftkey** 2018-09-26 13:20 UTC
