### ISSUE TITLE
clicking red 'X' on macOS doesn't close app

### ISSUE THREAD

**Issue by ramtronik** [desktop/desktop#12391] opened 2021-06-07 13:53 UTC
seems to occur after making a commit. just opening an closing the app is ok, but do something with it, switch out and back to it, and it doesn't respond to the red 'X'

**Comment by steveward** [comment] 2021-06-07 16:06
Thanks for the report @ramtronik. I was unable to reproduce this issue -- would you be able to make a short video displaying the behavior?

**Comment by ramtronik** [comment] 2021-06-07 16:12
Typical, it always does it to me, but not when I try to reproduce.

What is different is, I usually have it in the background, maximised and I ctrl-arrow to a different screen. Maybe it’s a time thing ? I usually close it down when xcode gets sluggish, and tghen the red x is inoperative…

Regards,
PHil

**Comment by ramtronik** [comment] 2021-06-07 16:18
Ok, so I can do it reliably now.

1: open it from the shortcut icon on the launch bar.

2: ensure full-screen with green maximise  icon.

3: ctrl-arrow to desktop.

4: click icon on launchpad to re-open github.

No amount of clicking ‘x’ will work, but click menu ‘Github Desktop’, quit works.

I’m also still seeing the ‘all files are new’ issue despite upgrading my github today. So, it’s as buggy as it ever was for me. That’s a known issue, I’ve seen it online.

Regards,
Phil
From: Phillip Abraham
Sent: 07 June 2021 17:12
To: desktop/desktop ***@***.***>; desktop/desktop ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [desktop/desktop] clicking red 'X' on macOS doesn't close app (#12391)

Typical, it always does it to me, but not when I try to reproduce.

What is different is, I usually have it in the background, maximised and I ctrl-arrow to a different screen. Maybe it’s a time thing ? I usually close it down when xcode gets sluggish, and tghen the red x is inoperative…

Regards,
PHil

**Comment by tidy-dev** [comment] 2021-06-08 14:14
Was able to reproduce.. Thanks for the additional repro steps @ramtronik. An easy work around I found was to just use the green arrow to go out of full screen mode and then hit x. I know that is not a solution.. but hopefully will help you till we have time to prioritize this bug.

**Comment by ramtronik** [comment] 2021-06-08 14:17
Ah, that’s cool. It’s not a show-stopper by any means, but it does make me think like ‘I’m sure I closed this thing already LOL’ ……

the bug I logged about the ‘all files show as new’ is a lot more annoying/disruptive …

regards,
Phil

**Comment by steveward** [comment] 2021-07-12 20:49
Closing as a duplicate of #9757.

**Closed as completed by steveward** 2021-07-12 20:49 UTC
Labels: priority-3
