### ISSUE TITLE
Changes pane not wide enough

### ISSUE THREAD

**Issue by fpark12** [desktop/desktop#2421] opened 2017-08-08 21:10 UTC
### Description

When changed files have very long path names, github fails to allow users to widen the Changes pane enough to show the full paths. 

### Version

**GitHub Desktop version:** Version 0.7.2

**OS version:** Windows 10 x64

### Steps to Reproduce

1. Change files that have long path names
2. Go to Changes pane and observe that the list of changed files would have abbreviated paths.
3. Click and drag the right side of the pane to expand it to see the full paths of the files and fail because the max width is limited.

**Expected behavior:** User should be able to extend the window freely to show full file paths.

**Actual behavior:** Changes pane has a predefined max width.

**Reproduces how often:** 100%

**Comment by joshaber** [comment] 2017-08-08 21:13
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1588. Please follow that issue for further updates.

**Closed by joshaber** 2017-08-08 21:13 UTC
