### ISSUE TITLE
Move to recycle bin no longer working on Windows 10

### ISSUE THREAD

**Issue by AssetKid** [desktop/desktop#10433] opened 2020-08-24 14:53 UTC
### Describe the bug

The `Also move this repository to Recycle Bin` option no longer works. The file is not moved to the recycle bin.

### Version & OS

v2.5.4 | Windows 10 v2004

### Steps to reproduce the behavior

1. Remove...
2. Select the `Also move this repository to Recycle Bin` option.
3. Remove button.

### Expected behavior

Folder should be moved to the recycle bin.

### Actual behavior

Folder is not moved to the recycle bin.

### Screenshots

![image](https://user-images.githubusercontent.com/40426812/91060580-cf11eb00-e633-11ea-9616-9cc828c45ddf.png)

### Logs

`info: [ui] [BranchPruner] No branches to prune.`

### Additional context

Potential Cause: https://github.com/desktop/desktop/pull/10143

**Comment by niik** [comment] 2020-08-24 15:23
Hey @AssetKid, thanks for opening this and sorry to hear you're having problems deleting repositories. I tried this myself and I was unable to reproduce it. Can you try creating a brand new repository from within the app and then removing it (including moving it to the Recycle Bin) and see if it's still reproducible?

I'm wondering if you're hitting https://github.com/desktop/desktop/pull/8333. I.e. there's an open file within the repository and the removal fails because of that. Due to what seems to be a bug in electron we're not able to detect when a delete fails and show an appropriate error message.

![remove-test](https://user-images.githubusercontent.com/634063/91063492-5d836e00-e62e-11ea-86c8-64034ed217cc.gif)

**Comment by AssetKid** [comment] 2020-08-24 15:35
It is working as expected after creating a repo from within the app.

**Comment by niik** [comment] 2020-08-25 06:29
Thanks for confirming @AssetKid. I'm going to close this since we have a PR open to resolve this as soon as electron has a fix out on their side

**Closed** 2020-08-25 06:29 UTC
Labels: more-info-needed
