### ISSUE TITLE
Duplicated squash modal 

### ISSUE THREAD

**Issue by Wentong-Liu** [desktop/desktop#16842] opened 2023-06-06 03:58 UTC
### The problem

When squash commits, it first pops up a modal for commit message. After click "squash commits" it pops up again. See screenshots below

### Release version

Version 3.2.3 (arm64)

### Operating system

Mac OS 13.3.1 (22E261)

### Steps to reproduce the behavior

1. Go to history
2. select multiple commits
3. right click and select "squash 2 commits"
4. input some message on the modal
5. the modal pops up again

### Screenshots

![iShot_2023-06-06_11 51 24](https://github.com/desktop/desktop/assets/12538593/ed26ff88-cada-45e2-9312-74dbfa52b5ec)

**Comment by sergiou87** [comment] 2023-06-06 07:51
Duplicate of https://github.com/desktop/desktop/issues/16605, fixed in https://github.com/desktop/desktop/pull/16632

Thanks for your report anyway!

**Closed as completed by sergiou87** 2023-06-06 07:51 UTC
