### ISSUE TITLE
Window hiding after using a second screen

### ISSUE THREAD

**Issue by Raul6469** [desktop/desktop#2107] opened 2017-06-24 10:00 UTC
### Description

I use a second screen with my laptop, in which I display the GitHub desktop window. The problem is when I disconnect the second screen, the window seems to be again on that second screen, as we can guess with the Windows animations.

Here is the animation : 

![ezgif-1-4bfa617f98](https://user-images.githubusercontent.com/24607388/27507662-df629b12-58d3-11e7-8809-2cf4c57e8601.gif)

### Version

**GitHub Desktop version:** 0.6.2, but the problem was also here in the previous version, 0.6.1

**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Connect a second screen to your laptop
3. Move GitHub desktop window to that second screen
4. Disconnect the second screen

**Expected behaviour:** The window should be displayed in your laptop screen

**Actual behaviour:** The window seems to be in that inexistant second screen

**Reproduces how often:** Always

Hope this might be useful, this is my first contribution !

**Comment by Raul6469** [comment] 2017-07-30 06:20
Any thoughts on this ? I'll just add that the issue is independent of screens orientation (not only vertically as I initally wrote).

**Comment by shiftkey** [comment] 2017-07-31 12:25
@Raul6469 I can't reproduce this at the moment because I'm travelling (and they look at you funny when you try and take an external monitor on a plane), but maybe @iAmWillShepherd is able to reproduce it on his Windows machine.

My gut feeling is that we should be able to get [events](https://github.com/electron/electron/blob/master/docs/api/screen.md) when the screens are added/removed, and maybe we can move the app to a better location.

**Comment by Raul6469** [comment] 2017-07-31 12:30
Thanks for the answer @shiftkey ! I was just about to close this issue because I found a solution to my problem [here](https://superuser.com/a/53590) with some keyboard tricks. It seems that it can occur for other windows programs as well, so I don't really think that the problem is with desktop...

**Comment by iAmWillShepherd** [comment] 2017-08-02 15:23
@shiftkey, unfortunately, I can't reproduce because I'm working on my laptop. Haven't actually unpacked everything since moving -_-.

**Comment by lownignitus** [comment] 2017-08-17 07:57
I just had to deal with this same issue myself. I had GitHub installed on my mass storage HDD. I had to reinstall windows because it was simpler when I got an M.2 drive to use as my main boot drive. Launching from the install save on the HDD brought it up in such a way that it did not display on any screen. I tried the tried and true Shift+Right click to bring up system menu for icon to select move. To my surprise and horror this did bumpkiss... 

Thankfully I found this ticket and @Raul6469 's solution to his same problem. This allowed me to bring it back.

**Comment by shiftkey** [comment] 2017-09-26 04:01
A similar report to this around restoring the app: #2853 

> On a Windows multimonitor setup with the primary monitor being a High-DPI monitor (3000x2000 pixels - DPI-Font-Size set to 200%) and the secondary monitor being an ordinary 27" monitor (DPI-Font-Size set to 100%), when re-starting GitHub Desktop it tries to recreate its screen position somewhere out of the overall screen estate spanned by the two monitors.

**Comment by leonrenkema** [comment] 2017-09-30 18:16
I am experiencing the same issue, even when restarting and reinstalling the program it is still opening on the second screen. I have seen this also with other Electron applications. My solution was Ctrl-Shift-right-click on the application icon in the taskbar and then click maximize. This will force the screen to open on the main screen and then the problem is solved.

But for Github Desktop this seems disabled, maybe a solution is enabling this function so the there is a way to maximize the window?

**Comment by ostensene** [comment] 2017-10-18 13:17
Hi

I am experiencing the same issue. I would like to add that using the keyboard shortcuts WIN+Left, WIN+Right, WIN+Up or Win+Down was not working when the program was on the disconnected monitor.

I also was able to get the program to the correct screen with the help of the task manager and then dragging the title bar when the window was maximized

**Comment by joshlangner** [comment] 2017-11-09 23:00
I've also been able to reproduce the issue on my Windows 10 environment. The only solution was to delete the file `%APPDATA%\GitHub Desktop\window-state.json`, per the discussion over here: https://github.com/desktop/desktop/issues/2893

**Comment by shiftkey** [comment] 2017-11-23 22:30
A bunch of extra details was provided in https://github.com/desktop/desktop/issues/3409

**Comment by rcmaehl** [comment] 2017-11-24 04:24
I'm also experiencing this issue with multiple monitors (3). Work around I'm using is to run it Maximized.

**Comment by ismail4040** [comment] 2017-12-02 11:51
@leonrenkema thx my friend. You solved my problem

**Comment by balcsida** [comment] 2018-01-05 13:16
Just an FYI: since Fall Creators Update, there are no options in Task Manager for window management, therefore workaround mentioned by @ostensene does not work.
You have to delete the %APPDATA%\GitHub Desktop\window-state.json, as @joshlangner mentioned.

![image](https://user-images.githubusercontent.com/1768446/34610756-cee52d3e-f222-11e7-8509-08294010ddb9.png)

**Comment by rcmaehl** [comment] 2018-01-05 14:13
@balcsida Say it isn't so! D:

**Comment by jarcane** [comment] 2018-01-23 10:01
Can confirm that the window-state.json delete fix works.

What's possibly interesting is it was triggered for me by a client update. It was working fine, then I clicked the "restart now" to run an update, and then the window wouldn't come back.

And a peek at the JSON data does confirm it'd placed the X/Y at some absurd coordinates:

```json
{
    "width": 3840,
    "height": 2080,
    "x": 30847,
    "y": 32767,
    "isMaximized": false,
    "isFullScreen": false,
    "displayBounds": {
        "x": 1920,
        "y": 0,
        "width": 2560,
        "height": 1440
    }
}
```

**Comment by lifewcody** [comment] 2018-01-23 15:36
I had the same issue, nothing works (the Win+Up/Down/Left/Right). Shift right clicking doesn't work either.

My coordinates were x: -1000, y: 0 (which is way off).

Deleting the .json file worked for me.

**Comment by yuhang-lin** [comment] 2018-01-25 19:07
Recently I experienced the same problem in Windows 10. Is there any way for the program to detect whether the second monitor is plugged in or not?

**Comment by JamesFaix** [comment] 2018-02-04 16:00
I've been having this issue occasionally since the overhaul of GitHub Desktop. Using Windows 10. Deleting the windowstate file is the only thing that has worked.  I've tried the normal Window management tricks like `Alt + Tab` , `Win + Left`, changing resolution; none of those did anything..

**Comment by joshlangner** [comment] 2018-02-20 22:07
Can we unmark this as "needs-reproduction"? It's clearly reproduceable.

**Comment by iAmWillShepherd** [comment] 2018-02-23 08:08
@joshlangner `needs-reproduction` is a label we use internally. Being reproducible for us means that _we_ are able to reproduce the issue (we are working to improve our label names 😅). I think everyone on our team is on a single monitor or laptop, which is why we've gone so long without reproducing.

**Comment by mswezey23** [comment] 2018-02-23 20:18
I experience the same issues as above - had to resort to deleting the .json file under APP_DATA to fix. 

Latest Windows 10 build and update

**Comment by ja1977ja** [comment] 2018-02-23 22:01
20 lut 2018 23:07 "joshlangner" <notifications@github.com> napisał(a):

**Comment by mmmaxwwwell** [comment] 2018-02-25 22:48
Hello,

I experienced this problem today. 

Workaround was editing %APPDATA%\GitHub Desktop\window-state.json while the app was closed. That file seems to be written to every time the app closes. 

I'm running 3 monitors with a nvidia card. Monitors are left to right at the same level. Y value was set to a negative integer in the window-state.json file.

I'll note that my nvidia card never really played well with any drivers I try and throw at it. Sometimes, infrequently, settings get reset, display order is changed, main display is changed, etc. In ubuntu, I've got some options in nvidia-settings that aren't available in windows, namely the viewport paramater. While I don't see this option to adjust the viewport in windows, nvidia probably uses something like it internally. I think the absolute location of the viewport (its equiv in windows) may be initialized somewhat randomly on my setup due to the driver issues. ie the left screen is always adjacent, to the left of and equal height as the middle screen, but on each boot the left screen's origin could be rendered at (0,0), (0,-1080) or (0,+1080).

Its just a hunch from behavior I've observed, but I hope it helps.

**Comment by iAmWillShepherd** [comment] 2018-02-27 01:27
This is a known issue, please read steps to fix in our [known-issues doc](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#window-is-hidden-after-detaching-secondary-monitor---2107)

**Comment by shiftkey** [comment] 2018-02-27 03:07
As I talked about in https://github.com/desktop/desktop/pull/3943#issuecomment-365212714 I'm not a fan of this workaround, and I'd like to handle this better in the app. Desktop is just blindly restoring the co-ordinates of the window without considering that the screen configuration might have changed to drop an existing screen.

We have access to the [screen](https://electronjs.org/docs/api/screen) API in Electron to detect the configuration of the users, and we should be able to workaround this without manual intervention by the user:

 - detect if the stored co-ordinates can be associated with a connected screen
 - if so, it should restore as-is (the current behaviour)
 - if not, restore the app to the center of [the primary display](https://electronjs.org/docs/api/screen#screengetprimarydisplay)
 - ensure `electron-window-state` is refreshed with the new position

I have ideas on implementing this (it'll be on the critical path of launching, so I don't want this to be too complex) and I have access to an external monitor currently to test this without needing VMs.

**Comment by mswezey23** [comment] 2018-02-27 16:55
I agree with @shiftkey. A workaround, especially as one that requires a deletion of a file, should not be acceptable to close this issue out. 

To put it bluntly, that's just lazy to not update the program to detect the user's setup and current configuration of monitors.

**Comment by shiftkey** [comment] 2018-02-28 00:27
Pulling this into 1.1.x to see if we can do better at restoring the window _somewhere_.

**Comment by magicmaster85** [comment] 2018-03-28 01:55
Same Issue on Windows 10.0.16299 with Github Desktop 1.1.1. A suggestion, maybe try using "connected" displays as "DisplayLink" drivers are considered connected, but not "active." Possibly create If/else with "active displays". "Primary display" does not work either as these users (including me) sometimes mark main display as one that is now disconnected.

**Comment by awinner1** [comment] 2018-05-15 16:37
One option rather than delete the %APPDATA%\GitHub Desktop\window-state.json file is to close the program and then edit edit it and change the x and y to 0. i.e.
from: {"width":960,"height":660,"x":4399,"y":150,... 
to       {"width":960,"height":660,"x":0,"y":0,...**

**Comment by tejasVR** [comment] 2018-05-19 16:06
Hey there everyone! I literally had this problem today, and found a super short fix: On the monitor, you are working on, bring any window into the half-pane view. Now, when a series of windows shows up, select GitHub Desktop, and then drag the git hub window into the front view. Attached a small gif to help visualize the process:

![github off screen fix](https://user-images.githubusercontent.com/17838397/40270515-dffa4a34-5b5c-11e8-87bc-0733fa2335fa.gif)

Hope this helps everyone out!

**Comment by rcmaehl** [comment] 2018-05-21 13:13
@tejasVR Windows 10 only (for sure) AND only certain builds (if I remember correctly). Looks like anyone not on Windows 10 will need to upgrade 😉

**Comment by JonneKonink** [comment] 2018-05-24 18:34
Hi, 

I don't seem to have the problem when opening GitHub Desktop from a desktop shortcut, which I set to open to maximized window.

Hope this helps.

**Comment by magicmaster85** [comment] 2018-05-24 18:55
@JonneKonink a previous user stated that was a workaround (hence you don't see the issue we're having).

**Comment by JonneKonink** [comment] 2018-05-24 22:36
@magicmaster85 Sorry, I forgot to mention that I did have the same issue, so this is indeed a workaround. Opening from the Win start menu doesn't work, but from the desktop does.

**Comment by qisope** [comment] 2018-06-06 19:05
You can retrieve lost windows by doing the following:

- Activate the app by clicking the Taskbar icon
- Hit Alt+Space which will show the Window menu
- Hit M, or click the Move menu item
- Tap one of your cursor keys which will lock the window to your mouse cursor
- You can them move you mouse cursor and the window will come along with it
- Drop it where you please, with a click of the mouse

I need this for a variety of apps recently where their windows like to vanish outside of the bounds of my displays - Slack desktop app, Chrome dev tools windows...

**Comment by jarcane** [comment] 2018-06-06 20:09
Can confirm that @tejasVR's workaround does work on the current Win10 build; but it didn't work for me when I posted earlier, so it's possible something changed.

As an added tip, you can do the tiling trick faster by just hitting Win+left or right arrow.

**Comment by jdclarke5** [comment] 2018-06-17 08:39
In Windows 7 Pro the following worked for me:

- Click taskbar icon (i.e. window is open and selected off-screen)
- Alt+Space
- Maximise

**Comment by hawley83** [comment] 2018-06-17 12:03
Hey how's it going well I pray.watery eyes on someyoulol left eye gouge
power caps high static towers by planetary fitness

**Comment by ZaxLofful** [comment] 2018-08-08 19:29
Has any progress been made on why you can't shift-right click?

This is a feature that all windows are supposed to implement properly, GitHub desktop is the only app I use that has this issue.

For something this simple I shouldn't have to go crawling over the internet to does something so common and widespread knowledge in IT.

I had this same issue and it drove me nuts for a little while.

**Comment by bpluly** [comment] 2018-08-09 11:47
I reproduced this after making my second screen the primary screen and rebooting. On opening Github Desktop I get the transparent, unfocusable window problem. The window-state.json had a reasonable set of geometry and window coordinates, it had been on the same screen when last closed.

Deleting the json file fixed it for the next and subsequent opens.
From that it sounds like its any change to the order or type of screens attached and that deleting the file has the side effect of getting all display properties again.

**Comment by jmurdick** [comment] 2018-09-14 18:31
Any chance this issue could get fixed?  Been open for more than a year, almost two years.  Extremely annoying.

**Comment by leonrenkema** [comment] 2018-09-15 08:46
Slack (also electron?) has recently introduced a button "move to current display", maybe borrow that solution?
![image](https://user-images.githubusercontent.com/497194/45584482-6ca30280-b8d4-11e8-9384-268716eedb86.png)

**Comment by reza-faghihi** [comment] 2018-10-04 06:58
> You can retrieve lost windows by doing the following:
> 
> * Activate the app by clicking the Taskbar icon
> * Hit Alt+Space which will show the Window menu
> * Hit M, or click the Move menu item
> * Tap one of your cursor keys which will lock the window to your mouse cursor
> * You can them move you mouse cursor and the window will come along with it
> * Drop it where you please, with a click of the mouse
> 
> I need this for a variety of apps recently where their windows like to vanish outside of the bounds of my displays - Slack desktop app, Chrome dev tools windows...

Thanks, dude it really worked for me

**Comment by rschuetzler** [comment] 2018-10-15 14:51
My guess is that this is an issue with https://github.com/mawie81/electron-window-state.

**Comment by eliasvanderlinden** [comment] 2018-10-16 10:11
use this fix: it's by far the fastest for windows 10.

https://github.com/desktop/desktop/issues/2107#issuecomment-390414700

**Comment by EPDISI** [comment] 2018-11-05 13:43
> I've also been able to reproduce the issue on my Windows 10 environment. The only solution was to delete the file `%APPDATA%\GitHub Desktop\window-state.json`, per the discussion over here: #2893

above was the only fix that worked for me! Thank you!

**Comment by gurkanakcakaya** [comment] 2018-12-26 07:40
It's an old issue but maybe it can be useful to somebody, if you check the logs it's some authentication fail (at least in my case)
to open it you can go to AppData/Roaming/github Desktop/
Rename the Cache folder to Old_Cache or just remove it this will bring you back the dekstop
This won't solve the authenticaton, to solve this change your ssh link to the https link

**Comment by Croydon** [comment] 2019-01-22 20:52
I'm using GitHub Desktop with two displays for a long time now, but I run today for the first time into this issue. https://github.com/desktop/desktop/issues/2107#issuecomment-343320044 fixed it for me

**Comment by irfanrulz** [comment] 2019-02-06 07:40
Here is the Fix 
https://github.com/desktop/desktop/issues/3342#issue-274469274

**Comment by aldobsom** [comment] 2019-03-22 22:55
there is a workaround by switching to tablet mode
![image](https://user-images.githubusercontent.com/30396343/54857105-f2798d80-4cfd-11e9-87fe-11b1ba606d5e.png)

**Comment by vaibhavhrt** [comment] 2019-04-23 05:39
Had this issue on my laptop(no secondary screen) with a detachable screen. Deleting `%APPDATA%\Roaming\GitHubDesktop\window-state.json` fixed it.

**Comment by mswezey23** [comment] 2019-04-24 05:28
Almost 2 years and still hasn't been properly fixed 😏

**Closed** 2019-05-21 13:45 UTC
Labels: bug, electron, priority-3, windows

**Comment by goodlux** [comment] 2019-11-19 17:02
I'm having this problem on OS X Catalina. Slack is open, can't find it anywhere! Can't restart it!

**Comment by tierninho** [comment] 2019-11-19 17:15
@goodlux Please fill a new issue and provide more details.

**Comment by mswezey23** [comment] 2019-11-19 19:55
> I'm having this problem on OS X Catalina. Slack is open, can't find it anywhere! Can't restart it!

The topic in this thread is for GitHub Desktop, not Slack. :)

**Comment by MaslinoJ** [comment] 2020-01-24 18:18
I had the same issue ..  jumped up and down with no good results . . until i tried some thing on task manager,

1. right click on the application/screen not showing,
2. choose maximize.

**Comment by Jonas-Carvalho** [comment] 2020-01-27 14:52
> > You can retrieve lost windows by doing the following:
> > 
> > * Activate the app by clicking the Taskbar icon
> > * Hit Alt+Space which will show the Window menu
> > * Hit M, or click the Move menu item
> > * Tap one of your cursor keys which will lock the window to your mouse cursor
> > * You can them move you mouse cursor and the window will come along with it
> > * Drop it where you please, with a click of the mouse
> > 
> > I need this for a variety of apps recently where their windows like to vanish outside of the bounds of my displays - Slack desktop app, Chrome dev tools windows...
> 
> Thanks, dude it really worked for me

Worked smoothly! Thx!
