### ISSUE TITLE
Branch name should not truncate

### ISSUE THREAD

**Issue by jakunico** [desktop/desktop#9024] opened 2020-02-01 00:30 UTC
### Describe the feature or problem you’d like to solve

Branch name truncates when there is plenty of space available.

### Proposed solution

Allow current branch button to use a little bit more screen width.
This way you will know what branch you are working on without having to click the button.

### Additional context

![image](https://user-images.githubusercontent.com/1474405/73583377-8a90e900-4470-11ea-8454-9b1edc0712cf.png)

**Comment by tierninho** [comment] 2020-02-01 00:51
@jakunico Thanks for filing this. This is a dupe of https://github.com/desktop/desktop/issues/4569 which provides some additional context. Please follow along there.

**Closed by tierninho** 2020-02-01 00:51 UTC
