### ISSUE TITLE
Projects group or folders

### ISSUE THREAD

**Issue by mateusvicente100** [desktop/desktop#10016] opened 2020-06-16 12:13 UTC
Today we can only view all projects in a simple list. Would be good we organize this in folders or groups, because when you get a lot of projects this list get harder to manage.

![git-project-list](https://user-images.githubusercontent.com/50463556/84772563-7da10c00-afb1-11ea-821d-4171b5361d34.png)

**Comment by tierninho** [comment] 2020-06-16 18:25
@mateusvicente100 Thank you for the suggestion. This is a duplicate of #1533 which resulted in #6460. We had to examine the overall organizational problem as holistically as possible and understand a wide range of possibilities, so not every feature could be implemented. We will reopen 1533 if we move forward with grouping.

**Closed by tierninho** 2020-06-16 18:25 UTC
