### ISSUE TITLE
Mac: Keyboard shortcut now the same for "Repository->Pull" and "Branch->Create Pull Request"

### ISSUE THREAD

**Issue by GandalfSaxe** [desktop/desktop#2298] opened 2017-07-21 19:35 UTC
### Description

Default now as that Cmd+Shift+P is now defined twice in the menu, namely for both: 
* Repository->Pull
* Branch->Create Pull Request

I did not see this before 0.7.0

### Version

**GitHub Desktop version: 0.7.0

**OS version: macOS 10.13 beta 4 (17A306f)

### Steps to Reproduce

1. Press Cmd+Shift+P

**Comment by j-f1** [comment] 2017-07-21 19:36
This is a duplicate of #2274, and is fixed in #2278.

**Closed** 2017-07-21 19:36 UTC
