### ISSUE TITLE
History's changed file items should have "Show in Finder" and "Open with External Editor" contextual menus commands also.

### ISSUE THREAD

**Issue by geowar1** [desktop/desktop#2307] opened 2017-07-23 17:17 UTC
Description

The changed file items in the "X Uncommitted Changes" tab have a contextual (popup) menu with "Show in Finder" and "Open with External Editor" commands. It would be nice if the changed file items in the History tab had the same contextual menu.

Version

GitHub Desktop version: Deer Types (222)
OS version: 10.12.6

**Comment by shiftkey** [comment] 2017-07-24 13:45
@geowar1 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Closed by shiftkey** 2017-07-24 13:45 UTC
Labels: enhancement, future-proposal

**Comment by billygriffin** [comment] 2018-11-17 00:16
I think this exists now, so I'm going to remove `future-proposal`.

<img width="398" alt="screen shot 2018-11-16 at 5 16 00 pm" src="https://user-images.githubusercontent.com/5091167/48653551-593f1100-e9c3-11e8-9a48-66f6779bcc75.png">

**Comment by shiftkey** [comment] 2018-11-17 11:53
@billygriffin I believe this was a duplicate of #2845 which we added support for in #4037 :tada:
