### ISSUE TITLE
Black squares in the app window

### ISSUE THREAD

**Issue by konopkoman** [desktop/desktop#7102] opened 2019-03-15 20:19 UTC
There are black squares in the window when scrolling

![Annotation 2019-03-15 231728](https://user-images.githubusercontent.com/11742887/54459731-a0be8980-4778-11e9-9398-9377b86876be.jpg)

**Comment by tierninho** [comment] 2019-03-15 20:46
@konopkoman Thanks for filing. 

Any other details you can share, like OS, version of Desktop, or the steps that led up to this?

**Comment by konopkoman** [comment] 2019-03-16 20:43
Win10, just scroll the app window

**Comment by tierninho** [comment] 2019-03-18 17:46
I cannot reproduce this. It would be great if you could send over more details @konopkoman 

Until then, closing this issue. Happy to reopen if needed or if other report the same. Thanks.

**Closed by tierninho** 2019-03-18 17:46 UTC
Labels: more-information-needed
