### ISSUE TITLE
Can't sign in to GitHub Enterprise

### ISSUE THREAD

**Issue by pksublime** [desktop/desktop#2076] opened 2017-06-21 14:02 UTC
### Description

Can't sign in to Enterprise using username and password - see #2064 
Then trying "Sign in using your browser" and it doesn't work either

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Try signing in to Enterprise
2. Enter my enterprise server address
2. Try username and password - receive 403 (see #2064 
3. Try "Sign in using browser"
4. Get error ```request to https://<server>/api/v3/user failed, reason unable to verify the first certificate```

**Expected behaviour:** Authentication to work

**Actual behaviour:** Can't authenticate

**Reproduces how often:** 100%

### Logs

Can't locate the log file for new GitHubDesktop Beta

#### Additional Information

Our Enterprise server is behind a firewall and is self-signed.
I can provide the output of certutil against the servers certifcate, but don't want to post publically.

**Comment by tierninho** [comment] 2017-06-21 14:04
closing as dupe of https://github.com/desktop/desktop/issues/2064

**Comment by shiftkey** [comment] 2017-06-21 14:22
> Our Enterprise server is behind a firewall and is self-signed.

Handling self-signed certificates was a part of #671 and we've just updated Electron to a version that handles this on Windows. This will be available as part of the next update, and given you're using the web flow I think you should be good to go. I'm not sure if #2064 is the same issue you'll face.

**Comment by shiftkey** [comment] 2017-06-24 16:34
@pksublime does the GitHub Enterprise server you're connecting to have a self-signed certificate? Can you tell me more about that setup so we can confirm this is fixed by #671?

**Comment by GortMcTabs** [comment] 2017-06-30 15:42
We're receiving the same error message mentioned above, but I _believe_ we're using a wildcard cert, not self signed. Although the cert verification failed on initial prompt to log in, we got things working by skipping the initial prompt and adding our account through File > Accounts> Enterprise.

(Cc @nathanblack)

**Comment by ddiguy** [comment] 2017-07-12 19:19
I'm having problems with this as well.  We have a self signed certificate.  I can download it, but not sure  why I can't get it to work.  As a work around, I am using the older version of GitHub desktop for now.

**Comment by GortMcTabs** [comment] 2017-08-08 17:38
FYI - I tried this on a new install and I was able to login successfully with the initial prompts.

v 0.7.2

**Comment by joshaber** [comment] 2017-08-31 21:17
It sounds like this was fixed 💥

**Closed by joshaber** 2017-08-31 21:17 UTC
Labels: bug
