### ISSUE TITLE
Commit message popup list hidden under code pane (z-order issue)

### ISSUE THREAD

**Issue by joyfullservice** [desktop/desktop#16692] opened 2023-05-13 16:05 UTC
### The problem

When typing a description for a commit, you may press `#` to reference a related issue, or `:` to add an emoji to the description. The list that pops up is underneath the code view pane, so you may not be able to fully see the titles.

### Release version

Version 3.2.3 (x64)

### Operating system

Windows 10 Pro

### Screenshots

![image](https://github.com/desktop/desktop/assets/7254992/b92926e6-0442-49a7-8239-28930c5354cf)

**Comment by tidy-dev** [comment] 2023-05-15 14:03
Thanks for the issue @joyfullservice. This is a duplicate of https://github.com/desktop/desktop/issues/16650 and [a solution ](https://github.com/desktop/desktop/pull/16651)has already been merged.

**Closed as completed by tidy-dev** 2023-05-15 14:03 UTC

**Comment by Broken60** [comment] 2023-05-18 18:27
Ok

**Comment by Broken60** [comment] 2023-07-22 08:44
Hahahahahajaha
