### ISSUE TITLE
Using Up and Down Arrows To Browse Changes Tab Has Inconsistent Behavior

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#7058] opened 2019-03-11 05:50 UTC
## Description
When using the arrow up and down keys to move between changed files, the behavior isn't consistent once scrolling commences.  This a bit difficult to describe and is easier to see.

https://www.dropbox.com/s/9ro2nczj6n1d30u/GitHub%20Arrow%20Up%20and%20Down%20Bug.mov?dl=0

Essentially, if you highlight a changed file in a list that is long enough that a scroll bar is engaged, then you start to move down, by tapping the down arrow key, the highlighted region will begin to traverse the list of changes, opening up each file's diff view, until scrolling is required, at which point, the changes view only scrolls and doesn't traverse the list anymore and the diff views stop opening as a consequence.

## Version
* GitHub Desktop: 1.6.3
* Operating system: macOS 10.14.3

## Steps to Reproduce
1.  Create a repo with many files.
2.  Make a change in every file
3.  View the changes list and select a change
4.  Use the arrow down key to traverse down the list until scrolling engages
-->

### Expected Behavior
I would expect that the highlighted region highlighting each file would continue to move down the list and each file's diff would open.

### Actual Behavior
Scrolling is engaged and the highlighted region stops moving, resulting in being stuck in one file's diff view.

**Comment by thinkyhead** [comment] 2019-03-11 20:59
I can confirm that this is has been a vexing issue for about the last month or so. No workarounds discovered.

**Comment by billygriffin** [comment] 2019-03-11 21:05
Thanks for the detailed report @JosephTLyons! This is a duplicate of https://github.com/desktop/desktop/issues/6845, so please feel free to weigh in or follow along there. It looks like we know which PR caused it, so hopefully that should make it easier to track down the fix. Thanks again!

**Closed by billygriffin** 2019-03-11 21:05 UTC
