### ISSUE TITLE
Error while uploading files locally on Github Desktop for Mac

### ISSUE THREAD

**Issue by SamkitS** [desktop/desktop#2258] opened 2017-07-17 14:07 UTC
### Description

I downloaded Github for Desktop for Mac and clicked on File>>Add Local Repository>>Selected the file Path.

Then it showed me a error message. I have included the screenshot

The error message said 

The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes.

### Version

I am using the latest version of Github Version 0.6.2 for Mac

**GitHub Desktop version:** [0.6.2]

**OS version:** [Mac OS Sierra 10.12.5 (16F73)]

### Steps to Reproduce

1. Download Github Desktop for Mac
2. Click on file add local Repository.
3. Add file path.
4. Observe error messages.

<img width="973" alt="screen shot 2017-07-17 at 9 23 58 pm" src="https://user-images.githubusercontent.com/30083797/28277083-66022dbc-6b36-11e7-907e-7008fac4924a.PNG">

**Expected behavior:** [Such errors should not be shown.]

**Actual behavior:** [I should be able to easily add files and upload and sync]

**Reproduces how often:** [Now when I open the App, it shows me thrice and no work is done]

**Comment by joshaber** [comment] 2017-07-17 15:02
Thanks for opening this up @SamkitS!

The error in the attached screenshot is about trying to open the `.DS_Store` file, which is different from the error you wrote about in the issue body. Which one are you trying to solve?

**Comment by SamkitS** [comment] 2017-07-17 15:55
@joshaber Thank you for noting it

**Comment by Tivo389** [comment] 2017-07-25 13:20
Hello @joshaber

I seem to be having the exact same issue as @SamkitS
Other than the Github version the OS I use is the exact same.

Although I've used Git before, I'm completely new to Github.
I've provided the details below based on @SamkitS format.
However please feel free to let me know if there are other details I can provide that might help you.

Regards,
Shun

========================
DESCRIPTION:
- Downloaded Github for Desktop (Mac).
- Dragged a new folder into the app.
- Error message pops up.

ERROR MESSAGE:
- The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

GITHUB DESKTOP VERSION:
- 0.7.0

OS VERSION
- Mac OS Sierra 10.12.5 (16F73)

STEPS TO REPRODUCE
- Install Github for Desktop.
- Make new folder.
- Drag folder into app.
- Error message pops up.

EXPECTED BEHAVIOR:
- A repository would be made.

ACTUAL BEHAVIOR:
- An error message pops up.

REPRODUCES HOW OFTEN:
- Always.
- Tried reinstalling the app, same results.
- Tested with different folders in different locations, same results.

OTHER INFO:
- Not certain if it's related, but when I attempted to make a new Repository with a new folder it states that, "This directory appears to be a Git repository. Would you like to add this repository instead?". However "Create Repository" cannot be clicked. (Screenshot attached)
![screen shot 2017-07-26 at 01 11 26](https://user-images.githubusercontent.com/17847898/28573900-557af6c0-71a0-11e7-8864-45d7ee28953a.png)



- Over a year ago I tried using Git with command lines but eventually transferred over to using a Git GUI called "SourceTree".
========================

**Comment by shiftkey** [comment] 2017-07-27 14:12
@SamkitS thanks for the details. Anything interesting in the [log files](https://github.com/desktop/desktop/blob/master/docs/installation.md#log-files) that might show the command that was running at the time?

> The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes

If you're able to reproduce this (I think the `.git` folder has been created, and if you don't care about the history you can safely delete that) you should be able to open the Developer Tools (under the **View** menu) and see in the console the Git commands that were executing at the time.

> Not certain if it's related, but when I attempted to make a new Repository with a new folder it states that, "This directory appears to be a Git repository. Would you like to add this repository instead?". However "Create Repository" cannot be clicked. (Screenshot attached)

Because it detects that it's already a Git repository, we can move you over to a simpler dialog - that's the "add this repository" link in the middle.

**Comment by joshaber** [comment] 2017-08-08 18:13
Thank you for your issue!

We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by joshaber** 2017-08-08 18:13 UTC
Labels: more-information-needed, needs-reproduction

**Comment by SamkitS** [comment] 2017-08-17 14:07
@joshaber can you reopen this issue ?

**Comment by j-f1** [comment] 2017-08-17 14:11
@SamkitS

> We haven't gotten a response to our questions above. With only the information that is currently in the issue, we don't have enough information to take action.

If you answer their questions above, they’ll probably reopen it.

**Comment by SamkitS** [comment] 2017-08-17 14:16
@shiftkey I do see the .git folder, I am unsure how to locate 'Developer Tools (under the View menu) and see in the console the Git commands that were executing at the time'. 
You mean in Desktop application ? I am sorry i am really a newbie !

**Comment by romanddimov** [comment] 2017-11-08 18:47
This was happening to me, and I noticed that instead of using the directory I wanted, it was taking my whole user. I just deleted the git tracking on the user directory and it fixed everything

`rm -rf .git`

hope this helps

**Comment by SamkitS** [comment] 2017-12-13 10:05
@romanddimov thanks a-lot, this really helped me !

**Comment by ibrahimatmaca** [comment] 2020-03-04 09:59
> Bu başıma geliyordu ve istediğim dizini kullanmak yerine tüm kullanıcımı aldığını fark ettim. Kullanıcı dizinindeki git izlemeyi sildim ve her şeyi düzeltti
> 
> `rm -rf .git`
> 
> Bu yardımcı olur umarım

Thanks !!!
