### ISSUE TITLE
Double-click the title to get all selected, then copy the selected title, the result is not as expected

### ISSUE THREAD

**Issue by drakeet** [desktop/desktop#5956] opened 2018-10-20 02:42 UTC
Hi, this project is great, I absolutely love it, thank you so much. 
I found a small problem: when I double-click the title of a commit to get all selected, then I press `command` + `c` keys to copy the selected title, the result is not as expected.

Example:

Face a title: **Migrate to AndroidX and tag to v2.2.0**
I will get the result is not as expected:
```
Migrate to AndroidX and tag to v2.2.0

drakeet committed
```
What I expected is just: `Migrate to AndroidX and tag to v2.2.0`, do not plus the line break and `drakeet committed`.

Screenshots (GIF): 
![oct-20-2018 10-40-33](https://user-images.githubusercontent.com/5214214/47250497-a24b8600-d454-11e8-9662-eda42f094268.gif)

Thanks!

**Comment by j-f1** [comment] 2018-10-21 16:39
Duplicate of #4382.

**Comment by niik** [comment] 2018-10-22 14:38
Hey @drakeet, thank you so much for opening this and a special thanks for including a Gif, that's super helpful. I'm gonna close this out in favor of #4382 as per @j-f1's suggestion and we can continue the discussion there. I believe where we've landed at is that we'd welcome a community contribution to solve this issue.

**Closed by niik** 2018-10-22 14:38 UTC
