### ISSUE TITLE
CLI checkouts don't trigger branch comparison UI update

### ISSUE THREAD

**Issue by sbonami** [desktop/desktop#4955] opened 2018-06-18 15:15 UTC
## Description

If a branch is open with a comparison to another branch, upon doing a `git checkout` (from the CLI) to the compared branch, Github Desktop maintains the comparison to the parent branch. This results in a `Behind (0)` and `Ahead (0)` result.

## Version
* GitHub Desktop: `v1.2.3`
* Operating system: macOS High Sierra 10.13.5

## Steps to Reproduce

1. Navigate to an active branch
2. Perform a comparison to the parent branch (e.g. master)
3. From the command line, execute `git checkout <parent>`
4. Open the Desktop app and observe

### Expected Behavior

The branch comparison to clear, similar to when I've switched branches within the app.

### Actual Behavior

A branch comparison to self, thus a `Behind (0)` and `Ahead (0)` result.

## Additional Information

I'm not sure this is a common use case. I utilize both the app and CLI in my workflow as each provides features that are useful in different scenarios. There also exists the ability to clear the comparison, so the priority is low imho.

### Logs
 
N/A

**Comment by iAmWillShepherd** [comment] 2018-06-19 00:55
Thanks for taking the time to open an issue! 🙇 

Good catch!, We should be clearing out the compare selection when we notice `HEAD` has changed.

**Comment by j-f1** [comment] 2018-06-19 14:56
Should the state be cleared when a commit is made?

**Comment by iAmWillShepherd** [comment] 2018-06-19 15:56
> Should the state be cleared when a commit is made?

No, the intended behavior was to have the compare state be sticky so people won't have to constantly re-select the comparison branch. What we need to do is clear the state whenever we notice the comparison branch is equal to itself.

**Comment by billygriffin** [comment] 2019-11-21 14:31
Thanks so much for the issue @sbonami! Since we haven't seen this come up again and it does feel like an irregular combination of events, I'm going to close it until we see it resurface. Really appreciate you clearly explaining how it occurs!

**Closed by billygriffin** 2019-11-21 14:31 UTC
Labels: bug, help wanted, priority-3
