### ISSUE TITLE
Publish repository modal showing up when repo is already published

### ISSUE THREAD

**Issue by Mlocik97-issues** [desktop/desktop#5719] opened 2018-09-24 09:23 UTC
## Version

* GitHub Desktop:

* Operating system:

**Comment by steveward** [comment] 2018-09-28 00:13
@Mlocik97-issues were you able to resolve this issue? Often this error is thrown when you try to publish a branch that does not yet have any commits. Make sure you [commit your changes](https://help.github.com/desktop/guides/contributing-to-projects/committing-and-reviewing-changes-to-your-project/), and then try clicking `Publish` again.

**Comment by Mlocik97-issues** [comment] 2018-09-28 20:10
Now I haven't error, but something else,... Github Desktop is suggesting Publish already published repo... WTF https://www.youtube.com/watch?v=4TmorqtW3bU&feature=youtu.be&ab_channel=GabrielMlocik

**Comment by Mlocik97-issues** [comment] 2018-09-28 20:19
in 1.4.0 and 1.4.1 it also happen

**Comment by billygriffin** [comment] 2018-10-01 17:28
@desktop/support Would you mind taking a look at the video? It appears the repro steps are:

1. Create a repo locally, including .git
2. Add the local repo to Desktop
3. Make a commit
4. Publish to GitHub
5. Make another commit
6. Try pushing, and instead of pushing it pops the "Publish repository" modal instead of pushing.

**Comment by tierninho** [comment] 2018-10-09 17:30
@Mlocik97-issues As we haven't heard back from you, we will be closing this issue for now. We are happy to revisit the issue if you have more questions. Thank you.

**Comment by steveward** [comment] 2018-10-12 13:49
@Mlocik97-issues Thanks for the video! I'm working on trying to reproduce this. 

Would you also be able to upload a log file from a day where you reproduced this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The logs are split up by date.

**Comment by shiftkey** [comment] 2018-10-14 20:44
Oops, looks like we still need some more info about the issue.

**Comment by steveward** [comment] 2018-10-15 15:05
@Mlocik97-issues I've tested out a few scenarios but have not been able to reproduce this issue. If you could reproduce this behavior again and then upload a log file, that would be helpful!

**Comment by shiftkey** [comment] 2018-10-25 11:00
Not sure we ever figured out the version here, but this feels very similar to #5936 which has more details (and I've hopefully fixed in #5948).

**Comment by billygriffin** [comment] 2018-10-25 14:39
Since we think this hopefully will be fixed in #5948, I'm going to go ahead and close this out. Definitely let us know if you're seeing it again though, and sorry for the confusion.

**Closed by billygriffin** 2018-10-25 14:39 UTC
Labels: more-information-needed
