### ISSUE TITLE
GitHub Desktop Auto Updater Doesn't Escalate When Needed on Mac

### ISSUE THREAD

**Issue by burnumd** [desktop/desktop#2840] opened 2017-09-22 14:16 UTC
### Description

The GitHub Desktop application on Mac doesn't prompt for escalation when restarting to install an update if the current user is a non-administrator account, causing the update to fail silently.

### Version

**GitHub Desktop version:** 1.0.0

**OS version:** Mac OS 10.12.6 (16G29)

### Steps to Reproduce

1. Open a copy of the Mac GitHub Desktop application that is not up to date as a non-administrator user
1. Click on the prompt to restart the application to install updates
1. When the application reopens, the version number will not have updated and the application will still prompt for updates

**Expected behavior:** The desktop application will auto-update on restart

**Actual behavior:** The application restarts, but is not updated

**Reproduces how often:** Always, when the desktop client is out of date

### Logs

[2017-09-22.desktop.production.log.zip](https://github.com/desktop/desktop/files/1324785/2017-09-22.desktop.production.log.zip)

**Comment by joshaber** [comment] 2017-09-22 14:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/2323. Please follow that issue for further updates.

**Closed by joshaber** 2017-09-22 14:19 UTC
