### ISSUE TITLE
Conflict file path not showing while taking pull origin

### ISSUE THREAD

**Issue by kanji-keraliya** [desktop/desktop#10496] opened 2020-09-03 06:04 UTC
### Describe the bug

After updated latest version of GitHub desktop application its not showing which file changes present while pull origin. before this version showing list of file changes that conflict with origin

### Version & OS

V2.5.4 OS- MacOS Catalina

### Steps to reproduce the behavior

1. do some changes in file which already pushed file in git origin but not in local
2. Press on pull origin
3. Showing this dialog but not getting proper detailed information which files have conflict
<img width="441" alt="Screenshot at Sep 03 11-28-43" src="https://user-images.githubusercontent.com/30310660/92076892-fce7f400-edd8-11ea-9216-83aad6694863.png">
But before latest version its showing list of files which are conflict with local and origin

### Expected behavior

Showing list of files which are conflict with local and origin same as previously. So we get idea which file have conflict

### Actual behavior

Not showing conflict file list

### Screenshots

<img width="441" alt="Screenshot at Sep 03 11-28-43" src="https://user-images.githubusercontent.com/30310660/92077084-54865f80-edd9-11ea-8983-0b8b8f5bc19b.png">

**Comment by MonaPie07** [comment] 2020-09-03 06:26
You guys are hard to get rid off delete me plz

Sent from Yahoo Mail on Android 
 
  On Wed., 2 Sep. 2020 at 11:06 p.m., Kanji Keraliya<notifications@github.com> wrote:   


Describe the bug

After updated latest version of GitHub desktop application its not showing which file changes present while pull origin. before this version showing list of file changes that conflict with origin

Version & OS

V2.5.4 OS- MacOS Catalina

Steps to reproduce the behavior
   
   - do some changes in file which already pushed file in git origin but not in local
   - Press on pull origin
   - Showing this dialog but not getting proper detailed information which files have conflict


But before latest version its showing list of files which are conflict with local and origin
Expected behavior

Showing list of files which are conflict with local and origin same as previously. So we get idea which file have conflict

Actual behavior

Not showing conflict file list

Screenshots

**Comment by niik** [comment] 2020-09-03 07:47
Hi @kanji-keraliya, thanks for opening this and thanks especially for including screenshots, that always helps. This looks like the same issue as is described in https://github.com/desktop/desktop/issues/10496 so I'm going to close this issue in favor of that and ask that you subscribe to it to stay up to date with progress.

**Closed by niik** 2020-09-03 07:47 UTC
