### ISSUE TITLE
GitHub Desktop Commit Sign Off

### ISSUE THREAD

**Issue by omi-jbrivero** [desktop/desktop#19205] opened 2024-09-05 08:28 UTC
### The feature request

GitHub Desktop Commit Sign Off

### Proposed solution

GitHub Desktop Commit Sign Off just like Source-Tree

**Comment by sergiou87** [comment] 2024-09-05 09:33
Duplicate of https://github.com/desktop/desktop/issues/5351

Please, subscribe to that issue to keep track of any progress. Thanks for your report! 🙏

**Closed as completed by sergiou87** 2024-09-05 09:33 UTC
