### ISSUE TITLE
Close button doesn't work while fullscreen on OSX 11.5.2 

### ISSUE THREAD

**Issue by isak-combrinck** [desktop/desktop#12838] opened 2021-08-25 08:43 UTC
### Describe the bug
While running GitHub Desktop in fullscreen clicking on the red close button doesn't close the program. It only hides the menu bar again but GitHub Desktop stays open on screen as before.

If it's not running fullscreen the close button works as expected.

### Version & OS

I am currently running GitHub Desktop Version 2.9.2 (arm64) on OSX 11.5.2.
Note: I have been having this issue for about the last year. It was also present on my old MacBook, running the Intel based architecture. After switching to the Arm based MacBook and still seeing the same problem I decided to report the bug.

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Enter Fullscreen Mode
3. Click on the red close button

### Expected behavior

I expect the current GitHub Desktop window to close and keep running in the taskbar.

### Actual behavior

Nothing happens. The window stays open and in focus. You have to either exit fullscreen mode and then press the close button or quit the program using CMD + Q.

**Comment by steveward** [comment] 2021-08-26 12:59
Looks like the same behavior that was previously fixed in an Electron upgrade (https://github.com/desktop/desktop/issues/5287).

**Comment by haykam821** [comment] 2021-09-04 02:08
I can reproduce this on GitHub Desktop 2.9.3 and macOS Monterey 12.0 beta.

**Comment by agisilaos** [comment] 2021-12-13 19:43
I can reproduce this on `GitHub Desktop Version 2.9.5 (arm64)`, macOS Monterey version: `12.0.1 (21A559)`

**Closed as completed** 2022-01-19 10:28 UTC
Labels: bug, macOS, priority-3
