### ISSUE TITLE
Clicking outside the "Create a Branch" modal closes the modal, losing branch name input

### ISSUE THREAD

**Issue by docmars** [desktop/desktop#7526] opened 2019-05-13 17:14 UTC
**Please describe the problem you think should be solved**
When creating a new branch, clicking anywhere outside the modal that pops up, even with input for the new branch name, closes the modal, which makes the user lose their new branch + name they entered. This forces them to repeat the whole workflow.

What's the use case and why does this happen? Sometimes you need to switch to another window and return to the GitHub app later. At times, the easiest way is to click anywhere in the GitHub window. Most of it is the black modal overlay, which triggers closing the "Create a Branch" modal.

**[Optional] Do you have any potential solutions in mind?**
1. Don't close modals when clicking the black overlay.
2. Or, (less ideal) warn the user when they've already inputted values before having them lose their work.

**Comment by shiftkey** [comment] 2019-05-13 17:58
@docmars which OS are you using?

**Comment by docmars** [comment] 2019-05-13 20:55
@shiftkey macOS 10.14 Mojave

**Comment by tierninho** [comment] 2019-05-14 02:05
Thanks for reporting this, @docmars .

> Don't close modals when clicking the black overlay.

Currently we treat the closing of modals conditionally, depending on the action of the modal. I hear what you are saying and I experience this too. Although it can be a minor annoyance, I suspect most people create their branch on the spot and do not have this problem (at least for this modal).

However, I _do_ think we can be smarter at deciding which modals can be only closed by clicking `x`. I will let others weigh in, as I do not have strong feelings about making any changes... yet.

**Comment by niik** [comment] 2019-05-14 11:59
The core behavior here of being able to dismiss a non-destructive dialog by clicking on the overlay is an intentional design decision and one where I think the pros outweighs the cons.

> Sometimes you need to switch to another window and return to the GitHub app later. At times, the easiest way is to click anywhere in the GitHub window. Most of it is the black modal overlay, which triggers closing the "Create a Branch" modal.

This, however, is not intended behavior. Especially not on macOS where the default behavior is to ignore first click on a blurred application. We turned off this behavior generally in https://github.com/desktop/desktop/pull/3843 but the intention was never to make it such that the first click would dismiss a dialog. I've opened #7530 to address this.

**Closed** 2019-05-16 17:12 UTC
Labels: bug, priority-3
