### ISSUE TITLE
Error "Unknown error (0x80092013)" on push/pull to Enterprise instance

### ISSUE THREAD

**Issue by happywino** [desktop/desktop#3260] opened 2017-11-07 20:22 UTC
### Description

Unknown error (0x80092013)

### Version

**GitHub Desktop version:** Was 0.8, issue started after upgrading to 1.0.7

**OS version:** Windows Server 2012 R2 DataCenter Edition

### Steps to Reproduce

1. Attempt to push or pull to/from Enterprise repository

**Expected behavior:** Push/Pull completes without error

**Actual behavior:** Error from developer console: 

`git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
fatal: unable to access 'https://redacted address of github enterprise instance.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

**Reproduces how often:** 100% since upgrading to 1.0.7

#### Additional Information

I'm new to github and GitHub Desktop and the web interface is all I'm familiar with.  If I choose "Repositort\View on GitHub" the repository opens successfully in a browser window.

**Comment by j-f1** [comment] 2017-11-07 20:37
Thanks for reporting this!

Do https://github.com/dear-github/dear-github/issues/267 and https://github.com/desktop/desktop/issues/2187#issuecomment-313309981 help you?

**Comment by shiftkey** [comment] 2017-11-07 21:25
The version of Git embedded in Desktop uses the Windows SChannel APIs for validating certificates as part of the HTTPS handshake. We've had various reports of this failing due to other tools being installed alongside, like anti-virus programs. As @j-f1 suggested, see what else you have installed that might be interfering.

As a workaround, you can revert to the classic OpenSSL behaviour by opening the repository in a shell and running these two commands. 

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

If your GitHub Enterprise server has internal SSL certificates, you'll need to extract them into a PEM file and put them somewhere on your local machine. Otherwise, [the PEM file](https://curl.haxx.se/docs/caextract.html) distributed by the cURL team should do the trick.

**Comment by happywino** [comment] 2017-11-07 22:40
Disabling the AV on this system didn't help.

I'm no PKI expert but doesn't the fact that IE can connect on the same machine suggest that the issue isn't tied to the certs themselves?

**Comment by happywino** [comment] 2017-11-07 23:15
Pulled these from the logs in the hope it helps;

> 2017-11-07T23:10:11.675Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Manage-ScheduledTasks - REDACTED (has token)
> 2017-11-07T23:11:11.815Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 60.127s)
> 2017-11-07T23:11:11.817Z - error: [ui] `git -c credential.helper= push origin master:master --progress` exited with an unexpected code: 128.
> fatal: unable to access 'REDACTED.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.

Sometimes there is a long timeout (like above) but the majority of the time the error comes back pretty much instantaneously.

**Comment by shiftkey** [comment] 2017-11-07 23:44
> I'm no PKI expert but doesn't the fact that IE can connect on the same machine suggest that the issue isn't tied to the certs themselves?

It's not tied to the certs, but to how `curl` (the part of Git responsible for everything HTTPS-related) is using SChannel.  [This mailing list thread has some additional context](https://curl.haxx.se/mail/lib-2016-03/0202.html):

>>When curl is built with the WinSSL (schannel) SSL backend certificate revocation checking is enabled by default and the checking is handled automatically by the Windows OS, not by libcurl. 

I've had some reports of this but not enough details to recreate the issue on my end - whether it's related to something installed on the user's machine or something on the network isn't clear to me.

> `The revocation function was unable to check revocation because the revocation server was offline.`

The error message suggests something is blocking SChannel checking if the certificate has been revoked, which is part of the normal handshake process to let administrators blacklist certificates.

> Sometimes there is a long timeout (like above) but the majority of the time the error comes back pretty much instantaneously.

Coming back to the earlier mailing list comment:

>> Whatever proxy settings you are using in libcurl will not be used to retrieve the revocation 
resource, instead the OS will use its settings. Assuming those settings  are correct that error message usually means what it says, the revocation server is offline. 

This might seem a bit silly to ask, but how often is this occurring for you in the logs? Is every push/pull/fetch affected? Could you share the full logs so we can see if there's any chance the revocation server wasn't offline while you were using this?

**Comment by happywino** [comment] 2017-11-08 00:37
After a little digging I discovered [this article](https://blogs.msdn.microsoft.com/ieinternals/2011/04/07/understanding-certificate-revocation-checks/) that explains that IE suppresses any error if it fails to reach the CRL/OSCP URL, and proceeds as if nothing happened (rational being there's nothing the user can do anyway).  I applied the registry setting that re-surfaces the warning when this happens and lo and behold I get the notification in IE now (after a long pause which I assume to be the same 60 second timeout as was shown in the logs I posted above)

So, it would seem that the revocation server isn't reachable in either case, even though IE makes it look otherwise.  In my case this is most likely because I'm behind a proxy and/or because of very restrictive firewall policies.

For me this begs two questions;

1. The version I was using previously worked without issue, presumably because it wasn't checking for revocation?
2. Can a setting be exposed that suppresses the revocation check?

**Comment by shiftkey** [comment] 2017-11-08 00:51
> The version I was using previously worked without issue, presumably because it wasn't checking for revocation?

The previous version of GitHub Desktop does not use SChannel, but uses OpenSSL library. This worked for Enterprise because we did the heavy lifting to merge certificates from the Windows Certificate Store into the OpenSSL bundle that our version of Git would then use. That's no longer present, because we are now using SChannel which is backed by the Windows Certificate Store.

> Can a setting be exposed that suppresses the revocation check?

Not currently. I'd recommend the workaround above about switching the repository to use OpenSSL to see if that gets you back :

```
$ git config --global http.sslBackend "openssl"
$ git config --global http.sslCAInfo [path to .pem file]
```

**Comment by happywino** [comment] 2017-11-08 01:44
Switching to openssl resolves the issue, as does this .gitconfig addition

> [http "https://weak.example.com"]
> 	sslVerify = false

**Comment by shiftkey** [comment] 2017-11-08 01:46
@happywino without more information to reproduce this issue I'm going to have to close this out. 

Let me know if there's anything more you can provide about what might be responsible for interfering with the revocation checks in your environment.

**Closed** 2017-11-08 22:23 UTC
Labels: more-information-needed

**Comment by happywino** [comment] 2017-11-08 22:49
@shiftkey I think in my case at least, the system in question cannot reach the revocation server due to intentional network restrictions.

That being said, I don't think that should prevent the internal use of the tool, it seems an option to allow the revocation check to be skipped for individual sites should be allowed for cases like this.  I'm new to the open source world, should I write this up as a request rather than an issue?

**Comment by CharlesStover** [comment] 2018-10-03 23:43
Disabling sslVerify resolved this issue for me.

**Comment by AndyGee** [comment] 2018-11-16 08:16
Check your "C:\Users\<user>.gitconfig" for proxy configuration, or anything else that might be providing wrong credentials - Had the same issue, and it turned out to be the corporate proxy settings.
