### ISSUE TITLE
Find in current file

### ISSUE THREAD

**Issue by aMoniker** [desktop/desktop#4697] opened 2018-05-15 15:26 UTC
This isn't a problem, but it would be a very nice feature to have. I'd like to be able to `CMD/CTRL + F` and find text within the currently selected file.

This would be really nice, for example, when I'm doing line-by-line selections while assembling a commit, and want to search through the file to make sure I've selected them all.

**Describe the solution you'd like**
An `Edit > Find` menu similar to other apps like Chrome.
Shortcut of `CTRL/CMD + F`.
A text input similar to chrome pops up, and allows me to type in search terms.
I can hit `Enter` continually to advance to the next found result, which is highlighted in the file view.
When the search reaches the last result, advancing to the next wraps it around to the first result.
Explicit text matching is fine, but you could add regex, case-sensitive, etc. if you want to get fancy.

**Describe alternatives you've considered**
I can open the file in my editor and use the find feature there, but this does not help when determining which lines are to be included in the commit within the GH Desktop app.

**Comment by iAmWillShepherd** [comment] 2018-05-15 16:12
Thanks for taking the time to open an issue! 🙇 

I've gone ahead and added the enhancement label so when we have our next planning session, we can discuss this.

**Comment by aMoniker** [comment] 2018-05-15 16:19
Thanks for your fast response @iAmWillShepherd! I hope you think the feature is useful.

The desktop app is excellent for doing line-by-line commits, and this would make that even better.

**Comment by iAmWillShepherd** [comment] 2018-05-15 16:28
I do think this is useful! It's a problem I deal with fairly often and is the source of many botched commits for me. I'm sure others have had the same problem and would love this feature.

**Comment by shiftkey** [comment] 2018-05-15 22:46
This feels very similar to #4484

**Comment by iAmWillShepherd** [comment] 2018-05-16 15:33
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4484. Please follow that issue
for further updates.

@aMoniker, although that issue is closed, it is marked `future-proposal` so we know to come back to it in our planning session. If you have any additional details you'd like us to know about your proposal, please use that issue.

**Closed by iAmWillShepherd** 2018-05-16 15:33 UTC
Labels: enhancement
