### ISSUE TITLE
Closing GitHub Desktop forcefully closes Notepad++ when Notepad++ was opened by GitHub Desktop

### ISSUE THREAD

**Issue by mmseng** [desktop/desktop#11518] opened 2021-02-02 22:39 UTC
### Describe the bug

Closing Desktop when the "Open in Notepad++" button was used to launch Notepad++ causes Notepad++ to force close. This can cause loss of work and Notepad++ to misbehave when reopened.

### Version & OS

GitHub Desktop 2.6.2
Notepad++ 7.9.1
Windows 10 x64 20H2

### Steps to reproduce the behavior

1. Open GitHub Desktop.
2. Clone a repository.
3. Make sure Notepad++ is closed.
4. Click "Open in Notepad++ button in GitHub Desktop interface. Notepad++ opens the appropriate files.
5. Close GitHub Desktop. Notepad++ is forcefully closed.
6. Reopen Notepad++.
7. Notepad++ might recover, or it might hang. If it weren't for Notepad++'s newish feature that saves open and unsaved work, any new unsaved tabs opened previously could be lost.

### Expected behavior

Closing GitHub Desktop has NO effect on Notepad++.

### Actual behavior

Closing GitHub Desktop closes Notepad++ (only when Notepad++ was opened by GitHub Desktop). Having Notepad++ already open, and THEN using GitHub Desktop's "Open in Notepad++" button prevents the issue from occurring.

### Additional context

I originally thought this was intended behavior until I saw Notepad++ start to misbehave upon being reopened. Either way, I am frequently using Notepad++ for many other activities than just editing repo files, regardless of whether I opened it with GitHub Desktop or not. As such, it should NOT be GitHub Desktop's prerogative to close Notepad++.

If this is an intended behavior then:
1) It should be made optional, letting the user choose whether GitHub Desktop closes Notepad++ when being closed.
2) It should close Notepad++ gracefully and not forcefully.

Thanks,
== Matt

**Comment by sergiou87** [comment] 2021-02-03 10:44
Thank you @mmseng for your report! I can reproduce this behavior and it's definitely not intended. I got a fix already, but I don't understand why it's needed 🤣 

In case you're interested, the fix consists in passing `usesShell: true` for Notepad++ here:

https://github.com/desktop/desktop/blob/c2b1b93/app/src/lib/editors/win32.ts/#L339

**Comment by sergiou87** [comment] 2021-02-03 11:32
I got a better fix for this in #11520 😄

**Closed as completed** 2021-02-03 11:47 UTC
Labels: bug, priority-2
