### ISSUE TITLE
Changing the casing of a file name isn't detected in the diff and not committed

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#12425] opened 2021-06-10 13:09 UTC
### Describe the bug
If you change the name of a file without adding or removing characters and just changing their casing (for example `readme` -> `README`), GitHub desktop will not detect these changes at all and will not let you commit them (even if you change the contents of the file itself, the name will remain the same). A possible workaround is changing one character, committing, then changing the name again to the one you want and committing again but that's unwanted behavior. Not sure if it is possible to fix this as it may be an issue on git's side but please let me know!

### Version & OS
GitHub desktop version 2.8.3 on Windows 10 version 21H1 build 19043.985

### Steps to reproduce the behavior

1. Rename a file in your IDE or file explorer by changing the casing of it's characters and not removing nor adding any
2. Go to your repository on github desktop
3. Observe that the diff did not reflect that name change
4. Additionally, you can change the contents of the file to see that the diff shows up for the old name and not the new one.

### Expected behavior
The file is renamed with the new casing

### Actual behavior
The new name of the file is completely ignored

### Screenshots
My diff:
![image](https://user-images.githubusercontent.com/38259440/121530484-6266b200-c9f5-11eb-8f9c-a046f104b5cc.png)
The actual file on the IDE:
![image](https://user-images.githubusercontent.com/38259440/121530524-6c88b080-c9f5-11eb-9a1f-f2ad5f597252.png)

**Comment by steveward** [comment] 2021-06-10 19:31
@ImRodry thanks for the issue. By default Git sets the `core.ignorecase` value to `true` inside a repository created on Windows. See [this explanation](https://github.com/desktop/desktop/issues/2672#issuecomment-329011490) along with [this follow up comment](https://github.com/desktop/desktop/issues/2672#issuecomment-338171399) for some further details.

Since this is the expected behavior I am going to close this out, but let me know if you have any further questions about this.

**Closed as completed by steveward** 2021-06-10 19:31 UTC

**Comment by lourenco-melo** [comment] 2025-02-19 15:15
Yes, you can set core.ignorecase to false in Git using the following command:
`git config --global core.ignorecase false`

Alternatively, if you want to change this setting only for a specific repository, navigate to that repository and run:
`git config --local core.ignorecase false`
