### ISSUE TITLE
As a user, I want to star specific repos and have them always appear at the top of the list.

### ISSUE THREAD

**Issue by ryanhuff** [desktop/desktop#12852] opened 2021-08-27 15:39 UTC
### Describe the feature or problem you’d like to solve

There are about 3 dozen repositories that I have locally. The "recent" repos always shows 3, but there are about 5-6 that I interact with on a regular basis. It would be nice to have those always listed at the top for easy access, without having to search and clear the search, etc.

### Proposed solution

Allow me to star or pin repos to have those always appear at the top of the list.

**Comment by tidy-dev** [comment] 2021-08-31 11:30
@ryanhuff Thanks for your input. This is a duplicate of #8183, which unfortunately currently isn't being worked on. But, we may revisit in the future so I going to link this issue. Feel free to add your comment or thumbs up to that issue as well.

**Closed as completed by tidy-dev** 2021-08-31 11:30 UTC
Labels: enhancement
