### ISSUE TITLE
Cannot add/remove patch on large diff

### ISSUE THREAD

**Issue by PatMyron** [desktop/desktop#6510] opened 2018-12-29 18:50 UTC
## Description

After expanding a large diff that was not displayed by default, I was unable to add or remove specific hunks of a file diff from being including in a commit

## Version

* GitHub Desktop:
Version 1.5.1

* Operating system:
MacOS 10.14.2

## Steps to Reproduce
This is the large hunk that was being committed:
https://github.com/PatMyron/advent-of-code/commit/27573a3955ac6ee1eef333369443f3c63447800d
There was also a small hunk later in the file I was trying to ignore for this commit

### Expected Behavior
I expected to be able to click near the line numbers to include part of a file diff in a commit
### Actual Behavior
I had to run this on the command line instead:
`~/Documents/GitHub/advent-of-code/2018 $ git add -p 5.py`
[output](https://github.com/desktop/desktop/files/2716634/commandLineGit.txt)

### Logs
[2018-12-28.desktop.production.log](https://github.com/desktop/desktop/files/2716620/2018-12-28.desktop.production.log)
[2018-12-29.desktop.production.log](https://github.com/desktop/desktop/files/2716621/2018-12-29.desktop.production.log)

**Comment by shiftkey** [comment] 2018-12-31 15:18
@PatMyron thanks for the report! I was able to reproduce the issue using these steps:

 - create a new file in a repository, using the contents from this gist https://gist.github.com/shiftkey/b7879e34d21dfd7478471f8fc6c125ff - it's over 10MB of text, but is enough to hit the threshold and show the warning UI

 - in GitHub Desktop, view the diff for the new file - you should see the warning

<img width="1325" alt="screen shot 2018-12-31 at 11 14 27 am" src="https://user-images.githubusercontent.com/359239/50562786-8afb0580-0ced-11e9-9120-8131a5b44499.png">

 -  after clicking "View Diff" you should see the diff contents with the sidebar selected

<img width="1320" src="https://user-images.githubusercontent.com/359239/50562796-a534e380-0ced-11e9-8ab7-30a02a93c6b7.png">

 - note that while you can hover over the numbers and click on them, the actual diff itself is not updated to reflect those changes - all lines remain selected

**Comment by shiftkey** [comment] 2018-12-31 15:19
Marking as `priority-2` because it affects crafting a commit, and the workaround requires users to know about `git add -p`.

**Comment by mastef** [comment] 2019-02-25 07:28
@shiftkey  Is this related to this bug report? The file itself is not that big ( file is ~79K ). The latest change adds a chunk of inline js code in the end ( a library in this case ). Can't select portions to commit.

![2019-02-25 14-24-35 2019-02-25 14_25_46](https://user-images.githubusercontent.com/762297/53320846-7744d780-3909-11e9-8576-53abf46316de.gif)

**Comment by shiftkey** [comment] 2019-03-08 13:14
@mastef I believe that's a different issue, but we made some changes to this area in `1.6.3` which went out this week that might have addressed the issue - if you are able to see the same behaviour please open a fresh issue with repro steps.

**Comment by sergiou87** [comment] 2024-09-19 08:25
It seems to be fixed in v3.4.5 (although I ran into a different bug while testing this 😱 )

**Closed by sergiou87** 2024-09-19 08:25 UTC
Labels: bug, priority-3
