### ISSUE TITLE
Can't push from GitHub desktop with Actions

### ISSUE THREAD

**Issue by mydigitalself** [desktop/desktop#7079] opened 2019-03-13 13:30 UTC
**Please describe the problem you think should be solved**
We have recently started using Actions on our GitHub repository.
I just started trying out GitHub desktop and fell at the first hurdle

When I try to push I get an error ending with

>(refusing to allow an integration to create .github/main.workflow

I have made no changes to that file in my commit

**Comment by steveward** [comment] 2019-03-13 18:11
@mydigitalself thanks for the report. This looks like a duplicate of https://github.com/desktop/desktop/issues/6526. 

There is work being done to allow apps using OAuth tokens (like GitHub Desktop) to create/modify the `main.workflow` file, but I don't have a firm timeline for when that will be available. Until that is fully shipped you can workaround this by authenticating with a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) from the command line, or by modifying the token GitHub Desktop uses to use your personal access token. To do the latter you will need to edit the credentials in macOS Keychain Access or Windows Credential Manager -- specifically the `GitHub - https://api.github.com/<user>` entry. 

I'm going to close this issue out, but please let me know if you have any questions about this.

**Comment by billygriffin** [comment] 2019-09-03 14:28
I'm going to reopen this issue to track the work on the OAuth side, and we'll close it when people can push these files, especially now that Actions has more users.

**Closed** 2019-09-27 22:13 UTC
Labels: enhancement

**Comment by britzl** [comment] 2019-10-03 10:08
A fix for this issue was part of the release notes for GitHub Desktop 2.2, but I'm still getting the same error when trying to push a change to a workflow file.

**Comment by niik** [comment] 2019-10-03 11:24
Hi @britzl. The fix that ended up shipping in 2.2 requires users who want to be able to push workflow files to sign out and then sign back in again in order to grant GitHub Desktop the permissions required.

We have a follow-up PR (#8357) which will make this flow semi-automatic but that unfortunately didn't make it into yesterday's release.

I will update the issue body to include this information for any other users who stumble on this issue from the release notes.

**Comment by britzl** [comment] 2019-10-03 16:34
@niik Thank you for clearing that up! Now I can finally push workflows from the comfort of my desktop!

**Comment by billygriffin** [comment] 2019-10-03 17:29
That's great @britzl! 🎉

**Comment by reloxx13** [comment] 2019-12-21 21:24
un in this today

! [remote rejected]     my-skr-mini-e3 -> my-skr-mini-e3 (refusing to allow an  OAuth App to create or update workflow `.github/workflows/bump-date.yml` without  `workflow` scope)
--


updated a fork with sourcetree.

**Comment by niik** [comment] 2019-12-23 10:38
> updated a fork with sourcetree. tried relogin already and re-add oauth app

Hi @reloxx13, this issue relates to the ability to push actions with GitHub Desktop. If I'm understanding your description correctly you are using SourceTree. For that you'll have to contact the SourceTree support team. If you are using GitHub Desktop and are unable to push please open a new issue and fill out the template so that we can assist you.

**Comment by RehanSaeed** [comment] 2020-01-15 16:34
Any chance of a similar fix for Visual Studio?

**Comment by ethomson** [comment] 2020-01-16 12:50
@RehanSaeed - the Visual Studio team is aware of and working on this issue.  I haven't heard an ETA but I'll see if I can discover anything.

**Comment by AaronMT** [comment] 2020-01-20 21:38
Does @gittower have a work-around or a fix? I am running into this too on (4.0)

**Comment by reloxx13** [comment] 2020-01-21 07:22
its fixed in sourcetree, a re-sign in window for github popped up when i tried to push and now the scope is set.

**Comment by jhildenbiddle** [comment] 2020-07-21 15:56
@AaronMT -- I'm also having issues with Tower for Mac. Until the issue gets resolved, I'm just using GitHub Desktop to push when I've made a change to a workflow.

**Comment by jwpjrdev** [comment] 2021-01-27 16:39
I can vouch for the Tower (macOS) issues. I'll probably just use GitHub Desktop for workflows for now.

**Comment by alexrinass** [comment] 2021-01-28 08:12
@AaronMT @jhildenbiddle @jwpjrdev Until supported, you can always create a Personal Access Token with the appropriate rights and use this in Tower for Mac for authentication.

**Comment by jwpjrdev** [comment] 2021-01-28 13:27
Will give it a try.

**Comment by ManAnRuck** [comment] 2021-04-15 16:42
For Tower users:
you can use this workaround…

1. generate a "[Personal Access Token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token)" **with workflow** rights
2. Change Remote url to `https://YOUR_USERNAME:YOUR_TOKEN@github.com/YOUR_USERNAME/YOUR_REPOSITORY`
  a. via Tower (Right click your remote and click "Edit Connection Settings…")
  b. via [git commands](https://docs.github.com/en/github/getting-started-with-github/managing-remote-repositories)
