### ISSUE TITLE
UI elements hidden in clone dialog

### ISSUE THREAD

**Issue by fenduru** [desktop/desktop#3070] opened 2017-10-16 15:23 UTC
### Description

The default window size hides UI elements in the "clone" dialog.

![image](https://user-images.githubusercontent.com/1354771/31619925-e5433b56-b263-11e7-8d4d-93c1b54e1b93.png)

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Windows 7

### Steps to Reproduce

1. Install Github Desktop
2. Click "Clone a Repository"
3. Select enterprise tab
4. If there are projects in the list of repositories, the clone/cancel buttons are hidden

**Expected behavior:** Dialog should either re-center or provide a scrollbar to access the off-screen elements

**Actual behavior:** UI elements are hidden and unreachable without closing dialog and reopening, or resizing window before the dialog opens.

**Reproduces how often:** Any time you switch from Github.com tab to enterprise tab

#### Additional Information

I'm working on training videos for my coworkers, and this makes the setup instructions more complicated than I would like, as I have to instruct them to resize the window first.

**Comment by iAmWillShepherd** [comment] 2017-10-16 15:42
Thanks for bringing this to our attention! 👍

**Comment by tierninho** [comment] 2017-10-17 09:58
Can reproduce this in 1.0.5beta0 as well. 

Steps to repro below. So when a user is not signed into one of two accounts, the modal recognizes the height of the 'please signin' tab. When the user switches to the 'already signed in' account tab, the modal expands off the screen.

Reproduce:
- sign-in to dotcom, sign-out of Enterprise
- exit Desktop and re-open
- open Clone repo modal and navigate to Enterprise, now close modal
- open Clone repo modal (should be on Enterprise tab)
- click dotcom tab and it should load off the screen

<img width="467" alt="screen shot 2017-10-17 at 10 44 33 am" src="https://user-images.githubusercontent.com/14828183/31658434-e823c24e-b328-11e7-9adb-5b0252c355de.png">
<img width="464" alt="screen shot 2017-10-17 at 10 44 48 am" src="https://user-images.githubusercontent.com/14828183/31658435-e842d7ba-b328-11e7-9e6f-f82ab9167bbf.png">

**Comment by a-golovanov** [comment] 2018-10-20 02:08
The issue can be easily fixed by recentering the dialog on every resize, but some may consider the resulting user experience a bit odd. What do the GitHub devs think about that?

**Comment by billygriffin** [comment] 2019-03-15 23:00
Is this just on Windows @tierninho? I wasn't able to repro on macOS following your steps. The modal seems to resize appropriately based on the content.

**Comment by tierninho** [comment] 2019-03-16 00:55
@billygriffin I can repro this on a Mac and Windows, but only if I have a reduced height on my Desktop application.

**Comment by billygriffin** [comment] 2019-11-21 15:14
Thanks @fenduru for the issue. Because this only happens in a particular set of circumstances and at the minimum window height, and because there are ways around it (resize the window, or just select the repo you want and hit enter, etc.), I'm going to close it for now. However, if we see it come up for others and it's sufficiently blocking, we're definitely open to revisiting. Thanks!

**Closed by billygriffin** 2019-11-21 15:14 UTC
Labels: bug, help wanted, priority-3
