### ISSUE TITLE
Feature request: provide filter in the changes/history list

### ISSUE THREAD

**Issue by NeilMacMullen** [desktop/desktop#8913] opened 2020-01-14 15:15 UTC
### Describe the feature or problem you’d like to solve

Sometimes I know the name of the file I have changed and want to view it or alternatively want to ensure that I haven't accidentally made changes outside a particular folder.  At the moment there is no apparent way to filter the changelist to get to what I want to see.

### Proposed solution

Provide a 'live' filter box above the list of changed files.  As characters are typed into the filter, the list of changed files should be filtered to those whose name/path contains the filter text.  Some visual indication (warning) might be useful to make it obvious that there are changes that are not listed.

How will it benefit Desktop and its users?

With this feature users can...
1.  Quickly find a specific file in order to review changes
2.  Easily check that they haven't accidentally changed files in unexpected directories
3.  Review files in a more logical order (e.g. filter to all changes in "content", review then filter to all changes in "code" etc....)

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment] 2020-01-14 15:27
Hi @NeilMacMullen, this looks like a duplicate of https://github.com/desktop/desktop/issues/6407, so I'm going to close it in favor of that one. We don't have plans to work on this in the immediate future, but will update that issue when there's an update. Thanks for the issue!

**Closed by billygriffin** 2020-01-14 15:27 UTC
