### ISSUE TITLE
no other branches are displayed

### ISSUE THREAD

**Issue by liuyuno** [desktop/desktop#3170] opened 2017-10-27 02:55 UTC
### Description

![image](https://user-images.githubusercontent.com/28513143/32085978-c68a7bb2-bb04-11e7-959c-246654d0d284.png)

# other repository **no other branches are displayed**

### Version

**GitHub Desktop version: 1.0.5 [version here]

**Comment by kellpossible** [comment] 2017-10-27 02:56
Possible duplicate of #3169 ?

**Comment by shiftkey** [comment] 2017-10-27 03:41
Closing in favour of #3169

**Closed by shiftkey** 2017-10-27 03:41 UTC
