### ISSUE TITLE
Automatics checks for update in 0.8.0 do not work, manual update check fails 

### ISSUE THREAD

**Issue by DRSAgile** [desktop/desktop#2715] opened 2017-09-13 12:26 UTC
### Description

In regular use of GitHub desktop 0.8.0 it was never found out that new versions of the program have appeared. Manual update checks have made the spinner running for forever, and, at another time, generated "Error: command failed" in the code about the IO on the downloaded "delta" file for 0.8.1 version (see below).

### Version

0.8.0

### Steps to Reproduce

See above.

### Logs

```
2017-09-13T11:48:48.949Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: ��������� ���� ��� ��������� ������. ---> System.Net.WebException: ���������� �� ����� ������� WebClient. ---> System.IO.IOException: ������� �� ����� �������� ������ � ����� "C:\Users\������������\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg", ��� ��� ���� ���� ������������ ������ ���������.
   � System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   � System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   � System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   � System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- ����� ����������� ����������� ����� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- ����� ����������� ����������� ����� ���������� ---
   � System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   � System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   � System.Threading.Tasks.Task`1.get_Result()
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
   � Squirrel.Update.Program.Main(String[] args)
---> (���������� ���������� #0) System.Net.WebException: ���������� �� ����� ������� WebClient. ---> System.IO.IOException: ������� �� ����� �������� ������ � ����� "C:\Users\������������\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg", ��� ��� ���� ���� ������������ ������ ���������.
   � System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   � System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   � System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   � System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- ����� ����������� ����������� ����� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Update.Program.<Download>d__7.MoveNext()<---


    at AutoUpdater.emitError (C:\Users\[UserName]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at squirrelUpdate.download (C:\Users\[UserName]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21)
    at C:\Users\[UserName]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14
    at ChildProcess.<anonymous> (C:\Users\[UserName]\AppData\Local\GitHubDesktop\app-0.8.0\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

#### Additional Information

This might be related with the issue of code pages and their conversions?

**Comment by shiftkey** [comment] 2017-09-13 12:38
@DRSAgile the autoupdater will try and download the delta file, and should fall back to downloading the whole package if it's not successful. Do you see any mention of a `.nupkg` package being downloaded after this?

The stack trace suggests this is a problem with downloading the file, looking at this bit of the stack trace:

```
   � System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   � System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   � System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   � System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
```

But the characters around this message are really valuable to helping us identify where the root cause of this issue is.

```
System.IO.IOException: ������� �� ����� �������� ������ � ����� "C:\Users\������������\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg", ��� ��� ���� ���� ������������ ������ ���������
```
If they're not retained in the original log file, the `%LOCALAPPDATA%/GitHubDesktop/SquirrelSetup.log` is the original source of truth for the updater and installation work happening behind the scenes.

I don't think this is related to the earlier discussions about code pages and unicode account names - the .NET APIs should support this stuff out-of-the-box.

**Comment by DRSAgile** [comment] 2017-09-13 12:49
@shiftkey Thanks for reply.

By this time I have already downloaded and installed 0.8.2 from this site manually, so "%LOCALAPPDATA%/GitHubDesktop/SquirrelSetup.log" does not contain anything from the previous version any more. In the new version check for update goes normally, but this is maybe because so far there is no newer version to download (0.8.3 or something). I will write back here if there will be this error again when there will be a new release.

There is some weird staff happenning, though (why GHD tries to "hack" Chrome's link?) in the log file:

2017-09-13 15:29:33> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-09-13 15:29:33> ApplyReleasesImpl: File 'C:\Users\[UserName]\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Google Chrome.lnk' could not be converted into a valid ShellLink: System.Runtime.InteropServices.COMException (0x80004005): HRESULT E_FAIL.

**Comment by shiftkey** [comment] 2017-09-13 12:51
> There is some weird staff happenning, though, in the log file (why GHD tries to "hack" Chrome's link?):

@DRSAgile that's Squirrel looking for links related to the app to update (because each version is stored in a different folder). I wouldn't worry about that.

**Comment by shiftkey** [comment] 2017-09-13 12:52
> I will write back here if there will be this error again when there will be a new release.

Closing this out pending feedback about the next update from @DRSAgile. If someone else encounters this I'd love to get my hands on their `SquirrelSetup.log` file.

**Comment by jeffpapp** [comment] 2017-09-13 13:21
I'm running into a similar issue.  Here's what I have in my SquirrelSetup.log

```
2017-09-13 07:18:17> Program: Starting Squirrel Updater: --download https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:18:17> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:18:17> CheckForUpdateImpl: Using existing staging user ID: ab8175a2-ed7e-536f-a594-7a793a889bfa
2017-09-13 07:18:17> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:18:17> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.8.0&env=production&id=GitHubDesktop&localVersion=0.8.0&arch=amd64
2017-09-13 07:18:17> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.2-delta.nupkg
2017-09-13 07:18:17> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg
2017-09-13 07:18:21> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.UpdateManager.DownloadReleasesImpl.downloadRelease(String updateBaseUrl, ReleaseEntry releaseEntry, IFileDownloader urlDownloader, String targetFile, Action`1 progress)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Squirrel.UpdateManager.DownloadReleasesImpl.downloadRelease(String updateBaseUrl, ReleaseEntry releaseEntry, IFileDownloader urlDownloader, String targetFile, Action`1 progress)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---
```

**Comment by DRSAgile** [comment] 2017-09-13 13:27
It looks like the "delta" file is downloaded/written in a way that requires the elevation of privileges to access it?

**Comment by jeffpapp** [comment] 2017-09-13 13:35
I'm also getting lots of errors that the delta files are in use by another process once it does actually download the files.

```
2017-09-13 07:30:33> Program: Starting Squirrel Updater: --download https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:30:33> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:30:33> CheckForUpdateImpl: Using existing staging user ID: ab8175a2-ed7e-536f-a594-7a793a889bfa
2017-09-13 07:30:33> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.8.0&env=production
2017-09-13 07:30:33> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.8.0&env=production&id=GitHubDesktop&localVersion=0.8.0&arch=amd64
2017-09-13 07:30:34> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg
2017-09-13 07:30:34> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.2-delta.nupkg
2017-09-13 07:30:34> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg
2017-09-13 07:30:34> IEnableLogger: Failed downloading URL: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
2017-09-13 07:30:34> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/githubdesktop-0.8.1-delta.nupkg
2017-09-13 07:30:34> IEnableLogger: Failed downloading URL: https://central.github.com/api/deployments/desktop/desktop/latest/githubdesktop-0.8.1-delta.nupkg: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
2017-09-13 07:30:38> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\jpapp\AppData\Local\GitHubDesktop\packages\GitHubDesktop-0.8.1-delta.nupkg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFileAsync(Uri address, String fileName, Object userToken)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<LogIfThrows>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.FileDownloader.<DownloadFile>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_0`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Download>d__7.MoveNext()<---
```

**Comment by shiftkey** [comment] 2017-09-14 01:36
@jeffpapp could you attach the whole log (or you can send it to me - email is in my profile) - I'd love to understand what fallback behaviour Squirrel is doing when it encounters this error.

**Comment by shiftkey** [comment] 2017-09-14 02:12
Well I think I know the problem.

The `0.8.0` client will send this information to the update server:

```
https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.8.0&env=production&id=GitHubDesktop&localVersion=0.8.0&arch=amd64
```

The response that comes back looks like this:

```
1E607824B9FBFF5BE34EF5F393464AE899F6EFBD GitHubDesktop-0.8.0-full.nupkg 81440726
9089B32450BDFE613B7A9166C48E302AD68A161A GitHubDesktop-0.8.0-delta.nupkg 7628586
D54413BEFA17FEEB07961CBCE84DCB3723A46BED GitHubDesktop-0.8.1-full.nupkg 83060889
9030AF1B22A26478313C47340903F035243C9058 GitHubDesktop-0.8.1-delta.nupkg 25349535
927552E29DB302DC8B87BE98B676D46516749826 GitHubDesktop-0.8.1-full.nupkg 83070985
A269767E5A34BF238B0D5AE9F4514F70899AB9D5 GitHubDesktop-0.8.1-delta.nupkg 25359887
B613F69D0627613790286E01850249532ACFCE2C GitHubDesktop-0.8.2-full.nupkg 83068989
92975B6F11F0A921C475E25F5B41A0A507E308F7 GitHubDesktop-0.8.2-delta.nupkg 732885
```

And in the SquirrelSetup.log file there's these three messages:

```
2017-09-14 11:36:38> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg
2017-09-14 11:36:38> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.1-delta.nupkg
2017-09-14 11:36:38> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.8.2-delta.nupkg
```

This explains the file being locked - it's trying to download the same file twice.

I'll look at our update server code and see if we can get it to return just one update for the `0.8.1` release, which should unblock clients that are stuck and unable to update, without needing to reinstall.

**Comment by joshaber** [comment] 2017-09-14 11:48
The server's been fixed.

Try checking for updates again and lemme know how it goes!

**Comment by jeffpapp** [comment] 2017-09-15 16:00
> The server's been fixed.
> 
> Try checking for updates again and lemme know how it goes!

I got the update message bar in the app this morning and everything updated correctly to 0.9.1.

**Comment by joshaber** [comment] 2017-09-15 16:02
Great! Sounds like this is fixed 🤘

**Closed by joshaber** 2017-09-15 16:02 UTC
Labels: bug, Windows
