### ISSUE TITLE
repo filter does not search in repo alias

### ISSUE THREAD

**Issue by staabm** [desktop/desktop#14607] opened 2022-05-12 07:05 UTC
### The feature request

I have created aliases for various repos in github desktop - which is a awesome feature btw.

I am wondering whether its intended, that searching within the repo filter does not find/search in the defined aliases.

----

see my repo list (including a repo with an alias):
![grafik](https://user-images.githubusercontent.com/120441/168011610-c8158611-7a9c-4e18-afcb-066a394d82d3.png)

and when I search for that alias, the repo is not in the list:

![grafik](https://user-images.githubusercontent.com/120441/168011649-066e5f8c-3fd4-4469-af02-d630671ed172.png)

### Proposed solution

the repo filter should find repositories with a defined alias, when searching for the alias

**Comment by sergiou87** [comment] 2022-05-12 09:55
Hmmm weird, I recall adding support for alias search, and it actually works for me:

![image](https://user-images.githubusercontent.com/1083228/168044496-0853972c-03b8-408d-b01e-5f672f7a9d58.png)

As you can see, I search for `copy` and that word is only in that repo's alias. Does this happen to you with every single alias or only that one?

**Comment by staabm** [comment] 2022-05-12 10:08
good catch.. it seems to work for some

![grafik](https://user-images.githubusercontent.com/120441/168047102-480649d4-2652-4a38-8587-0e9ef6fa48ca.png)

**Comment by staabm** [comment] 2022-05-12 10:10
maybe the problem is caused by me searching for a term, which is also my username and therefore it matches "everything"

![grafik](https://user-images.githubusercontent.com/120441/168047472-2646a21a-0297-48d3-8e50-81a93b0b1942.png)

**Comment by sergiou87** [comment] 2022-05-12 10:18
I think that makes sense! It tries to match the alias, the repo and the owner of that repo (in this case, your user): https://github.com/desktop/desktop/blob/fb3fea5575c0adbbc121e9cc23ec66f2cd0a51de/app/src/ui/repositories-list/group-repositories.ts#L93-L95

`nameOf` would be `staabm/phpstan` in your specific case: https://github.com/desktop/desktop/blob/318db91fb3c16d280bdaa013ffa450c6a68d6c76/app/src/models/repository.ts#L155-L164

**Comment by staabm** [comment] 2022-05-14 06:39
it might make sense to weight the different kinds of search-hits, so e.g. hits in the alias get more important then hits in the repo name?

**Comment by DNAOFFICIALL** [comment] 2022-05-14 07:08
I've been looking for my repositories over the years to retrieve my photos and videos via Windows 7 activated with a Yahoo account or any other account I own. Is there a way to get all my accounts?  Find and retrieve?

**Comment by sergiou87** [comment] 2022-05-16 07:36
@staabm you mean (in your example) something like hiding hits in the repo name if there were hits in the alias? I think that might be more confusing to users as that behaviour would be hard to predict 😕 

In any case, seems like the app is working as intended, so I'm gonna close this issue 😳

**Closed as completed by sergiou87** 2022-05-16 07:36 UTC
Labels: more-info-needed

**Comment by staabm** [comment] 2022-05-16 07:50
> you mean (in your example) something like hiding hits in the repo name if there were hits in the alias?

nope, I mean sorting search results differently, by sorting more specific search hits to the top
