### ISSUE TITLE
GUI network

### ISSUE THREAD

**Issue by lfaveur** [desktop/desktop#15263] opened 2022-09-10 14:39 UTC
### The feature request

Is it possible to add a gui of a repo as 'network'

![image](https://user-images.githubusercontent.com/20400434/189488027-65bb8508-6da2-4233-b09d-058b0370a808.png)

additionnaly the possibility to turn the schema horizontally

### Proposed solution

This will be good have it inside guthub desktop to avoid us use the website github to consult the branches

### Additional context

I think horizontally can be perfect and guithub desktop will be a complete tools.

![image](https://user-images.githubusercontent.com/20400434/189488218-f1ec9874-7787-40f8-adfb-c5d7d6f48f0e.png)

**Comment by sergiou87** [comment] 2022-09-12 10:39
Hello! I think this is duplicate of #9452, so I'm gonna close this issue in favor of that one. Feel free to subscribe to it if you want to get notified when we make any progress on it 😄  (right now it's not in our roadmap, though, sorry! 😅 )

**Closed as completed by sergiou87** 2022-09-12 10:39 UTC
