### ISSUE TITLE
desktop cannot find previously cloned repos after update

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#14345] opened 2022-04-13 14:35 UTC
### The problem

I just updated GitHub desktop to the latest version (2.9.13) and some of my repos are no longer being recognized by the app. This doesn't happen with all the repos, only ones to which I pushed recently.

### Release version

2.9.13

### Operating system

Windows 11 x64

### Steps to reproduce the behavior

1. On a previous version of GitHub Desktop, clone a repo and push to it at least once
2. Update to version 2.9.13
3. Your repo should no longer appear as valid and you should see a screen similar to the one in the screenshots field below

### Log files

[2022-04-13.desktop.production.log](https://github.com/desktop/desktop/files/8482295/2022-04-13.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/38259440/163199235-c3ce1fc8-392a-479a-b32d-68d2983894ec.png)
(Clicking check again or locating to the same folder doesn't fix it)

### Additional context

The reason I gave for this error occurring is my best guess and what happened before I updated, however the issue itself could be related to something else, I hope this helps track it down further though.

**Comment by scottfavre** [comment] 2022-04-13 14:37
I'm seeing this as well. Not all repositories, only some.

**Comment by tidy-dev** [comment] 2022-04-13 14:44
Duplicate of #14336 - Closing this - Please follow along there.

**Closed as completed by tidy-dev** 2022-04-13 14:44 UTC
