### ISSUE TITLE
GitHub Desktop deletes repository files

### ISSUE THREAD

**Issue by victor-david** [desktop/desktop#11992] opened 2021-04-13 04:32 UTC
### Describe the bug

GitHub Desktop, under certain conditions, deletes repository files. Details below.

### Version & OS

GitHub Desktop 2.7.2 - Windows 7 Ultimate 64 bit.

### Steps to reproduce the behavior

This is what happened to me. 

1. **Master** branch. All files committed. No pending changes.
2. Attempt to switch to another branch.
3. GitHub Desktop responds with _fatal: cannot create directory at '[name of directory]': Permission denied_
4. Branch remains on **master**, with all files in the [name of directory] now deleted (they were part of master)
5. GitHub Desktop now shows changes in the repository master branch in the form of the deleted files (that it deleted). 

### Expected behavior

A clean recovery from the error that prevented GHD from switching to the other branch.

### Actual behavior

GHD fails to recover and deletes an entire directory. 

(It does seem strange that GHD could first delete the directory successfully, but then didn't have permission to create it. ??)

### Screenshots
n/a

### Logs
~~~txt
2021-04-13T00:21:46.574Z - error: 
[ui] `git -c credential.helper= -c protocol.version=2 checkout --progress color-picker --
` exited with an unexpected code: 128.
stderr: fatal: cannot create directory at 'src/Restless.Toolkit/Controls': Permission denied
~~~
### Additional context

I had been comparing directories in the repository and (I suppose) that my compare program had a directory locked, which caused the _permission denied_.

Fortunately, I have backups  so I rebooted to kill the offending process, grabbed the deleted directory and put it back. Others who run into this could be out of luck.

Also, I realize this could be an edge case, but it would be nice if GHD could recover gracefully instead of wiping out data. 

Thanks.

**Comment by steveward** [comment] 2021-04-13 21:14
@victor-david thanks for the report and sorry about this. I'll take a look and see if I can reproduce this. What specific compare tool were you using?

For future reference if the files are all showing as deleted you can use the discard feature to "undo" the deletion by discarding the uncommitted changes in GitHub Desktop.

**Comment by victor-david** [comment] 2021-04-13 22:23
@steveward thanks for the quick reply. I have ExamDiff Pro version 3.5. It's quite old these days, but does what I want. Likely time for an update....

Also, I appreciate the discard feature reminder. I use it all the time for quick, temporary experiments, but it didn't occur to me to use it for this. I guess I was in "oh-no-what-happened" mode. :)

**Comment by steveward** [comment] 2021-04-20 18:53
Thanks @victor-david -- I tested this out in ExamDiff Pro Version 11.0 and didn't even see lockfiles created when diffing two directories. I may be missing a setting somewhere, though. I'd be curious to see if you are able to reproduce this again in a newer version. It looks like v3.5 is back from 2007, so it does look like it's a bit out-of-date. 😄 

I'm going to close this out but let me know if you have any updates about this.

**Closed as completed by steveward** 2021-04-20 18:53 UTC
Labels: investigation-needed
