### ISSUE TITLE
Allow user to select the files they want to discard

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#2248] opened 2017-07-14 15:24 UTC
Right now, discarding changes is an all or one-by-one affair. It would be nice to allow users to select multiple files so they can batch discard changes.

**Comment by JosephTLyons** [comment] 2017-07-18 10:44
Awesome, thanks for opening this suggestion Will.

**Comment by UgurAldanmaz** [comment] 2017-07-23 20:07
I need this functionality usually. I would like to work on it. I did not look at the source code yet, so I do not know if this task can be considered as [accepting-prs.](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md#accepting-prs)

Can I work on it? Thanks!

**Comment by j-f1** [comment] 2017-07-23 20:55
Since it’s not assigned to anyone, why don’t you try it out?

**Comment by UgurAldanmaz** [comment] 2017-07-23 21:24
I want to be sure that it is a good start point. Thanks! I will do my best.

**Comment by iAmWillShepherd** [comment] 2017-08-02 16:01
>Can I work on it? Thanks!

@UgurAldanmaz , sure thing. I've added the label `accepting-prs`

**Comment by UgurAldanmaz** [comment] 2017-08-03 17:36
Thanks @iAmWillShepherd! I took a look at the code and played around with it to understand. 

I am not experienced in electron but I want to gain. It will take a while to get done. Do we have a deadline?

**Comment by iAmWillShepherd** [comment] 2017-08-03 17:46
No, there isn't a deadline since this issue isn't prioritized for  v1.0. If you'd like this to be a part of v1.0, I'd recommend having a PR open and ready for review in a few weeks. Also, to ensure your PR gets merged promptly, make sure to ask for feedback early and often.

**Comment by UgurAldanmaz** [comment] 2017-08-03 18:01
> to be a part of v1.0,

It sounds great! Ok, I got it. I will be ready as soon as possible. Thank you again!

**Comment by joshaber** [comment] 2017-08-10 19:34
This is really a duplicate of #1712.

**Closed by joshaber** 2017-08-10 19:34 UTC
Labels: accepting-prs, enhancement
