### ISSUE TITLE
Repository scroll bar is always positioned at the top

### ISSUE THREAD

**Issue by Morilli** [desktop/desktop#7870] opened 2019-06-25 17:16 UTC
## Description

When opening the repository list on the side, the scroll bar will seem to be positioned at the very top, although this isn't true when a repository low enough in that list was selected beforehand. Any scrolling or moving the scrollbar will therefor result in an immediate reposition of either the scrollbar or the repository list.

## Version

* GitHub Desktop: ``Version 2.0.4``

* Operating system: ``Microsoft Windows [Version 10.0.18362.207]``

## Steps to Reproduce

1. Select a repository relatively low in the repository list
2. Reopen the repository list.
3. See the mismatch between the actual position in that list and the position the scroll bar seems to indicate.

### Expected Behavior

The scroll bar should be positioned at the appropriate place.

### Actual Behavior

It is always positioned at the very top.

## Additional Information

Video: https://streamable.com/8wcjx

**Comment by shiftkey** [comment] 2019-06-25 17:19
@Morilli thanks for the feedback!

We have a previous issue that covers this #7329 - please follow along with that.

**Comment by Morilli** [comment] 2019-06-25 17:24
I actually looked at that issue and while not entirely sure what the exact proposal in there is, it doesn't seem like the main issue there was the position of the scrollbar being incorrect, but rather the general position, or am I understanding that wrong here?

**Comment by shiftkey** [comment] 2019-06-25 17:30
@Morilli #7329 is related to the scroll position not being remembered, which is what I believe is the same root cause of the behaviour you're seeing. I'm happy to reopen this and dig into whether they are related.

**Comment by shiftkey** [comment] 2019-06-26 17:20
@Morilli I've been able to reproduce the behaviour on my Windows machine, and it's down to a few parts of our `List` implementation (that extends the `Grid` provided by `react-virtualized`).

First, on Windows we render a fake scrollbar so that it looks consistent with macOS:

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L803-L838

The `onFakeScroll` is used here to update the `scrollTop` separate to the rendering of the `Grid` itself:

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L855-L860

Second, we use a `scrollIntoRow` value to track which row should be visible in the list. How this is used in code is a bit complex: 

 - we use the `scrollIntoRow` prop to track the row that should be in focus when the list is first rendered

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L193-L194

 - we also have a `List.scrollIntoRow` field

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L240-L244

 - inside the constructor for `List`, the `List.scrollIntoRow` field is set to the first selected row if there are any selected rows

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L272-L276

 - inside `List.renderGrid` we have this code to compute what should be provided to `Grid` that ultimately controls the rendering

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L761-L766

The way I interpret this code is:

 - if `this.props.scrollToRow` is set, use that value
 - otherwise, use `this.scrollToRow`
 - reset `this.scrollIntoRow` for the next render

Third, the scroll position is managed separately to each of the previous two things, and is a prop managed externally which is passed into `Grid` in the same way:

https://github.com/desktop/desktop/blob/b3ae2c312efc6d089d3c06ecd23f037304c61b78/app/src/ui/lib/list/list.tsx#L208-L212

This is why I'm in favour of merging this issue with #7329 - I don't think one or the other can be fixed on their own, because I think the app needs to be smarter about managing this scroll position. Does that make sense @Morilli?

**Comment by Morilli** [comment] 2019-06-26 17:32
@shiftkey I don't really understand much about the technical details, but it seems that you have investigated this quite a bit, so if you're of the opinion that merging these two issues together is the best option, then I'm gonna trust you on that judgement.

**Comment by tidy-dev** [comment] 2024-09-16 20:11
Closing this in favor of https://github.com/desktop/desktop/issues/7329 because I did some testing and am not seeing the reported  immediate reposition of either the scrollbar or the repository list. This component has gone through a few iterations since this issue. However, the issue of the repo list always opening at top of the scroll still exists and can tracked in the aforementioned issue.

**Closed by tidy-dev** 2024-09-16 20:11 UTC
Labels: bug, windows, priority-3
