### ISSUE TITLE
Repository remains a GitHub repository after GitHub remote is removed

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#6330] opened 2018-12-03 03:10 UTC
## Description
GitHub Desktop keeps attempting to sync with GitHub.com for a repository that no longer has any remotes on GitHub.com.

## Version
* GitHub Desktop: 1.5.1beta0+
* Operating system: Win 10 1809

## Steps to Reproduce
1. Create a local repository
1. Publish it to GitHub
1. Remove the remote via GIT (`git remote remove origin`)
1. Delete the repository from GitHub.com
1. Refresh GitHub Desktop

## Additional Information
Desktop keeps attempting to find the repository on GitHub.com (errors in developer tools), even though it is also displaying the 'Publish this repository to GitHub' button.

![image](https://user-images.githubusercontent.com/26179051/49350812-1b561400-f676-11e8-9b3e-df2a1e93cfc8.png)

I am guessing that the isGitHubRepository property doesn't get reset easily, short of a delete and add it back operation.  This is probably a minor issue.

**Comment by tierninho** [comment] 2018-12-03 22:52
@msftrncs Thanks for the heads up! I was able to reproduce this and agree with you that is a minor issue. 

We do surface an error if the user attempts to push/pull/fetch on the removed repo, and the user always has an option to fully remove the repo from Desktop (Repo menu > Remove) if they do not want to see it anymore.

However, the constant `get` against the API may be of concern. @desktop/core any thoughts? Feel free to close this issue if we will not fix.

**Comment by outofambit** [comment] 2018-12-03 23:02
@msftrncs @tierninho agree this is a minor issue, but i think cleaning this up so we don't make `get`s that we know will fail would be great. going to mark "help wanted" in case someone wants to pick this up.

**Comment by billygriffin** [comment] 2019-11-20 20:23
Because this isn't something we've seen come up since the initial report, my expectation is that it's a very rare occurrence. I'm going to close until we see it come up again. Thanks for the report!

**Closed by billygriffin** 2019-11-20 20:23 UTC
Labels: bug, help wanted, priority-3
