### ISSUE TITLE
Authentication error when trying to clone Gists using GitHub Desktop from GitHub Enterprise Server

### ISSUE THREAD

**Issue by Nikhilthe1** [desktop/desktop#10351] opened 2020-08-07 22:22 UTC
I am trying to clone a public gist using URL of my Github Enterprise Server and I repeatedly get authentication error with retry clone dialogue box. I have tried logging out and logging back in multiple times as suggested.

I was able to clone same gist using same credentials using GitBash.

### GitHub Desktop Version 2.5.0
Operating System: Windows Server 2016

### Steps to reproduce the behavior

1. Sign in GitHub Desktop Enterprise Server in File -> Options
2. Click on File -> Clone Repository
3. Click on URL tab.
4. Enter URL for Gist on GitHub Enterprise Server and local path of empty directory.
5. Get authentication error.

### Expected behavior

Successful cloning of Gist.
Note: I am able to clone repositories from GitHub Enterprise Server using same credentials.

### Actual behavior
Authentication Failed message.

### Logs
2020-08-07T22:15:08.327Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://gist.github-dev.[removed intentionally]/[my id]/9b85b8c9cf1fa82a2c0152e0df0caac3'
2020-08-07T22:15:09.882Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://gist.github-dev.[removed intentionally]/[my id]/9b85b8c9cf1fa82a2c0152e0df0caac3 H:\9b85b8c9cf1fa82a2c0152e0df0caac3 (took 1.542s)
2020-08-07T22:15:09.883Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://gist.github-dev.[removed intentionally]/[my id]/9b85b8c9cf1fa82a2c0152e0df0caac3 H:\9b85b8c9cf1fa82a2c0152e0df0caac3` exited with an unexpected code: 128.
stderr:
Cloning into 'H:\9b85b8c9cf1fa82a2c0152e0df0caac3'...
remote: Anonymous access denied
fatal: Authentication failed for 'https://gist.github-dev.esa.dshs.wa.lcl/dharmns/9b85b8c9cf1fa82a2c0152e0df0caac3/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

### Additional context

I have tried changing folder name for local path. Also tried using save button on GitHub browser.

**Comment by tierninho** [comment] 2020-08-08 00:20
@Nikhilthe1 thanks for the report. This is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a git push to push your changes.

See #2973 for more information about some of the known issues with using Gists in GitHub Desktop. I am going to reference this issue in #2973 and close it out for the time being.

**Closed by tierninho** 2020-08-08 00:20 UTC

**Comment by Fralleee** [comment] 2021-09-23 14:17
Why are these issues closed when there isn't a fix?

Also using the command line as a workaround is something you might suggest when the issue is relatively new, not three years old.

**Comment by PatchaIT** [comment] 2024-12-23 16:43
I just tried this today, and still same issue.
