### ISSUE TITLE
JetBrains PhpStorm not showing in the external editor dropdown menu

### ISSUE THREAD

**Issue by rinodrummer** [desktop/desktop#11852] opened 2021-03-24 08:22 UTC
### Describe the bug

I've recently installed GitHub Desktop and found that in the **Integrations** tab of the **Options**, I  can't set _JetBrains PhpStorm_ as default external editor because it doesn't appear in the list (even if it's listed on the [documentation](https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/configuring-a-default-editor#supported-editors) as supported editor).

### Version & OS

- GitHub Desktop Version 2.6.6;
- Windows 10 (version 10.0.18363);

### Steps to reproduce the behavior

1. Go to 'File';
2. Click on 'Options';
3. Select 'Integrations';
4. Click on the 'External editor' dropdown menu;
5. There should be a full list of my installed IDEs (if supported), including _JetBrains PhpStorm_ (which is not), but I can only select _Notepad++_ because is the only shown.

### Expected behavior

I would like to use my favourite IDE (_JetBrains PhpStorm_, which is a supported IDE as stated in the documentation) as external editor.

### Actual behavior

I can't select _JetBrains PhpStorm_ as external editor because isn't shown in the dropdown menu.

### Screenshots

[Screenshot showing the issue](https://i.imgur.com/MyxcbP0.png)

### Additional context

I've installed PhpStorm without the JetBrains Toolbox but and is installed on C:\ as the O.S., while GitHub Desktop is installed on D:\ as Notepad++.

**Comment by steveward** [comment] 2021-03-24 17:47
Thanks for the report @rinodrummer. I was able to reproduce this as well on Windows. On macOS the integration still worked. I tested this out with PHPStorm and WebStorm, so it seems this is a broader issue with JetBrains IDEs.

**Comment by rinodrummer** [comment] 2021-03-25 05:53
@steveward Do I need to report the bug to JetBrains too or you are handling the issue by yourself?

**Comment by steveward** [comment] 2021-03-25 15:06
@rinodrummer if you'd like to reach out to JetBrains it would be helpful to know if anything has changed on their end that may have broken this. Thanks!

**Comment by rinodrummer** [comment] 2021-03-26 09:09
@steveward I created an [issue on YouTrack](https://youtrack.jetbrains.com/issue/WI-59454).

I invite you to check [this comment](https://youtrack.jetbrains.com/issue/WI-59454#focus=Comments-27-4792768.0-0).

As stated on there, the actual detection process may be a bit off because needs manual adjustments on every PhpStorm and WebStorm update.

I think that, if possible, it should at least check all the register keys which _contains_ the "PhpStorm" and "WebStorm" string in their name, instead of the full version name.

**Comment by steveward** [comment] 2021-03-26 12:48
@rinodrummer thanks, that aligns with what was mentioned in https://github.com/desktop/desktop/issues/9453#issue-593766796 by @van800, which is what I assumed was the issue.

**Comment by Seb33300** [comment] 2021-03-31 05:38
There is no way to check if a key starting by `PhpStorm` exists [instead of checking for specific version numbers](https://github.com/desktop/desktop/blob/0fec3adca67e890e917ee3ba70c9dd394fc24493/app/src/lib/editors/win32.ts#L240)?

**Comment by ghost** [comment] 2021-04-13 03:31
I am also having this issue with Webstorm.

**Comment by mcquiggd** [comment] 2021-06-03 08:08
For info, JetBrains Rider is also not appearing in the list of available editors.

Only Notepad++ and VS Code are displayed as options.

**Comment by say25** [comment] 2021-11-09 17:41
I'm ~90% confident we re-wrote how JetBrains tools are handled in GitHub Desktop after the last comment here. Closing

**Closed as completed by say25** 2021-11-09 17:41 UTC
Labels: bug, priority-3

**Comment by powpppp** [comment] 2021-11-09 17:42
0x9ef1918a9bee17054b35108bd3e2665e2af1bb1b

**Comment by Justin-Frazier** [comment] 2021-11-09 17:53
It's always that nagging 10% though.
![image](https://user-images.githubusercontent.com/68287649/140977928-4d329193-a37f-4f90-ad39-5fb467b61366.png)

**Comment by Justin-Frazier** [comment] 2021-11-09 17:58
@say25 Would you please re-open this issue until it is fixed?

**Comment by say25** [comment] 2021-11-09 19:02
This seems like a duplicate of https://github.com/desktop/desktop/issues/13257 to me. I'd just hate for this to be double tracked

**Comment by milan-sahana** [comment] 2024-03-22 02:44
same issue in my Windows 11 with PhpStorm 2323.3.6

**Comment by yuvraj-timalsina** [comment] 2024-03-27 12:13
Same issue in my Fedora 39 PhpStorm 2023.3.6

**Comment by milan-sahana** [comment] 2024-03-27 12:27
Now I have installed PhpStorm 2023.3.5 its working fine for me..
________________________________
