### ISSUE TITLE
Add Support for Windows Terminal

### ISSUE THREAD

**Issue by Elderry** [desktop/desktop#7854] opened 2019-06-24 01:41 UTC
**Please describe the problem you think should be solved**
Since [Window Terminal](https://devblogs.microsoft.com/commandline/windows-terminal-microsoft-store-preview-release/) is in shop now, it would be nice to have it select-able in github desktop.

**Comment by Mojo222** [comment] 2019-06-25 14:51
Duplicate of #

**Comment by AndreiMaga** [comment] 2019-07-15 15:10
Unfortunately at the moment this is not possible.
As stated in [#607](https://github.com/microsoft/terminal/issues/607) the terminal dev team is working on the command line options. So at the moment this feature is not possible but will be in the future.

Microsoft is planning to make available the option to set "Default Terminal". See [#493](https://github.com/microsoft/terminal/issues/492) . So everything could be solved by opening the "default terminal".

Also for someone that wants to pick this issue up, ```HKEY_LOCAL_MACHINE\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\PackageRepository\Packages\Microsoft.WindowsTerminal_xxx``` is the reg you're looking for.

Hope this gets fixed soon.

**Comment by xPaw** [comment] 2019-10-13 08:44
As far as I understand it, there's a "wt.exe" shortcut/symlink to the windows app that can be checked for in path?

If I do `wt` in run or cmd, it launches the terminal.

**Comment by Biswa96** [comment] 2019-11-13 20:44
Registry may not be the correct way to find a UWP package. Try with [`FindPackagesByPackageFamily`][1] Win32 API. As an example,

    FindPackagesByPackageFamily(L"Microsoft.WindowsTerminal__cw5n1h2txyewy", ...);


[1]: https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-findpackagesbypackagefamily

**Comment by Biswa96** [comment] 2019-11-13 20:44
Registry may not be the correct way to find a UWP package. Try with [`FindPackagesByPackageFamily`][1] Win32 API. As an example,

    FindPackagesByPackageFamily(L"Microsoft.WindowsTerminal", ...);

[1]: https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-findpackagesbypackagefamily

**Comment by Biswa96** [comment] 2019-11-13 21:07
Registry may not be the correct way to find a UWP package. Try with [`FindPackagesByPackageFamily`][1] Win32 API. As an example,

    FindPackagesByPackageFamily(L"Microsoft.WindowsTerminal_8wekyb3d8bbwe", ...);

Or with Powershell command: `Get-AppxPackage *WindowsTerminal*`

<details><summary>Here is the output of that command (click to expand)</summary>

```
Name              : Microsoft.WindowsTerminal
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 0.6.2951.0
PackageFullName   : Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_0.6.2951.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsTerminal_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok

```
</details>


[1]: https://docs.microsoft.com/en-us/windows/win32/api/appmodel/nf-appmodel-findpackagesbypackagefamily

**Comment by billygriffin** [comment] 2019-11-21 15:45
Looks like maybe there are limitations to being able to do this currently. If someone wants to respond when there's a more defined path forward, especially if you're willing to make a PR to add support for this integration, we're happy to reopen at that point. Thanks!

**Comment by outofambit** [comment] 2020-02-04 19:53
#607 was just closed a week ago, so this could be revisited when that is released.

**Comment by AndreiMaga** [comment] 2020-02-04 20:02
#607 from windows terminal(if you click on it, it should send you to the right issue) . I guess it was my mistake not to put the name of the repo in front of the issue link.

**Comment by AndreiMaga** [comment] 2020-02-04 20:06
My bad, did not check that 607 from terminal is finished. Sorry. Can you open it and assign it to me, I'll work on it in the next few days. Thanks

**Comment by Prajwal-Koirala** [comment] 2020-02-17 17:22
A+

**Closed** 2020-03-03 18:51 UTC
Labels: enhancement, help wanted, integrations, windows
