### ISSUE TITLE
Publish repository instead of push

### ISSUE THREAD

**Issue by mcDandy** [desktop/desktop#6054] opened 2018-10-31 14:02 UTC
## Version

* GitHub Desktop: 1.4.3

* Operating system: Windows 10 version 1803 build 17143.345

## Steps to Reproduce

make a commit
sometimes shows Publish repository
### Expected Behavior

Button says push to origin
### Actual Behavior

screen shows Publish repository altouh allready on githubh

## Additional Information

Not intended
![obrazek](https://user-images.githubusercontent.com/18588943/47792923-5a164880-dd1d-11e8-8b5d-284e3adf2f4d.png)
Intended
![obrazek](https://user-images.githubusercontent.com/18588943/47793309-4a4b3400-dd1e-11e8-8d5a-52e28e29b9e4.png)

### Logs

[2018-10-31.desktop.production.log](https://github.com/desktop/desktop/files/2534694/2018-10-31.desktop.production.log)

**Comment by iAmWillShepherd** [comment] 2018-10-31 20:12
Could you verify the email address in your git configuration matches the one on Github.com?

**Comment by mcDandy** [comment] 2018-10-31 20:18
Yes

**Comment by steveward** [comment] 2018-10-31 20:52
This feels similar to https://github.com/desktop/desktop/issues/6007. @mcDandy is your repository also showing the in the `Other` section of the repository list?

Also, if you go to the menu and select `Repository` > `Repository Settings` > `Remote` does the `Primary remote` URL point to the correct repository on GitHub?

**Comment by mcDandy** [comment] 2018-11-01 06:38
Will look after school

st 31. říj 2018 21:52 odesílatel Steve Ward <notifications@github.com>
napsal:

**Comment by mcDandy** [comment] 2018-11-01 17:30
It points to correct url. Now behaving as expacted. Where is "Other" section?

**Comment by steveward** [comment] 2018-11-02 00:06
The `Other` section of the repository list is where non-GitHub repositories are categorized. The two other reports of this issue I've seen (#5936 and #6007) have had the repositories appearing under the `Other` category as well as continuing to throw the message that the repository needs to be published. Since this seems to be a duplicate of those issues I am going to close this issue out. I'm continuing to work on trying to reproduce this, but @mcDandy please let me know if you run into this bug again.

**Closed by steveward** 2018-11-02 00:06 UTC
Labels: more-information-needed

**Comment by danyj** [comment] 2019-01-24 21:09
I have the same issue now.  Repo history

1. Had public organisation repo
2. Changed owner made repo private
3. Deleted the repo from local and live git
4. Created repo with same name for the org again

now I cannot push http://prntscr.com/mbr79l

I asked Git for support and were advised to Remove all of the files in %APPDATA%\GitHub Desktop\
and restart and see if that worked. 

I have well over 30 repos I am working on, it is just pain to browse for all of them again. 

Also tried signing out , closing app , signing in. 
Did not help.

**Comment by danyj** [comment] 2019-01-24 21:10
And yes , when cloning it also places the clone under `Other` . The repo is live, published  and public on Git

**Comment by miguelk5** [comment] 2019-03-01 21:17
Why nobody fixed this yet ? It do not have sense

**Comment by miguelk5** [comment] 2019-03-01 21:19
Please disable this project to public until you finish it. Why I see publish repository ? If i created it by command line already is public ... Please close this project.
