### ISSUE TITLE
Rename repository (only for work in app)

### ISSUE THREAD

**Issue by Kattnienika** [desktop/desktop#9466] opened 2020-04-07 16:49 UTC
Could I add the rename repository feature in the application? Renaming would only be in the app, not on github.com.

The function would contribute to better organization in repositories.

**Comment by steveward** [comment] 2020-04-07 18:15
Thanks for contributing @Kattnienika. I'm going to close this as a duplicate of https://github.com/desktop/desktop/issues/7856 -- please follow along there for updates about this.

**Closed by steveward** 2020-04-07 18:15 UTC
