### ISSUE TITLE
Issue #5865 was NOT Fixed NOR verified (just blindly closed after refactoring)

### ISSUE THREAD

**Issue by jzabroski** [desktop/desktop#8995] opened 2020-01-28 20:07 UTC
### Describe the bug

https://github.com/desktop/desktop/issues/5865

### Version & OS

GitHub Desktop version 2.2.4
Windows 10 Pro

### Steps to reproduce the behavior

1. Clone toddams/RazorLight repository
2. Click on master branch, then click on PRs
3. Says 0 PRs
4. GitHub.com/toddams/RazorLight/pulls/ shows 3 PRs

### Expected behavior

1. Don't close issues without verifying something was actually fixed? :)
2. Re-open #5865 and actually fix the UI so PRs are pulled down
3. Consider adding useful logging - 

### Actual behavior

Here is my log.

```
2020-01-28T19:28:47.037Z - info: [ui] [AppStore] loading 17 repositories from store
2020-01-28T19:28:47.038Z - info: [ui] [AppStore] found account: jzabroski (John Zabroski)
2020-01-28T19:28:47.327Z - info: [ui] launching: 2.2.4 (Windows 10.0.17763)
2020-01-28T19:28:47.327Z - info: [ui] execPath: 'C:\Users\john.zabroski\AppData\Local\GitHubDesktop\app-2.2.4\GitHubDesktop.exe'
2020-01-28T19:28:47.836Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:28:51.952Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:28:51.974Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:28:52.212Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:29:14.966Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: RazorLight - jzabroski (has token)
2020-01-28T19:29:15.833Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:29:37.186Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: RazorLight - jzabroski (has token)
2020-01-28T19:29:37.934Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:30:49.130Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EntityFrameworkMappingTablePerHierarchy - jzabroski (has token)
2020-01-28T19:30:49.946Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:30:54.815Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:30:54.815Z - info: [ui] Background fetch for 17 repositories took 7.712sec
2020-01-28T19:45:25.077Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:45:33.812Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: RazorLight - jzabroski (has token)
2020-01-28T19:45:34.681Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:45:55.940Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: EntityFrameworkMappingTablePerHierarchy - jzabroski (has token)
2020-01-28T19:45:56.795Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:45:59.459Z - info: [ui] Current tutorial step is NotApplicable
2020-01-28T19:45:59.460Z - info: [ui] Background fetch for 17 repositories took 4.641sec
2020-01-28T19:46:06.584Z - info: [ui] Current tutorial step is NotApplicable
```

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Logs are useless, but I uploaded them anyway.  Attached is the Fiddler v4 screenshot showing that it seems the Pull Requests refresh button is _hitting the wrong endpoint_, followed by the correct endpoint _but sending a cache header_.

![image](https://user-images.githubusercontent.com/447485/73300311-c876de80-41de-11ea-844e-ac4809b34507.png)

### Additional context

I'm not an expert in GitHub but, as a paying customer, it looks really bad to push code without testing it... https://developer.github.com/v3/pulls/#list-pull-requests
Feels like the plumber showed up to my house and left with my sink.

Why are you sending a cache header when I explicitly click Refresh... 

![image](https://user-images.githubusercontent.com/447485/73300859-b6e20680-41df-11ea-98b7-a370737be238.png)

**Comment by lee-dohm** [comment] 2020-01-28 20:52
Thanks for letting us know about your negative experience with Desktop. We're investigating right now. We'll comment further on the original issue. Since this is a duplicate of that original issue, I'm closing this one.

Additionally, @jzabroski, numerous parts of your issue are considered to be a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as they are insulting or derogatory. You may consider this an official warning.

**Closed by lee-dohm** 2020-01-28 20:52 UTC
