### ISSUE TITLE
The Branches List is empty

### ISSUE THREAD

**Issue by losiesta** [desktop/desktop#3173] opened 2017-10-27 04:47 UTC
### Description

I created some branches,but none of these show in the Branches List.In the Merge Branch,there shows
all the branches.

### Version

**GitHub Desktop version:** 1.0.5

**OS version:** Windows 10

### Steps to Reproduce

1. create some branches.
1. try to switch to other branch in the Branches List

**Expected behavior:**  The Branches List lists none.

**Actual behavior:** The Branches List lists all branches.

**Reproduces how often:** every time.

#### Additional Information
it works well when i use old vision.

**Comment by sebastiano-guerriero** [comment] 2017-10-27 07:28
Same issue on ver 1.0.5 for Mac (OS X 10.12.6). The list of branches is not visible, but the filter is working fine.

**Comment by filipsobol** [comment] 2017-10-27 07:48
I have the same issue. @losiesta made a mistake in bug report, should be:

**Actual behavior:** The Branches List is empty 
**Expected behavior:** The Branches List lists all branches.

**Comment by tierninho** [comment] 2017-10-27 08:03
Closing as duplicate of #3169 

Please track progress there.

**Closed by tierninho** 2017-10-27 08:03 UTC
