### ISSUE TITLE
Sign-in Button Doesn't work

### ISSUE THREAD

**Issue by NU11PT4** [desktop/desktop#16697] opened 2023-05-15 13:35 UTC
### The problem

Hello Developers,

I have compiled the GitHub desktop for Linux mint and when I opened the program for the first time, I tried to connect to my GitHub account, clicked the blue button and it redirected me to authorizing page. when all the pairings are done, it prompted me to open GitHub-desktop and it will not open. The anchor links in the page also didn't help me to do so.

Thanks and Best regards.

### Release version

Version 3.2.3 (x64)

### Operating system

Linux Mint 21.1 Cinnamon 5.6.8 Kernel 5.15.0-71-generic

**Comment by steveward** [comment] 2023-05-15 13:44
Thanks for the issue @NU11PT4. At this time we do not provide support for the Linux version of GitHub Desktop, since it is an unofficial fork. There are some known authentication issues being tracked in the fork's issue tracker: https://github.com/shiftkey/desktop/issues. I would recommend looking there to see if there is an existing issue. I'm going to close this out.

**Closed as completed by steveward** 2023-05-15 13:44 UTC

**Comment by tidy-dev** [comment] 2023-05-15 13:47
As this could be linux related, I would refer you what @steveward commented. I only add that this appears to be a duplicate of https://github.com/desktop/desktop/issues/11410.. which unfortunately no-one on the team has been able to reproduce but maybe you will find some of the comments helpful.

**Comment by NU11PT4** [comment] 2023-05-15 14:37
> Thanks for the issue @NU11PT4. At this time we do not provide support for the Linux version of GitHub Desktop, since it is an unofficial fork. There are some known authentication issues being tracked in the fork's issue tracker: https://github.com/shiftkey/desktop/issues. I would recommend looking there to see if there is an existing issue. I'm going to close this out.

Sorry but I am using the official repository, not the @shiftkey's forked repository. I have build the project using information in "package.json"/section:"scripts". Since there is no official ".desktop" for the project, I wrote a one manually and pasted it in "/usr/share/applications" folder.

Can it be the cause of problem?

here is the script:
`[Desktop Entry]
Name=Github Desktop
Type=Application
Terminal=false
Exec=/opt/desktop-linux-x64/desktop
Icon=/opt/desktop-linux-x64/resources/app/static/icon-logo.png`

**Comment by sasm23014** [comment] 2024-02-19 19:26
I think it requires to run Github Desktop as a sudoer. I have the same issue when I am logged in as a Standard user, but everything seems to work fine when I am logged in as an Administrator. The problem is that I want to use the Github Desktop under the Standard user and I have not found a solution yet.
