### ISSUE TITLE
GitHub desktop constantly crashing

### ISSUE THREAD

**Issue by jiveshsg** [desktop/desktop#3255] opened 2017-11-07 16:14 UTC
Error: Mode github-diff-syntax failed to advance stream.
    at at (app/node_modules/codemirror/lib/codemirror.js:1639:1)
    at dt (app/node_modules/codemirror/lib/codemirror.js:1693:1)
    at tt (app/node_modules/codemirror/lib/codemirror.js:1539:1)
    at nt (app/node_modules/codemirror/lib/codemirror.js:1584:22)
    at ft (app/node_modules/codemirror/lib/codemirror.js:1830:1)
    at At (app/node_modules/codemirror/lib/codemirror.js:2208:1)
    at Ft (app/node_modules/codemirror/lib/codemirror.js:2289:1)
    at Bo (app/node_modules/codemirror/lib/codemirror.js:4306:1)
    at Fo (app/node_modules/codemirror/lib/codemirror.js:4213:1)
    at zo (app/node_modules/codemirror/lib/codemirror.js:4269:1)

Version: 1.0.7
OS: Mac OS 10.13.1

**Comment by j-f1** [comment] 2017-11-07 16:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2678. Please follow that issue for further updates.

**Closed** 2017-11-07 16:50 UTC
