### ISSUE TITLE
Github Desktop Crashing with notepad++ open on selecting open with notepad++

### ISSUE THREAD

**Issue by Kherae** [desktop/desktop#9614] opened 2020-04-24 02:09 UTC
### Describe the bug
When I click "open with notepad++" when notepad++ is already open (as admin), github desktop (when not run as admin) crashes.

### Version & OS
Desktop v 2.4.2
Notepad++ v7.8.5
OS: Windows 10.0.18363

### Steps to reproduce the behavior
click "open in notepad++" on any modified file on the list when notepad++ is already open as admin, without the desktop client run as admin. or when dealing with merge conflicts

### Expected behavior
open with notepad++ functions the same as open with default editor: it just opens the files.

### Actual behavior
github desktop crashes:
Error: spawn C:\Program Files (x86)\Notepad++\notepad++.exe EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Version: 2.4.2
OS: Windows 10.0.18363

### Additional context
I did use a registry override for opening npp with multiple files when running as admin, which might be part of why it does this. also, NPP is my default editor and I always run it as admin. github desktop was never run as admin prior to testing for whether that was the issue. (seems it was)

It'd be nice to just tell github desktop to NOT list notepad++ or, for that matter, use it as the default option when merge confligs and such show. I'd rather just set "open with default" as default

**Comment by tierninho** [comment] 2020-04-25 00:15
@Kherae Thank you for reporting this issue and apologies for the troubles.

`EACCESS` is a generic permissions issue reported by Node while it tries to launch the file.

I tried reproducing your issue but no luck so far. Desktop opened the file successfully with roughly the same OS setup as you. Note, I did not attempt to use a registry override though, as I am not sure what steps are needed for this.

When you say "Desktop crashes", do you mean the whole app crashes or an error is surfaced that blocks you for completing the task? Curious if have you tried without the registry override, if possible?

> It'd be nice to just tell github desktop to NOT list notepad++ or, for that matter, use it as the default option when merge confligs and such show. I'd rather just set "open with default" as default

You can change from NPP to any editor (as long as its downloaded) in Desktop > File > Options > Integrations > External editor. This will set the default to another editor. As for the "open with default" option, the applications shown as determined by the Windows operating system. For example, if it's a photo, Windows will show apps that are for photos.

Let us know how it goes please.

**Comment by Kherae** [comment] 2020-04-25 00:48
I meant that "github desktop" crashes, with that error popup and a window with a button to "exit and restart". also, I can't set the default to another editor, as only NPP is available. what I mean for "open with default"  I meant the option itself in github desktop; that of "Open with default editor". When merge conflicts happen, it defaults to choosing the external editor (notepad++), rather than that option: "Open with default program". The problem I am having is that, while NPP is my default editor, choosing "open with notepad++" crashes, and "open with default doesn't".

As for the registry edit, I can't fully remember the details, other than that it involved deleting the provided 'open with notepad++' option under `HKEY_CLASSES_ROOT/*/shell` (somewhere in there) and putting in the key EditWithNotepad. default string was `Edit with &N++`, subkey Command with path to NPP as default string. probably not very helpful

https://superuser.com/questions/212914/shellexecute-failed-2-error-for-notepad-on-windows-7-64bit/1269546#1269546 this. it was the first option I used I think.

also, to make sure it was clear: you used "Run as admin" on notepad++, and didn't with github desktop, right? have a hunch that it might be specifically related to -how- it is run. might be that, for whatever reason, my operating system is not allowing a non-elevated process to open stuff in an elevated process. I know windows 10 is finicky about that kind of stuff

**Comment by tierninho** [comment] 2020-04-28 00:53
Thank you for the added details.

> I meant that "github desktop" crashes, with that error popup and a window with a button to "exit and restart".

If you can grab a screenshot of that, it would be much appreciated.

> also, I can't set the default to another editor, as only NPP is available. what I mean for "open with default" I meant the option itself in github desktop; that of "Open with default editor". When merge conflicts happen, it defaults to choosing the external editor (notepad++), rather than that option: "Open with default program". The problem I am having is that, while NPP is my default editor, choosing "open with notepad++" crashes, and "open with default doesn't".

Understand, thanks for sharing. So if you want to switch your editor, like to Atom for example, you have to download another editor and Desktop will recognize that editor and allow you to change it. Otherwise, NPP will be the only option. With the "Open in Default" option, that is not managed by Desktop, but by Windows. 

> you used "Run as admin" on notepad++, and didn't with github desktop, right?

Yes, that is what I tried. Any chance that NPP is working if you do not run as admin? If it is still broken, we can rule out the permissions issue for now.

> have a hunch that it might be specifically related to -how- it is run. might be that, for whatever reason, my operating system is not allowing a non-elevated process to open stuff in an elevated process. I know windows 10 is finicky about that kind of stuff

I think you may be right on this.

**Comment by Kherae** [comment] 2020-04-28 02:40
![Untitled](https://user-images.githubusercontent.com/25236459/80441004-c0ead280-88be-11ea-93da-8fa9bfdd3b2e.png) (think I did this right?)

regarding "Open with Default", I feel that should be an option under "External Editors"

it works if neither are run as admin, but that kinda goes against why I set NPP to run as admin (permissions issues when trying to save files in certain locations, IE hosts file).

**Comment by tierninho** [comment] 2020-04-28 20:01
Thank you for the screenshot, that is exactly it. 

> regarding "Open with Default", I feel that should be an option under "External Editors"

Unfortunately, we cannot control the applications associated with "Open with Default" as that is controlled by the operating environment.

> it works if neither are run as admin, but that kinda goes against why I set NPP to run as admin (permissions issues when trying to save files in certain locations, IE hosts file).

Gotcha, thanks for clarifying. I will try again to reproduce the issue.

**Comment by Kherae** [comment] 2020-04-28 23:22
I am aware that github desktop cannot control what 'open with default' does, that is not what I am asking for. what I am asking for is that, within the "External Editors" selection box, "open with default" should be an option that is always there in addition to whatever else it populates it with (IE, NPP)

**Comment by tierninho** [comment] 2020-04-29 00:51
Ah, gotcha. Here is a mock-up of that request.

![Screen Shot 2020-04-28 at 2 50 30 PM](https://user-images.githubusercontent.com/14828183/80551610-b896a400-895f-11ea-99b2-6bbe5ff2de10.png)

**Comment by Kherae** [comment] 2020-04-29 00:53
yes, like that exactly

**Comment by tierninho** [comment] 2020-05-21 01:17
cc @desktop/design for thoughts on whether adding the Open in Default option as an External Editor makes sense. 

👀 @billygriffin as well

**Comment by niik** [comment] 2020-10-20 14:31
Hi @Kherae, thanks for your suggestion. We've chosen to explicitly list editors instead of providing a more generic "Open in default" option so that users don't accidentally end up executing arbitrary code when they assumed we would launch an editor. Imagine a user asking GitHub Desktop to 'Open in Editor' on a `.exe` or `.bat` file for example.

See https://github.com/desktop/desktop/issues/4753#issuecomment-392394769 and https://github.com/desktop/desktop/issues/5411 for some of our previous thinking around this.

As the specific issue with notepad++ seems to be environment specific I'm going to close this issue and I hope you've been able to find a workaround or a different editor that works for you.

**Closed by niik** 2020-10-20 14:31 UTC

**Comment by Kherae** [comment] 2020-10-21 17:09
understandable. just hope it addresses the permissions issue as well in some way...

**Comment by KeithGriffiths2002** [comment] 2022-02-15 10:26
If you are opening notepad++ as an administrator, you need to do the same for GitHub
Locate github.exe and change it to open as admin. or don't open notepad++ as admin. 
Either way the error should disappear.
