### ISSUE TITLE
Branches button is disabled while on an unborn branch

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#2121] opened 2017-06-26 17:29 UTC
If you create a second branch, and then remove the initial commit before publishing, you cannot go back to the master branch. The UI of the commit button says `master` while the branch is locked on X. 

v0.6.2, OSX 10.11.5

Reproduce:
- File > New Repo, follow steps but don't publish
- Create new branch, switch to new branch
- Undo initial commit

Expected result: User can switch branches back to `master`, and `commit button` and branch are matching.

<img width="739" alt="screen shot 2017-06-26 at 1 20 21 pm" src="https://user-images.githubusercontent.com/14828183/27551921-5cd9a892-5a73-11e7-8674-80143e022a1f.png">

**Comment by OnclickSell** [comment] 2017-12-15 20:48
I think it is because the user is not identified by the GitHub client. run these commands inside your current repository if worked:  git config --global user.email "you@example.com" 
git config --global user.name "Username"

**Comment by shiftkey** [comment] 2018-02-28 03:02
I can reproduce this in 1.1.0, and it's related to the undo commit step at the very end. Here's what Git reports after that:

```
~/Documents/GitHub/doooot/ git status
On branch doot

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.gitattributes
	.gitignore
	LICENSE

nothing added to commit but untracked files present (use "git add" to track)
```

And the branch list contains `master` only:

```
~/Documents/GitHub/doooot/ git branch
  master
```

The reason the UI is ending up in this state is "No commits yet" is what we consider an unborn repository, and `canOpen` is set to false in here:

https://github.com/desktop/desktop/blob/a0172aaa541c0118162987d15dd9199ff1d6e680/app/src/ui/toolbar/branch-dropdown.tsx#L104-L107

In theory, we do a more relaxed check of this:

```diff
diff --git a/app/src/ui/toolbar/branch-dropdown.tsx b/app/src/ui/toolbar/branch-dropdown.tsx
index 5238d4091..3c96169f4 100644
--- a/app/src/ui/toolbar/branch-dropdown.tsx
+++ b/app/src/ui/toolbar/branch-dropdown.tsx
@@ -104,7 +104,7 @@ export class BranchDropdown extends React.Component<IBranchDropdownProps> {
     } else if (tip.kind === TipState.Unborn) {
       title = tip.ref
       tooltip = `Current branch is ${tip.ref}`
-      canOpen = false
+      canOpen = branchesState.allBranches.length > 0
     } else if (tip.kind === TipState.Detached) {
       title = `On ${tip.currentSha.substr(0, 7)}`
       tooltip = 'Currently on a detached HEAD'
```

But then this uncovers a whole different problem:

<img width="583" alt="screen shot 2018-02-28 at 1 55 27 pm" src="https://user-images.githubusercontent.com/359239/36767559-1a228756-1c8f-11e8-841d-f0e2f8ea6786.png">

Maybe that message is a bit unclear, but this feels very niche in terms of audience it'll affect (and new repositories are easy to create anyway).

@tierninho any objection to doing just that fix above? This won't fix the issue where you undo `master` (rather than switching branches) because Git doesn't consider `master` to be a valid branch at that point.

**Comment by agisilaos** [comment] 2018-03-13 21:49
Just an FYI, currently started working on it and openen a PR #4236 ⭐️

**Comment by tierninho** [comment] 2018-03-14 20:41
@shiftkey just spotted your question. No objection!

**Closed** 2018-03-15 02:10 UTC
Labels: bug, help wanted
