### ISSUE TITLE
Fetch with ssh failed when succeed with bash

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12786] opened 2021-08-17 13:01 UTC
### Describe the bug
Unable to fetch origin with  "Authentication failed. Some common reasons include:“

### Version & OS

Win10 pro 19041.1165
Github desktop Ver 2.9.0 (x64)

### Steps to reproduce the behavior

See actual behaviour.

### Expected behavior

Fetch just like git bash.

### Actual behavior

Poped windows when fetch.

Bash behaviour:
```
$ which ssh-agent
/usr/bin/ssh-agent
(base)

$ git -c credential.helper= fetch --progress --prune origin -v
 = [up to date]      main              -> origin/main
 = [up to date]      Modelling         -> origin/Modelling
 = [up to date]      analytic-solution -> origin/analytic-solution
(base)
```

git config about ssh: 

```
[core]
	sshCommand = "ssh"
```
(ssh.exe is in `C:\Program Files\Git\usr\bin`)

ssh config:

```
Host uni.github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/uni
```

github repo remote:
`git@uni.github.com:my_user_name/my_repo_name.git`

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

2021-08-17T12:45:23.384Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 22 repositories took 14.7s of which 0.0s paused, total 14.7s
2021-08-17T12:47:56.686Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.640s)
2021-08-17T12:47:56.686Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by steveward** [comment] 2021-08-17 18:33
Thanks for the issue @Clevin4958. GitHub Desktop doesn't have great SSH support, but this is actually something that we are actively working on. We just released a beta version with SSH improvements -- would you mind testing it out to see if that gets things working for you? You can find the beta [here](https://github.com/desktop/desktop#beta-channel).

**Comment by ghost** [comment] 2021-08-17 23:39
> Thanks for the issue @Clevin4958. GitHub Desktop doesn't have great SSH support, but this is actually something that we are actively working on. We just released a beta version with SSH improvements -- would you mind testing it out to see if that gets things working for you? You can find the beta [here](https://github.com/desktop/desktop#beta-channel).

The beta worked via dialogue. The host is detected (I think). Out of curiosity, is it based on its own instance of ssh-agent? It doesn't detect existing ones in background

**Comment by Clevin49958** [comment] 2021-08-18 02:32
Update: it's working on my PC now. but failed when I try to reproduce it on my laptop

Version:
win10 home 19042.1165
**Version 2.9.1-beta4 (x64)**

Bash is working perfectly 
`$ ssh -T git@uni.github.com
Hi Clevin4958! You've successfully authenticated, but GitHub does not provide shell access.
(base)`

**Setting:**
![image](https://user-images.githubusercontent.com/30225955/129826758-d18b3366-bed8-49c6-8860-d9b94cad5535.png)
with or without system openSSH option I get the same result

git and ssh config is same as above but git is installed in D drive, while still using ssh from git than from system32

**log:**

2021-08-18T02:19:16.017Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: ES263P1Private - Clevin4958 (has token)
2021-08-18T02:19:18.224Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 2.153s)
2021-08-18T02:19:18.224Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by steveward** [comment] 2021-08-18 19:26
@Clevin49958 any chance you mistyped your passphrase? There was a bug that [is now fixed](https://github.com/desktop/desktop/pull/12800) where the app would store an invalid passphrase.

**Comment by Srndo** [comment] 2021-08-18 19:40
> @Clevin49958 any chance you mistyped your passphrase? There was a bug that [is now fixed](https://github.com/desktop/desktop/pull/12800) where the app would store an invalid passphrase.

I have same error as @Clevin49958 on macOS BigSur. I dont think this error is connect with misstyping passphrase. I tried more times to follow multiple guides as well as [this](https://docs.github.com/en/github/authenticating-to-github/troubleshooting-ssh/error-permission-denied-publickey), but nothing worked. I was force to change communication via https. 

I am pretty sure that my keys is set properly because using version control over ssh in XCode with same repository working fine as well as with terminal.

**Comment by sergiou87** [comment] 2021-08-23 10:37
@Srndo are you using the latest beta? (2.9.1-beta7)

> Out of curiosity, is it based on its own instance of ssh-agent? It doesn't detect existing ones in background

@Clevin49958 **if you are using the system OpenSSH**, it should pick whatever you have running in the background. At least that's how it worked for me. Other than that, Desktop will try to remember passwords in the Windows Credential Manager (or the Keychain on Windows) if no ssh-agent was used by git/ssh.

**Comment by ghost** [comment] 2021-08-27 14:14
Is it possible to retrieve ssh passphrase if we forgot it but it is saved in GitHub desktop?

**Comment by sergiou87** [comment] 2021-08-30 09:25
@Clevin4958 yes! You just have to look for an entry called `GitHub Desktop - SSH key passphrases` in the Keychain (on macOS) or in the Windows Credential Manager (on Windows). I hope that helps 😄

**Comment by steveward** [comment] 2021-09-08 14:08
@Clevin4958 based on your reply it sounds like you were able to get things working, so I am going to close this out. Let us know if you are still having issues.

**Closed as completed by steveward** 2021-09-08 14:08 UTC
