### ISSUE TITLE
Github Desktop not logging in

### ISSUE THREAD

**Issue by Zerokk** [desktop/desktop#3116] opened 2017-10-21 10:09 UTC
### Description

When I try logging in the app with my user and password, I can only see the "Sign in into Github.com" message. Nothing else appears; it's as if the login request can't complete.

### Version

Latest. Installed it yesterday.

**OS version:** Windows 10.

### Steps to Reproduce

1. Open the app
2. Put my login credentials
3. Click on "sign in"
4. ... nothing happens.

Anybody else having the same problem?

**Comment by shiftkey** [comment] 2017-10-21 10:18
@Zerokk thanks for the report! This feels similar to #2769 but with some slightly different steps.

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by Zerokk** [comment] 2017-10-21 10:31
@shiftkey Where can I find the log files? I can't see the "help" button/tab anywhere in the app. I've been looking in my files for the log file but could not find them.

**Comment by shiftkey** [comment] 2017-10-21 10:33
@Zerokk the Help menu is part of the top menu, or you can just go to `%APPDATA%\GitHub Desktop\logs` on disk.

**Comment by Zerokk** [comment] 2017-10-21 10:37
@shiftkey Thank you! There you have the logs:

> 2017-10-21T10:02:27.564Z - info: [ui] [AppStore] loading 0 repositories from store
> 2017-10-21T10:02:27.569Z - info: [ui] [AppStore] found account: Zerokk (Zerok)
> 2017-10-21T10:02:27.598Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:02:27.719Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:02:27.803Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:02:27.961Z - info: [ui] launching: 1.0.4 (Windows 10.0.14393)
> 2017-10-21T10:02:28.002Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:02:29.431Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:04:13.213Z - info: [ui] [Welcome] advancing to step: SignInToDotCom
> 2017-10-21T10:04:13.220Z - info: [ui] [Welcome] current sign in state not found. ignoring...
> 2017-10-21T10:04:27.340Z - info: [ui] [AppStore] adding account Zerokk (Zerok) to store
> 2017-10-21T10:04:27.346Z - info: [ui] [Welcome] kind Authentication does not match Success. ignoring...
> 2017-10-21T10:29:44.464Z - info: [ui] [AppStore] loading 0 repositories from store
> 2017-10-21T10:29:44.468Z - info: [ui] [AppStore] found account: Zerokk (Zerok)
> 2017-10-21T10:29:44.468Z - info: [ui] [AppStore] found account: Zerokk (Zerok)
> 2017-10-21T10:29:44.499Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:29:44.611Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:29:44.716Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:29:44.765Z - info: [ui] launching: 1.0.4 (Windows 10.0.14393)
> 2017-10-21T10:29:44.804Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:29:46.185Z - info: [ui] [Welcome] no sign in step found. ignoring...
> 2017-10-21T10:30:23.832Z - info: [ui] [Welcome] advancing to step: ConfigureGit
> 2017-10-21T10:30:30.935Z - info: [ui] [Welcome] advancing to step: UsageOptOut
> 2017-10-21T10:30:32.877Z - info: [ui] [Welcome] advancing to step: ConfigureGit

**Comment by joshaber** [comment] 2017-10-23 14:42
Thanks @Zerokk! That does indeed look like a duplicate of #2769, so I'm gonna close this. Feel free to follow along over there!

**Closed by joshaber** 2017-10-23 14:42 UTC
Labels: more-information-needed

**Comment by orestotel** [comment] 2018-10-17 17:42
I encountered the same problem.

It occurred when I opened the Github desktop and then changed my Github password via Chrome browser. No issues were noticed by me until I tried to clone a forked repository from my account. 

It asked me to log in. I typed my login and the new password and pressed to log in. It didn't work, so I tried it several times.

After that, I changed my password again to make sure I'm typing the right password and making no mistakes, but even after these actions nothing has changed: 

> I type my login and password
> I press login

and it just doesn't log me in and does not clone the repository.

I will attach following screenshots to help this bug be fixed in the shortest time.

Image(Screenshot):
https://imgur.com/a/7Ot7PsT

**Comment by shiftkey** [comment] 2018-10-17 18:17
@orestotel this really feels like #5905 which we traced to the user not being signed into their GitHub account.

> Can you try logging out and then logging back in to GitHub Desktop to see if that gets things working? You can do this by going to the file menu in GitHub Desktop and selecting `File` > `Options` > `Accounts`.
