### ISSUE TITLE
[Stashing] Restoring stash doesn't actually get rid of stash

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#7286] opened 2019-04-12 22:17 UTC
**Repro steps**
1. Create stash on branch
1. Restore stash

**Expected**
The stash is removed and the _Stashed Changes_ element goes away.

**Actual**
The stash sticks around and the _Stashed Changes_ element is still there.

![2019-04-12 16 07 51](https://user-images.githubusercontent.com/1715082/56069003-9aefa000-5d46-11e9-985f-df78cfc4410d.gif)

**Comment by iAmWillShepherd** [comment] 2019-04-15 16:45
I've tried reproducing this since this issue was created and it doesn't seem to be an issue any longer. 

![2019-04-15 11 42 40](https://user-images.githubusercontent.com/1715082/56150137-c4d9da00-5f73-11e9-91a0-f5e4a5f47a0a.gif)

I'm leaving this open so that @desktop/quality-assurance can verify this is no longer an issue.

**Comment by tierninho** [comment] 2019-04-15 17:56
Cannot reproduce. Closing this issue.

**Closed by tierninho** 2019-04-15 17:56 UTC
Labels: bug
