### ISSUE TITLE
Merge Conflict Resolver

### ISSUE THREAD

**Issue by Mashimaro7** [desktop/desktop#18381] opened 2024-03-29 20:04 UTC
### The feature request

A handy way to resolve merge conflicts AFTER the merge.

### Proposed solution

A way to resolve conflicts post merge. Just an option, maybe under repository that lets you scan for conflicts.

### Additional context

If conflicts aren't resolved in time, there's no way to resolve them after the fact without manually opening a text file and searching through the files. With scripts, this isn't usually a big deal(though it is time consuming), but with say, Unity scene files, this is an incredibly annoying process. I just had a client try merging, Github desktop froze on the conflict screen, so he closed it, and there was no way to resolve the conflicts so he just committed it like that.

Also, it'd be nice if the conflict resolve wasn't just "choose one file or the other" but instead, let you go in and manually chose which changes to keep? Like, when you do a pull request it allows you to do this, but it'd be handy if Github Desktop had this as well.

**Comment by steveward** [comment] 2024-04-03 20:19
@Mashimaro7 thanks for the issue. If the merge conflict window is closed it should still show a banner in the app that there are conflicts that need to be resolved and should also warn about the conflicts when a commit is made. I'm not sure how the modal would have frozen, but if there's any further information you can share around that it would be helpful as that seems to be the cause of the issue.

Since this is likely an edge case and not something we've seen previously reported I'm going to close this out, but I'd be happy to follow up more to investigate this behavior or if you can provide some reproduction steps.

**Closed as completed by steveward** 2024-04-03 20:19 UTC

**Comment by Mashimaro7** [comment] 2024-04-03 20:24
> @Mashimaro7 thanks for the issue. If the merge conflict window is closed it should still show a banner in the app that there are conflicts that need to be resolved and should also warn about the conflicts when a commit is made. I'm not sure how the modal would have frozen, but if there's any further information you can share around that it would be helpful as that seems to be the cause of the issue.
> 
> Since this is likely an edge case and not something we've seen previously reported I'm going to close this out, but I'd be happy to follow up more to investigate this behavior or if you can provide some reproduction steps.

I've had it happen many times, on three different computers. And the "view conflicts" thing doesn't always show up, i know what you're talking about but sometimes it's just... not there lol. Still, i think there should be an easier way to sort through merge conflicts. What if you brought in a script from another project which had merge conflicts on it? Is there no way to sort through these conflicts? Seems like it would be easy to make a way to just "scan" for merge conflicts from Github Desktop, as it would only  need to scan for >>>>>> s in files.
