### ISSUE TITLE
Deleted repositories show up in GitHub Desktop

### ISSUE THREAD

**Issue by johnzoet** [desktop/desktop#6867] opened 2019-02-17 02:16 UTC
## Description

Deleted repositories via web site of Github.com show up in Desktop Github for several hours, then disappear from Desktop Github

## Version

* GitHub Desktop: 1.6.2

* Operating system: Windows 10

## Steps to Reproduce

Create new repository "test-repo" on Github.com web site
Delete repository "test-repo" on Github.com web site
Open Desktop Github

### Expected Behavior

Expected behaviour: Desktop Github does not show repository test-repo

### Actual Behavior

Actual behaviour : Desktop Github shows deleted repository test-repo

**Comment by billygriffin** [comment] 2019-02-17 03:56
@johnzoet Thanks for the report! Would you mind being more specific about what you mean by the repo showing in GitHub Desktop? Do you mean in the clone area? Or once you’ve added it to Desktop already? Screenshots would be helpful too if you don’t mind so we can look into it. Thanks again!

**Comment by johnzoet** [comment] 2019-02-17 20:44
The first time you open Github Desktop you see a list of repositories. The deleted repository did show up in the repository list.
I tried to replicate the issue and now get the opposite, but maybe related, issue. Now, after adding a new repository I do not see the new repository. Looks like there is a delay between the Github web site and the Github Desktop tool.
I have added two screen shots, one from Github and the other from Github Desktop.
![screenshot-github com-2019 02 18-09-27-09](https://user-images.githubusercontent.com/9982429/52918907-79cf8c00-3361-11e9-8eb5-7858bdff9989.png)

**Comment by johnzoet** [comment] 2019-02-17 20:45
![annotation 2019-02-18 093320](https://user-images.githubusercontent.com/9982429/52918947-e9457b80-3361-11e9-847d-8f28af8a4695.jpg)

**Comment by niik** [comment] 2019-02-18 07:46
Hi @johnzoet. GitHub Desktop doesn't automatically add repositories created on GitHub.com, you have to clone them to your machine first by clicking on the File menu and the selecting `Clone Repository`. You can also use the `Add` button in the sidebar as shown in your screenshot.

Once you open the clone dialog it's possible that newly created repositories doesn't show up since, just as you said, we store a local copy of all repositories available for cloning. You can refresh that list by clicking on the refresh button in the clone dialog as shown below.

![image](https://user-images.githubusercontent.com/634063/52935355-7df7ab80-3359-11e9-992a-30c26f2dbcd2.png)

GitHub Desktop will also never delete a local repository that you've cloned before from your machine even though it has been deleted from GitHub.com, this is by design.

I hope that helps clear things up, please don't hesitate to add more context to this issue if there's anything I'm missing but for now I'm going to close this as I believe this is the intended behavior.

**Closed by niik** 2019-02-18 07:46 UTC
Labels: more-information-needed

**Comment by johnzoet** [comment] 2019-02-18 09:36
I understand the process about adding local repositories to Github Desktop , but this is not the behaviour that happened the first time I opened Github Desktop. The very first time I saw all my remote repositories on Github without adding any local repository. Even the deleted remote Github repositories showed up 2 times with exactly the same name. These deleted repositories were not on my local PC and I had not added them to Github Desktop either.
Now Github behaves as expected. Maybe by uninstalling the application , clearing any cached files I can reproduce the behaviour I saw first time.
I have read quite a lot now about Git and cannot give any logical explanation for the remote repositories showing up in Github Desktop.

**Comment by johnzoet** [comment] 2019-02-18 22:11
I have reproduced partly the repositories problem in a fresh install of Github Desktop using a Virtualbox Windows 10 guest.

Steps below:
Install Github Desktop.
Enter Github credentials.
Next Github Desktop shows all remote repositories. Screen capture attached.
Github keeps on displaying the remote repositories after application shutdown.
Once a local repository has been created or cloned from remote repository, the behaviour changes.
Now , Github Desktop shows the most recent local repository.
Shutdown Github Desktop.
Create new remote repository.
Open Hithub Desktop, click File > Clone repository.
The new remote repository shows up in the list : ok
Remove remote repository.
Open Hithub Desktop, click File > Clone repository.
The deleted remote repository shows up in the list : not ok
This is clearly a caching issue in Github Desktop.
![github desktop annotation 2019-02-19 100213 1](https://user-images.githubusercontent.com/9982429/52978653-11eb7500-3437-11e9-9ac3-6f04d153a74e.jpg)

**Comment by abrahamwilliam** [comment] 2019-05-09 20:36
I  too have this issue.

**Comment by wilsandbrink** [comment] 2019-07-31 22:37
Same issue
