### ISSUE TITLE
"Open in Command Prompt" crashes the application

### ISSUE THREAD

**Issue by t7m** [desktop/desktop#4093] opened 2018-02-23 15:14 UTC
### Description

Click "Open in Command Prompt" from the Repository menu. Application crashes.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Microsoft Windows [Version 10.0.16299.248]

### Steps to Reproduce

See description.

**Expected behavior:** No crash

**Actual behavior:** Crash

**Reproduces how often:** 100%

### Logs

Error message:
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.13
OS: Windows 10.0.16299

**Comment by iAmWillShepherd** [comment] 2018-02-23 17:07
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3882. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-02-23 17:07 UTC

**Comment by shiftkey** [comment] 2018-02-23 22:24
@iAmWillShepherd @t7m this has been fixed in #4044 which is currently available on the [beta channel](https://github.com/desktop/desktop#beta-channel), and will go out to the stable channel on Monday.
