### ISSUE TITLE
Scroll is almost unusable

### ISSUE THREAD

**Issue by akapitoha** [desktop/desktop#7060] opened 2019-03-11 08:44 UTC
## Description
When I try to scroll with touchpad scrollbar just twitches, but actually screen is not being scrolled. Sometimes I'm able to scroll. Though when I try to scroll up, the screen is being scrolled down.

## Version
* GitHub Desktop:
1.6.3
* Operating system:
Mac os 10.14.2

## Steps to Reproduce
I uploaded a gif for better undestanding

### Expected Behavior
Correct scroll behavior as in previous version

### Actual Behavior
You can see on gif
![scroll](https://user-images.githubusercontent.com/3147449/54110629-7be2b300-4414-11e9-8f0a-a7c5fd9c1536.gif)

**Comment by billygriffin** [comment] 2019-03-11 20:58
Thanks @akapitoha! I'm curious if any other users are seeing this. I'm unable to reproduce on two different Macs with the same OS setup (except `10.14.3`). Any other information that might be pertinent to help us reproduce?

**Comment by FrankManns** [comment] 2019-03-13 16:39
I'm consistently seeing this issue.

#### Version
GitHub Desktop: 1.6.4
MacOS: 10.13.6

#### Steps to Reproduce
1. In either the Changes or History tab, click on a file that's long enough to scroll
2. Assuming your scroll direction is "natural", swipe up to scroll down to the bottom of the file. Then keep swiping up.

As you continue to swipe up, the file will scroll up and down wildly.

**Comment by spencer-microsoft** [comment] 2019-03-13 17:43
I'm also seeing this issue

MacOS: 10.14.3
GitHub Desktop: 1.6.4

Scroll direction: natural

**Comment by tierninho** [comment] 2019-03-14 19:15
Cannot reproduce either.

Possible if anyone share a repo with the corresponding file they are having trouble with? Would like to take a peek. Thanks!

**Comment by billygriffin** [comment] 2019-03-14 19:30
In addition to what @tierninho asked for above, I'd love to understand if folks experiencing this are using a particular type of mouse or trackpad when experiencing this. I've tried reproducing on 3 different macOS machines, two laptop trackpads, and an external trackpad and magic mouse, to no avail. If there's anything else you can share that might help us in figuring out how to reproduce this, that would be appreciated.

**Comment by FrankManns** [comment] 2019-03-14 20:05
I just restarted GitHub Desktop and the problem went away 🤷‍♂️. Prior to that, I was able to reproduce the issue with all of the following

Input Device: Trackpad and Magic Mouse
Scroll Direction: Natural and Not
Monitor: MacBook and external
Repository: My private repo and this repository - I cloned `https://github.com/desktop/desktop`, selected `bda087d12` from the list of commits on the History tab, and selected `dispatcher.ts`. It doesn't really matter what file it is as long as it can scroll.

**Comment by billygriffin** [comment] 2019-03-14 23:50
@FrankManns Don't you just love problems that aren't reliably reproducible? 😄 Thanks for letting us know it's cleared up and for the detailed repro steps. ❤️ If others are able to share details, that would be awesome. Otherwise, we'll probably need to close this until we're able to understand how to reproduce.

**Comment by mikew** [comment] 2019-03-19 14:11
Dupe of https://github.com/desktop/desktop/issues/1380? This issue has been going on for years.

**Comment by billygriffin** [comment] 2019-03-19 17:44
Looks like that @mikew, thank you! I'm going to close this issue and we'll continue to track in #1380. I wish we knew how to repro this reliably so we could get to something that fixes it, so if anyone can help in that regard, it'd be much appreciated.

**Closed by billygriffin** 2019-03-19 17:44 UTC
Labels: more-information-needed
