### ISSUE TITLE
Remember selection of changes

### ISSUE THREAD

**Issue by pinguin999** [desktop/desktop#7544] opened 2019-05-16 10:21 UTC
The selection of changes is reset and all changes are selected after app restart.

Example:

> “When I update the app, close & reopen, change to an other project or reboot the selection of changes in a dirty working space are reset and all changes are selected. Best solution would be to have the same selection on reopen.”

**Comment by say25** [comment] 2019-05-16 10:31
This looks to be a duplicate of https://github.com/desktop/desktop/issues/5870

**Closed by say25** 2019-05-16 10:31 UTC
