### ISSUE TITLE
Select Branch to Compare Selects Wrong Branch

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#9971] opened 2020-06-09 04:47 UTC
### Describe the bug

When I click on the Select Branch to Compare dropdown and pick a branch that I want to compare to my current branch, the wrong branch is picked and placed into that field.  This only happens in specific repositories, not all.  The only way to pick the branch I want is to type it in until the list filters down to the one I want, then select it.

### Version & OS

macOS 10.15.5
GitHub Desktop 2.5.2

### Steps to reproduce the behavior

Unfortunately, this doesn't work in every repo and I can't determine what is exactly causing it in order to make a reproducible example.  Currently, this is happening with my work repositories, so I cannot even provide a link to a repo that exhibits the bug or provide a screen capture video.

1. Click "Select Branch to Compare"
2. Pick a branch
3. Notice that the branch that shows up as the selected branch is not the one you chose

### Expected behavior

I would expect the correct branch to be selected

### Actual behavior

The wrong branch is selected

### Screenshots

Unable to post any unless I can reproduce it in a non-private repository.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

It *seems* to happen with branches that are similarly prefixed.  What I'm noticing is happening with my work repositories is that if there are two branches named:

1) `X`
2) `XY`

Where X and Y can be full words or multiple words

If I select the `X` branch, the `XY` branch is selected.  I don't think I've noticed a case where I pick branch `X` and some other branch that doesn't have `X` as a prefix is selected.  The weird thing is, I've tried recreating this in a new repository, but I am not able to reproduce the bug there.  I will update this issue if I can find a way to reproduce it.

**Comment by rafeca** [comment] 2020-06-09 14:46
Thanks for the report @JosephTLyons ! This seems like an interesting issue! 🕵️

I'm going to investigate it, but if you can answer a couple of questions that would be very helpful for me:

1. Can you reproduce it 100% of the times on a specific repo and clicking on a specific branch?
1. Can you give me a bit more information about the branch names? Do they also have different capitalization? does `X` contain only alphanumeric chars? if you can provide an example of `X` and `XY` that does not expose private information that would be very helpful as well.

**Comment by tierninho** [comment] 2020-06-09 20:26
I was able to successfully recreate this. Every time I click compare `X` it reverts to `XY` branch, but not vice-versa. 

I set up a private repo (https://github.com/tierninho/STASHd/branches), with three branches. I renamed both branches as `X` and `XY`. When I try to compare `master` against `X`, it always reverts to `XY`. I noticed you have to be on `master` to see the bug.

I think the renaming both branches affected this. I had two branches with similar names and everything worked fine. As soon as I renamed them both to `X` and `XY` , bingo.

**Comment by JosephTLyons** [comment] 2020-06-09 21:47
Same, I actually was able to recreate the bug as well in a private repo.  Here is a zip file with a `.mov` screen video and the repo I made that has the issue.  In the first half of the video, you can see the issue happen 3 or 4 times at normal speed.  In the second half of the video, I clicked and held the mouse down and you can what is happening.  The positions of the branches are changing on the down click of the mouse, then on the upclick of the mouse, the wrong branch is selected:

[Select Branch to Compare Issue.zip](https://github.com/desktop/desktop/files/4755040/Select.Branch.to.Compare.Issue.zip)

**Comment by JosephTLyons** [comment] 2020-06-09 23:16
> I was able to successfully recreate this. Every time I click compare `X` it reverts to `XY` branch, but not vice-versa. 
> 
> 
> 
> I used a private repo (https://github.com/tierninho/STASHd), with two branches (in addition to `master`). I renamed both branches as `X` and `XY`. When I try to compare `master` against `X`, it always reverts to `XY`. I noticed you have to be on `master` to see the bug.
> 
> 
> 
> I think the renaming both branches affected this. I had two branches with similar names and everything worked fine. As soon as I renamed them both to `X` and `XY` , bingo.

Hmmm, I’m not sure I had to rename my branches to get it to happen.  I think it happened just after creating them.  I will say that after encountering this bug for many weeks, I have noticed that it actually doesn’t happen every time.  I can get it to happen many times in a row, then randomly it won’t happen.  Maybe you’ve were lucky enough to have to work properly in the case where you didn’t rename the branches and have it now work in the case where you did rename the branches.

**Comment by tierninho** [comment] 2020-06-09 23:54
You are correct, as I tried it again and the renaming was irrelevant.

**Comment by rafeca** [comment] 2020-06-10 08:27
Thanks for the information @tierninho and @JosephTLyons ! This is a great catch!

I've been able to reproduce the issue now! it looks like a race condition between the mouse handlers, going to see if it's easy to send a quick fix for this.

**Closed** 2020-06-11 15:23 UTC
Labels: bug, priority-3

**Comment by JosephTLyons** [comment] 2020-06-12 01:04
Nice work @rafeca, can't wait for this fix to land in a new build!  Much appreciated.
