### ISSUE TITLE
GitHub Desktop no longer displays list of repositories available to clone

### ISSUE THREAD

**Issue by Omegahed** [desktop/desktop#2156] opened 2017-06-29 21:00 UTC
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

GitHub Desktop no longer displays list of repositories available to clone.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.6.2

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** Windows 10 Version 1703

### Steps to Reproduce

1. Select File >> Clone repository...

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** Clone repository dialog box should present list of available repositories to clone; as in previous versions.

**Actual behavior:** Clone repository dialog does not present list of available repositories. You know must know the name of the repository before you can clone it.

**Reproduces how often:** 100%

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by j-f1** [comment] 2017-06-29 21:05
This appears to be a duplicate of #57. Please follow along there instead.

**Comment by joshaber** [comment] 2017-06-29 21:48
Yup, thanks!

**Closed by joshaber** 2017-06-29 21:48 UTC
