### ISSUE TITLE
Highlight repositories with unstaged / uncommitted changed in the repository list

### ISSUE THREAD

**Issue by tobiasschuerg** [desktop/desktop#4265] opened 2018-03-16 09:01 UTC
Would be nice if I could see directly in the reposity list, which repo has unstaged changes.

Could simply be done with blue dots (see screenshot) or a colored icon or another icon ...

![image](https://user-images.githubusercontent.com/1324555/37511930-d95a6710-2900-11e8-9b63-ffb90e2c8150.png)

**Comment by j-f1** [comment] 2018-03-16 13:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2259. Please follow that issue for further updates.

**Closed** 2018-03-16 15:36 UTC
