### ISSUE TITLE
Contrast - Red & Green

### ISSUE THREAD

**Issue by mrwompin** [desktop/desktop#2974] opened 2017-10-06 03:42 UTC
### Description

The desktop client uses very light colored red and green to indicated deletes and additions, I'm not sure if I've always been color blind, but trying to see the difference between the two colors is nearly impossible for me. I really like the client, it's simple to use and it is helping me learn source control, but this color thing is becoming a real hurdle to get passed. Would it be possible to get settings to adjust colors or contrast, or to have a dark mode so that the reds and greens stand out more? Thank you so much for all you do in providing this website and control and collaboration.

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Windows 10

### Steps to Reproduce

1. open repo, make adds and deletes, hard to see if colorblind

**Expected behavior:** able to see difference between green and red on screen

**Actual behavior:** everything looks white

**Reproduces how often:** always, I think I'm colorblind

**Comment by niik** [comment] 2017-10-06 07:33
Hey @mrwompin, thanks for writing in! There's an issue tracking a dark mode (https://github.com/desktop/desktop/issues/1515) and while it's not part of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) we'll be revisiting, and consider it again when planning for future releases.

I'm curious if you find that the red/green contrast of diffs on GitHub.com are any easier for you to pick apart? Ours are definitely a bit paler than them and I see no real need for them to be. Firing up my red-green confusion simulator I can definitely see that the contrast leaves a lot to be desired. I'm gonna take a look at this and see if we can't improve the situation a little at least.

**Comment by mrwompin** [comment] 2017-10-06 12:22
Thank you for writing back that's awesome of you! I hopped on the website and it is a lot easier to read, the highkight over the line numbers are kinda of hard to read but better than on the client.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Markus Olsson <notifications@github.com> Date: 10/6/17  3:33 AM  (GMT-05:00) To: desktop/desktop <desktop@noreply.github.com> Cc: mrwompin <mmarkwald01@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [desktop/desktop] Contrast - Red & Green (#2974) 
Hey @mrwompin, thanks for writing in! There's an issue tracking a dark mode (#1515) and while it's not part of our current roadmap we'll be revisiting, and consider it again when planning for future releases.
I'm curious if you find that the red/green contrast of diffs on GitHub.com are any easier for you to pick apart? Ours are definitely a bit paler than them and I see no real need for them to be. Firing up my red-green confusion simulator I can definitely see that the contrast leaves a lot to be desired. I'm gonna take a look at this and see if we can't improve the situation a little at least.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/desktop/desktop","title":"desktop/desktop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/desktop/desktop"}},"updates":{"snippets":[{"icon":"PERSON","message":"@niik in #2974: Hey @mrwompin, thanks for writing in! There's an issue tracking a dark mode (https://github.com/desktop/desktop/issues/1515) and while it's not part of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) we'll be revisiting, and consider it again when planning for future releases.\r\n\r\nI'm curious if you find that the red/green contrast of diffs on GitHub.com are any easier for you to pick apart? Ours are definitely a bit paler than them and I see no real need for them to be. Firing up my red-green confusion simulator I can definitely see that the contrast leaves a lot to be desired. I'm gonna take a look at this and see if we can't improve the situation a little at least."}],"action":{"name":"View Issue","url":"https://github.com/desktop/desktop/issues/2974#issuecomment-334680993"}}}

**Comment by JW0914** [comment] 2017-10-07 13:56
@niik It would be far more helpful to either explain, or link to an explanation, why the dark theme was removed from the newer version of GitHub Desktop... clearly this wasn't an oversight, but an overt decision.

**Comment by adamreisnz** [comment] 2017-10-08 22:40
I'd also like to chime in here, the slightly darker green/red diff colors in the old Github Mac app were definitely nicer and easier to see than the current pale colors. 

+1 for making them a bit darker

**Comment by joshaber** [comment] 2017-10-09 12:37
This looks like a duplicate of https://github.com/desktop/desktop/issues/2586 so I'm gonna close it. Feel free to follow along over there!

@niik I'll assign that one to you instead.

**Closed by joshaber** 2017-10-09 12:37 UTC
Labels: needs-design-input

**Comment by adamreisnz** [comment] 2017-10-09 20:16
Thanks, I've subscribed there.
