### ISSUE TITLE
Why there is not official binaries for Linux of Github Desktop?

### ISSUE THREAD

**Issue by anaibol** [desktop/desktop#8184] opened 2019-08-30 14:07 UTC
Why there is not official binaries for Linux of Github Desktop?

**Comment by billygriffin** [comment] 2019-08-30 15:45
Hi @anaibol, thanks for the issue. This is a duplicate of https://github.com/desktop/desktop/issues/1525 so please follow along there. Thanks!

**Closed by billygriffin** 2019-08-30 15:45 UTC
Labels: more-info-needed
