### ISSUE TITLE
Ability to update tags when fetching origin

### ISSUE THREAD

**Issue by jdavisp3** [desktop/desktop#15978] opened 2023-01-20 22:23 UTC
### The feature request

I would like "Fetch origin" to update tags from upstream.

### Proposed solution

Add a setting to make it the default behavior when fetching.

**Comment by tidy-dev** [comment] 2023-01-25 13:38
@jdavisp3 Thank you for reaching out. Could you elaborate on the behavior you are seeing?

I just added at tag to my remote. Then fetched through GitHub Desktop and it fetched the tag. Are you expecting a different behavior?

**Comment by jdavisp3** [comment] 2023-01-25 16:46
> @jdavisp3 Thank you for reaching out. Could you elaborate on the behavior you are seeing?
> 
> I just added at tag to my remote. Then fetched through GitHub Desktop and it fetched the tag. Are you expecting a different behavior?

Hm, I am seeing a different behavior. Now the tag in question was _changed_ from one commit to another. Could that make a difference?

**Comment by tidy-dev** [comment] 2023-01-27 13:55
That is definitely odd; you can only change from one commit to another by first deleting the tag and then retagging the other commit. But, if it is an already pushed tag, that is generally not advised as it is considered rewriting history for your repository consumers (leading to mismatched histories if someone else already pulled it before it was changed) and is why we do not support deleting pushed tags in GitHub Desktop.

Is it possible another user changed this tag?

**Comment by jdavisp3** [comment] 2023-01-27 15:08
> That is definitely odd; you can only change from one commit to another by first deleting the tag and then retagging the other commit. But, if it is an already pushed tag, that is generally not advised as it is considered rewriting history for your repository consumers (leading to mismatched histories if someone else already pulled it before it was changed) and is why we do not support deleting pushed tags in GitHub Desktop.
> 
> Is it possible another user changed this tag?

It's definitely possible -- this particular tag represents "the currently deployed commit" of an app in a private repository. So the tag gets changed automatically by design.

**Comment by tidy-dev** [comment] 2023-01-27 17:56
Ah. That is an interesting approach to tagging. Unfortunately we do not support/test scenarios with the intention of changing tags on commits. I seems that would likely be the root cause of this issue as Git's default way of [filtering which tags it download](https://git-scm.com/docs/git-fetch) to only do objects that are currently checked out (maybe it also doesn't re-download tags it already has) 

> By default, tags that point at objects that are downloaded from the remote repository are fetched and stored locally.

I am wondering if explicitly running `git fetch --tags` on the command line will solve it for you. Maybe you also need to do `git fetch --tags --prune-tags` which would[ remove any tags](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune-tags) that do not exist on the remote. Tho.. I am not sure on that as the tag does exist .. it just doesn't exist on the remote for the commit that it is locally associated with. 

I will mark this as an enhancement; tho I am not sure the GitHub Desktop team would be interested in finding a way to support this as we intentionally support the traditional version control tagging process to mark a time in history and increment that version as new current versions are deployed.

**Comment by jdavisp3** [comment] 2023-01-27 20:59
> Ah. That is an interesting approach to tagging. Unfortunately we do not support/test scenarios with the intention of changing tags on commits. I seems that would likely be the root cause of this issue as Git's default way of [filtering which tags it download](https://git-scm.com/docs/git-fetch) to only do objects that are currently checked out (maybe it also doesn't re-download tags it already has)
> 
> > By default, tags that point at objects that are downloaded from the remote repository are fetched and stored locally.
> 
> I am wondering if explicitly running `git fetch --tags` on the command line will solve it for you. Maybe you also need to do `git fetch --tags --prune-tags` which would[ remove any tags](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt---prune-tags) that do not exist on the remote. Tho.. I am not sure on that as the tag does exist .. it just doesn't exist on the remote for the commit that it is locally associated with.

Yep, you can definitely make this work on the command line with `git fetch origin --tags --force`.

> I will mark this as an enhancement; tho I am not sure the GitHub Desktop team would be interested in finding a way to support this as we intentionally support the traditional version control tagging process to mark a time in history and increment that version as new current versions are deployed.

Understood, we also use versioned tags that never change. It's just been handy to have a name that means "whatever was deployed last", etc.

**Comment by niik** [comment] 2023-01-30 09:14
Hey @jdavisp3, thanks for reaching out. We just saw a similar request in https://github.com/desktop/desktop/issues/16032 and I'm going to reiterate that response here. Given that it is the expected behavior of Git to not delete local tags (https://git-scm.com/docs/git-tag#_on_re_tagging) GitHub Desktop will not do so either. For references that change frequently the idiomatic Git approach would be to use a branch, not a tag. I see it as unlikely that we'd implement a preference to automatically delete tags remotely since that's something which could get users into big trouble if they don't fully understand the consequences of doing so.

If this is a workflow required on your team you could look into the [fetch.prune](https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchprune) [fetch.pruneTags](https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchpruneTags) config setting to see if that could help out but be aware that this will delete local tags on each fetch and is not something we can recommend.

Given that we are unlikely to implement this request I'm going to close this out. Wish I had better news for you and I hope you find a workaround!

**Closed as completed by niik** 2023-01-30 09:14 UTC
Labels: enhancement

**Comment by jdavisp3** [comment] 2023-01-30 14:01
Thanks for checking!

**Comment by kd-tka** [comment] 2025-03-17 12:59
GitHub Desktop History and "git tag" should always show the same list of Tags (but they don't)

![Image](https://github.com/user-attachments/assets/146adba1-89ae-444d-a74b-b1214665effb)
