### ISSUE TITLE
Option to "Commit and Push"

### ISSUE THREAD

**Issue by InfinityBush** [desktop/desktop#2272] opened 2017-07-19 02:56 UTC
In the old version, there was a checkbox that allowed for "commit and push" instead of committing and then pushing. I know this is a very small thing, but I liked it so I didn't have to remember to push after committing.

**Comment by joshaber** [comment] 2017-07-19 14:23
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Closed by joshaber** 2017-07-19 14:23 UTC
Labels: future-proposal

**Comment by j-f1** [comment] 2017-07-19 15:07
It looks like this is a duplicate of #2256.
