### ISSUE TITLE
Switch branch to upstream/master not working

### ISSUE THREAD

**Issue by PiezPiedPy** [desktop/desktop#3095] opened 2017-10-18 16:42 UTC
While in a fork of a repository I have an upstream/master branch available in the branches list as expected but I am unable to switch to it.
 When I try, the branch will switch to origin/master instead ??
This small bug is making it impossible for me to merge branches into upstream/master which I have push access to with the desktop app.
Not a big issue though just slightly annoying, as I can allways use git 😉
Also showing the full path of the branch on the tab and lists when an upstream branch would be of beneficial use to myself and possibly others.

**Comment by tierninho** [comment] 2017-10-19 09:37
So tested this and forked repo or not the issue is reproducible. 

Trying to change the branch from `Master` to `Origin/HEAD` fails. The branch remains on `Master` or whatever current branch the user was on.

<img width="779" alt="screen shot 2017-10-19 at 10 31 50 am" src="https://user-images.githubusercontent.com/14828183/31764523-5a8a8070-b4b9-11e7-9b7a-607c30137bf1.png">

I used this repo to test: https://github.com/ng2-ui/map

No logs found. Mac, v1.0.5.beta0

**Comment by shiftkey** [comment] 2018-01-19 19:17
@tierninho tested out the `ng2-ui/map` repository on `1.0.12` on macOS and I don't see the `origin/HEAD`:

<img width="675" src="https://user-images.githubusercontent.com/359239/35166883-3475f09e-fd08-11e7-9a50-f047f531afb1.png">

I'm not sure where this crept in, but `origin/HEAD` doesn't really make sense as a branch to checkout (it just represents the tip of the remote repository).

@PiezPiedPy we don't currently have a good solution for this, as I tested your scenario (where both upstream and remote have a branch named `master`) and it now fails in this way:

<img width="458" src="https://user-images.githubusercontent.com/359239/35167036-cc6fd7ac-fd08-11e7-8c48-2e313964a209.png">

This is because I already have a local ref named `master`, and we're not clever enough to name the branches better. I captured this in a test here and added some extra context: https://github.com/desktop/desktop/pull/3624/files#diff-082232a811b0d91d2610434996595204R112

If you have any thoughts on how you'd like this to work, let me know and we can try and figure out a way out of this.

**Comment by shiftkey** [comment] 2018-01-19 19:27
@PiezPiedPy 

> This small bug is making it impossible for me to merge branches into upstream/master which I have push access to with the desktop app.

As a workaround, you could remove the current `master` ref from your remote and switch yourself to the right `master`:

```
git checkout [other-branch]
git checkout -D master
git checkout upstream/master -b master --
```

That will let you use the "Merge into current branch" flow in the app to merge branches, but won't address the underlying ability to switch between `origin/master` and `upstream/master`.

**Comment by shiftkey** [comment] 2018-10-14 19:57
Coming back to the details about this:

> While in a fork of a repository I have an upstream/master branch available in the branches list as expected but I am unable to switch to it.
> When I try, the branch will switch to origin/master instead ??
> This small bug is making it impossible for me to merge branches into upstream/master which I have push access to with the desktop app.
> ...
> Also showing the full path of the branch on the tab and lists when an upstream branch would be of beneficial use to myself and possibly others.

I don't have the full picture of the behaviour here, but I believe this is the same root cause as #4527 about being able to checkout a branch with the same name that exists on multiple remotes.

@tierninho @billygriffin any objections to closing this out in favour of that discussion?

**Comment by tierninho** [comment] 2018-10-15 20:09
@shiftkey No objections to closing this

**Closed** 2018-10-15 20:19 UTC
Labels: bug, priority-3
