### ISSUE TITLE
Version 2.9.9 (x64) has missing dependency

### ISSUE THREAD

**Issue by celtic-coder** [desktop/desktop#13938] opened 2022-02-18 01:04 UTC
Selecting "Help" -> "About GitHub Desktop" gives the following screen:

![about-github-desktop-v 2 9 9](https://user-images.githubusercontent.com/11787866/154596462-62405f34-de33-4059-bee4-38e37bf7e395.png)

Clicking the "Check for Updates" button, then gives the following error:

![error-missing-a-dependency](https://user-images.githubusercontent.com/11787866/154596841-5db6c023-0ac8-4baf-a07f-e85cc6fadddd.png)

This error is on Windows 10 64-bit.

**Comment by sergiou87** [comment] 2022-02-18 08:01
Thanks for your report!!

However, I cannot reproduce this issue. If you close the app, reopen it, and then try to Check for Updates… does it still happen?

**Comment by celtic-coder** [comment] 2022-02-18 15:17
Hi Sergio  (@sergiou87),

I re-opened the app again today, following a system shutdown. I got the same error.

The GitHub Desktop log (2022-02-18.desktop.production.log) has the following message repeated:

`
2022-02-18T00:32:24.383Z - info: [ui] launching: 2.9.9 (Windows 10.0.19044)
2022-02-18T00:32:24.384Z - info: [ui] execPath: 'C:\Users\New\scoop\apps\github\current\GitHubDesktop.exe'
2022-02-18T00:32:24.839Z - error: [ui] Error checking for updates
Error: The application is missing a dependency it needs to check and install updates. This is very, very bad.
    at file:///C:/Users/New/scoop/apps/github/2.9.9/resources/app/renderer.js:57:118185
    at EventEmitter.onAutoUpdaterError (file:///C:/Users/New/scoop/apps/github/2.9.9/resources/app/renderer.js:57:118601)
    at EventEmitter.emit (node:events:390:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:833)
`

As can be seen, I am using [Scoop](https://scoop.sh/) to keep the application updated. The scoop [bucket](https://github.com/ScoopInstaller/Extras/blob/master/bucket/github.json) makes reference to https://central.github.com/deployments/desktop/desktop/latest/GitHubDesktop-2.9.9-x64-full.nupkg. Might there be an issue with how this was packaged, perhaps?

Kind Regards,
Liam

**Comment by sergiou87** [comment] 2022-02-18 15:26
Oh, that's very interesting, thank you. Is  this the first time you install the app from Scoop?

If it is not, is it the first time `Check for Updates` fails like that for you?

**Comment by sergiou87** [comment] 2022-02-18 15:28
Looks like this problem is already known: https://github.com/ScoopInstaller/Extras/issues/2071

**Comment by celtic-coder** [comment] 2022-02-18 16:40
Hi Sergio (@sergiou87),

I have used Scoop to install / update the GitHub Desktop application for quite some time. I've never had any of the problems described in https://github.com/ScoopInstaller/Extras/issues/2071. 

Since I used only Scoop to update the application, I don't believe that I have ever used the `Check for Updates` button previously.

Kind Regards,
Liam

**Comment by sergiou87** [comment] 2022-02-23 15:12
Thank you for your report again, but since this seems very specific to Scoop and shouldn't cause any harm (`Check for Updates` should be used only in standalone installations), I'm gonna close this issue.

**Closed as completed by sergiou87** 2022-02-23 15:12 UTC
Labels: bug, priority-3

**Comment by celtic-coder** [comment] 2022-02-23 15:42
Okay, thanks for looking into the issue!
