### ISSUE TITLE
When deleting a branch, you can click multiple times on 'Delete', causing error popups

### ISSUE THREAD

**Issue by FreHu** [desktop/desktop#5331] opened 2018-08-03 12:10 UTC
The button 'Delete' should be disabled after first click, while deletion is in progress. Clicking n times will then show n-1 popups saying the branch was not found.

**Comment by FreHu** [comment] 2018-08-03 12:28
The button in question:
![githubdesktop_2018-08-03_14-10-38](https://user-images.githubusercontent.com/5097067/43642860-7047b1be-9729-11e8-8d88-5fc39dfc10dc.png)

**Comment by steveward** [comment] 2018-08-03 15:41
Thanks for the report @FreHu! I was able to reproduce this on my Windows 10 machine. The most I was able to get was three error dialogs with some fast clicks.

Here's the error dialog that is thrown for reference:

![screen shot 2018-03-8 at 11-33-02](https://user-images.githubusercontent.com/721500/43651699-174e4450-9711-11e8-8424-c12b15fb9111.png)

**Comment by adamreisnz** [comment] 2018-08-19 23:03
Having the same issue, I think it's because clicking the first time on the delete button doesn't do anything. Then, automatically, you think you maybe didn't click properly or the app lagged, so you click again which causes the error popup because the branch was in fact already deleted.

**Comment by shiftkey** [comment] 2018-08-20 11:14
@adamreisnz thanks for the update - #5371 should fix the blocking problem but I'm not sure why it took so long. Are you able to see any slow Git operations in the log around that time that might explain why it took so long?

**Comment by adamreisnz** [comment] 2018-08-20 11:42
No, the thing is I don't think any operations are still in progress.
The modal just doesn't go away, and remains visible, until I close it manually.

The branch does get deleted, both locally and on the remote.

**Comment by shiftkey** [comment] 2018-08-20 11:52
> The branch does get deleted, both locally and on the remote.

Maybe this is the clue - we don't surface any Git error if we're unable to delete the remote branch successfully.

I'll add that as a test case to #5371.

**Closed** 2018-08-28 17:48 UTC
Labels: bug
