### ISSUE TITLE
Cannot commit due to a Husky Error 

### ISSUE THREAD

**Issue by zahra-audacia** [desktop/desktop#18755] opened 2024-06-04 09:32 UTC
### The problem

This has happened to me and my colleague on the same day. Where we can't commit on github desktop due to this error. We have done the steps stated as in other issues https://github.com/desktop/desktop/issues/17385#issuecomment-1718170235, but they have not worked. We can both commit in command prompt or VS/VSC so we are unsure what the issue is. We have checked out environment variables etc. 

### Release version

Version 3.4.0

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Have husky implemented for checking commit messages 
2. Try to commit 

### Screenshots

![image](https://github.com/desktop/desktop/assets/111436128/2a47b4c2-b499-4bf2-a386-41ccebe638e7)

**Comment by fbastien** [comment] 2024-06-04 11:43
Probably a duplicate of #18739, isn't it?

**Comment by tidy-dev** [comment] 2024-06-04 11:45
Closed in favor of https://github.com/desktop/desktop/issues/18739

**Closed as completed by tidy-dev** 2024-06-04 11:45 UTC
