### ISSUE TITLE
Unable to authenticate when pushing from command line

### ISSUE THREAD

**Issue by jpgreninger** [desktop/desktop#4339] opened 2018-03-27 06:49 UTC
## Version

* GitHub Desktop: 1.1.1

* Operating system: Windows 10 1709 Build 16299.248

## Steps to Reproduce

1. Open the Command Prompt
2. 'git push origin --tags --force'

### Expected Behavior

Tags are pushed to origin and updated (used to happen)

### Actual Behavior

Authentication error

**Comment by jpgreninger** [comment] 2018-03-27 06:50
[2018-03-27.desktop.production.log](https://github.com/desktop/desktop/files/1850717/2018-03-27.desktop.production.log)

**Comment by shiftkey** [comment] 2018-03-27 11:01
@jpgreninger thanks for the feedback.

We no longer include a "Git Shell" experience like we did with the classic Windows app, so the standalone Git for Windows you're running is likely trying to find it's own credentials from the Windows credential store.

Does it prompt you to sign in? Or does it go straight to displaying an error?

**Comment by jpgreninger** [comment] 2018-03-27 16:22
I get a pop-up to sign in which fails. Then it also asks for the information from the command line which also fails.  How do you push force tags from the desktop app if not from the command line?


________________________________

**Comment by shiftkey** [comment] 2018-03-27 20:13
> I get a pop-up to sign in which fails. Then it also asks for the information from the command line which also fails.

Please ensure you are running an up to date version of [Git for Windows](https://gitforwindows.org), as [GitHub disabled support for weak cryptographic protocols](https://blog.github.com/2018-02-02-weak-cryptographic-standards-removal-notice/) back in February, which might be the cause of these errors.

**Comment by jpgreninger** [comment] 2018-03-27 20:38
Ok, I'll try it out when I get a chance


________________________________

**Comment by shiftkey** [comment] 2018-03-27 20:48
I'm going to close this out as an external issue. [This note](https://github.com/Microsoft/Git-Credential-Manager-for-Windows#notice-experiencing-github-pushfetch-problems) has more details about the situation, and the errors themselves that occur while fetching/pushing are very vague:

```
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': 
```

**Closed by shiftkey** 2018-03-27 20:48 UTC

**Comment by jpgreninger** [comment] 2018-03-28 06:18
Your suggestion worked.  Thanks!


________________________________
