### ISSUE TITLE
Allow the setting of a favorite flag on repos in the list

### ISSUE THREAD

**Issue by DanaMW** [desktop/desktop#11843] opened 2021-03-21 08:37 UTC
In the repo list it would be nice to allow the setting of "favorites". The recent list constantly changes so it would be useful to be able to set favorites to be at the top of the list of the repos.
When I go down the list to make sure I am updated or when i work on a couple of repos the ones I work on normally get removed from the recent list. With a settings flag of favorite I can keep the repos I work with most at the top. 
Thank you for your consideration..

**Comment by Rexogamer** [comment] 2021-03-21 15:38
Hey! This is a duplicate of #8183, which unfortunately currently isn't being worked on - however, they may look at this again in the future

**Comment by tidy-dev** [comment] 2021-03-22 11:10
@DanaMW Thank you for the suggestion! As @Rexogamer has already linked this to the feature we are tracking under and explained is not currently being considered at this time (Thank you! @Rexogamer). I am going to close this one out.

**Closed as completed by tidy-dev** 2021-03-22 11:10 UTC
