### ISSUE TITLE
Version 0.7.1 renamed the EXE and broke my shortcuts

### ISSUE THREAD

**Issue by xt0rted** [desktop/desktop#2374] opened 2017-08-01 01:09 UTC
### Description

With version 0.7.0 the `.exe` under `%LOCALAPPDATA%\GitHubDesktop` was `GitHub Desktop.exe`. After today's update to 0.7.1 my shortcut doesn't open GitHub Desktop because it's been renamed to `GitHubDesktop.exe`. There are also two copies of the application "installed" though the old version doesn't open or do anything.

### Version

**GitHub Desktop version:** 0.7.1
**OS version:** Win10 CU

### Steps to Reproduce

1. With 0.7.0 installed open the application & pin it to your task bar
1. Update to 0.7.1
1. Try using your pinned shortcut and watch nothing happen

**Expected behavior:** Pinned shortcuts should continue to work

**Actual behavior:** Pinned shortcuts continued pointing to the old EXE which wasn't removed, doesn't open, and doesn't give any type of alert as to why it immediately closed

**Reproduces how often:** All day long

![image](https://user-images.githubusercontent.com/831974/28804829-ac855b44-7633-11e7-95b9-f42358e86196.png)

![image](https://user-images.githubusercontent.com/831974/28804892-58511ed6-7634-11e7-8382-bf494ee74c54.png)

Contents of `SquirrelSetup.log` from the time of the 0.7.1 update:
```
2017-07-31 14:17:28> CheckForUpdateImpl: Using existing staging user ID: c2b309d5-b771-54b4-858b-783d44928eab
2017-07-31 14:17:28> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=0.7.0&env=production
2017-07-31 14:17:28> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=0.7.0&env=production&id=GitHubDesktop&localVersion=0.7.0&arch=amd64
2017-07-31 14:17:28> FileDownloader: Downloading file: https://central.github.com/api/deployments/desktop/desktop/latest/GitHubDesktop-0.7.1-full.nupkg
2017-07-31 14:17:31> ApplyReleasesImpl: Writing files to app directory: C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1
2017-07-31 14:17:31> LogHost: Rigging execution stub for lib/net45/GitHubDesktop_ExecutionStub.exe to C:\Users\brian\AppData\Local\GitHubDesktop\GitHubDesktop.exe
2017-07-31 14:17:33> LogHost: Rigging execution stub for lib/net45/resources/app/git/mingw64/libexec/git-core/GitHub.Authentication_ExecutionStub.exe to C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\resources\app\git\mingw64\libexec\GitHub.Authentication.exe
2017-07-31 14:17:34> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\GitHubDesktop.exe]
2017-07-31 14:17:35> ApplyReleasesImpl: Starting fixPinnedExecutables
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Command Prompt.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Firefox Developer Edition.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: GitHub Desktop.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Google Chrome Canary.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: LINQPad 5.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Microsoft Azure Storage Explorer.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Microsoft SQL Server Management Studio.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Notepad2 x64.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Opera Browser.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Outlook 2016.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Visual Studio 2015.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Visual Studio 2017.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Visual Studio Code.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Wavebox.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Examining Pin: Windows PowerShell.lnk
2017-07-31 14:17:35> ApplyReleasesImpl: Processing shortcut 'C:\Users\brian\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\GitHub Desktop.lnk'
2017-07-31 14:17:35> ApplyReleasesImpl: Old shortcut target: 'C:\Users\brian\AppData\Local\GitHubDesktop\GitHub Desktop.exe'
2017-07-31 14:17:35> ApplyReleasesImpl: New shortcut target: 'C:\Users\brian\AppData\Local\GitHubDesktop\GitHub Desktop.exe'
2017-07-31 14:17:35> ApplyReleasesImpl: Old iconPath is: 'C:\Users\brian\AppData\Local\GitHubDesktop\GitHub Desktop.exe'
2017-07-31 14:17:35> ApplyReleasesImpl: Finished shortcut successfully
2017-07-31 14:17:35> ApplyReleasesImpl: Fixing up tray icons
2017-07-31 14:17:35> ApplyReleasesImpl: cleanDeadVersions: for version 0.7.1
2017-07-31 14:17:35> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.7.0
2017-07-31 14:17:35> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.7.1
2017-07-31 14:41:47> Program: Starting Squirrel Updater: --processStartAndWait GitHub Desktop.exe
2017-07-31 14:41:47> Program: Want to launch 'C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\GitHub Desktop.exe'
2017-07-31 14:41:47> Program: File C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\GitHub Desktop.exe doesn't exist in current release
2017-07-31 14:41:47> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

**Comment by TheGrimSilence** [comment] 2017-08-01 01:19
Same here

**Comment by TheGrimSilence** [comment] 2017-08-01 01:23
I have to manually change the shortcut link on my taskbar. For some reason opening the new Desktop executable still, sets the shortcut link to the old one. Which for whatever reason the old executable refuses to fire on click.

**Comment by shiftkey** [comment] 2017-08-01 11:11
I think this is the same root cause as #2370 but I'll get @joshaber to confirm this when he's around.

I installed `0.7.2` and that has the right path again, so I think this is just restricted to that update:

<img width="447" src="https://user-images.githubusercontent.com/359239/28822785-fe9296ec-7690-11e7-830f-5105935e5d45.png">

**Comment by shiftkey** [comment] 2017-08-01 11:46
Yep, this was a necessary change due to how Squirrel.Windows applies delta packages. See #2239 for these changes:

> The Windows exe name is now `GitHubWindows` (no space). This is because Squirrel.Windows can't diff files with spaces in their names, so it'd always fall back to downloading the full update. Our shortcut is still created as `GitHub Desktop`. 

I'm not sure what this means for the desktop shortcut though. 🤔

**Comment by shiftkey** [comment] 2017-08-01 11:52
@xt0rted @TheGrimSilence did you have any issue with the original shortcut?

I'd need to read over the Squirrel.Windows source to see if it cares at all about the folder where pinned shortcuts are stored: `%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\` but my gut feeling is that it's not the case...

**Comment by shiftkey** [comment] 2017-08-01 12:10
As discussed with @grokys just now, a workaround to get back to a happy place is to clear the pinned shortcut and pin to the taskbar again - the start menu should be fine.

**Comment by shiftkey** [comment] 2017-08-01 13:25
Alright, I can spot at least two issues that the renaming of the .exe had flow-on effects for:

 - as part of rewriting the shortcuts, the new [target](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs#L488) is derived from the icon for the current shortcut:

```c#
target = Path.Combine(rootAppDirectory, Path.GetFileName(shortcut.IconPath));
```

As the shortcut points to the old executable at this point, a pinned taskbar shortcut will remain broken. Our code [to update the desktop shortcut (if found)](https://github.com/desktop/desktop/blob/master/app/src/main-process/squirrel-updater.ts#L110-L117) avoids this, because it's run in the context of the updated app.

 - when the app does `autoUpdater.quitAndInstall()` it spawns `Update.exe` to [relaunch itself](https://github.com/electron/electron/blob/master/lib/browser/api/auto-updater/squirrel-update-win.js#L81):

```js
const exeName = path.basename(process.execPath)
...
spawnUpdate(['--processStartAndWait', exeName], true, function () {})
```

It's not aware that the executable has been renamed, so it doesn't appear to have been updated. That's this error:

```
2017-07-31 14:41:47> Program: Starting Squirrel Updater: --processStartAndWait GitHub Desktop.exe
2017-07-31 14:41:47> Program: Want to launch 'C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\GitHub Desktop.exe'
2017-07-31 14:41:47> Program: File C:\Users\brian\AppData\Local\GitHubDesktop\app-0.7.1\GitHub Desktop.exe doesn't exist in current release
2017-07-31 14:41:47> Unhandled exception: System.ArgumentException: Value does not fall within the expected range.
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

**Comment by TheGrimSilence** [comment] 2017-08-01 13:29
@shiftkey you talk a lot 😂 but yeah it breaks the shortcut's link. Opening the new version and repinning to the task bar still gives the wrong path but that may only be me. OS is W10Px64

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiftkey** [comment] 2017-08-01 13:32
> Opening the new version and repinning to the task bar still gives the wrong path but that may only be me.

If this is what you have for the newly pinned shortcut, you're up to date (and the shortcut should launch).

<img width="376" src="https://user-images.githubusercontent.com/359239/28827614-85e8b2a8-76a4-11e7-8115-432e3d275364.png">

If not, please share more about your setup.

**Comment by TheGrimSilence** [comment] 2017-08-01 13:33
Still getting GitHub Desktop.exe in my path for whatever reason but that seems as it'd be a W10 Issue?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiftkey** [comment] 2017-08-01 13:35
@joshaber feels on polishing the update process more within the app? I'm not sure what we can do given Electron won't relaunch the process correctly once the exe has been renamed, and getting anything into Squirrel will take time, but maybe we can update the shortcuts in the taskbar too?

**Comment by shiftkey** [comment] 2017-08-01 13:37
@TheGrimSilence if the source shortcut is broken, pinning won't change that behaviour. But I think we've got enough information here to confirm where the problem is.

**Comment by joshaber** [comment] 2017-08-01 13:56
>feels on polishing the update process more within the app? [...] maybe we can update the shortcuts in the taskbar too?

Is that a problem outside of this issue? I'm hesitant to spend time on something that's a one-time issue for the beta.

**Comment by shiftkey** [comment] 2017-08-01 14:03
> Is that a problem outside of this issue?

Given we handle updating the desktop shortcut in-app (in theory Squirrel.Windows does this too, but here we are) one could point to that as a precedent for doing that for the taskbar (again, if it exists there).

**Comment by joshaber** [comment] 2017-08-01 14:16
Well, so, we're not really doing it ourselves, we're shelling out to Squirrel which does it: https://github.com/desktop/desktop/blob/c01ef5386b3f8f835dd73de679f77d2df0ee3aef/app/src/main-process/squirrel-updater.ts#L111

But I guess I'm still confused... is updating the taskbar a problem which exists separate from this issue?

**Comment by TheGrimSilence** [comment] 2017-08-01 14:52
Updating the taskbar lies within the update code itself if I'm not mistaken. However if it's a permanent change to GitHubDesktop.exe then there's not that much of a use to change the code. Maybe backup code to ensure the path is accurate but besides that the path is set to no space from here and shouldn't be an issue further.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiftkey** [comment] 2017-08-01 15:52
> Well, so, we're not really doing it ourselves, we're shelling out to Squirrel which does it: 

Sure, but the fact we're doing this manually in the app stands out to me, and suggests we shouldn't rely on Squirrel to do this implicitly when updating.

> But I guess I'm still confused... is updating the taskbar a problem which exists separate from this issue?

Let me take another shot at this. We're checking and updating the shortcut in two places currently in the app when it receives the "--squirrel-updated" event:

 - the start menu
 - the desktop (only if it exists)

This feels like we should be performing the same "check-and-update" if a shortcut is found in the taskbar.

**Comment by joshaber** [comment] 2017-08-01 16:16
>This feels like we should be performing the same "check-and-update" if a shortcut is found in the taskbar.

Perhaps? I guess it's still not clear to me if this is an actual problem separate from this issue?

**Comment by shiftkey** [comment] 2017-08-01 17:00
> Perhaps? I guess it's still not clear to me if this is an actual problem separate from this issue?

How about we review this after the next update? I'd like to confirm the inbuilt Squirrel stuff will update this taskbar icon between updates, and it's not just the rename that's to blame.

**Comment by shiftkey** [comment] 2017-08-01 18:39
Closing this out as I think we trust Squirrel.Windows enough to update the taskbar shortcut when we don't change the name of the executable.

Will retest this upgrade process with `0.7.3` and see if we still encounter issues.

**Closed by shiftkey** 2017-08-01 18:39 UTC
Labels: bug

**Comment by xt0rted** [comment] 2017-08-01 19:46
After installing 0.7.1 I manually updated the target exe name to remove the space. Then it auto updated to the beta of 0.7.3 and the start in path was correctly updated to `app-0.7.3-beta0`.

**Comment by shiftkey** [comment] 2017-08-01 20:14
@xt0rted we don't trust `0.7.1` because it thinks it's on the beta channel. Please test out `0.7.2` as `0.7.3` will be the next stable release.
