### ISSUE TITLE
GitHub Desktop names repository incorrectly and opens wrong repository

### ISSUE THREAD

**Issue by jkafkaris** [desktop/desktop#3855] opened 2018-01-25 02:02 UTC
### Description

GitHub Desktop names repository incorrectly and opens wrong repository. I have 2 repos on Github Enterprise, one named VertigoRealityVive and the other VertigoReality. If I clone both to my PC they are both named VertigoRealityVive. Uninstalling GitHub Desktop and removing localdata then had both repos receive the name VertigoReality.

### Version

1.0.12

**GitHub Desktop version:** [1.0.12]

**OS version:** [Windows 10]

### Steps to Reproduce

1. Clone repo VertigoRealityVive
1. Clone repo VertigoReality
1. both repose then have same name in GitHubDesktop - though it only happens with these 2 repos and initially VertigoRealityVive was named VertigoReality, but I changed it on GitHub Enterprise settings.

**Expected behavior:** 

I expect each repo to be named what they are on GitHub Enterprise, or at least give me a way to change it.

**Actual behavior:** 

Both are named the same. They do commit to correct repo, but selecting "View on GitHub" they go to the same repo - so one is correct and one is not.

Log attached

[2018-01-25.desktop.production.log](https://github.com/desktop/desktop/files/1662310/2018-01-25.desktop.production.log)

**Comment by iAmWillShepherd** [comment] 2018-01-26 17:03
Thanks for taking the time to open an issue! 🙇 

I've sent you an email with the same instructions in case you have data you want to remain private.

I need to know the state of your database, I have a hunch on what the issue could be, but I’d like confirmation.

To get to your database:

1. Select `View -> Toggle Developer Tools` in the application menu
1. Select the `Application` tab in Chrome Dev Tools _(the tab may be located in a popup menu identified the >> icon)
1. Expand the `IndexDB` tree node on the left-most column
1. Expand the `gitHubRepositories` object store
1. Select the item labeled `cloneURL`
1. Expand the value object (right-most column) for the two repositories you are having issues with
1. Take a screenshot

Additionally, select the item labeled name from the `gitHubRepositories` object store and take a screenshot of that as well. If you have multiple keys with the same name, expand all of their value objects.

![gitHubRepositories.cloneURL](https://user-images.githubusercontent.com/1715082/35451243-336f20c8-0288-11e8-9bf1-dc196ac1522d.png
![gitHubRepositories.name](https://user-images.githubusercontent.com/1715082/35451309-64eb09d2-0288-11e8-8c0b-677871d18170.png)

**Comment by AmeeRamy** [comment] 2018-01-26 17:27
I am an Arab man who does not speak or understand English
Please do not email me anymore
Thank you


________________________________

**Comment by jkafkaris** [comment] 2018-01-31 11:39
I followed the above step and sent the information, but after the weekend, I reinstalled, deleted local repos and cloned again from online repos and it appeared to fix my issue. Thanks.

**Comment by sarah37** [comment] 2019-04-20 13:33
I'm having the same issue - my two repos pax and pax_old both keep showing up as pax_old. I've tried all sorts of combinations of reinstalling, deleting all the databases in the Desktop app via dev tools, re-cloning from Github both through desktop and the console, but no luck. Is there any fix for this by now? It almost seems like the reference to pax_old is buried somewhere in the repo itself because I deleted all the Desktop databases and the issue persisted after re-adding the repo (no matter if I re-clone, or add a local copy).

**Comment by notthatnathan** [comment] 2019-07-18 12:30
Still happening. If you rename a repo on Github (`myrepo` -> `myrepo-old`), then make a new `myrepo` locally and push, it is renamed in the app to `myrepo-old`.

I've cleared the entries in the app DB, recloned from github.com (which shows the names correctly), and even deleted `.git` in the new repo and re-inited. Nothing works.

Seems like a regression, since I've done this many times before ("hey, I should use [new framework] for [never-ending side project]") and not had this issue.

**Comment by tierninho** [comment] 2019-07-18 19:19
@nathansobo and @sarah37 I tested your scenario and got the same results. 

Be sure to check the remote origin is correct. I had to manually change mine to match the "new" repo name. Go to Repository menu > Repository Settings > Remote

From `https://github.com/tierninho/Repo123` ---> `https://github.com/tierninho/Repo123-old`

At this point I am going to reopen this issue and label as a bug until a fix arrives.

Side note: this issue feels familiar and there may be another open issue on it

**Comment by LordPeaches** [comment] 2019-08-15 21:05
Hello. I am having this same issue. Here are the steps I went through:

I originally had a GitHub repo named 'MysteryCache'. I renamed the Repo to 'Candles', and changed the file name locally. GitHub Desktop didn't update the name until the next day. Today I created a new repo locally called 'MysteryCache' and pushed that to GitHub. Now GitHub Desktop shows I have two repos, both named 'Candles'. It also keeps telling me I need to constantly push my branch to the original Candles repo, even though my branch has been published for over a week now. Kinda difficult to tell which repo I am working in.

**Comment by tierninho** [comment] 2019-08-15 21:38
@LordPeaches Thanks for the details. So it is a 3-step process.

1. rename repo of GitHub
2. change name on local
3. change remote repository (Go to Repository menu > Repository Settings > Remote)

You can verify your changes by typing this is the terminal for each repo: `git remote -v`. It should show something like:

`origin	https://github.com/tierninho/Candles.git (fetch)`
`origin	https://github.com/tierninho/Candles.git (push)`

and 

`origin	https://github.com/tierninho/MysteryCache.git (fetch)`
`origin	https://github.com/tierninho/MysteryCache.git (push)`

**Comment by probablycorey** [comment] 2019-08-15 23:22
I was able to verify this behavior and both repos have this as the output of `git remote -v`

```
origin	https://github.com/evil-probablycorey/Candles.git (fetch)
origin	https://github.com/evil-probablycorey/Candles.git (push)
```

I'm going to dig int why this happens.

**Comment by LordPeaches** [comment] 2019-08-16 04:00
Hi @tierninho , I noticed that even though both of the repos show up as under the name 'Candles', they both were pushing to my 'MysteryCache' repository instead. This is why one of my branches was getting pushed to the wrong repository. I have now fixed it, but the naming issue is still there.

**Comment by tierninho** [comment] 2019-08-16 17:47
@LordPeaches Appreciate the additional comments. 👍 Definitely some bugs that need to be addressed.

**Comment by probablycorey** [comment] 2019-08-16 22:30
I have a feeling there might be multiple bugs lurking in here. But I'm going to describe what I think is the main bug.

1. You create a repository called `yellow` via Desktop and push it to github.com
2. Now go to the `yellow` repo on github.com and rename it to `black`
3. Go back to desktop and select a different repository and then switch back to the `yellow` repository.
4. Notice with pleasure that the repo's name is now `black`
5. Go to the command line and type `git remote -v`

**What I'd expect** 
I'd expect to see the origin set as `https://github.com/your-clever-name/black.git (fetch)`

**What I actually see**
The origin is still set to `https://github.com/your-clever-name/yellow.git (fetch)`

This is normally fine because github.com's routing is clever and `https://github.com/your-clever-name/yellow.git` will forward to `https://github.com/your-clever-name/black.git`. But if you create a new repo called `yellow` everything is screwed up.

I _think_ when desktop detects a repo name change it should update git's origin. But I want to verify this assumption with @outofambit or @niik who are the experts on this.

**Comment by outofambit** [comment] 2019-08-19 23:31
@probablycorey i agree with this write-up one hundred (100) percent! here's a related issue we encountered before in case that extra context helps! #7455 (its a little more complicated since it involves also moving repos between users/orgs)

**Comment by LordPeaches** [comment] 2019-08-20 16:06
Any temporary workaround? I deleted GitHub desktop and reinstalled, and the issue persisted. I really don't want to have to delete the repositories from GitHub and reupload them.

**Comment by pkamat95** [comment] 2019-08-21 03:16
Had the same issue too, but on Mac. Deleting the GitHub Desktop folder in ~/Library/Application Support/ and reinstalling the app worked for me (where reinstalling the app alone wouldn't). Not sure what the equivalent would be on Windows though

**Comment by LordPeaches** [comment] 2019-08-23 20:47
This worked, going into /appdata/roaming and deleting the GitHub Desktop folder, as well as my local repositories, seemed to fix the issue.

**Comment by outofambit** [comment] 2020-03-16 17:20
This is closed by #9138, which is currently available on beta and slated to go out in our next production release.

**Comment by ginagr** [comment] 2020-04-10 14:06
I am still facing this issue with the 2.4 release

**Comment by ginagr** [comment] 2020-04-10 14:08
![image](https://user-images.githubusercontent.com/16846028/78996690-1ed39800-7b13-11ea-8435-2c05d76d096d.png)
 I changed a repo name and then made a new one with the same name and when attempting to clone it locally with GitHub Desktop, it won't update to the new repo.

**Comment by steveward** [comment] 2020-04-10 14:48
@ginagr could you upload your log file? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. Thanks!

**Comment by ginagr** [comment] 2020-04-10 14:58
[2020-04-10.desktop.production.log](https://github.com/desktop/desktop/files/4462071/2020-04-10.desktop.production.log)

The steps taken:

1. Changed repo 'arammu' to 'arammu-app'
2. Created new repo 'arammu'
3. Attempted to clone repo 'arammu' with Github Desktop
4. Github Desktop clones 'arammu-app' instead

Thank you for the quick reply!

**Comment by marcevrard** [comment] 2020-04-16 14:12
I could solve the issue by deleting GitHub Desktop catch data:
`rm -r "~/Library/Application Support/GitHub Desktop/Cache"`
Then restart GitHub Desktop.

**Comment by steveward** [comment] 2020-04-16 14:38
@ginagr the log file you uploaded indicated you are on v2.4 -- this bug was fixed in v2.4.1 If you update to the latest version you should no longer encounter this issue.

**Comment by ginagr** [comment] 2020-04-16 17:02
@steveward  yes I have tried multiple times and have double checked I have 2.4.1 
![image](https://user-images.githubusercontent.com/16846028/79484756-2519b680-7fe2-11ea-9b01-83d2bc902407.png)

However, I followed @marcevrard 's suggestion and deleted the cache and was able to add the existing repo now without issues.

**Comment by CWKSC** [comment] 2020-04-17 17:03
I have the same problem as the wrong repository URL link and repository name of GitHub desktop, but correct git commit and link to correct local folder.
Same,  I solved the problem by followed @marcevrard 's suggestion and deleted file of ...\AppData\Roaming\GitHub Desktop\Cache

**Comment by shaneparsons** [comment] 2020-05-04 15:02
I also just had this happen in 2.4.3

**Comment by Twinbird24** [comment] 2020-06-03 02:33
This is happening to me in **2.5.0** as well. marcevrard's suggestion of deleting GitHub Desktop cache data and restarting the app fixed it for me.

**Comment by grondag** [comment] 2020-06-12 02:43
Happened to me today on 2.5.2. [#3855](https://github.com/desktop/desktop/issues/3855#issuecomment-614678594) fixed.

**Comment by Gnastw** [comment] 2020-06-30 13:54
Happened to me today on 2.5.3, fixed !
Process : remove repo, delete cache, restart github and clone.

**Comment by lukasgabriel** [comment] 2020-07-16 08:00
Encountered this exact issue on 2.5.3. 
After following the instructions in this thread and deleting all files in the GitHub Desktop Cache, the problem appears to be fixed.

**Comment by gnowland** [comment] 2020-08-05 06:36
Happened to me just now - so frustrating, took 20 minutes of renaming directories and renaming/re-cloning repo on github before I found this thread. I think the clear cache function should at least be surfaced in the github desktop preferences/settings advanced pane...

**Comment by trevyn** [comment] 2020-09-27 12:56
Just hit this on 2.5.5 after renaming a repo and then creating a new repo with the old name. Removing `~/Library/Application Support/GitHub Desktop/Cache` appears to have worked.

@outofambit @steveward Should this issue be re-opened?

**Comment by steveward** [comment] 2020-09-28 12:42
I'm going to reopen this since we've continued to have reports of this occurring.

**Comment by reganjohnson** [comment] 2020-10-01 03:57
Same issue here - removing cache solves the problem.
"rm -r ~"/Library/Application Support/GitHub Desktop/Cache"

**Comment by laflier** [comment] 2020-11-13 14:24
I just ran into the same problem this morning with GitHub Desktop 2.5.7 when it became clear that two projects were going their separate ways. Here's what I did:

1. Renamed a repository
2. Copied the local repository, removed the GIT files/folders, and attempted to create a new repository in Desktop with a different name but it came in with the same name as before
3. Uploaded the new repository to GitHub.com with a different name and then deleted the repository in Desktop
4. Cloned the new repository from GitHub.com and it still came into Desktop with the old name.

Removing the cache solved it.

**Comment by omginput** [comment] 2020-11-25 10:16
Because everyone was talking about *nix systems:
Here is the cache under Windows C:\Users\ <your_user> \AppData\Roaming\GitHub Desktop\Cache
Delete all the files in there.

**Comment by jackjt8** [comment] 2021-02-05 21:57
Unfortunately deleting the application cache from `%appdata%\Roaming\GitHub Desktop\Cache` did not solve the issue. It still seems to be confusing repos with the same name.

**Comment by jnsmelinda** [comment] 2021-02-21 01:48
I have the same issue using the latest version (`2.6.3`) on MacOS.
Closing the application and deleting the cache directory solves the issue (`~/Library/Application\ Support/GitHub\ Desktop/Cache`).

**Closed** 2021-05-28 11:11 UTC
Labels: bug, priority-2

**Comment by mrkingfoxx** [comment] 2021-06-08 10:08
Do you guys have a wonderful morning glad to finally see some light￼

**Comment by jcamato** [comment] 2021-07-30 09:56
> I have the same issue using the latest version (`2.6.3`) on MacOS.
> Closing the application and deleting the cache directory solves the issue (`~/Library/Application\ Support/GitHub\ Desktop/Cache`).

I had the same issue this week. Following @jnsmelinda advice solved it for me. Thank you!

**Comment by dannyjim-ml** [comment] 2021-08-08 03:30
I'm on 2.9.0 on Windows 10 and just had the same problem, closing the application and going into appdata\Roaming\GIthub Desktop\Cache and deleting all the contents ended up fixing it.

**Comment by trevyn** [comment] 2021-08-08 04:10
@steveward @tidy-dev Looks like this needs to be reopened again. :)

**Comment by asantech** [comment] 2022-07-04 08:34
hi, i had a repo name "beverage-shop", then 
1. I changed the repo name to "beverage-shop-nextjs" in github.com, and removed the "beverage-shop" repo from github desktop (because the name didn't get changed here automatically) 
2. I added the local directory to github desktop by "add local repository" and got the "beverage-shop-nextjs" repo name (which is correct)
3. I created a new repo named "beverage-shop" in github.com and then cloned the repo to my local folder by "git clone <...>" command
4. then I added the repo (the local directory) to github desktop by "add local repository"
5. then I got a repo named "beverage-shop-nextjs" (which is not correct and should be "beverage-shop"), 

so now I have two repos named "beverage-shop-nextjs", the repo works fine (I mean git operation) and contains the right files, but the same name they have makes me confused. 
this equal name problem is only in github desktop, everything in github.com is ok

**Comment by Suvraneel** [comment] 2022-07-31 21:53
How has it been 3years without a fix  :octocat: 

# Issue replication  
See all comments above this

# Config
Win11 x64

---

Not fixed on Reinstalls etc
 Also, FYI it works perfectly with **Git Bash** but not with Github Desktop

**Comment by Pietro228** [comment] 2023-02-13 14:39
2023 and still not fixed :)) Please reopen this issue, it's NOT fixed

**Comment by augiwan** [comment] 2023-04-13 14:37
The issue still exists, please re-open.

**Comment by noamvaza** [comment] 2023-07-11 16:00
WIn V3.2.6 reproduced

> removing cache solves the problem. "rm -r ~"/Library/Application Support/GitHub Desktop/Cache"

**Comment by ShetlandJ** [comment] 2023-08-28 09:08
Removing the `Cache` folder does not solve the issue. Issue reproduced on OSX, Ventura

**Comment by iyzyi** [comment] 2024-05-25 12:45
> 我在 Windows 2.9.0 上使用 10 并且遇到了同样的问题，关闭应用程序并进入 appdata\Roaming\GIthub Desktop\Cache 并删除所有内容最终修复了它。

Useful!

**Comment by crontab** [comment] 2025-02-02 21:12
Version 3.4.15 (macOS), still happening. Removing `~/Library/Application Support/GitHub Desktop` eventually fixes the issue but keep in mind the app will start in clean state, you'll need to reconfigure and add all your repositories again.

**Comment by MaddyMurder** [comment] 2025-10-25 19:25
Issue still present on version 3.5.3 (Windows 11). The easiest fix is to remove the cache, and then to select the repository in Github Desktop. On Windows Its located in `%appdata%\GitHub Desktop\Cache`.

> Version 3.4.15 (macOS), still happening. Removing `~/Library/Application Support/GitHub Desktop` eventually fixes the issue but keep in mind the app will start in clean state, you'll need to reconfigure and add all your repositories again.

I don't think this is necessary, just removing the cache worked fine for me.

**Comment by MaddyMurder** [comment] 2025-10-25 19:30
Just noticed this is marked as completed. I don't think it should be. The issue still requires either deleting cache or cloning the repository again, which is not obvious to users encountering the bug.

**Comment by cedx** [comment] 2026-02-04 10:05
+1 I also encountered this problem today. t would be handy to have some way to clear the cache from the UI.
