### ISSUE TITLE
Scrolling of image not working

### ISSUE THREAD

**Issue by jgwill** [desktop/desktop#8431] opened 2019-10-08 12:58 UTC
### Describe the bug

When an image displayed in the difference/history and is higher than the size of the screen, I can not scroll it up/down (the bug is Scrolling control are missing)

### Version & OS
Windows 10
### Steps to reproduce the behavior

1.  Add commit a 4000 height image
2. Change it
3. Commit again
4. Go to the history to see the difference

### Expected behavior

Scrolling capability.  Mouse wheel to move both image

### Actual behavior

Nothing happen

### Screenshots

Add screenshots to help explain your problem, if applicable.
![image](https://user-images.githubusercontent.com/23141173/66397371-acd69680-e9a9-11e9-95ad-4314fe8b820e.png)

**Comment by kuychaco** [comment] 2019-10-08 17:28
Thanks for the report @jgwill! I was able to repro this (on MacOS High Sierra 10.13.6). Filing as a bug 👍

**Comment by kuychaco** [comment] 2019-10-08 19:49
Actually this looks to be a duplicate of this #2480, with this [comment](https://github.com/desktop/desktop/issues/2480#issuecomment-451779032) capturing the overall issue.

Closing for now but happy to reopen if it turns out to be another underlying issue with images. Thanks for filing @jgwill!

**Closed by kuychaco** 2019-10-08 19:49 UTC
Labels: bug, priority-3
