### ISSUE TITLE
Github Desktop / White Screen of Death

### ISSUE THREAD

**Issue by behrsl25** [desktop/desktop#5858] opened 2018-10-09 15:40 UTC
## Description

I have been receiving the white screen of death in Github Desktop for about two weeks now. I tried all the workarounds found in the community pages and other questions. Some of the more frequent mentions that workd for other people but did not work for me were removing the latest app version in the C:\Users\YourName\DataApp\Local\GitHubDesktop, Alt-Space-X, Uninstall and Reinstall, and I even uninstalled and reinstalled the Python and R programs that I use Github for.

## Version

*GitHub Desktop:
1.4.0.0

* Operating system:
Windows 10 Home Edition
Version 1803
OS Build 17134.285

## Steps to Reproduce

Opening the program to a white screen. There are no steps beyond that.
### Expected Behavior

I expect the program to open
### Actual Behavior

I receive the white screen of death, as it is referred to

**Comment by billygriffin** [comment] 2018-10-09 15:43
Thanks for the report @behrsl25, and sorry you're having this issue. Since it seems likely to be a configuration-related problem, would you mind taking a look @desktop/support?

**Comment by behrsl25** [comment] 2018-10-09 16:01
404 This is not the webpage you are looking for.

**Comment by say25** [comment] 2018-10-09 16:56
@behrsl25 the support link is just a way to ping team members it isnt publicly accessible by design. They should reach out on this issue when they can.

**Comment by steveward** [comment] 2018-10-09 17:37
@behrsl25 I see you mentioned deleting `%LocalAppData%\GitHubDesktop` -- did you also delete the `%AppData%\GitHub Desktop`directory? Some users have had success resolving this by doing that.

- close Desktop 
- remove all the files in %APPDATA%\GitHub Desktop\
- launch Desktop again

Let us know if that helps.

**Comment by behrsl25** [comment] 2018-10-09 19:16
This let me get into the Desktop program. I reinstalled the app, and created a new repo location. I was able to rename my old files as old, and I'm now going to try and re-create what I need for school. Thank you for your suggestions!

**Comment by billygriffin** [comment] 2018-10-09 21:47
@behrsl25 Great to hear, and thanks @steveward! ❤️ I'm going to close since this seems to be resolved.

**Closed by billygriffin** 2018-10-09 21:47 UTC
Labels: more-information-needed

**Comment by liyouluo** [comment] 2018-12-25 09:03
Here's what I did,
1. close Desktop
2. remove all the files in %AppData\Roaming\GitHub Desktop
3. launch Desktop again
