### ISSUE TITLE
File list on the left is to narrow (my opinion)

### ISSUE THREAD

**Issue by harald2013** [desktop/desktop#2292] opened 2017-07-20 19:27 UTC
### Description

File list on the left is to norrow, and it cannot be expanded very much. I would prefer to be able to expand it more, so that i see the directories as well.

Example attached.

**GitHub Desktop version:** [0.7.0]

**OS version:** [W10]

![2017-07-20_211132](https://user-images.githubusercontent.com/3505286/28435137-20c4d110-6d92-11e7-9950-5a352c4d6a18.png)

**Comment by joshaber** [comment] 2017-07-20 19:34
We agree!

This is a duplicate of https://github.com/desktop/desktop/issues/1588. Please follow that issue for further updates.

**Closed by joshaber** 2017-07-20 19:34 UTC
