### ISSUE TITLE
Grayed out menu items, "Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#6313] opened 2018-11-29 19:49 UTC
## Description

I opened the dev tools and saw a JavaScript error repeated several times:

![image](https://user-images.githubusercontent.com/82317/49247291-897faa00-f3dc-11e8-9473-65fd75e2c530.png)

## Version

* GitHub Desktop:

1.5.1-beta0

<img width="274" alt="screen shot 2018-11-29 at 1 42 29 pm" src="https://user-images.githubusercontent.com/82317/49247369-bcc23900-f3dc-11e8-9033-7aa5f7b9aa7e.png">
<img width="247" alt="screen shot 2018-11-29 at 1 43 27 pm" src="https://user-images.githubusercontent.com/82317/49247379-c481dd80-f3dc-11e8-8276-fa8e5d9d6600.png">
<img width="287" alt="screen shot 2018-11-29 at 1 43 37 pm" src="https://user-images.githubusercontent.com/82317/49247394-cb105500-f3dc-11e8-9372-04c83684f902.png">
<img width="256" alt="screen shot 2018-11-29 at 1 43 50 pm" src="https://user-images.githubusercontent.com/82317/49247410-d3689000-f3dc-11e8-9a10-97db153ebb64.png">

* Operating system:

macOS High Sierra 10.13.6

## Steps to Reproduce

I'm not sure. I have been using the app all day with no troubles. I pushed up a branch and hit Cmd-R in the app to open the 'new pull request' page for the branch in my browser, and noticed no such page opened. I tried it a few more times, no luck. That's when I went to the menu and saw the option was grayed out, along with many other options.

### Expected Behavior

Menu options would work and not be grayed out.

### Actual Behavior

Many menu options are grayed out, including "About GitHub Desktop" which seems like it should always work.

**Comment by iAmWillShepherd** [comment] 2018-11-29 22:58
What happens if you restart the app? Is that state persisted?

**Comment by cheshire137** [comment] 2018-11-30 16:05
Nope, exiting and reopening the app made it work normally again!

**Comment by shiftkey** [comment] 2018-12-17 14:58
Looking at the stack trace, it seems like this is the problem code:

```ts
function userWithLowerCase(user: IGitHubUser): IGitHubUser {
  return {
    ...user,
    email: user.email.toLowerCase(),
    login: user.login.toLowerCase(),
  }
}
```

The stack trace itself refers to line 518, which is the end of the function - but I think that's it's own confused way of saying the second case is undefined (based on my attempts to breakpoint here):

<img width="562" src="https://user-images.githubusercontent.com/359239/50094717-36826100-01ea-11e9-8d50-e2001bb53f9a.png">

Maybe we have some cached users which don't have a `login` defined that we then try to cache. @cheshire137 was this occurring with a GitHub repository?

**Comment by cheshire137** [comment] 2018-12-17 15:00
> was this occurring with a GitHub repository?

It was!

**Comment by cheshire137** [comment] 2019-02-25 19:26
This happens to me periodically. Exiting and relaunching the app fixes it. Here's some recent JS console output when it occurred:

![image](https://user-images.githubusercontent.com/82317/53362952-f7b30a80-3900-11e9-8dd6-1f615394dd2c.png)

**Comment by shiftkey** [comment] 2019-02-25 20:00
Marking as `priority-2` because of the impact (menus not working). The presence of `undefined` makes me think something at runtime is violating the type checks we have setup in this area.

**Comment by shiftkey** [comment] 2019-02-25 22:22
Thanks to @cheshire137 who helped test the build from #6940 and uncovered the problem commit involved with this.

I'll spare the person responsible who created the commit from being named, but this is the API response that GitHub returns to the app for this comment:

```
  ...
  "commit": {
    "author": {
      "name": "[redacted]",
      "email": "",
      "date": "2018-12-06T20:33:38Z"
    },
    "committer": {
      "name": "[redacted]",
      "email": "",
      "date": "2018-12-06T20:33:38Z"
    },
    ... 
  "author": {},
  "committer": {},
  ...
```

Because `author` is an empty object here (rather than `null`) this code path is tripped an object with an undefined `name` and `login`, and an empty `email` is returned:

https://github.com/desktop/desktop/blob/e5b1df648db9390c0e6c4309ff4edde3d00ad2e0/app/src/lib/stores/github-user-store.ts#L254-L268 

We can relax the type declarations coming from the API to reflect this newly-discovered anarchy:

```diff
diff --git a/app/src/lib/api.ts b/app/src/lib/api.ts
index 1f055b9e7..aa4ca569c 100644
--- a/app/src/lib/api.ts
+++ b/app/src/lib/api.ts
@@ -57,7 +57,7 @@ export interface IAPIRepository {
  */
 export interface IAPICommit {
   readonly sha: string
-  readonly author: IAPIUser | null
+  readonly author: IAPIUser | {} | null
 }
 
 /**
```

And this highlights the code we need to update to properly handle this case.

**Comment by shiftkey** [comment] 2019-02-26 17:07
After talking a bit more about this with @cheshire137 I wanted to clarify where my head is at:

 - #6945 is a fix for the known issue about caching an invalid user returned via the API
 - the menus being disabled might be a race condition that gets tripped in a way that's unrelated to #6945
    -  the app encounters a merge conflict and reports this to the user, disabling the menu while the popup is shown
    -  the user resolves the conflict via an external tool
    - the user switches back to the app, the popup is dismissed, but the menu remains disabled

My next steps are to try and trigger this problem state myself

**Comment by shiftkey** [comment] 2019-02-26 18:09
Dropping this down to `priority-3` unless I can get an easy, consistent reproduction of the disabled menus state.

**Comment by shiftkey** [comment] 2019-03-06 15:56
Alright, I've got what I believe is one reproduction of this issue:

 - run the app up in development mode (this will help later on)
 - have multiple repositories open in the app
 - for the first repository, trigger merge conflicts and see the dialog
 - dismiss the dialog, confirm the menus are working
 - switch to a different repository
 - restart the app
 - switch over to the Dev Tools, open the React tab, and wait

You want to keep an eye on the `currentPopup` root state - initially this is `null` :

<img width="387" src="https://user-images.githubusercontent.com/359239/53894043-c2e03b00-4005-11e9-941c-2d92c3af6205.png">
 
A couple of minutes after launching this will change to an object:

<img width="344"  src="https://user-images.githubusercontent.com/359239/53894268-341fee00-4006-11e9-97f8-dd0c1723f57b.png">

`29` is the enum code for `MergeConflicts`, and those branches are the ones associated with the earlier merge.

And despite there not being a popup you'll see some of the menu items are disabled:

<img width="1257" src="https://user-images.githubusercontent.com/359239/53894348-53b71680-4006-11e9-8ead-41122581a21e.png">

What happened? My guess:

 - background fetching kicked in
 - it looks at the status of our conflicted repository
 - ??? 
 - something sets `currentPopup` to try and resolve conflicts **despite not being the selected repository**.
- `menu-update` gets stuck in this code path and assumes all the menu items should be disabled

https://github.com/desktop/desktop/blob/8b3c9743dff19cd9c06151767cb7b9b511391134/app/src/lib/menu-update.ts#L300-L302

Now that I know how to trigger this I'll unpack what happens in `???` but for now I'm glad I can see this on my own end.

**Comment by shiftkey** [comment] 2019-04-01 15:17
We published a beta last week which I believe addresses these two identified issues, so for the moment I'm going to close this out as resolved pending it being available in production. If you spot something that you believe might be related to this, please open a fresh issue rather than add to the existing discussion.

**Closed by shiftkey** 2019-04-01 15:17 UTC
Labels: bug, priority-3
