### ISSUE TITLE
Commit ignores selected files and puts all changed files into commit

### ISSUE THREAD

**Issue by ChessMess** [desktop/desktop#7081] opened 2019-03-13 18:58 UTC
## Description

When committing changes all files are committed regardless of if they are selected to be committed or not.

## Version
1.6.4

* GitHub Desktop:

* Operating system:
10.14.1 Mojave

## Steps to Reproduce

1. Modify more than one file in the repo.
2. Note that multiple files are listed under changes column. 
3. Click the top checkbox to unselect all. 
4. Click a single file to commit, note one file has checkbox checked and no others do.
5. Press commit button

### Expected Behavior
Only selected file will be committed. 

### Actual Behavior
All files are committed, including unchecked files.

## Additional Information
I've uninstalled and re-installed, no change. Actually noted this in previous version but didn't report because I was sure it was a big enough bug someone would have reported it and expected the next version to clean it up.

In the attached log file I changed two files, only selected one to commit, and it committed both files.

### Logs
macOS logs location: `~/Library/Application Support/GitHub 
[2019-03-13.desktop.production.log](https://github.com/desktop/desktop/files/2963164/2019-03-13.desktop.production.log)

**Comment by mido1966** [comment] 2019-03-13 19:22
Alles ok  passssssssssst Dankeschön thanks

‏‫من الـ iPhone الخاص بي‬

‫في 13‏/03‏/2019 الساعة 7:59 م، كتب/كتبت ‏Chris Koerner ‏<notifications@github.com<mailto:notifications@github.com>>:‬

Description

When committing changes all files are committed regardless of if they are selected to be committed or not.

Version

1.6.4

  *   GitHub Desktop:

  *   Operating system:
10.14.1 Mojave

Steps to Reproduce

  1.  Modify more than one file in the repo.
  2.  Note that multiple files are listed under changes column.
  3.  Click the top checkbox to unselect all.
  4.  Click a single file to commit, note one file has checkbox checked and no others do.
  5.  Press commit button

Expected Behavior

Only selected file will be committed.

Actual Behavior

All files are committed, including unchecked files.

Additional Information

I've uninstalled and re-installed, no change. Actually noted this in previous version but didn't report because I was sure it was a big enough bug someone would have reported it and expected the next version to clean it up.

In the attached log file I changed two files, only selected one to commit, and it committed both files.

Logs

macOS logs location: `~/Library/Application Support/GitHub
2019-03-13.desktop.production.log<https://github.com/desktop/desktop/files/2963164/2019-03-13.desktop.production.log>

**Comment by ChessMess** [comment] 2019-03-13 19:25
This is on a Mac, not iPhone.

**Comment by Fedefreez** [comment] 2019-03-13 21:15
Have you tried to use git via terminal and commit only some files?
If yes, did it work?

**Comment by steveward** [comment] 2019-03-14 00:31
@ChessMess thanks for the report. I've so far been unable to reproduce this successfully. Would you be able to upload a short video or GIF showing this behavior?

**Comment by ChessMess** [comment] 2019-03-15 14:41
I recorded an example of this. It's important to note that I went to recreate this issue with a new repository and could not. However it always happens on this repo so I don't know what is different that is causing the issue. I could not attach the file directly here because it's larger than the 10Meg file limit (I used Apples screen recorder which made a 35M .mov file). So I uploaded it to my google drive and shared it with the link below:

https://drive.google.com/open?id=1FGH-ik-u4MwZYymGD-D04QQyX2lIfB8_

**Comment by ChessMess** [comment] 2019-03-19 14:20
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9343/54613132-94645600-4a30-11e9-9f9f-8c82d567cff9.gif)

**Comment by tierninho** [comment] 2019-03-20 22:21
I tried reproducing this, but could not after multiple attempts.

Just a guess, but there seems to be a lag in your Desktop use, which may be causing the UI to react slowly. Maybe a very large repo or something running in the background?

As no one else has experienced this and it only happens on one of your repos, I am going to close this for now. If you have any more details that are pertinent to this issue, please share and we can investigate further. Thanks.

**Comment by rgreenhalge** [comment] 2021-08-04 18:57
I have this same issue. All files are committed regardless of whether they are "checked" or not. This just stared happening with the last update. 

EDIT: this is in a RushStack monorepo. I have to think that is related. It still works correctly in my other repos. @chessmess were you able to resolve the issue in your repo?

**Comment by ChessMess** [comment] 2021-09-22 23:26
I had to wipe and re-clone the repo.

**Comment by sergiou87** [comment] 2021-09-23 07:33
@rgreenhalge does it happen with all repositories? Which specific version of GitHub Desktop are you using?

It's weird that it got fixed by re-cloning the repo. Is there anything "special" in your repository git config?

**Closed** 2021-09-30 07:54 UTC
Labels: more-info-needed

**Comment by EmadBeltaje** [comment] 2025-10-14 17:11
iam having this issue right now! 
hope u have been doing good through all those years @ChessMess 😁
