### ISSUE TITLE
"Ignore" context-menu option incorrectly adds carriage return to .gitignore

### ISSUE THREAD

**Issue by cpcallen** [desktop/desktop#3514] opened 2017-12-06 12:22 UTC
### Description

When I select a file to ignore from the list of modified files, and then choose "Ignore" from the context menu, the filename is appended to `.gitignore` as desired—but incorrectly suffixed with a `\r` (`^M`).

### Version

**GitHub Desktop version:** 1.0.10
**OS version:** Mac OS X El Capitan, 10.11.6 (15G17023)

### Steps to Reproduce

1. Modify a file in the current repository.
1. Select file in "Changes"; choose "Ignore" from context menu.
1. Open .gitignore with text editor.

**Expected behavior:** Filename of ignored file added to .gitignore, suffixed with `\n`.
**Actual behavior:** Filename of ignored file added to .gitignore, suffixed with `\r\n`.
**Reproduces how often:** Always?

### Logs

[2017-12-06.desktop.production.log](https://github.com/desktop/desktop/files/1535093/2017-12-06.desktop.production.log)

#### Additional Information

A suitable setting of `core.autocrlf` will ensure that the carriage return is not actually committed, but it should not have been added in the first place.

**Comment by niik** [comment] 2017-12-06 13:07
It seems like this was added in https://github.com/desktop/desktop/pull/2366 and that it intentionally uses CRLF when `autocrlf` and `safeclrf` are both set to true. @cpcallen Can you verify that both those options are set to true for your repository?

I'm gonna ask @shiftkey to elaborate on the reasoning behind this but I think this comment summarizes the intent: https://github.com/desktop/desktop/issues/1535#issuecomment-304631828

**Comment by cpcallen** [comment] 2017-12-06 13:27
@niik: Nope: neither option is set for my repository:

`$ git config --get core.autocrlf`
(no output)
`$ git config --get core.safecrlf`
(no output)

I applaud the intent of #2366, but if it is the cause of this behaviour then there appears to be a defect in the implementation.

**Comment by niik** [comment] 2017-12-06 13:36
Aha, thank you so much for that extra detail @cpcallen. 

> there appears to be a defect in the implementation.

I agree. So what's happening then is that we seem to be defaulting to CRLF regardless of platform when `autocrlf` _isn't_ set.

https://github.com/desktop/desktop/blob/dd54f83a269d6353b5b48ae90d923e6130845ad1/app/src/lib/stores/git-store.ts#L1101-L1106

And I can't see how this part would ever occur since we're concatenating the path prior to calling this function without a trailing newline.

https://github.com/desktop/desktop/blob/dd54f83a269d6353b5b48ae90d923e6130845ad1/app/src/lib/stores/git-store.ts#L1096-L1099

This logic certainly looks odd to me but to be fair I haven't spent much time looking into it it. At some point I'd expect ut to fall back into the platform behavior.

**Comment by j-f1** [comment] 2017-12-06 19:39
Maybe we should use something like [`detect-newline`](https://www.npmjs.com/package/detect-newline) to figure out what kind of newline to insert.

**Comment by shiftkey** [comment] 2017-12-06 22:10
@cpcallen Yeah, I'm a bit hazy on this too but I think @niik is on the money with this comment:

> So what's happening then is that we seem to be defaulting to CRLF regardless of platform when `autocrlf` _isn't_ set.

This fix was originally for a issue reported from someone using Windows, where it's far more common to see a system or global Git set `core.autocrlf` because of line ending shenanigans.

**Comment by shiftkey** [comment] 2017-12-06 22:30
@j-f1 it's probably worth exploring - [the method itself](https://github.com/sindresorhus/detect-newline/blob/master/index.js) is rather small, and doing our own inference about the working directory state of the `.gitignore` file seems reasonable

**Comment by shiftkey** [comment] 2017-12-06 22:45
Marking this as `help-wanted` as it's rather isolated and relatively low-risk.

The problem we have is in [this method](https://github.com/desktop/desktop/blob/master/app/src/lib/stores/git-store.ts#L1081-L1107) and the bit at the end:

https://github.com/desktop/desktop/blob/94643ad0920f5fbe094b461450c505184bef7a71/app/src/lib/stores/git-store.ts#L1101-L1108

That last part assumes `git config core.autocrlf` returns a value, but `getConfigValue()` returns `string | null`. I think we just need to handle `null` in here better, something like this:

```ts
// no core.autocrlf setting found, fallback to Git default behaviour
if (!autocrlf) {
  resolve(`${text}\n`)
  return
}

const linesEndInCRLF = autocrlf === 'true'
if (linesEndInCRLF) {
  resolve(`${text}\n`)
} else {
  resolve(`${text}\r\n`)
}
```

Feel free to `git blame` through this code and ask questions about what I was thinking - I'm pretty sure this is my code.

**Comment by shiftkey** [comment] 2017-12-07 00:11
As this is some low-hanging fruit and not a new regression, I'm going to drop it from the 1.0.x hotfixes and leave it for a bit if someone wants to try their hand at contributing a fix.

**Closed** 2018-02-02 20:17 UTC
Labels: bug
