### ISSUE TITLE
Branch Create time issue

### ISSUE THREAD

**Issue by siby05** [desktop/desktop#14964] opened 2022-07-13 09:49 UTC
### The problem

Branch Create time shown in app is not correct

### Release version

.0.4 (x64)

### Operating system

windows 10

### Steps to reproduce the behavior

1. Create a new branch in Repo
2. Fetch origin in DesktopApp
3. check the time of newly created Branch.

### Screenshots

![image](https://user-images.githubusercontent.com/17449518/178704917-310f8935-f252-4fbf-abd2-46e91c610e81.png)

### Additional context

here the branch is just created and when looks its showing created before 30+ mins
Note: System time is correct.

**Comment by tsvetilian-ty** [comment] 2022-07-13 10:10
Hey @siby05, the time you're referring to is based on the last commit in the branch and not the actual time the user created the branch. It's not a bug. Therefore, I will close the issue.

**Closed as completed by tsvetilian-ty** 2022-07-13 10:10 UTC
