### ISSUE TITLE
Required formatting for branch name not allowed

### ISSUE THREAD

**Issue by dbchristopher** [desktop/desktop#3599] opened 2017-12-13 22:55 UTC
### Description

The GitHub desktop app currently helps automatically formats the branch name with some variation of kebab-case. However, this is proving a little bit too strict for my company's workflow. We have some automatic actions that run when a name branch is suffixed with `--preview`. The desktop app automatically replaces multiple dashes with a single dash, so something like `branch-name--preview` becomes `branch-name-preview`.

I would very much appreciate it if the app allowed for a little bit more freedom with how users name their branches.

### Version

**GitHub Desktop version:** 10.0.10

**OS version:** MacOS 10.13.1

### Steps to Reproduce

1. Branch -> New Branch
1. Name a branch with--multiple--dashes---
1. The branch name will be reformatted to only allow one dash between words.

**Expected behavior:** More flexible naming conventions are allowed

**Actual behavior:** Strict kebab-case is applied

**Reproduces how often:** Always

**Comment by joshaber** [comment] 2017-12-13 23:45
Interesting! I'm not sure why we'd restrict multiple dashes. That _sounds_ like a bug. Thanks for bringing it to our attention @dbchristopher!

**Comment by ofek** [comment] 2018-01-03 15:57
@joshaber This also affects us at @DataDog since we use NAME/SOME-FEATURE naming.

ex. https://github.com/DataDog/integrations-core/branches

**Comment by shiftkey** [comment] 2018-01-03 20:20
For reference, this came in way back in #526:

```diff
 /** Sanitize a proposed branch name by replacing illegal characters. */
  export function sanitizedBranchName(name: string): string {
 -  return name.replace(/ /g, '-')
 +  // See https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html
 +  // ASCII Control chars and space, DEL, ~ ^ : ? * [ \
 +  // | " < and > is technically a valid refname but not on Windows
 +  // the magic sequence @{, consecutive dots, leading and trailing dot, ref ending in .lock
 +  return name.replace(/[\x00-\x20\x7F~^:?*\[\\|""<>]|@{|\.\.+|^\.|\.$|\.lock$|\/$/g, '-')
 +    .replace(/--+/g, '-')
 +    .replace(/^-/g, '')
  }
```

I wasn't aware of us doing this `string.replace(/--+/g, '-')` in the classic Windows app. While it does make multiple invalid characters condense down, it also affects multiple dashes.

cc @Haacked  for any extra input

**Comment by Haacked** [comment] 2018-01-03 21:24
Yeah, that approach was meant to condense multiple invalid characters into one dash, but it's the wrong implementation since it doesn't factor in dashes that are intentional.

It's probably overly prescriptive in the first place. I think you could probably remove that `string.replace(/--+/g, '-')` line.

**Comment by shiftkey** [comment] 2018-01-04 11:21
> I think you could probably remove that `string.replace(/--+/g, '-')` line.

If someone wants to have a go at contributing, this change and an additional regression test in [`app/test/unit/sanitize-test-name-test.ts`](https://github.com/desktop/desktop/blob/master/app/test/unit/sanitize-test-name-test.ts) should be enough to close this out.

**Comment by joshaber** [comment] 2018-01-08 14:52
>This also affects us at @DataDog since we use NAME/SOME-FEATURE naming and forward slashes are converted to hyphens by Desktop.

@ofek Slashes _should_ be allowed except as a starting or ending character. That restriction is part of Git's spec as described in https://www.kernel.org/pub/software/scm/git/docs/git-check-ref-format.html:

>6. They cannot begin or end with a slash /

**Comment by ofek** [comment] 2018-01-08 20:26
@joshaber Indeed, please forgive me! Upon typing `/` the first time, the message appears and I didn't try typing anything after that.

**Comment by JQuinnie** [comment] 2018-01-14 23:10
> If someone wants to have a go at contributing, this change and an additional regression test in app/test/unit/sanitize-test-name-test.ts should be enough to close this out.

Looking in the .ts, I noticed that there seems to be a test that will test double--dashes, but it doesn't actually do that. What is the test case it is performing?

https://github.com/desktop/desktop/blob/d5c4b4ad9483670aeec4d0974f4aba1c82e748c6/app/test/unit/sanitize-test-name-test.ts#L42-L46

**Closed** 2018-01-24 02:32 UTC
Labels: bug, good first issue, help wanted

**Comment by stevemoser** [comment] 2018-05-15 19:30
@ofek @joshaber I thought was running into the issue of not being able to create a 'feature/feature-name' type of branch and found this issue. However it looks like maybe I just ran into a UX bug. When I type 'feature/' the app shows a validation error instantly and I thought that no slashes were allowed. Maybe only show the validation error on submission so that users don't think that branch names with forwards slashes in the middle of them are not allowed. Or maybe it is just me :)

**Comment by iAmWillShepherd** [comment] 2018-05-15 21:25
@stevemoser would you mind opening a new issue describing your problem? This issue is about formatting with dashes (`-`).

**Comment by davidrmusti** [comment] 2021-05-24 12:33
> @ofek @joshaber I thought was running into the issue of not being able to create a 'feature/feature-name' type of branch and found this issue. However it looks like maybe I just ran into a UX bug. When I type 'feature/' the app shows a validation error instantly and I thought that no slashes were allowed. Maybe only show the validation error on submission so that users don't think that branch names with forwards slashes in the middle of them are not allowed. Or maybe it is just me :)

As suggested by @iAmWillShepherd, I opened a new enhancement issue for this "UX bug" you mentioned here as I also ran into this and was confused: [Modify warning about forward slashes in branch name](https://github.com/desktop/desktop/issues/12275)
