### ISSUE TITLE
Cloning Repositories Failure

### ISSUE THREAD

**Issue by ArtifexYT** [desktop/desktop#6838] opened 2019-02-13 15:45 UTC
Hello, whenever I try to clone my repositories to any directory on my computer, it throws an error. It's a school computer, we use different computers for each class but this has never happened before. I'm unsure if it's a bug or just a new problem.

[Screenshot](https://imgur.com/a/YNAnE9q)

**Comment by billygriffin** [comment] 2019-02-13 16:58
@ArtifexYT Thanks for the report and sorry it was failing for you. This error is usually caused by your network blocking the attempt by Windows to check the revocation status of a certificate, which then causes the whole operation to error. You can find a workaround for this issue here:

https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326

We have also seen this error occurring for users running certain antivirus software like Kaspersky due to the filtering it performs. If you are running Kaspersky try temporarily disabling it to see if that fixes this issue, and let us know if you run into any further issues. I'm going to close this because the workaround almost always resolves it, but please let us know if not. 😄

**Closed by billygriffin** 2019-02-13 16:58 UTC

**Comment by ArtifexYT** [comment] 2019-02-13 17:12
I don't have permissions to disable anything that requires administrative
access, I'm a student. I could clone and push to repositories before (last
Thursday) and when I came back to work on my Discord bot it threw the error.

**Comment by steveward** [comment] 2019-02-13 18:28
@ArtifexYT has anything changed on your system since you last used GitHub Desktop? Do you know if there is any antivirus software running on this machine? I'm assuming since you are in a campus environment you are behind a firewall or proxy that could be causing issues, but it is strange that this issue only started occurring recently.

It would be helpful if you could open up Git Bash and run the following command (if you do not have Git installed you can download it from https://git-scm.com/download/win):

`openssl s_client -connect github.com:443`

That should give some more information about the SSL issue. Please let us know the full output of that command.

**Comment by ArtifexYT** [comment] 2019-02-13 18:31
Alright. I'll try that once I'm in a class where I have access to a laptop.

**Comment by ArtifexYT** [comment] 2019-02-13 18:52
And no settings have been changed, at least to my knowledge. Also, there is an antivirus software running on the [mysdhc.net](mysdhc.net) domain which we use to login onto the computers and for the computer internet. But, however it wouldn't prevent anything from occuring nor does it have access to mess with the firewall.
