### ISSUE TITLE
An unexpected scrollbar was generated on the Commit Panel.

### ISSUE THREAD

**Issue by hanbings** [desktop/desktop#17320] opened 2023-08-31 19:43 UTC
### The problem

When pasting text that exceeds the width of the window into the Commit Messgae (Summary) input box in the Commit Panel at once, a scrollbar will be generated in the entire Commit Panel.

### Release version

3.3.1

### Operating system

Windows 11 22H2

### Steps to reproduce the behavior

1. Open any repo.
2. Note that the files to be committed and the Commit Message input box area are displayed on the left.
3. Copy the following text into the "Summary (required)" input box and paste "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
4. Observe whether a scroll bar appears at the bottom of the left window.

### Screenshots

![GIF](https://img1.imgtp.com/2023/09/01/Z4MC6fF1.gif)

### Additional context

Open `#repository-sidebar > div.panel` style and remove the `overflow-y` style to solve the problem. I'll test and make a PR later if needed (but I didn't find an overflow-y style for this anywhere so I'll fix it with an override).

**Comment by laukstein** [comment] 2023-09-04 14:12
I can confirm this happens when pasting long text. No unnecessary scrollbar when typing, only on paste.
![image](https://github.com/desktop/desktop/assets/183966/e5d16231-cde4-4794-b2db-a37ef5093f1f)

**Comment by hanbings** [comment] 2023-09-04 16:00
> I can confirm this happens when pasting long text. No unnecessary scrollbar when typing, only on paste. ![image](https://user-images.githubusercontent.com/183966/265482883-e5d16231-cde4-4794-b2db-a37ef5093f1f.png)

Yes, thank you. This problem only occurs when **pasting text**, and I'd like to be able to fix it because it only requires one line of code to prevent the user from having to move the mouse multiple times to slide the scroll bar.

**Comment by laukstein** [comment] 2023-09-04 18:11
The issue is caused by this div having too large "left" value locating it out of view
![image](https://github.com/desktop/desktop/assets/183966/fcab85ed-ff60-46fc-bc5c-9f76f539bf7c)

**Comment by steveward** [comment] 2023-09-06 14:05
Thanks for reporting this @hanbings and for the investigation @laukstein! I'll mark this as a bug for the team to get fixed.

**Comment by steveward** [comment] 2023-09-06 14:06
I missed that you already opened a PR @hanbings, thanks!

**Comment by laukstein** [comment] 2023-09-06 19:13
@steveward https://github.com/desktop/desktop/pull/17322 might maybe "fix" this, but it is not the correct fix for this bug. See in screenshot I reported - JavaScript applies too large CSS `left` value, the fix should be there.

**Closed as completed** 2023-10-03 13:26 UTC
Labels: bug, priority-3
