### ISSUE TITLE
Update from master silently fails when there is a merge conflict

### ISSUE THREAD

**Issue by thesyntaxinator** [desktop/desktop#9993] opened 2020-06-12 21:05 UTC
### Describe the bug

When working on a separate branch, update from master silently fails when there are merge conflicts

### Version & OS

2.5.0 MacOS
Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Switch to a non master branch
2. Click Branch -> Update from master
3. Nothing happens

### Expected behavior

Update from master should pull the updates from master and notify if there is a merge conflict

### Actual behavior

Nothing happens

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by thesyntaxinator** [comment] 2020-06-12 23:05
When I run git pull origin master at the command line it pulls the updates and then tells me there is a merge conflict, which then shows up in Github desktop. In contrast, when I select update from master in Github Desktop it doesn't do anything, whereas it should pull those changes and then notify me that there is a merge conflict. This behavior only seems to happen when pulling the changes on master would result in a merge conflict locally.

**Comment by tierninho** [comment] 2020-06-13 00:31
Thanks for the update. So these are your steps?

- Switch to a non-master branch
- open command line to run `git pull origin master`, merge conflicts present
- Go back to Desktop to see merge conflicts
- Click Branch -> `Update from master`

Any chance you could share the logs?

**Comment by thesyntaxinator** [comment] 2020-06-13 01:13
No, my steps are:
Switch to non master branch
Make changes
Don’t commit those changes 
Have someone else make, commit, and push conflicting changes to master branch
From GitHub desktop (still on non master branch with uncommitted changes) click update from master 
- GitHub desktop does nothing, whereas it should pull the changes and notify that there is a conflict

**Comment by tierninho** [comment] 2020-06-16 21:01
Logs would be very helpful here. Please share if you can, thanks.

**Comment by steveward** [comment] 2020-09-30 13:02
@thesyntaxinator after someone else makes changes to the remote `master` branch you would need to switch to `master` to click the `Pull origin` button to merge in those changes to your local branch. Once you do that the `Update from master` button would work as intended. It's a way to quickly update your local branches with the changes in your local default branch. I'm going to close this out but let me know if that doesn't seem to be the issue.

**Closed by steveward** 2020-09-30 13:02 UTC
Labels: more-info-needed
