### ISSUE TITLE
Can't load Github Desktop

### ISSUE THREAD

**Issue by yuleshow** [desktop/desktop#1661] opened 2017-05-20 07:34 UTC
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** [What you expected to happen]

**Actual behaviour:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.
2017-05-20T07:30:28.228Z - error: Uncaught exception on main process
TypeError: Cannot read property 'screen' of undefined
    at o.exports (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:12:10249)
    at new L (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:1:37416)
    at g (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79026)
    at App.S.app.on (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:80223)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
2017-05-20T07:30:28.231Z - error: Uncaught exception on main process
TypeError: Cannot read property 'screen' of undefined
    at o.exports (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:12:10249)
    at new L (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:1:37416)
    at g (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79026)
    at h (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79268)
    at App.S.app.on (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:81409)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)
2017-05-20T07:31:52.394Z - error: Uncaught exception on main process
TypeError: Cannot read property 'screen' of undefined
    at o.exports (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:12:10249)
    at new L (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:1:37416)
    at g (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79026)
    at h (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:79268)
    at App.S.app.on (/Applications/GitHub Desktop.app/Contents/Resources/app/main.js:14:81409)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)

**Comment by shiftkey** [comment] 2017-05-20 09:31
@yuleshow this is a duplicate of #1564. Please add any additional information about your environment there so we can get to the bottom of it.

**Closed by shiftkey** 2017-05-20 09:31 UTC
