### ISSUE TITLE
Toolbar: Can View Unusable Menus By Hovering From One To Another

### ISSUE THREAD

**Issue by lovesanxx** [desktop/desktop#2217] opened 2017-07-11 06:54 UTC
### Description

Toolbar menus that should be unusable (they are grayed out and cannot be accessed without reproducing this), are viewable by hovering from one usable menu to the unusable menu beside it.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Ensure that you have an unusable tab menu, and you cannot hover over it and it open.
2. A viewable tab menu must be beside it.
3. Hover your mouse over the usable tab menu, then glide over to the (previously) unusable menu. It should open, but all the menu items should be unusable.

Example here:
![showing the bug](https://user-images.githubusercontent.com/13669835/28054657-ab8dc498-65ca-11e7-9c2e-bbb68f1a4e13.gif)

**Expected behavior:** Not to be able to see them.

**Actual behavior:** I was able to see their menu items, but I was unable to interact with them.

**Reproduces how often:** anytime you try, and for me, it happened accidentally.

Thanks!

**Comment by iAmWillShepherd** [comment] 2017-07-11 14:49
This looks like the expected behavior. Are you clicking on each menu item or simply hovering over them?

**Comment by lovesanxx** [comment] 2017-07-12 04:58
I am just hovering. I did not know that was expected. It feels odd, and like it should not be there.

**Comment by niik** [comment] 2017-07-12 06:26
> This looks like the expected behavior. Are you clicking on each menu item or simply hovering over them?

On macOS, yeah, but not on Windows.

![windows-disabled-menu](https://user-images.githubusercontent.com/634063/28104414-2e8d8ab6-66db-11e7-8b49-efc87efd9707.gif)

I'm going to close this one out in favor of https://github.com/desktop/desktop/issues/1521 as they seem to be describing the same issue.

@lovesanxx Thank you so much for opening this, that GIF is super helpful

**Closed by niik** 2017-07-12 06:26 UTC
