### ISSUE TITLE
Issue autocomplete popover is below line selections and co-authors placeholders

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#7554] opened 2019-05-16 18:01 UTC
## Description

Hi franz 👋 

If my diff is long enough to get down past the commit message and then I type `#` to autocomplete an issue, then the line selection is on top of the issue autocompletion. The co-authors placeholder is also above the autocompletion menu.

<img width="399" alt="Screen Shot 2019-05-16 at 1 53 51 PM" src="https://user-images.githubusercontent.com/13760/57876170-b553e800-77e2-11e9-9891-f5127c855f53.png">

## Version

* GitHub Desktop: 1.7.0-beta7
* Operating system: macOS 10.14.5 (18F132)

**Comment by tierninho** [comment] 2019-05-16 18:15
Fellow comrade, this is a duplicate of https://github.com/desktop/desktop/issues/4084 so will be closing this issue for now. Thanks for filing 👍

**Closed by tierninho** 2019-05-16 18:15 UTC
