### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by gara3d** [desktop/desktop#17239] opened 2023-08-17 15:43 UTC
### The problem

I am logged in to the Github.com 

![logged](https://github.com/desktop/desktop/assets/127188265/d7743b7b-e4ae-427d-8e34-9fafa6c825e5)

While trying to log into the Github Enterprise, I get error `Cannot read properties of undefined (reading 'name')`

![2](https://github.com/desktop/desktop/assets/127188265/4a4e446b-7680-475a-86b7-44f2f99702bf)

### Release version

Version 3.2.8 (x64)

### Operating system

Windows 10

### Log files

[2023-08-17.desktop.production.log](https://github.com/desktop/desktop/files/12371217/2023-08-17.desktop.production.log)

**Comment by sergiou87** [comment] 2023-08-17 17:03
Thank you for your report @gara3d !

We're gonna close this as it's a duplicate of https://github.com/desktop/desktop/issues/17237 and the fix is already in https://github.com/desktop/desktop/pull/17238

We will release a new version with the fix soon. Sorry for all the trouble and thank you for your patience 💖

**Closed as completed by sergiou87** 2023-08-17 17:03 UTC

**Comment by sergiou87** [comment] 2023-08-17 18:47
@gara3d  A hotfix (3.2.9) has been released. You can download it at https://desktop.github.com/ 

Let us know if that works! 🤞

**Comment by gara3d** [comment] 2023-08-18 08:53
Perfect! it works now. Thanks
