### ISSUE TITLE
Cannot rename repositories in the app

### ISSUE THREAD

**Issue by tomhamming** [desktop/desktop#10555] opened 2020-09-10 21:08 UTC
### Describe the bug

The repository names shown in the app are forced to be the name of the repository on GitHub. If you have more than one copy of a repo checked out, you can't tell them apart. Desktop should at least use the folder name instead of the repo name, or maybe even allow renaming in the UI without affecting the checkout folder.

### Version & OS

GitHub Desktop 2.5.5, macOS Big Sur Beta 6

### Steps to reproduce the behavior

1. Check out two copies of the same repo, to different folders named different things in Finder
2. Try to tell them apart in GitHub Desktop

### Expected behavior

I expect a way to tell which checkout is which.

### Actual behavior

There is no observed difference.

### Screenshots

<img width="1474" alt="Screen Shot 2020-09-10 at 2 07 59 PM" src="https://user-images.githubusercontent.com/431326/92806651-0a6c2380-f36f-11ea-981c-a87ae91412c8.png">

**Comment by tierninho** [comment] 2020-09-10 21:40
@tomhamming thanks for filing this issue. This sounds like a duplicate of #8175 and #8175, both which were included in #6460. See #8158 (comment) specifically for the current thinking on this. Thanks!

**Closed by tierninho** 2020-09-10 21:40 UTC
