### ISSUE TITLE
Cannot specify GIT binary directory

### ISSUE THREAD

**Issue by mancoast** [desktop/desktop#5454] opened 2018-08-23 11:35 UTC
## Description

Greetings,

The GitHub Desktop system requires an enhancement.  This enhancement should enable the use of portable GIT binaries.

## Version

* GitHub Desktop:
![image](https://user-images.githubusercontent.com/7040493/44523062-93d82c80-a6a6-11e8-88ef-48e806fb8b61.png)

* Operating system:
Windows 7

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/7040493/44523019-71461380-a6a6-11e8-8de3-f79e2225d5df.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/7040493/44523157-edd8f200-a6a6-11e8-82dd-1cb8aba7bbcf.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/7040493/44523051-88850100-a6a6-11e8-9f98-c217b46be3bd.png)

## Additional Information

n/a

### Logs

n/a

Thanks,
coast

**Comment by mancoast** [comment] 2018-08-23 11:37
FYI, this is the required binary:
![image](https://user-images.githubusercontent.com/7040493/44523292-57590080-a6a7-11e8-8540-c0be0a8d01ce.png)

**Comment by shiftkey** [comment] 2018-08-23 12:27
@mancoast thanks for the report. 

Two things to add to what you've shared here:

 - I gather you have installed Git for Windows but chosen to not add Git to your PATH, which is the warning that is displayed here. I talked about this over in #5358 because Git Bash doesn't need to check this.
 - `Command Prompt` here is just a plain CMD prompt, not the enhanced "Git CMD" prompt you point to within the Git for Windows install. Can you share why you prefer that over the plain CMD?

**Comment by mancoast** [comment] 2018-08-23 12:49
Greetings @shiftkey 

I have not installed GIT for windows, simply unzipped the portable archive.
![image](https://user-images.githubusercontent.com/7040493/44526175-2b427d00-a6b1-11e8-948d-10103bdf5da6.png)

The systems require an enhanced "Git CMD" prompt due to lack of admin rights to install/modify the systems' Path environment variable.

Thanks,
coast

**Comment by shiftkey** [comment] 2018-08-23 13:49
> The systems require an enhanced "Git CMD" prompt due to lack of admin rights to install/modify the systems' Path environment variable.

You can change environment variables for your account without needing admin rights like this:

<img width="502" src="https://user-images.githubusercontent.com/359239/44526726-815ff200-a6aa-11e8-994e-64c44fe440ea.png">

I went through these steps to test how Desktop works with a portable Git install:

 - downloading the latest PortableGit archive and extracting it to `C:\Users\shiftkey\Desktop\PortableGit`

 - finding the `Path` environment variable for my current user and selecting "Edit":

<img width="643" src="https://user-images.githubusercontent.com/359239/44529019-aeaf9e80-a6b0-11e8-8b5d-d5356f61a354.png">

 - adding `C:\Users\shiftkey\Desktop\PortableGit\cmd\` to my user's PATH environment variable (don't forget the `cmd` here!)

<img width="536" src="https://user-images.githubusercontent.com/359239/44529041-ba02ca00-a6b0-11e8-93c5-904380559f94.png">

 - launch GitHub Desktop again and launch `Open in Command Prompt`

<img width="292" src="https://user-images.githubusercontent.com/359239/44529128-e6b6e180-a6b0-11e8-9287-e76b7fc806ea.png">

 - no error, and `git` now works

<img width="509" src="https://user-images.githubusercontent.com/359239/44529096-d30b7b00-a6b0-11e8-9438-82d3ec59d3c4.png">

For the moment we don't plan to add a "Locate Git" option here, and instead rely on the user to setup `PATH` (this works for all OSes Desktop runs on currently) so I'm going to close this out as "by design". 

If the pain here ends up with more issues like this it suggests that we need to revisit this dialog and make it clear what we're looking for.

**Closed by shiftkey** 2018-08-23 13:49 UTC

**Comment by lmstearn** [comment] 2022-10-22 04:57
Thanks, changing the PATH worked.
A **Locate Git** button isn't a bad idea, might be a bit of work changing the PATH string for Git via the registry though. These days, altering such registry keys isn't de rigeur, and usually requires account elevation (perhaps even as a dedicated child process after install), which explains why the Git clients don't do it.
