### ISSUE TITLE
v2. Bitbucket: Authentication failed - since March 1st 2022

### ISSUE THREAD

**Issue by marcreig** [desktop/desktop#14052] opened 2022-03-02 09:06 UTC
**previous: https://github.com/desktop/desktop/issues/14035**

Sorry to insist, @steveward 

But is important that we all try to resolve this.
Since yesterday bitbucket changes, there is a lot of people through the globe having multiple problems.
Most of the people use SourceTree. But I like and I'm used to GitHub Desktop. I had to use Bitbucket on it because job...

Talking on https://community.atlassian.com/t5/Bitbucket-articles/Announcement-Bitbucket-Cloud-account-password-usage-for-Git-over/ba-p/1948231/page/2?tempId=eyJvaWRjX2NvbnNlbnRfbGFuZ3VhZ2VfdmVyc2lvbiI6IjIuMCIsIm9pZGNfY29uc2VudF9ncmFudGVkX2F0IjoxNjQ2MjExMTk5Mzc0fQ%3D%3D&tempId=eyJvaWRjX2NvbnNlbnRfbGFuZ3VhZ2VfdmVyc2lvbiI6IjIuMCIsIm9pZGNfY29uc2VudF9ncmFudGVkX2F0IjoxNjQ2MTUwMDIwMDY1fQ%3D%3D#U1959791

with [David Dansby](https://community.atlassian.com/t5/user/viewprofilepage/user-id/3197218)

and they are addressing it to a: can you "git something" through CMD on to those shared projects? Then probably it's not BitBucket, but GitHub Desktop...

Thing is, as I said, I can normally work on my projects. Shared ones are the ones failing on Authentication.

Can we know how you do the "login" task? Which API methods? Or how it is implemented? Maybe there is something that could need change to formally function with Bitbucket as always...

It0s like a very specific problem on authentication on to shared projects as contibutor. But not as a project owner.

**Comment by sergiou87** [comment] 2022-03-02 10:48
Hi @marcreig ! 👋 

As far as I can tell, GitHub Desktop doesn't do anything special about authentication on non-GitHub repositories, it completely relies on git for that. Basically, it runs `git clone…` or whatever operation you want, then git asks for username and password, and GH Desktop provides whatever the user inputs 😕 

Could you try running `git -c credential.helper= fetch --progress --prune origin` from a terminal? That's what GitHub Desktop is running exactly and failing for you.

Instead of showing a window asking for credentials, it should ask for those credentials from the very same terminal.

**Comment by Necko1996** [comment] 2022-03-02 16:53
This is what I got after running the command:
https://prnt.sc/GvTUk45i9Wy2

Url from the console (official announcement):
https://community.atlassian.com/t5/Bitbucket-articles/Announcement-Bitbucket-Cloud-account-password-usage-for-Git-over/ba-p/1948231

Solution:
- Go to Personal Settings (You will see it by clicking on your profile picture on BitBucket)
- then App Passwords
- Create app password (also mark options u want)
- After creating the form will give you a password, use it in the GitHub Desktop app

For me after all these steps, it's working fine.

**Comment by marcreig** [comment] 2022-03-02 17:50
@sergiou87 thanks for the reply.

This is what I've got:
![image](https://user-images.githubusercontent.com/3540728/156418868-cbe86a92-745b-4d97-99e4-de23957d2887.png)

Top CMD, opened on shared project folder location (I'm shared contributor with admin rights on it), and fired your command. This is what I got (and is the one I could not make it work on GitHub Desktop).

Bottom CMD, opened on my project folder location (I'm owner on bitbucket), fired same command and rare thing is that it fails too! But with different error. Do not ask me for credentials but on GitHub Desktop works fine and syncs as expected...
But the error citates my correct User on Bitbucket.

Ideas?

**Comment by marcreig** [comment] 2022-03-02 18:03
> This is what I got after running the command: https://prnt.sc/GvTUk45i9Wy2
> 
> Url from the console (official announcement): https://community.atlassian.com/t5/Bitbucket-articles/Announcement-Bitbucket-Cloud-account-password-usage-for-Git-over/ba-p/1948231
> 
> Solution:
> 
> * Go to Personal Settings (You will see it by clicking on your profile picture on BitBucket)
> * then App Passwords
> * Create app password (also mark options u want)
> * After creating the form will give you a password, use it in the GitHub Desktop app
> 
> For me after all these steps, it's working fine.

In my case as indicated on previous responses, works like your case on MY projects/repos, but doesn't over shared ones (even beig a contributor with admin rights). Login fails. 
I've tried with an APP Password on my account and as I said, it's token let's me login and sync on my projects. Not on shared ones.
I've created App passwords on repos owners and used their tokens to login on my GitHub Desktop and try to sync, and doesn't work. 
So shared projects are unsyncable, with my atlasian user/pwd pair credentials, or owners ones, or any of the app passwords (with full rights all checks checked) created on every user.

**Comment by steveward** [comment] 2022-03-02 18:35
@marcreig I just tested out creating a token for my Bitbucket account and confirmed it worked in GitHub Desktop. I don't have any repositories that I'm a contributor on, though.

It would be helpful to know if you are able to work with these specific repositories with a token used via the command line (not using GitHub Desktop's Git). That would help narrow down if the issue is with the token auth or something specific with GitHub Desktop and Bitbucket.

**Comment by marcreig** [comment] 2022-03-03 09:32
@steveward 

ok, this morning github desktop didnt sync with my own project too. I reentered my atlassian pair, and didn't work.
Tried with my user/app pwd and did. Nice.
Thinking maybe shareds problem's gone, I've tried to sync, but failed. No mine Atlassian pair. No app passwords, and event not my colleagues user pairs or app passwords.

So I traveled to shared project folder and through CMD fired a simple "FETCH". Same result as @Necko1996 
![image](https://user-images.githubusercontent.com/3540728/156536744-8c3e3341-cce2-4fdd-a796-adfcd82be68d.png)

**Comment by marcreig** [comment] 2022-03-03 09:39
Tried again using a credentials helper on the command:
![image](https://user-images.githubusercontent.com/3540728/156538026-e1987d67-8ba0-4b63-a275-9793573dedc2.png)

Same result. Do not pass.
Tried my Atlassian PWD, and my APP pwd. None of'em.

**Comment by marcreig** [comment] 2022-03-03 10:41
Ok! Solved!

Basically:

- Completly close Github Desktop and developing GUI. Everything releated.
- Delete all bitbucket related credentials from Windows "keychain".
- Delete entire shared projects folders from my local (not mine projects, only shared ones). Or save on to diferent paths away, if you need to recuperate some made code changes. But be sure the folders are not were they used to be anymore.
- Open Github desktop and travel to shared projects. It says they're removed and asks for removing from Github Desktop. Accept removing all of'em.
- On to Github Desktop, go to one of your own projects and re-sync (fetch button). It's going to ask for credentials. Write your Atlassian USER, the one appearing on bitbucket personal page. NOT the mail, but the user AS-IS. You need to have an APP Password created with ALL permisions set. All the checks you can check, do it. Save the token received on App password creation, and use it on GitHub Desktop login prompt.
- It normally syncs and everything works as expected. So now, it's shared projects turn.
- Forget GitHub desktop. Open CMD an do a CLONE of those removed project, with the APP password and atlassian user on it, like this: `C:\Users\*******\AppData\Local\GitHubDesktop\app-2.9.10\resources\app\git\cmd\git.exe clone -b develop https://ATLASSIANUSER:APPPASSWORD@bitbucket.org/*******/*******.git C:\PATH\TO\FOLDER\WHERE\REMOVED`
- Everything is going to get on place. And then, back to GitHub Desktop, you need to manually add the project through ADD button and selecting "Add existing repository". Choose your recent cloned path and voilà!
- You're free to sync, push, pull or whatever is needed.

Drastic solution, but functional one.

Now I have to resolve piplines to AWS, which are failing on the last part of the deployment with a: 
`INFO: Deployment created with id xxx.
INFO: Waiting for deployment to complete.
aws deploy wait deployment-successful --deployment-id xxx
Waiter DeploymentSuccessful failed: Waiter encountered a terminal failure state
ERROR: Deployment failed. Fetching deployment information...
...
"errorInformation": {
            "message": "The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.", 
            "code": "HEALTH_CONSTRAINTS"
        }, `
don't even know why...

**Comment by marcreig** [comment] 2022-03-03 12:07
Ok! About pipelines, solved too.
Found the error on Bitbucket CI/CD pipelines. Releated with instance health.
Found the error on google. Ask to look at AWD console on CodeDeploy movements and search fo the details on errors there appearing.
All google searches say: look at the service on the AWS instance running. Be sure its ready and running.
It is. They say: look at the logs! I do and found something releated with ssl, ruby, permisions, yada yada...
Search the error and a guy says: I usually solve this simply restarting the CodeDeploy service on the instance.
Said and done. All works back to normal now. 

So for me, all done. Struggling travel, happy end.

**Comment by sergiou87** [comment] 2022-03-03 12:13
Ughh sorry you had to go through all that, but I'm happy it worked. Thank you for sharing all the steps you took to get it working, I'm sure it'll help someone else ❤️ 

I'm still surprised your commands in https://github.com/desktop/desktop/issues/14052#issuecomment-1057208478 didn't prompt for the Username and Password and probably just picked it from somewhere else 😕 

In any case, I'm gonna close this and hope this was a one-off issue 🤞  Thank you again for your patience, and we're sorry we couldn't help you with this.

**Closed as completed by sergiou87** 2022-03-03 12:13 UTC
