### ISSUE TITLE
Cannot trust potentially unsafe repo

### ISSUE THREAD

**Issue by customlab** [desktop/desktop#14384] opened 2022-04-15 08:03 UTC
### The problem

I keep my repos in an intranet fileserver and share with my colleages. After last update 2.9.14(x64) win 11, it shows a message tha this repo is potentially unsafe because it is owned by another user.
It shows 2 buttons Tust repo... and Remove.
But Trust repo does nothing at all, so I cannot use github desktop if the bug is fixed

### Release version

2.9.14(x64) 

### Operating system

win 11

### Log files

2022-04-14T14:48:05.720Z - error: [ui] `git remote -v` exited with an unexpected code: 128.
stderr:
fatal: unsafe repository ('//koinos_mpla/koinos/mpla/mpla/CRM/mpla' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory //koinos_mpla/koinos/mpla/mpla/CRM/mpla

2022-04-14T14:49:34.960Z - info: [ui] [AppStore] loading 14 repositories from store

### Screenshots

![image](https://user-images.githubusercontent.com/35843267/163543474-39d46b3b-eeeb-4a9c-b87e-21ba63e2a4f3.png)

**Comment by hugofintecture** [comment] 2022-04-15 10:00
Duplicate of https://github.com/desktop/desktop/issues/14336. Try with the latest Beta release: https://github.com/desktop/desktop/issues/14336#issuecomment-1099881641

**Comment by steveward** [comment] 2022-04-15 12:21
Going to close this out @customlab -- let us know if you run into any issues with the beta.

**Closed as completed by steveward** 2022-04-15 12:21 UTC
