### ISSUE TITLE
Force push support (needed for workflow editing)

### ISSUE THREAD

**Issue by aminya** [desktop/desktop#8787] opened 2019-12-12 09:12 UTC
I cannot force push to .github workflow files using any other Git managing solution. Only Github desktop allows me to that (https://github.com/desktop/desktop/issues/7079). However, Github desktop doesn't have any force push. What should I do?

**Comment by tierninho** [comment] 2019-12-12 18:06
@aminya Desktop does have Force Push, but only when rebasing. 

The rebase option is under the Branch menu.

Not sure if this is the best solution for your situation though. Let me know, thanks!

**Comment by kuychaco** [comment] 2019-12-13 02:34
Hi @aminya, thanks for taking the time to open an issue. It looks like this is a duplicate of #3580 so I'm going to go ahead and close it. We don't currently have plans to support general force pushing, and you can see https://github.com/desktop/desktop/issues/3580#issuecomment-459907211 for extra context

**Closed by kuychaco** 2019-12-13 02:34 UTC
