### ISSUE TITLE
Ability to add repository to favorites list

### ISSUE THREAD

**Issue by CriggerMarg** [desktop/desktop#11886] opened 2021-03-29 09:43 UTC
### Describe the feature or problem you’d like to solve
App does not support adding repositores to favorites list. 
"Recent" does not solve the problem as it does not remember how much time I spent in repositores and quickly forgetting about all my 10 repositories I use in everyday work.
And when I have about ~100 checked out repositories on my machine, it's getting complicated to find my work repositories. I have to type repository name to filiter list and find interesting repo.

### Proposed solution

Add ability to add repository to favorites or pinned list.

**Comment by tidy-dev** [comment] 2021-03-29 11:02
@CriggerMarg  Thanks for your input. This is a duplicate of #8183, which unfortunately currently isn't being worked on. But, we may revisit in the future so I going to link this issue. Feel free to add your comment or thumbs up to that issue as well.

**Closed as completed by tidy-dev** 2021-03-29 11:02 UTC
