### ISSUE TITLE
Add ability to pin some repos to the top of the list

### ISSUE THREAD

**Issue by Raicuparta** [desktop/desktop#12990] opened 2021-09-20 08:38 UTC
### Describe the feature or problem you’d like to solve

The repo list can build up quickly and require constant filtering to find some repos that we access frequently. The "Recent" category helps, but isn't always the solution if the use is messing around with a lot of repos in a short time span.

### Proposed solution

Easiest way to do it would be adding a "Pin repo" option to the context menu when right-clicking an item in the repository list. Pinned repos would show under a "Pinned" category above the "Recent" category.

**Comment by Sumantsahu9888** [comment] 2021-09-20 09:37
Whoud you tried another whoud you tried rebooting and looking another instance device

**Comment by Sumantsahu9888** [comment] 2021-09-20 09:38
Instant task manager

**Comment by sergiou87** [comment] 2021-09-21 11:28
@Raicuparta Thanks for your input! This is a duplicate of #8183, which unfortunately currently isn't being worked on. But, we may revisit in the future so I going to link this issue. Feel free to add your comment or thumbs up to that issue as well.

**Closed as completed by sergiou87** 2021-09-21 11:28 UTC
