### ISSUE TITLE
GITHUB Enterprise organization selection cant be switched

### ISSUE THREAD

**Issue by grinch1987** [desktop/desktop#7052] opened 2019-03-10 09:38 UTC
**Description**
Hi,

When I’m trying to publish my project (Enterprise) and want to link it with specific organization it can be clicked:
https://enterprise.githubsupport.com/attachments/token/Cz7b6MX7AZniCjKcMNGmRwJvw/?name=image001.png

After I click the ‘none’ option it will open my all organization by when I click on one of them it won’t do the selection,

And because of it , it will upload to my users organization.

 

Will be great if you can check it.

Thx 

**Version**
1.6.3

**Operating system**
windows 7 SP1

**Expected Behavior**
organization selection should be switched and chosen according to users selection.

**Actual Behavior**
selection inst changing and only 'NONE' selection is available

**Comment by andyeff** [comment] 2019-03-12 11:07
Confirming that I have the same problem, with v1.6.3, on Windows 10.

**Comment by steveward** [comment] 2019-03-12 15:53
@grinch1987 thanks for the report about this. I was able to reproduce this issue as well. 

As a workaround for this issue you can follow these steps to use the command line to set up the repository:

1. Create a new repository directly in your GitHub Enterprise instance (do not select the checkbox to initialize the repository)
2. Open your repository in GitHub Desktop 
3. Go to the menu and select `Repository` > `Open in <default_command_line_application>`
4. Run the command `git remote add origin <repository_URL>` to add an `origin` remote URL that points to your newly created remote repository
5. Run the command `git push -u origin master` to push to the remote repository

That should get the repository working in GitHub Desktop. Let me know if you have any questions about this.

**Comment by steveward** [comment] 2019-03-12 15:56
@desktop/core we should look into getting a fix out for this regression 🔜 since it will affect any GitHub Enterprise user trying to publish a repo to a specific organization.

**Comment by cgolebio** [comment] 2019-03-13 18:40
Hello, same problem exists in 1.6.4 for Mac

**Comment by billygriffin** [comment] 2019-03-13 19:37
@cgolebio Thanks! 1.6.4 was to fix some issues for Windows 7 and 8 users. The fix for this should be coming in the next few days.

**Closed** 2019-03-14 11:39 UTC
Labels: bug, priority-2
