### ISSUE TITLE
Symlinks are false by default and completely ignore the global settings

### ISSUE THREAD

**Issue by gaharavara** [desktop/desktop#7083] opened 2019-03-14 02:39 UTC
## Description

I was cloning  a repository using github-desktop and for the code in it I had to turn turn the ```git config core.symlinks``` to true, I set it up to true through git and then cloned the repo using github-dektop after cloning when I rechecked ```git config core.symlinks``` it showed false inside the cloned repo, which made the cloned repo full of errors. I don't know why the global settings of git for symlinks is not synced to github-desktop also it seems like their is no likely option to switch it.

I had to then clone it again using ```git clone```.

## Version

* GitHub Desktop: 1.5.0

* Operating system: Windows 10

## Steps to Reproduce

> Clone any project that requires symlinks to be enabled to true via GitHub dekstop, their 
is no option on the desktop app to check the status of symlink, when you change to git bash and their you set the symlink to true globally with the command ``` git config --global core.symlink true ``` and verify it via ``` git config core.symlink``` you will
get it true in git bash, but now again if you use GitHub desktop to install the project their is no indication that the symlinks are false in their and after cloning via desktop app when you open the cloned repo inside it ```git config core.symlink``` you get false while if you had cloned it via gitbash it would return true.
### Expected Behavior

The expected output would be it should check whether or not the symlinks are enabled or disabled before cloning a project.
### Actual Behavior

The desktop app keeps the symlinks disabled despite the change in configurations done through git bash.

**Comment by shiftkey** [comment] 2019-03-14 11:42
@AsociTon thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by AsociTon** [comment] 2019-03-16 02:05
@shiftkey I have updated the template, hope this does the job : )

**Comment by shiftkey** [comment] 2019-03-17 17:45
@AsociTon are you able to test this out with the latest version of GitHub Desktop - you should be able to update using the `Help` -> `About GitHub Desktop` menu item. The version you are running is four months behind our most recent release, and I know there has been at least one Git update in that time.

**Comment by AsociTon** [comment] 2019-03-18 10:51
@shiftkey checked it on V1.6.4(latest), it is still present.

**Comment by rbellamy** [comment] 2019-07-15 19:53
I just tested this with Git for Windows and seeing the same behavior.

Cloned via the simple `git clone git@github.com:xyz/abc` moments ago (project redacted):
```
> git clone git@github.com:xyz/abc
cd abc
> git --version
git version 2.22.0.windows.1
> git config -l --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=true
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Users/rbellamy/.gitconfig       winupdater.recentlyseenversion=2.22.0.windows.1
file:C:/Users/rbellamy/.gitconfig       user.name=G. Richard Bellamy
file:C:/Users/rbellamy/.gitconfig       user.email=rbellamy@terradatum.com
file:C:/Users/rbellamy/.gitconfig       core.sshcommand=C:/Windows/System32/OpenSSH/ssh.exe
file:C:/Users/rbellamy/.gitconfig       core.symlinks=true
file:C:/Users/rbellamy/.gitconfig       core.editor="D:\Apps\vscode-insiders\Code - Insiders.exe" --wait
file:C:/Users/rbellamy/.gitconfig       diff.tool=bc
file:C:/Users/rbellamy/.gitconfig       difftool.bc.path=C:/Program Files/Beyond Compare 4/bcomp.exe
file:C:/Users/rbellamy/.gitconfig       merge.tool=bc
file:C:/Users/rbellamy/.gitconfig       mergetool.bc.path=C:/Program Files/Beyond Compare 4/bcomp.exe
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=git@github.com:xyz/abc
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

**Comment by rbellamy** [comment] 2019-07-15 20:03
See https://github.com/git-for-windows/git/issues/2262

**Comment by outofambit** [comment] 2019-07-15 20:14
Thanks for sharing @rbellamy! GitHub Desktop uses Git for Windows internally so I believe that issue you linked to would be the core problem.

**Comment by rbellamy** [comment] 2019-07-16 13:52
You'll see that I did not have the proper permissions, so my input was nothing but noise. Sorry about that.

**Comment by shiftkey** [comment] 2019-07-23 12:24
@rbellamy it looks like we can close this out based on the discussion upstream and finding that permissions was the root cause of the issue.

Let me know if there's anything else we need to be aware of in Desktop.

**Comment by rbellamy** [comment] 2019-07-23 15:58
I agree. Even though I wasn't the OP I think it's pretty obvious the cause of this symptom.

**Comment by shiftkey** [comment] 2019-07-23 16:01
@rbellamy oops, I didn't realise there was another user involved. Given this has been discussed on the Git for Windows project, I think if there's any extra context we should raise that there.

I'm satisfied that we know what the problem is as it relates to Desktop.

**Closed by shiftkey** 2019-07-23 16:01 UTC
Labels: investigation-needed
