### ISSUE TITLE
Changes lost during switch to branch

### ISSUE THREAD

**Issue by ogamespec** [desktop/desktop#8012] opened 2019-07-24 13:14 UTC
My changes lost while switching to new branch from origin (with moving changes there).

Period.

**Comment by MarcelloTheArcane** [comment] 2019-07-24 13:25
Just happened to me too. This is very strange.

**Comment by steveward** [comment] 2019-07-24 13:53
Thanks for the report @ogamespec. 

Are you able to reproduce this consistently? If so, can you share the exact steps you are taking? I just tried to reproduce this and was unsuccessful.

It would also be helpful if you could share the operating system, version of GitHub Desktop, and a log file from today. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by MarcelloTheArcane** [comment] 2019-07-24 14:04
Here are my logs. I'm not sure what is pertinent:

```
2019-07-24T11:53:25.706Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 17.774s)
2019-07-24T11:53:25.706Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(objectname:short)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 9.551s)
2019-07-24T11:53:25.926Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 2.008s)
2019-07-24T11:53:26.276Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.306s)
2019-07-24T11:53:26.277Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 6.213s)
2019-07-24T11:53:30.716Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 5.314s)
2019-07-24T11:53:30.750Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 4.468s)
2019-07-24T11:53:34.425Z - info: [ui] Executing getChangedFiles: git log 57a2f50300eb36002a1c9439392c7db66d852595 -C -M -m -1 --no-show-signature --first-parent --name-status --format=format: -z -- (took 8.503s)
2019-07-24T11:53:34.426Z - info: [ui] Executing getRemotes: git remote -v (took 7.290s)
2019-07-24T11:53:34.426Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color --not --remotes -- (took 7.891s)
2019-07-24T11:53:34.762Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color --not --remotes -- (took 8.686s)
2019-07-24T11:53:36.512Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at window.setTimeout (C:<*>AppDataLocalGitHubDesktopapp-2.1.0webpack:appsrclibhighlighterworker.ts:85:14)
2019-07-24T11:53:36.520Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 7.708s)
2019-07-24T11:53:36.520Z - info: [ui] Executing getStashEntries: git log -g -z --pretty=%gd%x1F%H%x1F%gs refs/stash (took 8.428s)
2019-07-24T11:53:36.538Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 2.111s)
2019-07-24T11:53:36.544Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color --not --remotes -- (took 5.786s)
2019-07-24T11:53:41.184Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color --not --remotes -- (took 8.482s)
2019-07-24T11:53:45.085Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 10.323s)
2019-07-24T11:53:45.605Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 9.066s)
2019-07-24T11:53:47.146Z - info: [ui] Executing getConfigValueInPath: git config -z trailer.separators (took 5.962s)
2019-07-24T11:53:47.159Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.072s)
2019-07-24T11:53:52.935Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- pages/quotes/index.vue (took 5.766s)
2019-07-24T11:53:52.935Z - info: [ui] Executing getWorkingDirectoryDiff: git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- pages/quotes/index.vue (took 7.002s)
2019-07-24T11:54:07.305Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 17.584s)
2019-07-24T11:54:07.306Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(objectname:short)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 19.263s)
2019-07-24T11:54:11.519Z - info: [ui] Executing getPartialBlobContents: git show HEAD:pages/quotes/index.vue (took 18.499s)
2019-07-24T11:54:31.300Z - info: [ui] [AppStore] loading 3 repositories from store
2019-07-24T11:54:31.301Z - info: [ui] [AppStore] found account: MarcelloTheArcane (Max Reynolds)
2019-07-24T11:54:36.171Z - info: [ui] launching: 2.1.0 (Windows 10.0.17134)
2019-07-24T11:54:36.171Z - info: [ui] execPath: 'C:/<*path*>/GitHubDesktop.exe'
2019-07-24T11:54:36.181Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.600s)
2019-07-24T11:54:36.182Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.208s)
2019-07-24T11:54:37.842Z - info: [ui] Executing getCommits: git log 57a2f50300eb36002a1c9439392c7db66d852595 --date=raw --max-count=1 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 1.656s)
2019-07-24T11:55:18.151Z - info: [ui] [Timing] Action 'create commit' for '<*repo*>' took 4.787s
2019-07-24T11:55:41.885Z - info: [ui] [Timing] Action 'checkout branch from list' for '<*repo*>' took 0.000s
2019-07-24T11:55:43.935Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	pages/quotes/index.vue
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2019-07-24T11:55:46.008Z - info: [ui] [Timing] Action 'stash and checkout' for '<*repo*>' took 2.385s
2019-07-24T11:55:46.105Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<master> (took 2.169s)
2019-07-24T11:55:53.356Z - info: [ui] [Timing] Action 'checkout branch from list' for '<*repo*>' took 0.000s
2019-07-24T11:55:55.073Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	pages/quotes/index.vue
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2019-07-24T11:55:57.333Z - info: [ui] [Timing] Action 'stash and checkout' for '<*repo*>' took 2.548s
2019-07-24T11:56:00.870Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	pages/quotes/index.vue
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
2019-07-24T11:56:03.054Z - info: [ui] [Timing] Action 'stash and checkout' for '<*>' took 2.453s
2019-07-24T13:22:56.517Z - info: [ui] [AppStore] loading 3 repositories from store
2019-07-24T13:22:56.518Z - info: [ui] [AppStore] found account: MarcelloTheArcane (Max Reynolds)
2019-07-24T13:22:56.991Z - info: [ui] launching: 2.1.0 (Windows 10.0.17134)
2019-07-24T13:22:56.992Z - info: [ui] execPath: 'C:/<*path*>/GitHubDesktop.exe'
2019-07-24T13:22:57.756Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.017s)
2019-07-24T13:22:58.363Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.565s)
2019-07-24T13:25:00.871Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.463s)
2019-07-24T13:25:07.571Z - info: [ui] Background fetch for 3 repositories took 10.407sec
2019-07-24T13:27:56.120Z - info: [ui] [Timing] Action 'checkout branch from list' for '<*repo*>' took 0.001s
2019-07-24T13:27:59.244Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<master> (took 1.268s)
2019-07-24T13:28:00.589Z - info: [ui] [popStashEntry] a stash was popped successfully but exit code 1 reported.
2019-07-24T13:28:03.253Z - info: [ui] [Timing] Action 'stash and checkout' for '<*repo*>' took 5.278s
2019-07-24T13:28:16.943Z - info: [ui] [Timing] Action 'checkout branch from list' for '<*repo*>' took 0.000s
2019-07-24T13:28:20.584Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2019-07-24T13:28:21.033Z - error: [ui] `git -c credential.helper= checkout --progress filter-and-sort --` exited with an unexpected code: 1.
stdout:
pages/quotes/index.vue: needs merge

stderr:
error: you need to resolve your current index first

2019-07-24T13:28:23.033Z - info: [ui] [Timing] Action 'stash and checkout' for '<*repo*>' took 2.742s
2019-07-24T13:28:26.167Z - info: [ui] [createDesktopStashEntry] a stash was created successfully but exit code 1 reported. stderr: 
2019-07-24T13:28:26.623Z - error: [ui] `git -c credential.helper= checkout --progress filter-and-sort --` exited with an unexpected code: 1.
stdout:
pages/quotes/index.vue: needs merge

stderr:
error: you need to resolve your current index first

2019-07-24T13:28:28.520Z - info: [ui] [Timing] Action 'stash and checkout' for '<*repo*>' took 2.637s
2019-07-24T13:39:32.033Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stdout:
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
	deleted:    assets/products.js
	deleted:    components/QuoteListLine.vue

no changes added to commit

```

**Comment by MarcelloTheArcane** [comment] 2019-07-24 14:08
I too was trying to change branch to the master branch. I tried to get it to 'bring the changes with me', and it didn't work very well.

It stashed the changes, and showed a warning about `LF` - didn't catch all of it but I think it was a standard Windows / Linux issue (I use WSL as my terminal and edit on VS Code. The line formatting should be sorted, but that might be a clue). 

Some of the changed files (I think the new and uncommitted ones?) got stashed successfully, but a few of my files got deleted - all the lines were red. Most importantly **the changes had completely disappeared**. I only have the last time I committed the file which is very annoying!

#### Bit of OS info: 
Windows 10
Github Desktop version 2.1.0
Git version 2.17.1

**Comment by MarcelloTheArcane** [comment] 2019-07-24 14:10
One thing that might help - I was messing around with the `$PATH` in WSL, and in doing so screwed up the `gpg2` signing. This meant I couldn't commit anything. I have fixed this now, but might be what was causing `exit with error code 1`.

**Comment by tierninho** [comment] 2019-07-24 17:57
@MarcelloTheArcane Based on the logs, it looks like the same bug as https://github.com/desktop/desktop/issues/7827. 

Were your changes found in the stash?

**Comment by MarcelloTheArcane** [comment] 2019-07-25 05:31
@tierninho Yep, must be what happened. I got some Big Red Warning messages too, and when I saw this issue was created about ten minutes before the same thing happened to me I hopped on the bandwagon!

I think the repo is safe and sound now, after resolving a conflict where apparently a whole file was deleted then copied back again 🤷‍♂

**Comment by shiftkey** [comment] 2019-07-25 16:30
@tierninho I think we can move this into #7827 as it looks like the same related issue.

Looking at the first steps that @MarcelloTheArcane attached to the earlier issue:

```
2019-07-24T11:55:41.885Z - info: [ui] [Timing] Action 'checkout branch from list' for '<*repo*>' took 0.000s
2019-07-24T11:55:43.935Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	pages/quotes/index.vue
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
```

This step comes from #7474 where we want to try the quickest path to switching branches, but it's not a clean checkout so Git reports an error because there's conflicting changes on the destination branch for this file.

The app then falls back to creating a stash for the current working directory changes, which appears to complete without error:

```
2019-07-24T11:55:46.105Z - info: [ui] Executing createStashEntry: git stash push --include-untracked -m !!GitHub_Desktop<master> (took 2.169s)
```

I assume at this point that the working directory is clean, but then the second attempt to checkout reports the same error:

```
2019-07-24T11:55:55.073Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	pages/quotes/index.vue
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
```

Maybe something is not working as expected with the stash itself? It's hard to say without more context...

**Comment by tierninho** [comment] 2019-07-25 18:57
@MarcelloTheArcane Glad everything is back in order again.

@ogamespec if you require further assistance please let us know.

Closing this issue as the underlying problem is found at #7827 so follow along there.

**Closed by tierninho** 2019-07-25 18:57 UTC
Labels: more-info-needed
