### ISSUE TITLE
macOS: can't close window while fullscreen

### ISSUE THREAD

**Issue by chrstphrchvz** [desktop/desktop#5287] opened 2018-07-30 21:10 UTC
## Description

On macOS, the GitHub desktop window can't be closed if it is fullscreen (in its own space rather than on a desktop space, i.e. not maximized); it can only be closed if the window is not in fullscreen mode.

## Version

* GitHub Desktop: 1.3.0

* Operating system: macOS 10.13.6

## Steps to Reproduce

1. Enter fullscreen using either the green title bar button, View menu > "Toggle Full Screen", or using the command-control-F keyboard shortcut.
2. Attempt to close the window using either the red title bar button, Window menu > "Close window", or using command-W. 
### Expected Behavior

The window should close.
### Actual Behavior

The window stays open.

### Logs

I do not have access to the log at the moment, but will attach it later unless it's not considered necessary for this issue.

**Comment by shiftkey** [comment] 2018-07-30 21:41
@chrstphrchvz thanks for the report. I was able to reproduce this on `1.3.0` too, and as I'm not familiar with the repro steps I'll also confirm this is a recent regression due to the Electron upgrade.

**Comment by shiftkey** [comment] 2018-08-01 12:40
This isn't a regression (`1.2.6` also has the same behaviour) but I suspect the app doesn't handle the right event(s) to close the current window when maximised.

**Comment by shiftkey** [comment] 2018-11-01 10:47
I believe this is the same as https://github.com/electron/electron/issues/13135 which was reported upstream, and will be fixed when we upgrade Electron in #6069.

**Closed** 2018-11-21 18:43 UTC
Labels: bug, electron, macOS, priority-3

**Comment by WorkShop-Office** [comment] 2018-11-21 18:58
I don't know it's not my job
