### ISSUE TITLE
Losing stash on local branch rename.

### ISSUE THREAD

**Issue by harley-codes** [desktop/desktop#16229] opened 2023-03-01 03:17 UTC
### The problem

I renamed a local branch that had yet to be published, and I noticed I lost my stash. Upon renaming back to its prior name, the stash reappeared. Cannot confirm if this is going to happen for a remote branch, only noticed for local. Upon

### Release version

Version 3.1.8 (x64)

### Operating system

Windows 10

### Steps to reproduce the behaviour

1. Create a local branch
2. Make a code change
3. Stash changes
4. Rename the branch

**Comment by sergiou87** [comment] 2023-03-01 10:34
Thanks for your report! 💖 

I was able to repro this. AFAIK the stash is named after the branch from where it was created, not sure if possible but it should be renamed along with the branch.

I set it to priority 2 because even though data is not lost, it might be hard to know how to get it back.

**Comment by steveward** [comment] 2023-03-01 18:07
This was previously discussed in https://github.com/desktop/desktop/issues/7283 back when we initially implemented stashing, and the warning was added when attempting a rename with a stash. @Harley-Torrisi did the warning appear when you renamed?

I do agree that this is confusing when it happens (especially if you potentially miss the warning).

**Comment by harley-codes** [comment] 2023-03-02 23:10
@steveward just had a look and there was, completely missed it... Call me stupid and slap me silly 😂 
"Your current stash changes on this branch will no longer be visible in GitHub Desktop if the branch is renamed."

**Comment by sergiou87** [comment] 2023-03-07 12:10
Then I will close this as expected behavior. Thanks for letting us know! ❤️

**Closed as completed by sergiou87** 2023-03-07 12:10 UTC
Labels: bug, priority-2
