### ISSUE TITLE
"Checkout with GitHub Desktop" does nothing

### ISSUE THREAD

**Issue by gemal** [desktop/desktop#12853] opened 2021-08-27 16:10 UTC
I use GitHub Desktop both at work and at home.
So I create a branch and then a pull request at work
Then at home I go using the browser to the URL like this:
https://github.com/XXXX/xxx/pull/28511
and click the "Checkout with GitHub Desktop"
and nothing happens in GitHub Desktop. absolutely nothing
only the log reveals something:

```
2021-08-27T16:02:28.906Z - info: [main] Received possible protocol arguments: 4
2021-08-27T16:02:28.906Z - info: [main] Processing protocol url
2021-08-27T16:02:29.123Z - warn: [ui] failed fetching PR for gemal/xxx/pulls/28511
Error: Not Found
    at ct (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta1\webpack:\app\src\lib\http.ts:178:11)
    at Pt.fetchPullRequest (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta1\webpack:\app\src\lib\api.ts:893:7)
    at Object.fetchPullRequest (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta1\webpack:\app\src\lib\stores\app-store.ts:1653:9)
    at Object.openPullRequestFromUrl (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1672:11)
    at Object.openRepositoryFromUrl (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta1\webpack:\app\src\ui\dispatcher\dispatcher.ts:1624:9)
2021-08-27T16:02:29.550Z - info: [main] Error report submitted
```

Using: `Version 2.9.3-beta1 (x64)`

**Comment by steveward** [comment] 2021-08-30 21:26
Thanks for the issue @gemal. 

- Can you share the specific browser you are using? 
- Does the `Open in Desktop` button work anywhere else (i.e. cloning a repository with `Open with GitHub Desktop`)?
- Are you only using one GitHub account?

**Comment by gemal** [comment] 2021-09-01 10:29
I tried in both Firefox and Chrome. Same error (nothing) and same error:
when I try to click open in the clone I get the "Clone a repository" dialog in GitHubDesktop so that seems to work
I'm using only one github account

```
Error: Not Found
    at ct (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta2\webpack:\app\src\lib\http.ts:178:11)
    at Pt.fetchPullRequest (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta2\webpack:\app\src\lib\api.ts:893:7)
    at Object.fetchPullRequest (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta2\webpack:\app\src\lib\stores\app-store.ts:1653:9)
    at Object.openPullRequestFromUrl (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta2\webpack:\app\src\ui\dispatcher\dispatcher.ts:1672:11)
    at Object.openRepositoryFromUrl (C:\Users\Henrik Gemal\AppData\Local\GitHubDesktop\app-2.9.3-beta2\webpack:\app\src\ui\dispatcher\dispatcher.ts:1624:9)
```

**Comment by steveward** [comment] 2021-09-15 21:14
@gemal I did some testing and was able to reproduce this issue. Can you confirm if you are working in a repository that is a fork? 

It looks like this specifically happens when checking out a PR that was created from a fork. We previously had a bug around this (but not specific to forks) that was addressed in https://github.com/desktop/desktop/issues/12215.

Testing steps:

- I tested the checkout in Desktop flow on https://github.com/desktop/desktop/pull/12944 (not a fork), and the app correctly checked out the PR branch.
- Next I tested https://github.com/desktop/desktop/pull/12777 (which is from a fork), and the app did not properly switch branches and threw an error:

```
2021-09-15T20:59:49.438Z - warn: [ui] failed fetching PR for mahezsh/desktop/pulls/12777
Error: Not Found
    at ct (/webpack:/app/src/lib/http.ts:178:11)
    at At.fetchPullRequest (/webpack:/app/src/lib/api.ts:893:7)
    at Object.fetchPullRequest (/webpack:/app/src/lib/stores/app-store.ts:1656:9)
    at Object.openPullRequestFromUrl (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1671:11)
    at Object.openRepositoryFromUrl (/webpack:/app/src/ui/dispatcher/dispatcher.ts:1623:9)
```

It looks like the app is fetching from the wrong user -- it should be `desktop/desktop/pulls/12777` instead of `mahezsh` in this instance. 

/cc @desktop/engineering for confirmation

**Comment by gemal** [comment] 2021-09-17 07:04
> 
> @gemal I did some testing and was able to reproduce this issue. Can you confirm if you are working in a repository that is a fork?

yes I confirm

**Comment by sergiou87** [comment] 2021-09-22 09:23
@gemal @steveward does it work for you now? I can't reproduce it, and it looks like the URL used to get the PR is correct (`desktop/desktop/pulls/12777` in this case).

If it doesn't work for you, could you paste here the URL to which `Checkout in GitHub Desktop` is pointing? For example, in #12777 the URL I get is `x-github-client://openRepo/https://github.com/desktop/desktop?branch=pr%2F12777&pr=12777`

**Comment by gemal** [comment] 2021-09-22 09:36
weirdly enough it seems to work now on 2 links I tried

**Comment by sergiou87** [comment] 2021-09-22 10:00
Maybe it was a regression introduced on the web and has been fixed already 😅  

Closing for now, let us know if you find a case that doesn't work! Thanks!! 😄

**Closed as completed by sergiou87** 2021-09-22 10:00 UTC
Labels: bug, priority-2
