### ISSUE TITLE
Large file diffs freeze

### ISSUE THREAD

**Issue by mib32** [desktop/desktop#1686] opened 2017-05-22 11:55 UTC
### Description

When you click on the filename on the left, to look at diff, and if the diff is really large (for example, compiled javascript bundle) the application will freeze for 30-60 seconds.

### Version

**GitHub Desktop version:** 0.5.5

**OS version:** 10.12.4

**Comment by shiftkey** [comment] 2017-05-22 11:57
@mib32 to reproduce this locally, could you give an idea of how many lines are in the diff output? If you can give a snapshot of the app at this point I can give you the command to run so I can get an idea of how big the diff is...

**Comment by mib32** [comment] 2017-05-22 12:06
@shiftkey It is a big single line file with size of `5656581` bytes, that was deleted - so the diff also `5656581` bytes big.
<img width="1919" alt="2017-05-22 15 03 29" src="https://cloud.githubusercontent.com/assets/8045292/26308060/39b351e4-3f00-11e7-8b73-ba39321f7757.png">

**Comment by shiftkey** [comment] 2017-05-22 12:10
@mib32 could you open the repository in the terminal, run this command and tell me how many lines it is?

```
git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- public/rzd/build/static/js/main.d899a03f.js.map | wc -l
```

I think I've got that path right.

**Comment by mib32** [comment] 2017-05-22 12:13
@shiftkey There's just 8 lines.

**Comment by shiftkey** [comment] 2017-05-22 12:17
@mib32 of course, because it's a sourcemap file 🤦‍♂️ 

Anyway, that gives me enough to dig into.

**Comment by shiftkey** [comment] 2017-05-30 15:26
<img width="1427" src="https://cloud.githubusercontent.com/assets/359239/26591007/b0ede566-4532-11e7-8b2e-2aecfe2f8b45.png">

Looks like we spend **a lot** of time in [`updateHeightsInViewport`](https://github.com/codemirror/CodeMirror/blob/6992c534ad33ce60e7500fe04a99a481ef8f548e/src/display/update_lines.js#L8).

Particularly this line?

<img width="464" src="https://cloud.githubusercontent.com/assets/359239/26591085/f1d4dc74-4532-11e7-9831-12a3b3d4d4e1.png">

**Comment by veeramarni** [comment] 2017-06-05 02:03
Is it because of using codemirror?

**Comment by benrondeau** [comment] 2017-08-31 22:56
Any update on a solution? Thanks

**Comment by shiftkey** [comment] 2017-08-31 22:57
@benrondeau I retested this and the issue is still the same. I'm looking into alternative editors but that's going to take time to evaluate accurately due to all the integration we rely on in Codemirror.

**Comment by benrondeau** [comment] 2017-08-31 23:07
If the issue with Codemirror cannot be mitigated quickly, can you add a conditional in the source code which only render certain file sizes (>1mb) or types (.map) if the user wants? This would leave the functionality intact while resolving the UI rendering block

**Comment by shiftkey** [comment] 2017-08-31 23:20
@benrondeau I've moved that suggestion over to #2596 to discuss further alongside tracking this issue

**Comment by benrondeau** [comment] 2017-08-31 23:51
Thanks!

**Comment by mourner** [comment] 2017-10-02 16:58
Running into the same problem with big JSON test fixtures (~5MB, 1 line).

> I'm looking into alternative editors but that's going to take time to evaluate accurately due to all the integration we rely on in Codemirror.

Is there a reason to use an editor like Codemirror in the first place? The diff view is not editable or even code-highlighted. Only individual lines / diff blocks are interactive.

**Comment by joshaber** [comment] 2017-10-23 17:39
We introduced some limits in #3032 which should prevent freezes in the future.

**Closed by joshaber** 2017-10-23 17:39 UTC
Labels: bug, codemirror

**Comment by benrondeau** [comment] 2017-10-23 19:02
@joshaber FYI - the new limits set in #3032 seem far too high. I have 1mb minified files which brick the app for 10-20 seconds, and that is ~66% below the limit set that was set. I am on a computer with decent specs and 16gb RAM, and it still takes that long.

May I recommend bringing the file size limits way down (1mb) and not rendering minifed files at all (since they have almost now value)? Or if not lowered limits, not rendering minified files by default and give the user the option to render a file (as shown in [this comment](https://github.com/desktop/desktop/issues/2596#issue-254494958))? I'll even help with the PR if that is helpful.

PR #3032 is definately a step forward but still allows the app to be bricked for 30 seconds for rendering files by the limits set, and on an older computer with less power, maybe even more. Thanks

**Comment by j-f1** [comment] 2017-10-23 19:07
Although one of the limits is that the diff can’t be over 3MB, the other new limit is:

> A diff cannot have a line longer than 500,000 characters, e.g., minified files.

This should resolve your concerns about minified files.

**Comment by joshaber** [comment] 2017-10-23 19:38
Yup, as @j-f1 noted I _hope_ the other heuristic will catch minified files. But they are pretty arbitrary, so if it doesn't, let us know and we'll adjust them!

**Comment by benrondeau** [comment] 2017-10-23 21:23
Thanks!

**Comment by mib32** [comment] 2017-11-26 15:20
Why aren't we using Atom.

**Comment by shiftkey** [comment] 2017-11-26 21:19
> Why aren't we using Atom.

We had some chats with the Atom team about this early in development, and experimented with extracting the relevant bits, but things were too tightly coupled to the rest of the codebase for us to do it in a sane way. But that was ~1yr ago, maybe it's more reusable now?

**Comment by mourner** [comment] 2017-11-26 21:25
But why use an editor component in the first place? Any comment on this? The diff is read only after all, and diff color highlighting is very simple.

**Comment by j-f1** [comment] 2017-11-26 21:30
Highlight → Split by `\n` → Render to `<DiffLine />` component → Put in groups of ***n*** in `<DiffChunk />` components in a `<List />` (where ***n*** is high enough so that the list doesn’t have to manage thousands of elements, but small enough that there won’t be a massive blank space at the bottom of the diff)

**Comment by shiftkey** [comment] 2017-11-26 21:35
> But why use an editor component in the first place? Any comment on this? 

We get a lot of stuff for free from using Codemirror:

 - line selection - while the text isn't editable, the diff control needs to support selecting lines to do partial commits
 - syntax highlighting - this is actually something we didn't support in the classic apps, and Codemirror supports a range of languages in-the-box

I'm not opposed to improvements around this area, but please keep in mind what is currently supported.

**Comment by mourner** [comment] 2017-11-26 21:42
@shiftkey CodeMirror seems like a huge overkill for those things, so there's a nice room for improvement here.

 - line selection — seems relatively easy to implement from scratch since it doesn't require complex interactions, just clicks
- syntax highlighting — not sure what you mean by languages support, since the only highlighting I see is the language-agnostic diff highlighting, like this:

![image](https://user-images.githubusercontent.com/25395/33244604-641c3f44-d303-11e7-97cb-a372dab71330.png)

**Comment by shiftkey** [comment] 2017-11-26 21:46
@mourner is this something you're interested in contributing to?

**Comment by mourner** [comment] 2017-11-26 21:47
Maybe some day. :) I realize this might be a much bigger chunk of work than it seems, just wanted to capture a possible solution in comments.

**Comment by joshaber** [comment] 2017-11-27 13:36
CodeMirror also gives us soft wrapping and a path forward if we wanna add inline editing (e.g., resolving merge conflicts).

I'm not thrilled with CodeMirror either, but I haven't seen an alternative that addresses all our use cases yet.
