### ISSUE TITLE
"Move" change to a branch?

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#8564] opened 2019-11-01 16:16 UTC
I have a private branch from a shared master, which I use to resolve a few problems independently from master. In case of a successful implementation or fix, I'd like to "move" this change to master (or another branch). Therefore, I use this approach:
- Switch to master
(optional: update --rebase)
- cherry-pick the change to master
- switch to fix branch
- revert the change
- git reset --soft to "delete" the history of that change
- update the fix branch from master, which brings in the fix again.
This looks complicated, but this avoids problems with complicated merges, that arises from cherry-picking. Do you think, this might be a useful feature?

**Comment by niik** [comment] 2019-11-01 16:36
Hi @sdiedrichsen, thanks for reaching out!

I'm happy that you've found a workflow that works for you! My initial reaction is that it's unlikely that we'd incorporate this exact flow into the application but we're always looking to understand more about the various workflows and requirements our users have so I'd be delighted if you could tell us a little bit more about your setup and why an approach like the [GitHub flow](https://guides.github.com/introduction/flow/) isn't working for you. What types of changes do you keep on the private branch that you don't want to make it to master?

In the past we've discussed being able to move changes that you've accidentally committed (see https://github.com/desktop/desktop/issues/1021) to the wrong branch. Right now we're focused on trying to prevent accidental commits on protected branches (https://github.com/desktop/desktop/issues/7023) but if we decide to tackle moving commits after the fact it's possible that may become a tool that you could use.

For now I'm going to close this issue as it's not something we'll be focusing on in the short term but don't let the fact that the issue is closed discourage you from providing more context, we can always reopen later if we so choose.

**Closed by niik** 2019-11-01 16:36 UTC
