### ISSUE TITLE
No tiling buttons in Windows 11

### ISSUE THREAD

**Issue by aminya** [desktop/desktop#12685] opened 2021-07-27 23:56 UTC
### Describe the bug
When hovering over the maximize button, the tiling buttons do not appear like any other app.

### Version & OS

- Github 2.9.0
- Windows 11 (21H2 22000.65)

### Steps to reproduce the behavior

1. Hover on the maximize button

### Expected behavior

What I expect to see
![image](https://user-images.githubusercontent.com/16418197/127242217-2c6ef275-f8c1-4e21-9205-44445278d14f.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/16418197/127242162-fe490626-1f7a-4d44-8d79-4dd75c1dfa54.png)

### Screenshots

See the above

**Comment by irinaGambeeva** [comment] 2021-07-28 00:06
ср, 28 июл. 2021 г., 02:57 Amin Yahyaabadi ***@***.***>:

**Comment by steveward** [comment] 2021-07-28 19:01
Thanks for the report @aminya. Closing as a duplicate of https://github.com/desktop/desktop/issues/12542.

**Closed as completed by steveward** 2021-07-28 19:01 UTC
