### ISSUE TITLE
Misplaced tooltip

### ISSUE THREAD

**Issue by thinkyhead** [desktop/desktop#13636] opened 2022-01-06 12:23 UTC
### Describe the bug
Sometimes the tooltip appears in the top-left of the window, amusingly behind the stop-light buttons.

### Version & OS

Version 2.9.6 (arm64) on macOS 12.1 (21C52)

### Steps to reproduce the behavior

1. Hover over a file title

### Expected behavior

Tooltip appears in the location of the pointer.

### Actual behavior

Tooltip appears in the top-left corner.

### Screenshots

<img width="551" alt="image" src="https://user-images.githubusercontent.com/698003/148382370-f2986615-02f4-4abf-a74a-113224b6dfc2.png">

**Comment by steveward** [comment] 2022-01-06 16:40
Thanks for the report @thinkyhead! I was unable to reproduce this, but I'll label this as a bug for us to investigate.

**Comment by agisilaos** [comment] 2022-01-06 17:53
I've encountered this many times in the past @steveward. Make sure to play around with the size of the GitHub Desktop window.

**Comment by sergiou87** [comment] 2022-01-07 12:59
I haven't been able to repro this specifically as shown in the screenshot, but instead the tooltip didn't show up anywhere at all (or I couldn't find it 😆 ). After that I resized the window and was unable to repro it again 😢

**Comment by haykam821** [comment] 2022-01-26 21:33
I am able to reproduce this issue somewhat reliably from the merge conflicts list just by scrolling and keeping the cursor in the same position. Sometimes the tooltip will be offset but still near the cursor, while other times it will be in the top-left corner. Having an existing tooltip when scrolling seems to prevent the issue from occurring.

![](https://user-images.githubusercontent.com/24855774/151250424-8e03c80f-330f-49e5-922d-419d3d67ec19.png)

**Comment by tidy-dev** [comment] 2022-01-26 22:36
@haykam821 Thanks for that scrolling repro step. I was able to reproduce with that info about scrolling in the history commit list. Not sure what the root cause is, but being able to kind of reproduce it is great step in right direction. 😸  

https://user-images.githubusercontent.com/75402236/151258428-957d56f3-19a1-4c60-90d2-3d7a0a0494bf.mov

**Comment by niik** [comment] 2022-02-01 16:19
Another way of reliably reproducing this is to click on the fetch button while pointing at the description

![2022-02-01 17-17-58 2022-02-01 17_18_34](https://user-images.githubusercontent.com/634063/152007226-d513eff4-46da-4ffe-a763-0010ba8570bf.gif)

**Comment by haykam821** [comment] 2022-02-01 16:42
Would this potentially be caused by trying to hover over elements detached from the DOM? Both the scrolling and fetching reproductions would make sense to involve tooltips on detached elements. 

The tooltip rect is determined via `getBoundingClientRect`:

https://github.com/desktop/desktop/blob/b54339c0baeb8157dfa08ed7ed757be1373f1b49/app/src/ui/lib/tooltip.tsx#L78

However, for elements detached from the DOM, this will always be a zero `DOMRect`:

```js
const elem = document.createElement("div");
elem.getBoundingClientRect() // {"x": 0, "y": 0, "width": 0, "height": 0, "top": 0, "right": 0, "bottom": 0, "left": 0}
```

Therefore, this bug should be fixable by adding an additional check for the element being present on the DOM, such as `elem.parentNode !== null`:

https://github.com/desktop/desktop/blob/b54339c0baeb8157dfa08ed7ed757be1373f1b49/app/src/ui/lib/tooltip.tsx#L70

**Comment by haykam821** [comment] 2022-02-01 17:28
I've just looked into it further and I seem to have found the cause for the fetching reproduction. The fix I applied seems to have worked. The other cause may still be applicable for the scrolling reproduction, however.

The mouse rect is initialized as a zero `DOMRect`:

https://github.com/desktop/desktop/blob/df3b2652326c1d66a585a17054877589ff516899/app/src/ui/lib/tooltip.tsx#L142

This is fine in most cases, because a `mousemove` listener updates the mouse rect accordingly:

https://github.com/desktop/desktop/blob/df3b2652326c1d66a585a17054877589ff516899/app/src/ui/lib/tooltip.tsx#L302-L304

However, the `mousemove` listener is never called when a component is mounter. The `mouseenter` listener is, meaning the tooltip is shown without the mouse rect ever being updated.

The solution here is quite simple: since the `mouseenter` listener also is passed a `MouseEvent`, the mouse rect can be updated when the tooltip is queued to be shown.

**Comment by thinkyhead** [comment] 2022-05-04 16:14
I see progress has been made! Without applying any patches, I find now that the first shortened path in the list has a tooltip at {0,0} (owl position) if it is "created" under the mouse pointer. For your entertainment:

https://user-images.githubusercontent.com/698003/166724457-97aafb74-4abc-418f-aa29-930b7027e093.mov

And when scrolling under the pointer, the tooltips are all over the place:

https://user-images.githubusercontent.com/698003/166724677-c4782287-5913-405b-877e-331a1aee6c60.mov

I suspect these are all solved by the patches described above, and I look forward to inheriting them in a future release.

**Closed as completed** 2022-10-19 08:34 UTC
Labels: bug, priority-3
