### ISSUE TITLE
Default avatar keeps showing up

### ISSUE THREAD

**Issue by svivian** [desktop/desktop#4047] opened 2018-02-19 17:14 UTC
### Description

1. Switch to a different repo using the dropdown top left.
2. Look at where the avatar should be in the bottom left.

I keep getting the default avatar there for 2-5 seconds before switching to mine (or longer if the app is running slowly). Happens every time I start GH and every time I switch repos. I understand it when there are new avatars in History that have not loaded yet, but my avatar is already downloaded, surely it can appear much quicker?

Incidentally, it wasn't until I looked at some old issues that I realised this actually was a "default avatar", I was about to report an issue with someone else's avatar showing up. Can't we switch to a better placeholder (blank or plain silhouette) instead of this confusing emoji thing?

### Version

**GitHub Desktop version:** 1.0.13
**OS version:** macOS High Sierra 10.13.3

**Comment by j-f1** [comment] 2018-02-19 21:12
I’m also unable to see my avatar. (the default avatar is @hubot’s)

**Comment by shiftkey** [comment] 2018-02-20 01:38
We've avoided the work to implement and manage our own on-disk cache of images because it's a hard problem to do well, and because we get a lot for free in-the-box with Chromium. We swap in the Hubot avatar so we're showing _something_ while we wait for the network to get the proper image, but I'm curious if there's some corner cases we're missing here.

Some more information about that area:

 - the commit form avatar is resolved per-repository, so seeing it change when you switch repositories is to be expected

https://github.com/desktop/desktop/blob/a991d2a0469120b843e06950add087fd6a2be2d2/app/src/lib/stores/app-store.ts#L1558-L1561

 - this is done using the `GIT_AUTHOR_IDENT` logical variable, which let's us ask Git "what does the author look like for this repository?" rather than poking at the `user.name` and `user.email` config values for each repository

https://github.com/desktop/desktop/blob/a61a5bdc94ee8237dfff328957cdaee99a9b61e1/app/src/lib/git/var.ts#L23-L29

 - the last time I looked at this area was probably #3513 and I noticed that we could leverage blob URLs as well as Chromium's disk cache for images to avoid unnecessary network calls:

<img width="969" src="https://user-images.githubusercontent.com/359239/36403409-afbf09b2-1634-11e8-9a3e-f44b27c55f5a.png">

**Comment by tierninho** [comment] 2018-09-17 21:01
@svivian and @j-f1 is this still an issue for you? 

I cannot reproduce on v1.4, although I do see the default avatar for a micro second which is normal.

**Comment by j-f1** [comment] 2018-09-18 01:38
I haven’t seen it recently but I’ll comment here if I see it again.

**Comment by billygriffin** [comment] 2018-10-01 16:07
Since we haven't seen this recur, going to close this for now and if it pops back up we can reopen.

**Comment by billygriffin** [comment] 2018-10-02 22:38
Bummer, thanks @svivian. I'm going to reopen and add `help wanted` to see if there's anyone experiencing this who wants to dig into it and propose a solution. While it doesn't inhibit someone's workflow, it's certainly not the behavior that they'd expect. I tried on a really old machine and a mobile network, and couldn't repro (it swapped my avatar in very quickly).

**Comment by svivian** [comment] 2018-10-05 16:22
I get similar issues with pretty much everything in github desktop. For example there are constantly screens saying "No local changes" flashing up every time I click a file in the changes tab, and then changing to show the file diff. Same with "No history" in the History tab.

Going back to the avatar thing,

> We swap in the Hubot avatar so we're showing something while we wait for the network to get the proper image

Why do you need to show "something"? Isn't it more confusing to show the wrong image temporarily, than show a blank space while the correct image loads?

**Comment by shiftkey** [comment] 2018-10-13 13:44
@svivian thanks for the extra details

>  For example there are constantly screens saying "No local changes" flashing up every time I click a file in the changes tab, and then changing to show the file diff. Same with "No history" in the History tab.

Are you able to spin this off into a fresh issue separate to this? I opened #1913 ages ago to track something similar, but I'm happy to close that in favour of more specific feedback. I also have a branch lying around that digs into introducing a "loading" mode for some components that I think will help here.

> Isn't it more confusing to show the wrong image temporarily, than show a blank space while the correct image loads?

I don't believe this is something we've thought about doing, and I'm open to exploring this further.

**Comment by billygriffin** [comment] 2019-11-21 15:08
@svivian I'm really sorry you're experiencing this. Unfortunately because it's not something we've seen come up from anyone else and nobody has picked it up as a help wanted issue, it doesn't seem to be particularly common. I'm definitely not opposed to exploring what you suggested, but given that our team has limited bandwidth, I'm going to close this for now. If others are experiencing it and it's becoming particularly annoying for folks, we're definitely happy to reopen.

**Closed by billygriffin** 2019-11-21 15:08 UTC
Labels: help wanted
