### ISSUE TITLE
Ability to checkout commit directly from History tab

### ISSUE THREAD

**Issue by Marius-Juston** [desktop/desktop#10068] opened 2020-06-24 01:44 UTC
Hello,

It would be nice to have the feature implemented so that when you right-click a commit in the History, it adds the options to checkout commit. Currently, there does not seem to have a simple way to implement a commit checkout, and having this feature would be nice to have and make it easier to go back to a previous commit. There is currently revert commit; however, that is not always what you want to do.

**Comment by tierninho** [comment] 2020-06-24 01:52
Hi @Marius-Juston Thanks for the suggestion! Just to clarify, you would like to checkout a SHA based on a specific commit? 

Because that would place the user in a detached head state, we are unlikely to implement such a feature. Is this a state you go into frequently? Do you find a SHA or tag for likely to be used when doing so? 

Looking forward to learning more.

**Comment by Marius-Juston** [comment] 2020-06-24 01:55
It do not use this very often but, sometimes I have to back to a previous commit to verify which one there was a bug or to just test the code working in an earlier version. To do this I do use the checkout based on a SHA based on specific commit thus bringing me to a detached head state.

**Comment by tierninho** [comment] 2020-06-24 02:00
Appreciate the feedback. We will probably explore this request if we allow git tag checkouts in a similar fashion.

**Comment by Marius-Juston** [comment] 2020-06-24 02:01
I just felt like this would be a quick and simple feature to add the GitHub desktop and other people might appreciate it. I feel like it would just be calling the `git checkout [SHA of the right-clicked commit] .` and since GitHub Desktop already implements what happens when it is in a detached head state that would be all that is needed.

**Comment by ghost1372** [comment] 2020-08-28 11:15
any news?
I started working on a PR today
I have no experience with electron. For now, I was able to add `checkout commit` contextMenu But it still does nothing
I am currently researching to see if I can use the functions in the Desktop or not😁

![Untitled](https://user-images.githubusercontent.com/9213496/91554025-92036c80-e943-11ea-8336-7c25999c9cb8.png)

**Comment by tierninho** [comment] 2020-08-28 17:23
@ghost1372 Thanks for the update. As we have not labeled this issue `help-wanted` please be aware that there is no guarantee your PR will be merged or reviewed. Happy coding!

**Comment by jonchardy** [comment] 2021-12-16 18:52
Looks like this has been implemented recently: https://github.com/desktop/desktop/pull/12160

**Comment by eSilverStrike** [comment] 2022-01-17 17:35
I don't see this implemented. There is not checkout commit option in the menu when I right click on a commit in the history. It would be so much easier to debug things if I could just quickly go back to a certain point in the history of the repository to see if a bug exists at that point. 

Updated: Okay I see you have to create a new branch and then delete it afterwards. (just don't push the changes)

**Comment by Tranks27** [comment] 2022-02-14 00:39
Currently there's a "create branch from commit" option which is good enough. Just delete the branch after checking it out.

**Comment by vdheuvel** [comment] 2022-02-18 11:17
I would also like to see this feature. Same use case as Marius-Juston. I want to checkout an old version in detached head mode, so I can run an older version for a bit. 
Create branch for commit is not good enough for me, that just creates extra work.
In the meantime I'll keep on using the command line for this use case...

**Comment by steveward** [comment] 2022-03-03 18:49
Requested in https://github.com/desktop/desktop/issues/14053.

**Comment by JokerMartini** [comment] 2022-07-05 16:11
Can we not checkout a commit from the history tab in github desktop? That seems ridiculous this feature does not exist yet

**Comment by tecodan** [comment] 2022-09-19 02:35
+1 here.
Sometimes i need to look at code at a previous point in time. I don't want to create branches just to go look at a snapshot in the past (and I know you can just do it from CLI but I have users complaining having to go back/forth between GUI and CLI)

**Comment by thisispete** [comment] 2022-09-26 19:24
+1 this seems like basic functionality in any git tool that is currently missing, I do not want to create a new branch and then have to delete it later, I want to be able to quickly get my local code to the state it was in at a previous commit to be able to do manual forensic regression testing to find out at what point an obscure bug was introduced for instance.

**Comment by TushnaE** [comment] 2022-10-05 00:11
+5

**Comment by OmarB97** [comment] 2022-10-06 20:41
+1

**Comment by NajamShehzad** [comment] 2022-10-15 09:00
Is there any plan to implement the "Checkout to commit", I usually use the commit checkout, there no need to create new branch each time I want to go back and find the bug. When we have this case we need to do it so many time. So if I use the checkout the branch I endup creating maybe dozens of new branches, which later I need to clean.
Why it's so difficult for you to implement this?
It's so helpful and simple.

**Comment by swalchemist** [comment] 2022-10-27 00:51
+1

Fairly often I copy the SHA from GitHub Desktop and then go to the command line to check it out. I don't want to have to create a branch every time I do this.

**Comment by KorbenDeSmet** [comment] 2022-11-29 10:46
+1

Would be handy to checkout to a certain commit to check different states of a branch without having to create a new one each time.

**Comment by rsodre** [comment] 2022-12-03 15:07
duuudes!
this is one of the last the remaining reasons I go to the terminal
the other is to make empty commits

**Comment by araulinaitis-D3D** [comment] 2022-12-14 16:18
+1

I'd like the option to `git checkout` a SHA through the GUI instead of creating a new branch or having to open a terminal

**Comment by AlexandreR56** [comment] 2022-12-21 21:11
+1

**Comment by ionoy** [comment] 2022-12-22 08:20
+1

One more reason why creating a new branch for a temporary checkout is a bad idea: if you are not sure what commit to checkout, you can end up creating and deleting branches multiple times.

**Comment by mccarthyp-snet** [comment] 2023-02-08 08:03
Any updates on this? Why is this taking more than 2 years?

**Comment by kitswas** [comment] 2023-02-08 08:18
@mccarthyp-snet 
Well, I did get it done.
See https://github.com/kitswas/github-desktop/commit/45388c9571a2ea46a5e866c4aa1c10f5f03bd0de
I build and use it myself.

I didn't create a pull request due to
https://github.com/desktop/desktop/issues/10068#issuecomment-682960430

EDIT: You reminded me, it's probably time to rebase and build again.

**Comment by JokerMartini** [comment] 2023-02-08 21:40
I would love for this to be implemented. Please rebase so they can implement it. It's one of the main features that drives me nuts they don't have while SourceTree does have this feature.

**Comment by kitswas** [comment] 2023-02-10 16:47
Rebased. See https://github.com/kitswas/github-desktop/tree/checkout-a-commit

**Comment by JokerMartini** [comment] 2023-02-10 22:14
well now hopefully will integrate the feature since it's been requested over several years ago

**Comment by kitswas** [comment] 2023-02-17 05:38
Requesting review for PR #16120.

**Comment by JokerMartini** [comment] 2023-02-17 15:46
hopefully they jump on this and merge into main.

**Comment by TristanBrotherton** [comment] 2023-02-17 17:28
I really need this feature. The use-case is simply, something broke. I want to go back into the commit history easily to isolate at which point it broke. Then I want to go back to the current HEAD and push a fix.

**Comment by jabamaus** [comment] 2023-02-26 07:43
+1 Just came to do this for the first time. Shocked that this functionality was missing.

**Comment by JokerMartini** [comment] 2023-02-27 01:14
@tierninho and updates or thoughts on your end?

**Comment by darthun** [comment] 2023-03-12 13:57
+1 I understand that there are risks to checking out an old commit and that it can lead to bad practices and detached head. But give control to the users and let them handle the responsibility. If you're so concerned about controlling how people use the software, then put it behind a "Danger Zone" or advanced option.

**Comment by BluishGreenProductions** [comment] 2023-03-15 20:19
+1
I would really appreciate this feature, even if it is flagged as "Advanced Use"

**Comment by thereallee** [comment] 2023-03-26 02:32
+1 Surprised its not already here

**Comment by hexiy** [comment] 2023-04-01 16:42
+1 how is it not a thing yet

**Comment by kfarr** [comment] 2023-04-05 19:44
This is very odd not to include as it seems like a very common use case. Workaround for now seems to be create a branch from the commit with right-click and then just don't publish that branch to remote?

**Comment by Gakk** [comment] 2023-04-14 09:14
I am really missing this feature. Whenever a bug is reported we need to find out which version this affects. I know that Git has the _bisect_ command to do this, but that is more when trying to find the exact commit where the bug was introduced. Our first step is to quickly check if the was present in the previous release, and then we need to checkout the tagged commit for that version.

**Comment by JokerMartini** [comment] 2023-04-14 12:11
I'm guessing no one on the development team cares at all to chime in and make an acknowledgement of the growing requests for this feature. Instead they just ignore everyone. Cool cool....

**Comment by Gakk** [comment] 2023-04-14 13:09
Wow, @JokerMartini, that was harsh.

As a developer and product manager I know that you always have to prioritize, and that you never can (or should) implement every single proposed feature.

There are only 57 people world wide that has shown interest in this feature, and currently only 31 participants monitoring this feature. The Desktop-team has 753 open issues and feature requests, and sorted by number of comments this one is (as we speak) not even among the top 10.

Keep up the good work, Desktop-team, and hopefully this feature in the future will have gathered enough traction that it will be implemented 😇

**Comment by digidoor** [comment] 2023-04-14 20:36
This feature would be a godsend. Having to create another branch to checkout an older commit (just to see when something worked/broke) is a very clunky workaround that clutters the repo needlessly.

**Comment by Andrej730** [comment] 2023-04-17 06:27
Sounds like exactly what I need!

Other way to do it I had in mind is to have an option to drag-n-drop commit on "Current branch" field

![image](https://user-images.githubusercontent.com/9417531/232401522-5bdd83ef-65c9-46a2-9302-95049e66e1dc.png)

Seems very natural too since that was I expecting noticing that checking out commit changes "Current branch" to "Detached HEAD on hash".

![image](https://user-images.githubusercontent.com/9417531/232401784-37ec18d0-0ada-45fd-b28e-40b34d9915df.png)

**Comment by kitswas** [comment] 2023-05-30 13:05
@RichardBray01 
This is in the works.  
See https://github.com/desktop/desktop/pull/16120.

**Comment by JustinGol** [comment] 2023-06-05 00:20
This is a common workflow Ive seen with lots of engineers including myself, I cant understand why this wouldnt be prioritised.

**Comment by JokerMartini** [comment] 2023-06-05 11:03
> Wow, @JokerMartini, that was harsh.
> 
> As a developer and product manager I know that you always have to prioritize, and that you never can (or should) implement every single proposed feature.
> 
> There are only 57 people world wide that has shown interest in this feature, and currently only 31 participants monitoring this feature. The Desktop-team has 753 open issues and feature requests, and sorted by number of comments this one is (as we speak) not even among the top 10.
> 
> Keep up the good work, Desktop-team, and hopefully this feature in the future will have gathered enough traction that it will be implemented 😇

Just being realistic here. What's being asked of is not hard at all. Literally would take an hour or two to implement. Considering it's already implement and sitting in a pull request.

**Comment by Nordskog** [comment] 2023-06-23 00:35
> There are only 57 people world wide that has shown interest in this feature

Make that 58. Coming from SourceTree I had always assumed this was a standard feature.
Tracking down what commit caused the bug I'm looking for tonight just got a lot more tedious.

**Comment by MCKLtech** [comment] 2023-06-23 13:16
+1. Having this today could likely save me a few hours.

**Comment by steven4547466** [comment] 2023-06-23 18:45
Was looking just for this. 3 year anniversary of this request and it's still not in after many people have shown the need for it. I am now one of those people.

**Comment by Rosetsugh** [comment] 2023-06-27 06:34
+1.
Also coming from SourceTree and finding myself in a situation, when something very basic and yet needed is just not yet in GitHub Desktop.Sad.

**Comment by Gakk** [comment] 2023-06-27 06:51
A quick update to all the +1s (and others).

@kitswas has implemented this, and has contributed his work in PR #16120 ❤️

It is currently under review and needed a few small changes that is being worked on now. I hope and believe that it will be merged very soon 🤞

**Closed** 2023-06-30 16:00 UTC
Labels: enhancement

**Comment by kitswas** [comment] 2023-06-30 17:24
**UPDATE:** PR Merged. Thanks to @tidy-dev and @sergiou87 for the code review.
_This feature will soon be available in Beta._
Cheers! 🎉✨🎊
