### ISSUE TITLE
GitHub Desktop is not working properly

### ISSUE THREAD

**Issue by sgundappaciber** [desktop/desktop#2286] opened 2017-07-20 06:55 UTC
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Additional Information

Error while committing files to github via GitHub desktop
Error: write EOF
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite (net.js:804:14)

Version: 0.7.0
OS: Windows 6.1.7601

**Comment by joshaber** [comment] 2017-07-20 11:24
Thanks @sgundappaciber! We've seen reports of this error but have yet to figure out how to reproduce it so that we can fix it. Could you outline the steps that lead to it?

**Comment by sgundappaciber** [comment] 2017-07-20 11:36
Hi,
The steps to Reproduce.
1. Add local folder inside the local repository. The folder has 2000 odd files and many subfolders.
2. Automatically all the files will appear inside the changes tab
3. Enter Summary and Description
4. Click on Commit to Brach Folder name
5. Then i get error after some minutes.

i hope above steps will help you.

**Comment by joshaber** [comment] 2017-07-20 15:28
Thanks @sgundappaciber, that matches with some of our other reports. Any chance you'd be able to send the repository to us?

**Comment by sgundappaciber** [comment] 2017-07-21 04:26
hi,
Sorry, I can't share repository content.
I can help with any other info.

**Comment by joshaber** [comment] 2017-07-21 13:59
No worries. This sounds like a duplicate of https://github.com/desktop/desktop/issues/2041 so let's track it over there.

**Closed by joshaber** 2017-07-21 13:59 UTC
Labels: bug
