### ISSUE TITLE
Strange launch error

### ISSUE THREAD

**Issue by Zac-Garby** [desktop/desktop#1664] opened 2017-05-20 12:00 UTC
![screen shot 2017-05-20 at 12 57 59](https://cloud.githubusercontent.com/assets/19708658/26275576/044c03fc-3d5c-11e7-8552-6a78114453f6.png)

### Steps to Reproduce

1. I had gh desktop open when I shut down my computer
2. When I opened it again, it was in the dock, and the os had reopened it because i clicked
  reopen windows on login. so, it had the black dot below it but no windows of it were open
3. When I clicked the dock icon, it opened up, giving me the error message above
4. I closed the window (the cross button) and opened it again, getting the same error each time

**Comment by shiftkey** [comment] 2017-05-21 03:51
Duplicate of #1564 - please provide additional information there about your setup, if it's interesting...

**Closed by shiftkey** 2017-05-21 03:51 UTC
