### ISSUE TITLE
4.5 gigs of RAM usage after I closed(!) the program

### ISSUE THREAD

**Issue by PiMoNFeeD** [desktop/desktop#12493] opened 2021-06-22 18:36 UTC
### Describe the bug
So, I've had the program opened for some time while working on my project, I pushed several commits to my repo, browsed some commits and changes for quite some time as well, then I **closed** the program and around half an hour later my PC started lagging very badly, I opened my task manager and I saw that its not closed, eating like quarter of my CPU (could've been more if not for a compilation process I had in the background) and eating more than 4 GIGS(!) of my RAM

### Version & OS
2.9.0 x64, Windows 8.1

### Steps to reproduce the behavior
...I dont know?..

### Screenshots
![image](https://user-images.githubusercontent.com/36343425/122980454-512c8680-d3a1-11eb-9b0c-19ddac731b93.png)

### Logs
My most recent log is from 2 hours ago so obviously it won't help

**Comment by sergiou87** [comment] 2021-06-23 07:32
Thanks for your report @PiMoNFeeD !!

Is this the first and only time you've seen this? Or has it happened to you multiple times already?

I'm just wondering how easy it is to reproduce this problem 🤔

**Comment by steveward** [comment] 2021-06-23 13:41
I'll also reference this in https://github.com/desktop/desktop/issues/10625 where we are keeping track of these types of reports.

**Comment by sergiou87** [comment] 2021-06-23 13:43
I just remembered we recently got this other report #12320

**Comment by PiMoNFeeD** [comment] 2021-06-24 10:10
> Thanks for your report @PiMoNFeeD !!
> 
> Is this the first and only time you've seen this? Or has it happened to you multiple times already?
> 
> I'm just wondering how easy it is to reproduce this problem

Yeah, this is my first time, I've been using github desktop for quite some time now and I've never had this problem

**Comment by sergiou87** [comment] 2021-06-24 10:21
Thanks for your reply! I'm gonna close this in favor of #10625. If you see this happening again, please post as much info as you can in that other issue. I'm sorry we can't help more than that, but we can't reproduce it 😢

**Closed as completed by sergiou87** 2021-06-24 10:21 UTC
