### ISSUE TITLE
Can't upload node_modules

### ISSUE THREAD

**Issue by lagauche** [desktop/desktop#3370] opened 2017-11-19 19:36 UTC
I have a node_modules folder with a lot of folders/files. Desktop Github Win10 64bit crashes when I try and add the repository with it and when I try and commit to master:

Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.9
OS: Windows 10.0.15063

Since there are lots of folders I also can't drag and drop it on the github web upload.

Also in github desktop I can't collapse node_modules to a folder so I have to scroll through all 1889 files to find the ones I need to commit.

I don't know what to do : P Ideas?

**Comment by shiftkey** [comment] 2017-11-19 20:46
@lagauche sorry to hear you're having problems!

> I have a node_modules folder with a lot of folders/files. Desktop Github Win10 64bit crashes when I try and add the repository with it and when I try and commit to master:

I'd like to try and recreate this - are you able to share:

 - the `package.json` file that triggers this behaviour (I'm mostly interested in the `dependencies` and `devDependencies`)
 - the version of `node` and `npm` you are running
 - any `.gitignore` file that might be at the root of your repository

**Comment by shiftkey** [comment] 2017-11-19 23:41
Cross-referencing #2041 which is the same error but a different repro

**Comment by lagauche** [comment] 2017-11-20 04:17
Heya totally, thank you! Here's a google drive link to a folder with the package.json and package-lock.json 

https://drive.google.com/open?id=1PPJWrwQ4Ypyw_eG8ICN2lb3YXqh7iqbN

Let me know if you have any issues downloading.

This package is from an example to show off OSC.js. I believe it's the browser example, but it's been awhile so not certain which example:
https://github.com/colinbdclark/osc.js-examples/tree/master/browser

**Comment by shiftkey** [comment] 2017-11-20 04:21
@lagauche thanks for the extra information. I'll let you know if I can't reproduce it on my end.

**Comment by shiftkey** [comment] 2017-11-21 01:37
@lagauche I've tried to recreate this with `npm` `v5.5.1` and Desktop `1.0.9` against two different repositories without success.

Using the `package.json` and `package-lock.json` files from Google Drive:

```
mkdir test-package-json-commit
cd test-package-json-commit
git init
cp ~/Downloads/package.json .
cp ~/Downloads/package-lock.json .
npm install
```

I'd then drag-and-drop this repository onto Desktop and have alot of files ready to commit:

<img width="978" src="https://user-images.githubusercontent.com/359239/33050298-477139e8-ceb8-11e7-9c74-717af78b2937.png">

But then that commit completes without error. Grrr.

Cloning https://github.com/lagauche/xbabylonOSCBasex and running an `npm install` in there gets me into a similar state:

<img width="989" src="https://user-images.githubusercontent.com/359239/33050344-85d91750-ceb8-11e7-9a6e-bc2357df35c5.png">

But I can commit those 1854 changes too (eventually). :hurtrealbad: 

What am I missing from your setup?

**Comment by lagauche** [comment] 2017-11-21 05:43
Ah strange! Could it make any difference that I'm on Win10 64bit?

**Comment by lagauche** [comment] 2017-11-21 05:47
I made a video to show you my commit and then the crash. I'm using a different repo but it's the exact same npm package:
https://drive.google.com/open?id=18QTtcMmHxKtCaBFwBYoFM4IKupk72-rE

**Comment by niik** [comment] 2017-11-28 08:20
> Also in github desktop I can't collapse node_modules to a folder so I have to scroll through all 1889 files to find the ones I need to commit.
> I'm guessing mine has extra files because I often transfer between mac and pc so I have a lot of .DS_Store files.

@lagauche While not a solution to the underlying problem this sounds like a good use case for `.gitignore` unless you really really need to have the packages in source control. If you take a look at GitHub Desktop (and most other projects using npm) the only thing we actually commit into source control is `package.json` and then each developer (and build server) pulls down the packages needed.

See https://github.com/desktop/desktop/blob/0ad92d769c776a337723e48587c82fc477e67b39/.gitignore#L3 and https://github.com/desktop/desktop/blob/0ad92d769c776a337723e48587c82fc477e67b39/.gitignore#L7

**Comment by shiftkey** [comment] 2018-02-01 04:14
There's a few of these issues without clear steps to reproduce the issue, so I'm going to close this out in favour of the original issue #2041 which is still open.

**Closed by shiftkey** 2018-02-01 04:14 UTC
Labels: needs-reproduction

**Comment by yosef-123** [comment] 2020-09-28 22:55
So how do I add node modules to github repository ??? I didn't understand

**Comment by AvanParvadiya** [comment] 2021-10-12 13:51
Can any one help me to add node_modules to my github repository?
