### ISSUE TITLE
Enhancement: Git History on a Single File

### ISSUE THREAD

**Issue by say25** [desktop/desktop#3754] opened 2018-01-09 23:20 UTC
### Git History on a Single File

It would be awesome to see Git history (git log file.extension) for a single file at a time.

### Version

**GitHub Desktop version:** 1.0.12-beta1

**Comment by shiftkey** [comment] 2018-03-26 02:05
@say25 thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I added the `future-proposal` label to this issue and closed it so that we won't get overwhelmed with our backlog! We will revisit this in our next planning session.

**Closed by shiftkey** 2018-03-26 02:05 UTC
Labels: enhancement, future-proposal

**Comment by LarsFosdal** [comment] 2019-05-21 10:44
This is a necessary feature when visiting files to see the evolvement of the impacted code.
Bump.

**Comment by billygriffin** [comment] 2019-12-20 19:02
From @intrepidws in #8639:

> It would be very helpful to be able to right-click on a file, either in the Changes or History tab, and have a "View on GitHub" menu item available.

> I ran into this issue earlier today while editing a file because I needed to perform a git blame on a specific line. Since that isn't possible in the desktop app, it's something that I need to perform on GitHub.com - and it would be nice to be able to quickly navigate to that file in my repo. Another use case that I ran into is needing to see the history for a given file.

**Comment by billygriffin** [comment] 2020-02-14 15:21
From @EricSambach in #9080 

> 1. Sometimes changes come in and it is not clear who made the change, it would help us to be able to search for a particular filename to find the commit comments and also be able to ask the individual who made the change what the reason for it was (if comment is unclear).
> 2. Being able to see the history of a single file can help to understand why/when changes were made.

> Yes, point 2 does appear to be the Blame option, which would be nice if it was also directly available within GitHub Desktop. I was just hoping that GitHub Desktop could be the one-stop-shop for all GitHub functionality.

> Point 1 is simply a file search over the change history.
Example: when I know a file was changed, but I don't know who or when the change was made, a search would be nice (some change sets can be very large).
Yes this could be seen by using GitHub directly, but I would prefer to search for it in Desktop directly, if possible.

**Comment by cpetry** [comment] 2020-03-28 13:26
Where is this on the current roadmap? The roadmap itself does not have many topics currently...
Can I vote somewhere?

**Comment by steveward** [comment] 2020-03-30 12:57
@cpetry thanks for your feedback about this. The [roadmap](https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md) is focused on broader areas that the GitHub Desktop team is currently working on. Upvoting the issue with a 👍 and sharing the specific use cases you have for this feature is helpful for us in planning future product priorities.

**Comment by graphical-iain** [comment] 2020-05-11 21:28
With Tk deprecated in macOS, and thus the possible eventual loss of `gitk`, I think this feature will soon become instrumental for navigating local repositories.

**Comment by frumbert** [comment] 2021-10-04 23:26
so ... is this on the roadmap somewhere we can upvote for it? for me it's the reason i DO NOT use github desktop anymore.

**Comment by steveward** [comment] 2021-10-05 12:50
@frumbert the best way to give feedback is to upvote the issue since that lets us know it's a desired feature and helps us to prioritize future product decisions.

**Comment by ekimbernow** [comment] 2021-12-14 18:52
👍  We manage repos of 40K+ files across about 150 active authors. Being able to see both the log with diffs and blame report for individual files is essential.

**Comment by circleb** [comment] 2022-09-19 18:18
Hard to believe this isn't already implemented!

**Comment by calebrader** [comment] 2022-09-26 15:39
Please add this feature.

**Comment by PeterMurphyRWA** [comment] 2022-09-30 10:48
I'm selecting a version control system for our company, and really want to use GitHub
So I'm making a list of the basic requirements:  IMHO the top 2 things anyone needs are... 

1. To see the commit history of a specific file 
2. To be able to revert a commit
You can do (1) in github.com but not on desktop and you can do (2) in desktop but not in github.com 

An example gives you the context... 
I have a report that references a database table column that now doesn't exist 
So I know the problem is in the data dictionary for that table, probably someone removed a column without thinking of downstream effect 
And all I need to do is look at the history for that single file and see what needs to be reverted
But I can't that in GitHub desktop

This problem would be fixed by being able to see the commit history of a specific file in GitHub desktop
This is a *very* basic requirement - IMHO it should have been in first draft Miminal viable product, and it should go right to  the top of the roadmap.

**Comment by skolsocial** [comment] 2022-10-04 14:26
Please add this feature.

**Comment by ekimbernow** [comment] 2022-10-04 14:44
We are moving from EGit to Desktop and per-file history is so far the most requested feature.

**Comment by private-jil** [comment] 2022-10-14 11:23
> 👍 We manage repos of 40K+ files across about 150 active authors. Being able to see both the log with diffs and blame report for individual files is essential.

Sourcetree is really good for that. i'm not a huge fan of Atlassian, but they did a pretty good job with that one.  Wish this feature was in github desktop as well.

**Comment by FelixDraconis** [comment] 2023-02-27 19:03
Like some of the posters above not having this basically defeats the whole point of having a repository.

**Comment by mo-dtech** [comment] 2023-03-11 04:55
Yes - please add this feature. Surprised that this feature does not already exist. I use this all the time with our existing version control system. 
![image](https://user-images.githubusercontent.com/127247053/224465693-a0ae3fc6-c845-4f08-a58d-f92a13236b09.png)


Also need to be able to diff out of this list also.
![image](https://user-images.githubusercontent.com/127247053/224465674-4e5ba843-9b35-4f9e-95c5-46b98f92321b.png)

**Comment by intrepidws** [comment] 2023-03-11 11:53
Even if this were just a right-click menu item that linked to the website version of the history for that file, that would be super helpful.

**Comment by jornjanssen90** [comment] 2023-07-05 12:50
would be very nice to have this in github desktop. also the diff in left-right view

**Comment by mo-dtech** [comment] 2023-07-11 16:09
I used SourceTree instead of Github desktop because this allows me to diff like what I describe above.

![image](https://github.com/desktop/desktop/assets/127247053/d7a39b26-91f4-4ab3-86c8-fca5bda28faf)


You can also setup a separate diff tool if you prefer (I prefer Beyond Compare). All you have to do is select the file and press ctrl+d to use your preferred diffing tool that you have setup.

![image](https://github.com/desktop/desktop/assets/127247053/10744a8d-468e-4a35-884f-8a03f843e81f)

**Comment by creativetags** [comment] 2023-09-19 11:32
This feature would be so helpful

**Comment by arthabus** [comment] 2023-10-24 10:45
Was exploring alternatives to smartgit and loved the simplicity of github desktop, but lack of this feature is a dealbreaker. Sadly.

I often need to track down changes of specific files to see when regression was introduced and how to revert it.

sourcetreeapp is the next in line.

**Comment by intrepidws** [comment] 2023-10-24 13:32
I still maintain that just adding a right-click menu item that linked to the website version of the history for that file, would be an easy quick fix here.

**Comment by arthabus** [comment] 2023-10-24 13:39
@intrepidws by "the website version" do you mean github repository? 

In my case my code is hosted in a bitbucket repo and unless there is a web version of github desktop that has that feature this is not gonna help unfortunately. Unless I misunderstood you.

**Comment by intrepidws** [comment] 2023-10-24 13:41
@arthabus Yes, I did mean a Github repo. Does bitbucket not have a website page where you can view the history of a file?

**Comment by arthabus** [comment] 2023-10-24 19:02
@intrepidws yeah, you are actually right. Never used it before. Would be interesting to see at least such implementation. 

That might be just me but I really like how smartgit did it where they just filter and only show commits where the file was changed in the commit tree.

**Comment by intrepidws** [comment] 2023-10-24 19:49
@arthabus Sure, I agree that there could be a very nice native implementation within the app - but linking to the web version of the file history would be a nice quick fix while that is in process.

**Comment by rrwoods** [comment] 2023-12-20 04:43
this is such a basic use case that i am shocked it has gone unimplemented for this long :/

**Comment by mo-dtech** [comment] 2023-12-21 19:21
> I still maintain that just adding a right-click menu item that linked to the website version of the history for that file, would be an easy quick fix here.

Although you can get a file history on the website you cannot do diff from this web file history.  So, viewing what the changes are requires downloading the file from the website and doing a local compare (see picture below)... Not very useful

![image](https://github.com/desktop/desktop/assets/127247053/b5d295af-0d4c-453d-97be-4de4fd91ca54)

**Comment by mo-dtech** [comment] 2023-12-21 20:26
This is how it works in SourceTree

![image](https://github.com/desktop/desktop/assets/127247053/58348e73-5930-4367-bd9f-54bb61426f9e)


This opens up a new window
![image](https://github.com/desktop/desktop/assets/127247053/6c7c37aa-f9f6-4ec7-9070-c42251a1981c)


You can also use an 3rd party diff tool
![image](https://github.com/desktop/desktop/assets/127247053/28559997-6dbf-4207-8427-01736d4ed169)

Viewing changes in 3rd party diff tool
![image](https://github.com/desktop/desktop/assets/127247053/d1158bc6-aec0-4c66-89c6-9d51857066f5)

**Comment by Mavahu** [comment] 2024-05-29 13:28
Is there any plan to implement this in the future?

**Comment by lazycoder71** [comment] 2024-08-16 02:24
This feature is not implemented yet? It's been 6 years.

**Comment by hoyt-qflow** [comment] 2024-08-22 18:56
Recently tried to swap to desktop from tortoise, and lack of this feature is both surprising and a reason to swap back to tortoise. There are many instances when I know which file I want to check on, but not which commits may have been involved.

**Comment by hoangqwe159** [comment] 2024-11-04 22:43
Please add this feature. I dont want to open Git Kraken again

**Comment by loudenvier** [comment] 2025-02-18 17:58
I spent next to 30min digging the interface to see the history of a local file only to discover it's not implemented! To add insult to injury it's been quite a few years on the radar and nothing happened. This may be a dealbreaker for many people and such important feature missing makes Github Desktop seems like an afterthought IMO... :-( (since I was using Android Studio, it have this feature built-in for local history)

**Comment by nikita-kiryanov** [comment] 2026-01-27 12:47
Any news on implementing this?
