### ISSUE TITLE
Cannot switch to dark theme

### ISSUE THREAD

**Issue by tioteath** [desktop/desktop#2268] opened 2017-07-18 15:47 UTC
### Description

The dark them option is missing.

### Version

**GitHub Desktop version:** 0.6.2

**OS version:** windows 10

### Steps to Reproduce

1. Open app
1. Search for Look&Feel settings

**Expected behavior:** Dark Theme switch is easy accessible

**Actual behavior:** It is impossible to find Dark Theme switch

**Reproduces how often:** 100

**Comment by joshaber** [comment] 2017-07-18 15:57
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/1515. Please follow that issue for further updates.

**Closed by joshaber** 2017-07-18 15:57 UTC
