### ISSUE TITLE
Github Desktop gets stuck on Configure Git screen when setting it up for the first time.

### ISSUE THREAD

**Issue by mlandos** [desktop/desktop#8505] opened 2019-10-21 18:02 UTC
### Describe the bug

After downloading Github Desktop, I tried using it for the first time. However, when i get to the "Configure Git" page(screenshot below), where is asked what name i would like to have written on my commits, I click Continue after putting my name and email, but the Continue button doesn't trigger anything, is like if i hadn't click the button, not even an error is thrown. 
I've tried uninstalling and installing again, even deleting the GitHubDesktopSetup.exe file and downloading it again, but the same thing happens.

### Version & OS

I'm using Windows 10 and the Github Desktop version available on the website, which i believe to be 2.2.1 (https://desktop.github.com/)

### Screenshots

![image](https://user-images.githubusercontent.com/50081718/67230043-6e72ba00-f434-11e9-9053-0369aa0baeb1.png)

**Comment by billygriffin** [comment] 2019-10-21 18:33
Hi @mlandos, I'm so sorry you're experiencing this! Would you mind sharing your logs here from `Help` -> `Show Logs in Finder/Explorer`? That might help us figure out whether there's some error happening under the hood.

**Comment by tierninho** [comment] 2019-10-21 18:36
Also, if you could go to your command line (Command Prompt) and type `git config --list`. Please past the output for us. Thanks.

**Comment by mlandos** [comment] 2019-10-21 18:50
> Hi @mlandos, I'm so sorry you're experiencing this! Would you mind sharing your logs here from `Help` -> `Show Logs in Finder/Explorer`? That might help us figure out whether there's some error happening under the hood.

Hi @billygriffin, thanks for your reply. I can't click on the Help button, since i can't even get passed through the screen I showed on my original post. Basically I did the same as the guy on this video did (https://www.youtube.com/watch?v=qtxWg3kOnd0), but when clocking on continue on the screen that shows up at 1:43 it doesn't do anything. I'll try to reach to the log files manually and post them. Thanks.

> Also, if you could go to your command line (Command Prompt) and type `git config --list`. Please paste the output for us. Thanks.

Hi  @tierninho, thanks for your time. the output of the command give says: "git" is not recognized as an internal or external command.

**Comment by tierninho** [comment] 2019-10-21 19:02
@mlandos Thanks for the update. If you have not set up Git yet, please follow the instructions here: https://help.github.com/en/github/getting-started-with-github/set-up-git#setting-up-git 

This is a separate process from GitHub and Desktop, and is required to use the software. Once you are done, you can use the Git username and email on the Configure Git page in Desktop.

Let us know how it goes.

**Comment by bgermerTR** [comment] 2019-10-27 21:47
same issue here.

**Comment by tierninho** [comment] 2019-10-28 18:22
@mlandos  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

@bgermerTR Please open a new issue if you still need assistance. Thank you.

**Comment by philippthiele** [comment] 2019-11-21 08:37
I had the same issue. Installing git, setting username & email using command line (as described [here](https://help.github.com/en/github/getting-started-with-github/set-up-git#setting-up-git)) and then starting GitHub Desktop again worked for me.

**Comment by NoahMZX** [comment] 2019-12-23 23:09
I had the same issue. the next page only appears unless I delete all text on Configure Git page.

**Comment by billygriffin** [comment] 2019-12-27 19:36
Since we've seen further reports of this, I'm going to reopen the issue. @philippthiele @bgermerTR @NoahMZX Would you mind sharing any further details about your setup that you think could be causing this to help us diagnose?

**Comment by billygriffin** [comment] 2019-12-27 20:14
I think this is likely the same root cause at #8675, so I'm going to close this in favor of that. If y'all wouldn't mind heading over to that issue and letting us know if that seems like it's the cause of what you're seeing or if it's likely something different, that would be really helpful. Thank you!

**Closed by billygriffin** 2019-12-27 20:14 UTC
Labels: more-info-needed

**Comment by philippthiele** [comment] 2019-12-27 20:46
Hi @billygriffin I am not sure of this is the same issue. I installed github Desktop on a completely new PC and did not use git there before. How should the lock file have been created? But if the workaround I used deletes the lock file it could be the same issue.

**Comment by Laddeus** [comment] 2020-01-13 12:33
Currently having the same problem after installing desktop on a different machine.

**Comment by steveward** [comment] 2020-01-13 19:09
@Laddeus you should be able to resolve this by deleting the `.gitconfig.lock` file. The location of the lock file should be be `C:\Users\<Your_User\.gitconfig.lock`  -- once you delete that file you should be able to proceed on the `Configure Git` screen.

**Comment by Laddeus** [comment] 2020-01-13 22:29
@steveward Thanks for the reply! I solved the problem by running the program as administrator.
