### ISSUE TITLE
Github Desktop Branches List Disappeared

### ISSUE THREAD

**Issue by benweddel** [desktop/desktop#2527] opened 2017-08-22 21:08 UTC
### Description

The branches list has disappeared from view. Cannot change branches using the desktop GUI.

### Version

GitHub Desktop version: 0.8.1-beta1

OS version: Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Launch GitHub Desktop
2. Click "View"
3. Select "Branches list"

This is affecting all repositories. Looks like a regression after updating to latest.

Reproduces how often: 100% of the time (after relaunching app, signing in and out, restarting computer...)

### Logs

[2017-08-22.desktop.beta.txt](https://github.com/desktop/desktop/files/1243394/2017-08-22.desktop.beta.txt)

**Comment by steveward** [comment] 2017-08-22 21:21
Thanks for reporting this bug @benweddel. I'm going to close it as a duplicate of https://github.com/desktop/desktop/issues/2522. You can follow along there for updates.

**Closed by steveward** 2017-08-22 21:21 UTC

**Comment by shiftkey** [comment] 2017-08-23 22:38
FYI: the `0.8.1-beta2` update is now available and contains this fix.
