### ISSUE TITLE
Windows client clips offscreen at large text sizes 

### ISSUE THREAD

**Issue by cyrusae** [desktop/desktop#15141] opened 2022-08-20 04:21 UTC
### The problem

Today I installed GitHub Desktop on my laptop for the first time. On launch, the window with the "Create repository" etc. menus (see screenshot #1) clipped offscreen vertically. 

I attempted to zoom out in the client. This had no effect. I closed the window and restarted my machine; also no change.

I attempted to maximize the window; this was a mistake, as it produced the additional horizontal clipping seen in screenshot #2. It will not go back to the non-maximized size that did at least keep the close button on screen.

I am low vision and use multiple Windows system-level features as a result (see "Steps to reproduce"). However, I have not had this issue on other computers and earlier versions of GitHub Desktop (see "Additional context") and had in fact previously found the design to be usefully responsive.

### Release version

Version 3.0.5 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Set Windows 11 text size to 191% (Accessibility settings for display) and system scale to 125% (display).
2. Open GitHub desktop.

Optional:
4. Attempt to maximize window (clips offscreen)
5. Attempt to un-maximize window (does nothing)
6. Attempt to zoom out (does nothing)

### Log files

[2022-08-20.desktop.production.log](https://github.com/desktop/desktop/files/9386219/2022-08-20.desktop.production.log)

### Screenshots

Window clips offscreen, including top bar

![image](https://user-images.githubusercontent.com/86699936/185728499-6042d644-223c-4e8b-a132-b09a7b659e20.png)

where the top bar controls end up 

![image](https://user-images.githubusercontent.com/86699936/185728514-e796df8b-0fbb-4f60-9bbd-def5d0fc5ebb.png)

About menu clipping offscreen, further example of this meaning I can't use controls

![image](https://user-images.githubusercontent.com/86699936/185728558-792a66ff-45d4-4585-87b5-13dd33ed31f4.png)

### Additional context

This is happening on my laptop (17" screen); I have GitHub desktop on my desktop computer (also Windows 11, 27" and 34" screens) and have not had this issue with it. However, I last used GitHub desktop on that machine several months ago so this may be a new issue across screen sizes as opposed to a function of my laptop screen being relatively small for my accessibility requirements.

**Comment by cyrusae** [comment] 2022-08-20 06:05
Addendum: I've confirmed that this means I can't set up repositories full stop: 
![image](https://user-images.githubusercontent.com/86699936/185731495-e607237a-6fae-4ec9-9c9a-8e9369383fd3.png)

**Comment by tsvetilian-ty** [comment] 2022-08-20 09:56
@cyrusae thanks for reaching out! That is a known issue, and it should be fixed in the [beta release](https://desktop.github.com/beta/). Could you try it out and share your feedback?

**Comment by cyrusae** [comment] 2022-08-22 20:09
> @cyrusae thanks for reaching out! That is a known issue, and it should be fixed in the [beta release](https://desktop.github.com/beta/). Could you try it out and share your feedback?

`Version 3.0.6-beta3 (x64)` still clips vertically with no option to scroll to reach buttons/controls, but appears to have resolved the horizontal clipping: 

![image](https://user-images.githubusercontent.com/86699936/186009577-40769131-e308-44b9-87ff-261a66072993.png)

![image](https://user-images.githubusercontent.com/86699936/186009628-37a2d84b-f0e7-4070-a71d-6477b0e6284e.png)

(Apologies if this means there was an existing issue, my attempts at keyword search didn't find anything but I may just have failed to surface someone else's phrasing.)

**Comment by cyrusae** [comment] 2022-08-22 22:44
Addendum: Beta does restore `ctrl+` zoom but result (one increment) is just 
![image](https://user-images.githubusercontent.com/86699936/186031515-245227d6-2881-4a36-8966-a0ff6a42b816.png)
I should note that on launch I was surprised by how small the text size was in the first place; it does not appear to be pulling from system text size and I'm not sure if I just never ran into that on my larger desktop screen because it's large enough to use the client zoomed in.

**Comment by tsvetilian-ty** [comment] 2022-08-25 16:50
I've tested it, and you're absolutely correct about the "Let's get started!" screen it's impossible to use when zoomed in. Also, the dialogs don't have scrollable content, so the user can't use them either. 

The only option you have now is to scale down and zoom out so you can create or add a repo.

I'll label this issue as a bug.

**Comment by cyrusae** [comment] 2022-09-11 09:48
Most recent beta `ctrl+-` and the corresponding menu items no longer work, for the record (noticed and updated today).

**Comment by mettij** [comment] 2022-11-10 22:31
Hi, I'm interested in picking up this issue, can I get assigned to it?

**Comment by niik** [comment] 2024-09-18 13:25
We believe this was fixed by a combination of several accessibility related PRs such as #18412 that made zoomed-in dialogs scrollable. I tried running the "Let's get started screen" at 200% zoom and create a repository and both experiences were usable.

Since I'm no longer able to reproduce this I'm going to close it out but please let me know if either of you are still able to reproduce and we'll take another look!

**Closed as completed by niik** 2024-09-18 13:25 UTC
Labels: bug, priority-3
