### ISSUE TITLE
Context menu "open in" not always enabled for editable files on Windows

### ISSUE THREAD

**Issue by JC3** [desktop/desktop#12108] opened 2021-04-30 18:08 UTC
### Describe the bug

For some text file types on Windows, when right-clicking the file in the left pane, both "Open In Notepad++" and "Open With Default Program" are disabled, even if the file is editable in Notepad++ or has a default program registered, respectively.

Examples of file extensions that don't work (both actions disabled) on my system include: *.bat, *.sh, .gitignore.

![image](https://user-images.githubusercontent.com/5651184/116735160-25ea7400-a9bc-11eb-87e0-5f6f0f9ed44a.png)

Examples of file extensions that work as expected (appropriate actions enabled) include: *.pro, *.txt, *.csv, *.cpp

![image](https://user-images.githubusercontent.com/5651184/116735194-2e42af00-a9bc-11eb-977b-1b312bd63824.png)

Note also that, on my machine, Notepad++ is, in fact, the default program associated with .gitignore files -- this makes it extra strange that both "Open In" options are disabled in GHD:

![image](https://user-images.githubusercontent.com/5651184/116736122-73b3ac00-a9bd-11eb-97a8-e83eb2db8d1d.png)

I do not know how GHD determines if the actions should be enabled, so I do not know what the precise cause is.

Expected behavior: "Open In Notepad ++" should be enabled for *all* text files (and tbh, probably for binary files too, as it has use there as well). "Open With Default Program" should be enabled for all files with a default program (and as a bonus, it would be nice if it fell back to the *open* verb, and then to the *edit* verb).

### Version & OS

GitHub Desktop: 2.8.0
OS: Windows 10, 64-bit

**Comment by JC3** [comment] 2021-04-30 18:23
PS After browsing through some other issues here, worth noting: The full path to the repo in my example is:

    C:\Users\JC3\Projects\Qt\modelsplit\

There are no multibyte characters or single quote marks in any of the full paths and filenames to any of the files in this repo.

**Comment by tidy-dev** [comment] 2021-05-03 11:57
@JC3 Sorry for your frustration. These extensions `'.cmd', '.exe', '.bat', '.sh` were disabled as a security precaution. 

However, there is an [open issue](https://github.com/desktop/desktop/issues/6361) requesting they be reenabled for the external editor option as it can be reasonably assumed that these applications (that are limited by GitHub Desktop) will not run the file on open.

I am going to close this issue if favor of the one already established. Feel free to give it a thumbs up or add your own context.

**Closed as completed by tidy-dev** 2021-05-03 11:57 UTC

**Comment by JC3** [comment] 2021-05-03 23:00
> @JC3 Sorry for your frustration. These extensions `'.cmd', '.exe', '.bat', '.sh` were disabled as a security precaution.
> 
> However, there is an [open issue](https://github.com/desktop/desktop/issues/6361) requesting they be reenabled for the external editor option as it can be reasonably assumed that these applications (that are limited by GitHub Desktop) will not run the file on open.
> 
> I am going to close this issue if favor of the one already established. Feel free to give it a thumbs up or add your own context.

Hi. Why can't I edit .gitignore?

**Comment by tidy-dev** [comment] 2021-05-07 12:45
@JC3 Sorry it took a bit to get back to you. Desktop does not have anything to limit the `.gitignore` file over any other file. Thus, I am unable to reproduce being unable to open `.gitignore` in my default program or notepad++. I suspect it is something to do with your specific environment. Maybe try uninstalling/reinstalling notepad++. 

![image](https://user-images.githubusercontent.com/75402236/117451237-3e084900-af10-11eb-9836-0b6609443f3e.png)
