### ISSUE TITLE
GitHub Desktop won't open at all

### ISSUE THREAD

**Issue by Aleg21-11** [desktop/desktop#19327] opened 2024-09-29 22:49 UTC
I downloaded GitHub Desktop but it doesnt open either when just installing nor when i try to open in it in my %appdata% files. I can't find it in my windows explorer either, but when I open the control Panel I see the github Desktop app there, until I click it and then it dissapears. I dont know what the problem is. I have tried

Uninstalling and Installing again
Deleted the files in %LOCALAPPDATA% and %APPDATA%
Running the installer as Admin

Using exe to install

**Comment by sergiou87** [comment] 2024-09-30 07:24
Dupe of https://github.com/desktop/desktop/issues/19315

**Closed as not planned by sergiou87** 2024-09-30 07:24 UTC
