### ISSUE TITLE
Git name and email getting overridden by SourceTree

### ISSUE THREAD

**Issue by PLPeeters** [desktop/desktop#1860] opened 2017-06-01 14:00 UTC
### Description

After each commit with SourceTree, my name and email in the GitHub client are getting overridden by the ones used in SourceTree. The same issue happens the other way around.

### Version

**GitHub Desktop version:** 0.5.8

**OS version:** OS X 10.12.3

### Steps to Reproduce

1. Make a commit in SourceTree (to any repository) with another user
2. Open the GitHub Desktop preferences and look at the Git tab

**Expected behaviour:** The name and email didn't change.

**Actual behaviour:** The name and email changed to the ones used by SourceTree.

**Reproduces how often:** 100%

### Logs

N/A

#### Additional Information

N/A

**Comment by shiftkey** [comment] 2017-06-01 14:05
> After each commit with SourceTree, my name and email in the GitHub client are getting overridden by the ones used in SourceTree.

That panel displays [what's declared globally for your `user.name` and `user.email` config](https://github.com/desktop/desktop/blob/master/app/src/ui/preferences/preferences.tsx#L56-L57), so I think the issue here is with SourceTree.

**Comment by PLPeeters** [comment] 2017-06-01 14:13
That's what I figured, but wouldn't it be better for clients to store that in their own data instead of relying on Git's config values? That would avoid issues like this.

Moreover, since the Git Desktop client is authenticated to the user's GitHub account, I have a feeling it should implicitly use a name and email of its own for Git instead of the one defined globally (it could default to that one, though). I feel having a panel to configure those values only exacerbates this, but maybe that's just me.

The issue is a sort of the same with SourceTree, but they _do_ store the name and email, which allows me to switch back in a click.

**Comment by shiftkey** [comment] 2017-06-01 14:57
> Moreover, since the Git Desktop client is authenticated to the user's GitHub account, I have a feeling it should implicitly use a name and email of its own for Git instead of the one defined globally (it could default to that one, though).

There's a few schools of thought around this, and it generally leads to one of two end games:

 - every IDE providing it's own settings pane, and overriding the global `user.name` and `user.email` settings by passing in the author information when committing, like this:  `git commit --author='name <email>' ...`

While this is nicer for closely tying account information to commits and avoiding touching configuration values, we've found it's a bit more confusing for users who are familiar with the global config and expect it to behave in that way.

 - set `user.name` and `user.email` in `~/.gitconfig`, _if not already defined by another tool_, and using this value when committing

I still like this solution, as it means whichever tool is doing the `git commit` - whether it's an IDE or even the command line - uses the same values. Visual Studio also works in the same way as Desktop.

<img width="322" src="https://cloud.githubusercontent.com/assets/359239/26685561/e1128c80-46c0-11e7-99d0-e360055266fb.png">

I think keeping things shared is better for everyone, but this is just my opinion.

> The issue is a sort of the same with SourceTree, but they do store the name and email, which allows me to switch back in a click.

This bit is unclear to me (and I haven't had a chance to test this out, so apologies) but it feels like they're doing a mixture of both of these options.

**Comment by PLPeeters** [comment] 2017-06-02 07:55
Since this seems to be a topic people have divergent opinions about, I feel like a simple way to make everyone happy would be to add a checkbox to enable or disable this, something like "use global configuration", which is checked by default.

* If it's checked, the client uses and overrides the global Git config when the values are changed, as it does now.
* If it's not checked, the client sets the defaults to the values in the global Git config and stores the name and email used for commits in the preferences. They are then passed with each commit.

Thoughts?

> This bit is unclear to me (and I haven't had a chance to test this out, so apologies) but it feels like they're doing a mixture of both of these options.

Now that I think about it, it's actually weird. When I do a "Set as default" on my _BitBucket_ account in SourceTree, it somehow sets my name and email for Git back to what they were, but that doesn't make any sense, as those aren't part of the BitBucket account...

**Comment by shiftkey** [comment] 2017-06-25 22:37
I couldn't reproduce this issue after signing into my Bitbucket account, but I think the magic is related to this feature under Preferences (it was enabled by default):

<img width="691" src="https://user-images.githubusercontent.com/359239/27520254-a1d61358-59bb-11e7-9062-5af6aa269bc0.png">

My name and email are shown correctly before committing and I didn't see it change the global config either after the commit.

<img width="923" src="https://user-images.githubusercontent.com/359239/27520256-a78a06ce-59bb-11e7-93cf-07570e249819.png">

As this initial issue was related to SourceTree behaviour, and it's not something that we can address here in Desktop, I'm going to close this out.

@PLPeeters if you still feel strongly about the "use global configuration or use account information" changes, please open a new issue so we can talk about that further.

**Closed by shiftkey** 2017-06-25 22:37 UTC
Labels: bug

**Comment by j-f1** [comment] 2017-06-25 23:00
The app could also modify the repository-local config instead of the global one.

**Comment by PLPeeters** [comment] 2017-06-26 10:00
@shiftkey I just tried unchecking that box, but it just makes SourceTree use the global configuration files for its config, so the issue persists... 

I agree with @j-f1 here, making the app modify the local configuration would be better (or at least making it configurable).

**Comment by kguds** [comment] 2018-03-30 21:41
Also agree with this - would like to use github desktop for personal projects on the same laptop as I use tortoisegit for work.
