### ISSUE TITLE
Frozen APP

### ISSUE THREAD

**Issue by elvisz2016** [desktop/desktop#4387] opened 2018-04-03 15:31 UTC
The App is frozen!! My system is Win 10.
![image](https://user-images.githubusercontent.com/24736504/38259267-2b3b75f2-3797-11e8-89dd-a98c2936edbf.png)

**Comment by nerdneha** [comment] 2018-04-04 06:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3983. Could you provide the information in that issue including the fact that your system is Win 10, the version of Desktop you are running, the last action you did before your app froze, log files, and any other interesting details about your setup?

**Closed by nerdneha** 2018-04-04 06:00 UTC
