### ISSUE TITLE
`Publish branch` button fails to update

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#9678] opened 2020-04-30 20:33 UTC
After clicking the `Publish branch` button and seeing the branch show up on the remote, the button fails to go away, and switch to the `Fetch origin` button.

Steps I took:
- Cloned this repo which a fork https://github.com/anshul78/easylist
- Opened a new branch, attempted to commit a change, clicked "Yes, fork this repo"
- Tried to publish the branch.

I expected Fetch origin to show up but it never did, despite seeing the code pushed. I wonder if being a clone of a fork of a fork is confusing the upstream logic?

Here is the `remote -v` output along with the state of Desktop after clicking `Publish branch`:
![Screen Shot 2020-04-30 at 10 24 20 AM](https://user-images.githubusercontent.com/14828183/80755898-5491ee00-8acd-11ea-9bb8-af9c619dabc7.png)

Here are the branches published on dotcom:
![Screen Shot 2020-04-30 at 10 24 35 AM](https://user-images.githubusercontent.com/14828183/80755905-56f44800-8acd-11ea-8a49-3e2fb7995743.png)

_v2.4.3, OSX_

**Comment by rafeca** [comment] 2020-05-01 12:16
Hey @tierninho ! Did the publish button disappear after refreshing/restarting the UI or it stayed there? What happens if you click publish again? Gonna try to reproduce it with that same repo

**Comment by tierninho** [comment] 2020-05-01 18:33
> Did the publish button disappear after refreshing/restarting the UI or it stayed there? 

The button continues to persist after refreshing/restarting the UI. I even tried reloading from the console. When I recloned the repo, it did go away.

> What happens if you click publish again? 

It says Pushing, then Fetching, then goes back to the Publish state.

> Edit: I haven't been able to reproduce using the same steps 😢

It might just be some one-off weird state I got into. Feel free to close if you agree.

**Comment by rafeca** [comment] 2020-05-05 08:12
Let's close it for now, since it's possible that it was a one-off weird state. If somebody experiences it again we can reopen and investigate further.

**Closed by rafeca** 2020-05-05 08:12 UTC
Labels: bug, priority-3

**Comment by attilabalogh** [comment] 2020-06-09 16:18
I have the same issue with a new repository I added using Desktop. The master branch is updated on github.com with each commit, but the button continues to say "Publish branch".

**Comment by conquillacarl** [comment] 2020-11-26 14:22
I am also having this issue - after updating and restarting my machine I have the Publish Branch button showing but not doing anything when clicked. It could be that it has something to do with the repository being located on a network drive?

Edit: Fixed; After waiting a few minutes it appears it has switched to the correct branch and things seem to be working correctly again.

**Comment by FredieDidier** [comment] 2022-03-31 20:44
> I have the same issue with a new repository I added using Desktop. The master branch is updated on github.com with each commit, but the button continues to say "Publish branch".

Hi, I am facing this same issue. Anyone knows any solution to fix it?
