### ISSUE TITLE
Where is the old version?

### ISSUE THREAD

**Issue by bumblebritches57** [desktop/desktop#3737] opened 2018-01-06 23:51 UTC
I don't want this web nonsense, where's the old one?

My High Sierra upgrade deleted it.

**Comment by iAmWillShepherd** [comment] 2018-01-06 23:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/2295. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-01-06 23:54 UTC

**Comment by j-f1** [comment] 2018-01-06 23:59
> I don't want this web nonsense

Why not? What’s wrong with the new version? Is there something we can fix?

**Comment by chaosvolt** [comment] 2019-04-16 20:49
I've been having some weird issues as of late with fetch, push, cloning etc all failing to work right in desktop (luckily shell/command line still goes through). There are two major things I'm testing for, related to it working right on my desktop at home but not on my laptop.

The first thing I'm testing is the fact that the PC has an older version of desktop while the laptop has 1.4, and it would've been infinitely less hassle to test for this if I didn't have to search so hard for a link to one of the older versions. Now that I do have an older version I can test if the issue is with the version vs. something specific to this machine.
