### ISSUE TITLE
Authentication failed issue - Azure DevOps

### ISSUE THREAD

**Issue by RoHeck** [desktop/desktop#18594] opened 2024-05-10 06:02 UTC
### The problem

I have the same probleme like in this issue [#18586](https://github.com/desktop/desktop/issues/18586)
I was asked to create a new issue with my log files.

I use Windows 11 with Github-Desktop 3.3.17 (everything worked with 3.3.14)
My repro is hosted with Azure DevOps

### Release version

3.3.17

### Operating system

Windows 11

### Log files

[2024-05-10.desktop.production - issue.log](https://github.com/desktop/desktop/files/15271460/2024-05-10.desktop.production.-.issue.log)

### Screenshots

![grafik](https://github.com/desktop/desktop/assets/74710019/f98278f6-4218-403d-b7ed-c33a04008c6b)

**Comment by sergiou87** [comment] 2024-05-10 08:47
Hey @RoHeck 👋 

Thank you for your report and your logs. Is it possible that you're providing the wrong password when asked for credentials?

More specifically, Azure DevOps repos require "Personal Access Tokens" (instead of your account password) which can be generated following the instructions in this article: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows

Please, let us know if that helps.

**Comment by RoHeck** [comment] 2024-05-10 09:34
In the past I was able to connect without a personal access token, but i have tried it out with a token just now, but it results with the same issue.

**Comment by erencylk** [comment] 2024-05-10 17:47
I have same problem. I was able to access via PAT, but now we are getting the same error.

**Comment by steveward** [comment] 2024-05-10 18:12
@RoHeck just to confirm so we're not missing anything -- did you ensure your access token had the correct scopes set? One way to check would be to use the same token on the command line to clone a repo.

> I have same problem. I was able to access via PAT, but now we are getting the same error.

@erencylk are you also using Azure DevOps? Can you share the log file from GitHub Desktop from a day you encountered this error?

**Comment by erencylk** [comment] 2024-05-10 18:26
> @RoHeckhiçbir şeyi kaçırmamamızı sağlamak için sadece onaylamak amacıyla -- erişim belirtecinizin doğru kapsamların ayarlandığından emin oldunuz mu? Kontrol etmenin bir yolu, bir repoyu klonlamak için komut satırında aynı belirteci kullanmak olacaktır.
> 
> > Bende de aynı sorun var. PAT üzerinden erişebildim ancak şimdi aynı hatayı alıyoruz.
> 
> @erencylksiz de Azure DevOps kullanıyor musunuz? Bu hatayla karşılaştığınız günün günlük dosyasını GitHub Desktop'tan paylaşabilir misiniz?

I'm using Azure DevOps server. Git desktop version 3.3.14 works but when I update it it doesn't work

**Comment by RoHeck** [comment] 2024-05-13 06:25
I have tried it with a read/write, as well as with a full-access token.

Is there a way to download 3.3.14 just that i can use a functional version for the moment?

**Comment by jonaspetraska7** [comment] 2024-05-13 07:03
Go to your install path : %LOCALAPPDATA%/GitHubDesktop/app-3.3.14 there should be a GitHubDesktop.exe for the 3.3.14 version, make a shortcut and use 👍

**Comment by RoHeck** [comment] 2024-05-13 07:35
@jonaspetraska7  Perfect! It works - thank you very much!

**Comment by sergiou87** [comment] 2024-05-13 09:53
@erencylk  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

@RoHeck just curious, does your repo use submodules or LFS? 🤔 Does it work if you run `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` from the terminal (which is exactly what GitHub Desktop does) ? It should ask you for credentials too.

**Comment by ianfife** [comment] 2024-05-14 15:12
Getting the same issue.

**Comment by RoHeck** [comment] 2024-05-16 10:05
git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin
dosen't work too
but a simple "git fetch" as well as "git  fetch --progress --prune --recurse-submodules=on-demand origin" works

**Comment by sergiou87** [comment] 2024-05-24 08:04
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by sergiou87** [comment] 2024-05-29 09:21
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏

**Closed as completed by sergiou87** 2024-05-29 09:21 UTC

**Comment by umarWonderTree** [comment] 2024-06-03 10:02
I'm on 3.4.0 and getting same problem. I'm not prompted for username/password but bullet point list of troubleshooting options. I tried to push the code through visual studio, it was successful. I can see the updated changes on Github Desktop, but still I can't push anything from Github Desktop.

**Comment by RoHeck** [comment] 2024-06-03 14:29
The problem is still there in 3.4.0 for me.

**Comment by tidy-dev** [comment] 2024-06-03 14:33
@RoHeck and @umarWonderTree  [have you tried setting the git config to allow using http path](https://github.com/desktop/desktop/issues/18594#issuecomment-2128857417)?

**Comment by SvenPepermansFS** [comment] 2024-06-04 12:10
> @RoHeck and @umarWonderTree [have you tried setting the git config to allow using http path](https://github.com/desktop/desktop/issues/18594#issuecomment-2128857417)?

I'm working with Azure DevOps repositories that are all hosted under the same org. After updating to 3.4.0, as expected Github Desktop prompts me for a login, except it does this for each repository separately instead of re-using my credentials after logging in a first time. Is this expected behavior to prompt login for each repository? PAT management wise, it's quite an annoyance to re-login for each repository.

**Comment by penCsharpener** [comment] 2024-06-05 13:16
I'm on 3.4.0 and can't use Github Desktop anymore with an on-premise Azure DevOps instance for about a month now. Whatever combination of logins I try it won't authenticate. Tried as username: email, AD user name with and without domain, as password a PAT. The `git config --global credential.https://gitlab.com.useHttpPath true` didn't help either. Any other git client works. When I remove all git related logins from the Windows credential manager, gitextension asks for a login with the git credential manager. Github Desktop prompts with with it's own login and it puts credential in Windows credential manager but it never works.

**Comment by niik** [comment] 2024-06-12 11:40
:wave: we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.

<img width="608" alt="Screenshot of Desktop's advanced preferences section with a highlight around the new option to enable Git Credential Manager" src="https://github.com/desktop/desktop/assets/634063/5d4da983-7663-49dd-bb7b-ce51ee9d2d3a" />

When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs). 

Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.

**Comment by jacobguilbeau** [comment] 2024-06-12 16:17
> 👋 we just shipped GitHub Desktop 3.4.2-beta2 to our [beta channel](https://desktop.github.com/beta/). This includes support for using [Git Credential Manager](https://gh.io/gcm). It's currently off by default but you can enable it in Settings under the advanced tab. We believe this will address the authentication problems outlined in this issue.
> 
> <img alt="Screenshot of Desktop&apos;s advanced preferences section with a highlight around the new option to enable Git Credential Manager" width="608" src="https://private-user-images.githubusercontent.com/634063/338943212-5d4da983-7663-49dd-bb7b-ce51ee9d2d3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDkyNDUsIm5iZiI6MTcxODIwODk0NSwicGF0aCI6Ii82MzQwNjMvMzM4OTQzMjEyLTVkNGRhOTgzLTc2NjMtNDlkZC1iYjdiLWNlNTFlZTlkMmQzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNjE1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDkyNjM3ZGE3NzEwYWQyYmU3YjY2Yjk4M2E0MTQ5ZTVjZjU2MjUzM2YyNzE3ZDM4OTI3YzU4NGRiOGY2ODUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QpdIeCR2h0-omae3SN_YB8H2WP1EJfhea7aASNlfvxs">
> When Git Credential Manager (GCM) is enabled all credentials for third-party (i.e. Azure Devops, BitBucket, GitLab etc) will be handled, and stored, outside of GitHub Desktop. GCM supports browser-sign in to many popular services and will avoid the need to create personal access tokens (PATs).
> 
> Please download our beta version from https://desktop.github.com/beta/ to give this a go and please report back with your experience. We'll be collecting feedback in our beta channel which will inform when we make this available to all users. Installing the beta version will not clear your preferences or tracked repositories and you can switch to the production version by simply downloading the latest version from https://desktop.github.com.

I can confirm that with beta 3.4.2 GitHub Desktop, checking "Use Git Credential Manager" and then installing git-credential-manager allowed my organization's Azure DevOps to sign-in flawlessly to GitHub Desktop via SSO.  This is for a GitHub Desktop that previously worked with a PAT from Azure DevOps that no longer did, as other people have reported in this thread.  Thanks!

For everyone else, to clarify my steps (This is on Windows 10 22H2)

1. Installed git-credential-manager via dotnet tools - dotnet tool install -g git-credential-manager
2. Ran git-credential-manager configure which then listed:
Configuring component 'Git Credential Manager' ...
Configuring component 'Azure Repos provider' ...
3. Installed GitHub Desktop beta 3.4.2 as listed above
4. Opened and configured GitHub Desktop beta 3.4.2 to use Git Credential Manager as listed above
5. Pulled from my existing repo at which point a Git Credential Manager window appeared asking me to Single Sign-On to my organization's Microsoft account.  I did and the repo pulled successfully - no PAT or passwords (other than SSO) needed.

**Comment by niik** [comment] 2024-06-12 16:23
That's great to hear @jacobguilbeau, thanks for reporting back!

> and then installing git-credential-manager

Just for the record, installing Git credential manager is not necessary for GitHub Desktop's functionality since we bundle it within Desktop.
