### ISSUE TITLE
dark mode - blinking issue in diff when switching between changed file

### ISSUE THREAD

**Issue by adamsir** [desktop/desktop#5614] opened 2018-09-12 14:05 UTC
## Description

Dark mode - travelling between changed files will cause ui blinking in the right column(probably the empty state is triggering while re-rendering the right view)

## Version

* GitHub Desktop: 1.3.5

* Operating system: macOS High Sierra 10.13.6

**Comment by shiftkey** [comment] 2018-09-12 14:08
@adamsir are you able to capture a video/GIF of the problem too? This will help us understand what you're seeing.

**Comment by adamsir** [comment] 2018-09-12 14:16
![github_client_5614](https://user-images.githubusercontent.com/5871877/45431106-3cc2e780-b6a7-11e8-9bd6-eea023bbb144.gif)

**Comment by j-f1** [comment] 2018-09-12 14:55
I see this in the light theme too. Looks like there are 3 steps:

1. “No local changes”
1. Diff with solid white/black text
1. Syntax-highlighted diff

**Comment by cwongmath** [comment] 2018-09-15 22:31
I can confirm this as well. https://gyazo.com/304f5f3ce7f98c84d177387f6796dcd4

**Comment by j-f1** [comment] 2018-09-15 23:05
Seems like this shouldn’t be labeled `themes` since the themes don’t affect it.

**Comment by shiftkey** [comment] 2018-09-16 16:35
Some extra context: this work is being performed in `TextDiff`, which invokes the highlighter web worker and then updates the Codemirror diff

https://github.com/desktop/desktop/blob/dd831bc4d494c830ea2fc9ec80d11906776b42cf/app/src/ui/diff/text-diff.tsx#L114

I suspect this flicker is the first render of the diff (with no highlighting) which is then updated with the tokens to highlight:

https://github.com/desktop/desktop/blob/dd831bc4d494c830ea2fc9ec80d11906776b42cf/app/src/ui/diff/text-diff.tsx#L145-L152

**Comment by shiftkey** [comment] 2018-09-16 18:10
I've also been able to see this behaviour on Windows 10, but I'm open to suggestions about how to mitigate this (should we skip rendering the diff until the syntax highlighting either succeeds or fails?)

**Comment by steveward** [comment] 2023-05-18 20:41
Fixed in https://github.com/desktop/desktop/pull/6660.

**Closed by steveward** 2023-05-18 20:41 UTC
Labels: bug, priority-3
