### ISSUE TITLE
Incorrectly reporting "there will be conflicting files"

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#5664] opened 2018-09-16 22:07 UTC
## Description

Github desktop has been reporting "there will be conflicting files after this merge" incorrectly in my last few merges. This makes us think there will be merge conflicts, but then we go ahead and proceed with the merge, which goes fine and no conflicts arise from it after all.

## Version

* GitHub Desktop: 1.4.0

* Operating system: OS X 10.11.6

## Steps to Reproduce

I don't know under what circumstances this happens, as I have seen this new feature work correctly before, but the last few times it happened, all I tried to do was to merge some commits from the master branch back into some feature branches. I did this for 2 different feature branches in 2 different repos, and it happened all 4 times.

### Expected Behavior
For there to be no warning, as there were no merge conflicts.

### Actual Behavior
A warning is displayed which is confusing, as there are no actual conflicts after the merge.

## Additional Information

I did some additional merges, and actually found the opposite happened too. I initiated a merge, it told me there would be no merge conflicts, but then after the merge, conflicts appeared after all.

### Logs

There was no additional information in the logs.

**Comment by shiftkey** [comment] 2018-09-16 22:43
@adamreisnz I'd love to dig into this myself - are you able to reproduce this against a public repository?

**Comment by adamreisnz** [comment] 2018-09-16 22:49
No sorry, this happened in our private repos.
If it helps, the work flow was something along the lines of:

1) Feature branch created based of master branch
2) Work done on feature branch
3) Work done on master branch
4) Other feature branches merged into master branch
5) Try to back-merge changes from master into the feature branch

At that stage the app reported the conflicts, but none appeared.

If I see this happen again, I will try to get the logs right away.

**Comment by shiftkey** [comment] 2018-09-16 23:27
@adamreisnz I don't generate much detail in the logs for this (because merges can be complex and I don't want to bloat the logs with the raw output that may include sensitive code). You can look at the Console tab in Dev Tools with Verbose messages enabled and find the relevant `git merge-tree` operation (it should have three SHAs as arguments) and you can run that again on the command line to see the conflicts that the app was detecting.

I'm tracking #5568 which seems to be a limitation about `git merge-tree`, and I suspect Git is jumping in and performing more heavy lifting on the actual `git merge` than what `git merge-tree` does.

**Comment by adamreisnz** [comment] 2018-09-16 23:51
So it happened again a couple of times.
`git merge-tree` reported several conflicts, but then when I did the actual merge, there were none.

Is there any information from the `git merge-tree` command output that will help you analyse this?

**Comment by shiftkey** [comment] 2018-09-17 00:00
@adamreisnz `git merge-tree` is probably showing conflict markers. I'm curious what the output looks like there, versus how the files look after the merge (when they were able to be merged successfully).

**Comment by adamreisnz** [comment] 2018-09-17 00:34
Ok, can I email that to you as they contain proprietary code I don't want to post that here.

**Comment by shiftkey** [comment] 2018-09-17 00:36
@adamreisnz my email [handle]@[this website] works

**Comment by adamreisnz** [comment] 2018-09-17 00:52
Thanks, sent

**Comment by shiftkey** [comment] 2019-07-30 16:59
We've made some progress on a solution here, and as the work requires more than just a bugfix I'm going to close this out in favour of #8049. Please follow along with that.

**Closed by shiftkey** 2019-07-30 16:59 UTC
Labels: investigation-needed
