### ISSUE TITLE
SSH signing doesn't work

### ISSUE THREAD

**Issue by applecuckoo** [desktop/desktop#15302] opened 2022-09-17 07:31 UTC
### The problem

I have an SSH key tied to my Git configuration. This key works fine when I do a `git commit -S -m` through Git Bash, but when I do it through GitHub Desktop, I get the following error:

>error: Load key "C:\\Users\\[username]\\AppData\\Local\\Temp/.git_signing_key_tmp[changing string]": invalid format?
>fatal: failed to write commit object

### Release version

3.0.8

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Add an SSH key for signing as shown in [this GitHub guide](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key#telling-git-about-your-ssh-key)
2. Try doing a commit with GitHub Desktop

### Log files

[2022-09-16.desktop.production.log](https://github.com/desktop/desktop/files/9591196/2022-09-16.desktop.production.log)
[2022-09-17.desktop.production.log](https://github.com/desktop/desktop/files/9591197/2022-09-17.desktop.production.log)

### Screenshots

![error](https://user-images.githubusercontent.com/113647417/190845842-bd0faa4d-d2fd-4865-b418-b174214a855e.png)
![macerror](https://user-images.githubusercontent.com/113647417/191170621-4cda769b-3cc8-4e6a-a60a-e8b048695f57.png)

### Additional context

~~On my Mac, I don't get an error when I use my SSH key there.~~
_**UPDATE 20/09/22:**_ Doesn't work on a Mac either!

**Comment by applecuckoo** [comment] 2022-09-17 08:01
**UPDATE**: I have since tried getting Git Bash to automatically start up ssh-agent as described [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows), though it only makes a difference with the shell. So still the same problem with Github Desktop.

**Comment by steveward** [comment] 2022-09-19 17:37
Thanks for the report @applecuckoo. I was able to reproduce this as well on my Windows machine. I'm not quite sure what's happening here as the signing key mentioned in the `Temp` directory looks correct. I confirmed it also worked from the command line for me as well.

I'll label this as a bug for us to investigate.

**Comment by applecuckoo** [comment] 2022-09-19 19:32
Thanks @steveward, glad to know it's not just me.

**Comment by applecuckoo** [comment] 2022-09-20 05:00
Hmm, terminal doesn't work either, I think that might be a bug with git itself. What do you think?

**Comment by applecuckoo** [comment] 2022-09-20 08:04
Alright, filed a bug on the Git mailing list ([linked here](https://lore.kernel.org/git/CACNTUeYfOXwF+WWAi=EVLw3snkAFtAoDkBK_YZG6AxVvPAHDQg@mail.gmail.com/)) about this bug.

**Comment by JiaweiShen9** [comment] 2022-10-14 01:59
> **UPDATE**: I have since tried getting Git Bash to automatically start up ssh-agent as described [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows), though it only makes a difference with the shell. So still the same problem with Github Desktop.

I ran into similar issue and thanks to this updated post I fixed it by running an ssh command before I commit. Apparently git commit signing with ssh doesn't work without ssh agent running. I haven't seen this documented anywhere nor can I infer this by reading the error message I got. I think it should be documented by Github or git to prevent causing more confusion.

**Comment by mettij** [comment] 2022-11-10 22:35
Hi, im interested in trying to solve this issue, can i be assigned to it?

**Comment by jblsk** [comment] 2022-11-18 09:36
I have the same behaviour on MacOs Ventura in terminal. Clearly, the path in error message is constructed wrong, as there is duplicated slash after the TMPDIR env. variable:
```
% git commit -S --amend                                   
error: Load key "/var/folders/x0/2d98rx897cnfgb1q9chxfq4c0000gp/T//.git_signing_key_tmpnM7iuw": invalid format?

fatal: failed to write commit object
% echo error: Load key '"'$TMPDIR
error: Load key "/var/folders/x0/2d98rx897cnfgb1q9chxfq4c0000gp/T/
```
The key itself is in place:
```
% ls -a $TMPDIR | grep .git_signing_key_tmpnM7iuw 
.git_signing_key_tmpnM7iuw
```
but the path to it it the error message on top is wrong.

**Comment by gosuto-inzasheru** [comment] 2022-12-13 12:22
@jblsk any (short term) solution to this? im kinda stuck on this

note: this is occurring for me in cli!! sorry didnt catch the context of this issue so fast

**Comment by jblsk** [comment] 2022-12-13 14:06
@gosuto-inzasheru unfortunately no, I simply switched to gpg keys instead of ssh, was quick and easy.

**Comment by applecuckoo** [comment] 2022-12-13 19:00
@gosuto-inzasheru same here, gpg seems more reliable.

**Comment by marco-brandizi** [comment] 2023-03-10 15:50
In my case, I've been banging my head until I realised `user.email` is wrong, different than the one in my GH profile. I've used  `git config --global user.email <email>` and then it worked fine.

**Comment by jnnnnn** [comment] 2024-05-16 04:05
We had this problem and fixed it by using a path to the key instead of the contents of the public key file. 

In the examples below, I will use `id_rsa` as the filename of the key, but newer versions of `ssh-keygen` may default to `id_ed25519` or similar, so adjust as necessary.

Here's what my gitconfig (on Windows) now looks like:

```properties
[user]
	name = Your Name Here
	email = your@email.here
	signingkey = "~/.ssh/id_rsa.pub"
[commit]
	gpgsign = true
[gpg]
	format = ssh
[gpg "ssh"]
	allowedSignersFile = "~/.ssh/id_rsa.pub"
```

If you have a passphrase on your key, you will now probably get the error

    incorrect passphrase supplied to decrypt private key?

To fix this, you will also need to set up the openssh agent. See https://stackoverflow.com/a/58784438 :
1. enable/start the `OpenSSH Authentication Agent` in Services (search in the start menu)
2. in a command window, run `ssh-add %USERPROFILE%/.ssh/id_rsa` and provide your passphrase
   - or in bash, run `ssh-add ~/.ssh/id_rsa`
   - or in powershell, run `ssh-add $HOME/.ssh/id_rsa`
4. When you reboot, repeat the above steps
   - by following https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases you can remove your passphrase, or start the agent automatically (although you will still have to do `ssh-add` after every reboot).
   - by following https://stackoverflow.com/a/4356869 you can install [PuTTy](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html), use PuttyGen to convert your key for Pageant and then set `GIT_SSH="C:\Program Files\PuTTY\plink.exe"` although you will have to readd your key to pageant every time you reboot.

**Comment by niik** [comment] 2024-09-18 08:47
Given that this issue was reported to occur outside of GitHub Desktop (in the terminal) as well and given that we currently don't do anything special to support ssh signing I'm going to say that this isn't an issue with GitHub Desktop and close this issue. I'm happy that you have found and shared workarounds for the problem and should we choose to add specific ssh signing support we'll be sure to come back here to pick up the shared context.

**Closed as completed by niik** 2024-09-18 08:47 UTC
Labels: bug, priority-3
