### ISSUE TITLE
Can no longer copy the commit ID in Desktop Beta

### ISSUE THREAD

**Issue by danhollick** [desktop/desktop#1874] opened 2017-06-02 11:38 UTC
### Description

Just updated Github Desktop and I can no longer copy the commit ID seen here:
![screen shot 2017-06-02 at 1 34 08 pm](https://cloud.githubusercontent.com/assets/13898607/26724158/3dbcee58-4798-11e7-8350-82410f35b2c3.png)
Not a huge issue, but seems like a step backwards.

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Select a commit in the History Tab of a repo
1. Try to highlight the commit ID

**Comment by shiftkey** [comment] 2017-06-02 11:48
Duplicate of #1501 and we're talking about how to address this in #1778

**Closed by shiftkey** 2017-06-02 11:48 UTC
