### ISSUE TITLE
installer doesn't complete, missing `screen` module

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#1875] opened 2017-06-02 12:47 UTC
### Description

Installer doesn't complete successfully, appears to get stuck in a loop

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Windows 10 x64 (Version 1703, OS Build 15063.332), ie Creators Update GA.

### Steps to Reproduce

1. Install GitHub Desktop

**Expected behaviour:** Installer completes and launches application

**Actual behaviour:** From @jstangroome: "it just pegs the CPU as "GitHub Desktop.exe" starts, launches a copy of itself, then dies, and repeats ad infinitum"

**Reproduces how often:** repeatable, even after cleaning folders at `%LOCALAPPDATA%\GitHubDesktop` and `%APPDATA%\GitHub Desktop`

### Logs

https://gist.github.com/jstangroome/82f832dd66be0e77c9f6e338bff2bced

```
2017-06-02T01:27:11.603Z - error: Error: Cannot find module '../screen'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\jason\AppData\Local\GitHubDesktop\app-0.5.9\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as screen] (C:\Users\jason\AppData\Local\GitHubDesktop\app-0.5.9\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at o.exports (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\~\electron-window-state\index.js:19:1)
    at new T (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\app-window.ts:42:13)
    at S (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:294:18)
    at App.C.app.on (C:\Users\jason\AppData\Local\SquirrelTemp\webpack:\app\src\main-process\main.ts:163:3)
```

**Comment by chylex** [comment] 2017-06-02 13:17
Downloaded MSI installer after running into this issue, but that one doesn't seem to be doing anything at all, it just spins up my hard drive and then dies.

**Comment by pldmgg** [comment] 2017-06-04 15:39
I'm having the same issue. Same information as @shiftkey for WIndows 10 and also tried on Windows 2016 Server Eval Build 14292.rs1_release_sec.170427-1353 with same results.

**Comment by jstangroome** [comment] 2017-06-08 02:54
When Github Desktop is launched automatically by the GitHubDesktopSetup.exe it failed in this manner. However attempting to launch the app via the newly created icon on the Windows desktop succeeds without error.

**Comment by JmLallem** [comment] 2017-06-13 19:18
Same issue on Windows 7 x64

**Comment by lfuser** [comment] 2017-06-24 23:17
Same issue here. "GitHub Desktop.exe" and "Update.exe" processes keep popping up after running "GitHubDesktopSetup.exe", no UI or error shown at all. Windows 10 x64 1703.
I'm guessing it has to do with firewall blocking internet access to these executables by default (as intended for me).
This may be related to #1863.

**Comment by stevspa** [comment] 2017-06-29 16:15
I've spent about the past hour putting a forehead-shaped dent in the sheetrock over this same issue. I have a fresh install of Windows 10 1703, and each install attempt yielded multiple processes appearing and disappearing in Task Manager. I had no luck with either the regular installer or the system-wide installer; even after rebooting, the app would not launch. I've seen similar errors in the logs about the screen module, and many, many attempts to process pins, as well as the perpetually recurring desktop icon.

And then I disabled McAfee on-access scanner and access protection.

Having rebooted, disabled McAfee, and cleaned previous installation attempts from the disk, GitHub Desktop installed like a champ and launched without issues the first time. And the second time. I reenabled McAfee and Desktop still launches normally.

**Comment by shiftkey** [comment] 2017-06-29 16:23
Thanks for the reports everyone!

We're pretty sure this will be fixed by #1925 which is under review at the moment - I'm probably paraphrasing @joshaber here but there were some launch arguments the installer passes to the app that we weren't handling correctly, resulting in a race condition which put us into this weird state of looping forever.

**Comment by chylex** [comment] 2017-06-29 16:37
I'm only running Microsoft Security Essentials with no realtime protection enabled. Firewall enabled but no popups iirc.

**Comment by niik** [comment] 2017-07-08 15:57
@revanmj Ran into this problem in #2204.

@revanmj It looks like we're getting ready to ship a fix for this problem, hopefully we should have a new version out in a few weeks which solves this.

**Closed** 2017-07-14 14:49 UTC
Labels: bug, Windows
