### ISSUE TITLE
githubdesktop in mac os is white page after startup

### ISSUE THREAD

**Issue by lide1202** [desktop/desktop#5610] opened 2018-09-12 03:24 UTC
mac os high seirra 10.13.6
git version 2.19.0
github desktop laster

githubdesktop in mac os is white page after startup

**Comment by lide1202** [comment] 2018-09-17 13:27
<img width="939" alt="1" src="https://user-images.githubusercontent.com/9875609/45625807-61acc580-bac0-11e8-9833-b804dbe9cacd.png">
error like this, please help me ,thanks.

**Comment by lide1202** [comment] 2018-09-17 13:35
![1](https://user-images.githubusercontent.com/9875609/45626219-85bcd680-bac1-11e8-9ca8-1bc13781b06e.jpg)

error like this, please help, thanks!

**Comment by shiftkey** [comment] 2018-09-17 14:10
@lide1202 please refer to my previous comment - are you using an external monitor connected via DisplayLink? Could you try unplugging that and launching Desktop to see if it works, as you might have the same known issue as #5387?

**Comment by shiftkey** [comment] 2018-09-24 13:42
I'm going to close this out because, without more information, I believe this is the same root cause as was identified in #5387.

**Closed by shiftkey** 2018-09-24 13:42 UTC
Labels: more-information-needed
