### ISSUE TITLE
Empty pop-up form is shown when a squash finish

### ISSUE THREAD

**Issue by jdbruxelles** [desktop/desktop#16731] opened 2023-05-20 05:36 UTC
### The problem

Since the last update, when I squash two commits and it succeeds, I get a form that I don't need because I have nothing to do with it at that time.

### Release version

3.2.3

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Make two unpushed commits
2. Go to the History sidebar
3. Complete the squash of the two commits
4. Squash complete? Here is the pop-up.

### Screenshots

![image](https://github.com/desktop/desktop/assets/18559798/facfe1b2-6964-4ef2-9c0f-98ed315cd8ca)

**Comment by sergiou87** [comment] 2023-05-22 07:39
Duplicate of https://github.com/desktop/desktop/issues/16605, fixed in https://github.com/desktop/desktop/pull/16632

Thanks for your report anyway!

**Closed as completed by sergiou87** 2023-05-22 07:39 UTC
