### ISSUE TITLE
Profile Pic/Avatar Broken on Enterprise

### ISSUE THREAD

**Issue by ambroselittle** [desktop/desktop#1569] opened 2017-05-17 17:31 UTC
### Description

Profile pic showing as broken.

### Version

**GitHub Desktop version:** 0.5.3
**OS version:** Windows 10.0.15063

### Steps to Reproduce

1. Sign into an Enterprise instance (with 2FA).

**Expected behaviour:** To see avatar (that shows on the Web site).

**Actual behaviour:** Shows broken image.

**Reproduces how often:** 100%, for all users in history, too.

### Logs
<img width="457" alt="no-profile-pic" src="https://cloud.githubusercontent.com/assets/2660021/26167408/abd22066-3b04-11e7-86d7-4a7eca1dd673.png">

[Archive.zip](https://github.com/desktop/desktop/files/1008583/Archive.zip)

**Comment by rossipedia** [comment] 2017-05-17 17:32
Duplicate of #821

**Comment by ambroselittle** [comment] 2017-05-17 17:34
Oops. My bad. I did search but did not match on the right terms.

**Closed** 2017-05-17 17:34 UTC
