### ISSUE TITLE
Not deleting previous / old version after update

### ISSUE THREAD

**Issue by FrzMtrsprt** [desktop/desktop#15192] opened 2022-08-29 12:38 UTC
### The problem

GitHub desktop does not delete the previous version, and the NuGet package cache after an update.
As a result, it is taking up nearly three times as much storage space.

### Release version

3.0.6

### Operating system

Windows 11 22H2 22621 & Windows 11 Dev 25188

### Steps to reproduce the behavior

1. Install GitHub Desktop 3.0.5
2. Click `Restart GitHub Desktop` in the update prompt
3. After GitHub Desktop 3.0.6 restarts, check the install directory

### Log files

[2022-08-29.desktop.production.log](https://github.com/desktop/desktop/files/9444478/2022-08-29.desktop.production.log)

### Screenshots

![image](https://user-images.githubusercontent.com/15852717/187202103-d798644b-11f6-41b1-99af-143594e4aee0.png)

**Comment by steveward** [comment] 2022-08-29 20:43
Thanks for the issue @FrzMtrsprt. The current behavior for the Squirrel installer GitHub Desktop uses is that two versions of the app stick around (see https://github.com/Squirrel/Squirrel.Windows/issues/589#issuecomment-180075676), and it looks like that is the case here. 

However, we are looking into an issue where failed updates cause a large accumulation of leftover files, and you can see some discussion about that [here](https://github.com/Squirrel/Squirrel.Windows/issues/1195#issuecomment-1216633178). 

I'm going to close this out since what you are seeing is expected behavior with Squirrel.

**Closed as completed by steveward** 2022-08-29 20:43 UTC

**Comment by robertlzj** [comment] 2022-09-14 03:40
@steveward 
Hi, just some additional, by searching Github Desktop. Found there are **many** of them, some are old since last modify time at 2021.
Not sure which of them should be deleted manually.

> C:\Users\User\AppData\Local\SquirrelTemp\tempf\lib\net45\GitHubDesktop.exe
> C:\Users\User\AppData\Local\GitHubDesktop\app-3.0.7\GitHubDesktop.exe
> C:\Users\User\AppData\Local\GitHubDesktop\app-3.0.6\GitHubDesktop.exe
> C:\Users\User\AppData\Local\SquirrelTemp\tempd\lib\net45\GitHubDesktop.exe
> C:\Users\User\AppData\Local\SquirrelTemp\tempb\lib\net45\GitHubDesktop.exe
> C:\Users\User\AppData\Local\GitHubDesktop\GitHubDesktop.exe

And which now, I can't lunch GitHubDesktop from `C:\Users\User\AppData\Local\GitHubDesktop\`, but from `C:\Users\User\AppData\Local\SquirrelTemp\tempf\lib\net45\GitHubDesktop.exe`.
