### ISSUE TITLE
Unable to push or pull changes to/from a public github wiki

### ISSUE THREAD

**Issue by aubergine10** [desktop/desktop#6811] opened 2019-02-09 20:01 UTC
## Description

Note: This might be same or similar issue to #3839

After successfully cloning a public github wiki to desktop, any subsequent attempts to pull or push changes fails.

Wiki home page: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki
Wiki clone URL: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition.wiki.git

## Version

* GitHub Desktop: 1.7.1
* Operating system: Windows 10 v.1809 b.17763.292

## Steps to Reproduce

Note: I have contributor privs on the public repository the wiki is associated with.

* Clone a public github wiki to desktop using the clone URL shown on the wiki home page
* Make changes online, try to pull them local = doesn't work
* Make changes locally, try to push them online = doesn't work

### Expected Behavior

Should pull and push in same way as repos.

### Actual Behavior

After cloning, any attempt to push or pull changes fails.

## Additional Information

```
withPushPull @ app-store.ts:2615
withPushPull @ app-store.ts:2591
performPull @ app-store.ts:2610
withAuthenticatingUser @ app-store.ts:2603
withAuthenticatingUser @ app-store.ts:3622
async function (async)
_pull @ app-store.ts:2599
pull @ dispatcher.ts:325
pull @ app.tsx:703
onMenuEvent @ app.tsx:291
i.ipcRenderer.on @ app.tsx:206
emitTwo @ events.js:126
emit @ events.js:214
http.ts:135 GET https://api.github.com/repos/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition.wiki 404 (Not Found)
t.request @ http.ts:135
request @ api.ts:504
fetchRepository @ api.ts:261
repositoryWithRefreshedGitHubRepository @ app-store.ts:2283
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:2229
withAuthenticatingUser @ app-store.ts:3596
_pull @ app-store.ts:2600
pull @ dispatcher.ts:325
pull @ app.tsx:703
onMenuEvent @ app.tsx:291
i.ipcRenderer.on @ app.tsx:206
emitTwo @ events.js:126
emit @ events.js:214
install.ts:27 fetchRepository: 'krzychu124/Cities-Skylines-Traffic-Manager-President-Edition.wiki' returned a 404
warn @ install.ts:27
fetchRepository @ api.ts:263
async function (async)
fetchRepository @ api.ts:258
repositoryWithRefreshedGitHubRepository @ app-store.ts:2283
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:2229
withAuthenticatingUser @ app-store.ts:3596
_pull @ app-store.ts:2600
pull @ dispatcher.ts:325
pull @ app.tsx:703
onMenuEvent @ app.tsx:291
i.ipcRenderer.on @ app.tsx:206
emitTwo @ events.js:126
emit @ events.js:214
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: Cities-Skylines-Traffic-Manager-President-Edition.wiki - aubergine10 (has token)
app-store.ts:2615 Uncaught (in promise) Error: The repository has no remotes.
    at withPushPull (app-store.ts:2615)
    at Ce.withPushPull (app-store.ts:2591)
    at Ce.performPull (app-store.ts:2610)
    at withAuthenticatingUser (app-store.ts:2603)
    at Ce.withAuthenticatingUser (app-store.ts:3622)
    at <anonymous>
withPushPull @ app-store.ts:2615
withPushPull @ app-store.ts:2591
performPull @ app-store.ts:2610
withAuthenticatingUser @ app-store.ts:2603
withAuthenticatingUser @ app-store.ts:3622
async function (async)
_pull @ app-store.ts:2599
pull @ dispatcher.ts:325
pull @ app.tsx:703
onMenuEvent @ app.tsx:291
i.ipcRenderer.on @ app.tsx:206
emitTwo @ events.js:126
emit @ events.js:214
install.ts:27 fetchRepository: 'krzychu124/Cities-Skylines-Traffic-Manager-President-Edition.wiki' returned a 404
warn @ install.ts:27
fetchRepository @ api.ts:263
async function (async)
fetchRepository @ api.ts:258
repositoryWithRefreshedGitHubRepository @ app-store.ts:2283
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:2229
withAuthenticatingUser @ app-store.ts:3596
refreshIndicatorForRepository @ app-store.ts:2006
async function (async)
refreshIndicatorForRepository @ app-store.ts:1978
refreshIndicatorsForRepositories @ app-store.ts:1965
refreshAllIndicators @ app-store.ts:1953
window.setTimeout @ app.tsx:187
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: Cities-Skylines-Traffic-Manager-President-Edition.wiki - aubergine10 (has token)
http.ts:135 GET https://api.github.com/repos/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition.wiki 404 (Not Found)
t.request @ http.ts:135
request @ api.ts:504
fetchRepository @ api.ts:261
repositoryWithRefreshedGitHubRepository @ app-store.ts:2283
async function (async)
repositoryWithRefreshedGitHubRepository @ app-store.ts:2229
withAuthenticatingUser @ app-store.ts:3596
refreshIndicatorForRepository @ app-store.ts:2006
async function (async)
refreshIndicatorForRepository @ app-store.ts:1978
refreshIndicatorsForRepositories @ app-store.ts:1965
refreshAllIndicators @ app-store.ts:1953
window.setTimeout @ app.tsx:187
install.ts:31 Background fetch for 2 repositories took 1.208sec
```

### Logs

[2019-02-09.desktop.production.log](https://github.com/desktop/desktop/files/2848205/2019-02-09.desktop.production.log)

**Comment by steveward** [comment] 2019-02-11 14:56
Thanks for the detailed report @aubergine10! This does look like a duplicate of https://github.com/desktop/desktop/issues/3839, so I'm going to close this issue out in favor of that one. Please follow along in #3839 for updates about this.

**Closed by steveward** 2019-02-11 14:56 UTC
