### ISSUE TITLE
Text selection – no support for macOS text drag and drop

### ISSUE THREAD

**Issue by NiklasBr** [desktop/desktop#4896] opened 2018-06-08 07:28 UTC
## Description
The general drag and drop as expected does not work. Normally one should be able to grab selected text and then drag it somewhere to be dropped. This is a minor issue, but one of the kind which when they happen will stop you right in the track and go "oh, one more of these things… Sigh".

## Version
* GitHub Desktop: 1.2.3
* Operating system: macOS 10.12.6 (16G1408)

## Steps to Reproduce
1. Select source text/code in the diff view.
2. Try to use drag it to the Finder, or any text editor, or code editor.

### Expected Behavior
I expect to be able to drag the text selection to a target of my choice.

Example of expected behaviour:
![2018-06-08 09 18 06](https://user-images.githubusercontent.com/279826/41144523-7c258ee6-6afd-11e8-98be-1a0d5accff33.gif)
### Actual Behavior
The selection blurs and disappears.

## Additional Information
This also works in Chrome 67 in case you were wondering.

**Comment by niik** [comment] 2018-06-08 07:59
Hey @NiklasBr, thanks for opening this.

To clarify, this only affects the diffs, text selection from other areas of the app where we allow it seem to work as intended.

![drag-and-drop](https://user-images.githubusercontent.com/634063/41145495-87bb7ce0-6b00-11e8-8be4-f2f5ff10b872.gif)

Looking at https://codemirror.net/demo/markselection.html I'm able to drag text so I'm wondering if we're doing something special with regards to how we use CodeMirror here.

I think we'd welcome some help with troubleshooting why this is happening so I'm gonna mark this as help-wanted.

**Comment by billygriffin** [comment] 2019-11-20 21:42
Thanks @NiklasBr for the issue. Since this isn't something we've seen others struggling with, nobody has picked it up, and it's only an issue in diffs as @niik pointed out, I'm going to close this. We're definitely always open to reopening if it's a problem that others are experiencing. Thanks again!

**Closed by billygriffin** 2019-11-20 21:42 UTC
Labels: codemirror, enhancement, help wanted
