### ISSUE TITLE
a commit disappears from change history of a branch

### ISSUE THREAD

**Issue by vincent3569** [desktop/desktop#3704] opened 2017-12-30 23:16 UTC
### Description
I have a repositoty (https://github.com/vincent3569/zenphoto-perso) that is a fork from another repo (https://github.com/zenphoto/zenphoto)

In my repo, I have 2 branchs (master and perso).
in perso branch, I added a personnal dev
in master branch, I updated some translations and I made a pull request to the initial repo.

after that
I merge master branch into perso branch (so I have all commits of my new feature + my translations update)

after the pull request has been merged into upstream/master, 
I want to keep my fork sync with upstream (although it seems to be useless since my repo is up to date because I am at the initiative of the changes).

on my_repo/master I made a "merge into current branch" from upstream/master.
and on my_repo/perso I made a "merge into current branch" from master.

**after that, my personnal commit on my_repo/perso desapears from changes history of this branch.
I still see it on github.**

### Version

**GitHub Desktop version:** [github desktop 1.0.12-beta0]

**OS version:** [Microsoft Windows 10.0.16299.125]

### Steps to Reproduce
See above

### Logs
[2017-07-31.desktop.production.log](https://github.com/desktop/desktop/files/1594853/2017-07-31.desktop.production.log)

#### Additional Information
screenshots of github desktop

![zenphoto -- master](https://user-images.githubusercontent.com/1224809/34457878-4f6a118a-edbf-11e7-9851-3d0b7f3818cf.PNG)
![zenphoto-perso -- master](https://user-images.githubusercontent.com/1224809/34457879-4f85dcd0-edbf-11e7-8c28-c93d536aa7ac.PNG)
![zenphoto-perso -- perso](https://user-images.githubusercontent.com/1224809/34457880-4fa130a2-edbf-11e7-8462-d57231cff64a.PNG)
![zenphoto-perso -- perso on github](https://user-images.githubusercontent.com/1224809/34457897-cb9da4e2-edbf-11e7-8681-e78081e1b84f.PNG)
![zenphoto-perso -- master on github](https://user-images.githubusercontent.com/1224809/34457898-cbb5ed2c-edbf-11e7-8639-0536c4cf86e6.PNG)

**Comment by vincent3569** [comment] 2017-12-31 08:34
if it may usefull, I saw another log file 
[2017-12-30.desktop.beta.log](https://github.com/desktop/desktop/files/1595064/2017-12-30.desktop.beta.log)

and other fact:
on github, if I rename my fork (ie https://github.com/vincent3569/zenphoto-dev)
when I go to github desktop, after fetch/syn, I can see the commit
and if I use the 1rst name again (https://github.com/vincent3569/zenphoto-perso), I loose it again

the screenshots
![capture1](https://user-images.githubusercontent.com/1224809/34460420-b552c53e-ee0d-11e7-9a41-a2869c4b2d3f.PNG)
![capture2](https://user-images.githubusercontent.com/1224809/34460421-b56a36e2-ee0d-11e7-932a-f612be9ff672.PNG)

and my today's logs
[2017-12-31.desktop.beta.log](https://github.com/desktop/desktop/files/1595069/2017-12-31.desktop.beta.log)
[2017-07-31.desktop.production.log](https://github.com/desktop/desktop/files/1595070/2017-07-31.desktop.production.log)

**Comment by vincent3569** [comment] 2018-01-10 15:08
not clear for me:
you need me to reproduce the issue? or you have to reproduce it yourself?

**Comment by iAmWillShepherd** [comment] 2018-01-10 18:26
@vincent3569 that label is for us, so we don't need anything more from you at the moment. But, keep an eye on this issue in case we do need more info.

**Comment by shiftkey** [comment] 2018-01-10 18:52
@vincent3569 what @iAmWillShepherd said. I think all the details are there, it's just the steps through are tricky to understand.

One additional thing you could do for me is to run this command inside each repository that you're troubleshooting:

```
$ git log --graph --oneline
```

This will show a better visual representation of the repository, to help me understand the commit that you're missing.

For example, I ran this on `master` in `vincent3569/zenphoto-perso`:

```
~/src/test/zenphoto-perso/ git log --graph --oneline | more
*   ad806e28 Merge pull request #1121 from vincent3569/master
|\
| * 407b490a update french translations
|/
* 316514f2 Show note in admintoolbox if site status is "closed for testing" fix #1120
* 26e04786 Small text addition to last pull request/commit as manual pagebreak is not exactly tinyMCE dependent.
*   664c4fac Merge pull request #1119 from vincent3569/master
|\
| * 76b435ed more for https://github.com/zenphoto/zenphoto/issues/1116
|/
* a4cdd5d0 Revert: Again use htmlawed as fallback only if native php tidy extension is not available #1116
* 928c6812 Fix undeclared global js variables required by admin toolbox for delete links. First part of #1118
*   fc8c810a Merge pull request #1117 from vincent3569/master
|\
| * 631d3f5f fix rel attribute on <a> tag
|/
* f11faf98 Use htmlawed for "reparing" broken html only
* a90066fc Finally add accidentally forgotten file…
...
```

And I ran this on the `perso` branch on `vincent3569/zenphoto-perso`:

```
~/src/test/zenphoto-perso/ git log --graph --oneline | more
*   b9455336 Merge branch 'master' into perso
|\
| *   ad806e28 Merge pull request #1121 from vincent3569/master
| |\
* | \   b2d89737 Merge branch 'master' into perso
|\ \ \
| | |/
| |/|
| * | 407b490a update french translations
| |/
* | e580c96d new feature
|/
* 316514f2 Show note in admintoolbox if site status is "closed for testing" fix #1120
* 26e04786 Small text addition to last pull request/commit as manual pagebreak is not exactly tinyMCE dependent.
*   664c4fac Merge pull request #1119 from vincent3569/master
|\
| * 76b435ed more for https://github.com/zenphoto/zenphoto/issues/1116
|/
* a4cdd5d0 Revert: Again use htmlawed as fallback only if native php tidy extension is not available #1116
* 928c6812 Fix undeclared global js variables required by admin toolbox for delete links. First part of #1118
*   fc8c810a Merge pull request #1117 from vincent3569/master
|\
| * 631d3f5f fix rel attribute on <a> tag
|/
```

It's the `new feature` commit that you're not seeing sometimes in the repository, correct?

```
~/src/test/zenphoto-perso/ git show e580c96d | more
commit e580c96d4939aa6b3796d3897da699c260e4d20e
Author: vincent3569 <vincent_bourganel@yahoo.fr>
Date:   Sat Dec 30 22:43:47 2017 +0100

    new feature

    navigate between single news within category
    https://github.com/zenphoto/zenphoto/issues/1087

diff --git a/zp-core/zp-extensions/zenpage.php b/zp-core/zp-extensions/zenpage.php
index 94b3bfd6..0c513076 100644
...
```

If that's the case, we can then look into how Desktop is getting that data and see why it's not showing that commit. I don't think renaming of the repository is the issue here, but I'll keep that in mind.

**Comment by vincent3569** [comment] 2018-01-10 20:41
yes this is this `e580c96d` commit that disappears.

I ran your commande on my folder:

```
D:\Famille\Documents\_Vincent\Site Internet\Galerie photo\GitHub\zenphoto-perso>git log --graph --oneline
*   ad806e28 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1121 from vincent3569/master
|\
| * 407b490a update french translations
|/
* 316514f2 Show note in admintoolbox if site status is "closed for testing" fix #1120
* 26e04786 Small text addition to last pull request/commit as manual pagebreak is not exactly tinyMCE dependent.
*   664c4fac Merge pull request #1119 from vincent3569/master
|\
| * 76b435ed more for https://github.com/zenphoto/zenphoto/issues/1116
|/
* a4cdd5d0 Revert: Again use htmlawed as fallback only if native php tidy extension is not available #1116
* 928c6812 Fix undeclared global js variables required by admin toolbox for delete links. First part of #1118
*   fc8c810a Merge pull request #1117 from vincent3569/master
|\
| * 631d3f5f fix rel attribute on <a> tag
|/
* f11faf98 Use htmlawed for "reparing" broken html only
```

I have something else new:
I am now with GitHub Desktop version: [github desktop 1.0.12-beta1]

When I go to perso branch for the 1st time, I can see the commit.
If I switch to master branch  and return to perso branch , the commit disappears

the screenshots:

![capture1](https://user-images.githubusercontent.com/1224809/34794451-f9da640c-f64e-11e7-9a30-6ee23e9adc63.PNG)
![capture2](https://user-images.githubusercontent.com/1224809/34794452-f9f74324-f64e-11e7-8245-f73114c78e52.PNG)

**Comment by ttsanton** [comment] 2018-01-29 15:46
Hello,

I believe this issue is happening to me as well. I'm running GitHub Desktop ver. 1.0.12 on Mac OS High Sierra 10.13.2

I committed some changes on a dev branch I created. A few days later, I merged changes from the master onto my dev branch. However, the changes I made before don't show up anymore on the History tab of GitHub Desktop, but I can view the changes on GitHub.com and within my IDE when I switch between the master and dev branch using GitHub Desktop.

Screenshots below.

**GitHub Desktop not showing the Jan 23 and Jan 25 commits:**
![screen shot 2018-01-29 at 10 39 33 am](https://user-images.githubusercontent.com/7467196/35518884-c8c75f6e-04e0-11e8-95f7-0cca18ef6fcb.png)

**GitHub.com showing the Jan 23 and Jan 25 commits:**
![screen shot 2018-01-29 at 10 41 20 am](https://user-images.githubusercontent.com/7467196/35518975-fd6c2862-04e0-11e8-8dd5-a7aa43e54b26.png)

**Comment by shiftkey** [comment] 2018-02-02 01:41
@vincent3569 @ttsanton I've been able to reproduce this using the `zenphoto-perso` fork, and switching between `master` and `perso`.

 - The first time you view the `perso` branch, the problem commit `e580c96d` is in the history
 - Then, you switch to `master` and the commit is gone (this is expected)
 - Switching back to `person`, it appears to be rendering the history but it omits the `e580c96d` commit

I think this is related to how we're rendering the history, rather than the name of the repository. I need to throw more tracing around this to understand how it's broken.

**Comment by tablatronix** [comment] 2018-04-04 15:37
same issue here missing all commits around a specific date and from a merged deleted branch, not sure which broke it, I did some cherry picking and a merge, looking at graphs now to see what the deal is.

**Comment by bryanmyers** [comment] 2021-01-28 17:08
Me too. GitHub Desktop version 2.6.2 MacOS 10.14.6  github webpage vs desktop.  Merge branch 361... doesn't show up.  which is a shame since I need to undo that commit.

**github website:**
![Screen Shot 2021-01-28 at 9 04 34 AM](https://user-images.githubusercontent.com/4756253/106172831-1c950580-6148-11eb-9fcc-358f5133ef96.png)

**github desktop:**
<img width="479" alt="Screen Shot 2021-01-28 at 9 04 46 AM" src="https://user-images.githubusercontent.com/4756253/106172864-2454aa00-6148-11eb-9b35-12630c87a514.png">

**Closed** 2021-07-19 08:29 UTC
Labels: bug, priority-3
