### ISSUE TITLE
Summary of commit message remains in text field after committing

### ISSUE THREAD

**Issue by billygriffin** [desktop/desktop#5262] opened 2018-07-26 20:01 UTC
## Description

When I type a commit message and commit, the summary of my commit message sticks around after I commit.

## Version

* GitHub Desktop: Latest beta

* Operating system: Mac OSX High Sierra

## Steps to Reproduce

1. Files selected to commit
2. Type commit message
3. Click commit to [branch]

![2018-07-26 11 44 35](https://user-images.githubusercontent.com/1715082/43285568-f013bfdc-90e4-11e8-863a-bd062337f9be.gif)

### Expected Behavior
The commit happens and the text fields for the commit message are cleared

### Actual Behavior
The commit happens and the summary text field remains with the text that was in it before I clicked commit

**Comment by shiftkey** [comment] 2018-07-26 20:03
@billygriffin thanks for the report. I've got a fix for this under review in #5260 and once that's merged I can publish another beta to ensure this is resolved.

**Comment by billygriffin** [comment] 2018-07-26 21:43
LGTM! Thanks!

**Comment by shiftkey** [comment] 2018-07-27 13:03
Reopening this to investigate because I have a report of this not being resolved with `1.3.0-beta6`.

**Comment by billygriffin** [comment] 2018-07-27 21:59
Strange. Tested this on several machines and all cleared the summary out of the input field as expected.

**Comment by shiftkey** [comment] 2018-07-28 14:53
I reverted this to the `1.2.6` behaviour in #5269 so this issue should be resolved, but the original issue about switching tabs/apps remains and needs better investigating.

**Closed by shiftkey** 2018-07-28 14:53 UTC
Labels: bug

**Comment by LynanBreeze** [comment] 2018-12-24 03:48
still suffering this in 1.5.1 (Windows)

**Comment by shiftkey** [comment] 2018-12-24 13:18
@LynanBreeze are you seeing the behaviour reported in #4046? As I understand it, the steps to reproduce it are outlined here https://github.com/desktop/desktop/issues/4046#issuecomment-406566833

If you're seeing a different behaviour, please open a new issue and provide details so we can investigate further.
