### ISSUE TITLE
Profile pic won't load, messes up the UI

### ISSUE THREAD

**Issue by rusty595** [desktop/desktop#6041] opened 2018-10-30 17:28 UTC
## Description
My profile image has stopped loading, causing it to write the alt text rather than display an empty box. My image does not display in any other view, just a blank space. I have tried signing out and back in to no avail.

![image](https://user-images.githubusercontent.com/10696825/47736939-ac952d80-dc67-11e8-9be5-d631b2316fa2.png)

## Version
* GitHub Desktop: 1.4.3
* Operating system: Microsoft Windows [Version 10.0.17134.345]

## Steps to Reproduce
My profile picture hasn't loaded since I rebooted my PC, to reproduce this specific issue you could probably disconnect while it's trying to cache the image.

### Expected Behavior
I expect my profile picture to be displayed.
If my profile picture cannot be displayed, I expect a small empty profile-picture sized box.

### Actual Behavior
![image](https://user-images.githubusercontent.com/10696825/47736939-ac952d80-dc67-11e8-9be5-d631b2316fa2.png)

## Additional Information
I do not have a Github Enterprise account, so this is not a duplicate of those bugs.

### Logs
[2018-10-30.desktop.production.log](https://github.com/desktop/desktop/files/2530792/2018-10-30.desktop.production.log)

**Comment by tierninho** [comment] 2018-10-30 17:42
@rusty595 Thanks for filing, but this is a duplicate of another open issue: https://github.com/desktop/desktop/issues/5671 

Please follow along there.

**Closed by tierninho** 2018-10-30 17:42 UTC
