### ISSUE TITLE
Scrolling glitch on merge resolution window

### ISSUE THREAD

**Issue by danpalmer** [desktop/desktop#12189] opened 2021-05-10 14:26 UTC
### Describe the bug

When clicking the on a merge conflict to select a resolution option, the list scrolls instead of the dropdown menu opening. See attached video.

I suspect this could be an invisible scrollbar that is overlaid on top of the content which is intercepting click events, but I'm not sure.

### Version & OS

Version 2.8.1
macOS 11.2.3

### Steps to reproduce the behavior

1. Merge a branch that has conflicts (I suspect >>5 conflicts is necessary to trigger the bug)
2. Try selecting the dropdown menu on each conflict to select a resolution option.
3. Sometimes the list will scroll instead, not always, but frequently.

### Expected behavior

Clicking the dropdown should always open the dropdown.

Optionally, if the view is scrollable, having a visible scrollbar would be nice - it can be difficult to know where you are on the list otherwise.

### Actual behavior

When clicking the on a merge conflict to select a resolution option, the list scrolls instead of the dropdown menu opening. 

### Screenshots

https://user-images.githubusercontent.com/202400/117674806-e84bcf00-b1a3-11eb-9599-416378d08f03.mov

### Logs

I don't believe logs are necessary for this one as I think it's just a UI glitch, but do let me know if they're going to help.

**Comment by steveward** [comment] 2021-05-10 20:29
Thanks for the report @danpalmer! This looks like a duplicate of https://github.com/desktop/desktop/issues/6199, so I'll reference this issue to bump that one up.

**Closed as completed by steveward** 2021-05-10 20:29 UTC
