### ISSUE TITLE
Changed file list refreshes multiple times

### ISSUE THREAD

**Issue by jevin** [desktop/desktop#14364] opened 2022-04-14 10:50 UTC
### The problem

The "Changed files" list refreshes multiple times. It looks like it's showing previously uncommitted changes. It happens very fast, please have a look at the video attached (around 11s).

### Release version

Version 2.9.14 (x64)

### Operating system

Mac OS Monterey (12.2)

### Steps to reproduce the behavior

1. Switch to editor
2. Modify file(s)
3. Switch to Github Desktop
4. Changed file list and diff refreshes multiple times (sometimes briefly showing the previously uncommitted diff)

### Screenshots

https://user-images.githubusercontent.com/1003859/163376519-3acbd869-27bc-421a-8845-936aee93d1ad.mov

**Comment by steveward** [comment] 2022-04-14 17:23
Thanks for reporting this @jevin. The video is helpful! Are you able to reproduce this in multiple repositories? I tested things out for a bit and was unable to reproduce this directly.

**Comment by jevin** [comment] 2022-04-14 17:29
Thanks! Yeah I briefly tested another repo and it does not seem to happen there. 

Is there anything I can run on my repo to fix this?

**Comment by antialiasis** [comment] 2022-04-20 16:19
I have also been having this problem with GitHub Desktop recently - strange, inopportune extra UI refreshes while I'm working in the GitHub Desktop window. I think it's a regression in some relatively recent version, as I noticed it only started happening quite recently (within the last month, maybe two at the most).

**Comment by steveward** [comment] 2022-04-21 18:38
@antialiasis thanks for sharing that you've seen this to -- are you also using macOS?

**Comment by antialiasis** [comment] 2022-04-21 20:50
Yes, on a MacBook Pro laptop.

**Comment by jevin** [comment] 2022-04-22 05:34
I've had a few changes on my repo recently, maybe @antialiasis has done similar things and that could help find the issue.
- I've renamed the master branch to main
- I've had an alert asking me to sign up (or telling me that I'm logged out), but I was signed up properly in the settings

Is there a way to clear user related cache? I could log out, clear that cache and see if that solves anything.

**Comment by antialiasis** [comment] 2022-04-22 10:40
We haven't renamed the master branch, although we did switch the default to be the development branch instead of master (I could swear that's more recent than the problem, though...?) No alert to sign up here, as far as I can recall.

On the other hand, quickly checking another repo (on which the default branch is still master), I'm not _at a glance_ seeing the same behaviour there, so maybe it does have something to do with that...?

**Comment by antialiasis** [comment] 2022-04-22 11:32
Adding a bit more information: in the affected repo, I've checked out a branch that's neither the old default (master) nor the new default (development). Right now, I've got a single changed file which I've unchecked in the changes list. Reliably, if I wait a few minutes with another window (such as the Chrome window where I'm typing this) selected, and then switch back to the GitHub Desktop window, a strange double UI refresh occurs where the file becomes momentarily checked before it refreshes again and is unchecked. Similar jarring refreshes where the view momentarily switches to a different file, etc. have occurred while I'm e.g. typing a commit message.

**Comment by jevin** [comment] 2022-04-22 11:37
It looks like we're having exactly the same issue. It must be due to the branch renaming. I logged off right after I left my comment and I haven't had the jarring refreshes yet.

Can you try that @antialiasis ?

**Comment by antialiasis** [comment] 2022-04-22 12:23
I logged out of GitHub Desktop and back in and still seem to be having the same problem in the same repo...

**Comment by jevin** [comment] 2022-04-22 12:25
Oh I’m actually still logged out and still haven’t had the issue.

**Comment by antialiasis** [comment] 2022-04-22 12:43
Little more information: the UI refresh (which can happen while I'm typing a commit message) also momentarily clears out the commit message as well as removing focus from the message field. While the commit message I was typing is restored on the second refresh, focus is not restored to the field afterward. Very disruptive.

Can also confirm that if I stay logged out, I'm not seeing it happen. Once I've logged in again, I see the problem again.

**Comment by antialiasis** [comment] 2022-04-29 09:32
@steveward Is this bug being looked into, or are there any more details I could provide that could help? It's majorly disruptive of my use of the program.

**Comment by steveward** [comment] 2022-05-02 19:25
@antialiasis @jevin you could try clearing out the locally cached data to see if the app restores back to a state where this doesn't happen. You'll need to log in/add your repositories back again after doing this.

1. Close GitHub Desktop
2. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
3. Restart GitHub Desktop

Let me know if that makes a difference.

**Comment by antialiasis** [comment] 2022-05-03 09:52
I've done so and it seems to have fixed the issue.

**Comment by antialiasis** [comment] 2022-05-04 16:41
As it happens I'm now working on a previously unaffected repo that has just had its default branch changed (after I cleared out the cache), and it's now exhibiting the issue. So I think it must be related to that. (GitHub Desktop still seems to think master is the default branch, if I look at the branch menu.)

EDIT: The problem looks fixed again after I delete just the "Cache" folder under ~/Library/Application Support/GitHub Desktop/ - shows the correct default branch and does not do the weird refreshes. Helps for anyone else experiencing this problem - no need to re-add all your repos this way.

**Comment by thinkyhead** [comment] 2022-05-17 20:30
I've just started to see this issue after the macOS 12.4 update. It reminds me of an issue I've seen in my own Electron app work using IPC. I found that my "file watcher" received more than one IPC message, so I just dealt with it by ignoring any IPC messages that arrive too soon after the previous one. But maybe this is not at all related to IPC and file watching.

**Comment by steveward** [comment] 2022-10-12 18:15
Closing this out since it looks like this is no longer an issue. We can reopen and investigate if this is still persisting.

**Closed as completed by steveward** 2022-10-12 18:15 UTC
Labels: investigation-needed
