### ISSUE TITLE
GitHub Desktop for Mac keeps asking me for root access to install "helper"

### ISSUE THREAD

**Issue by iBobik** [desktop/desktop#4890] opened 2018-06-07 21:40 UTC
## Description

When update is available is triggers OS dialog osking for a root permission. Even of not using app, event if Keynote presentation is live.

![snimek obrazovky 2018-06-07 v 23 14 12](https://user-images.githubusercontent.com/614232/41127466-5171ffb0-6aab-11e8-9832-2eb6b3e561cc.PNG)

For many people it is anoying, but @joshaber closed issue #3616 as a "working as intended". But is it intended to be anoying? If not the issue should be clarified as an UX bug and keep open untill solved. People tried to protest in that closed issue, but no reaction from GitHub staff, so I created this new issue.

## Version

* GitHub Desktop: 1.2.2

* Operating system: macOS High Sierra 10.13.4 (17E202)

## Steps to Reproduce

1. Keep app open and wait until it will find a new version.

### Expected Behavior

Update will be installed without root access. Or at least asks for a permission when user started update process (no dialog when not using an app) and better describe why it needs root.

### Actual Behavior

Asking for a root when user not using GitHub Desktop, even when it could be anoying.

### Logs

Nothing relevant in logs

**Comment by iBobik** [comment] 2018-06-25 14:49
Now it offered me update from 1.2.3 to 1.2.4, again the dialog **appeared when not using GitHub**.

**Comment by iAmWillShepherd** [comment] 2018-06-25 15:02
Thanks for taking the time to open an issue! 🙇 

I have a few additional questions:
1. Where is Desktop being installed on your system? 
1. Does your system have multiple user accounts?
1. Are you the admin of the account Desktop is installed under?

It seems like the issue you are experiencing is due to your user account or directory not having proper permissions, forcing macOS to verify your identity before moving forward.

**Comment by iBobik** [comment] 2018-06-25 15:23
1. /Applications
2. Only Guest
3. Yes

**Comment by iAmWillShepherd** [comment] 2018-06-25 15:53
I'm currently unable to reproduce this issue, but there is one thing I want some clarification on: 
> no dialog when not using an app

@iBobik do you get this dialog even when Desktop is not open and running?

**Comment by justinjdickow** [comment] 2018-06-25 16:54
Original issue here: https://github.com/desktop/desktop/issues/3616

**Comment by iBobik** [comment] 2018-06-25 22:32
The dialog is shown only if Desktop is open, but even if in background.

Btw, this could be interesting: See the screenshot in first post - in about
dialog it is "Downloading" but it is stuck (nothing is downloading) until I
proceed access dialog.



Jan Pobořil

2018-06-25 18:54 GMT+02:00 Justin Dickow <notifications@github.com>:

**Comment by shiftkey** [comment] 2018-06-26 15:18
@iBobik I'm pretty sure that message is coming from inside [Squirrel.Mac](https://github.com/squirrel/squirrel.mac) - the update framework that comes with Electron: https://github.com/Squirrel/Squirrel.Mac/blob/203315f93e41086a2ab9d1ab2f5f8663878f145a/Squirrel/SQRLShipItLauncher.m#L92


```objc
NSString *prompt = NSLocalizedString(@"An update is ready to install.", @"SQRLShipItLauncher, launch shipit, authorization prompt");

NSString *iconName = [NSBundle.mainBundle objectForInfoDictionaryKey:@"CFBundleIconFile"];
NSString *iconPath = (iconName == nil ? nil : [NSBundle.mainBundle.resourceURL URLByAppendingPathComponent:iconName].path);
```

I need to dig into why that prompt is being shown for some users and not for others, hopefully that can clarify the intent here.

**Comment by shiftkey** [comment] 2018-06-26 15:24
@iBobik some extra clues here:

```objc
BOOL targetWritable = [self canWriteToURL:targetURL];
BOOL parentWritable = [self canWriteToURL:targetURL.URLByDeletingLastPathComponent];

return [SQRLShipItLauncher launchPrivileged:!targetWritable || !parentWritable];
```

This snippet is part of the updater, where it checks that either the target bundle and the parent directory are writeable by the current user - if not, it elevates. Does that make sense at all with how your `/Applications` directory is configured?

**Comment by shiftkey** [comment] 2018-06-26 16:08
@iBobik I've tracked similar issues for [Atom](https://github.com/atom/atom/issues/7058#issuecomment-283698557) and [VSCode](https://github.com/Microsoft/vscode/issues/7426#issuecomment-248083953) to the ownership of the installation.

As discussed over in #3616 the message is one that is dictated by macOS, and I suspect the updater is just smart enough here to detect that it needs elevation to apply the update here. So I'm not quite sure what else we can do here aside from confirm the permissions for the current `GitHub Desktop.app`.

**Comment by iBobik** [comment] 2018-06-27 11:30
Changed owner to username nad group to staff. Will see what will happen next update.



26. 6. 2018 v 18:08, Brendan Forster <notifications@github.com>:

**Comment by shiftkey** [comment] 2018-06-27 19:00
I'm going to close this out to keep our issue tracker under control, but please follow up with more details if the next update shows the same issue.

**Closed by shiftkey** 2018-06-27 19:00 UTC
Labels: macOS, more-information-needed

**Comment by iBobik** [comment] 2018-06-27 21:08
So for the record:
```
sudo chown -R my-admin-user:staff /Applications/*
```
It will fix it for all third party apps. System apps are protected, so it will do nothing with them.

**Comment by mapninja** [comment] 2019-06-07 15:52
Thank you @iBobik. You have improved my quality of life immensely, today.

**Comment by lukasc-ubc** [comment] 2020-05-16 21:41
Thank you @iBobik. That works, though it doesn't seem like a great solution to change the ownership of all Applications.
