### ISSUE TITLE
On the very first run after installing on Mac, you cannot clone a Git repository through any methods available.  You must QUIT the application and restart it, once, to clone a repo.

### ISSUE THREAD

**Issue by rwthompsonii** [desktop/desktop#5522] opened 2018-08-31 04:24 UTC
## Description

You get the error "cannot find path to local repository" or thereabouts.  I can't reproduce it after quitting the app or i'd screenshot it.

## Version

version 1.3.4

* GitHub Desktop:

* Operating system:
OS X El Capitan 10.11.6

## Steps to Reproduce

Install from zipped github desktop from website.  run app, drag to applications. 

### Expected Behavior

when I click "clone repo" it would clone the repo.

### Actual Behavior

when I click "clone repo" it errors with "cannot find path to local repo".  No matter which repo I picked.  Also, you can't click "choose" button for path, it does nothing when this happens.  You can still type the path, though.

### Logs

[2018-08-31.desktop.production.log](https://github.com/desktop/desktop/files/2338740/2018-08-31.desktop.production.log)

**Comment by iAmWillShepherd** [comment] 2018-08-31 15:55
Thanks for taking the time to open an issue! 🙇 

I am unable to reproduce this issue. I am curious why your reproduction steps includes a step to move the application to another directory while it's already running. I know in general you can do this in macOS without running into issues, but I have a feeling that move may have something to do with the issue you had. If this is no longer an issue, do you mind closing this out?

**Comment by rwthompsonii** [comment] 2018-08-31 15:58
Because the normal user flow that I'm familiar with is to move the
installed application to the Applications folder where all the others are.

That being said, if it's not reproducible I understand. Idk how to close it
though.

**Comment by iAmWillShepherd** [comment] 2018-08-31 16:19
@outofambit was able to reproduce this by doing the following steps:
1. Open Desktop
1. Move `Desktop.app` to another directory (while it's running)
1. Errors happen

> I am curious why your reproduction steps includes a step to move the application to another directory **while it's already running**.

Just wanted call out that bit ☝️  

I know the normal workflow is to move the application to the Applications directory. What caught my interest is that you moved the application to another directory while it was running. Doing that can lead to unexpected behavior, so I'd just avoid moving applications **while they are running**.

**Closed by iAmWillShepherd** 2018-08-31 16:19 UTC
Labels: reviewer-needs-to-reproduce

**Comment by rwthompsonii** [comment] 2018-08-31 16:35
Ah, that does make sense. However, wouldn't it just make more sense to
install it in the location everyone wants it to be in in the first place?

And to give an error that points at the actual problem, if possible?

**Comment by iAmWillShepherd** [comment] 2018-09-03 00:42
If you're on MacOS, we do not ship an installer, just the package itself. From there, you can move it to whatever directory you wish.
