### ISSUE TITLE
Stash feature request

### ISSUE THREAD

**Issue by kaster14** [desktop/desktop#3473] opened 2017-11-30 19:10 UTC
-The ability to "stash" changes when switching between branches so I don't have to make a relatively unneeded commit and don't need to discard changes

### Description

Feature request

**Comment by j-f1** [comment] 2017-11-30 19:12
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1633. Please follow that issue for further updates.

**Comment by iAmWillShepherd** [comment] 2017-11-30 19:21
Closing this issue because, as @j-f1 stated, this is a duplicate of #1633. If there are any additional details you would like to share, please do so in that issue.

**Closed by iAmWillShepherd** 2017-11-30 19:21 UTC

**Comment by kaster14** [comment] 2017-11-30 19:48
Thanks, I did search through the current open issues before creating this one but I guess I didn't look hard enough... Thanks again

**Comment by fallanic** [comment] 2017-11-30 23:10
#1633 is closed right now, and I don't see stashing in the roadmap https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md

Is it currently being considered?

**Comment by shiftkey** [comment] 2017-11-30 23:38
@fallanic we'll revisit and update the roadmap as part of our team gathering in January. The later milestones are more fuzzy because we didn't think it was worth getting too detailed too early.
