### ISSUE TITLE
Application does not respect custom gitconfig and gitignore files

### ISSUE THREAD

**Issue by stefanbauer** [desktop/desktop#3614] opened 2017-12-15 11:57 UTC
### Description

The desktop client does not respect a custom gitconfig and/or gitignore. With that in mind, this application is not usable, because you see permanently files that are ignored globally.

The application should therefore respect different locations for gitignore and gitconfig. Globalwide, systemwide and repositorywide.

If there is already a gitconfig/gitignore in that paths, the application should use it. In my case for instance `/usr/local/etc/gitconfig`. The application ignores that and creates an own file in `~/.gitconfig`. That should not be the case.

The same is true for `/usr/local/etc/gitignore`. This file gets totally ignored in the application.

### Version

**GitHub Desktop version:** 1.0.11 on macOS
**OS version:** macOS

**Comment by joshaber** [comment] 2017-12-15 17:13
>The desktop client does not respect a custom gitconfig and/or gitignore. With that in mind, this application is not usable, because you see permanently files that are ignored globally.

Hmm, that sounds like a bug. Does git on the command line behave the same way?

I have a `core.excludesfile` configured and it does seem to be respected.

>The application ignores that and creates an own file in ~/.gitconfig

That is true. If you configure the git user and email from the app we will save it to the global git config.

**Comment by stefanbauer** [comment] 2017-12-16 08:22
Thanks for your reply @joshaber - here we go!

I think here is the problem:

- the `core.excludesfile` is configured in my `/usr/local/etc/gitconfig`
- this `/usr/local/etc/gitconfig` is not respected by the application, even it is a default path, where git checks if a gitconfig is available (git itself checks first this path (systemwide), then the gitconfig in home directory (global) and at least the one in the repository and merges all the configurations.
- This is the problem, and i think it is a bug, because git behaves different (correct!) while github desktop does not.

Resolution:

You have just to also use/load the `gitconfig` files in the proper locations, what git does also. Systemwide, Global and at least per repository.

**Comment by shiftkey** [comment] 2017-12-17 03:07
@stefanbauer system Git configuration values are handled differently to global configuration values. These are intended to tied to a given Git installation, and not shared between builds of Git on your machine. The version of Git we ship in Desktop is intended to be portable (built from source [here](https://github.com/desktop/dugite-native/blob/master/script/build-macos.sh#L29-L35)), so it contains it's own system Git configuration.

It's not 100% clear that you've done this, but I suspect that's what's happening here. If you want Desktop to pick up your `core.excludesfile`, it should be in the global `~/.gitconfig`.

**Comment by stefanbauer** [comment] 2017-12-17 17:58
Why is not the native git version used, installed on the system and respect this configuration?

**Comment by j-f1** [comment] 2017-12-17 18:58
@stefanbauer We can’t guarantee that users have git installed and that it’s a new enough version to support all the features we use.

**Comment by stefanbauer** [comment] 2017-12-17 19:00
Gotcha! Idea: What is if there would be an option in the preferences, where the user can define a path to the git installation he would like to use or if he just would like to use the internal git (default)?

**Comment by j-f1** [comment] 2017-12-17 19:21
That’s a good idea, but I feel like it might lead to issues with people trying to load an older version (since we could update the git version in Desktop at any time without notice) and reporting bugs that are due to their usage of an old git version. It would probably just be simpler to fix any issues you’re having with the embedded git internally. In your case, would it be possible to move the systemwide configuration options to `~/.gitconfig`?

**Comment by stefanbauer** [comment] 2017-12-17 19:24
In general i don't have issues. May be my configuration is little bit "special". This comes because we have kind of provision for our developers where we store a "predefined" git configuration in the systemwide configuration, where the user should not change it. And the user defined configuration is empty, so that every user *can* override system wide settings if necessary. Imho is that the idea behind these different pathes, that configuration can be set at any level and at the end the user can override or add functionality to his own git configuration, if the "default" configuration does not fit.

**Comment by shiftkey** [comment] 2017-12-17 21:58
> What is if there would be an option in the preferences, where the user can define a path to the git installation he would like to use or if he just would like to use the internal git (default)?

This has been asked before, and I outlined the reasons why we don't have plans to support it at the moment here: https://github.com/desktop/desktop/issues/3435#issuecomment-347388985

**Comment by shiftkey** [comment] 2017-12-17 22:02
Closing this out as we know the root cause, and have provided ways to workaround the issue.

**Closed by shiftkey** 2017-12-17 22:02 UTC
