### ISSUE TITLE
Resolving conflicts is painful for Unity users

### ISSUE THREAD

**Issue by andybak** [desktop/desktop#8459] opened 2019-10-13 13:13 UTC
### Describe the feature or problem you’d like to solve

Unity scenes and assets are huge complex YAMLfiles not meant to be edited by humans (sadly). The only option offered when I have a conflict is to fix it manually in a text editor. This is difficult and error-prone.

### Proposed solution

Other Git GUIs have a simple "Accept theirs" or "Accept yours" button to resolve conflicts without manual editing. This would be useful in general but specifically helps with very large conflicts such as those common with Unity projects.

### Additional context

I'm basing this on the Intellij/Rider/PyCharm approach which is what I end up using when I need to fix conflicts beyond the Github Desktop comfort zone.

**Comment by Rexogamer** [comment] 2019-10-13 18:28
Dupe of #8248

**Comment by billygriffin** [comment] 2019-10-14 16:14
@andybak Thanks for the issue, and @Rexogamer thanks for pointing out the previous one that was directly related. I'm going to close this as a duplicate.

**Closed by billygriffin** 2019-10-14 16:14 UTC
