### ISSUE TITLE
Git clone returns isn't a Git repository

### ISSUE THREAD

**Issue by TristanLee9608** [desktop/desktop#15389] opened 2022-09-30 08:51 UTC
### The problem

Used the UI on GH Desktop to git clone. After git clone, the cloned repository should automatically be opend on GH Desktop but returns an error "{path to repository} isn't a Git repository.

### Release version

3.0.8

### Operating system

windows 7

### Log files

[2022-09-30.desktop.production.log.txt](https://github.com/desktop/desktop/files/9682193/2022-09-30.desktop.production.log.txt)

### Screenshots

![image](https://user-images.githubusercontent.com/47909442/193226422-94312d4c-d8ef-4bfe-ac0e-6bfee9d310ed.png)

git clone worked but it seems GHD can't read?

![image](https://user-images.githubusercontent.com/47909442/193226448-afb4f970-d428-486a-b8ea-257c540135f5.png)

### Additional context

My customer, @sungtaekchoi , is the Site Admin of their GHES 3.0.8. He gets a lot of this same error from his enterprise members.
On the log file, he cloned the repository by GHD UI and got the "isn't a Git repository". 
2022-09-30T04:09:42.491Z - info: [ui] [AppStore] adding repository at D:\OCRINKJET_LOG_MANAGER to store
above log is when he opened the repository through File > Add local repository, which had no error message.

Additionally, [2022-09-22.desktop.production.log.txt](https://github.com/desktop/desktop/files/9682327/2022-09-22.desktop.production.log.txt) is from one of his enterprise member, which had below error right after executing GHD.
![image](https://user-images.githubusercontent.com/47909442/193230181-12ca2d3c-f972-4990-a755-6b86c31ee8b7.png)
plus the runtime error as below after 20 seconds.
![image](https://user-images.githubusercontent.com/47909442/193230025-7e705e3c-4b21-404d-850d-c0c8bde35772.png)
disregarding the above errors, the member tried git clone but had "isn't a Git repository" error, and the repository QD_ACT(Test) isn't on the list either.
![image](https://user-images.githubusercontent.com/47909442/193230892-06904084-c781-40c1-a320-dcb0bc8e1b3a.png)
but from file explorer, you can see that the repo has cloned.
![image](https://user-images.githubusercontent.com/47909442/193231093-aedb4439-e08c-46dd-a3b8-990debf91089.png)
Unlike @sungtaekchoi could open the repo after the error, this member can't open the repository and is unable to use GHD

**Comment by steveward** [comment] 2022-09-30 20:56
Thanks for the issue @TristanLee9608. It looks like you previously reported similar errors in https://github.com/desktop/desktop/issues/14801. Is this the same user/organization?

The `Runtime Error` looks like a memory allocation issue. I'm not sure what's causing that, as it isn't an error we have seen before. Has that user tried restarting their machine?

The Git LFS error seems to be caused by a crash when attempting to install it:

```
2022-09-22T00:18:10.754Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
stdout:
warning: error running C:\Users\shses.kim\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\mingw64\bin\git.exe 'config' '--includes' '--global' '--replace-all' 'filter.lfs.smudge' 'git-lfs smudge -- %f': '' 'exit status 0xc0000005'
Run `git lfs install --force` to reset Git configuration
```

It also looks like the clone is failing due to a invalid path type:

```
2-09-22T01:42:19.424Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=master clone --recursive --progress -- [github url] E:\Source Code\QD_ACT(Test) (took 28.301s)
2022-09-22T01:42:20.785Z - error: [ui] Could not determine repository type
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

A few questions to help diagnose this:

- Are the drives the users are attempting to clone to network drives? We've seen issues with that in the past.
- Is there any antivirus/security software in place that could be affecting GitHub Desktop and causing the lfs install to fail?

Any details you can possibly share about the user environment would be helpful in diagnosing this issue. Thanks.

**Comment by TristanLee9608** [comment] 2022-10-05 00:39
Sorry for the late reply, @sungtaekchoi and I are checking the above questions to the users in the enterprise. This may take a while...

**Comment by TristanLee9608** [comment] 2022-10-05 00:47
For @sungtaekchoi's case, the drive he attempted to clone was not network drive. and there is an antivirus software in their enterprise called `Symantec Endpoint Protection`. He's checking whether this software blocked the lfs installation.

**Comment by sungtaekchoi** [comment] 2022-10-07 03:04
hi @TristanLee9608. it will take some time to confirm. i will let you know

**Comment by sungtaekchoi** [comment] 2022-10-13 07:51
hi
first of all, It is not clear what Symantec Endpoint Protection is blocked installation or not
but I did clone again today. but i It won't happen again.(error message : isn't a git repository)
is there anything else to check more??

**Comment by TristanLee9608** [comment] 2022-10-13 08:13
Hi @sungtaekchoi , Thank you for checking the antivirus.
Did `error: [ui] git lfs install --skip-repo exited with an unexpected code: 2.` happen in the logs made today?
If possible, could you upload the log file? 
it would be named `2022-10-13.desktop.production.log.txt`

안녕하세요 프로님, 확인 감사합니다. 
혹시 오늘 clone을 하셨을때의 로그에는 `error: [ui] git lfs install --skip-repo exited with an unexpected code: 2.` 에러가 발생하지 않았나요?
가능하시다면 오늘 생성된 로그 업로드 부탁드립니다.  `2022-10-13.desktop.production.log.txt`

@JamesJeongTangun

**Comment by TristanLee9608** [comment] 2022-10-24 00:12
Hi @steveward , is there any updates regarding this issue?

**Comment by sungtaekchoi** [comment] 2022-10-27 23:51
hi @TristanLee9608
The person who raised this issue is currently using a different tool. and not easy to check Symantec Endpoint Protection
so. i think we need to close this issue first and if i have same problem then i will contact you again

**Comment by steveward** [comment] 2023-05-26 14:42
Closing this out, let us know if you have any further questions going forward.

**Closed as completed by steveward** 2023-05-26 14:42 UTC
