### ISSUE TITLE
"Repository > Open in Visual Studio Code" causes window focus on the wrong window.

### ISSUE THREAD

**Issue by shawntabrizi** [desktop/desktop#14675] opened 2022-05-24 19:44 UTC
### The problem

When opening a repository using:

"Repository > Open in Visual Studio Code"

The wrong visual studio code window is brought into focus. What happens now is the last visual studio code window that you have interacted with is brought into focus.

For example:

* Currently in focus is Project A in VS Code
* Switch to GitHub Desktop Application, navigate to Project B
* Click "Repository > Open in Visual Studio Code"
* Project A window comes into focus again
* Project B window opened out of focus somewhere else

This is a behavior that has been broken for a while, but at one point, maybe a year ago, worked perfectly. I am reporting the issue now because I have just been burned too many times by this since I have multiple copies of the same repo that I work from (in order to keep multiple branches open at once). Yesterday, I started working in the wrong project because of this error (and not being careful).

### Release version

Version 3.0.0 (arm64)

### Operating system

MacOS Monterey 12.4 (M1)

### Steps to reproduce the behavior

* Open Project A in VS Code
* Switch to GitHub Desktop Application, navigate to Project B
* Click "Repository > Open in Visual Studio Code"
* Project A window comes into focus again
* Project B window opened out of focus somewhere else

### Log files

Not relevant, but happy to share them if you think that my assessment is wrong here.

### Screenshots

https://user-images.githubusercontent.com/1860335/170119250-92bb058a-b542-41b1-8826-9c3da56e915d.mov

### Additional context

In the video above, you can see I open a "pink" project from GitHub desktop. I have no other windows open at the time, so it correctly brings that window into focus.

I make that window full screen, as I would if I was working on projects with my Mac.

Then I go back to GitHub desktop to open a "green" project, and you can see that it brings the "pink" project back into focus.

If I go back to my other screen, you will see the green window which was opened, but not brought into focus.

**Comment by sergiou87** [comment] 2022-05-25 07:45
Hey @shawntabrizi ! 👋 

Thank you for your report, but I don't think GitHub Desktop can do much about this 😞  We just tell VS Code to open the repo, and it's VS Code who decides which window to focus. In your case, I think the problem is you're switching to fullscreen the first project you open, so something like this happens:
1. Desktop tells VS Code to open a second repository
1. VS Code gets the focus
2. Since the only repository that was opened in VS Code was in fullscreen, it switches to the virtual desktop where that repository is in fullscreen.
3. VS Code opens the second repository as you requested
4. VS Code *probably* attempts to focus to the new repository but it's in a different virtual desktop so it does nothing?

If you try doing the same steps without switching to fullscreen, it does indeed work (or it does for me, at least 😅 ). In any case, that's VS Code behavior, not Desktop's, so I'm going to close this, sorry 😢

**Closed as completed by sergiou87** 2022-05-25 07:45 UTC

**Comment by shawntabrizi** [comment] 2022-05-25 13:52
@sergiou87 you are right, without the full screen, behavior seems to work.

Thanks for looking into it. I guess I will open an issue to VS Code and see what they say. Hopefully it isn't an OS issue :/
