### ISSUE TITLE
show files as changed even if not modified

### ISSUE THREAD

**Issue by chandradeepak** [desktop/desktop#13312] opened 2021-11-12 05:22 UTC
### Describe the bug
Write a clear and concise description of what the bug is.
It shows files like .sh and files in bin dir as changed even though they are not changed

### Version & OS

Version 2.9.4 (x64)
Windows 10 x64

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Go to 'Gihtub desktop' 
2. Click on 'Changes'
3. Scroll down to ''

### Expected behavior

Expected it only show changes if there are differences

### Actual behavior

It shows so many files as modified even with out having difference 

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by chandradeepak** [comment] 2021-11-12 05:22
![githubdesktopissue](https://user-images.githubusercontent.com/6901293/141414329-7cb84d21-7856-49f8-9b11-f4d82484f604.png)

**Comment by sergiou87** [comment] 2021-11-12 09:37
Thanks for your report @chandradeepak 

Is it possible you changed the access permissions of those files?

**Comment by chandradeepak** [comment] 2021-11-12 09:41
It was fine before. I think it is broken in new version. In terms of permissions, do we need to change the permissions of all the files. It clearly can recognize there are no changes done. Why does the UI show it in change list?

**Comment by sergiou87** [comment] 2021-11-12 09:53
Could you run `git status` in your repository from the terminal to see the output?

GitHub Desktop only shows the changes as they're listed by the output of `git status`, so checking that output we might understand better the reason for this 😄

**Comment by chandradeepak** [comment] 2021-11-12 12:21
|movetogomod ✓| → git status
On branch movetogomod
Your branch is up to date with 'origin/movetogomod'.

nothing to commit, working tree clean

**Comment by chandradeepak** [comment] 2021-11-12 12:25
![githubdesktopissue2](https://user-images.githubusercontent.com/6901293/141466472-d79a42a4-e0e5-4d2d-a546-c1fa081746b0.png)
this is the snaphost of number of files showing changed


one thing i forgot to mention is this is WSL code it is showing so that path is 
\\wsl$\Ubuntu\home\chandra\go\src\github....

Does that has some thing to do with it. I have code in wsl but i have github desktop in windows.  and i added the repo path using above wsl path to see . So even though git status shows no changes at all in wsl terminal the github desktop is not showing that . It says 64 files changed.

**Comment by sergiou87** [comment] 2021-11-15 09:25
Could you try running `git status` from a Git Bash console on Windows instead of WSL?

I think the problem might be in mixing WSL and Windows. #12127 seems similar to your issue and maybe https://github.com/desktop/desktop/issues/12127#issuecomment-832679097 can help 🤞

**Comment by chandradeepak** [comment] 2021-11-16 10:21
this is what it shows

git status shows the difference. And when i see what the difference is 
 git diff docker/test/run-tests.sh
warning: LF will be replaced by CRLF in docker/test/run-tests.sh.
The file will have its original line endings in your working directory
diff --git a/docker/test/run-tests.sh b/docker/test/run-tests.sh
old mode 100755
new mode 100644

**Comment by sergiou87** [comment] 2021-11-16 11:22
Yeah so I think the problem is the mix of WSL (Linux) and Windows, and following the instructions @steveward gave in https://github.com/desktop/desktop/issues/12127#issuecomment-832679097 should fix the issue 🤞 

I'm gonna close this assuming that's the problem. If you follow those instructions and it doesn't work, please let us know and I'll be happy to reopen this and help out!

**Closed as completed by sergiou87** 2021-11-16 11:22 UTC
