### ISSUE TITLE
Up arrow at the top of History list sends us to a random commit

### ISSUE THREAD

**Issue by snicolet** [desktop/desktop#2763] opened 2017-09-18 08:50 UTC
### Description

When the history is long, highlighting the last commit (the most recent one) at the top of the history list and then typing the "up" arrow sends us to a random commit in the list, sometimes years ago.

### Version

**GitHub Desktop version:** [0.9.1]

**OS version:** [Mac OS X 10.9.5]

### Steps to Reproduce

1. Launch GitHub Desktop
1. Switch to a branch with a long history (for instance the master branch of an active project)
1. Click on the History panel to show the history of the last commits
1. Click on the most recent commit, or navigate to it with up/down arrow keys
1. Once the most recent commit is highlighted at the top of the list, type the "up" arrow key

**Expected behavior:** The list should not change and the most recent commit should stay highlighted

**Actual behavior:** The list jumps to a random commit, sometimes years ago

**Reproduces how often:** 100%

### Logs

[2017-09-18.desktop.production.log.txt](https://github.com/desktop/desktop/files/1310124/2017-09-18.desktop.production.log.txt)

**Comment by tierninho** [comment] 2017-09-18 09:12
@snicolet The `up` arrow cycles you to the bottom of the history list as it is an endless loop. All commits are in chronological order. 

Similarly, hitting the `down` arrow on the last commit will bring you to the latest commit.

Perhaps @desktop/design has some new thoughts on the matter.

**Comment by shiftkey** [comment] 2017-09-18 09:52
Cross-referencing the earlier report on this: #2479

**Comment by snicolet** [comment] 2017-09-18 11:50
@tierninho Nope, in my case the `up`arrow does not cycles me to the bottom of the history list, but jumps to a random commit N somewhere in the middle of the list (it changes every time). This means that I can not undo the effect of the `up` arrow with a subsequent `down`arrow, as the `down`arrow just brings me to commit (N+1).

In fact, anyway, I think the list should not change when we are on top of the list and we hit `up`.

PS: this is with an history of 4135 commits for the chess program project https://github.com/official-stockfish/Stockfish

**Comment by tierninho** [comment] 2017-09-18 12:21
@snicolet Thanks for the clarity. I was able to reproduce the error on your repo, however I do have a temporary "fix" as well. 

Looks like the all commits in the History need to be loaded first, and then the functionality works as intended. This means scrolling to the bottom of the 4,135 commits, then attempting the `up` arrow.

Due to the long list of commits, upon first opening the History tab, it appears there is a limited load of commits that prevents Desktop from jumping to the true first commit.

**Comment by joshaber** [comment] 2017-09-18 14:13
Yeah, this is a weird bit of behavior caused by the way keyboard navigation wraps around. We should disable it.

**Comment by shiftkey** [comment] 2017-09-18 21:50
There be dragons here, as we found out in #2539 when we took a shot at this.

**Comment by shiftkey** [comment] 2017-09-20 06:40
#2479 is marked as `future-proposal`, so I'm going to close this out as a duplicate.

Feel free to add any other feedback to that issue.

**Closed by shiftkey** 2017-09-20 06:40 UTC
Labels: bug
