### ISSUE TITLE
Surface at-mention user list above other panes

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6459] opened 2018-12-19 23:53 UTC
The `autocompletion-popup user` and `autocompletion-popup issue` lists in the description field are not surfacing above other parts of Desktop.

It works properly in the Summary and Co-Author fields.

Reproduce:
- Use `@username` or `#issue-number` in the description field. For the latter, you must have issues created.

<img width="491" alt="screen shot 2018-12-19 at 3 43 07 pm" src="https://user-images.githubusercontent.com/14828183/50255123-822d3a00-03a5-11e9-90f1-b3abeab6e4b4.png">

<img width="291" alt="screen shot 2018-12-19 at 3 53 25 pm" src="https://user-images.githubusercontent.com/14828183/50255328-42b31d80-03a6-11e9-8b9e-a57904547d64.png">

v1.5.1, mac

**Comment by j-f1** [comment] 2018-12-20 02:43
I think this is due to a PR that was merged a while ago. It fixed an issue where the corners of the text box poked into the focus outline by clipping the text box to that shape.

**Comment by outofambit** [comment] 2019-01-14 21:21
@j-f1 is right—@niik identified https://github.com/desktop/desktop/pull/6234 as the likely cause of this regression.

**Closed** 2019-01-15 17:45 UTC
Labels: bug, priority-2
