### ISSUE TITLE
No window, and when forcing a window get all white window on MacOS

### ISSUE THREAD

**Issue by alison985** [desktop/desktop#4906] opened 2018-06-09 18:17 UTC
## Description
No Github Desktop window is being painted to the screen. When forcing a window to appear the window is all white and most menu options are grayed out.

## Version
* GitHub Desktop: Latest public release
* Operating system: MacOS 10.13.3

## Steps to Reproduce
I was using Github Desktop fine. It prompted me that it had a new version so I clicked the "Restart Now" link. I waited but no Github Desktop window appeared. If I Cmd+Tab the top menu bar admits I'm in Github Desktop but no window appears. If I go to File > New Repository a white window is shown. If I go to the bottom Mac menu bar when a white window is available and choose Show All Windows it will show me the white window, when I go to the bottom Mac menu bar when no window is available it will be a blue OS screen that says No Available Windows.

### Expected Behavior
See the repository I'm working on in the Window with diffs and ability to add commit message, etc.

### Actual Behavior
See no window or white window.

## Additional Information
Here is what the white window looks like:
https://www.dropbox.com/s/k7i4fu5dqgqghm8/Screenshot%202018-06-09%2013.15.08.png?dl=0

### Logs
[2018-06-09.desktop.production.log](https://github.com/desktop/desktop/files/2087225/2018-06-09.desktop.production.log)

**Comment by alison985** [comment] 2018-06-09 18:18
Note: I also tried just downloading the app directly again from desktop.github.com but no go. Same behavior.

**Comment by shiftkey** [comment] 2018-06-10 09:17
@alison985 thanks for the report. This feels like #4054, but I'd like to confirm this is the same root cause - are you able to open the **View** | **Toggle Developer Tools** menu and see if there's any interesting errors under the **Console** tab?

**Comment by alison985** [comment] 2018-06-10 13:21
@shiftkey Here's the console error: https://www.dropbox.com/s/9wb73s5k6132jho/Screenshot%202018-06-10%2008.20.40.png?dl=0

**Comment by shiftkey** [comment] 2018-06-10 22:30
@alison985 thanks for that. This is the same as #4054, so I'll close this out in favour of that. 

There's a workaround here to get you back to a happy place: https://github.com/desktop/desktop/issues/4054#issuecomment-393419464

**Closed by shiftkey** 2018-06-10 22:30 UTC
Labels: more-information-needed
