### ISSUE TITLE
Sugesstion:  a little function ,  allow people to copy the history hash code

### ISSUE THREAD

**Issue by 709889989** [desktop/desktop#1790] opened 2017-05-26 09:23 UTC
I want to change the history version . to run the shell "git reset [commit]" , but i can't copy the commit hash code .

like:
git reset --keep a879ec06ef9504db8df2a19aac0d07609fe36131

**Comment by shiftkey** [comment] 2017-05-26 09:24
Duplicate of https://github.com/desktop/desktop/issues/1501

**Closed by shiftkey** 2017-05-26 09:24 UTC
