### ISSUE TITLE
Will the "Sync" feature be provided again as an option?

### ISSUE THREAD

**Issue by drakeet** [desktop/desktop#2751] opened 2017-09-16 01:54 UTC
I got a reply by @j-f1 : 

> Please note that the old Desktop will be deprecated fairly soon; although you’ll still be able to use the classic app, it won’t get any more support or updates. If there’s something you don’t like about the new app, please open an issue and tell us about it!

Thanks for j-f1. I love the old Desktop(v223). Because I think its **Sync** feature is particularly great. But to the new version, this feature was discarded. I would like to know whether this feature can be provided again, at least as an option, if so, it would be great, I think a lot of people have no reason to use the old version.

![image](https://user-images.githubusercontent.com/5214214/30508244-f52acaa8-9a57-11e7-90b5-380574ca4d47.png)

Thanks so much for your work and offering so good and great software.

**Comment by drakeet** [comment] 2017-09-16 01:59
Link to #2295, #549, #1565

**Comment by ricksentam** [comment] 2017-09-16 02:40
is this a good desktop ? if so , I will reconnect that , as I missing the software too , so much fun :)

**Comment by CrazyBunQnQ** [comment] 2017-09-16 04:50
I agree with you!!!

**Comment by j-f1** [comment] 2017-09-16 12:51
In most cases, the Push/Pull/Publish button should be the same as the old sync button. The only difference AFAIK is that if your local branch is both ahead of and behind the remote, it will pull and merge on the first click, and you have to click again to push.

**Comment by shiftkey** [comment] 2017-09-18 00:13
Some context about why we moved away from sync button in #549 (emphasis mine):

> ### Magic sync button
> 
> A very common feedback with the current clients has been that the sync button is scary. We believe that it currently serves two groups of users very well, the first being those who deeply understand Git and realize what it's doing and the second is those users who have deep trust in the app and doesn't care all that much about its inner workings. It doesn't work so well for the remainder of users and various suggestions have been made over the years on how to address this. The most current thinking being that we'd keep it but with some sort of combo/dropdown so that users could explicitly pull or explicitly push.
> 
> We've taken another approach by replacing the ambiguous sync button with a contextual button that changes from “Push,” “Pull,” and “Publish” based on how far or ahead you are from the remote branch. **In essence we'll present the action that would be taken by a sync button.**
>
> **We've opted for using Git terminology primarily so that the button text is something users can throw into Google in order to understand what the action does.** Additionally in the case of errors we'll be able to present the underlying error as received from Git to the user (for them to Google). Note that this concept assumes that we keep background fetching in TNG:9000 as we'll need to reflect changes to the remote.

Putting that aside, this is a duplicate of #1565, so please add your feedback to that issue.

**Closed by shiftkey** 2017-09-18 00:13 UTC
