### ISSUE TITLE
Github desktop is not opening

### ISSUE THREAD

**Issue by lucastaehli** [desktop/desktop#4020] opened 2018-02-15 10:28 UTC
-->

### Description

1. Turn on Computer. Start GitHub Desktop: It works.
2. Close Github Desktop and reopen: Doesnt work anymore.
3. Since some days opening GitHub Desktop doesnt work at all.

Reinstalling GitHub helped sometimes, but the problems described in 1. and  2. were still there.

### Version

**GitHub Desktop version:** [1.0.13.0]

**OS version:** [Windows 10. Version 1709]

### Steps to Reproduce

1. [See description]

**Reproduces how often:** [100% until Github Desktop doesnt open at all]

**Comment by iAmWillShepherd** [comment] 2018-02-15 16:59
Could you attach your log file to this issue, please? 🙏

**Comment by lucastaehli** [comment] 2018-02-16 11:15
I saw from other issues that every time I start Github Desktop, Squirrel Updater starts:

`2018-02-15 15:38:38> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-15 15:38:38> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-15 15:38:38> CheckForUpdateImpl: Using existing staging user ID: ______
2018-02-15 15:38:38> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-15 15:38:38> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=1.0.13&env=production&id=GitHubDesktop&localVersion=1.0.13&arch=amd64
2018-02-16 12:03:39> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-16 12:03:39> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-16 12:03:39> CheckForUpdateImpl: Using existing staging user ID: ______
2018-02-16 12:03:40> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production
2018-02-16 12:03:40> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=1.0.13&env=production&id=GitHubDesktop&localVersion=1.0.13&arch=amd64
`

**Comment by Poemtech** [comment] 2018-02-23 21:03
I'm having the same problem.  Two processes start but there is no window open or minimized.  There also is no log file associated with the current running processes, according to the time stamp on the log file.

**Comment by Poemtech** [comment] 2018-02-23 21:20
is the arch-amd a clue?  My processor is an Intel Core i7
running update by hand gives:
`2018-02-23 16:10:05> Program: Starting Squirrel Updater: --checkForUpdate https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production 2018-02-16`


`2018-02-23 16:10:05> Program: Fetching update information, downloading from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production 2018-02-16`

`2018-02-23 16:10:05> CheckForUpdateImpl: Using existing staging user ID: b04d8c30-5345-5fe0-9d18-52c553d298ad`

`2018-02-23 16:10:05> CheckForUpdateImpl: Downloading RELEASES file from https://central.github.com/api/deployments/desktop/desktop/latest?version=1.0.13&env=production 2018-02-16`

`2018-02-23 16:10:06> FileDownloader: Downloading url: https://central.github.com/api/deployments/desktop/desktop/latest/RELEASES?version=1.0.13&env=production+2018-02-16&id=GitHubDesktop&localVersion=1.0.13&arch=amd64`

**Comment by tierninho** [comment] 2018-09-17 21:04
@iAmWillShepherd see anything in the logs? Looks like a potential dupe of #3757 ...

**Comment by billygriffin** [comment] 2018-10-01 15:57
Going to close this in favor of #3757.

**Closed by billygriffin** 2018-10-01 15:57 UTC
Labels: Windows, investigation-needed
