### ISSUE TITLE
Installation process under windows 10

### ISSUE THREAD

**Issue by coaperator** [desktop/desktop#2122] opened 2017-06-26 19:57 UTC
The bug with the installation under Windows 10

I recorded a video
https://youtu.be/rT-nHDSjnTU

Windows 10, app version 0.6.1/0.6.2
![image](https://user-images.githubusercontent.com/6645911/27557872-9f740574-5ad4-11e7-9afc-a595e63ef30c.png)

It only helps to reboot or log off
After that the program is started normally

How do I play this bug? Just run an installation under windows 10

**Comment by carljohansen** [comment] 2017-06-27 05:10
Er, I think I might have seen the same problem when installing on Windows 10.  I noticed that same behaviour in Task Manager, and GHDesktop worked for me after logging out and back in.  In case it helps, here is a snippet from my SquirrelSetup.log file.  Notice that it just goes around in an endless loop:

2017-06-27 15:02:38> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-27 15:02:38> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-06-27 15:02:39> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
2017-06-27 15:02:39> ApplyReleasesImpl: About to create shortcuts for GitHub Desktop.exe, rootAppDir C:\Users\Carl Johansen\AppData\Local\GitHubDesktop
2017-06-27 15:02:39> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Carl Johansen\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk
2017-06-27 15:02:39> ApplyReleasesImpl: About to save shortcut: C:\Users\Carl Johansen\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\GitHub, Inc.\GitHub Desktop.lnk (target C:\Users\Carl Johansen\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Carl Johansen\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-27 15:02:39> ApplyReleasesImpl: Creating shortcut for GitHub Desktop.exe => C:\Users\Carl Johansen\Desktop\GitHub Desktop.lnk
2017-06-27 15:02:39> ApplyReleasesImpl: About to save shortcut: C:\Users\Carl Johansen\Desktop\GitHub Desktop.lnk (target C:\Users\Carl Johansen\AppData\Local\GitHubDesktop\GitHub Desktop.exe, workingDir C:\Users\Carl Johansen\AppData\Local\GitHubDesktop\app-0.6.2, args , toastActivatorCSLID 27d44d0c-a542-5b90-bcdb-ac3126048ba2)
2017-06-27 15:02:39> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2017-06-27 15:02:39> ApplyReleasesImpl: Examining Pin: Windows Media Player.lnk
2017-06-27 15:02:39> Program: Starting Squirrel Updater: --createShortcut GitHub Desktop.exe
[REPEAT FOREVER...]

**Comment by sinaa** [comment] 2017-06-27 19:16
Can also confirm that the installation gets stuck in an infinite loop. Since the application keeps respawning, it's near impossible to kill it (and thus requires a reboot).

**Comment by leskal** [comment] 2017-06-27 21:43
Can confirm it also

Win 10 64bit 1703

**Comment by joshaber** [comment] 2017-06-28 16:00
Thanks all, this looks like a duplicate of https://github.com/desktop/desktop/issues/1863. Feel free to follow along over there.

**Closed by joshaber** 2017-06-28 16:00 UTC
