### ISSUE TITLE
Continually seeing "Connection was reset" error messages.

### ISSUE THREAD

**Issue by clawton** [desktop/desktop#10638] opened 2020-09-24 16:25 UTC
### Describe the feature or problem you’d like to solve

Repeatedly see the message:
fatal: unable to access 'https://XXXXXXX/': OpenSSL SSL_connect: **Connection was reset in connection to** XXXXXXX.visualstudio.com:443 

Sometimes it doesn't happen, sometimes only once but always, after repeated attempts, the operation eventually succeeds.
Happens on fetches, pulls, pushes, etc.

### Proposed solution

Add an advanced option to retry failed connections.  Should be configurable to the amount of retries.

How will it benefit Desktop and its users?
Wont cause so many scary messages. :)

### Additional context
If there is a config files or somewhere where this can already be set, please advise.

**Comment by tierninho** [comment] 2020-09-24 18:47
@clawton Thanks for the report. It looks like there may be some network issues or antivirus inference but hard to say at this point. Can you include the logs seen in the Help menu? Also, are you using a proxy by chance?

**Comment by clawton** [comment] 2020-09-24 18:51
Attaching logs where this issue happens...

[2020-09-24.desktop.production.log](https://github.com/desktop/desktop/files/5278528/2020-09-24.desktop.production.log)

**Comment by tierninho** [comment] 2020-09-24 20:04
Thanks. I don't see anything revealing in the logs. Anything unique about your connection or setup? I don't think I have seen a url like that before.

> If there is a config files or somewhere where this can already be set, please advise.

Not that I know of.

**Comment by clawton** [comment] 2020-09-24 20:49
URL is awkward because there are spaces in the project name of our Azure Devops project.

Anyway, if your team could take my request for retries into consideration, that would be great. As you saw from the log, it happens and then just works. Weird.  If there are any suggestions as to what causes the error and how to fix it, please let me know.  Thanks.

**Comment by tierninho** [comment] 2020-09-24 22:45
> Anyway, if your team could take my request for retries into consideration, that would be great. 

Thanks for the suggestion - it is worth a thought. Not sure how retries we attempt currently.

> If there are any suggestions as to what causes the error and how to fix it, please let me know. Thanks.

@niik any thoughts on the causes?

**Comment by steveward** [comment] 2020-09-25 01:05
@clawton can you run the command `git config --list --show-origin` to verify that you do not have any leftover proxy settings configured? Having an empty proxy config can throw this type of error.

**Comment by clawton** [comment] 2020-09-25 01:28
@steveward Here's the output:

```
E:\KPM\MCT>git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/etc/gitconfig core.editor="C:\\Program Files\\Notepad++\\notepad++.exe" -multiInst -notabbar -nosession -noPlugin
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=true
file:C:/Program Files/Git/etc/gitconfig pull.rebase=false
file:C:/Users/clawt/.gitconfig  core.autocrlf=true
file:C:/Users/clawt/.gitconfig  core.excludesfile=C:\Users\clawt\Documents\gitignore_global.txt
file:C:/Users/clawt/.gitconfig  user.name=Chris Lawton
file:C:/Users/clawt/.gitconfig  user.email=clawton@dlssolutions.com
file:C:/Users/clawt/.gitconfig  gc.autodetach=false
file:C:/Users/clawt/.gitconfig  pull.rebase=true
file:C:/Users/clawt/.gitconfig  filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/clawt/.gitconfig  filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/clawt/.gitconfig  filter.lfs.process=git-lfs filter-process
file:C:/Users/clawt/.gitconfig  filter.lfs.required=true
file:C:/Users/clawt/.gitconfig  http.sslbackend=openssl
file:C:/Users/clawt/.gitconfig  http.sslcainfo=C:\Program Files\Git\mingw64\ssl\cert.pem
file:C:/Users/clawt/.gitconfig  gui.recentrepo=E:/KPM/MCT
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://dlssolutions.visualstudio.com/KPM%20MCT/_git/KPM%20MCT
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        gui.wmstate=zoomed
file:.git/config        gui.geometry=1322x693+304+304 254 315

```

**Comment by niik** [comment] 2020-10-19 08:44
Hi @clawton, thanks for opening this. It sounds like there are connectivity issues that's causing these errors. These connectivity problems could be either on your end or that of Azure Devops. It's unlikely that we'll be adding an option for retrying connections in Desktop as we believe something like that would best be implemented in Git itself where they can make a contextual decision on whether retrying makes sense depending on where in the communication process the interruption came. As such I'm going to close this as this isn't something we're going to be working on in the near term.

**Closed by niik** 2020-10-19 08:44 UTC
Labels: more-info-needed

**Comment by MauricioJuniorR** [comment] 2021-04-21 12:56
C:\Users\MAC 2006\Documents\Intellectus>git config --list --show-origin
file:C:/Program Files/Git/etc/gitconfig pack.packsizelimit=2g
file:C:/Program Files/Git/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/etc/gitconfig filter.lfs.required=true
file:C:/Program Files/Git/etc/gitconfig http.sslbackend=openssl                                                         file:C:/Program Files/Git/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw32/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/etc/gitconfig core.autocrlf=true
file:C:/Program Files/Git/etc/gitconfig core.fscache=true
file:C:/Program Files/Git/etc/gitconfig core.symlinks=false
file:C:/Program Files/Git/etc/gitconfig pull.rebase=false
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager-core
file:C:/Program Files/Git/etc/gitconfig credential.https://dev.azure.com.usehttppath=true
file:C:/Program Files/Git/etc/gitconfig init.defaultbranch=master

C:\Users\MAC 2006\Documents\Intellectus>

**Comment by TheRealMilesLee** [comment] 2021-06-13 14:07
I just tried using proxy to connect, and all the problem solved

**Comment by theskepticalcat** [comment] 2021-06-14 10:00
> Я просто попробовал использовать прокси для подключения, и вся проблема решена

please help! how to do that?.. thank you..
