### ISSUE TITLE
Github Desktop doesn't respect default pull strategy set on global gitconfig

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#15553] opened 2022-11-02 15:11 UTC
### The problem

When installing Git, you are prompted to choose the default pull strategy, which is set to merge by default. If you set it to rebase, this will set `pull.rebase` to true in your global gitconfig. Github Desktop doesn't follow this setting nor does it prompt you to set it, always defaulting to merge which is annoying and should be fixed.

### Release version

3.1.2

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Install Git on your machine
2. When installing, set the default pull strategy to rebase, or make sure your global `pull.rebase` gitconfig entry is set to `true`
3. In one of your projects, make sure you have commits to pull.
4. Make some changes and commit them before pulling
5. Press the pull button
6. Notice how GitHub Desktop creates a merge commit instead of rebasing, which is what would happen if you wan `git pull`

**Comment by steveward** [comment] 2022-11-02 15:41
Thanks for the issue @ImRodry. This config option should be respected, unless you are using the `Update from <default branch>` option in the menu. See https://github.com/desktop/desktop/issues/7956 for some context around that. For reference this is what you should see when the config option is set to `true`:


<img width="513" alt="Screen Shot 2022-11-02 at 11 36 18 AM" src="https://user-images.githubusercontent.com/721500/199533295-0bdf012b-f8a6-4143-9e7b-e54657d8bb82.png">

Any chance you have a local config that could be overriding this? Running `git config --list --show-origin` will show you all the config options and their origin.

**Comment by ImRodry** [comment] 2022-11-02 15:47
I had already run that command and that's how I found out the setting that was defining this behavior, so it is set to true and it's coming from the global config. I'm not sure what issue I'm supposed to look at since you linked this issue but I can say that I tried this with the default branch by using the button in your image which did not show that text. Also, in your image, you don't seem to have any commits to be pushed locally, which is something I noted in the original report.

**Comment by steveward** [comment] 2022-11-02 15:56
Apologies, https://github.com/desktop/desktop/issues/7956 is what I meant to reference. Having new commits won't make a difference, you'll still see the same thing but with an indicator that you have local commits to push:

<img width="296" alt="Screen Shot 2022-11-02 at 11 56 03 AM" src="https://user-images.githubusercontent.com/721500/199538347-8185bcd3-3dc0-4ef3-bffe-c9d3c6370f31.png">

**Comment by steveward** [comment] 2022-11-02 15:57
Are you seeing `Pull origin with rebase` in the button?

**Comment by ImRodry** [comment] 2022-11-02 16:09
No, I simply see this
![image](https://user-images.githubusercontent.com/38259440/199541645-448eb8ce-6a59-4ed4-8606-03b63aaf7e3e.png)

**Comment by steveward** [comment] 2022-11-02 16:58
Hmmm, I confirmed with a quick test switching back and forth between `git config --global pull.rebase true/false` correctly updates the button as well. Could you share the output of `git config --list --show-origin` so that we can check if there are any configuration issues that could be causing this?

**Comment by ImRodry** [comment] 2022-11-02 18:38
No as that can expose some sensitive info but I can show you the output of `git config pull.rebase` which is `true`. Keep in mind I never defined it through the command, I picked an option when installing
![image](https://user-images.githubusercontent.com/38259440/199574255-540b0ba2-c1b6-4cdd-a666-c47381158cd5.png)

**Comment by steveward** [comment] 2022-11-02 19:09
Can you also verify that `git config --local pull.rebase` returns `true` (or empty)?

**Comment by ImRodry** [comment] 2022-11-02 19:22
It’s empty

**Comment by steveward** [comment] 2022-11-03 12:54
Unfortunately I'm running out of ideas. There was a similar issue reported in https://github.com/desktop/desktop/issues/11718 but that user never came back with an update. Just to confirm -- when you pull via the command line does it respect the rebase setting? You could also try running `git config --local pull.rebase true` to see if setting the local config option triggers it correctly.

**Comment by ImRodry** [comment] 2022-11-03 13:44
Yes when I run `git pull` on any repository it rebases correctly. I believe the issue here is that this setting is set in git’s install path which, in my case, is D:/Program Files/Git/etc/gitconfig and not the config on %userprofile%, so maybe github desktop isn’t looking there? I could set it to true on every repo but that would be rather annoying

**Comment by steveward** [comment] 2022-11-03 14:26
Thanks for the update -- that definitely is the issue (and is why I was hoping to see the output of `git config --list --show-origin` since that would've shown that it was configured there). You'll want to set it to your global `.gitconfig` and not the system config if you want GitHub Desktop to pick it up. GitHub Desktop ships with its own version of Git so it picks up the system config from that separate installation. You don't need to set it on every repo, the global `.gitconfig` will be enough.

I'm going to close this out since we've seem to have figured out the issue, but let me know if you have any further questions.

**Closed as completed by steveward** 2022-11-03 14:26 UTC

**Comment by ImRodry** [comment] 2022-11-03 15:24
Yeah setting the global config works apparently. I think it would be nice if github desktop would look there but I understand why it doesn’t. Thanks!
