### ISSUE TITLE
Windows 7, 8 and 10 needs apps to be DPI-aware

### ISSUE THREAD

**Issue by BenMcLean** [desktop/desktop#14612] opened 2022-05-13 22:50 UTC
### The problem

Github Desktop doesn't scale correctly with high DPI settings on Windows 10.

### Release version

Version 3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Set Windows "Make Everything Bigger" to 175% and resolution to 1080p
2. Open Github Desktop
3. Maximize the window
4. Oh no! Controls go off screen!

### Screenshots

![image](https://user-images.githubusercontent.com/1747250/168398704-a29a4276-27a3-46f6-b8e2-cb3bf71c7255.png)

### Additional context

On Windows 10, there is a feature called UI Scaling described in this article: https://www.thurrott.com/windows/windows-10/4597/windows-10-feature-focus-display-scaling

This is a good feature for people with vision problems to make the text and GUI elements bigger in most Windows programs.

This feature first started on Windows XP but programmers only started having to worry about it when Windows 7 started trying to scale up apps that didn't tell the newer Windows API that they were DPI-aware. As InfoWorld says, "For apps that aren't high-DPI aware, Microsoft has a quick and dirty fix called DPI virtualization. Windows deliberately reports the wrong DPI resolution to such apps, so their elements render as if they were on a lower-resolution display. The results are then zoomed to fit the current display." http://www.infoworld.com/article/2952506/microsoft-windows/high-resolution-displays-reveal-windows-10-blind-spot.html

What needs to be done to fix this is to make apps DPI-aware, as discussed in this article from Microsoft https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx and explained in this tutorial. https://msdn.microsoft.com/en-us/library/windows/desktop/dd464659(v=vs.85).aspx

Here is a really good blog post about the issue: http://www.hanselman.com/blog/LivingAHighDPIDesktopLifestyleCanBePainful.aspx

**Comment by tsvetilian-ty** [comment] 2022-05-14 16:13
@BenMcLean, that's an awful issue that renders the app unusable in some cases 😞 The problem appears in multi-monitor setups with different DPI scaling. You can check #13940 for more information

**Comment by BenMcLean** [comment] 2022-05-15 21:28
Probably can be fixed by https://github.com/electron/electron/pull/33231

**Comment by sergiou87** [comment] 2022-05-16 07:51
Yep, there are a few issues related to UI scaling that come from Electron. They will be fixed (🤞 ) once we upgrade, but it'll take a bit since upgrading Electron can introduce new regressions (like this one) so we need to be extra careful.

I'm gonna close this as duplicate of the many related issues like #13940 or #14037

Please subscribe to any of them if you want to get notified once we fix it.

**Closed as completed by sergiou87** 2022-05-16 07:51 UTC
