### ISSUE TITLE
Option not to confirm discarding changes

### ISSUE THREAD

**Issue by simonlast** [desktop/desktop#1918] opened 2017-06-06 20:13 UTC
### Description

I find it frustrating that I have to confirm to discard changes every time. It would be nice if this was not the default, or there was a setting to disable this.
Or, the best UX would be to add the ability to undo this action.

### Version

**GitHub Desktop version:** 0.5.9

### Steps to Reproduce

1. Discard changes on a file.
2. A dialog pops up.

**Comment by shiftkey** [comment] 2017-06-07 00:38
For reference, we provided an option for the confirmation dialog under Preferences/Options when removing repositories:

<img width="478"  src="https://user-images.githubusercontent.com/359239/26857332-4b12a672-4b00-11e7-827b-097b9a03bb3d.png">

I'll let @desktop/core chime in on how the feel about this.

**Comment by joshaber** [comment] 2017-06-07 13:34
We provided this option in Classic on Mac:

![screen shot 2017-06-07 at 9 34 27 am](https://user-images.githubusercontent.com/13760/26881137-8c9e1f22-4b64-11e7-970d-2e2bc64a1d9a.png)

**Comment by lee-dohm** [comment] 2017-06-07 17:26
I definitely agree with the "Do not show this message again" system for dialogs.

In the Atom github package, we have an obvious "Undo Discard" button that shows up after changes have been discarded:

<img width="308" alt="screen shot 2017-06-07 at 10 22 06 am" src="https://user-images.githubusercontent.com/1038121/26891831-340856e6-4b6b-11e7-9668-665c3aea1909.png">

Personally, I feel that no dialog is better than the option of disabling one.

**Comment by shiftkey** [comment] 2017-06-07 17:49
@lee-dohm we're tracking "Undo Discard" as a feature here https://github.com/desktop/desktop/issues/861

**Comment by lee-dohm** [comment] 2017-06-07 17:51
Sounds like this is a duplicate of #861 then. Would you agree @simonlast?

**Comment by simonlast** [comment] 2017-06-07 17:58
I agree, undo discard with no dialog is far superior 👍

**Closed** 2017-06-07 17:58 UTC
Labels: enhancement
