### ISSUE TITLE
Creating a new repo with a space in the name doesn't get mangled correctly

### ISSUE THREAD

**Issue by fluffy-critter** [desktop/desktop#3798] opened 2018-01-15 06:14 UTC
### Description

I am working with someone who is new to git, and who is just learning how to make new repositories. He keeps on forgetting that you cannot have spaces in repository names. When he creates a repository from github.com, this works fine (as the space is mangled to an underscore), but if he creates it from GitHub Desktop, the push fails with nonsensical errors.

Tracking this down was difficult as for the most part the errors he was getting were along the lines of the following (when attempting an initial push from the command line):

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

which led to a wild goose chase of fixing all his ssh keys, which had no effect. Eventually it came to light that GitHub Desktop was also showing an error, `Git name field cannot be a disallowed character.`

As he is remote and a git novice it was very difficult to even get any sort of useful information out of him, and eventually the solution we came to was for him to delete his .git directory and re-create the repo, which worked fine.

### Version

**GitHub Desktop version:** Unknown, presumably the latest Windows build as of 1/14/2018 (as he had reinstalled on that day as a standard troubleshooting step).

**OS version:** Windows 10, again unknown specific build...

### Steps to Reproduce

1. Create a repository with a space in the name from GitHub Desktop
1. Attempt to push

**Expected behavior:** Successful push to the remote repo with the name properly mangled

**Actual behavior:** Failure to push with an unrelated authentication error

**Reproduces how often:** 100%

### Logs

[2018-01-14.desktop.production.log](https://github.com/desktop/desktop/files/1633030/2018-01-14.desktop.production.log)

**Comment by shiftkey** [comment] 2018-01-15 16:00
@fluffy-critter thanks for the details. A log file will definitely help us with understanding the issue with the pushes (if they're related to SSH not being setup correctly or something else).

The `Git name field cannot be a disallowed character.` error feels very similar to #3722, which was fixed in #3751 and will go out with the next update.

**Comment by fluffy-critter** [comment] 2018-01-15 21:15
Thanks, I'm working on getting that information. Note that the failed pushes were from the command line rather than from GitHub Desktop, but hopefully GitHub Desktop has logs around things.

It turns out that he had created the repository on a different machine and copied it to his laptop via USB thumb drive, though, and he is currently traveling so he doesn't have access to those logs. Hopefully the logs he does have access to will be useful anyway.

**Comment by fluffy-critter** [comment] 2018-01-15 21:24
Okay, I got a log that shows the resulting error, although it doesn't appear to have any information about the repo it's trying to connect to. It's attached anyway. Hopefully that's helpful, or leads to the next thing to look for.

**Comment by joshaber** [comment] 2018-01-16 16:02
@fluffy-critter It looks like the attachment didn't come through. Could you give it another shot?

**Comment by iAmWillShepherd** [comment] 2018-01-16 18:25
@joshaber it looks like it's in the first comment at the bottom.

**Comment by fluffy-critter** [comment] 2018-01-16 20:15
Yeah I attached it to the initial bug report, sorry that wasn't obvious.

**Comment by shiftkey** [comment] 2018-02-01 03:01
@fluffy-critter thanks for the log file, and apologies for the delay in replying.

Looking at the recent errors, I suspect this is related to the repository using SSH remotes, which we don't have first-class support for in Desktop. This is being tracked in #2579, so please follow along with that issue.

Looking at the fetch error that gets repeated:

```
2018-01-14T04:50:40.759Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

For SSH remotes, Git will delegate to a running `ssh-agent` process on the machine that is configured with the user's SSH keys to handle authentication. The error you are seeing feels very much in that vein.

To confirm you have your SSH agent setup correctly, we have these two guides:

 - first, [Generating a new SSH key and adding it to the SSH agent](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-windows)
 - next, [Adding a new SSH Key to your GitHub Account](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/#platform-windows)

If you've run through both guides, you should be able to fetch/push/pull as long as that `ssh-agent` process is running with your SSH keys.

Alternatively, if you don't need SSH authentication I can help switch you over to HTTPS remotes - which Desktop will support fine. Just run this command against the repository and attach the output here:

```
> git remote -vv
```

**Comment by fluffy-critter** [comment] 2018-02-01 03:31
Based on the auth errors the very first thing I tried having my associate do was those two steps, generating a new key and adding it to the github account. Also he was able to access other repositories just fine using an ssh remote and the very same existing keys he was using before.

Is it possible that the client was attempting to connect to a malformed URL (with a space still in it) and the ssh/auth error was simply because it didn't look like a valid repo? Because that's the only thing that made sense given the debugging steps I had him go through to try to clear the issue up.

**Comment by fluffy-critter** [comment] 2018-02-01 03:34
Oh and another thing to mention: he had created the repo *from GitHub Desktop*, with a space in the name. It got mangled to not having a space server-side. Then he was unable to actually push to the very repo he had just created.

**Comment by shiftkey** [comment] 2018-02-01 04:04
> Is it possible that the client was attempting to connect to a malformed URL (with a space still in it) and the ssh/auth error was simply because it didn't look like a valid repo? 

The `git@github.com: Permission denied (publickey).` error suggests that the server and client got some way through the handshaking process, so I'm pretty sure the URL for the remote is valid. Adding the output of `git remote -vv` to this issue should confirm it.

> Oh and another thing to mention: he had created the repo from GitHub Desktop, with a space in the name. It got mangled to not having a space server-side.

I'm puzzled about this one for a couple of reasons:

 - the new repository dialog should swap in spaces for dashes, like the GitHub website does

<img width="478" src="https://user-images.githubusercontent.com/359239/35660328-825a6356-075f-11e8-87b2-7429a5f0fd15.png">

 - we don't enforce the same validation rules in the publish dialog (I'll open a separate issue about that)

<img width="475" src="https://user-images.githubusercontent.com/359239/35660510-87fdef34-0760-11e8-96ba-4da7430eea9d.png">

 - the API doesn't reject this repository name when creating, but instead adds in the spaces 

<img width="493" src="https://user-images.githubusercontent.com/359239/35660601-1f0aa034-0761-11e8-81a3-f3b19e2a1785.png">

 - remotes are only set after publishing completes successfully, using the `clone_url` value - which points to the HTTPS URL for the repository

https://github.com/desktop/desktop/blob/6ff3112dc2acdf43ba6517ff40cd3411d9c3269f/app/src/lib/stores/app-store.ts#L2190-L2192

If the user is able to provide more details about the publish step (the initial steps jumped from "create repo" to "pushing") and include specifics like "this was the name of the repository I used" and "the publish completed and it's configured with an `origin` that looks like this" then we can get a better idea of what's happening to them.

**Comment by fluffy-critter** [comment] 2018-02-01 04:10
Okay, hopefully if this happens again I can get more detailed/sensical information. Unfortunately, as I said, he's a git novice, and also treats it as voodoo. I'm not sure I can even trust the order of events he shared, and I don't know if he even remembers exactly what he did.

If this does occur again I'll try having him use https instead of ssh. Or next time I'm at his workspace I'll see if I can clone one of our existing repositories from his machine via ssh, which should also narrow it down.

**Comment by shiftkey** [comment] 2018-02-01 04:19
@fluffy-critter thanks. I'm going to close this out to try and stay on top of our backlog, but if you can provide more details about reproducing the issue I'm happy to revisit this.

**Closed by shiftkey** 2018-02-01 04:19 UTC
Labels: more-information-needed
