### ISSUE TITLE
"Warning: line endings have changed from 'LF' to 'CRLF'." when files have LF line endings on Windows

### ISSUE THREAD

**Issue by stuartpb** [desktop/desktop#3841] opened 2018-01-22 08:33 UTC
### Description

As initially noticed in https://github.com/desktop/desktop/pull/1906#issuecomment-359083709 and observed further in #3828, GitHub Desktop presents an erroneous warning about line endings for text files with LF line endings in the working directory.

This bug is not affected by the setting of `core.autocrlf`. I haven't tried changing the value of `core.eol`: it might impact this, but the behavior with its default value of `native` is a bug, so whether changing `core.eol` changes the behavior or not isn't really relevant.

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to reproduce

1. Clone https://github.com/testcases/repo-with-lf-endings (can be from within GitHub Desktop or another Git implementation like Git for Windows).
2. Edit `README.md` to make a content change to the file in an editor that allows you to switch between CRLF and LF line endings (such as Atom, via the line-ending tile on the footer status bar). Save the file with LF line endings.
3. Open the repository in GitHub Desktop.

**Expected behavior:**

GitHub Desktop should present the changes as normal, with no remarks about the line endings (as the LF line endings in the working copy of the file match the LF line endings of the file as recorded within the repository data).

**Observed behavior:**

An `svg.octicon.line-endings` warning-triangle element containing a `title` with the content `Warning: line endings have changed from 'LF' to 'CRLF'.` appears next to the `svg.octicon.status-modified` status icon in the `div.changed-file div.header` when reviewing the changed file. (The use of CSS selectors in this description is to communicate the precise location of the erroneous element.)

**Comment by brcontainer** [comment] 2018-01-22 13:31
Have you tried a .gitattributes file with:

```
* text=auto
```

Or fix by extension file:

```
*.svg text eol=lf
```

**Comment by shiftkey** [comment] 2018-01-22 21:20
@stuartpb could you also include the contents of your `~/.gitconfig` (feel free to scrub any identifying information) to help with reproducing the issue?

**Comment by stuartpb** [comment] 2018-01-23 02:08
> Have you tried a .gitattributes file with:
>
> ```
> * text=auto
> ```

[As I originally stated](https://github.com/desktop/desktop/pull/1906#issuecomment-359083709), this was the first thing I tried, and it has no effect (you can check out the `gitattributes` branch of the repository defined above).

> Or fix by extension file (use only LF):
>
> ```
> *.svg text eol=lf
> ```

While this does suppress the warning, it doesn't change the fact that the original warning, presented by GitHub Desktop in the normal case, is in error (that *in no way* have line endings "changed from 'LF' to 'CRLF'").

> @stuartpb could you also include the contents of your ~/.gitconfig (feel free to scrub any identifying information) to help with reproducing the issue?

These are the entire contents of my personal .gitignore:

```
[user]
	name = Stuart P. Bentley
	email = s@stuartpb.com
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[gui]
	recentrepo = C:/Users/Stuart/Documents/GitHub/repo-with-lf-endings
```

Are you saying that you *weren't* able to reproduce the issue on a Windows machine on your end? Because, to be clear, this is an *underlying bug in GitHub Desktop's implementation of this warning*, stemming from the [presumptuous mistranslation](https://github.com/desktop/desktop/blob/5da6a34e8ce0289bc7e0e7696b16276b261961bb/app/src/lib/git/diff.ts#L318-L347) of [Git's `check_safe_crlf` message about how line endings *will change* on checkout](https://github.com/git/git/blob/720b1764def1cfd67004d917ec954df20983e6bb/convert.c#L196-L221)  into [an assertion that line endings *have changed* in the working copy](https://github.com/desktop/desktop/blob/525936a9aec13202206887ea0ab3e2124d7211ad/app/src/ui/changes/changed-file-details.tsx#L54-L57), and I'd be *very* suprised to see this mistranslation fail to reproduce.

**Comment by brcontainer** [comment] 2018-01-30 05:23
@staceb Isn't configuration from Github Desktop, you using Windows, Git assumes CRLF, but your "text editor" uses LF only.

Or you change your text editor to CRLF or in your "local repository" change to use only LF using Git commands, example: 

In Github Desktop select your repository and in menu go to Repository > Open in Command Prompt:

![Repository > Open in Command Prompt](https://user-images.githubusercontent.com/4368952/35549291-056c489a-056c-11e8-87cd-ea416c79e979.png)

Execute this commands (In this exact order):

```
git config core.eol lf
git config core.autocrlf input
```

**Comment by staceb** [comment] 2018-01-30 10:47
@brcontainer I believe GitHub Desktop will honour whatever settings you have in your `.gitattributes` file. 

If there's nothing set for line endings in there, it'll use the settings in your `~/.gitconfig` file.

@shiftkey, please correct me if I'm wrong here! 

The fact that `*.svg text eol=lf` worked would say to me there's a line ending conversion happening from `LF` to `CRLF` into the working directory or object database. 

I believe `native` will convert all line endings to CRLF on Windows so if this is the setting on @stuartpb's machine, the error message would make sense? 

@stuartpb I'm wondering if you could try the same steps using git on the command line? 

It would be useful to see how git handles the same settings when editing and committing the file with LF line endings.

**Comment by brcontainer** [comment] 2018-01-30 11:45
@staceb sorry, my bad, the previous message was for Stuarpb (autocomplete fail :P)

**Comment by staceb** [comment] 2018-01-30 14:51
Ha, no worries @brcontainer. Hope it helps anyways 😄

**Comment by brcontainer** [comment] 2018-01-30 16:05
@staceb I tried in .gitattributes

```
* text=auto
* text eol=lf
```

Work fine :) (cc @stuartpb)

**Comment by nerdneha** [comment] 2018-05-08 07:33
Hi @stuartpb! Were @staceb's suggestions helpful?

I'm going to go ahead and close this one out but if the suggestions didn't help, could you give us some more information so we can further troubleshoot? Happy to re-open it at that time and help you further. Thanks!

**Closed by nerdneha** 2018-05-08 07:33 UTC
Labels: reviewer-needs-to-reproduce

**Comment by fwextensions** [comment] 2018-10-10 02:46
I'm seeing this confusing message as well in v1.4.1 on Windows 10.  The files on disk are plainly LF, but the warning says they have changed to CRLF.  Other repos where the files actually are CRLF don't show any warning.

**Comment by tierninho** [comment] 2018-10-10 16:59
@fwextensions this is a known issue with a pending fix yet to be implemented. Follow along here: https://github.com/desktop/desktop/issues/5741

**Comment by SikoSoft** [comment] 2019-11-19 22:16
A year on and the misleading string is still in place.

The issue is very simple: the string seems to be used regardless of what type of line endings are actually in use, so long as it detects a change in them.

For me, I just added linting rules in my project, which forced the lines to be LF. I changed my files FROM CRLF to LF, and GitHub reports the same message (indicating they were changed "to" CRLF, rather than from).

After adding the proper config to my .gitattributes file, the message and icon went away.

Nonetheless, the error is incredibly misleading because it actually states the opposite of what happened if you come from my approach (which I imagine many people complaining did).

**Comment by RedTShirtGaming-Studios** [comment] 2022-03-25 11:02
I don't know if this has been fixed but I was having the same problem. The way that I solved it, was by putting the project into a .zip file and then uploading it, Hope this helps! :)

**Comment by yilmaz22** [comment] 2022-05-13 15:59
> @stuartpb Isn't configuration from Github Desktop, you using Windows, Git assumes CRLF, but your "text editor" uses LF only.
> 
> Or you change your text editor to CRLF or in your "local repository" change to use only LF using Git commands, example:
> 
> In Github Desktop select your repository and in menu go to Repository > Open in Command Prompt:
> 
> ![Repository > Open in Command Prompt](https://user-images.githubusercontent.com/4368952/35549291-056c489a-056c-11e8-87cd-ea416c79e979.png)
> 
> Execute this commands (In this exact order):
> 
> ```
> git config core.eol lf
> git config core.autocrlf input
> ```

Thanks

**Comment by kavicastelo** [comment] 2024-02-27 12:19
I'm still facing this problem😕
In my case, some files are saying,
`This diff contains a change in line endings from 'LF' to 'CRLF'.`
and others are saying,
`This diff contains a change in line endings from 'CRLF' to 'LF'.`

If I fix one warning another warning occurs.

The `.gitattributes` file can solve this problem but how to solve it in these kinds of scenarios?

**Comment by brcontainer** [comment] 2024-02-27 12:35
@kavicastelo https://github.com/desktop/desktop/issues/3841#issuecomment-361480731 or https://github.com/desktop/desktop/issues/3841#issuecomment-361642026

**Comment by kavicastelo** [comment] 2024-02-27 17:22
@brcontainer both of these happening in the same project. I had 12 or more files to commit. the first time 4 files were warned like this #3841 (comment). then I changed the `.gitattributes` file like this.
```
* text=auto
* text eol=lf
```
after that change, the first warned files problems were solved(4 files). all of the other files were warned like this #3841 (comment) (rest of 8 files). 😕

**Comment by khiav223577** [comment] 2024-03-13 10:18
Adding `* text eol=lf` to .gitattributes resulted in my PNG and XLSX files becoming corrupted in a Linux environment.

There are strange diffs:
![image](https://github.com/desktop/desktop/assets/4011729/17324c82-3013-4ef6-8520-dc99f3723fc1)

**Comment by steveward** [comment] 2024-03-13 13:28
@khiav223577 this issue tracker is for GitHub Desktop, if you're having issues with Git on the command line I'd recommend asking for help at [GitHub Community](https://github.community) or [GitHub Support](https://support.github.com/).

**Comment by brcontainer** [comment] 2024-03-13 18:20
> Adding `* text eol=lf` to .gitattributes resulted in my PNG and XLSX files becoming corrupted in a Linux environment.
> 
> There are strange diffs: ![image](https://private-user-images.githubusercontent.com/4011729/312412357-17324c82-3013-4ef6-8520-dc99f3723fc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNTQxMjcsIm5iZiI6MTcxMDM1MzgyNywicGF0aCI6Ii80MDExNzI5LzMxMjQxMjM1Ny0xNzMyNGM4Mi0zMDEzLTRlZjYtODUyMC1kYzk5ZjM3MjNmYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTNUMTgxNzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE0NTQ2YjA4ODQxMzljZGYzODA5NWEwMDRjMmRmZGQ3MjM3YTM0ZGQ3Zjc4MTY4ODliZjJiMTVkZDc3ODI1NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.koANWSxP_gQHRRhwdGKtjf9WYFFtRvtN8CAaGps6prA)

see my other comments, try fixing LF by extension, example:

```
*.svg text eol=lf
*.php text eol=lf
*.js text eol=lf
*.txt text eol=lf
```
Or turn off autocrlf with git command in project folder:

```
$ git config --global core.autocrlf false
```

**Comment by khiav223577** [comment] 2024-03-15 04:29
@brcontainer Thanks for your help!

The original issue I encounter is: `This diff contains a change in line endings from 'CRLF' to 'LF'.`
It is resolved after I added the following in .gitattributes:

```
*.rb text eol=crlf
```

Note: I keep `autocrlf` being true
```
$ git config --global core.autocrlf
$ true
```

**Comment by brcontainer** [comment] 2024-03-15 18:56
> @brcontainer Thanks for your help!
> 
> The original issue I encounter is: `This diff contains a change in line endings from 'CRLF' to 'LF'.` It is resolved after I added the following in .gitattributes:
> 
> ```
> *.rb text eol=crlf
> ```
> 
> Note: I keep `autocrlf` being true
> 
> ```
> $ git config --global core.autocrlf
> $ true
> ```

It's a matter of necessity, I don't use CRLF (carriage return + line feed) as a line break, because most languages (programming, markup and style) perfectly understand only LF (line feed), besides most editors modern text (or complete IDEs) work with either CR, LF or CRLF and even allow you to configure the line wrapping style per file with the ".editconfig" file so that when opening the file, Enter works according to your preference.

Note that your previous problem was being caused by _not specifying the extension_, so I suggested "eol=lf" in the comment because it is the most common, but of course it was just an example, you can apply "eol=crlf" or not specify it and let core.auto do the work, follow the documentation:

https://git-scm.com/docs/gitattributes#_eol

**Comment by brcontainer** [comment] 2024-03-15 19:15
> both of these happening in the same project. I had 12 or more files to commit. the first time 4 files were warned like this #3841 (comment). then I changed the `.gitattributes` file like this.
> 
> ```
> * text=auto
> * text eol=lf
> ```
> 
> after that change, the first warned files problems were solved(4 files). all of the other files were warned like this #3841 (comment) (rest of 8 files). 😕

Adjust the EOL by extension, each project is different, there is no way to suggest something that works universally, but the general rule is to set the EOL only for specific files needed.

I personally prefer to turn off core.autocrlf because my projects are operating system independent, and even for pure text files, not related to programming, I always use LF. But this is a matter of necessity, so manually configuring type by type is the best solution and only configure files that are actually script or pure text.

So here's an example:

``` none
*.svg text eol=lf
*.html text eol=lf
*.text text eol=lf
*.php text eol=lf
*.js text eol=lf
*.json text eol=lf
```

DO NOT configure image, video, or other binary files and depending on the type of project, you should not even create anything related to "text eol" in gitattribute, even more so if you use `.editorconfig` (https://editorconfig.org/ suported by SublimeText, VSCode, Github, Gitlab, and more), YOU SHOULD JUST **TURN OFF `core.autocrlf`**.

**Comment by shreekant89** [comment] 2024-05-11 14:45
This is actually difference because of line ending in linux/mac ((LF) character (represented as ‘\n’))
and Windows uses Carriage Return and Line Feed (CRLF) characters (‘\r\n’)
1.run command **git config --list**
2.and see if its having value core.autocrlf=true if its value is false then you can use   command:- git config core.autocrlf true 
3.if still you find issue execute command :- git config core.eol lf
4.if issue is still there then command :- **git add --renormalize .**   
5.if issue still not solved then delete cache git rm --cached  and if still not solved  re-install git
