### ISSUE TITLE
GitHub Desktop doesn't support repositories from SSH servers with password

### ISSUE THREAD

**Issue by ndpetwar** [desktop/desktop#14676] opened 2022-05-25 06:30 UTC
### The problem

My git shell is working well fetching ,pushing ,pulling and doing all other required operations. I am also able to do all operations using eclipse->team in my repository but GitHub desktop showing authentication error. 
these are my logs
2022-05-25T06:16:32.822Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 4 repositories took 2.4s of which 0.0s paused, total 2.4s
2022-05-25T06:23:06.835Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
Permission denied, please try again.
Permission denied, please try again.
git@10.64.28.130: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)

### Release version

3.0.0

### Operating system

windows 10

### Log files

[2022-05-24.desktop.production.log](https://github.com/desktop/desktop/files/8768481/2022-05-24.desktop.production.log)

**Comment by sergiou87** [comment] 2022-05-25 07:50
@ndpetwar I assume this is not a repository hosted on GitHub and it was cloned with SSH, is that right? If so, have you added your SSH key to ssh-agent? Take a look at this docs: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent

**Comment by ndpetwar** [comment] 2022-05-25 07:58
yes sir i have already added ssh key to ssh agent and thats why able to connect to the server repo via git bash  but not with github desktop @sergiou87

**Comment by ndpetwar** [comment] 2022-05-25 08:05
@sergiou87 take a look at the command line results
D:\GSTM_PROJ_NEW\utility-project>git config --list
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager-core
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Nisha Duhan
user.email=_______(edited)
gui.recentrepo=D:/
init.defaultbranch=main
credential.helper=wincred
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.origin.url=git@edited(serverip):/home/GSTM_DATA/utility-project.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
//some more branches information
branch.utility_test.rebase=false
branch.demo_branch.remote=origin
branch.demo_branch.merge=refs/heads/demo_branch
branch.demo_branch.rebase=false

**Comment by sergiou87** [comment] 2022-05-25 08:11
Interesting, are you using ssh agent from PuTTY? It's recommended to use Git for Windows instead.

**Comment by ndpetwar** [comment] 2022-05-25 08:22
no that was windows cmd and not putty (and as project editor we use eclipse and to communicate and get changes from all colleagues we use github desktop) but github desktop suddenly stop working after 19 may altogether and we are getting authentication error on all of our team systems github dektop .

**Comment by ndpetwar** [comment] 2022-05-25 08:25
@sergiou87  can you please resolve the authentication problem ,we are working to resolve it since last week and tried everything but cant get out of it.

**Comment by ndpetwar** [comment] 2022-05-25 08:34
we are just using cmd and git bash to check whether we are able to communicate to repo using these or not. Now as We can perform all the git operation on git bash,cmd and eclipse team so we figured out that this authentication problem is only with github desktop.

**Comment by sergiou87** [comment] 2022-05-25 08:38
We haven't made any changes related to SSH support in a long time, so I'm not entirely sure if this is a GitHub Desktop issue 🤔 

The only change I can think of is when we upgraded Git to v2.35.3 in GitHub Desktop 2.9.15. I can suggest you try an older version of the app **BUT** ⚠️ make sure you back up the apps settings (located in `C:\Users<YourUserName>\AppData\Roaming\GitHub Desktop`) because those might be wiped after downgrading the app ⚠️ 

If you're interested in trying this, you can install this version which is prior to the mentioned Git change: https://centralreleases.blob.core.windows.net/github-desktop/releases/2.9.12-c058bcc5/GitHubDesktopSetup-x64.exe

Please, if you try it, let me know if that version works

**Comment by ndpetwar** [comment] 2022-05-25 08:43
ok i will let you know

**Comment by ndpetwar** [comment] 2022-05-25 09:00
@sergiou87 older version also not works for me the same error continues.
error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
Permission denied, please try again.
Permission denied, please try again.
git@-------serverip-----: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

**Comment by sergiou87** [comment] 2022-05-25 09:02
That version you just tried was released in March 23rd 2022, so I don't think anything changed on GitHub Desktop that caused this problem. Is it possible something changed on your end (either on your machine's setup, network setup, repo's server setup…) on May 19?

**Comment by ndpetwar** [comment] 2022-05-25 09:05
We add a password on our git on our server but github desktop not asking for any password.
i.e  ssh git@serverip cmd ask for password now
Can you tell me some commands that i can run and we can trouble shoot where the error is?

**Comment by sergiou87** [comment] 2022-05-25 09:10
Oh, so you added a password on your server, not on your SSH key? Right now GitHub Desktop supports SSH key with passphrases, but if your server is what requests the password… that's not supported.

Could you paste here the terminal output when git asks you for this password when you use git pull/push/whatever from the command line?

For example, I'd like to see something like this:

```
$ git pull
Enter password for git@serverip:
Pulling objects…
...
```

Knowing the prompt text displayed to you might help me understand the problem better. Thanks!

**Comment by ndpetwar** [comment] 2022-05-25 09:16
D:\GSTM_PROJ_NEW\utility-project>git pull
git@serverip's password:
Already up to date.

D:\GSTM_PROJ_NEW\utility-project>git fetch
git@serverip's password:

D:\GSTM_PROJ_NEW\utility-project>git branch
  Business-Validation-Pradipta
  Nisha/Sourcs-code-error-1
  PRADIPTA-SQL-NAAT
  Release_error_removal1
  copy_of_my_ear
  demo_branch
  dummy_branch_as_master
  feature_error_removal
  heena-errorcode-3
  master
  master-backup
  nitya-sub-branch
  utility_live
* utility_test

D:\GSTM_PROJ_NEW\utility-project>

**Comment by ndpetwar** [comment] 2022-05-25 09:20
![Capture](https://user-images.githubusercontent.com/31008963/170228433-dbe47671-01ec-4d6b-a18a-6963bd47a657.PNG)

**Comment by sergiou87** [comment] 2022-05-25 09:35
Thank you. I can confirm that's definitely not supported and has never been. We can look into adding support for it but I can't promise anything soon, sorry 😕

**Comment by sergiou87** [comment] 2022-05-25 09:40
This is the prompt we should support: https://github.com/PowerShell/openssh-portable/blob/2474b9130b4892ef4992af87ea63dd8dc3911c40/sshconnect2.c#L903-L905

In order to support it, we'd probably need to add another check here looking for `something@something's password: ` https://github.com/desktop/desktop/blob/365d089534585a9e4672525ad6504cf25c0e6607/app/src/lib/trampoline/trampoline-askpass-handler.ts#L95-L102

**Comment by ndpetwar** [comment] 2022-05-25 09:56
But sir all of our team work is on halt pls try to provide the facility asap.
Thanks a lot for giving us your precious time and helping us.Will need your support in future also.
Thank you

**Comment by sergiou87** [comment] 2022-05-25 10:00
I'm looking into it, but even if I fixed the problem now, it'd take a while until it's available in public releases. My best advice if you need to resume your work as soon as possible, is that you revert that requirement of your server of using a password to whatever you had set up before May 19th 😕

**Comment by ndpetwar** [comment] 2022-05-25 10:09
Ok sir thanks a lot

**Comment by ndpetwar** [comment] 2022-05-25 11:11
@sergiou87  well is there some policy in github to reward 😄any user that suggest enhancement or detect bug😀😀

**Comment by sergiou87** [comment] 2022-05-25 13:30
Not for suggestions, sorry 😂  Contributors, however, get a special "thank you" from the team in the next version: 

<img width="919" alt="Screen Shot 2021-05-05 at 12 50 13 PM" src="https://user-images.githubusercontent.com/5091167/117194104-ec8d7c00-ada0-11eb-9109-6071580a283a.png">

Not what you were expecting, but it's what we have, sorry 😂

**Comment by sergiou87** [comment] 2022-05-25 15:35
@ndpetwar I implemented support for this in #14677

Maybe I can make a test build so you can try it out, if that helps.

**Comment by sergiou87** [comment] 2022-05-25 16:37
In case you're interested, you can download the test build from here: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.1-test8-1f117dd6/GitHubDesktopSetup-x64.exe

**Comment by ndpetwar** [comment] 2022-05-26 05:03
ok i will download and try

**Comment by ndpetwar** [comment] 2022-05-26 06:29
finally test version works for us all thanks a lot for your immediate response and support @sergiou87

**Comment by ndpetwar** [comment] 2022-05-26 06:30
can we continue our work on this test version untill it releases publically.

**Comment by sergiou87** [comment] 2022-05-26 08:32
That's great!! I'm very glad it works, thank you for your patience 🙇‍♂️ I will let you know when this is in a public release (presumably, that will be `3.0.2` in a few weeks, or in `3.0.2-beta1` around next week if you don't mind using betas).

**Comment by ndpetwar** [comment] 2022-05-26 08:43
ok @sergiou87  till then we use the test build provided by you ,hope it keep all of our changes and commit intact till we move to the new release.

**Closed as completed** 2022-06-06 14:21 UTC
Labels: enhancement

**Comment by sergiou87** [comment] 2022-06-27 10:16
Hey @ndpetwar 👋 

Just for your information, we just released v3.0.3 which finally includes this change. Thank you for your patience again!!

**Comment by hotmeteor** [comment] 2022-06-28 14:51
I'm getting some new prompt about adding SSH password to access codeserver.dev. Could this be related to this change?
![CleanShot 2022-06-28 at 09 49 50@2x](https://user-images.githubusercontent.com/378585/176210294-cc6be60b-1ac2-45d1-b591-7019d8001070.jpg)

**Comment by sergiou87** [comment] 2022-06-29 07:22
@hotmeteor yes, that's from this change. I see it's not wrapping the text as one would expect, sorry 😓 

Other than that, is there any problem with it?

**Comment by hotmeteor** [comment] 2022-06-29 14:41
@sergiou87 Thanks. I guess I'm not sure what to do with it? I've never authenticated with codeserver.dev before this change. Or maybe I'm misunderstanding?

**Comment by sergiou87** [comment] 2022-06-29 15:54
Weird, if that dialog pops up it means git/ssh is trying to access that server under the hood and needs your password for that. Are you actively using the repository that corresponds to that SSH user/server?

**Comment by hotmeteor** [comment] 2022-06-30 12:36
I'm actively using the repo but I don't know what the `drush.in` domain is for. A quick search pulled up stuff around Drupal, but we're not using Drupal 🤷

**Comment by sergiou87** [comment] 2022-06-30 14:49
Could you run `git remote -v` in your repository and see if there is anything even remotely similar to that `codeserver.dev.…`?

**Comment by hotmeteor** [comment] 2022-06-30 14:50
There's not. And it happens in multiple repos.

**Comment by sergiou87** [comment] 2022-06-30 15:12
It could be another repo from your list that GitHub Desktop is trying to fetch in background. Do any of your repositories come from that server? 🤔

**Comment by cartoonsub** [comment] 2022-07-05 08:40
How do I turn off the constantly appearing window? It prevents me from working
![2022-07-05_11-38-03](https://user-images.githubusercontent.com/30393521/177287474-9b61b4f4-19bb-4bb2-b123-f507dec8556d.png)

**Comment by Orokyunless** [comment] 2022-07-05 09:07
Leave me alone please.

**Comment by hotmeteor** [comment] 2022-07-05 15:01
@cartoonsub Yep, that's my issue as well.

**Comment by sergiou87** [comment] 2022-07-11 08:31
@hotmeteor It could be another repo from your list that GitHub Desktop is trying to fetch in background. Do any of your repositories come from that server? 🤔

@cartoonsub is that prompt for the active repository? Or is it from a different repository in your list?

**Comment by hotmeteor** [comment] 2022-07-12 13:50
@hotmeteor I have searched my entire computer for `drush.in` and there's nothing found, of course it could be some weird remote referenced in another repo. Just weird that it started to show up.

**Comment by sergiou87** [comment] 2022-07-12 14:31
@hotmeteor it's just a new feature for repositories that need it. If GitHub Desktop needs a password to access some repo's remote, it will prompt you for it.

**Comment by cartoonsub** [comment] 2022-07-18 12:37
> 

I use a third-party repository for one project that is not linked to github.

**Comment by sergiou87** [comment] 2022-07-18 14:31
@cartoonsub if that repository is added to the list of repositories in Desktop, or if it's a submodule of the repo you're using, I guess `git` will try to fetch it and for that it will need your SSH credentials. Does that make sense?

**Comment by ndpetwar** [comment] 2023-03-09 07:34
@sergiou87 today i changed my repository password in the server and as earlier in the GitHub desktop i choose remember password option so now it again showing error of authentication and the password entering prompt screen is not appearing .Kindly help once again
