### ISSUE TITLE
Repo creation failure error

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#1750] opened 2017-05-24 18:28 UTC
I created a repo within a repo (on my local) and upon publishing the repo, I got a error message saying "Repo creation failure" and a 422 error as well. Despite this the repo was still pushed to dotcom.

<img width="544" alt="screen shot 2017-05-24 at 2 26 35 pm" src="https://cloud.githubusercontent.com/assets/14828183/26419265/17fa387c-408d-11e7-8833-9016776d8586.png">

0.5.8, OSX 10.11.5

Reproduce:
- File > New Repo, set location within the folder of a current repo
- Try to publish it to dotcom

<img width="1123" alt="screen shot 2017-05-24 at 2 20 21 pm" src="https://cloud.githubusercontent.com/assets/14828183/26419101/92bf5688-408c-11e7-846c-2134b1de9091.png">

Upon a second try, I could not repoduce.

**Comment by joshaber** [comment] 2017-05-26 16:04
@niik saw some of these when he was poking around in Splunk. Maybe related to name encoding?

**Comment by niik** [comment] 2017-05-26 16:26
> @niik saw some of these when he was poking around in Splunk. Maybe related to name encoding?

After having looked at this some more I'm pretty sure this is due to trying to create a private repository on a plan which doesn't allow it and us doing a really poor job of explaining what happened. I can't find a reference to this on the developer docs but we return a 422 when repo plan and visibility aren't compatible.

This should have been fixed with https://github.com/desktop/desktop/pull/1786

![image](https://cloud.githubusercontent.com/assets/634063/26503387/c98a7552-4240-11e7-8afe-709067ebe78c.png)

![image](https://cloud.githubusercontent.com/assets/634063/26503394/cec56f86-4240-11e7-9436-61b42d704652.png)

@tierninho Is it possible that you were using a test account at the time?

**Comment by shiftkey** [comment] 2017-05-26 16:34
It's weird that the error message is different from what we expected in https://github.com/desktop/desktop/pull/1421 🤔

**Comment by tierninho** [comment] 2017-05-26 18:34
@niik Yes, I have been using a test account. As part of the Marketplace testing, my billing and private repo access changed several times, so you suspicion looks to be correct. Will test again if there are fixes coming for the error messaging.

**Comment by niik** [comment] 2017-06-01 16:30
I'm gonna close this out unless there are any objections. @tierninho if you're able to reproduce it with 0.5.9 please reopen.

**Closed by niik** 2017-06-01 16:30 UTC
Labels: bug
