### ISSUE TITLE
categorize repositories

### ISSUE THREAD

**Issue by Harindulk** [desktop/desktop#13653] opened 2022-01-09 09:56 UTC
please add a feature to categorize repositories, it's very useful when we have a lot of repositories and find Want one ✌️
![image](https://user-images.githubusercontent.com/61319844/148668921-05484add-9b54-4bbd-abca-bf41af17bc2b.png)

**Comment by niik** [comment] 2022-01-10 10:14
Thanks for the feedback @Harindulk. This is close to a duplicate of #12254. As we stated there, we don't have any plans to allow for custom group names since we already group repositories by user/org/recent/other. Repository list reordering is something we may look into in the future, and is being tracked in issues like #8183 and #11608. I'm going to close this out since we're tracking repository list improvements in multiple issues.

**Closed as completed by niik** 2022-01-10 10:14 UTC
