### ISSUE TITLE
Problem to upgrade the react version to 16.4

### ISSUE THREAD

**Issue by scottge** [desktop/desktop#6405] opened 2018-12-12 18:25 UTC
**Please describe the problem you think should be solved**
I need to use the react-select component in the desktop app. There is a known type issue which gets fixed in @types/react 16.4.13 JedWatson/react-select#2860
So I have to upgrade the react version in desktop in order to get the fix. I use yarn upgrade to upgrade the react version and @types/react version, but after I do this, I get tons of errors when doing yarn install.

Here are the repo steps:

cd app
yarn upgrade react@16.4.2
cd..
yarn upgrade @types/react@16.4.18
yarn add @types/prop-types --dev
delete both yarn.lock files
yarn
At the end, you will get lots of errors similar to

node_modules/@types/react/index.d.ts:2682:19 - error TS2320: Interface 'IntrinsicClassAttributes<T>' cannot simultaneously extend types 'ClassAttributes<T>' and 'ClassAttributes<T>'.
  Named property 'ref' of types 'ClassAttributes<T>' and 'ClassAttributes<T>' are not identical.

2682         interface IntrinsicClassAttributes<T> extends React.ClassAttributes<T> { }

**Comment by tierninho** [comment] 2018-12-12 18:33
@desktop/engineering any thoughts?

**Comment by outofambit** [comment] 2018-12-12 18:55
Hi @scottge, this looks like a duplicate of #6226. Can we continue the conversation there? it looks like this is the same output from the end of that issue. Please reopen that issue (or comment there) if you're having further problems you'd like help with.

**Closed by outofambit** 2018-12-12 18:55 UTC
