### ISSUE TITLE
original file modification date/time information lost after branch changes

### ISSUE THREAD

**Issue by heradv** [desktop/desktop#9020] opened 2020-01-31 14:21 UTC
### Describe the bug

original file modification date/time information lost after branch changes

### Version & OS

V2.3.1, Windows 10 (1709 build 16299.1087)

### Steps to reproduce the behavior

1. memorize a file's modification date/time what is not present in the other branch
2. change to the other branch
3. file disappears
4. change back to the original branch
5. file appears again but its modification date/time changed to the current time

### Expected behavior

should keep the modification date/time what was before the branch changes.

### Actual behavior

not keeping the modification date/time what was before the branch changes.

**Comment by tierninho** [comment] 2020-01-31 19:23
@heradv Thanks for filing. A few clarifying questions:

- On step 3, you say the file disappears. Un committed files will only follow you to the new branch if you have the option selected in the File > Options > Advanced tab. Otherwise, the files are stashed. What is your selection?
- What are you using to verify the timestamp?

Possible to include your logs from that day? See the Help menu in Desktop.

**Comment by heradv** [comment] 2020-02-01 07:57
I talked about committed files. Every file that not common in both braches "created" (or deleted) at the moment of branch change, so modification date/time also will be the creation date/time.
Its possible to see in any file manager including explorer. There is not file timestamp information in the log, so its irrelevant.

**Comment by tierninho** [comment] 2020-02-03 19:04
I am not sure this is within our control as I do think that Desktop and the OS file managers are in-sync. 

I reproduced this by:
- Make commit on branch A
- Select the file, on in Finder (mac), and "Get Info" to see timestamp. Close both finder and get info windows.
- Go to another branch, wait one minute
- Return to the file, check timestamp again.
- Both Created and Modified dates have changed.

@desktop/core for confirmation.

**Comment by lee-dohm** [comment] 2020-02-03 19:53
I'm not sure I understand the utility of "remembering" the original file modification date. By analogy:

1. If you performed the same operation without source control by deleting the file and then recreating it with the exact same contents, I would expect the observed behavior
1. If you changed the file to have different contents (including being empty but not deleted) then changed it back to the exact same contents as before, I would expect the observed behavior

Additionally:

* No information is lost in this operation because git/Desktop can tell you when the file was last updated in source control even if that information is not reflected in the file system
* The proposed system (git or Desktop updating the file modification date to be the same as it was before the changes) would lose information, namely the fact that the file had been touched twice since

Perhaps I'm not seeing a potential use case though?

**Comment by tierninho** [comment] 2020-02-05 01:33
Thank for the comments @lee-dohm 

@heradv If you have any thoughts on the use cases behind this, please share. Until then, going to close this issue as observed behavior is expected and no info is lost in this operation. Thank you for using Desktop!

**Comment by heradv** [comment] 2020-02-05 12:42
OK, classifying this behaviour as error maybe was too strong. Yes, git/Desktop do the same as if i do everything by hand, but such behaviour is obviously primitive. That is not true that no information is lost, because if there is not any change except branch changes, then why changes anything?
I know git server is not storing file dates, but I think it should. I personally when working in a directory containing many files order them by descending modification time, so every file I just modified is "on hand". When I have to change branches, then this "setup" is ruined. In this situation browsing in git logs to find out what was the original file date is pointless, because in my file manager I can only find them by name when all of its time is the same. And remembering file names is harder (at least for me) than choose them from a smaller set of recently used ones.

**Comment by joliv3ira** [comment] 2021-11-10 23:25
Hello guys! 
I don´t know if I am on the right place, but I really need help with that (Same problem). 
I am working with TOTVS Protheus ERP, that have AdvPL, and it is a "compiled language". 
The problem is, with timestamp changing, we loose reference for files that is allready compiled. 

Then, we can not know if the file on Master Branch (for example) is the same file compiled on the ERP (The ERP assumes the timestamp from the file @ the compilation (when the file is compiled it gets encrypted).

Hope to find a solution for that. 

Sorry about the poor english ;)

Regards, 

Jorge

**Comment by heradv** [comment] 2021-11-24 21:59
@joliv3ira I think we should suggest this as a new choosable feature.

**Comment by tidy-dev** [comment] 2021-11-30 12:06
Sorry as I can see your struggles - not sure how that can be resolved when using version control. But, as communicated in the previous comments, this is a natural consequence of using git/version control and Desktop is simply a graphical interface for that. Thus, this is not something we could set a choosable feature. Thank you for using Desktop!

**Closed by tidy-dev** 2021-11-30 12:06 UTC

**Comment by heradv** [comment] 2021-11-30 19:37
you misunderstood me. i try to suggest that the background system should make able to store original file timestamps THEN implement a switch wich can change between the keeping and not keeping behaviour. but maybe this is not the right forum for this. i start to suspect that you only deal with the UI/desktop version here. but i do not know then where should i suggest this. :(

**Comment by tidy-dev** [comment] 2021-12-01 11:34
@heradv Correct! This issue tracker is just for GitHub Desktop. The underlying version control is [Git.](https://github.com/git/git) You might try there, but even so I am not sure it is possible by the nature of the software (or it would mean a very significant change). Good luck!
