### ISSUE TITLE
Rebasing Staging with master results in a push/pull indicator

### ISSUE THREAD

**Issue by nomanAdfenix** [desktop/desktop#3254] opened 2017-11-07 16:08 UTC
![rebaseissue](https://user-images.githubusercontent.com/28341249/32503313-312ada12-c3dd-11e7-849a-4652791b9922.PNG)

### Description

I have rebased my staging branch with master and after merging the code from master to staging I am facing Pull/Push Origin requests seen in the attached photo.

### Version

**GitHub Desktop version:** [1.0.7]

**OS version:** [windows 10]

### Steps to Reproduce

1. Rebase branch Staging onto master
2. merge master into staging 
3. pull/push staging
4. checkout master
5.you will see push/pull origin request

**Expected behavior:** No push/pull should be seen

**Actual behavior:** looking at the push/pull indicators

**Reproduces how often:** every time I do the rebase

**Comment by shiftkey** [comment] 2017-11-07 21:17
@nomanAdfenix could you open the repository in a shell at the point where you see this count, run these two commands and attach the output?

```
$ git rev-list --left-right --count master..origin/master
$ git status
```

It's hard to say what exactly is happening here, but let's see what Git is reporting about your `master` branch and we can go from there...

**Comment by shiftkey** [comment] 2017-11-07 21:56
> I have rebased my staging branch with master and after merging the code from master to staging I am facing Pull/Push Origin requests seen in the attached photo.

Could you also include the commands you ran here, so it's clear how you're rebasing branches to end up in this state?

**Comment by nomanAdfenix** [comment] 2017-11-08 16:03
I'll do it the next time I do the rebase and update the thread.

**Comment by nomanAdfenix** [comment] 2017-11-09 08:06
![snapshot1](https://user-images.githubusercontent.com/28341249/32594654-2485679a-c52d-11e7-9dff-51c00566e5fd.PNG)
![snapshot2](https://user-images.githubusercontent.com/28341249/32594655-24a41d70-c52d-11e7-94e2-df126c43e7f3.PNG)
![snapshot3](https://user-images.githubusercontent.com/28341249/32594656-24c0eb44-c52d-11e7-864e-29698f7c3881.PNG)

I am attaching the snapShots in order from 1-3. I hope it would help to figure out.

**Comment by shiftkey** [comment] 2017-11-09 20:58
@nomanAdfenix I think the issue is this step:

```
$ git rebase Staging
```

This takes the current ref you are on (in this case, master) and rebases it **on top of `Staging`**, using the common ancestor commit for both refs as the base.

I was able to reproduce this by running a similar command against the `desktop` repo (after resolving many conflicts):

```
$ git checkout master
$ git rebase encodings-as-a-first-class-thing
...
$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 502 and 589 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
```

I believe Desktop is reporting the right numbers here for the branch, because rebasing `master` will rewrite the OIDs for commits which were already pushed, and Git will consider them distinct.

Whenever I'm doing rebasing I usually include both refs, to avoid this sort of confusion:

```
$ git rebase master Staging
```

This will rebase `Staging` on top of `master`, which may have been what you intended to do.

**Comment by nomanAdfenix** [comment] 2017-11-10 13:27
Thanks saved me a ton man. did the $ git rebase master staging thing and it
worked like a charm.

**Closed** 2017-11-10 22:45 UTC
