### ISSUE TITLE
Indication of Changes in Repository Selection Dropdown

### ISSUE THREAD

**Issue by JamesCoyle** [desktop/desktop#3826] opened 2018-01-19 10:58 UTC
### Description

It would be helpful if repositories which have changes were highlighted in the repository selection dropdown. This would help to identify repositories which may require a commit and would aid visual identification of packages the user is currently working on if they have a lot of other repositories cloned locally.

![image](https://user-images.githubusercontent.com/10384436/35147242-cf7df45e-fd05-11e7-9346-4bb263fb583c.png)

### Version

**GitHub Desktop version:** 1.0.12

**Comment by j-f1** [comment] 2018-01-19 11:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2259, which we’re hoping to get to in v1.3. Please follow that issue for further updates.

**Closed** 2018-01-19 15:31 UTC
