### ISSUE TITLE
Months of history missing from GitHub desktop

### ISSUE THREAD

**Issue by kpeterssolid** [desktop/desktop#10114] opened 2020-06-30 17:47 UTC
### Describe the bug

In our private work repository that was imported from a Mercurial repository, all of the history from 2019-08-05 until 2019-11-14 is missing in the GitHub Desktop app, but it's visible and correct on the GitHub site.

### Version & OS

Version: 2.5.3, Windows 10.

### Steps to reproduce the behavior

1. Go to the History tab.
2. Scroll down to Nov 14, 2019.
3. The next entry is from Aug 5, 2019.

### Screenshots

![Github bug 1](https://user-images.githubusercontent.com/2333050/86159168-288fea80-bac7-11ea-8280-e7a9879a86b3.png)
![GitHub bug 2](https://user-images.githubusercontent.com/2333050/86159183-2e85cb80-bac7-11ea-971d-bf78232c06cb.png)

**Comment by tierninho** [comment] 2020-06-30 18:18
@kpeterssolid Thanks for sharing. I do not think we have had a report of this in the past.

Any chance you can share your logs? See them under the Help menu in Desktop.

If the content is too private, look for any errors or failures in the logs and paste them here. Thanks.

**Comment by kpeterssolid** [comment] 2020-06-30 21:05
There's a lot of logs, here are the last 5.  A lot of the errors seem to be related to the internet cutting out sometimes.

[2020-06-25.desktop.production.log](https://github.com/desktop/desktop/files/4854427/2020-06-25.desktop.production.log)
[2020-06-26.desktop.production.log](https://github.com/desktop/desktop/files/4854428/2020-06-26.desktop.production.log)
[2020-06-29.desktop.production.log](https://github.com/desktop/desktop/files/4854429/2020-06-29.desktop.production.log)
[2020-06-30.desktop.production.log](https://github.com/desktop/desktop/files/4854430/2020-06-30.desktop.production.log)
[2020-06-24.desktop.production.log](https://github.com/desktop/desktop/files/4854431/2020-06-24.desktop.production.log)

**Comment by tierninho** [comment] 2020-06-30 21:39
Thank you. Here are some relevant errors:

```
TypeError: Failed to fetch
2020-06-30T15:05:03.277Z - warn: [ui] fetchRepository: an error occurred for 'solid-innovation-systems-inc/sra.com-fusion'
TypeError: Failed to fetch
2020-06-30T15:05:03.366Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sra.com-fusion - kpeterssolid (has token)
2020-06-30T15:05:04.170Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/Solid-Innovation-Systems-Inc/sra.com-fusion.git/': Could not resolve host: github.com
2020-06-30T15:05:04.461Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
```

```
2020-06-29T15:05:12.382Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at Object.t.parseError (file:///C:/Users/strab/AppData/Local/GitHubDesktop/app-2.5.3/resources/app/renderer.js:29:129312)
    at onAutoUpdaterError (file:///C:/Users/strab/AppData/Local/GitHubDesktop/app-2.5.3/resources/app/renderer.js:12:111903)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:1804:29)
    at electron/js2c/renderer_init.js:1603:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1593:7)
    at EventEmitter.emit (events.js:203:13)
    at Object.onMessage (electron/js2c/renderer_init.js:2399:16)
```

```
2020-06-29T15:05:36.995Z - warn: [ui] fetchRepository: an error occurred for 'Solid-Innovation-Systems-Inc/sra.com-server'
TypeError: Failed to fetch
2020-06-29T15:05:36.997Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
TypeError: Failed to fetch
2020-06-29T15:05:36.999Z - warn: [ui] failed fetching open PRs for repository solid-innovation-systems-inc/sra.com-server
TypeError: Failed to fetch
2020-06-29T15:05:36.999Z - error: [ui] Error refreshing pull requests for 'solid-innovation-systems-inc/sra.com-server'
```

These indicate a network issue, which is often caused by a firewall or proxy server interfering with Git. Do you have anything like that?

**Comment by kpeterssolid** [comment] 2020-06-30 21:52
We don't have a proxy server, and we have the usual firewalls (Windows software firewall, plus one on the NAT router), but my internet here does cut out more often than I'd like.

Is there a way to re-synchronize the local GitHub desktop with the github site?

**Comment by tierninho** [comment] 2020-06-30 22:05
You could try turning the firewall off and clone the repo again to see if that works. I am unsure if solely clicking the `fetch` button or using the Repository > Pull option will solve the issue. 

Let us know how it goes.

**Comment by kpeterssolid** [comment] 2020-06-30 22:53
I had done fetches before, and that didn't do anything.  I turned off the firewall, and re-cloned the repo, but the issue remains.  Repository --> Pull doesn't fix it either.

Here's today's log file again, if that helps.
[2020-06-30.desktop.production.log](https://github.com/desktop/desktop/files/4854741/2020-06-30.desktop.production.log)

**Comment by tierninho** [comment] 2020-06-30 23:53
@steveward Any ideas here for resolving this?

**Comment by steveward** [comment] 2020-07-07 21:13
@kpeterssolid do you encounter the `could not resolve host` when attempting Git operations from the command line? Are you running any other security software that could be interfering with connections to GitHub?

**Comment by kpeterssolid** [comment] 2020-07-07 22:00
I don't use the git command line tools very much, but I don't remember seeing any error messages on the command line.  No there aren't any other security tools that would interfere with connections.  I recloned the repository at the request of @tierninho, and there were no errors, but the problem was still there.

**Comment by steveward** [comment] 2020-09-30 17:41
@kpeterssolid can you verify that the commits exist locally by running a command like `git log --pretty --oneline --after="2019-08-05" --before="2019-11-14"`from the command line? That will give you the history for that date range.

**Closed** 2020-10-20 15:01 UTC
Labels: more-info-needed
