### ISSUE TITLE
Github desktop

### ISSUE THREAD

**Issue by khdrvss** [desktop/desktop#17560] opened 2023-10-14 07:00 UTC
### The problem

![image](https://github.com/desktop/desktop/assets/133764568/9fd0c325-d178-4a36-af24-4cf31849962d)
![image](https://github.com/desktop/desktop/assets/133764568/acca276e-b243-4580-b416-1d20cb09277e)
In this image it can be seen the process of signing in to the Github account through default web browser ,however it does nothing the process is endlesss it doesnt open any browsers. My internet connection is good, default browser is set.

### Release version

Version 3.3.3 (x64)

### Operating system

Windows 11 pro

### Screenshots

![image](https://github.com/desktop/desktop/assets/133764568/d59d1f2f-a095-47a8-93cc-645ac42e4d87)

**Comment by tidy-dev** [comment] 2023-10-16 12:27
👋 @khsdevy Sorry for your troubles. This appears to be a duplicate of https://github.com/desktop/desktop/issues/11410. I am going to close it in favor tracking the issue there. 

Unfortunately, we have not been able to replicate and therefore haven't nailed down a reason this sometimes happens; tho, seemingly an environmental factor. 

Some users have been able to resolve theirs by:
- wait a few minutes and click the button in the browser again it works. 
- restarting their machines
- uninstalling and reinstalling GitHub Desktop. 
- fixing where there machine was blocking (antivirus/firewall) the first authenticated network call. 
- closing multiple different browsers that were open.

Hopefully that helps with debugging. If you happen to figure out a reason, please let us know so we can help other users.

**Closed as completed by tidy-dev** 2023-10-16 12:27 UTC
