### ISSUE TITLE
Desktop Client opening wrong repo after cloning  

### ISSUE THREAD

**Issue by breathe67** [desktop/desktop#9605] opened 2020-04-22 22:28 UTC
### Describe the bug

a) on Github, I forked a repo (protobuf) to my own copy C.
b) using Github Desktop I cloned C to my local machine.
c) using Github Desktop I open the repo page in github (ctrl-shift-G), and it takes me to the web URL for the original repo, not my forked copy C.  Additionally, if I "Create Issue on Github" it also goes to the original repo.

Note if I push any changes to C it does show up on github correctly.

### Version & OS

version 2.4.2, on Windows 10

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by tierninho** [comment] 2020-04-22 23:38
Hi @breathe67 , thanks for the issue! This is a duplicate of #9500 so I’m going to close it. I’d love it if you could add some specific feedback there about how you’re using forks and why you’re more interested in viewing your fork than the upstream repo. Thanks!

**Closed by tierninho** 2020-04-22 23:38 UTC

**Comment by breathe67** [comment] 2020-04-23 17:33
Thanks for the reply. In the past I've needed to make small config changes
and alterations to get a 3rd party project to build successfully (e.g.
protobuf has had some compiler & library errors for me) . So I basically
want to import the upstream repo but keep the config changes I make. I need
somewhere to store those changes while being able to easily rebase it to
the upstream repo, and a github fork seemed like a good best way - unless
you know of another ?

Chris

**Comment by breathe67** [comment] 2020-04-23 17:35
sorry- posted that reply on the bug feedback as well.
