### ISSUE TITLE
'History' pane doesn't refresh, even when I've committed changes locally

### ISSUE THREAD

**Issue by MikeyCSharpDude** [desktop/desktop#16185] opened 2023-02-21 13:33 UTC
### The problem

After committing a change and even pushing it to the remote server, the 'History' pane does not show that change, not even after a fetch or pull. I have to close and reopen GitHub Desktop in order to see the change, something I never have to worry about in SourceTree. Also, GitHub Desktop is EXTREMELY SLOW, compared to SourceTree.

### Release version

3.1.7 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Commit a change.
2. Look at the 'History' to see if the change/commit is there. <= It is not.

**Comment by steveward** [comment] 2023-02-21 20:05
@MikeyCSharpDude thanks for the report. Could you upload the log file from GitHub Desktop so that I could get some more information about this issue? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by MikeyCSharpDude** [comment] 2023-02-21 20:13
Hi, Sure, it's attached. Or, should I actually "upload" it somewhere?

Regards,

Michael Gonzalez

**Comment by steveward** [comment] 2023-02-21 21:58
You'll need to attach it to an issue reply since email attachments don't make it through. Thanks.

**Comment by MikeyCSharpDude** [comment] 2023-02-21 22:01
Here are the logs from yesterday, 2/20/23.
[2023-02-20.desktop.production.log](https://github.com/desktop/desktop/files/10798129/2023-02-20.desktop.production.log)

**Comment by steveward** [comment] 2023-02-24 15:06
Thanks, I'm not seeing any specific errors, but there are a few operations that are taking a bit longer than average. Is there anything running on your system that could be interfering with GitHub Desktop? We've seen antivirus software cause slowdowns in operations.

**Comment by MikeyCSharpDude** [comment] 2023-02-24 15:09
> Thanks, I'm not seeing any specific errors, but there are a few operations that are taking a bit longer than average. Is there anything running on your system that could be interfering with GitHub Desktop? We've seen antivirus software cause slowdowns in operations.

I don't so but I'm a software developer with lots of running apps, such as Visual Studio, etc., so, who knows but all other apps seem to be responsive. GitHub Desktop is much slower than SourceTree, btw.

**Comment by steveward** [comment] 2023-03-14 16:47
How large is the repository that you are working with in GitHub Desktop?

**Comment by MikeyCSharpDude** [comment] 2023-03-14 16:50
> How large is the repository that you are working with in GitHub Desktop?

8.82 MB

**Comment by steveward** [comment] 2023-04-19 13:02
@MikeyCSharpDude I'm not seeing anything outside of the normal timing of Git operations in the log file. Do you think you would be able to reproduce this in a short video clip? Are you seeing this History refresh issue in multiple repositories?

**Comment by MikeyCSharpDude** [comment] 2023-04-19 13:16
Github Desktop is just too slow, extremely slow, so I am working with
SourceTree, for now, till those issues get resolved; can't be waiting many
seconds for every operation in the former; will get back to testing it when
I have time...

**Comment by steveward** [comment] 2023-04-19 13:48
I'll close this out then since we have a few other existing issues tracking performance (see https://github.com/desktop/desktop/issues/13586).

**Closed as completed by steveward** 2023-04-19 13:48 UTC
