### ISSUE TITLE
Cannot fetch master after deleting and creating new master 

### ISSUE THREAD

**Issue by NodoFox** [desktop/desktop#6639] opened 2019-01-15 23:43 UTC
## Description

- Deleted a master branch from terminal
- Created a new master from the origin in terminal
- Github desktop has this branch as default, but I can no longer update it. No option to pull or fetch origin. I only see "Publish branch" option

## Version

* GitHub Desktop: Version 1.5.1

* Operating system:
macOS
10.13.6

## Steps to Reproduce
- Deleted a master branch from terminal
- Created a new master from the origin in terminal
- Github desktop has this branch as default, but I can no longer update it. No option to pull or fetch origin. I only see "Publish branch" option

### Expected Behavior

Github desktop should be able to fetch origin and update master.

### Actual Behavior

Unable to fetch origin and update master

**Comment by outofambit** [comment] 2019-01-15 23:48
Hi @NodoFox! Thanks for reaching out. Unfortunately I'm not able to reproduce this following these steps. Could you share the terminal commands you used for steps 1 and 2? I might be doing something slightly different. Thank you!

**Comment by NodoFox** [comment] 2019-01-16 05:06
Hello @outofambit 
Here's the set of screenshots before and after - https://imgur.com/a/zjzRkNv
I was able to reproduce with these steps. 
```
git checkout some_other_branch
git branch -D master
git checkout remotes/origin/master
git checkout -b master
```

You'll see that on github desktop you can no longer update master

**Comment by steveward** [comment] 2019-01-16 14:45
Thanks for those extra details @NodoFox. The issue here is that the new `master` branch is not set up to track the upstream `origin/master` branch. You can run this command to checkout a new branch and track the existing upstream branch:

`$ git checkout -b master --track origin/master`

or you can explicitly set a branch to track an upstream branch with the `git branch` command:

`$ git branch --set-upstream-to=origin/master master`

I hope that helps. I'm going to close this issue out, but please let us know if you have any other questions.

**Closed by steveward** 2019-01-16 14:45 UTC
Labels: more-information-needed
