### ISSUE TITLE
Sublime Text 3 not shown as external editor

### ISSUE THREAD

**Issue by aafulei** [desktop/desktop#13352] opened 2021-11-20 00:40 UTC
### Describe the bug

Cannot detect Sublime Text 3 as the external editor even though it has been installed.

### Version & OS

GitHub Desktop version - Version 2.9.4 (x64)

OS Version - macOS Catalina 10.15.7 (19H1519)

### Steps to reproduce the behavior

1. Go to Preferences > Integrations > External Editor
2. "Sublime Text" does not show up there, even though it has been installed

### Expected behavior

Expect "Sublime Text" to show up there in Preferences > Integrations > External Editor, and expect it to be invoked properly

### Actual behavior

No "Sublime Text" in Preferences > Integrations > External Editor.

### Screenshots

<img width="605" alt=" 2021-11-20 at 8 23 57 AM" src="https://user-images.githubusercontent.com/43313691/142707331-7189c716-8b7c-4fb1-a67c-fae937a551e8.png">

*^ the above screenshot shows that Sublime Text is not listed as the external editor*

<img width="430" alt=" 2021-11-20 at 8 24 05 AM" src="https://user-images.githubusercontent.com/43313691/142707335-da7c7b5e-be0c-4881-8489-68de5595d8ea.png">

*^ the above screenshot shows that Sublime Text has been installed in Applications*

### Logs

```
2021-11-20T00:18:47.854Z - info: [ui] [AppStore] loading 22 repositories from store
2021-11-20T00:18:47.855Z - info: [ui] [AppStore] found account: aafulei (Aaron Fu Lei)
2021-11-20T00:18:47.912Z - info: [ui] [BranchPruner] Last prune took place in 13 hours - skipping
2021-11-20T00:18:48.376Z - info: [ui] launching: 2.9.4 (Mac OS 10.15.7)
2021-11-20T00:18:48.377Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-11-20T00:19:41.176Z - info: [ui] [AppStore] loading 22 repositories from store
2021-11-20T00:19:41.177Z - info: [ui] [AppStore] found account: aafulei (Aaron Fu Lei)
2021-11-20T00:19:41.242Z - info: [ui] [BranchPruner] Last prune took place in 13 hours - skipping
2021-11-20T00:19:41.702Z - info: [ui] launching: 2.9.4 (Mac OS 10.15.7)
2021-11-20T00:19:41.702Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2021-11-20T00:22:12.460Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 21 repositories took 9.0s of which 0.0s paused, total 9.0s
```

### Additional context

The Sublime Text 3 version is the latest build for Version 3, i.e. Version 3.2.2 Build 3211.

It was installed as `/Applications/Sublime Text.app` in the standard way, i.e. drag and drop after clicking the `.dmg` file acquired from the official website.

```sh
$ mdls -name kMDItemCFBundleIdentifier -r /Applications/Sublime\ Text.app
com.sublimetext.3
```

```sh
$ readlink `which subl`
/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl
```

**Comment by steveward** [comment] 2021-11-22 21:55
@aafulei thanks for the report. Have you restarted GitHub Desktop since installing Sublime Text 3 on your machine?

**Comment by aafulei** [comment] 2021-11-23 09:23
> @aafulei thanks for the report. Have you restarted GitHub Desktop since installing Sublime Text 3 on your machine?

@steveward Yes I have. Not only did I restart GitHub Desktop, but also I have restarted Sublime Text 3, and mac as well.

I am a programmer, not in this field though. I am interested in knowing the mechanism that GitHub Desktop identifies which editors are installed in the macOS system. Wondering if you could briefly desribe the general idea so that I may help provide some more information.

One more thing, once I installed both Sublime Text 4 and Sublime Text 3 (which is allowed given proper configuration), but then I removed ST4, and then GitHub Desktop began to believe that there are no Sublime Text edtiors at all on my machine. I reinstalled GitHub Desktop and ST3 later, with restarts, but still doesn't help. GitHub Desktop still can't see that ST3 has been installed.

**Comment by steveward** [comment] 2021-11-23 19:00
@aafulei thanks for the update. I was also able to reproduce this by uninstalling Sublime Text 4 and then installing the latest Sublime Text 3. 

You can read how our editor integration works here:

https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

It is helpful to know that Sublime Text was previously detected -- this looks similar to issues reported in https://github.com/desktop/desktop/issues/13089. In that specific case Sublime Text showed up again after a period of time.  I'll test a few things out to see if I can figure out what's going on here.

**Comment by steveward** [comment] 2022-03-29 15:27
Another issue was opened about this in https://github.com/desktop/desktop/issues/14197 with further details, so I'm going to close this out in favor of that one. @aafulei there's a workaround in #14197 that you could follow to get Sublime Text 3 working.

**Closed as completed by steveward** 2022-03-29 15:27 UTC
Labels: investigation-needed

**Comment by aafulei** [comment] 2022-07-13 05:46
> Another issue was opened about this in #14197 with further details, so I'm going to close this out in favor of that one. @aafulei there's a workaround in #14197 that you could follow to get Sublime Text 3 working.

Thank you @steveward. Just noticed your message and just tried the workaround there, i.e. removing `'com.sublimetext.4'` from `/Applications/GitHub Desktop.app/Contents/Resources/app/renderer.js`. I happily confirm that it works!

**Comment by aafulei** [comment] 2022-08-16 14:10
> > Another issue was opened about this in #14197 with further details, so I'm going to close this out in favor of that one. @aafulei there's a workaround in #14197 that you could follow to get Sublime Text 3 working.
> 
> Thank you @steveward. Just noticed your message and just tried the workaround there, i.e. removing `'com.sublimetext.4'` from `/Applications/GitHub Desktop.app/Contents/Resources/app/renderer.js`. I happily confirm that it works!

Sadly I would like to mention that this fix does not seem to last beyond any upgrade. That is, after an upgrade, the `renderer.js` will be reset and `'com.sublimetext.4'` seems to reappear again 🙀🙀
