### ISSUE TITLE
Icon? issue: fatal: git show-ref: bad ref refs/tags/Icon? (0000000000000000000000000000000000000000)

### ISSUE THREAD

**Issue by grzesir** [desktop/desktop#18160] opened 2024-02-09 01:55 UTC
### The problem

It is EXTREMELY annoying. Every new github repo that I make locally gives me the error `fatal: git show-ref: bad ref refs/tags/Icon? (0000000000000000000000000000000000000000)`. I believe this is because I changed my Macbook to show all hidden files (useful for development). Now every single repo I create has this error popping up non stop and literally makes github desktop unusable. 
I have tried everything: adding to the gut ignore for the project, creating a global git ignore on my computer, and I even created a shell script to delete these from the repo. Nothing works long term. It keep coming back and it makes github desktop unusual. PLEASE FIX THIS!

<img width="1225" alt="Screenshot 2024-02-08 at 8 52 06 PM" src="https://github.com/desktop/desktop/assets/1148971/396c5187-d3b0-4a1a-93e9-8ad114c9d170">

### Release version

3.3.6 x64

### Operating system

MacOS Sonoma 14.2.1

### Steps to reproduce the behavior

1. Create a new repo
2. Never be able to use GitHub desktop because the pop up comes up every 2 seconds

### Log files

[2024-02-09.desktop.production.log](https://github.com/desktop/desktop/files/14216417/2024-02-09.desktop.production.log)

### Screenshots

<img width="1125" alt="Screenshot 2024-02-08 at 8 54 24 PM" src="https://github.com/desktop/desktop/assets/1148971/0d2cdb9c-f4e4-4124-b664-d2dd85a36f6f">

### Additional context

This might be happening on my computer because I made it show all the hidden files using this in terminal:

`defaults write com.apple.Finder AppleShowAllFiles true`

**Comment by steveward** [comment] 2024-02-09 16:30
The bad ref error usually indicates a repository issue. In this case it looks like the tag is causing problems, due to the ? in the file name. Is that possibly a file that got accidentally moved there? I would try deleting that ref in the `.git` directory to see if that resolves things. Let me know if that helps.

**Comment by steveward** [comment] 2024-02-09 16:36
I found a couple of StackOverflow questions that looks related:

https://superuser.com/questions/298785/icon-file-on-os-x-desktop
https://stackoverflow.com/questions/42679090/what-is-an-icon-file

If you delete it does it get recreated? Are you using a file syncing service? A few people have mentioned that potentially causing this as well.

Since this is a system issue I'm going to close this out, as it's not caused by GitHub Desktop, but hopefully that gets you on the right path.

**Closed as completed by steveward** 2024-02-09 16:36 UTC

**Comment by grzesir** [comment] 2024-02-09 17:04
I have deleted it many times, it always comes back. I even created a shell
script to delete it because it comes back so often.

Robert Grzesik 347-635-3416

**Comment by grzesir** [comment] 2024-02-10 02:58
@steveward can we please re-open this issue? It is definitely not resolved, I've tried everything in the SO articles several times and it keeps coming back

**Comment by steveward** [comment] 2024-02-10 03:27
@grzesir this is outside of the scope of support we can provide in our issue tracker since this isn't a specific issue with GitHub Desktop. You may want to reach out to Apple support for assistance to see if they can help with determining why these files are being created on your system.

**Comment by grzesir** [comment] 2024-02-10 21:07
Steve these files are created on every Apple system, it is a standard file
made by macOS. What I did was turn on hidden files on macOS and it started
to cause a problem in GitHub desktop. It is most definitely an issue with
GitHub desktop, not macOS. No other software, including the git command
line tool has an issue with the standard Icon files on macOS, it is a
problem with GitHub desktop.

Robert Grzesik 347-635-3416

**Comment by steveward** [comment] 2024-02-12 18:16
@grzesir what does `git fsck` return from the command line? That should show the repository issues. GitHub Desktop does run some specific commands that could be throwing different errors, but the underlying issue is still with the local repository.

**Comment by grzesir** [comment] 2024-02-13 22:53
This is what git fsck produces. There are clearly many corrupt files.
However, the problem is that when I fix these issues they keep coming back.
I even created a shell script that I have to use on every repo on my entire
computer several times a day. Git does not cause this issue, only GitHub
Desktop creates this issue.

Here's the result of git fsck:

Roberts-MacBook-Pro-2:options_rolling_calls robertgrzesik$ git fsck

bad sha1 file: .git/objects/09/Icon

bad sha1 file: .git/objects/0c/Icon

bad sha1 file: .git/objects/11/Icon

bad sha1 file: .git/objects/12/Icon

bad sha1 file: .git/objects/17/Icon

bad sha1 file: .git/objects/18/Icon

bad sha1 file: .git/objects/28/Icon

bad sha1 file: .git/objects/2a/Icon

bad sha1 file: .git/objects/30/Icon

bad sha1 file: .git/objects/37/Icon

bad sha1 file: .git/objects/46/Icon

bad sha1 file: .git/objects/47/Icon

bad sha1 file: .git/objects/59/Icon

bad sha1 file: .git/objects/5e/Icon

bad sha1 file: .git/objects/61/Icon

bad sha1 file: .git/objects/63/Icon

bad sha1 file: .git/objects/6b/Icon

bad sha1 file: .git/objects/7c/Icon

bad sha1 file: .git/objects/7d/Icon

bad sha1 file: .git/objects/82/Icon

bad sha1 file: .git/objects/87/Icon

bad sha1 file: .git/objects/97/Icon

bad sha1 file: .git/objects/9b/Icon

bad sha1 file: .git/objects/9c/Icon

bad sha1 file: .git/objects/a6/Icon

bad sha1 file: .git/objects/a7/Icon

bad sha1 file: .git/objects/ac/Icon

bad sha1 file: .git/objects/b5/Icon

bad sha1 file: .git/objects/b6/Icon

bad sha1 file: .git/objects/b9/Icon

bad sha1 file: .git/objects/cb/Icon

bad sha1 file: .git/objects/cf/Icon

bad sha1 file: .git/objects/d2/Icon

bad sha1 file: .git/objects/d4/Icon

bad sha1 file: .git/objects/dc/Icon

bad sha1 file: .git/objects/df/Icon

bad sha1 file: .git/objects/e0/Icon

bad sha1 file: .git/objects/e3/Icon

bad sha1 file: .git/objects/e5/Icon

bad sha1 file: .git/objects/e6/Icon

bad sha1 file: .git/objects/ea/Icon

bad sha1 file: .git/objects/f0/Icon

bad sha1 file: .git/objects/f5/Icon

bad sha1 file: .git/objects/fa/Icon

Checking object directories: 100% (256/256), done.

error: refs/Icon?: invalid sha1 pointer
0000000000000000000000000000000000000000

error: refs/heads/Icon?: invalid sha1 pointer
0000000000000000000000000000000000000000

error: refs/remotes/Icon?: invalid sha1 pointer
0000000000000000000000000000000000000000

error: refs/remotes/origin/Icon?: invalid sha1 pointer
0000000000000000000000000000000000000000

error: refs/tags/Icon?: invalid sha1 pointer
0000000000000000000000000000000000000000

error: bad ref for .git/logs/Icon?

error: bad ref for .git/logs/refs/Icon?

error: bad ref for .git/logs/refs/heads/Icon?

error: bad ref for .git/logs/refs/remotes/Icon?

error: bad ref for .git/logs/refs/remotes/origin/Icon?






Here's the shell script I created. It fixes the problem for a few minutes
then the issues comes back again:



# A script to remove bad 'Icon?' files from a git repository

# Steps:
# 1. Run this: chmod +x remove_icons.sh
# 2. Run this: ./remove_icons.sh

#!/bin/bash

# Remove bad sha1 files from .git/objects
find .git/objects -name 'Icon?' -type f -delete

# Remove bad references from .git/refs, .git/logs, and their subdirectories
find .git/refs .git/logs -name 'Icon?' -type f -delete

# Check for consistency in the repository
git fsck --full

# Find and delete any remaining 'Icon?' files in the repository
find . -name 'Icon?' -type f -delete

# Add changes to staging
git add .

# Commit the changes
git commit -m "Removed Icon? files causing issues"







Also my .gitignore contains these lines, which seem to get ignored by
GitHub Desktop:



# Apple Files
Icon*
.DS_Store
.local/**
Icon?
Icon\r





Robert Grzesik
347-635-3416

**Comment by steveward** [comment] 2024-02-23 15:42
@grzesir those files won't be ignored in Git, since they're in your `.git` directory (any files created there won't be tracked). Are you using a file syncing service that could be causing these files to keep coming back? I would recommend asking for assistance at https://discussions.apple.com/community/macos, since this is a macOS issue and not something that is being generated by GitHub Desktop. This is outside of the scope of support we can provide since it's a machine-specific issue and not GitHub Desktop that is generating those files.

**Comment by LockerJ** [comment] 2024-05-09 00:15
This happened to me as well, really bad issue seeing as it cripples the ability to use github. 
Fortunately I was able to isolate the root cause - I had recently backed my github folders up to Google Cloud before this happened, and hadn't done anything else. 
To fix it, I removed those folders from my Google Cloud backup and then deleted all the 'Icon?' hidden files from the directory. 
As soon as I finished both those steps, the errors resolved and haven't returned. 

Frustrating bug because I want to be able to utilize Cloud backups for these folders as a mechanism for keeping up-to-date files on non-technical employees' computers (i.e. who don't use Github).

**Comment by grzesir** [comment] 2024-05-09 04:35
Yes this is how I fixed it as well. Google Cloud syncing was causing the
issue.

Honestly I still think that GitHub desktop should deal with this better,
but removing the folders from google sync fixed the issue.

Robert Grzesik 347-635-3416

**Comment by aleroemer** [comment] 2024-08-20 03:24
Hi! Really struggling with this as well. I am less versed in Git + computing in general. My github folder lives in my Google Drive. If I understand correctly, I should move the folder?

**Comment by steveward** [comment] 2024-08-23 14:53
@aleroemer we recommend moving repositories outside of Google Drive to avoid issues like this.

**Comment by grzesir** [comment] 2024-08-26 00:29
Yes, once I moved everyone out of my Google drive folder the problems went
away

Robert Grzesik 347-635-3416
