### ISSUE TITLE
Error with current index routes back to stashing dialogue

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7502] opened 2019-05-10 01:12 UTC
When you attempt to stash a file(s) that consists of a conflicted file, an error is surfaced asking you to resolved your current index as expected. Upon dismissing it, the stashing dialogue is resurfaced instead of allowing the user to resolve the conflict. A minor annoyance and possible loop for a novice user.

Repro:
- Create conflicted file in the Changes
- Attempt to stash
- Acknowledge index warning

![image](https://user-images.githubusercontent.com/14828183/57496040-aadaa100-726c-11e9-9b04-2992376d0f38.png)

tested in v1.7.0-beta7, mac

**Comment by shiftkey** [comment] 2019-05-10 17:01
@iAmWillShepherd do we have an issue somewhere for "make the app aware of stash conflicts"? I couldn't find one after a scan of the open issues, so I'm not sure where this sits on our roadmap around the stash flow...

**Comment by iAmWillShepherd** [comment] 2019-05-20 15:28
@shiftkey I don't think we have one for this. I can create one. I'm curious what you think we should do with this awareness. I think we should prevent the stash dialog from being show and instead show an error that informs you that you must fix the conflicts or discard the conflicted files first.

cc @billygriffin for thoughts.

**Comment by iAmWillShepherd** [comment] 2019-05-20 15:31
Reproductions of error

**Stashing conflict**
![2019-05-20 10 23 29](https://user-images.githubusercontent.com/1715082/58033374-fb15f680-7ae9-11e9-9c8b-a667917b65d9.gif)

**Merge conflict**
![2019-05-20 10 22 37](https://user-images.githubusercontent.com/1715082/58033410-0f59f380-7aea-11e9-8fa1-852599a5c7d5.gif)

**Rebase conflicts**

We disable the branch selector, so stashing is a non-factor.

**Comment by billygriffin** [comment] 2020-01-16 23:31
Because we haven't seen this pop up organically and it's a bit contrived, I'm going to close it for now.

**Closed by billygriffin** 2020-01-16 23:31 UTC
Labels: bug, epic:stashing
