### ISSUE TITLE
Dark theme for repo chooser

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#5787] opened 2018-09-30 14:34 UTC
Would be great for desktop to support dark mode in mojave. For example, add local project -> choose, and the file chooser is light themed. Such system dialogs should instead support system-wide dark mode.

**Comment by iAmWillShepherd** [comment] 2018-10-01 15:55
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #5037. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-10-01 15:55 UTC
