### ISSUE TITLE
Failure to Push large number of PNG files

### ISSUE THREAD

**Issue by jack-bennett** [desktop/desktop#16116] opened 2023-02-10 22:58 UTC
### The problem

I added ~300 PNG files to my project's assets in Xcode. These included ~50 icon images, plus ~200 of the @2x and @3x files required for different size iPhone screens. There were also another ~100 auxiliary binary files I keep stashed with the project. The Commit worked fine, but the Push to origin shows the double-arrow icon spinning endlessly with no indications of progress. I have allowed it to spin for ~1 hour and then checked on whether any files have made it to the repository -- none have so far as I can tell from a spot check. I also force-quit GitHub Desktop once and tried to Push again with the same result. Been using GitHub Desktop for quite some time with no other issues.

### Release version

3.1.6 (x64)

### Operating system

macOS 12.6.3 (Monterey)

### Steps to reproduce the behavior

1. Add a large number (>300) of image (PNG) files to the assets catalog in an Xcode project.
2. Commit the added files in GitHub Desktop.
3. Push the Commit to origin.

### Log files

[2023-02-10.desktop.production.log](https://github.com/desktop/desktop/files/10711771/2023-02-10.desktop.production.log)

**Comment by jack-bennett** [comment] 2023-02-10 23:09
Since filing the above bug, I force-quit Desktop again, then did another Commit of some additional changes, followed by a Push. All this apparently has worked, with the large number of binary files discussed in the bug report also showing up in the repository. So while the behavior was certainly odd, no damage has been done and given the perhaps unusual circumstances of this problem, I'd give it a low priority -- unless it happens again.

**Comment by steveward** [comment] 2023-02-13 18:53
Thanks for the issue @jack-bennett. We've had similar reports of this, and unfortunately it can be caused by a number of variables. Since we have some existing issues around this (see https://github.com/desktop/desktop/issues/15636) and things are now working for you I'm going to close this out.

**Closed as completed by steveward** 2023-02-13 18:53 UTC

**Comment by jack-bennett** [comment] 2023-02-13 20:34
Thanks for the response. Fine by me to close this if you have an existing issue.  
.................................  Jack Bennett  ***@***.*** ................................. 

    On Monday, February 13, 2023, 10:54:05 AM PST, Steve Ward ***@***.***> wrote:  
 
 


Thanks for the issue @jack-bennett. We've had similar reports of this, and unfortunately it can be caused by a number of variables. Since we have some existing issues around this (see #15636) and things are now working for you I'm going to close this out.
