### ISSUE TITLE
upstream/master is unavailable in list of branches to merge from

### ISSUE THREAD

**Issue by brentonstrine** [desktop/desktop#7927] opened 2019-07-06 16:00 UTC
## Description
As a user, I want to be able to keep my fork up to date with an upstream repository by merging into my branch a branch from upstream. However, in the branch merge menu of GHD, upstream repositories do not show up. 

## Version

* GitHub Desktop: 2.1.0

* Operating system:MacOS 10.14.5 (Mojave)

## Steps to Reproduce
1. Fork a repo
2. Clone it to GitHub Desktop
3. Fetch
4. From the branch menu, select "Choose a branch to merge into **master**" (note that `upstream` is not listed(
![image](https://user-images.githubusercontent.com/1900802/60758442-aae4ec00-9fe4-11e9-9b73-a127c21c701f.png)
5. Attempt to merge from upstream master. It is not available to choose, and does not appear even when searching for `upstream`.
![image](https://user-images.githubusercontent.com/1900802/60758448-c05a1600-9fe4-11e9-9ff0-a6b4a91356b2.png)

### Expected Behavior
Expected to see upstream branches available to merge from.
Here is a video of it working as expected: https://youtu.be/7o9BeepHSws

### Actual Behavior
Only local and origin branches appear, no upstream branches are available. 

## Additional Information
I have noticed that normally this issue is fixed with a fetch. However, there are times when fetching does not solve this problem.

**Comment by steveward** [comment] 2019-07-07 00:28
Thanks for the report @brentonstrine! Would you mind uploading a log file from GitHub Desktop? I'd like to take a closer look at whether or not there's a fetching issue.

Thanks for writing in. Could you send over the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by tierninho** [comment] 2019-07-18 01:13
@brentonstrine I was unable to reproduce this. Please share the logs so we can investigate further.

**Comment by brentonstrine** [comment] 2019-07-18 03:09
So sorry, I haven't seen it happen in quite a while. Trying to get the kids from someone who I know it happened to.

**Comment by tierninho** [comment] 2019-07-22 22:26
I was able to reproduce this issue however I am unsure if it is a bug or by design.

If you add a forked repo, log out, then attempt to fetch the upstream branches will not load. I attempted this with a public repo and public forked repo. 

Once I logged back in and fetched, the upstream branches appeared as expected. 

I suspect this is what happened in your case. Once we get those logs or a confirmation, we can move forward. Thanks.

**Comment by brentonstrine** [comment] 2019-07-23 02:13
Just had something similar happen, though not exactly the same. 

Upstream currently has 3 branches, `master`, `prod` and `refcode1.0`. However the third one does not show up in the list of upstream branches:
![image](https://user-images.githubusercontent.com/1900802/61677478-d26ad280-accd-11e9-89bd-9af8924119e2.png)

![image](https://user-images.githubusercontent.com/1900802/61677487-db5ba400-accd-11e9-90a0-59bfedbcd4fa.png)

Logs:



[2019-07-06.desktop.production.log](https://github.com/desktop/desktop/files/3419850/2019-07-06.desktop.production.log)
[2019-07-08.desktop.production.log](https://github.com/desktop/desktop/files/3419851/2019-07-08.desktop.production.log)
[2019-07-09.desktop.production.log](https://github.com/desktop/desktop/files/3419852/2019-07-09.desktop.production.log)
[2019-07-10.desktop.production.log](https://github.com/desktop/desktop/files/3419853/2019-07-10.desktop.production.log)
[2019-07-11.desktop.production.log](https://github.com/desktop/desktop/files/3419854/2019-07-11.desktop.production.log)
[2019-07-12.desktop.production.log](https://github.com/desktop/desktop/files/3419855/2019-07-12.desktop.production.log)
[2019-07-13.desktop.production.log](https://github.com/desktop/desktop/files/3419856/2019-07-13.desktop.production.log)
[2019-07-14.desktop.production.log](https://github.com/desktop/desktop/files/3419857/2019-07-14.desktop.production.log)
[2019-07-17.desktop.production.log](https://github.com/desktop/desktop/files/3419858/2019-07-17.desktop.production.log)
[2019-07-18.desktop.production.log](https://github.com/desktop/desktop/files/3419859/2019-07-18.desktop.production.log)
[2019-07-19.desktop.production.log](https://github.com/desktop/desktop/files/3419860/2019-07-19.desktop.production.log)
[2019-07-20.desktop.production.log](https://github.com/desktop/desktop/files/3419861/2019-07-20.desktop.production.log)
[2019-07-22.desktop.production.log](https://github.com/desktop/desktop/files/3419862/2019-07-22.desktop.production.log)
[2019-07-23.desktop.production.log](https://github.com/desktop/desktop/files/3419863/2019-07-23.desktop.production.log)

**Comment by shiftkey** [comment] 2019-07-23 11:53
@tierninho @brentonstrine some thoughts on this based on the recent testing:

> If you add a forked repo, log out, then attempt to fetch the upstream branches will not load. I attempted this with a public repo and public forked repo.

If you're not logged in at the time, I think this changes the behaviour of our `GitStore.loadRemotes` function, which updates the current and upstream remotes in the repository:

https://github.com/desktop/desktop/blob/fcbb95d9df8741ab48f0dd06625c8204aa743e7c/app/src/lib/stores/git-store.ts#L1096-L1100

If the repository isn't detected as a GitHub repository (not clear from the test cases, but it should revert to the "computer" icon in the repository list) that might be a clue.

> Once I logged back in and fetched, the upstream branches appeared as expected.

Hearing that this then works after the user has signed in again makes me wonder if this is related to the behaviour inside `GitStore.fetch`, where we only fetch from the remotes we know are good. That's where we'll look for this `upstreamRemote` and include that:

https://github.com/desktop/desktop/blob/fcbb95d9df8741ab48f0dd06625c8204aa743e7c/app/src/lib/stores/git-store.ts#L801-L804

@brentonstrine the most recent log file `2019-07-23.desktop.production.log` shows there are some networking issues with the fetch that we hide from the user if it wasn't a manual fetch - do you see these errors when performing a manual fetch on the fork?

```
2019-07-23T00:18:35.499Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/brentonstrine/refcode.org.git/': Could not resolve host: github.com

2019-07-23T00:18:35.535Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/team-refcode/refcode.org.git/': Could not resolve host: github.com
```

Fetches consistently failing would explain why new refs are not displayed in Desktop, which feels like what was happening yesterday.

**Comment by brentonstrine** [comment] 2019-07-23 16:18
@shiftkey I figured out what had happened yesterday. It was actually just that I didn't understand what was happening because the UI is confusing. (Also, I think this is all new behavior? Or somehow I missed that you can do this.)

- I had clicked on the `upstream/refcode1.0` link in the branch dropdown. I didn't realize that this creates a local branch named `refcode1.0` that is tracking upstream. I didn't know that GHD had the ability to track upstream at all!
- So when I saw `refcode1.0` as a local branch, I thought it was tracking my fork. 
- When you're looking to pull in an upstream branch which you have a local copy of, there's no way to see (from the list--look at my screenshot) that it is one of your local branches. The local branches tracking upstream don't have any kind of indicator to tell you whether they're tracking origin or upstream.

I think there are some other things about the UI that need to be cleaned up as well but those were the big ones.

**Comment by shiftkey** [comment] 2019-07-23 18:53
@brentonstrine that's some helpful context - thanks! 

> I had clicked on the `upstream/refcode1.0` link in the branch dropdown. I didn't realize that this creates a local branch named `refcode1.0` that is tracking upstream.

Tracking branches are a part of Git that we leverage a lot in the app - publishing a new branch or checking out an existing branch will also set the tracking branch, so that things like the ahead/behind count work "for free" in the app.

> * So when I saw `refcode1.0` as a local branch, I thought it was tracking my fork.
> ...
> The local branches tracking upstream don't have any kind of indicator to tell you whether they're tracking origin or upstream.

Yeah, this is the tricky part. When you have a tracking branch set, we display the remote name in the button in the header to help orient you:

<img width="741" src="https://user-images.githubusercontent.com/359239/61738473-c67c2080-ad60-11e9-8c24-bc77621b70b7.png">

This means we're going to push/pull changes with `origin` (which is on my fork) which is expected. I can think of some situations where this isn't helpful, the big one being when you don't have `push` permissions to the upstream repository, so you need to push to your fork and open a PR.

Currently you'd need to do something like this:

 - `git branch --unset-upstream [branch]` (unset current tracking branch)
 - `git push -u origin [branch]` (create branch on fork, set as tracking branch)

> I think there are some other things about the UI that need to be cleaned up as well but those were the big ones.

I'd love some input from @desktop/product about this area based on what we've covered, about whether we can make it clearer from the list which branches are tracking an upstream branch. Knowing in the list that `refcode1.0` is tracking `upstream/refcode1.0` might have helped avoid some of this confusion in the first place.

**Comment by brentonstrine** [comment] 2019-07-24 23:46
@shiftkey Thanks. I've figured out a lot more about how these features work but there are still some major limitations for our workflow. 

1. Our team is exclusively using GHD, not the CLI at all (yet--they are students new to computers).
2. Pushing to upstream is blocked.

These limitations have the resulting problem:

- Our developers aren't able to make a local branch that they can merge into `upstream/refcode1.0`.
- - They only have `master` locally, and merging in from `upstream/refcode1.0` doesn't work because `master` commits end up polluting the branch.
- The only way they _can_ accomplish this (that I know of) is to first click on `upstream/refcode1.0` and create the local branch tracking upstream. 
 - - However, they can't push to upstream because pushing is blocked, and they can't change which remote the branch is tracking without leaving GHD and going into the CLI.
 - - Thus they need to make a branch off of the local `refcode1.0` tracking upstream, and that branch will naturally track origin. 

Takeaways:

 - In the list of branches, I wish there was a way to see which remote each branch is tracking at a glance without having to go into each branch
 - I wish there was a way to change which remote a branch tracked from within GHD.
 - I wish there was a way to create a new branch directly from a chosen upstream branch in GHD (e.g. `git checkout -b myBranch upstream/refcode1.0`

**Comment by tidy-dev** [comment] 2024-09-16 19:16
After reading all the comments here, I believe 
1) The original issue of "upstream/master is unavailable in the list" is untrue (unless you are logged out). 
2) The issue was opened due to confusion about whether a branch is tracking origin or tracking upstream since it is not clear from the branch list until you check out a branch.

Since the original issue does not exist. I am going to close this. But, I am going to add a comment to https://github.com/desktop/desktop/issues/8509 to track as another improvement to make the Forks experience better.

**Closed** 2024-09-19 13:48 UTC
Labels: design-input-needed
