### ISSUE TITLE
Pull option does not appear when "Pull first before pushing" error is thrown

### ISSUE THREAD

**Issue by NudeNULL** [desktop/desktop#5451] opened 2018-08-22 10:27 UTC
## Description

On MacOS I create a commit, also on Windows machine for the same repository from another account was pushed another commit before, when I press Push on MacOS machine is gave me the error about "Pull first before pushing...blabla" but no Pull is displayed...so i am stuck.

## Version

* GitHub Desktop:1.3.3

* Operating system:
macOS High Sierra 10.13.6

## Steps to Reproduce

In our case it was reproduced like this:
1. From windows machine push to master a commit
2. From macOS machine commit to master
3. From macOS machine try to Push (Github Desktop is showing 1 Push)
4. Appears an error something like - "You have to pull before pushing"
5. Github Desktop continues to show that there is no Pull...
### Expected Behavior
After the step 4 usually GitHub Desktop loads the commit and updates UI -> so we see that there is a Pull, and after pulling we can Push.

### Actual Behavior

In the UI I always see that I have 1 Push and 0 Pulls and whatever I tried(restart Github Desktop, try Pushing again, adding one more commit to push), it doesn't help, It simply don't load the commit that had to be pulled before pushing.

**Comment by steveward** [comment] 2018-08-23 15:56
Thanks for the report @NudeNULL. I was able to reproduce this behavior as well. I did some digging and found this was previously reported in https://github.com/desktop/desktop/issues/2431 and then fixed in https://github.com/desktop/desktop/pull/2445, so this appears to be a regression. 

As a workaround you should be able to pull down that change by going to the file menu in GitHub Desktop and selecting `Repository` > `Pull`.

**Comment by shiftkey** [comment] 2018-08-25 17:30
@steveward #5451 is this issue. Can you clarify which issue this is a duplicate of, as I couldn't spot a different open issue that looks like this one.

**Comment by steveward** [comment] 2018-08-28 18:14
@shiftkey I meant to link to https://github.com/desktop/desktop/issues/3766. Clipboards are hard.

**Comment by steveward** [comment] 2018-08-28 18:19
Actually taking a deeper look at #3766 it's the same error message, but different repro steps, so I'm going to reopen this issue. Sorry for the noise.

**Comment by cheshire137** [comment] 2018-10-18 18:57
I experienced this as well in 1.4.3-beta2 in macOS.

**Closed** 2019-02-22 18:24 UTC
Labels: bug, priority-3
