### ISSUE TITLE
Github desktop show files changed at local when pulled. 

### ISSUE THREAD

**Issue by tushar-solace** [desktop/desktop#5482] opened 2018-08-27 06:57 UTC
When we make a pull, sometimes it shows some list of files which is not actually changed by me on my machine. 

Please let us know how we can avoid getting those files listed in change list.

**Comment by steveward** [comment] 2018-08-27 15:09
Thanks for the report @tushar-solace. This is often caused by line ending or file mode changes -- is that possibly what could be happening in this situation? Are you seeing the entire file as changed in the diff view?

If it does look like you are dealing with line endings issues I would recommend reading our [guide with some recommendations](https://help.github.com/articles/dealing-with-line-endings/) for handling line endings.

**Comment by niik** [comment] 2018-09-03 14:10
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2018-09-03 14:10 UTC
Labels: more-information-needed
