### ISSUE TITLE
Unable to differentiate a repo cloned twice

### ISSUE THREAD

**Issue by vasanthmurari** [desktop/desktop#8648] opened 2019-11-17 07:16 UTC
### Describe the feature or problem you’d like to solve
If user clones the same repo twice, everytime, the user has to place the mouse on top of the repo to find which folder it belongs to in order to find the details of repository and the UI doesn't feel very user friendly. 

### Proposed solution
Would suggest to give the repo name in the list as the folder name for easier identification.

How will it benefit Desktop and its users?
By doing this, user can clone the same repository multiple times and avoid the confusion.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.
![image](https://user-images.githubusercontent.com/28107660/69004371-127e4280-08c7-11ea-94c8-f5d2678648f0.png)

**Comment by tierninho** [comment] 2019-11-18 18:35
@vasanthmurari thanks for filing this issue. If you hover over the repo names, you will be able to see the paths.

Regardless, this request sounds like a duplicate of https://github.com/desktop/desktop/issues/8175 and https://github.com/desktop/desktop/issues/8175, both which were included in https://github.com/desktop/desktop/issues/6460. See https://github.com/desktop/desktop/issues/8158#issuecomment-524644986 specifically for the current thinking on this. Thanks!

**Closed by tierninho** 2019-11-18 18:35 UTC
