### ISSUE TITLE
Suggestion for improving 'clone repository' dialog

### ISSUE THREAD

**Issue by kres0345** [desktop/desktop#7684] opened 2019-06-04 19:30 UTC
### A thing that has bugged me for a while now

When I go to a repository and choose "Open in desktop", then it opens a dialog in Github desktop, now here's my issue: Pressing the enter key DOES NOT accept the cloning prompt. You would assume it just confirms the prompt because the button is blue. 

Let me be honest, I don't even recognize where pressing enter actually does lead to, I just know accidentally pressing it requires me to re-launch the cloning prompt.

P.s. I am on Windows 10, not sure whether it matters 🤷‍♂

**Comment by tierninho** [comment] 2019-06-04 19:56
@kres0345 Thank you for the report and sorry for the frustrating experience. 

I assume you are seeing this window (below) and when you click `clone` it does not work.
![Screen Shot 2019-06-04 at 9 50 20 AM](https://user-images.githubusercontent.com/14828183/58909235-529d9000-86ae-11e9-9b19-7f6685130b48.png)

Some info we need:
- Please share your logs so we can get a better indication of what could be happening.  Click the `Help` menu > `Show Logs in Explorer` 
- What version of the Desktop are you using? Click the `Help` menu > `About GitHub Desktop`  
- Possible to share the repo you are trying to clone?

**Comment by kres0345** [comment] 2019-06-04 20:02
@tierninho Negative, I have exactly zero issues with cloning.  I am just complaining about that when you get that exact prompt and press the ENTER Key, it doesn't _click_ the blue button

**Comment by kres0345** [comment] 2019-06-04 20:02
NO, I accidentally closed it

**Comment by tierninho** [comment] 2019-06-04 20:22
Not 100% sure that I understand. Possible to show photos or clarify the steps that you want changed?

My reproductions steps:
- go to a repo on Github and click `Clone` button and then `Open in Desktop`
- In browser prompt, click `Open Desktop`
- Desktop opens and the clone modal is shown
- Click `Clone` button

**Comment by kres0345** [comment] 2019-06-04 20:28
Could I maybe get you to carefully read the original post again? First of all I want you to understand that this is NOT a bug, I am trying to tell you that my UX wasn't optimal.

I hope you understand :D

**Comment by iAmWillShepherd** [comment] 2019-06-05 14:56
@kres0345 I've just tried reproducing this issue and am not getting the same behavior as you. Are there any additional steps I may be missing?

**macOS**
![2019-06-05 09 42 38](https://user-images.githubusercontent.com/1715082/58966391-d96a6f80-8777-11e9-88be-e00bcc4a5556.gif)

**Windows**
![2019-06-05 09 48 13](https://user-images.githubusercontent.com/1715082/58966386-d66f7f00-8777-11e9-9d5b-54dc9ace713d.gif)

**Steps I took to reproduce**
1. Open _Clone_ dialog
1. Entered a URL for repo
1. Entered location to clone to
1. Hit <kbd>Enter</kbd>
1. Clone took place*

Based off your repro steps, I expected the last step to result in the clone dialog being dismissed such that no clone takes place.

Also, it would be super helpful if you included the content that was asked for in https://github.com/desktop/desktop/issues/7684#issuecomment-498819228.

**Comment by kres0345** [comment] 2019-06-05 16:07
![github](https://user-images.githubusercontent.com/17174333/58971737-58819700-87bc-11e9-98d6-6c6b02bc4cfe.gif)

What I did was simply click clone button, then ENTER button, no selecting, no clicking in the GitHub Desktop. If I was going to click the URL field first, then I could simply click the clone button instead, but I am a heavy keyboard user

**Comment by kres0345** [comment] 2019-06-05 16:08
My steps

1. Hit clone button in repo with mouse.
2. Press Enter key.

**Comment by tierninho** [comment] 2019-06-06 18:24
closing as this is a dupe of https://github.com/desktop/desktop/issues/5234

**Closed by tierninho** 2019-06-06 18:24 UTC
Labels: investigation-needed, more-information-needed
