### ISSUE TITLE
New GitHub Desktop continuously issues a error message

### ISSUE THREAD

**Issue by zstadler** [desktop/desktop#3078] opened 2017-10-17 15:28 UTC
### Description
I've just installed the new GitHub Desktop after using the old GitHub Desktop for years.

This error message 

![image](https://user-images.githubusercontent.com/1304610/31673142-21f10d36-b367-11e7-953a-530dbdc6bdb5.png)

is received after adding an existing repository and whenever I select the repository or change between "Changes" and "History" views

* It is not clear where this option can be set.
* It is also not clear why the new GitHub Desktop issues an error where the old GitHub Desktop works perfectly.

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** Microsoft Windows [Version 10.0.16299.19]

### Steps to Reproduce

1. Clone or download https://github.com/IsraelHikingMap/Map
1. Open the repository in the new GitHub Desktop
1. The error message will appear.

**Expected behavior:** No error should be produced, just like the old GitHub Desktop.
In case of a real issue, a proper error message should explain how and where to make the requested change in the settings

**Actual behavior:**  The above error message was received.

**Reproduces how often:** 100% of the time

### Logs

There is nothing I could see in the log file:

```
2017-10-17T14:10:57.217Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-17T14:10:58.837Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-17T14:10:58.848Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-17T14:10:59.589Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-17T14:10:59.717Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--squirrel-firstrun"}
2017-10-17T14:10:59.954Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-17T14:11:00.644Z - info: [ui] launching: 1.0.4 (Windows 10.0.16299)
2017-10-17T14:11:00.711Z - info: [ui] [Welcome] no sign in step found. ignoring...
2017-10-17T14:11:01.269Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.283s)
2017-10-17T14:39:10.056Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2017-10-17T14:39:17.944Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2017-10-17T14:39:23.073Z - info: [ui] Opt out reported.
2017-10-17T14:40:29.008Z - info: [ui] [AppStore] adding repository at F:\Users\Steed\Documents\GitHub\IsraelHikingMap\Map to store
2017-10-17T14:40:36.473Z - info: [ui] Executing getChangedFiles: git log d7a11a7c3222ad16bd812372a8cfc4225c6d0fb3 -C -M -m -1 --first-parent --name-status --format=format: -z -- (took 1.351s)
2017-10-17T14:40:37.601Z - info: [ui] Executing getCommitDiff: git log d7a11a7c3222ad16bd812372a8cfc4225c6d0fb3 -m -1 --first-parent --patch-with-raw -z --no-color -- Rules/IsraelHiking.mrules (took 1.126s)
2017-10-17T14:41:44.284Z - info: [ui] [AppStore] adding account zstadler (null) to store
2017-10-17T14:44:12.970Z - info: [ui] [AppStore] loading 0 repositories from store
2017-10-17T14:44:12.974Z - info: [ui] [AppStore] found account: zstadler (null)
2017-10-17T14:44:14.691Z - info: [ui] launching: 1.0.4 (Windows 10.0.16299)
2017-10-17T14:44:37.199Z - info: [ui] [AppStore] adding repository at F:\Users\Steed\Documents\GitHub\IsraelHikingMap\Map to store
2017-10-17T14:44:49.326Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: Map - zstadler (has token)
2017-10-17T14:47:39.142Z - info: [ui] [AppStore] loading 1 repositories from store
2017-10-17T14:47:39.145Z - info: [ui] [AppStore] found account: zstadler (null)
2017-10-17T14:47:40.897Z - info: [ui] launching: 1.0.4 (Windows 10.0.16299)
2017-10-17T14:48:58.045Z - info: [ui] Executing getRemotes: git remote -v (took 1.132s)
2017-10-17T14:48:58.046Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.119s)
2017-10-17T14:48:58.047Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.129s)
2017-10-17T14:48:58.226Z - info: [ui] Executing getRemotes: git remote -v (took 1.302s)
2017-10-17T14:48:58.593Z - info: [ui] Executing getRemotes: git remote -v (took 1.085s)
2017-10-17T14:48:58.593Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 1.082s)
2017-10-17T14:49:01.799Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.683s)
2017-10-17T14:51:36.476Z - info: [ui] [AppStore] adding repository at F:\Users\Steed\Documents\GitHub\IsraelHikingMap\Site to store
2017-10-17T14:51:41.304Z - info: [ui] Executing isUsingLFS: git lfs track (took 4.787s)
2017-10-17T14:51:44.449Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 3.132s)
2017-10-17T14:51:45.580Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 4.263s)
2017-10-17T14:51:53.019Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 11.706s)
2017-10-17T14:51:58.705Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 5.523s)
2017-10-17T14:57:03.083Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.345s)
```

#### Additional Information

None

**Comment by shiftkey** [comment] 2017-10-17 22:40
@zstadler we've been tracking this for a while in #2449 but reproducing it has been less successful. 

> is received after adding an existing repository and whenever I select the repository or change between "Changes" and "History" views

I wasn't able to trigger this from a fresh clone and switching between changes and history, so maybe I'm missing some steps.

Could you help me clarify:

 - do you have a lot of working directory changes in the repository?
 - which branch are you on when you switch between Changes and History?

**Comment by zstadler** [comment] 2017-10-18 06:39
To your questions:
- There is a huge amount of files in ignored directories of the repository. This could be a reason you were not able to reproduce the issue.
- I'm working on the master branch

Interestingly, GitHub Desktop seems to break before getting enough information on the repository's status. For example, when switching to "History" view, the error happens during the "Refreshing Repository" stage.

![image](https://user-images.githubusercontent.com/1304610/31703971-cfe346cc-b3e7-11e7-84c9-2cbaecfa90a0.png)

After the refresh fails, GitHub Desktop shows this status:

![image](https://user-images.githubusercontent.com/1304610/31704028-20743c72-b3e8-11e7-80af-63732254c537.png)

**Comment by tierninho** [comment] 2017-10-19 12:45
I can reproduce this error anytime, but in a slightly different manner. Just clone a directory that is not a git repo, like the default Music or Movies folder on a mac. 

The `The output from the command could not fit into the allocated stdout buffer. Set options.maxBuffer to a larger value than 10485760 bytes` error will pop up like 8x, and the console logs with show an API 404 while trying to fetch an random old, deleted repo "loco-repo":

<img width="893" alt="screen shot 2017-10-19 at 1 41 45 pm" src="https://user-images.githubusercontent.com/14828183/31771282-6d373d0c-b4d3-11e7-85e9-f714ce3b45dc.png">

**Comment by zstadler** [comment] 2017-10-19 18:54
Thank you @tierninho !

It looks like this is exactly the cause of the issue I have. 

By mistake, the repository contained a large folder with lots of "new" files. Once I delete the directory, the problem is gone.  

Command-line `git status` had no problem dealing with the repository.

**Comment by shiftkey** [comment] 2017-10-20 00:00
@tierninho @zstadler thanks for the repro steps!

**Comment by shiftkey** [comment] 2017-10-31 01:33
@tierninho actually, this bit of the repro isn't clear to me:

> Just clone a directory that is not a git repo, like the default Music or Movies folder on a mac.

How are you getting this problem folder the app? It's not clear how I should get the app into this state.

Here's what I've tried:

 - **File** | **Clone Repository** -> **URL** -> specify path like `/Users/shiftkey/Desktop/photos` -> clone errors in a different way

![](https://user-images.githubusercontent.com/359239/32203350-e073e268-be36-11e7-88c3-91d4f6e7c856.png)

 - Drag and drop uninitialized repository onto window -> add repository view tells you to create new repository (which seems like a different flow)

![](https://user-images.githubusercontent.com/359239/32203482-96b2b5c2-be37-11e7-9adf-c6addbce1800.png)

**Comment by tierninho** [comment] 2017-10-31 08:22
@shiftkey All I did was chose `Add Local Repository` and then select the default "Movies" folder (for example).

**Comment by shiftkey** [comment] 2017-10-31 22:38
@tierninho so it's got a `.git` folder created underneath? 

```shellsesssion
$ ls -a ~/Movies
$RECYCLE.BIN   ..             .gitattributes desktop.ini
.              .git           .localized
```

And if I probe this directory, how many files are there?

```shellsession
$ cd ~/Movies
$ find . -type f | grep -v ".git" | wc -l
       4
````

**Comment by tierninho** [comment] 2017-11-01 10:09
@shiftkey  yes, there is `.git` folder underneath and results are:

```shellsession
$ ls -a ~/Movies
$RECYCLE.BIN/ ./            ../           .localized    ppp/

$ cd ~/Movies
$ find . -type f | grep -v ".git" | wc -l
       3
```

**Comment by joshaber** [comment] 2017-11-13 19:34
At any rate, this looks like a duplicate of https://github.com/desktop/desktop/issues/2449.

**Closed by joshaber** 2017-11-13 19:34 UTC
Labels: bug, needs-reproduction
