### ISSUE TITLE
Add editor support for VSCodium

### ISSUE THREAD

**Issue by jebjordan** [desktop/desktop#10446] opened 2020-08-25 22:59 UTC
### Describe the feature or problem you’d like to solve

A clear and concise description of what the feature or problem is.
I cannot select VSCodium as my editor even though I have it installed.
Can we not simply let the user select an executable to open the things in?

### Proposed solution

Put an option to simply browse for an executable to attempt to open the things in.

How will it benefit Desktop and its users?
more fine control, not being limited.

**Comment by tierninho** [comment] 2020-08-25 23:50
@jebjordan Thanks for the request. We do not code the integrations with each editor ourselves as it mean little room for development on features. Please see this document for directions on our to support VSCodium: 

https://github.com/desktop/desktop/blob/1de8d45fc6dc3da6b7099c68f0d4a97c311bf972/docs/technical/editor-integration.md

Labeling this issue as `help-wanted` in case others would like to contribute.

**Comment by niik** [comment] 2020-08-26 07:26
Hi @jebjordan. Support for VSCodium was added in https://github.com/desktop/desktop/pull/8163 and this is the first report we've gotten that it's not working. What OS are you on and what version of VSCodium are you using?

Cc @Rexogamer

**Comment by niik** [comment] 2020-09-02 16:08
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2020-09-02 16:08 UTC
Labels: help wanted, integrations

**Comment by KallePM** [comment] 2020-12-17 21:10
The problem is that for VSCodium `isExpectedInstallation` checks the installation with this: 
`return displayName === 'Visual Source Codium' && publisher === 'VSCodium'` ([here](https://github.com/desktop/desktop/blob/7a7388edd069cc8e97ec6d3cdbe4d2747af5fbc4/app/src/lib/editors/win32.ts#L424))

To fix this, change the line mentioned above to:
```
return (
        displayName.startsWith('VSCodium') &&
        publisher === 'Microsoft Corporation'
      )
```
This will check for the correct values and fix the issue of VSCodium not showing up as an editor.

**Comment by Rexogamer** [comment] 2020-12-17 21:14
This is a pretty simple fix (although it seems a bit weird that Microsoft is still considered the publisher?), although I unfortunately wouldn't be able to test this currently. However, since it's one line (and seemingly you've tested this locally) do you wanna take this one Kalle?

**Comment by mrrezaie** [comment] 2022-11-18 11:45
Hi, 

In my case (Github Desktop 3.1.2 x64), there are two issues:

1.  the key doesn't match
https://github.com/desktop/desktop/blob/da1b41b9c83acba02b4d5cbf795d3d18d0f6595c/app/src/lib/editors/win32.ts#L213
the latest version (1.73.1.22314) key: `{88DA3577-054F-4CA1-8122-7D820494CFFB}_is1`

2. the `publisher` still doesn't match
https://github.com/desktop/desktop/blob/da1b41b9c83acba02b4d5cbf795d3d18d0f6595c/app/src/lib/editors/win32.ts#L223
the latest version (1.73.1.22314) publisher: `VSCodium`

Temporary fix:
Create a sudo key:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{D77B7E06-80BA-4137-BCF4-654B95CCEBC5}_is1]
"InstallLocation"="F:\\VSCodium\\"
"DisplayName"="VSCodium"
"Publisher"="Microsoft Corporation"
```

Result:
![image](https://user-images.githubusercontent.com/38867713/202697326-9f9679c5-e056-47d4-9023-834df851099d.png)
