### ISSUE TITLE
Can't right-click on the border between items in file list

### ISSUE THREAD

**Issue by niik** [desktop/desktop#4471] opened 2018-04-19 13:41 UTC
Copied from @shiftkey's comment at https://github.com/desktop/desktop/pull/4188/files#r182525383. Related to multiple selection in the file list.

Repro steps:

 1. Select a sequence of files
 2. Right-click on the border between two files

<img width="568" src="https://user-images.githubusercontent.com/359239/38950645-c9073878-430b-11e8-9a97-b78217d63dc4.png">

Expected behaviour: context menu appears
Actual behaviour: nothing happens

I think this is due to the `div` inside the `ChangedFile` component having significant margin that ignores events (i.e. you need to click inside this space to trigger the context menu):

<img width="767" src="https://user-images.githubusercontent.com/359239/38950711-01108602-430c-11e8-87db-e12c8468826b.png">

**Comment by jsunsawyer** [comment] 2018-06-21 20:36
For me, the un-clickable area (for right click) is not just the border, but a small sliver at the top of each item, and from the baseline of each items text to the bottom.

This happens when multiple files are selected (via shift click or cmd + a) or when no files or a single file is selected.

**Comment by billygriffin** [comment] 2019-03-15 23:47
This seems to be working now for me, and may have been fixed in @JQuinnie's PR. @tierninho Would you mind verifying?

**Comment by tierninho** [comment] 2019-03-16 00:40
I can verify that you **cannot** open the right-click menu by clicking on the sliver. 

I do not think a user should be allowed to click the sliver as @JQuinnie's PR was adequate, and that a user might accidentally change the wrong file.

**Comment by billygriffin** [comment] 2019-03-16 03:34
Thanks! I tend to agree @tierninho even though I can’t reproduce the behavior you’re seeing. I must be clicking oh so very slightly on one side or another. I’m going to close this and we can reopen if it comes up from users having problems with it.

**Closed by billygriffin** 2019-03-16 03:34 UTC
Labels: bug, help wanted, priority-3

**Comment by jsunsawyer** [comment] 2019-03-17 00:44
@billygriffin If I remember correctly, for me, it was much more than the slight border at the time. It was more like the bar that should be clickable was not totally clickable, and has since been resolved.

**Comment by billygriffin** [comment] 2019-03-17 22:46
Great! Thanks for the additional context @jsunsawyer, and glad to hear it’s good to go from your perspective now.
