### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by camillej413** [desktop/desktop#6138] opened 2018-11-08 22:47 UTC
I'm getting an error when trying to clone a repository from github desktop. When trying to clone a repository the following error pops up
...
fatal: unable to access 'https://github.xyz.com/myuser/infra-core.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

The log file contains
2018-11-08T22:24:35.175Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://github.xyz.com/myuser/infra-core.git C:\Users\myuser\OneDrive - myuser Production\GitRepositories\infr-core\` exited with an unexpected code: 128.
Cloning into 'C:\Users\myuser\OneDrive - myuser Production\GitRepositories\infr-core'...
fatal: unable to access 'https://github.xyz.com/myuser/infra-core.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

Any help would be appreciated.

**Comment by steveward** [comment] 2018-11-09 02:48
Thanks for the report @camillej413. Could you run the following command from the command line and let me know the output?

`openssl s_client -connect <github.your_enterprise_url.com>:443`

That command should hopefully give some more useful output about the SSL error. If you need to keep the output private you can email it to support@github.com. Just mention GitHub Desktop and it will get routed to me.

**Comment by say25** [comment] 2018-11-09 22:44
This is just a guess from my personal work experiences. 

1. Do you have a password on your SSH key? This will cause it to fail.
2. Do you have SSO for GitHub (I am assuming enterprise given you are hiding some of the repo url details) if so try cloning with a SSH key without a password

**Comment by billygriffin** [comment] 2018-11-14 02:39
@camillej413 👋 Were you successful in resolving this or able to try out @say25's suggestion?

**Comment by camillej413** [comment] 2018-11-14 04:41
I do not have any passwords or pass phrase on my SSH key. Still failing with the error mentioned above.

**Comment by billygriffin** [comment] 2018-11-14 13:55
@camillej413 Thanks for the followup. Have you tried cloning from the command line? If you do that do you experience the same error, or is it exclusive to cloning from Desktop?

Also, what version of GitHub Desktop are you using, and what OS version?

**Comment by camillej413** [comment] 2018-11-14 15:00
I am using GitHub Desktop 1.4.3 on Windows 10 version 1709. If I run git clone from the command line I get the same error message.

**Comment by shiftkey** [comment] 2018-11-21 13:05
> If I run git clone from the command line I get the same error message.

This to me suggests the issue isn't specific to GitHub Desktop. There's a mention of `Protocol : TLSv1` that suggests the right cipher isn't being chosen (GitHub.com deprecated support for protocols older than `TLSv1.2` for security reasons, but I'm not sure whether GitHub Enterprise has the same restrictions).

**Comment by tierninho** [comment] 2018-11-30 22:08
@camillej413 Hope this was resolved with the upgrade to `TLSv1.2`. 

As we haven't heard back from you on this, please let us know if you need further help and we will reopen this issue. Thank you!

**Closed by tierninho** 2018-11-30 22:08 UTC
Labels: more-information-needed
