### ISSUE TITLE
"View on Github" sends to the source of the forked repos and not the forked repos himself

### ISSUE THREAD

**Issue by cookiesicharp** [desktop/desktop#9535] opened 2020-04-16 09:44 UTC
### Describe the bug

The option `View on Github` under the tab `Repository` in the menu, sends to the repos source where the current repos has been forked, and not to the currrent repos.

### Version & OS

Github: V 2.4.1
OS: Windows 10

### Steps to reproduce the behavior

1. Clone a forked repository
1. Click on `View on Github` in the menu.
1. See error

### Expected behavior

The current repos should be opened on github.com

### Actual behavior

The source repos, where the current repos has been forked, is opened on github.com

**Comment by billygriffin** [comment] 2020-04-16 13:52
Hi @cookiesicharp, thanks for the issue! This is a duplicate of #9500 so I’m going to close it. I’d love it if you had more specific feedback there about how you’re using forks and why you’re more interested in viewing your fork than the upstream repo. Thanks!

**Closed** 2020-04-16 13:52 UTC
