### ISSUE TITLE
switching branch triggers an error

### ISSUE THREAD

**Issue by leonsegal** [desktop/desktop#4938] opened 2018-06-14 09:18 UTC
Every time I switch to another branch using 'cmd + b' within a local repo, I get the following error modal:

```
A lock file already exists in the repository, which blocks this operation from completing.
```

I am using a mbp with high sierra 10.13.5 and github desktop 1.2.3

The error can be dismissed without consequence, I just thought you might want to know about it.

The error does not appear when changing branches with point and click in the menus.

I have looked this error up and various sources suggest creating a lock file, then deleting it, but this did not fix the error.

Leon

**Comment by steveward** [comment] 2018-06-14 15:49
Thanks for opening this @leonsegal. Could you upload a log file so we can take a closer look at what the issue might be?

macOS logs location: `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`

You can also access the log files by going to the file menu in GitHub Desktop and selecting `Help` > `Show Logs in Finder`. Please upload a log file from a day where you experienced this error.

**Comment by leonsegal** [comment] 2018-06-14 15:52
Log:
```
2018-06-14T15:51:00.018Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: brand-iq - leonsegal (has token)
2018-06-14T15:51:00.019Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: brand-iq - leonsegal (has token)
2018-06-14T15:51:00.048Z - error: [ui] `git -c credential.helper= checkout --progress master --` exited with an unexpected code: 128.
fatal: Unable to create '/Users/leon/Sites/brand-iq/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

(The error was parsed as 34: A lock file already exists in the repository, which blocks this operation from completing.)
```

**Comment by leonsegal** [comment] 2018-06-15 16:29
No, this is the weird thing (and why I posted it).

I do use phpstorm, which has git integration, but this a new bug since a recent update.

I will investigate if it is phpstorm causing the error.

**Comment by shiftkey** [comment] 2018-07-06 19:18
> Every time I switch to another branch using 'cmd + b' within a local repo, I get the following error modal:

This seems to be something fairly easy to reproduce, particularly if it's happening without WebStorm running.

**Comment by leonsegal** [comment] 2018-07-09 07:38
I am new to this - did you want me to reproduce it? 

Should I take a screen shot?

**Comment by paulrehkugler** [comment] 2018-08-08 16:01
I also get this error frequently when clicking on the “open this in GitHub Desktop” link, when switching branches locally works just fine. Here’s the relevant log:

```
2018-08-08T15:56:58.790Z - error: [ui] `git -c credential.helper= checkout --progress **redacted** --` exited with an unexpected code: 128.
fatal: Unable to create '/Users/rehkugler/Documents/Development/**redacted**/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

(The error was parsed as 34: A lock file already exists in the repository, which blocks this operation from completing.)
```

I’m unsure if this is related, but the error dialog also appears twice (i.e. when I click “Close” it immediately reappears. Clicking “Close” on the second dialog closes the error permanently)

**Comment by shiftkey** [comment] 2018-08-08 18:04
Thanks for the details everyone. I've been able to reproduce this, and I'm going to see if we can work this into a future update.

**Comment by ssowens** [comment] 2018-08-08 18:06
Hi, I am getting the same error also as described above. I will attach a picture of the Github desktop version 
<img width="453" alt="github version" src="https://user-images.githubusercontent.com/3893230/43855642-45541508-9b14-11e8-8c51-1cc0797cc691.png">
that I'm running and I am running MacOS High Sierra Version 10.13.5

**Comment by shiftkey** [comment] 2018-08-10 13:45
I've been able to reproduce this consistently by checking out a PR in the PR list on `1.3.2-beta1` on macOS - whether it's a PR from a local branch or a fork.

I've not been able to reproduce this in development mode yet (so I can debug it better) or reproduce it on `master`. When I do encounter this, it seems like the checkout doesn't complete and I need to do it again (and I can trigger it multiple times 😞).

For anyone else who has encountered this, can you share the steps you performed to trigger this? I'd like to confirm they're similar to mine while I try and get a more detailed repro together.

**Comment by shiftkey** [comment] 2018-08-10 15:00
I've opened #5368 to address the original reported steps, which I believe also addressed the issue I was seeing. I'd love to hear any different repro steps from others, but if that's the only common steps this should be fixed in `1.3.3`.

**Comment by shiftkey** [comment] 2018-08-10 15:09
> I also get this error frequently when clicking on the “open this in GitHub Desktop” link

I'll see if I can reproduce this one - it's a different code path to the one I've fixed in #5368

**Comment by amrita-griffin** [comment] 2018-08-10 16:50
@shiftkey I am getting this error as well. I use GitHub Desktop and had to rename a repository, but I was able to add in changes right after that, so I don't think that's the issue. 
Another issue I had, and am adding it though I don't think it's related, was that GitHub desktop couldn't locate my project and I manually mapped it to my local folder. Not sure why that happened.

After that, made a few changes, and when I tried to commit a subset of changes using Github Destop, I get the exact same message: 
``` 
A lock file already exists in the repository, which blocks this operation from completing.
```

 If it helps, I'm on a different branch, and needed to switch between branches and that's when this message shows up. I am back to my original  branch that I was initially at, excluded a few files intended for my other branch, and it still throws the error message and doesn't allow me to push. 

Next, I went to the command prompt and tried to, at a minimum atleast stash my changes via git directly. That also threw me a different message: 
```
fatal: Unable to create 'M:/GitHub/repository-name/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Cannot save the current index state
```

**Comment by shiftkey** [comment] 2018-08-12 19:37
I've dropped the proposed PR #5368 from the next release because I found another place that has the same issue with keyboard navigation and the <kbd>Enter</kbd> key, and I need some context: https://github.com/desktop/desktop/issues/5344#issuecomment-412365757

But once we resolve that it should be an easy fix to get out the door.

**Comment by shiftkey** [comment] 2018-11-09 14:12
I believe this will be resolved with #5952 which enables `--no-optional-locks` for all users and will be available with 1.5.0 next week.

If someone is still able to trigger this on that version, I'd love an updated log or set of reproduction steps.

**Closed by shiftkey** 2018-11-09 14:12 UTC
Labels: bug, priority-2

**Comment by wanda-madikana-sage** [comment] 2021-05-19 19:54
Make sure your application is not running

**Comment by leonsegal** [comment] 2021-08-10 06:13
> Make sure your application is not running

Sorry, which application do you mean? l think this issue is closed now.

**Comment by ashpimm88** [comment] 2022-09-27 14:51
Hi I not long ago started using this and I have been making a heap of change to our project an now when I go to commit it says the same message about a lock file already existing. I don't even know what that is lol any help please?!

**Comment by LesnierM** [comment] 2023-01-10 22:17
I have the same error.

**Comment by ghero56** [comment] 2024-11-18 23:17
Me too

**Comment by aqibcyb12** [comment] 2025-01-23 12:52
goto the folder .git in your explorer , a file name index.lock is available just delete and commit again , cheers folk😍
