### ISSUE TITLE
TypeError: Cannot read property 'screen' of undefined

### ISSUE THREAD

**Issue by lawlmart** [desktop/desktop#1564] opened 2017-05-17 16:36 UTC
![image](https://cloud.githubusercontent.com/assets/10986838/26165307/76a2de28-3afd-11e7-8f7a-846e024699f1.png)

**Comment by joshaber** [comment] 2017-05-17 18:03
That stack trace looks like #1538.

Are you connected to any external monitors? Anything funny about your setup?

**Comment by lawlmart** [comment] 2017-05-17 18:14
Nope

**Comment by shiftkey** [comment] 2017-05-18 01:26
First line of the stack trace maps to this:

```js
var B=h.app||h.remote.app,H=h.screen||h.remote.screen,Y=100...
```

This looks like the internals of [`electron-window-state`](https://github.com/mawie81/electron-window-state/blob/master/index.js#L10-L11):

```js
  var app = electron.app || electron.remote.app;
  var screen = electron.screen || electron.remote.screen;
```

And we're already calling this problem out on our side when [initializing](https://github.com/desktop/desktop/blob/master/app/src/main-process/app-window.ts#L29) the `AppWindow`:

```ts
    if (!windowStateKeeper) {
      // `electron-window-state` requires Electron's `screen` module, which can
      // only be required after the app has emitted `ready`. So require it
      // lazily.
      windowStateKeeper = require('electron-window-state')
    }
```

Gonna dig into the Electron JS side and see if I can wrap my head around why `screen` might be undefined despite us waiting until the app is ready.

cc @desktop/electron for input on troubleshooting further

**Comment by tierninho** [comment] 2017-05-18 13:43
Got same error while re-launching the app with a new build (v0.5.4), but I prematurely hit the dock icon to launch it again instead of waiting for the app to launch automatically. Closed it and clicked it again and it opened fine.

<img width="745" alt="screen shot 2017-05-18 at 9 32 49 am" src="https://cloud.githubusercontent.com/assets/14828183/26204903/3d17d0b2-3bae-11e7-960d-b28a7488506f.png">

OSX 10.11.5

**Comment by lawlmart** [comment] 2017-05-18 15:13
Feels like I did the same thing, that's probably the trick.

**Comment by shiftkey** [comment] 2017-05-18 22:08
@tierninho that's really interesting. I'll see if i can trip it in a similar way.

**Comment by jessereitsma** [comment] 2017-05-22 09:16
I have the same issue on v0.5.5

I have resolved it by closing the older / non beta Github Desktop that I had been using before.
After I quit that process, I could restart Github Desktop Beta succesfully. 
After that, I was unable to reproduce it.
Even when Github Desktop (The non beta) is open, the beta still starts normally.

**Comment by joshaber** [comment] 2017-05-22 20:58
_snagging this from @shiftkey :hurtrealbad:_

**Closed** 2017-05-23 16:55 UTC
Labels: bug, macOS, needs-reproduction

**Comment by joshaber** [comment] 2017-05-23 18:34
0.5.7 was just released with, we believe, a fix for this issue. Please let us know if you're still seeing it after updating!
