### ISSUE TITLE
UI obliterated and dev tools opened when audio file dropped onto UI

### ISSUE THREAD

**Issue by kethinov** [desktop/desktop#6498] opened 2018-12-27 16:55 UTC
## Description
If you drag an audio file (and presumably other types of media) into the UI, the UI is replaced irrevocably with the Chromium media player UI and the dev tools are opened. You have to quit the app and reopen it to reset state.

## Version
1.5.1
* Operating system: macOS 10.14.2

## Steps to Reproduce
1. Open app
2. Drag a media file into UI (I used a m4a but probably other stuff will reproduce this as well)

### Expected Behavior
App should ignore the drag/drop event as there is nothing useful to do with this kind of file. (I dragged it over the app by accident.)

### Actual Behavior
UI is replaced irrevocably with the Chromium media player UI and the dev tools are opened. You have to quit the app and reopen it to reset state.

![screen shot 2018-12-27 at 11 45 52 am](https://user-images.githubusercontent.com/419567/50487950-33e3f080-09ce-11e9-815c-5bb7f06b37ff.png)

**Comment by shiftkey** [comment] 2018-12-27 18:57
@kethinov thanks for the report!

I've been trying to reproduce this with an MP3 file but instead of seeing that UI I see it shows the "Add Local Repository" dialog (but blocks because it correctly detects that this isn't a folder):

<img width="986" alt="screen shot 2018-12-27 at 2 54 18 pm" src="https://user-images.githubusercontent.com/359239/50491163-5b938280-09e7-11e9-9a8f-63aee67ebfdd.png">

Am I missing something with those repro steps?

The logic for this area is managed here - it's pretty primitive, and poking at the contents of `e.dataTransfer.files` might be worth exploring to see if we can warn about dropping files onto the app:

https://github.com/desktop/desktop/blob/40cd77e3e29a9ebc5770502e9240069eef6018db/app/src/ui/app.tsx#L650-L675

**Comment by kethinov** [comment] 2018-12-27 19:06
Weird. I can't reproduce it now either. Every time I try to drag a file or a group of files onto any spot in the app I just get various dialogs (the correct dialogs).

**Comment by kethinov** [comment] 2018-12-27 19:08
I wonder if it's a race condition in Electron in which that event wasn't caught in time before the native Chromium behavior took over. At the time my CPU was under heavier load. Best guess I have.

**Comment by tierninho** [comment] 2019-01-10 22:34
Cannot reproduce either. Closing for now, but happy to reopen if this surfaces again.

**Closed by tierninho** 2019-01-10 22:34 UTC
Labels: more-information-needed
