### ISSUE TITLE
Github Desktop window stuck off the screen

### ISSUE THREAD

**Issue by thenninger** [desktop/desktop#3877] opened 2018-01-29 13:40 UTC
When using a secondary monitor, it's possible that the application window will be "lost" off of the primary screen after disconnecting the secondary while PC is in sleep mode.

**GitHub Desktop version:** 1.0.12

**OS version:** 10.0.16299.192

### Steps to Reproduce

1. Using a secondary monitor, move the Github window to that secondary monitor.
2. Put computer to sleep - in my case close laptop lid.
3. Unplug monitor
4. Wake up PC (open lid)
5. Login to PC if applicable
6. Try to restore the Github window. The window will be stuck off the screen.

**Expected behavior:** The application window, when restored or made active, will appear on the primary monitor and be visible.

**Actual behavior:** The window is stuck in the location on the, now unplugged, secondary monitor.

**Reproduces how often:** 100%

**Comment by iAmWillShepherd** [comment] 2018-01-31 20:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of 2107. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-01-31 20:15 UTC
