### ISSUE TITLE
All file modes changed after commit

### ISSUE THREAD

**Issue by binarynoise** [desktop/desktop#8806] opened 2019-12-17 18:56 UTC
### Describe the bug
GitHub Desktop messes up with file attributes.

### Version & OS

Version 2.2.4
Win 10 home 64bit build 1903

### Steps to reproduce the behavior

open existing repo in GHD, commit something

### Expected behavior
no files on disk get changed

### Actual behavior

every file has this diff:
```diff
diff --git a/someFile b/someFile
old mode 100755
new mode 100644
```

### Additional context
I use git via cygwin -> should GHD be using the tools in %PATH instead of the bundeled?

**Comment by binarynoise** [comment] 2019-12-17 18:57
and how to revert the file attributes

**Comment by outofambit** [comment] 2019-12-17 19:08
Hi @binarynoise, thanks for reaching out! This is likely an issue outside of GitHub Desktop, but I'd like to be sure. Do you see similar behavior when committing from the git CLI directly? For example if you edit a file that hasn't had its permissions already changed, open the same repo in a terminal and run `git status -vv` do you see output similar to this?

```shellsession
$ git status -vv   
On branch permissions-test

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package.json

--------------------------------------------------
Changes not staged for commit:
diff --git i/package.json w/package.json
old mode 100755
new mode 100644
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by binarynoise** [comment] 2019-12-17 19:17
Where can I find that permissions-test branch/repo?

And I don't understand "a file that hasn't had its permissions already changed".
None of the files had explicit permissions set. I work on Windows so these permissions dont apply anyway. I just created the files and added content. Nothing else

Despite that I used IntelliJ IDEAs git plugin for a year now and did not have such issues. Now I also downloaded GHD and did a commit with it and then the issue appeared

**Comment by binarynoise** [comment] 2019-12-17 19:26
It might also be an Issue between the two git versions (the bundeled and the cygwin git)

**Comment by binarynoise** [comment] 2020-01-16 17:39
@outofambit Anything new?

**Comment by steveward** [comment] 2020-01-28 19:23
@binarynoise this is caused by Cygwin -- the [`core.filemode` Git documentation](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefileMode) actually mentions it directly:

>A repository, however, may be on a filesystem that handles the filemode correctly, and this variable is set to true when created, but later may be made accessible from another environment that loses the filemode (e.g. exporting ext4 via CIFS mount, visiting a Cygwin created repository with Git for Windows or Eclipse). In such a case it may be necessary to set this variable to false.

Using `core.filemode = false` is a good way to mitigate this issue, since GitHub Desktop uses Git for Windows. Since this isn't a specific issue with GitHub Desktop I am going to close this out.

**Closed by steveward** 2020-01-28 19:23 UTC
Labels: more-info-needed, support
