### ISSUE TITLE
clone of specific repository fails at 15%

### ISSUE THREAD

**Issue by wind-soft** [desktop/desktop#3695] opened 2017-12-28 07:57 UTC
Description
每次克隆到百分之十五就不动了。
Version
GitHub Desktop version: 1.0.11
OS version: Windows 10 10.0.16299.125
Steps to Reproduce
1.打开https://github.com/mrdoob/three.js，点击clone，open in desktop
2.克隆到15%就卡住了。
3.一直等下去，最后显示失败。
Expected behavior: 完整将整个项目克隆到本地。
Actual behavior: 每次克隆到15%就卡住，无法继续克隆了。
Reproduces how often: 100%
Additional Information
无论是下载zip还是克隆到本地，都无法正常获取整个项目。
希望至少为zip下载支持断点续传，否则中国区用户很堪忧。

**Comment by iAmWillShepherd** [comment] 2017-12-28 13:47
@wind-soft, thanks for taking the time to open an issue. Would it be possible for you to translate your issue into English? I'm doubtful anyone on the team can read Mandarin or Cantonese and I'm not too good at reading passed grade school level.

I'm going to close for now.

**Comment by j-f1** [comment] 2017-12-28 17:35
Google Translate says:

---

Each cloning to fifteen percent will not move.
Description
Each cloning to fifteen percent will not move.
Version
GitHub Desktop version: 1.0.11
OS version: Windows 10 10.0.16299.125
Steps to Reproduce
1. Open https://github.com/mrdoob/three.js, click clone, open in desktop
Cloned to 15% stuck.
3. Wait until the last failure
Expected behavior: Clone the entire project locally.
Actual behavior: Each cloned to 15% stuck, can not continue to clone.
Reproduces how often: 100%
Additional Information
Whether it is to download zip or clone to the local, can not get the entire project normally.
Hope that at least for the zip download support resuming, or users in China is very worrying.

**Comment by shiftkey** [comment] 2017-12-28 22:08
@wind-soft Could you also attach any log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This may provide some additional information to help troubleshoot.

**Comment by wind-soft** [comment] 2017-12-30 13:21
[2017-12-28.desktop.production.log](https://github.com/desktop/desktop/files/1594406/2017-12-28.desktop.production.log)

**Comment by wind-soft** [comment] 2017-12-30 13:23
Sorry for response late. It is not easy to find this page again. Also there was no message left for my account. Here is the log.

**Comment by wind-soft** [comment] 2017-12-30 14:56
Description
Once click"clone", it can only be proceeded to 15% and then stops.
Version
GitHub Desktop version: 1.0.11
OS version: Windows 10 10.0.16299.125
Steps to Reproduce
1. Go to webpage https://github.com/mrdoob/three.js，click "clone"，"open in desktop".
2. Github Desktop begins to clone the project and stops receiving at 15%。
3. Wait for a long time and it will tell you "failed" at last。
Expected behavior: Clone the project to my computer。
Actual behavior: It will be stopped at 15% no matter which project I cloned.
Reproduces how often: 100%

**Comment by gengjiawen** [comment] 2017-12-31 02:48
looks like this is a big repo, and the network speed is not poor. Maybe this is due to gfw.
```
Receiving objects:  15% (24044/158176), 53.84 MiB | 13.00 KiB/s   
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: RPC failed; curl 56 Send failure: Connection was reset

(The error was parsed as 4: The remote disconnected. Check your Internet connection and try again.)
```

**Comment by wind-soft** [comment] 2017-12-31 04:51
My network is not bad. Let me show you the report of speed test.
![u](https://user-images.githubusercontent.com/24189622/34459356-3a57f7ac-ee29-11e7-8c2f-a2b0387371a8.png)

**Comment by gengjiawen** [comment] 2017-12-31 04:59
I mean the connection to `github.com`. You can try `git clone https://github.com/mrdoob/three.js` in cmd and see the result.

**Comment by wind-soft** [comment] 2017-12-31 05:01
@shiftkey @iAmWillShepherd Do you have any idea?

**Comment by wind-soft** [comment] 2017-12-31 05:13
I tried on my Mac. It stops, too.
@gengjiawen

**Comment by gengjiawen** [comment] 2017-12-31 05:16
Have tried this in terminal. I still think it's because gfw. Try to use proxy on your mac if you are using something like `shadowsocks-ng`.

**Comment by shiftkey** [comment] 2017-12-31 10:38
> I tried on my Mac. It stops, too.

This sounds like a networking issue if it's occurring on different OSes. If you're testing the clone from the command line (which GitHub Desktop is doing under the hood for both macOS and Windows) you can add extra diagnostics by providing additional environment variables:

```
$  GIT_TRACE=1 GIT_CURL_VERBOSE=1 GIT_TRACE_PACKET=1 git clone https://github.com/mrdoob/three.js
```

Maybe this will help understand why `curl` is failing at that specific point...

**Comment by wind-soft** [comment] 2018-01-10 08:08
@shiftkey Sorry for response late.
terminal also told me "EOF", same as the desktop software.

**Comment by shiftkey** [comment] 2018-01-10 11:51
> terminal also told me "EOF", same as the desktop software.

So this isn't tied to Desktop, but probably  to something in `curl`.

This error is the best clue to figure out what to try next:

```
error: RPC failed; curl 56 Send failure: Connection was reset
```

`56` is `CURLE_RECV_ERROR` and is a vague reference to `Failure with receiving network data` and this issue covers one scenario around a proxy failure https://github.com/curl/curl/issues/1016 but maybe we can enable tracing like mentioned here https://github.com/desktop/desktop/issues/3695#issuecomment-354596872 and get some additional context.

**Comment by shiftkey** [comment] 2018-01-10 18:23
I'm going to close this out because it's not specific to Desktop, and requires being in a certain location to reproduce the problem.

@wind-soft @gengjiawen if you are able to dig deeper into what the `curl` error means I'm happy to help troubleshoot further, but otherwise I can't help much currently...

**Closed by shiftkey** 2018-01-10 18:23 UTC
Labels: more-information-needed

**Comment by vermatanya1994** [comment] 2018-01-15 07:17
Try using 
git clone --depth 1 <repo_URI>
then 

git fetch --unshallow 
or
git fetch
or 
git fetch --depth=2147483647

Then do 
git pull

This worked for me....
