### ISSUE TITLE
GHDesktop freezes entirety of windows 10

### ISSUE THREAD

**Issue by Reginald-Halifrax** [desktop/desktop#6817] opened 2019-02-10 19:25 UTC
After not opening github desktop in a while I opened it for some work on a fork. github proceeded to freeze my entire Windows 10 OS, I could see the after images of the windows i had opened, but lost all ability to interact with them. eventually losing even the ability to use task manager.

## Version
1.5.1

Operating system: Windows 10

## Steps to Reproduce:
1. Open github desktop
2. Wait for things to "load"

### Expected Behavior:
Github desktop opens and I get my work done.

### Actual Behavior
The entirety of my OS freezes leaving only my mouse operable.

## Additional Information
I recently upgraded my ram, so this gave me a big scare as I thought I must have done it wrong.
I have ran memory intensive games already and had no issue. Github being opened and freezing on a pull (and promptly freezing windows 10) was my best guess.

I'm much too nervous to open the program again until I'm sure it wont do it again.

I also saw this issue was raised before but were all promptly closed when no one could solve the problem. So I apologize for duplicate issues.

### Logs
Can't say the log told me anything useful either.

[2019-02-10.desktop.production.log](https://github.com/desktop/desktop/files/2849267/2019-02-10.desktop.production.log)

**Comment by steveward** [comment] 2019-02-11 15:48
Thanks for the report @Reginald-Halifrax. These types of freezes can often be caused by either the graphics card or bad memory. Please make sure that you're running on the latest graphics drivers available for your system. Additionally it would be helpful if you could check the Windows Event Log after one of these crashes and see if you can find anything in there that could help debug this. Here's how to check that:

1. Select the `Search` option from the Windows Start Menu
2. Type "View event logs" into the search box, and select the first menu item
3. In the left sidebar, expand "Windows Logs" and select "Application"
4. In the right sidebar, select "Filter Current Log..." and check the "Error" event level.

That should hopefully give some more information about why this is happening.

**Comment by niik** [comment] 2019-02-18 07:57
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2019-02-18 07:57 UTC
Labels: more-information-needed, support, windows
