### ISSUE TITLE
"Choose..." button for local path only accepts files instead of folders for "Clone repository" option

### ISSUE THREAD

**Issue by joshSi** [desktop/desktop#14050] opened 2022-03-02 08:23 UTC
### Describe the bug
When trying to clone a repository, clicking on "Choose..." for local path prompts file selection rather than folder selection

### Version & OS

Version 2.9.10 (x64), Windows 11

### Steps to reproduce the behavior

1. Click on "File" -> "Clone repository..."
2. Scroll down to 'Local path'
3. Click on "Choose..."

### Expected behavior

The "Choose..." button on 'Local path' should prompt to Select a Folder rather than a file,

similar to its the equivalent in "File" -> "New repository..."

### Actual behavior

The File Explorer that comes up only allows files to be selected, then shows an error that the file already exists

### Screenshots

![sc1](https://user-images.githubusercontent.com/19968417/156321964-07d1bcb2-1e7f-4348-aac6-446c65afc5eb.png)

![sc2](https://user-images.githubusercontent.com/19968417/156322677-1a351128-3d71-402d-ab74-842427fe70d3.png)
^ (should be **Select Folder** with option to select)

![sc3](https://user-images.githubusercontent.com/19968417/156322714-ebab217d-4d1f-4acc-b053-bce3ffcc5657.png)
^ (should not have option to select a file)

![sc4](https://user-images.githubusercontent.com/19968417/156322731-9d99f950-827f-4d1e-9c35-8934b4081f93.png)

### Logs

NA

### Additional context

In contrast, the "New Repository..." Local path seems totally fine:

![c1](https://user-images.githubusercontent.com/19968417/156323025-e43fc8f3-33fa-4c2f-8c24-0a7ad55c439b.png)

![c2](https://user-images.githubusercontent.com/19968417/156323039-f619dbff-138f-42d1-911f-bfe4047cf103.png)
^ (has **Select Folder**, as expected)
![c3](https://user-images.githubusercontent.com/19968417/156323057-491d66d1-6a2c-4899-918f-36c44bac1e80.png)

**Comment by Harry-Hopkinson** [comment] 2022-03-03 17:18
I get this issue as well - I am currently working on it.

**Comment by jrshelby** [comment] 2022-03-03 19:39
+1 to this. It was particularly annoying before the most recent updated when the bug with the "Local Path" not being pre-populated was fixed. This meant that the box would not prepopulate, and the "Choose" button wouldn't easily allow you to select a different folder.

**Comment by niik** [comment] 2022-03-07 10:53
Thanks for opening this, seems to be a duplicate of https://github.com/desktop/desktop/issues/12812 where we determined that we should revert to the old behavior although it seems that fell between chairs. I'll see if we can get a quick resolution on whether to keep this behavior mac-specific or revert it all together. I'll close this in favor of the original issue though so please subscribe to https://github.com/desktop/desktop/issues/12812 to follow along!

**Closed as completed by niik** 2022-03-07 10:53 UTC
