### ISSUE TITLE
After pull, I get an alert "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#9053] opened 2020-02-05 08:17 UTC
### Version & OS

Git Hub Desktop 2.3.1 with macOS 10.15,3

### Steps to reproduce the behavior

1. Trigger a Pull

### Expected behavior

A feedback, that the pull with rebase did succeed. That was the case in previous versions.

### Actual behavior

Now, I get an alert.

### Screenshots

![GitHubErrorAlert](https://user-images.githubusercontent.com/47812706/73823252-21a2cb80-47f8-11ea-9d6b-de549aa679b7.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by steveward** [comment] 2020-02-05 15:16
Thanks for the report @sdiedrichsen. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue. Thanks!

Thanks,
Steve

**Comment by sdiedrichsen** [comment] 2020-02-06 07:15
Here's the log:

>>>>>>

020-02-06T07:12:29.397Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:12:41.714Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MusicApps - sdiedric (has token)
2020-02-06T07:12:45.746Z - info: [ui] Executing checkoutBranch: git -c credential.helper= checkout --progress lhierl/TronTempoCompile -- (took 4.026s)
2020-02-06T07:12:47.006Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.259s)
2020-02-06T07:12:47.137Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:12:47.145Z - info: [ui] [Timing] Action 'checkout branch from list' for 'musicapps/MusicApps' took 5.413s
2020-02-06T07:12:47.587Z - warn: [ui] deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/lhierl/TronTempoCompile/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
    at o (/webpack:/app/src/lib/http.ts:68:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:170:6)
    at x.fetchPushControl (/webpack:/app/src/lib/api.ts:827:6)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:883:29)
2020-02-06T07:12:47.588Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/lhierl/TronTempoCompile/push_control: Internal Server Error (500)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:26)
2020-02-06T07:12:59.292Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MusicApps - sdiedric (has token)
2020-02-06T07:13:00.718Z - info: [ui] Current tutorial step is NotApplicable
2020-02-06T07:13:00.729Z - info: [ui] [Timing] Action 'checkout branch from list' for 'musicapps/MusicApps' took 1.413s
2020-02-06T07:13:01.149Z - warn: [ui] deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/57588690-Repeater-gets-confused/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
    at o (/webpack:/app/src/lib/http.ts:68:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:170:6)
    at x.fetchPushControl (/webpack:/app/src/lib/api.ts:827:6)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:883:29)
2020-02-06T07:13:01.149Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/57588690-Repeater-gets-confused/push_control: Internal Server Error (500)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:26)

<<<<<<

**Comment by niik** [comment] 2020-02-11 12:02
> Now, I get an alert.
> 
> ### Screenshots
> See attachments

Hey @sdiedrichsen, it seems as if the screenshots didn't make it into the issue. Could you try again please? The errors that we're seeing in the log file shouldn't affect the behavior of the application so I'm guessing  there's something else you're running into. A screenshot of the alert/dialog you're seeing would be ideal

**Comment by sdiedrichsen** [comment] 2020-02-11 12:25
Markus, 

see above. 

Best,

Steffan

**Comment by tierninho** [comment] 2020-02-12 18:49
I spotted two errors in the logs:

```
2020-02-06T07:13:01.149Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/57588690-Repeater-gets-confused/push_control: Internal Server Error (500)
```

and 

```
2020-02-06T07:13:01.149Z - warn: [ui] deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/57588690-Repeater-gets-confused/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
```

@niik Any thoughts?

**Comment by niik** [comment] 2020-02-13 14:04
Hi again @sdiedrichsen, thanks so much for staying on and helping us troubleshoot this, we really appreciate it.

Are you're seeing the `Cannot read property 'length' of undefined` regardless of what branch you're currently on?

Second question, and this might sound like an odd one but, do any of your branch names contain the pound sign (`#`)? Do any of them start with `#` or do any of the branches share the same prefix up until the `#` character (one example could be `branch-a` and `branch-a#2`).

**Comment by sdiedrichsen** [comment] 2020-02-13 15:56
Hello Markus, 

thanks for following up. 

#1: Alert

The alert is not presented right now. So I watched the log output and no matter what branch I checkout, this lines appear in the log:

deserialize: invalid JSON found at 'https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/STEFFAND-XXXXXX/push_control' - status: 500, length: '(missing)' id: '(missing)'
SyntaxError: Unexpected end of JSON input
    at o (/webpack:/app/src/lib/http.ts:68:5)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:170:6)
    at x.fetchPushControl (/webpack:/app/src/lib/api.ts:827:6)
    at Ve.refreshBranchProtectionState (/webpack:/app/src/lib/stores/app-store.ts:883:29)
2020-02-13T15:48:49.120Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: API error https://github.aso.apple.com/api/v3/repos/musicapps/MusicApps/branches/STEFFAND-FlexPitch_PV/push_control: Internal Server Error (500)
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:171:26)


Out of curiosity I pasted the URL given above into Safari, That’s the response:

{
  "message": "Must authenticate to access this API.",
  "documentation_url": "https://developer.github.com/enterprise/2.19/v3"
}
Does that tell you anything? 




#2; Pound

No, I don’t have any pound signs. But I use slashes  But this reminds me of an oddity, when I had a branch named like Fix-in-Func(). The “()” triggered something I don’t remember  and we had to rename that branch using the console. 

The branches look like these:

  sdiedrichsen/Fix-seemingly-identical-pointers
  sdiedrichsen/ISSUE509/xml-data-creation-deprecated
  sdiedrichsen/Static-Analyzer-Potential-Leak-
  sdiedrichsen/Static-Analyzer-SECURITY-strcpy-is-unsafe
  sdiedrichsen/Static-Analyzer-data-can-be-NULL
* sdiedrichsen/Static-Analyzer-null-pointer-passed
  sdiedrichsen/Static-Analyzer-potential-memory-leak

Best,

Steffan

**Comment by 0723Cu** [comment] 2020-05-17 03:40
Duplicate of #

**Comment by steveward** [comment] 2024-04-05 15:07
I'm going to close this out as stale. @sdiedrichsen if you're still encountering this issue let us know and we can reopen and investigate further (I also looked through the issue tracker and couldn't find any other recent reports of this).

**Closed by steveward** 2024-04-05 15:07 UTC
Labels: investigation-needed
