### ISSUE TITLE
Cherry-pick commit

### ISSUE THREAD

**Issue by maxkoshevoi** [desktop/desktop#11393] opened 2021-01-14 12:13 UTC
### Describe the feature or problem you’d like to solve

Is there some way to cherry-pick commit from one branch to another? I expected this feature to be in right-click menu of a commit in "Compare branches" tab, but it's not there:
![image](https://user-images.githubusercontent.com/6609929/104589486-9e7a2e80-5672-11eb-98da-10def52e69bf.png)

### Proposed solution

Add cherry-pick option to commits when comparing branches

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by billygriffin** [comment] 2021-01-14 13:31
Closing as a duplicate of #1685, thanks for the issue!

**Closed as completed by billygriffin** 2021-01-14 13:31 UTC
