### ISSUE TITLE
Rebase claims that branches are up to date with each other

### ISSUE THREAD

**Issue by vonas** [desktop/desktop#9192] opened 2020-02-27 22:23 UTC
### Describe the bug

Trying to update the current branch by applying its commits on top of another branch (i.e. rebasing) doesn't work reliably.

### Version & OS

Version 2.3.1 on Windows 7

### Steps to reproduce the behavior

I have created an example repository with which you should be able to see the problem immediately by just cloning it. Visit [`vonas/-issue-desktop-desktop-rebase`](https://github.com/vonas/-issue-desktop-desktop-rebase), clone the repository (from within GitHub Desktop if you like), check out the branch `rebase` and try to rebase that branch to `master`

- Click `Branch`
  - and `Rebase current branch...` (Ctrl+Shift+E)
- Select branch `master`

### Expected behavior

Rebase should be possible with a message around these lines:
> *This will update **rebase** by applying its **1 commit** on top of **master***

### Actual behavior

Instead this message is shown and `Start rebase` is not clickable:
> *This branch is up to date with **rebase***

### Screenshots

![rebase](https://user-images.githubusercontent.com/24623262/75491927-040bf080-59b7-11ea-930e-45376d70227f.png)

### Steps in more detail

If you cannot reproduce the problem try to follow these steps (that's what I did):

1. Create an empty repository
2. Create a file "file.txt" and commit it
3. Create a branch "rebase" and check it out
4. Create a file "rebase.txt" and commit it
5. Check out master
6. *Try to perform the steps from above (i.e. perform a rebase)*

### Additional context

On the other hand, opening a terminal and typing `$ git rebase master` works as expected.

**Comment by tierninho** [comment] 2020-02-27 22:30
@vonas This is a duplicate of an open issue https://github.com/desktop/desktop/issues/8049 Please follow along there.  Thank you for filing this, nevertheless!

**Closed by tierninho** 2020-02-27 22:30 UTC
