### ISSUE TITLE
Can't discard a chunk on macOS

### ISSUE THREAD

**Issue by guidezpl** [desktop/desktop#10194] opened 2020-07-13 10:20 UTC
### Describe the bug

Context menu option to discard modified lines is always greyed out.

### Version & OS

2.5.3, macOS 10.15.5

### Steps to reproduce the behavior

1. Make changes to a file, and wait for the app to pick up changes
2. Right click some blue area in the gutter 

### Expected behavior

Able to discard a chunk

### Actual behavior

Option is greyed out

### Screenshots

<img width="417" alt="Screenshot 2020-07-13 at 12 16 22" src="https://user-images.githubusercontent.com/6655696/87293707-fdfc5380-c502-11ea-8d25-2fbe2aa8529f.png">

**Comment by rafeca** [comment] 2020-07-13 15:10
Hey @guidezpl !

In order to discard an entire hunk, you need to right-click on the gutter that appears between the line numbers and the actual code:

<img width="560" alt="Screen Shot 2020-07-13 at 17 01 51" src="https://user-images.githubusercontent.com/408035/87320035-af62af80-c52a-11ea-8a96-8f4a19fe3a63.png">

When clicking on a specific line we allow to discard just that line, but only under certain circumstances (only when that line belongs to a hunk that as only added or deleted lines, not a mix of both).

The reasoning behind that is that discarding a single line when there are both added and deleted lines in the hunk (like in your screenshot) would cause something unexpected to most of the users: in your case it would remove the added line, meaning that the final result would be the line being removed.

This could be mitigated if we allowed users to undo these discards but since we don't allow that yet we've opted to just disable any action that could lead to unexpected behaviour (we're planning to reenable it once we implement undo though).

You can see more information in https://github.com/desktop/desktop/issues/10083#issuecomment-649531481.

I'm going to close this issue in favor of https://github.com/desktop/desktop/issues/10083, feel free to comment there if you want to add something else to that issue.

**Closed by rafeca** 2020-07-13 15:10 UTC

**Comment by guidezpl** [comment] 2020-07-13 17:15
I take your point about the discarding behavior for individual lines. But I think the vast majority of the time a user would be wanting to undo their change, i.e. delete the whole hunk. Right clicking that tiny bit of space doesn't feel intuitive and I would have never found it out on my own.

To improve this, how about including the "Discard modified lines" context menu when right clicking on the area left of the gutter as well?

**Comment by rafeca** [comment] 2020-07-13 18:04
Thanks for the feedback, this is something we're going to consider.

The reasoning behind the current behaviour is to make it consistent with how partial commits work (clicking on a line selects it, clicking on the gutter selects the whole hunk), but I agree that this can be confusing when discarding changes.

> To improve this, how about including a "Discard modified lines" in the context menu (as well as the "Discard modified line") when right clicking on the area left of the gutter?

That could work, but I'm worried by the fact that we currently only highlight the clicked line when clicking on it (as opposed to when clicking on the gutter), since this could cause confusion. I think though that we can try to tweak the design of the highlighting when right clicking to accommodate this.

When tweaking this, something we want to make sure is that there's a clear distinction between discarding a single line and discarding a hunk (since a hunk can be quite large, discarding a whole hunk by mistake can be quite disruptive for a user).
