### ISSUE TITLE
MSEdge & Firefox do not open GitHub desktop

### ISSUE THREAD

**Issue by aminya** [desktop/desktop#10010] opened 2020-06-15 19:12 UTC
### Describe the bug

When I try to open a repository in GitHub desktop after clicking open from the MSEdge prompt nothing happens.

### Version & OS

- GitHub Desktop 2.5.2
- MSEdge 83
- Win 10 2004

### Steps to reproduce the behavior

1. Go to a repository
2. Click on clone
3. Click on open in desktop
4. Click open in MSEdge prompt

### Expected behavior

Open the repo in GitHub desktop

### Actual behavior

Does not open

### Screenshots

![image](https://user-images.githubusercontent.com/16418197/84696519-40d20800-af12-11ea-8669-15926e300f97.png)

### Additional context
Similar to https://github.com/desktop/desktop/issues/5324, but GitHub is not opened at all.

**Comment by tierninho** [comment] 2020-06-15 19:34
@aminya Thank you for filing this bug. I can confirm that clicking the Open in Desktop button sends the user to https://desktop.github.com/ instead of opening the repo in Desktop. We had an earlier report of this, which I can't find as of yet.

Note, I see the old menu in Edge 83:
![Screen Shot 2020-06-15 at 9 22 23 AM](https://user-images.githubusercontent.com/14828183/84697811-7ebb3600-aeea-11ea-918c-d3f8d088a242.png)

Both Chrome on OSX and Win10 work fine, so it is an isolated problem.

**Comment by tierninho** [comment] 2020-06-16 18:32
Another report filed https://github.com/desktop/desktop/issues/10024, this time with Firefox browser. I tested with OSX and the issue is present.

**Comment by davidfokkema** [comment] 2021-08-04 13:43
@aminya were you running inside a VM? I had the same issue in Windows 10 running in Parallels. This turned out to be the problem: Parallels shares applications by default. You can disable that, but only after you have installed Windows. By that time Parallels has registered all Mac applications in the Windows Registry along with file associations and URLs.

What worked for me:
1. Start regedit.exe
2. Search for 'x-github-desktop-auth'
3. If the key or container has something like 'GitHub (Mac)': delete the key or container. This also takes care of 'x-github-client' associations.

Now, only the associations from the *Windows* GitHub Desktop app remain.

**Comment by aminya** [comment] 2021-08-05 04:28
No, I wasn't running a VM. 

P.S: I am on a new system now, and the button works as intended. But I remember that I had this problem with a native machine I was using when I reported this issue.

**Comment by davidfokkema** [comment] 2021-08-05 07:39
So not a VM problem, ;-). If you no longer experience the bug, maybe this issue can be closed?

**Comment by aminya** [comment] 2021-08-05 07:43
I cannot guarantee that this is fixed, but the conditions that triggered the bug are not valid anymore. I will let the maintainers decide on closing.

**Comment by steveward** [comment] 2021-09-28 17:27
Thanks for the updates on this @davidfokkema and @aminya. Closing this out since I was unable to reproduce the issue.

**Closed by steveward** 2021-09-28 17:27 UTC
Labels: bug, priority-3
