### ISSUE TITLE
Add support for detecting Jetbrains tools in Desktop (Phpstorm, webstorm, etc) with Jetbrains Toolbox

### ISSUE THREAD

**Issue by dacoto97** [desktop/desktop#7195] opened 2019-04-01 15:35 UTC
Add the option to choose a program installed on my computer other than the ones it automatically detects.
![image](https://user-images.githubusercontent.com/16915053/55340127-593c3b00-54a4-11e9-8481-4406dad82e32.png)

**Comment by billygriffin** [comment] 2019-04-01 15:40
Hi @dacoto, here's the PR where a PhpStorm integration was added for macOS: https://github.com/desktop/desktop/pull/3749. Are you on a different OS?

Here's more information about our editor integration more generally (https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md), and we frequently accept pull requests to add new editors.

**Comment by dacoto** [comment] 2019-04-01 15:44
I'm using windows 10

**Comment by billygriffin** [comment] 2019-04-01 15:50
Thanks @dacoto! Do you have any interest in making a PR to add PhpStorm for Windows? We haven't heard requests to add that editor for Windows previously so we don't intend to build anything in, but we'd be happy to review a PR if you're interested in doing so.

**Comment by dacoto** [comment] 2019-04-01 17:10
Ok, I have seen the documentation and I will prepare the integration with PhpStorm.

**Comment by dacoto** [comment] 2019-04-01 19:01
Hello, the installation address is this: %appdata%\..\Local\JetBrains\Toolbox\apps\PhpStorm\ch-0\191.6183.95\bin, it is not in the log files, since it is a temporary address, what can I do?

**Comment by shiftkey** [comment] 2019-04-04 16:15
@dacoto we're limited at the moment by what we can support because on Windows we look at the registry for installed programs, and it looks like the JetBrains tools have changed things in recent versions to include the version (numeric or calendar) in the registry keys.

For example, our WebStorm integration looks like this:

https://github.com/desktop/desktop/blob/64a075b1019b9e4358777449ef87cdebde52c1ac/app/src/lib/editors/win32.ts#L233-L241

This means it probably won't detect versions released in 2019 or beyond (or 64-bit versions), and it'd be great to figure out a more future-proof approach here. I don't have a working JetBrains license at the moment to help out with investigating, and I'm swamped with working on some upcoming features currently, but once I have some breathing space I'd love to use this as an excuse to catch up with @citizenmatt to talk more about our options to make the JetBrains experience better so we can size up the work involved.

**Comment by dacoto** [comment] 2019-04-04 20:13
@shiftkey Thank you very much for your help, I have acquired a PhpStorm license, but you can use a free 30 days license, I have been researching and the problem is that they have launched the tool Jetbrains Toolbox, which is an installer of all programs and not it is added to the registry except for the Jetbrains Toolbox.
I hope that @citizenmatt can help us, I will also try to talk with the support agents, to know if they have any ideas.

**Comment by KaKi87** [comment] 2019-11-18 10:48
Hello there, any news on this ?
I've seen that GitHub Desktop supports JetBrains WebStorm and nothing else, which is sad.
Personally I use IntelliJ Ultimate to support all programming languages and platforms.
Thanks

**Comment by billygriffin** [comment] 2019-11-18 15:59
@KaKi87 We have documentation for people who want to add support for more editors here: https://github.com/desktop/desktop/blob/development/docs/technical/editor-integration.md

Because the number of different editors people used can be infinite, we try to support the most widely used ones (assuming they fit the requirements specified in the docs), but we rely on external contributors to add support for others. If you want to investigate whether you can hook up support for your editor with Desktop, we encourage you to do so!

**Comment by dacoto97** [comment] 2019-11-20 11:13
I have worked on the changes and created a PR #8656 
- Added support for PhpStorm 2019.2 and 2019.2.4
- Added support for WebStorm 2019.2 and 2019.2.4

**Closed** 2020-03-02 10:28 UTC
Labels: integrations, investigation-needed
