### ISSUE TITLE
Pull with rebase doesn't allow pulling when we have changes in the working tree

### ISSUE THREAD

**Issue by ImRodry** [desktop/desktop#15660] opened 2022-11-21 12:38 UTC
### The problem

If you're rebasing with merge (the default option) GitHub desktop allows you to pull commits with changes on your working tree, as long as the pulled commits don't change the same files you're changing. This is not the case with pull with rebase as GitHub Desktop as it always requires you to stash your changes to pull.

### Release version

3.1.2

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Make some changes on your project
2. Have someone else push to your branch
3. Try to pull and observe the error

**Comment by steveward** [comment] 2022-12-01 21:20
Thanks for the report @ImRodry. I tested this out and was unable to reproduce the issue. I set `rebase = true` in my `.gitconfig` to test, and was able to hit the error when attempting to pull a change to a file that also has an uncommitted change, but did not encounter it with uncommitted changes present that did not have a matching file to pull.

If you're able to reproduce this it'd be helpful if you could share the steps so that we can get a better understanding of what might have happened. Thanks!

**Comment by ImRodry** [comment] 2022-12-06 00:03
@steveward not sure how that happened but when I try to pull a commit while having changes from other files I get this error
![image](https://user-images.githubusercontent.com/38259440/205772735-be4ec264-ed40-40bf-bb19-6887729582ce.png)

**Comment by ImRodry** [comment] 2023-02-16 11:15
Any updates on this? This is still very much an issue and it's been a while

**Comment by steveward** [comment] 2023-06-27 14:45
@ImRodry just tested this again and was correctly seeing this when pull.rebase was enabled:

<img width="470" alt="Screenshot 2023-06-27 at 10 43 17 AM" src="https://github.com/desktop/desktop/assets/721500/a7f186ca-235e-47db-938e-06b013bafa8d">

I'm going to close this out since this is the intended behavior.

**Closed as completed by steveward** 2023-06-27 14:45 UTC

**Comment by ImRodry** [comment] 2023-06-27 17:41
> @ImRodry just tested this again and was correctly seeing this when pull.rebase was enabled:
> 
> <img alt="Screenshot 2023-06-27 at 10 43 17 AM" width="470" src="https://user-images.githubusercontent.com/721500/249190172-a7f186ca-235e-47db-938e-06b013bafa8d.png">
> I'm going to close this out since this is the intended behavior.

Why is that intended behavior when GitHub desktop allows us to get around that when pulling with merge?
