### ISSUE TITLE
Clicking on preference dialog tabs closes the preference dialog.

### ISSUE THREAD

**Issue by grantcarver** [desktop/desktop#1730] opened 2017-05-24 05:45 UTC
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

After updating from 0.5.6 to 0.5.7 switching tabs in the preferences dialog closes is after a 2 second delay. 

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.5.7

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** macOS Sierra 10.12.5

### Steps to Reproduce

1. Open the preferences dialog,
1. Click on either the Git or Advanced tabs.

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behaviour:** Tab is selected and dialog remains usable.

**Actual behaviour:** Tab is selected but dialog automatically closes. It appears that the button click on the tab is being propagated to the close button. Tabbing and using arrows allows tabs to change without closing.

**Reproduces how often:** 100%

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

Only the usage event to https://central.github.com/api/usage/desktop being reported in the logs: 
```
2017-05-24T05:32:21.624Z - info: Opt in reported.
2017-05-24T05:32:21.957Z - info: Opt in reported.
2017-05-24T05:32:36.262Z - info: Opt in reported.
2017-05-24T05:32:43.722Z - info: Opt in reported.
2017-05-24T05:33:05.026Z - info: Opt in reported.
2017-05-24T05:35:53.284Z - info: Opt in reported.
2017-05-24T05:37:31.341Z - info: Opt in reported.
2017-05-24T05:39:56.319Z - info: Opt in reported.
2017-05-24T05:40:19.605Z - info: Opt in reported.
2017-05-24T05:40:47.142Z - info: Opt in reported.
2017-05-24T05:41:20.944Z - info: Opt in reported.
```

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by niik** [comment] 2017-05-24 06:15
Duplicate of #1724, fixed in #1726

**Closed by niik** 2017-05-24 06:15 UTC
