### ISSUE TITLE
Github weird behaviour, errors over errors

### ISSUE THREAD

**Issue by Temepest74** [desktop/desktop#8094] opened 2019-08-12 10:35 UTC
To give a background. I had this file on bitbucket, the file size exceeded the maximul bitbucket size. So I changed to github. Well, nothing worked good at all. After working in some ways I had to configure it for Git large files. This was easy, but I got errors over erorrs, I was not able to push because "I was not authetificated", even if I was, I got all the recomanded thinks I read in the error pop up msg but my problem was not solved. So I just decided to remove .git folder and start again. When I create a new repository my github destop is empty, no files to push, but the folder is not empty. Any help? 
![image](https://user-images.githubusercontent.com/28103890/62859519-36bbf900-bcb2-11e9-8e62-c84e78a6635e.png) 
![image](https://user-images.githubusercontent.com/28103890/62859531-41768e00-bcb2-11e9-84c0-266693bfde24.png)
Edit: this is file from github 
![image](https://user-images.githubusercontent.com/28103890/62859559-5d7a2f80-bcb2-11e9-84c8-c776d5acf97b.png)

**Comment by steveward** [comment] 2019-08-12 13:22
Thanks for the report @Temepest74. 

Did you add your files to the correct location where your new repository was created? I'm not seeing a .git directory in the screenshot you attached, so my guess is that the repository was initialized in a different location. You can go to the menu and select `Repository` > `Open in Explorer` to find the exact location where the repository lives on disk. Then add your project files to that location and your changes should appear in GitHub Desktop.

Let me know if you run into any issues with that.

**Comment by Temepest74** [comment] 2019-08-12 14:03
it did not saved me in the right place, but everythik I do seems to go wrong. 
If I do this: 
![image](https://user-images.githubusercontent.com/28103890/62870808-1e0e0c00-bccf-11e9-8546-e6b69a11c4de.png)
It will make me another folder with that repository name(search for AReality)
![image](https://user-images.githubusercontent.com/28103890/62870865-3716bd00-bccf-11e9-8626-e60d85447ba0.png)

**Comment by steveward** [comment] 2019-08-12 19:40
@Temepest74 try this:

1. Drag-and-drop the project folder into GitHub Desktop
2. Select the `Create a new repository` option in the message that states this is not an existing repository
3. Click `Create repository`

That should get things working.

**Comment by Temepest74** [comment] 2019-08-13 07:26
I got this error now, how I can solve this? 
![image](https://user-images.githubusercontent.com/28103890/62922741-fcf5fb80-bd60-11e9-987c-fce15569a3cf.png)
I had this project on bitbucket befor but it did not happened

**Comment by Temepest74** [comment] 2019-08-13 07:27
and this shows when I unde the initial commit 
![image](https://user-images.githubusercontent.com/28103890/62922783-19923380-bd61-11e9-87a4-8748cdbd90df.png)

**Comment by Temepest74** [comment] 2019-08-13 07:33
It happens even if I set GLF for .webm (the biggest file from my project and the one I got a precedent error for)

**Comment by steveward** [comment] 2019-08-13 13:09
@Temepest74 it looks like you are committing a large file to your repository -- GitHub Desktop should warn you before you do that. If you choose to commit that file the push will fail since it exceeds the [size limits of files for GitHub repositories](https://help.github.com/en/articles/working-with-large-files).

Is this a file that you need to commit to your repository? If so, I would recommend using something like Git LFS, which is supported in GitHub Desktop. It allows you to work with large files. You can read more about adding large files to Git LFS here:

https://help.github.com/en/articles/configuring-git-large-file-storage

You will need to use the command line or directly edit the `.gitattributes` file in your repository in order to manage your large files. Let me know if you have any questions about this.

**Comment by Temepest74** [comment] 2019-08-13 16:29
after running this command, the github destop start behaving weird again 
![image](https://user-images.githubusercontent.com/28103890/62959022-83154f00-be00-11e9-9efd-1b91bb7b8f22.png)
![image](https://user-images.githubusercontent.com/28103890/62959030-890b3000-be00-11e9-9399-855b54b71fdc.png)
and yes, the path is set in the right way
D:\Unity\GitHub\AugmentedReality\AugmentedReality

**Comment by steveward** [comment] 2019-08-13 20:41
>Is there a way to find the files bigger then 100mb and auto assign them to glf?

This command would work from Git Bash within your repository directory:

`find . -type f -size +100M`

That should list all of your files over 100MB in size.

If you need to remove large files over 100MB that have already been committed to your repository you can use something like the [BFG Repo Cleaner](https://rtyley.github.io/bfg-repo-cleaner/).

**Comment by Temepest74** [comment] 2019-08-14 05:21
Now it works, but this folder is there and every commit I do with only that folder throw this error 
![image](https://user-images.githubusercontent.com/28103890/62996230-9231e680-be6c-11e9-9b0e-32433b81d878.png)

**Comment by steveward** [comment] 2019-08-14 19:37
Can you share the log file from GitHub Desktop? That should give some more information about this error.

Thanks for writing in. Could you send over the log file from GitHub Desktop so that I could get some more information about this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Temepest74** [comment] 2019-08-15 12:03
[2019-08-15.desktop.production.log](https://github.com/desktop/desktop/files/3505440/2019-08-15.desktop.production.log)
I had made two push today and a commit with the weird file

**Comment by Temepest74** [comment] 2019-08-15 12:25
and now, after making changes to repository it does not show them...

**Comment by Temepest74** [comment] 2019-08-15 23:04
Now, when I try to add another type of file to glf this error pop up... 
![image](https://user-images.githubusercontent.com/28103890/63132539-0d5cdf00-bfca-11e9-8dc4-2eb268d7cb72.png)
Beside that, some part of the project are submiteble and some not. why? this is the entire log from today
[2019-08-15.desktop.production.log](https://github.com/desktop/desktop/files/3507452/2019-08-15.desktop.production.log)

**Comment by steveward** [comment] 2019-08-17 02:40
@Temepest74 the `Not a Git directory` error is happening because you are attempting the command outside of a Git directory. You can use `cd /path/to/repository` to change to the correct location, or go to the menu in GitHub Desktop and select `Repository` > `Open in Git Bash` to directly launch into the correct directory.

The only error I am seeing in the log file is this:

```
2019-08-15T12:00:53.026Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stdout:
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
	AReality/

nothing added to commit but untracked files present
```

Usually this is caused by having nested Git repositories, see [this issue comment](https://github.com/desktop/desktop/issues/4432#issuecomment-381677801). Could you check to see if there are nested `.git` directories that could be causing this? My guess is that you may have accidentally initialized multiple repositories while attempting to reinitialize your project.

**Comment by Temepest74** [comment] 2019-08-17 04:27
It does not matter what I do, it will always be a second repository there. Even if I delet it

**Comment by steveward** [comment] 2019-08-19 17:40
@Temepest74 could you open up the root directory in PowerShell and run `tree /F` to show the directory structure and files that exist within those directories?

**Comment by tierninho** [comment] 2019-09-05 00:30
@Temepest74  As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Closed by tierninho** 2019-09-05 00:30 UTC
Labels: support
