### ISSUE TITLE
Can't sign in to account from GitHub desktop with Chrome as default browser on MacOS 10.15.5

### ISSUE THREAD

**Issue by ikurakoosh** [desktop/desktop#10095] opened 2020-06-27 19:28 UTC
### Describe the bug

Can´t sign in to account from GitHub desktop with Chrome as default browser on MacOS 10.15.5
Get error: The application “Google Chrome” does not have permission to open “x-github-desktop-auth://oauth?code=98ba8c5bf8b081193a5e&state=c592ba5e-0729-45d0-891e-4346ae2ace86.”

### Version & OS

MacOS 10.15.5
Current version of GitHub Desktop
### Steps to reproduce the behavior

1. Open Github Desktop
2. Click on 'Sign in to GitHub.com'
3. A new window opens in Chrome and a dialog box says "Open GitHub Desktop?"
4. Click "Open GitHub Desktop?"

### Expected behavior

I expected to be taken to the sign-in page, to sign in and then returned to GitHub Desktop.

### Actual behavior

I get an error and can't go any further.

### Screenshots

<img width="370" alt="Screen Shot 2020-06-27 at 2 20 15 PM" src="https://user-images.githubusercontent.com/67201143/85930412-d90cad00-b881-11ea-8852-3d9735e0cb2d.png">

<img width="486" alt="Screen Shot 2020-06-27 at 2 24 58 PM" src="https://user-images.githubusercontent.com/67201143/85930440-0eb19600-b882-11ea-9772-2b7cedf1393b.png">

<img width="440" alt="Screen Shot 2020-06-27 at 2 25 09 PM" src="https://user-images.githubusercontent.com/67201143/85930469-30ab1880-b882-11ea-827a-e4f564d15959.png">

### Logs

[2020-06-27.desktop.production.log](https://github.com/desktop/desktop/files/4841125/2020-06-27.desktop.production.log)

**Comment by tierninho** [comment] 2020-06-29 18:07
@ikurakoosh Thanks for filing this issue.

I spotted the this in your logs as well. Do you still have Desktop in your downloads directory?

```
Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
```

As for the Chrome error, are you still getting it after doing above?

**Comment by niik** [comment] 2020-07-06 13:20
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2020-07-06 13:20 UTC
Labels: more-info-needed

**Comment by rbbcgc** [comment] 2020-10-31 04:05
I am facing the same problem. Is it possible to resolve?

**Comment by rithujaa** [comment] 2020-11-18 07:22
Hey I had the same problem. It was because I hadn't moved my github desktop to applications after downloading it. Once you move it to application, it should work.

**Comment by kessiez** [comment] 2020-12-03 23:55
> Hey I had the same problem. It was because I hadn't moved my github desktop to applications after downloading it. Once you move it to application, it should work.

It's still not working for me. It says "signing in using your browser," but nothing pops up.

**Comment by arispeaks** [comment] 2021-01-24 18:06
> Thank you for your issue!
> 
> We haven't gotten a response to our questions.
> With only the information that is currently in the issue, we don't have enough
> information to take action. I'm going to close this but don't hesitate to reach
> out if you have or find the answers we need, we'll be happy to reopen the
> issue.

@niik looks like a solution has been found for this issue: On MacOS 10.15.5- 10.15.7, Move GitHub Desktop from downloads to applications folder to allow open permissions for Google Chrome. I can confirm that this is still an issue with release 2.6.2. Anyway to integrate this messaging into the installer prompts for GitHub Desktop?

**Comment by niik** [comment] 2021-01-25 09:15
> @niik looks like a solution has been found for this issue: On MacOS 10.15.5- 10.15.7, Move GitHub Desktop from downloads to applications folder to allow open permissions for Google Chrome. I can confirm that this is still an issue with release 2.6.2. Anyway to integrate this messaging into the installer prompts for GitHub Desktop?

@arispeaks Thank you for reaching out! Yes, we are looking into ways to suggest moving the app to the proper folder, the first step of this (#11280) is to get an idea of how many of our users are currently running the app from outside of the applications folder. Once we've got a good sense of that we can start looking at the prompt. cc @sergiou87

**Comment by ereta19** [comment] 2021-02-04 06:23
I also have the same problem, any solutions yet to solve this nightmare?

**Comment by arispeaks** [comment] 2021-02-04 19:06
@ereta19 see above, moving the dropbox desktop app from downloads folder to applications folder should do the trick

**Comment by nagysandorantal** [comment] 2022-02-15 19:03
I have the same problem.

**Comment by Marroco93** [comment] 2022-02-23 14:17
I just move the folder from Downloads to Desktop and works!

**Comment by af-md** [comment] 2022-04-19 10:25
If the above steps don't work then try this:
1)Remove VSCode entirely from your machine (download and app folder). 
2) Download it again 
3) Before opening it, move it to the app folder and then open it.
4) Sign into Github and it should work now

**Comment by Bert-King** [comment] 2022-10-22 13:51
> @ereta19 see above, moving the dropbox desktop app from downloads folder to applications folder should do the trick

nice

**Comment by viradia2** [comment] 2023-02-09 19:33
Moving from Download folder to Application folder did the trick for me.

**Comment by EgleValu** [comment] 2023-03-22 07:52
What do you mean move from Downlaods folder? The app is installed in the C:\Users\User\AppData\Local\GitHubDesktop

**Comment by steveward** [comment] 2023-03-22 15:32
@EgleValu this issue is specific to macOS, not Windows. If you're encountering problems on Windows feel free to open an issue.

**Comment by CristianMaldonadoBarreto** [comment] 2024-01-29 06:50
This problem can be fixed by giving google chrome access to your downloads folder.
