### ISSUE TITLE
Arrow navigation doesn't work in emoji select window

### ISSUE THREAD

**Issue by m3r1v3** [desktop/desktop#16119] opened 2023-02-11 12:27 UTC
### The problem

When navigating with the arrows (up/down) in the emoji window, the window closes instead of scrolling through the list. Previously, this problem was not present.

### Release version

3.1.6

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Type `:` symbol in Summary/Description text field for opening emoji select window
2. Press Arrow Down key on keyboard
3. The emoji window is closed (in previous versions the list would scroll)

**Comment by andrewhong04** [comment] 2023-02-12 05:38
I've been looking into this and it seems like https://github.com/desktop/desktop/pull/15641 caused this bug. A pull request will be out shortly.

**Comment by steveward** [comment] 2023-02-13 16:00
Thanks for the report @merive, this is a duplicate of https://github.com/desktop/desktop/issues/16044 so I'm going to close this issue out. You can follow along there for updates.

**Closed as completed by steveward** 2023-02-13 16:00 UTC
