### ISSUE TITLE
Disable Compare to Branch menu item if modal is active

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#5603] opened 2018-09-11 16:23 UTC
If the user is engaged with another modal, especially one that requires an action or acknowledgement, we are currently disabling most of our menu options. It seems one slipped by these rules. 

Branch > Compare to Branch should be disabled along with the rest. 

<img width="528" alt="screen shot 2018-09-11 at 9 13 51 am" src="https://user-images.githubusercontent.com/14828183/45373305-f20c7700-b5a3-11e8-9c63-0fc026579fbe.png">

tested in 1.4.0-beta3, mac

**Comment by kanishk98** [comment] 2018-09-13 15:13
@tierninho Hi. I'm just beginning to explore Desktop and this seems like a good place to start. Since this issue doesn't seem to be assigned to anyone yet, I'd like to take it up.

**Comment by tierninho** [comment] 2018-09-13 15:17
@kanishk98 thanks for taking this on and please reach out to the team if you have any questions

**Comment by kanishk98** [comment] 2018-09-14 23:00
So I haven't run any tests yet, but I suppose adding `compare-to-branch` in the `menu-update.ts` file did the job. 

![screen shot 2018-09-15 at 4 25 42 am](https://user-images.githubusercontent.com/24617297/45578506-ac9bc280-b89f-11e8-86f4-65879b8a8c6d.png)

@tierninho As I'm sure you'll notice, the dialog is transparent. I got the following warning in my terminal while running the dev build:
`GitHub Desktop-dev[9528:93939] *** WARNING: Textured window <AtomNSWindow: 0x7feabd55fb00> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

Did a little bit of digging but couldn't find anything relevant. May I know what's happening here?

**Comment by shiftkey** [comment] 2018-09-16 15:53
@kanishk98 don't worry about that message, it's something that will be fixed as part of the upcoming Electron 3.0 release: https://github.com/electron/electron/issues/12814#issuecomment-421208525

**Comment by kanishk98** [comment] 2018-09-17 04:59
@shiftkey Sure, I'll ignore the message, no problem, but I'm troubled that the dialog is actually transparent. 
According to https://github.com/electron/electron/issues/11150#issue-274913410 this problem occurs when `titleBarStyle = hidden`, which does seem to be the case on Desktop. 
I think I'm missing something here.

**Comment by shiftkey** [comment] 2018-09-17 11:20
@kanishk98 that's not a new warning, and Desktop has been working fine despite it over many different builds of Electron which display that warning 🤷‍♂️

**Comment by tierninho** [comment] 2018-09-17 16:36
Can one of the Desktop devs chime in please? Thanks.

**Comment by shiftkey** [comment] 2018-09-17 16:40
@kanishk98 feel free to push a PR if you're satisfied with the fix. I've not been able to reproduce the issue with the current dialogs on my macOS environment.

**Comment by shiftkey** [comment] 2018-09-18 14:55
@kanishk98 @tierninho I think the issue with the dialog isn't that they're transparent, but running Node 10 introduces issues with `node-sass` - #5644 is the correct fix for that, if you're not able to downgrade to Node 8. But i'm not worried about that for the scope of this PR.

**Comment by billygriffin** [comment] 2018-11-28 23:14
This appears to have been fixed in #5673 so I'm going to close it now 😄

**Closed by billygriffin** 2018-11-28 23:14 UTC
Labels: good first issue, help wanted
