### ISSUE TITLE
Feature Request: Cherry-Picking commits from another branch

### ISSUE THREAD

**Issue by kiuru** [desktop/desktop#1685] opened 2017-05-22 11:52 UTC
### Description

Would be great if I could cherry-pick commits from another branch. That would be very useful and often used feature in our company.

### Version

**GitHub Desktop version:** 0.5.7
**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

For example, I would like to select "cherry-pick..." and then it opens window where I could tag specific commits from another branches to my active branch.

And same thing step-by-step:

1. Select "Branch" tab from client's toolbar and select "cherry-pick...".
1. New window opens where I can tag specific commits from another branches to my active branch.

**Comment by nathanpitman** [comment] 2017-05-23 15:36
Something I have requested many times for the old desktop client so adding my vote here to see this become a reality in the new GitHub Desktop. 👍

**Comment by kiuru** [comment] 2017-05-24 09:36
@nathanpitman Do you have any good advice how to reproduce this new feature to project contributors? Is my example good enough or will come to mind some better one? I thought that was the best one.

**Comment by nathanpitman** [comment] 2017-05-24 09:59
Here's how it worked in GitBox (my previous fave OS X Git client):

![screen shot 2017-05-24 at 10 56 13](https://cloud.githubusercontent.com/assets/694545/26397909/b74405ca-406f-11e7-972f-9b54ea21f039.png)

1. Pick branch you want to cherry pick from on the right in the title bar (development).
2. Commits which are not in the branch on the left (master) are denoted with a blue marker in the commit list
3. Right click on a commit with a blue marker and then choose 'Cherry-pick' from the context menu
4. This commits the 'commit' you cherry picked to the local branch
5. Switch branch on the right back to origin/master and push changes
6. Done

Pretty quick and easy. :)

**Comment by kiuru** [comment] 2017-05-24 10:29
Sorry for my lack of understanding, but when I choose "origin/development" on the right in the title bar, does it means commits on below (in the middle of screen) will update according to this branch?

That function is not available at this moment on GitHub Desktop client. Is there anything else good reasons than cherry-pick why they should also add this function to client?

I mean I trying to figure out the most easily way to implement cherry-pick to the current version of client. :)

**Comment by nathanpitman** [comment] 2017-05-24 10:38
I don't really care how it's implemented, so long as there is a low friction way to cherry pick a commit and merge it into another branch. :)

**Comment by loukia** [comment] 2017-05-26 05:52
As an feature in UI, this could also be a improvement on current feature "Branch / Merge into current branch".

![image](https://cloud.githubusercontent.com/assets/25928312/26482505/80352ad2-41f0-11e7-81c3-3578962994a9.png)

In 0.5.8, there is a text which says for example "This will bring in 7 commits from **master**". You can select "Merge into **current branch**" or close the window.

If there would be possibility to **view and select** (i.e cherry-pick) from these commits, it would be a great solution for this feature request.

**Comment by joshaber** [comment] 2017-06-29 20:39
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Comment by MaximilienRedemption** [comment] 2017-08-30 17:13
Cherry picking please.

**Comment by ratebeerjoet** [comment] 2017-10-25 20:09
Yes, it would be great to be able to select and deselect which commits should be included. A simple checkbox and an option to "[ X ] De/Select All" at the top that you can click once to select all and click again to deselect all.

**Comment by hagaic** [comment] 2017-12-25 11:49
Please add this feature

**Comment by dayleparker** [comment] 2018-01-03 06:32
+1, I would love to see this implemented.

**Comment by thenninger** [comment] 2018-01-04 16:59
+1 Yes, Please! I need this right now actually.

**Comment by sungjin0213** [comment] 2018-01-18 15:25
+1 Please add cherry picking! I'm using two different apps for source repository because of this.

**Comment by okoethibm** [comment] 2018-02-22 09:53
+1 here. These "advanced" features are the reason for using a stand-alone git client in the first place.

**Comment by aquinn** [comment] 2018-02-28 14:38
Would really like to see this feature also.

**Comment by ha404** [comment] 2018-03-07 22:39
Please, let it be drag and droppable like in Tower :)

**Comment by madelineearp** [comment] 2018-03-13 15:29
+1

**Comment by mandibuswell** [comment] 2018-04-13 04:40
+1

**Comment by RamanHalaburda** [comment] 2018-04-13 13:28
+1

**Comment by j-f1** [comment] 2018-04-13 13:30
Please use the 👍 button on the original comment in the issue instead of commenting +1 so people subscribed to this issue don’t get unnecessary notifications.

**Comment by fabatista** [comment] 2018-05-10 13:08
Yeap I agree!

**Comment by sffc** [comment] 2018-10-10 06:29
+1, and please make sure to support the `-x` option in git cherry-pick.

**Comment by nathanpitman** [comment] 2018-10-31 09:15
Having this in the desktop client or the website would be awesome. Cherry pick is such a useful feature, esp when working between many branches and larger teams.

**Comment by thenninger** [comment] 2018-10-31 14:00
@kiuru Why is this issue closed? Is it not a valid enhancement?

**Comment by kiuru** [comment] 2018-10-31 18:56
@thenninger This request has future-proposal label. Team GitHub said this is beyond the scope of their current roadmap, and they are going to revisit this later. GitHub didn't want to keep this on their backlog and that's why it's closed.

**Comment by kristianjaeger** [comment] 2019-07-31 16:04
+1 please add this!

**Comment by thanhgb** [comment] 2019-10-10 02:01
+1 
I really want this feature, please add it in roadmap.

**Comment by AdamDiament** [comment] 2019-11-06 14:30
Please add this!

**Comment by SylwesterZarebski** [comment] 2019-12-10 13:30
Closed `future proposal` for more than 2 years ago. This Github representational client is almost dead by design (looks like it is modified by few persons in private time after work, not large corporation).

**Comment by alexanderadam** [comment] 2019-12-10 13:52
> This Github representational client is almost dead by design (looks like it is modified by few persons in private time after work, not large corporation).

What makes you think like that?
As far as I can see, [it is actively maintained and by the GitHub staff](https://github.com/desktop/desktop/commits/development).

IMHO it's just the policy that's "wrong". [Closing an issue](https://github.com/desktop/desktop/issues/1685#issuecomment-312099238) that isn't a `wontfix` (or similar) is the wrong way in my opinion.

Also the label `future-proposal` [is not a relevant label for this project](https://github.com/desktop/desktop/blob/development/docs/process/labels.md) and I guess it is therefore additionally ignored.

As a user it is very difficult to follow the development here.
I have a similar impression of the [Linux support](https://github.com/desktop/desktop/issues/1525) here: [it is still recommended to use the fork that lives outside of this repository](https://github.com/desktop/desktop/blob/93369aaa3ce7e50945a36c62fecf5203ed8c5bd9/docs/contributing/linux-testing-and-you.md#testing-release-candidates) (although it is working great).

**Comment by SylwesterZarebski** [comment] 2019-12-10 14:26
Why? Because it is very bad habit to close issues to *keep backlog simple* and many of `feature proposals` lies in this grave. What is worse, most of them are essential to even think to use this software as console replacement.

**Comment by alexanderadam** [comment] 2019-12-10 14:34
You probably didn't read properly.

1. I didn't ask "why".
2. I asked what makes you think that it "looks like it is modified by few persons in private time after work".

**Comment by SylwesterZarebski** [comment] 2019-12-10 14:51
Because small private projects have many bad habits like this one. Isn't it obvious? Just look around.

**Comment by niik** [comment] 2019-12-10 15:15
Hey folks, let's keep this focused on the issue at hand please. We're well aware that cherry-picking is an important part of the toolbox for a lot of users and I understand that it's particularly meaningful for many of you who have responded in this thread. We've all had times when we wish the tools we use would just have that one feature that means the most to us.

If we can't maintain a respectful tone and stay focused on the issue we're going to have to lock this thread which isn't something we like to do as it eliminates the possibility for people to explain their use cases and offer insight that helps us prioritize features and provides context for how we can best solve the problem if/when we choose to pick up the issue.

If you'd like to add your +1 for this feature please do so by adding an emoji 👍 reaction at the top of this page.

I'm going to minimize recent comments that are either unrelated to this issue and/or aren't written in a respectful tone and I hope we can leave it at that.

**Comment by hron84** [comment] 2019-12-16 13:10
@niik you (GitHub) promised to re-visit this feature later despite it's closed. However, it did not happened since two years. It's not surprising that if a core Git feature used by many developers missing from an official GitHub client makes users disappointed. 

While I totally agree the comments without respectful tone can be avoided, please provide us a deeper insight when do you plan to take a look into this feature or what can we expect about it. 

Also, closing a feature makes a bad message for developers that you aren't interested in this issue. GitHub on its own provides a numerous ways to manage your backlog either by making a Project that can contain issues only that meant to be on the backlog, or making Milestones. Closing isn't a neccessary part of this workflow and keeping these tickets open says us you are still keep this feature in your mind.

**Comment by daikhioualid** [comment] 2020-01-16 07:49
+1 please add this!

**Comment by rahul-desai3** [comment] 2020-02-24 23:40
+1 please add this feature

**Comment by pwp333** [comment] 2020-03-12 17:41
This is the missing feature in github. Other competitors already have it.

**Comment by wreiske** [comment] 2020-03-24 19:08
We need this for GitHub Enterprise Server! 

https://github.community/t5/How-to-use-Git-and-GitHub/Feature-request-Cherry-pick-commits-from-UI/m-p/20745/highlight/false#M6125

**Comment by hottestchilipepper** [comment] 2020-03-26 13:24
I made it. Please review the pull request. Thank you

**Comment by nathanpitman** [comment] 2020-03-26 17:17
Superb @hottestchilipepper - what do we have to do to get this merged in @joshaber?

**Comment by say25** [comment] 2020-03-26 19:40
Josh isn't working on Desktop right now. But @desktop/engineering should be able to weigh in.

**Comment by wreiske** [comment] 2020-03-26 19:54
Now we just need it in GitHub.com and GitHub Enterprise Server! Thanks @hottestchilipepper for your work on the desktop app.

**Comment by outofambit** [comment] 2020-04-03 20:56
Please see https://github.com/desktop/desktop/pull/9362#issuecomment-608653710 for context. Thank you!

**Comment by nerdneha** [comment] 2020-04-03 22:32
Hello 🍒! We've reopened this issue to gather more information around your use cases for cherry-picking.  We're interested in hearing the following from you:
* when you use cherry-picking today
* how frequently you cherry-pick
* is there anything you do consistently before or after cherry picking
* whether there's any required parts of cherry-picking by your team or repo (ex: my team/repo requires we do ____ as part of our process)

**Comment by ha404** [comment] 2020-04-03 22:45
- I use it whenever I need to transfer a feature into another branch for whatever reason
- This occurs maybe ~1-2 a week
- I like to see if there are any conflicts that occur, if any, I'll choose to either abort or fix the conflicts
- I'm used to squashing changes into `master` so there aren't any precursor things we'd have to do

**Comment by say25** [comment] 2020-04-03 23:07
@nerdneha In my own experience, we still use release branches for one of our deployables. In that case, we occasionally need to pull a changeset that already is on master into our release branch. This is a workflow we are looking to deprecate as we move to CI/CD and/or release tags

**Comment by davidcornewell** [comment] 2020-04-04 01:31
We cherry-pick commits between branches several times a week. We require that a pull request be made targeting the branch to review. Bitbucket had a plugin PR Booster that let us cherry-pick to a branch VIA a pull request. We could then cherry-pick any additional commits to that PR branch.

**Comment by hottestchilipepper** [comment] 2020-04-04 05:18
In service branches, it is very useful.
We have a project which is release to iOS and Android markets. We have 'master', 'service-ios', 'service-android' and 'hotfix'. We develop on 'master' branch. When some problems are noticed, we make a commit to fix it and push on 'master' branch. But if the problem is serious enough that users cannot use the application, we have to make hotfix. So we cherry-pick only some commits from 'master' to 'hotifx', to not to merged all changes from 'master' to application in service. Then merge 'hotfix' to 'service-ios' and 'service-android'.
Sometimes, some commits should be cherry-picked from 'master' to 'service-ios' or 'service-android' specifically, which is emergency by specific market's policy.

**Comment by dbking77** [comment] 2020-04-06 23:41
We (used to) cherry-pick 3-4 times a week.  Often a "smallish" bug fix the was found on the master branch would get back-ported to 1 or 2 "stable" releases that were in use by customers.   There were almost never "merge" conflicts with these small cherry-picks   
With this cherry-pick feature, we woul still wanted github hooks and PRs to be created for each one, so they got CI test, and possible approval.

**Comment by JonKohler** [comment] 2020-04-09 00:06
While we are currently a large GitHub customer for the majority of our SCM estate, with the one large exception of a large mono repo that powers a key component of one of our products. That lives (for now) in Gerrit. I'd have to run some stats, but I'd say (easily) we use the "Cherry Pick" button in the Gerrit UI 100+  _**per day**_. 

We've got a "mainline" branch of code that is our primary landing zone for code, and we've got release branches for many different iterations of code that we ship to customers. 

The code landing into mainline could either feature/enhancements that will bake there until the next branch cut/release or they could be bug fixes/patches that have been found to impact customers. 

We always have multiple release branches open, similar in concept to Windows 7, 8, 10, etc where customers may be running a particular release train and do not want to do a major upgrade to get one single patch release. 

As such, When we have a customer-impacting bug/issue, we'll patch it in mainline, then use Gerrit cherry pick to port it over to a release branch (or many release branches).

Gerrit makes this _**extremely**_ easy since its just a single button. Gerrit (otherwise) is a bit of a PIA, so if it sniffs even the smallest of merge conflicts it will choke and die, but by and large the majority of these work just great.

**Comment by AdamDiament** [comment] 2020-04-09 05:27
I use gitkraken for this - it has great features such as cherry picking and stashing capabilities, plus a solid modern UI lacking from something like source tree.

**Comment by kristianjaeger** [comment] 2020-04-10 19:57
The main use case I can think of at the moment is when you want to only take your changes into master.  So, if for example if someone has the typical feature -> develop -> master branch pattern there are times when folks do not follow a good practice and have things in develop too long and one might not know if they are stable or not to merge to master. So it would be great to reduce risk and cherry pick in those odd, unfortunate, circumstances. Thanks.

**Comment by mhanley00** [comment] 2020-05-13 16:04
My clients would use GUI cherry-picking frequently to make text updates to config/json files that need to flow into multiple branches. Currently for these updates, they make the same changes to multiple branches (we can have up to 3 different dev branches with hooked up to different services at any given time) and it would be awesome if they could just click a button in GitHub to cherry-pick those same changes to multiple branches!

**Comment by CeuxDruman** [comment] 2020-07-09 21:13
- when you use cherry-picking today: As part of our continuous delivery and agile/scrum processes, we have several "live" releases at the same time but at different environments or status, so every time we make a hot-fix for any of that releases, we have to cherry-pick that hot-fix to the other "live" ones (branches).

- how frequently you cherry-pick: Once/Twice per hot-fix.

- is there anything you do consistently before or after cherry picking: Before: Pushing a hot-fix to one of the live branches. After: Creating a new tag (optional: depending on the target release branch status)

- whether there's any required parts of cherry-picking by your team or repo (ex: my team/repo requires we do ____ as part of our process): It is required a Pull Request for approving the cherry-pick in the same way we do with a normal commit/branch.

**Comment by ladas-larry** [comment] 2020-09-08 14:07
We use cherry-pick to include hotfixes into the release branch. That happens every week.

**Comment by shinchan305** [comment] 2020-09-15 21:48
+1 please add this feature

**Comment by cdobrescu-ionos** [comment] 2020-12-11 16:29
+1 please add this feature

**Comment by thanhkaiba** [comment] 2020-12-16 08:57
+1 please add this feature

**Comment by HendryLeo** [comment] 2020-12-29 09:42
+1 please add this feature

**Comment by primadance** [comment] 2021-01-29 17:48
It's 2021 and no Cherry-pick feature yet?

**Comment by CyrilMazur** [comment] 2021-01-30 08:44
I just opened back my old version of Git Tower to cherry-pick one commit 😅

**Comment by say25** [comment] 2021-01-30 23:52
This was recently added to the roadmap https://github.com/desktop/desktop/pull/11484 can’t say it will be tomorrow but it’s coming soon.

**Comment by MiguelRipoll23** [comment] 2021-02-07 13:04
It’s great to see that this feature will arrive at some point, however is a little bit upsetting that these kind of features can’t be provided by the community using extensions like VS Code.

Most of the most up-voted features are stalled, I understand that the development team is small and product decisions should be taken as all feature suggestions can’t be added. That’s exactly why I think extension support is a must for GitHub Desktop.

Anyways, happy to see cherry-picking support coming someday. Don’t take my comment as criticism, I love GitHub Desktop as it is but I’d like to see it less limited.

**Comment by kurtextrem** [comment] 2021-02-15 11:39
Please don't forget this PR: https://github.com/desktop/desktop/pull/9362, not sure if it is majorly outdated by now (~1 year old PR), but at least someone implemented first-steps towards cherry-picking already.

**Comment by tidy-dev** [comment] 2021-02-16 11:11
@kurtextrem Thank you for the reference! I am working on the new Cherry Picking feature and have read through that PR. However, as can be read in the comments of the PR, it doesn't quite follow the design pattern we would like to implement. But, no worries cherry picking is under way!

**Comment by JonKohler** [comment] 2021-02-16 13:25
@tidy-dev any chance the web UI gets love at the same time?

**Comment by tidy-dev** [comment] 2021-02-16 14:16
@JonKohler My work is scoped to the GitHub Desktop app and I have not heard any word of GitHub.com adding cherry picking. Sorry to disappoint on that aspect. But, hopefully you can enjoy it on GitHub Desktop soon. 🙂

**Closed** 2021-03-11 12:57 UTC
Labels: enhancement

**Comment by billygriffin** [comment] 2021-03-17 23:38
Hi folks! We've released most of the cherry picking work to the beta version, though we are planning to iterate on a few things with the drag and drop flow in the next few days. Would anyone who would use cherry picking in Desktop be interested in doing a 30 minute usability test with us to see how the flow feels on beta? If you aren't using the beta, you can download it here: https://github.com/desktop/desktop#beta-channel

Also, if you have a chance to use it, please feel free to respond here as well with feedback. ❤️

**Comment by Seb33300** [comment] 2021-03-30 08:24
Can someone please explain how cherry picking works?

Just installed the update, but the only change I can find if a `New` badge on the `History` tab (I don't know why, nothing changed since the previous version except that the diff was on slip mode by default instead of unified).
And nothing related to cherry picking in context menus.

**Comment by Seb33300** [comment] 2021-03-30 10:03
Fixed in 2.7.1

**Comment by tidy-dev** [comment] 2021-03-30 11:07
@Seb33300 Sorry for the confusion! As @Seb33300 said, cherry-picking is in release 2.7.1 now!

**Comment by uguraktas** [comment] 2021-03-30 11:22
> @Seb33300 Sorry for the confusion! As @Seb33300 said, cherry-picking is in release 2.7.1 now!

Expected feature 🎉
