### ISSUE TITLE
"GitHub Desktop has unexpectedly quit" at every launch

### ISSUE THREAD

**Issue by fbitterlich** [desktop/desktop#14038] opened 2022-03-01 15:01 UTC
### Describe the bug
On every launch, I get a sytem message saying "GitHub Desktopn has unexpectedly quit", even though the app appears to be running fine. (Is there maybe a background process with the same name that has crashed?)

### Version & OS

GitHub Desktop 2.9.10 (x64)
macOS 10.15.7 on Intel iMac

### Steps to reproduce the behavior

Click Github Desktop icon in the dock to launch it

### Expected behavior

Just the app launching

### Actual behavior

App launches, but system shows message "Github Desktop has quit unexpectedly" ("GitHub Desktop wurde unerwartet beendet.")
The app itself appears to be running, though.

### Screenshots

Screenshot showing error message and app running behind it.
![Bildschirmfoto 2022-03-01 um 15 50 27](https://user-images.githubusercontent.com/22008998/156192499-7579346b-9317-4b5d-b904-1f7a8bbfa23b.png)

### Logs

Crash log (partial) and app log attached.

#### Crash log
Process:               GitHub Desktop [4607]
Path:                  /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
Identifier:            GitHub Desktop
Version:               2.9.10 (2.9.10)
Code Type:             X86-64 (Native)
Parent Process:        GitHub Desktop [4606]
Responsible:           GitHub Desktop [4606]
User ID:               504

Date/Time:             2022-03-01 15:51:50.252 +0100
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Anonymous UUID:        080F01E8-6D8E-04B0-1A08-9BA1F581C023

Time Awake Since Boot: 17000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [4607]

VM Regions Near 0x20:
--> 
    __TEXT                 000000010e2a1000-000000010e2a3000 [    8K] r-x/r-x SM=COW  /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop

Application Specific Information:
crashed on child side of fork pre-exec

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_malloc.dylib        	0x00007fff73595e41 nanov2_forked_calloc + 7
1   libsystem_malloc.dylib        	0x00007fff73580f59 malloc_zone_calloc + 99
2   libsystem_malloc.dylib        	0x00007fff73580ed9 calloc + 24
3   libobjc.A.dylib               	0x00007fff72215603 allocateBuckets(unsigned int) + 29
4   libobjc.A.dylib               	0x00007fff72215096 cache_fill + 283
5   libobjc.A.dylib               	0x00007fff72214b27 lookUpImpOrForward + 530
6   libobjc.A.dylib               	0x00007fff72214399 _objc_msgSend_uncached + 73
7   libxpc.dylib                  	0x00007fff7361f89e xpc_atfork_child + 125
8   libSystem.B.dylib             	0x00007fff703aeab8 libSystem_atfork_child + 59
9   libsystem_c.dylib             	0x00007fff734288ad fork + 40
10  com.github.Electron.framework 	0x0000000115c781ef uv_spawn + 527
11  com.github.Electron.framework 	0x000000011c4049d1 node::PromiseRejectCallback(v8::PromiseRejectMessage) + 234001
12  com.github.Electron.framework 	0x0000000116cbc26b v8::internal::Accessors::MakeAccessor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Name>, void (*)(v8::Local<v8::Name>, v8::PropertyCallbackInfo<v8::Value> const&), void (*)(v8::Local<v8::Name>, v8::Local<v8::Value>, v8::PropertyCallbackInfo<v8::Boolean> const&)) + 12651
13  ???                           	0x0000002f07f0aa38 0 + 201996675640
14  ???                           	0x0000002f07e8c862 0 + 201996159074
15  ???                           	0x0000002f07e8c862 0 + 201996159074
16  ???                           	0x0000002f07e8c862 0 + 201996159074
17  ???                           	0x0000002f07f5ab62 0 + 201997003618
18  ???                           	0x0000002f07e89dcf 0 + 201996148175
19  ???                           	0x0000002f07fab9b6 0 + 201997334966
20  ???                           	0x0000002f07e8c862 0 + 201996159074
21  ???                           	0x0000002f07e8c862 0 + 201996159074
22  ???                           	0x0000002f07e8c862 0 + 201996159074
23  ???                           	0x0000002f07e8c862 0 + 201996159074
24  ???                           	0x0000002f07e8c862 0 + 201996159074
25  ???                           	0x0000002f07e8c862 0 + 201996159074
26  ???                           	0x0000002f07e8c862 0 + 201996159074
27  ???                           	0x0000002f07e8c862 0 + 201996159074
28  ???                           	0x0000002f07e8c862 0 + 201996159074
29  ???                           	0x0000002f07e8c862 0 + 201996159074
30  ???                           	0x0000002f07e8c862 0 + 201996159074
31  ???                           	0x0000002f07e8c862 0 + 201996159074
32  ???                           	0x0000002f07e8c862 0 + 201996159074
33  ???                           	0x0000002f07e8c862 0 + 201996159074
34  ???                           	0x0000002f07e8c862 0 + 201996159074
35  ???                           	0x0000002f07e8c862 0 + 201996159074
36  ???                           	0x0000002f0004c24f 0 + 201863774799
37  ???                           	0x0000002f07e8c862 0 + 201996159074
38  ???                           	0x0000002f07e8c862 0 + 201996159074
39  ???                           	0x0000002f07e8c862 0 + 201996159074
40  ???                           	0x0000002f07e8c862 0 + 201996159074
41  ???                           	0x0000002f07e8c862 0 + 201996159074
42  ???                           	0x0000002f07e8c862 0 + 201996159074
43  ???                           	0x0000002f07e8a89c 0 + 201996150940
44  ???                           	0x0000002f07e8a5c7 0 + 201996150215
45  com.github.Electron.framework 	0x0000000116d8bafc v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) + 684
46  com.github.Electron.framework 	0x0000000116c69239 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) + 713
47  com.github.Electron.framework 	0x000000011c2e793c node::EmitAsyncDestroy(node::Environment*, node::async_context) + 273612
48  com.github.Electron.framework 	0x000000011c2e8a7d node::EmitAsyncDestroy(node::Environment*, node::async_context) + 278029
49  com.github.Electron.framework 	0x000000011c2e87cb node::EmitAsyncDestroy(node::Environment*, node::async_context) + 277339
50  com.github.Electron.framework 	0x000000011c2a25ed node::LoadEnvironment(node::Environment*, std::__1::function<v8::MaybeLocal<v8::Value> (node::StartExecutionCallbackInfo const&)>) + 109
51  com.github.Electron.framework 	0x0000000115dd3ca7 v8::CodeEvent::GetScriptName() + 197335
52  com.github.Electron.framework 	0x0000000115d4cf3a v8::internal::compiler::RawMachineAssembler::TargetParameter() + 8970
53  com.github.Electron.framework 	0x0000000117d970df v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5180991
54  com.github.Electron.framework 	0x0000000117d9a8a8 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5195272
55  com.github.Electron.framework 	0x0000000117d967f8 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 5178712
56  com.github.Electron.framework 	0x0000000115f50055 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 1957
57  com.github.Electron.framework 	0x0000000115f51223 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 6515
58  com.github.Electron.framework 	0x0000000115f50ca1 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 5105
59  com.github.Electron.framework 	0x0000000115f4f25d v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 12173
60  com.github.Electron.framework 	0x0000000115f4fb93 v8::internal::ExternalReference::fast_c_call_caller_pc_address(v8::internal::Isolate*) + 739
61  com.github.Electron.framework 	0x0000000115c82be8 ElectronMain + 152
62  libdyld.dylib                 	0x00007fff733c8cc9 start + 1

#### App log

2022-03-01T14:49:51.271Z - info: [ui] [AppStore] loading 4 repositories from store
2022-03-01T14:49:51.271Z - info: [ui] [AppStore] found account: fbitterlich (Frank Bitterlich)
2022-03-01T14:49:51.359Z - info: [ui] [BranchPruner] Last prune took place in an hour - skipping
2022-03-01T14:49:51.488Z - info: [ui] Subscribed 'fbitterlich' to Alive channel
2022-03-01T14:49:52.365Z - info: [ui] launching: 2.9.10 (Mac OS 10.15.7)
2022-03-01T14:49:52.366Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2022-03-01T14:51:50.992Z - info: [ui] [AppStore] loading 4 repositories from store
2022-03-01T14:51:50.993Z - info: [ui] [AppStore] found account: fbitterlich (Frank Bitterlich)
2022-03-01T14:51:51.163Z - info: [ui] [BranchPruner] Last prune took place in an hour - skipping
2022-03-01T14:51:51.345Z - info: [ui] Subscribed 'fbitterlich' to Alive channel
2022-03-01T14:51:51.905Z - info: [ui] launching: 2.9.10 (Mac OS 10.15.7)
2022-03-01T14:51:51.905Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2022-03-01T14:54:19.055Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 0.7s of which 0.0s paused, total 0.7s

### Additional context

None.

**Comment by sergiou87** [comment] 2022-03-01 15:42
Thanks for your report @fbitterlich! ❤️ 

I believe this is a duplicate of #13974 that has been addressed in #14034. We'll try to deploy a new release with this fix soon. Sorry about this inconvenience and thanks for your patience 🙇‍♂️

**Closed as completed by sergiou87** 2022-03-01 15:42 UTC
