### ISSUE TITLE
partial links in commits are clickable and do not go to expected location

### ISSUE THREAD

**Issue by shiftkey** [desktop/desktop#6690] opened 2019-01-22 22:54 UTC
## Description

The way GitHub Desktop renders links in the commit history does not consider whether it's a valid URL, and the user can click through to a non-existent repository.

## Version
* GitHub Desktop: 1.6.0
* Operating system: macOS

## Steps to Reproduce
1. Clone this repository to your local machine: https://github.com/BotsBurgh/BOTSBURGH-FTC-2018-19
2. Switch to the history tab and select the commit `754ce5b27a4066a208df4d4293d2aa194a1787ce`. Notice that a link is rendered in the commit summary.

<img width="1008" src="https://user-images.githubusercontent.com/359239/51570720-3ffc8a00-1e76-11e9-9056-655dc3e1d2e0.png">

### Expected Behavior

Two ideas: 
 - the `...` in the URL should be a flag for "oh, this isn't a working URL" and the link isn't rendered 
 - the app stitches together the URL that was split in two so the link works, while retaining the formatting

### Actual Behavior

The user can click the link and be navigated to URL ending in `...` which just 404s

<img width="625"  src="https://user-images.githubusercontent.com/359239/51570900-cc0eb180-1e76-11e9-8263-dcf3c192ebaf.png">

## Additional Information

This feels like a side-effect of us emulating how GitHub the website renders commits. Here's what you see for the [commit in question](https://github.com/BotsBurgh/BOTSBURGH-FTC-2018-19/commit/754ce5b27a4066a208df4d4293d2aa194a1787ce):

<img width="762" src="https://user-images.githubusercontent.com/359239/51427105-00117a80-1bca-11e9-8fcf-3cfa7b84afc6.png">

Note that the second half of the split URL in the commit description is a working link 🤷‍♂️. 

Viewing the commit in Git shows the unmodified URL on one line (with no description)

```shellsession
$ git show 754ce5b --format=medium
commit 754ce5b27a4066a208df4d4293d2aa194a1787ce
Merge: 968a86a 17403d7
Author: nitsl <niteshramanathan@gmail.com>
Date:   Fri Jan 18 19:05:10 2019 -0500

    Merge branch 'master' of https://github.com/BotsBurgh/BOTSBURGH-FTC-2018-19
```

### Logs

N/A

**Comment by tidy-dev** [comment] 2024-09-18 14:10
Unable to reproduce (Even able to merge the repo in the reproduction steps.) This was likely addressed in the refactor of the commit details header.

**Closed by tidy-dev** 2024-09-18 14:10 UTC
Labels: bug, priority-3
