### ISSUE TITLE
Github  Desktop is very slow

### ISSUE THREAD

**Issue by FireCulex** [desktop/desktop#7108] opened 2019-03-18 02:00 UTC
## Version

* GitHub Desktop:

* Operating system:

### Logs

![GitHubDesktop_2019-03-17_18-59-10](https://user-images.githubusercontent.com/9983630/54502234-c2d61a00-48e6-11e9-8fe9-ce09444e77f1.png)

It can easily take over a minute to fetch and push something as simple as changing 1 byte.
Whats with the massive idle time?

**Comment by tierninho** [comment] 2019-03-18 17:36
@FireCulex In order to help resolve your issue, please fill out the template above. 

We need the information as it may be relevant in determining the underlying problem. Thanks for meeting us halfway 😄

**Comment by tierninho** [comment] 2019-03-20 20:20
@FireCulex As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Comment by FireCulex** [comment] 2019-03-21 03:46
Github Desktop 1.6.5 Windows 10
Change 1 byte, Fetch, Push, or even Pull
Expected: to be more responsive
Actual: long delay, performance shows mostly idle.
I'm quite adept at hacking but troubleshooting information is either outdated or scarce. If you could point me in the right direction?

**Comment by FireCulex** [comment] 2019-03-21 13:33
[2019-03-21.desktop.production.log](https://github.com/desktop/desktop/files/2992227/2019-03-21.desktop.production.log)
just loading the program has to wait on refreshing the repository. very slow.

**Comment by tierninho** [comment] 2019-03-21 17:53
@FireCulex Thanks for the update. 

Unfortunately nothing stands out in your logs. Were do doing anything in Desktop in particular or is it slow all around? How is the performance of other applications running at the same time? 

I did see the mention of ~20MB being processed in your pic. Not a huge amount but perhaps a clue. 🤷‍♂️The Network tab in the dev tools may serve up some additional context as well.

**Comment by FireCulex** [comment] 2019-03-21 21:51
The application itself isn't unresponsive and the swirling icon works just fine. I can commit to master, then it takes 5s-10s then  push origin will show up, then I press it and it swirls and says Hang on... Then it fetches, then it refreshes repository Individually the delay isn't so bad, its just at each step it accumulates.
I couldn't tell you what the ~20MB is about since each repository is under 300k.

**Comment by tierninho** [comment] 2019-03-21 23:03
cc @desktop/support Any thoughts on this one?

**Comment by steveward** [comment] 2019-03-22 00:11
I've actually got a user I'm corresponding with via email who is hitting similar perf issues. Unfortunately these types of issues can be difficult to reproduce and diagnose. I do see some high fetch times in the log:

```
2019-03-21T13:26:00.073Z - info: [ui] Executing getRemotes: git remote -v (took 31.581s)
2019-03-21T13:26:00.428Z - info: [ui] Background fetch for 3 repositories took 185.113sec
```

That fetch is taking almost 3 minutes for three repositories. I have seven repositories and a fetch takes around 2-5 seconds on average.

@FireCulex Do any of these repositories have a large number of branches? Also, how is performance for you when working with this repository from the command line? If you have not tested that out could you try running `git fetch --progress --prune origin` to see if you are able to replicate these performance issues on the command.

**Comment by lYesterdaYl** [comment] 2019-03-22 19:44
I also just installed this....My pc got reset, so I have to reinstalled this. The version I used earlier didn't have this lag issue at all, but this version is very slow, viewing commit, push, pull etc.

**Comment by tierninho** [comment] 2019-03-22 20:58
@lYesterdaYl Please up your comment with some more detail, like OS, desktop version, steps if relevant, and any other info you can share that might help us find the root of the issue. As Steve mentioned, these types of issues can be difficult to reproduce and diagnose. Thanks in advance.

**Comment by lYesterdaYl** [comment] 2019-03-22 23:56
@tierninho Hi, I am using Win 10. The system is up to date, but this also happened on my other pc which is also Win 10 but not up to date. I used choco command in CMD to installed version 1.5 later, and the app doesn't have any lag anymore. So, I believe the lagging issue is only happening the latest version.

**Comment by FireCulex** [comment] 2019-03-26 07:33
@steveward git clone from the cmdline is instantaneous as is the other git commands. 
```
$ time git fetch 

real	0m0.450s
user	0m0.025s
sys	0m0.026s

```

versus `Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 65.745s)`

**Comment by outofambit** [comment] 2019-07-11 21:32
is anyone still experiencing this in a more recent version of GitHub Desktop (like v2.1.0)?

**Comment by a-tambov** [comment] 2019-07-30 00:05
Hi, I've been experiencing this issue for many months. I always update immediately to the latest version, currently on GitHub Desktop 2.1.0. I'm on Windows 10 with latest updates as well. 

Here is an extract from the logs:
==============================================
2019-07-29T23:47:45.566Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: XXXXXXXXXXXXXXXXXXXXXX - XXXXXXXX (has token)
2019-07-29T23:48:33.483Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin feature/XXXXXXXX:feature/XXXXXXXX --progress (took 47.863s)
2019-07-29T23:49:18.888Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 45.350s)
==============================================

push and fetch take 47 and 45 seconds, when I use command line on the same repository it is only 1-3 seconds.

I work with 5 repositories in GitHub Desktop, it doesn't depend on repository, every repository fetch, pull and push always slow from GitHub Desktop and quick from command line.

Happy to answer further questions if there any. Cheers.

**Comment by tierninho** [comment] 2019-07-30 01:06
@a-tambov Thanks for sharing. 

Is there any other relevant information about your repositories or setup? Is there a large amount of data in your repositories? Maybe you are using a slow internet connection? Are you using a VPN or proxy server? 

Any repo you want to share so we can clone? Unfortunately, these types of issues can be difficult to reproduce and diagnose.

**Comment by a-tambov** [comment] 2019-07-31 03:01
Main repository is quite big, monthly stats is like this:
17 authors have pushed 199 commits to XXXXXXX and 225 commits to all branches. On XXXXXXX, 426 files have changed and there have been 14,208 additions and 3,375 deletions.

I can't reveal any specific information about the repos, but it seems that the issue doesn't depend on the size of them. On smaller repos issue still the same, it takes long time, about a minute to do pull, push, fetch from the UI and seconds to do the same from command line, so I guess it has nothing to do with the speed of the internet connection.

Typical operation from command line like this, was done in seconds. Same action from the GitHub Desktop would have taken about a minute, this issue very consistent.

$ git push --set-upstream XXXXXXX feature/XXXXXXXXXXXX
Counting objects: 11, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (11/11), done.
Writing objects: 100% (11/11), 1.82 KiB | 18.00 KiB/s, done.
Total 11 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 9 local objects.
remote:
remote: Create a pull request for 'feature/XXXXXXXXXXXX' on GitHub by visiting:
remote:      https://github.com/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
remote:
To https://github.com/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * [new branch]          feature/XXXXXXXXXXXX -> feature/XXXXXXXXXXXX
Branch 'feature/XXXXXXXXXXXX' set up to track remote branch 'feature/XXXXXXXXXXXX' from 'XXXXXXX'.

**Comment by a-tambov** [comment] 2019-07-31 03:03
@tierninho I hope this will help, cheers.

**Comment by tierninho** [comment] 2019-07-31 20:13
Thanks for sharing. So far nothing stands out and it will be hard to pinpoint the exact reasoning. Gonna leave this issue open in case more data surfaces from you are other users.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:11
Since Microsoft bought GitHub (why? because he has the money, like 3.500.000.000 paid for simple java lagging Minecraft game, worth 2 million..)
you can expect everything to be corrupted. 
Its a commercial thing.
The big fishes get the food from the open source, then start buying the good stuff and/or corrupt it by trolling everything around.
Like almost nothing works. (Experienced it a lot). 
When you publish a good thing, expect the thing (when using MS functions) stop functioning after the latest update. 
That way they stay in control.
Everything that has potential is corrupted so the normal single programmer gets nuts.

This issue is just a part of the whole.

Follow the money.

Homework:

Clone ReplayMod and try to compile it.

It doesn't work, and the maintainers "never seen that particular error msg and had spend to much time on it, blah blah blah".
But: give source + needed tools + versions -> it should work, compile.

But computer says no.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:15
So, GitHub doesn't work.
You also can not manually upload files over 25MB and/or over 100 files.
Or just lots of files are missing.
Its a boycot of the normal single programming dude's. Otherwise all software would work, and they are out of business.
Like every detail and thought of every aspect in your life is controlled by them.
Denying this statement is part of their mind control program, so you even will defend them.
Microsoft is shit, and everything they create and/or buy will be turned into shit.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:15
These trolls here replying back to you? Its their work to keep you hanging.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:15
Now my account will be flagged.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:16
Uploading with git desktop.
26 kb/s

👎

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:17
More homework:

Build a github yourself. Open source of course. No limits.

**Comment by TheJavaProfessor** [comment] 2019-10-29 18:20
Bill Gates has this psychological disorder. Once he had this little computer with switches that drove him mad, because he can not program it himself.
Now he's doing the same to the world. Everything he touches will drive you mad.
What is windows? A garbage operating system build for viruses build for damage control because of "illegal downloading" software.... You need xbox.

**Comment by DarinBeard** [comment] 2019-12-04 16:32
I will jump on this wagon and say that all three developers working with me have the same slow and laggy issues and two have since stopped using it because the issue is bad enough they prefer to not deal with it.

**Comment by outofambit** [comment] 2019-12-16 20:04
I appreciate the intent behind this issue and the discussion, but I think this is much too broad to get a productive investigation or diagnosis. Let's open new issues for specific performance problems going forward, thank you!

**Closed by outofambit** 2019-12-16 20:04 UTC
Labels: more-info-needed, performance

**Comment by a-tambov** [comment] 2019-12-16 20:21
I confirm the issue has gone. An update (either 2.2.1 or 2.2.2) has fixed it.

**Comment by timeshift-ted** [comment] 2020-07-29 17:00
I have a similar issue. For 10 to 20 seconds program is completely unresponsive for most actions (like starting up, clicking on list of repositories, trying to select the text box to type commit notes, pretty much anything). Can not even select from dropdown menu. Was working great until a few weeks ago and then got extremely slow. On version 2.5.3. Going to switch to GitKraken or another client as it's become basically unusable. Will try again the next time they publish an update to see if issue is fixed. Command line git is fast as usual.

**Comment by steveward** [comment] 2020-07-29 17:14
@timeshift-ted are you on a Windows machine? Are you running any antivirus/security software that could be causing this?

**Comment by timeshift-ted** [comment] 2020-07-29 17:48
Yes, on Windows. No antivirus/security software that I know of. The software had been running great until a week or two ago and then suddenly because extremely slow. I assume this was due to an update. Windows Server 2019 Datacenter running on AWS.

**Comment by ghost** [comment] 2020-12-07 16:53
I'm problems in 2.6.0. where it says that the origin was never fetched and can't fetch the origin at all.

**Comment by dxc-jbeck** [comment] 2021-02-02 14:15
I had this problem this morning. I uninstalled GitHub Desktop. Then I searched from the root of c:\ for "GitHub Desktop" and deleted all the matching folders.  Then I re-installed and it's working fast again.
