### ISSUE TITLE
Crash when reading Repository from an 'Online Only' / Smart Sync Dropbox Folder

### ISSUE THREAD

**Issue by themorgantown** [desktop/desktop#11068] opened 2020-11-18 20:14 UTC
### Description

Dropped a Github repo onto Github. The folder is currently syncing via Dropbox. The application showed the following error: 

```
Error: read EFAULT
    at Pipe.onStreamRead (internal/stream_base_commons.js:200:27)

```

Dropbox Smart Sync is on by default, a Dropbox feature which downloads file markers but no data. Files retrieved by Mac Apps like GitHub trigger Dropbox to download the file, but this speed depends on internet speed. If Github Desktop could be aware that these files being requested will arrive after a greater delay it would avoid crashes. This occurs even if Dropbox is in the status of 'synced'. An entire folder setup as 'Online only' will fail when loaded into Github. 

### Version & OS

Version: 2.6.0
OS: Mac OS 10.16.0
Apple Silicon 

### Steps to reproduce the behavior

1. Load large repository into Github Desktop which is missing some files
2. As Github attempts to sync, the application crashes

This does not occur on smaller repositories since the files download much faster from Dropbox. 

### Expected behavior

Github could handle files within a /Dropbox path by waiting a bit longer for file attributes + data if the response is slow.

### Actual behavior

Crash. 

### Screenshots

<img width="712" alt="Screen Shot 2020-11-18 at 3 01 47 PM" src="https://user-images.githubusercontent.com/50146/99582512-34b21100-29b0-11eb-8068-351e9a9c892e.png">
 
Logs: [2020-11-18.desktop.production.log](https://github.com/desktop/desktop/files/5562489/2020-11-18.desktop.production.log)

**Comment by niik** [comment] 2020-11-18 20:40
Hey @themorgantown, thanks for opening this and sorry to hear you're having problems.

> Apple Silicon

I wanted to ask about :point_up: It might seems silly but could you confirm that you're running on one of the new Apple machines that with the M1 processor? We haven't had any reports of users running on those machines yet.

> Error: read EFAULT

We've seen a few (5 distinct users or so) of these crashes today all running on Big Sur but we haven't been able to nail down the cause yet. Does this crash happen immediately after launch? Are you able to view a repository that's not handled by Dropbox?

> The folder is currently syncing via Dropbox

We've highly recommend against keeping Git repositories in Dropbox in the past as it's been a source of a lot of problems for folks (regardless of them using GitHub Desktop, just Git, or other tools).

**Comment by themorgantown** [comment] 2020-11-18 20:52
> I wanted to ask about ☝️ It might seems silly but could you confirm that you're running on one of the new Apple machines that with the M1 processor? We haven't had any reports of users running on those machines yet.

It runs great! No issues (I think) which are related to the architecture but I thought it might be useful to include. I've done several commits, pulls and pushes and cannot complain. 

> Does this crash happen immediately after launch? Are you able to view a repository that's not handled by Dropbox?

It originally happened because I delete a repo out from under Github (GitHub desktop was closed) I opened it and it was asked to 'locate' the repo which it couldn't find, so I pointed it to the Dropbox repo I have, which was 'smart synced'. (not the best name) 

> We've highly recommend against keeping Git repositories in Dropbox in the past as it's been a source of a lot of problems for folks (regardless of them using GitHub Desktop, just Git, or other tools).

Totally agree with you! This workflow has against all odds served me well since I use it as a personal 'git stash' and I blame only myself for its shortcomings while also hoping this report serves others. 

As a side note, I've used Github with Resilio sync, Syncthing, and Dropbox and Dropbox is the most bulletproof so far.

**Comment by steveward** [comment] 2021-01-11 21:06
Since we have had a couple of separate reports about this I am going to close this out to consolidate our issues. Please follow along in https://github.com/desktop/desktop/issues/11258 for updates.

**Closed as completed by steveward** 2021-01-11 21:06 UTC
