### ISSUE TITLE
Can't find repository

### ISSUE THREAD

**Issue by KorGgenT** [desktop/desktop#10707] opened 2020-10-01 18:30 UTC
### Describe the bug
![image](https://user-images.githubusercontent.com/30208401/94847968-4e43cd00-03f1-11eb-96a1-104a97f98d68.png)

I have added Qt to my project folder and added it to my .gitignore in one branch. I think the fact that this library is 50GB and in a .gitignore is an issue.

### Version & OS
github desktop 2.5.6
windows 10
git version 2.28.0.windows.1

### Steps to reproduce the behavior
Might be able to reproduce here by cloning my repo (this is the actual branch that causes the issue): <https://github.com/KorGgenT/Cataclysm-DDA/tree/object-creator>
and then download and install Qt into the root folder.

### Expected behavior
Being able to use github desktop in my repo, with branches, commits, etc.

### Logs
[2020-10-01.desktop.production.log](https://github.com/desktop/desktop/files/5314089/2020-10-01.desktop.production.log)

### Additional context
I found #10657 when searching for similar issues, since I originally attempted making a symlink. However I decided to open a new issue because there were slightly different problems I was running into.

**Comment by steveward** [comment] 2020-10-01 20:57
@KorGgenT thanks for the report. This can happen when the output of Git status exceeds 20MB, which causes GitHub Desktop to be unable to parse it. Since you're working with such a large repository my guess is that this is the likely culprit. As a workaround you can make an initial commit to the repository via the command line, and then add it to GitHub Desktop. Let me know if that doesn't get things working.

**Comment by KorGgenT** [comment] 2020-10-01 21:00
since my repo is actually a fork in order to work on another repo, i won't be able to make an initial commit. I can see if creating a PR for a .gitignore for the Qt folder can help...

**Comment by steveward** [comment] 2020-10-02 14:13
@KorGgenT I'd recommend running `git status` in the repository from the command line to check the output of the diff. This will let you know if there are a large subset of files possibly being missed by the .gitignore that could be causing this issue.

**Comment by KorGgenT** [comment] 2020-10-02 20:03
![image](https://user-images.githubusercontent.com/30208401/94965017-b74a4400-04c8-11eb-8072-da29eb6bafba.png)
Adding Qt to the .gitignore is on an in-progress branch.

**Comment by steveward** [comment] 2020-10-06 02:22
@KorGgenT thanks for checking that. The uncommitted Qt folder is definitely causing this -- adding that directory to `.gitignore` should resolve this issue. I'm going to close this out since we've tracked down the cause of this, but let me know if you run into any further configuration issues.

**Closed by steveward** 2020-10-06 02:22 UTC
