### ISSUE TITLE
Github desktop won't open (macOS 11.0.1)

### ISSUE THREAD

**Issue by nbara** [desktop/desktop#11176] opened 2020-12-04 14:31 UTC
### Describe the bug

The app won't open since installing the latest update (4 Dec). 

The app appears to be open in the dock and and menu bar, but the main window is invisible. When I click on "about Github Desktop" , I get the following empty window.

<img width="833" alt="Screenshot 2020-12-04 at 15 24 21" src="https://user-images.githubusercontent.com/10333715/101175107-0df90900-3645-11eb-8f11-d34d0eb8e592.png">

I have access to the developer window, which shows an error:

<img width="1266" alt="Screenshot 2020-12-04 at 15 24 11" src="https://user-images.githubusercontent.com/10333715/101175201-28cb7d80-3645-11eb-82d2-e14fff5795f8.png">

### Version & OS

Latest macOS (11.0.1).

I've tried the latest version linked on https://github.com/desktop/desktop (beta and stable), as well as the latest brew `github` version:
`==> Downloading https://desktop.githubusercontent.com/releases/2.5.6-e0dac138/GitHubDesktop.zip`

### Steps to reproduce the behavior

1. Launch Github Desktop

### Expected behavior

The main window should be visible but is not.

### Logs

Logs contain confidential info so I cannot attach. 

I've tried removing plist files.

**Comment by niik** [comment] 2020-12-04 14:36
Hi @nbara, sorry to hear you're having problems.

This is an error I'd expect to see if you've downloaded and installed the most recent beta version of GitHub Desktop and then switched back to the production version. The beta version contains a backwards-incompatible database upgrade so switching to the production version again requires resetting the internal database which you can do by deleting the `~/Library/Application\ Support/GitHub\ Desktop` folder.

Or you can reinstall the latest beta version by downloading it from https://central.github.com/deployments/desktop/desktop/latest/darwin?env=beta

Please let us know if the problem persist after trying either one of those options

**Comment by nbara** [comment] 2020-12-04 14:39
Hi @niik thanks for the quick reply. Using your link to the latest beta, I get the same behaviour but a different error in devtools. See screen:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/10333715/101176537-e99e2c00-3646-11eb-988f-bc71a82cdd16.png">

**Comment by niik** [comment] 2020-12-04 16:03
Hey @nbara, thanks so much that's very helpful. I know why this is happening now and I should be able to come up with a fix for the problem in a bit but I wanted to ask if you've been a long time user of Desktop? The reason I ask is that while I know the cause of the problem (there's a GitHubRepository in you IndexedDB missing its parentID property) the only reason I can think of which could have caused that is if the GitHubRepository in question was created before we added that property which was a very long time ago now.

There's likely another reason it could be missing but that's the only thing I've come up with thus far.

**Comment by nbara** [comment] 2020-12-04 16:08
Yeah I've been using Desktop since pretty much the beginning :)

**Comment by niik** [comment] 2020-12-04 17:43
Hey @nbara 

> Yeah I've been using Desktop since pretty much the beginning :)

That's amazing :heart:

I have a good path forward on a fix for this but given that it's late friday afternoon and that it looks like this is only affecting a rare subset of users who have been using the app for a very long time and who have also been using the beta version of the app I think we're going to have to wait until early next week with a release to fix this.

I have two options for you, either you delete the `~/Library/Application\ Support/GitHub\ Desktop` folder and start fresh (you'll have to sign back in again and add your local repositories).

Or you take a backup copy of the same folder and copy and paste the following hack into the DevTools console of the app

```js
indexedDB.open('Database', 70).onsuccess = event => {
  const db = event.target.result
  const tx = db.transaction(['gitHubRepositories'], 'readwrite')
  const objectStore = tx.objectStore('gitHubRepositories')

  objectStore.getAll().onsuccess = event => {
    const repos = event.target.result.filter(x => x.parentID === undefined)
    const putNext = () => {
      const repo = repos.shift()
      if (repo !== undefined) {
        console.log(repo)
        objectStore.put({ ...repo, parentID: null }).onsuccess = putNext
      }
    }
    putNext()
  }
}
```

That script should take care of finding that stray repository and fix it up. Once you've run it you can relaunch the app and it should work.

**Comment by hubgit** [comment] 2020-12-06 14:07
I'm getting a slightly different error after downloading the latest beta from the link above (which I have been using, not sure if I'd accidentally switched back to stable):

![image](https://user-images.githubusercontent.com/14294/101282265-02841a00-37cc-11eb-8db5-38378fecc701.png)

This is macOS 11.0.1, and I have been using GitHub Desktop for quite a long time.

Nothing's logged when running the script above in Dev Tools, so I guess it's not an undefined `parentID`.

It's working ok again after removing `~/Library/Application\ Support/GitHub\ Desktop`.

**Comment by MarkEdmondson1234** [comment] 2020-12-07 08:50
I had the same issue as https://github.com/desktop/desktop/issues/11176#issuecomment-738819835 and another long time user.  I had a lot of repos so didn't want to delete and add them all again but copy-pasting the script (https://github.com/desktop/desktop/issues/11176#issuecomment-738921088 ) worked and its all good again after a restart.

I got the dev tools to show via View > Toggle Dev Tools

**Comment by nbara** [comment] 2020-12-07 08:55
> either you delete the `~/Library/Application\ Support/GitHub\ Desktop` folder and start fresh (you'll have to sign back in again and add your local repositories).

Yeah I ended up doing that. A bit of a chore to re-add all repos by hand again, but it's working fine now.

**Comment by niik** [comment] 2020-12-07 09:06
> I'm getting a slightly different error after downloading the latest beta from the link above (which I have been using, not sure if I'd accidentally switched back to stable):

@hubgit Thanks for reaching out! That's likely related to the same change but not identical to this issue so I've opened #11192 to track that problem.

**Closed as completed** 2020-12-07 12:57 UTC
Labels: support

**Comment by niik** [comment] 2020-12-08 09:15
The beta channel has been updated to 2.6.1-beta3 which includes a fix for this issue. If you don't receive automatic updates please download the latest version from https://github.com/desktop/desktop#beta-channel. Should the problem persist after upgrading please let us know about it!

**Comment by platon9000** [comment] 2020-12-08 09:30
Yes

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
