### ISSUE TITLE
Slow Git operations on WSL repos

### ISSUE THREAD

**Issue by omzy** [desktop/desktop#18102] opened 2024-01-29 16:47 UTC
### The problem

Every operation takes like 10 times longer when using WSL based repositories as opposed to local ones. For example, I just switched to a different repository and it took something like 30 seconds. Here is the relevant output from the log file:

```
2024-01-29T16:40:04.017Z - info: [ui] Executing getCommits: git log 346d99ee7b80aceb7978df7ef5504f8237092af4 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 3.672s)
2024-01-29T16:40:04.653Z - info: [ui] Executing getBranchesDifferingFromUpstream: git for-each-ref --format=%00%(refname)%00%(objectname)%00%(upstream)%00%(symref)%00%(HEAD)%00 refs/heads refs/remotes (took 1.101s)
2024-01-29T16:40:07.233Z - info: [ui] Executing getCommits: git log 5f8016912700097fbc894b071a8281eddce9b0fb --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.665s)
2024-01-29T16:40:10.721Z - info: [ui] Executing getCommits: git log 0eb50e5562b403ecd350840f701aa3d8fc735146 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 5.956s)
2024-01-29T16:40:13.618Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 2.549s)
2024-01-29T16:40:15.237Z - info: [ui] Executing getCommits: git log d0258f3b7bce88ea8f8308cb70048b79438e5b96 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 6.237s)
2024-01-29T16:40:18.225Z - info: [ui] Executing getCommits: git log b41bb3c54a6397caa8b41d8531782aeecaa395e8 --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.741s)
2024-01-29T16:40:19.404Z - info: [ui] Executing getCommits: git log origin/PP-13976..PP-13976 --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 5.250s)
2024-01-29T16:40:23.170Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 3.765s)
2024-01-29T16:40:23.321Z - info: [ui] Executing fastForwardBranches: git fetch . --show-forced-updates --no-write-fetch-head --stdin (took 18.667s)
2024-01-29T16:40:24.344Z - info: [ui] Executing getCommits: git log 9f4816b1da41300244eab10d27c333035d2ebdac --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 2.110s)
2024-01-29T16:40:27.868Z - info: [ui] Executing getBranches: git for-each-ref --format=%00%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(symref)%00 refs/heads refs/remotes (took 2.502s)
2024-01-29T16:40:29.314Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --skip=0 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 6.143s)
2024-01-29T16:40:33.766Z - info: [ui] Executing getCommits: git log origin/PP-13976..PP-13976 --date=raw --max-count=100 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 5.273s)
2024-01-29T16:40:37.742Z - info: [ui] Executing getAllTags: git show-ref --tags -d (took 3.975s)
2024-01-29T16:40:38.679Z - info: [ui] Executing getCommits: git log d4e83e2c4b71f3800fefc896ad5622fb299097dc --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 9.940s)
```

### Release version

3.3.8

### Operating system

Windows 10

**Comment by steveward** [comment] 2024-01-30 19:50
Thanks for the report @omzy. I'll add this to our tracking issue for performance related issues.

**Comment by steveward** [comment] 2024-01-30 19:51
Are your repositories large in size? Are you running any antivirus or other security software on this machine that could also be affecting performance? I know you mentioned repositories outside of WSL seem to be fine, but just want to confirm.

**Comment by steveward** [comment] 2024-02-08 17:10
@omzy in the interest of issue consolidation I'm going to close this out since we have other open issues tracking performance. If you have any further information about your setup like I asked for above you can follow up here.

**Closed as completed by steveward** 2024-02-08 17:10 UTC
Labels: performance

**Comment by aleixrodriala** [comment] 2026-03-26 13:25
I've been dealing with the same 10x slowdown on WSL repos. The root cause is every git command going through 9P across the VM boundary (~40ms floor per operation). I built a fork that bypasses this entirely by running a daemon inside WSL that handles git natively over TCP: [GithubDesktopWSL](https://github.com/aleixrodriala/GithubDesktopWSL)

Brings operations like git status down from 43ms to 2ms. Installs side-by-side with official Desktop. Would appreciate any feedback!
