### ISSUE TITLE
Team members cant clone or push

### ISSUE THREAD

**Issue by MattSowards** [desktop/desktop#4023] opened 2018-02-15 23:48 UTC
### Description

Hi! I work with a team of 4 others and it seems 2 out of 4 people can clone the project and upload files, out of the other 2, 1 of them cant even clone it, and the other 1 cant push files. I currently only have the logfile of the 1 that can't even clone it, since it seems his is more serious. They've attempted to re-clone it which has costed me to raise my Git LFS Storage bandwidth up to $30 a month.

### Version

1.0.13

-->

**GitHub Desktop version:** [1.0.13]

### Steps to Reproduce

1. [Download Github Desktop, Git SCM, Git LFS]
2. [Open Github Desktop, Run Gitbash, type git lfs install]
3. [Connect To Private Repository, Attempt to clone]
4. [Error Log Occurs]

**Comment by shiftkey** [comment] 2018-02-16 00:12
@MattSowards 

Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by MattSowards** [comment] 2018-02-16 00:29
[2018-02-14.desktop.production.log](https://github.com/desktop/desktop/files/1729841/2018-02-14.desktop.production.log)

**Comment by MattSowards** [comment] 2018-02-16 12:57
That's the log file.

**Comment by iAmWillShepherd** [comment] 2018-02-16 16:50
These messages from your logs look like they could be the problem lines:
```
error: Unable to create 'C:/Users/jojom/Documents/Unreal Projects/BattleForItAll/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
fatal: revert failed
```

```
2018-02-14T14:02:39.472Z - error: [ui] `git -c credential.helper= revert 975974c3dc2843936b3a3bf0be57e2281910aa6e` exited with an unexpected code: 128.
error: Your local changes to the following files would be overwritten by merge:
	Content/BattleRoyale/Airdrop/textures/Main_Crate_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Main_Crate_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Main_Crate_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Main_Crate_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Main_Crate_roughness.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_01_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_01_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_01_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_01_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_01_roughness.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_02_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_02_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_02_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_02_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_02_roughness.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_03_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_03_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_03_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_03_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_03_roughness.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_04_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_04_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_04_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_04_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Strap_04_roughness.uasset
	Content/BattleRoyale/Airdrop/textures/Top_Cloth_AO.uasset
	Content/BattleRoyale/Airdrop/textures/Top_Cloth_albedo.uasset
	Content/BattleRoyale/Airdrop/textures/Top_Cloth_metallic.uasset
	Content/BattleRoyale/Airdrop/textures/Top_Cloth_normal.uasset
	Content/BattleRoyale/Airdrop/textures/Top_Cloth_roughness.uasset
	Content/BattleRoyale/Maps/Demonstration_Lobby.umap
Please commit your changes or stash them before you merge.
error: The following untracked working tree files would be overwritten by merge:
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L10_Remove_Foliage_Grass_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L11_Remove_Foliage_Bushes_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L1_Ice_or_Puddle_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L2_Snow_or_Grass_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L3_Snow_Rough_or_Rocks_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L4_Snow_Slush_or_Mud_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L5_Forest_Ground_a_LayerInfo.uasset
	Content/ProceduralNtr_vol2/maps/Landscape_Layer_Info/L6_Forest_Ground_b_LayerInfo.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/Spline_Meshes/pine_branches/Textures/T_Pine_Branches_BC_v02.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/Spline_Meshes/pine_branches/Textures/T_Pine_Branches_NM_v02.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/Spline_Meshes/pine_branches/Textures/T_Pine_Branches_Translucency.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/Spline_Meshes/pine_branches/Textures/T_Pine_Branches_merge_v02.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Materials/edleberry_bush_snow.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Static_Meshes/Elderberry_Living_Large.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Textures/T_Elderberry_BC.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Textures/T_Elderberry_NM.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Textures/T_Elderberry_T.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/eldeberry_bushes/Textures/T_Elderberry_merge.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Materials/grass_green_01.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Static_Meshes/green_grass_patch_tall_01.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Textures/grass_green_color.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Textures/grass_orange_brown_color.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Textures/grass_orange_brown_merge.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/grass/Textures/grass_orange_brown_normal.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/landscape_auto_foliage/EldeBush_Live_L01.uasset
	Content/ProceduralNtr_vol2/pnp_v2_assets/Assets/landscape_auto_foliage/Green_Grass_L01.uasset
Please move or remove them before you merge.
Aborting
fatal: revert failed
```

```
Downloading Content/AmmoSet/Textures/PaperBox/cal12GaugePaperBox_roughness.uasset (70 KB)
Error downloading object: Content/AmmoSet/Textures/PaperBox/cal12GaugePaperBox_roughness.uasset (7bc3171): Smudge error: Error downloading Content/AmmoSet/Textures/PaperBox/cal12GaugePaperBox_roughness.uasset (7bc31716b6ed2e8111829655c57851b0ef69a48c070357f517ca266288823551): batch response: Post https://github.com/MattSowards/BattleForItAll.git/info/lfs/objects/batch: dial tcp: lookup github.com: no such host

Errors logged to C:\Users\jojom\Documents\Unreal Projects\BattleForItAll\.git\lfs\objects\logs\20180214T234746.8089074.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Content/AmmoSet/Textures/PaperBox/cal12GaugePaperBox_roughness.uasset: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by MattSowards** [comment] 2018-02-16 18:06
I see, but it is generated every time he clone a project?

**Comment by MattSowards** [comment] 2018-02-16 18:33
Here is the other log file. 
[GitLog_Error (1).txt](https://github.com/desktop/desktop/files/1732419/GitLog_Error.1.txt)

**Comment by iAmWillShepherd** [comment] 2018-02-16 18:38
Are you able to clone the repository using the CLI? 

If you have not tried, could you please give me the output of this command on your machine?
`GIT_TRACE=1 git clone [your repo]`

**Comment by MattSowards** [comment] 2018-02-16 18:43
What is CLI?

**Comment by RoastyToast** [comment] 2018-02-16 18:44
Hey Shepherd,

I am the main weapon animator of the project I try to get this all going. The output log commented out above it a error from Github Desktop. What exactly do you mean with CLI?

**Comment by iAmWillShepherd** [comment] 2018-02-16 19:25
CLI is command line interface. 

Judging by this log entry: `C:/Users/jojom/Documents/Unreal`
You are running Windows, so try running that command in Git Bash.

**Comment by RoastyToast** [comment] 2018-02-18 11:43
Its working now. But what command to would I need to run to download changes and updates to the repo?

**Comment by iAmWillShepherd** [comment] 2018-02-23 08:22
I believe you are referring to `git pull`. Check out this [guide](https://guides.github.com/introduction/git-handbook/#basic-git) for more info.

**Comment by shiftkey** [comment] 2018-02-26 03:11
@RoastyToast from what I can glean from the logs, this is the same root cause for your machine as https://github.com/desktop/desktop/issues/3752 and it's occurring because a space in your Windows account name isn't handled correctly by Git LFS when it invokes the GIT_ASKPASS batch file. Please follow along with #3752 when I can get around to closing that out.

**Comment by shiftkey** [comment] 2018-02-26 03:15
@MattSowards I think the other errors from your initial log file are just Git errors (rather than Git LFS) -
 if there's anything fresh logs you'd like me to look at please open a new issue.

**Closed by shiftkey** 2018-02-26 03:15 UTC

**Comment by RoastyToast** [comment] 2018-02-27 19:02
I am following along. But is there a way to update my project using GitBash for so far than right now.

I am also on a company network of my health care house I am living at so there are some restritiction if we are talking about secure connections and such things. 

A small example is that I do motion captured animations with the Xbox Connect if I need to head to party chat I am not able to talk due my internect connections as there is no toredo connections. Normally this is fixed by putting a cable connetion in your pc or Xbox but this options I don't have.

Might this be the other reason I am having this issue?
