### ISSUE TITLE
Squash and Merge Button UI Issue

### ISSUE THREAD

**Issue by JosephTLyons** [desktop/desktop#12469] opened 2021-06-17 07:24 UTC
### Describe the bug

There seems to be a little bit of a UI artifact on the right side of the button.  This appears on the rebase, squash and merge, and merge button (I assume they are all the same)

### Version & OS

GitHub: Version 2.9.0 (x64)
macOS: 11.3

<img width="246" alt="Screen Shot 2021-06-17 at 3 20 36 AM" src="https://user-images.githubusercontent.com/19867440/122350557-514d0200-cf1b-11eb-909f-c82e00683ae4.png">

**Comment by tidy-dev** [comment] 2021-06-17 12:46
@JosephTLyons Thanks for your issue! However, I am unable to reproduce it. I was curious if you could think of something about your environments view settings that could impact the UI. I have tried reducing my app to the smallest height/width and fiddling with the zoom settings. But, have yet to see any extra bits in the UI.
![image](https://user-images.githubusercontent.com/75402236/122398585-04cbeb80-cf48-11eb-9531-0ea4d318fa5b.png)


Going to close this for now, but if you can provide more detailed repro steps (and it is not a user environment specific behavior), we can reopen it.

**Comment by jfirebaugh** [comment] 2021-08-23 22:00
This is 100% reproducible for me in 2.9.0. It's dependent on the width of the sidebar.

https://user-images.githubusercontent.com/98601/130525077-47f93afb-fe29-4dda-b6cf-16b1b7f2f23b.mov

**Comment by JosephTLyons** [comment] 2021-08-23 22:15
> This is 100% reproducible for me in 2.9.0. It's dependent on the width of the sidebar.
> 
> 
> 
> https://user-images.githubusercontent.com/98601/130525077-47f93afb-fe29-4dda-b6cf-16b1b7f2f23b.mov
> 
> 
> 
> 

Nice catch!

**Comment by steveward** [comment] 2024-09-18 15:41
I'm no longer able to reproduce this when adjusting the width of the sidebar. I'm going to close this out, but if this is still an issue let us know and we can reopen.

**Closed as completed by steveward** 2024-09-18 15:41 UTC
Labels: bug, priority-3
