### ISSUE TITLE
'view and restore stashed changes' doesn't work

### ISSUE THREAD

**Issue by ares7823** [desktop/desktop#11056] opened 2020-11-18 00:11 UTC
### Describe the bug

When I pull the git that has a conflict with what I am working on, I used to stash my changes before being updated and restore them. But recently this functionality didn't work as intended and wiped out my changes, without any warning, when I click on 'restore'

### Version & OS
2.6.0
Windows 10

### Steps to reproduce the behavior

1. change anything in your project simultaneously using both user1 and user2 account
2. push the changes from user2
3. click on 'Fetch Origin' from user1
4. you get the warning message recommending to stash the changes before downloading
5. follow the instruction, pull the git and restore your change afterward

### Expected behavior

Your changes should be shown on the panel of 'changes' and ready to pull

### Actual behavior

You don't see your changes anywhere, it automatically removed your works in your local machine too

### Logs

[2020-11-17.desktop.production.log](https://github.com/desktop/desktop/files/5556919/2020-11-17.desktop.production.log)

**Comment by steveward** [comment] 2020-11-18 02:18
I'm sorry for the trouble @ares7823. This sounds similar to the issues that were reported in https://github.com/desktop/desktop/issues/10651 and https://github.com/desktop/desktop/issues/9670.

I was unable to reproduce this with a quick test, but there may be a race condition I am missing. I created a merge conflict between my local and remote repository, GitHub Desktop stashed my changes, and I was able to restore the stash successfully (which then resulted in a merge conflict). Are you able to see if you can reliably reproduce this?

**Comment by ares7823** [comment] 2020-11-18 13:40
My project doesn't have any other branch but the master. Not sure if they are similar to this issue..

________________________________

**Comment by steveward** [comment] 2020-11-19 02:59
Thanks for that clarification -- in both cases a merge is being performed so there could be similar edge-cases causing the lost changes. Are you able to reproduce this behavior?

**Comment by ares7823** [comment] 2020-11-19 04:04
I am pretty new to github and not familiar with the general process. Can you clarify what I should provide from reproducing the behavior? To reproduce what I've experienced, I think I need someone else to push the commits before I pull with having my changes held.

**Comment by steveward** [comment] 2021-08-03 17:27
@ares7823 have you ran into this issue in GitHub Desktop again? I haven't seen any other reports recently of this behavior.

**Comment by ares7823** [comment] 2021-08-05 23:00
Hi,
Thanks for reaching out. I haven’t got this issue recently as I’m staying of the project.



iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: Steve Ward ***@***.***>
보낸 날짜: Wednesday, August 4, 2021 2:28:08 AM
받는 사람: desktop/desktop ***@***.***>
참조: Lee, Jungmin ***@***.***>; Mention ***@***.***>
제목: Re: [desktop/desktop] 'view and restore stashed changes' doesn't work (#11056)


@ares7823<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fares7823&data=04%7C01%7Cjzl95%40psu.edu%7Cfcba046f10ca4f7099ab08d956a4100a%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637636084909352412%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IFXspFq2CJEqAYnwd2eIj2klPmkpUeQVluRJ3ASX4hg%3D&reserved=0> have you ran into this issue in GitHub Desktop again? I haven't seen any other reports recently of this behavior.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdesktop%2Fdesktop%2Fissues%2F11056%23issuecomment-892027841&data=04%7C01%7Cjzl95%40psu.edu%7Cfcba046f10ca4f7099ab08d956a4100a%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637636084909352412%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TC1q2Oi97IkBxyfGUAADYW%2FJ5xX%2BSVsmqinIMhZyW0M%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAH3D54XDG2KQB4Y5EAAYBFTT3ARKRANCNFSM4TZIJEKQ&data=04%7C01%7Cjzl95%40psu.edu%7Cfcba046f10ca4f7099ab08d956a4100a%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637636084909362360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ThwPKQSEG5PXFTWKzu6201jOaUpqwhvMga1A4hhz2Lo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjzl95%40psu.edu%7Cfcba046f10ca4f7099ab08d956a4100a%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637636084909362360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r909B7V%2Blkbf1gkdkrzkLNqCjJEqkGuCvwqheJT7mX4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjzl95%40psu.edu%7Cfcba046f10ca4f7099ab08d956a4100a%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C637636084909372327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=svqQP3aZdhv3687aMujlyfd8HsjpTFIaVrpP%2BEDg4Go%3D&reserved=0>.

**Comment by steveward** [comment] 2021-08-09 20:30
Thanks for the update @ares7823, I'm going to close this out, but let me know if you encounter this issue again.

**Closed as completed by steveward** 2021-08-09 20:30 UTC
