### ISSUE TITLE
Keyboard up/down arrows inconsistent behavior with repo selector

### ISSUE THREAD

**Issue by nycdotnet** [desktop/desktop#11269] opened 2020-12-21 18:26 UTC
### Describe the bug

In the repository selector, the behavior of the up and down keyboard keys is inconsistent.  It would be great if the down arrow  would consistently allow the user to select a matching repository.

### Version & OS

2.6.1, Windows 10 x64 latest

### Steps to reproduce the behavior

1. Configure at least a few repos in GitHub Desktop.
2. Click the repo selector in the top left corner (or CTRL+T)  and type any text that will match some repos - I typed `nycdo` in my screenshot, but it doesn't seem to matter.
3. You will see a list of matching repositories that GitHub Desktop knows about.
4. Press the down arrow key on the keyboard with the repository search box still focused.  _Sometimes_ this will navigate down to the first matching repository.  Often it will not.
5. Press the up arrow key on the keyboard with the repository search box still focused; This seems to _always_ navigate down to the bottom match (it loops around to the bottom from the top).
6. Once having "unstuck" the text box, you should be able to navigate up and down, including into and out of the repository search box with the up and down arrow keys freely.

### Expected behavior

The down arrow should always pick the first selection in the results in the repository picker.

### Actual behavior

Often, pressing the down arrow key does nothing.  Unsticking it by using the up arrow key appears to fix it, and then down arrow will work as expected.

### Screenshots

![GitHubDesktop-Issue-2020-12-21](https://user-images.githubusercontent.com/3755379/102809326-c6d27e00-438f-11eb-8357-9bdf657804d2.png)

**Comment by filiptronicek** [comment] 2021-01-31 16:13
I have also found, that sometimes it gets bugged and when trying to navigate down, it just doesn't sometimes let me go down
(in this video, I never pressed the arrow up, just the arrow down key)

https://user-images.githubusercontent.com/29888641/106390201-84b54700-63e7-11eb-8f21-3c9370dff991.mp4

I am on 2.6.3-beta1 (Win10), but this has been happening for a while now.

**Comment by nycdotnet** [comment] 2021-01-31 23:04
I have also observed the behavior in @filiptronicek ‘s video where Desktop “fights” against your down arrows and will go back up on its own, though this is somewhat rare.  Not sure if it’s the same underlying cause.  Thanks.

**Comment by Seth10001** [comment] 2022-03-14 13:16
+1

**Comment by DCzajkowski** [comment] 2022-03-23 15:00
Indeed, reproducible on macOS, so this is OS independant

**Comment by lukep-coxauto** [comment] 2022-11-16 23:10
This is still an issue with latest GitHub Desktop version as of 2022-11-16 (Version 3.1.2).  It doesn't seem to be related only to using the filter.  If you hold down the up or down arrow (on Windows at least) it doesn't smoothly scroll. It will jump around as it scrolls.  It's inconsistent though, sometimes the arrows will work correctly.

**Comment by nycdotnet** [comment] 2023-01-25 20:28
@tidy-dev / @sergiou87 thank you for improving the keyboard navigation in #15620 .  I believe you have fixed this issue as well.  Can others confirm?

**Comment by lukep-coxauto** [comment] 2023-01-25 20:33
How do we determine which version this fix is included in?  I have 3.1.4 on Windows x64 and I still see inconsistent behavior in the repo selector dropdown.  Sometimes down doesn't do anything, sometimes it does navigate down, and sometimes it navigates down and then jumps back up to the previous selection.

**Comment by nycdotnet** [comment] 2023-01-25 20:34
This seems fixed for me in 3.1.5 which just got released today.  I am on x64 Mac at present.

**Comment by lukep-coxauto** [comment] 2023-01-25 20:35
Great! my Desktop app is showing 3.1.4 as the latest version still, but I'll give this a try tomorrow and see if the new release fixes it.

**Comment by filiptronicek** [comment] 2023-01-26 14:51
I can confirm the issue is no longer present, thank you all!

**Comment by sergiou87** [comment] 2023-01-31 14:40
Thank you all for reporting back! We can close this now 😄

**Closed as completed by sergiou87** 2023-01-31 14:40 UTC
Labels: enhancement

**Comment by DCzajkowski** [comment] 2024-01-26 11:31
The arrows are broken again as of January 2024 :/

**Comment by symonxdd** [comment] 2024-05-07 07:51
> I have also found, that sometimes it gets bugged and when trying to navigate down, it just doesn't sometimes let me go down (in this video, I never pressed the arrow up, just the arrow down key)
> 
>  2021-01-31.17-02-00.mp4 
> I am on 2.6.3-beta1 (Win10), but this has been happening for a while now.

This issue still persists on version 3.3.14 (x64), sometimes, it's unclear at which instances.
