### ISSUE TITLE
macOS icon is slightly too large

### ISSUE THREAD

**Issue by RA80533** [desktop/desktop#9531] opened 2020-04-15 21:23 UTC
### Describe the feature or problem you’d like to solve

macOS applications developed by Apple follow a distinct visual language when it comes to their icons. Many third-party applications follow suit, including GitHub's own Atom. GitHub Desktop attempts to emulate the native macOS design for circular icons but fails in a very subtle regard: it is slightly too large.

### Proposed solution

Rescale the icon to the appropriate size.

### Additional context

The icons shown in the screenshot below belong to [Fork](https://git-fork.com), [Atom Nightly](https://atom.io/nightly), and GitHub Desktop, respectively.

![Example](https://user-images.githubusercontent.com/32469082/79390053-00b7ce80-7f3d-11ea-891a-c209afdf70be.png)

**Comment by billygriffin** [comment] 2020-04-15 22:02
Thanks for the issue! I'm closing this as a duplicate of #7536.

**Closed by billygriffin** 2020-04-15 22:02 UTC

**Comment by golfstok** [comment] 2020-04-15 22:05
Can you close all conectuns

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Billy Griffin <notifications@github.com>
Sendt: Thursday, April 16, 2020 12:03:58 AM
Til: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [desktop/desktop] macOS icon is slightly too large (#9531)


Closed #9531<https://github.com/desktop/desktop/issues/9531>.
