### ISSUE TITLE
failed to open application

### ISSUE THREAD

**Issue by tweaker33** [desktop/desktop#3253] opened 2017-11-07 16:07 UTC
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\laurens\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\laurens\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.16299

**Comment by j-f1** [comment] 2017-11-07 16:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2678. Please follow that issue for further updates.

**Closed** 2017-11-07 16:50 UTC
