### ISSUE TITLE
Branch name only supports up to 37 characters.

### ISSUE THREAD

**Issue by altair2020** [desktop/desktop#18087] opened 2024-01-25 23:05 UTC
### The problem

![image](https://github.com/desktop/desktop/assets/6660869/805e1a59-72a7-4cb0-a901-f20fda686d01)

abcdefghijklmnopqrstuvwxyz12345678901

### Release version

3.3.8 64

### Operating system

Windows

### Steps to reproduce the behavior

click on current branch and filter.

### Additional context

there is not enough room for a long branch name.
example:
firstname.lastname/appname/bugnumber-description-of-issue
abcdefghijklmnopqrstuvwxyz12345678901

there is only 37 characters available to make a branch name this is not enough.

**Comment by steveward** [comment] 2024-01-26 15:50
Thanks for the report @altair2020. I'm not able to reproduce the issue on macOS, but I'll give it a look on Windows as well.

<img width="441" alt="Screenshot 2024-01-26 at 10 48 28 AM" src="https://github.com/desktop/desktop/assets/721500/626c96d3-9ad1-4f3b-9518-ae9120f93356">

Can you share a few more details? Any steps I could be missing here?

**Comment by altair2020** [comment] 2024-01-27 02:12
It’s probably a feature request bro.

I need more letters and a bigger text input box. I tried to clone the repo but got a bunch of errors with the npm. Running commands I had no idea about. Gave up


On 26 Jan 2024, at 15:50, Steve Ward ***@***.***> wrote:

﻿

Thanks for the report @altair2020<https://github.com/altair2020>. I'm not able to reproduce the issue on macOS, but I'll give it a look on Windows as well.

Screenshot.2024-01-26.at.10.48.28.AM.png (view on web)<https://github.com/desktop/desktop/assets/721500/626c96d3-9ad1-4f3b-9518-ae9120f93356>

Can you share a few more details? Any steps I could be missing here?

**Comment by steveward** [comment] 2024-01-30 13:37
I'm going to close this out, but if you're having specific issues cloning a repository please feel free to open a new issue.

**Closed as completed by steveward** 2024-01-30 13:37 UTC
