### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by marcpalestina** [desktop/desktop#3921] opened 2018-02-02 19:00 UTC
### Description

Program screen when black and had to exit out and reopen to see program.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Windows 10 Pro 1709 build 17083.1000

### Steps to Reproduce

1. Open program
1. Make changes in a repository 
1. Add description and commit
1. Enjoy black screen for the program

**Expected behavior:** Push changes to github

**Actual behavior:** Black screen 

**Reproduces how often:** Have not tried to reproduce

#### Additional Information

Same issues appear in chrome, could be an issue with using hardware acceleration.

**Comment by iAmWillShepherd** [comment] 2018-02-02 20:55
Thanks for opening an issue!

All new issues now require steps to reproduce (also called "repro steps") the
problem or the behavior you wish to see on GitHub Desktop. We do this so we can
be certain that we are understanding what it is you're describing and don't
prematurely close the issue or implement the wrong feature. If you need help
writing detailed repro steps, please see the [How Can I Contribute? document](https://github.com/desktop/desktop/blob/master/docs/contributing/README.md).

**Comment by marcpalestina** [comment] 2018-02-02 21:24
Thank you for letting me know. I thought I put in the proper info under steps to reproduce. I tried to recreate after a system restart and seem to have something better pinned down.

1. Play video in Chrome that is playing using html5 video
2. Open github desktop
3. Make changes to a repo, leave comment and commit.
4. Program screen will go black in different places finally ending with whole window black.
5. Closing and reopening the program fixes it but seems to randomly repeat.

This is using an AMD GPU on Windows 10 with Radeon Software Version 18.1.1.

Side note: The How Can I Contribute? link goes to a page not found. I think the page you were referencing was [desktop/CONTRIBUTING.md](https://github.com/desktop/desktop/blob/master/CONTRIBUTING.md)

Thank you.

**Comment by iAmWillShepherd** [comment] 2018-02-02 21:44
@marcpalestina thanks for the steps to reproduce as I was not able to reproduce with your original steps. Also, I appreciate you pointing out that link issue. I use snippets and I had not updated it since our docs have changed.

**Comment by marcpalestina** [comment] 2018-02-02 22:20
@iAmWillShepherd Thank you for looking into it. If I am able to reproduce it better I will update the steps.

One thing to look at is, as I made mention in the first post, I think this issue is related to an issue with Chromium which, unless I am mistaken, GitHub Desktop is built on. I had the same issue come up in Chrome and had to go into the settings and turn off "Use hardware acceleration when available". By the looks of things I do not see if there is a way for a user to do so. I maybe wrong if this is the actual case but it is discussed in this thread on [productforums.google.com](https://productforums.google.com/forum/#!topic/chrome/Zeh76dW19QU). I hope this helps with a solution and not just a random correlation or wrong assumption. Thank you again.

**Comment by shiftkey** [comment] 2018-02-03 11:02
>  I had the same issue come up in Chrome and had to go into the settings and turn off "Use hardware acceleration when available".

This is something that Electron also supports, through the [`app.disableHardwareAcceleration()`](https://electronjs.org/docs/api/app#appdisablehardwareacceleration) API.

Rather than making this a general option for users to manage, I'd design this to be an [escape hatch](https://dictionary.cambridge.org/dictionary/english/escape-hatch) without a UI to go with it. I say this because the Electron API needs to be invoked _before_ the application is ready (i.e. the user can interact with the app).

I'd recommend Desktop check for an environment variable named something like `DESKTOP_DISABLE_HARDWARE_ACCELERATION` (this is basically what the classic GitHub for Windows app did) and then calling the right Electron API. This means we'll also be able to support users who are unable to launch Desktop due to video card issues with hardware acceleration, if they're out there.

**Comment by NikolaTotev** [comment] 2018-03-09 19:48
I just updated windows and the same bug happened. Even after full reinstall github desktop is just black.

**Comment by elliot-labs** [comment] 2018-03-31 11:07
I just updated to the latest release 1.1.1 and I am experiencing the same black screen issue.
Everything is completely black but the interface still works as indicated by cursor changes. also the interface is interactive by the fact that I can press the maximize button and the close window button.

I did not update windows, Github desktop was working, an application restart was requested for the github desktop application to update, I pressed restart, and the app relaunched, except this time it was a completely black UI.

Steps to reproduce:
Start application.

Troubleshooting:
Uninstall and reinstall the application,
Update graphics drivers.
Reboot computer.

System Info (post driver update):
```
OS Name	Microsoft Windows 10 Pro
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ELLIOT-LAPTOP
System Manufacturer	Dell Inc.
System Model	Latitude E5470
System Type	x64-based PC
System SKU	06DE
Processor	Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz, 2801 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.18.6, 12/8/2017
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Bound
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.16299.248"
User Name	ELLIOT-LABS\elliot
Time Zone	Eastern Daylight Time
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	11.8 GB
Total Virtual Memory	18.2 GB
Available Virtual Memory	14.0 GB
Page File Space	2.38 GB
Page File	C:\pagefile.sys
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, Secure Memory Overwrite, UEFI Code Readonly, SMM Security Mitigations 1.0
Virtualization-based security Services Configured	
Virtualization-based security Services Running	
Device Encryption Support	Meets prerequisites
A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

Thanks!

**Comment by elliot-labs** [comment] 2018-04-01 19:09
I was able to resolve it on my side by switching my rendering to the integrated graphics (Intel) instead of my discrete card (AMD).

Power saving is on the Intel chipset where high performance is on the AMD chipset.

![intel](https://user-images.githubusercontent.com/5030490/38176525-a9bb2cd6-35be-11e8-8197-6f8c470a1e5c.PNG)

**Closed** 2018-04-12 14:42 UTC
Labels: reviewer-needs-to-reproduce

**Comment by Aangbaeck** [comment] 2018-04-25 13:18
This is very much still a problem. I was able to fix it with the help of this thread though. Thanks!

**Comment by iAmWillShepherd** [comment] 2018-04-25 15:28
@Aangbaeck , would you mind sharing what worked for you?

**Comment by Aangbaeck** [comment] 2018-04-26 12:49
I dropped alot of graphics settings (hardware acceleration and antialiasing etc) in the AMD graphics setttings dialogue on my computer. I did it specifically for this app and it solved the issue. Sorry that I can't be more specific.

**Comment by iAmWillShepherd** [comment] 2018-04-27 03:54
Could you try re-enabling hardware acceleration to see if the problem comes back? I have a hunch that's the issue. Also, did adding [this environment variable](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) have any effect?

**Comment by danieldogeanu** [comment] 2018-06-11 19:10
This is still a problem. I've done the same thing, I changed the graphics settings, to `Power Saving` and it worked. It doesn't work on `High Performance`. I guess this has something to do with AMD Radeon graphics cards. It was in the `Not Assigned` mode initially, and I guess that's set to `High Performance` by default. 

I haven't made any changes to any environment variables at all. Just reinstalled the app and got a black screen after restarting it.

![github_settings](https://user-images.githubusercontent.com/5739197/41251725-7b4b97f4-6dc3-11e8-997c-d60e4edc9efb.PNG)

**Comment by anisharya16** [comment] 2018-07-07 15:14
thanks for this, i changed to Power saving mode and it worked for me
