### ISSUE TITLE
Only show 'Unable to fetch' dialog when user has initiated fetch

### ISSUE THREAD

**Issue by OiYouYeahYou** [desktop/desktop#4134] opened 2018-02-28 22:45 UTC
### Description

When the application is unable to fetch a dialog is produced informing the user. This is useful when the user has clicked on the sync button. But I have found it a nuisance when disconnected and wanting to commit code offline.

I thought of the #3854 Offline mode myself. But it is clunky as there are situations where one may be fetched from a non-network location.

### Version

**GitHub Desktop version:** 1.1.0
**OS version:** OSX and Win 10

### Steps to Reproduce

1. Go offline
1. Wait
1. Observe dialog when it appears

**Suggested behavior:**  Only show 'Unable to fetch' dialog when the failure is from a user-initiated fetch. Stay silent from auto-fetch

**Comment by shiftkey** [comment] 2018-03-01 00:32
I was about to move this over to #3854 which is talking about "Offline mode" but then realised that we shouldn't be displaying fetch errors when the background fetch is occurring. We should try and reproduce this issue and correct this behaviour, and then talk about controlling the background fetch in #1128 because "offline mode" probably isn't something we want to be managing in the app.

**Comment by tierninho** [comment] 2018-09-17 21:33
Based on the reproduction of this issue while offline: 

A manual fetch produced this:
<img width="1078" alt="screen shot 2018-09-17 at 2 12 27 pm" src="https://user-images.githubusercontent.com/14828183/45650845-75d2d180-ba84-11e8-896e-6a6df1b4cbfd.png">

while an automatic fetch produced these (no UI errors seen):
<img width="1298" alt="screen shot 2018-09-17 at 2 14 57 pm" src="https://user-images.githubusercontent.com/14828183/45650920-ab77ba80-ba84-11e8-9b51-0ceb70378889.png">
<img width="675" alt="screen shot 2018-09-17 at 2 29 02 pm" src="https://user-images.githubusercontent.com/14828183/45651396-3f965180-ba86-11e8-95f4-d205d6423195.png">

> We should try and reproduce this issue and correct this behaviour, and then talk about controlling the background fetch in #1128 because "offline mode" probably isn't something we want to be managing in the app.

@shiftkey Lemme know if this is sufficient to close this issue. Thanks.

**Comment by billygriffin** [comment] 2018-10-01 16:21
Given the response above from @tierninho I'm going to go ahead and close this. We can reopen if we see it again!

**Closed by billygriffin** 2018-10-01 16:21 UTC
Labels: investigation-needed
