### ISSUE TITLE
Wrong identity when committing changes 

### ISSUE THREAD

**Issue by Tingkai-Z** [desktop/desktop#8432] opened 2019-10-08 20:39 UTC
### Describe the bug

I have two github accounts. I first loged out my personal account from github desktop and loged in the work account. 
When I commit the changes to the branch, it shows I am commit as my personal account. While my personal account does not even have access to that repo. 

### Version & OS

Version 2.2.0
Windows 10

### Steps to reproduce the behavior

1. Have first account loged in
2. Log first account out
3. Log in the second account
4. commit changes to a branch (as that second account)
5. See the commit information on github  (It shows commit as the first account)

### Expected behavior

Commit changes as the right identity

### Actual behavior

I am not sure why this happened.

### Screenshots

![image](https://user-images.githubusercontent.com/55846029/66430992-293c9a00-e9e9-11e9-9414-2c2c88d9c2cd.png)

The one with a bright yellow glow profile picture is my personal account.
The one with the default picture is my work account.

### Logs

https://gist.github.com/tingkai-zhang/6d1c623752e4d98f313d1f6e2d946347

**Comment by kuychaco** [comment] 2019-10-08 20:56
Thanks @Tingkai-Z or taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/610 (scenario 4). Please follow that issue for further updates.

**Closed by kuychaco** 2019-10-08 20:56 UTC
