### ISSUE TITLE
Error 0x80071129: The tag present in the reparse point buffer is invalid when default install location is used and is synced with OneDrive

### ISSUE THREAD

**Issue by axsms** [desktop/desktop#16593] opened 2023-04-24 14:24 UTC
### The problem

I receive "error 0x80071129: The tag present in the reparse point buffer is invalid" when synchronizing a large number of repositories in the default Desktop install location of Documents. 

### Release version

Version 3.2.1 (x64)

### Operating system

Windows 10 Enterprise

### Steps to reproduce the behavior

Attempt to apply properties to a file that has this issue and the error will display.  Properties may be applied automatically by right-clicking a synchronized directory in Windows Explorer and deselecting Always keep on this device, which worked fine. But then enabling Always keep on this device caused the issue. 
### Log files

The log files contain confidential information and no errors. The error is in Windows, exacerbated by GH Desktop. 

### Screenshots

![image](https://user-images.githubusercontent.com/83303625/234025715-4ef741fb-9d25-47ee-804c-a1fe7195a2f9.png)

### Additional context

Please see #13017 which is calling out the default save location. I am opening this issue because it actually contributes to this error, which becomes more likely to occur when a large number of files or frequently changing files are synchronized by OneDrive. 

I anticipate that this error will be relatively rare on a small number of files, given that the likelihood of encountering it appears to be influenced by the quantity of files. Furthermore, the specific file types contained within a repository may contribute to this issue as well, due to Windows security settings that may be in place. However, this further supports the case @BioTurboNick presented in #13017.

This is the second occurrence in two days for me. The resolution is to run `chkdsk c: /r /f` (assuming _c:_ is the default drive of the user profile). This takes approximately 30 minutes on my system, which has 16GB DDR4, 1TB NVMe, and Ryzen 9 processor. The system cannot be used during this time, by the way.

**Comment by sergiou87** [comment] 2023-04-25 08:15
Thank you for your report @axsms ! If I'm not missing anything, this is a duplicate of #13017

I see #13017 is not labelled so I think nobody in the team saw it 😞 And I think it makes sense, if Windows now syncs `Documents` by default via OneDrive, and given we recommend people not to use OneDrive/Dropbox/etc. to store repositories in them.

I will close this in favor of #13017 and talk to my team about what to do. Please let me know if I'm wrong and this is something else.

**Closed as not planned by sergiou87** 2023-04-25 08:15 UTC

**Comment by axsms** [comment] 2023-04-25 11:53
Perfect. Thank you, @sergiou87.

**Comment by joekron** [comment] 2025-12-10 17:24
I had the exact same issue as @axsms after trying to remove old onedrive and sharepoint synced folders. I found i could just delete as many subfolders as possible, one by one, until you find which one will not delete. then cut and paste that to somewhere else on your pc, and delete the then empty old onedrive folders. its quicker than running chkdsk c: /r /f
