### ISSUE TITLE
Detached HEAD + Uncommitted Changes = Cannot Switch Branch

### ISSUE THREAD

**Issue by the-avid-engineer** [desktop/desktop#7715] opened 2019-06-06 18:51 UTC
## Description
There is a problem when switching from a Detached HEAD to a branch if you have uncommitted changes.

## Version
* GitHub Desktop: 2.0.3
* Operating system: Microsoft Windows [Version 10.0.17134.765]

## Steps to Reproduce
1. In GitHub Desktop, Clone a repository that has some commits
2. Make some arbitrary change, so that you see at least one file on the `Changes` tab in GitHub Desktop
3. On the `History` tab in GitHub Desktop, right-click any commit and click on `Copy SHA`
5. In Git Bash (or anything that can run a git command), run `git checkout <paste>` (paste the Commit SHA you copied)
6. In GitHub Desktop, try to switch from `Detached HEAD` to any branch

Assuming you cannot switch (which is the case for me every time), here's what I do next to get around it:

7. In Git Bash, run `git add .` and `git stash` to stash all changes
8. In GitHub Desktop, try to switch from `Detached HEAD` to any branch

### Expected Behavior
Step 6 should switch to the selected branch

### Actual Behavior
Step 6 does not switch to the selected branch, it stays on the Detached HEAD.

## Additional Information
On Step 8, I get this cute popup (the branch I tried to switch on Step 6 was `master`)

![image](https://user-images.githubusercontent.com/36554739/59058087-b8c21880-8850-11e9-9d43-4066ba97747c.png)

### Logs
[2019-06-06.desktop.production.log](https://github.com/desktop/desktop/files/3263030/2019-06-06.desktop.production.log)

**Comment by shiftkey** [comment] 2019-06-06 19:08
@the-avid-engineer thanks for submitting a detailed reproduction!

I'll see if I can reproduce this myself, and then figure out what's involved with supporting this flow.

**Comment by shiftkey** [comment] 2019-06-06 19:33
@the-avid-engineer I've been able to reproduce it, and the problem area is here:

https://github.com/desktop/desktop/blob/46291625ec0f5e72350aa714775dca16f893ee51/app/src/ui/app.tsx#L1672-L1676

We've baked an assumption into the "Switch branch" dialog setup that you'd be on a valid branch, which gets skipped when you are on a detached HEAD, so the dialog is never shown.

The simplest workaround - "just show me the dialog" - doesn't quite solve this. Here's what it looks like:

<img width="493" alt="Screen Shot 2019-06-06 at 4 29 17 PM" src="https://user-images.githubusercontent.com/359239/59060827-5d0b8580-8878-11e9-94d6-2c9651f74f12.png">

This seems reasonable, but look at that first option. We can't stash this at some arbitrary SHA, because that's not something you'll be able to get back to easily - which was the goal of this feature.

I'm gonna cc @iAmWillShepherd and @outofambit at this point for their thoughts on what we should be doing here, as well as cc @desktop/product for :eyes: and thoughts if they have them.

I've marked it as `priority-3` because this is the first report about it, but I could promote it to `priority-2` because preventing the user from switching branches feels significant enough to prioritize.

**Comment by the-avid-engineer** [comment] 2019-06-06 19:38
Just my two cents - I would expect that switching from a Detached Head to a Branch **always** brings your changes to that branch, barring any conflicts.

**Comment by iAmWillShepherd** [comment] 2019-06-06 21:33
@the-avid-engineer 

Desktop does everything possible to prevent your repo from getting into a detached head state. Since your use-case involves putting the repo in this state using the CLI, would you mind elaborating on your workflow a bit? I'd like to understand your needs a little bit more so I can identify the gaps in our original design.

In the meantime, you can use this workaround to ensure you have a branch Desktop can associate a stash with.

`git checkout -b this-would-have-resulted-in-a-detached-head <commit>`

**Comment by the-avid-engineer** [comment] 2019-06-06 21:40
@iAmWillShepherd This is just a dumb gotcha, I was not making changes to the detached head. I ran into the issue because I needed to browse a previous state of a repository on my machine, so I ran a `git checkout <commit>` in Git Bash with uncommitted changes sitting on `master`. I tried to switch back to `master` with GitHub Desktop instead of Git Bash, and voila.

**Comment by the-avid-engineer** [comment] 2019-06-06 21:45
I actually do this quite often (going to a detached head), but I'm not sure if I've ever done it before today with uncommitted changes floating around.

**Comment by iAmWillShepherd** [comment] 2019-06-06 22:50
> This is just a dumb gotcha, I was not making changes to the detached head. I needed to browse a previous state of a repository on my machine, so I ran a `git checkout <commit>` in Git Bash with uncommitted changes sitting on `master`. I tried to switch back to `master` with GitHub Desktop instead of Git Bash, and voila.

Ah! I can see how that may be frustrating. I'm a bit wary of giving the option to take changes to another branch since that is likely to result in conflicts and other gotchas. Conflicts are scary enough when you expect them to happen; having them happen when you least expect it is something I'd like to avoid.

I hope this doesn't come off as me ignoring the bit of frustration you experienced, but I'm going to close this issue out to indicate that this isn't a bug, but a deliberate design decision. I think there is more risk to supporting detached head states than reward at this time and I'm happy to continue this conversation to understand how we can improve the stashing experience.

**Closed by iAmWillShepherd** 2019-06-06 22:50 UTC
Labels: bug, priority-3

**Comment by the-avid-engineer** [comment] 2019-06-06 23:19
That's totally fair. Before I submitted this issue, I did not know that GitHub Desktop actively avoids the Detached HEAD state. I may put in a feature request to create a branch from a commit. (I didn't know this was a thing either 😂)

**Comment by iAmWillShepherd** [comment] 2019-06-06 23:31
> That's totally fair. Before I submitted this issue, I did not know that GitHub Desktop actively avoids the Detached HEAD state. I may put in a feature request to create a branch from a commit. (I didn't know this was a thing either 😂)

Now that's something I can get behind. Like, what if while in a detached head state, Desktop still allowed you to create a new branch from that commit? In that case, I think we can rely on Git's normal behavior of bringing changes over to the new branch so long as that branch is not ahead of the one you're switching from (which is never the case when creating a new one). I think that would be a decent step towards solving this issue.

**Comment by the-avid-engineer** [comment] 2019-06-06 23:37
That would be a nice touch. If the app could do it from the History context-menu, I wouldn't even need to enter the detached head state

![image](https://user-images.githubusercontent.com/36554739/59072794-0a7e9900-8879-11e9-9229-59dd170eeeac.png)

A "Branch from this commit" option, or something

**Comment by iAmWillShepherd** [comment] 2019-06-06 23:50
@the-avid-engineer,

Would you mind creating a new issue for that suggestion?

**Comment by the-avid-engineer** [comment] 2019-06-06 23:51
I will do that!

**Comment by the-avid-engineer** [comment] 2019-06-07 00:18
https://github.com/desktop/desktop/issues/7719

**Comment by Peter92** [comment] 2020-03-04 11:06
I actually had to come here and search for "detached head" to find out why I wasn't able to switch branches. The branches remain selectable but nothing happens when clicked, so it genuinely comes across as if Github Desktop is bugged.

If taking changes won't be implemented, the ideal solution in my eyes would be a popup asking if you want to discard the changes or stay in the same branch. That'd be miles better than just ignoring any commands until the changes are discarded.

**Comment by BaptisteJosh** [comment] 2021-02-12 14:47
Is there way to fix this state, this happened on one of my branches and I can't get detached head back to origin/branch

**Comment by the-avid-engineer** [comment] 2021-02-26 18:20
@BaptisteJosh Use git cli

**Comment by Novian1325** [comment] 2024-06-15 15:10
> @BaptisteJosh Use git cli

What a useless comment, people asking how to do this with desktop and your reply is dont use desktop, thanks genius
