### ISSUE TITLE
Can't find path of repo in middle of work

### ISSUE THREAD

**Issue by shivamsharmanps** [desktop/desktop#11472] opened 2021-01-28 12:35 UTC
### Describe the bug

 In the middle of work, the laptop shut down itself due to battery down then I logged-in again in the system then GitHub desktop lost path of the repo (local) and asking with this actio of button **Locate, close again  or remove**

### Version & OS
Version 2.6.2
Windows 10

### Steps to reproduce the behavior

1. Sudden system shut down 
2. Logged-in again in system
3. Open Github desktop
4. See the error "Can't find "Repo Name"

### Expected behavior

It should not have lost path of repo in local system

### Actual behavior

A clear and concise description of what actually happened.

### Screenshots

Message = "Can't find "<Repo_Name>

### Logs

/*Can not give*/

### Additional context
/*Can not give */

**Comment by frankbenoni123** [comment] 2021-01-28 12:59
Det var ikke morro. Men har opplevd dette før.   Gir oss. Nu. Oki. ?   
Bergen,  M v h 

Frank Benonisen        Sogn. El sign.       

    Den torsdag 28 januari 2021 13:36:16 CET, shivamsharmanps <notifications@github.com> skrev:  
 
 


Describe the bug

In the middle of work, the laptop shut down itself due to battery down then I logged-in again in the system then GitHub desktop lost path of the repo (local) and asking with this actio of button Locate, close again or remove

Version & OS

Version 2.6.2
Windows 10

Steps to reproduce the behavior
   
   - Sudden system shut down
   - Logged-in again in system
   - Open Github desktop
   - See the error "Can't find "Repo Name"

Expected behavior

It should not have lost path of repo in local system

Actual behavior

A clear and concise description of what actually happened.

Screenshots

Message = "Can't find "<Repo_Name>

Logs

/Can not give/

Additional context

/*Can not give */

**Comment by steveward** [comment] 2021-01-28 18:03
Thanks for the report @shivamsharmanps. Was it only one repository that was lost on disk? We've seen reports of repositories being lost after updates (i.e. https://github.com/desktop/desktop/issues/10548). Is it possible an update was triggered after you restarted GitHub Desktop?

I'm going to close this out since it sounds like a once-off bug, but if we continue to hear reports of this happening we can reopen for further investigation.

**Closed as completed by steveward** 2021-01-28 18:03 UTC
