### ISSUE TITLE
Unicode text files are not supported

### ISSUE THREAD

**Issue by DannyVarod** [desktop/desktop#5487] opened 2018-08-27 17:11 UTC
*  UTF-16 text files are recognized as binary and hence their content is not displayed

* UTF-8 text files are displayed with a unicode character at the beginning of the file (assume entire file in same language)

Possible solution: Identify the encoding of the file by the unicode characters and enable displaying non-ANSI files correctly (or at least the common formats e.g. UTF-8, UTF-16, UTF-32).

**Comment by iAmWillShepherd** [comment] 2018-08-27 18:13
Thanks for taking the time to open an issue! 🙇 

@DannyVarod, could you clarify the following line for me?

> UTF-8 text files are displayed with a unicode character at the beginning of the file (assume entire file in same language)

* Are you referring to the filename, commit summary and/or description, or file contents?
* Could you include a test file I can use to reproduce this issue?
* Could you also provide images and/or GIFs of the issue in action?

As far as I know, Desktop uses _utf-8_ encoding, so I'm interested to know what's failing here.

**Comment by DannyVarod** [comment] 2018-08-29 09:33
UTF-8 example, a red dot appears at the beginning of the file content:
![githubdesktop-utf-8](https://user-images.githubusercontent.com/3163137/44779005-0786a780-ab87-11e8-88ba-6624bad49aba.png)

When converting file encoding, this red dot appears as a change:
![githubdesktop-utf-8 2](https://user-images.githubusercontent.com/3163137/44779175-719f4c80-ab87-11e8-8271-134ca002e7ca.png)
Perhaps a better behavior would be to notify on encoding change separately from content change.

UTF-16 example, content display is not available:
![githubdesktop-utf-16](https://user-images.githubusercontent.com/3163137/44779007-0786a780-ab87-11e8-9c53-84b6db115784.png)

**Comment by iAmWillShepherd** [comment] 2018-08-30 17:04
We actually have a few issues tracking something very similar to this, #1607 and https://github.com/desktop/desktop/issues/3923. We have not heard much feedback about utf-8 encoding being an issue, so the work needed to make this happen hasn't been prioritized. 

Bumping @desktop/product for thoughts on adding the ability for desktop to detect the encoding of a file and offer users the option to change how a file is decoded.

@desktop/eng Is it possible for git to detect file encoding changes independently of its content?

**Comment by billygriffin** [comment] 2018-08-31 15:07
@desktop/support Are there specific configuration-related things @DannyVarod can do to mitigate this?

**Comment by billygriffin** [comment] 2018-09-01 00:51
Thanks @steveward! Since there's a workaround here and there are other open issues relating to our handling of encoding, I'm going to close this.

**Closed by billygriffin** 2018-09-01 00:51 UTC

**Comment by AllanRobertson** [comment] 2021-09-13 20:30
github.com is not able to diff nor (easily) display unicode files.
They are treated as binary files. If it is possible to get GitHub Desktop to work, then what is preventing github.com from displaying unicoded?

**Comment by davidcorbin-atmosera** [comment] 2023-04-25 13:39
"working-tree-encoding=utf-16" does not seem to be a workaround in any case... What is needed is the ability for Git to keep all file encodings IDENTICAL, and be enhanced to actually work with them.... I have many files where different unicode characters all "Degrade" to the same UTF-8. Also it is unknown when someone will save a file (properly or in error) with a different encoding, so that is something that should be readily highlighted in *any* diff.

**Comment by RokeJulianLockhart** [comment] 2023-09-26 23:09
> and there are other open issues relating to our handling of encoding

@billygriffin, which?
