### ISSUE TITLE
"error: you need to resolve your current index first"

### ISSUE THREAD

**Issue by nunoperalta** [desktop/desktop#8739] opened 2019-12-03 09:22 UTC
### Describe the bug

Not able to switch a branch and bring changes to it, after resolving conflicts.

### Version & OS

2.2.3
Windows 10

### Steps to reproduce the behavior

1) Pull some changes from origin that will conflict with your current modified files.

2) Resolve these conflicts in Visual Studio Code.

3) GitHub Desktop will now display a "green tick" on these conflicted files, saying that the conflicts were resovled.

4) Try to switch Branch and choose "Bring my changes to XXXX"

5) You get an error: "error: you need to resolve your current index first"

There is absolutely no way, as far as I can see, to stage the conflicted files to the index.
I tried context menus, top menus, untick and tick again the checkbox, etc...

The only way I could fix this was by externally adding/staging the 3 conflicted files.

I would like GitHub to either auto-stage the files, if the checkbox is ticked, or have another option to Stage/Add, e.g. in the context menu.

**Comment by niik** [comment] 2019-12-03 14:55
Hi @nunoperalta, thanks for opening this.

I believe what you are describing is the expected behavior, this is due to the underlying constraints enforced by Git. You need to either commit or abort the merge after resolving your conflicts, only then are you allowed to switch branches.

When Git encounters a conflict it sets up the index and the working directory with special metadata such that it can accurately create a merge commit based on the two diverging trees. There's no way currently to safely stash all that metadata and bring it to another branch.

Could you describe what you're trying to achieve by stashing and bringing the resolved files to another branch?

**Comment by nunoperalta** [comment] 2019-12-03 18:57
Hello,

Definitely not an expected behavior to me, and unfortunately a limitation.
The expected behavior to me is to give flexibility to a developer. Something I always had with SVN, but with Git I really feel like a lot of things just slow me down, or need many workarounds just to get what I want.

So, this is my scenario (which already happened a few times):

1) I make some changes in the main branch (e.g. master, or whatever "base" branch everyone is based on), but I don't commit/push anything there.

2) Eventually I create a branch for this work I'm doing, but before that, I pull any changes that are pending.

3) Because some of those changes were made on places I have changes on, there are some conflicts created.

4) I edit the files in Visual Studio Code. The conflicts are marked as resolved in GitHub Desktop.

5) I can't move to the new branch I created because I can't bring my changes to it:
"error: you need to resolve your current index first"

6) Then I come back to Visual Studio Code, and use the extension Git Lens to resolve the problem for me. What I do is press the "+" icon ("Stage this file/change"), which puts the previously conflicted files back to the Staged Files.

This makes GitHub show again the "Modified" icon, instead of "Conflict Resolved" icon.

7) Now I can move to the branch and bring my changes to it.


Why is Git / GitHub forcing me to commit my changes to the master, simply because I had some conflicts there? That doesn't make any sense.

And the solution is simple: add some button/option so I can put those files back to the staged files, or simply do that automatically...


If it helps, please note that I have Auto-Stash and Rebase enabled.
Without these options, Git is simply a NIGHTMARE to work with.

The only problem I have now with Git is this limitation I explained above.

**Comment by niik** [comment] 2019-12-04 15:02
Hi @nunoperalta, I can definitely understand the frustrations related to switching from one version control system and its idiosyncrasies to another. Especially when it feels like the new system is fighting against you and making you feel like you're not able to work as quickly and efficiently as you've done in the past.

As I hinted at in my previous answer there's not a whole lot we (i.e. the GitHub Desktop developers) can do here. To the best of my knowledge (though I've been wrong before) Git does not support stashing an unmarked index (i.e. an in-progress merge conflict resolution). The exact reasoning behind that is something that can only be provided by the developers of Git itself but I'm afraid that by manually staging the file and then stashing you're inadvertently going to create a single parent commit instead of a merge commit (a commit with two or more parents).

My recommendation to work around this would be to always start by creating a new branch instead of working on master. You can always merge from master into your new branch which will achieve the same result as staying on master and pulling but you won't run into the issue of having to attempt to carry conflicted changes with you to another branch. Branches are quick to create and remove in Git compared to other version control systems and should be used liberally and you can easily rename your branch in GitHub Desktop later in case you didn't get the name right from the beginning. See this guide about [GitHub's recommended flow](https://guides.github.com/introduction/flow/) for more information.

 I'm going to close this issue since since there's not much our team can do here. I hope you're able to find a workflow that suits your needs.

**Closed by niik** 2019-12-04 15:02 UTC
Labels: more-info-needed, support

**Comment by ghnp5** [comment] 2019-12-04 18:50
@niik I honestly don't understand how you can't do much about this...

I said in my previous reply:

> Then I come back to Visual Studio Code, and use the extension "**GitLens**" to resolve the problem for me. What I do is **press the "+" icon** ("Stage this file/change"), which puts the previously conflicted files back to the Staged Files.


So, there **is** an easy solution, which is to just Stage the previously conflicted file again to the index. That's basically doing a "**git add**".

That solution is also explained here:
https://appuals.com/how-to-fix-git-error-you-need-to-resolve-your-current-index-first/

> An example is:
> $ git add file.txt
> $ git commit
> You can add your personal commentary while committing. An example is:
> $ git commit –m “This is Appuals Git repository”


Also suggested here:
https://stackoverflow.com/questions/14171076/how-to-resolve-a-git-merge-conflict

> $ emacs GDCatalog/.classpath
> ... resolve conflict ...
> $ git add GDCatalog/.classpath
> ... do the same for all other files ...
> $ git commit


So, why are you ignoring this as a problem/limitation that "can't do much about it", when ALL you need to do is add an option to "re-add/stage" to the index?
(or do it automatically as soon as conflict is resolved, if the checkbox is already ticked anyway)


Having to go to the command line, or having to use another GUI to fix a simple problem, to me, isn't ideal... I'm using GitHub Desktop so I don't need to use the command line or any other GUI.


> To the best of my knowledge (though I've been wrong before) Git does not support stashing an unmarked index (i.e. an in-progress merge conflict resolution).

Hence I'm suggesting to re-add the file to the index, after the conflict is resolved... (or have a context menu option to do it)


> I'm afraid that by manually staging the file and then stashing you're inadvertently going to create a single parent commit instead of a merge commit (a commit with two or more parents).

And is this a reason to not provide the option?
Those files aren't even committed.

All I'm doing is pulling whatever is **already** committed, into my local workstation.
Then, I simply want to move to another branch with the exact same changes I had before pulling.

If this is not something I should do, then why provide the option to "bring changes to branch" at all, anyway?

**Comment by nunoperalta** [comment] 2019-12-04 18:50
@niik I honestly don't understand how you can't do much about this...

I said in my previous reply:

> Then I come back to Visual Studio Code, and use the extension "**GitLens**" to resolve the problem for me. What I do is **press the "+" icon** ("Stage this file/change"), which puts the previously conflicted files back to the Staged Files.


So, there **is** an easy solution, which is to just Stage the previously conflicted file again to the index. That's basically doing a "**git add**".

That solution is also explained here:
https://appuals.com/how-to-fix-git-error-you-need-to-resolve-your-current-index-first/

> An example is:
> $ git add file.txt
> $ git commit
> You can add your personal commentary while committing. An example is:
> $ git commit –m “This is Appuals Git repository”


Also suggested here:
https://stackoverflow.com/questions/14171076/how-to-resolve-a-git-merge-conflict

> $ emacs GDCatalog/.classpath
> ... resolve conflict ...
> $ git add GDCatalog/.classpath
> ... do the same for all other files ...
> $ git commit


So, why are you ignoring this as a problem/limitation that "can't do much about it", when ALL you need to do is add an option to "re-add/stage" to the index?
(or do it automatically as soon as conflict is resolved, if the checkbox is already ticked anyway)


Having to go to the command line, or having to use another GUI to fix a simple problem, to me, isn't ideal... I'm using GitHub Desktop so I don't need to use the command line or any other GUI.


> To the best of my knowledge (though I've been wrong before) Git does not support stashing an unmarked index (i.e. an in-progress merge conflict resolution).

Hence I'm suggesting to re-add the file to the index, after the conflict is resolved... (or have a context menu option to do it)


> I'm afraid that by manually staging the file and then stashing you're inadvertently going to create a single parent commit instead of a merge commit (a commit with two or more parents).

And is this a reason to not provide the option?
Those files aren't even committed.

All I'm doing is pulling whatever is **already** committed, into my local workstation.
Then, I simply want to move to another branch with the exact same changes I had before pulling.

If this is not something I should do, then why provide the option to "bring changes to branch" at all, anyway?

**Comment by tierninho** [comment] 2019-12-16 19:09
@niik added comments from a new issue #8800 addressing the same subject. I closed the newer issue as it is better to keep all the comments together in one issue. 

---

Hello,

I'm really not happy with the fact that my previous request was discarded/ignored so easily: https://github.com/desktop/desktop/issues/8739

All I'm asking is whether it's possible to add a context menu option that will simply perform the following command:

`git add FILE_PATH`

So that after a conflict was resolved, we can add the file back to the index, and therefore be able to perform a 'switch branch' without getting the error:

> error: you need to resolve your current index first

--

1) Make changes on a file as you go.
It is not convenient at this time to create a new branch, so you just work on the master.

![image](https://user-images.githubusercontent.com/57591332/70852821-d75b3900-1e9d-11ea-8b1d-d1db727b9ca6.png)

2) Now you want to create a new branch, but you want to update your current master with all the changes made since your last update.

3) You get a conflict, and you resolve it.

![image](https://user-images.githubusercontent.com/57591332/70852864-4173de00-1e9e-11ea-8314-a9c19eca1d22.png)

4) Since the conflict is resolved, there should be nothing stopping you from switching to a new branch. After all, you should be in the exact same state as you were before the conflict happened.

5) However, if you switch to the new branch with the option "Bring my changes to XXX":

![image](https://user-images.githubusercontent.com/57591332/70852877-6e27f580-1e9e-11ea-8f0f-d4177a5c4c31.png)

6) I can easily fix this by running:

`git add README.txt`

And the file is back to normal (look at the icon at the right):

![image](https://user-images.githubusercontent.com/57591332/70852887-8a2b9700-1e9e-11ea-9452-1a3746e6f324.png)

7) Now I can switch branch.

--

My question is -- **can we have this "git add" feature in GitHub Desktop itself, without having to do it manually or using 3rd party UIs?**

Or, if the "checkbox" at the left is Ticked, shouldn't "git add" be done automatically anyway?


![image](https://user-images.githubusercontent.com/57591332/70852916-04f4b200-1e9f-11ea-9b38-d73f03bbb0b5.png)

**Why do I want to do this? (use case)**

Due to the high pace development in my team, I want to always work with the latest code, as much as possible. Therefore, I develop while I am in "master".

However, at the time I'm ready to commit my changes, I must create a branch and then do a pull request.

But, every time I did a "pull/update" from master, some conflicts might have happened, and those are stopping me from moving to my new fresh branch, until I do "git add" for all those conflicted (now resolved) files.

**Comment by nunoperalta** [comment] 2020-01-28 22:40
@tierninho  @niik - Regarding this you said:

> My recommendation to work around this would be to always start by creating a new branch instead of working on master.

I just want to add that someone else mentioned the exact workflow I described above, in #7746 :

> To not be annoyed by this, it forces a workflow on the user of defining their branch before making their changes. That's not how we work. If we find a problem, we solve the problem, then commit that work in a branch for PR review.

So as you can see, I'm not the only one doing this.


I understand if my suggestion can't be implemented just yet (although it's hard for me to believe it's that hard to develop), but **can this Issue at least stay open, as it's a very valid feature suggestion?**

**Comment by tierninho** [comment] 2020-01-29 00:17
@nunoperalta At this point the previous comments around the limitations still stand. Apologies if it is disrupting your workflow. 

There may be some relief ⬇️ in this week's releases, as we are opening up the preferences around staging files.

<img width="727" alt="71534387-53e51300-28b3-11ea-84bb-e5b811b03432" src="https://user-images.githubusercontent.com/14828183/73316927-919dca00-41d8-11ea-90b0-143325b5a1c4.png">

Note, there are numerous issues we reopen when the time comes to revisit certain areas of the app. We mainly close issues so we can focus on ones that need more immediate attention.

**Comment by nunoperalta** [comment] 2020-01-29 17:52
Thank you. The popup doesn't really bother me (I like to be asked what to do when I switch, as I don't want always the same). Have a good day.
