### ISSUE TITLE
Squash/rebase dialog remains open (blank) after finishing work

### ISSUE THREAD

**Issue by Sergio0694** [desktop/desktop#16849] opened 2023-06-06 11:41 UTC
### The problem

Since a few releases ago (a couple weeks maybe?) it seems the squash/rebase dialog is a bit broken. By that I mean, every time I squash commits and/or rebase, I end up with the dialog popping up, completely blank, after all work is already done. It's not a show stopped, but it's a bit annoying, as you just have to manually close it every time. I basically end up with this:

![](https://github.com/desktop/desktop/assets/10199417/89f2658b-2691-4301-9df2-54a7c690c923)

Every single time I squash/reorder/rebase stuff.

### Release version

3.2.3 (x64)

### Operating system

Windows 11 (x64), build 22621.1178

### Steps to reproduce the behavior

1. Squash/reorder some commits
2. Observe that after applying changes, the blank dialog above pops up

### Log files

[2023-06-06.desktop.production.log](https://microsofteur-my.sharepoint.com/:u:/g/personal/sergiopedri_microsoft_com/ESUJupseOulGiP8EOkc-N3QB9azG4cMR0vGfMGGs_Nr64Q?e=8qFaKF)

> **Note**: only `@microsoft` AAD accounts can open the link (I'm working on the Microsoft Store, so the logs include some internal names which I can't share here).

**Comment by sergiou87** [comment] 2023-06-06 11:42
Duplicate of https://github.com/desktop/desktop/issues/16605, fixed in https://github.com/desktop/desktop/pull/16632

Thanks for your report anyway!

**Closed as completed by sergiou87** 2023-06-06 11:42 UTC
