### ISSUE TITLE
Github Desktop Azure Repos Authentication failed not asking for credentials

### ISSUE THREAD

**Issue by redubleglen** [desktop/desktop#9816] opened 2020-05-17 10:20 UTC
### Describe the bug

I have a new Azure Repo and need to clone it via GitHub Desktop
Usually if I clone it in GitHub Desktop, it would ask me for my username and password (Personal Token)… but this time it just show an error message of Authentication failed. No more fields to enter my credentials.

### Version & OS

Version 2.5.0

### Steps to reproduce the behavior

Here's a sample private repo I made for this https://githubdesktest@dev.azure.com/githubdesktest/gittestprivate/_git/gittestprivate
 (i'll probably delete this after 3 days)

1.) Clone repository (URL) with https://githubdesktest@dev.azure.com/githubdesktest/gittestprivate/_git/gittestprivate
2.) Once clone is pressed the Authorization failed message shows.

### Expected behavior

A username and password field should show.

### Actual behavior

Error message is showing.

### Screenshots

![image](https://user-images.githubusercontent.com/50043636/82141798-cd819b80-986a-11ea-9531-187a7a884341.png)

### Logs

2020-05-17T10:16:39.592Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://githubdesktest@dev.azure.com/githubdesktest/gittestprivate/_git/gittestprivate'
2020-05-17T10:16:40.381Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- https://githubdesktest@dev.azure.com/githubdesktest/gittestprivate/_git/gittestprivate C:\Users\nndata\Documents\GitHub\gittestprivate` exited with an unexpected code: 128.
stderr:
Cloning into 'C:\Users\nndata\Documents\GitHub\gittestprivate'...
fatal: Authentication failed for 'https://dev.azure.com/githubdesktest/gittestprivate/_git/gittestprivate/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)

**Comment by redubleglen** [comment] 2020-05-17 10:54
Can someone please confirm if this has already been fixed for the next Release?

Tried to download the Beta version **Version 2.5.1-beta1** and this issue is fixed there.

I can access the Azure repo using this beta version, as it asked me for the credentials.

**Comment by HossienMehdikhah** [comment] 2020-05-18 06:18
ok, i solve my problem i install visual studio but not install git.
i use github and github use git.

**Comment by rafeca** [comment] 2020-05-18 09:06
Hey @redubleglen ! Thanks for filling this issue and apologies for the caused inconvenice.

As you mention, this has indeed been fixed in v2.5.1-beta and the fix will come to the next stable version of Desktop. You can check https://github.com/desktop/desktop/issues/9776 for more context 😃

**Closed by rafeca** 2020-05-18 09:06 UTC

**Comment by in-fke** [comment] 2024-06-14 08:13
Seems to re-occur?
![image](https://github.com/desktop/desktop/assets/73228413/395da955-1689-4848-98e5-24538901fde4)
