### ISSUE TITLE
Pull request is shown as passing when in fact it is still pending

### ISSUE THREAD

**Issue by BasThomas** [desktop/desktop#4142] opened 2018-03-01 09:35 UTC
### Description

With the recently introduced pull request status in GitHub Desktop, it seems like a pending pull request can be shown as passing:

GitHub:
<img width="38" alt="screen shot 2018-03-01 at 10 31 30" src="https://user-images.githubusercontent.com/4190298/36837181-e9759686-1d3b-11e8-9821-67e05f394fda.png">

GitHub Desktop:
<img width="74" alt="screen shot 2018-03-01 at 10 31 17" src="https://user-images.githubusercontent.com/4190298/36837182-e9e2cf62-1d3b-11e8-885f-0813950f3b13.png">

### Version

**GitHub Desktop version:** 1.1.0

**OS version:** macOS 10.13.3

### Steps to Reproduce

1. Checkout a branch of a pull request that has both passing and pending checks
1. Expect to see a pending status in GitHub Desktop

**Expected behavior:** The status should be pending (yellow dot)

**Actual behavior:** The status is shown as passing

**Reproduces how often:** Not sure

**Comment by iAmWillShepherd** [comment] 2018-03-01 18:24
Thanks for taking the time to open an issue! 🙇 

When you observe this behavior, how much time has elapse between you kicking off a new build and checking to see if the status is updated in Desktop? There is some delay between when you do something on dotcom and when Desktop updates to reflect that event.

**Comment by iAmWillShepherd** [comment] 2018-03-01 18:54
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4122. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-03-01 18:54 UTC
Labels: more-information-needed
