### ISSUE TITLE
External Diff is the only reason I suffer SourceTree

### ISSUE THREAD

**Issue by SurajGupta** [desktop/desktop#3091] opened 2017-10-18 13:41 UTC
Please add an External Diff feature where I can call-out to an external diff tool like Beyond Compare or Araxis.

The lack of this feature is the only reason I continue to suffer SourceTree, which has gotten worse with each release.  Oh - as a reminder, you and Atlassian are competitors.  Wouldn't this be a nice ________________ (insert your catch phrase here)?

**Comment by wlscaudill** [comment] 2017-10-18 13:46
PLEASE add this, it's a little strange/ridiculous that this isn't supported already.  This is the first source management client of all the ones I've used throughout my 15 year career that doesn't support this!  I also suffer SourceTree for this feature and agree that the product continues to degrade with each release...

**Comment by j-f1** [comment] 2017-10-18 14:58
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1765. Please follow that issue for further updates.

**Comment by iAmWillShepherd** [comment] 2017-10-18 15:18
> This is the first source management client of all the ones I've used throughout my 15 year career that doesn't support this

@wlscaudill we are actively working on adding features such as the one you are requesting, but we first had to get more basic functionality completed. See our [Roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md) to see what you can expect from us down the road.

**Comment by iAmWillShepherd** [comment] 2017-10-18 15:25
Please follow the issue @j-f1 referenced. I will be closing this one and re-opening issue #1765.

**Closed by iAmWillShepherd** 2017-10-18 15:25 UTC
