### ISSUE TITLE
Branch button won't automatically update for new PR with # and status

### ISSUE THREAD

**Issue by jonator** [desktop/desktop#5052] opened 2018-06-27 18:58 UTC
## Description

When I open a pull request, the pull request number/status is not automatically updated in the branches button. It only updates if I open the drop-down and select the branch I'm currently on.

## Version

* GitHub Desktop: 1.2.6

* Operating system: Microsoft Windows [Version 10.0.17134.112]

## Steps to Reproduce

1. Open pull request
2. Observe (most likely) no PR # and status indicator in branch button
3. Open the branch drop-down and select the current branch, the one with the newly opened PR.

### Expected Behavior

Network poll automatically updates PR # and status next to branch for newly create PR.

### Actual Behavior

Branch button won't automatically update for new PR with # and status.

## Additional Information

1. Make sure app is in new dark mode

### Logs

```
2018-06-27T03:33:05.313Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.237s)
2018-06-27T03:33:05.315Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access '--REDACTED--': Could not resolve host: github.com

2018-06-27T03:33:06.467Z - warn: [ui] getFetchPollInterval: failed for --REDACTED--
TypeError: Failed to fetch
2018-06-27T13:02:44.417Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at Object.t.parseError (file:///C:/Users/jon.ator/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/renderer.js:27:39622)
    at onAutoUpdaterError (file:///C:/Users/jon.ator/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/renderer.js:14:30278)
    at CallbacksRegistry.apply (C:\Users\jon.ator\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\common\api\callbacks-registry.js:46:25)
    at EventEmitter.ipcRenderer.on (C:\Users\jon.ator\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\renderer\api\remote.js:261:21)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
2018-06-27T13:02:44.419Z - error: [ui] Error checking for updates
Error: GitHub Desktop was not able to contact the update server. Ensure you have internet connectivity and try again.
    at Object.t.parseError (file:///C:/Users/jon.ator/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/renderer.js:27:39622)
    at onAutoUpdaterError (file:///C:/Users/jon.ator/AppData/Local/GitHubDesktop/app-1.2.6/resources/app/renderer.js:14:30278)
    at CallbacksRegistry.apply (C:\Users\jon.ator\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\common\api\callbacks-registry.js:46:25)
    at EventEmitter.ipcRenderer.on (C:\Users\jon.ator\AppData\Local\GitHubDesktop\app-1.2.6\resources\electron.asar\renderer\api\remote.js:261:21)
    at emitThree (events.js:135:13)
    at EventEmitter.emit (events.js:216:7)
2018-06-27T13:02:46.496Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.601s)
2018-06-27T13:02:46.499Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access '--REDACTED--': Could not resolve host: github.com



2018-06-27T13:02:47.976Z - warn: [ui] getFetchPollInterval: failed for --REDACTED--
TypeError: Failed to fetch
2018-06-27T13:33:02.311Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sommelier - jonator (has token)
2018-06-27T13:33:09.394Z - info: [ui] Executing push: git -c credential.helper= push origin EN-1276:EN-1276 --progress (took 7.061s)
2018-06-27T13:33:11.234Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.831s)
2018-06-27T13:33:15.668Z - info: [main] opening in browser: --REDACTED--
2018-06-27T14:03:08.974Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.408s)
2018-06-27T14:08:30.145Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.429s)
2018-06-27T14:13:52.574Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.622s)
2018-06-27T14:19:13.314Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.326s)
2018-06-27T14:24:34.113Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.107s)
2018-06-27T14:29:54.883Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.321s)
2018-06-27T14:35:15.922Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.577s)
2018-06-27T14:40:36.596Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.113s)
2018-06-27T14:45:57.157Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.110s)
2018-06-27T15:23:42.378Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
fatal: unable to access '--REDACTED--': Could not resolve host: github.com

2018-06-27T15:23:44.006Z - info: [ui] Executing getAheadBehind: git rev-list --left-right --count EN-1173...origin/EN-1173 -- (took 1.261s)
2018-06-27T15:23:44.677Z - info: [ui] Executing getCommits: git log HEAD --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-color -- (took 1.902s)
2018-06-27T15:23:45.682Z - warn: [ui] getFetchPollInterval: failed for --REDACTED--
TypeError: Failed to fetch
2018-06-27T16:24:08.336Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 4.335s)
2018-06-27T16:29:28.898Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.065s)
2018-06-27T16:34:49.903Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.565s)
2018-06-27T16:40:11.214Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.701s)
2018-06-27T16:45:31.804Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.127s)
2018-06-27T16:50:53.034Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.773s)
2018-06-27T16:56:14.194Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.235s)
2018-06-27T17:01:36.013Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.123s)
2018-06-27T17:06:58.235Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.624s)
2018-06-27T17:12:19.678Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.065s)
2018-06-27T17:17:40.689Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.075s)
2018-06-27T17:23:03.195Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.583s)
2018-06-27T17:28:24.738Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.118s)
2018-06-27T17:33:45.675Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.053s)
2018-06-27T17:39:07.917Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.292s)
2018-06-27T17:44:28.693Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.070s)
2018-06-27T17:49:49.717Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.093s)
2018-06-27T17:55:10.989Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.362s)
2018-06-27T18:00:31.919Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.294s)
2018-06-27T18:05:53.023Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.399s)
2018-06-27T18:11:14.120Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.496s)
2018-06-27T18:16:35.695Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.069s)
2018-06-27T18:20:08.208Z - info: [ui] No submodules found. Skipping "git submodule status"
2018-06-27T18:21:56.650Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.027s)
2018-06-27T18:27:17.705Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.074s)
2018-06-27T18:32:38.718Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.085s)
2018-06-27T18:33:49.060Z - info: [main] opening in browser: --REDACTED--
2018-06-27T18:34:06.474Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: --REDACTED-- - jonator (has token)
2018-06-27T18:34:11.178Z - info: [ui] Executing push: git -c credential.helper= push origin EN-1276:EN-1276 --progress (took 4.694s)
2018-06-27T18:34:12.291Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.109s)
2018-06-27T18:34:35.741Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: --REDACTED-- - jonator (has token)
2018-06-27T18:34:37.207Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.462s)
2018-06-27T18:37:59.502Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.324s)
2018-06-27T18:40:15.012Z - info: [main] opening in browser: --REDACTED--
2018-06-27T18:40:27.404Z - warn: [main] Prevented new window to: chrome-devtools://devtools/bundled/toolbox.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@3cf8514bb1239453fd15ff1f7efee389ac9df8ba/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true
2018-06-27T18:43:20.104Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.114s)
2018-06-27T18:48:40.873Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.252s)
2018-06-27T18:54:02.464Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.827s)

```

**Comment by shiftkey** [comment] 2018-06-27 19:08
@jonator there's two different ways that we'll check the PR information of the current branch:
 
 - the pull request fetcher is run in the background at 10min intervals
 - an action that refreshes the local repository state (fetch, checkout, etc)

I think you're triggering the second path by forcing a checkout of the current branch, but we don't currently don't have a good way to detect that you opened a PR from within the app without querying the GitHub API again.

@iAmWillShepherd any other insights to provide about this area?

**Comment by shiftkey** [comment] 2018-07-03 19:12
I'm going to close this out as "by design" - the pull request fetcher updates in the background, or a manual fetch will check the current branch matches with an open PR, and without more aggressive background work or some way for GitHub The Website to "push" a message to the client this is the fastest we can react currently.

**Closed by shiftkey** 2018-07-03 19:12 UTC
