### ISSUE TITLE
Can't switch branches or see branches

### ISSUE THREAD

**Issue by sm-cdecker** [desktop/desktop#2535] opened 2017-08-23 15:23 UTC
### Description

Branches dropdown is completely empty, entering search criteria returns nothing. Completely unable to see or switch branches after recent update.

### Version

**GitHub Desktop version:** Version 0.8.1-beta1

**OS version:** Windows 10 64 bit

**Expected behavior:** 
I expected to see a list of my branches that I can switch between.

**Actual behavior:** 
An empty list was shown

**Reproduces how often:** 
Just click on the branches dropdown under your project.

### Logs
Nothing in the logs since after the update.

**Comment by tierninho** [comment] 2017-08-23 15:33
Hello! this is a duplicate of #2522. The issue got fixed in #2531, and it’ll be out in the next update.

**Closed by tierninho** 2017-08-23 15:33 UTC

**Comment by shiftkey** [comment] 2017-08-23 22:38
FYI: the `0.8.1-beta2` update is now available and contains this fix.
