### ISSUE TITLE
Exit code 1 received when trying to commit file without changes

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#7738] opened 2019-06-09 09:58 UTC
## Description
I had some stashed changes which I restored into my branch, and then some merge conflicts appeared. After resolving the merge conflicts, I actually ended up with a file that was unchanged.

However, Github Desktop didn't recognise the file as such, and it still kept showing up in the list of changed files (but with no diff visible in the right hand side panel).

When I tried to commit, it failed with exit code 1.

I had to edit the file, save it, and undo my change again for Github Desktop to recognise that the file was in fact unchanged, and to have it removed from the list of changed files.

## Version
* GitHub Desktop: 2.0.4-beta0
* Operating system: OS X Mojahve

## Steps to Reproduce
1. Make changes to a particular file
2. Switch to another branch
3. Stash changes when asked and keep them in the branch
4. Switch back to the original branch
5. Make some changes to the same file that will create a merge conflict
6. Commit these changes
7. Restore the stashed changes
8. Resolve the conflicts so that the file becomes unchanged (e.g. same as last committed version)

## Expected Behavior
For the file not to be present in the list of changed files in Github Desktop, and for the commit button to be disabled.

## Actual Behavior
File remains present in the list of changed files in Github Desktop and the commit button is enabled. Pressing it causes an exit code 1 error.

## Logs
```
2019-06-09T09:45:12.528Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stdout:
On branch enhancements-may-2019
Your branch is ahead of 'origin/enhancements-may-2019' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

(The error was parsed as 17: There are no changes to commit.)
```

**Comment by shiftkey** [comment] 2019-06-10 12:55
@outofambit @iAmWillShepherd thoughts on what this might be related to?

**Comment by iAmWillShepherd** [comment] 2019-06-10 13:56
I've been able to reproduce this in Desktop as well as the CLI.

Steps to reproduce in the CLI:

Make change to file
```sh
~/repos/desktop/desktop-test-repos/stash(master) » echo "A" >> modified                                       iamwill@artemis
```

Switch branches in Desktop and select _Leave my changes on `master`_

Switch back to `master`
```sh
~/repos/desktop/desktop-test-repos/stash(b1) » git checkout master                                            iamwill@artemis
Switched to branch 'master'
```

Commit a change on `master`
```sh
~/repos/desktop/desktop-test-repos/stash(master) » echo "B" >> modified                                       iamwill@artemis
~/repos/desktop/desktop-test-repos/stash(master*) » git commit -am "move ahead"                               iamwill@artemis
[master f6eafa2] move ahead
 1 file changed, 1 insertion(+)
```

Pop stash
```sh
~/repos/desktop/desktop-test-repos/stash(master) » git stash pop                                              iamwill@artemis
Auto-merging modified
CONFLICT (content): Merge conflict in modified
```

☝️  results in the following conflict
```sh
~/repos/desktop/desktop-test-repos/stash(master*) » cat modified                                              iamwill@artemis
B
<<<<<<< Updated upstream
B
=======
A
>>>>>>> Stashed changes
```

Take upstream changes so the file has the following contents
```
B
B

```

At this point, I checked the status to see if Git thinks there is a change
```sh
~/repos/desktop/desktop-test-repos/stash(master*) » git status                                                iamwill@artemis
On branch master
Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

	both modified:   modified

no changes added to commit (use "git add" and/or "git commit -a")
```

Check the diff
```sh
~/repos/desktop/desktop-test-repos/stash(master*) » git diff modified                                         iamwill@artemis
diff --cc modified
index cbf9134,dae835f..0000000
--- a/modified
+++ b/modified
```

Try to commit the empty change
```sh
~/repos/desktop/desktop-test-repos/stash(master*) » git commit -am "test"                                     iamwill@artemis
On branch master
nothing to commit, working tree clean
```

The same behavior is present in the CLI. This is the same error being thrown in Desktop due to the error code being non-zero.

```sh
~/repos/desktop/desktop-test-repos/stash(master*) » echo $?                                                   iamwill@artemis
1
```

In summary, I think this is happening because Desktop relies on the parsed output of `git status` to present change details in the changes list. Desktop then tries to produce a diff of the changes, but the diff is empty. When you attempt to commit, Desktop presents a _Commit failed_ error.

![Screen Shot 2019-06-10 at 8 50 06 AM](https://user-images.githubusercontent.com/1715082/59199958-cfbc7f80-8b5c-11e9-82dd-26cb4dd8fe29.png)

After this error is produced, Desktop then gets new output from `git status` 
```sh
~/repos/desktop/desktop-test-repos/stash(master) » git status                                                 iamwill@artemis
On branch master
nothing to commit, working tree clean
```

Since there are no changes, Desktop doesn't show the file in the _Changes_ list. I think the underlying issue is that we don't proactively remove files from the changes list it they have an empty diff. I think this is fine since we only produce a diff when needed. Checking the diff of every file before inserting it into the changes list doesn't seem like a great idea to me, so I'm not sure what a fix would look like.

**Comment by iAmWillShepherd** [comment] 2019-06-10 15:14
@adamreisnz 

The root cause of this issue is that the file needs to be re-added to the index for Git - and by extension Desktop - to recognize that no changes are present in the file.

Running `git add [path]` will unblock you for now.

We are planning to ship conflict resolution for stashed changes, so this shouldn't be a problem in the future. Since this is something we're already planning to tackle I'm going to close this issue. feel free to follow #7748.

**Closed by iAmWillShepherd** 2019-06-10 15:14 UTC
Labels: investigation-needed

**Comment by adamreisnz** [comment] 2019-06-11 00:39
Ok, thanks for looking into it
