### ISSUE TITLE
Renaming git folder or categorizing folder

### ISSUE THREAD

**Issue by jericizon** [desktop/desktop#9290] opened 2020-03-16 02:53 UTC
### Describe the feature or problem you’d like to solve

Be able to distinguish the git folders. I have two different git folder named as main

![git-request](https://user-images.githubusercontent.com/8746166/76719224-18503b80-6774-11ea-8dfd-a36b4f775232.jpg)

### Proposed solution
- Be able to categorize or rename git folders in UI.

**Comment by steveward** [comment] 2020-03-16 17:33
@vasanthmurari thanks for the feedback. If you hover over the repo names, you will be able to see the path of the repositories.

This looks like a duplicate of https://github.com/desktop/desktop/issues/8175 and #8158, which were included in https://github.com/desktop/desktop/issues/6460. See https://github.com/desktop/desktop/issues/8158#issuecomment-524644986 specifically for the current thinking on this.

**Closed by steveward** 2020-03-16 17:33 UTC
