### ISSUE TITLE
Pull Request Closed does not update in Desktop Version

### ISSUE THREAD

**Issue by SASFMONTOYA** [desktop/desktop#4241] opened 2018-03-14 16:58 UTC
## Description
**### (Español)**
Los Pull request que hacen los usuarios no se actualizan cuando se cierran desde la versión web.
Por ejemplo, se abrió un Pull request como una prueba, efectivamente se muestra en la versión desktop (img 1).
Pero se cerró desde la versión web (img 2) y continúa mostrándose en la versión desktop.

**### (English)**
The Pull requests that made by users are not updated when they are closed from the web version. For example, a Pull request was opened as a test, it is effectively displayed in the desktop version (img 1).
But it was closed from the web version (img 2) and continues showing in the desktop version.

• [img 1](https://i.imgur.com/wYHUDq9.png)
• [img 2](https://i.imgur.com/1vyaG2h.png)

## Version

* GitHub Desktop: 1.1.0

* Operating system: Windows 8.1 Pro

### Logs

[2018-03-14.desktop.production.log](https://github.com/desktop/desktop/files/1812137/2018-03-14.desktop.production.log)

**Comment by tierninho** [comment] 2018-03-14 17:00
@SASFMONTOYA This is a duplicate of https://github.com/desktop/desktop/issues/4122 Please follow along there.

**Closed by tierninho** 2018-03-14 17:00 UTC

**Comment by SASFMONTOYA** [comment] 2018-03-14 17:04
Ok, thanks :D
