### ISSUE TITLE
Repository not opening in BBEdit

### ISSUE THREAD

**Issue by dwins18** [desktop/desktop#9553] opened 2020-04-17 19:26 UTC
### Describe the bug
GitHub Desktop says "Open the repository in your external editor". When I click "Open in BBEdit", it opens BBEdit, but it just opens a new document.

### Version & OS

Version 2.4.1; macOS Catalina Version 10.15.4

### Steps to reproduce the behavior

1. Open a repository in GitHub Web.
2. Click "Clone or download".
3. Click "Open in Desktop"
4. Click "Open in BBEdit"

### Expected behavior

I expected the repository data to open in BBEdit so I can edit it.

### Actual behavior

A new document opened in BBEdit.

### Screenshots

![Screen Shot 2020-04-17 at 3 22 49 PM](https://user-images.githubusercontent.com/63875193/79606317-6b911300-80bf-11ea-8142-aeb00e3fe5fb.png)
![Screen Shot 2020-04-17 at 3 23 01 PM](https://user-images.githubusercontent.com/63875193/79606336-7186f400-80bf-11ea-9f6e-d7869acfda57.png)

### Logs

[2020-04-17.desktop.production.log](https://github.com/desktop/desktop/files/4494835/2020-04-17.desktop.production.log)

### Additional context

**Comment by steveward** [comment] 2020-04-17 21:36
Thanks for the report @dwins18 -- I'm going to close this as a duplicate of #9050. You can follow along there for updates.

**Closed by steveward** 2020-04-17 21:36 UTC

**Comment by dwins18** [comment] 2020-04-18 18:46
> Thanks for the report @dwins18 -- I'm going to close this as a duplicate of #9050. You can follow along there for updates.

Where do I enter the code entitlement?
