### ISSUE TITLE
Pull requests list still uses old remote after changing repository settings

### ISSUE THREAD

**Issue by AlanSl** [desktop/desktop#5856] opened 2018-10-09 10:35 UTC
## Description

After changing the remote in _Repository > Repository Settings_, the _Pull Requests_ list under _Current Branch_ should show pull requests on the new remote. Instead, it continues showing the pull requests for the old remote for some unknown period of time, before changing.

It should update the list immediately (or at least, consistently after the next Fetch).

## Version

* GitHub Desktop: 1.4.2

* Operating system: MacOS 10.12.6

## Steps to Reproduce

1. Find and clone a repository that has been forked. For example, https://github.com/davidmarkclements/d3-fg.git
2. Fetch, review the list of available branches and pull requests
3. Use Repository > Repository settings to change the remote to a fork. For example, https://github.com/AlanSl/d3-fg.git
4. Check the Pull Requests list. It will display the old list, and refer to the old list in text (e.g. "You're all set! No open pull requests in `previous-remote-name.someProject.git`")
5. Fetch, restart GitHub desktop, etc - it still displays the old list.
6. Come back to it after maybe an hour (possibly, some remote activity is required for it to refresh), and it seems to finally start showing the new list (or alternatively, delete and re-clone). Change the remote again, back to the original, and again the Pull Request list stays stuck on the old list.

### Expected Behavior

The Pull Requests list under Current Branch should show pull requests on whatever the current remote is.

### Actual Behavior

The Pull Requests list under Current Branch shows pulls requests from the previous remote, and doesn't update the list to show pull requests on the new remote for some long time.

## Additional Information

![image](https://user-images.githubusercontent.com/29628323/46663620-7a3b6780-cbb6-11e8-80cd-1f47dcb75eec.png)

![image](https://user-images.githubusercontent.com/29628323/46663606-714a9600-cbb6-11e8-8b64-a85a33104d8f.png)

There is a current pull request on `https://github.com/davidmarkclements/d3-fg.git` which I want to pull. I can't see it, because GitHub Desktop is still showing pull requests for `https://github.com/goto-bus-stop/d3-fg.git`, which is the previous remote I set this local repo to use yesterday. 

I have fetched, through both the UI and `git fetch`, after changing the remote to `https://github.com/davidmarkclements/d3-fg.git`, but it is still looking for PRs in yesterday's remote.

### Logs

```
2018-10-09T10:22:19.326Z - info: [ui] Background fetch for 28 repositories took 20.151sec
2018-10-09T10:22:22.445Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:22:24.503Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:22:26.017Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:22:30.672Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:22:32.329Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:27:45.814Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:30:06.379Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: d3-fg - AlanSl (has token)
2018-10-09T10:30:08.045Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.653s)
2018-10-09T10:30:09.235Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune upstream (took 1.186s)
```

**Comment by steveward** [comment] 2018-10-11 00:09
Thanks for opening this @AlanSl! I was able to reproduce this behavior using the steps you mentioned.

Is it a common scenario for you where you need to change the `origin` remote URL of a repository? I have definitely seen cases where users have mistakenly cloned the upstream repository instead of their fork, and as a result have had to change the remote URL. Just trying to gather data about how common of a scenario this may be.

Since this is self-resolving after a period of time I am going to mark it as a `priority-3` bug.

**Comment by AlanSl** [comment] 2018-10-11 09:07
The workflow where I encountered this is based on a few people working on different branches of a project we are contributors without admin rights to. So we each have our own fork, and we post PRs to the upstream. What I want to do is be able to switch between the different forks with minimal friction.

For example, I'm working on a branch, so I set the remote to my fork. A colleague posts a PR, so I switch to the upstream repo to review it. A colleague mentions that their work overlaps my work, so I switch the remote to their repo so I can look at and if appropriate cherry pick before they have posted a PR. And so on.

In theory I could clone every fork separately, but I prefer this way to avoid have multiple versions of the same file with the possibility of saving an edit in the wrong fork. It works well - but for the fact it takes a random amount of time for the PRs list to update.

**Comment by embick** [comment] 2018-10-11 15:58
(Hope this isn't too off-topic)

Has an issue been posted yet for an enhancement to change the "Repository Settings > Remote" tab to a *list* of remotes, from which the user could set/change the current primary? Instead of tediously manually changing the remote every time.

Because that's also what the workflow looks like for syncing a fork with upstream right now: have to switch the remote to upstream to fetch updates, then switch back to the fork. And that workflow seems very common.

**Comment by steveward** [comment] 2018-10-11 17:41
@embick GitHub Desktop does support upstream remotes, but not multiple custom remotes (see https://github.com/desktop/desktop/issues/1442). If you clone a fork we will add the upstream remote and then fetch from it periodically. You should see a list of upstream branches in the branch list using the convention `<upstream>/<branch_name>`, which will allow you to merge changes from upstream into your fork. Let me know if you aren't seeing that.

**Comment by msftrncs** [comment] 2018-11-27 00:03
I think it would be useful if Desktop would provide a UI to see and set the 'upstream' setting.  I don't know what I have done wrong, but I have had to set the upstream URL myself using GIT in a shell, as it never seems to be set for me.   I have done the aforementioned practice though a few times, of cloning the upstream directly and then needing to fix the links later to make my own fork.  I'll have to keep a better eye out for when I next fork a repository.

**Comment by msftrncs** [comment] 2018-11-27 04:16
@AlanSl, would the pull requests be updated, if you were to switch to a different repository, and then back to the desired repository, AFTER you have changed the remote URL setting?

**Comment by calculuschild** [comment] 2019-02-05 19:03
Any progress on this one or a workaround? I just ran into this issue and would like to access my pull requests... We moved to a new repository after the original owner abandoned the project but GitHub Desktop still looks for PRs in the old repo.

**Comment by shiftkey** [comment] 2019-07-30 16:37
I'm going to close this out as we've revamped our Pull Request list for the 2.0 release to cache better and be more responsive to changes.

Please read along with these PRs for more information: #7501 #7163 #7027

**Closed by shiftkey** 2019-07-30 16:37 UTC
Labels: bug, help wanted, priority-3
