### ISSUE TITLE
Garbled cyrillics / encoding mess in 0.6.0 GH Desktop

### ISSUE THREAD

**Issue by AdOps** [desktop/desktop#1981] opened 2017-06-12 12:43 UTC
### Version

**GitHub Desktop version:** [0.6.0]

**OS version:** [10.9.5]

### Steps to Reproduce

1. Just open any repo with cyrillic markdown or JS (UTF-8)

<img width="514" alt="screen shot 2017-06-12 at 14 38 03" src="https://user-images.githubusercontent.com/24861420/27034309-62dfc92a-4f7d-11e7-8bcb-36c385a3615d.png">

**Comment by shiftkey** [comment] 2017-06-12 13:07
This is a duplicate of #1958 which has been fixed in #1970 and will be available in the next update.

**Closed by shiftkey** 2017-06-12 13:07 UTC
