### ISSUE TITLE
Unable to Login to GitHub Desktop

### ISSUE THREAD

**Issue by XY40493** [desktop/desktop#12199] opened 2021-05-12 16:00 UTC
Describe the bug
Unable to clone repository using GitHub Desktop as it if giving below error

3 resources from my team facing the same issue

Need help\suggestions urgently please.

Version & OS
Version 2.6.6 in Windows 10

Expected behavior
it should allow to login

Actual behavior
But Redirecting to Welcome to GitHub Desktop page

![image](https://user-images.githubusercontent.com/49957176/118006849-e91f6500-b34b-11eb-9de9-5263ec734284.png)

[2021-05-12.desktop.production.log](https://github.com/desktop/desktop/files/6467432/2021-05-12.desktop.production.log)
https://user-images.githubusercontent.com/49957176/118006104-45ce5000-b34b-11eb-9578-a97c149e7db3.mp4

**Comment by sergiou87** [comment] 2021-05-13 10:03
Hello @XY40493! 👋 

Thank yo for your report, I'm sorry you're having trouble to sign in.

That video you posted is super useful ❤️  I wonder if you could help me out debugging the issue, since I can't reproduce it on my end. Don't feel like you have the obligation to help, but we would be immensely grateful if you did!

You would only need to follow these steps (I included a video following the steps myself, see it at the end of this post):

1. While you're in that welcome/sign in screen, press <kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> in order to show the Developer Tools.
2. From the Developer Tools, press <kbd>Control</kbd>+<kbd>P</kbd> or click the `···` -> `Open file…` menu to open the file `api.ts`
3. Within the file `api.ts`, look for the function `requestOAuthToken`. You can press <kbd>Control</kbd>+<kbd>F</kbd> to find it faster.
4. Click on the line numbers for the first line right after the `try {` and first line right after the `} catch(e) {`. That will add breakpoints to those lines, so the app pauses right after you attempt to sign in.
5. ⚠️  ⚠️  **IMPORTANT:** if you're gonna share any screenshots or videos about the process, make sure you collapse the `Scope` section on the right panel, otherwise you would leak your GitHub token!!! You can see how I do this in the video at `0:40`.
6. Try to Sign in to GitHub.com
7. Once click on `Open` in your browser and you get back to GitHub Desktop, the app should be paused in the first line where you added the breakpoint.
8. You only have to click on the "Step over next function call" button (or press <kbd>F10</kbd>) a few times to see what the app does.
![image](https://user-images.githubusercontent.com/1083228/118110020-30f0cb80-b3e2-11eb-8179-f0de691a32d9.png)
9. At some point, the app will jump to the line inside the `catch` of that function. I would love to know from where did that happen: was it from the `await request(…` line? From the `await parsedResponse…` line? Or from somewhere else?


https://user-images.githubusercontent.com/1083228/118108837-c55a2e80-b3e0-11eb-8e8b-86cf5bbfe2ec.mov

**Comment by XY40493** [comment] 2021-05-13 10:41
> Hello @XY40493! 👋
> 
> Thank yo for your report, I'm sorry you're having trouble to sign in.
> 
> That video you posted is super useful ❤️ I wonder if you could help me out debugging the issue, since I can't reproduce it on my end. Don't feel like you have the obligation to help, but we would be immensely grateful if you did!
> 
> You would only need to follow these steps (I included a video following the steps myself, see it at the end of this post):
> 
> 1. While you're in that welcome/sign in screen, press Control+Shift+I in order to show the Developer Tools.
> 2. From the Developer Tools, press Control+P or click the `···` -> `Open file…` menu to open the file `api.ts`
> 3. Within the file `api.ts`, look for the function `requestOAuthToken`. You can press Control+F to find it faster.
> 4. Click on the line numbers for the first line right after the `try {` and first line right after the `} catch(e) {`. That will add breakpoints to those lines, so the app pauses right after you attempt to sign in.
> 5. ⚠️  ⚠️  **IMPORTANT:** if you're gonna share any screenshots or videos about the process, make sure you collapse the `Scope` section on the right panel, otherwise you would leak your GitHub token!!! You can see how I do this in the video at `0:40`.
> 6. Try to Sign in to GitHub.com
> 7. Once click on `Open` in your browser and you get back to GitHub Desktop, the app should be paused in the first line where you added the breakpoint.
> 8. You only have to click on the "Step over next function call" button (or press F10) a few times to see what the app does.
>    ![image](https://user-images.githubusercontent.com/1083228/118110020-30f0cb80-b3e2-11eb-8179-f0de691a32d9.png)
> 9. At some point, the app will jump to the line inside the `catch` of that function. I would love to know from where did that happen: was it from the `await request(…` line? From the `await parsedResponse…` line? Or from somewhere else?
> 
>  Screen.Recording.2021-05-13.at.11.44.14.mov

Hi 
Good Day 

Hope my below attachment will help you to find the issue 

https://user-images.githubusercontent.com/49957176/118114903-8039fa80-b3e8-11eb-92ca-810ec47b9d4c.mp4

**Comment by sergiou87** [comment] 2021-05-13 10:54
Thank you @XY40493 that's indeed very useful!! ❤️ 

It seems the request we make to get the token needed to use GitHub Desktop normally is failing for some reason.

Once the app gets inside the `catch…` zone, could you switch to the `Network` tab in the Developer Tools and look for a request to `/login/oauth/access_token`?

It should be something like this:

![image](https://user-images.githubusercontent.com/1083228/118116203-47028a00-b3ea-11eb-8087-71edfd903d4d.png)

I wonder if you see any kind of error in that screen. Again, if you share any screenshot or video, please be careful not to share any tokens with it!

**Comment by XY40493** [comment] 2021-05-13 13:07
> Thank you @XY40493 that's indeed very useful!! ❤️
> 
> It seems the request we make to get the token needed to use GitHub Desktop normally is failing for some reason.
> 
> Once the app gets inside the `catch…` zone, could you switch to the `Network` tab in the Developer Tools and look for a request to `/login/oauth/access_token`?
> 
> It should be something like this:
> 
> ![image](https://user-images.githubusercontent.com/1083228/118116203-47028a00-b3ea-11eb-8087-71edfd903d4d.png)
> 
> I wonder if you see any kind of error in that screen. Again, if you share any screenshot or video, please be careful not to share any tokens with it!

Please find the attached errors


https://user-images.githubusercontent.com/49957176/118129592-a9fd1c80-b3fc-11eb-9aea-0916db3ebc31.mp4

![image](https://user-images.githubusercontent.com/49957176/118129674-c6995480-b3fc-11eb-8ae5-592ef3303db6.png)

**Comment by sergiou87** [comment] 2021-05-13 13:39
Thank you @XY40493 for those extra screenshot and video 😄  

I just deleted the whole comment because the video and screenshot exposed more info than they should 😅  In any case, it also has the data I need to understand this issue better. I'll investigate and let you know what I find! 🕵️

**Comment by XY40493** [comment] 2021-05-13 13:46
> Thank you @XY40493 for those extra screenshot and video 😄
> 
> I just deleted the whole comment because the video and screenshot exposed more info than they should 😅  In any case, it also has the data I need to understand this issue better. I'll investigate and let you know what I find! 🕵️

I hope you will find the solution soon

**Comment by sergiou87** [comment] 2021-05-14 09:00
Sorry I still couldn't find anything. I saw this in your video:

![image](https://user-images.githubusercontent.com/1083228/118247168-2813fe80-b4a3-11eb-9c7b-eef3332b4343.png)

Could you make that column wider to see what's in there? I think that'll give us a clue of why the request happened.

Also, I think that if you switch to the `Console` at that point, it should show something more:

![image](https://user-images.githubusercontent.com/1083228/118247276-4974ea80-b4a3-11eb-9a89-2cd80bbdd874.png)

In any case, I suspect there is something wrong with that remote environment that is preventing the app from sending that request, I just don't know what exactly 😕 

Thank you again for all your help, it's being super valuable!!

**Comment by XY40493** [comment] 2021-05-14 09:23
> Sorry I still couldn't find anything. I saw this in your video:
> 
> ![image](https://user-images.githubusercontent.com/1083228/118247168-2813fe80-b4a3-11eb-9c7b-eef3332b4343.png)
> 
> Could you make that column wider to see what's in there? I think that'll give us a clue of why the request happened.
> 
> Also, I think that if you switch to the `Console` at that point, it should show something more:
> 
> ![image](https://user-images.githubusercontent.com/1083228/118247276-4974ea80-b4a3-11eb-9a89-2cd80bbdd874.png)
> 
> In any case, I suspect there is something wrong with that remote environment that is preventing the app from sending that request, I just don't know what exactly 😕
> 
> Thank you again for all your help, it's being super valuable!!

![image](https://user-images.githubusercontent.com/49957176/118250434-c48bd000-b4a6-11eb-9420-bf9e9120e76b.png)
![image](https://user-images.githubusercontent.com/49957176/118250517-dcfbea80-b4a6-11eb-82a7-aea6a5862730.png)

**Comment by sergiou87** [comment] 2021-05-14 09:44
Thank you @XY40493 , looks like there is something in that remote machine preventing the app from sending the request. It could be a firewall or an antivirus blocking certain outgoing requests, or maybe which has just blocked them for GitHub Desktop.

Could you try to just uninstall GitHub Desktop and reinstalling it again from https://desktop.github.com ?

**Comment by XY40493** [comment] 2021-05-14 09:49
> Thank you @XY40493 , looks like there is something in that remote machine preventing the app from sending the request. It could be a firewall or an antivirus blocking certain outgoing requests, or maybe which has just blocked them for GitHub Desktop.
> 
> Could you try to just uninstall GitHub Desktop and reinstalling it again from https://desktop.github.com ?

I have uninstalled and Installed it may be nearly 4 times

**Comment by XY40493** [comment] 2021-05-14 09:57
> > Thank you @XY40493 , looks like there is something in that remote machine preventing the app from sending the request. It could be a firewall or an antivirus blocking certain outgoing requests, or maybe which has just blocked them for GitHub Desktop.
> > Could you try to just uninstall GitHub Desktop and reinstalling it again from https://desktop.github.com ?
> 
> I have uninstalled and Installed it may be nearly 4 times

This was the initial issue after uninstalling GitHub Desktop and deleting folders from Appdata and reinstalling GitHub Desktop i am facing above issue
![image](https://user-images.githubusercontent.com/49957176/118254434-62819980-b4ab-11eb-9ac1-6ada66905bfd.png)

**Comment by sergiou87** [comment] 2021-05-14 10:13
That seems to be exactly the same issue, but for some reason in your videos it wasn't surfaced to the app with that red banner as it does now.

Does that machine have any antivirus or firewall that you can disable? If you don't have permission to manage that machine, I'm afraid you might need to contact your system admin to further diagnose the issue 😞

**Comment by XY40493** [comment] 2021-05-14 10:17
> That seems to be exactly the same issue, but for some reason in your videos it wasn't surfaced to the app with that red banner as it does now.
> 
> Does that machine have any antivirus or firewall that you can disable? If you don't have permission to manage that machine, I'm afraid you might need to contact your system admin to further diagnose the issue 😞

If My lead logs into this virtual machine with his credentials then GitHub desktop is working 100%.
To one my colleague he can use github desktop on one machine without any issues and on another 2 machines he is facing same issues.

**Comment by sergiou87** [comment] 2021-05-14 10:53
I'm extremely surprised about that 😐 

Have you tried your user in a completely different machine?

The `ERR_CONNECTION_RESET` error should be a low-level error completely independent of the user, and dependent on the network setup or the server directly rejecting the connection through which the request is sent.

Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine?

**Comment by XY40493** [comment] 2021-05-14 12:14
> I'm extremely surprised about that 😐
> 
> Have you tried your user in a completely different machine?
> 
> The `ERR_CONNECTION_RESET` error should be a low-level error completely independent of the user, and dependent on the network setup or the server directly rejecting the connection through which the request is sent.
> 
> Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine?

 Have you tried your user in a completely different machine? (Yes and it worked)
 
 Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine? (Okay Will DO that and will let you know ASAP)

**Comment by XY40493** [comment] 2021-05-14 14:22
> > I'm extremely surprised about that 😐
> > Have you tried your user in a completely different machine?
> > The `ERR_CONNECTION_RESET` error should be a low-level error completely independent of the user, and dependent on the network setup or the server directly rejecting the connection through which the request is sent.
> > Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine?
> 
> Have you tried your user in a completely different machine? (Yes and it worked)
> 
> Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine? (Okay Will DO that and will let you know ASAP)

Could you try creating a new GitHub account and trying to sign in with that from the very same virtual machine? (I tried this was stuck with same issue even it asked me to authorize the desktop after authorizing same error "unable to fetch authenticated user."

**Comment by sergiou87** [comment] 2021-05-14 14:36
Thanks for trying all that out ❤️ 

All that info points in the same direction: it's a problem of the configuration of that virtual/remote machine. The only data point that contradicts this theory is:
> If My lead logs into this virtual machine with his credentials then GitHub desktop is working 100%

I don't understand how different credentials could lead to different behaviors in this very specific error 😞 

Can you try to disable any antivirus or firewall temporarily and see if it makes a difference? 🤞

**Comment by XY40493** [comment] 2021-05-14 16:04
> disable any antivirus or firewall temporarily

I tried by Making antivirus disable but still no luck at all
Is there any other option to clone to repository to local machine
Github desktop is not working

i am getting following error with git bash "OpenSSL SSL_connect: Connection was reset in connection to github.com:443"

**Comment by sergiou87** [comment] 2021-05-14 16:23
That seems similar to the other one 🤔  Does that machine connect to the internet via a proxy?

**Comment by XY40493** [comment] 2021-05-14 16:25
> That seems similar to the other one 🤔 Does that machine connect to the internet via a proxy?

No its not

**Comment by sergiou87** [comment] 2021-05-17 10:44
For now I've run out of ideas on this issue, sorry 😞  I don't see anything that points to the app: the error is in a request sent to fetch info about the user logged in.

I'm gonna close this one in favor of #11410, which covers a bunch of login-related issues. Sorry I can't be of more help!

**Closed as completed by sergiou87** 2021-05-17 10:44 UTC

**Comment by amarhany20** [comment] 2024-01-13 10:07
i know it is 2 years later, but I fixed it by disabling Run As Administrator in Github Desktop Compatitbility Settings, which I enabled before. That's just for me. Not sure if it is going to work for you, I just wanted to share that this worked for me. Good luck on fixing your problemos.
