### ISSUE TITLE
Error: write EOF

### ISSUE THREAD

**Issue by daanbreur** [desktop/desktop#5132] opened 2018-07-09 17:11 UTC
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

Version: 1.0.8
OS: Windows 10.0.17134

**Comment by shiftkey** [comment] 2018-07-09 17:15
@daanbreur thanks for the report.

We believe this has been fixed in `1.1.0` as part of https://github.com/desktop/desktop/pull/4058 - can you ensure you're running the latest version of Desktop?

**Comment by shiftkey** [comment] 2018-07-10 12:51
@daanbreur I'm going to close this out because I believe it's a known issue that's been resolved, but please reply if you are still seeing issues and provide more details about the steps to reproduce the issue.

**Closed by shiftkey** 2018-07-10 12:51 UTC
