### ISSUE TITLE
unable to update refs/remotes/origin/HEAD

### ISSUE THREAD

**Issue by nareshm12608** [desktop/desktop#19072] opened 2024-08-06 11:01 UTC
### The problem

Facing an issue to do cloning from github desktop

Cloning into 'W:\6.Script\qlik-cps-common-execution-metrics'... remote: Enumerating objects: 10, done.         remote: Counting objects: 100% (10/10), done.         remote: Compressing objects: 100% (6/6), done.         remote: Total 10 (delta 0), reused 4 (delta 0), pack-reused 0         Receiving objects: 100% (10/10), done. error: Unable to create '//se5xxasqdfdev.tcad.telia.se/Qlik QDF DEV/10.Sandbox/920.doh460/6.Script/qlik-cps-common-execution-metrics/.git/refs/remotes/origin/HEAD.lock': No such file or directory fatal: unable to update refs/remotes/origin/HEAD

### Release version

9

### Operating system

2019

**Comment by nareshm12608** [comment] 2024-08-06 11:11
Release Version :3.3.18

**Comment by steveward** [comment] 2024-08-06 15:32
Thanks for the report @nareshm12608. Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by nareshm12608** [comment] 2024-08-07 07:50
please find the attached log
[2024-08-06.desktop.production.log](https://github.com/user-attachments/files/16520077/2024-08-06.desktop.production.log)

**Comment by steveward** [comment] 2024-08-07 16:02
It looks like there is a nested repository in that repository. Are you able to navigate to that file path wherever the repository is hosted to see if it exists? Are you aware if this was previously added by mistake? It's likely that it will continue to cause issues.

Since this isn't an issue with GitHub Desktop I'm going to close this out, but if you have any further questions I can follow up.

**Closed as completed by steveward** 2024-08-07 16:02 UTC

**Comment by nareshm12608** [comment] 2024-08-09 06:06
It looks like there is a nested repository in that repository. 
Are you able to navigate to that file path wherever the repository is hosted to see if it exists? Yes , we are able to
 Are you aware if this was previously added by mistake? It's likely that it will continue to cause issues. .. we deleted all the files and again we clone the repository but still the issue is happening.

We have created New repository and tried to clone in to the path but still same issue with Sandbox folder.

but when we tried with clone repository for another then it was working fine. please let us know the reason.

Please find the log files
[2024-08-09.desktop.production.log](https://github.com/user-attachments/files/16556690/2024-08-09.desktop.production.log)


Regards
Naresh M

**Comment by steveward** [comment] 2024-08-12 18:31
I think the issue is with the repository that you are cloning from -- you will need to try and resolve the issue there by removing the erroneous files. If you are using a different repository hosting service I would recommend reaching out to them for support.

This path is causing issues:

```
error: Unable to create '//se5863asqdfdev.tcad.telia.se/Qlik QDF DEV/10.Sandbox/920.doh460/6.Script/testing-sandbox/.git/refs/remotes/origin/HEAD.lock': No such file or directory
fatal: unable to update refs/remotes/origin/HEAD
```
