### ISSUE TITLE
Recreate the Graph Flow feature from 4 years ago.

### ISSUE THREAD

**Issue by JenuelDev** [desktop/desktop#11720] opened 2021-03-06 01:51 UTC
I saw this GitHub desktop 4 years ago, what great about this is it's easy to visualize the flow of what is committed and not committed. I hope this will be added to Github Desktop.

![image](https://user-images.githubusercontent.com/31676163/110191012-61a40a00-7e61-11eb-988d-ffece3c27543.png)

or something like this,
![image](https://user-images.githubusercontent.com/31676163/110192053-d463b400-7e66-11eb-8cb2-2b260df5a964.png)

**Comment by steveward** [comment] 2021-03-08 20:12
Thanks for the request @sergiou87. I'm going to close this as a duplicate of https://github.com/desktop/desktop/issues/9452. You can follow along there for updates about this feature.

**Closed as completed by steveward** 2021-03-08 20:12 UTC
Labels: enhancement
