### ISSUE TITLE
Disabling background updates not working on macOS

### ISSUE THREAD

**Issue by v57** [desktop/desktop#15177] opened 2022-08-26 15:15 UTC
### The problem

When i disable background updates, it still sometimes fetches repositories. Basically logs says that it does calls `git -c credential.helper= fetch --progress --prune origin`

### Release version

3.0.6

### Operating system

macOS 12.5

### Steps to reproduce the behavior

1. Disable automatic updates
2. Wait...
3. Fetching origin status will appear

### Log files

[2022-08-26.desktop.production.log](https://github.com/desktop/desktop/files/9434334/2022-08-26.desktop.production.log)

### Screenshots

<img width="709" alt="Screenshot 2022-08-26 at 18 04 50" src="https://user-images.githubusercontent.com/2669441/186937306-e62918a5-e9cb-4eee-a59f-586ce9cf20a9.png">

**Comment by niik** [comment] 2022-08-26 15:22
Hey @v57, thanks for reaching out! I'm pretty sure this is caused by the bug described in https://github.com/desktop/desktop/pull/15104#discussion_r947863356 which will be fixed once #15104 lands.

Could you try restarting the application after disabling background updates? If this is caused by the bug I just pointed to then a restart should fix it. Note however that the currently selected repository will still be updated periodically in the background.

Separate to that bug there's also https://github.com/desktop/desktop/issues/15162 and https://github.com/desktop/desktop/issues/15163 which is likely why you're seeing this bug now. If you would like to help please see https://github.com/desktop/desktop/issues/15163#issuecomment-1228571515 where @sergiou87 has provided a test build which we're looking for help testing out from people who're experiencing this issue. If you'd be willing to install the test version and report back that would be very helpful. Note that once you've installed the test build you'll have to manually install the latest production build again.

**Comment by steveward** [comment] 2022-12-15 20:53
This should be fixed, but let us know if you're still hitting this issue @v57 and we can reopen to investigate further.

**Closed as completed by steveward** 2022-12-15 20:53 UTC
Labels: bug
