### ISSUE TITLE
P

### ISSUE THREAD

**Issue by renatochaves1999** [desktop/desktop#15502] opened 2022-10-21 23:13 UTC
### The problem

I published a project in php and in the language it appears hack

### Release version

Version 3.1.2

### Operating system

Windows 10 64 bits

### Screenshots

![hack language](https://user-images.githubusercontent.com/45311074/197303686-0d7cfe9d-fa90-416f-8487-9a27c3691ffc.png)

**Comment by tsvetilian-ty** [comment] 2022-10-22 13:50
Hey @renatochaves1999 👋 the issue is not related to GitHub Desktop, so I will close it. 

The file's content may be the reason your `PHP` file is recognized as `Hack`. If your file contains only HTML, GitHub will default to `Hack` as a language! Both `PHP` and `Hack` use the `.php` extension, so GitHub will use the file's content to determine if it's `PHP` or `Hack`.

**Closed as completed by tsvetilian-ty** 2022-10-22 13:50 UTC
