### ISSUE TITLE
Kedit, The Hessling Editor, and Far Manager integration

### ISSUE THREAD

**Issue by frank-e** [desktop/desktop#9385] opened 2020-03-27 23:23 UTC
### Describe the feature or problem you’d like to solve

For **several** hours I tried to figure out the "unknown" external editor integration, and I'm **completely** lost. At some point I read that about 25% of your users have no supported editor, and that you were surprised that this causes no more pain. 

Today I saw that somebody tries to add `notepad++` to the list of supported editors, good luck with that, but it isn't my editor. Three "classic" more than 30 years old editors are `vim` (was visual mode of `ed`), `emacs`, and [XEDIT](https://en.wikipedia.org/wiki/XEDIT "xedit"). My editor `KeditW32.exe` is an installed commercinal XEDIT clone, a free and open source variant [THE](https://en.wikipedia.org/wiki/The_Hessling_Editor "THE") exists.

### Proposed solution

Users should be able to specify anything they have as "external editor".  It's odd to scan the registry for uninstall instructions of an installed editor, "portable" installations should also work. While trying to figure out what GitHub Desktop apparently does, one user apparently tried to "fake" an installation of a portable atom. 

I have a `x.cmd` one-liner starting `KeditW32.exe` for file(s), command line arguments as is, or with a pre-pended `DIR ` for a directory. Apparently some supported editors already have a starter script.

**However**, I don't often open directories in my editor, that was fun 25 years ago under DOS, but with long file names `explorer.exe` is better suited to show directories. So what would actually be a feature for me could be "open directory with [Far Manager](https://en.wikipedia.org/wiki/Far_Manager "FAR")" or "open file with KeditW32 / THE / &hellip;".

**Comment by billygriffin** [comment] 2020-03-30 12:53
Thanks for the issue @frank-e! I'm going to close this as mostly a duplicate of #5083 - feel free to add any additional context there. I think more generally you're correct that we haven't seen this come up a ton as a big pain point for people, and that could be for any number of reasons, but we try to ensure we understand the breadth of people experiencing any particular problem prior to prioritizing work on it. Thanks again.

**Closed by billygriffin** 2020-03-30 12:53 UTC
