### ISSUE TITLE
Scroll bar interferes with button click area

### ISSUE THREAD

**Issue by J-rg** [desktop/desktop#12886] opened 2021-09-01 14:07 UTC
### Describe the bug
In the “Resolve conflicts before rebasing [branch]” dialog, the scroll area overlaps with the buttons when using overlay scrollers, making it difficult to click the drop down buttons next to the “Open in [external editor]” buttons immediately after scrolling.

### Version & OS
Version 2.9.3 (x64), macOS 11.5.2 (20G95)

### Steps to reproduce the behavior
1. Trigger the resolve conflicts dialog.
2. Scroll down.
3. Click the arrow button.

### Expected behavior
The pull-down menu is displayed.

### Actual behavior
The view scrolls to a different position.

### Screenshots
![](https://user-images.githubusercontent.com/4042863/131684727-cf68fdfb-e9fc-4ed2-b28e-72a5139c7d66.gif)

**Comment by steveward** [comment] 2021-09-03 18:34
Thanks for the issue @J-rg! I'm going to close this as a duplicate of https://github.com/desktop/desktop/issues/6199.

**Closed as completed by steveward** 2021-09-03 18:34 UTC
