### ISSUE TITLE
Squash and merge

### ISSUE THREAD

**Issue by unrulife** [desktop/desktop#15954] opened 2023-01-17 09:52 UTC
### The problem

I have two branches, branch A and branch B(Include C files and *.lib file), and some files in branch A are different from those in branch B, and some files are removed from branch A.  When I merge branch A into branch B with squash and merge, the different parts of the branch A and branch B show conflict. When I resolve the conflict(All finally use the branch A files) and click Continue merge, and then the merge process complete.  But what I found was that the different parts were successfully merged, but the parts that were removed from branch A were not merged into branch B, so the files that were removed from branch A were still in branch B. Otherwise, the differenct libarary file(*.lib) can't be updated.

### Release version

3.1.3

### Operating system

WIN11

### Steps to reproduce the behavior

1. Switch to branch A;
2. Click "choose a branch to merge into branch A";
3. Switch to Squash and merge;
4. Select branch B;
5. Click Squash and merge;
6. Resolve conflict;
7. Click continue merge;
8. complete.
9. Check the files, find that the removed part in branch A is still in branch B.( I think removed files should merge into branch B, But it isn't like that.)

### Additional context

Github Desktop

**Comment by steveward** [comment] 2023-01-18 16:27
Thanks for the report @unrulife. I'm not sure I fully understand the issue, but I was unable to reproduce any problems when using squash and merge after resolving conflicts. Did you use the ours/theirs option when resolving conflicts? If you can share some specific screenshots of the behavior you are seeing that may better help me understand the issue.

**Closed as completed** 2023-01-25 18:09 UTC
Labels: more-info-needed
