### ISSUE TITLE
Difficult to visually determine which line is selected in Windows context menu on discard changes

### ISSUE THREAD

**Issue by toddbellMSFT** [desktop/desktop#5990] opened 2018-10-25 00:06 UTC
## Description

I am in a repo with several local commits that involved a file. That file turns out never needed to be changed. Right click that file in the GitHub Desktop explorer -> Discard changes. This removed ALL of my changes even though I didn't click Discard All Changes. 

Oh that's alright they are just in your Recycle bin.

My Recycle bin is currently too big. and after just 5 minutes after opening is STILL not fully indexed.

I made MULTIPLE undone changes to my files. I see the folder I changed, double click and I only get properties? I can only "Restore folder" from here? So if I discard multiple changes only the last discarded change to a file will be around? So would discarding different files at different times restore only the last discarded change of that file?

## Version

* GitHub Desktop: 1.4.3

* Operating system: Windows 10 1809 (OS Build 17763.55)

## Steps to Reproduce

0. This is mostly a problem with the recycle bin. But proof that you can't really rely on this as the only backup.
1. start with a brand new repo
2. edit 3 files and commit
3. edit only one of those files and commit
4. edit the three files again 
5. right click on one file -> "Discard Changes"

you should see the prompt here, which I assumed was just for that one file

### Expected Behavior

expected: only that file should move

### Actual Behavior

actual: all my files left my repo :(

## Additional Information

to restore:
open recycle bin
…
My recycle bin is hundreds of gigs large. I am able to locate my folder, but there's hundreds of file changes in there, and it seems to freeze up. I'm opening an issue with Windows as well regarding the bin size.

### Logs

[2018-10-24.desktop.production.log](https://github.com/desktop/desktop/files/2512761/2018-10-24.desktop.production.log)

**Comment by toddbellMSFT** [comment] 2018-10-25 00:18
I think the main "Discard Changes" issue is probably user error due to accessibility of hardware:

I can't see the shading of my selection in the context menu. I am using a Samsung 4k tv for development  where the current contrast settings for the github desktop context menu is not enough to determine what is currently highlighted. 

In the default light theme, highlighting seems to show as slightly yellow which doesn't show up as well as completely inverting the text color.

**Comment by billygriffin** [comment] 2018-10-25 14:18
@toddbellMSFT Thanks for the issue! Trying to understand this, and I wasn't able to reproduce this from your initial steps. From your follow up comment, are you suggesting that you may have accidentally clicked "Discard All Changes" because you weren't able to see it that well because of the contrast of the selected state in the context menu?

**Comment by toddbellMSFT** [comment] 2018-10-25 15:08
![githubdesktoprevertcontrast](https://user-images.githubusercontent.com/38890212/47510489-19a26080-d82d-11e8-8a05-cf78061e2af0.jpg)

**Comment by billygriffin** [comment] 2018-10-25 16:28
Thanks for the screenshot @toddbellMSFT, I updated the title with what I think is the issue you're describing. Is that accurate? 

@desktop/support Have you seen this before on Windows?

**Comment by steveward** [comment] 2018-10-25 18:57
I bumped up the contrast on a old 32in TV I have and I believe I was able to replicate this behavior. It was not easy to discern what I was hovering over based on the fill color around the `Discard changes` menu item. However, the `Discard changes` text itself still did become noticeably bolder (which seems to be the same behavior in the image @toddbellMSFT shared). 

I had to pretty much max out the contrast on the TV to notice this -- how high is the contrast setting set to on your Samsung TV @toddbellMSFT?

**Comment by toddbellMSFT** [comment] 2018-10-25 21:46
Contrast settings are set at 100%, moving it to 50% is SUPER dim.

**Comment by billygriffin** [comment] 2018-11-14 02:30
@toddbellMSFT Thanks for this issue and apologies for the delay in following up. I think we're going to look at this in the context of https://github.com/desktop/desktop/issues/5342 so I'm going to close this in favor of that one. I'd like to wrap our heads around the larger UX for discarding changes especially if it continues to be something that causes people headaches. Thanks again for helping us understand the cause.

**Closed by billygriffin** 2018-11-14 02:30 UTC
Labels: more-information-needed
