### ISSUE TITLE
Account switch

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#19716] opened 2024-12-14 13:14 UTC
### The feature request

Add a page where you can add more accounts simultaneosly to use in github desktop

### Proposed solution

In the top-right you can insert a profile icon where you can click on it and from here you can change from an account to another

**Comment by sergiou87** [comment] 2024-12-16 10:58
Duplicate of https://github.com/desktop/desktop/issues/3707

Please, subscribe to that issue if you wanna be notified when we make any progress on it, thank you!

**Closed as completed by sergiou87** 2024-12-16 10:58 UTC
