### ISSUE TITLE
Ability to set font size

### ISSUE THREAD

**Issue by Erkam246** [desktop/desktop#8798] opened 2019-12-13 22:39 UTC
### Describe the feature or problem you’d like to solve

Add an option to set font size in settings under Appearance

### Proposed solution

Better readable code

**Comment by tierninho** [comment] 2019-12-14 00:17
@Erkam246 Thanks for filing. This is a dupe of #3543 so i will close this issue. Please follow along there.

In the meantime, have you tried our zoom feature? See the `View` menu on Mac or Windows.

Alternatively, keyboard commands are:

```
Reset Zoom (Mac: ⌘0; Windows: Ctrl+0)
Zoom In (Mac: ⌘=; Windows: Ctrl+=)
Zoom Out (Mac: ⌘-; Windows: Ctrl+-)
```

**Closed by tierninho** 2019-12-14 00:17 UTC

**Comment by Erkam246** [comment] 2019-12-14 09:43
I mean only for  the code not the whole application
