### ISSUE TITLE
Dev build does not fetch the list of Organizations

### ISSUE THREAD

**Issue by Venkat5694** [desktop/desktop#3364] opened 2017-11-18 05:49 UTC
### Description

[Dev build does not fetch the Organizations]

### Version

**GitHub Desktop version:** [1.0.10]

**OS version:** [OS X 10.12.6]

### Steps to Reproduce

1. Run `yarn build:dev`
2. Run `yarn start`
3. Choose a local repository and click on Publish repository
4. Sign-in using your github account
5. Click on Publish repository
6. Notice that there are no organizations listed even if the user is a part of an Organization.

**Expected behavior:** [Organizations must be listed]

**Actual behavior:** [None listed]

**Reproduces how often:** [Always in dev build]

**Comment by shiftkey** [comment] 2017-11-18 22:38
@Venkat5694 my gut feeling is that maybe this is related to the first launch of the app only - do the list of organizations appear when you restart the app?

**Comment by shiftkey** [comment] 2017-11-19 21:09
@Venkat5694 I can reproduce this with one account and not with another. Both accounts have 2FA enabled, but the one that uses SMS shows this issue - the one backed by a 2FA app doesn't. Weird.

**Comment by Venkat5694** [comment] 2017-11-20 03:20
@shiftkey I tried restarting the app, rebuilding it and even logging out and then logging in. Still it fails to fetch org list. I do not have 2FA enabled.

**Comment by joshaber** [comment] 2017-11-20 12:59
I would _guess_ this is because our production OAuth app is exempted from org restrictions, but the dev OAuth app isn't.

**Comment by shiftkey** [comment] 2017-11-20 23:18
@joshaber ah yes, good shout. I had a poke at my account that failed this and it only has the one organization - which does have restrictions enabled for apps. @Venkat5694 I think this might be the case for you too.

**Comment by shiftkey** [comment] 2017-11-21 23:00
Closing this out as working as intended - the dev OAuth app is not intended to be trusted, so organizations enabling restrictions like this is to be expected.

**Closed by shiftkey** 2017-11-21 23:00 UTC
Labels: bug
