### ISSUE TITLE
Pins option for repository selection

### ISSUE THREAD

**Issue by learning-zone** [desktop/desktop#14229] opened 2022-03-24 09:21 UTC
### Search for existing feature requests

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the feature I am requesting.

### The feature request

Pins option in left pannel under Filter for selecting repositories.

### Proposed solution

Pins option in left pannel under Filter for selecting repositories.

**Comment by tidy-dev** [comment] 2022-03-24 12:31
@learning-zone  Thanks for your input. This is a duplicate of https://github.com/desktop/desktop/issues/8183, which currently isn't being worked on. But, we may revisit in the future so I going to link this issue. Feel free to add your comment or thumbs up to that issue as well.

**Closed as completed by tidy-dev** 2022-03-24 12:31 UTC
