### ISSUE TITLE
Split view diff does not highlight changed word

### ISSUE THREAD

**Issue by DrJume** [desktop/desktop#11553] opened 2021-02-09 21:24 UTC
### Describe the bug

When viewing the changes in a commit in the History tab in the left side panel, changes for a file shown in the diff in split view are not highlighted (as seen in the screenshots).

### Version & OS

GitHub Desktop: `2.6.3`
OS: `macOS Catalina 10.15.7`

### Steps to reproduce the behavior

1. Commit a line with more than ~240 characters.
2. Change a word in this line and commit this change.
3. Go to the left side panel 
4. Click on "History" tab
5. Click on the latest commit
6. Click on the file to see the diff
7. Click on the gear icon (Diff settings)
8. Select Diff display: "Split (beta)"

### Expected behavior

The changed word is highlighted as seen in the **unified** diff display.

### Actual behavior

The changed word is *not* highlighted in the **split** diff display.

### Screenshots

**Unified** diff view:
![image](https://user-images.githubusercontent.com/12785972/107426213-36f3b980-6b20-11eb-9c90-055854efd5b5.png)

**Split** diff view:
![image](https://user-images.githubusercontent.com/12785972/107426284-4d9a1080-6b20-11eb-985d-7030a9275589.png)

### Additional context

In all lines tested with a length less than `228` characters, the word surrounded with `{}` was highlighted.
Other tested lines with `243` or more characters, the word surrounded with `{}` was **not** highlighted.
So the threshold should be somewhere in between.

By experimenting a bit, the curly brackets (symbols) are not the direct cause. Any inserted/deleted word or word change have the same result.

**Comment by steveward** [comment] 2021-02-16 21:47
Thanks for the detailed report and reproduction steps @DrJume! I was able to reproduce this issue as well.

**Comment by steveward** [comment] 2021-08-04 15:08
Reported again in https://github.com/desktop/desktop/issues/12718.

**Comment by steveward** [comment] 2024-10-18 14:12
I'm not longer able to reproduce this issue, which is likely due to the new diff engine resolving this. Closing out as resolved.

**Closed as completed by steveward** 2024-10-18 14:12 UTC
Labels: bug, priority-3
