### ISSUE TITLE
"fatal: Could not write a new index file" on Windows 10

### ISSUE THREAD

**Issue by MarkerB** [desktop/desktop#6036] opened 2018-10-30 16:22 UTC
## Description

I get this error when attempting to commit. I can start from scratch with a new clone of an entire repo, but it eventually comes back again.

![gitdesktopcommitfatal](https://user-images.githubusercontent.com/6379326/47733233-2dd7ca80-dc3e-11e8-8dc2-20f6fd0f3d5d.jpg)

It's happened with various repositories, and on my previous Windows 7 Ultimate installation.

I've tried to delete the .git/index file, but then it shows that all the files in my repo are brand new. That's not going to work.

If I restore an older version of the .git/index file, I still get the same error on committing.

My workaround each time has been to start over from scratch, cloning the github.com repo down to my machine, and re-implementing all the changes I had made since my last successful commit and push.

I additionally find I often need to uninstall and reinstall GitHub Desktop to get it to commit without error.

## Version

* GitHub Desktop for Windows 1.4.3 64 bit

* Operating system: Windows 10 Pro

### Logs

2018-10-30T15:58:29.041Z - info: [ui] Background fetch for 3 repositories took 2.028sec
2018-10-30T16:02:09.254Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.395s)
2018-10-30T16:13:30.883Z - info: [ui] Background fetch for 3 repositories took 1.837sec
2018-10-30T16:18:07.639Z - info: [ui] [AppStore] loading 3 repositories from store
2018-10-30T16:18:07.641Z - info: [ui] [AppStore] found account: MarkerB (Mark Bernard)
2018-10-30T16:18:08.096Z - info: [ui] launching: 1.4.3 (Windows 10.0.16299)
2018-10-30T16:18:08.097Z - info: [ui] execPath: 'C:\Users\mark\AppData\Local\GitHubDesktop\app-1.4.3\GitHubDesktop.exe'
2018-10-30T16:18:09.081Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.137s)
2018-10-30T16:18:16.401Z - error: [ui] `git reset -- .` exited with an unexpected code: 128.
Unstaged changes after reset:
M	xxxxxxx_archive.php
M	functions/xxx/xxxmisc.php

fatal: Could not write new index file.

**Comment by steveward** [comment] 2018-10-30 17:10
@MarkerB a few other questions that may help us track down the cause of this:

- Are you storing this repository in a regular user directory with the correct permissions set? Often these types of errors can be related to permissions issues, but if you are able to clone to the directory then that doesn't seen likely. 

- Is this repository being stored in a directory that is being tracked by a file sharing service like DropBox? That can sometimes cause these types of issues as well.

**Comment by MarkerB** [comment] 2018-10-30 17:33
Ah, hah!  I am using Google Backup and Sync!  I thought it would be read-only, but who knows?

I'll disable it and try again.

Thank you so much for this!

**Comment by steveward** [comment] 2018-10-31 19:42
@MarkerB just wanted to follow up -- did that get things working for you?

**Comment by MarkerB** [comment] 2018-10-31 19:55
Oh, yes.  So far, so good.  It was an intermittent problem, so I wanted to give it a little more of a test.

Google Backup and Sync may have been locking the git index file when it saw the file updated, locking it long enough to upload it to the cloud.  Maybe GitHub Desktop needed the file more freely accessible than that.

Since Google Backup and Sync doesn't allow exclusion by folder, I had to put my git repo in a completely separate folder.

Thank you so much!  This had been a real problem for me in the last week; not sure why it came and went. Timing.

**Comment by alphaKuz** [comment] 2018-10-31 20:06
No more

**Comment by steveward** [comment] 2018-11-01 11:43
@MarkerB I'm glad to hear things are working now. Since we've identified that as the root cause I'm going to close this issue out.

**Closed by steveward** 2018-11-01 11:43 UTC
Labels: more-information-needed

**Comment by riwalenn** [comment] 2019-04-04 09:33
Thanks man, you right Google Backup and Sync suck :/

**Comment by MarkerB** [comment] 2019-04-04 14:18
> Thanks man, you right Google Backup and Sync suck :/

It's probably not that simple. It seems more likely it's just an unfortunate interaction between GitHub and Google and creative methods they use to keep track of things.

**Comment by riwalenn** [comment] 2019-04-04 14:37
> It's probably not that simple. It seems more likely it's just an unfortunate interaction between GitHub and Google and creative methods they use to keep track of things.

Yeah sorry, it's just that i have a very poor english and just to thank you for the solution. And i think it isn't normal that the problem already exist and they don't found a solution :/

**Comment by Abesuden** [comment] 2020-03-28 00:23
I had the same issue but my solution was to close my VS Code program. I guess it ties up the GitHub Desktop and causes this type of issue.

**Comment by wangdanyang711** [comment] 2020-07-07 09:13
![image](https://user-images.githubusercontent.com/59977368/86756424-f5c09600-c074-11ea-9870-9dcf2c8a3d41.png)
Hello there. 
I also get the same issue when push, after reinstall operating system. 
Please give me solution.

**Comment by steveward** [comment] 2020-07-07 14:38
@wangdanyang711 are you storing your repositories in a file syncing service? Are there any other Git applications running? Can you verify that the correct file permissions are set for the location where you are storing your repositories?

**Comment by wangdanyang711** [comment] 2020-07-07 15:50
Thanks for your reply.
-are you storing your repositories in a file syncing service? 
   I don't know about the file syncing service. so I am not sure I am using it.
-Are there any other Git applications running? 
   yes. Git Bash application installed. for using git with command lines. but I am not so good at command lines for git.
  so I don't use it.
![image](https://user-images.githubusercontent.com/59977368/86807167-34257780-c0ac-11ea-8a50-91296a3336e6.png)

-Can you verify that the correct file permissions are set for the location where you are storing your repositories?
   you mean like as below image?
![image](https://user-images.githubusercontent.com/59977368/86807534-89618900-c0ac-11ea-966a-3f985b4530cc.png)
It seems readonly. so I unchecked readOnly option but also it does not work.

**Comment by steveward** [comment] 2020-07-07 18:25
The folder permissions would be visible in the `Security` tab. Are you able to commit changes using Git Bash?

**Comment by xdevs23** [comment] 2025-01-02 19:05
In case you can't track down another git process holding the lock, sometimes you just need to delete the `.git/index.lock` file. That can happen when a git process crashes or is killed.
