### ISSUE TITLE
Provide a better error message and give users the option to retry a failed clone

### ISSUE THREAD

**Issue by joshaber** [desktop/desktop#926] opened 2017-02-08 21:02 UTC
As of https://github.com/desktop/desktop/pull/924, we tell the user when a clone has failed, but the user now has to close out of the error message, go back into the clone dialog, select the same repo again, and clone. A better solution would be to provide users the option to immediately retry cloning the same repo if it fails.

**Comment by Daniel-McCarthy** [comment] 2019-02-28 23:51
I talked with @iAmWillShepherd  and have looked into the error handlers and how to detect this error in order to throw a user friendly error in it's place as per the previous Issue #2838. 

I ran into an issue with being able to properly detect the error. I started by debugging the error handlers to see what the error object contained as it is passed through. I started in [`gitAuthenticationErrorHandler()`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/ui/dispatcher/error-handlers.ts#L127-L171) and placed a breakpoint before causing the clone failed error to be emitted. The error that was passed into the error handler did not seem to have much distinguishing information (primarily a 128 exit code and the error text itself). Here is what the function did with the error:

- The clone error is passed into the gitAuthenticationErrorHandler.
- The error has a result object that contains an exit code 128, a null gitError, and null gitErrorDescription. It has the error message in the stderr variable.
- The handler passes the error to asErrorWithMetadata() and checks if the result is null. The result is not null and it continues.
- The handler then passes the error to asGitError() and checks if the result is null. The result is not null and continues.
- Then it checks if the error's result's gitError variable is null. The check is returning true and the handler returns the error immediately.

It seems strange that this information was null. The 128 exit code seems to be generic and the main identifying information is the error text itself. This seems unusual given that the other error handlers seem to expect and rely on git and dugite errors. I had intended to use this information to attempt to add a handler for this specific cloning error.

**Comment by shiftkey** [comment] 2019-03-01 16:25
@Daniel-McCarthy 

Given the details provided my initial feeling is that the app isn't parsing the output from [`git()`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/core.ts#L107-L112) to an error in the way you're expecting. I'll walk through the extra context on what happens _before_ the error handlers fire that I believe is relevant to the root cause of your issue:

1.  Errors are parsed when an exit code doesn't match the `successExitCodes` array (by default this is just a set containing `0`, so any non-zero exit code should trigger error parsing).

https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/core.ts#L129-L131

Ensure you haven't set `128` as a `successExitCodes` value, otherwise `git()` will not bother parsing for errors. `clone.ts` doesn't look like it passes in a `successExitCodes` option, so I think this is fine.

2. If the function should parse for errors, it will first try and parse `stderr` for a matching `DugiteError`, and if no match is found it will fall back to reading `stdout`.

https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/core.ts#L132-L137

This is where I have questions about what you are seeing currently:

 - what do `stderr` and `stdout` contain?
 -  looking at the [list of regexes here](https://github.com/desktop/dugite/blob/b6f08de5130b0a9cbff478ad91e621bc4f4f3d68/lib/errors.ts#L55), what output are you expecting to match to which error from this list? 

This could be something changing between Git versions and we just need to tweak `dugite` to add a new mapping (or relax an existing regex). **This is what I would focus on stepping through as part of seeing the clone fail.**

3. We build up the `IGitResult` to return here by appending the description (if a Git error was found):

https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/core.ts#L139-L140

If we have no `gitError`, we likely won't have a `gitErrorDescription`.

4. Whether this function returns or errors is driven by the `expectedErrors` parameter passed into `git()` - this is a way for the caller to anticipate an error and handle it itself rather than propagate this to the error handlers.

https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/core.ts#L142-L149

You can see an example of this over in #6961 with the rebase workflow:

https://github.com/desktop/desktop/blob/76d48b925f969aad3c192929f4db3574e5b9a46b/app/src/lib/git/rebase.ts#L190-L200

I believe `git()` is throwing an error here for all clones that error, because you're seeing the error handlers fire, but that's something to be aware of if you're interested in changing the behaviour of how `clone.ts` works.

**Comment by Daniel-McCarthy** [comment] 2019-03-01 20:08
@shiftkey This is wonderful information! Thank you for sharing all this in such great detail. I found this very useful.

After reading this I have compared the `stderr` I was getting compared to the available regex patterns.

Dugite includes this:
`"fatal: unable to access '(.+)': Failed to connect to (.+): Host is down": GitError.HostDown,`

`"Cloning into '/home/hellokitty/Documents/GitHub/Chixel'...
fatal: unable to access 'https://github.com/Daniel-McCarthy/Chixel.git/': Could not resolve host: github.com"`
___
It appears the regex pattern is no longer matching the error. Unless there are extra factors to consider, I think we could update the pattern in dugite to:
`"Cloning into '(.+)'... fatal: unable to access '(.+)': Could not resolve host: (.+)"`

**Comment by shiftkey** [comment] 2019-03-01 20:24
@Daniel-McCarthy this seems like a good contribution to `dugite` as a pre-requisite for this work. 

These PRs where we've made changes to the error parsing should be a good guide to show what needs to change: https://github.com/desktop/dugite/pull/306 https://github.com/desktop/dugite/pull/271

> Unless there are extra factors to consider, I think we could update the pattern in dugite to:
> `"Cloning into '(.+)'... fatal: unable to access '(.+)': Could not resolve host: (.+)"`

My gut feels that this should be an additive regex that maps to the same error code, because I'm not 100% sure the old message is deprecated. `Could not resolve host` comes from here inside `curl` (which Git depends upon):

https://github.com/curl/curl/blob/65eb65fde64bd5faff6d6a7740f9436336e290e0/lib/asyn-thread.c#L458-L459

I couldn't find the same `Host is down` message in `curl`, but that might be because it receives this message from the underlying OS. Anyway, we can talk more about this in the PR.

**Comment by Daniel-McCarthy** [comment] 2019-03-01 20:33
@shiftkey Wonderful. Thanks again for the help and fantastic information. I will look into adding this regex pattern to Dugite.

**Comment by Daniel-McCarthy** [comment] 2019-03-05 19:30
I talked with @shiftkey to get a better idea of what the scope of this proposed functionality would be. I was hoping to work on #2838, which was marked `Help Wanted` but was merged into this Issue. However, it seems that this Issue still requires some more thought and is not currently marked `Help Wanted.` Perhaps @desktop/product would have a good idea of what this feature would entail. Any thoughts would certainly be appreciated.

**Comment by billygriffin** [comment] 2019-03-07 17:15
Chatted with @Daniel-McCarthy about this, and added `help wanted` here as they've already made progress on surfacing a better error message here and getting the internals set up to try the clone again. We discussed that the popup surface would have the error message, and also a "Close" button and a "Retry Clone" button. Feel free to ask if anyone has additional questions.

**Comment by Daniel-McCarthy** [comment] 2019-03-07 20:58
@billygriffin 
This appears to be what is thrown when cloning with no internet connection as of [Dugite #308](https://github.com/desktop/dugite/pull/308). I mentioned I would update this thread with the error that would now be thrown when Dugite is next bumped.
![image](https://user-images.githubusercontent.com/4957200/53988483-3018cc80-40e9-11e9-8059-310e9af28a69.png)

**Comment by billygriffin** [comment] 2019-03-07 21:24
@Daniel-McCarthy Thanks! That's a bit of an odd one but I still think it provides *some* information that's a bit more plain language to where it's better than what's present today. 😄

**Comment by Daniel-McCarthy** [comment] 2019-03-11 03:24
I have the base for a pull request ready. However, if one wishes to test the retry cloning dialog via the host is down error, then Dugite must be bumped to version `1.86.0` first.

However, in order to bump Dugite there is a pending change that needs to be made (A description for `DugiteError.UnresolvedConflicts` seemingly needs to be added to the `getDescriptionForError` function in `src/lib/git/core.ts`). I will capture this in a separate Issue.

**Comment by shiftkey** [comment] 2019-05-06 16:22
Just dropping a note in here to indicate the clone is not resumable by default in Git, so this "retry" step won't reuse the previous clone attempt. I wrote up a workaround in #7440 if you work in an environment with a really flaky network.

**Closed** 2020-04-30 00:22 UTC
Labels: enhancement, help wanted

**Comment by manugd14** [comment] 2020-05-12 19:04
Now, when trying to clone a repo from an external host (gitlab in this case), instead of prompting me for my gitlab credentials once authentification with github fails, I enter on the infinite retry loop.....
