### ISSUE TITLE
The old icon remains in the list of installed Windows applications

### ISSUE THREAD

**Issue by rakleed** [desktop/desktop#11839] opened 2021-03-19 23:01 UTC
### Describe the bug
The old icon remains in the list of installed Windows applications in Settings and Control Panel, although you recently updated the icon (https://github.com/desktop/desktop/pull/11388 and https://github.com/desktop/desktop/pull/11541).

### Version & OS
GitHub Desktop 2.6.6
Windows 10 v. 20H2

### Steps to reproduce the behavior
1. Install GitHub Desktop on Windows
1. Go to "Settings - Apps - Apps & features" or "Control Panel - Programs - Programs and Features"
3. Scroll down to GitHub Desktop
4. Look at the icon opposite GitHub Desktop

### Expected behavior
The new icon is displayed in front of the GitHub Desktop.

### Actual behavior
The old icon is displayed in front of the GitHub Desktop.

### Screenshots
<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/19418601/111849832-a2028e00-891f-11eb-931a-8be5b0369b6b.png)

![image](https://user-images.githubusercontent.com/19418601/111849864-b47cc780-891f-11eb-9772-5dd5d30231ca.png)

</details>

### Additional context
This information will probably be useful - http://www.jrsoftware.org/ishelp/index.php?topic=setup_uninstalldisplayicon.
To fix this, you most likely need to update UninstallDisplayIcon in the registry.

**Comment by steveward** [comment] 2021-03-24 18:13
Thanks for the report @rakleed. The icon cache should eventually update to the new icon after a period of time. To force a fix for this you can log out and then log back in to your Windows user account. Thanks for using GitHub Desktop!

**Closed as completed by steveward** 2021-03-24 18:13 UTC

**Comment by rakleed** [comment] 2021-03-24 20:13
@steveward I installed the latest 2.6.6 in a virtual machine from scratch, but it didn't help. So the problem is clearly not the cache.

**Comment by rakleed** [comment] 2021-03-27 16:05
@ampinsk and @tidy-dev, please take a look.

**Comment by ItzLevvie** [comment] 2021-04-11 19:08
I'm unable to reproduce; even on a clean install of Windows 10.

**Comment by ItzLevvie** [comment] 2023-06-02 21:41
This issue happens because the `app.ico` file in `C:\Users\%USERNAME%\AppData\Local\GitHubDesktop` has not been updated with the latest icon:
![image](https://github.com/desktop/desktop/assets/11600822/889b170e-bcb5-44c6-aeea-785890c22f89)
![image](https://github.com/desktop/desktop/assets/11600822/1f0c5457-b960-44e5-ab5d-e9d9ac27036b)
![image](https://github.com/desktop/desktop/assets/11600822/d9dfcd9a-572c-4153-a2fd-af52bf0897e5)

When you copy `desktop-development\app\static\logos\icon-logo.ico` to `C:\Users\%USERNAME%\AppData\Local\GitHubDesktop\app.ico` it will work correctly:
![image](https://github.com/desktop/desktop/assets/11600822/50b6029c-7562-4e6b-96f9-a26dd9084f98)
![image](https://github.com/desktop/desktop/assets/11600822/346eb34f-42f3-4141-bc92-97ea631c6961)

This is part of GitHub Desktop's build process for building the Windows binaries so this is technically not publicly accessible to any contributor out there so only a GitHub Desktop engineer can make these fixes. Perhaps @tidy-dev or someone else should take a look into this internally.

In the future this should be unified where the build process can grab the icons from the desktop repo so that we don't run into the same issues again if GitHub decides to bring a new icon in the next 5 or 10 years later.
