### ISSUE TITLE
Pixel overflow in multiple screen

### ISSUE THREAD

**Issue by M4dHgDg** [desktop/desktop#14767] opened 2022-06-09 07:38 UTC
### The problem

Its hard to see, but on multiple screen, the border of the windows overflow to the next screen. In the attached picture, i highlighted where is the corned of my second monitor. Not a big bug, but still :) 

### Release version

Version 3.0.1 (x64)

### Operating system

Windows 10

### Screenshots

![sd](https://user-images.githubusercontent.com/55232838/172791206-f82dae73-2e43-443e-86d0-46b219ee4e61.png)

**Comment by M4dHgDg** [comment] 2022-06-09 07:40
may its easier if screen is not black: 
![sd2](https://user-images.githubusercontent.com/55232838/172792047-4765c3dd-01c9-4d62-a585-bc39aa7123f5.png)

**Comment by sergiou87** [comment] 2022-06-09 07:59
I think this is duplicate of #13939

Please, subscribe to that issue if you want to be notified when it's fixed!

**Closed as completed by sergiou87** 2022-06-09 07:59 UTC
