### ISSUE TITLE
Default branch not changing

### ISSUE THREAD

**Issue by kjvdven** [desktop/desktop#14844] opened 2022-06-21 07:01 UTC
### The problem

I use github desktop in combination with our self hosted gitlab installation. Here we set develop as our default Branch, but github desktop isn't updating it in the application and still shows main as our default branch. 

### Release version

Version 3.0.2 (arm64)

### Operating system

MacOS Montery 12.4

### Steps to reproduce the behavior

1. Create a new repository on gitlab
2. Check out the repository in github desktop
3. Create a branch "develop" 
4. Make the branch "develop" the default branch
5. Fetch all changes

### Screenshots

![Screenshot 2022-06-21 at 08 54 42](https://user-images.githubusercontent.com/306806/174735986-591f6d16-b0ca-400a-a6b7-b86bfe18ab9b.png)
![Screenshot 2022-06-21 at 08 55 58](https://user-images.githubusercontent.com/306806/174735990-5229652c-3062-4b7c-90eb-6a206cf873c3.png)

**Comment by sergiou87** [comment] 2022-06-21 14:21
Thanks for your report @kjvdven ! I think this is (to some extent) a duplicate of #14266, so I added a mention to this issue there. Because of that I'll close this issue in favor of that one. Feel free to subscribe to it if you want to get notified if we made any progress!

**Closed as completed by sergiou87** 2022-06-21 14:21 UTC
