### ISSUE TITLE
show Repository in explorer no longer working

### ISSUE THREAD

**Issue by highfly117** [desktop/desktop#4669] opened 2018-05-13 10:15 UTC
when clicking repository and show in explorer or Ctrl-Shift-F nothing happens. This used to work but for some reason doesn't anymore 

## Version

* GitHub Desktop: Github desktop version 1.1.1

* Operating system: windows 10, Microsoft Windows [Version 10.0.16299.431]

### Expected Behavior
to open explorer folder that the repository files are in.

### Actual Behavior
nothing

### Logs

log files are in  `%APPDATA%\Roaming\GitHub Desktop\logs\

[2018-05-13.desktop.production.log](https://github.com/desktop/desktop/files/1998428/2018-05-13.desktop.production.log)

**Comment by shiftkey** [comment] 2018-05-13 12:05
@highfly117 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by highfly117** [comment] 2018-05-13 12:46
I have found a fix for this. I had to remove the repository folders and then re-clone them and now it works again

**Comment by shiftkey** [comment] 2018-05-13 23:11
@highfly117 it looks like this is a duplicate of #4662 

```
2018-05-13T10:07:50.419Z - error: [main] Unable to find file at 'C:\Users\adam_\OneDrive\Documents\LiveGridpy'
Error: EINVAL: invalid argument, stat 'C:\Users\adam_\OneDrive\Documents\LiveGridpy'
```

I've added some context to that issue about the underlying problem, and a workaround for if you want to keep using your files from OneDrive, so please follow along with that.

**Closed by shiftkey** 2018-05-13 23:11 UTC
Labels: more-information-needed
