### ISSUE TITLE
Errors immediately following launch after 1.6.3 update

### ISSUE THREAD

**Issue by lewisarmistead** [desktop/desktop#7028] opened 2019-03-07 16:27 UTC
## Description
I am receiving an error every time I open GitHub Desktop that says "error launching git: The filename or extension is too long" - when I close this, a "Can't find <repository>" error message displays on the GitHub Desktop main pane (and this happens for every repository I switch to). When I switch between repositories using the dropdown menu in the top left, the error message "Git returned an unexpected exit code '1' which should be handled by the caller.'" - please note that the single quote at the end of the error message is not a typo. When I press the "Locate..." button and select the repo folder, I get the same error message. When I press the "Clone Again" button and select the repo folder, I get the same error as the first one I encountered "error launching git etc..."

## Version
* GitHub Desktop*: 1.6.3
* Operating system*: Windows 7 Professional (Microsoft Windows [Version 6.1.7601])

## Steps to Reproduce
Nothing on my system changed except for the version update from 1.6.2 to 1.6.3 when I rebooted my computer this morning.

### Expected Behavior
I expect to be able to use the GitHub Desktop application after launching.

### Actual Behavior
I am unable to connect the application with any repositories via any git commands available on the application GUI.

## Additional Information
I believe this is somehow related to the update from 1.6.2 -> 1.6.3 since I was not getting the error messages when 1.6.2 was running yesterday

I've tried uninstalling GitHub Desktop and reinstalling it, rebooting my computer, updating Git (although I now realize GH Desktop uses its own Git separate from what is designated in my PATH), running `git config --system --replace-all core.longpaths true` as an Administrator, and adding 
`[core]
longpaths = true`
to the gitconfig file located here: C:\Users\Lewis.Armistead\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\git\mingw64\etc\gitconfig as a manual attempt at replicating the functionality of the previous git command.

### Logs
Here is an abbreviated log from this morning showing the first error message:
[2019-03-07.desktop.production.log](https://github.com/desktop/desktop/files/2942173/2019-03-07.desktop.production.log)

Looking at the logs yesterday, I noticed that the GitHub Desktop version was 1.6.2:
[2019-03-06.desktop.production.log](https://github.com/desktop/desktop/files/2942222/2019-03-06.desktop.production.log)

Please note that the initial errors on 3/6 were related to my computer not being connected to the internet.

**Comment by shiftkey** [comment] 2019-03-07 16:38
@lewisarmistead thanks for the report!

> I've tried uninstalling GitHub Desktop and reinstalling it, rebooting my computer, updating Git (although I now realize GH Desktop uses its own Git separate from what is designated in my PATH), running `git config --system --replace-all core.longpaths true` as an Administrator, and adding
> `[core] longpaths = true`
> to the gitconfig file located here: `C:\Users\Lewis.Armistead\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\git\mingw64\etc\gitconfig` as a manual attempt at replicating the functionality of the previous git command.

If `core.longpaths` is something you require to set for all Git usage on your machine, you should use the global Git config at `~/.gitconfig` - or `git config --global --replace-all core.longpaths true` - and Desktop will use that. Modifying the system config for the Git embedded in Desktop will be removed when the next update is applied, putting you back to where you previously were.

System config is reserved for the Git distribution itself, and I don't think we'll enable `core.longpaths` by default because of the recommendations in the Git for Windows docs:

> **core.longpaths**:
> Enable long path (> 260) support for builtin commands in Git for Windows. This is disabled by default, as long paths are not supported by Windows Explorer, cmd.exe and the Git for Windows tool chain (msys, bash, tcl, perl…​). Only enable this if you know what you’re doing and are prepared to live with a few quirks.

**Comment by n8all3n** [comment] 2019-03-07 17:03
I just got the 1.6.3 update, and I've tried to update longpaths global, system, and a local repo, but am still getting the same error as @lewisarmistead

**Comment by lewisarmistead** [comment] 2019-03-07 17:08
@shiftkey I tried doing the global option previously as well with the same errors. Do you know what changes between 1.6.2 and 1.6.3 could have caused the error since I wasn't seeing it with 1.6.2?

Thank you for the prompt response!

**Comment by shiftkey** [comment] 2019-03-07 17:29
@lewisarmistead @n8all3n between `1.6.2` and `1.6.3` we upgraded the `dugite` package:

```diff
$ git diff release-1.6.2..release-1.6.3 -- app/package.json                                                                                        ±[shiftkey/rebase/force-push-sometimes]
diff --git a/app/package.json b/app/package.json
index 2d1331d8b..9c3de662f 100644
--- a/app/package.json
+++ b/app/package.json
@@ -3,7 +3,7 @@
   "productName": "GitHub Desktop",
   "bundleID": "com.github.GitHubClient",
   "companyName": "GitHub, Inc.",
-  "version": "1.6.2",
+  "version": "1.6.3",
   "main": "./main.js",
   "repository": {
     "type": "git",
@@ -26,7 +26,7 @@
     "deep-equal": "^1.0.1",
     "dexie": "^2.0.0",
     "double-ended-queue": "^2.1.0-0",
-    "dugite": "^1.80.0",
+    "dugite": "1.83.0",
     "electron-window-state": "^4.0.2",
     "event-kit": "^2.0.0",
     "file-uri-to-path": "0.0.2",
```

[`dugite@1.81.0`](https://github.com/desktop/dugite/releases/tag/v1.81.0) upgraded to Git `v2.20.1` as well as Git LFS `v2.6.1` - which might be a factor here. I've not been able to spot any regressions with these versions, but if you're able to find versions of Git that work fine with `core.longpaths` enabled that's a starting point.

I also see this issue on the Git for Windows tracker, but I'm not clear if it's been resolved: https://github.com/git-for-windows/git/issues/2075

**Comment by mark-jensen** [comment] 2019-03-07 20:05
Desktop 1.6.3 giving me the same error in Windows 7, but working as expected on Mac (10.14.3).

**Comment by lewisarmistead** [comment] 2019-03-08 01:07
@shiftkey thanks for the time looking into this. This issue is a bit above my head; I don't think it's worth it for me to manage the application's embedded git version if that ends up being the requirement. I've switched to using Atom for the time being but would be interested in switching back if this issue gets resolved

**Comment by shiftkey** [comment] 2019-03-08 12:02
@lewisarmistead to help speed up troubleshooting it'd be nice to know what versions of Git are working on your machine for the repositories which need `core.longpaths`, compared to the current one in Desktop. Are you able to share that information too if you have an alternate working setup?

**Comment by mgenovese** [comment] 2019-03-08 15:01
I am having the same issue since upgrading from 1.6.2 to 1.6.3.

**Comment by steveward** [comment] 2019-03-08 18:24
@lewisarmistead @lewisarmistead @mgenovese @n8all3n -- are any of you working with public repositories that I could take a look at to see if I can reproduce the same issue you are experiencing? So far I have been unsuccessful in reproducing this issue in both Windows 7 and Windows 10 virtual machines -- cloning fails as expected with a long file path in the repository, but setting `core.longpaths` to `true` resolves the issue.

It would also be helpful if you could share the version of Git for Windows that you have currently installed on your Windows 7 machines by launching Git Bash and running `git --version`. Thanks!

**Comment by mgenovese** [comment] 2019-03-08 18:41
I am currently running Windows 7, Git version "2.21.0.windows.1".

**Comment by n8all3n** [comment] 2019-03-08 19:13
I'm running Windows 7, Git version 2.10.1.windows.1.  Like @mgenovese  everything was working fine, prior to auto upgrading to 1.6.3.  

Basically any repository I go to gives this error, so any of my public repos it occurs on.

**Comment by lewisarmistead** [comment] 2019-03-08 19:33
@shiftkey @steveward I am also running Git 2.21.0.windows.1, but I had an older version installed (that I updated upon initial troubleshooting) when I encountered the problem initially although I'm not sure which one. I encountered/am still encountering the same problem with both the old version of Git and 2.21.0

**Comment by Thomas-Fisher** [comment] 2019-03-11 15:54
Hello, i was having the same issue, with version 1.6.3, i would get the following error upon opening github desktop: "error launching git: The filename or extension is to long."

I navigated to the following folder and attempted to open git.exe and got the same issue
~\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\git\cmd

I appear to have found a possible fix (unsure on the side affects of doing this but it has allowed me to now use application again )

I found the following git.exe 2691 KB - the previous git.exe was 40KB
~\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\git\mingw64\bin
I copied the exe from there into the ~\AppData\Local\GitHubDesktop\app-1.6.3\resources\app\git\cmd location and reopened GitHubDesktop and it appears to be working on the surface

**Comment by lewisarmistead** [comment] 2019-03-11 17:21
I just tried the fix that @Thomas-Fisher proposed, and it seems to be working for me as well

**Comment by mgenovese** [comment] 2019-03-11 17:50
The fix that @Thomas-Fisher proposed allows my Windows Client to startup without error.  However, when I try to clone down using my server URL (not public sorry) I get a bunch of errors starting with "warning: templates not found in /mingw64/share/git-core/templates" and ending with "fatal: 'submodule' appears to be a git command, but we are not able to execute it".  So I traded one issue for another.

**Comment by shiftkey** [comment] 2019-03-11 17:54
@Thomas-Fisher @lewisarmistead @mgenovese I can't recommend the workaround for swapping out `app\git\cmd` for the version in `app\git\mingw64\bin` because these are not equivalent binaries and serve different purposes. 

We're working on a hotfix release over in #7063 and once that's published to beta I'd love some assistance from you to confirm we're back to a happy place.

**Comment by Thomas-Fisher** [comment] 2019-03-11 17:58
@mgenovese Sorry that didn't work for you, i hadn't tried cloneing, i just tried it and get the same issue
![image](https://user-images.githubusercontent.com/6746343/54145934-d6850a80-4426-11e9-840e-ece93cfdd7a9.png)

@shiftkey I guessed that swapping the .exe's would not be a good option but it allowed me to do what i needed for the time being ( just pulling and pushing) until a fix was found.

Glad a hotfix is on the way

**Comment by shiftkey** [comment] 2019-03-11 19:01
I'd love to be able to ensure we close out this issue as now handling folders that exceed `MAX_PATH` (260 characters) correctly, and for those who have been involved with this issue I'd love some concrete steps to reproduce this.

The bit that I'm missing is **what folder is your problem repository located in on disk**? We don't log this for privacy reasons, but in this situation it'll help me confirm the setup to trigger this.  Git fails in all sorts of ways around `MAX_PATH` and ideally I'd like to see this same error as you are.

This is what I'm currently lacking:

 - what version of Windows are you running?

```
> cmd /c ver
```

- is `core.longpaths` set in the repository?

```shellsession
$ git config core.longpaths
```

- what is the full path to the repository folder on disk? (this is helpful to ensure I'm configuring my environment correctly)
- is this a public repository I can access and poke at it (this will help greatly with troubleshooting)
 - which folder inside the repository is longer than `MAX_PATH`?
- is this folder tracked by Git?

@lewisarmistead @n8all3n  @mark-jensen @mgenovese @Thomas-Fisher you've all reported this issue - are you able to provide more details so I can reproduce this? If you're concerned about sharing some details publicly you can email me at [handle] at github dot com to help with troubleshooting.

Also, if you're able to [build Desktop on Windows](https://github.com/desktop/desktop/tree/development/docs/contributing) I'd love to work with you to test specific builds in advance of this hotfix, so we can ensure this is resolved or reported upstream if it's reproducible on the latest version of Git for Windows.

**Comment by CPernet** [comment] 2019-03-11 19:18
I have the exact same issue -- the long path solves nothing for me (tried all the different ways indicated above and elsewhere) ; turning back to an older version and no problem

**Comment by nerdneha** [comment] 2019-03-11 19:38
Hi @CPernet, thanks for letting us know that you're also affected by this. 

Any chance you might be able to provide some of the answers to @shiftkey's [questions above](https://github.com/desktop/desktop/issues/7028#issuecomment-471676909) so we can get to the root of this? 

We'd love to work with you to get us reproducing this consistently.

**Comment by mgenovese** [comment] 2019-03-11 20:41
Only thing I can offer right now is mt Windows version - 6.1.7601

**Comment by nerdneha** [comment] 2019-03-11 23:34
Hi all 👋🏾, wanted to give you all an update! Our current plan is to release the beta in about 12 hours (plus or minus a few) during the workday of our non-US developers 🌏🌍🌎. We'll post back here with the beta release but we will be relying upon the folks in this issue (and a few others) to give us feedback on whether your GitHub Desktop app is back to normal.

This hotfix (#7063) should address the overarching issue but won't address the root cause, which would make us confident that this error wouldn't happen again. We still absolutely want and need to get to the root cause but we need your help by getting some help on the questions that have been [asked above](https://github.com/desktop/desktop/issues/7028#issuecomment-471676909).

📋 Thanks to a few folks (thanks @mgenovese!) we're getting Windows versions but we also need answers to some of the other questions, ex: 
* > is core.longpaths set in the repository?
* > what is the full path to the repository folder on disk? (this is helpful to ensure I'm configuring my environment correctly)
* > which folder inside the repository is longer than MAX_PATH?

(and others)


If anyone has a minute to reply here, message us, or find an opportunity to pair, we'd love to get more information so that we can get a better long-term fix out 🙏🏾🙇🏾‍♀️.

**Comment by lewisarmistead** [comment] 2019-03-12 02:10
@shiftkey @nerdneha - sorry for the late response. I cloned my hello world repo, which is public, to try to help troubleshoot. see my answers to your questions here:
- what version of Windows are you running?
  - Version 6.1.7601
- is core.longpaths set in the repository?
  - it seems as though it is
```
Lewis.Armistead@LARMISTEAD-P50 MINGW64 /c/Git_Repositories/hello-world (master)
$ git config core.longpaths
true
```
- what is the full path to the repository folder on disk? (this is helpful to ensure I'm configuring my environment correctly)
  - C:\Git_Repositories\hello-world
- is this a public repository I can access and poke at it (this will help greatly with troubleshooting)
  - I cloned a public repo to try to help in reproducing the issue
- which folder inside the repository is longer than MAX_PATH?
  - I don't think there are any longer than MAX_PATH
- is this folder tracked by Git?
  - since I wasn't able to clone the repo using GitHub desktop, I cloned it in Git Bash. Changes seem to be being tracked, at least when I add or remove files
```
Lewis.Armistead@LARMISTEAD-P50 MINGW64 /c/Git_Repositories/hello-world (master)
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    python.exe

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

Let me know if I can provide any other information to help troubleshoot.

**Comment by gregorio4g** [comment] 2019-03-12 09:37
Hi, I have the same error. Here are the answers for your questions;

- what version of Windows are you running? Microsoft Windows [Version 6.1.7601]
- is core.longpaths set in the repository? false
- what is the full path to the repository folder on disk? d:\Users\105053053\Documents\GitHub\nextgen-cr\
- is this a public repository I can access and poke at it? None of my repositories is public :(
- which folder inside the repository is longer than MAX_PATH? I don't know how to check the value of MAX_PATH, but it does not seem that my folders have long names.
- is this folder tracked by Git? I have no folders inside this repository.

**Comment by Thomas-Fisher** [comment] 2019-03-12 11:50
@nerdneha @shiftkey 

Windows version : 6.1 build 7601 service pack 1

is core.longpaths set in the repository? i cannot check this currently as doing git config core.longpaths returns "error launching git: the filename or extension is too long" and i am not sure where else i could find out

what is the full path to the repository folder on disk? : D:\GitHub\1234567\src\core
The longest path inside that repo would be "D:\GitHub\1234567\src\core\coretestharness"
(i have just replaced the name of the overarching folder with numbers, the folder name is of size 7 )

This would be the checkout from location of core
http://1234567890:1234/1234567890/core

In regards to being able to build desktop for windows will just following [https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md](url) get me to a point where i can test a certain build? ( also are the versions for node yarn and python specific? e.g i currently have python 3.7.2 )

**Comment by shiftkey** [comment] 2019-03-12 12:46
We have published `1.6.4-beta1` just now which reverts the embedded Git in Desktop from `2.20.1.windows.1` to `2.19.2.windows.1`, which we believe will address this issue.

In the process of investigating we've identified at least two known issues with `2.20.1.windows.1` that have since been fixed in Git for Windows:

 - https://github.com/git-for-windows/git/issues/1989
 - https://github.com/git-for-windows/git/issues/2075

Because of the complexity of the setup to trigger these issues **we are looking for any Windows users to help us confirm this problem has been resolved, which requires installing [the latest beta](https://github.com/desktop/desktop#beta-channel) and testing their problem repositories again**.

We plan to make this available today to everyone, but it would be great to know in advance that these specific issues are addressed.

Thanks again for working with us to get this resolved!

**Comment by Thomas-Fisher** [comment] 2019-03-12 12:59
@shiftkey  Do i need to clone a beta branch and build it to test? or do i installed from the link under the heading below

Beta Channel
Want to test out new features and get fixes before everyone else? Install the beta channel to get access to early builds of Desktop:

**Comment by shiftkey** [comment] 2019-03-12 13:02
@Thomas-Fisher you can install the latest beta channel to test it out. I'll follow up with your other questions about the setup in a moment.

**Comment by shiftkey** [comment] 2019-03-12 13:07
@Thomas-Fisher 

> In regards to being able to build desktop for windows will just following https://github.com/desktop/desktop/blob/development/docs/contributing/setup.md get me to a point where i can test a certain build? ( also are the versions for node yarn and python specific? e.g i currently have python 3.7.2 )

Yes, that setup guide should be all that you need. In terms of specific dependencies:

 - Node 8 or later
 - Yarn - any recent version (this will bootstrap the version we have vendored in the repository)
 - Python 2 - this is required to build native modules, and I don't believe Python 3 is supported

I'd like to work with some of the people in this thread as part of our next Git upgrade to ensure we're still in a good place - please let me know if you're able to build and test Desktop locally on Windows.

**Comment by mgenovese** [comment] 2019-03-12 13:15
I verified that my core.longpaths is set to true in my git config.

**Comment by shiftkey** [comment] 2019-03-12 13:16
@mgenovese does the new beta build resolve your issue?

**Comment by mgenovese** [comment] 2019-03-12 13:44
The beta appears to be working for me too.  I am able to do most of the tasks mentioned in @Thomas-Fisher's post.  Will test the rest shortly and will update if any issues are found.

**Comment by JamieKeeling** [comment] 2019-03-12 13:46
With the beta now installed I no longer encounter the issue reported.

**Comment by gregorio4g** [comment] 2019-03-12 13:53
GitHub Desktop works now with 1.6.4-beta1 version. Thank you

**Comment by lewisarmistead** [comment] 2019-03-12 14:27
I also am no longer seeing the original issues when running the 1.6.4 beta. Thanks @shiftkey @nerdneha and @Thomas-Fisher for the help getting this resolved

**Comment by mark-jensen** [comment] 2019-03-12 14:34
All set, working normally for me.

**Comment by Thomas-Fisher** [comment] 2019-03-12 14:36
@shiftkey as i mentioned above with the installer 1.6.4-beta1 version works fine. i have attempted to clone and build [https://github.com/desktop/desktop/tree/release-1.6.4-beta1](https://github.com/desktop/desktop/tree/release-1.6.4-beta1) <-- is that the correct one?. I am getting Errors when i attempt to build it

![image](https://user-images.githubusercontent.com/6746343/54206719-c6c20080-44d0-11e9-8cce-ca9eca6b14e5.png)
( i have both python 3.7.2 and 2.7.13 installed )
When ever i try doing yarn inside the check out folder, it says installing v1.13.0 and then i get errors. its most likely a pebcak issue as i have not used yarn before

![image](https://user-images.githubusercontent.com/6746343/54208611-25d54480-44d4-11e9-823c-9118346fba32.png)

**Comment by shiftkey** [comment] 2019-03-12 14:50
@Thomas-Fisher it looks like it's finding Python 3 which is not compatible:

<img width="697" src="https://user-images.githubusercontent.com/359239/54209439-88224b00-44bc-11e9-8806-d521febab0e0.png">

If you're able to ensure that only Python 2  is on your PATH, you should be able to build the project.

**Comment by Thomas-Fisher** [comment] 2019-03-12 15:15
@shiftkey Ok excellent it is all working now i can use the locally built dev app. I incorrectly assumed when i installed python 2 it would add it to the path on its own and thought the issue was to do with yarn installing 1.13.0

**Comment by shiftkey** [comment] 2019-03-12 15:18
I'm going to close this out because `1.6.4` is now out on production, which should resolve this issue. 

Please open a fresh issue and fill out the template if this is still occurring for you.

**Closed by shiftkey** 2019-03-12 15:18 UTC
Labels: investigation-needed

**Comment by JohnAllenJr** [comment] 2019-05-09 13:08
If it's on your side, I suggest using long path tool.
Helped me to save my project.

**Comment by ArnoInen** [comment] 2019-08-23 12:33
I am simple man. I just use sourcetree; github client is made of children's tears and frustration
