### ISSUE TITLE
Github desktop tried to rebase with my changes still present and when i aborted all my code was gone.

### ISSUE THREAD

**Issue by nithin-murali-arch** [desktop/desktop#14965] opened 2022-07-13 10:02 UTC
### The problem

Github desktop tried to rebase with my changes still present and when I aborted all my code was gone.

### Release version

Version 3.0.3 (x64)

### Operating system

MacOS Monterey

### Steps to reproduce the behavior

Happened randomly.

### Log files

2022-07-13T09:57:21.499Z - info: [ui] [continueRebase] continuing rebase for 14ebd26bd7ea80e8b14908b79bbc58c06afe6daf
2022-07-13T09:57:22.845Z - info: [ui] [continueRebase] completed rebase - got ConflictsEncountered and on tip 8a9c10bfb194f04d7152d51c509177bd7182c6ac - kind Detached
2022-07-13T09:57:30.478Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 12.232s)
2022-07-13T09:57:33.178Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.312s)
2022-07-13T09:57:33.193Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 30.1s of which 89288.4s paused, total 89318.6s
2022-07-13T09:57:58.559Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.270s)
2022-07-13T09:58:01.728Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.114s)
2022-07-13T09:58:22.322Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.246s)
2022-07-13T09:58:28.259Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 5.472s)
2022-07-13T09:58:28.371Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 15.9s of which 17.3s paused, total 33.1s
2022-07-13T09:58:38.061Z - info: [ui] No submodules found. Skipping "git submodule status"
2022-07-13T09:59:16.824Z - info: [ui] [Timing] Action 'checkout branch from list' for 'pwa' took 1.528s

**Comment by tidy-dev** [comment] 2022-07-13 10:49
@nithin-murali-arch Usually when you have active changes, the rebase flow will ask you to stash them. Just curious if you have a stash. You would see a stash bar at the bottom of changes list above the commit message entry form. Do you have stash there?

You said it happens randomly -> curious how you invoked the rebase?

**Comment by nithin-murali-arch** [comment] 2022-07-13 12:31
There was no stash. I didn't run a rebase, it so happened that I went to the Github desktop window and it said that conflicts were resolved and showed a rebase button. I do recall that I ran a rebase last night, however I resolved the conflict on vscode. I don't think I came back to Github desktop after that.

**Comment by tidy-dev** [comment] 2022-07-13 12:40
It sound like GitHub Desktop detected an ongoing rebase. 

For my understanding:
1. You ran a rebase from Desktop
2. Went to vscode to resolve the conflicts 
3. Made other changes so you expected those changes to be in the changes list
4. Came back to Desktop and Desktop recognized the rebase conflicts were resolved.
5. Hit continue rebase
6. Your changes were gone.

^ Based on this:
After 2, did you attempt to complete the rebase in any other software -> command line or vscode plug in?
Can you see if your changes are actually still in the code base and were committed as part of the conflict resolution/rebase process?

**Comment by nithin-murali-arch** [comment] 2022-07-13 13:10
Made changes again after the rebase completed on command line, those changes are gone now.

**Comment by nithin-murali-arch** [comment] 2022-07-13 18:19
Yes used cli in vscode to complete rebase

**Comment by tidy-dev** [comment] 2022-07-22 10:13
Sorry for taking so long to get back to this. I was unable to reproduce.

I tried doing:
1. Creating a conflict between branch A and branch B.
2. Initiated a rebase branch A with Branch B in GitHub Desktop
3. Opened the conflict is VsCode - resolved the conflict
4. Finished the rebase in terminal
5. Added new changes in VsCode.
6. Opened Desktop.

Desktop worked as expected:
- no continue rebase
- showed changes made in changes list

Unfortunately, without being able to reproduce, we are unable to address this issue. I am going to close it, but if you can provide anymore context/find a way to reproduce it. I will gladly reopen.

**Closed as not planned by tidy-dev** 2022-07-22 10:13 UTC
