### ISSUE TITLE
Unable to perform move, resize, restore, mini/maxamize from Windows Taskbar

### ISSUE THREAD

**Issue by brandongohwh** [desktop/desktop#3856] opened 2018-01-25 15:03 UTC
### Description

Unable to perform move, resize, restore, mini/maxamize from Windows Taskbar (i.e. no context menu opens when right-clicking the Github Desktop window from the Windows Toolbar), which is a problem when I'm using a multi-screen set-up on my Desktop and need to remote desktop from a laptop. Of course, this happens when Github Desktop is not on the main screen (in a multi-screen environment).

### Version

**GitHub Desktop version:** 1.0.12

**OS version:** Windows 10 Fall Creators Update Build 16299 (10.0.16299.192)

### Steps to Reproduce

1. Open Github Desktop
2. Mouse over to Windows Toolbar for window preview
3. Right-click and the window appears and disappears (if it is on the main screen) or it doesn't even come into view at all if it is on the secondary screen and the system is being accessed from remote desktop.

**Expected behavior:** Context Menu must open

**Actual behavior:** Window appears and disappears (if it is on the main screen) or it doesn't even come into view at all if it is on the secondary screen and the system is being accessed from remote desktop.

**Reproduces how often:** 100%

### Logs

(As attached, although it doesn't seem to be of much help as the main features of Github work fine)
[2018-01-25.desktop.production.log](https://github.com/desktop/desktop/files/1664422/2018-01-25.desktop.production.log)

#### Additional Information

None to my knowledge since all the other applications on the system work fine.

**Comment by iAmWillShepherd** [comment] 2018-01-26 16:17
Any one on @desktop/core  have a multi-monitor setup to reproduce this on?

**Comment by shiftkey** [comment] 2018-01-28 06:58
@brandongohwh @iAmWillShepherd this feels very similar to #2311, and I think this should be folded up into that.

**Comment by iAmWillShepherd** [comment] 2018-01-31 20:38
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2311. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-01-31 20:38 UTC
Labels: needs-reproduction
