### ISSUE TITLE
Publishing private repository without premium results in incorrect error.

### ISSUE THREAD

**Issue by Chandler-Davidson** [desktop/desktop#2359] opened 2017-07-29 01:19 UTC
### Description

When publishing a new repository,  if "Keep this code private" is selected and the user does not have Github premium an error appears saying "Unable to publish repository. Please check if you have an internet connection and try again." Instead, it should give a notice that publishing private repositories is only for premium members.

### Version

**GitHub Desktop version:** 0.7.0

**OS version:** 10.12.3

### Steps to Reproduce

1. Create a new repository
2. Select "Publish Repository"
3. Select "Keep this code private"
4. Select "Publish Repository"

**Expected behavior:** An error appears that says "Private repositories are for restricted to Github Premium."

**Actual behavior:** An error appears that says "Unable to publish repository. Please check if you have an internet connection and try again."

**Reproduces how often:** 100%

**Comment by joshaber** [comment] 2017-07-31 14:51
Thanks @Chandler-Davidson! This is a duplicate of https://github.com/desktop/desktop/issues/2279, fixed in https://github.com/desktop/desktop/pull/2281. It'll be out in the next update!

**Closed by joshaber** 2017-07-31 14:51 UTC
