### ISSUE TITLE
Window outside boundary

### ISSUE THREAD

**Issue by sarden11037** [desktop/desktop#3517] opened 2017-12-06 17:08 UTC
### Description

My github desktop version was working fine they I switched to dual monitors and it seems that the application is situation outside the screen boundary. As a result, I can't access the application even after resetting it. I upgraded to the new version release the was released December 05, 2017 but that did nothing. I found another issue report, #3342 , that was having the same issue. I can confirm as per that report that removing the windows-state.json file has resolved the issue. Before that , switching between single screen and dual monitors did not resolve the issue either. 

GitHub Desktop version: [1.0.10]
OS:
Microsoft Windows [Version 10.0.16299.64]

Expected behavior:
GitHubDesktop window shows up on the screen

Actual behavior:

After selecting icon, the application moves outside the screen boundaries. 

Reproduces how often:
every time

Solution:
Remove window-state.json
from \AppData\Roaming\GitHub Desktop

**Comment by iAmWillShepherd** [comment] 2017-12-06 17:43
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3342. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2017-12-06 17:43 UTC
