### ISSUE TITLE
Open in Terminal opens a different directoy and not the repository directory

### ISSUE THREAD

**Issue by mfsbo** [desktop/desktop#16102] opened 2023-02-09 18:06 UTC
### The problem

On Windows machine, after the upgrade to Version 3.1.6 (x64) following behaviour started.
Open a repo and click on Repository menu then choose Open in Windows Terminal. 
Previous version behaviour is that it opened Terminal with current directory as Repository root directoy.
Current version opens System32 directory instead of root directory

### Release version

3.1.6

### Operating system

Windows 10 x64

### Steps to reproduce the behavior

1. Open a Repository
2. Select Repository Menu
3. Select "Open in Windows Terminal" (Windows Terminal Default need to be setup to run in Administrator Mode)
4. Expect it to open respository directory in Windows Terminal however it will open System32 directory.

I have tried other terminals and 
- Bash worked as expected
- Command Prompt Worked as expected
- Powershell worked as expected
- Powershell core worked as expected

### Log files

[2023-02-09.desktop.production.log](https://github.com/desktop/desktop/files/10700129/2023-02-09.desktop.production.log)

### Additional context

I have tested with Windows Terminla Setup without Administrator mode and it works as expected. 
![image](https://user-images.githubusercontent.com/50488401/217899180-152df808-efa5-4b21-918f-02a5eb8c9218.png)
Under above settings it works as expected
Powershell version is 7.3.2

**Comment by steveward** [comment] 2023-02-09 21:38
Thanks for the report @mfsbo, I was able to reproduce this as well when enabling Administrator mode. I'll mark this as a bug.

**Comment by tsvetilian-ty** [comment] 2023-02-10 13:49
That is an interesting case, but I'm not sure if it's a bug 🤔 I think the issue comes from the access elevation when spawning the terminal process and its expected security behavior. 

### My reasoning:
> When `Run this profile as Administrator` is enabled
1. You start GitHub Desktop with your current user
2. You click "Open in Windows Terminal"
3. GitHub Desktop tries to spawn a terminal process as the current user
4. Windows triggers "UAC" to elevate the access to Administrator
5. After the elevation, the terminal defaults to `system32` since it's the default startup directory for elevated session

If you try to run GitHub Desktop as Administrator, the "Open in Windows Terminal" option will work as expected since GitHub Desktop uses the same privileges as the terminal, and the path will be correct.

**Comment by steveward** [comment] 2023-02-10 14:26
Thanks @tsvetilian-ty, it does look like this is the expected behavior based on docs I found around this as well. 

@mfsbo since this behavior is expected to prevent malicious software from being run with admin privileges, I'm going to close this issue out as it's likely not something we would be able to work around. Sorry that I don't have better news.

**Closed as completed by steveward** 2023-02-10 14:26 UTC
Labels: windows

**Comment by mfsbo** [comment] 2023-02-10 15:21
Thanks a lot. I have setup Github to run in elevated mode via the github desktop properties
![image](https://user-images.githubusercontent.com/50488401/218128509-207cd5cf-cac7-4f88-97f6-aed023fe59e8.png)
and that does solve the issue. Both Github and Terminal now have same level of access.
