### ISSUE TITLE
Github desktop does not start without internet connection

### ISSUE THREAD

**Issue by DeepSOIC** [desktop/desktop#6762] opened 2019-02-02 20:04 UTC
## Description
the title says it all. Can't start Github desktop when working offline. It works if I start with internet, and disconnect afterwards.

## Version
* GitHub Desktop: 1.6.1
* Operating system: Microsoft Windows [Version 10.0.17763.253], Russian

## Steps to Reproduce
1. disconnect from the internet
2. launch GitHub desktop

### Expected Behavior
GitHub should start, and I expect to be able to commit to my repos.

### Actual Behavior
nothing. GitHub process appears for a second in task manager, and vanishes. No splash screen, no window.

### Logs
[2019-02-02.desktop.production.log](https://github.com/desktop/desktop/files/2824803/2019-02-02.desktop.production.log)

**Comment by tierninho** [comment] 2019-02-04 18:36
@DeepSOIC Thank you for filing this. 

I tried to reproduce this but Desktop works fine when offline. When looking at your logs there was an error when Desktop attempted to check for updates. I suspect it is the culprit, however you are on the latest build. @desktop/engineering any thoughts?

```
2019-02-02T08:08:38.799Z - error: [ui] Error checking for updates
Error: Command failed: 4294967295
System.AggregateException: ��������� ���� ��� ��������� ������. ---> System.Net.WebException: ���������� ��������� ��������� ���: 'central.github.com'
   � System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   � System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   � System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   � Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()
   --- ����� ����������� ����������� ����� ���������� ---
   � System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   � System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   � System.Threading.Tasks.Task`1.get_Result()
   � Squirrel.Update.Program.executeCommandLine(String[] args)
   � Squirrel.Update.Program.main(String[] args)
   � Squirrel.Update.Program.Main(String[] args)
---> (���������� ���������� #0) System.Net.WebException: ���������� ��������� ��������� ���: 'central.github.com'
   � System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   � System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   � System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Utility.<LogIfThrows>d__38`1.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   � Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- ����� ����������� ����� �� ����������� ������������, ��� �������� ���������� ---
   � System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   � System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   � Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---
    at AutoUpdater.emitError (C:\Users\EMB\AppData\Local\GitHubDesktop\app-1.6.1\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:70:24)
    at squirrelUpdate.checkForUpdate (C:
```

**Comment by DeepSOIC** [comment] 2019-02-05 13:57
I just tried to clear up the log and run GitHub Desktop with no internet connection. No log files appeared. So the attached logs may have no relevance to the problem.

**Comment by krzysdz** [comment] 2019-02-14 08:06
When starting GitHub Desktop from command line using `github` command (`%localappdata%\GitHubDesktop\bin\github` or `%localappdata%\GitHubDesktop\bin\github.bat`) while disconnected from internet a following error message is logged:
```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

**Comment by steveward** [comment] 2019-02-15 16:39
@krzysdz thanks for the report. I wasn't able to reproduce this issue. Can you share the log file so we can see if there is any more information there?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by krzysdz** [comment] 2019-02-15 23:06
I tried to reproduce the issue today so that my logs wouldn't be full of other information. I tried to start GitHub Desktop both from desktop shortcut and PowerShell.

In both cases there was no window showing up and no logs were generated in `%appdata%\GitHub Desktop\logs` with today's date. The only message was the one that I got in PowerShell (the same as in my previous message).

After experimenting a bit I noticed that **the error occurs only if completely disconnected** from any network. When I connected to my phone's WiFi hotspot, but **without internet connection** (mobile data transfer was turned off) GitHub Desktop **has successfully started** (this time logging information about an error while checking for updates).

I tried also to reproduce it on my main PC, but as I have Hyper-V enabled I'm always connected to a Hyper-V Virtual Ethernet Adapter (vEthernet) and a virtual network and GitHub Desktop launches without a problem. When I finally managed to remove this additional network and disabled other connections it was still working, so I can't tell what has to be done in order to succesfully reproduce it on other computers. It may be also worth noting that the issue exists on laptop, but my main PC is a desktop.

So if you want to reproduce the error you have to disconnect the device from all networks, not just eg. disable internet connection on your router/switch, but in some cases it still may not be enough to reproduce this behaviour.

**Comment by shiftkey** [comment] 2019-02-15 23:39
:wave: I haven't had a chance to read into the issue but I just wanted to call out some extra context based on that stack trace:

```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
```

[`dns.js`](https://github.com/nodejs/node/blob/v8.9.0/lib/dns.js) is part of the Node core, and this is a layer below the code that Desktop manages. There's some interesting clues in here in terms of the stack trace and source maps - it looks like this code is the behaviour causing you problems: 

https://github.com/nodejs/node/blob/f76ce0a75641991bfc235775a4747c978e0e281b/lib/dns.js#L244-L252

**Comment by krzysdz** [comment] 2019-02-15 23:52
@shiftkey After quick Google search it looks more like an Electron issue (electron/electron#6437) that also affected older versions of VS Code: Microsoft/vscode#7570, https://github.com/Microsoft/vscode/issues/59634#issuecomment-432942761

It could be probably fixed with an Electron update to 3.x (based on comments in these threads), which as I can see is scheduled for GitHub Desktop 1.6.3.

**Comment by krzysdz** [comment] 2019-02-16 00:13
I've just tested 1.6.3-beta1 and it works offline. @DeepSOIC if you need GitHub Desktop to work offline try updating it to the newest beta version (or enable local loopback on Windows).

**Comment by shiftkey** [comment] 2019-02-19 13:59
Moving this into the next milestone now that we're planning to ship Electron 3 in the next update.
Closing this out because there's no additional work to do. Thanks for the help troubleshooting @krzysdz!

**Closed by shiftkey** 2019-02-19 13:59 UTC
Labels: electron
