### ISSUE TITLE
Keyboard shortcut for focusing Changes and History views

### ISSUE THREAD

**Issue by astoilkov** [desktop/desktop#9496] opened 2020-04-10 07:32 UTC
### Describe the feature or problem you’d like to solve

While my focus is on the commit message (⌘G) I want to return focus to the Changes or History view but I can't.

### Proposed solution

My proposal is to make ⌘1 and ⌘2 focus on the views after showing them.

#### How will it benefit Desktop and its users?
Github Desktop is the simplest and quickest git client for the most common git tasks. Changing the focus from the commit message to the Changes and History views is a very common task. The new behavior will make a very common task even quicker. This is why I believe this feature is a step towards GitHub Desktop values.

**Comment by billygriffin** [comment] 2020-04-13 14:54
Hi @astoilkov, thanks for the issue! I just tried to reproduce this and it works exactly as you proposed. Here are the keyboard shortcuts in Desktop: https://help.github.com/en/desktop/getting-started-with-github-desktop/keyboard-shortcuts-in-github-desktop

Is that not happening for you?

**Comment by astoilkov** [comment] 2020-04-13 15:02
Sorry, maybe I didn't the issue very well. Let me describe what's happening and what I think it makes more sense to happen.

What I want to happen:
- Hit ⌘G to focus commit message
- Hit ⌘1 to focus Changes view
- Use arrow keys to move around Changes view

What is actually happening:
- Hit ⌘G to focus commit message
- Hit ⌘1 to focus Changes view (focus is still on the commit message)
- Using arrow keys moves the cursor in the commit message input not inside the Changes view

**Comment by billygriffin** [comment] 2020-04-13 15:06
@astoilkov Oh interesting, that does feel like a bug to me, thanks for sharing the more detailed repro steps!

**Comment by tierninho** [comment] 2020-04-13 18:13
I tested this by omitting the `⌘G` step to see what the experience is when using just `⌘1` or `⌘2`. **By default**, it looks like we do not allow the user to use the arrow keys to move selected items in the Changes or History tabs. The only way to get there is by clicking with the mouse or tabbing over to the list and then using arrows to reach the desired item.

It sounds like the desired outcome from using `⌘1` or `⌘2` is that the selected item should be actively highlighted blue, thus allowing the user to use the arrow keys immediately. 

If the cursor is already in the commit area and the user selects `⌘1`, currently the only difference is the location from where the tabbing begins. All other functionality remains intact. 


_tested on`2.4.1-beta1`, OSX_

**Comment by billygriffin** [comment] 2020-04-13 18:51
@tierninho Good call, thanks for clarifying in more detail! So I guess the question may be whether it's desirable to allow you to arrow until you've tabbed *into* the element. @astoilkov To be honest, now that I know that you can tab into the element immediately after using Cmd-1 or Cmd-2 and then arrow around, I'm less convinced that this should be changed. Thoughts?

**Comment by astoilkov** [comment] 2020-04-13 19:13
What happens very often is I focus the input and then want to go back to the Changes view to include/exclude a file. Let me give a few points where I see problems with the current behavior:
- Hit ⌘G, you need to hit Tab eight times in order to focus the Changes View
- Hit ⌘G and Shift+Tab (a hard shortcut for your hand) and all items are selected you need an extra arrow key press in order to start selecting items. Note that Shitft+Tab works only if your focus is on the commit message which means this shortcut works conditionally (not always)
- Hit ⌘2 then ⌘1, you need to hit Tab twice (works regardless of where the focus is but is complicated)

What I said in the first comment is that GitHub desktop power is doing common tasks really fast and easy. I believe a fast way to focus Changes and History view without using the mouse or multiple keyboard presses will benefit users like me which like to do things as fast as possible.

Let's take the GitHub site for example. There are a lot of shortcuts which move the focus so you can do stuff easily:
- `/` focuses the search bar
- `L` focuses the labels and lets you assign a label
- `A` does the same for Assignees, you have `P` for projects, `M` for milestones

@billygriffin What do you think? I can explain in even bigger details why I believe this change is beneficial if you want me to.

**Comment by billygriffin** [comment] 2020-04-14 16:26
Makes sense to me @astoilkov, I initially thought that if the commit message was focused and then you hit Cmd-1, you could simply tab into the files to use your arrow keys to go through them, but as you point out that doesn't appear to be the case. Thanks for explanation.

**Comment by astoilkov** [comment] 2020-04-14 16:29
Great! I am looking forward to increasing my productivity. Thanks!

**Comment by steveward** [comment] 2021-05-20 19:58
Feedback from #12247:

> Describe the feature or problem you’d like to solve
> When using the Mac desktop app I can use the up and down arrows to move between commits, but once on a commit I'd like to navigate to the files column and move up and down the files. The obvious action is to use the right arrow to move into the files column where it should then select the top file from where I can use the down arrow to move through the files. This is how the Mac's finder operates when in column view.
> 
> Proposed solution
> Update the UI so that the right arrow moves from the active commit into the files column and selects the first file.
> 
> Even better would be for the right arrow to then step into the code pane.
> 
> Obviously the left arrow would step left.
> 
> Additional context

**Comment by niik** [comment] 2023-04-13 07:21
> Makes sense to me @astoilkov, I initially thought that if the commit message was focused and then you hit Cmd-1, you could simply tab into the files to use your arrow keys to go through them, but as you point out that doesn't appear to be the case. Thanks for explanation.

I believe that as of https://github.com/desktop/desktop/pull/16463 you should be able to hit <kbd>Cmd+1</kbd> and then hit tab to reach the file list so I'm going to tentatively close this issue out.

**Closed by niik** 2023-04-13 07:21 UTC
Labels: bug, priority-3
