### ISSUE TITLE
It never opens command prompt and keep showing bellow error massage - My OS win 8.1

### ISSUE THREAD

**Issue by kasra-appscore** [desktop/desktop#2235] opened 2017-07-12 23:37 UTC
Error: spawn where ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Version: 0.6.2
OS: Windows 6.3.9600

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by iAmWillShepherd** [comment] 2017-07-13 15:08
Closing this issue since it is a duplicate of #2178.

**Closed by iAmWillShepherd** 2017-07-13 15:08 UTC
Labels: more-information-needed

**Comment by niik** [comment] 2017-07-13 15:13
@kasra-appscore Hey, thanks for opening this! We're trying really hard to reproduce and fix this so it would be immensely helpful to us if you could answer the questions I put down in https://github.com/desktop/desktop/issues/2178#issuecomment-312947823.
