### ISSUE TITLE
Can't connect to my local repo: update: 1.6.2 -> 1.6.3

### ISSUE THREAD

**Issue by mateuszromanowski** [desktop/desktop#7038] opened 2019-03-08 06:57 UTC
## Description
After upgrade from 1.6.2 version to 1.6.3 can't connect to my local repo (at NAS drive).
Application blinking and can't do anything.

## Version

* GitHub Desktop: 1.6.3

* Operating system:
Windows 7: Microsoft Windows [Version 6.1.7601]

## Steps to Reproduce
1. Version 1.6.2
2. Create local repo
3. Update to 1.6.3
4. Can't connect to local repo - application blinking

### Expected Behavior
Stopping blinking, and connect to repo

### Actual Behavior
Blinking. Can't connect to repo.

**Comment by Gedd18** [comment] 2019-03-08 13:35
Exactly the same problem on windows 10. 
Repos were from github.com on my HD since many time.
After have updated **G**ithub**D**esktop, unable to connect any repos.
Then after have removed repos from GD, it was unable to add local repo.

**Comment by margarethannum** [comment] 2019-03-08 15:44
I'm having the same issue, can't connect to any of my repos that already were on my desktop. Tried removing and re-cloning them and still having the blinking with error message 'Can't find "folder-name"'

Git updated to 1.6.3
Windows 7

Here's an example from the log file (it's this x200 as it tries over and over to find the repos): 

2019-03-08T15:26:20.075Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.052s)
2019-03-08T15:26:20.272Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.421s)
2019-03-08T15:26:21.391Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.067s)

**Comment by steveward** [comment] 2019-03-08 18:34
@mateuszromanowski @Gedd18  @margarethannum thanks for the reports about this. Are you able to reproduce this issue when creating a new repository in GitHub Desktop, or is it only occurring with existing repositories? If possible a GIF or short video clip of the behavior you are seeing in the app would be helpful as well.

It would also be great if you could upload the log file from GitHub Desktop -- that may give some more information about this issue. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please send over a log file as an attachment from a day where you experienced the issue.

**Comment by margarethannum** [comment] 2019-03-08 20:38
@steveward when creating a new repository on GitHub Desktop, I get an error message: "Unable to create the new repository because there are too many files in this directory" (Though I do not think there are too many files)

The "blinking" effect is coming from the GitHub Desktop repeatedly trying to refresh the open repository, failing, and then opening the fullscreen message "Can't find "name-of-repository"" quickly before going back to the "Refreshing repository" view. See below for screenshots of what it toggles between every second or two:

![image](https://user-images.githubusercontent.com/29231686/54053501-75a2cb80-41b5-11e9-9946-8a456a6c43ae.png)

![image](https://user-images.githubusercontent.com/29231686/54053510-7d627000-41b5-11e9-80eb-f23db62f80aa.png)

Log from today: 
[2019-03-08.desktop.production.log](https://github.com/desktop/desktop/files/2947300/2019-03-08.desktop.production.log)

**Comment by margarethannum** [comment] 2019-03-08 21:03
Also it may go without saying but the repository above does exist at the location specified! And the blinking/"Cant find" happens for every repository I've tried to open in GitHub Desktop today, not just this one; for repos I have on both GitHub Enterprise and GitHub.com.

**Comment by collinberke** [comment] 2019-03-08 22:33
I'm experiencing the same issue. Working with Windows 7, 64bit on my machine. Saw the banner to update to a new version and clicked the link. Desktop app restarted and that's when the issue started to occur, flickering from current repository to Cant find "[Repository Name]". The behavior is like that seen from issue #6670.  

Here is the most recent log file for the day the issue started to occur (03/08/2019): 
[2019-03-08.desktop.production.log](https://github.com/desktop/desktop/files/2947675/2019-03-08.desktop.production.log)
 . 

Attempted the work around referenced here: https://github.com/desktop/desktop/issues/6670#issuecomment-456071586 from issue #6670. No luck.

**Comment by tierninho** [comment] 2019-03-09 01:48
I noticed the avatar in this [comment](https://github.com/desktop/desktop/issues/7038#issuecomment-471068628) is the default hubot, which could be a clue as to why this is happening 🤔

**Comment by a-tambov** [comment] 2019-03-10 21:50
Can't connect to local repos and cannot clone from GitHub after update from 1.6.2 -> 1.6.3 
Windows 10, 64 bit.

**Comment by Gedd18** [comment] 2019-03-10 22:00
Dialog box with "unknown error" at startup
The same error when creating a new repos

**Comment by mateuszromanowski** [comment] 2019-03-11 07:10
@steveward Log and gif in attachment
[2019-03-08.desktop.production.log](https://github.com/desktop/desktop/files/2951003/2019-03-08.desktop.production.log)
![github_dektop](https://user-images.githubusercontent.com/11481494/54106003-19b68d80-43d5-11e9-92ea-7f29402cb932.gif)

**Comment by steveward** [comment] 2019-03-11 17:28
Just to update everyone, we've been looking into this in depth and we're continuing to try to diagnose what's causing these issues. We'll keep you updated as we make progress and we hope to have a release as soon as possible. To help us get it fixed more quickly, we would love your help. 

There is a specific command we would like for you to run using GitHub Desktop's bundled `git.exe` to provide us with some more information about what may be causing this error. To do this you will need to use the Command Prompt, PowerShell, or Git Bash to enter the path to the specific `git.exe`. Here is what the specific path looks like:

`%LocalAppData%\GitHubDesktop\app-1.6.3\resources\app\git\cmd\git.exe`

The full command you will want to run is this:

`%LocalAppData%\GitHubDesktop\app-1.6.3\resources\app\git\cmd\git.exe --no-optional-locks status --untracked-files=all --branch --porcelain=2`

Here are the steps for reference:

1. Open the repository in GitHub Desktop
2. Go to the menu and select `Repository` > `Open in <command_line_application>` (if you do not have Git installed you can use the command prompt and `cd` to your repository's directory)
2. Run the command `%LocalAppData%\GitHubDesktop\app-1.6.3\resources\app\git\cmd\git.exe --no-optional-locks status --untracked-files=all --branch --porcelain=2`
3. Share the output of that command in a reply in this issue

**Comment by steveward** [comment] 2019-03-11 17:59
I originally mentioned that the command was possible in Git Bash or PowerShell along with CMD, but that was slightly incorrect. If you are using Git Bash or PowerShell you will need to use the **full path** rather than the `%LocalAppData%` variable, i.e.:

`C:\Users\<Your_User\AppData\Local\GitHubDesktop`

**Comment by Gedd18** [comment] 2019-03-11 20:57
Error message : 
The application can't start correctly (0xc0000017)

**Comment by steveward** [comment] 2019-03-11 21:19
Thanks for helping us troubleshoot this @Gedd18. That error seems to indicate a possibly memory issue on your machine. Did this happen when you attempted to run the command I gave inside of command prompt (cmd.exe)?

**Comment by Gedd18** [comment] 2019-03-11 21:26
absolutly !

**Comment by mateuszromanowski** [comment] 2019-03-12 06:29
@steveward I have following messages:

`.gitattributes: Function not implemented`
`(..files in repo..): Function not implemented`
`fatal: cannot use .git/info/exclude as an exclude file`


Of course .git folder and .gitattributes file exist

**Comment by shiftkey** [comment] 2019-03-12 12:46
We have published `1.6.4-beta1` just now which reverts the embedded Git in Desktop from `2.20.1.windows.1` to `2.19.2.windows.1`, which we believe will address this issue.

In the process of investigating we've identified at least two known issues with `2.20.1.windows.1` that have since been fixed in Git for Windows:

 - https://github.com/git-for-windows/git/issues/1989
 - https://github.com/git-for-windows/git/issues/2075

Because of the complexity of the setup to trigger these issues **we are looking for any Windows users to help us confirm this problem has been resolved, which requires installing [the latest beta](https://github.com/desktop/desktop#beta-channel) and testing their problem repositories again**.

We plan to make this available today to everyone, but it would be great to know in advance that these specific issues are addressed.

Thanks again for working with us to get this resolved!

**Comment by mateuszromanowski** [comment] 2019-03-12 14:02
@steveward 1.6.4-beta1 resolve this problem.
With that version all it's working fine.
(sorry for my bad English)

**Comment by collinberke** [comment] 2019-03-12 14:18
I downloaded the `1.6.4-beta1`. Everything seems to be working on my machine, @steveward @shiftkey. I'm running Windows 7, 64-bit.  It seems to have resolved the 
I referenced in my previous comment: https://github.com/desktop/desktop/issues/7038#issuecomment-471099482.

**Comment by shiftkey** [comment] 2019-03-12 15:16
I'm going to close this out because `1.6.4` is now out on production, which should resolve this issue. 

Please open a fresh issue and fill out the template if this is still occurring for you.

**Closed by shiftkey** 2019-03-12 15:16 UTC
Labels: investigation-needed, more-information-needed
