### ISSUE TITLE
System window animations no longer play on Windows

### ISSUE THREAD

**Issue by DanielRouxSA** [desktop/desktop#14037] opened 2022-03-01 14:30 UTC
### Describe the bug
Since one of the recent application updates, the system windows animations for opening, closing, maximizing, minimizing and restoring the application window no longer play on Windows.

### Version & OS

- GitHub Desktop version 2.9.10 (x64)
- Tested on the following Windows versions:
  - Windows 10 20H2
  - Windows 11 21H2

### Steps to reproduce the behavior

1. Perform any of the following actions on the application window:
   - Open
   - Close
   - Maximize
   - Minimize
   - Restore

### Expected behavior

The system window animation associated with the performed action is applied to the application window.

### Actual behavior

No animation is applied to the application's main window; the window instantly appears, disappears or snaps to its new position.

### Screenshots

No screenshots are applicable since the issue can only be observed in motion.

### Logs

[2022-03-01.desktop.production.log](https://github.com/desktop/desktop/files/8162197/2022-03-01.desktop.production.log)

### Additional context

I suspect that the update that introduced this issue may have been version 2.9.9, with specific reference to https://github.com/desktop/desktop/pull/13930; this appears to be a manifestation of https://github.com/electron/electron/issues/32899 and/or https://github.com/electron/electron/issues/32993.

**Comment by sergiou87** [comment] 2022-03-01 15:40
Ouch! That sucks 😞  I recently disabled animations on my Windows machine for performance reasons, so I didn't even notice that 🤦‍♂️ 

Thanks for your report and for going through Electron's issues to find the reason for this!! ❤️

**Comment by DanielRouxSA** [comment] 2022-04-05 07:46
It looks like the Electron issue has been found and fixed, as per electron/electron/pull/33599. I am however uncertain how their release process works, so I don't know in which Electron version the fix will arrive.

**Comment by sergiou87** [comment] 2022-04-05 10:25
Yay! Thanks for reporting back again 🙇‍♂️ 

Just to clarify… we probably won't upgrade Electron right away after they release this fix, because upgrading Electron usually comes with additional uncertainty of new regressions (as this one that you reported when we upgraded to Electron 15).

**Comment by DanielRouxSA** [comment] 2022-04-05 13:50
Absolutely - framework upgrades aren't to be taken lightly. Additionally, this is merely a cosmetic issue, so I'd classify it as low priority anyway and not reason enough on its own to necessitate a framework upgrade.

**Comment by Levminer** [comment] 2022-04-22 14:03
Hi! 

This was fixed Electron 17.4.0. The app currently uses 17.0.1, so it should be just a small upgrade. I hope this gets fixed soon, its kind of annoying.

**Comment by sergiou87** [comment] 2022-09-06 15:20
Closing this as it will be finally fixed with the Electron upgrade to v19 in 3.0.8. See https://github.com/desktop/desktop/pull/15239

**Closed as completed by sergiou87** 2022-09-06 15:20 UTC
Labels: bug, windows, electron, priority-2

**Comment by LadyS82** [comment] 2022-12-21 14:00
> ### Describe the bug
> Since one of the recent application updates, the system windows animations for opening, closing, maximizing, minimizing and restoring the application window no longer play on Windows.
> 
> ### Version & OS
> * GitHub Desktop version 2.9.10 (x64)
> * Tested on the following Windows versions:
>   
>   * Windows 10 20H2
>   * Windows 11 21H2
> 
> ### Steps to reproduce the behavior
> 1. Perform any of the following actions on the application window:
>    
>    * Open
>    * Close
>    * Maximize
>    * Minimize
>    * Restore
> 
> ### Expected behavior
> The system window animation associated with the performed action is applied to the application window.
> 
> ### Actual behavior
> No animation is applied to the application's main window; the window instantly appears, disappears or snaps to its new position.
> 
> ### Screenshots
> No screenshots are applicable since the issue can only be observed in motion.
> 
> ### Logs
> [2022-03-01.desktop.production.log](https://github.com/desktop/desktop/files/8162197/2022-03-01.desktop.production.log)
> 
> ### Additional context
> I suspect that the update that introduced this issue may have been version 2.9.9, with specific reference to #13930; this appears to be a manifestation of [electron/electron#32899](https://github.com/electron/electron/issues/32899) and/or [electron/electron#32993](https://github.com/electron/electron/issues/32993).
