### ISSUE TITLE
Comparing a forked repo on GitHub open wrong repo

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3111] opened 2017-10-20 09:41 UTC
If you fork a repo, then attempt to `Branch > Compare on GitHub` or `Create Pull Request` on that repo, the browser will open the original repo instead. 

<img width="607" alt="screen shot 2017-10-20 at 10 34 24 am" src="https://user-images.githubusercontent.com/14828183/31814872-d13cbb56-b582-11e7-936a-277f91e33278.png">

forked repo
https://github.com/tierninho/map

original repo
https://github.com/ng2-ui/map

URLS that are opened are:
https://github.com/ng2-ui/map/compare/master...tierninho:test

<img width="1038" alt="screen shot 2017-10-20 at 10 39 54 am" src="https://user-images.githubusercontent.com/14828183/31814963-1d20c602-b583-11e7-849b-d03b12041f77.png">

https://github.com/ng2-ui/map/compare/master...tierninho:test?expand=1

<img width="1030" alt="screen shot 2017-10-20 at 10 40 01 am" src="https://user-images.githubusercontent.com/14828183/31814964-1d4609f8-b583-11e7-9745-9776b105b189.png">

tested in 1.0.5-beta0, mac

**Comment by joshaber** [comment] 2017-10-20 11:44
This is kinda dependent on https://github.com/desktop/desktop/issues/2364, as currently we don't know anything about a forked repository's parent.

**Comment by j-f1** [comment] 2017-10-20 11:58
I think the second behavior is correct — most of the time, you’re going to open a PR from the forked repo to the parent, since you don’t have access to the parent. For example, [this PR](https://github.com/desktop/desktop/pull/2372) is opened from https://github.com/j-f1/forked-desktop, and it wouldn’t have been useful for me to open it against the fork.

**Comment by shiftkey** [comment] 2017-11-08 02:27
> If you fork a repo, then attempt to `Branch > Compare on GitHub` or `Create Pull Request` on that repo, the browser will open the original repo instead.

I think this is by design, as all the redirection is occurring in the browser. It's not clear to me what the correct behaviour should be, because we should be encouraging forks to target the upstream repository.

As of `1.0.8` we open this URL for "Compare on GitHub" for a forked repository:

```
https://github.com/shiftkey/desktop/compare/new-branch
```

This is redirected so that it compares the branch on my fork to the upstream default branch:

```
https://github.com/desktop/desktop/compare/master...shiftkey:new-branch
```

Similarly, "Create Pull Request" will launch this URL for a branch on my fork:

```
https://github.com/shiftkey/desktop/pull/new/new-branch
```

Which is redirected to:

```
https://github.com/desktop/desktop/compare/master...shiftkey:new-branch?expand=1
```

**Comment by joshaber** [comment] 2017-11-14 16:42
Whoops, looks like our bot got a little too aggressive. Re-opening.

**Comment by shiftkey** [comment] 2017-11-20 04:20
Closing this out as the behaviour is all driven by GitHub The Website rather than the app - see [this comment](https://github.com/desktop/desktop/issues/3111#issuecomment-342689987) for the redirects  - and I think this is a pattern we want to encourage.

If anyone else has feelings on this, just shout and we can revisit.

**Closed by shiftkey** 2017-11-20 04:20 UTC
Labels: more-information-needed
