### ISSUE TITLE
Lots of files with "No content changes found"

### ISSUE THREAD

**Issue by Avallach7** [desktop/desktop#3987] opened 2018-02-10 14:38 UTC
### Description

Many files in my repository are shown as modified, but clicking on them makes right panel show "No content changes found". "git status" command does not show them as modified. There are indeed no content changes. I think it is because I copied them somewhere and pasted back, so that timestamp has changed. Git ignores file timestamps and this desktop client should as well. Currently displaying them seems to be pointless and there is no way to reset their state or hide them other than reverting them one by one.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** Windows 10.0.16299

### Steps to Reproduce

1. Change timestamp of some file in the repository
2. Open repository in GitHub Desktop

**Expected behavior:** File is not shown as modified 

**Actual behavior:** File is shown on GitHub Desktop as modified, but preview displays "No content changes found" 

**Reproduces how often:** 100%

**Comment by shiftkey** [comment] 2018-02-11 23:11
@Avallach7 could you share some additional details to help understand the issue:

 - a screenshot of Desktop when it's viewing the diff of a file that it considers to be modified
 - the output of this command when run in the repository

```
$ git status --porcelain=2
```

**Comment by shiftkey** [comment] 2018-02-26 03:40
Closing due to inactivity. @Avallach7 if you're able to provide the details requested above I'm happy to revisit this.

**Comment by Avallach7** [comment] 2018-03-01 22:19
Today it happened again:
![image](https://user-images.githubusercontent.com/3155782/36872539-dea368b8-1da5-11e8-8cdb-a28420324cdf.png)
Git Gui shows this:
![image](https://user-images.githubusercontent.com/3155782/36872659-41446102-1da6-11e8-9724-257d7a7a315b.png)
This time ``git status`` shows them as modified, but git diff shows nothing for them:
```
...
        modified:   resources/meshes/third-party/tomas-laulhe/WindowGothic.mtl
        modified:   resources/meshes/third-party/tomas-laulhe/WindowGothic.obj

no changes added to commit (use "git add" and/or "git commit -a")

Avallach@Polygon MINGW64 ~/home/Projects/kharynic (master)
$ git diff

Avallach@Polygon MINGW64 ~/home/Projects/kharynic (master)
```

**Comment by Avallach7** [comment] 2018-03-01 22:20
```
Avallach@Polygon MINGW64 ~/home/Projects/kharynic (master)
$ git status --porcelain=2
1 .M N... 100644 100644 100644 05600acd20b48bc318280395f865558eb6c00661 05600acd20b48bc318280395f865558eb6c00661 .gitignore
1 .M N... 100644 100644 100644 5c290fb26335be2d35f809f0716bc79213337927 5c290fb26335be2d35f809f0716bc79213337927 bin/Build/b14b32a200649d0650c1a6ff3db39cf4.js
1 .M N... 100644 100644 100644 9a9382ea45c1485e8d43dd97fab54b3c492c460d 9a9382ea45c1485e8d43dd97fab54b3c492c460d bin/Build/c4a04a575075c81f407623dbdb9f01d7.json
1 .M N... 100644 100644 100644 0a0ba3ff6d92dc98ffc2f8d4c92f7b1bd21e9b25 0a0ba3ff6d92dc98ffc2f8d4c92f7b1bd21e9b25 bin/index.html
1 .M N... 100644 100644 100644 1dc4a931ef7f7787041a3349db3d7078d8550dfe 1dc4a931ef7f7787041a3349db3d7078d8550dfe engine/Assets/scene.unity
1 .M N... 100644 100644 100644 6b6385a21b3d4c937aa43641c30e62d15bfad400 6b6385a21b3d4c937aa43641c30e62d15bfad400 engine/ProjectSettings/GraphicsSettings.asset
1 .M N... 100644 100644 100644 6eb935bf40a3e31693c12683925a1ffd06355759 6eb935bf40a3e31693c12683925a1ffd06355759 engine/ProjectSettings/ProjectSettings.asset
1 .M N... 100644 100644 100644 648bc434dd575aa347b99788da1e39a7b2a0733a 648bc434dd575aa347b99788da1e39a7b2a0733a engine/ProjectSettings/QualitySettings.asset
1 .M N... 100644 100644 100644 4d4e26f089f0978af224c76b101b26f8a236c79b 4d4e26f089f0978af224c76b101b26f8a236c79b resources/meshes/third-party/tomas-laulhe/Book.mtl
1 .M N... 100644 100644 100644 485ae85a2ab0a69154d8703e3a5574ac16a8761a 485ae85a2ab0a69154d8703e3a5574ac16a8761a resources/meshes/third-party/tomas-laulhe/Book.obj
1 .M N... 100644 100644 100644 f4e130d8246ff3fd7d8c228b4c13de1d5f5d6670 f4e130d8246ff3fd7d8c228b4c13de1d5f5d6670 resources/meshes/third-party/tomas-laulhe/Candelabrum.mtl
1 .M N... 100644 100644 100644 260e34fc758d2d459dc0743aea63767358ed4cbc 260e34fc758d2d459dc0743aea63767358ed4cbc resources/meshes/third-party/tomas-laulhe/Candelabrum.obj
1 .M N... 100644 100644 100644 118295420b94571ea566b1612985e678da7246e3 118295420b94571ea566b1612985e678da7246e3 resources/meshes/third-party/tomas-laulhe/Candelabrum_tall.mtl
1 .M N... 100644 100644 100644 e02eaf4414aa83434b664511857ee82b882de3a1 e02eaf4414aa83434b664511857ee82b882de3a1 resources/meshes/third-party/tomas-laulhe/Candelabrum_tall.obj
1 .M N... 100644 100644 100644 2d1659d6806f6fac46c252ffc3067914d3773bd6 2d1659d6806f6fac46c252ffc3067914d3773bd6 resources/meshes/third-party/tomas-laulhe/Candle.mtl
1 .M N... 100644 100644 100644 e3f94d2ea45d5c32e16901884e356a41c2b9fe0d e3f94d2ea45d5c32e16901884e356a41c2b9fe0d resources/meshes/third-party/tomas-laulhe/Candle.obj
1 .M N... 100644 100644 100644 5abf5121e35426f95859abea994d3ba44ca17f58 5abf5121e35426f95859abea994d3ba44ca17f58 resources/meshes/third-party/tomas-laulhe/Potion.mtl
1 .M N... 100644 100644 100644 993c84b36ddfff54dc6722ffea0aa059f2838b01 993c84b36ddfff54dc6722ffea0aa059f2838b01 resources/meshes/third-party/tomas-laulhe/Potion.obj
1 .M N... 100644 100644 100644 8bbb07436b779907892bd161b04ff4ab44200d8c 8bbb07436b779907892bd161b04ff4ab44200d8c resources/meshes/third-party/tomas-laulhe/Potion3.mtl
1 .M N... 100644 100644 100644 f2c193eb97f500cceb1401fc384e716fd7b2a6c6 f2c193eb97f500cceb1401fc384e716fd7b2a6c6 resources/meshes/third-party/tomas-laulhe/Potion3.obj
1 .M N... 100644 100644 100644 4471f85a5baadf7c9e7dd4162e4516f77684ec48 4471f85a5baadf7c9e7dd4162e4516f77684ec48 resources/meshes/third-party/tomas-laulhe/Potion4.mtl
1 .M N... 100644 100644 100644 a06eebc3fa7f098e71e09f9b604dbf46b9eb168b a06eebc3fa7f098e71e09f9b604dbf46b9eb168b resources/meshes/third-party/tomas-laulhe/Potion4.obj
1 .M N... 100644 100644 100644 a7e90d2a1cbe6fd0783eb987ba7874b29c733d21 a7e90d2a1cbe6fd0783eb987ba7874b29c733d21 resources/meshes/third-party/tomas-laulhe/Potion5.mtl
1 .M N... 100644 100644 100644 2995c85f168bd4141239333e4ad6bab361fad725 2995c85f168bd4141239333e4ad6bab361fad725 resources/meshes/third-party/tomas-laulhe/Potion5.obj
1 .M N... 100644 100644 100644 fdfc29210e909d07850ec6a91fa7fdbe6f86b469 fdfc29210e909d07850ec6a91fa7fdbe6f86b469 resources/meshes/third-party/tomas-laulhe/Potion5Full.mtl
1 .M N... 100644 100644 100644 cb831cf4a143880a256049bde98e080a3c523e3b cb831cf4a143880a256049bde98e080a3c523e3b resources/meshes/third-party/tomas-laulhe/Potion5Full.obj
1 .M N... 100644 100644 100644 e14a2bce2083ef7d9d2c1065e77ef1d33b1df398 e14a2bce2083ef7d9d2c1065e77ef1d33b1df398 resources/meshes/third-party/tomas-laulhe/Sail ship.mtl
1 .M N... 100644 100644 100644 cb88c5feb7c8983d8330090a45771fd25cb97e65 cb88c5feb7c8983d8330090a45771fd25cb97e65 resources/meshes/third-party/tomas-laulhe/Sail ship.obj
1 .M N... 100644 100644 100644 84cf7e51e44e7b585982f81d1ba394bcb9e5f951 84cf7e51e44e7b585982f81d1ba394bcb9e5f951 resources/meshes/third-party/tomas-laulhe/Scroll.mtl
1 .M N... 100644 100644 100644 60580ce1b1cd827f1df5dba0f803381df2b735b6 60580ce1b1cd827f1df5dba0f803381df2b735b6 resources/meshes/third-party/tomas-laulhe/Scroll.obj
1 .M N... 100644 100644 100644 9092faf948182c7070ef01ffa1b4e519625c8a1c 9092faf948182c7070ef01ffa1b4e519625c8a1c resources/meshes/third-party/tomas-laulhe/Stairs.mtl
1 .M N... 100644 100644 100644 6545359d6c7b9ab8921712b27d866eafd662adc5 6545359d6c7b9ab8921712b27d866eafd662adc5 resources/meshes/third-party/tomas-laulhe/Stairs.obj
1 .M N... 100644 100644 100644 e2a3d3683a8ef38f7c94e4bab1a996a477c856bf e2a3d3683a8ef38f7c94e4bab1a996a477c856bf resources/meshes/third-party/tomas-laulhe/Viking boat.mtl
1 .M N... 100644 100644 100644 b35190ea340d44f873e804583ba0551f71e17d56 b35190ea340d44f873e804583ba0551f71e17d56 resources/meshes/third-party/tomas-laulhe/Viking boat.obj
1 .M N... 100644 100644 100644 814ea898b903411a763752d1197138f2b6a86215 814ea898b903411a763752d1197138f2b6a86215 resources/meshes/third-party/tomas-laulhe/Window.mtl
1 .M N... 100644 100644 100644 7ea927023d7ab651d5fa0e04e2e651392eb360fe 7ea927023d7ab651d5fa0e04e2e651392eb360fe resources/meshes/third-party/tomas-laulhe/Window.obj
1 .M N... 100644 100644 100644 4046b2fbdbf8124f145e57823b538b8704d4b505 4046b2fbdbf8124f145e57823b538b8704d4b505 resources/meshes/third-party/tomas-laulhe/WindowGothic.mtl
1 .M N... 100644 100644 100644 aadd1243a7fcbf55cad2dd0dcebb645b52f3a6ed aadd1243a7fcbf55cad2dd0dcebb645b52f3a6ed resources/meshes/third-party/tomas-laulhe/WindowGothic.obj

```

**Comment by RationalMatta** [comment] 2018-03-20 16:21
This happened to me with some (but not all) autogenerated documentation files, i.e. files had been overwritten but content was identical.

**Comment by shiftkey** [comment] 2018-03-25 22:41
@Avallach7 @RationalMatta apologies for the delay. The ⚠️ icon in the top-right is our way of surfacing the Git warning that the line endings of the file will be changed as part of committing - you should be able to hover over that and see a tooltip with more details.

There's a number of Git settings that can affect your line endings when you're working. See if you have any of these defined:

```
$ git config core.eol
$ git config core.autocrlf
$ git config core.safecrlf
```

These are all ignored if you have a `.gitattributes` file setup in the repository - this is what we recommend doing because the settings stay with the repository when it's moved between machines. If you have one of those defined, can you share what's in these files?

To emulate the underlying diff output from Desktop, you can run this command from Git itself:

```
$ git diff HEAD --no-ext-diff --patch-with-raw -z --no-color -- [path]
```

I think you'll see something like this mentioned in the output:

```
warning: CRLF will be replaced by LF in ...
```

Thinking on this some more, maybe we need to push the ⚠️ message down into the diff body and explain _why_ the file is being listed - the clue is clearly being missed, and might help with avoiding confusion. You can encounter this message for the "empty diff" as well as the "diff has changed" scenario, so it's a bit tricky to rework this (and why I went with the icon in the first place).

cc @desktop/core @desktop/comrades for feels

**Comment by RationalMatta** [comment] 2018-03-30 11:03
You are probably right. Exact situation is no longer occurring but I can see that several of the JSDoc generated help files have an orange triangle (which I had not noticed on the right hand pane) that mentioned line changes occuring in a repo with core.autocrlf=true. Probably would be a good idea to show them more prominently. Also I'm not sure what the logic is in when a warning is on the left hand file list and when on right. Also also it would make sense that if you have core.autocrlf=true and only change being in line changes to not show it as a change since essentially commit would not change repo, right?

**Comment by tom10271** [comment] 2018-04-16 01:29
It is possible that mod of files (like changed from 644 to 700) and git considered it as file changed without content changes. It would be great if this application for stating it clearly no content changed but mod does.

**Comment by shiftkey** [comment] 2018-04-16 01:57
@tom10271 

>  It would be great if this application for stating it clearly no content changed but mod does.

This is being tracked in https://github.com/desktop/desktop/issues/557.

**Comment by shiftkey** [comment] 2018-07-04 18:53
@RationalMatta 

> Also I'm not sure what the logic is in when a warning is on the left hand file list and when on right. 

The ⚠️ in the file list is for files that are marked as conflicted by Git. This is another hint that we need to distinguish these line ending issues from conflicts better.

**Comment by shiftkey** [comment] 2018-07-04 18:59
I'm going to move making this experience better to #5098, please follow along with that.

**Closed by shiftkey** 2018-07-04 18:59 UTC
Labels: more-information-needed, reviewer-needs-to-reproduce

**Comment by daGUY** [comment] 2018-10-23 23:01
I see this issue all the time when working with Visual Studio projects that use SASS or LESS stylesheets – every time I run a build or make changes, a bunch of CSS files appear as "changed" but aren't actually any different.

The annoying thing is that this prevents me from switching branches unless I discard all the CSS files first, because it thinks they're uncommitted changes.

I use a couple other git clients (SourceTree, etc.) and GitHub Desktop is the only one I've ever seen with this issue.

**Comment by TheGreatDuck** [comment] 2019-08-27 02:18
This problem is heavily affecting me, atm and any workaround would be appreciated. My project involves running a script that generates a version control friendly variant of my source. The problem is that that causes m entire 3000 file repository to sound alarm bells that it has been modified. Is there any way to hide file changes that have no text changes?

**Comment by muhibraza** [comment] 2019-09-05 18:33
I am having the same issue. My projects are for STM32 ARM cortex microcontroller and I'm using a code generation tool from Quantum Leaps called QM Modeler. Whenever I click "Compile" on this tool it generates a bunch of files even if there are no content changes. But GitHub desktop tool still lists them in the staging area just because the timestamp changed. Then I have to scroll through all the files to manually check if anything really changed or not. I would appreciate a mechanism that tells GitHub Desktop to ignore timestamp changes if contents are the same and avoid listing it in the staging area.

**Comment by marklanhamhc** [comment] 2019-09-11 09:48
This is also happening to me when switching branches. It asks if I want to bring the changes over to the working branch but then the changes just disappear and I lose my code. This is really not good!

**Comment by tierninho** [comment] 2019-09-11 17:18
@magicmarvman This sounds like a stashing issue. Please file a [new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) if you'd like us to investigate.

**Comment by tierninho** [comment] 2019-09-11 17:19
@marklanhamhc This sounds like a stashing issue. Please file a [new issue](https://github.com/desktop/desktop/issues/new?template=bug_report.md) if you'd like us to investigate.

**Comment by JeremieD** [comment] 2019-09-20 03:25
I also seem to have this problem. I can tell by running `git status` that file permissions have changed. It's probably because I overwrote some files on macOS. It must have messed up the Windows file permissions or something. I don't know a whole lot about Windows permissions...
Discarding the changes in GitHub Desktop doesn't work. I also tried fiddling with the permissions but nothing.

**Comment by vanvught** [comment] 2019-12-09 14:15
I also seem to have this problem.

**Comment by tierninho** [comment] 2019-12-09 18:58
@vanvught Please open a new issue if you are having trouble.

**Comment by cyberpower678** [comment] 2020-08-25 22:25
This is also happening to me.  No way to work around it. :-(

**Comment by tierninho** [comment] 2020-08-26 00:03
@cyberpower678 Please open a new issue if you are having trouble.

**Comment by BVerma-CRM** [comment] 2022-03-14 05:43
running below command after moving the latest changes to folder solved the issue for me

`sudo chmod -R 100775 .`

**Comment by justingolden21** [comment] 2022-05-01 21:40
Relevant prettier read: https://prettier.io/docs/en/options.html

In `.prettierrc` I set `"endOfLine": "crlf"` and it stopped showing diffs for the line endings every time I run format.

(I of course have `.gitattributes` set to `* text=auto` as well)

**Comment by maxine-l-m** [comment] 2022-08-21 08:37
@shiftkey Any plans to make the ui change (pushing the "lf will be changed to crlf" to the diff body)

**Comment by cprovatas** [comment] 2023-01-13 00:56
+1 I am currently experiencing this issue

**Comment by GregSlazinski** [comment] 2023-01-23 14:22
+1 this is happening a lot lately

**Comment by GregSlazinski** [comment] 2023-01-23 14:33
For me this happens if a text file has a NUL (0x00) character somewhere inside.

**Comment by unmanned-harry** [comment] 2023-01-31 00:24
This same thing happened to me while working on the WSL Docker Image of Ubuntu 20.04 of C files.
Suddenly 700+ changed files with not a single line of code change...

**Comment by themarkroberts** [comment] 2023-03-03 00:19
Happening now for me

**Comment by samrrr** [comment] 2023-03-09 21:18
This bug still exist.

**Comment by AlbertShown** [comment] 2023-03-21 16:36
Since Feb 10, 2018, this bug still exists.

**Comment by SplitThePotMichal** [comment] 2023-06-29 02:32
> 10, 2018, this bug still exists.

2023 still exists.

**Comment by Schmitt-DE** [comment] 2023-09-11 14:47
I got a zip file with hundreds of files. I wanted to check which files actually changed against the master branch. I overwrote my local repo und started Github Desktop. I lists all files. 99% show "No content changes found". So why the hell do you show me those irrelevant files then? You know that there are no changes. Then do not list them as changed. Or at least please make some checkbox "Only show changed files where the content changed". I dont care about any timestamp, metadata, end of line stuff. I want to see actual content changes.

**Comment by thomasrex3** [comment] 2024-02-02 15:47
Still an issue and they dont care

**Comment by ataraxia89** [comment] 2024-03-13 11:57
This is still a bug

**Comment by nathanfranke** [comment] 2024-03-17 14:29
My workaround: Stash all changes, then restore

**Comment by Investigamer** [comment] 2024-03-22 21:55
Getting this issue myself. All files changed in all repositories just show "No content changes found", mostly Python based projects.

**Comment by Birgerev** [comment] 2024-04-02 14:19
Can confirm still present, "LF will be replaced by CRLF" too

**Comment by BHare1985** [comment] 2024-04-04 15:37
I had this issue when pointing github desktop for windows to my WSL files.  Solution was `git config core.filemode false` in WSL.

**Comment by celojevic** [comment] 2024-04-05 10:54
I noticed a similar issue in Plastic, where that would show (unchanged) files in the changelog if the timestamp on the file changed. There is an option to turn it off there. Maybe something similar going on here?

**Comment by symonxdd** [comment] 2024-05-08 16:45
> > 10, 2018, this bug still exists.
> 
> 2023 still exists.

2024 still exists.

**Comment by cuongdevops98** [comment] 2024-05-21 13:15
> My workaround: Stash all changes, then restore

Worked like a charm!!
And I still encounter this issue today, heavily affect my work.

**Comment by Birgerev** [comment] 2024-05-22 11:38
For unity projects, this really helped get rid of these empty changes: https://github.com/gitattributes/gitattributes/blob/master/Unity.gitattributes

**Comment by miklish** [comment] 2024-09-03 21:43
The correct work-around for this specific timestamp-change issue is posted by @nathanfranke :

> My workaround: Stash all changes, then restore

Folks are conflating the original issue of this ticket with the separate issue of having files with modified linebreaks.

This is not an 'LF to CRLF' issue.

This issue is about files with no modifications to the code text (not even changes to linebreaks from LF <--> CRLF, or changes to other whitespace). The issue the OP is talking about is when the file date is modified (e.g.: file is cut then pasted back with no changes to the file contents) and SourceTree treats them as "modified".

**Comment by philkonick** [comment] 2024-09-12 15:51
Happens for me and our whole team. Specifically with files generated by NSwag. The files show up in git changes but there's no actual changes, and if you stage the file it just disappears. This is mostly just an annoyance, but would love to resolve it. I think my whole team would appreciate it.

**Comment by louisfacun** [comment] 2024-10-30 18:03
> I had this issue when pointing github desktop for windows to my WSL files. Solution was `git config core.filemode false` in WSL.

this solution works for me! (if you use github desktop on a wsl path)

**Comment by mcclaim** [comment] 2025-02-12 10:57
2025 still exists. I noticed that this happens after linters.

**Comment by zengfanfan** [comment] 2025-02-22 10:02
This is a big problem existing for 7 years! 
Could any one just solve it!

**Comment by isFanzy** [comment] 2025-03-18 12:19
run `git add , ` and then `nothing to commit, working tree clean`

**Comment by isFanzy** [comment] 2025-03-18 12:20
run `git add .  `and then `nothing to commit, working tree clean`

**Comment by VIRUXE** [comment] 2025-04-08 18:11
Once in a while I also get this.

I just add and commit.

>CRLF will be replaced by LF the next time Git touches it

**Comment by blackletum** [comment] 2025-04-28 07:37
such an annoyance. 

most of the time too, it WILL show the changes once you commit them and go to the History tab, which is absurd

**Comment by MarcTCruz** [comment] 2025-05-22 17:47
git stash -all
git stash pop

Works for me.

**Comment by pchemguy** [comment] 2025-09-26 10:20
Why is it so hard to reset timepstamps on any files with no content changes detected!?

**Comment by kte608** [comment] 2025-10-15 13:44
This issue is happening for me as well, and it is a major pain. The problem seems to be with the timestamps.
