### ISSUE TITLE
Unable to install Github Desktop on Mac OS

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#15053] opened 2022-07-30 03:34 UTC
### The problem

I downloaded `GitHubDesktop-arm64.zip` from official website and then unzipped it, but I cannot open `Github Desktop.app`.

### Release version

3.0.5

### Operating system

Mac OS Monterey 12.5(with M1 Pro chip)

### Steps to reproduce the behavior

1. Enter the official website page: [https://desktop.github.com/](https://desktop.github.com/)
2. Click on link `Download for an Apple silicon Mac.` below button `Download for macOS` to start the download
3. Unzip file `GitHubDesktop-arm64.zip`
4. Open `Github Desktop.app`

### Screenshots

When I open `Github Desktop.app`, an error pops up:

<img width="260" alt="WX20220730-113319@2x" src="https://user-images.githubusercontent.com/54263609/181870935-fd2781d3-5895-4d25-abd4-1dff8eae4464.png">

**Comment by steveward** [comment] 2022-08-01 15:18
Thanks for the report @sonvier. Could you translate the error message in the screenshot for me?

**Comment by sonvier** [comment] 2022-08-02 01:03
The application `GitHub Desktop.app` cannot be opened.

**Comment by ghost** [comment] 2022-08-02 01:03
> Thanks for the report @sonvier. Could you translate the error message in the screenshot for me?

The application GitHub Desktop.app cannot be opened.

**Comment by JonnycatMeow** [comment] 2022-08-03 06:57
do sudo chmod -R 755  on your terminal then drop the application

**Comment by JonnycatMeow** [comment] 2022-08-03 06:57
then it should work

**Comment by ghost** [comment] 2022-08-03 13:15
> do sudo chmod -R 755 on your terminal then drop the application

This method didn't work for me

**Comment by williamhannry** [comment] 2022-08-07 23:16
⁣Get BlueMail for Android ​

**Comment by williamhannry** [comment] 2022-08-09 21:30
> 
> 
> ⁣Get BlueMail for Android ​

**Comment by steveward** [comment] 2022-08-10 15:55
@williamhannry can you dry downloading the [regular version of GitHub Desktop](https://central.github.com/deployments/desktop/desktop/latest/darwin) to see if that works?

**Comment by ghost** [comment] 2022-08-11 02:08
> @williamhannry can you dry downloading the [regular version of GitHub Desktop](https://central.github.com/deployments/desktop/desktop/latest/darwin) to see if that works?

I have downloaded it but still can't open it, could this be caused by my system? I don't think there's anything wrong with the software itself.

**Comment by akhilpotdar1** [comment] 2022-08-29 23:26
@sonvier I am also facing the same issue for the Mac OS Monterey 12.5(with M1 Pro chip). Following the steps outlined in your first post, I too am getting the following error for the GitHubDesktop-arm64.zip:

Screenshot:
![image](https://user-images.githubusercontent.com/43649633/187315775-38c67ff6-03e6-454b-ac60-aa4b41106124.png)

**Comment by steveward** [comment] 2022-09-09 16:08
It may be helpful if you open `Console.app` and see if anything is logged there when you attempt to open GitHub Desktop on your machine.

**Comment by ssunabashir** [comment] 2023-02-08 00:55
I am facing the same issue on MacOS ventura 13.2

**Comment by ghost** [comment] 2023-02-08 03:21
I currently find a possible solution: Create a new administrator account, download github desktop in this account, and then migrate the downloaded software to the original account for installation.

**Comment by atomrab** [comment] 2023-02-18 23:51
I am having the same problem on a 2021 Macbook Pro with an M1 chip running Monterey 12.6.3. I get both the small window that says it can't be opened and the following, even when running with limited admin privileges (this is an institutionally managed machine at a public university): 
<img width="337" alt="Screen Shot 2023-02-18 at 5 50 32 PM" src="https://user-images.githubusercontent.com/4740995/219904664-0fdcd3a0-5b90-45ab-a221-2f0e8c5dd6a4.png">

**Comment by tidy-dev** [comment] 2023-02-23 18:58
@atomrab You could have a similar issue to described in this issue. However, on Feb 2nd, we [revoked certificate for versions before 3.1.3](https://github.com/desktop/desktop/issues/16052) and having one of those versions can also cause that same warning as you showed. Being an institutionally managed machined, it is possible that the software just has not been updated.

Since the author of this issue found a work around, it would indicate that the issue is that the user did not have permission on the system to run the software and not an issue with GitHub Desktop. Going to close this out.

**Closed as completed by tidy-dev** 2023-02-23 18:58 UTC

**Comment by oresamp** [comment] 2023-02-26 11:05
I had the same problem with my Archiver App. I tried to unzip it with [Archiver App](https://archiverapp.com), then I got the same window that the App can't be opened. Then I tried to unzip it with the standard zip mac os app and it worked.

**Comment by IngAjVillalon** [comment] 2023-03-31 22:46
> I had the same problem with my Archiver App. I tried to unzip it with [Archiver App](https://archiverapp.com), then I got the same window that the App can't be opened. Then I tried to unzip it with the standard zip mac os app and it worked.

@oresamp  You have got the right emphasis!

**Comment by jlopez16** [comment] 2023-06-28 00:59
> Archiver App

This worked for me! Thank you!

**Comment by jlopez16** [comment] 2023-06-28 01:00
> 



> > I had the same problem with my Archiver App. I tried to unzip it with [Archiver App](https://archiverapp.com), then I got the same window that the App can't be opened. Then I tried to unzip it with the standard zip mac os app and it worked.

This worked for me! Thank you!

**Comment by dhruvinprajapati** [comment] 2023-06-30 03:37
same problem I have facing, I mistakenly download Intel Github, I uninstall it and again install silicon github, then it's work fine

**Comment by Hkairon98** [comment] 2023-08-16 11:59
> @williamhannry can you dry downloading the [regular version of GitHub Desktop](https://central.github.com/deployments/desktop/desktop/latest/darwin) to see if that works?

heyy u found any solution

**Comment by JonnycatMeow** [comment] 2023-08-16 17:42
ok with the "will damage your computer. you should move it to trash" you can fix it by putting this in the command line xattr -r -d com.apple.quarantine /path/to/app/  replace  the /path/to/app/ with the github desktop app

**Comment by JonnycatMeow** [comment] 2023-08-16 17:43
also here is the link for the issue fix https://iboysoft.com/news/remove-will-damage-your-computer-error-mac.html#:~:text=To%20eliminate%20this%20message%2C%20simply,Mac%20to%20fix%20the%20issue.

**Comment by Bearxpress** [comment] 2023-12-09 02:29
Trying different unzippers worked for me too

**Comment by milad1372** [comment] 2024-06-19 21:18
To unzip the file, use the **Archive Utility**. After unzipping, it should work.

<img width="449" alt="Screenshot 2024-06-19 at 3 16 40 PM" src="https://github.com/desktop/desktop/assets/9199177/ba9eb127-b0a4-4efb-837a-847726772ae0">
