### ISSUE TITLE
getRecentBranches acts as a bottleneck, affecting app responsiveness

### ISSUE THREAD

**Issue by Shawn-in-Tokyo** [desktop/desktop#5112] opened 2018-07-07 04:19 UTC
Please see https://github.com/desktop/desktop/issues/4290

This is the same issue and as noted there:

*GitHub.com
*private repo
*no antivirus running

Here is the requested performance timeline for switching branches:
[CPU-20180707T124202.switiching branches.cpuprofile.zip](https://github.com/desktop/desktop/files/2172438/CPU-20180707T124202.switiching.branches.cpuprofile.zip)

For switching repos:
[CPU-20180707T125525.switched repo.cpuprofile.zip](https://github.com/desktop/desktop/files/2172439/CPU-20180707T125525.switched.repo.cpuprofile.zip)

And with the newest version 1.2.6
[CPU-20180707T130455.newest version.cpuprofile.zip](https://github.com/desktop/desktop/files/2172440/CPU-20180707T130455.newest.version.cpuprofile.zip)

Finally, when trying to get the version for the above and selecting "About desktop", it took +5 seconds. In trying to close that menu, it took +5 seconds.  When subsequently running the profiler and trying the same operation, it ran smoothly.  But after a few operations such as looking at history or looking at a repo list, then going back and viewing "About desktop", it was again very slow trying to close the menu showing the version.  This is captured below.  Note: this seems to be a common pattern.  Some operations is very slow, but subsequent similar operations are smooth.  Then, later that particular operation will be slow.  What is consistent is that I can't use Desktop for more than a minute without something slowing it down.

[CPU-20180707T131408.1.2.6 close about.cpuprofile.zip](https://github.com/desktop/desktop/files/2172444/CPU-20180707T131408.1.2.6.close.about.cpuprofile.zip)

**Comment by shiftkey** [comment] 2018-07-07 16:08
@Shawn-in-Tokyo thanks for the CPU profiles!

I had a quick glance at all the files and they all share this common flamegraph involving `getRecentBranches`:

<img width="856" src="https://user-images.githubusercontent.com/359239/42412524-450de752-81e4-11e8-9b57-7b2e52f02b3a.png">

This is the function responsible (it's a way for us to scan the reflog and find the branches you last interacted with):

https://github.com/desktop/desktop/blob/a61a5bdc94ee8237dfff328957cdaee99a9b61e1/app/src/lib/git/reflog.ts#L5-L50

It should limit itself to reading only 2500 lines, and we only need to return 5 branches at most, but maybe due to a large reflog, and the app trying to keep this list current, the app spends more time in here churning than we need to.

What's interesting here is that we seem to be spending all of the time inside this regex: 

https://github.com/desktop/desktop/blob/a61a5bdc94ee8237dfff328957cdaee99a9b61e1/app/src/lib/git/reflog.ts#L12

I'm going to tweak the title to indicate it's related to `getRecentBranches`, but I'm still puzzled about why 2500 regex calls (worst case scenario here) is taking 27s or so - that's about 10ms per regex call!

I'd like to confirm we need to tune this a bit by getting some details about the local repository:

 - how big the reflog is currently (i.e how many lines are we working with here?) I suspect this will return 2500 or near to it, to suggest we have a lot of reflog activity here.

```
$ git reflog -n 2500 | wc -l
```

 - how many entries are displayed under the "recent branches" list? This should be 5 or less, and if it's less this suggests we're scanning the whole list to find enough branches to display.

<img width="430" src="https://user-images.githubusercontent.com/359239/42412627-2b9875f6-81e6-11e8-82f4-e935d444590c.png">

**Comment by Shawn-in-Tokyo** [comment] 2018-07-09 10:16
For what it's worth, it seems to be ok now.

I removed all branches except for master and ran:

```
    git reflog expire --expire-unreachable=now --all
    git gc --prune=now

```
And am now showing

```
    git reflog -n 2500 | wc -l
         316
```

**Comment by shiftkey** [comment] 2018-07-09 11:51
@Shawn-in-Tokyo yeah, I was going to suggest that once I'd identified why the regex was so expensive, but I think we've got enough details here to dig into it.

**One last question: with this problem repository, were you mostly working in 2 or 3 branches?** I think what was happening here is we'd exhaust the entire reflog trying to read enough entries to fill the recent branches list, and need to tune this code to "give up" earlier.

For reference, my local Desktop fork (also on macOS) has over 1600 entries in it's reflog, and `getRecentBranches` takes 4ms to complete (looking very different to yours). But that might be down to me switching branches frequently so the required branches list will be populated quickly.

<img width="391" src="https://user-images.githubusercontent.com/359239/42448853-fef31932-8354-11e8-8312-761f6a2973f2.png">

**Comment by Shawn-in-Tokyo** [comment] 2018-07-10 04:04
Yes, I was mainly in two branches for some time and may have been only really using one for a few months.

**Comment by shiftkey** [comment] 2018-07-10 11:29
> Yes, I was mainly in two branches for some time and may have been only really using one for a few months.

This is interesting - thanks for the extra information!

**Comment by shiftkey** [comment] 2018-07-10 12:47
Marking as `reviewer-needs-to-reproduce` as I think these are the necessary steps:

 - cleanup all local branches
 - prune the reflog
    - `git reflog expire --expire-unreachable=now --all`
    - `git gc --prune=now`
 - checkout a new branch
 - generate a long reflog history (700+) by switching between the default branch and the new branch
 - see if this affects `getRecentBranches()`

**Comment by billygriffin** [comment] 2018-10-01 16:51
Added `help wanted` and `performance` here as I think it's a fairly rare case but if someone wants to dig into it that would be great.

**Comment by billygriffin** [comment] 2019-11-21 14:56
I think this is still potentially a weird state that folks can get into with a specific set of preconditions, but because we haven't seen this come up in more than a year and it does seem quite uncommon, I'm going to close this. Really appreciate the report @Shawn-in-Tokyo and if we see this come up more frequently we're definitely open to reopening this.

**Closed by billygriffin** 2019-11-21 14:56 UTC
Labels: help wanted, investigation-needed, performance
