### ISSUE TITLE
GitHub Desktop Beta cannot exit process after close main window

### ISSUE THREAD

**Issue by TGSAN** [desktop/desktop#13658] opened 2022-01-11 14:01 UTC
### Describe the bug
GitHub Desktop Beta cannot exit process after close main window.
Every time I launch it and close, a `GitHubDesktop.exe` process is added to the task manager.

### Version & OS

Version: 2.9.6-beta3 (arm64)
OS: Windows 11 10.0.22000.376 ARM64

### Steps to reproduce the behavior

1. Launch the GitHub Desktop.
2. Close or click File - Exit item to exit.
3. Open taskmgr.exe.
4. You can see the `GitHubDesktop.exe` process are not exit.

### Expected behavior

Exit the process after main windows closed.

### Actual behavior

The process keep running after close.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

```
2022-01-11T13:47:52.013Z - info: [ui] [AppStore] loading 1 repositories from store
2022-01-11T13:47:52.014Z - info: [ui] [AppStore] found account: TGSAN (TGSAN)
2022-01-11T13:47:52.334Z - info: [ui] [BranchPruner] Last prune took place in 7 hours - skipping
2022-01-11T13:47:52.884Z - info: [ui] launching: 2.9.6-beta3 (Windows 10.0.22000)
2022-01-11T13:47:52.885Z - info: [ui] execPath: 'C:\Users\TGSAN\AppData\Local\GitHubDesktop\app-2.9.6-beta3\GitHubDesktop.exe'
2022-01-11T13:47:54.890Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.002s)
2022-01-11T13:47:57.692Z - info: [ui] calling captureCommandOutput(where git)
2022-01-11T13:48:05.456Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune --recurse-submodules=on-demand origin (took 2.304s)
2022-01-11T13:48:37.871Z - info: [ui] [AppStore] loading 1 repositories from store
2022-01-11T13:48:37.873Z - info: [ui] [AppStore] found account: TGSAN (TGSAN)
2022-01-11T13:48:38.188Z - info: [ui] [BranchPruner] Last prune took place in 7 hours - skipping
2022-01-11T13:48:38.483Z - info: [ui] launching: 2.9.6-beta3 (Windows 10.0.22000)
2022-01-11T13:48:38.484Z - info: [ui] execPath: 'C:\Users\TGSAN\AppData\Local\GitHubDesktop\app-2.9.6-beta3\GitHubDesktop.exe'
2022-01-11T13:48:39.898Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.410s)
2022-01-11T13:49:26.730Z - info: [ui] [AppStore] loading 1 repositories from store
2022-01-11T13:49:26.731Z - info: [ui] [AppStore] found account: TGSAN (TGSAN)
2022-01-11T13:49:26.999Z - info: [ui] [BranchPruner] Last prune took place in 7 hours - skipping
2022-01-11T13:49:27.386Z - info: [ui] launching: 2.9.6-beta3 (Windows 10.0.22000)
2022-01-11T13:49:27.388Z - info: [ui] execPath: 'C:\Users\TGSAN\AppData\Local\GitHubDesktop\app-2.9.6-beta3\GitHubDesktop.exe'
2022-01-11T13:49:29.168Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.772s)
```

**Comment by steveward** [comment] 2022-01-11 20:04
Thanks for the report @TGSAN. I was able to confirm this is an issue in the beta version (on a Windows 10 machine). I also checked in production and verified processes exit correctly when the app is closed.

![Screenshot 2022-01-11 150051](https://user-images.githubusercontent.com/721500/149012922-fe702f90-4412-4eb5-bb8e-47ff1ed259d0.png)

**Comment by Jarenbeaver** [comment] 2022-01-13 12:15
- [ ]

**Comment by sergiou87** [comment] 2022-01-13 15:46
An update on this: the problem seems to be related to upgrading the app to Electron 13 in #13426 

We have tried the latest version of Electron 12 and the latest of 14 and both work great. We can only reproduce this with the different versions of Electron 13 (from 13.0.0 to 13.6.6). We're probably gonna upgrade to the latest 16 if we don't find other issues 🤞 

Thanks for your patience!

**Comment by tidy-dev** [comment] 2022-02-02 15:05
@TGSAN We upgraded to Electron 14 in beta a few days ago (2.9.7-beta1). Closing this issue as it should be resolved. Feel free to reach back out if you see any odd behaviors in beta. We greatly appreciate reports like this to catch things before they hit prod. Thank you again for the report!

**Closed as completed by tidy-dev** 2022-02-02 15:05 UTC
Labels: bug, priority-2
