### ISSUE TITLE
Can not able to fetch origin warning: url has no scheme: helperselector

### ISSUE THREAD

**Issue by harikrishnasrinivas** [desktop/desktop#9606] opened 2020-04-23 03:57 UTC
### Describe the bug

I can not able to fetch origin

getting below error

warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector

### Version & OS
GitDesktop version 2.4.2
Windows 10

### Steps to reproduce the behavior
1.) Open Git Desktop
2) click on fetch origin

### Expected behavior

It should get all the latest files

### Actual behavior

throwing below alert
"warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector"

### Logs

2020-04-23T03:25:01.669Z - info: [ui] [AppStore] loading 2 repositories from store
2020-04-23T03:25:02.616Z - info: [ui] launching: 2.4.2 (Windows 10.0.17763)
2020-04-23T03:25:02.616Z - info: [ui] execPath: 'C:\Users\srinivak\AppData\Local\GitHubDesktop\app-2.4.2\GitHubDesktop.exe'
2020-04-23T03:25:03.070Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.312s)
2020-04-23T03:25:03.127Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.212s)
2020-04-23T03:25:03.160Z - info: [ui] Executing getRemotes: git remote -v (took 1.501s)
2020-04-23T03:25:04.623Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.168s)
2020-04-23T03:25:08.394Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.473s)
2020-04-23T03:25:08.396Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
warning: url has no scheme: helperselector
fatal: credential url cannot be parsed: helperselector

**Comment by rafeca** [comment] 2020-04-23 08:06
Hey @harikrishnasrinivas! Thanks for the report!

This is an issue that has been introduced in the latest GitHub Desktop release. We're currently investigating it in https://github.com/desktop/desktop/issues/9597 so I'm going to close this issue.

In the meantime, to fix the problem on your computer you can run the following command on your terminal (as mentioned in https://github.com/desktop/desktop/issues/9597#issuecomment-617745963):

```
git config --unset --global credential.helperselector
```

Alternatively, you can manually edit your `.gitconfig` file (Under `C:\Users\<username>`) and remove the following lines:

```
[credential "helperselector"]
	selected = manager
```

If you're curious about the root cause of the issue, here's a comment explaining in deep detail the issue: https://github.com/desktop/desktop/issues/9597#issuecomment-617815126

**Closed by rafeca** 2020-04-23 08:06 UTC
