### ISSUE TITLE
Low priority - Desktop Beta feature request - history visualization

### ISSUE THREAD

**Issue by InfiniteAlgorithm** [desktop/desktop#2420] opened 2017-08-08 20:39 UTC
### Description

Recognizing Desktop Beta is not an official release, one feature that is not present in Desktop Beta is the interactive visualization of branching history. Of course the enumerated history stream is still available in the sidebar, but the visualization is helpful for reviewers to more quickly digest the history of a project. This is not a bug, but it would be a great feature to maintain in the redesigned version. Alternatively, mimicking the [Network](https://github.com/desktop/desktop/network) in Desktop would accomplish the same thing. Thanks for consideration.

### Version

**GitHub Desktop version:** 0.7.2 (Desktop Beta)

**OS version:** Microsoft Windows [Version 10.0.14393]

### Steps to Reproduce

*In theory if this were implemented:*
1. Open a repository in Desktop Beta.
1. Select a branch.
1. Navigate through the visual timeline of the branch history, with corresponding actions toggled in the sidebar and main canvas (similar to Desktop for Windows).

**Expected behavior:** Visual branch history of a repository available for navigation.

**Actual behavior:** No such feature exists in this release.

**Reproduces how often:** Always.

### Logs

N/A

#### Additional Information

N/A

**Comment by joshaber** [comment] 2017-08-08 20:40
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1634. Please follow that issue for further updates.

**Closed by joshaber** 2017-08-08 20:40 UTC
