### ISSUE TITLE
Cannot switch branch with untracked files

### ISSUE THREAD

**Issue by markp2** [desktop/desktop#7720] opened 2019-06-07 08:52 UTC
## Description

If you have any untracked files you cannot switch branches in desktop because this new dialog appears. Previously this was not the case and you could switch branches and carry around untracked files.

![](https://user-images.githubusercontent.com/33937982/59070161-a1674780-88b1-11e9-836e-92e0331fd621.png)

## Version

GitHub Desktop: 2.03
Operating system: macOS 10.14.5 (18F132)

## Steps to Reproduce

Try and switch branch with untracked files.

### Expected Behavior

Ignore untracked files like the previous versions and the command line.

### Actual Behavior

Annoying dialog every time you switch branches.

**Comment by shiftkey** [comment] 2019-06-07 11:32
@markp2 thanks for the feedback!

> Previously this was not the case and you could switch branches and carry around untracked files.

This is now that second option in the list - "Bring my changes to master". If you choose that you'll complete the flow and have your changes available there.

The context behind this new dialog is outlined in more detail in https://github.com/desktop/desktop/issues/6107, and we decided that checkout was a good point to ask the user whether they wanted to bring the changes with them, or leave them stashed with their previous branch.

**Comment by markp2** [comment] 2019-06-07 11:59
@shiftkey 

Thankyou, I see that now. 

The question is, even if I confirm that changes to be brought to master, when I end up in master, whether these files are considered as potentially part of the changes to be committed? Normal git workflow distinguished between files that have been added, and files that are untracked. This new desktop change merges those two sets and therefore appears to be a regression in desktop.

Also, this is confusing new and additional step because these are not **changes**. Git does not track these as changes and so why is the user being asked to bring changes [which are not changes] into the new branch?

**Comment by ChristophRob** [comment] 2019-06-07 12:29
quite unhappy with this new feature as well, switching branches is very annoying right now. Please consider to put a new configuration setting, which removes this extra dialog

**Comment by shiftkey** [comment] 2019-06-10 13:56
@markp2 I'm going to close this out, but let us know if you have any other questions about this area

**Closed by shiftkey** 2019-06-10 13:56 UTC

**Comment by jmonrove** [comment] 2019-06-10 15:38
I just mentioned this similar annoyance in [6107](https://github.com/desktop/desktop/issues/6107)

I really hope an option is added to be able to de/activate magic stashing as it slows down agile workflow.

**Comment by shiftkey** [comment] 2019-06-10 15:47
@jmonrove thanks for that input. I want to provide some extra context from your comment in #6107 that I think is overlooked:

> You travel to release and merge feature_1 (stash dialog)
> You travel to master and merge release (stash dialog if you didn't stash)
> You travel back to feature_1 (time to unstash)

This flow was intended to allow you to stash your changes on `feature_1` (because that's where you were last working on them). Once those changes are stashed you won't be prompted again until you return to `feature_1` and unstash them explicitly.

The goal with this feature was not just to support "magic stashing", but to make it easier to manage your uncommitted changes. Previously those would always be carried around as you switch branches, and potentially interrupt you because Git is very conservative about how to handle these uncommitted changes if conflicts arise. But now you can park them on your current branch and switch to other work without needing to commit or stash them.

**Comment by jmonrove** [comment] 2019-06-10 16:54
@shiftkey thanks for the reply!

I understand, I like to have the option to keep things contained through the desktop application (I used to do it directly from the terminal before by stashing changes). I also agree that it will help to solve those situations where you cannot checkout a different branch because of conflicts, you can just have it stashed and then go there.

Is just that the situation doesn't happen as often as just traveling with your changes ( it's happened probably 4 times in the last year), at least for me.

In my case, the popup fix for a rare occurrence, has turned into the new normal
