### ISSUE TITLE
line endings changes reported by Git are not displayed in diff

### ISSUE THREAD

**Issue by t7m** [desktop/desktop#1859] opened 2017-06-01 13:12 UTC
Please summarise the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

Windows GitHub Desktop shows 282 file changes. 

### Version

**GitHub Desktop version:** 0.5.9

**OS version:** Windows 10

### Steps to Reproduce

I have a couple files that are different. It shows that hundreds are different. Further, each file listed as "different" shows NO DIFFERENCES.

Further, I downloaded the ZIP from git (into another folder), and extracted that in place... and it shows 292 file differences. All these files are the same because I just downloaded them from the repository that they belong to.(!)!)!???) So I really don't understand. How can GitHub Windows think that files I downloaded from the repository are different than what's in the repository?

This application is completely confusing my development process.

**Expected behaviour:** I'm shown the actual file differences. This worked yesterday on a different machine.

**Actual behaviour:** It shows that basically every file is different

**Reproduces how often:** Always

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

**Comment by shiftkey** [comment] 2017-06-01 13:24
@t7m could you provide some screenshots?

**Comment by t7m** [comment] 2017-06-01 13:26
![git-issue](https://cloud.githubusercontent.com/assets/1796323/26681790/5054d392-46ac-11e7-9e27-03d4f4243d87.png)

Here's one. But I honestly don't see how this would help.

**Comment by shiftkey** [comment] 2017-06-01 13:29
@t7m cool, could you also click **Repository** | **Open command prompt** and run this command:

```
> git status --porcelain=v2 --untracked-files=all
```

This will give us an idea of the raw data that Git is reporting to us...

**Comment by t7m** [comment] 2017-06-01 13:36
I ran that. Do you need me to copy results or something?

**Comment by shiftkey** [comment] 2017-06-01 13:37
@t7m yes, please attach that here

**Comment by t7m** [comment] 2017-06-01 13:38
Here's some of it

1 .M N... 100644 100644 100644 ee78d890e5fb90f2530fbdb3cbb24db3cf7ada17 ee78d890e5fb90f2530fbdb3cbb24db3cf7ada17 admin/single-admin-user.php
1 .M N... 100644 100644 100644 35501147f35a87dfa004194a95a9b5c13ce1d553 35501147f35a87dfa004194a95a9b5c13ce1d553 admin/single-category.php
1 .M N... 100644 100644 100644 1f463f6c5105256ef00afeeeade6dbef4369a002 1f463f6c5105256ef00afeeeade6dbef4369a002 admin/single-homepage-banner.php
1 .M N... 100644 100644 100644 a32c981b25ceb76c0da1650f66b1c240b909daea a32c981b25ceb76c0da1650f66b1c240b909daea admin/single-page.php
1 .M N... 100644 100644 100644 c543d006a20dae1b62a34d9996129882c2e42aec c543d006a20dae1b62a34d9996129882c2e42aec admin/single-product.php
1 .M N... 100644 100644 100644 0f22ddb72e36492604242caf5275da692fb9db2f 0f22ddb72e36492604242caf5275da692fb9db2f admin/single-role.php
1 .M N... 100644 100644 100644 50c5caea55c2406471d108e1ce6bf94bf589bb66 50c5caea55c2406471d108e1ce6bf94bf589bb66 admin/single-shop-application.php
1 .M N... 100644 100644 100644 ec0de577fb2f5822ca128703b3bdb29c00cf381a ec0de577fb2f5822ca128703b3bdb29c00cf381a admin/single-shop.php
1 .M N... 100644 100644 100644 c21135d3ca67209c0c0e584137f4a070db7ec809 c21135d3ca67209c0c0e584137f4a070db7ec809 admin/single-tile-position.php
1 .M N... 100644 100644 100644 86d12eb562b2729af66a7a059a75b759863cc5ed 86d12eb562b2729af66a7a059a75b759863cc5ed admin/single-tile-rule.php
1 .M N... 100644 100644 100644 255e5cb56109b5949241d99973b4d2548bdcb2f5 255e5cb56109b5949241d99973b4d2548bdcb2f5 application.php
1 .M N... 100644 100644 100644 6b1322474387479a306dcc295b11a67f041b0608 6b1322474387479a306dcc295b11a67f041b0608 category.php
1 .M N... 100644 100644 100644 33c8c6fd72ef01a234b07bc1133fe1e5e7351c5f 33c8c6fd72ef01a234b07bc1133fe1e5e7351c5f friends.php
1 .M N... 100644 100644 100644 1f06091fb97393621646ac495c09b46046bf9350 1f06091fb97393621646ac495c09b46046bf9350 handlers/.htaccess
1 .M N... 100644 100644 100644 887a0ab8d0f7ee44882094936b0571a619dd7cd8 887a0ab8d0f7ee44882094936b0571a619dd7cd8 handlers/ApplicationHandler.php
1 .M N... 100644 100644 100644 4be0d999ddd6cc3862d53472247a66f02f52f8e7 4be0d999ddd6cc3862d53472247a66f02f52f8e7 handlers/FriendsHandler.php
1 .M N... 100644 100644 100644 e63b7221b1518aaa64b73f9cca1b4e1086b80abf e63b7221b1518aaa64b73f9cca1b4e1086b80abf handlers/HaggleHandler.php
1 .M N... 100644 100644 100644 ae490f019e79d353167319b7f773cda0a85d086e ae490f019e79d353167319b7f773cda0a85d086e handlers/LoginHandler.php
1 .M N... 100644 100644 100644 1bff83b10656331062181de5c4f10d4d81d02658 1bff83b10656331062181de5c4f10d4d81d02658 handlers/NewsletterHandler.php
1 .M N... 100644 100644 100644 b456e7bb9717a74e9953b1885e5b41c752ecff70 b456e7bb9717a74e9953b1885e5b41c752ecff70 handlers/OAuthHandler.php
1 .M N... 100644 100644 100644 af3aa53e9fde22bd14ed7e30265c1e99d7676e9b af3aa53e9fde22bd14ed7e30265c1e99d7676e9b handlers/ProductHandler.php
1 .M N... 100644 100644 100644 61fe2c2248462fd20d840d80fcc77163535429de 61fe2c2248462fd20d840d80fcc77163535429de handlers/SandboxLetMeInHandler.php
1 .M N... 100644 100644 100644 23617f68621c2e31c92f21d6ad00914511598dff 23617f68621c2e31c92f21d6ad00914511598dff handlers/SearchHandler.php
1 .M N... 100644 100644 100644 e078a12d725e168f7f2e4f1c2cb6dbc8ea25e015 e078a12d725e168f7f2e4f1c2cb6dbc8ea25e015 handlers/_BaseHandler.php
1 .M N... 100644 100644 100644 2b75ee480d3e78c6f467c8d8b658b8409009f940 2b75ee480d3e78c6f467c8d8b658b8409009f940 index.php
1 .M N... 100644 100644 100644 c20a65c1c8de2a81d751c1b5b7438618be8f9874 c20a65c1c8de2a81d751c1b5b7438618be8f9874 landing.php
1 .M N... 100644 100644 100644 a7cb8042ca754e90e5f0a526009c4770b79eee33 a7cb8042ca754e90e5f0a526009c4770b79eee33 login-required.php
1 .M N... 100644 100644 100644 69fafb85a884b3352572022afcbd87a6c80ffd93 69fafb85a884b3352572022afcbd87a6c80ffd93 logout.php
1 .M N... 100644 100644 100644 934374307c6ddd8966b2c684492c322a23ff23fb 934374307c6ddd8966b2c684492c322a23ff23fb product.php
1 .M N... 100644 100644 100644 8de1fa04d38fd06acbca639a3e1bed868ba97456 8de1fa04d38fd06acbca639a3e1bed868ba97456 seller-info.php
1 .M N... 100644 100644 100644 9bb771718c31059aaaf1bf6a934851f55ab02cfb 9bb771718c31059aaaf1bf6a934851f55ab02cfb shops/.htaccess
1 .M N... 100644 100644 100644 772e1ad1d14f5dc68a966bd174b20b04c1818121 772e1ad1d14f5dc68a966bd174b20b04c1818121 shops/microsite.php
1 .M N... 100644 100644 100644 d9177d9d1a7f2737a16fad9c3db4374ae01e1db4 d9177d9d1a7f2737a16fad9c3db4374ae01e1db4 test.php
1 .M N... 100644 100644 100644 7ce38cd82a7055611d6791147c6df2bedafd6bc4 7ce38cd82a7055611d6791147c6df2bedafd6bc4 ui-assets/images/ScoutAlley-fullcolor.svg
1 .M N... 100644 100644 100644 5651eb785dd20ea3d128861e4480aa7dd424e151 5651eb785dd20ea3d128861e4480aa7dd424e151 ui-assets/images/scout-alley-final-white.svg
1 .M N... 100644 100644 100644 c3012852ea2f8b1e510f84cb2fa0239e4a90a7d3 c3012852ea2f8b1e510f84cb2fa0239e4a90a7d3 ui-assets/images/scout-alley-final.svg
1 .M N... 100644 100644 100644 dd684bf7dba8c64aacf0eb1fd10731b7eef1601d dd684bf7dba8c64aacf0eb1fd10731b7eef1601d ui-assets/js/admin-bfv.js
1 .M N... 100644 100644 100644 bee3cdd6f1619ef867310cfb66a3bf24046255f0 bee3cdd6f1619ef867310cfb66a3bf24046255f0 ui-assets/js/admin-btv.js
1 .M N... 100644 100644 100644 94b36de53b7bf9b5f8442da12178b4a9128a1dae 94b36de53b7bf9b5f8442da12178b4a9128a1dae ui-assets/js/admin-category-selector.js
1 .M N... 100644 100644 100644 492ab5ddcfa02bff5a9870dabe84a4c9133293ea 492ab5ddcfa02bff5a9870dabe84a4c9133293ea ui-assets/js/admin-image-uploader.js
1 .M N... 100644 100644 100644 04ae87f7634755b5f7a32030367d7c14fc8c4ea8 04ae87f7634755b5f7a32030367d7c14fc8c4ea8 ui-assets/js/admin-my-account.js
1 .M N... 100644 100644 100644 bf8e35063c96dba073e292eecb4a99f1188bb775 bf8e35063c96dba073e292eecb4a99f1188bb775 ui-assets/js/admin-single-admin-user.js
1 .M N... 100644 100644 100644 c38572e35f4b7e24d598130f3d42ef767051777a c38572e35f4b7e24d598130f3d42ef767051777a ui-assets/js/admin-single-page.js
1 .M N... 100644 100644 100644 218594179c3245d1c9c0b31b71f47d7ad3c0a713 218594179c3245d1c9c0b31b71f47d7ad3c0a713 ui-assets/js/admin-single-product.js
1 .M N... 100644 100644 100644 63c546fd009d911236c9cf5d9a3454808d4cbda7 63c546fd009d911236c9cf5d9a3454808d4cbda7 ui-assets/js/admin-single-shop-application.js
1 .M N... 100644 100644 100644 fc89a98059fbcc70e03cbe545bfab058f136a1db fc89a98059fbcc70e03cbe545bfab058f136a1db ui-assets/js/admin-single-shop.js
1 .M N... 100644 100644 100644 42e28c584c317cddd622f08d4c44918cdb95230b 42e28c584c317cddd622f08d4c44918cdb95230b ui-assets/js/admin-single-tile-rule.js
1 .M N... 100644 100644 100644 da593e9f2f1f005345d51e3555a32c1dd6d26760 da593e9f2f1f005345d51e3555a32c1dd6d26760 ui-assets/js/application-page.js
1 .M N... 100644 100644 100644 d09fbe438b980e6181df8fe35973fb3dd09d5920 d09fbe438b980e6181df8fe35973fb3dd09d5920 ui-assets/js/category-page.js
1 .M N... 100644 100644 100644 90310e051e19ff174d6f8eddeeb8755ded65ca16 90310e051e19ff174d6f8eddeeb8755ded65ca16 ui-assets/js/friends-page.js
1 .M N... 100644 100644 100644 9f2378afd7d4b605a0bf26488eb0c952cb9b990a 9f2378afd7d4b605a0bf26488eb0c952cb9b990a ui-assets/js/haggle.js
1 .M N... 100644 100644 100644 df5bc8842d811fcbb4a3c417ffe8badc8dedf349 df5bc8842d811fcbb4a3c417ffe8badc8dedf349 ui-assets/js/jquery.history.js
1 .M N... 100644 100644 100644 212ec77c3fe3f3bcb9151845d9cf1b3fd73fead0 212ec77c3fe3f3bcb9151845d9cf1b3fd73fead0 ui-assets/js/js.js
1 .M N... 100644 100644 100644 acff119fbbf6c9bcba244f178029b0b1a8dfbfae acff119fbbf6c9bcba244f178029b0b1a8dfbfae ui-assets/js/lightslider.js
1 .M N... 100644 100644 100644 8c994c467b129d99cc3e93ac7f5724aea901eaeb 8c994c467b129d99cc3e93ac7f5724aea901eaeb ui-assets/js/materialize.js
1 .M N... 100644 100644 100644 00c0d5f85aa61bf157e34f417fb4abb26f6a6c08 00c0d5f85aa61bf157e34f417fb4abb26f6a6c08 ui-assets/js/materialize.min.js
1 .M N... 100644 100644 100644 86fde6f3df0912d93e88ef9ab068837d8120d38e 86fde6f3df0912d93e88ef9ab068837d8120d38e ui-assets/js/newsletter.js
1 .M N... 100644 100644 100644 8b28902e02f2caaec1fffb14bb184ff1d168fe19 8b28902e02f2caaec1fffb14bb184ff1d168fe19 ui-assets/js/oauth.js
1 .M N... 100644 100644 100644 28836b942023a12e1e52450468e1be97512c019d 28836b942023a12e1e52450468e1be97512c019d ui-assets/js/prodpage-image-slider.js
1 .M N... 100644 100644 100644 908ab304a4cda01879c9cd3df8ad71567cd297f1 908ab304a4cda01879c9cd3df8ad71567cd297f1 ui-assets/js/product-page.js
1 .M N... 100644 100644 100644 1fa9a68034795cd67790ec93cf0db2b78466b91d 1fa9a68034795cd67790ec93cf0db2b78466b91d ui-assets/js/product.js
1 .M N... 100644 100644 100644 500a89e47e5226b0d45c08a83febb678ffac8db5 500a89e47e5226b0d45c08a83febb678ffac8db5 ui-assets/js/smoothproducts.js
1 .M N... 100644 100644 100644 60f85a3600e27692c6e66b37ce596455aef061e7 60f85a3600e27692c6e66b37ce596455aef061e7 ui-assets/js/social-connections-oauth.js
1 .M N... 100644 100644 100644 34fc59bedfc1406f47febfdbe55ad76bbbdb68c1 34fc59bedfc1406f47febfdbe55ad76bbbdb68c1 ui-assets/js/user.js
1 .M N... 100644 100644 100644 170e3d228320c5a3f25b580f1026bd36e110f3bc 170e3d228320c5a3f25b580f1026bd36e110f3bc ui-assets/packages/dropzone/dropzone.css
1 .M N... 100644 100644 100644 7e4140a8bc1302b144469ddb2f920622c6432952 7e4140a8bc1302b144469ddb2f920622c6432952 ui-assets/packages/dropzone/dropzone.js
1 .M N... 100644 100644 100644 4901c82bd793789c02d9129c8819f0ea415ee5c3 4901c82bd793789c02d9129c8819f0ea415ee5c3 ui-assets/styles/admin-btv.css
1 .M N... 100644 100644 100644 d8217bc460a28c4307812b47454bbf5e8adbb389 d8217bc460a28c4307812b47454bbf5e8adbb389 ui-assets/styles/admin-fields.css
1 .M N... 100644 100644 100644 91893f73e0b27c4a211fa9e9f59ecf3b913ac74a 91893f73e0b27c4a211fa9e9f59ecf3b913ac74a ui-assets/styles/admin-general.css
1 .M N... 100644 100644 100644 6b6093b6e8388fd18b91ae2bb5bc26d17bc0a1f9 6b6093b6e8388fd18b91ae2bb5bc26d17bc0a1f9 ui-assets/styles/admin-header-elements.css
1 .M N... 100644 100644 100644 465e7a3ebd47a295d1f71586ee46312dcc87290d 465e7a3ebd47a295d1f71586ee46312dcc87290d ui-assets/styles/admin-login.css
1 .M N... 100644 100644 100644 bb8c22928e5e7b6ac7a0e045bd2f83ebc56dbdcc bb8c22928e5e7b6ac7a0e045bd2f83ebc56dbdcc ui-assets/styles/admin-lookup.css
1 .M N... 100644 100644 100644 8163e1f4db2b1a340cec26babf6b5bd8649317c4 8163e1f4db2b1a340cec26babf6b5bd8649317c4 ui-assets/styles/admin-menu.css
1 .M N... 100644 100644 100644 0bc1c799e22ce7506f6de756bf50e5c3707a8b21 0bc1c799e22ce7506f6de756bf50e5c3707a8b21 ui-assets/styles/admin-single-page.css
1 .M N... 100644 100644 100644 c771174ccc43d43330b522a4fcd927957d12b992 c771174ccc43d43330b522a4fcd927957d12b992 ui-assets/styles/admin-single-product.css
1 .M N... 100644 100644 100644 1d6b93c9064602e7fc73e05796729c07860be92c 1d6b93c9064602e7fc73e05796729c07860be92c ui-assets/styles/admin-single-shop-application.css
1 .M N... 100644 100644 100644 6eb8047ebef24ce57eb651221df4ea11fae8f86b 6eb8047ebef24ce57eb651221df4ea11fae8f86b ui-assets/styles/admin-single-shop.css
1 .M N... 100644 100644 100644 0f20fd32451ea342d56bb13cd8f8753061fc0f9b 0f20fd32451ea342d56bb13cd8f8753061fc0f9b ui-assets/styles/admin-single-tile-rule.css
1 .M N... 100644 100644 100644 0b5e04fe6b1ab318add52f83fccb48ac127589d2 0b5e04fe6b1ab318add52f83fccb48ac127589d2 ui-assets/styles/body-class.css
1 .M N... 100644 100644 100644 a8276b9ee66605115354b27dda676171feeeef64 a8276b9ee66605115354b27dda676171feeeef64 ui-assets/styles/controls.css
1 .M N... 100644 100644 100644 6bb310d8c72607174c0730123b92cb6300ed62e0 6bb310d8c72607174c0730123b92cb6300ed62e0 ui-assets/styles/font-awesome.min.css
1 .M N... 100644 100644 100644 855c845e538b65548118279537a04eab2ec6ef0d 855c845e538b65548118279537a04eab2ec6ef0d ui-assets/styles/fonts/fontawesome-webfont.svg
1 .M N... 100644 100644 100644 b70a5c5cb5e21c38d99355dc7068b90fd383896e b70a5c5cb5e21c38d99355dc7068b90fd383896e ui-assets/styles/footer.css
1 .M N... 100644 100644 100644 422f35c5eb26704a0205934b561b6df67862d90a 422f35c5eb26704a0205934b561b6df67862d90a ui-assets/styles/general.css
1 .M N... 100644 100644 100644 e29f7f4c6223aeb794ef4af149c2d53a4edd4f97 e29f7f4c6223aeb794ef4af149c2d53a4edd4f97 ui-assets/styles/landing-page.css
1 .M N... 100644 100644 100644 2ae67cc558d0db8f122cc202fb419d6507fd54e8 2ae67cc558d0db8f122cc202fb419d6507fd54e8 ui-assets/styles/lightslider.css
1 .M N... 100644 100644 100644 0c4649526d5f28cdb05abba018633025a65f8a9a 0c4649526d5f28cdb05abba018633025a65f8a9a ui-assets/styles/materialize.css
1 .M N... 100644 100644 100644 9104745509c6dbdc73a9d475b4635545e9ba8c18 9104745509c6dbdc73a9d475b4635545e9ba8c18 ui-assets/styles/materialize.min.css
1 .M N... 100644 100644 100644 26036bec8175d0528dc382822f8f3cb5204bb3ef 26036bec8175d0528dc382822f8f3cb5204bb3ef ui-assets/styles/menu.css
1 .M N... 100644 100644 100644 a5c42301d60e5bc0474656befb18483ef02563a7 a5c42301d60e5bc0474656befb18483ef02563a7 ui-assets/styles/product-page.css
1 .M N... 100644 100644 100644 e132dd3a1c993979c826d41d76d229d1558185c3 e132dd3a1c993979c826d41d76d229d1558185c3 ui-assets/styles/sa-friends.css
1 .M N... 100644 100644 100644 5ba608b293a508f1071095a089f8c9e926265dcf 5ba608b293a508f1071095a089f8c9e926265dcf ui-assets/styles/sa-header-footer.css
1 .M N... 100644 100644 100644 fc3abffdc544e9ba15d6cf3be3be61eba93d3232 fc3abffdc544e9ba15d6cf3be3be61eba93d3232 ui-assets/styles/sa-index-styles.css
1 .M N... 100644 100644 100644 ce4974d63336760190f531375e4b37189061d213 ce4974d63336760190f531375e4b37189061d213 ui-assets/styles/sa-index-styles2.css
1 .M N... 100644 100644 100644 847fce9b3eb6c137fa57893c4b165a0ad2c12c2f 847fce9b3eb6c137fa57893c4b165a0ad2c12c2f ui-assets/styles/sa-landingpages.css
1 .M N... 100644 100644 100644 e3ff3b6f15f8ca9f01114ed25fa4a3687b9cbb52 e3ff3b6f15f8ca9f01114ed25fa4a3687b9cbb52 ui-assets/styles/sa-preview-styles.css
1 .M N... 100644 100644 100644 de383d51648c6f8b9619ef8b1f39d1699b3e1b86 de383d51648c6f8b9619ef8b1f39d1699b3e1b86 ui-assets/styles/scout-styles.css
1 .M N... 100644 100644 100644 d2758c84b5930a31fa848d5885bc700b84575280 d2758c84b5930a31fa848d5885bc700b84575280 ui-assets/styles/smoothproducts.css
1 .M N... 100644 100644 100644 0d433b927055533799651c955847f5bc628317af 0d433b927055533799651c955847f5bc628317af ui-assets/styles/z__scout-styles_b4merge.css

**Comment by shiftkey** [comment] 2017-06-01 13:47
@t7m do any of the changed files in the list render a diff? If so, could you attach a screenshot of it?

**Comment by t7m** [comment] 2017-06-01 13:52
No, nothing shows a diff, not even the files I expect to be different.

I just want to start over, re-download the repository, and then swap out files I know I have changed elsewhere. I can't find a way to do this either.

How can I start over? I just want to download all the files and have it show no diffs. That seems like a logical starting point.

**Comment by t7m** [comment] 2017-06-01 14:08
Is there some possible EOL or whitespace issue? I don't see any option to change that type of comparison.

**Comment by shiftkey** [comment] 2017-06-01 14:12
> Is there some possible EOL or whitespace issue?

Maybe. Let's try a couple of things to confirm or eliminate this. Could you run these two commands and attach the output:

```
> git diff -- .gitignore
> git config -l --show-origin
```

What we're doing here is checking the raw diff output, which might have some clues, and the current settings you have for the repository.

**Comment by t7m** [comment] 2017-06-01 14:13
FYI: I can do a WinMerge and see that only six or so files are different. This is what I was expecting GitHub to show me. I will run these commands now.

**Comment by shiftkey** [comment] 2017-06-01 14:14
> FYI: I can do a WinMerge and see that only six or so files are different.

Interesting - which files are those it detects as different, and how do they differ?

**Comment by t7m** [comment] 2017-06-01 14:15
The first command resulted in nothing. Second command gives:

file:"C:\\ProgramData/Git/config"       core.symlinks=false
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    diff.astextplain.textconv=astextplain
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.clean=git-lfs clean -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.smudge=git-lfs smudge -- %f
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.required=true
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    filter.lfs.process=git-lfs filter-process
file:"C:\\Program Files\\Git\\mingw64/etc/gitconfig"    credential.helper=manager
file:C:/Users/t/.gitconfig    user.name=t7m
file:C:/Users/t/.gitconfig    user.email=t7m@users.noreply.github.com
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        remote.origin.url=https://github.com/propertyroomdev/scout-alley.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master

**Comment by t7m** [comment] 2017-06-01 14:16
The files that WinMerge shows as different are... different. Code changes, etc.

**Comment by t7m** [comment] 2017-06-01 14:19
Also... by default I'm telling WinMerge to ignore carriage return differences. If I turn that option off, I'd get about three more files. GitHub Desktop shows them all as different for no known reason.

**Comment by shiftkey** [comment] 2017-06-01 14:32
@t7m is this repository something you can bundle up and share with us? I'd like to get to the bottom of this and give you a proper answer, and it'll be quicker than going back-and-forth like this...

**Comment by t7m** [comment] 2017-06-01 14:35
You just want its zip file? I'll have to remove passwords from some things, could take a while.

I had no issues with DIFFs on a different machine yesterday. Both are Windows 10.

**Comment by shiftkey** [comment] 2017-06-01 14:37
@t7m feel free to scrub whatever stuff is necessary, as long as it still shows the behaviour -  you can also email it to me privately at `handle [at] github dot com` if you don't want to share it here. I think that with the environment variables you've provided above should be enough for me to recreate it.

**Comment by t7m** [comment] 2017-06-01 14:46
I can't really find a comfortable way to share this code. How much of this do you actually need? Even one file shows as different when it's the same.

**Comment by t7m** [comment] 2017-06-01 15:00
I sent the email with a subset of the files.

**Comment by t7m** [comment] 2017-06-02 19:58
I am still having this issue, now on both machines. Can you tell me if there are any updates? This is reproducible 100% of the time on two machines. You have my email, would you care to discuss offline?

**Comment by shiftkey** [comment] 2017-06-02 20:28
@t7m apologies for the lack of reply today - I did get your latest email, and I'll let you know if I can't reproduce the issue after the weekend

**Comment by t7m** [comment] 2017-06-03 00:24
No problem. The steps are 100% reproducible:

1. In GitHubDesktop, get a repository
1. From GitHub web in your browser, download that same repository as a zip
1. Extract that zip to some folder
1. Copy any file from that extracted-zip folder
1. Paste that file into the folder where GitHub Desktop is.

Expected result:
- GitHub Desktop shows no changes, since the files are identical

Actual:
- GitHub Desktop says there is a "changed file", however there clearly is not a changed file, and clicking on the file shows there is no difference in the files.

Again, these steps are 100% reproducible, the bug happens every time. This is not something specific to my files.

 I guess the question is: _what is GitHub Desktop comparing to determine something is different?_

**Comment by t7m** [comment] 2017-06-03 01:13
Note on those steps above... I can open the two (identical) files in good old Notepad and see that the one GHD downloaded has multiple lines and is formatted as expected. The file that comes from the web's "download zip" shows as one long line.

WinMerge shows these files as the same (even when comparing white space and EOL syntax). But there is a binary diff when looking at the files through a binary editor.

I just don't understand why Git Hub gets me two different versions of the same file. That's truly the issue here. A text comparison shows them the same, but there are some binary differences that cause this issue.

This will make using GHD almost impossible.

**Comment by shiftkey** [comment] 2017-06-06 14:24
I was able to recreate the issue as @t7m reported, and it comes down to `git diff` writing out to `stderr` (I'm pretty sure) the line endings being changed in the diff:

<img width="728" alt="screen shot 2017-06-06 at 11 20 02 am" src="https://cloud.githubusercontent.com/assets/359239/26833979/5d82c342-4aaa-11e7-949e-57e943833109.png">

For now I'm going to see if I can get the diff view to indicate there are line endings changes to the file - this can be in addition to actual diff content changes, so this probably needs some thought. But we should also make it clear in this case that there are no content changes.

**Comment by iAmWillShepherd** [comment] 2017-08-25 18:19
See issue #2548 for details.

**Comment by shiftkey** [comment] 2017-09-01 06:04
Closing in favour of #2548 as it's not clear yet what needs to change.

**Closed by shiftkey** 2017-09-01 06:04 UTC
Labels: bug

**Comment by milan-vugrinchev** [comment] 2018-04-06 15:45
Make an option to hide EOL changes
