### ISSUE TITLE
Auth issues when interacting with repositories hosted on non-GitHub hosts

### ISSUE THREAD

**Issue by hszequel** [desktop/desktop#18612] opened 2024-05-14 11:56 UTC
### The problem

Credentials are not persistence. After Github Desktop is closed and the operating system restarted credentials are requested again for non-GitHub hosts.

### Release version

3.3.17 

### Operating system

Windows 10 (x64)

### Steps to reproduce the behavior

1. Try to fetch origin from any azure dev ops repository.
2. Credential (PAT) is requested.
3. After the credentials are entered, fetching, and pushing work as expected.
4. After Github Desktop is closed and operating system restarted, credentials are requested again.

### Screenshots

![image](https://github.com/desktop/desktop/assets/72399993/401ddace-ecab-4478-be82-3a2a7298fa74)

**Comment by sergiou87** [comment] 2024-05-14 12:03
Thank you for your report. Could you upload all your log files (after redacting whatever is necessary) so we have more context to diagnose the issue? Thank you! 🙏 

Also, does your repository use LFS?

**Comment by hszequel** [comment] 2024-05-14 14:42
Please see the attached log files. After credentials are entered, it works but they need to be reentered.

[2024-05-14.desktop.production.log](https://github.com/desktop/desktop/files/15310085/2024-05-14.desktop.production.log)

The repository does not use LFS.

**Comment by aolszowka** [comment] 2024-05-14 14:52
Dupe of #18586

**Comment by hszequel** [comment] 2024-05-14 18:02
#18586 reported a bug that did not allow authentication to non-GitHub hosts like azure devops. After we upgraded from 3.3.14 to 3..3.15, we experienced this issue. Version 3.3.16 fixed #18586 but now that we are using 3.3.17 the issue is that authentication works but it is not persistent. Credentials have to be entered again, particularly when Github Desktop is closed and the operating system is restarted. This also happens when the user switches to a different repository.

**Comment by aolszowka** [comment] 2024-05-14 18:11
> Credentials have to be entered again, particularly when Github Desktop is closed and the operating system is restarted. This also happens when the user switches to a different repository.

@hszequel Did you read the comments in there? ( https://github.com/desktop/desktop/issues/18586#issuecomment-2108847224, https://github.com/desktop/desktop/issues/18586#issuecomment-2108874736 but most specifically https://github.com/desktop/desktop/issues/18586#issuecomment-2110627351) Does that last comment mimic what you're seeing? I can say that it appears to be working, even after relaunching GitHub Desktop and switching repositories.

**Comment by hszequel** [comment] 2024-05-14 18:41
Thank you for mentioning these comments. I just read them. Repositories are accessible. We can reproduce the issue with another user (different desktops). Interestingly, a third user accessing the same repos with Github Desktop 3.3.17 has not had the issue. The only difference that we can think of is that this user upgraded directly from 3.3.14 to 3.3.17 while the other two went from 3.3.14 to 3.3.15 (authentication broke). Then, 3.3.17.

Workarounds: 

1. We downgraded to 3.3.14. The issue is resolved. The problem is that GitHub Desktop does not allow you to opt out from upgrading at the next restart :(
2. Entering the PAT every time that it is requested (big usability issue).
3. After reading the comments by @aolszowka, I generated a new PAT. So far so good, but we have only used the app for 30 minutes after that. I will update the ticket tomorrow

Based on the above, this should probably be classified as a bug.

**Comment by aolszowka** [comment] 2024-05-14 18:45
@hszequel 

Something to note is to watch the Credential Manager:

![image](https://github.com/desktop/desktop/assets/2592881/d50aebe7-51d3-4a8f-b3d3-956699effcaa)

The behavior I was seeing (prior to removing all OLD credentials and removing any Repositories that were no longer accessible) is that after the initial prompt the credential would be created under the area boxed in red above and then after some set time the credential would disappear.

I am not familiar enough with their code base to know what code path's have the ability to delete/remove credentials from here, but that is where I'd start looking for the bug.

**Comment by aolszowka** [comment] 2024-05-14 18:50
Sorry to double post here; but if you look at the log you provided @hszequel you see it helpfully delete the cred right here:

`2024-05-14T12:17:58.593Z - info: [ui] askPassHandler: auth failed, deleting dev.azure.com credential`

Based on the log you've got 16 repositories; did you go clear out ALL of the old creds? And ALL of those repositories are still valid?

`2024-05-14T11:20:16.833Z - info: [ui] [AppStore] loading 16 repositories from store`

**Comment by hszequel** [comment] 2024-05-14 20:06
All the repositories are valid. Some of these repositories are on GitHub. The ones that are on Azure DevOps have been replaced.

**Comment by hszequel** [comment] 2024-05-16 21:45
After several days unable to use GitHub efficiently, I found a workaround:

Reverted to version 3.3.14 (works perfectly) and renamed Update.exe under the GitHubDesktop folder to disable auto-update until this issue is resolved.

**Comment by sergiou87** [comment] 2024-05-24 08:04
Hello 👋 

Please, try the latest beta (3.3.19-beta2) from https://desktop.github.com/beta which includes support for multiple git credentials on the same host based on different repository paths and let us know if it works.

After updating, you might need to re-enter your credentials for your Azure DevOps repositories.

For hosts other than `dev.azure.com`, you might need to set `useHttpPath` to `true` for whatever domain your repos are hosted on. For example, for gitlab:

`git config --global credential.https://gitlab.com.useHttpPath true`

Thank you for your patience 🙏

**Comment by sergiou87** [comment] 2024-05-29 09:20
You can download 3.4.0 now from https://desktop.github.com (auto-updates are rolled out progressively and might take longer)

Closing this now, thank you for your patience 🙏

**Closed as completed by sergiou87** 2024-05-29 09:20 UTC
