### ISSUE TITLE
How to start desktop?

### ISSUE THREAD

**Issue by renyaoxiang** [desktop/desktop#2169] opened 2017-07-01 09:44 UTC
### Description
I want to start the desktop , but it occored errors , 

### Version

**GitHub Desktop version:**  "version": "0.6.2",

**OS version:**  window 7

### Steps to Reproduce

1. npm run compile:dev

### Logs

console:
...
...
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ compile:dev: `cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ compile:dev script 'cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-07-01T09_33_09_727Z-debug.log
PS D:\node-workspace\desktop>

============================================
C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2017-07-01T09_33_09_727Z-debug.log

15 verbose pkgid @
16 verbose cwd D:\node-workspace\desktop
17 error Windows_NT 6.1.7601
18 error argv "D:\\software\\nodejs\\node.exe" "D:\\software\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile:dev"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error @ compile:dev: `cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js`
23 error Exit status 1
24 error Failed at the @ compile:dev script 'cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the  package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=development parallel-webpack --config app/webpack.development.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by joshaber** [comment] 2017-07-01 15:28
Did you run `npm install` first?

**Comment by renyaoxiang** [comment] 2017-07-01 17:10
yes , I did.
but there is errors while I run it at the first time,
and there is no errors at the second time. 
I don't make sure if the install script had run successfully.
I think I need more detail info beside the guide

**Comment by renyaoxiang** [comment] 2017-07-01 17:13
```   - *If you already have Visual Studio 2015 installed, ensure you have the **Common Tools for Visual C++ 2015**```
I have installed the two programs. it also made errors.

**Comment by joshaber** [comment] 2017-07-01 20:20
You said in #2170 that `npm install` failed. Could you please provide those logs?

**Comment by neagoedragos** [comment] 2017-07-12 14:53
I am having the same problem as in #2170: 

npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`

The problem is that I'm running npm install on a PC which has no access to the internet, only to the company intranet which has their own repositories. Everything else seems to install except for download-chromedriver.js.

**Comment by joshaber** [comment] 2017-07-12 14:58
Unfortunately you will need internet access in order to install our dependencies for building.

**Comment by neagoedragos** [comment] 2017-07-12 15:38
There should be a way to grab that missing npm module, save it locally so that npm install grabs it from there

**Comment by joshaber** [comment] 2017-07-12 15:44
That's more of an npm question than a Desktop question.

I'm gonna close this out. We can re-open if we discover a Desktop-specific problem.

**Closed by joshaber** 2017-07-12 15:44 UTC
Labels: more-information-needed
