### ISSUE TITLE
My Tags seems to dissappear whenever I Append to a Commit

### ISSUE THREAD

**Issue by kd-tka** [desktop/desktop#18462] opened 2024-04-15 13:24 UTC
### The problem

Whenever I ammend to a tagged commit, the tag seem to disappear from GitHub Desktop. The tag however, is still present on GitHub after I push the commit.

### Release version

Version 3.3.13 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

1. Commit
2. Tag the Commit
3. Ammend the Commit
4. Try to view Tag in History
5. Push to GitHub
6. Try to view Tag in GitHub

**Comment by steveward** [comment] 2024-04-16 20:10
Thanks for the issue @kd-tka. This is the expected behavior of Git -- the tag is not transferred when a commit is amended since it's a new commit. You'll have to recreate the tag. I hope that helps explain things -- let me know if you have any other questions.

**Closed as completed by steveward** 2024-04-16 20:10 UTC

**Comment by kd-tka** [comment] 2024-04-17 07:35
Hello Steve,

Yes, but when I recreate the identical tag for the amended commit, I get a get a message that the tag name has already been used.

I don’t want to change the tag name for the amended commit either, as I use a script to include the tag name info into my software as version info.
(which is also the  reason I need to recompile and amend the commit after tagging it…it’s a who come first chicken and egg problem).

Besides, on GitHub itself, the original commit tag remains for the amended commit. The tag only seems to disappear from display on GitHub Desktop.


Best Regards,
Tore Kallevik
Senior Electronics Engineer

[A picture containing graphics  Description automatically generated]<https://www.kystdesign.no/>

Mobile:   +47 45 666 432<tel:+4741486187>
E-mail:    ***@***.******@***.***>

[A blue and black logo  Description automatically generated with medium confidence]<https://url12.mailanyone.net/v1/?m=1mpqaF-0001As-3I&i=57e1b682&c=QyudsBDr8Zk4V4e7j6J22snMYGDLkIXyV9kJjMVn5JUJJ_VT9CJTPiUXoP_8jOs_1j2rrOEEuHB0UiHr-0uI9dx0K3t3r3urgKx5Ytv0RBiYeUSX7GliUJkUc02ZjmBTmQlkD_C5xiG6_sD5JzrmV_tJP3r27epzEAsjdqXK3_8IREAtKybU7r-x0fM9TVt0YtgNaWYf3em-TCrj7ZY1_Dt5fM1bOvyWe162xkJrGC-rrH3U_HVYzma_-TOnd9wTFSfQ7c03JpnRlctJU_kUDTFhhpKMZbH5O-0j4X-QsSEP3P_MtbQoFk_vw9uPlOtSvuJNhLn9f_7cZLzS0aSGdEiGvElO7x3Z0748dsfCB69Pa8S-tJWbawmq7TyzbjcTh-nTskJbZbhJh820MGe1GH18mtKCE9PriaJi4V2yyjBB5dRU6C5R6FwYb6FWsSXJ3NpZF0eR1ZX3KAML-aay4iz_ATsU2EKnEHSt-b_-RsVvGATdLlaIUFosVNC6WcswleAvRCXRzaP_3zjaSBWKvj3FxUvfMLcF6HVcCkWZOoWBpNnFUEuV-fkN2Dp7Y5smIeIMQA3-1BEbH3pOFpagVyU8UrkmniHUuSddH3ajVEb-RyElrfyjy4BMSYe9dmwthSElkkRsFaBVyOe6rl7PjMBRVbVyPyMhFUTeh-KYWanl0b4gLfgZOYqOQZ8pA-4_Djqbf7URQXWr9PaX6yGhjg>        [A white letter f on a black background  Description automatically generated] <https://url12.mailanyone.net/v1/?m=1mpqaF-0001As-3I&i=57e1b682&c=OLerizXbxVkziQeSRRv4k43Q4DswsysWx4d6K_-ILgXfG11waBE189VlFRSp9EHvTM68umHzOnYfkp_Oqn9oeZJnE9B-sIIcfbEJlYXseQxixx3_78ZGjfD3vswJdNQV0Amu7Mii3YsfeLh_2NE-MCHhQBRVd0urAEvJdQLQLTcGf6fKvTBuSBWF8zq7nlovChcXHQp98JDAc9H1e2xTXX-6rc_rJrz7EvYiGiihyHwRKylsXPSaRRTc2WMi0bxDq-ZEGMmnpClGO2-1cO1rOPMvz7e5ujLkU_5ucv5UJCbQ7AByDz0AkBKTcfmij6onKFWW9RpjlRALouoICYaLT4NYL-LkFW8e_6VH35covY68INNxjeNe3WVw2mqyi0R3Zt6wULuZ3x9vGXRIKy_QaHYM45hfXVrjuWajwE3NOtFPWP4C_6oVafRBUbh-VJAmACBGzLSoirzh8CRvIka9fGIUgmPMP1fJEkoojghtdGLPb6rzILFyxmjDA_49Da1zk0FqLCDSLjPwbNRXYSrPWGNRXhcq6sr4Fh51f1A6bQwm9Aj7cLqUmD1p9eoTupKjcY41SW72boOhgSwBj7XMmINldX_HyFA3vnj9Z5TnrEi1r_Ul29dl8NaLnHY-B-a9ruOTrqDIaIQYPA0gSSiqHEGFRvvg-f2xvfC9kumRS_l3L-7nt5iZUKNU8-Q0G9cO>         [A picture containing black, darkness  Description automatically generated] <https://url12.mailanyone.net/v1/?m=1mpqaF-0001As-3I&i=57e1b682&c=72vUPQF0oQBlbe1KK1idJL-DfQNu8VKTBZikXdubR0wP2BvKAIY9dEQjQCwr9BTH29ywjZnNUh1QFglSo4fwbxUBhAd1ulLC64DJOAUiHJqm2ZtK9acJlzfzl2ek0Q3Tq4PgHH2n2jd2SbHQrx8VHMP91Lcegr4Sbmsqbc91v_A8jRYkfVZzpvfxUPpM9zoFSNd7tFrYsKc2F18zpiJodFHQKJe_MeyobjSH9dYabeyqW_DMoMBJHeWKPuNbji6-8p8h8MqLtJfVGv4KDzJEv2lJIA2KfVuYkgX_qx-N8LnK4iD-6b0Nqvnh5x7zOmlBLHrcqXgorcRhDz4c0wMHL7c98WiDfFnaNXr-TSKLiDeykNmAK75yB55KBk76ytBGuiTGcugcWdMwnkGOxoLD7sradg6pEA6o54yw_957WdqRtXEVkZGLlu5OcXM46yTtiZSiyUQgoJ-danJrDIuqkMFYiaKXGCRGFofqZa1K86ZhiS4MXSvoVm4PmMG-W3ba7HnrmG76ttQ-WWVnJWRxltZwaAZKXI27tIsuIrProZo9g7cr81uzvfxkc2ngpgy8fpX76ahBAv_fy3xtc4ibKOiSD9QcW6gXeICWIgS0gNg_ewop3HueBmr6NWdDAwWpHzstwkHOWRciqyx4CHSLXy0jGXFhpxqROetQuze5yMmXaEeNVTEZ07K9jotEpV0C>

This e-mail has been sent by Kystdesign AS vat: 979 390 718.
CONFIDENTIALITY: This e-mail and any attachments are confidential and may also be privileged. If you are not the named recipient, please notify
the sender immediately and do not disclose the contents to another person use it for any purpose or store or copy the information in any medium.
ATTENTION: This e-mail and any attachments are believed to be free from any virus, or other defect, which may affect any system into which they are
received or opened. It is the responsibility of the recipient to ensure that they are virus free and to check that they will not adversely affect its system(s)
and data. Kystdesign accepts no responsibility for any loss or damage arising in any way from their receipt, opening or use.

**Comment by steveward** [comment] 2024-04-17 15:23
I'll add this feedback to https://github.com/desktop/desktop/issues/15702 where we are tracking the ability to search for tags.
