### ISSUE TITLE
"GitHub Desktop" Keeps Restoring Desktop Icon

### ISSUE THREAD

**Issue by Bartholomue** [desktop/desktop#2129] opened 2017-06-27 10:59 UTC
No matter how frequently I delete the desktop icon for GH, it keeps bringing it back when I launch it. This seems to happen most often when GH is invoked via the browser via the Optne this Project in GitHub Desktop links available from projects.

**Comment by tierninho** [comment] 2017-06-27 11:07
@Bartholomue Please share more details about your setup.

**Comment by shiftkey** [comment] 2017-06-27 13:32
We're tracking this in #1759 and I think it should be fixed by #1925

**Comment by shiftkey** [comment] 2017-06-27 13:33
Actually, the "bringing it back when I launch it" bit is interesting. Let's see if we can get more info.

**Comment by joshaber** [comment] 2017-07-17 15:17
This is indeed a duplicate of https://github.com/desktop/desktop/issues/1759, fixed by #1925.

**Closed by joshaber** 2017-07-17 15:18 UTC
Labels: bug, more-information-needed
