### ISSUE TITLE
GitHub Desktop encountered an error: spawn where ENOENT

### ISSUE THREAD

**Issue by Aymane01** [desktop/desktop#2178] opened 2017-07-03 11:58 UTC
### Description

When i tried to open the command prompt from GitHub desktop, I've got this error message : 

Error: spawn where ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

### Version

**GitHub Desktop version:** 0.6.2

**OS version:**  Windows 6.3.9600

**Comment by niik** [comment] 2017-07-04 20:20
Hi @Aymane01, we've seen this error around but we've been unable to reproduce it and we'd love your help to get to the bottom of it.

Could you tell us how you're launching the command prompt? Is it by right clicking on a repository in the list of repositories or by clicking on the main menu?

When we launch `cmd.exe` we do so by executing `START cmd` in the working directory of the currently selected repository. A `ENOENT` error usually means that either the working directory doesn't exist or the `START` command doesn't. It seems very odd to me that the start command wouldn't be there as it's a windows built-in so I'm cautiously leaning towards something interesting happening with the working directory of the repository. Could you copy and paste the full working directory path and paste it in here so that we could have a look at it? If you're not comfortable sharing it we'd be interested to know whether it contains any special characters or if it's a very long path.

Furthermore, if you could launch a command prompt manually and try running `START cmd` in it and verify that it launches a new command prompt that would be most helpful.

**Comment by kasra-appscore** [comment] 2017-07-13 23:12
It is about 1-2 months I installed GitHub Desktop and I only tried to open command prompt through repository>open command prompt. I haven't tried any other way yet. After clicking open command prompt menu, the program is closed and give me this error:
GitHub desktop encountered an error
GitHub desktop encountered an unrecoverable error and  will need  to restart. this has been reported to the team, but if.....
After restarting, same thing is happening!

I think I have nothing fancy in my working directory..
C:\wamp64\www\myProject

**Comment by joshaber** [comment] 2017-07-17 15:19
@kasra-appscore That sounds like a different problem. Could you create a new issue so we can track it?

**Comment by joshaber** [comment] 2017-07-17 15:28
@Aymane01 We'll need some more information to be able to debug your issue. Closing until that's provided.

**Closed by joshaber** 2017-07-17 15:28 UTC
Labels: more-information-needed

**Comment by ThomasAunvik** [comment] 2017-10-08 23:50
Ive been having the same problem, the erorr log i get is from github desktop:
```
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.3
OS: Windows 10.0.15063
```

The error i'm getting from launching from CMD in bin\github.bat is:
```
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. Med enerett.

C:\Users\Bruker\AppData\Local\GitHubDesktop\bin>github.bat
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

C:\Users\Bruker\AppData\Local\GitHubDesktop\bin>
```

**Comment by ThomasAunvik** [comment] 2017-10-09 00:11
**Solution?** Open github.bat on administrator mode. And i realized i havent installed git.
![](https://i.imgur.com/JlxYSeL.png)
Hitting "Open without Git", will not work, it will just reopen the same message.

I have now installed git, and i will check how it works:
Ok, i think i got it installed, but it kinda stopped.

**Final Tests:**
Launching GitHub.exe with Administrator and without gives the same error.
Launching from bin\github.bat without Administrator does not work.
Launching from bin\github.bat with Administrator works.

**What to do to fix it.**

- Install Git. https://git-scm.com/download
- Launch Github Desktop via bat file located GitHubDesktop\bin\github.bat with adminstrator mode.

(GitHubDesktop should be located at: "C:\Users\Bruker\AppData\Local")
