### ISSUE TITLE
Connect to Github bug

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#15183] opened 2022-08-27 15:14 UTC
### The problem

Pop up keeps asking me to sign in with your browser even though i successfully signed in already.
![image](https://user-images.githubusercontent.com/59441524/187034988-312a6736-5b79-460f-bf1f-3d667cd69169.png)
![image](https://user-images.githubusercontent.com/59441524/187035013-190b685c-8d9f-47cb-a8a4-8433cb7a82ec.png)

### Release version

Version 3.0.6 x64

### Operating system

Windows 10

### Steps to reproduce the behavior

Open github desktop, select any repo then pop up appears.

**Comment by tsvetilian-ty** [comment] 2022-08-27 16:53
@AllanOBrien thanks for reaching out! The issue is already reported, and you can find a potential fix liked in https://github.com/desktop/desktop/issues/15163#issuecomment-1229139345. I will close this issue, but you can follow the discussion in https://github.com/desktop/desktop/issues/15163 for more information.

**Closed as completed by tsvetilian-ty** 2022-08-27 16:53 UTC

**Comment by sergiou87** [comment] 2022-08-30 11:14
Hi all! We just released 3.0.7 with the fix a few hours ago.

> **Warning**
> If you have installed either the latest beta or one of the test builds I shared (3.0.7-test1 and 3.0.7-test2), **DO NOT** install 3.0.7 unless you don't mind losing your repositories on GitHub Desktop and re-adding them there. They **won't** be removed from your local disk, don't worry about that, they're just removed from the **repository list** inside of GitHub Desktop. This is because those beta and test builds use [Electron](https://electronjs.org) v19, while the latest 3.0.7 has Electron v17 and won't be able to open the repository database once it's been migrated to Electron v19.
>
> We will release a new production build soon with Electron v19 that you can update to. I will let you know again when that happens.

If ☝️ this ☝️ warning doesn't affect you, or you don't mind re-adding all your repos to GitHub Desktop, you can update immediately from the About dialog. If it doesn't find a release (**it's not enabled to _all_ users yet**), try hold <kbd>Alt</kbd> on your keyboard and then click on the `Ensure Last Version` button to force the upgrade:

https://user-images.githubusercontent.com/1083228/187416390-01ee032d-8dca-4635-ab0e-a3c4c87e4c5d.mov

You can also download it from https://desktop.github.com

Thank you for your patience!! 🙇‍♂️
