### ISSUE TITLE
When staging lines and the `lint-staged` hook is used, the entire file is commited

### ISSUE THREAD

**Issue by enriquecaballero** [desktop/desktop#1831] opened 2017-05-30 19:04 UTC
### Description

Instead of commiting the staged lines, GitHub Desktop seems to commit the entire file

### Version

**GitHub Desktop version:** 0.5.8
**OS version:** macOS 10.12.5 (Sierra)

### Steps to Reproduce

1. Stage a few lines in a file
1. Write your commit message
1. Commit

**Expected behaviour:** Only the selected lines should be commited
**Actual behaviour:** The entire file gets commited
**Reproduces how often:** Always

### Logs

```
2017-05-30T18:39:45.831Z - info: Stats reported.
```

#### Additional Information

Might not be useful here, but I should mention that the same thing seems to be happening in the new Atom Git Integration

**Comment by joshaber** [comment] 2017-05-30 19:26
Thanks for opening this up @enriquecaballero!

Would you be able to give us an example of the repository or a file on which this happens?

**Comment by enriquecaballero** [comment] 2017-05-30 19:42
![may-30-2017 15-40-25](https://cloud.githubusercontent.com/assets/7918284/26601619/8bcfd12e-454e-11e7-9496-8bed7d610069.gif)

**Comment by enriquecaballero** [comment] 2017-05-30 19:42
Repo: https://github.com/enriquecaballero/branchsite

**Comment by joshaber** [comment] 2017-06-01 13:39
@enriquecaballero Thank you! Unfortunately I'm still not able to reproduce the bug. It could be related to some git config setting. Could you copy and paste your `.git/config` and your global gitconfig in here?

**Comment by enriquecaballero** [comment] 2017-06-01 15:02
I figured it out. It seems that GitHub Desktop doesn't seem to play well with the `lint-staged` precommit git hook that I have set up in my package.json.

**Comment by enriquecaballero** [comment] 2017-06-01 15:03
The `commitmsg` git hook works fine.

**Comment by joshaber** [comment] 2017-06-01 15:06
Interesting! I'll change the title of this issue then.

**Comment by joshaber** [comment] 2017-06-01 15:07
https://github.com/okonet/lint-staged is the hook in question.

**Comment by enriquecaballero** [comment] 2017-06-01 15:10
Correct. I'm using it to run `prettier` (https://github.com/prettier/prettier) on any staged files. The config I have set up is:
```
{
  ...
  "scripts": {
    ...
    "precommit": "lint-staged",
  },
  "lint-staged": {
    "*.js": [
      "prettier-eslint --write",
      "git add"
    ]
  },
  ...
}
```

**Comment by enriquecaballero** [comment] 2017-06-01 15:13
It might be helpup to also point out, that this set up seems to work in other Git GUI's such as SourceTree and GitKraken.

**Comment by enriquecaballero** [comment] 2017-06-01 15:23
Okay, so I did a little more digging and it seems to be because GitHub Desktop doesn't actually _stage_ the files or lines before commiting. That makes the `git add` step during `lint-stage` to stage every file that is "checked" in any way. Is this expected behavior?

**Comment by shiftkey** [comment] 2017-06-01 15:27
> Okay, so I did a little more digging and it seems to be because GitHub Desktop doesn't actually stage the files or lines before commiting.

To clarify this, we don't apply your selected lines _to the index_ until you start the commit step. And because we don't really trust the state of your index, we'll unstage whatever might already be staged at this time too: https://github.com/desktop/desktop/blob/ba479ecff831a125b964356cdf93e22986c5a3dc/app/src/lib/git/commit.ts#L7

**Comment by enriquecaballero** [comment] 2017-06-01 15:28
hmm

**Comment by enriquecaballero** [comment] 2017-06-01 15:30
That means `git add` definitely won't work with this hook.

**Comment by shiftkey** [comment] 2017-06-01 15:35
> It might be helpful to also point out that this set up seems to work in other Git GUI's such as SourceTree and GitKraken.

To clarify, are you doing the staging of lines in these tools like you are here?

**Comment by enriquecaballero** [comment] 2017-06-01 15:42
@shiftkey In GitKraken, for example, the way one stages lines or files is different than on GitHub Desktop. You actually _stage_ the files or lines -- whatever you stage prior to commiting through the GUI becomes visible through `git status` as well. But to answer your question directly, yes, I do stage certain lines or hunks as I _intend_ to do in GitHub Desktop.

**Comment by enriquecaballero** [comment] 2017-06-01 15:43
@shiftkey They apply the files or selected lines to the index, I believe.

**Comment by shiftkey** [comment] 2017-06-01 15:46
@enriquecaballero cool, just wanted to confirm we weren't just talking about `git add` here

**Comment by enriquecaballero** [comment] 2017-06-01 16:09
@shiftkey Well, right. But then, what's should the solution be here? Should GitHub Desktop apply the selected files, lines, hunks to index?

**Comment by shiftkey** [comment] 2017-06-01 16:11
@enriquecaballero I'm not sure, but I'll leave it to @joshaber who is looking into it to see what the root cause is and what we can do about it

**Comment by joshaber** [comment] 2017-06-02 15:47
@enriquecaballero So this seems to be a known limitation in `lint-staged`. See https://github.com/okonet/lint-staged/issues/62 and https://github.com/okonet/lint-staged#automatically-fix-code-style-with---fix-and-add-to-commit:

>Please note, that it doesn’t work well with committing hunks (git add -p).

And indeed, I can reproduce this same "the whole file gets committed" behavior using the command line.

>It might be helpful to also point out that this set up seems to work in other Git GUI's such as SourceTree and GitKraken.

So I just gave this a shot. I wasn't able to test SourceTree as I don't have an Atlassian account and it appears to be required.

GitKraken does seem to do the right thing, which is interesting and makes me wonder what's going on there. Tower behaves the same way Desktop does.

**Comment by joshaber** [comment] 2017-06-02 16:00
Thinking about this more, I'm betting GitKraken and Sourcetree both use libgit2, in which case they build in hook support themselves. This means that their hook support won't quite match git.git's.

In this case, that happens to work the desired way. But it doesn't match how git itself behaves. So I think this is a won't fix.

If we find that git itself also behaves how GitKraken and Sourcetree do, we can revisit this.

**Closed by joshaber** 2017-06-02 16:00 UTC
Labels: bug, up-for-grabs

**Comment by enriquecaballero** [comment] 2017-06-02 16:04
Okay. I'll keep following GitHub Desktop's progress. Unfortunately, this is something I rely on a lot at work. So until this is fixed, I'll be sticking with other solutions. Thanks for looking into this issue.

**Comment by rodocite** [comment] 2018-03-07 01:30
This is happening to me while contributing to the https://github.com/styled-components/styled-components-website repo. The repo seems to push right away during a commit as well when you're committing to a published branch with an open PR.


![mar-06-2018 17-30-04](https://user-images.githubusercontent.com/5395456/37068531-0e8dfcf2-2164-11e8-93a6-0bb2e4bd510c.gif)

**Comment by shiftkey** [comment] 2018-03-07 01:35
@rodocite does `lint-staged` interfere with the commit itself, or does it just take a while because the commit hook is executing?

**Comment by rodocite** [comment] 2018-03-07 01:45
@shiftkey It looks like the precommit is cause for the lag. Removing it, the entire file still gets committed. Removing the `lint-staged` configuration in package.json completely solves the issue.
