### ISSUE TITLE
Use verified/primary github email for co-authorship

### ISSUE THREAD

**Issue by onebree** [desktop/desktop#4363] opened 2018-03-29 21:47 UTC
## Description

My local git config, as well as my Github settings, allow for using my personal email to sign commits. As per the Github settings/email page, when I hover over the "Primary" badge, I get:

> This email will be used for account-related notifications (e.g. account changes, password resets, billing receipts) as well as any web-based GitHub operations (e.g. edits and merges).

When I perform Github web operations, this email is used as expected. However, if someone assigns me as a co-author through Github Desktop, a no reply email is used instead. And if the project was ever moved off of Github, I imagine that commit signature wouldn't make sense. (I would expect the email to be reachable, in case the github account was closed.)

It seems like this happens when the person you tag does not have their email address public on their Github profile. I don't know if this is the cause though, as I have not looked far into this.

## Version

* GitHub Desktop: 1.1.1
* Operating system: mac OS high sierra, 10.13.3

## Steps to Reproduce

1. Tag a user who's email address is not publicly shown on their Github profile.
2. Make a commit.
3. View the commit message.

### Expected Behavior

See that the user's primary email was listed in the message.

### Actual Behavior

See that the no-reply email was used instead of their primary email.

### Logs

[2018-03-29.desktop.production.log](https://github.com/desktop/desktop/files/1862053/2018-03-29.desktop.production.log)

**Comment by shiftkey** [comment] 2018-03-30 01:20
@onebree thanks for the report! 

> It seems like this happens when the person you tag does not have their email address public on their Github profile. 

This is the behaviour you are seeing. Desktop is using the GitHub API to find details about this contributor, and is unable to find a public email address. You can see the code we're using to resolve the email address for the user here:

https://github.com/desktop/desktop/blob/d328cf729a9540b7db84632f00e77e2c12923037/app/src/ui/lib/author-input.tsx#L278-L298

> And if the project was ever moved off of Github, I imagine that commit signature wouldn't make sense. (I would expect the email to be reachable, in case the github account was closed.)

This is the big downside to the approach, but it still comes back to respecting what the other person has configured. There are other parts of GitHub that are designed around email privacy, like [blocking pushes](https://blog.github.com/2017-04-11-private-emails-now-more-private/) that contain a private email address so that this isn't accidentally made public.

I'm going to close this out as "by design", but feel free to follow up with any other questions you might have around this area of the app.

Also cc @niik for any additional input as he was involved with implementing this features.

**Closed by shiftkey** 2018-03-30 01:20 UTC

**Comment by onebree** [comment] 2018-03-30 01:27
Thank you so much for responding! I see now how this relates to user privacy.

I personally have no issue with my email being associated with commits. I just hide it from my GitHub public profile for the sake of limiting automatic recruitment emails. (In fact I turned it on yesterday, and the same day I got an email. Turned it back off!)

I don't foresee this happening, but if I ended up deleting my GitHub account, would the person who added me as a co-author be able to change the tag to my personal email? At least, without changing the history/commit hash? I've only ever amended messages in git in such a way that changes the hash, so IDK if what I'm asking is even possible.

Again thank you!

**Comment by shiftkey** [comment] 2018-03-30 01:31
> ... would the person who added me as a co-author be able to change the tag to my personal email? At least, without changing the history/commit hash?

Sadly this would involve rewriting the commit history (the hash for a commit is computed from the commit summary and description, among other things) which would cause all sorts of problems.

**Comment by onebree** [comment] 2018-03-30 14:08
Ah, well at least TIL a bit more about git! Thanks again!
