### ISSUE TITLE
Disable focus/highlighting of "Undo" button

### ISSUE THREAD

**Issue by benguild** [desktop/desktop#5013] opened 2018-06-23 08:28 UTC
**Is your feature request related to a problem? Please describe.**
If you accidentally tab to the "Undo" button while trying to type a commit message or description, it undos commits and merges them together if you type a space before noticing.

**Describe the solution you'd like**
Require a mouse click to avoid merging together commits and making things hell.

**Describe alternatives you've considered**
Not using GitHub Desktop.

**Teachability, Documentation, Adoption, Migration Strategy**
Not required

**Comment by iAmWillShepherd** [comment] 2018-06-25 14:54
Thanks for taking the time to open an issue! 🙇 

I think disabling the space bar on this button is the right call here; however, I'd love @desktop/design thoughts on this before moving forward with that as the solution.

**Comment by donokuda** [comment] 2018-06-25 17:10
I'm hesitant on disabling the spacebar since it feels like we're removing an expected behavior. I definitely agree that this isn't an ideal situation to find yourself in.

> Require a mouse click to avoid merging together commits and making things hell.

To clarify, is this the scenario you find yourself in?

1. Do some work and commit. _Undo button pops up at the bottom._
2. Do more work. _Files changed / added are shown in the changes list and are selected._
3. Click undo. _All changes from the previous commit are shown and  _combined_ with the current changes._

If the key part of this is that undoing a previous commit combines the changes with the current work, we could consider popping up a dialog that warns you about how undoing will combine both sets of changes (and then give the option to proceed forward or back out.)

Other potential solutions could include better undo support (e.g., somehow undo the undo) or somehow keeping the two changes separate from each other. I feel like the warning dialog would be a quicker solution to design and implement.

**Comment by benguild** [comment] 2018-06-25 17:12
As long as the warning dialog can't also be confirmed by keys by accident, that should be fine.

**Comment by j-f1** [comment] 2018-06-25 17:18
How about focusing the commit summary and entering the types character of the user types a letter or number while the undo button is focused?

**Comment by shiftkey** [comment] 2018-06-26 11:12
I'm not sure of the best way out of this right now but I'lll cross-reference #4596 where we talked about a similar issue with Undo causing a merge commit to be added to their working directory.

**Comment by billygriffin** [comment] 2019-08-22 16:18
I'm going to close this in favor of #4596 to try to streamline things a bit as it's a very similar issue being discussed, especially since we don't have an agreed upon solution yet.

**Closed by billygriffin** 2019-08-22 16:18 UTC
Labels: bug, priority-3
