### ISSUE TITLE
GitHib Desktop failed to launch 💥

### ISSUE THREAD

**Issue by twalve** [desktop/desktop#1812] opened 2017-05-28 23:48 UTC
### Description

<img width="800" alt="github_desktop" src="https://cloud.githubusercontent.com/assets/89387/26532947/c01c9b9e-4452-11e7-9bd2-af35674fc35e.png">

### Version
**GitHub Desktop version:** 0.5.6

**OS version:** 10.12.5 (16F73)

#### Additional Information

Despite your request for assistance—I attached a screenshot of that—there's also the bug that the incident information can't be copied from the window that you launch.

**Comment by shiftkey** [comment] 2017-05-29 13:51
@twalve this is a duplicate of https://github.com/desktop/desktop/issues/1564 which we believe is fixed in https://github.com/desktop/desktop/pull/1706 and is available in 0.5.7.

Please update and confirm this works for you :tada:

> there's also the bug that the incident information can't be copied from the window that you launch.

I'm pretty sure we made the error text selectable as part https://github.com/desktop/desktop/pull/1562  which reworked this error handling UI.

**Closed by shiftkey** 2017-05-29 13:51 UTC

**Comment by twalve** [comment] 2017-05-30 06:53
Thanks, Brendan
I’m on version 0.5.8, so should have had the changes you’re talking about?
If I see anything I’ll let you know
