### ISSUE TITLE
Unable to change Label of Local Repo

### ISSUE THREAD

**Issue by mrbryo** [desktop/desktop#1929] opened 2017-06-07 18:45 UTC
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

When I clone a repo multiple times it has the same name within the application even though each entry has different local folders. I should be able to set a name so I can easily distinguish between each duplicate. You ask why am I duplicating them? Because I use a different tool to upload changes to the server since I don't get direct server access to use the git command line tool to just update the repo on the server.

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** 0.5.9

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** Mac OS Sierra 10.12.5

### Steps to Reproduce

1. Clone a repo.
2. Clone it again into a new folder.

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** Change the label that shows in the application for the repo.

**Actual behavior:** No way to change the repo label.

**Reproduces how often:** Every time.

![2017-06-07_11-35-10](https://user-images.githubusercontent.com/1635119/26895133-693544be-4b75-11e7-9a62-ea629b1d0bc4.png)

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

Full Log Pasted

> 2017-05-22T18:02:36.418Z - info: Opt in reported.
> 2017-05-23T16:02:20.192Z - info: Stats reported.
> 2017-06-01T21:43:34.128Z - info: Stats reported.
> 2017-06-07T18:26:51.969Z - info: Stats reported.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

This is probably a feature request but maybe I've missed something? I've been using SourceTree for a while now but my company is switching from BitBucket to Github Enterprise. I haven't been able to get SourceTree to work with Github Enterprise with SSH due to authentication via 3rd party service (Okta).

Happy to provide any other information.

**Comment by shiftkey** [comment] 2017-06-07 19:17
Given these are currently Bitbucket repositories these related issues might not be relevant to your use case, but I'll point them out anyway:

 - We recently made a change to show the GitHub repository name instead of the folder name (if applicable) in #1801, but the fallback behaviour for non-GitHub repositories is still to show the folder name.
 - We also have an open issue about grouping repositories by organization: https://github.com/desktop/desktop/issues/1533

> When I clone a repo multiple times it has the same name within the application even though each entry has different local folders. 

Putting aside the label idea - the folder name is the same for each repository, but without a custom label you'd use something like the parent folder to make each repository distinct? Or is that too inflexible?

> You ask why am I duplicating them? Because I use a different tool to upload changes to the server since I don't get direct server access to use the git command line tool to just update the repo on the server.

So these are copies of the same remote repository (so the same remote URL), or do you push these changes to different remotes (and the remotes are organized based on client/customer/organization)?

**Comment by joshaber** [comment] 2017-06-29 20:35
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our [current roadmap](https://github.com/desktop/desktop/blob/master/docs/process/roadmap.md).

I'm going to add the `future-proposal` label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Closed by joshaber** 2017-06-29 20:35 UTC
Labels: enhancement, future-proposal

**Comment by adamreisnz** [comment] 2017-08-28 03:28
I guess there are the two cases we'd have to account for:

1. Having multiple clones of the same repo (can't distinguish those if repo names are used).
2. Having multiple projects with the same folder structure (e.g. `/client`, `/server`) (can't distinguish those if folder names are used).

Being able to apply a custom label would be ideal, as you'll get the most flexibility. Has the idea of a `.github-desktop.rc` been floated yet? It seems like we could store a desired label and perhaps other settings in there.

**Comment by steveward** [comment] 2018-05-02 14:43
Feedback from https://github.com/desktop/desktop/issues/4576:

>It'd be great, if there was a way to rename a repository.
>
>I have a project that is split into two repos: `project/client` and `project/server`. The app shows `client` and `server` only.
>
>I suppose, it could take `.git/description` file into the account. This file is used in `GitWeb` for example.

**Comment by steveward** [comment] 2018-06-15 02:01
From https://github.com/desktop/desktop/issues/4940:

>Having the ability to add a keyword(s) to each repository would be really helpful. Many repositories have names that are not associated with what they actually do.

**Comment by mgleahy** [comment] 2018-09-07 22:07
I have run into this same problem.  I have many repos, including those checked out from GitHub, and a variety of local ones.  I'm running into essentially the same problem as that described in #5544.

I see many other issues being closed and linked to this one...but this issue has been closed for over a year.  Does that mean it will never be addressed?

**Comment by steveward** [comment] 2018-09-19 01:02
@mgleahy thanks for the feedback. The fact that this issue is closed does not necessarily mean it will never be addressed. You can reference this comment by @billygriffin in https://github.com/desktop/desktop/issues/1633#issuecomment-417772108 for some more context about how we are handling `future-proposal` labels.

**Comment by innocuo** [comment] 2018-10-11 21:46
There's a temporary workaround, **although not recommended at all**, is to edit the renderer.js file directly in the installed GithubDesktop, to show the full path instead of the folder name.

It should be in c:/Users/[username]/AppData/Local/GithubDesktop/app1.4.2/resources/app/renderer.js
Look for the text "s.HighlightText,{text:e.name,highlight:this.props.matches.title" and replace e.name with e.path.

Obviously, I'd discourage this unless you know what you're doing, because renderer.js is minimized, so it's not easy to edit, and one mistake and you'll break your app.

If you're compiling from source, you can also change [repository-list-item.tsx](https://github.com/desktop/desktop/blob/master/app/src/ui/repositories-list/repository-list-item.tsx), line 120 ( text={repository.name} ).

A little bit more info for those interested: the indexedDB, that has the repositories list, doesn't have a name field. So there's no label/name/field that can be edited. The app "gets" the name directly from the repository path. I'm guessing that's why this feature hasn't been added, because it'd require some work (like adding new fields in the db, a ui to edit it, etc).

@steveward I think an improvement with less impact may be to display the path name over/under the repo label in tiny grey text, instead of as a tooltip. Additionally, maybe this can be added as an option.

**Comment by billygriffin** [comment] 2018-10-11 21:55
Thanks @innocuo, appreciate the color on this and for the recommendation not to do the workaround unless you're really advanced. 😄 

There are several issues we're trying to look at holistically related to the grouping and presentation/disambiguation of repos. We're going through all the `future-proposal` labeled issues currently, so I don't expect anything to happen on this in the near term, but it's definitely not lost on us and we totally agree that being able to visually understand which similarly-named repo you're looking at would be a nice improvement from where we are today.

**Comment by billygriffin** [comment] 2018-12-20 16:44
Thanks again for the idea! I'm removing `future proposal` in favor of #6460 which tries to capture *all the things*™️ in a more unified way since there have been so many different implementation ideas suggested.

**Comment by tierninho** [comment] 2020-03-25 20:48
Feedback from https://github.com/desktop/desktop/issues/7098

> I'd like ask for consideration to reopen this issue because the other solutions don't solve my use case: I have a repo cloned on my machine twice, that may not make sense but trust me I have my reasons.

> Currently it's not possible to differentiate between the two at all in the UI. This is aggravated by the fact that they jump to different locations when changes are made.

> A suggestion is that the .git/description file seems to match this use case. The app could simply pick this up if set and display it instead of the name. It's an optional label and it does not require any extra UI or data management in the app.

> As a more general comment: as you can see in #6460 it is very hard to provide a perfect structure for all use cases. This would allow for some flexibility that allows users to work around potential unforeseen use cases.

**Comment by varkor** [comment] 2020-03-25 23:09
@tierninho: I very much agree this is still a bit issue. Hovering over a repo takes several seconds before the tooltip pops up. This is a frustrating amount of time to wait to distinguish between two different repos with the same repo name. I would love if repos with the same name could be distinguished by their directory names. I don't think this issue (or https://github.com/desktop/desktop/issues/6460) should have been closed.

**Comment by shiftkey** [comment] 2020-09-14 12:16
I received a request from @webmasterlv over in https://github.com/shiftkey/desktop/issues/340:

> When you have multiple repositories with same names from different projects, there is no clear way to differentiate among them.
>
> I have repositories that happen to have same names such as foo/bar and baz/bar and they look the same. You can hover over it and it shows tooltip, but it takes time switching between projects.
>
> Also, the naming scheme that is now requires to remember what project this repository belongs to. It can at least display full repository name, like foo/bar, not just bar.

**Comment by varkor** [comment] 2020-09-14 14:30
@shiftkey: this is exactly what is raised in the comments above (https://github.com/desktop/desktop/issues/1929#issuecomment-604079169, https://github.com/desktop/desktop/issues/1929#issuecomment-604135194). Could this be taken as an indication the issue is not fixed, and should be reopened? As is, no-one is going to try to fix an issue they think is no longer relevant.

Alternatively, I would be happy to open a new issue if that's preferable.

**Comment by shiftkey** [comment] 2020-09-14 15:24
> Could this be taken as an indication the issue is not fixed, and should be reopened?

@varkor you're gonna have to ask one of the maintainers here about what they'd like to do with the feedback - I'm no longer active on this project.

**Comment by robbiegod** [comment] 2020-12-12 05:44
I'm thinking this is still not addressed?  I have a different situation.  I cloned my repo into a tool like Local WP so i can run the code locally.  It now displays the name as "public" because that is the name of the folder it has to live in in order for local to be able to load the site.  All I want to do is add a label or something so i know what website I am editting. Right now i only have 1 website setup, but when i add another one, its also going to be called "public".  Any help here to add a label or something?

**Comment by mrserb** [comment] 2020-12-13 01:19
Looks like this bug was not fixed yet? All relevant bugs referenced above are closed for some reasons and non of them open, why?

**Comment by marko-cancar** [comment] 2020-12-24 18:43
It's not a bug, but still, I would like to see option to display short paths instead of names...

**Comment by wshaver** [comment] 2021-02-01 23:51
+1 :( Ran into this issue today, where we have one repo with two very different branches. A months-long merge process from two separate teams. Both branches installed locally. Would be lovely to tell which one you're in at a glance. Both in the big repo list, and in the "current repository" thing when the list is closed.

**Comment by tgreen7** [comment] 2021-03-13 03:46
This is really frustrating. I can rename the repo folder but it is not reflected in github desktop. Please add a way to relabel so we can distinguish multiple copies of a single repo.

**Comment by robbiegod** [comment] 2021-03-13 03:49
I did discover one thing and it certainly isn't ideal, but is an ok workaround.  If you hover over the name of  the repo in Github Desktop the alt text will appear giving you the full path info.  So, that is how I have solved my issue.  I'd prefer a label of some sort, but this is ok for now.

**Comment by kj9lj** [comment] 2021-03-13 03:57
> This is really frustrating. I can rename the repo folder but it is not reflected in github desktop. Please add a way to relabel so we can distinguish multiple copies of a single repo.
