### ISSUE TITLE
unable to parse commit because commit message contains ASCII delimiter characters

### ISSUE THREAD

**Issue by ospaarmann** [desktop/desktop#6836] opened 2019-02-13 09:34 UTC
## Description

When I open GitHub Desktop this error appears and keeps popping up: 

![screenshot 2019-02-13 at 10 19 36](https://user-images.githubusercontent.com/308086/52701008-79a64980-2f79-11e9-80f7-415ae65a8196.png)

The second part of the error message is a partial of a commit comment. The full commit looks like this:

```
commit <COMMIT_SHA>
Author: <Author Name> <HiddenName@users.noreply.github.com>
Date:   Fri Feb 8 14:50:24 2019 +0100

    Set queue_sid based on looked up queue (#546)

    Set queue_sid based on looked up queue
    Params sent by Twilio differ from usecase to usecase, so we need to make sure that a `^]queue_sid`^_ is always set, no matter how the call ended up in the queue.
```

This error also pops up whenever I click on the History tab or change the Mac OS Desktop to the one where GitHub Desktop is open.

## Version

* GitHub Desktop: 1.6.1

* Operating system: Mac OS 10.14.2

## Steps to Reproduce

I tried to reproduce it but this seems to only happen if another author commits with these characters in the commit message. Reproducing it locally wasn't possible for me. Since this is a private repo I cannot share it with you.

### Expected Behavior

No error message.

### Actual Behavior

Error message keeps popping up.

**Comment by shiftkey** [comment] 2019-02-13 17:09
@ospaarmann thanks for the report!

There's two places where we bubble up this error:

https://github.com/desktop/desktop/blob/697eb56865b084c915b1cb967bfeaa8a13d2e881/app/src/lib/git/log.ts#L131-L135

https://github.com/desktop/desktop/blob/f9b1afae4a2efd5cd48b59b6f56e4cbe7a1702d0/app/src/lib/git/for-each-ref.ts#L83-L87

In both of these cases we're asking Git to return each the values of each commit delimited, and it looks like a a character in your commit message is being parsed by us incorrectly.

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot which case is the problem one.

> Since this is a private repo I cannot share it with you.

Would you be able to extract the commit to a new repository that you could share? I'm only interested in the commit message and the specific characters inside and how they're tripping our parsing code.

The rough steps to do this:

 - `git checkout --orphan <branchname>` to create a new branch separate from the main history of your repository
 - `git cherry-pick [sha]` to add the problem commit to the branch (will likely cause conflicts)
 - feel free to transform this into an empty commit (`git commit --allow-empty`) as long as the commit message is the same
 - add a new remote representing the public repository that you can share this commit on
 - `git push [new-remote] <branchname>` to push that single commit

**Comment by ospaarmann** [comment] 2019-02-14 13:30
Hi @shiftkey,

thanks for the reply. That is what I suspected. It might mess with the delimiters. 

You can find the repo with the commit message here: https://github.com/ospaarmann/github_desktop_issue_6836

Log file is attached. I hope that helps.

[2019-02-13.desktop.production.log](https://github.com/desktop/desktop/files/2865152/2019-02-13.desktop.production.log)

🚀

**Comment by shiftkey** [comment] 2019-02-14 13:59
@ospaarmann thanks for the sample repository. I was able to clone this down and see the issue for myself, so I think that's all we need to reproduce the bug.

**Comment by ospaarmann** [comment] 2019-02-14 14:21
@shiftkey nice. Can I delete the repository again or do you still need it?

**Comment by shiftkey** [comment] 2019-02-14 14:31
@ospaarmann please leave it up there for the moment. Once we've confirmed a fix and added a regression test we'll let you know that it's safe to cleanup.

**Comment by shiftkey** [comment] 2019-02-15 20:25
Bumping this up to `priority-2` because I see this error inside [`getCommits`](https://github.com/desktop/desktop/blob/a23bdc8f6c573b2bffd0a8bbffb53c12cf911edd/app/src/lib/git/log.ts#L62-L67) which is often called. I've also been able to trigger the issue while the repository is tracked in Desktop but not the selected one. This means the app becomes unusable in this situation.

I'd love to size up the work required to fix this. Going to spend some time to end the working week looking into this.

**Comment by shiftkey** [comment] 2019-02-15 21:07
Some extra context on the issue:

 - when I emit the commit message into the terminal using ` git log --pretty="%b"`, two characters light up in a way that most strings do not, which is _fascinating_ to me:

<img width="1160" src="https://user-images.githubusercontent.com/359239/52883884-d7d25880-3142-11e9-84db-64e6fef4b408.png">

 - copying that output to the clipboard and dumping the string into a hex viewer shows the two problem characters are `1D` and `1F` (highlighted)

<img width="594" alt="screen shot 2019-02-15 at 5 00 36 pm" src="https://user-images.githubusercontent.com/359239/52884052-46afb180-3143-11e9-91b2-ad361a093979.png">
<img width="600" src="https://user-images.githubusercontent.com/359239/52883985-0ea86e80-3143-11e9-9639-3ecbc2f0a907.png">

@ospaarmann I'm not sure how these crept into the commit, but I gather these were just supposed to be plain \`backtick\` characters?

  - the ASCII spec defines these characters as delimiters, and apparently this is also Unicode-specific according to [Wikipedia](https://en.wikipedia.org/wiki/Delimiter#ASCII_delimited_text)

<img width="1064"  src="https://user-images.githubusercontent.com/359239/52884208-c178cc80-3143-11e9-80e7-d3a2589c8242.png">

In terms of our parsing code inside Git commits, we rely on `1F` to not be used for content as this helps us to separate fields of a record, so simply using a different character here feels like an unsatisfactory solution.

@ospaarmann do you know how this commit was crafted? I'd love to know why those special characters were inserted after each backtick.

**Comment by shiftkey** [comment] 2019-02-15 21:10
Dropping this down to `priority-3` because the commit message contains non-printing ASCII characters. You can see that GitHub itself doesn't even know how to handle them:

<img width="1002" src="https://user-images.githubusercontent.com/359239/52884495-862acd80-3144-11e9-94cb-9eb7d41a5d99.png">

**Comment by ospaarmann** [comment] 2019-02-19 10:25
@shiftkey I asked the author of the commit and we aren't sure how these characters crept in there. Only thing I can tell you is that they aren't supposed to be there, that it wasn't copy & paste but that he entered the commit message directly and that he used a German keyboard on a mac.

I don't know if that helps.

**Comment by shiftkey** [comment] 2019-02-19 13:57
@ospaarmann thanks for the extra context.

I'm very hesitant to move away from using `0x1F` as our unit separator for this Git output - the character to use in this situation as defined by the spec -  in order to be able to correctly parse a specific problem commit. I also appreciate that rewriting Git history to cleanup the problem characters might not be possible for you to do currently.

**Comment by j-f1** [comment] 2019-02-19 20:08
@shiftkey If you switch to a noncharacter for the delimiter (FFFE, FFFF, or FDD0 through FDEF), there shouldn’t be any issues.

**Comment by wrzwicky** [comment] 2019-11-29 01:07
Hello? Anyone here? Any plans to fix this? As was pointed out above, you're parsing the string incorrectly, Can I trouble you to possibly parse it correctly?

I hate to play grumpy old man here, but you're parsing a string I don't control, from a file I don't control, and you're doing it wrong. I can't even guess at how to work around such a thing, much less fix it.

**Comment by steveward** [comment] 2020-03-27 13:50
Another case of this reported in https://github.com/desktop/desktop/issues/9373.

**Comment by radzo73** [comment] 2020-07-16 15:21
It's still happening. I ran across this issue when I had a commit description with "" in it, and now the popup won't go away. What can I do to resolve this?

**Comment by muhammadahmadsaeed** [comment] 2020-09-15 12:20
Because of this popup, I am unable to use github desktop. Other git clients work fine though.

**Comment by niik** [comment] 2022-07-01 12:46
I believe this was fixed in https://github.com/desktop/desktop/pull/11486 but never closed.

This issue was my motivation for writing https://github.com/desktop/desktop/pull/11486 in the first place so I'd be disappointed if it didn't solve it. Going to close this out but please report this again if you encounter it.

**Closed by niik** 2022-07-01 12:46 UTC
Labels: bug, priority-2
