### ISSUE TITLE
Certificate Validation issue with updated version of Gitlab

### ISSUE THREAD

**Issue by frenilm** [desktop/desktop#18991] opened 2024-07-17 06:29 UTC
### The problem

We have an in-house GitLab server hosted at 172.16.7.121, accessible on our intranet. This IP is bound to the domain automationgit.meditab.com, and we've added the meditab.com domain certificate. Our repository, cloned using this domain URL, was working fine until now. However, with the latest GitLab version, we're encountering a certification validation error, as shown in the attached screenshot.

Note: The error message pop-up continues after clicking "Add certificate".

### Release version

3.4.2 (x64)

### Operating system

Windows Server 2019

### Steps to reproduce the behavior

1. Clone Repository
2. Pull Changes

### Log files

[2024-07-17.desktop.production.log](https://github.com/user-attachments/files/16261106/2024-07-17.desktop.production.log)

### Screenshots

![Screenshot 2024-07-17 114845](https://github.com/user-attachments/assets/310bf133-8abb-4d66-b3b2-aa4209043dee)
![Screenshot 2024-07-17 114913](https://github.com/user-attachments/assets/2935cbae-19b5-4a18-8d5b-f404b142c36c)

**Comment by steveward** [comment] 2024-07-17 14:04
@frenilm thanks for the issue. Is the problem that the certificate warning is continuing to pop up even after you select `Add certificate`?

**Comment by shamsulsaleh** [comment] 2024-07-18 00:26
im facing the same error. It still keeps continue pop up error message after clicked "Add certificate".

as workaround, i go to previous version folder in GitHubDekstp "C:\<user>\AppData\Local\GitHubDesktop\app-3.4.1" and run "GitHubDesktop.exe". This version no issue.

**Comment by frenilm** [comment] 2024-07-18 05:59
> @frenilm thanks for the issue. Is the problem that the certificate warning is continuing to pop up even after you select `Add certificate`?

@steveward The error message pop-up continues after clicking "Add certificate".

**Comment by frenilm** [comment] 2024-07-18 06:05
@shamsulsaleh  Thank you for your input.

We are already implementing this approach. Since GitHub Desktop has an auto-update feature, we have also renamed the "C:\Users<user>\AppData\Local\GitHubDesktop\Update.exe" file to a random name to prevent automatic updates.

**Comment by steveward** [comment] 2024-07-19 15:47
Also reported in https://github.com/desktop/desktop/issues/18996 with a self-hosted GitLab instance.

**Comment by feeleen** [comment] 2024-07-23 09:08
Having the same issue with fresh standalone GD (after autoupdate)
tons of annoying certificate related popups on each action (fetch, push etc.)

**Comment by steveward** [comment] 2024-07-23 17:50
Reported in https://github.com/desktop/desktop/issues/19005.

**Comment by feeleen** [comment] 2024-08-01 12:33
Noticed strange behaviour

If I push changes to repo, first "Untrusted server" modal popup appears.. if I do nothing here, pressing no buttons and just wait - I see that my commit get's pushed anyway, repo successfully fetched and so on.. )))

**Comment by feeleen** [comment] 2024-08-01 12:38
If I will press the buttons in popups ("add certificate" for example) next popup appears with cert details and then another one

for example, 15 popups (3 х 5 = 15) must be clicked just to push changes to repo

**Comment by geomorillo** [comment] 2024-08-08 16:58
Remove the popups please github desktop is unusable like this

**Comment by Happyrobot33** [comment] 2024-08-08 23:07
can confirm having the same issue, it doesn't even respect having a global or repo specific git config for sslverify. Please fix its genuinely making me look for alternatives

**Comment by steveward** [comment] 2024-08-09 14:05
Has anyone in this thread reached out to GitLab support to see if they have ideas about what would be causing this? Also would be helpful to know who has enabled Git Credential Manager (the setting available in File -> Options -> Advanced).

I have a basic self-hosted Gitlab instance for testing, but was unable to reproduce the issue. Unfortunately there is not much we can do about this from our end, as the issue is specific to Gitlab. I'm going to close this out but if anyone is able to follow up with further information please update this thread.

**Comment by Happyrobot33** [comment] 2024-08-09 14:11
> Has anyone in this thread reached out to GitLab support to see if they have ideas about what would be causing this? Also would be helpful to know who has enabled Git Credential Manager (the setting available in File -> Options -> Advanced).
> 
> I have a basic self-hosted Gitlab instance for testing, but was unable to reproduce the issue. Unfortunately there is not much we can do about this from our end, as the issue is specific to Gitlab. I'm going to close this out but if anyone is able to follow up with further information please update this thread.

This doesnt even seem to be related to gitlab specifically. I use a direct IP reference to my gitlab instance, and i completely understand why its complaining about the https certificate. However, even when i have a global git config to ignore sslverify for that IP, it is still constantly showing the popup like its ignoring the git config option

**Comment by jclark16** [comment] 2024-08-09 16:03
> Has anyone in this thread reached out to GitLab support to see if they have ideas about what would be causing this? Also would be helpful to know who has enabled Git Credential Manager (the setting available in File -> Options -> Advanced).
> 
> I have a basic self-hosted Gitlab instance for testing, but was unable to reproduce the issue. Unfortunately there is not much we can do about this from our end, as the issue is specific to Gitlab. I'm going to close this out but if anyone is able to follow up with further information please update this thread.

This issue has been occurring for me with Git host which is not GitLab.  As @shamsulsaleh implies, the issue appears to be introduced with 3.4.2 as I have also reverted to using 3.4.1 to avoid this issue.

I'm not certain why you are not experiencing it, perhaps it's something to do with how our self-signed certificates are being generated.  But, surely someone could look at the changes in 3.4.2 in this area to determine the cause.  I cannot use an up-to-date version of GitHub Desktop without this and will probably need to look at other options for a Git UI going forward unless this is sorted.

**Comment by feeleen** [comment] 2024-08-09 17:31
> Has anyone in this thread reached out to GitLab support to see if they have ideas about what would be causing this? Also would be helpful to know who has enabled Git Credential Manager (the setting available in File -> Options -> Advanced).
> 
> I have a basic self-hosted Gitlab instance for testing, but was unable to reproduce the issue. Unfortunately there is not much we can do about this from our end, as the issue is specific to Gitlab. I'm going to close this out but if anyone is able to follow up with further information please update this thread.

It's not a Gitlab issue, I use only Github Desktop to access our local git repository
the problem is with untrusted certificates and that Github Desktop ignoring git config settings.

visual studio and TortoiseGit still works fine with our certificate, but Github Desktop fails after one of recent updates

**Comment by feeleen** [comment] 2024-08-09 17:37
> Has anyone in this thread reached out to GitLab support to see if they have ideas about what would be causing this? Also would be helpful to know who has enabled Git Credential Manager (the setting available in File -> Options -> Advanced).
> 
> I have a basic self-hosted Gitlab instance for testing, but was unable to reproduce the issue. Unfortunately there is not much we can do about this from our end, as the issue is specific to Gitlab. I'm going to close this out but if anyone is able to follow up with further information please update this thread.

moreover, that popups in Github Desktop doesn't really affect anything. You just don't click on it and wait, and voila, commit is pushed anyway, repo fetched and so on.

the bug is obvious, please fix it (use untrusted certificate to reproduce)


PS. "Focus on what matters instead of fighting with Git. " Now we fighting with Github Desktop itself ... sad but true

**Comment by geomorillo** [comment] 2024-08-18 03:41
im changing to lazygit until this error is fixed Closed

**Comment by sergiou87** [comment] 2024-08-21 03:35
Hmmm could you try a test build based on the changes you can see in https://github.com/desktop/desktop/pull/19071 ?

Those _may_ fix the problem for **some** of you. If you wanna give it a try, that'd be super helpful! Here you have the links:

- macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktop-arm64.zip
- macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktop-x64.zip
- Windows: https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktopSetup-x64.exe

**Comment by Happyrobot33** [comment] 2024-08-21 04:12
> Hmmm could you try a test build based on the changes you can see in #19071 ?
> 
> Those _may_ fix the problem for **some** of you. If you wanna give it a try, that'd be super helpful! Here you have the links:
> 
> * macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktop-arm64.zip
> * macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktop-x64.zip
> * Windows: https://desktop.githubusercontent.com/releases/3.4.4-test4-f4a38e64/GitHubDesktopSetup-x64.exe

Still constant popups for me when using a local ip / sslverify = false

**Comment by sergiou87** [comment] 2024-08-21 05:23
I _think_ the problem is related to [this check](https://github.com/desktop/desktop/blob/c694b334c6ca3911d03bd9601403c354137acbdf/app/src/lib/api.ts#L2275-L2291) we have to check if a URL with a hostname that is not well-known (e.g. github.com, gitlab.com, bitbucket.org…) could belong to a GitHub Enterprise Server instance. We try to hit the `/meta` endpoint of the git server _regardless_ of any git config (like sslverify).

Just curious, are you able to trust that certificate from Windows/macOS to make this work?

I'm gonna reopen this to investigate it more thoroughly 🕵

**Comment by Happyrobot33** [comment] 2024-08-21 06:02
Pressing the add certificate button still has additional popups showing up for the same Ip

**Comment by Happyrobot33** [comment] 2024-08-21 06:50
I got a dev environment setup, here is what I'm getting at runtime when the popups trigger

```
[28204:0821/024924.930:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -202
debug: [ui] isGitHubHost: failed with endpoint https://192.168.3.121/api/v3
TypeError: Failed to fetch
    at isGitHubHost (E:\Storage\Personal\Coding\desktop\webpack:\app\src\lib\api.ts:2278:28)
    at getEndpointKind (E:\Storage\Personal\Coding\desktop\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:172:29)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at getCredential (E:\Storage\Personal\Coding\desktop\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:101:24)
    at E:\Storage\Personal\Coding\desktop\webpack:\app\src\lib\trampoline\trampoline-credential-helper.ts:236:20
    at TrampolineServer.processCommand (E:\Storage\Personal\Coding\desktop\webpack:\app\src\lib\trampoline\trampoline-server.ts:174:20)
info: [ui] credential-helper: prompt for https://192.168.3.121/: completed
```

so yes, I'm pretty sure your theory is correct, and likely all that needs to be added here is proper fallbacking instead of erroring out fully? is there any reason this method should even return undefined instead of just saying its not a github host if it doesn't find meta?

**Comment by Happyrobot33** [comment] 2024-08-21 07:00
can confirm, making it deliberately always return false before the fetch line prevents the popup from appearing

**Comment by sergiou87** [comment] 2024-08-22 15:24
@Happyrobot33 new test build with the changes from #19149 if you don't mind giving it a try 🙏 

- macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-arm64.zip
- macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-x64.zip
- Windows: https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktopSetup-x64.exe

**Comment by feeleen** [comment] 2024-08-22 15:30
> @Happyrobot33 new test build with the changes from #19149 if you don't mind giving it a try 🙏
> 
> * macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-arm64.zip
> * macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-x64.zip
> * Windows: https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktopSetup-x64.exe

Can confirm that there's no popups anymore! thank you :) (windows)

**Comment by Happyrobot33** [comment] 2024-08-22 16:47
Can confirm, seems to be fixed! Thank you so much!

> @Happyrobot33 new test build with the changes from #19149 if you don't mind giving it a try 🙏
> 
> * macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-arm64.zip
> * macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktop-x64.zip
> * Windows: https://desktop.githubusercontent.com/releases/3.4.4-test5-1c281738/GitHubDesktopSetup-x64.exe

**Comment by sergiou87** [comment] 2024-08-22 17:03
Yay!! Thank you for testing it 🙏🙏🙏

**Comment by geomorillo** [comment] 2024-08-22 21:21
many thanks to you [sergiou87](https://github.com/sergiou87) seems to be fixed you are our hero!!!

**Comment by sergiou87** [comment] 2024-08-23 15:07
I made a new test build with some improvements to avoid hitting that `/meta` endpoint for every single git command #19149 If anyone gives this one a try, please let me know if it breaks anything. Hopefully it won't need more changes 🤞🤞🤞

- macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktop-arm64.zip
- macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktop-x64.zip
- Windows: https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktopSetup-x64.exe

Thank you everyone for your help and patience! 🙏 🙇‍♂

**Comment by feeleen** [comment] 2024-08-26 16:53
> I made a new test build with some improvements to avoid hitting that `/meta` endpoint for every single git command #19149 If anyone gives this one a try, please let me know if it breaks anything. Hopefully it won't need more changes 🤞🤞🤞
> 
> * macOS (Apple silicon): https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktop-arm64.zip
> * macOS (Intel): https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktop-x64.zip
> * Windows: https://desktop.githubusercontent.com/releases/3.4.4-test6-1325ae87/GitHubDesktopSetup-x64.exe
> 
> Thank you everyone for your help and patience! 🙏 🙇‍♂

still works fine for me, no popups

**Closed as completed** 2024-09-30 10:39 UTC
Labels: bug, investigation-needed, priority-2

**Comment by sergiou87** [comment] 2024-10-03 08:58
Hello everyone 👋 

We just released v3.4.6 with this fix (implemented in a different way as you can see in https://github.com/desktop/desktop/pull/19297)

Let us know if that works for you, thank you for your patience!

**Comment by shamsulsaleh** [comment] 2024-10-07 02:09
@sergiou87 downloaded and its working fine. No more popups.

**Comment by Sahar21170** [comment] 2024-10-11 10:04
"Cosmorama"

**Comment by lingkim098** [comment] 2024-10-21 08:20
Hello everyone,

**Comment by lingkim098** [comment] 2024-10-21 08:22
I think I missed a lot of work I'm just new one

**Comment by geomorillo** [comment] 2024-10-21 20:34
im still seeing the popups on Version 3.4.6 (x64)  :(

**Comment by geomorillo** [comment] 2024-11-07 19:22
please help still happening on Version 3.4.9 (x64)

**Comment by steveward** [comment] 2024-11-14 19:50
@geomorillo can you share more details about your setup? What Git hosting service are you using?

**Comment by geomorillo** [comment] 2024-11-16 03:04
,I'm using GitBucket on a vps server without SSL certificates. I'm not too concerned about it since it's just for personal projects,  I'm using it for a while and it's working fine so far. but i get this on Version 3.4.9 (x64)
![image](https://github.com/user-attachments/assets/555033c8-b4b1-4965-9966-103b9ed72548)
so add certificate doesnt work and cancel only reopens the untrusted server window

**Comment by geomorillo** [comment] 2024-12-10 20:21
No fix yet?

**Comment by Sahar21170** [comment] 2024-12-11 16:58
Cosmorama

**Comment by Sahar21170** [comment] 2024-12-11 16:58
Cosmorama

**Comment by geomorillo** [comment] 2025-01-27 13:33
Not working still happening on Version 3.4.15 (x64)

**Comment by tedkrapf** [comment] 2025-12-15 21:18
happening for me in latest version (3.5.4) on Win11
