### ISSUE TITLE
Show hover after 1 sec to be able to see repo path quicker

### ISSUE THREAD

**Issue by tchiaspko** [desktop/desktop#10501] opened 2020-09-03 19:18 UTC
### Describe the feature or problem you’d like to solve
Typically when I am working on multiple change I like to clone the repo with the name of the folder locally matches the branch name.  For example on my local machine i have the following folder structure
reponame_branch1
reponame_branch2
reponame_branch3 

I do this because I don't like using "git stash" and having to store and restore them when switching branch.

When I "add a local repository" from github desktop, they all show up as "reponame" 3 times so I don't know which one is which until I open them with right click and open with terminal
A screenshot is shown below

<img width="660" alt="differt_branch_same_repo" src="https://user-images.githubusercontent.com/49214278/92157523-610db680-eddf-11ea-9c43-49510fee59ae.png">

### Proposed solution
I propose using the folder name as well as the repo name instead of the repo name along

How will it benefit Desktop and its users?
This will allow users who like to use the stash method as well as users who like to clone the branch to a different folder.

### Additional context

Add any other context like screenshots or mockups are helpful, if applicable.

**Comment by tierninho** [comment] 2020-09-03 19:29
@tchiaspko thanks for filing this issue. If you hover over the repo names, you will be able to see the paths.

Regardless, this request sounds like a duplicate of #8175 and #8175, both which were included in #6460. See #8158 (comment) specifically for the current thinking on this. Thanks for using Desktop!

**Comment by tchiaspko** [comment] 2020-09-03 19:36
@tierninho Thanks for the quick reply. I didn't know about the hovering trick.  It takes about 2 seconds for the hover text to appear.  Is it possible to shorten the hovering delay time to 1 sec?

**Comment by tierninho** [comment] 2020-09-03 19:38
Thanks for the suggestion. I will leave this open for others to weigh in on changing it to 1 sec. 👍

**Comment by niik** [comment] 2020-09-04 12:33
Hey @tchiaspko. We'd love to lower the timeout but we're unfortunately limited by Chromium and the operating system here. I'm gonna close this in favor of https://github.com/desktop/desktop/issues/6384 which is about us implementing custom tooltips that would let us work around these limitations.

**Closed by niik** 2020-09-04 12:33 UTC
Labels: enhancement
