### ISSUE TITLE
GPG sign failure

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#18015] opened 2024-01-14 22:05 UTC
### The problem

The Github Desktop fails to sign the commits, while I can sign them via git bash. I can't find the reason why. I specified the path to GPG.exe following the suggestions I found on the internet but it still fails to sign.

ERROR:

gpg: skipped "<key>": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object

### Release version

Version 3.3.6 (x64)

### Operating system

Windows 10

**Comment by steveward** [comment] 2024-01-16 21:37
@o-filenko thanks for the issue. Is [this the guide](https://gist.github.com/xavierfoucrier/c156027fcc6ae23bcee1204199f177da) you followed? I would recommend making sure that your GPG program path is set correctly, as that is usually the cause of this. I'm going to close this out since we already have an existing issue tracking GPG support, but let me know if you have any further questions.

**Closed as completed by steveward** 2024-01-16 21:37 UTC
