### ISSUE TITLE
How can i publish my repository??????It is showing that please upgrade your plan!!!!!!

### ISSUE THREAD

**Issue by beingsport** [desktop/desktop#2190] opened 2017-07-05 16:05 UTC
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

What version of GitHub Desktop are you running? This is displayed under the
`About GitHub Desktop` menu item. If you are running from source, include
the commit by running `git rev-parse HEAD` from your local repository.

**GitHub Desktop version:** [version here]

The operating system you are running on may also help with reproducing the
issue:

 - If you are on macOS, launch `About This Mac` and write down the OS version
   listed.
 - If you are on Windows, open `Command Prompt` and attach the output of this
   command*: `cmd /c ver`

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

If the issue involves a specific public repository, including the information
about that repository will make it is easier to recreate the issue.

If you think screenshots or a GIF recording will help demonstrate the issue
better, feel free to add them here.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Logs

There may be some relevant information in log files generated by GitHub
Desktop:

 - If you are on macOS, attach the most recent log file from:
   `~/Library/Application Support/GitHub Desktop/logs/*.desktop.production.log`
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\\GitHub Desktop\\logs\\*.desktop.production.log`

The log files are organized by date, so see if anything was generated for
today's date.

#### Additional Information

Any additional information, configuration or data that might be necessary to
reproduce the issue.

If you are dealing with a performance issue or regression, attaching a
[Timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)
of the task will help the developers understand the runtime behavior of the
application on your machine.

**Comment by j-f1** [comment] 2017-07-05 16:18
Try unchecking the “Keep this code private” checkbox:
<img width="453" alt="" src="https://user-images.githubusercontent.com/25517624/27874007-0319dd12-617c-11e7-9011-43522e9feba0.png">

**Comment by iAmWillShepherd** [comment] 2017-07-05 16:21
It may be worth adding that question box to make sure user's understand that private repos is a paid feature on GitHub.

**Comment by niik** [comment] 2017-07-05 16:23
> It may be worth adding that question box to make sure user's understand that private repos is a paid feature on GitHub.

I think this should be solved as per @joshaber's suggestion [here](https://github.com/desktop/desktop/issues/2165#issuecomment-312270925)

> Right, we should default to private if the user's on a paid plan because we don't want them to accidentally leak code. But for users on free plans, we should uncheck it and disable it.

Adding a hint/explanation when it's disabled is a good idea though.

I'm going to close this out in favor of #2165.

@beingsport let us know if unchecking that box didn't solve your issue

**Comment by iAmWillShepherd** [comment] 2017-07-05 16:24
@beingsport, @j-f1 is correct. Unchecking that option should allow you to publish just fine. If you want to keep your code private, you need to [upgrade](https://github.com/pricing)

**Closed by niik** 2017-07-05 16:23 UTC

**Comment by beingsport** [comment] 2017-07-05 16:32
Still guys after unchecking..it is showing that Repository creation failed..please help I am trying since morning.

**Comment by beingsport** [comment] 2017-07-05 16:34
And I also can't upgrade as I am having the latest version only.So what should I do now?

**Comment by iAmWillShepherd** [comment] 2017-07-05 17:28
@beingsport, I am unable to reproduce this. Would you mind giving steps to reproduce (including a GIF of this behavior would be awesome) and submitting your log file?

**Comment by beingsport** [comment] 2017-07-05 17:34
Bro that problem has solved but a new one is there..after publishing my Repository..I can't access my website on the URL being sport.github.io...it is showing 404 Eror(There isn't a github pages site here)

**Comment by beingsport** [comment] 2017-07-05 17:35
Bro the version is 0.6.2..and in last attempt my URL was wrong..that was the problem ..but solve this 1 plz

**Comment by j-f1** [comment] 2017-07-05 17:57
It looks like you’re trying to add a page for https://beingsport.github.io. [This help page](https://help.github.com/articles/user-organization-and-project-pages/) should help you with that.

**Comment by beingsport** [comment] 2017-07-06 09:54
Can any one tell me that how i can upload my wordpress website to github?? It will support php format or not ?

**Comment by niik** [comment] 2017-07-06 10:21
> Can any one tell me that how i can upload my wordpress website to github?? It will support php format or not ?

GitHub pages does not support PHP, no. That said,  for support around GitHub pages I'll have to direct you to their [documentation](https://help.github.com/categories/github-pages-basics/) and ultimately to [GitHub support](https://github.com/contact). We will not be able to help you unless your questions relate to GitHub Desktop.

**Comment by beingsport** [comment] 2017-07-06 13:46
Okk bro thanx..

**Comment by vhsferreira** [comment] 2018-01-16 04:37
I'm new in GitHub. I'm now getting " Repository creation failed. (name already exists on this account). Any ideas?
Thanks

**Comment by joshaber** [comment] 2018-01-16 15:46
@vhsferreira Please open a new issue and fill out the issue template so that we can better help you.
