### ISSUE TITLE
Using Undo On Local Commits Can Lead to Data Loss

### ISSUE THREAD

**Issue by dsanders11** [desktop/desktop#5874] opened 2018-10-11 12:39 UTC
## Description

Data loss can happen if you use the 'undo' functionality on a reverted local commit. Noticed this when playing with #5873.

## Version

* GitHub Desktop: 1.4.2

* Operating system: macOS 10.13.6

## Steps to Reproduce

1. Make a change to a file.
2. Make a commit for this change, but do not push, so that it stays local.
3. Go to History tab, right-click on the local commit, 'Revert This Commit'. There are now 2 local commits that haven't been pushed.
4. Go to the Changes tab. Undo both commits.
5. View file on disk, the change made in step 1 should be gone.

### Expected Behavior

The change from step 1 should still be in the file. This is the behavior that happens if you simply skipped step 3 and used undo on the commit from step 2.

### Actual Behavior

When you undo the revert commit, the Changes tab shows the change from step 1 for that file, as if it's not committed by the commit from step 2, and the change is available to commit. I think this is the crux of the issue, as this is when things diverge between GitHub Desktop and the file on disk. If you only undo the revert commit, then view the file on disk, you'll see that it's back to the `HEAD` version, without the change from the commit in step 2, *but* the change is visible under Changes. So the Changes tab at this point is not reflecting the file on disk. Undoing the original commit removes the changes from the Changes tab, so now it reflects what's on disk, and now there's data loss, as the change from step 1 is lost.

**Comment by outofambit** [comment] 2018-10-11 15:46
@dsanders11 thanks for the detailed write up. this sounds like a bug to me! I've marked this as `investigation-needed` so we can reproduce it on our side and start to look into fixes. thanks again!

**Comment by steveward** [comment] 2018-10-11 19:08
@dsanders11 I was able to reproduce this behavior -- thanks again for the detailed steps!

**Comment by dsanders11** [comment] 2018-11-03 14:57
@steveward, ran into a similar issue which I think is probably the same root cause as this one, or at least a similar root cause. However, it's a 'data addition' bug instead of a 'data loss' bug.

1. Get a repo that has a pending commit to fetch
2. Make a commit, don't push, so it's local
3. Fetch the pending commits (should show 1 up, 1 down before clicking)
4. There are now two local commits, the second being the merge commit
5. Undo the merge commit

This leads to any new files in the merged commit being added to your working directory, making a real mess. That's why I called it a data addition bug, it adds stuff that wasn't there before.

**Comment by enioluwa23** [comment] 2019-02-05 14:57
I was going to open a new issue before I found this one but it seems pretty similar so I will comment on here first. My intention was to bring a commit back to staging but ended up wiping out those changes for good. The steps to reproduce are somewhat similar:

1. Clone a repo 
2. Make a new local branch
3. Make a change and commit to the local branch
4. Switch to the `History` tab and right click on the commit and `Revert Commit`
5. Switch back to the `Changes` tab
6. Click the `Undo` button to undo the recent revert commit
7. Switch back to the `History` tab and see the original commit is still there
8. For the last time, switch to the `Changes` tab and see that the `Undo` button is available for the original commit - there will be changes in the staging from the undone revert commit
9. Click the `Undo` button 
10. Original changes lost forever 

Not sure where exactly the issue lies but something about this does not seem right. Please investigate @outofambit @steveward

**Comment by tierninho** [comment] 2019-02-05 16:32
@enioluwa23 Thank you for filing, and including the detailed steps. After reproducing this, it appears to be the same as the original issue.

This seems to be normal behavior **in general**, ie commit, undo, commit, undo, however, we _should_ block the user at some point from undo-ing following a revert on a local branch.

This fix is still outstanding, so it is not clear yet when it will be resolved. Appreciate the patience.

**Comment by Peter92** [comment] 2020-03-13 15:07
I've just hit the same issue when checking if I'd introduced a bug in my changes.

Because I was doing a lot of similar but small changes, I'd not committed anything, and have just lost  2-3 hours of work due to this.

I think instead of blocking the user from undoing after a revert, just don't allow an undo if any of the uncommitted changes would be deleted.

**Comment by megaslav** [comment] 2020-04-29 12:15
This issue is still going on! 
I just lost hours of work because of this, worse part is I didn't even notice until I read this post. I just assumed GitHub Desktop was simply not seeing my changes, so I decided to google for it.

This is a very very bad bug. I don't understand how can you have this software out there?

**Comment by Ekl1p5e** [comment] 2020-05-08 05:16
I lost 3 days worth of work...scared me back over to SourceTree

**Comment by stribuda** [comment] 2020-06-02 12:43
Same here, lost my data after undoing commit.. Please fix it soon!

**Comment by cyndiac** [comment] 2020-07-14 16:58
I also just lost a ton of work, and was wondering if this is related:
Made a local commit 
→ forgot some files, reverted to try to add them (oof, thought that it would do the equivalent of Undo since it was local) 
→ lost all changes, couldn't find a "reset" and probably didn't hit Undo early enough to undo the revert, so I tried to revert my revert for the sake of recovering my files

Now in history I see:
(1) Revert "Revert "commit message"" 
(2) Revert "commit message"
-- where I expect to see "commit message" but it isn't there
(3) Commit before the commit I lost

I want my "commit message" commit back, and (2) lists the commit ID that was reverted, but the commit itself isn't in the history list, which is odd because (2) didn't disappear when (1) was added. Do I still have any chance to get my commit back?

**Comment by tareksanger** [comment] 2020-09-19 21:20
This has still not been fixed - I have lost a days worth of work.

**Comment by doublewhy** [comment] 2020-12-06 12:36
I had exactly the same problem as a topic starter. The whole file was removed instead of undoing the reversion of the commit.

**Comment by subspacefield** [comment] 2020-12-14 19:27
This issue is still occurring, is it going to be addressed?

**Comment by ConorHenry** [comment] 2020-12-29 23:02
I just lost literally about a month of work over this.

**Comment by ConorHenry** [comment] 2020-12-29 23:24
How is it that I have to type in the full name of an repo and my password just to delete a totally empty repo, but there was absolutely no warning after hitting "undo" before it deleted every single file in my directory with no way to recover them? 

How has this issue not been addressed after two years of people reporting data loss due to your product?

**Comment by ConorHenry** [comment] 2020-12-29 23:30
How is a bug that can cause complete data-loss tagged with the same priority as "Make changes list scrollbar consistent with the diff viewer scrollbar"????

**Comment by steveward** [comment] 2021-01-08 21:26
Apologies for not providing an update about this issue sooner. We're exploring ways to make it easier to recover from these types of situations, but for the time being I'd like to provide some more context about what's happening and how to recover from it.

Here’s the equivalent from the command line of what GitHub Desktop is doing when you follow the `revert` -> `undo` -> `undo` pattern:

`git revert <SHA_of_most_recent_commit>`
`git reset —mixed HEAD~1`
`git reset —mixed HEAD~1`

The double-reset is what is causing the changes to be lost from your working directory. Thankfully Git makes it really hard to lose work that has been previously committed to your repository. Since this work was previously committed it can be recovered by running the `git reflog` command from the command line. After running that command you should see the specific SHA and the commit message of your commit that was lost during the undo process. The commit can then be recovered by creating a new branch off of the SHA found in the reflog. Here is the specific command you will need to run from the command line:

`git checkout -b recovery <SHA>`

The `recovery` branch can then be merged back into your main branch in Github Desktop. 

If you have any questions about this process please let me know and I'd be happy to help further.

**Comment by moznualom2** [comment] 2021-01-08 22:02
*Follow me  *https://tinyurl.com/y5cnk96p

**Comment by moznualom2** [comment] 2021-01-08 22:02
*Follow me  *https://tinyurl.com/y5cnk96p

**Comment by moznualom2** [comment] 2021-01-08 22:02
*Follow me  *https://tinyurl.com/y5cnk96p

**Comment by ConorHenry** [comment] 2021-01-26 00:16
Unfortunately none of those tips can recover my data. 

Frankly the Undo button should just be disabled until this is fixed. It’s broken in a way that can lead to devastating data loss. Please disable this feature until it is fixed so nobody else has to go through what I’m going through right now. Please.

**Comment by rjmcf** [comment] 2021-02-12 20:09
Thankfully that recovery fix did actually work for me, but that was a very very scary 20 minutes when I thought I'd lost all that work!

**Closed** 2021-06-04 14:33 UTC
Labels: bug, priority-2

**Comment by cruiser1174** [comment] 2022-06-01 23:52
> Apologies for not providing an update about this issue sooner. We're exploring ways to make it easier to recover from these types of situations, but for the time being I'd like to provide some more context about what's happening and how to recover from it.
> 
> Here’s the equivalent from the command line of what GitHub Desktop is doing when you follow the `revert` -> `undo` -> `undo` pattern:
> 
> `git revert <SHA_of_most_recent_commit>` `git reset —mixed HEAD~1` `git reset —mixed HEAD~1`
> 
> The double-reset is what is causing the changes to be lost from your working directory. Thankfully Git makes it really hard to lose work that has been previously committed to your repository. Since this work was previously committed it can be recovered by running the `git reflog` command from the command line. After running that command you should see the specific SHA and the commit message of your commit that was lost during the undo process. The commit can then be recovered by creating a new branch off of the SHA found in the reflog. Here is the specific command you will need to run from the command line:
> 
> `git checkout -b recovery <SHA>`
> 
> The `recovery` branch can then be merged back into your main branch in Github Desktop.
> 
> If you have any questions about this process please let me know and I'd be happy to help further.

Absolute life saver - thanks!
