### ISSUE TITLE
Can't push tags that were created from cli

### ISSUE THREAD

**Issue by paolocattani** [desktop/desktop#11121] opened 2020-11-25 08:03 UTC
### Describe the bug

Can't push tags that were created from cli.
The only way to create a new tag is by using the option "Create tag..." manually as described [in this blog](https://github.blog/2020-05-12-create-and-push-tags-in-the-latest-github-desktop-2-5-release/) but I'm using an automatic system in my repo.

### Version & OS

Version 2.6.0
Windows 10 Pro

### Steps to reproduce the behavior

1. From git bash create a new tag
`git tag -a <tag> HEAD -m <tag_message>`
2. Open github desktop and commit
3. Push to remote

### Expected behavior
The tags should be pushed to remote

### Actual behavior

The tags doesn't get pushed to remote

### Screenshots

After creating the tag from cli it is visibile in github action
![image](https://user-images.githubusercontent.com/30072995/100197872-47ba6900-2efb-11eb-8637-a4b786675562.png)

But It doesn't get pushed to remote.
![image](https://user-images.githubusercontent.com/30072995/100197986-79cbcb00-2efb-11eb-8b70-a73f0361b091.png)

**Comment by jdngray77** [comment] 2020-11-25 21:21
Can confirm reproducibility on Mac with Desktop 2.6.0.

Curiously, [git-scm](https://git-scm.com/book/en/v2/Git-Basics-Tagging) states that
> By default, the git push command doesn’t transfer tags to remote servers. You will have to explicitly push tags to a shared server after you have created them. This process is just like sharing remote branches — you can run git push origin <tagname>.

Entirely speculation, but it seems as though the explicit 'Create tag...' some kind of a behaviour which enforces the segregated push which the tags requires, as opposed to it being implicitly inherited when handling the tag itself

Edit: 
Tested with `git push` vs `git push origin` ; they both sync the tagged commit to GitHub as expected, bar the tag.
With identical conditions, they both sync two objects and reproduce the same behaviour.

![image](https://i.ibb.co/NSmvM20/Screen-Shot-2020-11-25-at-9-26-23-pm.png)

It's possible this issue may be more widespread than just Desktop.

**Comment by steveward** [comment] 2020-11-25 21:52
Thanks for the report @paolocattani. We previously had the  the `--follow-tags` option feature-flagged in beta, which would push all tags:

https://github.com/desktop/desktop/blob/586294aebd117dee0a9cef90f23ad97e40eed846/app/src/lib/git/push.ts#L76-L78

This was then removed in https://github.com/desktop/desktop/commit/5b5040748900e4a86a48ee2f528be1de05da9cbe. Now we store tags created in GitHub Desktop in localStorage, which is why tags created via the command line are not being pushed. I'm not remembering the specific context around the development decisions for this feature so I'm going to ask @niik to weigh in on this.

**Comment by billygriffin** [comment] 2021-04-14 15:06
Hi folks, thanks for weighing in here and thanks @steveward for linking this. 

We initially had this capability when we built the tags feature, but we had to move to the explicitly tracked list of tags in Desktop after significant performance concerns. The reasoning and tradeoffs are described explicitly here: https://github.com/desktop/desktop/issues/9800

While I know it's not optimal, it's the best solution we could come up with given all the constraints, so I'm going to close this issue as something we don't intend to change. Thanks again and sorry that's it's not a better answer.

**Closed as completed by billygriffin** 2021-04-14 15:06 UTC
Labels: investigation-needed

**Comment by Sparticuz** [comment] 2021-05-11 16:48
@billygriffin @steveward Came looking to figure out why my tags weren't being pushed to Github. When I run `npm version #.#.#`, npm automatically updates my `package.json` and creates a tag, but because it's not created in Desktop, it's not being pushed. Now I must push in Desktop, then go into terminal and `git push --tags origin`. 👎

**Comment by MiguelRipoll23** [comment] 2022-08-28 12:15
Maybe add a way to push the latest created tag?
I'm facing the same issue.

**Comment by nfriacowboy** [comment] 2023-12-01 13:25
Totally support @MiguelRipoll23 proposal! Make total sense to have the option to push manually the tags. 
In my case I'm using the command `yarn version` to manage the version on the package file, and creating the tag accordantly. The current situation has the downside of being hard to maintain the same version on the package and in the tag version because I have no way to push the tag from Github Desktop.

**Comment by nfriacowboy** [comment] 2023-12-01 13:25
Totally support @MiguelRipoll23 proposal! Make total sense to have the option to push manually the tags. 
In my case I'm using the command `yarn version` to manage the version on the package file, and creating the tag accordantly. The current situation has the downside of being hard to maintain the same version on the package and in the tag version because I have not way to push the tag from the

**Comment by steveward** [comment] 2024-01-18 19:58
Feedback from https://github.com/desktop/desktop/issues/18031:

> I'm using a custom script that automatically increases the version of the application and creates a tag based on this version. Worth to mention this is not pushed to Github, but Azure DevOps. I've tested a little and even --follow-tags don't work in this case, maybe a git incompatibility with Azure. So to push tags, I have to use git push --tags origin. Even a menu option where I can do this manually would be fine for me, but currently Github Desktop has no option to force push on tags.
