### ISSUE TITLE
Unable to Load Files Correctly

### ISSUE THREAD

**Issue by derdang** [desktop/desktop#15040] opened 2022-07-27 06:22 UTC
### The problem

This is a long standing project that I work in a team with that has recently come across an issue where we were unable to upload **NEW** files into the github desktop application but are still able to do so in the Github Web version. Upon more research editing and processing modification on existing files can still be done on Github Desktop but new files are not observed to be added to the commit window to complete the uploading the commit in full. We would like a concise answer to resolve this situation.
![Screenshot 2022-07-26 231825](https://user-images.githubusercontent.com/17327792/181175318-7b351f63-6875-4a34-89ab-0689fae3b2f5.png)
![Screenshot 2022-07-26 231854](https://user-images.githubusercontent.com/17327792/181175321-30df473f-968a-42de-8348-1596df86a5f5.png)

The Examples as display above shows the moving of the same file into a different location in the file shows the existing instance of the file being deleted but the move being incomplete despite the file itself being moved over to its new location. This problem is more acute when the file is brand new for which we are not able to meaningfully upload.

### Release version

Version 3.0.5 (x64)

### Operating system

Window 10/11

### Steps to reproduce the behavior

1. Create a File (ex. Hello.txt)
2.File does not appear as a change
3. File cannot be committed as there has been no detectable changes.

**Comment by tsvetilian-ty** [comment] 2022-07-27 09:27
@derdang thanks for the report! I was unable to reproduce the issue. Could you run `git status` and share the output?

**Comment by derdang** [comment] 2022-07-27 21:33
![Screenshot 2022-07-27 143238](https://user-images.githubusercontent.com/17327792/181376311-b01a9256-64c7-4d40-8db5-6a7a12961727.png)

**Comment by derdang** [comment] 2022-07-27 21:35
this specifically affects this repo the other repos that I work with are currently operating normally for context the following is the .gitignore file
![Screenshot 2022-07-27 143516](https://user-images.githubusercontent.com/17327792/181376786-7b67c29f-8eec-4a36-84bf-cf95dbca0831.png)

**Comment by steveward** [comment] 2022-07-28 17:12
@derdang you have this line that is ignoring all file changes:

```
#Ignore everything
*
```

Removing that asterisk should resolve this issue. I'm going to close this out, but let me know if you have further problems.

**Closed as completed by steveward** 2022-07-28 17:12 UTC
