### ISSUE TITLE
Pushing to a branch over SSH from code detaches local branch from origin in GitHub Desktop

### ISSUE THREAD

**Issue by AlexejheroYTB** [desktop/desktop#6547] opened 2019-01-08 07:25 UTC
## Description

I am currently working on a Unity project and have installed the GitHub for Unity asset so that I could push to a branch from code.

In code, I have something like:

    gitClient.AddAndCommit(new List<string>() { "./Assets/Data/version.txt", 
        "./Assets/Data/version.txt.meta" }, "UPDATE VERSION - " + DateTime.Now.ToString(
        CultureInfo.InvariantCulture), null)
    .Then(() => 
        client.Push("git@github.com:QModManager/QModManager.git", "unity-app")

Committing works just fine, and so does pushing (according to git bash). The problem occurs when I open GitHub Desktop. More details in the expected/actual result section below.

## Version

* GitHub Desktop: 1.5.1

* Operating system: Microsoft Windows [Version 10.0.15063]

## Steps to Reproduce

I'm not sure that this would be easily reproduce-able, so I have put a link to the file which handles committing: [GitHubController.cs \[outdated\]](https://github.com/QModManager/QModManager/blob/unity-app/Unity%20App/Assets/Scripts/Editor/GitHubController.cs#L46)

### Expected Behavior

The branch remains attached to the origin branch, with the option to fetch it.

### Actual Behavior

The branch becomes detached from the origin branch, with the option of publishing it. If published, sometimes an error dialog appears saying "Try pulling before pushing" (without having the option to pull), other times it publishes just fine, but that action acts like a push with no commits. 

I have managed to reproduce both behaviors.

![image](https://user-images.githubusercontent.com/32238504/50815432-c7e67e00-1325-11e9-9ddd-91d785dee1a9.png)
![image](https://user-images.githubusercontent.com/32238504/50815447-d0d74f80-1325-11e9-8705-69b2ab16ec1d.png)

## Additional Information

- I had previously set the remote url to SSH using git bash.
- To fix this issue, in code, after pushing to SSH, I added a line to push the same branch to HTTPS, which cannot be done since I have TFA. I get an error, but this seems to allow me to publish the branch without getting the error dialog.

### Logs

[2019-01-08.desktop.production.log](https://github.com/desktop/desktop/files/2735540/2019-01-08.desktop.production.log)

**Comment by shiftkey** [comment] 2019-01-08 12:40
@AlexejheroYTB thanks for the report.

I believe button is reverting to "Publish branch" because there isn't a tracking branch set, which is a flag that you can pass in the Git CLI like this:

```shellsession
# set while pushing
$ git push -u origin master

# or set the current branch
$ git branch -u origin/master
```

I had a peek at the GitHub for Unity code and that seems to do it, but I still suspect that's the case because in the logs there's this error:

```
2019-01-08T06:48:45.580Z - error: [ui] `git -c credential.helper= push origin unity-app --set-upstream --progress` exited with an unexpected code: 1.
To github.com:QModManager/QModManager.git
 ! [rejected]        unity-app -> unity-app (non-fast-forward)
error: failed to push some refs to 'git@github.com:QModManager/QModManager.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

(The error was parsed as 10: The repository has been updated since you last pulled. Try pulling before pushing.)
```

Basically there is some other commits on the remote that you need to `git pull` into your branch, and if the tracking branch was set you'd see this on the button in Desktop, and Desktop would try to pull in those commits.

As a workaround, are you able to use the Git command line to ensure the tracking branch is set?

```shellsession
$ git checkout unity-app
$ git branch -u origin/unity-app
```

After that you should be able to run `git status` and see a mention comparing your current branch to  `origin/unity-app`.

With that in place, Desktop should switch to "Pull origin" and show the ahead/behind commit counts.

**Comment by AlexejheroYTB** [comment] 2019-01-08 12:46
There were actually no commits which needed to be pulled from the remote.

**Comment by shiftkey** [comment] 2019-01-08 12:51
@AlexejheroYTB you'll have to walk me through the details about your setup because the remote server doesn't seem to want to accept your `push`. Could you share the output of these commands?

```
$ git remote -vv
$ git checkout unity-app
$ git status
$ git rev-list --left-right --count unity-app...origin/unity-app
```

**Comment by AlexejheroYTB** [comment] 2019-01-08 13:09
Output of commands while GitHub Desktop is working as expected:

    $ git remove -vv
    origin  git@github.com:QModManager/QModManager.git (fetch)
    origin  git@github.com:QModManager/QModManager.git (push)

    $ git checkout unity-app
    Already on 'unity-app'
    Your branch is up-to-date with 'origin/unity-app'.

    $ git status
    On branch unity-app
    Your branch is up-to-date with 'origin/unity-app'.

    $ git rev-list --left-right --count unity-app...origin/unity-app
    0       0

Output of commands while GitHub Desktop is showing the publish button:  
_(I had to modify GitHubController.cs to enable automatic pushing again since I disabled it after seeing that it does not work properly)_

    $ git remote -vv
    origin  git@github.com:QModManager/QModManager.git (fetch)
    origin  git@github.com:QModManager/QModManager.git (push)

    $ git checkout unity-app
    Already on 'unity-app'
    M       Unity App/Assets/Scripts/Editor/GitHubController.cs

    $ git status
    On branch unity-app
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            modified:   Unity App/Assets/Scripts/Editor/GitHubController.cs

    no changes added to commit (use "git add" and/or "git commit -a")

    $ git rev-list --left-right --count unity-app...origin/unity-app
    1       0

Apart from the changed file. I personally don't see anything else weird. I can try committing GitHubController.cs and running the commands again.

Upon clicking the publish branch button, it acted like a push and pushed the commit. (after running the commands)

**Comment by AlexejheroYTB** [comment] 2019-01-08 13:10
I unfortunately did not run `git fetch --all` though

**Comment by shiftkey** [comment] 2019-01-08 13:19
> (I had to modify GitHubController.cs to enable automatic pushing again since I disabled it after seeing that it does not work properly)

I'm also assuming here that the Unity plugin did set the tracking branch information but maybe it didn't? I'm not sure what else to point to here as your setup looks correct now.

> Upon clicking the publish branch button, it acted like a push and pushed the commit. (after running the commands)

I just want to confirm here that you saw "Push origin" rather than "Publish branch" as that's the Desktop behaviour I've been focused on verifying here.

I'm not spotting anything else strange about this scenario, so I did a fresh clone of this repository over SSH and could see the Publish branch if I did `git branch --unset-upstream` on `unity-app`:

<img width="800" src="https://user-images.githubusercontent.com/359239/50832882-ee0c1e00-1325-11e9-88cc-f0ed5d2871f3.png">

But then when I ran `git branch -u origin/unity-app` it switched back to `Fetch origin` (and also found the PR associated with this branch) because the tracking branch was set:

<img width="824" src="https://user-images.githubusercontent.com/359239/50832902-fc5a3a00-1325-11e9-941a-c30294ecb211.png">

I think that's the root cause of the issue, and will enable you to fetch/push/pull again from Desktop using the right remote branch.

**Comment by AlexejheroYTB** [comment] 2019-01-08 13:21
> I just want to confirm here that you saw "Push origin" rather than "Publish branch" as that's the Desktop behaviour I've been focused on verifying here.
I saw "Publish branch" but the button press acted like a "Push origin", and it pushed the commit that was created from script

**Comment by shiftkey** [comment] 2019-01-08 13:22
> I saw "Publish branch" but the button press acted like a "Push origin", and it pushed the commit that was created from script

Thoughts @desktop/support about how to trigger this state? I'm kind of stumped...

**Comment by AlexejheroYTB** [comment] 2019-01-23 19:55
It is still reproduce-able in the latest version of GitHub Desktop

**Comment by steveward** [comment] 2019-02-06 20:06
@AlexejheroYTB I'm going to look into this further. I'll let you know as soon as I have any updates.

**Comment by steveward** [comment] 2019-09-20 18:38
@AlexejheroYTB I tried a couple of scenarios to reproduce this, but have not yet been successful. Is this something that you are still actively encountering in GitHub Desktop?

**Comment by steveward** [comment] 2020-01-09 18:42
@AlexejheroYTB I'm going to close this out as we have not been able to reproduce this issue. If you are still encountering this issue please let us know.

**Closed by steveward** 2020-01-09 18:42 UTC
Labels: support
