### ISSUE TITLE
Discard Changes confirm button does not work

### ISSUE THREAD

**Issue by jglovier** [desktop/desktop#3951] opened 2018-02-06 17:02 UTC
### Description

When I click the Discard Changes button from the Confirm Discard Changes modal, the button does nothing. However, if I click the Cancel button, the modal is dismissed as expected.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:** `10.13.2`

### Steps to Reproduce

1. Make some changes to files
1. Context click on the filename in the sidebar and select `Discard changes...`
1. Attempt to click `Discard Changes` from the resulting Confirm Discard Changes modal. The button does not work.

![image](https://user-images.githubusercontent.com/1319791/35872617-4803074c-0b35-11e8-818d-f7615ab49973.png)

**Expected behavior:** The `Discard Changes` button should complete the discard changes action.

**Actual behavior:** Nothing happened.

**Reproduces how often:** 100% of the time

### Logs

[2018-02-06.desktop.production.log](https://github.com/desktop/desktop/files/1700001/2018-02-06.desktop.production.log)

**Comment by tierninho** [comment] 2018-02-06 18:40
I tested this and couldn't reproduce. However I spotted this in the logs from above.

> 2018-02-06T16:40:20.038Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 3.496s)
2018-02-06T16:41:12.704Z - warn: [ui] fetchCombinedRefStatus: failed for repository github/github on ref 842086b11f7711fdc779a396efe40201a955ef12
TypeError: Failed to fetch
2018-02-06T16:41:12.717Z - warn: [ui] Error refreshing pull requests for 'github'
TypeError: Failed to fetch
2018-02-06T16:45:01.533Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 7.749s)
2018-02-06T16:50:20.159Z - warn: [ui] fetchCombinedRefStatus: failed for repository github/github on ref 4e31940c48ae040749695ed7080215da7b482954
Error: Server Error
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:162:1)
    at <anonymous>
2018-02-06T16:50:20.161Z - warn: [ui] Error refreshing pull requests for 'github'
Error: Server Error
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:162:1)
    at <anonymous>
2018-02-06T16:50:24.869Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 7.734s)
2018-02-06T16:55:47.805Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 7.082s)
2018-02-06T16:55:48.892Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.076s)
2018-02-06T16:57:20.190Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(committer)%00%(parent)%00%(symref)%00%(subject)%00%(body)%00%(trailers:unfold,only)%00%1F refs/heads refs/remotes (took 1.065s)
2018-02-06T16:58:57.655Z - error: [ui] `git submodule status --` exited with an unexpected code: 128.
fatal: no submodule mapping found in .gitmodules for path 'vendor/gitrpc-cli/libgit2'

**Comment by shiftkey** [comment] 2018-02-06 21:37
@jglovier thanks for the report!

This is a duplicate of #3912 and I've got a fix for it in #3917 awaiting review.

**Closed by shiftkey** 2018-02-06 21:37 UTC
