### ISSUE TITLE
Idea: warning when branches are not up to date

### ISSUE THREAD

**Issue by ruggi99** [desktop/desktop#9347] opened 2020-03-24 10:31 UTC
When fetching the repo from github (e.g. after starting Github desktop), would it be possible to emit a notice to inform the user that the local current branch (e.g. master) is not up to date with the upstream branch?
Without this notice I have to navigate to History Tab and compare the branches each time.
Eventually add a button to merge commits from the upstream.

**Comment by rafeca** [comment] 2020-03-24 18:18
Thanks for reporting the issue!

Desktop shows an indicator with the number of commits that the current branch is behind the remote branch is tracking:

<img width="829" alt="Screenshot 2020-03-24 at 19 15 07" src="https://user-images.githubusercontent.com/408035/77462075-dbcfb000-6e03-11ea-9b2b-ab0e9db383ae.png">

When clicking the "Pull" button it'll fetch the commits from the remote and merge/rebase them in your branch (depending on your git configuration).

Is this what you're looking for?

**Comment by ruggi99** [comment] 2020-03-24 19:08
I've never seen that warning. I'm working an a single repo that is a fork.
I think this works with own repos, but I'm quite sure it doesn't work with forked repos.
When upstream repo is updated with a commit to master branch, I fetch/pull upstream (i.e. the original repo), merge into my master branch locally and then push to origin repo (i.e. my forked repo).
For now I have to navigate to History tab to know if upstream has been updated

**Comment by rafeca** [comment] 2020-03-25 08:28
Thanks for the clarification @ruggi99! Yup the messaging next to the pull/push button only refers to your `origin` remote, so it's not going to take into account the upstream repository when working with forks.

There's still another prompt on the History tab that should notify you when the main branch on the upstream repository of a fork gets updated:

<img width="292" alt="52881834-2cbea080-313c-11e9-8a4d-39b2318341e3" src="https://user-images.githubusercontent.com/408035/77516210-402d5680-6e7a-11ea-8902-0b46ad3d983b.png">

This prompt has been there for a while, but we recently fixed some issues that prevented it from being displayed (see the linked PRs on https://github.com/desktop/desktop/issues/6875). These fix are going to be available on v2.5

**Comment by ruggi99** [comment] 2020-03-25 09:33
I didn't see that PR or related issues.
That prompt will help a lot, that's sure.
How about put an additional prompt in the main view of the changes Tab?
Like in the image below, create a blue notification that tells your branch is not updated with upstream

![Cattura](https://user-images.githubusercontent.com/25064808/77521401-ed0bd180-6e82-11ea-8d74-62b6a2aee340.PNG)

I propose this because, when Desktop is started, it fetches remote repos and the first window that appears is that in the image above, so a notification would be more visible in my opinion

**Comment by rafeca** [comment] 2020-03-25 09:55
Thanks for the suggestion!

In https://github.com/desktop/desktop/issues/6875 there's some exploration about potential next steps for the prompt. A discussed option was as you mention to put it on the "No local changes" screen, but the problem is that this screen is only shown when there are no local changes 😝

I'm going to close this issue in favor of #6675 where there's more context about the prompt.

**Closed by rafeca** 2020-03-25 09:55 UTC
Labels: more-info-needed
