### ISSUE TITLE
Error parsing JSON, possible attempt to deserialize HTML

### ISSUE THREAD

**Issue by niik** [desktop/desktop#1505] opened 2017-05-16 19:07 UTC
Looks to me like we're attempting to parse HTML as JSON somewhere in the app.

```
version: 0.5.3
osVersion: Windows 6.1.7601
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
at file:///app/renderer.js:3:77588
at XMLHttpRequest.J.ae.onreadystatechange (file:///app/renderer.js:3:74786)
```

**Comment by shiftkey** [comment] 2017-05-17 04:52
Disassembling the release app suggests it's the usage inside Octokat.js: https://github.com/philschatz/octokat.js/blob/master/src/requester.js#L177

Without more context, the 500ing of `/user/public_emails` is probably my best guess of the root cause, which is #1508. 

@niik any objections to closing this as a dupe of #1508?

**Comment by shiftkey** [comment] 2017-05-18 04:37
Closing this out as a dupe of #1508.

Reopen if we find another API call that fails in this way that tries to parse HTML as JSON.

**Comment by joshaber** [comment] 2017-05-18 15:19
This is still happening in 0.5.5: https://haystack.githubapp.com/desktop/needles/HxyELOY8y9Ul5-Ui-N3ZVw

**Comment by joshaber** [comment] 2017-05-18 15:34
We're seeing some other variations on this as well:

```
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
at file:///app/renderer.js:3:77567
at XMLHttpRequest.J.ae.onreadystatechange (file:///app/renderer.js:3:74765)
```

```
SyntaxError: Unexpected token : in JSON at position 0
    at JSON.parse (<anonymous>)
at file:///app/renderer.js:3:77567
at XMLHttpRequest.J.ae.onreadystatechange (file:///app/renderer.js:3:74765)
```

**Comment by shiftkey** [comment] 2017-05-25 10:11
Went back to this one this morning and found myself staring at this [snippet](https://github.com/philschatz/octokat.js/blob/v0.8.0/src/requester.js#L176-L180) again in the octokat.js requester:

```js
 if (jqXHR.responseText && ajaxConfig.dataType === 'json') {
    data = JSON.parse(jqXHR.responseText)
} else {
    data = jqXHR.responseText
}
```

And then I realised there's a subtle error in here. `ajaxConfig.dataType` is set by octokat.js as part of what it thinks is the expected response, but for non-JSON results this value isn't going to reflect reality. I thought `jqXHR.dataType` would reflect reality but that's also [set by the library](https://github.com/philschatz/octokat.js/blob/v0.8.0/src/requester.js#L15).

The Correct Way™ would be for the callback to look at the response header, and that seems fine as per the dev tools:

```
> jqXHR.getResponseHeader('Content-Type')
"application/json; charset=utf-8"
```

I'd put together a patch for this but it looks like an update for octokat.js is [imminent](https://github.com/philschatz/octokat.js/commit/581d59e7e358f36cebd835e76e9460b1a90d01ca) which has rewritten the requester code to [this](https://github.com/philschatz/octokat.js/blob/581d59e7e358f36cebd835e76e9460b1a90d01ca/src/requester.js#L138-L144):

```js
// Convert to JSON if we are expecting JSON
// TODO: use a blob if we are expecting a binary
if (!options.isRaw) {
  dataPromise = response.json()
} else {
  dataPromise = response.text()
}
```

This seems a bit more resilient, but I'm not 100% confident on that given how it still relies on `options` rather than poking at the response, so I'm testing this as a [scoped package](https://www.npmjs.com/package/@shiftkey/octokat) and poking around to see if there's anything else I can provide upstream.

**Comment by shiftkey** [comment] 2017-05-25 11:09
I'm experimenting with a scoped package based on the upcoming `0.9.0` release of Octokat.js and https://github.com/philschatz/octokat.js/issues/172 which should improve this situation:

 - [Desktop changes](https://github.com/desktop/desktop/compare/octokat-new-hotness?expand=1)
 - [my scoped package changes](https://github.com/philschatz/octokat.js/compare/master...shiftkey:test-new-release?expand=1)
 
The [additional changes](https://github.com/philschatz/octokat.js/compare/v0.8.0...v0.9.0-0) coming with `0.9.0` make me think we should do a bit more testing but let me know your feels on this @desktop/core if you think we should get this into an update sooner.

**Comment by joshaber** [comment] 2017-05-25 14:11
I'm fine with updating to 0.9.x once your PR lands to get this fixed. It's one of our most common haystack reports, but we don't have users banging down the door about it 🤷‍♂️

**Closed** 2017-05-26 11:53 UTC
Labels: bug, needs-reproduction
