### ISSUE TITLE
Selecting and copying wrapped code from commit details is broken

### ISSUE THREAD

**Issue by adamreisnz** [desktop/desktop#2987] opened 2017-10-08 20:45 UTC
### Description
See title and steps to reproduce.

### Version

**GitHub Desktop version:** 1.0.3
**OS version:** OS X 10.11.5

### Steps to Reproduce
View changes of a past commit, try to copy some code from a multi-line block.

![github-desktop-select-text](https://user-images.githubusercontent.com/490562/31320737-38e7a1fe-acd6-11e7-975a-c5f1af88bf9b.gif)

**Expected behavior:**
To be able to select code spread over multiple lines with no problem

**Actual behavior:**
See gif. Code directly underneath the line I start selecting from is unselectable, selection behaves awkwardly and in unexpected manner when expanding left/right, turns white at times, and the blue selection block grabs entire lines of code at once.

**Reproduces how often:** 100%

**Comment by adamreisnz** [comment] 2017-10-08 22:48
Here's a comparison from the old app with the new app, to further clarify this issue:

Old app, trying to select part of a wrapped line:
![image](https://user-images.githubusercontent.com/490562/31321791-a5adad5e-ace7-11e7-9059-d3d2e3c04583.png)

New app, trying to select the same part:
![image](https://user-images.githubusercontent.com/490562/31321797-b3f3107a-ace7-11e7-9a5e-7ac256d1bd80.png)

Upon hitting CMD-C with the new app, it has only copied the following text:

```
Validator
      .isCour
```

**Comment by niik** [comment] 2017-10-09 06:59
I've seen this behavior as well and it's super annoying.

**Comment by mischnic** [comment] 2017-10-10 08:41
Duplicate of #1551 ?

**Comment by niik** [comment] 2017-10-10 11:59
@mischnic Looks like it it, good spot!

**Closed by niik** 2017-10-10 11:59 UTC
Labels: bug, codemirror
