### ISSUE TITLE
Autentification failed

### ISSUE THREAD

**Issue by alpershin** [desktop/desktop#18610] opened 2024-05-14 06:54 UTC
### The problem

After updating from 3.3.14 to 3.3.17, the application shows an Authentication failed error when trying to connect to a private remote repository

### Release version

3.3.17

### Operating system

Windows 10

### Steps to reproduce the behavior

Try clone any repo from private git

### Log files

2024-05-14T06:21:56.567Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.

### Screenshots

![image](https://github.com/desktop/desktop/assets/66868943/598f80b0-629c-4c42-be6c-4c4492ff3713)

**Comment by debooster** [comment] 2024-05-14 07:30
i have the same issue but this also happens when pushing a local branch to the remote repository. A downgrade helps however the new update will be installed again the next morning.

**Comment by sergiou87** [comment] 2024-05-14 09:16
@debooster @alpershin could you upload the whole log file (after redacting whatever is necessary) so we can get more context about the issue? 🙏 Thank you and sorry for the inconvenience

**Comment by ouzdev** [comment] 2024-05-14 09:46
Hi @alpershin  I experienced the same issue and resolved it using the following command. This command removes Git credentials, and after running it, you will need to log in again:

`git config --system --unset credential.helper`

**Comment by sergiou87** [comment] 2024-05-14 11:30
@ouzdev weird... GitHub Desktop unsets credential.helper in every git invocation. Out of curiosity, does your repo use LFS?

**Comment by ouzdev** [comment] 2024-05-14 13:37
@sergiou87 Yes, my repo does use Git LFS, but I encountered the same error again 😅. I think there might be a problem with the version. It works inconsistently.

**Comment by Williams23678** [comment] 2024-05-14 14:23
am new in here and i will like to know more

**Comment by aolszowka** [comment] 2024-05-14 14:52
Dupe of #18586

**Comment by Vunda** [comment] 2024-05-15 10:44
I have the same issue and with version 3.3.18

**Comment by aolszowka** [comment] 2024-05-15 14:36
@Vunda Did you follow the linked thread? I went ahead and put a recap comment in there that should hopefully get you working again: https://github.com/desktop/desktop/issues/18586#issuecomment-2112715698

**Comment by debooster** [comment] 2024-05-16 08:14
@sergiou87 Included here the log of this morning. I was trying to pull updates from a repo and found that if I try about 4 times. It will actually not ask the last time and did pull in the new changes. 
[this-morning.log](https://github.com/desktop/desktop/files/15331759/this-morning.log)

**Comment by Vunda** [comment] 2024-05-17 07:18
For me today version 3.3.18 asked credentials again and works.

**Comment by Williams23678** [comment] 2024-05-18 04:55
So how do I do it when I'm using my cell phone it doesn't show everything in the phone

**Closed as completed** 2024-05-21 13:09 UTC
Labels: more-info-needed
