### ISSUE TITLE
I have followed the instructions on github pages qnd as per usual NOTHING WORKS!

### ISSUE THREAD

**Issue by Lkskwlkr** [desktop/desktop#4204] opened 2018-03-08 16:25 UTC
## Description

I have followed your instructions on https://pages.github.com/. I am at step number 4 and I am not able to commit and sync my changes. I am looking at a message on the publish branch button that states "Cannot publish unborn HEAD" I have no sync button that is shown in the image at step number 4 on https://pages.github.com/. 

I have been trying to achieve in so many areas of life and trying to learn all the time and it seems that anything that is Internet or technology related only work well for the scum of society. I am getting so sick and tired of my continued effort to be a part of this universe and continually just getting the life sucked out of me! I am emotional and upset and have every right to be because no one ever does their job properly except me.
I am broke and almost broken. :-(

## Version

* GitHub Desktop: Version 1.1.0

* Operating system: Microsoft Windows [Version 10.0.10586]

## Steps to Reproduce

As per https://pages.github.com/

### Expected Behavior

I expected that I would be financially free and able to do what I want as opposed to being a slave to this system. I should have access to an unlimited amount of money to spend as I choose and be able to enjoy life.

### Actual Behavior

I am continually made false promises and lied to!!

**Comment by iAmWillShepherd** [comment] 2018-03-08 18:25
Thanks for taking the time to open an issue! 🙇 

I understand how these things can cause so much frustration; working with tech can be extremely challenging at times. You are not alone in this, and I get burned by Git issues as well.

The issue is really on us as we have not updated that site to reflect the changes in the newest version of GitHub Desktop which is why you’re unable to find the **Sync** button. I apologize for that. We dropped the ball on updating those guides and thanks to you; we will be rectifying this issue soon. So thank you for bringing this to our attention! 😀

I have a suspicion of what may be causing this problem, but I'd like to confirm my theory first. Would you mind taking a screenshot of your project directory? 
1. Open the repo giving you issues
1. Select **Repository** -> **Show in explorer**
1. That will open up the directory for your repo
1. Take a screenshot of GitHub Desktop and the project directory next to one another

![2018-03-08_12-17-36](https://user-images.githubusercontent.com/1715082/37168584-ec398686-22ca-11e8-99c7-86cca3834c71.png)

**Comment by Kubrix** [comment] 2018-03-08 19:10
@Lkskwlkr. Please consider visiting a doctor preferably a qualified psychologist. Why do you deserve to have access to an unlimited amount of money? Considering you made little effort to describe the issue without many emotions you are not ready for work hard enough to have any money.

**Comment by lee-dohm** [comment] 2018-03-08 19:26
@Kubrix your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.

**Comment by niik** [comment] 2018-03-19 09:18
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

Since this issue was created we have updated the instructions on https://pages.github.com to work with the new version of GitHub Desktop.

**Closed by niik** 2018-03-19 09:18 UTC
Labels: more-information-needed
