### ISSUE TITLE
Github desktop failed to launch repeatedly on Win 10

### ISSUE THREAD

**Issue by gykhauth** [desktop/desktop#3303] opened 2017-11-11 12:26 UTC
Error: Mode github-diff-syntax failed to advance stream.
    at at (app\node_modules\codemirror\lib\codemirror.js:1639:1)
    at dt (app\node_modules\codemirror\lib\codemirror.js:1693:1)
    at tt (app\node_modules\codemirror\lib\codemirror.js:1539:1)
    at C:\Users\admin\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:4063:24
    at Jr.iterN (app\node_modules\codemirror\lib\codemirror.js:5539:8)
    at Bs.iterN (app\node_modules\codemirror\lib\codemirror.js:5651:41)
    at Bs.iter (app\node_modules\codemirror\lib\codemirror.js:6047:14)
    at Do (app\node_modules\codemirror\lib\codemirror.js:4058:1)
    at C:\Users\admin\AppData\Local\GitHubDesktop\app-1.0.7\webpack:\app\node_modules\codemirror\lib\codemirror.js:148:21

Version: 1.0.7
OS: Windows 10.0.15063

**Comment by j-f1** [comment] 2017-11-11 12:36
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #3249. The issue has been fixed, and there are [instructions](https://github.com/desktop/desktop/issues/3249#issuecomment-342735764) on how to update to the latest version with the fix.

**Closed** 2017-11-13 12:56 UTC
