### ISSUE TITLE
Toggling Full screen off causes the app to crash and start in full screen afterwards

### ISSUE THREAD

**Issue by Studio384** [desktop/desktop#1502] opened 2017-05-16 18:16 UTC
### Description

Hitting F11 will resize GitHub to use the full screen, however, hitting it again will cause the the app to resize but only show a black screen. Clicking will cause the app to crash but it will continue to run in the Task Manager, resulting in GitHub not opening.

Once the process is killed in the Task Manager, GitHub can be started again but will open in full screen. Repeat.

### Version

**GitHub Desktop version:** 0.5.3

**OS version:** Windows 10 version 1703

### Steps to Reproduce

1. Open GitHub
2. Toggle Full screen mode on
3. Toggle Full screen mode off

**Expected behaviour:** GitHub shows a normal window again

**Actual behaviour:** The app becomes fully black, any further interaction with any window will cause the black window to disappear.

**Reproduces how often:** 100%

### Logs

````
2017-05-16T17:52:20.724Z - error: Uncaught exception on main process
````

**Comment by tierninho** [comment] 2017-05-16 18:19
related to: https://github.com/desktop/desktop/issues/1436

**Comment by Studio384** [comment] 2017-05-16 18:21
@tierninho: Ha indeed, I only searched in the open issues. Either way, this is a real issue, didn't have anything to do with your VM.

**Comment by shiftkey** [comment] 2017-05-16 22:37
@Studio384 there's probably some other information I need to reproduce this (probably needs to be fixed in Electron/Chromium, so bear with me).

What monitors and display drivers do you have configured?

**Comment by Studio384** [comment] 2017-05-17 06:40
I'm using a Surface Pro 4 with the latest driver installed.

**Comment by fablabgsd** [comment] 2017-05-22 13:35
I have the same issue.
Windows 10 v1607
 dell precision 5520 laptop.
super high resolution - usually running to dual monitors but still occurs on laptop display.

tried uninstalling, but when reinstalled it retained the full screen mode so i went in and deleted the folders where it stores login info, settings etc and it opens normally, but if i go to fullscreen it repeats.

**Comment by majacobs47** [comment] 2017-05-22 17:56
I have run into the same problem.
Windows 10.014393 Build 14393
Dell Optiplex 7010
I also have a dual monitor setup

I tried uninstalling, but mine also retained the full screen mode. I did not try deleting the data manually. When I get this error, I have to go task manager and end the task in order to restart the program.

**Comment by Studio384** [comment] 2017-06-06 18:34
Just to let you all know that I'm unable to reproduce this again on version 0.5.9. Not sure in which version it got fixed for me, I have not tested ever since 0.5.3 (for obvious reasons) but accidentically toggled it just now, but i returned back to windowed-mode just fine.

**Comment by tierninho** [comment] 2017-06-09 17:27
So in v0.6.0, using Windows 10, this is still occurring for me. I noticed that when the user toggles away from full-screen mode, the Task Manager kills the App running and keeps all background processes running. I imagine the App should still be running.

In this pic, the black screen is up for me. Notice, Desktop is missing from Apps:
<img width="287" alt="screen shot 2017-06-09 at 1 21 06 pm" src="https://user-images.githubusercontent.com/14828183/26986815-2d98f56a-4d17-11e7-8fb4-8e70089b3f44.png">

**Comment by illusive-man** [comment] 2017-06-12 19:59
Same behavior here. Exiting full screen mode  crashes the app.

BTW I wonder why is there so much processes open by the app? Sometimes more than 10!

**Comment by joshaber** [comment] 2017-06-13 16:17
It looks like https://github.com/electron/electron/pull/9645 may fix this on the Electron side of life.

**Comment by LKarnai** [comment] 2017-06-17 06:41
Same exact issue here.

Windows 10 Pro
1607 version
14393.1358 build

**Comment by NewBreed117** [comment] 2017-06-18 18:57
I have the same issue.

Windows 10 Home
1703 version
15063.413 build

**Comment by byerlyb20** [comment] 2017-06-21 17:12
This has probably been found awhile ago by most of you, but I'll comment just for reference. If your GitHub Desktop is stuck in the fullscreen "loop", it can be fixed by quite simply deleting the `window-state.json` file located in the GitHub Desktop folder. Mine was located at `C:\Users\(home)\AppData\Roaming\GitHub Desktop`. In case you couldn't tell, I stumbled upon the same issue accidentally.

GitHub Desktop Version 0.6.1
Windows 10 Home
Version 1607
Build 14393.1358

**Comment by Studio384** [comment] 2017-06-21 23:33
The issue is back for me in version 0.6.1, Windows 10 Pro, version 1703. Which is weird because it first did work in this version on the same device, it only poped up after a reinstall of Windows.

**Comment by shiftkey** [comment] 2017-06-22 10:40
> If your GitHub Desktop is stuck in the fullscreen "loop", it can be fixed by quite simply deleting the window-state.json file located in the GitHub Desktop folder. Mine was located at C:\Users\(home)\AppData\Roaming\GitHub Desktop. In case you couldn't tell, I stumbled upon the same issue accidentally.

This is a great clue @byerlyb20 - thanks for suggesting it! This file is related to `electron-window-state` - it uses this file as a [backing store](https://github.com/mawie81/electron-window-state/blob/master/index.js#L17) for it's configuration values between sessions. I think there's enough clues here to dig into whether it's something in our code or in the event handlers that `electron-window-state` creates that are to blame here...

**Comment by shiftkey** [comment] 2017-06-22 10:49
@joshaber good point on that PR, I'll keep an eye on whether that makes it into a 1.6.x release.

**Comment by darkn3rd** [comment] 2017-07-10 06:47
This happening as well.  I tried to install it, but had no GUI installation, it just magically appeared, then disappeared.  Then I saw four Github Desktop.exe processes and AutoHotKey processes in TaskManager, but no GUI.

**Comment by shiftkey** [comment] 2017-07-24 20:21
@darkn3rd please open a new issue with reproduction steps if you can create it consistently with the latest version

**Comment by WJJeske** [comment] 2017-08-27 18:23
As it turns out, GH Desktop doesn't support the standard Windows taskbar windows management menu (Move, Resize, Minimize, etc. in Win 10 1703. In my case (Dell Precision 5510, Xeon, 32G) the GHD window sticks in the position of the auxiliary monitor and is thus inaccessible if I undock and attempt to use the app. Deleting window-state.json as @byerlyb20  suggests above is the only way I've been able to recover the UI. Thanks for that!!

**Comment by shiftkey** [comment] 2017-08-28 08:52
@WJJeske we talked about the lack of Windows taskbar features in #2311

**Comment by shiftkey** [comment] 2017-09-04 02:15
There's a few intertwined setups here without good repros, and I've not been able to recreate the crash for a dual-monitor setup, but I've been able find one annoying bug when using fullscreen mode that might be close to the root cause.

Here's my steps:

 - nuke whatever is in your `%APPDATA%\GitHub Desktop\window-state.json`
 - launch the app
 - <kbd>F11</kbd> to maximise the app
 - close the app
 - relaunch the app - it'll fill the screen and should be maximised
 - <kbd>F11</kbd> to try and restore the app

I'm really not sure what's happened here but a black rectangle is definitely not what we want here:

<img width="1440" src="https://user-images.githubusercontent.com/359239/30009097-f312bc3c-9168-11e7-8353-cdad1f2d0af2.png">

In Electron 1.7.x (see #2582) this will restore the window state when using the primary monitor, but not when you do this on a secondary monitor (nothing is displayed, not even a black rectangle, but rogue `GitHubDesktop.exe` processes hang around) so I don't think this is completely resolved.

**Closed** 2017-09-07 11:32 UTC
Labels: bug, Windows

**Comment by wenlock** [comment] 2017-10-30 15:57
Thanks @shiftkey ! this got me worked around on my Mac. 
```
rm "$HOME/Library/Application Support/GitHub Desktop/window-state.json"
```

**Comment by joshaber** [comment] 2017-10-30 16:02
@wenlock sent me his `window-state.json` prior to clearing it:

```json
{
  "width": 960,
  "height": 660,
  "x": 412,
  "y": 325,
  "isMaximized": false,
  "isFullScreen": true,
  "displayBounds": { "x": -3440, "y": -390, "width": 3440, "height": 1440 }
}
```

**Comment by wenlock** [comment] 2017-10-30 16:06
![image](https://user-images.githubusercontent.com/1907138/32181459-a125a5a0-bd51-11e7-999a-3f96ec46bcfd.png)

Screen shot for what it looks like.

**Comment by blosloos** [comment] 2017-10-31 08:58
Am now also facing a black GitHub Desktop window right away after the installation (identical to what is shown by shiftkey user above). Deleting the `window-state.json` or toggling is of no help; the app seems responsive, but just all blacked. Am on Win10 64bit, build 15063.674

**Comment by vladorepic** [comment] 2018-07-17 13:46
Still having this issue and am therefore not able to use GitHub Desktop..

**Comment by shiftkey** [comment] 2018-07-17 14:24
@blosloos @vladorepic please have a look at #3921 which talks about issues relating to hardware acceleration with certain graphics driver sets. We also have a [workaround](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#i-get-a-black-screen-when-launching-desktop) for these situations that might address the issue.

**Comment by les113** [comment] 2019-03-24 16:51
Poor UI.
Not resolved.
