### ISSUE TITLE
Protected branch warning unhelpfully appears in sidebar at all times

### ISSUE THREAD

**Issue by adamlui** [desktop/desktop#18896] opened 2024-06-26 04:36 UTC
### The problem

![image](https://github.com/desktop/desktop/assets/10906554/16d498a9-673d-42f4-b840-7e515430eef6)

This unhelpful warning recently started appearing and is not dismissable

### Release version

Version 3.4.1 (x64)

### Operating system

Windows 10

### Screenshots

![image](https://github.com/desktop/desktop/assets/10906554/fad69b02-88dc-4425-a28b-e82c72de90c2)

### Additional context

It is possible this is a new feature, but not very well thought out since it cannot be dismissed and takes away from precious vertical screen real estate (not everyone is working from enormous fancy monitors at a highly paid job)

**Comment by niik** [comment] 2024-06-26 11:18
Hey @adamlui, thanks for reaching out! This feature shipped back in 2019 as part of Desktop 2.2.4 so it's not new. Is it possible it's showing up for you now because you (or the repository owner) have recently enabled branch protections?

Our motivation for showing that warning is that when a branch is protected you're likely not going to be able to push to it and we heard feedback frequently from users who had accidentally committed changes on their default branch (which was protected) and then had to go to some lengths to figure out how to get rid of those commits and get them onto a new branch to contribute.

We believe the feature has served its purpose as we've seen a drastic decline in support requests related to accidentally committing to protected branches.

Could you tell me a little more about your use case here? Are you looking to commit to the protected branch anyway or is it the area that the warning occupies that's the main issue?

**Comment by adamlui** [comment] 2024-06-26 11:24
I didn't recently protect it and actually can't get it to appear again, so I guess the glitch is it wrongly detects unprotected branches as protected

**Comment by niik** [comment] 2024-06-26 11:40
Hey, thanks for reporting back. Yeah if that warning shows up and you haven't enabled branch protections then something is off somewhere. I've never seen a report of that before so let us know if it pops back up and we'll take another look. In the meantime there's nothing actionable here so I'm gonna close this out. Cheers!

**Closed as completed by niik** 2024-06-26 11:40 UTC

**Comment by adamlui** [comment] 2024-06-26 11:42
But I proved the glitch exists, and the action to take is investigate why it happens to stop it

**Comment by adamlui** [comment] 2024-06-26 11:51
@niik how come the ability to re-open closed issues is disabled in this repo i don't understand

**Comment by niik** [comment] 2024-06-26 12:07
> But I proved the glitch exists, and the action to take is investigate why it happens to stop it

If you are able to reproduce this issue please let us know either by commenting here or by opening a new issue. We unfortunately don't have the resources to be digging into an isolated issue without more reports of it where neither of us can reproduce it. As for the warning itself we are not of the opinion that the warning should be dismissible.

**Comment by adamlui** [comment] 2024-06-26 12:14
Why must an issue be "reproducible" for it to factually exist though? Clearly it exists unless you accuse me of photoshopping? Therefore it's open not closed? And what are these resources you speak of, the ridiculous salary you're paid to fix bugs like this you instead close because it's below your pay grade? Shall I snitch to your boss perhaps?

**Comment by niik** [comment] 2024-06-26 12:19
Hey @adamlui. I understand that you're frustrated but be aware that your comment is considered a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/development/CODE_OF_CONDUCT.md) as it was unprofessional or derogatory. You may consider this an official warning.

**Comment by adamlui** [comment] 2024-06-26 12:20
Your only job is make Desktop work, user has reported and proven a glitch exists making it not work as intended (you yourself admitting "something is off somewhere" if this is happening) therefore you insinuate the victim is lying to haphazardly close and demand reproduction, or are just outright lazy to abandon your job post of make Desktop work. Therefore you are the one being unprofessional and derogatory. You may consider tthis an official warning. I am screenshotting this interaction in case you do what I suspect you are about to do (to be sent to your superiors and to executives)

**Comment by adamlui** [comment] 2024-06-26 12:21
i.e. I have violated nothing and you are retaliating beacuse I have angered you for exposing you are being unprofessional and I am threatening to report your unprofessionalism, so you are like trying to scare me to stop (making it even more unprofessional) when it is not against any rule to do this.
