### ISSUE TITLE
Publishing an upstream branch to the origin repository

### ISSUE THREAD

**Issue by msftrncs** [desktop/desktop#7980] opened 2019-07-18 03:08 UTC
While trying to catch up to the changes to Desktop, bringing my fork up to date, this repository has switched from 'master' to 'development' as the primary branch, so I was trying to figure out how to use Desktop to do that, and I struggled a little.

I was able to select the 'upstream/development' branch.  However, now the fetch button read 'Fetch upstream', and there was no publish option I could find.   So I instead switched over to VS Code (opened from the repository menu of Desktop of course) and selected 'Publish' and poof, the 'development' branch was now published to my fork, and Desktop's fetch button switched to 'Fetch origin'.

Is support for this workflow supposed to exist?  I think Desktop fails to consider publishing to the origin.  The 'No local changes' screen seems to be stuck on the fact that I am looking at the upstream branch (says its 'already Published'), but from Git's point of view its a local branch and it should be available for publishing to origin, as was easily done with VS Code.

(Desktop 2.1.1-beta2)

**Comment by msftrncs** [comment] 2019-07-18 03:16
To provide some minor details, as I wrote this issue, I deleted the branch (development) that I published to origin (was published by VS Code and deleted using Desktop) (and its local copy), and attempted to repeat the process, my details above are from the second attempt with Desktop using the upstream branch, so, if in fact I missed it the first time, its not there the second time.  :)

**Comment by iAmWillShepherd** [comment] 2019-07-18 15:58
@msftrncs 

> While trying to catch up to the changes to Desktop, bringing my fork up to date, this repository has switched from 'master' to 'development' as the primary branch, so I was trying to figure out how to use Desktop to do that, and I struggled a little.

It seems like you are experiencing https://github.com/desktop/desktop/issues/5709.

> I was able to select the 'upstream/development' branch. However, now the fetch button read 'Fetch upstream', and there was no publish option I could find. So I instead switched over to VS Code (opened from the repository menu of Desktop of course) and selected 'Publish' and poof, the 'development' branch was now published to my fork, and Desktop's fetch button switched to 'Fetch origin'.

I've reproduced this using my fork of Desktop and this is indeed a bug. I've included more details and a set of reproduction steps to help whoever picks this up understand what's going on.

---

After cloning my fork, I made sure both remotes were available:

```sh
------------------------------------------------------------
~/Desktop/desktop(master) » git remote                          iamwill@artemis
origin
upstream
```

Then I checked what refs each remote was tracking:

**`origin`**
```sh
------------------------------------------------------------
~/Desktop/desktop/.git/refs/remotes(master) » tree origin       iamwill@artemis
origin
└── HEAD

0 directories, 1 file
```

**`upstream`**
```sh
------------------------------------------------------------
~/Desktop/desktop/.git/refs/remotes(master) » tree upstream     iamwill@artemis
upstream
├── Blank-State-Open-In-Shell
├── Fix-Multiple-Files-SVG
├── Hide-White-Space-In-Diff
├── Missing-Upstream-Branch
├── NoExistingRemoteBranchHandler
├── Reset-My-HEAD
├── development
├── github-release-generator
├── master
├── upgrade-react-transition-group
└── upgrade-to-latest-react

0 directories, 11 files
```

I checked out `upstream/development` and the `PushPullButton` text is _Fetch upstream_

![Screen Shot 2019-07-18 at 10 12 18 AM](https://user-images.githubusercontent.com/1715082/61469311-8ffb6b80-a944-11e9-9dc0-ea123065fd00.png)

**Comment by billygriffin** [comment] 2019-07-18 16:21
@msftrncs We've been discussing this internally. Because it's not likely to be low effort, and it represents a *really* uncommon use case where there's both a long-running fork *and* the default branch of the upstream repo changes names, I'm going to close this for now. We've never seen this come up as an issue in the past, and I'm glad you were able to get it figured out. We're definitely open to reopening the issue if we see it come up for others too. Sorry it became an issue for you.

**Closed by billygriffin** 2019-07-18 16:21 UTC
Labels: bug, priority-2

**Comment by msftrncs** [comment] 2019-07-19 00:21
@billygriffin, I just want to clarify, that even though the issue of the name change / change of the default branch in the 'upstream' Desktop repository was why I was trying to do this, the issue I am reporting here is actually regarding not being able to 'transfer' a branch from one remote to another remote.   The need to transfer a branch probably comes up more often, though usually work is merged between branches (or into new branches).

I do agree, just trying to find the right solution to handle the transfer (publish) to another remote could be tricky, and would not be a trivial fix or enhancement.

**Comment by billygriffin** [comment] 2019-07-19 16:34
Thanks for the additional context @msftrncs, that makes sense. I don't remember having seen that previously as a request or something that folks have had problems with in Desktop. I'm definitely onboard with it theoretically, but given constrained resources, we have to be increasingly rigorous with the things we prioritize or accept/review PRs for. If you think it's likely to be a broader problem than maybe I'm appreciating, happy to consider that.
