### ISSUE TITLE
Not seeing the branches

### ISSUE THREAD

**Issue by mephisto83** [desktop/desktop#2533] opened 2017-08-23 11:01 UTC
The branches of my repository, are no longer visible.

### Description

The branches of my repository, are no longer visible.

### Version

**GitHub Desktop version:** 0.8.1-beta1

**OS version:** Windows 10

### Steps to Reproduce

1. Open App
1. Pick Repository
1. Check for branches.

**Expected behavior:** I expect to see my branches

**Actual behavior:** I see an empty list.

**Reproduces how often:** Every time.

**Comment by j-f1** [comment] 2017-08-23 11:15
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2522. The issue got fixed in #2531, and it’ll be out in the next update.

**Closed** 2017-08-23 12:40 UTC

**Comment by shiftkey** [comment] 2017-08-23 22:38
FYI: the `0.8.1-beta2` update is now available and contains this fix.
