### ISSUE TITLE
Allow  right click on the "Current Repository" section

### ISSUE THREAD

**Issue by msavin** [desktop/desktop#13371] opened 2021-11-24 05:39 UTC
### Describe the feature or problem you’d like to solve

Currently, you can right click on any repository in your list to open in Terminal, text editor, etc. However, this convenient menu is not accessible when you right click on Current Repository. As a result, you have to perform unnecessary clicks to get tere.

### Proposed solution

Improved UI/UX and reduce the amount of clicks by offering the same context menu when right-clicking on current repository.

### Additional context

<img width="385" alt="Screen Shot 2021-11-24 at 11 06 12 AM" src="https://user-images.githubusercontent.com/2031235/143181150-08bbaf8e-cefd-455f-b02a-9de095cd29ce.png">
.

**Comment by tidy-dev** [comment] 2021-11-30 11:56
This is a duplicate of #13148. Closing in favor of tracking there. Feel free to thumbs up the other issue to show support.

**Closed as completed by tidy-dev** 2021-11-30 11:56 UTC
Labels: enhancement
