### ISSUE TITLE
Dirty index warning from aborted force push

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7103] opened 2019-03-15 20:44 UTC
Not sure if this is a one-off or if there may be a bug buried in here, but these are the steps which led to a "dirty index" warning. Note: I had a LFS file in my commits, which was unintentional.

- Have a LFS file committed
- Get into a force push with lease state
- Click the force push button, wait for it to fail
- State reverts back to Push origin with rebase
- Cannot commit files due to "dirty index" as DS Store file present 
- Fixed with `git rebase --abort`

```
install.ts:31 Executing push: git -c credential.helper= -c protocol.version=2 push origin testPR:testPR --force-with-lease --progress (took 209.624s)
install.ts:23 `git -c credential.helper= -c protocol.version=2 push origin testPR:testPR --force-with-lease --progress` exited with an unexpected code: 1.
Enumerating objects: 171, done.
2install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: TestWebAppProject - tierninho (has token)
install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: TestWebAppProject - tierninho (has token)
2install.ts:31 [AppStore.withAuthenticatingUser] account found for repository: TestWebAppProject - tierninho (has token)
install.ts:31 Executing pull: git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin (took 9.440s)
install.ts:23 `git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin` exited with an unexpected code: 1.
First, rewinding head to replay your work on top of it...

fatal: Dirty index: cannot apply patches (dirty: .DS_Store TestWebAppProject/Controllers/HomeController.cs sdfsd)

error @ install.ts:23
git @ core.ts:171
_tickCallback @ internal/process/next_tick.js:68
async function (async)
git @ core.ts:107
pull @ pull.ts:100
async function (async)
pull @ pull.ts:57
gitStore.performFailableOperation @ app-store.ts:2895
performFailableOperation @ git-store.ts:729
withPushPullFetch @ app-store.ts:2893
async function (async)
withPushPullFetch @ app-store.ts:2821
withPushPullFetch @ app-store.ts:2801
performPull @ app-store.ts:2821
withAuthenticatingUser @ app-store.ts:2812
withAuthenticatingUser @ app-store.ts:3903
_pull @ app-store.ts:2811
pull @ dispatcher.ts:334
PushPullButton.performAction @ push-pull-button.tsx:265
ToolbarButton.onClick.event @ button.tsx:111
Button.onClick.event @ button.tsx:147
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:201
executeDispatch @ react-dom.development.js:466
executeDispatchesInOrder @ react-dom.development.js:488
executeDispatchesAndRelease @ react-dom.development.js:586
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:597
forEachAccumulated @ react-dom.development.js:567
runEventsInBatch @ react-dom.development.js:728
runExtractedEventsInBatch @ react-dom.development.js:737
handleTopLevel @ react-dom.development.js:4201
batchedUpdates @ react-dom.development.js:12537
batchedUpdates @ react-dom.development.js:1939
dispatchEvent @ react-dom.development.js:4282
interactiveUpdates @ react-dom.development.js:12592
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
install.ts:23 `git commit -F -` exited with an unexpected code: 1.
On branch testPR
Your branch and 'origin/testPR' have diverged,
and have 64 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You are currently rebasing branch 'testPR' on '1074d88'.

nothing to commit, working tree clean

(The error was parsed as 17: There are no changes to commit.)
```

8b061eac07, mac

**Comment by shiftkey** [comment] 2019-03-19 13:11
I'm going to focus on this bit as this seems to be the root cause:

```
install.ts:31 Executing pull: git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin (took 9.440s)
install.ts:23 `git -c credential.helper= -c protocol.version=2 pull --recurse-submodules --progress origin` exited with an unexpected code: 1.
First, rewinding head to replay your work on top of it...

fatal: Dirty index: cannot apply patches (dirty: .DS_Store TestWebAppProject/Controllers/HomeController.cs sdfsd)
``` 

Some extra terminology to explain before we proceed:

> A **dirty work tree** is where you have changes that are not added to the index.
> A work tree that is not dirty is a **clean work tree**.
>
> A **dirty index** is where you have changes already added to it (in other words, "git diff --cached" will report some changes).
> A **clean index** matches the HEAD.
>
> [[source]](https://gitster.livejournal.com/29060.html)

The "dirty index" message here suggests there were some staged changes at the time the `git pull --rebase` was run, which is blocking the rebase from doing it's work. I was expecting a different error to occur here, based on my exploration of how "pull with rebase" and working directory changes relate in an earlier issue: https://github.com/desktop/desktop/issues/3422#issuecomment-468699803

![](https://user-images.githubusercontent.com/359239/53647023-f93b4600-3c12-11e9-8561-2ed588f4a6d7.png)

We can look into handling this error better in here, but it might require work in `dugite` to raise a new error code:

https://github.com/desktop/desktop/blob/08632922908b138da950427ad7e1ac1ce184c992/app/src/lib/git/pull.ts#L63-L66

On the second part:

```
install.ts:23 `git commit -F -` exited with an unexpected code: 1.
On branch testPR
Your branch and 'origin/testPR' have diverged,
and have 64 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You are currently rebasing branch 'testPR' on '1074d88'.

nothing to commit, working tree clean

(The error was parsed as 17: There are no changes to commit.)
```

I'm curious how you were able to enable the commit button (because there were files in the changes list) but then have it report "no changes to commit" because there were no changed files found. It feels related to the previous step but I'm not sure we have enough context from these logs, and a working Git repository.

**Comment by shiftkey** [comment] 2019-03-19 13:13
@tierninho I'm going to leave this in the milestone to tighten up the error handling in both of these cases, but once that is completed I'm going to move it out of the milestone until we can better understand the Git repository state that triggered these errors. Let me know if there's anything else you can recall from the repro steps.

**Comment by tierninho** [comment] 2019-03-19 17:53
@shiftkey Thank you for the detailed update. Not sure about the exact steps as the "hidden" LFS file threw me off. Not sure I can repro either.

**Comment by shiftkey** [comment] 2019-03-19 18:38
I've opened https://github.com/desktop/dugite/pull/320 to add support for a new error code to handle the first scenario. The second one does not need a new error code because it looks like it maps to `DugiteError.NothingToCommit`:

> (The error was parsed as 17: There are no changes to commit.)

**Comment by shiftkey** [comment] 2019-04-03 15:37
Dropping this one from the current milestone because I'm not sure how often it will happen, and it's blocked on upstream changes to `dugite`.

**Comment by shiftkey** [comment] 2019-04-17 21:15
I'm going to close this out for the moment because this has been an isolated report, and a future upgrade to `dugite` will add the new error code from https://github.com/desktop/dugite/pull/320 and need to be handled in Desktop, which has the context around where it should be handled.

I'm also not aware of other reports about this error, so I'm not sure how easy it is to reproduce:

```
nstall.ts:23 `git commit -F -` exited with an unexpected code: 1.
On branch testPR
Your branch and 'origin/testPR' have diverged,
and have 64 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You are currently rebasing branch 'testPR' on '1074d88'.

nothing to commit, working tree clean

(The error was parsed as 17: There are no changes to commit.)
```

**Closed by shiftkey** 2019-04-17 21:15 UTC

**Comment by lilgurl** [comment] 2019-10-31 10:50
[bugreport.zip](https://github.com/desktop/desktop/files/3793392/bugreport.zip)
