### ISSUE TITLE
Update to 2.2.4 forgets all repos

### ISSUE THREAD

**Issue by Sjors** [desktop/desktop#8788] opened 2019-12-12 14:29 UTC
### Describe the bug

When I updated to 2.2.4 the application showed me a launch wizard where I could add repositories. Everything I added before was gone (from the app, not from disk).

### Version & OS

Version 2.2.4 on macOS 10.15.2

### Steps to reproduce the behavior

It's not fully reproducable: I have another macOS machine at the same version which did not lose any data.

### Logs

This shows a launch of 2.2.3 and then 2.2.4:

```
2019-12-12T14:21:18.110Z - info: [ui] [AppStore] loading 9 repositories from store
2019-12-12T14:21:18.113Z - info: [ui] [AppStore] found account: Sjors (Sjors Provoost)
2019-12-12T14:21:18.701Z - info: [ui] launching: 2.2.3 (Mac OS 10.15.2)
2019-12-12T14:21:18.701Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2019-12-12T14:21:19.623Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.427s)
2019-12-12T14:21:19.623Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.031s)
2019-12-12T14:21:19.887Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:21:19.904Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:21:20.580Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.898s)
2019-12-12T14:21:27.336Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.889s)
2019-12-12T14:21:27.831Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:21:38.822Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:22:22.494Z - info: [ui] [AppStore] loading 0 repositories from store
2019-12-12T14:22:22.494Z - info: [ui] [AppStore] found account: Sjors (Sjors Provoost)
2019-12-12T14:22:22.954Z - info: [ui] launching: 2.2.4 (Mac OS 10.15.2)
2019-12-12T14:22:22.955Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2019-12-12T14:23:19.619Z - info: [ui] [AppStore] adding repository at /############# to store
2019-12-12T14:23:20.165Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:23:20.984Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:23:21.012Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:23:22.948Z - info: [ui] [BranchPruner] No branches to prune.
2019-12-12T14:24:14.646Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:27:08.051Z - info: [ui] Current tutorial step is NotApplicable
2019-12-12T14:27:38.536Z - info: [ui] Current tutorial step is NotApplicable
```

**Comment by niik** [comment] 2019-12-12 14:34
Hi @Sjors, I'm sorry to hear that! This is the first report we've seen about this and we haven't experienced anything like it during our testing either I'm afraid. If you're able to reproduce this or if you discover any more clues we'd love to hear about it.

It sounds like the database in which we store repositories either became corrupted or reset through some other means in the middle of the update.

I hope this didn't cause to much of a problem for you. If you have a lot of repositories to add back I'd like to offer a small tip which is that it's possible to drag more than one folder from Finder to the Desktop app to add multiple repositories in one fell swoop.

**Comment by Sjors** [comment] 2019-12-12 15:02
It's not a big problem for me, but seemed worth reporting.

**Comment by kuychaco** [comment] 2019-12-13 02:45
@Sjors glad to hear it wasn't too big a problem for you! 

I'm gonna go ahead and close this for now since it doesn't seem like there's any clear action to take from it, but (as @niik said) please feel free to re-open the issue
> If you're able to reproduce this or if you discover any more clues we'd love to hear about it.

**Closed by kuychaco** 2019-12-13 02:45 UTC
