### ISSUE TITLE
Image comparison max height/width does not make sense in relation to application and resolution.

### ISSUE THREAD

**Issue by MrDingodile** [desktop/desktop#6644] opened 2019-01-16 16:45 UTC
I believe this has to do with high DPI scaling (using a 2160p 16:9 monitor) in relation to very large images when previewed in Github Desktop.

This is what I see when comparing a texture file: 
![27572b8d9532f0442639fc89d82b3eaf](https://user-images.githubusercontent.com/42971310/51264193-3b3b6000-19b6-11e9-82cf-53fffd065d4e.jpg)

By editing the source with developer tools I can set the max width and max height myself, and produce what I'd expect to see: 
![acd0586077eb370536d30d7bb5ee2b30](https://user-images.githubusercontent.com/42971310/51264231-527a4d80-19b6-11e9-91ec-8258969ba095.jpg)

Given a simple config option to set the max height/width of image preview I would be able to proceed nicely, even if the default failed like in my case.

Hopefully this issue can be resolved quickly with a simple config option.

Cheers.

**Comment by tierninho** [comment] 2019-01-16 17:08
@MrDingodile Many thanks for filing this and adding the dev tools tips, however it looks to be a duplicate of this #2480, with this [comment](https://github.com/desktop/desktop/issues/2480#issuecomment-451779032) capturing the overall issue.

Closing for now but happy to reopen if it turns out to be another underlying issue with images.

**Closed by tierninho** 2019-01-16 17:08 UTC

**Comment by MrDingodile** [comment] 2019-01-17 15:00
> @MrDingodile Many thanks for filing this and adding the dev tools tips, however it looks to be a duplicate of this #2480, with this [comment](https://github.com/desktop/desktop/issues/2480#issuecomment-451779032) capturing the overall issue.
> 
> Closing for now but happy to reopen if it turns out to be another underlying issue with images.

Very well may be a duplicate, I wasn't getting search results I could without doubt say was the same issue, so figured I'd post it even as a duplicate.

Should I add my findings as a comment on #2480 ?

**Comment by tierninho** [comment] 2019-01-17 16:32
@MrDingodile many thanks for the follow up and offer to post your findings in #2480. I think it is okay to leave things as-is, because the two issues are now linked together and the person who fixes the underlying issue will see your issue referenced. 👍

**Comment by MrDingodile** [comment] 2019-01-17 17:21
Alright np.
