### ISSUE TITLE
Unsupported value ''*'' for git config key 'core.safecrlf'

### ISSUE THREAD

**Issue by gjcarver** [desktop/desktop#19047] opened 2024-08-01 09:31 UTC
### The problem

Unsupported value ''*'' for git config key 'core.safecrlf'

### Release version

Version 3.3.18 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Create a new Repository on your local drive.

### Log files

[2024-08-01.desktop.production.log](https://github.com/user-attachments/files/16454032/2024-08-01.desktop.production.log)

**Comment by sergiou87** [comment] 2024-08-01 14:54
Dupe of https://github.com/desktop/desktop/issues/19049#issuecomment-2263277815

**Closed as completed by sergiou87** 2024-08-01 14:54 UTC
