### ISSUE TITLE
An unknown error "Failed to execute getStatus: ENOENT"

### ISSUE THREAD

**Issue by underscoore** [desktop/desktop#9604] opened 2020-04-22 19:07 UTC
### An unknown error "Failed to execute getStatus: ENOENT" is appearing 

when I push my code from GitHub Desktop

### Steps to reproduce the behavior

1. Commit code 
2. Click on 'push' button 
3. And observe, an error popup will appear.

### refer to the attached screenshot <gitdesktop.png>
![gitdesktop](https://user-images.githubusercontent.com/21233349/80023055-95e93300-84fa-11ea-8e84-5fe392cec623.PNG)

**Comment by manciuszz** [comment] 2020-04-22 19:48
I also encountered this issue today. First I got something along the lines "cannot spawn ask-pass-trampoline.bat" after clicking the push button, then the whole application locked out with the "ENOENT" error - everytime you click close button, the error would pop-up again, making you to kill the process via task manager. After that GitHubDesktop.exe just stopped working altogether.

A quick check to "%localAppData%/GitHubDesktop/app-2.4.2" showed me that the "resources" folder was pretty much empty. Therefore, I deleted "%localAppData%/GitHubDesktop/app-2.4.2" folder and everything was working again.

**Comment by rafeca** [comment] 2020-04-23 12:03
Thanks for reporting this @ajaybit ! We'll need a bit more information in order to investigate this issue.

- Can you paste your GitHub Desktop logs when you encountered this problem? You can find them In the GitHub Desktop menu by going to `Help -> Show logs in Explorer`.
- Does this happen consistently? Does this happen only when pushing code? On every repository?

**Comment by ajaybit** [comment] 2020-04-28 06:12
Hi, @rafeca, now the Desktop app stops launching but found **.log** file in AppData hopes this might help.
Please find the attached file <SquirrelStup.log>

[SquirrelSetup.log](https://github.com/desktop/desktop/files/4543682/SquirrelSetup.log)

**Comment by ajaybit** [comment] 2020-04-28 06:17
Closed by mistake.

**Comment by Albarnie** [comment] 2020-04-28 06:20
Also getting the error, not after pushing but while looking at commit logs

**Comment by WizardOfMenlo** [comment] 2020-04-28 21:34
Hi there, I also am experiencing this issue, on a clean Windows 10 Install and while opening previously cloned repositories. 
Find attached the logs for convenience
[2020-04-28.desktop.production.log](https://github.com/desktop/desktop/files/4548621/2020-04-28.desktop.production.log)

**Comment by cgorlla** [comment] 2020-05-01 01:17
Just started having this issue. It must've been something in the previous update. It worked fine before.

**Comment by tierninho** [comment] 2020-05-01 01:37
@Albarnie @cgorlla Thank you for the comments. Any chance you could upload your log files as well? It would much appreciated and helpful. See the Help menu in Desktop.

**Comment by steveward** [comment] 2020-05-01 15:27
We're continuing to investigate this issue. If you are encountering the error try opening up File Explorer and deleting the `%LocalAppData%\GItHubDesktop` directory. You will then need to grab the installer again from http://desktop.github.com and reinstall. Your repositories and account data should remain intact since that is stored in `%AppData%\GitHub Desktop`. Let us know with a reply if that gets things working for you.

**Comment by Thothore** [comment] 2020-05-02 16:04
@steveward 

It just worked for me ! thanks

**Comment by cgorlla** [comment] 2020-05-02 16:15
@tierninho The issue has resolved itself. No idea why, I didn't do anything other than a reboot.

**Comment by kwhjvdkamp** [comment] 2020-05-11 08:21
C:\Users\info\AppData\Roaming\GitHub Desktop\logs

Hereby my logs. Several logs show errors saying fatal possibly due to a not very describtive popup telling something about "Failed to execute getStatus: ENOENT". This pop-up is bothering me already for a few days now, it suddenly started, I'm not 100% sure if it came along with the latest updated I performed, I don't dare to make a solid statement on that, but it seems to be....
Version 2.4.3. was released approx 10 days ago?

Performed steps:
YES I have removed sub folder 'GItHubDesktop' from %LocalAppData%\* and re-installed Github for desktop as stated
YES: I did use version 2.4.3. before
YES: I tried to commit, push, pull e.g. some branches with and without my VPN running. No luck it still pops-up (not consistently though, but is does...)

**Comment by fxteguhab** [comment] 2020-05-15 01:45
had the same error
@steveward solution worked for me. thx

**Comment by kwhjvdkamp** [comment] 2020-05-15 07:08
Thanks @fxteguhab for your advice. After ugrading Desktop three days ago (version 2.5.0) I end up with two versions ?? But the pretty meaningless message popped-up once more after upgrading and till  stays away. I delete folder 2.4.3.
![2020_05_15_08_56_14_Window](https://user-images.githubusercontent.com/9660415/82021460-2561ac00-968b-11ea-8712-08c58e60fe0e.png)

**Comment by abdullahseba** [comment] 2020-07-11 20:02
I have just started seeing this issue.  The popups accumulate and I have to either restart the application or click about a million times to get rid of each popup!  I tried @steveward's recommendation but it doesn't appear to have any effect.

**Comment by JenR8ed** [comment] 2020-09-11 05:31
I also got this issue. Please investigate the error and assign some people. Thanks!
[error "Failed to execute getStatus: ENOENT"](https://user-images.githubusercontent.com/21233349/80023055-95e93300-84fa-11ea-8e84-5fe392cec623.PNG)

**Comment by st4lk3r87** [comment] 2020-09-20 11:39
I get the same error too

**Comment by InfiniteCoder96** [comment] 2020-09-28 15:07
I get the same error

**Comment by Purvang-Acharya** [comment] 2020-09-30 11:47
I got the same error but steveward's solution worked, thank you

**Comment by bsamesh** [comment] 2020-10-20 14:26
Got the same error.
Will this solution affect the changes that I've committed and yet succeeded to push?

**Comment by knougitrepos** [comment] 2020-11-09 02:04
same here , having no idea at all how to figure it out ... gotta try reset my repos first

**Comment by SDCRoman** [comment] 2020-11-25 12:34
Same error also for me since today!

**Comment by steveward** [comment] 2020-11-25 16:58
See my reply [here](https://github.com/desktop/desktop/issues/9604#issuecomment-622433801) to see if that gets things working for you.

**Comment by TRI99ERED** [comment] 2020-12-21 14:29
Had the same issue today.

**Comment by Gioele-Bencivenga** [comment] 2021-01-03 00:24
> We're continuing to investigate this issue. If you are encountering the error try opening up File Explorer and deleting the `%LocalAppData%\GItHubDesktop` directory. You will then need to grab the installer again from http://desktop.github.com and reinstall. Your repositories and account data should remain intact since that is stored in `%AppData%\GitHub Desktop`. Let us know with a reply if that gets things working for you.

Thanks @steveward, this works for me.
I have to do it again each month so it's not optimal, but it lets me work.

**Comment by Dylan-Beppu** [comment] 2021-01-07 03:58
I've been having the same issue for about a month by now

**Comment by kanaksony** [comment] 2021-01-28 08:22
Same error.. long time issue -  no fix :(

![image](https://user-images.githubusercontent.com/6097596/106109866-0307b400-6170-11eb-80c2-c6c0811fd380.png)

**Comment by steveward** [comment] 2021-01-28 16:03
@kanaksony did you try the fix mentioned [here](https://github.com/desktop/desktop/issues/9604#issuecomment-622433801)?

**Comment by JiashuWu** [comment] 2021-03-05 04:02
Encountered the same issue unexpectedly. 

Followed the solution by @steveward and it worked. 

@kanaksony You can give it a try. 



> @kanaksony did you try the fix mentioned [here](https://github.com/desktop/desktop/issues/9604#issuecomment-622433801)?

**Comment by saxenageoffrey** [comment] 2021-03-10 11:49
> I also encountered this issue today. First I got something along the lines "cannot spawn ask-pass-trampoline.bat" after clicking the push button, then the whole application locked out with the "ENOENT" error - everytime you click close button, the error would pop-up again, making you to kill the process via task manager. After that GitHubDesktop.exe just stopped working altogether.
> 
> A quick check to "%localAppData%/GitHubDesktop/app-2.4.2" showed me that the "resources" folder was pretty much empty. Therefore, I deleted "%localAppData%/GitHubDesktop/app-2.4.2" folder and everything was working again.

This helped, Thank you!

**Comment by saxenageoffrey** [comment] 2021-03-10 11:50
I guess this happens every time there's an update. I'm not sure though.

**Comment by abdullahseba** [comment] 2021-03-10 12:24
Although I had this issue for some time as mentioned earlier, it has since disappeared!  Updates made no difference at the time.

**Comment by Reni-Yeno-H** [comment] 2021-04-13 10:56
I got produced this error when I reproduce github desktop to screen as a shortcut. Fixed it when the error gave an option (after clicking many oks inside github desktop) to remove the github desktop shortcut back to application folder.

**Comment by Reni-Yeno-H** [comment] 2021-04-13 10:58
I produced this error when I created Github Desktop to screen as a shortcut. Fixed it when the error gave an option (after clicking many oks inside Github Desktop) to remove the Github Desktop shortcut back to application folder.

**Comment by racheldotey** [comment] 2021-04-18 16:12
**Possible Solution:**
I found that this issue was happening for me because one of my local git repository folders was renamed. Git Hub Desktop was trying to find the repo but the directory path was invalid. This triggered the `"Failed to execute getStatus: ENOENT"` to pop up every few minutes when working with any repo in Git Hub Desktop.

**Comment by SugarD-x** [comment] 2021-09-15 23:49
I'm not sure if this is of much help for research, but I received this error after a system crash while GitHub Desktop was open. Upon restarting the computer, (and the application), the message popped up. My best guess is some kind of corruption in the program's searching of the file path is at fault.

**Comment by lmbarns** [comment] 2021-09-26 23:22
I updated github desktop last week, created a new repo, added my stuff, committed locally.

Today I worked on my project, committed changes and it spammed that message repeatedly and wouldn't let me close github desktop. After pressing the button 50 or so times it finally went away and said it couldn't find the repo, asked to try again or locate it.

I located it, still threw the same error.

I downloaded the installer from steveward's post, ran it without deleting the local appdata, just installed over it, then it works again.

**Comment by GlauciusZacher** [comment] 2021-12-21 22:35
Same error here, then i try clicking in "Clone again", and got this error.

![2021-12-21](https://user-images.githubusercontent.com/13805205/147006847-487706de-4dec-47b0-aa0f-e81e05599782.png)


Some files disappeared from this folder (C:\Users\glauc\AppData\Local\GitHubDesktop\app-2.9.6\resources\app), so i've downloaded GitHub Desktop again, runned the installer (without uninstalling), and the error gone away (and the files came back to this places).

**Comment by chloethegremlin** [comment] 2022-04-21 18:06
> 

Fix worked for me. Thank you!

**Comment by LowPowerLab** [comment] 2022-05-11 13:49
> We're continuing to investigate this issue. If you are encountering the error try opening up File Explorer and deleting the `%LocalAppData%\GItHubDesktop` directory. You will then need to grab the installer again from http://desktop.github.com and reinstall. Your repositories and account data should remain intact since that is stored in `%AppData%\GitHub Desktop`. Let us know with a reply if that gets things working for you.

This worked for me as well. Deleted content from this folder: C:\.....\AppData\Local\GitHubDesktop
Then I just executed the installer from http://desktop.github.com/ and it restored everything and started the app without issues again. Thanks!

**Comment by cagataygunay** [comment] 2022-10-25 12:17
> 

This worked for me too, cheers!

**Comment by gowtham-spagylotech** [comment] 2024-03-22 04:58
if you face this problem on the git desktop. The problem with git desktop needs an update. So, you can uninstall and reinstall Git Desktop. then that's fine. It works for me. Try this and share your experience. thank you.

**Comment by steveward** [comment] 2024-10-28 20:09
Closing this specific issue as stale. We still see some ENOENT errors, but they're usually caused by opening external editors.

**Closed by steveward** 2024-10-28 20:09 UTC
Labels: investigation-needed
