### ISSUE TITLE
Repo is listed under the "Other" category when the protocol is SSH

### ISSUE THREAD

**Issue by kocsismate** [desktop/desktop#2584] opened 2017-08-30 07:39 UTC
### Description

When you clone a GitHub repo via SSH in the GitHub Desktop app, it is usually wrongly categorized under the "Other" repos, although it should be under the "GitHub" repos.

As a workaround, I clone my affected repos in CLI, then add them to the GitHub Desktop app.

### Version

**GitHub Desktop version:** 0.8

**OS version:** 10.12.6

### Steps to Reproduce

Clone a GitHub repository via SSH in the GitHub Desktop app. The repo I used: `git@github.com:woohoolabs/yang.git`

**Expected behavior:** The repo should be listed under the "GitHub" category

**Actual behavior:** Instead, it is listed under the "Other" category

**Reproduces how often:** Usually. I have a repo which can be cloned in GitHub Desktop well: `git@github.com:woohoolabs/yin.git`

#### Additional Information

If I can remember well, GitHub for Mac had a functionality which showed all your repos and you could clone them easily (do I remember well?). It would be awesome to have this again and be able to choose the protocol!

**Comment by tierninho** [comment] 2017-08-30 12:48
@kocsismate Hello, and thanks for filing the issue. Tried reproducing it, but your repo went straight to GitHub category as intended. 

Anything in the console logs? View > Toggle Developer Tools

If you restart Desktop is the repo still listed as "other"?

**Comment by kocsismate** [comment] 2017-08-30 14:38
Yeah, id doesn't change when I restart the app. And unfortunately I couldn't find any problem in the console log:

```
Executing clone: git -c credential.helper= clone --recursive --progress --progress -- https://github.com/woohoolabs/yang.git ~/woohoo/yang4 (took 2.261s)
renderer.js:12 Executing getTopLevelWorkingDirectory: git rev-parse --show-cdup
renderer.js:12 Executing getRemotes: git remote -v
renderer.js:12 Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z
renderer.js:12 Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes
renderer.js:12 Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 --
renderer.js:12 Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%P -z --no-color
renderer.js:12 Executing getRemotes: git remote -v
renderer.js:12 Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT
renderer.js:12 Executing getRemotes: git remote -v
```

**Comment by shiftkey** [comment] 2017-08-30 23:35
@kocsismate it looks like that was cloned using the HTTPS remote URL, rather than SSH.

**Comment by shiftkey** [comment] 2017-08-30 23:37
I also tried reproducing it using **File** | **Clone Repository** and the SSH URL, but it switches the URL to the HTTPS URL underneath (as that last log snippet suggests) and it gets grouped correctly.

@kocsismate could you confirm that you're logging into your GitHub account? That's the only difference I can think of that might be to blame here...

**Comment by kocsismate** [comment] 2017-09-01 08:19
@shiftkey Yes, I was logged in, but the problem persists after logging out too.

But I think I was able to identify the problem. I have the following in my global Git config:

```
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
```

I use this to force using the SSH protocol instead of HTTP. As soon as I removed these lines, my problem was solved, and newly cloned repos were listed under "GitHub".

What do you think? Is it a normal behaviour?

**Comment by shiftkey** [comment] 2017-09-02 08:11
@kocsismate looks like it - I was able to recreate it in this way:

 - remove any `url` override entries from `~/.gitconfig`
 - clone a HTTPS GitHub repository down to my local machine using Git CLI
 - add the above entry to `~/.gitconfig`
 - drag-and-drop the Git repository onto the app to add it
 
#2605 should close this out.

**Closed** 2017-09-06 11:22 UTC
Labels: bug, needs-reproduction
