### ISSUE TITLE
Discard Changes button not working

### ISSUE THREAD

**Issue by talsafran** [desktop/desktop#3982] opened 2018-02-09 20:52 UTC
### Description

When I click the Discard Changes button from the Confirm Discard Changes modal, the button does nothing. However, if I click the Cancel button, the modal is dismissed as expected.

### Version

**GitHub Desktop version:** 1.0.13

**OS version:**  10.13.3

### Steps to Reproduce

Same exact issue as #3951 

![kapture 2018-02-09 at 12 38 03](https://user-images.githubusercontent.com/257028/36049475-b36bf188-0d97-11e8-8358-6be6b92ea3dc.gif)

**Expected behavior:** Clicking the button should discard changes

**Actual behavior:** Nothing happens

**Reproduces how often:** Consistently

### Logs

[2018-02-09.desktop.production.log](https://github.com/desktop/desktop/files/1712387/2018-02-09.desktop.production.log)

**Comment by tierninho** [comment] 2018-02-09 21:17
@talsafran thanks, this is a duplicate of #3912 and a fix for it in #3917 is awaiting review.

**Closed by tierninho** 2018-02-09 21:17 UTC
