### ISSUE TITLE
Clear filter text when switching tabs

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3739] opened 2018-01-08 19:04 UTC
For the `Clone Repository` modal:

- Any text input in the search filter carries over from GitHub to Enterprise tab, and vice-versa. Should the filter be cleared if the user navigates to another tab? I noticed some visual performance lags due to this. My repo lists have already been loaded, yet any search filter carried over causes me to wait some time for the list to load again. The the filter was cleared, the list is immediately searchable.
<img width="437" alt="screen shot 2018-01-08 at 10 40 12 am" src="https://user-images.githubusercontent.com/14828183/34686966-2530326a-f462-11e7-990b-cd432083a8ec.png">
<img width="438" alt="screen shot 2018-01-08 at 10 41 03 am" src="https://user-images.githubusercontent.com/14828183/34686972-29d1c13a-f462-11e7-8833-c47defd50694.png">
<img width="869" alt="screen shot 2018-01-08 at 10 55 18 am" src="https://user-images.githubusercontent.com/14828183/34687178-d13af518-f462-11e7-83f2-fbd56308497c.png">

**Comment by iAmWillShepherd** [comment] 2018-01-08 21:35
This should be split into separate issues. Check over the issues I've created to make sure I've captured everything.

**Comment by iAmWillShepherd** [comment] 2018-01-08 21:38
> I noticed some performance lags due to this. My repo lists have already been loaded, yet any search filter carried over causes me to wait some time for the list to load again.

Looking over that screenshot of Chrome Dev Tools, it's looking as if no data is actually being transferred since the 304 HTTP code is being shown. Are you saying we shouldn't reload the list when the user switches tabs?

**Comment by iAmWillShepherd** [comment] 2018-01-08 21:42
Also, just noticed one of these items is a duplicate of #3629

**Comment by tierninho** [comment] 2018-01-08 21:49
@iAmWillShepherd I removed the text in the body as requested. Was gonna eventually split them up but wasn't sure they were all worthy... but thanks for doing so!

Yes, see the dupe now. Forgot about that one.

> Looking over that screenshot of Chrome Dev Tools, it's looking as if no data is actually being transferred since the 304 HTTP code is being shown. Are you saying we shouldn't reload the list when the user switches tabs?

Implementing the clear on the tab switch will resolve my concern, which is that it interferes with the (visual) loading of the data. I experienced a delay in seeing my list as the app was doing a search at the same time.

**Comment by iAmWillShepherd** [comment] 2018-01-08 21:51
> ... which is that it interferes with the (visual) loading of the data.

Ahh, got it.

**Comment by reyronald** [comment] 2018-01-12 14:45
> Implementing the clear on the tab switch will resolve my concern, which is that it interferes with the (visual) loading of the data. I experienced a delay in seeing my list as the app was doing a search at the same time.

@tierninho Wouldn't that mean that when switching back again to the first tab the previously entered text would be lost? Is that the desired behavior?

**Comment by reyronald** [comment] 2018-01-12 18:50
@tierninho When I said "previously entered text" I meant the text entered when you were in that tab originally before switching, like this...

1. In Enterprise tab, user types 'enterprise repo'
2. Click Github tab, filter is cleared, doesn't have the text 'enterprise repo' anymore. 
3. Click Enterprise tab again... here do we want the text-box to still be blank, or should it have the original text 'enterprise repo' before step 2 ? In other words, should each tab "remember" what its filter was ? With your suggestion, implementing clear on each tab switching would mean the filter would be always blank when switching to any tab regardless, which is what I was wondering (?)

**Comment by tierninho** [comment] 2018-01-12 19:33
Ah gotcha, I hadn't considered step 3. I will leave the decision up to our core members and design team. 

Thanks for pointing out the additional use case!

**Comment by reyronald** [comment] 2018-01-13 22:38
I went ahead and pushed a PR with the initial suggested behavior in #3741. I also comitted the behavior I suggested in another branch and linked it there so we can compare.

**Comment by shiftkey** [comment] 2018-02-28 04:43
This was fixed in #3787. Thanks again @reyronald!

**Closed by shiftkey** 2018-02-28 04:43 UTC
Labels: enhancement, good first issue, help wanted

**Comment by reyronald** [comment] 2018-02-28 05:10
@shiftkey my pleasure!
