### ISSUE TITLE
Commit message emoji selection with arrow keys broke

### ISSUE THREAD

**Issue by postmodernistx** [desktop/desktop#16063] opened 2023-02-04 11:46 UTC
### The problem

When I want to use an emoji in my commit message, I was previously able to type ":" followed by part of the emoji name and then use the arrow keys to select the emoji.

This no longer works as of the latest version. Instead, the "dropdown menu" disappears when you press the arrow key down (or up).

Previously, I could "arrow key scroll" to the right emoji.

This happens regardless of the colon-emoji pattern being in the beginning, mid-sentence, or at the end.

Gif for clarity. Let's say I'd like to select `:bus:` or `:bulb:` from the list.
![bug](https://user-images.githubusercontent.com/18628999/216765409-bd5470eb-d043-4de2-b257-49c47eb6ff37.gif)

### Release version

Version 3.1.5 (x64)

### Operating system

macOS Monterey 12.1

### Steps to reproduce the behavior

1. Go to "Commit message summary field"
2. Start typing an emoji: `:bu`
3. Use arrow down key to try to select another emoji than the first one from the list

### Screenshots

![image](https://user-images.githubusercontent.com/18628999/216765556-5d172468-476f-47b1-8f6f-25af72d397d0.png)

**Comment by niik** [comment] 2023-02-06 09:30
Hey @postmodernistx, thanks for reaching out! I was able to reproduce this and that's definitely a bug. I don't recall of the top of my head any work being done in that area recently so we'll have to take a look and see what caused it.

**Comment by steveward** [comment] 2023-02-06 19:26
Looks like the same issue as https://github.com/desktop/desktop/issues/16044.

**Comment by postmodernistx** [comment] 2023-02-06 20:38
> Looks like the same issue as #16044.

Oops, sorry for the duplicate! Tried searching/looking for “emoji” & “arrow” but missed that one :)

**Comment by niik** [comment] 2023-02-10 07:41
Thanks @steveward! @postmodernistx: I'm gonna close this in favor of #16044, please subscribe to that issue to follow along!

**Closed as completed by niik** 2023-02-10 07:41 UTC
Labels: bug, priority-2, accessibility
