### ISSUE TITLE
GitHub desktop uses Windows Account instead of github account.

### ISSUE THREAD

**Issue by noritan** [desktop/desktop#9437] opened 2020-04-02 09:01 UTC
### Describe the bug

When COMMITted a file to my local repository, the COMMIT is recorded as it was committed by my Windows account instead of my github account.

### Version & OS

Github desktop Version 2.4.0
OS: Windows 10 Enterprise 10.0.17134 Build 17134

### Steps to reproduce the behavior

1. Login to Windows with an account which name is different from the github account.
2. Create and commit a file to a master of my private repository.
3. See History to confirm the file was committed by the Windows account.
4. When the commit is pushed to the Github repository, it was also recorded as the file is committed by the Windows account.

### Expected behavior

It is recorded as the file is committed by my github account.
Because I signed in to github desktop with my github account.

### Actual behavior

It is recorded as the file is committed by my Windows account on both local and github repositories.

### Screenshots

<img width="213" alt="GS004689" src="https://user-images.githubusercontent.com/1782695/78229415-ecbaa880-750a-11ea-9a6f-7a1fc80fa89d.png">
Github desktop history record says Windows account is used since April 2020.

"Nori Tan" is the name of github account and "Noriaki Tanaka" is the name of my Windows account.

<img width="261" alt="GS004691" src="https://user-images.githubusercontent.com/1782695/78229441-f5ab7a00-750a-11ea-9bdb-008c05a8f7a5.png">

There are same records on github.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
```
2020-04-02T07:41:47.542Z - info: [ui] [AppStore] loading 14 repositories from store
2020-04-02T07:41:47.544Z - info: [ui] [AppStore] found account: noritan (Nori Tan)
2020-04-02T07:41:49.145Z - info: [ui] launching: 2.4.0 (Windows 10.0.17134)
2020-04-02T07:41:49.146Z - info: [ui] execPath: 'C:\Users\ntan\AppData\Local\GitHubDesktop\app-2.4.0\GitHubDesktop.exe'
2020-04-02T07:41:52.030Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.959s)
2020-04-02T07:41:55.365Z - info: [ui] Executing getRemotes: git remote -v (took 4.519s)
2020-04-02T07:43:58.427Z - info: [ui] Background fetch for 14 repositories took 10.789sec
2020-04-02T07:46:57.218Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.917s)
2020-04-02T07:59:06.151Z - info: [ui] Background fetch for 14 repositories took 7.700sec
2020-04-02T08:14:05.931Z - info: [ui] Background fetch for 14 repositories took 7.519sec
2020-04-02T08:17:05.744Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.206s)
2020-04-02T08:21:15.130Z - info: [ui] [Timing] Action 'create commit' for 'noritan/DOCS' took 2.006s
2020-04-02T08:21:16.193Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: DOCS - noritan (has token)
2020-04-02T08:21:22.212Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 5.752s)
2020-04-02T08:21:25.922Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.554s)
2020-04-02T08:27:02.961Z - info: [ui] [AppStore] removing account noritan (Nori Tan) from store
2020-04-02T08:28:06.936Z - info: [ui] [AppStore] adding account noritan (Nori Tan) to store
2020-04-02T08:29:05.976Z - info: [ui] Background fetch for 14 repositories took 7.592sec
2020-04-02T08:44:05.748Z - info: [ui] Background fetch for 14 repositories took 7.385sec
2020-04-02T08:52:15.029Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3.322s)
2020-04-02T08:54:31.855Z - info: [ui] Executing getConfigValueInPath: git config -z pull.rebase (took 4.210s)
2020-04-02T08:54:31.877Z - info: [ui] Executing getCommits: git log origin/master..master --date=raw --max-count=100 --pretty=%H%x1F%h%x1F%s%x1F%b%x1F%an <%ae> %ad%x1F%cn <%ce> %cd%x1F%P%x1F%(trailers:unfold,only) -z --no-show-signature --no-color -- (took 4.222s)
```

**Comment by billygriffin** [comment] 2020-04-02 15:07
Hi @noritan, thanks for the issue! I think this is related to your Git config using the email for your Windows account. If you go to `Preferences` -> `Git` and check and make sure the email that's being used matches an email address on your GitHub account, that should make sure your commits are properly attributed. Please let me know if that solves the problem! 

We also have #610 that discusses this problem, and it's unfortunately tricky to thread the needle between supporting whatever people want in their Git config and ensuring that it's on their GitHub account.

**Comment by noritan** [comment] 2020-04-03 01:01
Hi @billygriffin Thank you for your reply.
I cannot find the menu item `Preferences` on my Github Desktop.
Instead of `Preferences` I tried "git config -l" command on a Command Prompt and found there is no configuration regarding my github account including the account ID and e-mail.

**Comment by tierninho** [comment] 2020-04-03 01:15
@noritan For preferences in Windows, please navigate to `File` > `Options`, then select the `Git` tab to add your credentials.

Here are guides to add your [username](https://help.github.com/en/github/using-git/setting-your-username-in-git) and [email](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git) to the git config file. The username and email should match what add to Desktop.

Thanks, and reach out if needed.

**Comment by noritan** [comment] 2020-04-03 05:51
@billygriffin My credentials are filled in the `Git` tab and it was confirmed that the credentials are written in my `.gitconfig` file at my home directory.

When I set the user.name and user.email using the `git config --global` command, these are listed in the response to the `git config -l` command and COMMITs are recognized as committed by my github account.  But the `.gitconfig` file was not modified.

**Comment by tierninho** [comment] 2020-04-03 18:00
Thanks for the update, glad it was mostly resolved. So to recap: Git credentials are now in Desktop and the `.gitconfig` file, and commits are showing with the right username. 👍 

> But the .gitconfig file was not modified.

Just to clarify, were you expecting the `.gitconfig` file to show up as modified within Desktop? Or do you mean, after you updated your credentials the `.gitconfig` file didn't save the information?

**Comment by noritan** [comment] 2020-04-04 08:16
@tierninho The credential `user.name` and `user.email` were already existing in the `$(HOME)/.gitconfig` file.  But it is not recognized by `git config` and Github Desktop application.

May be this is related to the behavior of git.

**Comment by tierninho** [comment] 2020-04-06 18:49
You can view all of your settings and where they are coming from using: `git config --list --show-origin`

With `--global` it interacts with `~/.gitconfig`.  So using `git config --global --edit` will allow you to edit the global file. You should see your credentials already there.

Note: `.gitconfig` and `~/.gitconfig` usually name different files. 

> But it is not recognized by git config and Github Desktop application.

We have had [past reports](https://github.com/desktop/desktop/issues/8041) of users editing the wrong `gitconfig` file, which won't be detected by Desktop as it is not the right place to make the change.

Check that you have [Show hidden files](https://support.microsoft.com/en-ca/help/14201/windows-show-hidden-files) enabled for Windows Explorer, as files starting with a `.` may be hidden from you.

Hope this helps!

**Comment by noritan** [comment] 2020-04-07 01:09
Thank you for detailed information.

I tried `--show-origin` option and found that the `user.email` credential is stored in `C:\SPB_Data\.gitconfig` which is affected by the `git config --global` command.

There is a `C:\Users\{account}\.gitconfig` file containing `user.email` entry, but this file is note referred by the `git config --list --show-origin` even if the `user.email` entry in the `C:\SPB_Data\.gitconfig` file is UNSET using `--unset` option.

I understand that the reason of my trouble is I am using the `C:\Users\{account}\.gitconfig` file which is not recognized by git and Github Desktop.

Regards,
Noriaki

**Comment by tierninho** [comment] 2020-04-07 01:52
Thanks for the update.

Is SPB_Data a repo? If so, then there is probably a local git config for that repo only. Local git configs take priority over global git configs.

> I understand that the reason of my trouble is I am using the C:\Users\{account}\.gitconfig file which is not recognized by git and Github Desktop.

On Windows systems, Git looks for the (global) `.gitconfig` file in the $HOME directory (C:\Users\$USER for most users). It looks like that is where your's is, so it should be picked up unless you have a local config set for the repo you are using. 🤔

**Comment by noritan** [comment] 2020-04-07 02:23
SPB_Data is not a repository.

I found information regarding SPB_Data directory by google, it was said the environment variable HOME is changed when the OrCAD application is installed.

Actually I have installed Cadence PCB Viewer on 27 MAR 2020.  This should be a root cause.

Regards,
Noriaki

**Comment by tierninho** [comment] 2020-04-07 18:35
Thanks for the confirmation. I will close this issue for now as you have identified the root cause. Feel free to reach out for any help!

**Closed by tierninho** 2020-04-07 18:35 UTC
Labels: more-info-needed
