### ISSUE TITLE
GitHub Desktop Links Not Understood by Firefox

### ISSUE THREAD

**Issue by Draco18s** [desktop/desktop#2558] opened 2017-08-27 20:22 UTC
### Description

When trying to open a repository in GitHub Desktop I click the link on the repository under Clone or Download.  Firefox then says that the URL type (x-github-client) was not understood.

### Version

**GitHub Desktop version:** Chocolate-Covered Yaks (3.3.4.0) 50415df

**OS version:** Microsoft Windows [Version 6.1.7601]

### Steps to Reproduce

1. Go to repo (e.g. https://github.com/Draco18s/CustomOreGen)
1. Under Clone or Download, click "open in desktop"

**Expected behavior:** GitHub desktop opens the repo and clones it locally

**Actual behavior:** 

The address wasn’t understood
Firefox doesn’t know how to open this address, because one of the following protocols (x-github-client) isn’t associated with any program or is not allowed in this context.

**Reproduces how often:** Always

#### Additional Information

I have uninstalled and reinstalled GitHub Desktop with no change in behavior.

**Comment by shiftkey** [comment] 2017-08-27 22:27
@Draco18s this is a duplicate of #1676. 

The classic Desktop client does not understand the new `x-github-client` protocol that is enabled on the website after you've signed into the new Desktop app.  Someone has provided [a Greasemonkey script](https://github.com/desktop/desktop/issues/1676#issuecomment-315876467) to workaround this in the meantime.

**Closed by shiftkey** 2017-08-27 22:27 UTC

**Comment by zdog234** [comment] 2019-07-26 13:31
I'm not sure if this is fully a duplicate, (at least in my case). At least in my case, there seems to be an issue with firefox.

For me, neither `x-github-client` nor `github-windows` URI schemes were working in firefox, but both were working in chrome. After I reinstalled firefox (and selected the option to clear old settings and extensions), both URI schemes started working.

**Comment by shiftkey** [comment] 2019-07-26 13:49
@zdog234 I think this is an intermittent issue with Firefox and the reported upstream bug seems to still be open for Windows 7: https://bugzilla.mozilla.org/show_bug.cgi?id=1496024
