### ISSUE TITLE
Also offer to Open in Visual Studio

### ISSUE THREAD

**Issue by Jay-o-Way** [desktop/desktop#15322] opened 2022-09-21 09:27 UTC
### The feature request

Visual Studio _Code_ is the standard way of GitHub Desktop to open (files of) a repository/branch. But I would love the ability to also offer to open in Visual Studio.

### Proposed solution

Add a button <kbd>Open in Visual Studio</kbd> and also the ability to save this preference in the Settings.

**Comment by tsvetilian-ty** [comment] 2022-09-21 12:02
Hey @Jay-o-Way thanks for reaching out! GitHub Desktop uses the windows registry to identify installed editor/IDEs. The issue is that Visual Studio uses a unique registry key and can't be detected using the current mechanics in GitHub Desktop. 

A proposal aims to improve the handling of external editors: https://github.com/desktop/desktop/pull/14843.
I will close this in favor of https://github.com/desktop/desktop/issues/12946

**Closed as completed by tsvetilian-ty** 2022-09-21 12:02 UTC
