### ISSUE TITLE
Not support comments in Chinese/Japanese

### ISSUE THREAD

**Issue by loushizan** [desktop/desktop#1979] opened 2017-06-12 07:18 UTC
### Description

When some comments are Chinese/Japanese, they are displayed as illegal character.

### Version

**GitHub Desktop version:** 0.6.0

**OS version:** 10.12.4

### Steps to Reproduce

1. Write comments in Chinese/Japanese
2. Select modified file at Changes area
3. Comments are displayed as illegal character at Diff area

**Expected behaviour:** Legal character

**Actual behaviour:** Illegal character

**Reproduces how often:** Everytime

### Logs

no logs

#### Additional Information

no additional information

**Comment by shiftkey** [comment] 2017-06-12 08:28
This is a duplicate of #1958 which has been fixed in #1970 and will be available in the next update.

**Closed by shiftkey** 2017-06-12 08:28 UTC
