### ISSUE TITLE
Constantly changing files in Dropbox folder, when Github Desktop is open on multiple machines

### ISSUE THREAD

**Issue by kbauer** [desktop/desktop#5085] opened 2018-07-03 09:45 UTC
I know that it is not *recommended* to place git repositories in Dropbox, but it works reliably regardless and for setup, it is the most convenient options to keep the repositories in sync across devices. For some of them, e.g. LaTeX projects, where using git to synchronize the repository across devices would necessitate heavy bloat of the repository with binary files, it is really the *only* viable option.

## Description
When running Github Desktop on a Dropbox repository on a remote machine, and on the local machine, Dropbox notifies about frequent changes ``.git/HEAD`` and some other files on the remote machine. As a consequence, needless synchronization conflicts occur, which don't happen if git is used from the command line.

The issue may affect only repositories, that are being synchronized with a remote location like Github and first came up for my [fork kbauer/apxproof](https://github.com/kbauer/apxproof).

## Version
* GitHub Desktop: 1.2.6
* Operating system: Microsoft Windows [Version 10.0.16299.492]

## Steps to Reproduce
1. Create some repository on Github
2. Clone it to a Dropbox folder. 
3. Leave Github Desktop running with this repository opened on at least two machines connected to the Dropbox account.

### Expected Behavior
For a Dropbox-hosted repository, github desktop should preferably remain dormant, while the device isn't being used (e.g. locked, or e.g. system-wide absence of user-interaction for upwards of 15 minutes, if such is detectable).

Note that users are free to place the Dropbox directory whereever they want, and that directories may be junction points or directory symlinks pointing into the Dropbox folder, e.g. created by

    mklink /J C:\Users\klaus\Documents\my-repository E:\Dropbox\my-repository
                         //                                //
       Symlink must be resolved      Dropbox folder may be anywhere,
       to judge if in Dropbox.       but is enforced to be named
                                     Dropbox.

### Actual Behavior
Both Github Desktop clients constantly poll the repository for changes, resulting in recurring "a file has changed remotely" notifications from Dropbox, and possibly needless (and usually harmless) synchronization conflicts.

### Workaround
Make sure to quit Github Desktop before leaving each device.

### Logs from "remote" machine
I left this machine at around 2018-07-02 19:30, and returned around 2018-07-03 10:00. Any changes caused in between on this device, mostly updates to ``HEAD`` presumably by ``git status`` queries which have not been logged, but also ``fetch`` actions, are undesirable.
[2018-07-03.desktop.production.log](https://github.com/desktop/desktop/files/2158610/2018-07-03.desktop.production.log)
[2018-07-02.desktop.production.log](https://github.com/desktop/desktop/files/2158611/2018-07-02.desktop.production.log)

**Comment by shiftkey** [comment] 2018-07-03 12:55
@kbauer thanks for the log files and the details to try and reproduce this.

I'm a bit puzzled why these commands would need to update `.git/HEAD` without diving into the Git source again - I know `git status` has flags for ensuring it doesn't update `.git/index` (we don't enable this), and I know `git fetch` will modify `.git/FETCH_HEAD` as that's an optimization done as part of `git pull`, but understanding why `.git/HEAD` is involved requires more digging on my end.

Is it just `.git/HEAD` that is triggering these notifications?

For context: these `status` and `fetch` calls are being fired in the background because we want to help the user know when remote commits are available to be merged, or new branches are available to be checked out. It's a slightly different workflow to the CLI, and we're having a discussion in #1128 about this behaviour.

> mostly updates to `HEAD` presumably by `git status` queries which have not been logged,

FYI: we only log Git operations that error or take more than 1s to complete:

https://github.com/desktop/desktop/blob/3dad272120c7fba60aa84941040f810cf71793af/app/src/ui/lib/git-perf.ts#L30-L33

**Comment by kbauer** [comment] 2018-07-03 13:49
I was getting the dropbox popup "You have changed file HEAD" (triggered only by *remote* changes) about every 10 minutes, while working locally. By the end of the evening I had three "conflicted copies" of ``HEAD`` in the ``.git`` directory, without any of the conflicts actually affecting anything.

At some point I also had a conflict with ``FETCH_HEAD``, though I *think* that was only after I had pushed changes to the remote.

**Comment by shiftkey** [comment] 2018-07-03 14:12
@kbauer I worry about the `.git` folder (which is intended to be specific to the repository _on that machine_) being used as a backup across machines, as some of the files are not intended to be kept in sync.

`.git/HEAD` is a file that points to the current ref (if on a branch) or the current commit (if detached from a ref) for the local repository - syncing that across multiple machines is going to cause problems as you switch between branches and add new commits.

**Comment by kbauer** [comment] 2018-07-03 14:36
@shiftkey It *is* a bit of a risk. In practice however, as long as the synchronization is completed before any changes are made, issues don't really occur. Dropbox is unique in having that process so highly optimized (delta sync, etc), that it only really becomes an issue if two connected machines permform writes at the same time, which seems to be happening here. (Not sure how Dropbox handles writes that result in equvalent contents, but different time stamps.)

**Comment by steveward** [comment] 2022-06-28 17:32
Closing this out as stale since it isn't something we've had more reports of.

**Closed by steveward** 2022-06-28 17:32 UTC
Labels: investigation-needed
