### ISSUE TITLE
Unable to delete an unpublished branch

### ISSUE THREAD

**Issue by fdelaneau** [desktop/desktop#9990] opened 2020-06-12 08:51 UTC
### The bug

Unable to delete an unpublished branch. 

### Version & OS

GitHub Desktop version 2.5.2
macOS Mojave version 10.14.6
### Steps to reproduce the behavior

1. Go to an unpublished branch.
2. Click on Delete… from the Branch menu.
3. Confirm the action
4. The error message is shown

### Expected behavior

1. A choice to switch to another existing branch should be provided.
2. The current branch should be deleted.

### Actual behavior

Despite no current change being listed the following error message is shown :

Unable to switch branches as there are 

> working directory changes which would be overwritten. Please commit or stash your changes.

It is followed by another error message after :

> error: Cannot delete branch 'invoices' checked out at '/Users/sven/Sites/freelancer/v3'

**Comment by rafeca** [comment] 2020-06-12 10:10
Thanks for reporting this issue @fdelaneau !

This error is normally shown when you try to delete a branch while you have local uncommitted changes.

You mention that you had no local changes in your repository? If that's the case this looks like a potential bug.

Can you look at your looks (by opening the `Help` menu and selecting `Show Logs...`), look for the error and paste it here? You should see something similar than:

```
`git -c credential.helper= -c protocol.version=2 checkout master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	XXXXXX
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
```

Thanks!

**Comment by fdelaneau** [comment] 2020-06-12 10:24
Hi Rafael,

This was quick. Here are my latest logs.

I had no local changes in the current branch and the master branch has also no changes.

I tried publishing a branch and deleting it since and got the same error. I then deleted the published branch using the GitHub online interface without any warning.

My guess is that that I don’t understand how things really work 😓

Regards,
Fabrice Delaneau

**Comment by rafeca** [comment] 2020-06-12 10:40
Hi again! Thanks for the explanation!

I cannot see your logs. I've seen you replied to the issue via email, so maybe GitHub doesn't support attachments via email. Can you try uploading the file via github.com ?

**Comment by fdelaneau** [comment] 2020-06-12 10:43
It seems so indeed.

[2020-06-12.desktop.production.log](https://github.com/desktop/desktop/files/4770293/2020-06-12.desktop.production.log)

**Comment by rafeca** [comment] 2020-06-12 11:39
Thanks for attaching the logs!

I can see the errors appearing in the logs related to the deletion of the branch. It seems like `git` is detecting 3 uncommitted files in your working directory. Are you sure they don't appear in the "changes" tab of GitHub Desktop?

```
2020-06-12T08:52:56.195Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout master --` exited with an unexpected code: 1.
stderr:
error: Your local changes to the following files would be overwritten by checkout:
	src/coreAPI/config/settings.server.credentials.dev.json
	src/dashboard/config/settings.server.credentials.dev.json
	src/public/config/settings.server.credentials.dev.json
Please commit your changes or stash them before you switch branches.
Aborting

(The error was parsed as 37: Unable to switch branches as there are working directory changes which would be overwritten. Please commit or stash your changes.)
```

**Comment by fdelaneau** [comment] 2020-06-12 11:48
As you can see in the screenshot, there is no local changes listed.

The server credentials should be in the .gitignore as they are local to our individual machines.

<img width="1174" alt="Capture d’écran 2020-06-12 à 13 46 38" src="https://user-images.githubusercontent.com/129808/84499561-26e6ba00-acb3-11ea-93f0-6132de5bec45.png">

**Comment by rafeca** [comment] 2020-06-12 12:08
Thanks for the information! That's quite strange... I'm going to investigate a bit to see if I can find a way to reproduce this.

One last question, what happens if you try to switch branches to e.g `master`?

**Comment by fdelaneau** [comment] 2020-06-12 12:10
It directly switches to the selected branch without prompting to stash or move the non committed files if this is what you where looking for 😊

**Comment by steveward** [comment] 2020-09-30 12:57
@fdelaneau following back up on this -- are you able to reproduce this issue still? Can you confirm the output of `git status` is empty as well?

**Comment by niik** [comment] 2020-10-20 14:42
Thank you for your issue!

We haven't gotten a response to our questions.
With only the information that is currently in the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by niik** 2020-10-20 14:42 UTC
Labels: more-info-needed
