### ISSUE TITLE
New branch creation delayed if stashing dialogue dismissed

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7478] opened 2019-05-07 20:29 UTC
If you create a new branch and the Switch Branch dialogue is surfaced and dismissed, then the new branch is not immediately available to the user. If you create a new branch without the stashing interference then the branch is immediately available.

Reproduce:
- edit a file so it is in the Changes list
- create new branch
- when Switch Branch dialogue is automatically surfaced, dismiss it
- check branch list, new branch is not there

The branch eventually shows up after a delay. Not 100% ideal if someone is looking use it right away.

![May-07-2019 10-22-24](https://user-images.githubusercontent.com/14828183/57330635-54296780-70b2-11e9-9239-d1681a88595c.gif)

v1.7.0 beta6, mac

**Comment by steveward** [comment] 2022-06-07 17:55
I'm not able to reproduce this behavior any longer, so I'm going to close this out.

**Closed by steveward** 2022-06-07 17:55 UTC
Labels: bug, priority-3
