### ISSUE TITLE
Attempting to copy EASTL appears to pull down (most) all files but fails to show up in GitHub desktop.

### ISSUE THREAD

**Issue by tronster** [desktop/desktop#8027] opened 2019-07-26 02:24 UTC
##Description
EASTL fails to install into the client

## Version
* GitHub Desktop:
2.1.0
* Operating system:
10.14.6

## Steps to Reproduce
2. Get a MBP (2019), latest non-beta macOS, install Github client
3. Attempt to copy locally: https://github.com/electronicarts/EASTL
4. Watch it copy (most) all files and then fail with an error message so it's not enumerated on the left side.

### Expected Behavior
EASTL to be copied and showing in GItHUB

### Actual Behavior
EASTL files copied but not added to GitHUB

## Additional Information
1. When using your Github your client why do users have to manually look up and fill out fields rather than have them pre-populated?

2. Add a bulk import option so users with new machines don't have to add every... single... GitHUB repository they have locally.

**Comment by shiftkey** [comment] 2019-07-26 11:44
@tronster thanks for the report!

> Watch it copy (most) all files and then fail with an error message so it's not enumerated on the left side.

Are you able to find the full error message that was seen? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot.

**Comment by tierninho** [comment] 2019-07-26 17:28
@shiftkey Reproduced this and here are the logs in the short form:

```
`git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/electronicarts/EASTL.git /Users/tierninho/Documents/GitHub/test/EASTL` exited with an unexpected code: 1.
stdout:
Submodule path 'test/packages/EAAssert': checked out 'e5e181255de2e883dd1f987c78ccc42ac81d3bca'
Submodule path 'test/packages/EABase': checked out 'ea91a59d1e7f9d0a0d1441900aa0c16a89915694'
Submodule path 'test/packages/EAMain': checked out '24ca8bf09e6b47b860286fc2f4c832f4009273d1'
Submodule path 'test/packages/EAStdC': checked out '6f4edf10d823164a9b5ed6c597c44514638f539a'
Submodule path 'test/packages/EATest': checked out '7be9ffc7e655968b3f96d7a425e82597e56c1fe6'
Submodule path 'test/packages/EAThread': checked out 'e4367a36f2e55d10b2b994bfbae8edf21f15bafd'

stderr:
Cloning into '/Users/tierninho/Documents/GitHub/test/EASTL'...
remote: Enumerating objects: 18, done.        
remote: Counting objects:   5% (1/18)
... (skipping to bottom)...           
Resolving deltas: 100% (86/86), done.
Submodule 'test/packages/EAThread' (git@github.com:electronicarts/EAThread.git) registered for path 'test/packages/EAAssert/test/packages/EAThread'
Cloning into '/Users/tierninho/Documents/GitHub/test/EASTL/test/packages/EAAssert/test/packages/EABase'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:electronicarts/EABase.git' into submodule path '/Users/tierninho/Documents/GitHub/test/EASTL/test/packages/EAAssert/test/packages/EABase' failed
Failed to clone 'test/packages/EABase' a second time, aborting
Submodule 'test/packages/EAAssert' (git@github.com:electronicarts/EAAssert.git) registered for path 'test/packages/EABase/test/packages/EAAssert'
Cloning into '/Users/tierninho/Documents/GitHub/test/EASTL/test/packages/EABase/test/packages/EAAssert'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Failed to clone 'test/packages/EAAssert' a second time, aborting
Failed to recurse into submodule path 'test/packages/EAAssert'
Failed to recurse into submodule path 'test/packages/EABase'
Failed to recurse into submodule path 'test/packages/EAMain'
Failed to recurse into submodule path 'test/packages/EAStdC'
Failed to recurse into submodule path 'test/packages/EATest'
Failed to recurse into submodule path 'test/packages/EAThread'

(The error was parsed as 2: Authentication failed. Some common reasons include:

- You are not logged in to your account: see GitHub Desktop > Preferences.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.)
```

This is a public repo. Tried the `clone in desktop` button on the repo page, but same result for both SSH and HTTPS.

The last commit in that repo had to do with submodules so maybe that's relevant? https://github.com/electronicarts/EASTL/commit/96aeae40ac08e9a68de0fc75801bb14f85893352

2.1.1-beta2, mac

**Comment by tierninho** [comment] 2019-07-26 17:30
Note: https://github.com/electronicarts/EASTL/issues/301

**Comment by shiftkey** [comment] 2019-07-26 18:43
@tierninho thanks for the information and repro!

I can reproduce this on the command line because the inner submodules (EASTL -> EAAssert -> EABase) use SSH URLs, which is being tracked by #2344.

The other issue here is that https://github.com/electronicarts/EASTL/issues/301 indicates you can't clone submodules without causing endless recursion. I enabling SSH authentication on the command line and ran ` git clone --recursive  https://github.com/electronicarts/EASTL` which lead to endless creation of submodules and I had to start `kill -9`-ing - the last submodule path I had was `/Users/shiftkey/src/test/EASTL/test/packages/EAAssert/test/packages/EABase/test/packages/EATest/test/packages/EAStdC/test/packages/EABase/test/packages/EAThread`

@tronster I'd recommend reaching out to the `EASTL` maintainers to see if they're able to get the command line clone experience under control. Once you can clone it from the command line, you can add it to Desktop and work with it there until #2344 gets resolved.

**Comment by tierninho** [comment] 2019-07-26 18:55
@tronster Gonna close this issue out as it is "resolved" for now and the ball is in the `EASTL` maintainers court. Please follow along at #2344. Thanks.

**Closed by tierninho** 2019-07-26 18:55 UTC
Labels: more-info-needed

**Comment by tronster** [comment] 2019-07-27 00:47
I tried to reach out to the maintainer (Rob Parolin, rparolin) but Github's direct contact people is no down?  (see attached screen shot)

**Comment by tierninho** [comment] 2019-07-27 01:35
There is an update the conversation on https://github.com/electronicarts/EASTL/issues/301

Looks like they will update the README file with details soon.
