### ISSUE TITLE
Zoom reseting every update

### ISSUE THREAD

**Issue by Yuhtin** [desktop/desktop#11229] opened 2020-12-14 16:59 UTC
### Describe the bug

Every time I update the desktop github, it zooms out. The bug is simple and I can zoom in again, but just to inform you that you are having this bug

### Version & OS

Windows 10.0.19041

### Steps to reproduce the behavior

1. Open github desktop and zoom to a random % (exemple: 150%)
2. Install a github desktop update 
3. And the zoom returns to the normal (100%)

### Expected behavior

Continue with the zoom I placed before the update

### Actual behavior

If I zoom in 150%, for example, when I update the app it goes back to 100%

### Screenshots

I don't have
[2020-12-14.desktop.production.log](https://github.com/desktop/desktop/files/5690330/2020-12-14.desktop.production.log)

**Comment by billygriffin** [comment] 2020-12-14 17:18
Hi @Yuhtin, thanks for the issue! This is a duplicate of #5315 so please follow along there.

**Closed as completed by billygriffin** 2020-12-14 17:18 UTC
