### ISSUE TITLE
"You have changes on this branch" dialog fails to display when attempting branch switch in detached HEAD state

### ISSUE THREAD

**Issue by narthur** [desktop/desktop#8098] opened 2019-08-13 13:34 UTC
## Description

I have a repository currently on a detached head with changed files. [According to the docs](https://help.github.com/en/desktop/contributing-to-projects/switching-between-branches), selecting a different branch should result in a window allowing me to choose what to do with the changed files, and then switch to the selected branch.

Instead, choosing a different branch seems to do nothing. The only thing I can find that changes is that the `GitHub Desktop > About GitHubDesktop` menu item (and other menu items) becomes disabled after attempting the switch. This makes me think that the dialog has actually been triggered, but for some reason I can't see or access it.

I do have a duel-monitor setup, in case that is a factor.

## Version

* GitHub Desktop: 2.1.0
* Operating system: macOS Mojave 10.14.6

## Steps to Reproduce

- Clone a repository with a submodule
- Add the submodule repository
- Change a file in the submodule
- View the repository in its detached head state
- Attempt to switch to another branch
- Notice that the dialog asking what to do with changes does not display

### Expected Behavior

A dialog should display asking what to do with uncommitted changes. Once a selection is made, the branch should be changed.

### Actual Behavior

No dialog appears, and the branch remains unchanged.

## Additional Information

- The repository I'm experiencing this issue with is a submodule with a detached head and uncommitted changes.
- I have a duel-monitor setup.

### Logs

[2019-08-13.desktop.production.log](https://github.com/desktop/desktop/files/3497125/2019-08-13.desktop.production.log)

**Comment by steveward** [comment] 2019-08-13 16:45
@narthur thanks for the detailed report! I was able to reproduce this as well on both Windows/macOS with a single-monitor setup, so I don't think that is the issue. It can be reproduced by just checking out a previous commit in your repository from the command line:

`git checkout <SHA1_of_commit>`

This puts the repository into a detached HEAD state, and I was then unable to switch branches. The only output in the console is `[Timing] Action 'checkout branch from list' for '<repo_name>' took 0.001s`.

**Comment by tidy-dev** [comment] 2024-09-16 17:48
I was unable to reproduce the part about "branch remains unchanged".  I am closing - assuming behavior has changed since this issue was opened.

I did: 
1. Checked out a previous commit so I was in a detached head state.
2. Modified a file on the repository such that I had a change listed in the changes list.
3. Switched to an existing branch.

What happened:
1. I was able to check out the branch
2. My changes came with me. They actually showed conflict markers since I changed a file already changed on the branch I moved to.

Why this is expected as opposed to "asking what to do with uncommitted changes"

The only options Desktop can give is to stash your changes or bring with you to the next branch. When we stash changes, we associate them to the currently checked out branch. In this case there are no checked out branch, thus, we automatically bring them with you to the next branch. 

Other notes: The user has the option to create a new branch from the detached head state if they want to preserve that change as being on top of the commit they have checked out as opposed to moving it to the branch they are switching too. 

Other implementation possibilities that I do not believe we would spend the time to implement as this is a edgecase adn Desktop provides a couple of outs. 
- Track stashes on detached state.. not a logically flowing as branches tho as you could create a stash on to very different commits and have to choose between which one to keep. Or.. we stash it using the commit? Seems unwieldy. 
- Ask the user if they want to create a branch to commit or stash their uncommitted changes too.

**Closed** 2024-09-17 19:13 UTC
Labels: bug, priority-3, epic:stashing
