### ISSUE TITLE
Merge hint count doesn't match actual conflicted files

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#6101] opened 2018-11-05 17:31 UTC
The merge hint indicated there will be more conflicted files than what was showed in the actual merge conflict modal. 

From four to three:
<img width="448" alt="screen shot 2018-11-05 at 9 12 43 am" src="https://user-images.githubusercontent.com/14828183/48014456-95c55f80-e0db-11e8-92e4-33bc7ff0578f.png">
<img width="507" alt="screen shot 2018-11-05 at 9 12 36 am" src="https://user-images.githubusercontent.com/14828183/48014454-95c55f80-e0db-11e8-83eb-675164731ef5.png">

Reproduction may be difficult. 

In command line:
```
Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both added:      UnitTestProject1/UnitTestProject1.sln
	both added:      UnitTestProject1/UnitTestProject1/Properties/AssemblyInfo.cs
	both added:      UnitTestProject1/UnitTestProject1/UnitTestProject1.csproj
```

tested in 1.5.0-beta3, mac

**Comment by shiftkey** [comment] 2018-11-05 17:51
> Reproduction may be difficult.

Yeah, and I think this comes down to `git merge-tree` not being smart enough to use the same rules as `git merge`. We've got #5568 which tracks the same problem manifesting with renames, but a good sample of a public repository with the actual commits being merged will help with reproducing, like I did in #5568 by capturing the commits associated with each branch.

```
$ git rev-parse polish-merge-status
361f587830413e05b7299d9f9932cff36aee0127
$ git rev-parse branch-list-context-menu
cbdb0f78739d21193d42eb0f87aa0cded6e505b9
```

That means I can re-run the same `git merge-tree` result at a later stage, even if the branches themselves are cleaned up.

**Comment by tierninho** [comment] 2018-11-05 22:19
I have come across an instance where the merge hint says there are conflicted files, yet when I click to resolve them, the success banner is shown because the `git merge-tree` is not being smart enough.

**Comment by outofambit** [comment] 2018-11-09 16:59
this also manifests for conflicts without markers (similar to #6123)
![conflicts without markers](https://user-images.githubusercontent.com/964912/48276768-accac100-e3fd-11e8-98f8-b8a9526070b4.gif)

**Comment by shiftkey** [comment] 2019-01-09 21:37
@outofambit is the repository in https://github.com/desktop/desktop/issues/6101#issuecomment-437424265 something you're able to find again and share? Having repeatable reproductions of merges that aren't working as expected would be ideal here to ensure I'm looking at the correct thing.

**Comment by shiftkey** [comment] 2019-01-10 18:22
@outofambit thanks for that repro. Here's what I did to test it out.

1. Setup the `merge-tree` parameters:

```shellsession
$ git rev-parse master
d8818c13b04aa5c9bea5ba9ae7c3e31f00a82d56
$ git rev-parse branch
8b6dbcd74e9db03c3fca5186b0052e23de417466
$ git merge-base d8818c13b04aa5c9bea5ba9ae7c3e31f00a82d56 8b6dbcd74e9db03c3fca5186b0052e23de417466
2d0a39e2caaf16046214c98dbd856d658c3b88ee
```

2. Run the `git merge-tree` command, but get no output:

```
$ git merge-tree 2d0a39e2caaf16046214c98dbd856d658c3b88ee d8818c13b04aa5c9bea5ba9ae7c3e31f00a82d56 d8818c13b04aa5c9bea5ba9ae7c3e31f00a82d56

```

3. Run the merge directly and see the conflict:

```
$ git merge branch
CONFLICT (modify/delete): README.md deleted in branch and modified in HEAD. Version HEAD of README.md left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

I suspect `git merge-tree` is great at finding those conflicts where both files have been modified, but less great at those "modified vs deleted" conflict scenarios.

**Comment by shiftkey** [comment] 2019-01-10 18:43
A theory that I'd like to unpack and explore (given a couple more real examples that I can test against) would be to test in two stages:

  - `git merge-tree` to find files that have been modified in both branches and cannot be merged automagically
  - run `git diff-tree [merge-base]..[branch]` for the base branch and the compare branch and filter on paths that will trigger the sort of conflict that `blegh-test` shows.

Why `git diff-tree`? This is a convenient way to see which paths have been changed on each branch, and shows the relevant context I think I need here:

Here's the output for the previous merge scenario:

```
$ git diff-tree 2d0a39e2caaf16046214c98dbd856d658c3b88ee..master
:100644 100644 bc5563688c73fa22aed7d7241a0acfc39d403174 e6f4326b1552dcb7ff434888aaa0c030b4f93351 M	README.md
:000000 100644 0000000000000000000000000000000000000000 898e96c97c360cef274d2748a06bb21a6d536b7e A	asuperlongfilenamethatnoonewouldeveruseexceptmaybetheywould.md

$ git diff-tree 2d0a39e2caaf16046214c98dbd856d658c3b88ee..branch
:100644 000000 bc5563688c73fa22aed7d7241a0acfc39d403174 0000000000000000000000000000000000000000 D	README.md
:000000 100644 0000000000000000000000000000000000000000 898e96c97c360cef274d2748a06bb21a6d536b7e A	asuperlongfilenamethatnoonewouldeveruseexceptmaybetheywould.md
```

We see that each branch has made changes to the same two entries:

 - `README.md` is modified in one branch but deleted in the other - I think that's the detail I'm missing
 - `asuperlongfilenamethatnoonewouldeveruseexceptmaybetheywould.md` is added in both with the same blob - if these differed content-wise I believe `git merge-tree` would try and merge the content and provide this detail to `stdout`.

**Comment by shiftkey** [comment] 2019-01-10 18:46
> Reproduction may be difficult.

@tierninho any chance you might be able to find this problem repository? I want to gather up more failures like this to help with benchmarking an improved solution...

**Comment by tierninho** [comment] 2019-01-10 18:51
@shiftkey Yep, the test repo is here: https://github.com/meaghanlewis/TestWebAppProject

**Comment by shiftkey** [comment] 2019-01-10 19:21
@tierninho I'm missing something with reproducing what you saw, because all I see is that `master` is ahead of `branch0308` (no newer commits on `branch0308`):

```shellsession
$ git rev-parse branch0308
1fc58eb974d1ff22e7de3f87d3af1122975f2b4b
$ git rev-parse master
bd8bf8b62e5f3f2f7056d07d9b10c33fe3a39685
$ git merge-base 1fc58eb974d1ff22e7de3f87d3af1122975f2b4b bd8bf8b62e5f3f2f7056d07d9b10c33fe3a39685
1fc58eb974d1ff22e7de3f87d3af1122975f2b4b
```

This shows the base of merging `master` into `branch0308` is the tip of `branch0308`, and all of the commits that will be merged are on `master`:

```shellsession
$ git rev-list --left-right --count master...branch0308
82	0
```

Merging `master` into `branch0308` does not trigger the original conflicts:

```shellsession
$ git merge master
Updating 1fc58eb..bd8bf8b
Fast-forward
 .gitignore                                                                        | 265 +------------------------------------------------
 ConsoleApp2/ConsoleApp2.sln                                                       |  25 +++++
 ConsoleApp2/ConsoleApp2/ConsoleApp2.vbproj                                        |   8 ++
 ConsoleApp2/ConsoleApp2/Program.vb                                                |   7 ++
 ConsoleApplication2/ConsoleApplication2.sln                                       |  22 ++++
 ConsoleApplication2/ConsoleApplication2/App.config                                |   6 ++
 ConsoleApplication2/ConsoleApplication2/ConsoleApplication2.csproj                |  60 +++++++++++
 ConsoleApplication2/ConsoleApplication2/Program.cs                                |  15 +++
 ConsoleApplication2/ConsoleApplication2/Properties/AssemblyInfo.cs                |  36 +++++++
 ConsoleApplication3/ConsoleApplication3.sln                                       |  22 ++++
 ConsoleApplication3/ConsoleApplication3/App.config                                |   6 ++
 ConsoleApplication3/ConsoleApplication3/ConsoleApplication3.csproj                |  60 +++++++++++
 ConsoleApplication3/ConsoleApplication3/Program.cs                                |  15 +++
 ConsoleApplication3/ConsoleApplication3/Properties/AssemblyInfo.cs                |  36 +++++++
 README.md                                                                         |  40 ++++++++
 TestWebAppProject/Controllers/HomeController.cs                                   |  13 +++
 TestWebAppProject/Views/Home/Contact.cshtml                                       |  18 ++++
 TestWebAppProject/appsettings.Development.json                                    |   2 +-
 TestWebAppProject/bundleconfig.json                                               |   2 +-
 UnitTestProject1/.DS_Store                                                        | Bin 0 -> 6148 bytes
 UnitTestProject1/UnitTestProject1.sln                                             |  49 +++++++++
 UnitTestProject1/UnitTestProject1/Properties/AssemblyInfo.cs                      |   7 ++
 UnitTestProject1/UnitTestProject1/UnitTest1.cs                                    |   1 +
 UnitTestProject1/UnitTestProject1/UnitTestProject1.csproj                         |  18 ++++
 UnitTestProject3/UnitTestProject3/tests/UnitTest1.cs                              |  20 ++++
 WindowsFormsApplication1/WindowsFormsApplication1/Form1.Designer.cs               |  16 +++
 WindowsFormsApplication1/WindowsFormsApplication1/Properties/AssemblyInfo.cs      |  71 +++++++++++++
 WindowsFormsApplication1/WindowsFormsApplication1/WindowsFormsApplication1.csproj |  54 ++++++++++
 _config.yml                                                                       |   1 +
 appveyor.yml                                                                      |  14 ++-
 fg0359.png                                                                        | Bin 0 -> 158704 bytes
 il_fullxfull.891227984_rqu8.jpg                                                   | Bin 0 -> 182633 bytes
 one.txt                                                                           |   4 +
 33 files changed, 642 insertions(+), 271 deletions(-)
 create mode 100644 ConsoleApp2/ConsoleApp2.sln
 create mode 100644 ConsoleApp2/ConsoleApp2/ConsoleApp2.vbproj
 create mode 100644 ConsoleApp2/ConsoleApp2/Program.vb
 create mode 100644 ConsoleApplication2/ConsoleApplication2.sln
 create mode 100644 ConsoleApplication2/ConsoleApplication2/App.config
 create mode 100644 ConsoleApplication2/ConsoleApplication2/ConsoleApplication2.csproj
 create mode 100644 ConsoleApplication2/ConsoleApplication2/Program.cs
 create mode 100644 ConsoleApplication2/ConsoleApplication2/Properties/AssemblyInfo.cs
 create mode 100644 ConsoleApplication3/ConsoleApplication3.sln
 create mode 100644 ConsoleApplication3/ConsoleApplication3/App.config
 create mode 100644 ConsoleApplication3/ConsoleApplication3/ConsoleApplication3.csproj
 create mode 100644 ConsoleApplication3/ConsoleApplication3/Program.cs
 create mode 100644 ConsoleApplication3/ConsoleApplication3/Properties/AssemblyInfo.cs
 create mode 100644 TestWebAppProject/Controllers/HomeController.cs
 create mode 100644 UnitTestProject1/.DS_Store
 create mode 100644 _config.yml
 create mode 100644 fg0359.png
 create mode 100644 il_fullxfull.891227984_rqu8.jpg
```

My guess is `branch0308` got a merge from `master` and I'd need to go back in time to some earlier commits (looking at the screenshot the branch was ~8 months before November, so sometime in March?)  to try and see if I can recreate it.

**Comment by shiftkey** [comment] 2019-01-10 19:50
Punting this to 1.6.1 as I have an idea about a way forward but it's not going to happen for the next release.

**Comment by tierninho** [comment] 2019-01-10 19:55
Not sure 🤔as that repo has been banged on quite a bit in the last month or two.

**Comment by shiftkey** [comment] 2019-01-23 12:50
Unassigning myself from this because I need to start making some inroads on rebasing tasks for 1.7. I think the idea in this earlier comment https://github.com/desktop/desktop/issues/6101#issuecomment-453207386 is worth exploring, but we can move this to a later milestone if someone isn't able to pick it up.

**Comment by billygriffin** [comment] 2019-04-11 23:06
Removing this from the milestone for 1.7.0 because I don’t think we have the bandwidth to get to it prior to the release, but we do think it’s still confusing behavior that we’ll hopefully be able to address in upcoming releases. @outofambit If you’d like to share how you were thinking about it for posterity, I think that’d be helpful for when we do get back to it.

**Comment by outofambit** [comment] 2019-04-15 18:38
To crystallize this research a bit more, I'll outline a potential fix for this issue.

## Current Implementation

The current implementation starts in [`AppStore.updateCompareToBranch`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/stores/app-store.ts#L811-L934), which [primarily relies](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/stores/app-store.ts#L895-L898) on [`mergeTree`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/merge.ts#L72-101).

## Proposed Fix

This fix should primarily touch `mergeTree` (which probably needs to be renamed, since it would no longer be just mergeTree). The general idea is to use `git diff-tree` to find conflicts and supplement that information with `git merge-tree`. At a high level:

1. get merge base with existing [`getMergeBase`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/merge.ts#L41-L63).
2. execute a `git diff-tree` twice, one for each branch tip ([see here](https://github.com/desktop/desktop/issues/6101#issuecomment-453207386) for details on what that command should look like)
3. parse a [`GitStatusEntry`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/models/status.ts#L6-L16) for each file on each branch
4. look at the pairs of `GitStatusEntry`s (two for each file from the two branches) and parse them using ['mapStatus`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/status-parser.ts#L174-L369)
5. then you'll need a function similar to [getMergeConflictDetails](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/status.ts#L338-L347), but instead of `getFilesWithConflictMarkers`, you'll need to write a function that uses `git merge-tree` in the same way that the current implementation of [`mergeTree`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/merge.ts#L72-101) does
6. This should give you a list of files that have conflicts, which the existing implementation of [`mergeTree`](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/merge.ts#L72-101) should indicate how to do, between [this](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/git/merge.ts#L95-L98) and [this](https://github.com/desktop/desktop/blob/40a7abaf9094bdb88c435662ea6a9b8705e4c1d4/app/src/lib/merge-tree-parser.ts#L194-L202)

Feel free to ping me if any of this doesn't make sense or if you see a simpler way to get there!

**Comment by shiftkey** [comment] 2019-05-01 21:29
In working through the equivalent feature for the rebase flow I've stumbled upon an escape hatch that might mean we don't need all that complexity from the proposed fix.

I'm currently testing the use of a worktree in a temporary directory to perform the merge . This means we could update the working directory using the **exact same merge steps** we use in the app, 
avoiding the need to use `git merge-tree` and then trying to cobble together the missing information that `git merge-tree` overlooks.

Based on my testing of #7445 I think the learnings and tools from there could be reused here. Stay tuned.

**Comment by billygriffin** [comment] 2019-09-05 21:56
I'm going to roll this into #8049 because we don't need to be tracking it in multiple places.

**Closed by billygriffin** 2019-09-05 21:56 UTC
Labels: bug, priority-2
