### ISSUE TITLE
Pulling without a clean directory doesn't show which files need to be stashed or discarded

### ISSUE THREAD

**Issue by amartinez1660** [desktop/desktop#10441] opened 2020-08-25 15:14 UTC
### Describe the feature or problem you’d like to solve

When pulling and there are files already modified it doesn't show anymore which files need to be discarded or stashed. It now only displays a button to 'Stash and Continue'

### Proposed solution

Sometimes we don't really need to stash the whole directory for it to pull. It would be great to display which files are triggering the requested stash and continue option (similar to how it was before).

### Additional context

Reference: before the 'stash and continue' update.

**Comment by tierninho** [comment] 2020-08-25 18:58
Thank you for the suggestion. Yes, currently we only offer a 'one size fits all' solution which forces the user to stash all changes not committed at the time. 

Labeling this as an enhancement to the Desktop.

**Comment by rustinlee** [comment] 2020-08-26 14:42
This was never an issue until the most recent update... Prior to today, the error dialog would always list exactly which files needed to be discarded or stashed, but now I'm getting this useless error message:
![image](https://user-images.githubusercontent.com/3959144/91317826-828bf400-e788-11ea-888a-9a99f472c030.png)
Meanwhile, typing `git pull` in the Git Bash console gives the exact information on which files are conflicting, like always. Why was this change made??

**Comment by tierninho** [comment] 2020-08-26 18:17
> This isn't an "enhancement", it's a major regression that affects the workflow of anyone using git in a team...

Duly noted as your statement is indeed a valid concern. We will take this into consideration!

**Comment by tustin2121** [comment] 2020-09-02 18:32
This seems to be related to PR #10053. I was also going to make an issue related to the loss of information here, so I'll just ~~second~~ third this one.

Previously, I could see which files were conflicting, and decide if the local changes were minor enough or reproduced in the incoming pull, I could simply revert the files. Now in order to get that information, I have to go to the command line, which defeats the purpose of using the desktop client. +1 to the "this isn't an enhancement, it's a regression" sentiment.

**Comment by tierninho** [comment] 2020-09-10 21:37
Hi all, we have [opened pull request](https://github.com/desktop/desktop/pull/10550) to address this issue. Thank you for your feedback and patience. We look forward to rolling it out soon!

**Closed** 2020-09-16 11:37 UTC
Labels: enhancement
