### ISSUE TITLE
app executes shortcut when user wants to change language inside text input

### ISSUE THREAD

**Issue by AlexeySinushkin** [desktop/desktop#6728] opened 2019-01-26 16:39 UTC
Hello, native speakers

When I want to commit
1. put cursor to Summary field
2. I see that current language is ENG (WIn10)
3. Press Ctrl+Shift -> language switch
4. try to type -> menu opening instead of enter any character

**Comment by AlexeySinushkin** [comment] 2019-01-29 04:04
Hello,  Brendan
I guess you never switch language before,  but this buttons bunchs used since windows 98 or 95.
Ctrl+Shift or Alt+Shift
And if conflict present, your program should give way. 
--
Отправлено из Mail.Ru для Android вторник, 29 января 2019г., 02:30 +08:00 от Brendan Forster  notifications@github.com :

**Comment by shiftkey** [comment] 2019-01-29 14:39
> I guess you never switch language before,  but this buttons bunchs used since windows 98 or 95.

I sometimes have this setup to catch things related to using different input languages, but it's been a while because I tend to nuke my test environments regularly.

I enabled this again and checked what my keyboard setting was, and it's defaulting to <kbd>Alt</kbd> + <kbd>Shift</kbd> - this is handy because we avoid using <kbd>Alt</kbd> in our shortcuts.

<img width="434" src="https://user-images.githubusercontent.com/359239/51914935-cfca9880-238e-11e9-8405-8ea2c6585863.png">

> And if conflict present, your program should give way.

From the last two steps of the repro:

> 3. Press Ctrl+Shift -> language switch
> 4. try to type -> menu opening instead of enter any character

It feels like you still have <kbd>Ctrl</kbd> + <kbd>Shift</kbd> pressed when you perform step 4 and press another key, which executes the menu shortcut associated with that key. Am I understanding that right? 

I tested this out with the commit summary having keyboard focus, <kbd>Ctrl</kbd> + <kbd>Shift</kbd> set as the language switcher shortcut and pressing that shortcut along with the <kbd>H</kbd> key (which isn't tied to a shortcut). I didn't see a <kbd>H</kbd> being inserted into the textbox. Are you expecting a different behaviour here?

What's interesting about this is whether the application keyboard shortcuts should fire when an input field has focus. I need to read some Electron resources (because Electron manages the menu shortcuts that are firing here) and understand who else has stumbled upon this, and what they did about it.

**Comment by AlexeySinushkin** [comment] 2019-01-29 15:14
May be you are right.  But I use blinde typing mode and it is very easy to switch using ONE thumb.  Attachment. 
--
Отправлено из Mail.Ru для Android вторник, 29 января 2019г., 22:39 +08:00 от Brendan Forster  notifications@github.com :

**Comment by steveward** [comment] 2022-08-01 19:32
Looking into this again and confirmed that `Alt` + `Shift` seems to be the default for switching input languages, and since we don't have any shortcuts using `Alt` I'm going to close this out, but If I'm missing something here let us know!

**Closed by steveward** 2022-08-01 19:32 UTC
