### ISSUE TITLE
GitHub Desktop not connecting to server with SSH key+passphrase after Windows Update to Windows 11, version 22H2

### ISSUE THREAD

**Issue by maborec** [desktop/desktop#15338] opened 2022-09-22 15:47 UTC
### The problem

I have been using GitHub for a long time without issues until today.
I have updated Windows to version Windows 11 22H2.
Since then, GitHub Desktop cannot connect to my git server.
I'm using my own git repository and I connect authenticating with an SSH key that has an associated passphrase.
After the update, when I try, for example, to Fetch, it gets stuck at "Fetching origin. Hang on...".
I have been looking at the logs and the console and there is no activity registered at all.

I have tried reinstalling completely with no success:
- Uninstall GitHub Desktop
- Remove directories "C:\Users\%USERNAME%\AppData\Local\GitHubDesktop" and  "C:\Users\%USERNAME%\AppData\Roaming\GitHub Desktop"
- Remove the stored passphrase from Windows Credentials
- Installing again GitHub Desktop

When trying to Fetch, I can see with ProcessExplorer there is a git.exe process in the GitHubDesktop.exe tree that never ends:

These are the commands of these processes, that are never closed:
![Snap 2022-09-22 at 17 51 04](https://user-images.githubusercontent.com/28343859/191795029-27583f73-24bf-408c-b191-ed28b00feaef.jpg)

- First "git.exe" command: **C:\Users\XXX\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\cmd\git.exe -c credential.helper= fetch --progress --prune origin**
- Second "git.exe" command: **git.exe -c credential.helper= fetch --progress --prune origin**
- "ssh.exe" command: **C:/Windows/System32/OpenSSH/ssh.exe -o SendEnv=GIT_PROTOCOL gitolite@192.168.100.1 "git-upload-pack '/ProjectName'"**

Is it possible that the git.exe command is waiting the passphrase to be entered but GitHub Desktop is not displaying the appropriate dialog?

### Release version

Version 3.0.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Open GitHub Desktop
2. Click on "Fetch"

### Log files

[2022-09-22.desktop.production.log](https://github.com/desktop/desktop/files/9627368/2022-09-22.desktop.production.log)

### Screenshots

![Snap 2022-09-22 at 17 40 23](https://user-images.githubusercontent.com/28343859/191792067-f62d001a-a950-4cd5-984d-825550198bb8.jpg)

**Comment by maborec** [comment] 2022-09-22 15:55
By the way, I can see with ProcessExplorer there is a git.exe process in the GitHubDesktop.exe tree that never ends:
![Snap 2022-09-22 at 17 51 04](https://user-images.githubusercontent.com/28343859/191793980-768cdc04-aed6-4360-9d20-8cc277e18838.jpg)

These are the commands of these processes, that are never closed:
- First "git.exe" command: **C:\Users\XXX\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\cmd\git.exe -c credential.helper= fetch --progress --prune origin**
- Second "git.exe" command: **git.exe -c credential.helper= fetch --progress --prune origin**
- "ssh.exe" command: **C:/Windows/System32/OpenSSH/ssh.exe -o SendEnv=GIT_PROTOCOL gitolite@192.168.100.1 "git-upload-pack '/ProjectName'"**

Is it possible that the git.exe command is waiting the passphrase to be entered but GitHub Desktop is not displaying the appropriate dialog?

**Comment by sergiou87** [comment] 2022-09-23 08:51
> Is it possible that the git.exe command is waiting the passphrase to be entered but GitHub Desktop is not displaying the appropriate dialog?

That is entirely possible 🤔 Could you try and run those commands from your command line and see what the prompt is? This is what GitHub Desktop is expecting: https://github.com/desktop/desktop/blob/2914fa3f50d5d329354cb134f7c8911017aa3b12/app/src/lib/trampoline/trampoline-askpass-handler.ts#L49

**Comment by maborec** [comment] 2022-09-23 09:09
Thank you, Sergio.

I have executed the git.exe line from the command line: **C:\Users\Admin\AppData\Local\GitHubDesktop\app-3.0.8\resources\app\git\cmd\git.exe -c credential.helper= fetch --progress --prune origin**

First, there was an issue with the key type:
**Unable to negotiate with _xx.xx.xx.xx_ port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss**
**fatal: Could not read from remote repository.**

I have edited .ssh/config so it accepts ssh-rsa and I have tried the command line again.
This time, it is working fine and it is asking for the passphrase with the text (including the space character at the end):
**Enter passphrase for key '/c/Users/Admin/.ssh/id_rsa':**

However, it is still not working in GitHub Desktop (same behaviour) 

It seems to me this text matches the promptRegex in the code you pointed to. In understand that GitHub Desktop should display a prompt asking for the passphrase, but it doesn't.
Is there any way for the command line output to be added to the log file, or an easy way to tweak the code to add some logging and see what is going on?

**Comment by sergiou87** [comment] 2022-09-23 09:18
Thanks for the quick check 🙌  As you say, that seems to match the regex perfectly. Did you try to enter your passphrase and see if it's able to fetch from the command line?

> Is there any way for the command line output to be added to the log file, or an easy way to tweak the code to add some logging and see what is going on?

I don't think so 😢 Other than building Desktop yourself (which is not terribly complicated if you're familiar with Node/JavaScript development).

I'm gonna try and repro it myself in a Win11 VM I have 🤞

**Comment by maborec** [comment] 2022-09-23 09:27
The fetch process worked fine in the command line.

It would be great to be able to configure a "debug mode" in GitHub Desktop and modify the code to be more verbose in the log file in certain parts of the code (for example outputting the command line results). 
Maybe i could open a new feature request for this?

**Comment by maborec** [comment] 2022-09-23 11:39
I'm a newbie with Node.js, but I'm trying to add some logging to figure out the issue.
I have installed Node.js and have been able to run Desktop using **yarn start**
Then, I have edited **trampoline-askpass-handler.ts** adding some **log.info()** calls to try to log what is happening.

I can see in the Console that it tries to recompile this change:

**[HMR] bundle rebuilt in 9544ms
process-update.js:51 [HMR] Checking for updates on the server...**

However, for some reason, it is no compiling the file I edited. The Console says:

**Ignored an update to unaccepted module ./app/src/lib/trampoline/trampoline-askpass-handler.ts -> ./app/src/lib/trampoline/trampoline-server.ts -> ./app/src/lib/trampoline/trampoline-environment.ts -> ./app/src/lib/ssh/ssh.ts -> ./app/src/ui/preferences/advanced.tsx -> ./app/src/ui/preferences/preferences.tsx -> ./app/src/ui/preferences/index.ts -> ./app/src/ui/app.tsx -> ./app/src/ui/index.tsx**

Any idea on how to enable the compilation of this changes (change the "unaccepted module" to "accepted")? 
Thanks!

**Comment by sergiou87** [comment] 2022-09-23 12:13
Hmmm "live reloading" is not enabled, instead we make changes in the code, and then focus on the Dev Tools pane and press Control+R to reload the app. After that, the changes we made take effect. Is that helpful? 😳

**Comment by maborec** [comment] 2022-09-23 15:01
Very helpful! I've been able to execute Desktop modifying the code by Control+R.

I have detected where the process gets stuck:
[https://github.com/desktop/desktop/blob/2914fa3f50d5d329354cb134f7c8911017aa3b12/app/src/lib/git/core.ts#L168](url)

At this point the code **GitProcess.exec(args, path, opts)** is executed and the promise never returns.
I have seen that the code of the class **GitProcess** is not in the source code of 'desktop', but is included in the library "dugite".
Therefore, I cannot dig deeper.

The call to  **GitProcess.exec(args, path, opts)** that gets stuck is receiving the parameters:
**args: -c,credential.helper=,fetch,--progress,--prune,--recurse-submodules=on-demand,origin**
**path: [the path of the project directory]**

Any suggestion on how to go on?

**Comment by sergiou87** [comment] 2022-09-23 15:54
And you said running git with those parameters just asked you for the passphrase but after that it worked fine, right? 🤔 

So with your changes, are you able to `log.info(…)` what happens in the `trampoline-askpass-handler.ts` and everything looks correct? You should see how that code picks both the SSH key filename from the prompt using the regex from before, and also how it tries to provide the right passphrase (either from the prompt dialog you got, or from the Windows Credentials Manager via [keytar](https://github.com/atom/node-keytar).

If all that makes its way to git/ssh, I wonder why is it getting stuck.

The way that passphrase makes it back to git/ssh is via a socket that [desktop-trampoline](https://github.com/desktop/desktop-trampoline) opens. Have you tried to restart in case you have some port in use or something weird going on? I'm out of ideas right now 🤔 😳

**Comment by maborec** [comment] 2022-09-23 16:40
> And you said running git with those parameters just asked you for the passphrase but after that it worked fine, right? 🤔

Yes, it works fine from the command line.

> So with your changes, are you able to log.info(…) what happens in the trampoline-askpass-handler.ts and everything looks correct? You should see how that code picks both the SSH key filename from the prompt using the regex from before, and also how it tries to provide the right passphrase (either from the prompt dialog you got, or from the Windows Credentials Manager via [keytar](https://github.com/atom/node-keytar).

I have been able to **log.info(...)**, and I have added many to see where the code goes through.
The code is not arriving to **trampoline-askpass-handler.ts**, it gets stuck before that:
In **core.ts**:

- **git()** is executed with the "fetch" command
- **withTrampolineEnv()** is executed
- It then invokes **GitProcess.exec()** within **GitPerf.measure()**

This is where the code gets stuck: It seems the Promise never ends.
So, the handlers in **trampoline-askpass-handler.ts** ar never invoked (I have added **log.info()** in all the functions there).
That's why it seems to be an issue in the "dugite", that contains dugite. This is where I lose track.

**Comment by sergiou87** [comment] 2022-09-29 11:02
Sorry I didn't get back to you! I've been busy 😅 

If it didn't even get to the `trampoline-askpass-handler.ts` it might mean git didn't invoke the `GIT_ASKPASS` app to prompt the ssh key passphrase (could you check your `git config` in that repo and see if maybe [`core.askpass`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreaskPass) is being replaced or something) 🤔 

Can you see the env variables of a given process from Process Explorer? It'd be nice to see if it has the right env variables set up by `withTrampolineEnv`

**Comment by maborec** [comment] 2022-10-04 08:01
I have no setting set for `core.askpass`: `git config -l | grep askpass`displays nothing.

These are the GIT-related environment options in the git.exe process. I think they look fine:
![Snap 2022-10-04 at 10 00 11](https://user-images.githubusercontent.com/28343859/193766518-56811119-8ee9-40cf-bb80-66093a880d99.jpg)

![Snap 2022-10-04 at 10 00 23](https://user-images.githubusercontent.com/28343859/193766530-87641e55-e387-4932-b03e-e0278f58b517.jpg)

**Comment by sergiou87** [comment] 2022-10-04 15:49
@maborec yeah, all that looks good. Have you seen `DESKTOP_` env vars? There should be a bunch used by the desktop-trampoline to identify the app.

Other ideas:
1. In Settings -> Advanced, uncheck the `Use system OpenSSH (recommended)` checkbox
2. Open the command prompt and run `C:\Windows\System32\OpenSSH\ssh.exe -V` to see the version of OpenSSH used:
![image](https://user-images.githubusercontent.com/1083228/193865992-8abed73c-470d-41a5-9d47-7ee344a79d26.png)

**Comment by maborec** [comment] 2022-10-05 07:52
Hi Sergio. Thank you again for your suppor and patience!

1. If I uncheck this option, I get a message saying authentication failed. Right now I have not linked Github Desktop with any GitHub account, because I'm using it with a private Git server, not GitHub. With this option unchecked, is it mandatory to log in GitHub?
2. This the version I have now: OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by sergiou87** [comment] 2022-10-05 08:17
1. Nope, the app should work mostly the same way with that option unchecked. The only difference is that, with that option checked, if you use Windows' OpenSSH for other SSH/git apps in your system, GitHub Desktop will reuse any SSH config you might have, whereas if the option is unchecked, none of that global configuration will be used (and GitHub Desktop will use the SSH bundled in the installation).

2. I'm surprised your version of OpenSSH is 8.6p1, while mine is 8.1p1 (and in theory my Windows installation is up to date O_o). As far as I can see, that version has exactly the same prompt parsed by Desktop 😞 Do you have any special configuration in your `C:/Users/<your username>/.ssh`?

3. Just to sanity check, could you tell me if the process has `DESKTOP_` env vars?

**Comment by maborec** [comment] 2022-10-05 08:37
Finally it is working now!
The situation is:
1. I'm connecting to a server that uses key types that the new OpenSSH version refuses by default (ssh-rsa,ssh-dss).
2. Therefore, in order to connect, I need to create a `config` file in the `.ssh` directory allowing these key types for the server I'm connecting to
3. When using the "System OpenSSH", the system hangs, even with the `config` file.
4. When unchecking "System OpenSSH" and with the `config` file, it connects properly.

Is it possible that the "System OpenSSH" is not reading the `config`  file in the user's `.ssh` directory?

**Comment by sergiou87** [comment] 2022-10-05 09:05
I can't tell if there's been a change in that system OpenSSH, but in theory it should be looking at that `.ssh/config` folder O_o

Now that you know what happens, are you able to reproduce that weird ssh behavior from the command line? I'd love to know if the system OpenSSH outputs some kind of message that GitHub Desktop could detect to aid users in the same situation 😕 

Thanks for all the info, it's very useful!! And I'm glad you got it working now 😌

**Comment by maborec** [comment] 2022-10-05 09:12
I have tried to connect using the system OpenSSH in the command line (opened from GitHub Desktop option "Open in PowerShell") and nothing special appears:
   `C:\Windows\System32\OpenSSH\ssh.exe <mysever_host>`
It asks for the key passphrase as usual:
   `Enter passphrase for key 'C:\Users\XXX/.ssh/id_rsa':`
I think this is the kind of test you wanted me to try. Should you want me to do any other test, please let me know.

**Comment by sergiou87** [comment] 2022-10-05 09:48
Yeah that's what I had in mind, or maybe try running this:
```
set GIT_SSH_COMMAND=C:/Windows/System32/OpenSSH/ssh.exe
C:/Users/XXX/AppData/Local/GitHubDesktop/app-3.0.8/resources/app/git/cmd/git.exe -c credential.helper= fetch --progress --prune origin
```

From the command line from your repo folder. That should be somehow equivalent to what GitHub Desktop does (you make git run `fetch`, but tell it to use the System OpenSSH with that `GIT_SSH_COMMAND` env variable)

**Comment by maborec** [comment] 2022-10-05 17:31
Executing this, `Enter passphrase for key '/c/Users/XXX/.ssh/id_rsa':` as usual.
The only thing that is a bit special in my case is that, after entring the passphrase, I get some warning messages from my gitolite server (I have to review it to prevent those messages).
However, this happened before I had this issue as well.
And these messages appear after entering the passphrase, not before.
But this is the only 'special' thing I can see when executing from the command line.

**Comment by maborec** [comment] 2022-10-07 13:37
Hi Sergio,
I have updated my gitolite repository to a new server. I thought that, maybe, after upgrading from a old server the problem might get solved. However, I still have the issue with the system OpenSSH.
Will se if this problem appears to anyone else as they get the version "OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3".
Now, when I execute the command from the command line, as you suggested, it behaves normally.

I can work fine unchecking the "System OpenSSH", so it's fine now (but I'm curious about this weird issue).

**Comment by sergiou87** [comment] 2022-10-10 08:15
Thank you for helping me to debug this. Right now I'm out of ideas, but since unchecking "System OpenSSH" works for you, I'm gonna close this and keep an eye in case someone else runs into this.

Thank you again and sorry I couldn't be of more help! 🙇‍♂️

**Closed as completed by sergiou87** 2022-10-10 08:15 UTC

**Comment by galeamark7** [comment] 2022-12-12 15:14
I have the same issue on a brand new install. If I uncheck OpenSSH everything works, if I enable this setting it gets stuck on Hang On... forever. Initially I tough it is because I copied the Repo from another pc and used a different key and though maybe that there could be the issue with some cached data, however my issues are exactly like mentioned above.

**Comment by galeamark7** [comment] 2022-12-12 15:17
My Version is

OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022

**Comment by TZECHIN6** [comment] 2023-04-29 08:44
Same here, the quick solution to make Github desktop to work with passphrase is to disbale the option of using system OpenSSH in windows11

**Comment by nobozo** [comment] 2023-05-07 23:12
I had the same problem. I fixed it by replacing the files in "c:\program files\openssh" with the files from a Windows 10 installation. Windows 10 uses ssh 8.1p1 while Windows 11 uses 9.2.p1.

**Comment by steveward** [comment] 2023-05-08 20:23
Thanks for sharing that @nobozo. I'm looking into this and tested out that version of OpenSSH and still hit this issue (ssh -V outputs OpenSSH_for_Windows_8.1p1, LibreSSL 3.4.2). Does that match your installed version? Trying to narrow down if something specific caused this issue, which we're also tracking in https://github.com/desktop/desktop/issues/16542.

**Comment by nobozo** [comment] 2023-05-08 22:24
On 5/8/2023 1:31 PM, Steve Ward wrote:
> Thanks for sharing that @nobozo <https://github.com/nobozo>. I'm looking 
> into this and tested out that version of OpenSSH and still hit this 
> issue (ssh -V outputs OpenSSH_for_Windows_8.1p1, LibreSSL 3.4.2). Does 
> that match your installed version? Trying to narrow down if something 
> specific caused this issue, which we're also tracking in #16542 
> <https://github.com/desktop/desktop/issues/16542>.

I'm also using

OpenSSH_for_Windows_8.1p1, LibreSSL 3.4.3

that I copied directly from a working Windows 10 system.

I'm not using GitHub at all. This was just logging into a Linux
server from a Windows desktop.

Good luck!

Jon
