### ISSUE TITLE
After cloning, unable to fetch, pull, or push to remote origin while signed into Enterprise

### ISSUE THREAD

**Issue by mkmangiapane** [desktop/desktop#7713] opened 2019-06-06 17:10 UTC
## Description
GitHub Desktop does not allow me to fetch, push, or pull to a remote repository while signed in to GitHub Enterprise and after cloning a remote repository.  After signing out of GitHub Enterprise in GitHub Desktop, fetch, push, and pull to the same remote repository works.

## Version
* GitHub Desktop: 2.0.4
* Operating system: Windows 10 (10.0.15063)

## Steps to Reproduce
1. Go to File -> Options... -> Accounts and sign in to GitHub Enterprise on GitHub Desktop if not signed in already.
2. Clone a remote repository using an existing repository from Enterprise
3. Make changes to file(s) and commit
4. Attempt to push origin and nothing happens
5. Go to File -> Options... -> Accounts and sign out of GitHub Enterprise
6. Click Push Origin
7. Enter your GitHub Enterprise credentials if prompted
8. Changed files should push to origin

### Expected Behavior
I expected that I would be able to push and pull files to the remote repository while signed in to GitHub Enterprise.

### Actual Behavior
While signed into GitHub Enterprise in GitHub Desktop, I cloned a remote repository to my local drive and made changes to some files.  After pushing my changes locally I clicked on the "Push Origin" button and nothing happened.  I tried the Repository -> Push command in the menu and CTRL + P and nothing happened, it would not push.   I also tried to fetch the remote files again and it would not fetch the files from the remote.  After I signed out of GitHub Enterprise and happened to click fetch again, I got a prompt for my credentials which I filled in and I was able to fetch, push, and pull to remote.  However, as soon as I signed back into GitHub Enterprise it was back to not letting me push or pull my files.  I signed back out, and I could push and pull to remote once again.

## Additional Information
If I clone from Git Bash and try to push while signed in I have the same problem.

**Comment by steveward** [comment] 2019-06-06 18:05
Thanks for the report @mkmangiapane. Would you be able to upload a log file from GitHub Desktop so that I could take a closer look at what was happening here?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by mkmangiapane** [comment] 2019-06-06 18:15
Hi @steveward I've attached a log from today when this happened.
[2019-06-06.desktop.production.log](https://github.com/desktop/desktop/files/3262904/2019-06-06.desktop.production.log)

**Comment by say25** [comment] 2019-06-06 19:48
I am also experiencing this issue. I was not on `release-1.7.1-beta1` and have since gotten a new work machine. We are on `GitHub Enterprise Server 2.16.9`. 

I'll see if I can reset up to get my machine building Desktop locally and if there is anything I can do to investigate myself while the team diagnoses as well.

**Comment by tierninho** [comment] 2019-06-07 01:08
@mkmangiapane Although there is not much in the logs to assist our investigation, is there any special set up you use to connect, like a proxy?

The only clues spotted in your logs were:
`warn: [ui] Open Repository from URL failed, did not find or clone repository`
`warn: [ui] fetchRepository: 'user001/CHI_G' returned a 404`

The former one has appeared in similar issues: 
https://github.com/desktop/desktop/issues/4304
https://github.com/desktop/desktop/issues/4731

**Comment by kicasta** [comment] 2019-06-07 10:43
Having the same problem with similar log messages. The fetch button just doesn´t seem to work anymore after the initial clone was made

Already tried deleting everything in %APPDATA%\GitHub Desktop\ and starting the client again with no success. By doing this, old repositories that in the first moment worked, presented the same problem. So in hinsight, there might be a problem with the new version of Github Desktop from yesterday (06.06.2019) that prevent new repositories to be cloned correctly

**Comment by mkmangiapane** [comment] 2019-06-07 14:33
I've attached a zip that has a video showing the problem I'm having along with the desktop log from that day.  The part to especially pay attention to starts at 1:20 right after I commit a local change and attempt to push it back to our remote server.

[GitHubDesktopIssue7713.zip](https://github.com/desktop/desktop/files/3266331/GitHubDesktopIssue7713.zip)

@tierninho The only thing special about this setup is it's a Github Enterprise server that's internal to our network, I'm not using a proxy.

**Comment by tierninho** [comment] 2019-06-07 21:57
@kicasta Thanks for the summary. Possible to send over your logs so we can investigate? See the Help menu in Desktop.

**Comment by iAmWillShepherd** [comment] 2019-06-07 23:05
> I am also experiencing this issue. I was not on `release-1.7.1-beta1` and have since gotten a new work machine. We are on `GitHub Enterprise Server 2.16.9`.
> 
> I'll see if I can reset up to get my machine building Desktop locally and if there is anything I can do to investigate myself while the team diagnoses as well.

**Comment by shiftkey** [comment] 2019-06-10 16:22
I want to point out from this first log that @mkmangiapane sent through had some interesting clues:

> Hi @steveward I've attached a log from today when this happened.
> [2019-06-06.desktop.production.log](https://github.com/desktop/desktop/files/3262904/2019-06-06.desktop.production.log)

```
2019-06-06T15:01:59.124Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'Redacted.For.Debugging' and 'user001'
2019-06-06T15:02:03.733Z - info: [ui] Executing clone: git -c credential.helper= clone --recursive --progress -- https://Redacted.For.Debugging/AuthoringSandbox/gitplay.git C:\gitplay\gitplay (took 4.592s)
```

@mkmangiapane **can you confirm this is you trying to clone a GitHub Enterprise repository?** Our "generic credentials" here should only be used for non-GitHub and non-GitHub Enterprise repositories, so this might be a clue about the underlying problem. I also don't seem to see an error in the logs resulting from these Git operations - **can you provide details about the errors you are seeing?**

What's interesting here is that further down it's trying to lookup information from the GitHub API for this repository, but failing:

```
2019-06-06T15:12:35.709Z - warn: [ui] fetchRepository: 'user001/CHI_G' returned a 404
2019-06-06T15:12:35.723Z - warn: [ui] fetchMentionables: 'repos/user001/CHI_G/mentionables/users' returned a 404
2019-06-06T15:12:35.777Z - warn: [ui] fetchAll: 'repos/user001/CHI_G/pulls?state=open' returned a 404
2019-06-06T15:12:35.796Z - warn: [ui] fetchAll: 'repos/user001/CHI_G/issues?state=open' returned a 404
```

My theory here is that, building on top of the previous detail about generic credentials, it's not finding the right account and is falling back to call the API unauthenticated - which obviously won't work for GitHub Enterprise. We had some other reports about users not seeing their GitHub Enterprise repositories grouped correctly in the list, and I have a theory that is related to the problem you are experiencing.

**Comment by mkmangiapane** [comment] 2019-06-10 16:32
@shiftkey Ignore the CHI_G stuff as I think that's a red herring, I was not trying to work in a private repository at the time and I'm not sure what it was trying to log there.  I can confirm however that's me just with a more redacted credential name there,

Please take a look at my comment with the zip file as it has a demo video of the problem in action and the log from that day.  It shows it breaking when I login to GitHub Enterprise in the form of the push and fetch commands not reacting to my mouse click, but that does not show up in the logs.

**Comment by shiftkey** [comment] 2019-06-10 17:59
@mkmangiapane 

> It shows it breaking when I login to GitHub Enterprise in the form of the push and fetch commands not reacting to my mouse click, but that does not show up in the logs.

This feels like something related to app state that means the push/fetch is ignored completely. I've not been able to trip this scenario on my end, but I'd like to dig into the steps leading up to that because I think they're key here.

At 0:44 in the video I see that your cloned GitHub Enterprise repository has the generic icon:

<img width="747" src="https://user-images.githubusercontent.com/359239/59213392-2a6cd000-8b8b-11e9-9341-cf2c2c9adcd2.png">

I'd like to poke at that a bit and see if we can diagnose why that's the case (the clone worked fine, but it was a public repository so it didn't need credentials to work). I think there's flow-on effects from that around push that could be breaking because we aren't in the right state.

If you're able to debug the live app a bit, I have these instructions handy to poke at whether the app is correctly finding your GitHub Enterprise account for this repository. Here's the setup:

 - launch **View** | **Toggle developer tools** to launch the Chrome Dev Tools
 - under the **Sources** tab, press <kbd>CTRL</kbd> + P to open the file filter, and find the `repository-matching.ts` file

<img width="419" alt="investigate-matching-ghe-filter-file" src="https://user-images.githubusercontent.com/359239/59214484-89cbdf80-8b8d-11e9-84cb-3bd8bbfd1b70.png">

 - inside `repository-matching.ts`, add two breakpoints to that first function `matchGitHubRepository` - the first at line 38 to indicate success, the second at line 42 to indicate we didn't find a match

<img width="352" alt="investigate-matching-ghe-breakpoints" src="https://user-images.githubusercontent.com/359239/59214483-89334900-8b8d-11e9-8d37-1a6183533136.png">

 - with that configured, open the repository list in the app and click on the problem repository - this will try and refresh it's information using the API

I've only ever been able to trip line 38 (the found account) after signing into my GitHub Enterprise account but i think you're going to end up on line 42 (with no account found). If you can get to this point can you confirm:

 - which breakpoint you hit - the found account or no account found?
 - over in the "Scope" sidebar you'll see the local variables at each level - they've been minified so they don't match up with the source, but you should be able to find an `Array` in the list - that contains the accounts we use to look up things. Is there anything interesting in there that might help us understand the behaviour you're seeing?
 
<img width="631"  src="https://user-images.githubusercontent.com/359239/59214480-89334900-8b8d-11e9-9986-657eda740d22.png">

**I think knowing which endpoints are set for your accounts, and the remote URL we're trying to match, will help us to reproduce the problem ourselves.**

**Comment by mkmangiapane** [comment] 2019-06-10 19:25
@shiftkey 
So while I'm signed into Enterprise I went to clone the repository.

I hit the line 38 breakpoint.  Here's what I can find in the array about the endpoint: https://adsd-app10.ss-inf.nsx1.census.gov/api/v3  

Looking at your example and comparing it looks like I'm hitting our internal server that hosts the repositories and is looking for the v3 API

However, when I tell the script to keep running, I get two errors in the console, which I've attached in a log file (Lines 5 and 43 in UltraEdit)

[06102019EnterpriseCloning.log](https://github.com/desktop/desktop/files/3273455/06102019EnterpriseCloning.log)

If I am signed out of Enterprise and I use the direct URL to clone the repository, I hit the line 42 breakpoint and I get no errors.  I've attached that log as well

[06102019URLCloning.log](https://github.com/desktop/desktop/files/3273469/06102019URLCloning.log)

Hopefully that sheds a little more light as to what's going on here.

**Comment by shiftkey** [comment] 2019-06-10 20:05
@mkmangiapane this is actually some very helpful information, particularly this bit:

```
http.ts:145 GET https://adsd-app10.ss-inf.nsx1.census.gov/api/v3/repos/AuthoringSandbox/gitplay/branches?protected=true 404 (Not Found)
```

This to me reads like we don't handle this error when refreshing the repository. I was under the impression that this API was available in GHE long enough that we could assume it's always there.

Do you know what version of GitHub Enterprise you are connecting to? This is the API documentation I'm working from, and it should be available in GHE 2.14 or later (support for this version is due to be discontinued next month, and the latest version is `2.17`):

> https://developer.github.com/enterprise/2.14/v3/repos/branches/#list-branches

I'm going to put together a patch to address this unhandled error, which is helpful here anyway, but knowing this is affecting refresh (and potentially repository grouping) is very helpful - thanks for working through this with me!

**Comment by jfridgen** [comment] 2019-06-11 16:22
Our organization is also having this issue and receiving 404 errors with the list protected branches call.  It seems to be a permissions issue, where normal GitHub Enterprise users don't have access to make that call (can replicate the 404 with the same API call using a tool like Postman).  If I instead launch GitHub Desktop with my GH Enterprise Admin ID, I do not receive this error (succeeds in Postman as well).

What's also interesting is that the error does not seem to occur for repos cloned before upgrading to GH Desktop v2.0.3 but any repos cloned/added after upgrading to this version do have this error.

Is there any way to avoid the list protected branches call, since it doesn't appear most users have the necessary access for this call?

**Comment by shiftkey** [comment] 2019-06-11 16:25
> Is there any way to avoid the list protected branches call, since it doesn't appear most users have the necessary access for this call?

This will be fixed by #7754 while I investigate what is actually supported for users on GitHub Enterprise Server. This should go out with the next update (hopefully tomorrow).

**Comment by kennethmac2000** [comment] 2019-06-11 16:33
Perhaps a 'me too' comment isn't very useful at this point, but I also have what appears to be the same issue. Clicking, eg, "Push origin" does nothing in GitHub Desktop 2.0.3 Windows 64-bit. Our GHE is 2.14.18.

Have worked around for now by using Git CLI.

**Comment by billygriffin** [comment] 2019-06-11 18:11
@kennethmac2000 Definitely useful, thank you! We're hoping to release a fix for this this week, and would love confirmation when that happens that you're no longer experiencing (or continue to experience) the issue when we do.

**Closed** 2019-06-11 18:17 UTC
Labels: more-information-needed

**Comment by mkmangiapane** [comment] 2019-06-11 18:19
@shiftkey I checked with our folks and we're currently running GitHub Enterprise 2.15.4

**Comment by shiftkey** [comment] 2019-06-11 18:36
@mkmangiapane thanks for that. I've talked with some of our Enterprise engineers and am investigating how I can correctly call this API (because we'd love to do some stuff with branch protections in the future).

**Comment by billygriffin** [comment] 2019-06-12 15:47
Hi folks, the release (2.0.4) is out and you should see it in the next few hours or you can manually check for updates in the "About GitHub Desktop" section. When you do update, would you mind letting us know if this is fixed? Thanks so much and sorry for the disruption!

**Comment by kennethmac2000** [comment] 2019-06-12 17:22
Works now for me - thanks for the quick turnaround!

The only thing that may be worth adding is that when I clicked "Push origin", a Publish dialog box came up, asking me to confirm the repository, organization, etc. (Interestingly, the organization field was unpopulated.) I clicked Cancel, and the push still seemed to work anyway.

**Comment by shiftkey** [comment] 2019-06-12 17:23
> The only thing that may be worth adding is that when I clicked "Push origin", a Publish dialog box came up, asking me to confirm the repository, organization, etc. (Interestingly, the organization field was unpopulated.) I clicked Cancel, and the push still seemed to work anyway.

@kennethmac2000 this might have happened because we weren't detecting your remote correctly and asking you to publish. If you're able to reproduce this consistently, please open a new issue with information so we can troubleshoot further.

**Comment by mkmangiapane** [comment] 2019-06-12 17:30
It's working for me and for my colleagues that had trouble.  Thanks for getting this fixed so fast!  A bunch of staff is scheduled to take training on Github tomorrow so to have this fixed makes things much easier :-D

**Comment by jfridgen** [comment] 2019-06-12 17:36
Works for me and a couple co-workers that had the same issue now.  Thanks for resolving and releasing a new version so quickly!

**Comment by BlakRose76** [comment] 2019-06-26 15:50
https://github.com/desktop/desktop/issues/7713#issuecomment-500917815

**Comment by syedauroosa11** [comment] 2024-09-10 04:26
Question:
During bitbake i run this command:
uroosa@uroosa27:~/yocto/build$ bitbake linux-xlnx
but i get this error
WARNING: linux-xlnx-6.6.10+git-r0 do_fetch: Failed to fetch URL git://github.com/Xilinx/linux-xlnx.git;protocol=https;name=machine;branch=xlnx_rebase_v6.6_LTS, attempting MIRRORS if available
ERROR: linux-xlnx-6.6.10+git-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/uroosa/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/uroosa/yocto/sources/poky/scripts:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot-native/usr/bin/arm-poky-linux-gnueabi:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot/usr/bin/crossscripts:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot-native/usr/sbin:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot-native/usr/bin:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot-native/sbin:/home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/recipe-sysroot-native/bin:/home/uroosa/yocto/sources/poky/bitbake/bin:/home/uroosa/yocto/build/tmp/hosttools"; export HOME="/home/uroosa"; LANG=C git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all clone --bare --mirror https://github.com/Xilinx/linux-xlnx.git /home/uroosa/yocto/build/downloads/git2/github.com.Xilinx.linux-xlnx.git --progress failed with exit code 128, see logfile for output
ERROR: linux-xlnx-6.6.10+git-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/Xilinx/linux-xlnx.git;protocol=https;name=machine;branch=xlnx_rebase_v6.6_LTS')
ERROR: Logfile of failure stored in: /home/uroosa/yocto/build/tmp/work/zybo_zynq7-poky-linux-gnueabi/linux-xlnx/6.6.10+git/temp/log.do_fetch.109576
ERROR: Task (/home/uroosa/yocto/sources/meta-xilinx/meta-xilinx-core/recipes-kernel/linux/linux-xlnx_6.6.10-v2024.1.bb:do_fetch) failed with exit code '1'

Then i tried to download it manually using command:
git clone [git@github.com](mailto:git@github.com):Xilinx/linux-xlnx.git

after successful cloning i added the cloned repository to the specified path but still i am gettin g the same issue why? Please help me in this regard i am trying to do this from more than 3 days.
