### ISSUE TITLE
Pressing up arrow key when top history item is selected selects the bottom loaded history entry instead of doing nothing

### ISSUE THREAD

**Issue by BryanCrow** [desktop/desktop#11657] opened 2021-02-26 18:01 UTC
### Describe the bug

When holding up key when looking at history to scroll to the top of the list, the up key press on the top history item wraps back down to the bottom of the loaded history list. Can't imagine anyone wanting this wrapping behavior as the history item it jumps to is arbitrary based on the amount of history that has been loaded, and is "down" not "up". And because history continues to load when you press down instead of cycling back to the top, there's no quick way to get back to the top of the list (one's goal when holding the up key). The up key should simply be ignored once your selection is at the top of the history list.

### Version & OS

2.6.3 on Mac OS Big Sur

### Steps to reproduce the behavior

1. Go to History Tab
2. Click on Top Entry in History List
3. Press Up Key
4. See selection jump to the last loaded commit in history.

### Expected behavior

Up key does nothing when newest commit in history is selected.

### Actual behavior

Last commit in history currently loaded at the bottom of the list gets selected.

**Comment by steveward** [comment] 2021-02-26 20:04
Thanks for the issue @BryanCrow! This looks like a duplicate of https://github.com/desktop/desktop/issues/7679 so I'm going to close this issue out. Please follow along there for updates.

**Closed as completed by steveward** 2021-02-26 20:04 UTC
