### ISSUE TITLE
Bad APP UX and Colors on Mac OS Fresh Install

### ISSUE THREAD

**Issue by a31amit** [desktop/desktop#10821] opened 2020-10-13 03:20 UTC
### Describe the bug

Github Desktop App having problem with Startup UI and colors showing screen which is unreadable for Human Users. 
Please see the screenshot for understanding. I can't say this is a MacOS problem or App UI, but this is fresh install of MacOS and Desktop app was never install before on this. 

### Version & OS

Github Desktop - Version 2.5.6 
Apple MacOS - Catalina - 10.15.7

### Steps to reproduce the behavior

1. Download Latest Reversion or mentioned version from Github website
2. Extract Downloaded Zip and move Github Desktop App to Mac OS Application's Folder
3. Run Github Desktop App
4. App UX and colors are all jumbled, however if someone managed to skip all the login/setup option later stages show proper colors and UX

### Expected behavior

App UX and Colors should be visible clearly. 

### Actual behavior

APP UX design and colors seems having issue, Please see the screenshot

### Screenshots

<img width="962" alt="Screen Shot 2020-10-12 at 8 11 10 PM" src="https://user-images.githubusercontent.com/6764613/95811429-22192d80-0cc8-11eb-83a2-967589a31b8d.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
```
2020-10-13T03:08:48.772Z - info: [ui] [AppStore] loading 0 repositories from store
2020-10-13T03:08:49.253Z - info: [ui] Opt in reported.
2020-10-13T03:08:49.295Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:08:49.324Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:08:49.599Z - info: [ui] launching: 2.5.6 (Mac OS 10.15.7)
2020-10-13T03:08:49.599Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2020-10-13T03:08:49.600Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:08:49.601Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:08:49.604Z - error: [ui] fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
Error: API rate limit exceeded for 216.228.112.21. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ne (/webpack:/app/src/lib/http.ts:170:11)
    at /webpack:/app/src/lib/api.ts:1242:11
    at Object.endpointSupportsBasicAuth (/webpack:/app/src/lib/stores/sign-in-store.ts:317:11)
2020-10-13T03:08:49.612Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:08:59.765Z - info: [ui] [AppStore] loading 0 repositories from store
2020-10-13T03:09:00.280Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:00.305Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:00.344Z - info: [ui] launching: 2.5.6 (Mac OS 10.15.7)
2020-10-13T03:09:00.345Z - info: [ui] execPath: '/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer)'
2020-10-13T03:09:00.345Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:00.356Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:00.366Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:00.437Z - error: [ui] fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
Error: API rate limit exceeded for 216.228.112.21. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ne (/webpack:/app/src/lib/http.ts:170:11)
    at /webpack:/app/src/lib/api.ts:1242:11
    at Object.endpointSupportsBasicAuth (/webpack:/app/src/lib/stores/sign-in-store.ts:317:11)
2020-10-13T03:09:12.384Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:09:43.050Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:10:31.897Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:10:34.339Z - info: [ui] [Welcome] no sign in step found. ignoring...
2020-10-13T03:11:31.154Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2020-10-13T03:11:31.155Z - info: [ui] [SignInStore] initializing OAuth flow
2020-10-13T03:11:31.156Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=de0e3c7e9973e1c4dd77&scope=repo%20user%20workflow&state=5c3af21d-f3f8-4b56-a140-01bd7b11065d
2020-10-13T03:11:31.156Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2020-10-13T03:11:31.177Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:31.309Z - error: [ui] fetchMetadata: unable to load metadata from 'https://api.github.com/meta' as a fallback
Error: API rate limit exceeded for 216.228.112.21. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
    at Ne (/webpack:/app/src/lib/http.ts:170:11)
    at /webpack:/app/src/lib/api.ts:1242:11
    at Object.endpointSupportsBasicAuth (/webpack:/app/src/lib/stores/sign-in-store.ts:317:11)
2020-10-13T03:11:31.312Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:41.280Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:43.238Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:43.239Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:45.470Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:45.496Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:11:50.633Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:12:40.214Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:12:45.015Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:12:45.242Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:13:14.826Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:13:14.833Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:13:19.526Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:13:23.392Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2020-10-13T03:13:38.122Z - info: [ui] [Welcome] advancing to step: Start
2020-10-13T03:13:46.074Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2020-10-13T03:13:48.698Z - info: [ui] [Welcome] advancing to step: UsageOptOut
2020-10-13T03:13:53.907Z - info: [ui] Opt out reported.
```
### Additional context

None

**Comment by niik** [comment] 2020-10-13 14:03
Hey @a31amit, thanks for opening this. This is the first we've ever heard of this particular problem on macOS and we're unable to reproduce it. It's likely a condition specific to your environment.

I'm going to close this as it's not reproducible but we'll keep an eye out for similar reports to see if there's a pattern.

Thanks again!

**Closed by niik** 2020-10-13 14:03 UTC
