### ISSUE TITLE
GitHub Desktop login fails

### ISSUE THREAD

**Issue by cellog** [desktop/desktop#8627] opened 2019-11-13 17:55 UTC
### Describe the bug

Logging into GitHub account appears to work, but actually fails, and no write action succeeds. Login on command-line and push works.

### Version & OS

Version 2.2.3
Mac OS 10.15.1

### Steps to reproduce the behavior

1. Log in
2. Attempt to push/pull something to a remote

### Expected behavior

works

### Actual behavior

Popup appears that the action failed.

### Screenshots

![Screen Shot 2019-11-13 at 12 53 42 PM](https://user-images.githubusercontent.com/98250/68790136-bab8b080-0614-11ea-9382-c5093465051d.png)

### Logs

(see screenshot)

### Additional context

I fixed the problem by installing ssh-askpass

https://github.com/theseal/ssh-askpass

**Comment by tierninho** [comment] 2019-11-13 18:18
@cellog Thanks for filing this and glad you fixed it with askpass. This is a common occurrence so I will close this issue as it is resolved and has been previously documented.

**Closed by tierninho** 2019-11-13 18:18 UTC

**Comment by cellog** [comment] 2019-11-13 19:04
I didn't figure out how to fix it until I filed a bug, and learned about the logs. I wouldn't consider this "fixed" in its current state. Where is it documented?

**Comment by tierninho** [comment] 2019-11-13 19:19
The logs show (and the UI warning) that the cause of the authentication error due to your ssh key not being added to the ssh-agent. Once you did so it was resolved. If I am missing something, please advise.

**Comment by cellog** [comment] 2019-11-13 21:57
Sure. ssh-agent *does* have my key in it. I can run all git commands in the shell without re-entering the password. It is only GitHub Desktop that appears to struggle with this.

The error in the log states that `/usr/X11R6/bin/ssh-askpass` is being called, but the file doesn't actually exist, which shows an assumption about configuration that is inaccurate. Also, it doesn't appear to be properly querying sshagent. That's why I question whether this ticket is in fact resolved. Thanks for the comment, and giving me more context.
