### ISSUE TITLE
Volume Percentage Calculation Problem

### ISSUE THREAD

**Issue by Hesham-Dev-LY** [desktop/desktop#15363] opened 2022-09-26 11:39 UTC
### The problem

I changed an image with another image with the same name in the project, and about opening the program and checking the changes before uploading the code I clicked on the image file, the original file size is `42.53 KiB` and the new size is `55.14 KiB` with an increment of `12.61 KiB`, but the percentage is wrong `130%` .

### Release version

Version 3.0.8 (x64)

### Operating system

MacOS 12.5

### Screenshots

<img width="825" alt="Screen Shot 2022-09-26 at 1 38 27 PM" src="https://user-images.githubusercontent.com/66942907/192267126-38a3b75f-5879-498a-ada9-2a0cb03fea1f.png">

**Comment by tsvetilian-ty** [comment] 2022-09-26 12:33
@Hesham-Dev-LY thanks for reaching out! GitHub Desktop uses the same percent diff strategy as the GitHub Web. You can check https://github.com/desktop/desktop/issues/14863#issuecomment-1165263587 for additional info. 

Since it's expected behavior, I will close the issue.

**Closed as completed by tsvetilian-ty** 2022-09-26 12:33 UTC
