### ISSUE TITLE
Allow to set both "fetch" and "push" remote URL

### ISSUE THREAD

**Issue by gitghs** [desktop/desktop#7528] opened 2019-05-14 09:04 UTC
**Please describe the problem you think should be solved**

I recently renamed one of my Bitbucket repositories and encountered trouble pushing my commits: Github Desktop kept asking my Bitbucket credentials and authentication kept failing.

I went to the `Reposity > Repository settings...` menu to update the `Primary remote reposity (origin)` field accordingly, but I still wasn't able to push.

I finally identified the issue when I ran `git remote -v` and saw 2 different remote URLs:
```
$ git remote -v
> origin  https://<NEW_REPO_URL> (fetch)
> origin  https://<OLD_REPO_URL> (push)
```

So I went and specifically changed the push-flagged URL and then everything was back to normal:
```
$ git remote set-url --push origin https://<NEW_REPO_URL>
```

**[Optional] Do you have any potential solutions in mind?**

It seems like the `Primary remote reposity (origin)` field only edits the `(fetch)` URL if the reposity happens to have separate `(fetch)` and `(push)` remotes.

It would be nice to see both `(fetch)` and `(push)` remote URLs in the `Reposity settings` menu in order to avoid such confusion.

**Comment by steveward** [comment] 2019-05-14 12:15
@gitghs thanks for the report. I just tested out changing a remote URL in two repositories (including a Bitbucket test repository) on my machine and was unable to reproduce this behavior. Are you able to reproduce this issue again in a test repository? Can you also share the specific version of GitHub Desktop and the operating system you are using?

**Comment by LeoDupont** [comment] 2019-05-14 14:23
@steveward (I was logged in with my company's Github when I wrote this issue, sorry about that)

I use Github Desktop 1.6.5 on Windows 10 Pro (17134).
But I previously used Sourcetree with this repository for some time, maybe the duplicate of URLs happened back then at some point.

I renamed and relocated several other Bitbucket repositories but I couldn't reproduce this behaviour, it worked well on the first try.

**Comment by steveward** [comment] 2019-05-14 18:04
@LeoDupont thanks for the update! Since we're unable to reproduce this I am going to close this issue out. Let us know if you run into anything again and we can investigate further.

**Closed by steveward** 2019-05-14 18:05 UTC
Labels: more-information-needed

**Comment by LeoDupont** [comment] 2019-05-15 08:21
@steveward I actually don't think Github Desktop has any bug to be fixed. This issue was more about adding a feature.

I think it would be nice to visualize every URLs printed by `git remote -v` in the repository settings in order to avoid being confused like I was in this case.

That is, if more people than just me encounter this very specific issue.
