### ISSUE TITLE
zoom level is reset to default after updating app version

### ISSUE THREAD

**Issue by dremovv** [desktop/desktop#11234] opened 2020-12-15 13:58 UTC
### Describe the bug

When I click `restart` to update app version, zoom level is reset to default.

### Version & OS
Version 2.6.1
OS: windows 10

### Steps to reproduce the behavior

1. Open github desktop (need any version but last so it could be updated)
2. In `View` tab click `zoom in` so zoom level is not default
3. In `An updated version of GitHub Desktop is available` block click `restart GitHub Desktop now` link
4. Zoom level reset to default.

### Expected behavior

Restarting after update does not change zoom level.

### Actual behavior

Zoom level is changed to default.

### Additional context

In my case, github desktop is installed on remote pc to which I connect using RDP. I use 4k display so I have to use 300-400%, otherwise letters are too small. RDP limitations do not allow me to set zoom level system-wide so I have to use github desktop's zoom in feature. But after every update zoom level is reset and I have to set it again.

**Comment by billygriffin** [comment] 2020-12-15 14:23
Hi @dremovv, thanks for the issue! This is a duplicate of #5315 so please follow along there.

**Closed as completed by billygriffin** 2020-12-15 14:23 UTC
