### ISSUE TITLE
No split view on Github desktop

### ISSUE THREAD

**Issue by PiSagar** [desktop/desktop#4436] opened 2018-04-12 12:33 UTC

**Comment by DJWassink** [comment] 2018-04-16 08:57
Possible duplicate of #172 ?

**Comment by shiftkey** [comment] 2018-04-16 09:36
@DJWassink could be.

If this gets no reply after 7 days we'll close it out and suggest that issue might be the best match for what they're looking for.

**Comment by shiftkey** [comment] 2018-04-21 23:05
Closing in favour of #172.

**Closed by shiftkey** 2018-04-21 23:05 UTC
Labels: more-information-needed
