### ISSUE TITLE
Commit failed - exit code 1 received

### ISSUE THREAD

**Issue by franklinkf** [desktop/desktop#3701] opened 2017-12-30 06:56 UTC
First time I am using GitHub desktop. After adding one local repository and trying to commit changes, message - Commit failed - exit code 1 received - is coming.

Please advice me the solution

**Comment by j-f1** [comment] 2017-12-30 12:08
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway 😀

**Comment by iAmWillShepherd** [comment] 2018-01-08 16:40
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/desktop/desktop/issues/3701#issuecomment-354542868).
With only the information that is currently on the issue, we don't have enough
information to take action. I'm going to close this but don't hesitate to reach
out if you have or find the answers we need, we'll be happy to reopen the
issue.

**Closed by iAmWillShepherd** 2018-01-08 16:40 UTC
Labels: more-information-needed

**Comment by jordaofabio** [comment] 2018-03-13 11:39
I have the same problem. :/

**Comment by j-f1** [comment] 2018-03-13 12:00
@jordaofabio Can you open a new issue and fill out the issue template so we can understand what’s happening and how to fix it?

**Comment by AlaaCherbib** [comment] 2018-03-13 15:07
I have same issue

**Comment by j-f1** [comment] 2018-03-13 17:15
@AlaaCherbib Can you open a new issue like I asked for above?

**Comment by illysky** [comment] 2018-03-24 16:29
I had this issue with committing a project with an xcode project inside, but noticed I had a .git folder included within the xcode project. Removed the .git and all OK. 

May or may not be relevant to you all, but thought I'd share.

**Comment by MR-Mostafa** [comment] 2018-03-28 21:06
I have same issue

**Comment by anibaleproductions** [comment] 2018-04-07 01:55
thanx @illysky

**Comment by katelynsalem** [comment] 2018-04-12 21:01
suggestion from @illysky seems to have solved it for me too. Had a .git in my repository (which I needed) and a .git in a subfolder (which I deleted), then it worked.

**Comment by clagusto** [comment] 2018-04-15 18:54
idem @illysky

**Comment by mrg123** [comment] 2018-04-16 15:49
thanx @illysky

**Comment by KSneijders** [comment] 2018-05-19 20:19
@illysky Same issue, same solution. Thanks

**Comment by AaronRiboy** [comment] 2019-03-26 17:02
> I had this issue with committing a project with an xcode project inside, but noticed I had a .git folder included within the xcode project. Removed the .git and all OK.
> 
> May or may not be relevant to you all, but thought I'd share.

But i dont .git folder in respository ..Please someone help me

**Comment by illysky** [comment] 2019-03-26 18:26
Perhaps you need to show hidden files then you’ll see the .git folder?

**Comment by ChoyCheeWei** [comment] 2019-08-02 19:03
may I know where to find the .git folder?

**Comment by tierninho** [comment] 2019-08-02 20:48
@ChoyCheeWei Check that you have [Show hidden files](https://support.microsoft.com/en-ca/help/14201/windows-show-hidden-files) enabled for Windows Explorer, as files starting with a `.` may be hidden from you. If you have a Mac, try [this](https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/)

**Comment by echarles5wits** [comment] 2020-03-25 14:59
Is there a workaround for this other than deleting the .git file? We have nested git repos by design.

**Comment by will-sloan** [comment] 2020-06-28 20:50
I have the same problem, and when I deleted the nested .git, I couldn't add the folder anymore and the changes aren't getting tracked. Anyone know why?

**Comment by Hri100v** [comment] 2020-10-28 06:00
> > I had this issue with committing a project with an xcode project inside, but noticed I had a .git folder included within the xcode project. Removed the .git and all OK.
> > May or may not be relevant to you all, but thought I'd share.
> 
> But i dont have .git folder in respository ..Please someone help me

I found such folder (it was nested in my new folder).

**Comment by SharonCytheria** [comment] 2021-04-03 03:02
@illysky works for me. Thanks a lot!

**Comment by AndressMartin** [comment] 2022-08-24 13:46
So, I get that the problem is that there are two .git files, one in the origin and one in the target folder.

However, in our case, this was by design: We are creating a game and the origin folder contains all scripts and modifications that should go to every client, while the branch I was "merging into" contains only specific modifications for that client. I separate each of these branches in their own directories, so indeed each one was using their own .git. 

Is there a better way to achieve this?

**Comment by steveward** [comment] 2022-08-31 15:22
@AndressMartin submodules are recommended -- they allow you to keep a Git repository as a subdirectory of another Git repository.
