### ISSUE TITLE
issue cloning repository over SSH

### ISSUE THREAD

**Issue by TCS-Taylor** [desktop/desktop#3658] opened 2017-12-21 16:32 UTC
### Description

My company has a GitLab server.  The Infrastructure dept. has historically never used Git, but I'm working on changing that so that our scripts can be versioned, centrally located and backed up, etc.
I created a new Group and Project in our GitLab server.  I added the public key to my user account on our GitLab server.  The private key is loaded in my pagent.

I downloaded GitHub Desktop and installed it.  I tested "cloning an existing project" using the http url provided by our GitLab server.  worked great.  I then removed that repository, deleted the repository from my local disk and attempted the same clone but using the SSH address provided by our GitLab server.  When I try that, nothing is created on my local disk, and I am given the error 

"Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository."

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. install github desktop
1. attempt to clone a repository from a local gitlab server (on my LAN) using ssh

**Expected behavior:** the repository to be cloned

**Actual behavior:** an error message

**Reproduces how often:** 100%

### Logs
```
2017-12-21T15:37:00.892Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- git@gitlab.tcsbasys.com:it-scripts/login_scripts.git C:\Users\thammerling\Documents\GitHub\login_scripts` exited with an unexpected code: 128.
Cloning into 'C:\Users\thammerling\Documents\GitHub\login_scripts'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

(The error was parsed as 2: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```

**Comment by j-f1** [comment] 2017-12-21 16:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2579. Please follow that issue for further updates.

**Comment by niik** [comment] 2017-12-22 07:42
@TCS-Taylor Thanks for reaching out. As @j-f1 mentioned our support for ssh-remotes still leaves a bit to be desired and requires some manual work on each machine to function properly. For now we'd recommend using http.

**Closed by niik** 2017-12-22 07:42 UTC
