### ISSUE TITLE
Losing stashed changes after renaming a branch, without any warning

### ISSUE THREAD

**Issue by nilslindemann** [desktop/desktop#16832] opened 2023-06-04 07:44 UTC
### The problem

See description below.

### Release version

3.2.1-linux2 (x64)

### Operating system

Linux Mint 21.1 Cinnamon

### Steps to reproduce the behavior

1. Have a test repo, open it in GitHub Desktop.
2. Create a branch named `foo`.
3. Switch to it, make some changes without committing.
4. Switch to `main` branch, choosing "leave my changes on `foo`".
5. Rename `foo` to `foo-renamed`.
6. Switch to `foo-renamed` branch. The stash is gone.

The stash can be restored by renaming `fo-renamed` back to `foo`, see [here](https://github.com/desktop/desktop/issues/8817). The point is, GitHub Desktop shows no warning, that the stash will be lost, when renaming the branch `foo` while in branch `main`.

**Comment by nilslindemann** [comment] 2023-06-04 08:02
In the meantime, It would be of interest to know the git command which prints out this previous name ("foo" in this case).

**Comment by tidy-dev** [comment] 2023-06-05 11:36
@nilslindemann Thanks for reaching out. This appears to be duplicate of https://github.com/desktop/desktop/issues/16442 of which fix is underway. :) 

There is a warning about the stash being lost, albeit not a very prominent one.
<img width="601" alt="CleanShot 2023-06-05 at 07 35 15@2x" src="https://github.com/desktop/desktop/assets/75402236/e9da6d65-45d2-4790-9040-4b618f71f76c">

**Closed as not planned by tidy-dev** 2023-06-05 11:36 UTC

**Comment by nilslindemann** [comment] 2023-06-05 18:14
@tidy-dev

Have you gone through the step-by-step instructions?

**Comment by nilslindemann** [comment] 2023-06-05 19:27
[Video](https://www.youtube.com/watch?v=sQ5Jq_z5j00). Sorry for bad quality, YouTube has not yet fully processed it.

**Comment by tidy-dev** [comment] 2023-06-06 14:51
Ah! Good catch that the check is not displayed when you are not on the branch you are renaming. However, still going to close this in favor of the tracking the change to move the stashes and remove the need for the warning all together.

**Comment by nilslindemann** [comment] 2023-06-07 04:09
Thanks for feedback, will delete video now.
