### ISSUE TITLE
Account type not being reported correctly

### ISSUE THREAD

**Issue by iAmWillShepherd** [desktop/desktop#1516] opened 2017-05-16 20:53 UTC
It looks like the `enterpriseAccount` property is only being submitted when it's set to `true`. This property should be sent when equal to `false` as well.

**Comment by joshaber** [comment] 2017-05-17 16:00
I couldn't reproduce this. The JSON sent from the app seemed to always include `enterpriseAccount` even when `false`.

**Comment by joshaber** [comment] 2017-05-18 12:55
This is still happening with 0.5.4. I haven't figured out where we're losing this data 😞

**Comment by joshaber** [comment] 2017-05-18 13:54
I think I've narrowed this down to a problem further up in our stats pipeline. Closing.

**Closed by joshaber** 2017-05-18 13:54 UTC
Labels: bug, triaged
