### ISSUE TITLE
No response for clicking 'X' in full screen mode on macOS

### ISSUE THREAD

**Issue by TerryChan** [desktop/desktop#12574] opened 2021-07-07 09:08 UTC
### Describe the bug

No response then click the red 'X' button on full screen mode

### Version & OS

Version 2.9.0 (x64)
macOS: 10.15.7 (19H2)

### Steps to reproduce the behavior

1. Enter full screen mode by clicking the green maximise button
2. Leave the Desktop screen by by move on touchpad with 4 fingers (maybe you have diffrent touchpad settings)
3. Enter the Desktop screen with 4 finger on touchpad again (don't click the Desktop icon on Dock)
4. Click the red 'X' button
5. No response

### Expected behavior

Exit the Desktop full screen

### Actual behavior

No response for clicking red 'X' button

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Additional context

When you go back to the Dekstop screen (repro step 3) by clicking Desktop icon on Dock, and then click the red 'X' button, sometimes the behavior is corrent, it will exit the full screen.

I'm not sure whether the issue is same as this one: #12391

**Comment by steveward** [comment] 2021-07-12 20:49
Thanks @TerryChan, this is a duplicate of #9757 so I am going to close this out.

**Closed as completed by steveward** 2021-07-12 20:49 UTC
