### ISSUE TITLE
Switching to a branch with submodules is not possible

### ISSUE THREAD

**Issue by enumag** [desktop/desktop#18821] opened 2024-06-11 20:42 UTC
### The problem

The issue has been reported 3 years ago in #13016 and mistakenly closed as duplicate of #9174 while it is in fact a separate and still existing bug.

If GitHub Desktop cloned a repository on a branch without submodules, when attempting to switch to a branch with submodules, GitHub Desktop throws the following error:

```
fatal: not a git repository: ../.git/modules/<submodule name>
fatal: could not reset submodule index
```

### Release version

3.6.1

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Create a repository with a default branch set to a branch without any submodules.
2. Create a branch in the repository and add a submodule to it.
3. Switch back to the default branch without submodule.
4. Checkout this repository with GitHub Desktop. It should checkout the default branch without submodules.
5. Try checking out the submodule branch. GitHub Desktop should throw the error mentioned at the top of this page.

### Log files

Can't share them publicly because I noticed it on a private repository. It should be easy to reproduce though.

### Screenshots

![image](https://github.com/desktop/desktop/assets/539462/5ee3a5ab-a337-417f-bd3e-703345a23737)

**Comment by steveward** [comment] 2024-06-13 15:55
Thanks for opening this @enumag.

**Comment by steveward** [comment] 2024-06-24 14:11
Closing this as a duplicate of https://github.com/desktop/desktop/issues/18673.

**Closed as completed by steveward** 2024-06-24 14:11 UTC
Labels: bug, priority-2

**Comment by thiagonrodrigues30** [comment] 2024-11-14 18:26
@steveward , this is a joke right? Are you able to read? This duplicate was created because the original one was MISTAKENLY CLOSED, the issue is still happening 3 years after as you can see by just looking at the comments on #13016

That is a very poor support given, to not say something else.

**Comment by james-belva** [comment] 2025-02-05 19:30
@steveward please re-open this. It is not a duplicate and is still an issue.
