### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by jdunham22** [desktop/desktop#4524] opened 2018-04-25 05:04 UTC
## Version

* GitHub Desktop:1.1.1

* Operating system:Microsoft Windows [Version 6.1.7601]

## Steps to Reproduce

1.  log into github.com on chrome
2. switch contexts to my workplace org "AppAccount"
3. click on one of our private repositories
4. click on "clone or download"
5. choose "open in desktop", "URL" (url is automatically filled out"
6. use the "choose..." button to choose a new folder
7. press "clone"

### Expected Behavior

Expected to check out the repository

### Actual Behavior

error message "We were unable to authenticate with github.com. Please enter your username and password to try again."  Inputting the correct password has no effect, the same dialog box comes back.

## Additional Information

![image](https://user-images.githubusercontent.com/723070/39226938-7c2a6742-480a-11e8-959d-15400292fa9e.png)

### Logs

[2018-04-25.desktop.production.log](https://github.com/desktop/desktop/files/1945498/2018-04-25.desktop.production.log)

**Comment by steveward** [comment] 2018-04-26 18:12
@jdunham22 I'm glad to hear things are working for you now. I'm going to close this out and mark it as being needed to be reproduced in case anyone runs into something similar in the future.

**Closed by steveward** 2018-04-26 18:12 UTC
Labels: reviewer-needs-to-reproduce

**Comment by Sugavanas** [comment] 2018-10-22 09:16
Hi,

I have this same problem happening to me.

https://i.gyazo.com/4f706c5f5d805081f3d41cb9dfe26c74.png
https://i.gyazo.com/4a7c30a6dbfae2753e48b37f6805bbb2.png

It was working fine before. I just signed out from the app and tried signing back in and this issue started happening. This was using the latest version of the app.

I uninstalled using Revo and installed back an old version I had, but it still has the same problem.

I don't see any repository on the list, I asked a friend to install github desktop to try it and he has the same problem as well.

**Comment by Sugavanas** [comment] 2018-10-22 09:17
Hi,

I have this same problem happening to me.

https://i.gyazo.com/4f706c5f5d805081f3d41cb9dfe26c74.png
https://i.gyazo.com/4a7c30a6dbfae2753e48b37f6805bbb2.png

It was working fine before. I just signed out from the app and tried signing back in and this issue started happening. This was using the latest version of the app.

I uninstalled using Revo and installed back an old version I had, but it still has the same problem.

I don't see any repository on the list, I asked a friend to install github desktop to try it and he has the same problem as well.

**Comment by Sugavanas** [comment] 2018-10-22 09:20
Hi,

I have the same problem. I am on Windows 10.

https://i.gyazo.com/4f706c5f5d805081f3d41cb9dfe26c74.png
https://i.gyazo.com/4a7c30a6dbfae2753e48b37f6805bbb2.png

It was working fine before. I just signed out from the app and tried signing back in and this issue started happening. This was using the latest version of the app.

I uninstalled using Revo and installed back an old version I had, but it still has the same problem.

I don't see any repository on the list, I asked a friend to install github desktop to try it and he has the same problem as well.

**Comment by bayssmekanique** [comment] 2018-10-22 13:12
@Sugavanas, I'm having the same issue. If I had to guess it's probably because of the data restore:  https://blog.github.com/2018-10-21-october21-incident-report/

**Comment by directred** [comment] 2019-01-03 17:31
> @jdunham22 thanks for the report. Could you go to the file menu and select `File` > `Options` > `Accounts` and make sure you are still logged in to your GitHub account?
> 
> > When I click on "Select a repository" in Desktop, I don't see any of the repositories for my work organization even though I can see them at github.com in Chrome.
> 
> You should see your repositories in GitHub Desktop by going to `File` > `Clone repository` > `GitHub.com`.

**Comment by directred** [comment] 2019-01-03 17:32
@steveward thanks for the fix above. I had to sign in using my private Enterprise account in order to clone a repo. Thanks for your help.

**Comment by reneegade** [comment] 2019-01-14 04:49
I just had the exact same issue. Downloaded desktop today. Was logged in in Chrome / clicked on clone or download / Open in desktop / cloning started then notification that it could not authenticate.

Signed out and back in again and all good.

**Comment by pjc0247** [comment] 2019-02-25 06:42
I think this still exists in v1.6.2, but issue has been closed.

**Comment by bnazaruk** [comment] 2019-02-26 23:50
just happened to me out of the blue. I created a repo using and try cloning it on a different machine using the same account and getting this error.

**Comment by tierninho** [comment] 2019-02-27 01:11
@bnazaruk We are happy to help you resolve. Please fill a new issue though. Thanks!

**Comment by bnazaruk** [comment] 2019-02-27 01:17
why filling another issue if this one hasn't been resolved? 

I fixed it for myself, but the bug is still there and lots of people gets frustrated. I'd suggest github to take it on with their QA team.

**Comment by tierninho** [comment] 2019-02-27 01:23
You may be correct, but every setup if different and each piece of the puzzle get us closer to resolving it. Since you resolved the issue, do mind sharing the fix? Thanks in advance.

**Comment by bnazaruk** [comment] 2019-02-27 17:29
the fix was mentioned before. You just log out and log in again via the settings. This is probably because the authentication module that's being shown when you need to confirm your creds, like when cloning a new repo, is broken. Maybe it has issues with the two-factor auth.

**Comment by Phil-Factor** [comment] 2019-03-04 09:53
I have no idea if this is the same issue but ....Created a gist, clicked on the 'save to your computer ...blah..GitHub Desktop'. All worked fine. Created a new gist and saved it to a file in Github directory created by the previous operation. saved in local repository. Tried to push to Github. 'Bang'. "We were unable to authenticate with gist.github.com. Please enter your usemame and password to try again." I did, Ir repeated etc etc. stuck in endless loop.

**Comment by NotHansDampf** [comment] 2019-03-10 16:17
Another lovely victim of this issue here.. Signed out and signed in both through my browser and by typing in my credentials, uninstalled and installed GitHub desktop numerous times... No dice. 

I can see everything I need in GitLab, and other collaborators seem to be able to clone/etc as needed without issue. I am on 1.6.2, a freshly downloaded installer and all.. 

Not sure what information I can provide, but a fix for this would be appreciated :)

**Comment by bnazaruk** [comment] 2019-03-11 16:46
@NotHansDampf a manual fix would be relogin. It was mentioned above. But yes, it would be great if github devs would fix this issue.

**Comment by steveward** [comment] 2019-03-11 19:18
@NotHansDampf you mentioned you were using GitLab:

> I can see everything I need in GitLab, and other collaborators seem to be able to clone/etc as needed without issue. I am on 1.6.2, a freshly downloaded installer and all..

Did you create a personal access token with the correct scope? You can follow GitLab's guide for how to do that here:

https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html

You won't be able to log in with your GitLab account in GitHub Desktop, but when you attempt to clone a GitLab repository you can enter your GitLab username and personal access token into the authentication dialog that appears. Let me know if that doesn't get things working.

**Comment by pjc0247** [comment] 2019-03-14 01:26
@tierninho I can give you a log.  Where can I find it?

Only happens in Github Desktop,  commandline works fine.

**Comment by steveward** [comment] 2019-03-14 14:08
@pjc0247 to access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. 

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by pjc0247** [comment] 2019-03-18 11:17
@steveward 

```
2019-03-18T11:10:36.845Z - info: [ui] [AppStore] loading 9 repositories from store
2019-03-18T11:10:36.847Z - info: [ui] [AppStore] found account: pjc0247 (Park June Chul)
2019-03-18T11:10:38.998Z - info: [ui] launching: 1.6.3 (Windows 10.0.17134)
2019-03-18T11:10:38.999Z - info: [ui] execPath: 'C:\Users\pjc02\AppData\Local\GitHubDesktop\app-1.6.3\GitHubDesktop.exe'
2019-03-18T11:10:39.013Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.761s)
2019-03-18T11:10:39.014Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.455s)
2019-03-18T11:10:39.819Z - info: [ui] Stats reported.
2019-03-18T11:10:40.763Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 2.382s)
2019-03-18T11:10:40.764Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.252s)
2019-03-18T11:10:56.653Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.138s)
2019-03-18T11:10:56.660Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/pjc0247/pix.oldschool.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
2019-03-18T11:11:32.119Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pix.oldschool - pjc0247 (has token)
2019-03-18T11:11:33.932Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.710s)
2019-03-18T11:11:33.933Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/pjc0247/pix.oldschool.git/'

(The error was parsed as 3: Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.)
```


`https://github.com/pjc0247/pix.oldschool.git/` is absolutely mine and but it says you don't have a permission. that's all

**Comment by NotHansDampf** [comment] 2019-03-18 11:20
@steveward: that was the issue! Wasn't aware that the token should be used as a password!

Thinking out loud, maybe that would be a nice piece of information to include in an authentication error message.

Thanks!!!!!

**Comment by steveward** [comment] 2019-03-22 16:38
@pjc0247 have you tried logging out and then logging back in to GitHub Desktop to see if that gets things working? Can you also verify that the `GitHub - https://api.github.com/<username>` entry exists in `Credential Manager` > `Windows Credentials`?

@NotHansDampf I'm glad to hear that got things working for you. I've got an [open PR](https://github.com/desktop/desktop/pull/7147) that walks through how to authenticate to Bitbucket and GitLab.

**Comment by Asciant** [comment] 2019-04-15 22:09
@steveward logging in and logging out didn't seem to help. Also the same error occurs when using the command line, so it isn't a Desktop specific issue.

**Comment by gmferguson** [comment] 2019-05-13 19:08
I'm having this same issue, but I am on a mac. When I go to file, there is no "Options > Accounts" path. Under the file dropdown, I only see Add New Repository, Add local Repository or Clone repository.

**Comment by gmferguson** [comment] 2019-05-13 19:10
Figured it out by going to Github Desktop>Preferences>Accounts. Signed out and back in and now cloning works as expected.

**Comment by Runemoro** [comment] 2019-10-05 01:57
This also happens when you use the "Clone again" button on a repository that you deleted both locally and on GitHub (but for some reason, still shows up in Github Desktop's repository list).

**Comment by ManalLiaquat** [comment] 2020-07-22 08:01
> ing to Github Desktop>Preferences>Accoun

Did this but error still not gone, I am having this when pulling; push is working fine

**Comment by Yuunus** [comment] 2020-09-16 00:32
Tried logging out from local GitHub and logging back again, that sorted out the authentication issues for me

**Comment by arehman98** [comment] 2020-09-19 07:22
Just Sign out from github desktop and then Sign in again ... it would resolve the errors. (it worked for me)

**Comment by jayjani10** [comment] 2020-11-12 06:33
> Just Sign out from github desktop and then Sign in again ... it would resolve the errors. (it worked for me)

EXACTLY !
This worked for me too! Thanks man 💯

**Comment by TinaMcN** [comment] 2020-11-19 02:15
> > Just Sign out from github desktop and then Sign in again ... it would resolve the errors. (it worked for me)
> 
> EXACTLY !
> This worked for me too! Thanks man 💯

Also worked for me, thank you for the tip!

**Comment by docdyhr** [comment] 2021-04-01 07:55
I have the same problem with GitHub Desktop for Mac. I have tried to sign in and out without any success! The issue still persists when logged in, but only for gist.github.com!? What is going on here...??

**Comment by Sunsprint** [comment] 2021-04-03 22:22
I'm on ubuntu and am having this issue. Relogging doesn't work.

**Comment by steveward** [comment] 2021-04-05 14:29
@docdyhr there is a current bug when working with Gists where pushing falls back to basic authentication (which will no longer work). See https://github.com/desktop/desktop/issues/2973 for details and tracking. The best workaround is to push to your gist via the command line.

@Sunsprint for problems with the Linux fork of GitHub Desktop please open an issue in https://github.com/shiftkey/desktop/issues. I would recommend searching the issue tracker to see if there is an existing related issue.

**Comment by sverrirb89** [comment] 2021-04-13 11:05
sign out of the github desktop and sign again it fixed my same problem.

**Comment by Devendrakumarsharma** [comment] 2021-05-28 05:48
Github Desktop>Preferences>Accounts. Signed out and back in and now cloning works as expected.

**Comment by AKheli** [comment] 2021-06-27 15:42
Signing out and back in didn't work for me. I had to clone the repo through terminal then locate it with Github Desktop.

**Comment by ghost** [comment] 2022-09-19 04:16
![cdc](https://user-images.githubusercontent.com/73213326/190949046-beb9e54c-25c8-4217-a2d2-a3315692014c.png)

**Comment by ghost** [comment] 2022-09-19 04:17
I have to login another account to github desktop and it gives me this error what should i do ? Anyone can helo me?

**Comment by steveward** [comment] 2022-09-20 16:44
@msvegad GitHub Desktop does not provide support for multiple accounts, you will need to log out of our existing account and then log in again. We're tracking multiple account support in https://github.com/desktop/desktop/issues/3707.

**Comment by amedwardson** [comment] 2022-10-28 15:22
> I just had the exact same issue. Downloaded desktop today. Was logged in in Chrome / clicked on clone or download / Open in desktop / cloning started then notification that it could not authenticate.
> 
> Signed out and back in again and all good.

I also just had this exact issue on macOS Monterey and signing out and in fixed it for me too 👍🏻

**Comment by KofiLeslie** [comment] 2023-02-27 09:05
This is very urgent. I cannot find my organizations in Github Desktop but I can see them in my browser. I have tried all the solutions here but none of them seem to solve my issue. I am using Ubuntu 22.04 LTS. Please help

**Comment by steveward** [comment] 2023-02-27 18:01
@KofiLeslie if you are logged in you will see repositories from organizations you belong to in the clone dialog. See [this article](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-and-forking-repositories-from-github-desktop).

**Comment by luojiawhu** [comment] 2023-02-28 15:58
Hi I have the same issue. I can login, see my org and the list of repos. However, when i click on clone or push commit, it tells me auth failed. I tried re-login but got no luck. I can see all the repos in chrome.

**Comment by steveward** [comment] 2023-02-28 17:28
@luojiawhu if you upload a log file in a reply I can take a look to see what might be happening there.

**Comment by danveritus** [comment] 2023-11-04 12:58
Facing this issue on Manjaro Linux.

**Comment by amarraff** [comment] 2024-05-28 15:43
Currently experiencing this on Linux Mint 21.3

**Comment by foinf** [comment] 2024-08-16 11:48
Same issue on Pop! OS 22.04 LTS. I can't clone any repositories at all. Tried signing out and in again.

**Comment by steveward** [comment] 2024-08-16 12:39
For issues authenticating with the Linux fork I would recommend looking through the issue tracker over there:

https://github.com/shiftkey/desktop/issues
