### ISSUE TITLE
update from master when branch is based on a different branch?

### ISSUE THREAD

**Issue by sdiedrichsen** [desktop/desktop#6885] opened 2019-02-20 09:10 UTC
Seen with GutHub desktop 1.6.2:

If I create a branch based on a branch xxx and not the master, the menu item Branch/Update from master doesn't make so much sense to me, it should say Update from xxx.

**Comment by niik** [comment] 2019-02-20 11:06
Hi @sdiedrichsen, thanks for reporting this. This is the intended behavior, the shortcut menu item will always do a quick update of your branch based on the "default branch". Accurately figuring out which branch a particular branch was based on is a complex task. If you look at the menu item two steps below `Update from master` you'll see the `Merge into Current branch` menu item which lets you pick which branch to merge from.

You can also click on the History view and select your origin branch as the "compare branch" and it'll both show you any commits your missing (and that the origin branch is missing) as well as let you quickly get up to date with that origin branch.

I hope that helps! I'm going to close this issue out for now as this is the intended behavior but feel free to comment if you have more context that would be helpful.

**Closed by niik** 2019-02-20 11:06 UTC
