### ISSUE TITLE
When copying text from file preview first character is missed

### ISSUE THREAD

**Issue by lambidu** [desktop/desktop#2621] opened 2017-09-05 21:18 UTC
### Description

When copying text from file preview first character is missed.

### Version

**GitHub Desktop version:** 0.8.0

**OS version:** Microsoft Windows [Version 10.0.15063]

### Steps to Reproduce

1. Open any file in preview
2. Select and copy some text
3. Try paste it anywhere

On the screenshot, selected text has been copied then pasted to notepad

![image](https://user-images.githubusercontent.com/2502621/30083499-4d4beb7c-9297-11e7-9e1e-d80c6a880734.png)

**Comment by j-f1** [comment] 2017-09-05 22:02
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2492, which got fixed in #2499 and should be released with the next update.

**Closed** 2017-09-05 22:13 UTC
