### ISSUE TITLE
Can there be a Linux app?

### ISSUE THREAD

**Issue by wall03** [desktop/desktop#9820] opened 2020-05-18 11:57 UTC
### Describe the feature or problem you’d like to solve

I would like to use GitHub Desktop, but I have Linux, and there isn't an app for that.

### Proposed solution

Why is there not a Linux app? Linux is the only major open-source OS, yet THE GITHUB does not have a Linux app.

### Additional context
Not applicable

**Comment by steveward** [comment] 2020-05-18 13:27
At this time there are no official builds of GitHub Desktop available for Linux, but a former developer of GitHub Desktop helps maintain a fork with Linux builds available for download:

https://github.com/shiftkey/desktop/releases

Closing as a duplicate of https://github.com/desktop/desktop/issues/1525 -- you can follow along there for any updates about Linux support.

**Closed by steveward** 2020-05-18 13:27 UTC
