### ISSUE TITLE
Push/Pull doesn't work anymore

### ISSUE THREAD

**Issue by Serkonda** [desktop/desktop#6668] opened 2019-01-19 14:05 UTC
## Description

Since the 1.6.0 update everytime I try to push some changes it opens the 'Publish repository' window, although my repo is already published and still there. 
Pulling doesen't work too and it seems like I cannot delete branches, it just keeps loading for infinite in this case. 

## Version

* GitHub Desktop: 1.6.0

* Operating system: Microsoft Windows [Version 10.0.17134.523]

## Steps to Reproduce

1. Open Desktop and despair...

### Expected Behavior
No problems

### Actual Behavior
Can't work with Desktop on anything

## Additional Information
If I move my local clone to a new folder and reclone the repo everything works until I close Desktop and open it again.

### Logs
[2019-01-18.desktop.production.log](https://github.com/desktop/desktop/files/2775585/2019-01-18.desktop.production.log)
[2019-01-19.desktop.production.log](https://github.com/desktop/desktop/files/2775586/2019-01-19.desktop.production.log)

**Comment by shiftkey** [comment] 2019-01-21 14:51
@Serkonda thanks for the report. This looks like the root cause of the problem:

```
019-01-19T13:49:39.837Z - error: [ui] `git -c credential.helper= push origin leaf-basics:leaf-basics --progress` exited with an unexpected code: 128.
fatal: no path specified; see 'git help pull' for valid url syntax

2019-01-19T13:49:57.903Z - error: [ui] `git -c credential.helper= push origin leaf-basics:leaf-basics --progress` exited with an unexpected code: 128.
fatal: no path specified; see 'git help pull' for valid url syntax
```

But I'm not sure where to start about recreating this on my end so I have a few things I need to start digging.

Can you share the output of these commands when run against the problem repository:

```
$ git remote -vv
$ git branch --all 
```

This will help me understand the state of your local repository and the remote to help with troubleshooting.

Second, do you have any hooks defined for the repository? These files live in`.git/hooks/` (ignore any ending in `.sample` as they're there for demonstration purposes) and might be running behind the scenes to trigger this issue.

Lastly, do you have any Git aliases configured in your global `~/.gitconfig`? I ask because the error message is suggesting the help docs for `git pull`, but the operation itself is a `git push`, and I'd like to confirm there's nothing like that which might be changing the behaviour of Desktop unexpectedly.

**Comment by Serkonda** [comment] 2019-01-22 15:40
**First of: I were able to fix the problem by reinstalling GitHub Desktop.**

But here the outputs:
- I have no hooks defined.
- No aliases too.

$ git remote -vv
```
origin  https://github.com/Serkonda/WebKara (fetch)
origin  https://github.com/Serkonda/WebKara (push)
```

$ git branch --all:
```
  error-prompt
* master
  tree-basics
  remotes/origin/HEAD -> origin/master
  remotes/origin/error-prompt
  remotes/origin/master
  remotes/origin/tree-basics
```

**Comment by steveward** [comment] 2019-01-29 18:57
@Serkonda I'm glad to hear you were able to get things working. Everything looks correct in your repository configuration output. I am going to close this issue out, but please let us know if you encounter this issue again.

**Closed by steveward** 2019-01-29 18:57 UTC
Labels: more-information-needed
