### ISSUE TITLE
Block selection in long diff cannot be selected

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7088] opened 2019-03-14 19:19 UTC
Block selection in long diff cannot be selected in order to commit a partial, like so:

![Mar-14-2019 09-12-24](https://user-images.githubusercontent.com/14828183/54384843-51be0a80-4639-11e9-9cc2-482d98ae6b1b.gif)

v1.6.5-beta2, mac

I used this to test with:
https://norvig.com/big.txt

⚠️ NOTE: you must see this UI first:

<img width="568" alt="Screen Shot 2019-03-14 at 9 16 58 AM" src="https://user-images.githubusercontent.com/14828183/54385181-1a9c2900-463a-11e9-9a8a-1248c622c048.png">

**Comment by shiftkey** [comment] 2019-03-14 19:21
Cross-referencing what feels like a related issue: #6510

**Comment by billygriffin** [comment] 2019-03-14 19:28
Yep, this is a duplicate of #6510 so I'm going to close. 😄 Thanks @tierninho!

**Closed by billygriffin** 2019-03-14 19:28 UTC
Labels: bug, priority-3
