### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by BoxGamesCorp** [desktop/desktop#14155] opened 2022-03-11 18:23 UTC
### Help please!

Enumerating objects: 2492, done.
Counting objects: 100% (2492/2492), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2048/2048), done.
error: RPC failed; curl 55 Send failure: Connection was aborted
send-pack: unexpected disconnect while reading sideband packet
Writing objects: 100% (2065/2065), 207.80 MiB | 2.63 MiB/s, done.
Total 2065 (delta 862), reused 79 (delta 5), pack-reused 0
fatal: the remote end hung up unexpectedly
Everything up-to-date

I'm trying to upload my project through the github application, or rather its files. There is such an error. I've uploaded a backup before, and I'm very surprised that this nonsense has reappeared. What is the problem please help!

**Comment by steveward** [comment] 2022-03-11 21:53
Thanks for the report @BoxGamesCorp. Unfortunately this type of error can often just be caused by a connection issue. Are you on a reliable network? Are you behind any sort of proxy or firewall? If you can try pushing on a different network that would help narrow down the issue.

Some users have also had success switching to use SSH instead of HTTPS. If you're interested in learning how to set a new SSH key you can follow [this guide](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent).

**Comment by BoxGamesCorp** [comment] 2022-03-29 20:59
It didn’t work out, I don’t understand, one project loads quietly, and the other cannot ...

**Comment by steveward** [comment] 2022-03-30 20:48
@BoxGamesCorp are you still having issues pushing, or are you encountering another specific error?

**Comment by BoxGamesCorp** [comment] 2022-03-30 20:53
The same problem, I'll try to solve it by connecting myself to another Internet source, it's just strange why one project loads and the other doesn't ... If I don't write, then the problem has been solved. Thank you in advance

**Comment by steveward** [comment] 2022-03-30 21:04
OK, let us know how that goes! I would recommend trying SSH like I mentioned above since that may help. I'm going to close this out.

**Closed as completed by steveward** 2022-03-30 21:04 UTC
Labels: support
