### ISSUE TITLE
Feature/OpenWithIntellij

### ISSUE THREAD

**Issue by RichardTMiles** [desktop/desktop#9087] opened 2020-02-10 18:15 UTC
### Describe the feature or problem you’d like to solve

When cloning a repository the default option is VS code. When changing options in context menu the editor IntelliJ does not resolve. 

### Proposed solution

the internal command (should the installation check box been pressed) that is in the path to open in IntelliJ is 

`idea .`

where the dot "." is the directory to open in a new project view. 

optionally allowing a custom command to run in this context menu would be nice. 

### Additional context

Thanks for all you do :) Keep up the good work!

**Comment by Rexogamer** [comment] 2020-02-10 18:32
There’s already a PR for this (albeit only on Mac): #8399

**Comment by tierninho** [comment] 2020-02-10 18:34
Closing this as a dupe of #8398. Please follow along there.

**Closed by tierninho** 2020-02-10 18:34 UTC
