### ISSUE TITLE
GitHub Desktop Installation Fails when MS Teams is installed, but not initialized

### ISSUE THREAD

**Issue by AndrewDownum** [desktop/desktop#15654] opened 2022-11-20 18:18 UTC
### The problem

I attempted to install GitHub Desktop for Windows (64bit) from https://desktop.github.com/ on a machine that I'm just doing initial setup on.  I had downloaded and installed Microsoft Office (Including MS Teams) but had not yet opened that application or set it up.

When attempting to install GitHub Desktop I got a SquirrelSetup log (full file attached
[SquirrelSetup.txt](https://github.com/desktop/desktop/files/10050375/SquirrelSetup.txt)

Reading the log seemed to indicate an issue with MS Teams, so I opened MS Teams and completed the initialization process there first, and then re-attempted the GitHub Desktop installation which worked normally at that point.

### Release version

Version 3.1.2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. Have a machine which has MS Teams Installed, but never opened/initialized
2. Attempt to install GitHub Desktop for Windows (64bit)
3. Crash

### Log files

[SquirrelSetup.txt](https://github.com/desktop/desktop/files/10050380/SquirrelSetup.txt)

**Comment by Moi0** [comment] 2022-12-01 06:16
[text 37.txt](https://github.com/desktop/desktop/files/10129737/text.37.txt)
[text 36.txt](https://github.com/desktop/desktop/files/10129738/text.36.txt)
[text 38.txt](https://github.com/desktop/desktop/files/10129739/text.38.txt)
[text 39.txt](https://github.com/desktop/desktop/files/10129740/text.39.txt)
[text 34.txt](https://github.com/desktop/desktop/files/10129741/text.34.txt)
[File Dec 04, 3 57 22 PM 2.txt](https://github.com/desktop/desktop/files/10129742/File.Dec.04.3.57.22.PM.2.txt)
[File Jan 10, 3 32 57 PM 2.txt](https://github.com/desktop/desktop/files/10129744/File.Jan.10.3.32.57.PM.2.txt)
[File_000.txt](https://github.com/desktop/desktop/files/10129745/File_000.txt)
[text 35.txt](https://github.com/desktop/desktop/files/10129746/text.35.txt)
[File Jan 10, 3 32 57 PM.txt](https://github.com/desktop/desktop/files/10129747/File.Jan.10.3.32.57.PM.txt)
[File_000 2.txt](https://github.com/desktop/desktop/files/10129748/File_000.2.txt)
[LICENSE-code 1 2.txt](https://github.com/desktop/desktop/files/10129749/LICENSE-code.1.2.txt)
[mamabears-logs-1668715762696.txt](https://github.com/desktop/desktop/files/10129750/mamabears-logs-1668715762696.txt)
[LICENSE-code 1.txt](https://github.com/desktop/desktop/files/10129751/LICENSE-code.1.txt)
[main.txt](https://github.com/desktop/desktop/files/10129752/main.txt)
[Note 2022-11-17 13-08-42.txt](https://github.com/desktop/desktop/files/10129753/Note.2022-11-17.13-08-42.txt)
[main 2.txt](https://github.com/desktop/desktop/files/10129754/main.2.txt)
[NOTICE.txt](https://github.com/desktop/desktop/files/10129755/NOTICE.txt)
[mamabears-logs-1668715762696 2.txt](https://github.com/desktop/desktop/files/10129756/mamabears-logs-1668715762696.2.txt)
[NOTICE 2.txt](https://github.com/desktop/desktop/files/10129757/NOTICE.2.txt)
[text.txt](https://github.com/desktop/desktop/files/10129758/text.txt)
[Note 2022-11-17 13-08-42 2.txt](https://github.com/desktop/desktop/files/10129759/Note.2022-11-17.13-08-42.2.txt)
[text 2.txt](https://github.com/desktop/desktop/files/10129760/text.2.txt)
[text 3.txt](https://github.com/desktop/desktop/files/10129761/text.3.txt)
[text 5.txt](https://github.com/desktop/desktop/files/10129762/text.5.txt)
[text 4.txt](https://github.com/desktop/desktop/files/10129763/text.4.txt)
[text 6.txt](https://github.com/desktop/desktop/files/10129764/text.6.txt)
[text 7.txt](https://github.com/desktop/desktop/files/10129765/text.7.txt)
[text 10.txt](https://github.com/desktop/desktop/files/10129766/text.10.txt)
[text 8.txt](https://github.com/desktop/desktop/files/10129767/text.8.txt)
[text 11.txt](https://github.com/desktop/desktop/files/10129768/text.11.txt)
[text 14.txt](https://github.com/desktop/desktop/files/10129769/text.14.txt)
[text 9.txt](https://github.com/desktop/desktop/files/10129770/text.9.txt)
[text 12.txt](https://github.com/desktop/desktop/files/10129771/text.12.txt)
[text 13.txt](https://github.com/desktop/desktop/files/10129772/text.13.txt)
[text 18.txt](https://github.com/desktop/desktop/files/10129773/text.18.txt)
[text 19.txt](https://github.com/desktop/desktop/files/10129774/text.19.txt)
[text 16.txt](https://github.com/desktop/desktop/files/10129775/text.16.txt)
[text 15.txt](https://github.com/desktop/desktop/files/10129776/text.15.txt)
[text 20.txt](https://github.com/desktop/desktop/files/10129777/text.20.txt)
[text 21.txt](https://github.com/desktop/desktop/files/10129778/text.21.txt)
[text 17.txt](https://github.com/desktop/desktop/files/10129779/text.17.txt)
[text 23.txt](https://github.com/desktop/desktop/files/10129780/text.23.txt)
[text 26.txt](https://github.com/desktop/desktop/files/10129781/text.26.txt)
[text 22.txt](https://github.com/desktop/desktop/files/10129782/text.22.txt)
[text 25.txt](https://github.com/desktop/desktop/files/10129783/text.25.txt)
[text 27.txt](https://github.com/desktop/desktop/files/10129784/text.27.txt)
[text 30.txt](https://github.com/desktop/desktop/files/10129785/text.30.txt)
[text 29.txt](https://github.com/desktop/desktop/files/10129786/text.29.txt)
[text 24.txt](https://github.com/desktop/desktop/files/10129787/text.24.txt)
[text 32.txt](https://github.com/desktop/desktop/files/10129788/text.32.txt)
[text 28.txt](https://github.com/desktop/desktop/files/10129789/text.28.txt)
[text 31.txt](https://github.com/desktop/desktop/files/10129790/text.31.txt)
> ### The problem
> I attempted to install GitHub Desktop for Windows (64bit) from https://desktop.github.com/ on a machine that I'm just doing initial setup on. I had downloaded and installed Microsoft Office (Including MS Teams) but had not yet opened that application or set it up.
> 
> When attempting to install GitHub Desktop I got a SquirrelSetup log (full file attached [SquirrelSetup.txt](https://github.com/desktop/desktop/files/10050375/SquirrelSetup.txt)
> 
> Reading the log seemed to indicate an issue with MS Teams, so I opened MS Teams and completed the initialization process there first, and then re-attempted the GitHub Desktop installation which worked normally at that point.
> 
> ### Release version
> Version 3.1.2 (x64)
> 
> ### Operating system
> Windows 11
> 
> ### Steps to reproduce the behavior
> 1. Have a machine which has MS Teams Installed, but never opened/initialized
> 2. Attempt to install GitHub Desktop for Windows (64bit)
> 3. Crash
> 
> ### Log files
> [SquirrelSetup.txt](https://github.com/desktop/desktop/files/10050380/SquirrelSetup.txt)
> 
> ### Screenshots
> _No response_
> 
> ### Additional context
> _No response_

Salut><

**Comment by steveward** [comment] 2023-01-26 22:54
Thanks for reporting this @Moi0. I'm not seeing anything specific to GitHub Desktop in the log file, normally there would be a line like this when the install attempt starts:

```
> Program: About to install to: C:\Users\Username\AppData\Local\GitHubDesktop
```

Did anything happen when you initially attempted the install, or did it immediately error out?

Since this is likely an edge case that we haven't had any other reports of I'm going to close this out, but if we see more cases of this in the future we can investigate further.

**Closed as completed by steveward** 2023-01-26 22:54 UTC

**Comment by demgunde23** [comment] 2023-04-15 15:30
hey, I'm also getting the exactly same issue as @AndrewDownum mentioned. i have uninstalled the MS Teams which i have not been using since while but still getting the same issue. please help me with this issue

[SquirrelSetup.txt](https://github.com/desktop/desktop/files/11239888/SquirrelSetup.txt)

**Operating system**
Windows 10

Steps to reproduce the behavior
Have a machine which has MS Teams Installed, but never opened/initialized
Attempt to install GitHub Desktop for Windows (64bit)
Crash

**Screenshots**
![image](https://user-images.githubusercontent.com/130847092/232234227-55450855-4bfd-46f8-b660-4b62aae49d21.png)

**Comment by thedevastator9** [comment] 2023-04-15 16:29
lør. 15. apr. 2023, 17:31 skrev demgunde23 ***@***.***>:

**Comment by UIT19521334** [comment] 2024-07-23 07:00
the same it installed but it show like this and i can't open github
![image](https://github.com/user-attachments/assets/7a274b84-3302-48db-ba9a-6f5e1b9ab3a4)

**Comment by mayurbadam** [comment] 2024-08-27 03:39
Even I am seeing the same error
![image](https://github.com/user-attachments/assets/178a5eec-2d8d-4047-b2eb-2762fbfe9c15)

Please help me resolve the issue, Iam also attaching the log file below:
[SquirrelSetup.log](https://github.com/user-attachments/files/16756152/SquirrelSetup.log)

**Comment by steveward** [comment] 2024-08-27 15:51
@mayurbadam I'm not seeing anything related to GitHub Desktop in the Squirrel log file you attached. Are you behind any antivirus or other security software that could be interfering with the installation You could try deleting the `C:\Users\AppData\Local\SquirrelTemp` directory and then restarting your machine to see if that helps.
