### ISSUE TITLE
Feature Request: Bring back the visual history / selector

### ISSUE THREAD

**Issue by omnipitous** [desktop/desktop#4628] opened 2018-05-07 18:48 UTC
## Description
The visual representation of your branch history in the old tool was an incredibly useful feature allowing easy inspection of history as well as an easy way to hop around the diff. Would be lovely to have in the new app.

## Version
* GitHub Desktop:
Version 1.1.1
* Operating system:
Microsoft Windows [Version 10.0.17134.1]

## Steps to Reproduce
Open the app. Don't see the visual branch history view.

### Expected Behavior
See the view.

### Actual Behavior
Don't see the view.

## Additional Information
This feature was great in the old desktop.

### Logs
Not pertinent for feature request.

**Comment by j-f1** [comment] 2018-05-07 19:28
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1634. Please follow that issue for further updates.

**Comment by shiftkey** [comment] 2018-05-07 21:04
@omnipitous thanks for the feedback, and thank @j-f1 for pointing out the existing issue.

**Closed by shiftkey** 2018-05-07 21:04 UTC
