### ISSUE TITLE
I suggest that you can create categories or folders in the list of items on the left side of the desktop software

### ISSUE THREAD

**Issue by wzs28150** [desktop/desktop#10359] opened 2020-08-10 05:16 UTC
Because I often use desktop software, I have cloned many projects through the software, but I can't sort them out in the project list, which makes me feel confused and unclear. Hope to add classification or archive classification or customize the directory function

**Comment by niik** [comment] 2020-08-10 08:28
Hi @wzs2815, thank you for the suggestion. This appears to be a duplicate of #1533 which resulted in #6460. While we don't currently have any plans to support creating folders we will reopen #1533 if we do decide to move forward with grouping so please follow that issue for any updates.

**Closed by niik** 2020-08-10 08:28 UTC
