### ISSUE TITLE
Git credential does not update with new login

### ISSUE THREAD

**Issue by kinsidar** [desktop/desktop#3023] opened 2017-10-11 22:43 UTC
### Description

When logging into a new Github account on Github Desktop and pushing changes, it is pushed as the previous account which was logged out

### Version

**GitHub Desktop version:** 1.0.3

**OS version:** Microsoft Windows [Version 10.0.10240]

### Steps to Reproduce

1. Log into your account in Github Desktop, clone a repository
1. Log out, log into a different account
1. Make changes and commit

![capture041](https://user-images.githubusercontent.com/13373809/31470837-a71e329e-ae9a-11e7-9fca-acb503f54d22.png)

**Expected behavior:** The changes are pushed on the new logged in account

**Actual behavior:** The changes are pushed on the old logged out account with the new logged in account's credentials

**Reproduces how often:** 100%

**Comment by shiftkey** [comment] 2017-10-11 22:50
@kinsidar 

I have a couple of questions:

 - Can you share which repository was used at the time of pushing?
 - Could you also attach the log files under **Help** | **Show logs in Explorer**?
 - Which "git scm" are you referring to? Could you provide more information and/or screenshots so I can understand how these might be related?

**Comment by kinsidar** [comment] 2017-10-11 22:55
Sure,

Repository:
https://github.com/peterennis/aegit

Log file:
[2017-10-10.desktop.production.log](https://github.com/desktop/desktop/files/1377415/2017-10-10.desktop.production.log)

I am also referring to enabling the git credential manager when installing git:
![git scm](https://user-images.githubusercontent.com/13373809/31471210-86e63d80-ae9c-11e7-9aa7-5770ff36de20.png)

**Comment by shiftkey** [comment] 2017-10-11 22:57
@kinsidar thanks for the help. Don't worry about the Git Credential Manager - we use a different way to authenticate.

**Comment by shiftkey** [comment] 2017-10-11 23:15
@kinsidar so what's happened is:

 - when Git creates a commit, it needs a name and email address
 - when you push commits to GitHub, it uses your GitHub credentials to verify you have access to that repository to push changes
 - so, for example, I could push commits that impersonate @joshaber, but I can't push to repositories that I cannot access but he can.
 - It's one of the downsides of how Git was designed (here's [a fun commit](https://github.com/amoffat/masquerade/commit/9b0562595cc479ac8696110cb0a2d33f8f2b7d29)) and why we recommend [commit signing](https://help.github.com/articles/signing-commits-using-gpg/) if you have concerns about this sort of thing)
 - when you login for the first time and you don't have a name and email set, we lookup and pre-fill details from your GitHub account. That's likely how the first account's name and email were set.
 - changing your account in the Preferences view won't do any checks for name and email. That's likely what (didn't) happen when you switched accounts.

Looking at the log for that repository, the three recent commits are for `Kinsa Durst <kinsadurst@gmail.com>` and then `peterennis <peterennis@yahoo.com>`. These are associated with two GitHub different accounts, which is where the confusion comes in.

**Comment by shiftkey** [comment] 2017-10-12 06:39
@kinsidar the distinction between commit author and credentials is by design, but we've had a couple of discussions about addressing this friction:

 - #610 - "Warn user if their user.email isn't in their GitHub.com emails"
 - #1860 - "Git name and email getting overridden by SourceTree"
 - #2829 - "GitHub Enterprise repos need their own e-mail setting or default of LDAP account email"

Let me know if there's any other questions you have around this area.

**Comment by shiftkey** [comment] 2017-10-17 00:21
I'm going to close this out as by design. @kinsidar please follow up if you have any other questions.

**Closed by shiftkey** 2017-10-17 00:21 UTC
