### ISSUE TITLE
GitHub Desktop stores password as plain text and can show it to the user

### ISSUE THREAD

**Issue by BasThomas** [desktop/desktop#2858] opened 2017-09-24 10:39 UTC
### Description

GitHub Desktop may boot and immediately show an error like `line 1: keyword expected; got **password**`.

### Version

**GitHub Desktop version:** 1.0.1

**OS version:** 10.12.6

### Steps to Reproduce

Not reproducible; but happening consistently during startup on one client; also after updating the app.

**Expected behavior:** Client works as expected

**Actual behavior:** Client works as expected, but prints an error message on startup including the user's password in plain text.

**Reproduces how often:** Every startup

### Logs

Let me know if/how I can share logs discretely.

**Comment by shiftkey** [comment] 2017-09-24 20:55
@BasThomas thanks for the information - you can send any sensitive details to the email address over in [my profile](https://github.com/shiftkey). Any stack traces that might explain how it's getting into this state are particularly helpful here...

**Comment by BasThomas** [comment] 2017-09-26 18:08
@shiftkey sent a mail.

**Comment by shiftkey** [comment] 2017-10-03 23:06
Just dropping a note in here to say that I've been going back and forth with @BasThomas about this, but I haven't been able to identify the root cause. Stay tuned.

**Comment by juanrivas89** [comment] 2017-10-03 23:08
El oct. 3, 2017 16:06, Brendan Forster <notifications@github.com> escribió:

Just dropping a note in here to say that I've been going back and forth with @BasThomas<https://github.com/basthomas> about this, but I haven't been able to identify the root cause. Stay tuned.

**Comment by shiftkey** [comment] 2017-10-03 23:29
And of course I stumble upon the source of this error message: https://github.com/git-lfs/git-lfs/blob/b7b1f2b7985c8f7a18c563c70898f669ffb8c13c/vendor/github.com/bgentry/go-netrc/netrc/netrc.go#L353

This seems to be occurring whenever we invoke `git lfs` in the app on @BasThomas's machine. While I work with him to reproduce the issue I'll try and trace back to how Git LFS is using `go-netrc` to stumble into this error. cc @technoweenie for hints.

**Comment by technoweenie** [comment] 2017-10-03 23:35
Sorry for the hassles. I had a similar experience, and LFS v2.3.2 adds a prefix to the message. Based on that message, it looks like you're missing a keyword. Is your `~/.netrc` correctly formatted, like this?

```
machine lfs.github.com
	login technoweenie
	password MYPASSWORD
machine api.github.com
	login technoweenie
	password MYPASSWORD
```

Also, LFS and GH Desktop don't store your password in this file. But it will read from it, like Git and Curl. If you don't want to use it, just delete it.

**Comment by shiftkey** [comment] 2017-10-03 23:39
@technoweenie thanks, I just encountered https://github.com/git-lfs/git-lfs/pull/2633 which makes this more helpful for the next release. I've asked @BasThomas if this matches up with what he's seeing on his machine.

**Comment by BasThomas** [comment] 2017-10-04 09:03
I’ll check!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shiftkey** [comment] 2017-10-11 07:51
@BasThomas I'm going to close this out as I think we know the root cause - please feel free to comment (either here or over email) if there's anything more to add.

**Closed by shiftkey** 2017-10-11 07:51 UTC
Labels: bug, more-information-needed
