### ISSUE TITLE
'View on Github' on forked repo jumps to the original

### ISSUE THREAD

**Issue by faludiz** [desktop/desktop#15737] opened 2022-12-06 21:16 UTC
### The problem

same as the title: 'View on Github' on forked repo jumps to the original, not to the actual (fork)

### Release version

3.1.2 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

1. fork a repo (work on it)
2. at the rep list (left side of the main window) click right on the repo
3. select `View on Github` command
4. opens the original repo in the browser, not the fork

**Comment by steveward** [comment] 2022-12-06 21:46
Thanks for the issue @faludiz. This is the intended behavior -- see [my comment here ](https://github.com/desktop/desktop/issues/13533#issuecomment-994257079) for why this happens. I'm going to close this out in favor of #13533.

**Closed as completed by steveward** 2022-12-06 21:46 UTC

**Comment by faludiz** [comment] 2022-12-07 06:14
oh... thanks
