### ISSUE TITLE
In Windows command line launcher does not work

### ISSUE THREAD

**Issue by amaajemyfren** [desktop/desktop#9550] opened 2020-04-17 18:29 UTC
### Describe the feature or problem you’d like to solve

I am using Windows 10 but I used to use bash.

I installed the github desktop from [here](https://desktop.github.com/) - the non-msi installer (that is to say [this one](https://central.github.com/deployments/desktop/desktop/latest/win32)).

Github desktop downloaded. I double clicked. It installed. Then I closed it without entering any configuration, authentication details or anything. I just closed it when it looked like this

![image](https://user-images.githubusercontent.com/32741226/79598322-6bf3d300-80ec-11ea-8d48-2f4c2c8da6a6.png)

I am no expert so I went to the [help page](https://help.github.com/en/desktop) to while away some time hoping to learn a thing or two. On [this page](https://help.github.com/en/desktop/getting-started-with-github-desktop/launching-github-desktop-from-the-command-line) I learnt 

![image](https://user-images.githubusercontent.com/32741226/79598546-d9076880-80ec-11ea-9236-ae49e32c7f1b.png)

So later I used windows git and cloned a repository.

I then go to the terminal and from PowerShell I get:

![image](https://user-images.githubusercontent.com/32741226/79600464-dd815080-80ef-11ea-8138-0a4230a8e655.png)

From cmd:

![image](https://user-images.githubusercontent.com/32741226/79600637-25a07300-80f0-11ea-8547-f4d79f546831.png)

It appears that there is no github in the path. I then go look for it in the start menu and there is no reference to github desktop.

### Proposed solution

There are several ways that this could be resolved:
#### Delete the help page about the command line.
This will never lead to the issue being brought up again but it has some challenges as a solution.

1. Currently it is not possible to start github desktop at all once you have closed it so removing the command line help does not assist you in actually using github desktop.
1. The command line tool - to me - appears as a better experience and so just removing any reference to it is not good.

I guess that together with this solution you could put github desktop in the start menu and so we could be able to access it like that in windows. As it is there is actually no way to access github desktop once you have installed it and closed it. (Well I suppose I can google and find where it is installed and then open the file manager to there and run the github.exe command from there - but maybe that is not a very good user experience ... )

#### At installation put `github` in the environmental path.
This is my proposed solution. Currently I can not even start github desktop since it is not in my path or in my start menu. It just appears as an installed application in programs and features. (If I was not too lazy I could google and find where it is installed (it is not in `C:/Program Files/` ) but that appears to be a poor experience)

**Comment by rafeca** [comment] 2020-04-20 13:14
Thanks for the detailed bug report!

I've tried uninstalling my current version of GitHub, making sure that no traces of it are left. Then after re-installing it from the non-msi installer I could see the GitHub app on the Start Menu (I'm using Windows 10).

One thing I noticed is that I had to restart the terminal in order to be able to use the `github` executable from it. Can you try uninstalling it and reinstalling it again to see if it fixes things?

Thanks!

**Comment by amaajemyfren** [comment] 2020-04-22 03:41
I had actually done this once so that I could be able to take the screen shots but I will do it again - incase I did it badly.

1. Go to **Control Panel** > **All Control Panel Items** > **Programs and Features** >

Find github and uninstall it.
![image](https://user-images.githubusercontent.com/32741226/79934218-b3ff5680-845a-11ea-9a03-e1ec17a365f6.png)

Nothing popped up - but it is gone.
![image](https://user-images.githubusercontent.com/32741226/79934422-2cfeae00-845b-11ea-9a90-7cea225620b3.png)

On to next step ... hmm wait you did say:
>making sure that no traces of it are left.

That means I have to find where git desktop is installed ... ok now I **MUST** google.
Ok [this](https://stackoverflow.com/a/46966548/8770431) suggests that I should go to this sort of path
![image](https://user-images.githubusercontent.com/32741226/79935245-18bbb080-845d-11ea-9892-c95a121e5b92.png)

So I went to `C:\Users\■■■■■■\AppData\Local` and found this directory
![image](https://user-images.githubusercontent.com/32741226/79936055-18241980-845f-11ea-933c-4ffb0fd90ca6.png)
Deleted it!
![image](https://user-images.githubusercontent.com/32741226/79936124-443f9a80-845f-11ea-9ac4-52164d437e62.png)
Checked under `LocalLow` and `Roaming` just to be sure and in `Roaming` I found
![image](https://user-images.githubusercontent.com/32741226/79936262-a7c9c800-845f-11ea-85b0-d3a5be48c861.png)
Which had all of these:
<p align="center">
<img src="https://user-images.githubusercontent.com/32741226/79936315-c7f98700-845f-11ea-91e7-2ee087c19c79.png">
</p>

So I deleted that too:
<p align="center">
<img src="https://user-images.githubusercontent.com/32741226/79936680-ba90cc80-8460-11ea-8895-1a2819becd19.png">
</p>

I hope I got everything.

2. Install github desktop again
 a. Download the Setup again
 b. Run it as Administrator - (this image refused to upload)

![image](https://user-images.githubusercontent.com/32741226/79937460-946c2c00-8462-11ea-9da3-60da3f64025b.png)

![image](https://user-images.githubusercontent.com/32741226/79937518-bf568000-8462-11ea-8563-032c13b0a3db.png)
Skipped that step

![image](https://user-images.githubusercontent.com/32741226/79937564-e1500280-8462-11ea-821f-aefdc7f21665.png)
Cancelled that and then closed the window.

Nothing in Recently added:
![image](https://user-images.githubusercontent.com/32741226/79937687-39870480-8463-11ea-80eb-37682f4b0b47.png)

Nothing under G:
![image](https://user-images.githubusercontent.com/32741226/79937725-56233c80-8463-11ea-942f-cb977988c1ae.png)


Started a new `cmd` window:
![image](https://user-images.githubusercontent.com/32741226/79937840-95518d80-8463-11ea-965b-097480bb1e31.png)
And in `powershell`:
![image](https://user-images.githubusercontent.com/32741226/79937972-fda06f00-8463-11ea-8b8b-b4c1f4732e98.png)

Sadly no joy.

**Comment by niik** [comment] 2020-10-20 14:35
> At installation put github in the environmental path.
> This is my proposed solution. Currently I can not even start github desktop since it is not in my path or in my start menu. It just appears as an installed application in programs and features. (If I was not too lazy I could google and find where it is installed (it is not in C:/Program Files/ ) but that appears to be a poor experience)

Hi @amaajemyfren, I'm sorry to hear you're having problems. GitHub Desktop is supposed to add an entry to the `PATH` environment variable at install and I'm not sure why it doesn't do so on your machine. Since this isn't something we're able to reproduce ourselves I'm afraid there's not much we can do here. I'm going to close this issue as it appears to be environment-specific. If you find any piece of information that would help in diagnosing this please let us know and we can reopen this issue.

**Closed by niik** 2020-10-20 14:35 UTC
