### ISSUE TITLE
Keyboard shortcut CTRL+` for open in command promt not worked

### ISSUE THREAD

**Issue by lutz** [desktop/desktop#9179] opened 2020-02-26 16:18 UTC
### Describe the bug

The shortcut for "Open in command promt" seems without a function. All other shortcuts worked well. The menuitem itself works also.

![image](https://user-images.githubusercontent.com/26437097/75364082-68e22080-58bb-11ea-9727-2b9fd34ae4ce.png)

### Version & OS

- Windows 10
- GitHub Desktop **2.3.1**

### Expected behavior

The command prompt open after using the keyboard shortcut.

### Actual behavior

Nothing happen

**Comment by steveward** [comment] 2020-02-26 16:31
Thanks for the report @lutz. I just tested this out and was unable to reproduce this issue using CMD as my default shell. Could you try changing to a different default shell like PowerShell to see if you can reproduce this error? Going `File` > `Options` > `Integrations` will allow you to change the shell.

**Comment by lutz** [comment] 2020-02-26 16:51
@steveward I tested it with all existed integrations (git bash, powershell) the behaviour is the same. The MenuItem Click works but not the shortcut.

**Comment by tierninho** [comment] 2020-02-26 17:35
@lutz I was unable to reproduce either. Can you confirm you can type the (`) key to make sure it's working on your keyboard. Also, do you have any settings in Windows that might override the (`) key, or do you have a different language keyboard that might alter the layout of keys?

Try this if you are on a german keyboard:
![Screen Shot 2020-02-26 at 7 33 59 AM](https://user-images.githubusercontent.com/14828183/75371230-78854900-586a-11ea-982b-1378ddadc5cf.png)

**Comment by lutz** [comment] 2020-02-26 19:34
@tierninho Thanks for the image. Of course i use a german keyboard and also use the right keys. In the simple notepad app the keys works also right. So i have no idea whay the shortcut not work. In this case the combination of <kbd>CTRL</kbd>+<kbd>`</kbd> is not the best choice.

**Comment by tierninho** [comment] 2020-02-26 20:26
>  In this case the combination of CTRL+` is not the best choice.

I tend to agree 👍 

I tested this workaround on a German keyboard on Windows... for whatever reason this works:

<kbd>CTRL</kbd>+<kbd>ö</kbd>

I simply just clicked every key on the keyboard 🤣

**Comment by lutz** [comment] 2020-02-27 07:27
<kbd>CTRL</kbd>+<kbd>ö</kbd> works correct. 

> I simply just clicked every key on the keyboard 🤣

Thank you for your time to test it 🤣. So in this case maybe i will be a good idea to change the current shortcut <kbd>CTRL</kbd>+<kbd>`</kbd> to a better choice like <kbd>CTRL</kbd>+<kbd>L</kbd> So then this issue should be a feature change.

**Comment by tierninho** [comment] 2020-02-27 19:40
Thanks for the confirmation. Our apologies for the confusion as this situation was not ideal. 

Going to close this for now.

**Closed** 2020-02-28 18:10 UTC
Labels: more-info-needed

**Comment by Wolfsblvt** [comment] 2020-03-12 15:31
Is it possible to just change the displayed shortcut for people using QWERTZ keyboards?  
`CTRL`+`ö` works, so it would help european developers to just see the right shortcut.  
No binding change needed, just da display one.

I mean the workaround works, but I am pretty sure there are hundreds and hundreds of people who don't use a shortcut here because they think they can't.

**Comment by cbusse1** [comment] 2022-02-11 12:49
> > In this case the combination of CTRL+` is not the best choice.
> 
> I tend to agree 👍
> 
> I tested this workaround on a German keyboard on Windows... for whatever reason this works:
> 
> CTRL+ö
> 
> I simply just clicked every key on the keyboard 🤣
> 
> ref: https://talk.dynalist.io/t/problematic-keyboard-shortcuts-on-german-keyboard-layout/1176

Thanks man! :D
