### ISSUE TITLE
Support WebAuthn authentication

### ISSUE THREAD

**Issue by paulschreiber** [desktop/desktop#8870] opened 2020-01-06 20:47 UTC
### Describe the feature or problem you’d like to solve

Please add WebAuthn support to GitHub Desktop. (Previously: #1111). This should be doable now that Electron has WebAuthn support.

**Comment by niik** [comment] 2020-01-07 13:17
Hey @paulschreiber, could you provide a bit more context for us here, we'd much appreciate if you could describe the scenario. When are you encountering the need for GitHub Desktop to support WebAuthn?

Is this only a problem when you're signing in with username/password, are you able to use the web flow authentication (by clicking on the "Sign in with your browser" link) as a workaround?

<img width="410" alt="image" src="https://user-images.githubusercontent.com/634063/71897921-43a52180-3158-11ea-866f-07c8aef550c4.png">

**Comment by paulschreiber** [comment] 2020-01-09 04:43
We didn't see the "sign in with your browser" option after launching the app and eventually got to this screen:
![image](https://user-images.githubusercontent.com/86784/72038810-b86b7f00-3270-11ea-983b-c04e20e5b8b3.png)

**Comment by niik** [comment] 2020-01-09 08:46
Hi @paulschreiber, thanks for getting back to us so quickly!

Were you able to try signing in with the web flow, and did that solve your issue? I understand that it's a bit tricky to locate and that's been by design up until now but it will be changing. Regardless if you've just launched the app or if you're signing in through the preferences dialog you should see the link just underneath the Sign in button.

<img width="725" alt="image" src="https://user-images.githubusercontent.com/634063/72052147-dd89dd00-32c4-11ea-8eb9-15066978c031.png">

I ask because the username and password authentication flow [has been deprecated](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/) and as such we will gradually be transitioning to using the web flow as the primary authentication flow.

With that in mind it's unlikely that we'll spend any time trying to add WebAuthn into a flow that won't be supported going forward.

If I understand your issue correctly then performing the sign in flow in a browser would allow you to use your hardware tokens.

**Comment by tierninho** [comment] 2020-01-14 01:34
@paulschreiber As we have not heard back from you on this issue, we are closing it for now. Should you have any more details or questions, please reach out and we will be happy to help. Thank you.

**Closed by tierninho** 2020-01-14 01:34 UTC
Labels: electron, enhancement, more-info-needed

**Comment by paulschreiber** [comment] 2020-01-14 03:29
@tierninho The confusion stems from the fact there there are two different auth flows: in-app and in-browser. If you start with the in-app flow, you can't use security keys. I didn't notice the "sign in using your browser" link (it has less visual weight, and is further from the form). It's great to hear you are getting rid of the in-app flow. Please do so expeditiously.
