### ISSUE TITLE
Fatal Error Message When Attempting to Fetch/Pull From Remote Origin

### ISSUE THREAD

**Issue by spnanon** [desktop/desktop#12743] opened 2021-08-09 07:16 UTC
### Describe the bug
GitHub Desktop fails to fetch and pull files from remote origin to local repository when the "Fetch origin" option is selected.  Gives the message:

``fatal: unable to access 'https://gitgud.io/<user>/<name>/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log."``

### Version & OS

Version 2.9.0, 64-bit

Windows 7, 64-bit

### Steps to reproduce the behavior

1. Select repository and branch
2. Click on "Fetch origin" (also fails if attempting to pull files after they are fetched via other means)
3. See error message

### Expected behavior

GitHub Desktop would fetch files from origin and pull, updating the local repository on computer.

### Actual behavior

Popup with the error message:

``fatal: unable to access 'https://gitgud.io/<user>/<name>/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.``

### Screenshots

Can provide if necessary, but would just be an image of the error message, mostly.

### Logs

Can provide if necessary, but log file just seems to read out the same error message.

### Additional context

Fetching/pulling worked after setting http.schannelCheckRevoke to false in Git Bash, then fetching and pulling in Git GUI/Bash.  This is what led me to believe it is a problem specific to GitHub Desktop.

Remote repository in question is located in GitLab/GitGud (I'm not familiar with the separation between them and GitHub, if any).  GitHub Desktop fetched/pulled from this repository for several years without issue.

**Comment by steveward** [comment] 2021-08-09 20:28
Thanks for the issue @spnanon. Usually setting http.schannelcheckrevoke resolves this, and if it's working in the command line it should also work in GitHub Desktop. Can you verify you set this to your global `.gitconfig` by running `git config --global --list`?

**Comment by Arndress** [comment] 2021-08-10 16:29
Just chiming in to say that I'm experiencing an identical issue to @spnanon with no other changes on my end.

I am able to push and pull via the command line, but I have the same error in the Desktop Client. I haven't made the suggested adjustments, but I'm also not sure why the sudden change.

Is there any chance this is connected to the degraded performance mentioned on the GitHub Status twitter account?

**Comment by steveward** [comment] 2021-08-10 17:19
@Arndress The site availability issue was likely the cause of it. Git operations should be back to normal now, but let me know if you are still encountering problems.

**Comment by spnanon** [comment] 2021-08-12 01:42
@steveward Yes, it lists it as false.  I'm still getting the same error message.

**Comment by steveward** [comment] 2021-08-12 21:14
@spnanon what does `git config http.sslBackend` return on your machine?

**Comment by spnanon** [comment] 2021-08-14 03:23
@steveward ``openssl``

**Comment by Arndress** [comment] 2021-08-26 15:19
This issue was resolved for me as of about 24 hours ago.

I made no changes to my system or settings. However, I am now automatically updated to GitHub Desktop 2.9.2, and it's possible that changes in version 2.9.1 a few days ago were the cause for this problem being rectified.

**Comment by spnanon** [comment] 2021-08-27 04:37
It's fixed for me, now, too.  I made no changes, either.

**Comment by steveward** [comment] 2021-08-30 16:23
Glad to hear this was resolved! I'm going to close this out.

**Closed as completed by steveward** 2021-08-30 16:23 UTC

**Comment by nicogodet** [comment] 2024-03-11 12:09
Hi, 

I have the same issue. Setting `http.schannelCheckRevoke=false` does not help.

Github Desktop log
```
2024-03-11T11:04:08.880Z - info: [main] Using toast activator CLSID {27D44D0C-A542-5B90-BCDB-AC3126048BA2}
2024-03-11T11:04:09.597Z - info: [ui] [AppStore] loading 39 repositories from store
2024-03-11T11:04:09.598Z - info: [ui] [AppStore] found account: nicogodet (Nicolas Godet)
2024-03-11T11:04:10.212Z - info: [ui] Subscribed 'nicogodet' to Alive channel
2024-03-11T11:04:10.235Z - info: [ui] launching: 3.3.11 (Windows 10.0.19045)
2024-03-11T11:04:10.236Z - info: [ui] execPath: 'C:\Users\godet\AppData\Local\GitHubDesktop\app-3.3.11\GitHubDesktop.exe'
2024-03-11T11:04:17.527Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 1.192s)
2024-03-11T11:04:17.820Z - error: [ui] `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://gitlab.nicodet.fr/isl/isl_box.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More detail may be available in the Windows System event log.

2024-03-11T11:04:29.282Z - info: [ui] Executing getCommits: git log 8fb3352348d810aea73f16e77d807acd2f8a8b3f --date=raw --max-count=1 -z --format=%H%x00%h%x00%s%x00%b%x00%an <%ae> %ad%x00%cn <%ce> %cd%x00%P%x00%(trailers:unfold,only)%x00%D --no-show-signature --no-color -- (took 1.104s)
```

Running `git -c credential.helper= fetch --progress --prune --recurse-submodules=on-demand origin` from git Bash works fine.

**Comment by nicogodet** [comment] 2024-03-11 13:22
Solved : recent changes on host restricts tls version to 1.3 only which seems to break gitlab desktop
Allowing 1.2 fix issue
