### ISSUE TITLE
Check for existing README prior to creation

### ISSUE THREAD

**Issue by joshhopkins** [desktop/desktop#6294] opened 2018-11-27 05:41 UTC
When adding an existing local project, choosing to create a new repository, the UI displays an option to `Initialise this repository with a README`.

This option was selected by default and in a tired state I selected 'create'. This completely wiped the README.MD file I had spent an hour writing and there doesn't seem to be a way of recovering this.

**Potential solution**

Check for existing README.MD file and prompt user if one exists.

**Comment by msftrncs** [comment] 2018-11-27 21:38
@iAmWillShepherd, I know it is common for me to create a folder, and start creating files, before I know I am going to turn it into a GIT repository, so when I do decide to use GIT, I need to create the repository from the files I already have, sometimes including a README.MD.  Maybe its a bad practice, but its the work flow I use over and over again.  I have definitely made the same mistake as @joshhopkins , but fortunately for me, I still had the file open in VS Code in an unsaved state, which then caused the message 'file on disk has changed' in VS Code.

**Comment by joshhopkins** [comment] 2018-11-28 04:56
@iAmWillShepherd I should clarify, in this case no repo previously existed, as @msftrncs pointed out. It may be an edge case, but there are times where creating a repo before writing the first line of code seems overkill. Often the README.MD file starts off as a scratch pad for me, and a repo is created at the point where some value is achieved. As a user, I would expect a good Git client to throw a warning before overwriting pre-existing files.

**Comment by billygriffin** [comment] 2018-11-28 15:31
Thanks @msftrncs and @joshhopkins for describing the workflow here. I'm wondering if it's something similar to the warning on this image, but instead it's a warning below the README checkbox and says something like: "It looks like you already have a README.md file in this folder. Checking this box will overwrite your existing README.md file with an empty one."

<img width="415" alt="screen shot 2018-11-28 at 8 24 50 am" src="https://user-images.githubusercontent.com/5091167/49161935-19432c80-f2e7-11e8-95f6-58b93b631860.png">

I don't know what detection of that file looks like from a technical perspective, but if it's fairly lightweight, it seems reasonable that we could support a warning like that. Thoughts? Either of you have interest in looking into how the app might detect whether someone has a pre-existing README?

**Comment by Daniel-McCarthy** [comment] 2018-11-28 16:03
@billygriffin It should be possible to use `fse` to call a `readDir` on the user's given local path, which will return a list of the file names in the folder (if any). From there, it would be possible to check for one named "ReadMe.md". There's also `fse.pathExists` as well for a specific file name.

A Git `rev-parse` command is actively being used to detect whether or not the given local path is a git repository, so there is an existing precedent for running checks on the path in order to display a warning. So as long as it doesn't pose much of a performance difference for users it should be practical.

**Comment by billygriffin** [comment] 2018-11-28 17:44
Thanks @Daniel-McCarthy! Would someone from @desktop/engineering mind weighing in on practicality of this as well and any potential drawbacks? It seems reasonable as something to prevent folks from getting into a tough spot like @joshhopkins and @msftrncs explained above, and I'd be inclined to make it `help-wanted`.

**Comment by outofambit** [comment] 2018-11-28 18:04
@billygriffin i'm in favor of the approach outlined by @Daniel-McCarthy. i think it should be fine from a performance standpoint. we probably want to use `readDir` and check for a number of possible readme names (`README`, `readme`, `readme.md`, etc.).

**Comment by Daniel-McCarthy** [comment] 2018-11-28 18:16
@outofambit Great! In regards to checking for multiple possible names, regular expressions would be a great way to check for a match regardless of the capitalization combinations, as well as with/without the inclusion of the `.md` extension

Otherwise, if we didn't want to use regular expressions for this, setting the string we are checking `.toLowerCase()` could limit the need to check for lots of variations and leave it to only `readme.md` and `readme`.

**Comment by Daniel-McCarthy** [comment] 2018-12-01 00:55
I have looked into this a bit. I have given a try at implementing it. This is what I had imagined the UI of it would look like:
![image](https://user-images.githubusercontent.com/4957200/49321380-ad221d80-f4cc-11e8-8e97-3207386283db.png)


It only appears when the user has the checkbox set to create a `ReadMe.md` on repository creation.
___

@outofambit We had discussed the detecting a file with the name `ReadMe.md` for all permutations of capitalization, as well as with and without the .md extension.

However, it dawned on me that if there is a `ReadMe` with no .md extension in the folder, it will not be overwritten on the creation of the repository. Instead they will have both `ReadMe` and `README.md` in their directory.

I tested what happens if a directory has both a  `ReadMe` file and a `README.md` and GitHub.com had a display preference for the `.md` file over the file without the extension. So it seems to be that the warning would only make sense for files that have the extension unless we want to do some additional behavior in that case.

**Comment by msftrncs** [comment] 2018-12-03 00:36
Just my opinion on the matter:

The real thing us users would like to see, is to not have our work destroyed (even if it is ultimately by our carelessness), so I would like to suggest that GitHub Desktop adopt a strategy to try to cause no harmful affects.  I would think it would be better to just not allow overwriting existing files (readme.md, .gitignore, .gitattributes, etc...) on creation of a repository, or even cloning a remote repository to a local folder.  This way GitHub Desktop cannot be accused of destroying work.  Instead, require the user to do that destructive action with his own means (ie, in Explorer/Finder or a shell).

Its very easy for a user to dismiss important warning dialogs, when we're used to getting them all day long.  Better yet, would be to require the user to reset his focus, by providing a dialog that requires interaction.  For instance, the 'Cancel' button should be default, and should start with the focus, and another checkbox should require being checked before an 'Overwrite' button can be pressed.

**Comment by Daniel-McCarthy** [comment] 2018-12-03 03:07
@msftrncs This is a great point. 

I have the a branch ready with the previously suggested changes ready for a pull request. I think the warning should be added at a bare minimum since currently the user is not notified whatsoever.

However, if we want to rethink the solution for this I would love to hear what the team thinks on this. If we wanted a confirm/decline dialog we could also have a setting to disable to the dialog (with the default being the dialog enabled, ideally).

Otherwise, if a `ReadMe.md` file already exists, does the user really have any benefit to initializing the repository with a new ReadMe? It would be fresh and blank, but it does not seem like a substantial convenience. We could disable the check box if a ReadMe is detected and have a message explaining why so as to avoid confusion.

**Comment by billygriffin** [comment] 2018-12-03 16:43
> Otherwise, if a ReadMe.md file already exists, does the user really have any benefit to initializing the repository with a new ReadMe? It would be fresh and blank, but it does not seem like a substantial convenience. We could disable the check box if a ReadMe is detected and have a message explaining why so as to avoid confusion.

+1 on this, excellent point. Let's do it.

> The real thing us users would like to see, is to not have our work destroyed (even if it is ultimately by our carelessness), so I would like to suggest that GitHub Desktop adopt a strategy to try to cause no harmful effects. I would think it would be better to just not allow overwriting existing files (readme.md, .gitignore, .gitattributes, etc...) on creation of a repository, or even when cloning a remote repository to a local folder. This way GitHub Desktop cannot be accused of destroying work. Instead, require the user to do that destructive action with his own means (ie, in Explorer/Finder or a shell).

@msftrncs Would you mind mapping out the flows specifically on how you think this might work? I'd like to separate the larger piece from what we're going to ship first as @Daniel-McCarthy suggested, and it'd be helpful to more explicitly map out the things we need to account for.

**Comment by Daniel-McCarthy** [comment] 2018-12-03 20:58
@billygriffin To clarify, you would like to skip the original warning idea and instead press forward with the disabling the check box when the file already exists?

If so, I can start looking into that and re-purpose my existing branch.

**Comment by billygriffin** [comment] 2018-12-03 22:46
@Daniel-McCarthy Assuming you were suggesting that as a better option than the original idea (in my opinion it is, but open to feedback), it makes sense to me. However, given that it's a lot worse if the detection has false positives (because we're not even getting people the option), if it's significantly more work for you to change the work you've done so far, I think maybe your time would be better spent elsewhere tbh. So I'll defer to your judgment.

**Comment by billygriffin** [comment] 2018-12-03 23:58
> Perhaps we could start with the warning and see how it performs. We could then update it later if it is proving reliable.

@Daniel-McCarthy I'm 👍 on this. Sorry for the churn.

**Comment by j-f1** [comment] 2018-12-04 00:10
How about only disabling the checkbox if a file already exists with the exact same name as the README that will be created? By using the `exists` method, the app will be able to properly handle both case-sensitive and case-insensitive file systems.

**Comment by Daniel-McCarthy** [comment] 2018-12-04 00:33
@j-f1 That is a good point. That would be ideal since Linux allows for both `readme.md` and `ReadMe.md` and other variations in the same folder. It would also simplify the implementation a bit as well. Thanks for the suggestion, I will try that out.

**Comment by tierninho** [comment] 2018-12-06 18:59
👋 Can someone in this thread clarify the reproduction steps for this issue? Thank you in advance.

**Comment by Daniel-McCarthy** [comment] 2018-12-06 19:53
@tierninho Certainly!
- Create a new folder in your default clone directory, lets say `.. /Documents/GitHub/Test`
- Create a `README.md` file, in the new `Test` folder. Ideally, put some identifiable text in the ReadMe file so that you know if it has been overwritten or not.
- Switch to GitHub Desktop. `File->New repository...`, then type `Test` as the name for the new repository (or whatever has been selected as the name).
- Enable `Initialize this repository with a README`
- Click `Create repository`

When you create it, the repository will be made in your folder. You should have a `README.md` file in the test folder, however, the contents should now be `# Test` instead of what was originally written.

**Comment by iAmWillShepherd** [comment] 2019-06-01 12:13
Fixed in https://github.com/desktop/desktop/pull/6338

**Closed by iAmWillShepherd** 2019-06-01 12:13 UTC
Labels: enhancement, help wanted
