### ISSUE TITLE
pre-commit hook not running to remove BOM from file

### ISSUE THREAD

**Issue by BoGnY** [desktop/desktop#5040] opened 2018-06-26 17:33 UTC
## Description
Github desktop not hook pre-commit hook..

## Version
* GitHub Desktop: 1.2.6
* Operating system: Win10 PRO 10.0.16299.492

## Steps to Reproduce
I have this pre-commit hook file:
```sh
#!/bin/sh
#
# A hook script to remove BOM headers

echo "Running pre-commit BOM headers removal"

git diff --cached --diff-filter=ACMR --name-only -z | xargs -0 -n 1 sh -c '
    for FILE; do
        file --brief --mime-type "$FILE" | grep -q text
        if [ $? -eq 0 ]; then
            FILE_TEMP="$(mktemp)"
            cp "$FILE" "$FILE_TEMP"
            git checkout -- "$FILE"
            sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE"
            NEEDSADD=`git diff --diff-filter=ACMR --name-only | wc -l`
            if [ $NEEDSADD -ne 0 ]; then
                sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE_TEMP"
                echo "Removed UTF-8 BOM from $FILE"
                git add "$FILE"
            fi
            cp "$FILE_TEMP" "$FILE"
            rm "$FILE_TEMP"
        fi
    done
' sh

ANYCHANGES=`git diff --cached --name-only | wc -l`
if [ $ANYCHANGES -eq 0 ]; then
    git commit --no-verify
    exit 1
fi
```
I select files to commit, I write commit message and I press "Commit to master", files added to the generated commit have UFT-8 BOM characters.. Nothing happens..

But if I launch commands from git shell:
```sh
$ git add .
$ git commit -m "my commit"
Running pre-commit BOM headers removal
Removed UTF-8 BOM from myfile.md
[master f49bcd9] my commit
 1 file changed, 1 insertion(+)
 create mode 100644 myfile.md
```
pre-commit hook succesfully work!

### Expected Behavior
Automatic deletion of UTF-8 byte order mark header

### Actual Behavior
Nothing happens

## Additional Information
None

### Logs
[2018-06-26.desktop.production.log](https://github.com/desktop/desktop/files/2138252/2018-06-26.desktop.production.log)

**Comment by shiftkey** [comment] 2018-06-26 17:56
@BoGnY thanks for the log:

```
2018-06-26T16:57:08.926Z - info: [ui] Executing createCommit: git commit -F - (took 1.293s)
```

I don't see any error when this commit happens - generally Git should either make noise and return with a non-zero exit code, or it should complete and add a new commit to the current branch. Any clues as to what Desktop did here?

**Comment by BoGnY** [comment] 2018-06-26 18:21
@shiftkey Desktop has create the commit and is waiting for the push... No errors happens..

Sorry, I haven't write a required step.. the file committed, MUST have utf-8 bom header..
Create a test file with bom header (I use Notepad++)..
On Desktop you have to see a 'red dot' as first chars, this is the bom header..

**Comment by shiftkey** [comment] 2018-06-27 13:32
@BoGnY thanks for the details!

I ran this up locally and found that when we were committing in Desktop we were getting this message to `stderr`:

```
Running pre-commit BOM headers removal
file: could not find any valid magic files! (No such file or directory)
```

Tweaking the script a bit to get more context:

```sh
#!/bin/sh
#
# A hook script to remove BOM headers

echo "Running pre-commit BOM headers removal"
echo "From directory $(pwd)"
echo "Using file at: $(where file)"

git diff --cached --diff-filter=ACMR --name-only -z | xargs -0 -n 1 sh -c '
    for FILE; do
	echo "using file $FILE"
        file --brief --mime-type "$FILE" | grep -q text
...
```

This is how it works from the command line:

```
Running pre-commit BOM headers removal
From directory /c/Users/shiftkey/Documents/GitHub/testing-bom-with-commit-hook
Using file at: C:\Program Files\Git\usr\bin\file.exe
using file README.md
Removed UTF-8 BOM from README.md
```

And this is the stderr output from Desktop committing:

```
Running pre-commit BOM headers removal
From directory /c/Users/shiftkey/Documents/GitHub/testing-bom-with-commit-hook
Using file at: C:\Program Files\Git\usr\bin\file.exe
using file README.md
file: could not find any valid magic files! (No such file or directory)
```

So I'm not sure how these two environments are different - same `file` program, same file path, different result. Thoughts?

**Comment by BoGnY** [comment] 2018-06-27 15:00
Hi!
Maybe I have found the problem...

Using `file --help`, I found:
`-m, --magic-file LIST - use LIST as a colon-separated list of magic number files`

So I search "magic" inside git dirs, I have found this file "C:\Program Files\Git\usr\share\misc\magic.mgc", I investigate on magic file: https://linux.die.net/man/5/magic

I have opened git bash on root dir project, and the command `file --brief --mime-type`**`-m magic.mgc`**` mybomfile.md | grep -q text` returns the fatal:
`file: could not find any valid magic files! (No such file or directory)`

IMHO, Desktop add option **-m** to identify file type, but utf-8 bom change headers file, this prevents 'file' command from finding a match, and therefore the error is returned even if the environment is the same...

I'm investigating deeper into the Desktop code 👍

**Comment by shiftkey** [comment] 2018-06-28 11:44
@BoGnY I was able to get the script working from Desktop by providing the full path to the .mgc file:

```sh
#!/bin/sh
#
# A hook script to remove BOM headers

echo "Running pre-commit BOM headers removal"

git diff --cached --diff-filter=ACMR --name-only -z | xargs -0 -n 1 sh -c '
    for FILE; do
        file --brief --mime-type -m "C:\Program Files\Git\usr\share\misc\magic.mgc" "$FILE" | grep -q text
        if [ $? -eq 0 ]; then
            FILE_TEMP="$(mktemp)"
            cp "$FILE" "$FILE_TEMP"
            git checkout -- "$FILE"
            sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE"
            NEEDSADD=`git diff --diff-filter=ACMR --name-only | wc -l`
            if [ $NEEDSADD -ne 0 ]; then
                sed -b -i -e "1s/^\xEF\xBB\xBF//" "$FILE_TEMP"
                echo "Removed UTF-8 BOM from $FILE"
                git add "$FILE"
            fi
            cp "$FILE_TEMP" "$FILE"
            rm "$FILE_TEMP"
        fi
    done
' sh

ANYCHANGES=`git diff --cached --name-only | wc -l`
if [ $ANYCHANGES -eq 0 ]; then
    git commit --no-verify
    exit 1
fi
```

I had a look at the embedded Git installation inside Desktop (which comes from Git for Windows) and we don't have a corresponding `usr/share/misc/magic.mgc` entry. This might be possible to incorporate into a future update, depending on how crucial it is for `file`.

**Comment by BoGnY** [comment] 2018-06-28 14:46
@shiftkey this is the problem!!

> I had a look at the embedded Git installation inside Desktop (which comes from Git for Windows) and we don't have a corresponding `usr/share/misc/magic.mgc` entry. This might be possible to incorporate into a future update, depending on how crucial it is for `file`.

I didn't think that Desktop used a embedded version of Git for Windows...
However, even adding `-m "C:\Program Files\Git\usr\share\misc\magic.mgc"` (I have even tried `-m "/c/Program Files/Git/usr/share/misc/magic.mgc"`) to script, Desktop not remove bom header..

Regarding the magic file, I think that `usr/share/misc/magic.mgc` file is crucial and should be inserted, since, as shown in the `file` documentation, which I previously linked to you, is a necessary file for **`-m`** option to work properly..

**Comment by shiftkey** [comment] 2018-06-28 15:33
> I didn't think that Desktop used a embedded version of Git for Windows...

It's called MinGit and more details about the motivations for it are outlined here: https://blogs.msdn.microsoft.com/devops/2016/09/03/whats-new-in-git-for-windows-2-10/

> However, even adding -m "C:\Program Files\Git\usr\share\misc\magic.mgc" (I have even tried -m "/c/Program Files/Git/usr/share/misc/magic.mgc") to script, my Desktop not remove bom header..

Unless you are running 32-bit Git for Windows, which is installed at a different path, I'm not sure how else our environments differ.

> Regarding the magic file, I think that usr/share/misc/magic.mgc file is crucial and should be inserted, since, as shown in the file documentation, which I previously linked to you, is a necessary file for -m option to work properly..

This is something to be discussed upstream, because this environment is supposed to be minimal (enough to run Git) and plenty of tools from the full Git for Windows installation have been removed.

**Comment by BoGnY** [comment] 2018-06-28 19:08
> Unless you are running 32-bit Git for Windows, which is installed at a different path, I'm not sure how else our environments differ.

No, I'm running 64-bit version, and path is correct..
I'm going crazy..

> > Regarding the magic file, I think that usr/share/misc/magic.mgc file is crucial and should be inserted, since, as shown in the file documentation, which I previously linked to you, is a necessary file for -m option to work properly..
> 
> This is something to be discussed upstream, because this environment is supposed to be minimal (enough to run Git) and plenty of tools from the full Git for Windows installation have been removed.
I understand the usefulness of having an embedded version of git with reduced size but, imho, since the application `file` is among those included, I would consider it as appropriated so this tool works correctly.. I do not think it is a strange file and not connected to any tool, but its presence is necessary for the operation of an included tool..

Obviously this is only my opinion.

The fact remains that Desktop adds the `-m` parameter even if it is not present in the shell script...

**Comment by shiftkey** [comment] 2018-06-29 11:36
> But it makes me do another reasoning: in the settings, you could make the user choose whether to use a light embedded version of git, or, if it is installed, to use the full version of Git for Windows?????

This has been asked before. See my earlier answer and context here about why we don't support an existing Git installation: https://github.com/desktop/desktop/issues/3435#issuecomment-347388985

> I understand the usefulness of having an embedded version of git with reduced size but, imho, since the application `file` is among those included

`file.exe` isn't included in `MinGit` - running the script from either the command line or Desktop shows that it uses the version in `C:\Program Files\Git\usr\bin\`. I checked the latest version of MinGit and it too doesn't contain `file.exe`. So we need to figure out how these two environments differ.

> The fact remains that Desktop adds the `-m` parameter even if it is not present in the shell script...

You haven't told me which version of Git for Windows you have installed, as that might be important here to reproducing the behaviour.

I went and tested the latest version of Git for Windows (2.18.0) and `file.exe` will block the commit step inside Desktop (I see `file.exe` chewing on one core, while Desktop shows the progress spinner, and I need to kill the process to complete the commit). Again, trying to figure out how your environment and mine differ - more details about your other Git setup would be great!

**Comment by shiftkey** [comment] 2018-06-29 11:46
Oops, I must have forgotten to refresh the tab and catch this clue:

>**UPDATE**: But after another 3 hours I discovered the problem... The embedded version of git doesn't have the `file` tool... So the `file` command returns an error!!!
> > `error on line 2: sh: file: command not found`

If you're running scripts from Git Bash or Git CMD, those environments will add the paths to `/usr/bin` to your PATH so these tools. That might be the difference here between the CLI and Desktop, and your setup and mine:

<img width="604" src="https://user-images.githubusercontent.com/359239/42090693-c60c622e-7b78-11e8-812e-990568f2c130.png">

Try explicitly adding `C:\Program Files\Git\usr\bin\` to your PATH in Windows.

**Comment by BoGnY** [comment] 2018-07-02 15:30
> Try explicitly adding `C:\Program Files\Git\usr\bin\` to your PATH in Windows.

It doesn't work.. I have tried with Git for Windows 2.16.1 and 2.18.0..
Desktop start an infinite loop on `file` command and never execute it... I have waited more that 1 hours..

The only thing that I have tried and have worked is creating an hard link from embedded git to Git for Windows, using cmd:
`mklink /J "C:\Users\LucaHP\AppData\Local\GitHubDesktop\app-1.2.6\resources\app\git" "C:\Program Files\Git"`

I have to relaunch it on every Desktop update, but all works correctly, even Git Credential Manager, GPG daemon to sign commit and other my git tool! 👍

**Comment by shiftkey** [comment] 2018-07-02 18:03
@BoGnY I'm glad you were able to workaround the issue!

I'm going to close this out as `file.exe` is not currently supported in the embedded Git that Desktop uses, and adding support for tools like this should be opened against https://github.com/desktop/dugite-native as that's the source of the embedded Git we ship in Desktop.

**Closed by shiftkey** 2018-07-02 18:03 UTC
Labels: more-information-needed
