### ISSUE TITLE
Issue with UP arrow key in History tab

### ISSUE THREAD

**Issue by daniel-rodrigue** [desktop/desktop#3093] opened 2017-10-18 15:15 UTC
### Description

In the History tab side panel, pressing the UP arrow key on first entry, move the currently selected entry to the last one in the history, also causing as a side effect, to load more history changes. This is very annoying when reviewing what were the latest changes after fetching the origin since you would expect the selection to stay at the top when you're done. 

### Version

**GitHub Desktop version:** 1.0.4

**OS version:** macOS 10.12.6

### Steps to Reproduce

1. Click the History tab
1. Select the first row
1. Press the UP arrow key
1. Problem: Notice that the selection is now at the bottom of the current loaded history. More history entries can be loaded as well.

**Expected behavior:** The selection should stay on first row.

**Actual behavior:** The selection goes down to the bottom of the loaded history.

**Reproduces how often:** All the time.

**Comment by j-f1** [comment] 2017-10-18 15:18
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2479. Please follow that issue for further updates.

**Comment by iAmWillShepherd** [comment] 2017-10-18 15:22
@daniel-rodrigue closing this issue since it's a duplicate. I've gone ahead and re-opened issue #2479 and applied the bug label.

**Closed by iAmWillShepherd** 2017-10-18 15:22 UTC
