### ISSUE TITLE
Add option to disable auto update of the app

### ISSUE THREAD

**Issue by Nikronic** [desktop/desktop#5465] opened 2018-08-24 18:28 UTC
Hello
I have <strong>data plan</strong> so I should take care of my data usage. So because Github Desktop app is in development, there is updates weekly or less.
Please <strong>add option to disable auto update</strong> so we can update app in free usage time. 

Best regards

**Comment by j-f1** [comment] 2018-08-24 20:11
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1128. Please follow that issue for further updates. (cc @shiftkey since you last touched that issue)

**Comment by billygriffin** [comment] 2018-08-24 22:08
@Nikronic To clarify, are you talking about background processes that happen within the app, or auto-updates of the app itself (like version 1.3.3 to 1.3.4)?

**Comment by Nikronic** [comment] 2018-08-24 22:08
No my issue not related to #1128 at all. I am talking about updating the Github Desktop app itself. (Downloading about 90mb)

**Comment by j-f1** [comment] 2018-08-24 22:34
Oops 😬

I knew what you were talking about, meant to search for it, and got the wrong issue. The right one is #3410.

**Comment by billygriffin** [comment] 2018-08-25 00:42
Thanks @j-f1 and @Nikronic! I'm going to close this in favor of #3410, so please follow along there. I don't anticipate progress on this in the very near term due to limited resources, but we're evaluating our product-related communication here (https://github.com/desktop/desktop/issues/5398) and hopefully that will bring more clarity to things like this. Thanks again.

**Closed by billygriffin** 2018-08-25 00:42 UTC

**Comment by DannyCarlton** [comment] 2024-01-23 20:01
This is over 5 years later, but I needed to stop updates because my main working computer is still using Win8.2. I finally found a solution.

I downloaded version 3.2.1 (the last compatible with Win8.2,) and for a while I would install it, update my repos, then uninstall it. (BTW, you can search for it, there are several download sites)

Finally, though, I located the executable (once installed) and deleted the "update.exe" in the main folder. (Since I kept the installation, I could always replace it if needed) 

I also deleted the app version folder for any past 3.2.1 

The installation (3.2.1) continued to work, but would not update.

I hope this helps anyone wandering here with the same problem I had.
