### ISSUE TITLE
Application startup: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ariffjeff** [desktop/desktop#11446] opened 2021-01-23 03:33 UTC
### Describe the bug
I received an error popup the moment Github Desktop started up. It did not crash, I just OK-ed out of the error message and everything continued to work fine. I do not know what could have caused this to happen.

![startupError](https://user-images.githubusercontent.com/42873506/105567378-6e303100-5cff-11eb-8f08-24657862bb32.png)

**Error from the log file which contains the dialog message and a little extra before info:**
```
2021-01-23T01:42:04.814Z - info: [ui] [AppStore] loading 7 repositories from store
2021-01-23T01:42:04.815Z - info: [ui] [AppStore] found account: ariffjeff (ariffjeff)
2021-01-23T01:42:04.815Z - info: [ui] [AppStore] found account: arj14008 (Ariff Jeff)
2021-01-23T01:42:05.080Z - info: [ui] launching: 2.6.2 (Windows 10.0.19041)
2021-01-23T01:42:05.080Z - info: [ui] execPath: 'C:\Users\ariff\AppData\Local\GitHubDesktop\app-2.6.2\GitHubDesktop.exe'
2021-01-23T01:42:05.165Z - error: [ui] `git lfs install --skip-repo` exited with an unexpected code: 2.
stderr:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1 pc=0x786287]

goroutine 1 [running]:
golang.org/x/text/unicode/bidi.Lookup(0xc0001c5d64, 0x1, 0x4, 0xb, 0x1)
	go/pkg/mod/golang.org/x/text@v0.3.0/unicode/bidi/prop.go:89 +0x2f7
golang.org/x/text/unicode/bidi.LookupRune(0x1, 0xb, 0x1)
	go/pkg/mod/golang.org/x/text@v0.3.0/unicode/bidi/prop.go:64 +0x7f
golang.org/x/text/secure/bidirule.init.0()
	go/pkg/mod/golang.org/x/text@v0.3.0/secure/bidirule/bidirule.go:252 +0x35
```

### Version & OS

Version 2.6.2
Windows 10 Pro

### Steps to reproduce the behavior

I started up VS Code first, then opened GitHub Desktop while VS Code was starting up, then immediately alt-tabbed to another application the very moment the GitHub Desktop application window opened. I can't see how this would cause this error though, but that's what I did.

The error only occurred once. I cannot reproduce the problem.

**Comment by steveward** [comment] 2021-01-26 18:25
Thanks for the detailed report @ariffjeff! I'm going to close this out since it seems to be a one-off error (and to help keep our open issues manageable), but I appreciate you opening this for reference in case any other users encounter this error in the future.

**Closed as completed by steveward** 2021-01-26 18:25 UTC

**Comment by fredcadete** [comment] 2021-02-08 15:30
This could be a git-lfs issue. I am seeing the same error intermittently when doing "git lfs pull".
This in CI, not involving the desktop client.

**Comment by vdsbenoit** [comment] 2021-02-11 12:58
@steveward, could we re-open this issue? We are getting more and more of these ones

**Comment by vdsbenoit** [comment] 2021-02-11 13:05
We have the issue with git-lfs/2.13.1 and git-lfs/2.13.2

**Comment by vdsbenoit** [comment] 2021-02-11 13:43
Forget about my previous comment. Since it is related to git-lfs, I will file a bug report on the git-lfs project.

That said, I am looking for a way to reproduce this issue, which is not systematic.

**Comment by steveward** [comment] 2021-02-11 16:53
This does look like a specific Git LFS issue, so I would recommend opening an issue over in that repository. It looks like there have been prior reports of this error in previous versions (e.g. https://github.com/git-lfs/git-lfs/issues/3540).
