### ISSUE TITLE
problem with deselect files for commit

### ISSUE THREAD

**Issue by fgvicente** [desktop/desktop#13984] opened 2022-02-23 13:32 UTC
Select doesn't work. 
When select some files it visually deselects them but when you give commit it adds all of them to commit

![image](https://user-images.githubusercontent.com/3626864/155328803-d9f37a12-61b7-412b-8d86-fcb3c0166023.png)

![image](https://user-images.githubusercontent.com/3626864/155328872-548ead81-755c-4f7d-96df-4d1e32206c80.png)

![image](https://user-images.githubusercontent.com/3626864/155328948-060c233d-5bb4-48d4-86d8-f6b812ae71b0.png)

after commit

![image](https://user-images.githubusercontent.com/3626864/155329200-11768511-4195-441b-a618-12d1b964261a.png)

**Comment by tidy-dev** [comment] 2022-02-23 17:33
@fgvicente Thanks for reaching out! I believe you are describing the expected behavior. 

The changes list has a few ways of interacting with it:.
1) When you select a file by clicking with the mouse on a non check mark part of a change, it becomes highlighted. This file is the one viewed in the diff.

2) You can ctrl click or shift click to highlight multiple changes. This gives you the ability to right click and apply context menu options to multiple files such as discard changes.
![image](https://user-images.githubusercontent.com/75402236/155374564-101094ae-6a9b-4146-b1a5-5a209cd3374a.png)

3) Toggling the check box by clicking on the checkbox will determine which files are committed.  If a file has a check or a dash (partial check), it means the whole file or part of the file will be commited.
![image](https://user-images.githubusercontent.com/75402236/155374316-fdd5c1a0-d5f7-402f-be09-35e933a38d28.png)
For example, in the above, the first file will have the one line committed and the 3rd file in the list will not be committed.

**Comment by fgvicente** [comment] 2022-02-23 18:06
![image](https://user-images.githubusercontent.com/3626864/155379818-663f293e-2abb-45a2-af95-6b25e4653b78.png)

@tidy-dev  Before, I used to select the two files of the image, give commit and only commit with those two files. now that doesn't work, because it gives comit to the 3 image files

**Comment by WATCHARA24MONTHON** [comment] 2022-02-23 18:19
Thanks,
I am send my Best Regard

**Comment by tidy-dev** [comment] 2022-03-02 01:32
@fgvicente Curious - I just tried and was unable to reproduce. Would you mind providing the Github Desktop version and your OS? 

Also, could you try doing this in another repository and see if it works there?

**Comment by fgvicente** [comment] 2022-03-02 17:41
@tidy-dev It's very weird. I don't know when it started. But I've been seeing him for several months now. my version is 2.9.10 and my operating system is windows 10. I am reviewing and with another repository it does not. that could be happening

**Comment by tidy-dev** [comment] 2022-03-02 19:45
@fgvicente Is the issue consistent or just sometimes?  Sorry to ask again, when you say "it does not", do you mean that the other repository does not have the issue?

Also could you upload the logs for a time where you have seen this happen. Find them via:
![image](https://user-images.githubusercontent.com/75402236/156437419-7e40de84-7533-43cc-a5f1-c2e4901a5c11.png)

Is there anything unusual about your git config setup?

**Comment by fgvicente** [comment] 2022-03-02 20:06
only this

2022-03-02T20:04:53.885Z - info: [ui] Executing createCommit: git commit -F - (took 6.056s)
2022-03-02T20:04:54.252Z - info: [ui] [Timing] Action 'create commit' for 'plantapps/pa-web-administrator' took 6.588s

**Comment by steveward** [comment] 2022-08-11 16:48
@fgvicente are you still encountering this issue in GitHub Desktop? I was unable to reproduce this behavior, and we have not had any other reports of this that I can find.

**Closed as completed** 2022-08-18 17:18 UTC
Labels: more-info-needed
