### ISSUE TITLE
renaming of branch not visible on github

### ISSUE THREAD

**Issue by vincent3569** [desktop/desktop#2367] opened 2017-07-31 17:40 UTC
I use github to share themes and plugin for the Zenphoto CMS.
In local, I use github desktop to manage my files on my PC.

I wanted to create a branch on a repository (https://github.com/vincent3569/zpBootstrap) and set this new branch as default one.
(To make it simple, the original master branch was obsolete, and I wanted to freeze the code in a dedicated branch called 1.x.)

my problem with github desktop (or github, I don't know)
on github desktop  and on github, I was able to create my branch 2.x and set it by default
In local, I was able to rename my old branch master to 1.x

By cons, on github, this old branch remains with the master name and is not renamed in 1.x.

Is it an issue ?
Can you help me to do the rights things to resynchronize both ?

Thank you in advance for your assistance.

**Comment by iAmWillShepherd** [comment] 2017-07-31 18:00
Thanks for creating this issue. I was able to reproduce this by doing the following.
1. Create a branch `dummy-original` using GHD
1. Publish branch `dummy-original` using GHD
1. Observe `dummy-original` has been created on GitHub.com
1. Rename `dummy-original` to `dummy-renamed` using GHD
    1. Modified a file on `dummy-renamed` and pushed commit using GHD (did this just in case branch needs to be pushed first
1. Observe that `dummy-original` has been renamed to `dummy-renamed` in GHD
1. Observe `dummy-original` has not been renamed to `dummy-renamed` on GitHub.com
1. Observe that commits to `dummy-renamed` pushed using GHD show up as commits to `dummy-original` on GitHub.com

**Comment by joshaber** [comment] 2017-07-31 18:24
As described, that's the intended behavior, though maybe not the _right_ behavior.

When Desktop renames a branch, it renames only the local branch. There's no such thing as renaming the remote branch. We could delete the old branch and push the renamed branch, but since that potentially effects others, I'm reticent to recommend it 🤔

**Comment by iAmWillShepherd** [comment] 2017-07-31 18:48
Ahh, I see. My mistake.

**Comment by iAmWillShepherd** [comment] 2017-07-31 18:49
Thanks for the suggestion!

This idea is interesting for the future, but this is beyond the scope of our current roadmap.

I'm going to add the future-proposal label to this issue and close it out, so that we don't get overwhelmed with our backlog! We'll revisit these as part of our next planning session.

**Closed by iAmWillShepherd** 2017-07-31 18:49 UTC
Labels: future-proposal

**Comment by vincent3569** [comment] 2017-07-31 19:14
Ok I understand that GHD can't push the renaiming.
But for now, how can I solve my personnal issue?
Thanks for your help.

**Comment by donokuda** [comment] 2017-07-31 19:15
@vincent3569 In this situation, instead of renaming the master branch, what are your thoughts on creating a new branch (named `1.x` in your example) off of `master` and pushing that instead? From there, you won't need to switch the default branch and you can continue making changes for 2.x in `master`.

Since this is intended behavior from git (renaming a branch doesn't rename the branch it's tracking), I'm hesitant to renaming the remote branch. One concern I have is that other collaborators working on the same branch would need to update their local branches to track the renamed branch.

**Comment by vincent3569** [comment] 2017-07-31 19:54
you are right, it perfectly solves my issue.
thks

**Comment by donokuda** [comment] 2017-07-31 20:08
@vincent3569 Good to hear! 🎉 I'm going to remove the `future-proposal` from this issue for now since your issue was solved and it doesn't seem like the original proposal is necessary anymore.

Best wishes on shipping 2.0! ✨
