### ISSUE TITLE
Collapsed when returned to window mode from full screen

### ISSUE THREAD

**Issue by zhangly7** [desktop/desktop#2040] opened 2017-06-18 02:37 UTC
### Description

GitHub desktop had no response when choose toggle full screen in full screen mode .

### Version

**GitHub Desktop version:** 0.6.1

**OS version:** windows 10.0.14393

### Steps to Reproduce

1. First I clicked toggle full screen
2. Then I press 'alt' to call the menu bar, wanted to changed it to normal window mode.
3. And it just became a small window with no response, like this 
![collapse](https://user-images.githubusercontent.com/16574599/27257710-1f342498-53ae-11e7-8832-addcf37e48e5.jpg), I had to end the process to close it

And next time I opened it, it still toggles full screen. 

**Reproduces how often:** every time I did it

**Comment by joshaber** [comment] 2017-06-19 15:31
This sounds like a duplicate of https://github.com/desktop/desktop/issues/1502. Feel free to follow along over there!

**Closed by joshaber** 2017-06-19 15:31 UTC
