### ISSUE TITLE
unhandled exception due to EACCESS error code when spawning git

### ISSUE THREAD

**Issue by antonija-nosto** [desktop/desktop#7111] opened 2019-03-18 09:41 UTC
## Description

My client crashes all the time. I also have problems where I am asked to give permissions to "git" and it's very likely connected with that.

## Version

* GitHub Desktop: 1.6.4

* Operating system: macOS Mojave 10.14.3

### Actual Behavior

<img width="712" alt="Screenshot 2019-03-18 at 11 29 36" src="https://user-images.githubusercontent.com/44493694/54520960-8fd96800-4972-11e9-9e5a-3abf850f724a.png">

**Comment by shiftkey** [comment] 2019-03-18 21:09
@antonija-nosto thanks for the report! I'm not too familiar with why we're seeing a `EACCES` exit code being raised when we try and invoke `git` from Node, so this bit of information is very interesting to me:

> I also have problems where I am asked to give permissions to "git" and it's very likely connected with that.

Are you able to share more detail about this? In particular I'm interested in:

 - what are you seeing that is asking you for permissions?
 - how are you trying to mitigate this?
 - what are the permissions for the installed Git?

You should be able to check the last item at the command line, like this:

```
$ ls -l /Applications/GitHub\ Desktop.app/Contents/Resources/app/git/bin/git
```

Does the owner and group that you see here make sense, or could this be a hint at the root cause of the issue?

**Comment by antonija-nosto** [comment] 2019-03-19 13:10
I click on Always Allow but that changes nothing. I get bombarded with this every time I code.

<img width="565" alt="Screenshot 2019-03-19 at 15 07 50" src="https://user-images.githubusercontent.com/44493694/54608160-ca1d3500-4a58-11e9-8a4d-e0a2e74411b5.png">

I checked permissions and they make sense, imo.

**Comment by newlighty** [comment] 2019-03-26 14:01
Error: spawn ‪E:\androidSdk\Sdk\platform-tools\adb.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by shiftkey** [comment] 2019-04-10 19:15
@antonija-nosto apologies for the delay in replying:

> I checked permissions and they make sense, imo.

Could you share what the ownership of the embedded Git is? I'm kind of stumped about how to trip this, and any helpful information here would be great...

**Comment by shiftkey** [comment] 2019-04-10 19:16
@newlighty it's not clear to me where your error is coming from. Please open a new [bug report](https://github.com/desktop/desktop/issues/new?template=bug_report.md) and fill out the issue template if you'd like us to investigate further.

**Comment by antonija-nosto** [comment] 2019-04-11 11:48
@shiftkey sorry, I am not sure I follow your question. What kind of info are you expecting here?

**Comment by shiftkey** [comment] 2019-04-11 12:42
@antonija-nosto I'm interested in the actual owner/group values when you run these three commands:

```
$ ls -l /Applications | grep GitHub
drwxr-xr-x@  3 shiftkey  staff      96  8 Apr 14:24 GitHub Desktop.app

$ ls -l /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop
-rwxr-xr-x@ 1 shiftkey  staff  18688  8 Apr 14:24 /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop

$ ls -l /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git
-rwxr-xr-x@ 1 shiftkey  staff  2405648  8 Apr 14:24 /Applications/GitHub Desktop.app/Contents/Resources/app/git/bin/git
```

Ideally they should be the same, but if the app can launch but it can't launch Git maybe they're not consistent (for some reason)? Essentially the error points to permissions to the executable being some unexpected result, but the source of why these permissions is incorrect is still puzzling to me...

**Comment by antonija-nosto** [comment] 2019-04-11 14:01
They are all the same.

**Comment by antonija-nosto** [comment] 2019-04-12 06:46
If I may add, I opened GitHub Desktop yesterday and left it open while developing and it didn't complain. I am not sure if the error resolved by itself, but so far so good. I had similar experience before but then it started to complain again until it stopped working altogether and then I came here :)

**Comment by shiftkey** [comment] 2019-04-24 13:02
> If I may add, I opened GitHub Desktop yesterday and left it open while developing and it didn't complain. I am not sure if the error resolved by itself, but so far so good. I had similar experience before but then it started to complain again until it stopped working altogether and then I came here :)

@antonija-nosto this is interesting, and I wonder if some other software is trying to be clever and changing things underneath Desktop (file permissions made the most sense given the mention of the `EACCES` error code). I don't have any other insight currently into what might be causing this, but I'm going to move this to "needs investigation" to see if we can figure out the root cause.

**Comment by antonija-nosto** [comment] 2019-04-26 10:48
After numerous updates from macOS and GitHub Desktop side, the issue resolved by itself. I haven't experienced this error for at least 2 weeks now.

**Comment by shiftkey** [comment] 2019-04-26 11:48
@antonija-nosto I'm going to close this out for the moment, but if you notice it again and can spot anything that might help us explain the issue and figure out what is causing it please let us know...

**Closed by shiftkey** 2019-04-26 11:48 UTC
Labels: investigation-needed, macOS
