### ISSUE TITLE
UI: Loss of focus when pressing down key in changed files list

### ISSUE THREAD

**Issue by JeanCollas** [desktop/desktop#8689] opened 2019-11-24 08:11 UTC
When having many files not committed, if you click on the changed files list and want to explore using the arrows, you will face loss of focus when going down (down 2-3 times after the last visible item).
This is a bit disturbing when you want to select items.

When going down the non-visible items should become visible.

I have had this behavior since the beginning and still in the current version.

**Comment by tierninho** [comment] 2019-11-25 18:34
@JeanCollas This is a duplicate of https://github.com/desktop/desktop/issues/6845. Please follow along there. Thanks.

**Closed by tierninho** 2019-11-25 18:34 UTC
