### ISSUE TITLE
Add notification on "Update from master" completed without changes

### ISSUE THREAD

**Issue by Xotabu4** [desktop/desktop#9648] opened 2020-04-28 15:51 UTC
### Describe the feature or problem you’d like to solve

Currently when you are selecting "Update from master", and your branch is already up to date, just nothing happens.

### Proposed solution

 It will be good to have some visible message, like alert, with "Already up to date!" success message. It can be same alert that is shown on all conflicts are merged, but with different text

### Additional context

![image](https://user-images.githubusercontent.com/3033972/80508368-a2e5a680-8980-11ea-8305-543208e16234.png)

**Comment by billygriffin** [comment] 2020-04-28 15:54
Hi @Xotabu4, agreed! This is a duplicate of https://github.com/desktop/desktop/issues/9095, where we've outlined a proposed solution that is in line with your suggestion, so I'm going to close this in favor of that one. Thanks again!

**Closed by billygriffin** 2020-04-28 15:54 UTC
