### ISSUE TITLE
Stuck on Windows App login screen - Only loading

### ISSUE THREAD

**Issue by SeeksThree** [desktop/desktop#12102] opened 2021-04-30 11:37 UTC
I am trying to log in to the Github application on Windows Desktop. When clicking "Open in browser" and Chrome prompts a window saying "Open Github application" and I click it, the log in screen in the application just keeps loading and the console is only saying "[SignInStore] initializing OAuth flow". Nothing else happens.

### Expected behavior
Accessing the main screen once logged in.

### Actual behavior
Stuck on the loading screen when trying to sign in. The console just says "initializing" as if it does not register the login attempt.
If I close the Github application and then click "Open Github Application" in the browser, it does not even open Github

**Comment by tidy-dev** [comment] 2021-05-03 11:02
Hi! @SeeksThree Thank you for the report and sorry for your troubles.

Unfortunately this is a known issue that we haven't been able to readily reproduce ourselves. We are tracking here https://github.com/desktop/desktop/issues/11410

It appears other people who have run into this are running GitHub Desktop on a VM. We would really appreciate if you could add details about your environment to the [tracking issue](https://github.com/desktop/desktop/issues/11410) that may help us narrow down the cause. 

Also, maybe worth a try to change your default browser.

I am going to close this issue in favor of tracking issue.

**Closed as completed by tidy-dev** 2021-05-03 11:02 UTC
