### ISSUE TITLE
Github desktop -> Can't sign in using edge browser, it simply hangs.

### ISSUE THREAD

**Issue by raroraccsf** [desktop/desktop#17591] opened 2023-10-19 18:43 UTC
### The problem

when I sign out from one account using options->sign out, close it, relaunch it to sign in as another user, the browser and the github desktop hangs, nothing happens. 

### Release version

3.3.4

### Operating system

Windows 10

### Steps to reproduce the behavior

1. launch desktop
2. File -> options->sign in -> continue with browser
3. I am using edge browser, it hangs

**Comment by tidy-dev** [comment] 2023-10-23 12:26
👋 @raroraccsf  Sorry for your troubles. This appears to be a duplicate of https://github.com/desktop/desktop/issues/11410. I am going to close it in favor tracking the issue there. 

Unfortunately, we have not been able to replicate and therefore haven't nailed down a reason this sometimes happens; tho, seemingly an environmental factor. 
- Some users have been able to resolve theirs by uninstalling and reinstalling GitHub Desktop. 
- Other have seen that if they wait a few minutes and click the button in the browser again it works. 
- Another user has seen that their machine was blocking (antivirus/firewall) the first authenticated network call. 
- Others have noted issues when they have multiple different browsers open. 

Hopefully that helps with debugging. If you happen to figure out a reason, please let us know so we can help other users.

**Closed as completed by tidy-dev** 2023-10-23 12:26 UTC
