### ISSUE TITLE
Odd unwanted separation in the middle of commit messages

### ISSUE THREAD

**Issue by NiklasBr** [desktop/desktop#5129] opened 2018-07-09 14:36 UTC
## Description
Many commit messages are being cut after some 75% even though the app clearly has enough room for the entire message. In addition to that, the rest of the message is being printed in the description area.

## Version
* GitHub Desktop: 1.2.6
* Operating system: macOS 10.12.6 (16G1408)

## Steps to Reproduce
1. Create a commit with a message, such as "Bah, undo that as it's not supported in the old version of fixer we have to run"
2. Look at it.

### Expected Behavior
The commit message, unbent, unbowed, unbroken, something something, like that. Or just kept on one line, that would be fine :)

### Actual Behavior
The message is being unnecessarily split into pieces.

## Additional Information
This makes issue #4382 more severe.

![screen shot 2018-07-09 at 16 26 32](https://user-images.githubusercontent.com/279826/42456538-77ae0180-8395-11e8-89e3-3fc23b4a5c17.png)

**Comment by shiftkey** [comment] 2018-07-09 15:23
@NiklasBr thanks for the report! I can reproduce this, and I'll drop some more context into here as to what's happening and why.

**Comment by shiftkey** [comment] 2018-07-09 15:30
This behaviour was added in https://github.com/desktop/desktop/pull/2575 and is a change we made to be consistent with how GitHub the Website truncates long commit summaries.

**Comment by shiftkey** [comment] 2018-07-09 15:52
Yep, this is by design. I used the same commit title on GitHub and got this result.

Here's how the "latest commit" looks:

<img width="996" src="https://user-images.githubusercontent.com/359239/42461251-68c7a280-8376-11e8-8742-be04ab33c65d.png">

And the commit summary page is the same:

<img width="1002" src="https://user-images.githubusercontent.com/359239/42461228-5eaa46c2-8376-11e8-971e-bf1da96600eb.png">

When you clone down the repository, you see that the commit summary is preserved rather than trimmed:

```
$ git log
commit 69d18d58d29b77594d90248e4cac24705b357d4c
Author: Brendan Forster <brendan@github.com>
Date:   Mon Jul 9 12:47:56 2018 -0300

    Bah, undo that as it's not supported in the old version of fixer we have to run
```

**Comment by shiftkey** [comment] 2018-07-09 15:54
Closing this out because it's a conscious decision to ensure that GitHub Desktop and GitHub the Website are consistent when displaying commits like this.

**Closed by shiftkey** 2018-07-09 15:54 UTC

**Comment by NiklasBr** [comment] 2018-07-09 18:15
Your conscious decision has led to a very kludgey and an ugly end result.
