### ISSUE TITLE
Suggestion: show repo summary status indicator in 'current repository' selector.

### ISSUE THREAD

**Issue by areaycee** [desktop/desktop#3847] opened 2018-01-23 07:01 UTC
One thing that I find myself doing regularly and imagine others may, is clicking through all repositories in the 'current repository' selector to see which, if any have uncommitted changes.  Is it possible to show one or more of the file status icons in the actual repo selection list as a summary to indicate the repo contains at least one file of the given state?  eg, uncommitted changes, not added. conflicted etc.

**Comment by j-f1** [comment] 2018-01-23 11:37
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #2259, which we’re hoping to get to in v1.3. Please follow that issue for further updates.

**Closed** 2018-01-23 14:04 UTC
