### ISSUE TITLE
Make Nº of recent branches configurable

### ISSUE THREAD

**Issue by Tefery** [desktop/desktop#15777] opened 2022-12-13 16:11 UTC
### The feature request

I work with dozens of branches, so, the "Recent branches" zone it's too small for me.

### Proposed solution

Make the number of recent branched saved configurable.

**Comment by steveward** [comment] 2022-12-13 18:30
Thanks for the issue @Tefery, I'm going to close this as a duplicate of https://github.com/desktop/desktop/issues/14311.

**Closed as not planned by steveward** 2022-12-13 18:30 UTC
Labels: enhancement
