### ISSUE TITLE
Desktop crash when committing

### ISSUE THREAD

**Issue by martimyc** [desktop/desktop#3190] opened 2017-10-29 04:15 UTC
### Description

I tyr to commit and the application crashes completlly saying this:
Error: write EOF
    at exports._errnoException (util.js:1050:11)
    at WriteWrap.afterWrite (net.js:813:14)

note that the repository is from bitbucket and i cloned it to my pc before adding it to the app.

### Version

**GitHub Desktop version:** 1.0.6

**OS version:** Microsoft Windows Version 10.0.10240

### Steps to Reproduce

1. [First step]
commit changes
1. [Second step]
crash
1. [and so on]

https://i.gyazo.com/4a85674dbd9908249e9a5cc3e02f2177.gif

![4a85674dbd9908249e9a5cc3e02f2177](https://user-images.githubusercontent.com/11175441/32140620-d05ed5ca-bc67-11e7-9c10-ae71aca93cdf.gif)

**Expected behavior:** commit

**Actual behavior:** crash

**Reproduces how often:** 100%

### Logs

[2017-10-09.desktop.production.log](https://github.com/desktop/desktop/files/1424788/2017-10-09.desktop.production.log)
[2017-10-27.desktop.production.log](https://github.com/desktop/desktop/files/1424789/2017-10-27.desktop.production.log)
[2017-10-28.desktop.production.log](https://github.com/desktop/desktop/files/1424790/2017-10-28.desktop.production.log)
[2017-10-29.desktop.production.log](https://github.com/desktop/desktop/files/1424791/2017-10-29.desktop.production.log)
[2017-10-04.desktop.production.log](https://github.com/desktop/desktop/files/1424792/2017-10-04.desktop.production.log)
[2017-10-05.desktop.production.log](https://github.com/desktop/desktop/files/1424793/2017-10-05.desktop.production.log)
[2017-10-08.desktop.production.log](https://github.com/desktop/desktop/files/1424794/2017-10-08.desktop.production.log)

**Comment by joshaber** [comment] 2017-10-30 12:09
Thanks @martimyc! This looks like a duplicate of https://github.com/desktop/desktop/issues/2041 so I'm gonna close it. Feel free to follow along over there!

**Closed by joshaber** 2017-10-30 12:09 UTC
