### ISSUE TITLE
NPM command not found on GitHub desktop

### ISSUE THREAD

**Issue by thucne** [desktop/desktop#18747] opened 2024-06-03 07:01 UTC
### The problem

Hi, I was trying to run a git hook that included an npm command, but then ran into an error that "npm: command not found". 

This was just fine when I tried to push using the normal command line/PowerShell. But then I got the issue when trying to push by GitHub Desktop

### Release version

3.4.0

### Operating system

Windows

### Steps to reproduce the behavior

1. Go to '.git/hooks/pre-push' and add one npm command such as 
```bash
    #!/bin/sh
    
    # bump version 1.0.0 -> 1.0.1, last number is incremented
    
    npm version patch -m "Bump version to %s"
```

2. Try to edit sth in the code, commit, then push (given that you have git initialized and config them to remote git)

**Comment by fbastien** [comment] 2024-06-03 11:57
This arise not only with npm commands.
I have a hook that executes a java program, and I also get `java: command not found` errors since upgrading from v3.3.18 to v3.4.0.
This is really annoying, I hope it will be fixed soon!

I suggest renaming this issue to "Command not found in hooks on GitHub Desktop".

**Comment by arnodemer** [comment] 2024-06-03 15:03
Agree with @fbastien,  on my side, pre-push failed on: 
>  **node**: command not found

note that, node's folder is part of %PATH%

**Comment by CalebSmith0801** [comment] 2024-06-03 15:09
Similar situation for me `npx.cmd: command not found`

Seems as if GitHub Desktop is no longer using the system PATH environment variable anymore. If I change my script to point to the exact file path for `npx.cmd` it works.

**Comment by fbastien** [comment] 2024-06-03 15:26
Do you think this is a security feature, or should it still use the system PATH ?

**Comment by TheMikeyRoss** [comment] 2024-06-03 20:05
Same here, i have a husky hook that runs `tsc` and now i get command not found

**Comment by Drumstix42** [comment] 2024-06-03 20:20
```
.husky/pre-commit: npm: command not found
husky - pre-commit script failed (code 127)
husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/<user>/bin:/mingw64/bin:/mingw64/usr/bin:undefined
```

**Comment by TheMikeyRoss** [comment] 2024-06-03 20:43
Yup @Drumstix42 I have the same exactt error msg. No matter what I change npm with I will always get:
`[something]: command not found`

**Comment by arnodemer** [comment] 2024-06-04 07:46
Solution is to revert back to previous version as @andylwelch said.
https://github.com/desktop/desktop/issues/18739#issuecomment-2146459493

**Comment by glundgren93** [comment] 2024-06-04 10:11
I think this could've been the root cause. 
#18676

**Comment by tidy-dev** [comment] 2024-06-04 11:38
Closing in favor of duplicate https://github.com/desktop/desktop/issues/18739

**Closed as completed by tidy-dev** 2024-06-04 11:38 UTC

**Comment by danwild** [comment] 2025-03-03 01:06
> ```
> .husky/pre-commit: npm: command not found
> husky - pre-commit script failed (code 127)
> husky - command not found in PATH=/mingw64/libexec/git-core:/mingw64/bin:/usr/bin:/c/Users/<user>/bin:/mingw64/bin:/mingw64/usr/bin:undefined
> ```

I also came here with the husky pre-commit error, which I fixed by modifying the path in my `husky/pre-commit` file:

```
#!/bin/sh
export PATH="/usr/local/bin:$PATH"

# now do pre-commit things..
```
