### ISSUE TITLE
Character corruption

### ISSUE THREAD

**Issue by pcavalcanteoliveira** [desktop/desktop#6042] opened 2018-10-30 17:58 UTC
**Please describe the problem you think should be solved**
Downloading .Rnw files by Github Desktop corrupts encoding. Special characters, specifically, are lost. 

Example:

What should be:

> "A inflação cheia medida pelo IPCA em um período"

Becomes: 

> “A infla??o cheia medida pelo IPCA em um per?odo”

**Comment by tierninho** [comment] 2018-10-30 18:16
@pcavalcanteoliveira thanks for filing. Can you provide some more details like the logs, your version of Desktop, mac/windows OS, and some reproduction steps. Valeu.

**Comment by shiftkey** [comment] 2018-11-07 15:37
@pcavalcanteoliveira are you able to provide a public commit or example to go with this issue? I think this is the same root cause as #3923

**Comment by billygriffin** [comment] 2018-11-14 02:34
Since I think we have this captured in #3923, I'm going to close this out. Sorry it's a pain for you @pcavalcanteoliveira.

**Closed by billygriffin** 2018-11-14 02:34 UTC
Labels: more-information-needed
