### ISSUE TITLE
Multiple issues related to SSL Interception (environs with proxy, enterprise MITM, etc)

### ISSUE THREAD

**Issue by DeepMac** [desktop/desktop#4189] opened 2018-03-06 21:22 UTC
## Description

GitHub Desktop exhibits issues with authentication and repository cloning when SSL interception is present, such as Enterprise MITM configurations (Proxies and other cybersecurity products).

1) Logging into GitHub account via username and password within the GUI gives an error indicating the username and password is incorrect when they are correct. Logging in via browser still works. But error message is mis-leading and could trigger user interaction loops (reset password, try new password, reset it again, etc).

2) Cloning a repository throws cryptic errors about SChannel. Documented in #3326 I suspect this is at least partially related to interception, as switching to OpenSSL can still throw errors because of expected certificate signatures not matching.

3) Instructions for the workaround here are inconsistent and don't seem to work. Do I use http.CAInfo, http.CAFile or http.CAPath? Do I specify the path in Windows notation (C:\foo\bar) or the Git bash shell form (/c/foo/bar)? Regardless of what I set, I could not get this solution to work. Instead, I had to issue a "git config --global http.sslVerify false" so I could use the openSSL backend and get around the problems with accessing the cert file.

4) Only that didn't actually work. Because now I get "fatal: .git/index: index file open failed: Permission denied". Or hey maybe it did, the files are there. But I just wasted 1.5 hours on this.

## Version

* GitHub Desktop: 1.1.0

* Operating system: Microsoft Windows 10.0.14393

## Steps to Reproduce

Reproduction would require access to a restricted corporate environment.
Recommend setting up a lab and configuring an Enterprise grade security product such as BlueCoat or similar that does MITM, then using internal certificates for the pass-back.

### Expected Behavior

1) Sign-in directly with no error, or get a message indicating issues communicating with auth server.

2) Clone the repo without any hassle.

3) Should never get here but if we do, shouldn't have confusing workarounds that don't work.

### Actual Behavior

Augh. See above. I'm hating this form now.

### Logs

[2018-03-06.desktop.production.log](https://github.com/desktop/desktop/files/1786763/2018-03-06.desktop.production.log)

**Comment by DeepMac** [comment] 2018-03-06 21:24
I'd like to suggest these and potential other failures related to this sort of environment be addressed during install. Detect the existence of MITM, alert the user. If they verify they are running in a restricted corporate environment, activate a "MITM Mode" where all configurations related to checking cert validity, revocation, etc are disabled. Optionally check for local CA's in the Windows cert storage.

**Comment by shiftkey** [comment] 2018-03-06 21:29
@DeepMac thanks for the detailed report! You've encountered a known issue which, as you mention, is related to SSL interception:

```
Cloning into 'C:\Users\jmercer1\Documents\GitHub\apache-log-parser'...
fatal: unable to access 'https://github.com/rory/apache-log-parser.git/': schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
```

This is occurring because our embedded Git is using SChannel - which relies on the Windows Certificate Store - for doing SSL/TLS handshaking. On some networks, the revocation checks are blocked, and so Git fails the clone. It's hard for us to detect this behaviour without actually performing a clone or fetch/push/pull.

This has been documented as a [known issue](https://github.com/desktop/desktop/blob/master/docs/known-issues.md#certificate-revocation-check-fails---3326) - the workaround documented will switch you back to the classic OpenSSL-based certificate checks and avoid this issue.

I've submitted a config flag to Git for Windows https://github.com/git-for-windows/git/pull/1450 to support bypassing the revocation check on SChannel - there's an open issue that I need to investigate to confirm this works as expected: https://github.com/git-for-windows/git/issues/1531

Once I'm confident in this new behaviour, and we update our embedded Git, I'll revisit #3326 which is improving this experience in Desktop.

**Comment by shiftkey** [comment] 2018-03-06 21:33
> Instructions for the workaround here are inconsistent and don't seem to work. Do I use http.CAInfo, http.CAFile or http.CAPath? Do I specify the path in Windows notation (C:\foo\bar) or the Git bash shell form (/c/foo/bar)? Regardless of what I set, I could not get this solution to work. Instead, I had to issue a "git config --global http.sslVerify false" so I could use the openSSL backend and get around the problems with accessing the cert file.

Oops, I missed this bit. The syntax here is the full Windows path, like this:

```
[http]
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
```

**Comment by shiftkey** [comment] 2018-03-06 21:47
@DeepMac following up on the other issue around login:

> Logging into GitHub account via username and password within the GUI gives an error indicating the username and password is incorrect when they are correct. 

Are you able to grab the specific error message you saw with the username/password flow. We don't capture this in the log file, and I'm curious about this because the browser login flow has a step where we create an access token through the GitHub API (which requires a network call that should be going through the proxy) but this completes without error.

**Comment by DeepMac** [comment] 2018-03-08 16:41
@shiftkey 1)  Thanks for updating the docs. In my case I used that path format and it still didn't work. But there may have been additional factors due to corporate environment's key and certificate management.

2) The only error I get when logging in via the app is "Invalid username or password." Nothing appears in the log, as you mentioned. I don't think pcaps would be useful since I assume it's HTTPS.

**Comment by shiftkey** [comment] 2018-03-21 08:44
> The only error I get when logging in via the app is "Invalid username or password." Nothing appears in the log, as you mentioned. I don't think pcaps would be useful since I assume it's HTTPS.

This is still open because I'm trying to wrap my head around why username/password authentication would fail but OAuth flow would succeed - both hit the GitHub API and should either pass through or get rejected by any sort of proxy.

**Comment by schlamar** [comment] 2019-05-29 07:24
@DeepMac 
- You need to point `sslCAInfo` to a file in PEM format (see https://stackoverflow.com/a/991772/851737 for conversion instructions). 
- You have to use escaped backslashes (e.g. `C:\\Users\\user\\cert.pem`). 
- `sslCAInfo` is only used if `http.sslBackend` is `openssl` (default is `schannel`).

**Comment by kflekac** [comment] 2019-09-23 22:41
> @DeepMac
> 
> * You need to point `sslCAInfo` to a file in PEM format (see https://stackoverflow.com/a/991772/851737 for conversion instructions).
> * You have to use escaped backslashes (e.g. `C:\\Users\\user\\cert.pem`).
> * `sslCAInfo` is only used if `http.sslBackend` is `openssl` (default is `schannel`).

Hi, I've changed my git config for my git for windows, and still receive a revocation error when trying to push/pull while using Github Desktop. This issue does not appear to happen when using Git Bash. Can any one provide guidance on what might be the issue?

**Comment by mislav** [comment] 2019-09-24 09:54
@kflekac I'm sorry that this issue affects you. It would be really helpful to us (and anyone else who reads this thread) if you shared more information about the following:

1. How exactly did you configure your git, i.e. paste relevant configuration options;
2. What exact error do you get from Desktop? Attaching a log file or quoting relevant parts from the logs would be great;
3. Try [the listed workaround](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#certificate-revocation-check-fails---3326) and report if it works. We don't suggest that you should keep this setting forever (it lowers security), but it might be helpful to at least know whether it has any effect.

Thank you!

**Comment by kflekac** [comment] 2019-09-25 04:10
I have this set up within my git config, which resolves the errors while using git bash
![image](https://user-images.githubusercontent.com/16280870/65568536-98ec6700-df9d-11e9-80b8-ae40abe0def4.png)

However github desktop gives me this error, despite not having schannel as my sslbackend
![image](https://user-images.githubusercontent.com/16280870/65568632-e7016a80-df9d-11e9-8045-c09178d1ba02.png)

This is the log:
![image](https://user-images.githubusercontent.com/16280870/65568704-19ab6300-df9e-11e9-9a59-f01af9eb3c91.png)

**Comment by mislav** [comment] 2019-09-25 06:31
@kflekac Thank you for the info. Per my above question, have you tried this as well? `git config --global http.schannelCheckRevoke false`

**Comment by kflekac** [comment] 2019-09-25 06:39
> @kflekac Thank you for the info. Per my above question, have you tried this as well? `git config --global http.schannelCheckRevoke false`

Yes, it still returns the revocation error

![image](https://user-images.githubusercontent.com/16280870/65575410-153d7500-dfb3-11e9-8274-f69066ce23cc.png)

**Comment by mislav** [comment] 2019-09-25 11:35
@kflekac Thank you for trying that out. Sadly, I don't have any more workarounds to suggest at this time. I don't have an idea why Desktop git acts differently than your system git.

**Comment by giuliohome** [comment] 2020-04-11 12:49
Referenced the steps to reproduce this issue in my [answer](https://stackoverflow.com/a/61121506/11323942).

**Comment by steveward** [comment] 2022-06-17 19:41
We've made improvements to proxy support and schannel (https://github.com/desktop/desktop/pull/10581), so I'm going to close this out.

**Closed by steveward** 2022-06-17 19:41 UTC
Labels: investigation-needed, windows
