### ISSUE TITLE
Selection in diff view doesn't work with long lines

### ISSUE THREAD

**Issue by mischnic** [desktop/desktop#2669] opened 2017-09-10 10:58 UTC
### Description

Text selection in the diff view doesn't work with long lines:
Here I tried to select the first three words "Lorem ipsum dolor", but the selection box is as high as the line and the text that is actually copied by cmd+C is displayed in white.
![example](https://user-images.githubusercontent.com/4586894/30248350-684fd6b2-9626-11e7-8e29-74671e090c8a.png)

### Version

**GitHub Desktop version:** 0.8.1

**OS version:** macOS Sierra 10.12.6

### Steps to Reproduce

1. Find a changed file with line which is longer than the window wide
2. Try to select and copy words from that line

**Expected behavior:** Selects the text according to mouse movement

**Actual behavior:** A strange selection box and different text gets selected

**Reproduces how often:** Always on long lines

**Comment by j-f1** [comment] 2017-09-10 11:49
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #1551. Please follow that issue for further updates.

**Closed** 2017-09-10 20:51 UTC
