### ISSUE TITLE
Bug: Github Desktop throws an error when running git hooks

### ISSUE THREAD

**Issue by liaoliaots** [desktop/desktop#13307] opened 2021-11-11 09:00 UTC
### Describe the bug
Github Desktop throws an error when running git hooks:

```
/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)
```

If I run `git commit -m "fix: update"` via git bash, this error does not occur.

<img width="310" alt="Screenshot 2021-11-11 165830" src="https://user-images.githubusercontent.com/27341089/141268625-9b8ebdd8-87d2-4733-970e-21c5edab9568.png">

### Version & OS

- Github Desktop: 2.9.4 (x64)
- OS: Windows 10 Pro 21H1, 64-bit operating system
- Git: 2.33.1.windows.1
- husky: 7.0.4
- lint-staged: 11.2.6

### Steps to reproduce the behavior

1. go to the git project
2. run `npx husky install`
3. run `npx husky add .husky/pre-commit 'npx lint-staged'`
1. change some files
2. input summary "chore: update" in Github Desktop
3. click "Commit to **main**"

### Expected behavior

This error should not occur

### Actual behavior

This error occurred

### Screenshots

<img width="463" alt="Screenshot 2021-11-11 165053" src="https://user-images.githubusercontent.com/27341089/141267524-9f87081e-07ff-42fc-a5b8-69db3d57b202.png">

### Logs

**2021-11-11.desktop.production.log**

```
2021-11-11T08:52:43.540Z - info: [ui] [AppStore] loading 1 repositories from store
2021-11-11T08:52:43.541Z - info: [ui] [AppStore] found account: liaoliaots (LiaoLiao)
2021-11-11T08:52:43.553Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-11-11T08:52:44.102Z - info: [ui] launching: 2.9.4 (Windows 10.0.19043)
2021-11-11T08:52:44.103Z - info: [ui] execPath: 'C:\Users\LiaoLiao\AppData\Local\GitHubDesktop\app-2.9.4\GitHubDesktop.exe'
2021-11-11T08:52:52.178Z - error: [ui] `git commit -F -` exited with an unexpected code: 1.
stderr:
/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)

2021-11-11T08:52:52.179Z - info: [ui] [Timing] Action 'create commit' for 'liaoliaots/codeliaoliao-app' took 0.416s
```

### Additional context

**.lintstagedrc.js**

```
module.exports = {
    '*.{ts,tsx}': ['prettier --write', () => 'tsc -p tsconfig.json', 'eslint --ext .ts,.tsx']
};
```

**git config --list**

<img width="409" alt="Screenshot 2021-11-11 170354" src="https://user-images.githubusercontent.com/27341089/141269488-5c312d1d-47ab-45ae-860b-6663661d2fca.png">

**Comment by sergiou87** [comment] 2021-11-12 11:32
Thanks for your report @liaoliaots !

This seems to be a duplicate of #12562 so I'm gonna close in favor of that. I'd suggest to write a comment there and subscribe in case there is any progress to address this.

**Closed as completed by sergiou87** 2021-11-12 11:32 UTC

**Comment by chrisauret** [comment] 2022-05-10 03:17
Same issues. Then I updated my PATH as shown here https://github.com/typicode/husky/issues/950
Fixed it for me 

Version & OS
Github Desktop: 3.0.0 (x64)
OS: Windows 10 Pro 21H1, 64-bit operating system
Git: 2.33.1.windows.1
husky: 8.0.0
lint-staged: 12.4.1

**Comment by raubana** [comment] 2022-05-11 23:58
I also have this problem. Seems to happen for pre-push as well but with even more errors.

**Comment by Mahek-Vasoya** [comment] 2024-01-30 08:46
I have the same problem for mac os. do we have any solution for that?
