### ISSUE TITLE
Text elements of image diff comparison breaks when the image is too small.

### ISSUE THREAD

**Issue by K0-RR** [desktop/desktop#12899] opened 2021-09-03 14:10 UTC
### Version & OS
2.9.2-linux1 on Arch Linux.
I cannot test this on Windows but it looks more like an upstream issue so reporting here. Let me know if I'm mistaken.

### Steps to reproduce the behavior

1. Create a repo with a small pic in it.
2. Change sth on the picture.
3. Look at the diff view in the Desktop app.

### Expected behavior
Fixed text line width? Non-breaking space? Redesigned diff viewer? 

### Actual behavior
![Screenshot from 2021-09-03 10-29-33](https://user-images.githubusercontent.com/43277609/131980489-97132b9c-0c47-40e0-af08-9ea7232b54f0.png)
![Screenshot from 2021-09-03 10-29-43](https://user-images.githubusercontent.com/43277609/131980490-0a1cb732-895e-4af9-a0b0-a9552b139a3d.png)
![Screenshot from 2021-09-03 10-30-02](https://user-images.githubusercontent.com/43277609/131980493-3663b3f0-d72e-4088-b5aa-91f0f9994053.png)

**Comment by NilsEnevoldsen** [comment] 2024-04-15 15:09
Duplicate of #11404.

**Comment by tidy-dev** [comment] 2024-04-15 17:16
@NilsEnevoldsen You are right. Closing this in favor of tracking it there. This is addressed in beta and will ship in the next production release.

**Closed as completed by tidy-dev** 2024-04-15 17:16 UTC
Labels: investigation-needed
