### ISSUE TITLE
Git/GitHub applying text file filter CRLF -> LF to binary PNG image files in error.

### ISSUE THREAD

**Issue by Maelstorm1973** [desktop/desktop#5323] opened 2018-08-02 19:29 UTC
## Description

When adding certain binary image files to the repository, GitHub is applying the CRLF -> LF filter in error.

## Version

* GitHub Desktop:  1.3.2

* Operating system: Microsoft Windows [Version 10.0.16299.547]

## Steps to Reproduce

1. Add binary image files to the repository (png files in my case).
2. Commit and push.
3. Pull files onto different machine (web server in my case).
4. The files on the other machine are corrupted.

### Expected Behavior

Binary files should be stored in the repository as is with no filters applied.

### Actual Behavior

CRLF -> LF filter is applied in error.

## Additional Information

[broken_files.zip](https://github.com/desktop/desktop/files/2254888/broken_files.zip)
[working_files.zip](https://github.com/desktop/desktop/files/2254894/working_files.zip)
![image](https://user-images.githubusercontent.com/12518894/43605836-87a033ee-964e-11e8-9ed1-d6c3290021e4.png)

### Logs

[2018-08-02.desktop.production.log](https://github.com/desktop/desktop/files/2254904/2018-08-02.desktop.production.log)

**Comment by shiftkey** [comment] 2018-08-02 19:35
@Maelstorm1973 I can't see any mentions of commits being done in that log file, but the really important thing I need to understand the issue is the contents of your `.gitattributes` file in the repository - this is where users can define filter rules that Git will apply when reading and writing between the object database in the repository and the working directory on disk.

Anything interesting in there?

**Comment by Maelstorm1973** [comment] 2018-08-03 00:16
After I posted this, I came across a blog that was talking about .gitattributes.  So using the information in that article, I added this line to it:

`*.png binary`

Now it's working.

The full file is this:
```
* text=auto
* text eol=lf
*.png binary

```
From what I can gather, it should determine if the file is text automatically, and if it is, then end of line markers should be converted to LF.  There is still a bug though, because a PNG image file is obviously binary, but GitHub Desktop thinks it a text file for some strange reason.  I shouldn't have to manually tell it that all PNG files are binary.

**Comment by shiftkey** [comment] 2018-08-03 11:03
@Maelstorm1973 thanks for the extra details. I don't believe this is a problem with Desktop, but more with how the `.gitattributes` file is configured. Let me explain the rules you've added to the file:

```
* text=auto
```

This is the rule to ensure any text files have their line endings normalized. This is a great default, and one we'll set in Desktop for new repositories.

```
* text eol=lf
```

This is the problem line - this rule essentially says "for all files consider them text and ensure the line endings are set to `LF`". That's why Git has gone and changed the line endings inside the PNG headers - it's spotted the `CRLF` at the start of the file and applied this filter rule to it.

<img width="480" src="https://user-images.githubusercontent.com/359239/43639509-d9ae2732-96f2-11e8-8358-da676e9b3aab.png">

I'd recommend making this rule apply only to the specific files types you are trying to control here, rather than `*`. Do you know which file extensions you want to to control the line endings of?

Applying more filter rules to this won't undo this behaviour - you'll need to:
 - configure your `.gitattributes` rules correctly to avoid changing line endings inside PNGs
 - restore the original image from an external source, 
 - commit the fix.

I'm happy to help figure out how to apply `eol=lf` rule correctly with the right context, but the others that I think you need are just this:

```
* text=auto
*.png -text
```

**Comment by shiftkey** [comment] 2018-08-14 13:03
Closing this out because I believe this was an error with the setup of the repository. @Maelstorm1973 let me know if there's anything else to add to this discussion.

**Closed by shiftkey** 2018-08-14 13:03 UTC
