### ISSUE TITLE
remote with pushurls to different hosts cannot authenticate correctly

### ISSUE THREAD

**Issue by brandondube** [desktop/desktop#3894] opened 2018-01-31 04:27 UTC
### Description

if I interact with remotes on the cli, everything works properly, e.g.
```
git push -u origin master
Everything up-to-date
Branch master set up to track remote branch master from origin.
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 483 bytes | 241.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
To https://bitbucket.org/<username</<repo>.git
   76bcd8e..dfcd232  master -> master
Branch master set up to track remote branch master from origin.
```
The other origin (on github) is already up-to-date, since that far succeeded in the Desktop GUI.

### Version

**GitHub Desktop version:** 1.0.14-beta1

**OS version:** Windows 10

### Steps to Reproduce

1.  clear all git credentials in windows control panel
1.  reboot
1. `git remote set-url origin --push --add <github url>`
    `git remote set-url origin --push --add <bitbucket url>`
1. git fetch
1. enter github creds
1. enter bitbucket creds
1. commit something
1. push (will succeed)
1. attempt the same in Github Desktop (will fail)

fetch continues to work in the UI since the bitbucket url is only a pushurl not a url or fetchurl.  It is only when the Desktop UI attempts to talk to bitbucket that it fails.

### Logs
The timestamp format is not something I can understand, so I am not sure if this excerpt is from before or after I reset all git creds.  I believe it is after since I reset my creds in the UI as well as the cli
```
2018-01-31T04:03:25.006Z - info: [ui] [AppStore] removing account [username] ([name]) from store
2018-01-31T04:03:32.588Z - info: [ui] [AppStore] adding account [username] ([name]) to store
2018-01-31T04:05:10.378Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: [repo] - [username] (has token)
2018-01-31T04:05:11.988Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.564s)
2018-01-31T04:08:02.501Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: [repo] - [username] (has token)
2018-01-31T04:08:08.094Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 5.563s)
2018-01-31T04:11:02.099Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: [repo] - [username] (has token)
2018-01-31T04:11:07.551Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 5.419s)
2018-01-31T04:11:57.825Z - info: [ui] [AppStore] loading 11 repositories from store
2018-01-31T04:11:57.828Z - info: [ui] [AppStore] found account: [username] ([name])
2018-01-31T04:11:58.618Z - info: [ui] launching: 1.0.14-beta1 (Windows 10.0.16299)
2018-01-31T04:11:58.618Z - info: [ui] execPath: '[path]'
2018-01-31T04:19:13.635Z - info: [ui] [AppStore] loading 11 repositories from store
2018-01-31T04:19:13.641Z - info: [ui] [AppStore] found account: [username] ([name])
2018-01-31T04:19:14.406Z - info: [ui] launching: 1.0.14-beta1 (Windows 10.0.16299)
2018-01-31T04:19:14.407Z - info: [ui] execPath: '[path]'
2018-01-31T04:19:23.941Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.542s)
```

**Comment by shiftkey** [comment] 2018-01-31 05:05
@brandondube i don't see any errors in the log - as a starting point, can you share what errors you were seeing through the app?

Also, can you attach the output of this command in your repository:

```
git remote -vv
```

And as I mentioned over in https://github.com/desktop/desktop/issues/3802#issuecomment-358479365, introducing separate fetch and push remotes has side effects for things that Desktop relies on, particularly around tracking remote branches.

Can you tell me a bit more about your use case, and how using multiple remotes in this way makes your life easier?

**Comment by brandondube** [comment] 2018-01-31 05:16
Error in desktop:
![](https://i.imgur.com/yg0XKh1.jpg)

no error in the console, just: `Executing push: git -c credential.helper= push origin master:master --progress (took 3.748s)`
if I do git status on the cli after this error, there are no issues
```
git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

excerpt from .git/config:
```
[remote "origin"]
	url = https://github.com/[username]/[repo]git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = https://github.com/[username]/[repo].git
	pushurl = https://bitbucket.org/[username]/[repo].git
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

git remote
```
git remote -vv
origin  https://github.com/[username]/[repo].git (fetch)
origin  https://github.com/[username]/[repo].git (push)
origin  https://bitbucket.org/[username]/[repo].git (push)
```

The creds for both are stored in Windows and the CLI pushes, fetches, etc, without errors.

In terms of use case, I use github personally, but a research group I am sharing this code with uses bitbucket; all I need/want is to push updates there as I sync with remote.

**Comment by shiftkey** [comment] 2018-01-31 05:52
@brandondube thanks for the extra details:

> The creds for both are stored in Windows and the CLI pushes, fetches, etc, without errors.

Desktop implements it's own `GIT_ASKPASS` program (which is backed by the Windows credential store) rather than relying on your `credential.manager` configuration setting - my best guess as to what's triggering this error is that it doesn't handle authenticating against Bitbucket on push (or something in that vein), but I haven't had a chance to reproduce this just yet.

**Comment by brandondube** [comment] 2018-01-31 05:54
Is this because of platform differences?  Can GIT_ASKPASS not just wrap credential.manager on Windows?  That may be an elegant solution.

**Comment by shiftkey** [comment] 2018-02-01 04:28
> Can GIT_ASKPASS not just wrap credential.manager on Windows? That may be an elegant solution.

Not currently - Desktop requires certain scopes on it's access token, and something that might be valid in the Windows Credential Store might not have these scopes. So keeping it separate from your credential manager is still preferred.

We do support authenticating against GitHub and non-GitHub repositories, but maybe there's some corner case with setting multiple push URLs on a remote that we haven't tested with yet.

**Comment by shiftkey** [comment] 2018-07-03 21:05
Yeah, this is down to our `GIT_ASKPASS` implementation only supporting one host and credentials, and setting multiple `push` urls in a remote requires us to detect and pass this through our `GIT_ASKPASS` implementation which isn't currently supported.

I'm not sure how much interest there is in supporting this on Desktop, so this isn't a priority currently because it requires touching a fair bit of our existing authentication work because we've always assumed "one remote === one host".

**Comment by mversluys** [comment] 2018-07-25 17:46
The other place this seems to come up is when using a custom lfs.url with a repository. From the command line, git will use different credentials to authenticate against the lfs.url, but in github desktop it fails, presumably for the reasons stated here.

**Comment by steveward** [comment] 2024-10-25 18:23
I'm going to close this out and reference it in https://github.com/desktop/desktop/issues/11575, which is the same issue.

**Closed by steveward** 2024-10-25 18:23 UTC
Labels: bug, priority-3
