### ISSUE TITLE
Pin repository to top 

### ISSUE THREAD

**Issue by renetik** [desktop/desktop#14820] opened 2022-06-16 18:01 UTC
### The feature request

Just a simple Pin repository to top, as you have in web so I don't get lost and can have active projects on top in list

### Proposed solution

This **recent** is not really useful , could be replaced with pinned.

### Additional context

Do it man its super easy ;)

**Comment by steveward** [comment] 2022-06-16 18:55
Thanks for the issue @renetik. This is a duplicate of https://github.com/desktop/desktop/issues/8183, which currently isn't being worked on. Feel free to leave a 👍🏻 in that issue and follow along for any future updates.

**Closed as not planned by steveward** 2022-06-16 18:55 UTC

**Comment by renetik** [comment] 2022-06-17 04:19
You closed this issue and also now i see you closed many other requesting this ... so dont mark it as competed at last, thats confusing... its wont fix .. you reject this feature request from me and others.
