### ISSUE TITLE
Unable to open GitHub Desktop

### ISSUE THREAD

**Issue by gilzan** [desktop/desktop#3594] opened 2017-12-13 18:13 UTC
### Description

[When I open GitHub Desktop, the icon appears in taskbar, but when I click on it, the window doesn't appear. If I go in multitasking mode I can see a preview of the application, but cliking on it still doesn't work ]

### Version

**GitHub Desktop version:** [1.0.10]

**OS version:** [Microsoft Windows [Versione 10.0.16299.64]]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [when an I click on the GitHubDesktop.exe the window appears]

**Actual behavior:** [The icon appears on taskbar, but windows doesn't appear]

**Reproduces how often:** [always]

**Comment by iAmWillShepherd** [comment] 2017-12-13 18:16
Are you on a multi-monitor setup?

**Comment by gilzan** [comment] 2017-12-13 18:18
Yes I'm in multi-monitor. I also trying to dsconnect the other monitors, restart the laptop and re-open the app, but still doesn't work

**Comment by strafe** [comment] 2017-12-13 18:23
@gilzan [try this](https://github.com/desktop/desktop/issues/2107#issuecomment-333326358) to make the window appear.

**Comment by iAmWillShepherd** [comment] 2017-12-13 18:24
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/desktop/desktop/issues/2107. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2017-12-13 18:24 UTC
Labels: more-information-needed
