### ISSUE TITLE
Unable to commit in repo post upgrading to 3.3.1. Throws error related to ruleset 

### ISSUE THREAD

**Issue by akashgamdha** [desktop/desktop#17333] opened 2023-09-04 04:16 UTC
### The problem

I am unable to commit to my GitHub repo after I upgraded to 3.3.1 version of GitHub Desktop.
It keeps on saying "One or more rules apply to the branch <branch_name> that will pushing. Want to switch branches?"

However, my repo does not have any ruleset defined.

Also, it does not allow me to create new branch from GitHub Desktop anymore.

### Release version

3.3.1

### Operating system

Windows 10 Enterprise 22H2 19045.3324

### Screenshots

![image](https://github.com/desktop/desktop/assets/109716449/fb544eae-9c85-4545-a2c8-26d23f9d7aba)
![image](https://github.com/desktop/desktop/assets/109716449/1adf9f7d-2bd3-4e6f-87b2-817c29b81ec3)
![image](https://github.com/desktop/desktop/assets/109716449/2354a592-d58a-4f69-9bb7-4941ae61f633)

**Comment by sergiou87** [comment] 2023-09-04 05:51
@akashgamdha  Could you upload the log file from GitHub Desktop so that I could get some more information about this error? To access the log files go to the file menu in GitHub Desktop and select Help > Show Logs.
The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by akashgamdha** [comment] 2023-09-04 06:05
[2023-09-01.desktop.production.log](https://github.com/desktop/desktop/files/12509788/2023-09-01.desktop.production.log)
[2023-09-04.desktop.production.log](https://github.com/desktop/desktop/files/12509790/2023-09-04.desktop.production.log)
[2023-09-03.desktop.production.log](https://github.com/desktop/desktop/files/12509791/2023-09-03.desktop.production.log)
Here are the log files of last 3 days. The issue started occurring when my software version was updated to 3.3.0. Now, I have updated it to 3.3.1 but issue is still persistent.

**Comment by sergiou87** [comment] 2023-09-04 06:14
Thank you @akashgamdha ! Unfortunately I don't see anything relevant to this problem… Do you have any kind of branch protection setting enabled in that repo? I mean in `Settings` -> `Branches` in the web UI:

![2023-09-04 at 08 13](https://github.com/desktop/desktop/assets/1083228/52fe7dc5-20f3-45ed-9d53-60c8e9ca0548)

**Comment by akashgamdha** [comment] 2023-09-04 06:33
> Thank you @akashgamdha ! Unfortunately I don't see anything relevant to this problem… Do you have any kind of branch protection setting enabled in that repo? I mean in `Settings` -> `Branches` in the web UI:
> 
> ![2023-09-04 at 08 13](https://user-images.githubusercontent.com/1083228/265362105-52fe7dc5-20f3-45ed-9d53-60c8e9ca0548.png)

Unfortunately, I don't see Branches option in my settings menu (probably because I am not admin of the repo). However, the weird thing is that I am able to create new branches and push commits to existing branches using other methods like Git GUI or Git Bash. It throws the error only in GitHub desktop. It used to work in GitHub desktop as well till last Thursday. The error message "One or more rules apply to the branch <branch_name> that will pushing. Want to switch branches?" contains hyperlink in "One or more" text. Clicking on it opens up GitHub.com page where it says no ruleset have been added. In have attached that screenshot in my original comment.

**Comment by akashgamdha** [comment] 2023-09-04 06:40
Any idea where can I download 3.2.9 version? Can't find it on official site https://desktop.github.com/

**Comment by sergiou87** [comment] 2023-09-04 07:06
Here is 3.2.9:
- Windows: https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.9-a98d46c0/GitHubDesktopSetup-x64.exe
- macOS (Intel): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.9-a98d46c0/GitHubDesktop-x64.zip
- macOS (arm64): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.2.9-a98d46c0/GitHubDesktop-arm64.zip

**Comment by rchoubey1** [comment] 2023-09-05 10:58
unable to downgrade to 3.2.9 version , github desktop is automatically downloading new version again @sergiou87

**Comment by sergiou87** [comment] 2023-09-05 11:39
Unfortunately you cannot prevent autoupdating, unless you just never close the app 😥

We're unable to reproduce the issue. We will keep digging.

Sorry for any inconveniences and thanks for your patience.

**Comment by vaindil** [comment] 2023-09-05 18:59
We determined the cause of the bug, a fix should start rolling out soon. It's an API-side fix, not a Desktop app fix, so no app update will be required. I'll report back when it's resolved.

**Comment by vaindil** [comment] 2023-09-05 20:42
@akashgamdha @rchoubey1 This should now be resolved, you can just close/reopen GitHub Desktop and it should pick up the corrected API values, meaning you no longer see these errors. Could you let us know if the problem is fixed?

**Comment by akashgamdha** [comment] 2023-09-06 05:30
@vaindil Looks like the issue is fixed. I am not seeing any error while creating branch or committing changes to existing branch.

**Comment by steveward** [comment] 2023-09-07 17:10
I'm going to close this out since the issue is now fixed, thanks for your help @akashgamdha!

**Closed as completed by steveward** 2023-09-07 17:10 UTC
Labels: investigation-needed
