### ISSUE TITLE
No such file or directory, mkdtemp

### ISSUE THREAD

**Issue by oleteacher** [desktop/desktop#3072] opened 2017-10-16 19:19 UTC
Never had issue until updated to Version 1.0.4, now when trying to clone any repository desktop fails.

I updated to 1.0.4 by using the in software banner telling me update available, restart now (or something like that).

### Description

Get this error:

ENOENT: no such file or directory, mkdtemp 'C:\Users\oleteacher\AppData\Local\Temp;c:\ffmpeg\bin\GitHubDesktop-lfs-progress-XXXXXX'

### Version

**GitHub Desktop version:**1.0.4

**OS version:** Win 10 Pro

### Steps to Reproduce

1. Click "Open in Desktop"
2. Click "Clone"
3. Error produced

**Comment by iAmWillShepherd** [comment] 2017-10-16 19:36
Could you attach your log file please?

**Comment by oleteacher** [comment] 2017-10-16 19:55
Was looking for logs when reporting issue based on:

```
 - If you are on Windows, attach the most recent log file from:
   `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log
```
But there is no such directory nor any "*.desktop.production.log" that I can find. 

Perhaps the SquirrelSetup.log?

**Comment by iAmWillShepherd** [comment] 2017-10-16 21:16
If you go to the top menu and select `Help -> Show logs in explorer` that should take you to the log folder.

**Comment by shiftkey** [comment] 2017-10-16 21:16
This feels like #3046 and might be related to the environment variables.

@oleteacher could you open a ̦PowerShell prompt and run this command:

```
> Get-ChildItem Env:
```

I'm pretty sure Node is using `%TEMP%` when it creates this file, and on one of my test machines it looks like this:

```
PS C:\Users\shiftkey> Get-ChildItem Env:

Name                           Value
----                           -----
...
TEMP                           C:\Users\shiftkey\AppData\Local\Temp
TMP                            C:\Users\shiftkey\AppData\Local\Temp
...
```

**Comment by oleteacher** [comment] 2017-10-16 22:20
Sorry for delay guys, I am a teacher and close off school gets a bit crazy:)

Here are the logs (will run powershell prompt next):

```
2017-10-16T18:50:51.904Z - info: [ui] [AppStore] loading 163 repositories from store
2017-10-16T18:50:51.904Z - info: [ui] [AppStore] found account: oleteacher (Susan)
2017-10-16T18:50:54.694Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 2.921s)
2017-10-16T18:50:54.698Z - info: [ui] Executing getBranches: git for-each-ref --format=%(refname)%00%(refname:short)%00%(upstream:short)%00%(objectname)%00%(author)%00%(parent)%00%(subject)%00%(body)%00%1F refs/heads refs/remotes (took 2.842s)
2017-10-16T18:50:54.698Z - info: [ui] Executing getRecentBranches: git log -g --no-abbrev-commit --pretty=oneline HEAD -n 2500 -- (took 2.843s)
2017-10-16T18:50:55.397Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-16T18:50:56.568Z - info: [ui] Stats reported.
2017-10-16T18:50:56.774Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.564s)
2017-10-16T18:50:59.503Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T18:50:59.508Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T18:51:15.790Z - info: [ui] [AppStore] loading 163 repositories from store
2017-10-16T18:51:15.790Z - info: [ui] [AppStore] found account: oleteacher (Susan)
2017-10-16T18:51:16.382Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-16T18:51:19.346Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T18:51:19.353Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T18:51:58.940Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/psttt.git - oleteacher (has token)
2017-10-16T18:51:58.941Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/psttt.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/psttt.git"}
2017-10-16T19:08:17.174Z - info: [ui] [AppStore] loading 163 repositories from store
2017-10-16T19:08:17.174Z - info: [ui] [AppStore] found account: oleteacher (Susan)
2017-10-16T19:08:17.846Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
2017-10-16T19:08:21.516Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T19:08:21.520Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T19:58:04.252Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T19:58:04.254Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T19:58:41.490Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/desktop/desktop.git - oleteacher (has token)
2017-10-16T19:58:41.491Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/desktop/desktop.git - payload: {"name":"open-repository-from-url","url":"https://github.com/desktop/desktop.git"}
2017-10-16T19:58:50.586Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.379s)
2017-10-16T19:59:16.004Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T19:59:16.005Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T20:04:09.194Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/givanz/VvvebJs.git - oleteacher (has token)
2017-10-16T20:04:09.196Z - warn: [ui] Open Repository from URL failed, did not find repository: https://github.com/givanz/VvvebJs.git - payload: {"name":"open-repository-from-url","url":"https://github.com/givanz/VvvebJs.git"}
2017-10-16T22:18:14.249Z - info: [ui] [AppStore] loading 163 repositories from store
2017-10-16T22:18:14.249Z - info: [ui] [AppStore] found account: oleteacher (Susan)
2017-10-16T22:18:14.871Z - info: [ui] launching: 1.0.4 (Windows 10.0.15063)
```

**Comment by oleteacher** [comment] 2017-10-16 22:26
Running powershell I get:

```
TEMP    C:\Users\oleteacher\AppData\Local\Temp;c:\ffmpeg\bin
TMP      C:\Users\oleteacher\AppData\Local\Temp
```
Kind of strange about ffmeg but did not make any changes today other than update GitHub Desktop. Matter of fact only thing this computer has done today, been turned off until firing up for GitHub Desktop.

**Comment by shiftkey** [comment] 2017-10-16 22:29
@oleteacher this is the problem value:

```
TEMP    C:\Users\oleteacher\AppData\Local\Temp;c:\ffmpeg\bin
```

If you modify this environment variable to drop the `;c:\ffmpeg\bin` value, this will make the error go away.

**Comment by oleteacher** [comment] 2017-10-16 22:45
Thanks @shiftkey 

`TEMP    C:\Users\oleteacher\AppData\Local\Temp;c:\ffmpeg\bin` has been like that with all past releases of GitHub Desktop and just popped up today with update to 1.0.4. I am told that if I remove that, one of the video production software we use will cease to function.

My only choice if I have to remove something will be GitGub Desktop. Wish I made the rules but we are governed by a IT department. They are God, lol

**Comment by shiftkey** [comment] 2017-10-16 22:59
@oleteacher thanks for the extra context. 1.0.4 added some changes around how we track progress generated by Git LFS, and we do this by creating a temp file using the Node's `fs.mkdtemp` API. I'm tracking #3046 to make the error handling more resilient.

> I am told that if I remove that, one of the video production software we use will cease to function.

I worry this other tool is abusing specific environment variables, as they should be a single path value rather than an array of values.

From [MSDN](https://technet.microsoft.com/en-us/library/cc749104%28v=ws.10%29.aspx?f=255&MSPPError=-2147217396):

 - `TEMP` | The temporary folder on the computer. For Windows XP, a typical path is `%USERPROFILE%\Local Settings\Temp`. For Windows Vista, a typical path is `%USERPROFILE%\AppData\Local\Temp`.
 - `TMP` | The temporary folder on the computer. For Windows XP, a typical path is `%USERPROFILE%\Local Settings\Temp`. For Windows Vista,, a typical path is `%USERPROFILE%\AppData\Local\Temp`.

We can handle this error better, but we assume this environment variable is a path - there might be other unrelated issues because of this.

**Comment by oleteacher** [comment] 2017-10-16 23:06
@shiftkey 

> I worry this other tool is abusing specific environment variables,

That is a very good point. Seems strange to me, never seen ffmeg done like that. Will certainly pass your info on to IT people.

Just checked a classroom laptop that the kids use and it too has same issue as mine with 1.0.4. Maybe this will get the IT peoples attention:)

Thanks for your help.

**Comment by shiftkey** [comment] 2017-10-17 00:18
Duplicate of #3046

**Closed by shiftkey** 2017-10-17 00:18 UTC

**Comment by oleteacher** [comment] 2017-10-17 00:32
Sorry, I searched for "ENOENT:" before opening issue. Saw "watching" but did not know it was the same. Will refrain from opting new issues and leave it to the professionals.

Cheers

**Comment by j-f1** [comment] 2017-10-17 01:13
@oleteacher Don’t worry about opening a duplicate issue. It’s always good to hear about other ways an issue can be reproduced.

**Comment by oleteacher** [comment] 2017-10-17 15:30
@shiftkey  FYI: you were correct in your solution and advice. Little off topic, but thought you may like to know:

Seems a IT consultant made the changes `C:\Users\oleteacher\AppData\Local\Temp;c:\ffmpeg\bin` as a "quick fix" and now all computers (about 200 of them) have to be reconfigured, lol

Thanks to all for help.

**Comment by bernardumeh** [comment] 2017-11-20 12:25
Had a similar issue on my windows 10 installation. 

### ENOENT: no such file or directory, mkdtemp 'C:\Users\bumeh\AppData\Local\Temp;C:\ant\bin\GitHubDesktop-lfs-progress-XXXXXX' 

I realized i had those path set in my user variables. i removed the path specified  and re-installed Github desktop and that fixed mine.

**Comment by abSarpong** [comment] 2017-11-24 19:49
how do i remove the path set in my  user variable. can you please help me with a step by step solution @bernardumeh . thanks in advance

**Comment by shiftkey** [comment] 2018-04-05 23:08
@nightfury134 check that your `TEMP` or `TMP` environment variables are set to a single path - you might need to update your Environment Variables settings.
