### ISSUE TITLE
fetch origin button not responding after start

### ISSUE THREAD

**Issue by Justin-JHG** [desktop/desktop#9487] opened 2020-04-08 22:28 UTC
### Describe the bug

fetch origin button not responding after start

### Version & OS
windows 10 1903, desktop 2.4.0

### Steps to reproduce the behavior

1. Restart/Start Desktop
2. Click on 'Fetch Origin'

### Expected behavior

Desktop would start fetch changes from origin

### Actual behavior

Button click seems to have no affect, nothing happens. 

the button will work after switch repo and switch back.
it also works if you go to History tab first and then click the fetch button

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

[2020-04-08.desktop.production.log](https://github.com/desktop/desktop/files/4453246/2020-04-08.desktop.production.log)

**Comment by billygriffin** [comment] 2020-04-08 22:59
@Justin-JHG Thanks for the issue! Unfortunately I'm not able to reproduce this under a variety of scenarios. Would you mind filling out the remainder of the template to provide more information that might help us diagnose this? Is this happening across all your repos, or just a particular one? And if you could upload a log file, that would be helpful too. Thanks!

**Comment by Justin-JHG** [comment] 2020-04-08 23:26
> @Justin-JHG Thanks for the issue! Unfortunately I'm not able to reproduce this under a variety of scenarios. Would you mind filling out the remainder of the template to provide more information that might help us diagnose this? Is this happening across all your repos, or just a particular one? And if you could upload a log file, that would be helpful too. Thanks!

Hi @billygriffin it happens on every repo, I just checked the GitHub Desktop repo and it have the same issue as well, log attached. not sure whether only happens when there is no upcoming changes from origin? as when it display as 'Pull Origin' and it worked, it won't work if it is display as 'Fetch Origin' thanks

**Comment by tierninho** [comment] 2020-04-09 00:48
This error from your logs:

```
2020-04-08T23:05:12.276Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress development --` exited with an unexpected code: 1.
stdout:
Client/Forms/fOrders.dfm: needs merge
Client/Forms/fOrders.pas: needs merge
Client/GridReports/fGRChargeCodes.dfm: needs merge
Client/GridReports/fGRChargeCodes.pas: needs merge
Oracle/FMS/Scripts/alter_purchase_details_add_account_code.sql: needs merge
Oracle/FMS/Trigger/B4_INS_PURCHASE_DETAILS.trg: needs merge
Oracle/FMS/Trigger/B4_UPD_PURCHASE_DETAILS.trg: needs merge
stderr:
error: you need to resolve your current index first
```

seems to appear when there are merge conflicts that need to be resolved or a new branch was created with conflicting files. Do you have files in your Changes tab that need to be committed? Any chance there are extra steps you could share?  Thanks!

For reference, here is a list of similar issues: https://github.com/desktop/desktop/issues?q=is%3Aissue+%22you+need+to+resolve+your+current+index+first%22

**Comment by Justin-JHG** [comment] 2020-04-09 01:17
> This error from your logs:
> 
> ```
> 2020-04-08T23:05:12.276Z - error: [ui] `git -c credential.helper= -c protocol.version=2 checkout --progress development --` exited with an unexpected code: 1.
> stdout:
> Client/Forms/fOrders.dfm: needs merge
> Client/Forms/fOrders.pas: needs merge
> Client/GridReports/fGRChargeCodes.dfm: needs merge
> Client/GridReports/fGRChargeCodes.pas: needs merge
> Oracle/FMS/Scripts/alter_purchase_details_add_account_code.sql: needs merge
> Oracle/FMS/Trigger/B4_INS_PURCHASE_DETAILS.trg: needs merge
> Oracle/FMS/Trigger/B4_UPD_PURCHASE_DETAILS.trg: needs merge
> stderr:
> error: you need to resolve your current index first
> ```
> 
> seems to appear when there are merge conflicts that need to be resolved or a new branch was created with conflicting files. Do you have files in your Changes tab that need to be committed? Any chance there are extra steps you could share? Thanks!
> 
> For reference, here is a list of similar issues: https://github.com/desktop/desktop/issues?q=is%3Aissue+%22you+need+to+resolve+your+current+index+first%22

I have resolved conflict now, but don't think that's the issue causing this. I'm still getting the issue 

[2020-04-09.desktop.production.log](https://github.com/desktop/desktop/files/4453504/2020-04-09.desktop.production.log)

**Comment by tierninho** [comment] 2020-04-09 01:54
Thanks for the update. Unfortunately, the latest logs provided no clues. 

Does the fetch button work you after waiting a few minutes or isn't just plain broken for you? Can you tell us a little more about your steps? Is it reproducible with other repos? I assume you are trying to fetch the latest from the remote. Thanks for sharing.

**Comment by Justin-JHG** [comment] 2020-04-09 02:02
hi @tierninho 
those 2 steps are the ones I can reproduce on every repo. 
basically just start the app and click the button 

I just had another test and yes it works after 2 minutes 

Thank you.

**Comment by tierninho** [comment] 2020-04-09 19:31
So based on your details, I think it is safe to close this issue as the app is running normally. 

> the button will work after switch repo and switch back.
> I just had another test and yes the button works after 2 minutes waiting

Essentially we perform backgrounding fetching every 60 mins or when you switch repos. Also, background fetching should not occur more than once every two minutes. Both points seem to be inline with what you have experienced.

Here is the explanation on our fetching logic for reference: https://github.com/desktop/desktop/issues/4950#issuecomment-397694857 

Feel free to reach out if you have noticed anything else or the wonkiness persists.

**Closed by tierninho** 2020-04-09 19:31 UTC
Labels: more-info-needed
