### ISSUE TITLE
Copy context menu can be invoked outside of the diff

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#9738] opened 2020-05-08 18:25 UTC
I am able to use the right-click menu to invoke the `copy` option when I am outside of the diff. This results in an empty clipboard. 

We should restrain from showing the right-click menu when outside of the diff lines. This includes the line number area as it can be invoked there as well.

Copy menu shown in the white area where there is no text to copy:
![Screen Shot 2020-05-08 at 8 18 35 AM](https://user-images.githubusercontent.com/14828183/81436352-11570100-9105-11ea-849f-355f7c4c632d.png)

_v.2.4.4-beta4, OSX_

**Comment by steveward** [comment] 2024-04-05 17:26
I was unable to reproduce this behavior so it looks like this has been fixed. I'm going to close this out. ✨

**Closed by steveward** 2024-04-05 17:26 UTC
Labels: bug, priority-3
