### ISSUE TITLE
Can't restore Stashed change when repo include submodule

### ISSUE THREAD

**Issue by chuongmep** [desktop/desktop#14213] opened 2022-03-20 04:01 UTC
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

Probem cause when im using a sub module in repo
Can visit repo :  https://github.com/chuongmep/CadPythonShell
I think should have a warning remind use or alert for this.
### Release version

Version 2.9.11 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

- Step 1: Open Repo contains submodule
- Step 2 : Edit some thing code and stash change
- Step 3 : See Problem

### Screenshots

![image](https://user-images.githubusercontent.com/31106432/159147426-28cf1690-c643-42e3-96f0-93d42ecac6ec.png)

**Comment by steveward** [comment] 2022-03-21 17:05
Thanks for the issue @chuongmep. This looks like a duplicate of https://github.com/desktop/desktop/issues/11679.

See [my comment](https://github.com/desktop/desktop/issues/11679#issuecomment-824344726) for a workaround for this issue. I'm going to close this out.

**Closed as completed by steveward** 2022-03-21 17:05 UTC
