### ISSUE TITLE
Feature Request: Allow alias for repository names

### ISSUE THREAD

**Issue by subspacefield** [desktop/desktop#8593] opened 2019-11-06 14:47 UTC
I checkout different branches from the same repository into different folder names.  In the Current repository list there will be duplicates.  

I can hover over an item and the tooltip will show what folder is be used but it would be nice it I could create an alias for the repo name.  Or have an option to show the folder name along with the repo name.  It would help to quickly identify what is in the folder if I have multiple checkouts for the same repo.

![github](https://user-images.githubusercontent.com/6495599/68308166-034ef780-0072-11ea-8ef7-c0abc17848d5.png)
![github2](https://user-images.githubusercontent.com/6495599/68308177-0813ab80-0072-11ea-997d-2639767ba0cd.png)

**Comment by outofambit** [comment] 2019-11-07 23:12
Hi @subspacefield thanks for filing this issue. This sounds like a duplicate of https://github.com/desktop/desktop/issues/8175 and https://github.com/desktop/desktop/issues/8175, both which were included in https://github.com/desktop/desktop/issues/6460. See https://github.com/desktop/desktop/issues/8158#issuecomment-524644986 specifically for the current thinking on this. Thanks!

**Closed by outofambit** 2019-11-07 23:12 UTC
Labels: enhancement
