### ISSUE TITLE
Performance issues after last update 1.3.1.

### ISSUE THREAD

**Issue by rohillion** [desktop/desktop#5310] opened 2018-08-01 15:03 UTC
Hi guys!

Since the last update:
- 1.3.1 July 30th 2018

GiHub Client is somehow triggering a background process that is killing my machine performance:
- MacBook Pro Mid 2014
- 2.5 GHz Intel Core i7
- macOS High Sierra 10.13.6

The process triggers as soon as I open the client and then every 10 minutes aprox. I can see 15 or 20 instances of git running in parallel on the Activity Monitor and pretty much taking 90% of the CPU capacity, fan goes crazy for about 10 or 20 seconds then as soon as all git instances disappear, all goes back to normal. It looks like is a background process that triggers every X amount o minutes.

Hope this helps!

**Comment by shiftkey** [comment] 2018-08-01 15:13
@rohillion thanks for the report!

Could you attach the full log files? The **Help** | **Show Logs in Finder** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot what behaviour on your machine might be involved.

**Comment by checkdigits** [comment] 2018-08-01 15:17
I'm also seeing similar problems on Windows 10, on two different machines.  It appears to be due to trying to get the statuses of each bookmarked repo and place the "blue dot" next to them - which is a very handy feature BTW!

My log for one of my machines is attached.

[2018-08-01.desktop.production.log](https://github.com/desktop/desktop/files/2250045/2018-08-01.desktop.production.log)

**Comment by shiftkey** [comment] 2018-08-01 15:44
@checkdigits thanks for the details. At a high level I think I can spot the common factors:

> 2018-08-01T15:09:33.256Z - info: [ui] [AppStore] loading 106 repositories from store

It's very cool to see your using this many repositories in Desktop. We rolled out the improved repository indicators in 1.3.0 and I think we need to perform some queuing of the background work in these situations. I've also got #5241 in the works which I'll prioritize getting into a future update.

**Comment by shiftkey** [comment] 2018-08-01 16:13
@checkdigits @rohillion I'm going to prioritize #5311 for the next update to hopefully take this pain away, and then dig into how we can make this better for users who have 100+ repositories

**Comment by shiftkey** [comment] 2018-08-01 19:37
@checkdigits @rohillion I'm going to close this out because `1.3.2` addresses the performance regression and we're tracking making improvements to this in #5312 so we can enable it again for users working with dozens of repositories - please follow along with that issue while we make that area better!

**Closed by shiftkey** 2018-08-01 19:37 UTC

**Comment by checkdigits** [comment] 2018-08-01 19:58
Excellent - I really do *love* Desktop and you’re right, I do have a lot of active repos (and those are only my bookmarked ones!) so I thought I might be a bit of an edge case.

Thanks for jumping on this so quickly.

**Comment by rohillion** [comment] 2018-08-24 11:29
Thanks a million for this! It works great now =)
