### ISSUE TITLE
Disable auto updates 

### ISSUE THREAD

**Issue by heshangoonawardena** [desktop/desktop#19252] opened 2024-09-13 05:56 UTC
### The feature request

disable auto updates feature is missing in the GitHub desktop

### Proposed solution

Add a disable auto update feature

**Comment by tidy-dev** [comment] 2024-09-16 10:42
@heshangoonawardena Thank you for reaching out. This is a duplicate of https://github.com/desktop/desktop/issues/19252. Closing in favor of tracking there. Can show your support by thumbs up that issue.

**Closed as completed by tidy-dev** 2024-09-16 10:42 UTC
