### ISSUE TITLE
git reset --soft HEAD~1

### ISSUE THREAD

**Issue by nunoperalta** [desktop/desktop#9005] opened 2020-01-29 18:06 UTC
Sometimes, I accidentally commit into a Branch I don't have permission to.
This is because I need to create a new branch, switch to it, commit my changes there, and do a pull request.

When this accident happens, I always have to Google how to undo a commit: `git reset --soft HEAD~1`
Because, when I use the "Revert this commit" option, GitHub Desktop does not keep the changes staged and automatically creates an extra commit.

The "Undo" button has already disappeared, and when that happens, I have absolutely no way to do this through GitHub Desktop. I have to use the command line instead.

--

My suggestion is to split the option "Revert this commit" into two:

* Revert this commit
* Undo this commit

The "Undo this commit" can be available only to the last commit, and only if it hasn't been pushed to origin yet. (if that makes sense?)

--

Context images below:

<img alt="" width="485" src="https://user-images.githubusercontent.com/359239/55236470-c6cf3980-520e-11e9-8e04-16ffc326de72.png">

<img alt="" width="457" src="https://user-images.githubusercontent.com/359239/55236639-2a596700-520f-11e9-943b-99cd721c08da.png">

**Comment by billygriffin** [comment] 2020-01-29 21:17
Hi @nunoperalta, thanks for the issue! We actually just released GitHub Desktop 2.3 today with a feature that will hopefully alleviate your problems with committing to branches that you don't have permissions to push: https://github.blog/2020-01-29-github-desktop-2-3-removes-obstacles-to-help-you-be-more-productive/

More generally, it's likely helpful to understand how "Undo" works in GitHub Desktop. It's only available for the most recent commit, and also available only for commits that have not yet been pushed to GitHub.com (because undoing them after the fact would require rewriting history and force pushing, which we're hesitant to support because it can cause some not so awesome side effects for teams of developers).

Because I'm hopeful that our latest release should help to alleviate the root cause of the issue, I'm going to close this. Thanks!

**Closed by billygriffin** 2020-01-29 21:17 UTC

**Comment by nunoperalta** [comment] 2020-01-30 09:45
Hello. I tried this today, with the new release, and it's definitely better now. I could Undo aftee attempting a push, and follow the proper workflow without having to leave the UI :)

**Comment by billygriffin** [comment] 2020-01-30 14:58
Hi @nunoperalta, thanks for following up! That is wonderful to hear! 🙌

**Comment by nunoperalta** [comment] 2020-01-30 16:02
@billygriffin - although I'm ok with the solution, it's strange that I do not get the same "protected" warning as described in the blog entry. I definitely have the version released yesterday (and a hotfix today).

I'm using Azure DevOps, and only when I attempt to Push, I get a huge error in a popup.
Thankfully, I can Undo the commit and switch to another branch, but I don't see the "protected" warning below the commit box.

Just saying, in case this could be some bug.

Thanks!

**Comment by billygriffin** [comment] 2020-01-30 16:29
@nunoperalta Ah! That makes a lot more sense, thank you for the additional information. Unfortunately the branch protection warning is only based on querying the GitHub API, so it will only work for GitHub repos. Apologies for the confusion.
