### ISSUE TITLE
Requirement bug: Organization uses GitHub enterprise, but I cannot access my Enterprise GitHub Account using specified option. 

### ISSUE THREAD

**Issue by hca-JosephSuvak** [desktop/desktop#14842] opened 2022-06-20 15:34 UTC
### The problem

I'm trying to maintain my GitHub Desktop to include my Personal GitHub AND my Enterprise GitHub accounts. However, I cannot access the GitHub account for my enterprise without logging out of my personal account and re-logging in. 

### Release version

Version 3.0.2

### Operating system

Windows 10 - Enterprise

### Steps to reproduce the behavior

1. Have an Enterprise Organization with github.com/org as their URL.
2. Create a User for your org.
3. Have an already Active User in GitHub Desktop
4. Try to utilize the GitHub enterprise login and you will not be able to do so, because it expects org.github.com

### Additional context

This is mega-annoying, because it seems to throw all my repos out of commission & I need to re-clone OR I get misidentified commits.  The only way around this issue is logging out of your personal account[which is an awful solution].

**Comment by niik** [comment] 2024-09-19 12:09
I'm pretty sure this is a duplicate of https://github.com/desktop/desktop/issues/3707, i.e. the ability to be signed into more than one GitHub.com account. Enterprise here is not referring to GitHub Enterprise Server but rather an enterprise managed user. Please let me know if I'm mistaken.

**Closed as completed by niik** 2024-09-19 12:09 UTC
Labels: enhancement, not-planned
