### ISSUE TITLE
Open a repository in Android Studio

### ISSUE THREAD

**Issue by paultallard** [desktop/desktop#14521] opened 2022-05-08 21:33 UTC
### The problem

I get an error when I try to open a repository in Android Studio.  Running on Windows 10, with Version 3.0.0 (x64) of GitHub Desktop I get "Error Launching Studio." "The environment Variable JAVA_HOME c:\Program Files\Android\Android Studio1\jre\bin\server\jvm.dll) does not point to a valid JVM installation.  I appear to be pointing at the correct version of Android Studio.  The location appears to be correct and the JVM  installation appears to be correct.  I have updated to the current 64 bit Java on my machine.  I have reinstalled and updated GitHub Desktop.  
What could be the issue?  32 bit Java?  64 bit Java?

### Release version

3.0.0 (x64)

### Operating system

Windows 10

### Steps to reproduce the behavior

Open a current repository
click on Open in Android Studio

**Comment by sergiou87** [comment] 2022-05-09 08:33
Thanks for your report @paultallard ! I'm gonna close this as duplicate of #14519 , for which I already submitted a PR with the fix in #14523 😄

**Closed as completed by sergiou87** 2022-05-09 08:33 UTC
