### ISSUE TITLE
Constantly using 400+% of CPU

### ISSUE THREAD

**Issue by ReagentX** [desktop/desktop#5789] opened 2018-09-30 21:20 UTC
## Description

* GitHub Desktop: 1.4.1

* Operating system: MacOS Mojave 10.14 (18A391)

## Steps to Reproduce

1. Open Github Desktop
### Expected Behavior

Program uses very little CPU
### Actual Behavior

Program consistently uses 400% or more CPU

### Logs

```2018-09-30T00:01:34.498Z - info: [ui] Background fetch for 17 repositories took 5.841sec
2018-09-30T00:16:34.405Z - info: [ui] Background fetch for 17 repositories took 5.781sec
2018-09-30T00:31:35.804Z - info: [ui] Background fetch for 17 repositories took 6.120sec
2018-09-30T00:46:35.181Z - info: [ui] Background fetch for 17 repositories took 5.947sec
2018-09-30T01:01:34.175Z - info: [ui] Background fetch for 17 repositories took 5.641sec
2018-09-30T01:16:34.617Z - info: [ui] Background fetch for 17 repositories took 6.113sec
2018-09-30T01:31:34.817Z - info: [ui] Background fetch for 17 repositories took 6.345sec
2018-09-30T01:32:07.104Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sixteenzero - ReagentX (has token)
2018-09-30T01:46:39.099Z - info: [ui] Background fetch for 17 repositories took 7.036sec
2018-09-30T02:01:34.883Z - info: [ui] Background fetch for 17 repositories took 5.803sec
2018-09-30T02:15:14.418Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sixteenzero - ReagentX (has token)
2018-09-30T02:15:21.862Z - info: [ui] Executing push: git -c credential.helper= push origin master:master --progress (took 7.434s)
2018-09-30T02:16:34.395Z - info: [ui] Background fetch for 17 repositories took 6.014sec
2018-09-30T02:31:41.757Z - info: [ui] Background fetch for 17 repositories took 7.413sec
2018-09-30T02:46:36.427Z - info: [ui] Background fetch for 17 repositories took 6.464sec
2018-09-30T03:01:37.304Z - info: [ui] Background fetch for 17 repositories took 6.616sec
2018-09-30T03:16:38.260Z - info: [ui] Background fetch for 17 repositories took 6.928sec
2018-09-30T03:31:38.466Z - info: [ui] Background fetch for 17 repositories took 5.739sec
2018-09-30T03:46:38.111Z - info: [ui] Background fetch for 17 repositories took 5.949sec
2018-09-30T04:01:39.000Z - info: [ui] Background fetch for 17 repositories took 5.975sec
2018-09-30T04:16:34.746Z - info: [ui] Background fetch for 17 repositories took 5.750sec
2018-09-30T04:31:36.104Z - info: [ui] Background fetch for 17 repositories took 6.762sec
2018-09-30T04:46:36.299Z - info: [ui] Background fetch for 17 repositories took 5.860sec
2018-09-30T05:01:36.346Z - info: [ui] Background fetch for 17 repositories took 6.060sec
2018-09-30T05:07:58.119Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sixteenzero - ReagentX (has token)
2018-09-30T05:12:43.912Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sixteenzero - ReagentX (has token)
2018-09-30T05:16:34.307Z - info: [ui] Background fetch for 17 repositories took 6.296sec
2018-09-30T05:31:34.621Z - info: [ui] Background fetch for 17 repositories took 6.641sec
2018-09-30T05:46:34.395Z - info: [ui] Background fetch for 17 repositories took 6.447sec
2018-09-30T06:01:34.158Z - info: [ui] Background fetch for 17 repositories took 6.239sec
2018-09-30T06:16:33.751Z - info: [ui] Background fetch for 17 repositories took 5.862sec
2018-09-30T06:31:35.004Z - info: [ui] Background fetch for 17 repositories took 6.331sec
2018-09-30T06:46:36.640Z - info: [ui] Background fetch for 17 repositories took 7.163sec
2018-09-30T16:04:43.348Z - info: [ui] Background fetch for 17 repositories took 5.992sec
2018-09-30T16:19:42.694Z - info: [ui] Background fetch for 17 repositories took 6.364sec
2018-09-30T16:34:46.656Z - info: [ui] Background fetch for 17 repositories took 6.190sec
2018-09-30T16:49:44.432Z - info: [ui] Background fetch for 17 repositories took 6.139sec
2018-09-30T17:04:42.420Z - info: [ui] Background fetch for 17 repositories took 5.983sec
2018-09-30T17:19:42.873Z - info: [ui] Background fetch for 17 repositories took 5.491sec
2018-09-30T17:34:42.780Z - info: [ui] Background fetch for 17 repositories took 6.983sec
2018-09-30T17:49:42.869Z - info: [ui] Background fetch for 17 repositories took 6.339sec
2018-09-30T18:04:43.896Z - info: [ui] Background fetch for 17 repositories took 5.772sec
2018-09-30T18:19:41.288Z - info: [ui] Background fetch for 17 repositories took 5.604sec
2018-09-30T18:34:39.987Z - info: [ui] Background fetch for 17 repositories took 5.816sec
2018-09-30T18:49:44.597Z - info: [ui] Background fetch for 17 repositories took 5.735sec
2018-09-30T19:04:42.356Z - info: [ui] Background fetch for 17 repositories took 5.875sec
2018-09-30T19:19:38.388Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pydemos - ReagentX (has token)
2018-09-30T19:19:43.796Z - info: [ui] Background fetch for 17 repositories took 7.345sec
2018-09-30T19:34:41.075Z - info: [ui] Background fetch for 17 repositories took 6.286sec
2018-09-30T19:49:44.730Z - info: [ui] Background fetch for 17 repositories took 5.484sec
2018-09-30T20:04:43.504Z - info: [ui] Background fetch for 17 repositories took 5.995sec
2018-09-30T20:19:41.892Z - info: [ui] Background fetch for 17 repositories took 5.549sec
2018-09-30T20:34:44.146Z - info: [ui] Background fetch for 17 repositories took 6.092sec
2018-09-30T20:49:40.228Z - info: [ui] Background fetch for 17 repositories took 6.336sec
2018-09-30T21:01:40.109Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: sixteenzero - ReagentX (has token)
2018-09-30T21:02:00.866Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pydemos - ReagentX (has token)
2018-09-30T21:02:27.568Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pydemos - ReagentX (has token)
2018-09-30T21:04:41.545Z - info: [ui] Background fetch for 17 repositories took 7.015sec
2018-09-30T21:14:35.498Z - info: [ui] [AppStore] loading 17 repositories from store
2018-09-30T21:14:35.498Z - info: [ui] [AppStore] found account: ReagentX (Christopher Sardegna)
2018-09-30T21:14:35.908Z - info: [ui] launching: 1.4.1 (Mac OS 10.14.0)
2018-09-30T21:14:35.908Z - info: [ui] execPath: '/Users/chris/Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper'
2018-09-30T21:16:43.550Z - info: [ui] Background fetch for 17 repositories took 6.666sec
```

**Comment by iAmWillShepherd** [comment] 2018-10-01 15:54
Thanks for taking the time to open an issue! 🙇 

Could you share some more info on the machine you're using to run Desktop?  
* Model
* CPU (include core count and thread count as well as 
* RAM
* Available storage

Judging by the logs, your CPU ramps up every 15 mins, is that the behavior you're observing?

**Comment by ReagentX** [comment] 2018-10-01 16:13
- 15” MacBook Pro Mid-2015
- 2.8GHz i7 (4980HQ), 4 cores, 8 threads
- 16GB DDR3
- 512GB SSD, ≈100GB free

It doesn’t ramp up, GitHub Desktop just stays at 400% CPU usage while it’s open.

**Comment by joaomlneto** [comment] 2018-10-04 08:43
@ReagentX I can't reproduce (GitHub Desktop 1.4.1, macOS Mojave 10.14, MBP mid-2015; w/ AMD graphics, 2.5GHz CPU).

Are you sure it's the CPU and you're not seeing increased fan spinning due to the discrete graphics after upgrading to Mojave?

**Comment by ReagentX** [comment] 2018-10-04 15:05
Yes, I am specifically monitoring CPU usage.

**Comment by ReagentX** [comment] 2018-10-28 07:53
The profile ended up being over 100mb, which is too big to attach here.

**Comment by shiftkey** [comment] 2018-10-31 18:52
@ReagentX thanks for the extra details. I'm not quite sure what's happening on your setup but I'll call out some interesting things that I've spotted:

The CPU usage of the main app is relatively low overall (the orange chart) but the FPS chart has lots of gaps (which suggests something is awry with painting the UI):

<img width="1276" src="https://user-images.githubusercontent.com/359239/47810911-30602000-dd23-11e8-973c-81e0098cbb91.png">

The frames list, which breaks down how long it took to draw each frame, shows some periods where it's above 30fps (so it's responsive) but then has some periods where it takes 30s - 90s (yep, seconds) to paint. I can't see anything interesting in the main process flame graphs to indicate something is stealing CPU time (for example, Git operations) but the only thing I can see is GPU activity.

<img width="1362" src="https://user-images.githubusercontent.com/359239/47811455-94371880-dd24-11e8-94c3-1e2c7c007f9f.png">

@ReagentX could you try setting the `GITHUB_DESKTOP_DISABLE_HARDWARE_ACCELERATION` environment variable to a value like `1` and launching Desktop fresh? I had an issue a while ago where some update changed the graphics card settings on my macOS, and I wonder if you're encountering something similar.

<img width="689"  src="https://user-images.githubusercontent.com/359239/47811613-ed06b100-dd24-11e8-9b5d-58facaae3ca4.png">

**Comment by ReagentX** [comment] 2018-11-23 04:32
Seeing as no other app on my Mac has issues with automatic graphics switching I would chalk that up to a bug in Github Desktop and not a bug in MacOS. However, on the latest public build of Desktop (1.5.0) I am unable to replicate the same CPU hogging behavior so I am going to close this issue.

**Comment by spindriftur** [comment] 2019-04-24 02:07
<img width="718" alt="Screen Shot 2019-04-21 at 6 10 16 PM" src="https://user-images.githubusercontent.com/26857602/56627526-2b19c900-6614-11e9-9928-b1999ca2c1e4.png">
I also have auto graphics switching this and git are always at 50%+ load

**Comment by hedgehog125** [comment] 2020-08-01 11:33
I've got this too on an iMac. It's been sitting at 300+% since I installed it :/

**Comment by diogomedeirostd** [comment] 2020-08-28 17:05
I also have this issue right now

**Comment by moss-elizabeth** [comment] 2020-09-11 15:18
I'm having the same issue as well.

**Comment by mrgoynes** [comment] 2020-09-19 16:19
I'm also having this issue.

**Comment by olatan** [comment] 2020-10-05 18:13
Also having this Issue. Brand new 27" iMac 2020 3,8ghz i7.

**Comment by duncanc19116256** [comment] 2020-10-19 00:25
same... send halp please! it's constantly at 500% +

**Comment by devonschmidt** [comment] 2020-10-24 01:34
Also, having this issue.

**Comment by dratushnyy** [comment] 2020-10-24 06:42
Also having this issue, however, the workaround from @shiftkey seems working

**Comment by jasonfutch** [comment] 2020-10-27 17:10
Same issue

**Comment by niklaskallina** [comment] 2020-10-27 17:48
same here

**Comment by lochyb** [comment] 2020-11-08 12:05
Same issue on a Macbook Air 2015 model.

**Comment by asiboe** [comment] 2020-12-17 01:06
Having the same issue, specifically the github desktop helper used over 400% CPU even after I quit the application
MacBook Pro Mid 2015 model, 2,5 GHz Intel Core i7, 16gb

**Comment by Darbjm** [comment] 2020-12-17 15:22
Same for me, just updated to Big Sur. MacBook Pro (Retina, 15-inch, Mid 2014), 2.2 GHz Quad-Core Intel Core i7, 16 GB

**Comment by zero0zero7** [comment] 2020-12-22 13:59
same here. Macbook Pro 2020, 16gb

**Comment by duaneking** [comment] 2021-02-04 17:57
Just had this app use up over my 400% of my Macs CPU, brand new install for hardware received and updated to the newest everything last night from a empty blank slate.  MacBook Pro 16-inch 2019, 16gb ram.

**Comment by Kim-Jong-Jonas** [comment] 2021-02-14 09:37
Same issue! GitHub Desktop (Renderer) kept on going even when I closed GitHub Desktop. Had to kill the prosess in Activity Monitor.

**Comment by xammah** [comment] 2021-02-18 20:42
Chiming in with the same issue, Macbook Pro 2019 8GB i5 running OSX 10.14.6

**Comment by captainbamb0o** [comment] 2021-02-27 08:45
same here. Over 400% of my MacBook Pro 2020 16GB i7

**Comment by MarshmallowFlame** [comment] 2021-03-23 09:41
Got this as well on MacBook Pro 16-inch 2019 running Big Sur. Over 500% :)

**Comment by steveward** [comment] 2021-12-15 18:12
From https://github.com/desktop/desktop/issues/13540:

>When the desktop app updater window pops up asking for credentials, if it goes unnoticed, it will spin up the CPU. I stepped away from my laptop running macOS Big Sur and when I came back the fans were going nuts. Checking activity monitor showed it was using 99.9% CPU.

**Comment by steveward** [comment] 2023-05-18 20:32
We have a few more current performance issues (https://github.com/desktop/desktop/issues/10625 which links this issue and https://github.com/desktop/desktop/issues/13586), so I'm going to close this out to help consolidate our issues tracker.

**Closed by steveward** 2023-05-18 20:32 UTC
Labels: investigation-needed, macOS, performance
