### ISSUE TITLE
Mismatch in Folder Name while adding submodules

### ISSUE THREAD

**Issue by scixor** [desktop/desktop#13170] opened 2021-10-24 19:01 UTC
### Describe the bug
It is a pretty minor bug I on a submoudle spree recently where I noticed that while adding large-ish submodule that the folder name had a copy of first char before it, at first I thought I wrote the folder name wrong in the command so I double checked command but it was fine. The screenshot is below.

![image](https://user-images.githubusercontent.com/27860105/138608331-4ce85729-8ca1-423e-8b7e-a318c16123f2.png)

when the cloning was done it recognised it alright when there was a change in gitmodules file

![image](https://user-images.githubusercontent.com/27860105/138608324-df9fb5e0-a5d4-47ce-9f0f-3f4d032ec853.png)

### Version & OS

Version 2.9.4 (x64)
Windows 10 Version 20H2

### Steps to reproduce the behavior
*I am not sure if it is reproducible in any other way, other than changing branches after adding a submodule or in between adding a submodule*
1. Add a git submodule which takes a bit of time 
2. Watch the app

### Expected behavior

I don't think that should happen, although it caused a mild `Did I write the folder name wrong` but nothing that big.

### Actual behavior

The folder name was wrong. I noticed this multiple times while adding a submodule as I was on submodule spree.

### Logs
https://gist.github.com/Sid911/70699030cdceb11ddb626ca164f27b6c#file-2021-10-24-desktop-production-L147-L248

**Comment by tidy-dev** [comment] 2021-10-27 12:23
Thanks for the report! This seems to be a duplicate of #4670. Thus I am going to close this one in favor of tracking it there.

**Closed as completed by tidy-dev** 2021-10-27 12:23 UTC
