### ISSUE TITLE
Files are marked as staged, even when they're not

### ISSUE THREAD

**Issue by adamalton** [desktop/desktop#14141] opened 2022-03-10 17:38 UTC
### Describe the bug
Each time you edit a file in a repository, GitHub desktop then shows that file as staged, even though `git status` lists the file as unstaged.

### Version & OS

Version 2.9.11 (x64)
macos 12.0.1

### Steps to reproduce the behavior

1. Open a repository in GitHub Desktop
2. Edit a file in that repository
3. Go back to GitHub Desktop to view the file status

### Expected behavior

The file should be shown in GitHub Desktop as modified, but not staged.

### Actual behavior

GitHub Desktop shows the file as modified and staged.

### Screenshots

https://youtu.be/2yWVDaE0lng

**Comment by niik** [comment] 2022-03-11 08:57
Hey @adamalton, thanks for reaching out. GitHub Desktop doesn't stage files into the index until just prior to you committing. The checkbox you're pointing to in the video is GitHub's "own version of staging" where we indicate that the file will be included in the next commit you make. I GitHub Desktop we assume that new files and changes are likely to be included in the next commit so we have them selected by default.

I hope that helps! I'm going to close this issue as it appears to be working as intended.

**Closed as completed by niik** 2022-03-11 08:57 UTC

**Comment by Salgat** [comment] 2025-02-26 17:04
@niik  Is there planned support to be able to manually stage changes (the git way)? This is an extremely useful feature, since it allows you to test and remove changes without affecting your staged changes and without having to commit the changes prior to introducing new changes.

**Comment by niik** [comment] 2025-02-27 07:41
@Salgat in short, no, there are no plans to change our approach. It's an intentional design decision and we believe that the current model is a great fit for the app. 

While it's almost always healthy to re-evaluate past decisions from time to time I will note that this behavior has been a core part of GitHub Desktop ever since its conception in [well over a decade ago](https://github.blog/news-insights/announcing-github-for-mac) and has been overwhelmingly well received.

I understand that's not the answer you were looking for but I wanted to give you a clear answer.

**Comment by mehul-jain1** [comment] 2025-04-29 06:46
> While it's almost always healthy to re-evaluate past decisions from time to time I will note that this behavior has been a core part of GitHub Desktop ever since its conception in [well over a decade ago](https://github.blog/news-insights/announcing-github-for-mac) and has been overwhelmingly well received.

@niik but I think staged and unstaged changes are much needed for developers as it is part of daily development workflow . VScode and source tree app has these so why not github desktop?

**Comment by adamalton** [comment] 2025-04-29 07:49
My personal view is that having the GitHub Desktop UI reflect the actual git status of your files would be a much better behaviour. Having your GUI showing a different state of reality to your terminal seems to be like the kind of idea someone would come up with as a prank, not a feature.

But perhaps GitHub Desktop is aimed at a different type of audience than me. If that's the decision and they're sticking with it, then fair enough.

This behaviour completely put me off the app though. I assumed it was a bug, and when I found out that it wasn't I was in disbelief. And then I put the app in the trash. I've been using Sublime Merge ever since, and it's great.

**Comment by mehul-jain1** [comment] 2025-04-30 10:38
@adamalton Yes on the similar lines i was using [source tree](https://www.sourcetreeapp.com/) and it was working great but lately the app started crashing on my system so I installed github desktop but this app sucks even more. Will try out sublime merge  . thanks.

**Comment by andrewaarestad** [comment] 2025-12-21 03:44
tried out github desktop today but this issue makes it a non-starter :(

the use case is clear - staging a file with changeset A, then making changeset B, allows you to see both diffs. not possible with GitHub Desktop.
