### ISSUE TITLE
Problem with commits when using multiple accounts.

### ISSUE THREAD

**Issue by Helderjfl** [desktop/desktop#9110] opened 2020-02-15 05:15 UTC
### Describe the bug 

I'm using Github Desktop on class to teach my students on how to use Git with a friendly interface. As many students use the same computer, we are facing a bug or behavior that, after a student sign off and another student sign on, Github Desktop does not automatically change the git user.name and user.email. So their commits get messed up because of that.
They could, of course change manually, but its inconvenient to do that on every class.

### Version & OS

Github Desktop 2.3
Windows 10 version 1909

### Steps to reproduce the behavior

1. Sign in with the first account, it'll register the user.name and user.email
2. Sign out.
3. Sign in with a different account.
4. Commit something.

### Expected behavior

To change the git user.name and user.email when the students change to accounts.

### Actual behavior

These data does not change, demanding it to be done manually or have the commit user wrong.

**Comment by tierninho** [comment] 2020-02-18 18:27
@Helderjfl thanks for sharing this. Is it possible to send us the logs from the day? See the Help menu in Desktop.

**Comment by outofambit** [comment] 2020-02-19 18:40
hi @Helderjfl thanks for sharing this. i think i know what the problem is here. during the initial onboarding, we ask the user to sign in to github and then configure their git username and email. as you've seen, signing in again by itself doesn't change the configured git username and email, nor does it prompt the user to. it's technically possible to change the app to facilitate that re-setting, but would take some engineering work.

what would your ideal flow look like? would the app prompt the user to change their git config in the app? or just do it for them automatically? i think doing it for them might be error-prone for some users.

also, when you say "change it manually", do you mean with the settings dialog?
<img width="628" alt="Screen Shot 2020-02-19 at 1 32 36 PM" src="https://user-images.githubusercontent.com/964912/74863730-5fd1dc00-531c-11ea-88d1-16e1133df7d6.png">

or via the git cli?

**Comment by Helderjfl** [comment] 2020-02-21 20:01
> hi @Helderjfl thanks for sharing this. i think i know what the problem is here. during the initial onboarding, we ask the user to sign in to github and then configure their git username and email. as you've seen, signing in again by itself doesn't change the configured git username and email, nor does it prompt the user to. it's technically possible to change the app to facilitate that re-setting, but would take some engineering work.
> 
> what would your ideal flow look like? would the app prompt the user to change their git config in the app? or just do it for them automatically? i think doing it for them might be error-prone for some users.
> 
> also, when you say "change it manually", do you mean with the settings dialog?
> <img alt="Screen Shot 2020-02-19 at 1 32 36 PM" width="628" src="https://user-images.githubusercontent.com/964912/74863730-5fd1dc00-531c-11ea-88d1-16e1133df7d6.png">
> 
> or via the git cli?

That's right, I told them to use the settings dialog to change the git information.
As they're high school students, the interface doing it for them would be better, but the interface at least telling them to change would be a great improvement.

**Comment by Helderjfl** [comment] 2020-02-21 20:02
> @Helderjfl thanks for sharing this. Is it possible to send us the logs from the day? See the Help menu in Desktop.

I'll try to get a log from one of the computers. I'm facing 2 problems, thats one of it, the other one may be related, as its also about the git information, but I don't know yet how to reproduce it.

**Comment by Helderjfl** [comment] 2020-03-06 21:46
So I uploaded every log of one of the computers. The last log show one of the problems that we are having with git config. For some reason it doesn't recognize the user.name and user.email configured on github, so the student have to close and open Github Desktop to work again.

[2020-01-15.desktop.production.log](https://github.com/desktop/desktop/files/4300550/2020-01-15.desktop.production.log)
[2020-02-11.desktop.production.log](https://github.com/desktop/desktop/files/4300551/2020-02-11.desktop.production.log)
[2020-02-13.desktop.production.log](https://github.com/desktop/desktop/files/4300552/2020-02-13.desktop.production.log)
[2020-02-14.desktop.production.log](https://github.com/desktop/desktop/files/4300553/2020-02-14.desktop.production.log)
[2020-02-17.desktop.production.log](https://github.com/desktop/desktop/files/4300554/2020-02-17.desktop.production.log)
[2020-02-20.desktop.production.log](https://github.com/desktop/desktop/files/4300555/2020-02-20.desktop.production.log)
[2020-02-21.desktop.production.log](https://github.com/desktop/desktop/files/4300556/2020-02-21.desktop.production.log)
[2020-02-27.desktop.production.log](https://github.com/desktop/desktop/files/4300557/2020-02-27.desktop.production.log)
[2020-02-28.desktop.production.log](https://github.com/desktop/desktop/files/4300558/2020-02-28.desktop.production.log)
[2020-03-02.desktop.production.log](https://github.com/desktop/desktop/files/4300559/2020-03-02.desktop.production.log)
[2020-03-03.desktop.production.log](https://github.com/desktop/desktop/files/4300560/2020-03-03.desktop.production.log)
[2020-03-05.desktop.production.log](https://github.com/desktop/desktop/files/4300561/2020-03-05.desktop.production.log)
[2020-03-06.desktop.production.log](https://github.com/desktop/desktop/files/4300562/2020-03-06.desktop.production.log)

**Comment by niik** [comment] 2020-10-20 14:39
Hi @Helderjfl, thanks for opening this! Suggesting a change or alerting the user that the commit author information isn't matching their currently signed in account is an area that we're looking at in https://github.com/desktop/desktop/issues/610 but for now, when you log in with different GitHub accounts you need to make sure you update the email address in Options/Preferences so that it matches an email address used with your currently logged in account.

![image](https://user-images.githubusercontent.com/634063/93764250-12e81800-fc13-11ea-90a4-42b45f7c9b00.png)

I'm going to close this in favor of #610 which we'er using as an overall tracking issue for problems related to mismatch between account and commit author information.

**Closed by niik** 2020-10-20 14:39 UTC
Labels: enhancement, more-info-needed
