### ISSUE TITLE
Can't find 'repo-xxx'

### ISSUE THREAD

**Issue by wlchn** [desktop/desktop#15533] opened 2022-10-27 02:02 UTC
### The problem

All Repos promot that 【Can't find 'repo-xxx'】 after restart my Mac.  I'm sure the repo path is no problem. Clicked the【Check Again】is No response.

I have encountered this error several times after restart.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/4652410/198172750-660e901a-cda2-4056-a596-0bd81956e90e.png">

### Release version

Version 3.1.2 (x64)

### Operating system

Darwin x64 21.6.0

**Comment by steveward** [comment] 2022-10-27 15:03
@wlchn thanks for the issue. Unfortunately this sounds like a corrupt database -- did GitHub Desktop update when this happened? We are tracking this in https://github.com/desktop/desktop/issues/9954. 

If the issue is continuing to occur I would try resetting GitHub Desktop:

1. Close GitHub Desktop
2. Delete all of the files under `~/Library/Application Support/GitHub Desktop/`
3. Restart GitHub Desktop

I'm going to close this out since we are tracking this issue, but let me know if you continue to have problems.

**Closed as completed by steveward** 2022-10-27 15:03 UTC
