### ISSUE TITLE
Add the option to remove recent repository category 

### ISSUE THREAD

**Issue by Josh65-2201** [desktop/desktop#12633] opened 2021-07-16 00:14 UTC
### Describe the feature or problem you’d like to solve
In the categories list at the top it always has 3 most recent repository that I don't want to see since it just takes up space.

### Proposed solution
Add an option in appearance settings.

**Comment by steveward** [comment] 2021-07-20 17:48
Thanks for the issue @josh-65! Closing as a duplicate of https://github.com/desktop/desktop/issues/11598.

**Closed as completed by steveward** 2021-07-20 17:48 UTC
