### ISSUE TITLE
Add UI for git blame

### ISSUE THREAD

**Issue by alexchandel** [desktop/desktop#9580] opened 2020-04-20 20:55 UTC
### Describe the feature or problem you’d like to solve

* `git blame` is an extremely useful git function.  GitHub even has a dedicated UI for it (the `Blame` button, next to the `History` button).
* GitHub Desktop should add a UI for `git blame` (perhaps accessible via a context menu option on a file listed in the `History` view).

### Proposed solution

GitHub Desktop users would have a UI displaying `git blame` information on any file, with GUI syntax highlighting and with more readable, linked author/commit information, within the same git GUI they're accustomed to seeing commit diffs.

GitHub Desktop already has a `History` view that displays differences with syntax highlighting similarly to GitHub (except in 1 column instead of 2), with which Blame would integrate naturally.  And `git blame` output is suited for 1-column display, just like GitHub Desktop currently displays diffs.

**Comment by tierninho** [comment] 2020-04-20 21:17
@alexchandel Thanks for filing this and offering a proposed solution. This is a duplicate of https://github.com/desktop/desktop/issues/2310 so please follow along there. Note, it is closed for now, but that doesn't mean we won't reopen it one day. Your feedback is important and valued and will help us determine the roadmap going forward.

**Closed by tierninho** 2020-04-20 21:17 UTC

**Comment by BorisMolch** [comment] 2024-04-15 11:53
is this possible ?
