### ISSUE TITLE
GitHub failed Desktop to lanch and not able to open command prompt 

### ISSUE THREAD

**Issue by Venkataramana2017** [desktop/desktop#4006] opened 2018-02-14 07:19 UTC
error 
======================================
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.13
OS: Windows 6.1.7601

====================
2nd issue 

Github desktop not able to sync/clone to my local and master repository 
 unable to open command line for the same   
Please summarize the issue in the title, and then use the template below to
fill out the details so we can reproduce the issue on our end.

### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by shiftkey** [comment] 2018-02-14 07:36
@Venkataramana2017 Thanks for reaching out!

We require the template to be filled out on all new issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Venkataramana2017** [comment] 2018-02-15 07:57
Hi I am unable to open the command prompt -- the following error 
===============
Please find the attached error file 
Error: spawn where ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 1.0.13
OS: Windows 6.1.7601

**Comment by Venkataramana2017** [comment] 2018-02-15 08:51
@shiftkey 
![github](https://user-images.githubusercontent.com/34304071/36247867-862b78ce-125b-11e8-861b-6e4354349834.PNG)

**Comment by shiftkey** [comment] 2018-02-16 00:43
@Venkataramana2017 thanks for the details - this is a duplicate of #3825 and I think we've isolated this down to `C:\Windows\System32` not being on your `PATH`.

The current [beta version](https://github.com/desktop/desktop#beta-channel) has better error handling at this, but please follow along with #3825 for the full resolution.

**Closed by shiftkey** 2018-02-16 00:43 UTC
Labels: more-information-needed
