### ISSUE TITLE
please solve this

### ISSUE THREAD

**Issue by mudassarahnmad** [desktop/desktop#9953] opened 2020-06-07 13:41 UTC
error: cannot spawn C:\Usersr\AppData\Local\GitHubDesktop\app-2.5.0\resources\app\static\ask-pass-trampoline.bat: No error
fatal: could not read Username for 'https://github.com': terminal prompts disabled

**Comment by rafeca** [comment] 2020-06-08 08:51
Hi @mudassarahnmad ! Sorry for the problem. This is a known issue on GitHub Desktop that can be caused by many things related to your Windows configuration.

Can you please take a look at the guide we have to fix this problem in the [known issues document](https://github.com/desktop/desktop/blob/development/docs/known-issues.md#ask-pass-trampolinebat-errors---2623-4124-6882-6789)?

I'm going to close this issue, but please reopen it if none of the solutions in that document solve your problem.

**Closed by rafeca** 2020-06-08 08:51 UTC
