### ISSUE TITLE
React highlight issue

### ISSUE THREAD

**Issue by danqing** [desktop/desktop#7396] opened 2019-04-25 16:14 UTC
Not a big deal, but the highlight is broken for React (probably due to backtick). Using latest stable on macOS.

![Screen Shot 2019-04-26 at 12 12 24 AM](https://user-images.githubusercontent.com/5134133/56751240-2aba3300-67b8-11e9-9f7d-c717dfad40fc.png)

**Comment by niik** [comment] 2019-04-25 16:43
Hi @danqing, thanks so much for opening this and letting us know.

I believe this is the same problem as that reported in https://github.com/desktop/desktop/issues/6908. An upgrade of CodeMirror was contributed in https://github.com/desktop/desktop/pull/6918 and it is believed that the issue will be solved by that.

The CodeMirror upgrade hasn't yet made it to the production channel but it will in the next production release. If you're feeling adventurous you can install our [beta channel](https://github.com/desktop/desktop#beta-channel) which contains the upgraded CodeMirror schemes.

Given that I believe this to be a duplicate of #6908 (please let me know if I'm mistaken) and given that I believe this will be fixed in the next production release. I'm going to close this

**Closed by niik** 2019-04-25 16:43 UTC
