### ISSUE TITLE
Unchanged files get staged when switching branches

### ISSUE THREAD

**Issue by chrisbecke** [desktop/desktop#7071] opened 2019-03-12 10:16 UTC
## Description

When I switch between branches using GitHub Desktop on my Mac, sometimes the files that the branch change causes to get added / changed on disk become 'staged'.

I need to perform a "Discard All" in GHD or `git reset` from the CLI to continue without comitting files that I havn't changes.

## Version

* GitHub Desktop: Version 1.6.2

* Operating system: macOS Mojave 10.14.3

## Steps to Reproduce

With a clean `git status`, from the "Current Branch" dropdown, simply switch branches a few times.

### Expected Behavior

"Changes" to remain empty. `git status` to report no changes.

### Actual Behavior

"Changes" fills with changed files: Typically the files that were changed between the original and new branch.

## Additional Information

This is an example of what `git status` shows after a switch

```
chris@chrismac:~/Projects/Site$ git status
On branch 19-experimental-no-cache-file-endpoint
Your branch is up to date with 'origin/19-experimental-no-cache-file-endpoint'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   DeploySiteData/DeploySiteData.csproj
	deleted:    Project.Library.s3/Project.Library.s3.csproj
	deleted:    Project.Library.s3/Signers/AWS4SignerBase.cs
	deleted:    Project.Library.s3/Signers/AWS4SignerForAuthorizationHeader.cs
	deleted:    Project.Library.s3/Signers/AWS4SignerForChunkedUpload.cs
	deleted:    Project.Library.s3/Signers/AWS4SignerForPOST.cs
	deleted:    Project.Library.s3/Signers/AWS4SignerForQueryParameterAuth.cs
	modified:   Project.WebSite.Client/ClientApp/package.json
	modified:   Project.WebSite.Client/ClientApp/src/components/auth/OktaSignInWidget.js
	modified:   Project.WebSite.Client/Project.WebSite.Client.csproj
	modified:   Project.WebSite.Client/appsettings.json
	modified:   Project.WebSite.SiteAPI/Controllers/FileController.cs
	deleted:    Project.WebSite.SiteAPI/Controllers/XFilesController.cs
	modified:   Project.WebSite.SiteAPI/Project.WebSite.WebAPI.csproj
	modified:   Project.WebSite.sln

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   DeploySiteData/DeploySiteData.csproj
	modified:   Project.WebSite.Client/ClientApp/package.json
	modified:   Project.WebSite.Client/ClientApp/src/components/auth/OktaSignInWidget.js
	modified:   Project.WebSite.Client/Project.WebSite.Client.csproj
	modified:   Project.WebSite.Client/appsettings.json
	modified:   Project.WebSite.SiteAPI/Controllers/FileController.cs
	modified:   Project.WebSite.SiteAPI/Project.WebSite.WebAPI.csproj
	modified:   Project.WebSite.sln
	deleted:    Scripts/sync-studios-to-servicedesk.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Project.Library.s3/Project.Library.s3.csproj
	Project.Library.s3/Signers/
	Project.WebSite.SiteAPI/Controllers/XFilesController.cs
```

### Logs

[2019-03-12.desktop.production.log](https://github.com/desktop/desktop/files/2956249/2019-03-12.desktop.production.log)

**Comment by billygriffin** [comment] 2019-03-12 15:21
Hi @chrisbecke, I'm not sure I understand the repro steps. When you say "with a clean `git status`" do you mean that there are no uncommitted changes to files at all or new files? Are you saying that files suddenly appear in the list that didn't appear previously? Any chance you'd mind adding a couple screenshots to help me understand this a bit better?

**Comment by chrisbecke** [comment] 2019-03-12 19:17
I simply mean that the repo initially shows no changed files. `git status` shows no changes and GitHub Desktop's Changes list is also empty.
Then, if I change Branches a few times using GitHub Desktop suddenly a whole lot of changes show up.

**Comment by chrisbecke** [comment] 2019-03-14 10:36
In an attempt to pin this issue down a bit more I tried to switch branches from the cli to see if changing branches rapidly would cause it.

Experiment #1 - changed branches about 10 times rapidly using `git branch <branch>` from terminal. Set focus to GitHub Desktop at the end, and no files had been invalidly staged.

"hmmm. Perhaps GHD stages files when it gets focus and scans the new branches?"

Experiment #2 - rapidly switch branches - again about 10 times - giving focus to GHD each time to ensure it notices and updates the active branch.
Result: no files end up staged. 

"Ok. Maybe its when i swtich branches rapidly in GHD."

Experiment #3 - switch branches rapidly in GHD - which previously was causing files to stage for no reason.
Result: after 30 attempts no files are staged.
--
So I don't know whats up. This problem has been plaguing me for a few months, it's just recently I figured out that switching branches in GHD was triggering it.

But now, that I report it, it goes away. I'm going to close this ticket until I get it to recur properly.

**Comment by johnstricklin** [comment] 2019-05-21 16:06
It happened to me today too.

**Comment by chrisbecke** [comment] 2019-05-22 05:28
I wish I could figure out some reliable steps to reproduce this. But it is definitely happening to me again.
I suspect it's an interaction with McAfee or some such IT installed agent locking files and causing a race condition when Github Desktop does a branch switch that causes the file watcher to invalidly stage unchanged files. I presume thats how GHD works that is...

**Comment by mido1966** [comment] 2019-05-22 15:20
Pls No Email mor pls Tank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: chrisbecke <notifications@github.com>
Datum: 22.05.19 07:29 (GMT+01:00)
An: desktop/desktop <desktop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [desktop/desktop] Unchanged files get staged when switching branches (#7071)


I wish I could figure out some reliable steps to reproduce this. But it is definitely happening to me again.
I suspect it's an interaction with McAfee or some such IT installed agent locking files and causing a race condition when Github Desktop does a branch switch that causes the file watcher to invalidly stage unchanged files. I presume thats how GHD works that is...

**Comment by tierninho** [comment] 2019-06-04 00:22
Closing this issue for now as the steps needed to reproduce are not clear at this point and we have had no reports of this as well. Happy to reopen if new info surfaces. Thanks!

**Closed by tierninho** 2019-06-04 00:22 UTC
Labels: more-information-needed

**Comment by dragosidle** [comment] 2021-01-03 12:10
Hi! 2 years later.
@chrisbecke , I encountered the same issue today but in my case it is happening because of sass which is precompiling the css file everytime I am switching branches. Cancelling the watch state of sass from the console made this behaviour stop.
