### ISSUE TITLE
low: moving repos back in place still shows error screen

### ISSUE THREAD

**Issue by ewerybody** [desktop/desktop#4546] opened 2018-04-27 15:47 UTC
## Description
Just like described in  #4253 an error screen appears when a repository is missing:

![](https://user-images.githubusercontent.com/49612/37480450-2e5400bc-2877-11e8-994a-9a4f700f2008.png)

Now, If you move it **back to its place**: The screen **still apears**!
Quitting and restarting the app doesn't help.
The screen shows the **exact** location where the repository was put back to!
The only thing you can do is: use the <kbd>Locate...</kbd>-button. Which also suggests the right directory already.

## Version
* GitHub Desktop: 1.1.1
* Operating system: Microsoft Windows [Version 10.0.16299.371]

## Steps to Reproduce
1. rename a repo directory
2. restart Github Desktop, see the screen
3. close Github Desktop
4. rename back to original name
5. restart Github Desktop: Still see the screen

### Expected Behavior
* you move the repo back in place: the repo automatically loads
* there is a reload button
* its loads as usual when restarting

### Actual Behavior
* the ui doesn't check for the repo being back in place
* there is no reload button or option
* when restarting Github Desktop the repo still seems missing!

## Additional Information
I know this sounds picky: You can just use the <kbd>Locate...</kbd>-button.
But it seems kinda weird that the app is somehow saving the state of a repo once being missing.
Whats the use of that?

**Comment by iAmWillShepherd** [comment] 2018-04-28 02:32
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #4264. Please follow that issue
for further updates.

**Closed by iAmWillShepherd** 2018-04-28 02:32 UTC
