### ISSUE TITLE
New Branch in detached HEAD doesn't check out new branch

### ISSUE THREAD

**Issue by mdiep** [desktop/desktop#9530] opened 2020-04-15 18:01 UTC
### Describe the bug

Creating a new branch from a detached HEAD creates the new branch, but doesn't check it out.

### Version & OS

Version 2.4.1
macOS

### Steps to reproduce the behavior

1. `git checkout --detach`
2. Go to GitHub Desktop
3. Cmd-Shift-N to create a new branch
4. Enter branch name and hit _Create Branch_

### Expected behavior

A new branch should be created and you should be on it.

### Actual behavior

A new branch is created, but you're left with a detached HEAD.

**Comment by tierninho** [comment] 2020-04-16 00:38
@mdiep Thank you for the issue. Hope this isn't causing you too much pain.

I attempted to reproduce the issue, but I ended up with the expected behavior.

Here is what I am seeing after following your steps:
![Screen Shot 2020-04-15 at 2 35 23 PM](https://user-images.githubusercontent.com/14828183/79402052-8419f580-7f26-11ea-9e27-b6dca36af42e.png)
![Screen Shot 2020-04-15 at 2 35 00 PM](https://user-images.githubusercontent.com/14828183/79402049-82503200-7f26-11ea-9b58-5dbeb8712f02.png)

Any chance you could send over your logs for us to take a peek? They can be located under the Help menu in Desktop. Thanks again.

**Comment by tierninho** [comment] 2020-04-16 01:07
So I can now reproduce this by allowing a file to remain in the Changes tab. Then when I add the new branch, I spotted an underlying error in the command line as a result of not stashing the changes. Since nothing was present in the UI or console, there is no way for you to know. Did you happen to have an uncommitted file?

If you are able to get back into the state, if you run `git status` on the detached HEAD, you should see something like this in the command line:

```
➜  detachedA git:(11c7849) ✗ git status
HEAD detached at 11c7849
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .gitignore

no changes added to commit (use "git add" and/or "git commit -a")
```

@outofambit I think this may be a bug, is there anything we can do to address this? Perhaps a warning dialogue could be surfaced?

@mdiep good catch finding this!

**Comment by mdiep** [comment] 2020-04-16 15:36
I hit this routinely (I often keep a checkout with a detached head due to other reasons). Usually by the time I go to create a branch, I have a file with changes.

**Comment by tierninho** [comment] 2020-05-21 01:24
Sorry that this keeps happening @mdiep 😞 

We hope others who run into this can add a comment below so we can get a better signal into how  often this is occurring. 

Thank you for using Desktop!

**Comment by niik** [comment] 2022-01-18 08:55
Stumbled upon this today (:wave: @mdiep). And I'm unable to reproduce it even with changes in the working directory. I'm guessing this got solved somewhere along the way. If you're still able to reproduce please let us know and we'll reopen, until then I'm going to close this out.

**Closed by niik** 2022-01-18 08:55 UTC
Labels: bug, priority-3

**Comment by mdiep** [comment] 2022-01-24 12:17
Yeah, this has been working for a while. Didn't realize the issue was still open. (👋🏻 @niik)
