### ISSUE TITLE
"Updating" spinner is blurry

### ISSUE THREAD

**Issue by gingerbeardman** [desktop/desktop#4875] opened 2018-06-05 16:30 UTC
## Description

"Updating" spinner is blurry

## Version

* GitHub Desktop: 1.2.2

* Operating system: macOS 10.13.4

* Computer: MacBook Pro (Retina, 13-inch, Early 2013)
* Monitor: Apple Cinema HD Display (1920 x 1200)

## Steps to Reproduce
About > Check for Updates

### Expected Behavior

Spinner should be sharp

### Actual Behavior

Spinner is very blurry

(I have not checked Retina mode)

## Additional Information

![screen shot 2018-06-05 at 17 18 22](https://user-images.githubusercontent.com/49612/40989543-06ec1a96-68e6-11e8-9442-f5e72dff34cf.png)

**Comment by niik** [comment] 2018-06-07 05:03
I can't reproduce this on a retina monitor (or at least it's not immediately obvious there) but I see it on a non-retina monitor. It seems Chrome converts the SVG into a bitmap in order to speed up rendering. If I leave the spinner be for a while or hover over it it snaps back into a crisp rendering again. Same thing happens if I try to locate the element in devtools.

I don't have a good idea of how to work around it so I'll open this up for suggestions from anyone who's spent more time wrangling Chrome's rendering internals than I have. I'm not too concerned about this particular instance but if there's an easy, low-risk workaround I think we'd be happy to look at it.

**Comment by gingerbeardman** [comment] 2018-06-07 11:49
It's all about the details, you know? Little things like this add up and it looks... untidy, lazy, unprofessional IMHO.

I'll try to put together reduced test case that will make hacking on this easier.

**Comment by Koklin** [comment] 2018-06-07 12:40
@gingerbeardman
I am going to try to say as much politely as possible: What the git is your problem with blurry spinner?

Does it affect GHD update check? No.
Does it affect GHD work in general? No
Does it affect anyone of thousands other GHD users? No.  So what exactly is your problem? 

You dare to speak about "unprofessional". Does any your your software/script have the same amount of users as GHD? If no that please do not even try to bring unprofessionalism.

You get the indication of update check progress - what more do you want?

**Comment by gingerbeardman** [comment] 2018-06-07 12:51
Hello @Koklin 

During my time as a Technology Evangelist at Apple this sort of lack of attention to detail would never have been acceptable. So that's where I'm coming from—I look for a level of attention to detail that matches the rest of my user experience. When something jumps out at me, I report it. Here's [another example](https://medium.com/f-a-t-e/spot-the-bulge-475f10c8bcdf).

If GitHub are fine with not having high levels of attention to detail, then that's fine. But let's not make this personal. Some of my software has had millions of downloads, FYI.

**Comment by lee-dohm** [comment] 2018-06-07 15:58
@gingerbeardman thank you for the detailed issue and the help in putting together a reduced test case. However, please let's refrain from the value judgements such as "lazy" and "unprofessional". Focusing on [constructive criticism](https://github.community/t5/Studies-in-Community/Being-toxic-is-not-constructive-criticism/ba-p/8029) is the best way to make your case for getting something fixed.

**Comment by lee-dohm** [comment] 2018-06-07 15:58
@Koklin your comment was deleted as a violation of the [Desktop Code of Conduct](https://github.com/desktop/desktop/blob/master/CODE_OF_CONDUCT.md) as it was unprofessional conduct. You may consider this an official warning.

**Comment by billygriffin** [comment] 2019-11-20 21:50
Since this isn't something that we have a solution for and it's a minor cosmetic issue, I'm going to close it for now. However, the invitation remains if someone knows if there's a low effort way to tackle this, feel free to respond in this issue and we can evaluate whether to reopen. Thanks!

**Closed by billygriffin** 2019-11-20 21:50 UTC
Labels: enhancement, help wanted

**Comment by gingerbeardman** [comment] 2019-11-21 01:08
Thanks @billygriffin
