### ISSUE TITLE
New repository: invalid path is flagged as existing repository

### ISSUE THREAD

**Issue by JakeHL** [desktop/desktop#5829] opened 2018-10-05 23:47 UTC
## Description

When passing the value: `C:` into the Local path field on the New repository, the warning that typically shows for existing repositories appears.

## Version

* GitHub Desktop: Version 1.4.2-beta0 commit: d8e79651a71a0bb72878b6ed465349712be845dd

* Operating system: Windows 10

## Steps to Reproduce

1. `From the main screen, press CTRL+N`
2. `Enter 'C:' into the path field`

### Expected Behavior
The path is invalid & should not be considered a git repository
### Actual Behavior
The existing repository warning appears

## Additional Information

<img width="335" alt="untitled" src="https://user-images.githubusercontent.com/9119973/46564743-4daaf580-c901-11e8-971b-fdd5074d86b8.png">

The error stems from rev-parse.ts -> getTopLevelWorkingDirectory(path) where the exit code defines the result. 0 is thrown under the previously mentioned conditions.

One potential solution would to utilize a path validation library to ensure that 1. the entered path is valid to the OS & 2. it actually exists before even executing the git commands. This would probably just be a bandaid fix as there is evidently an issue further down.

**Comment by steveward** [comment] 2018-10-11 00:39
Thanks for digging into this @JakeHL!  I was able to reproduce this behavior as well. I'm going to mark this as a priority-3 since it's resolvable by entering a valid path like `C:\path\to\repo`.

**Comment by AndreiMaga** [comment] 2019-05-13 18:54
I was not able to reproduce this in 1.6.5.
Is this still an open issue ?

![image](https://user-images.githubusercontent.com/29285479/57643105-9de9e480-75c1-11e9-9331-b93a8b5bb8d1.png)

**Comment by shiftkey** [comment] 2019-05-13 19:23
@tierninho @JakeHL the CLI is a bit annoying to test locally, because they need to invoke part of the bundled. on macOS at least if you've installed the CLI shortcut to `/usr/local/bin/github` you can tweak the CLI behaviour with a couple of steps:

1. Build the app in dev mode with what you'd like to change, in my case this was to `~/src/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app`

2. Find where this `/usr/local/bin/github` is symlinked to:

```
$ ls -l /usr/local/bin/github
lrwxr-xr-x  1 shiftkey  admin  77  8 May 08:36 /usr/local/bin/github -> /Applications/GitHub Desktop Test.app/Contents/Resources/app/static/github.sh
```

3. Edit the `/usr/local/bin/github` script to point to your dev mode app:

```shellscript
#!/bin/sh

# The least terrible way to resolve a symlink to its real path.
function realpath() {
  /usr/bin/python -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0";
}

# comment out this variable
#CONTENTS="$(dirname "$(dirname "$(dirname "$(dirname "$(realpath "$0")")")")")"
# hard-code this path to your new app to test
CONTENTS="/Users/shiftkey/src/desktop/dist/GitHub Desktop-dev-darwin-x64/GitHub Desktop-dev.app/Contents/"
BINARY_NAME="$(ls "$CONTENTS/MacOS/")"
ELECTRON="$CONTENTS/MacOS/$BINARY_NAME"
CLI="$CONTENTS/Resources/app/cli.js"

ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"

exit $?
```

4. Now run `github` to test with the new CLI behaviour. 

With these steps, I was able to see the new message:

<img width="582" src="https://user-images.githubusercontent.com/359239/57648267-649e7e00-759b-11e9-96e1-43a8376b7417.png">

**Comment by steveward** [comment] 2019-05-13 19:48
@AndreiMaga good catch! This is fixed. I'm going to close this issue out.

**Closed by steveward** 2019-05-13 19:48 UTC
Labels: bug, help wanted, priority-3
