### ISSUE TITLE
Cannot clone repositories

### ISSUE THREAD

**Issue by felorhik** [desktop/desktop#12262] opened 2021-05-21 16:31 UTC
### Describe the bug

When trying to clone repositories and selecting a directory manually to put it in, weather cloning via URL or the repository itself, the prompt to select the folder does not work and you cannot progress with cloning the repo through the github app.

### Version & OS

Version 2.8.1 - Windows 10

### Steps to reproduce the behavior

1. Try to clone a repo through GitHub.com or URL
2. Select a local path that is an empty directory.
3. Prompt never closes, making it impossible to progress with the clone.

### Expected behavior

The "Local Path" to be the desired path and being able to progress with the clone

### Actual behavior

The dialog for setting the local path breaks and you cannot select any directory.

### Screenshots

Dialog looks normal, so screenshot won't help, just the "select" button does nothing.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I need to manually set the local path for any repo I work with due to how my development environment works.

**Comment by steveward** [comment] 2021-05-24 19:25
Thanks for the report @jordanramstad. I was not able to reproduce this issue -- are you able to provide a short video clip reproducing this so I can verify I'm not missing any steps?

**Comment by felorhik** [comment] 2021-05-27 01:35
**since making the report I have discovered that you can manually write the path as well (a workaround for this issue)**.

I had a video, but removed it since loom didn't have the features I needed to share it properly.

To describe it better you need to have a premade folder, a wordpress sites `wp-content` folder is the use case I had. You clear out the folder, and try to select that folder through the clone repository dialog. You will find you cannot actually select the `wp-content` folder as you would expect. Instead it wants to create a new directory with the name of the repo, and if you try to clear that, the dialog becomes unusable and you cannot select the folder you want to use.

So here are the steps

1. Create an empty directory outside of the github desktop app
2. Open the clone repository dialog
3. Select any repository
4. Click "Choose" to choose a custom path
5. Clear out the repos name from the dialog
6. Attempt to select the folder you created
7. You will be unable to progress with the dialog and will be forced to close it and manually enter the path.

The way I described it did work fine before, it stopped working at some point (not sure what version it worked at). Also the app has been updated to version 2.8.2 and the issue is still there.

The use case here is for wordpress sites, since typically the repository set to be the wp-content folder, so the repo name and folder name won't match (since for cms repos, it makes sense to avoid having core cms files in the repo).

**Comment by steveward** [comment] 2021-06-02 19:53
Thanks for the clarification @jordanramstad. Creating a new directory inside of the selected directory is the default behavior -- as you mentioned you can edit the path directly to workaround this. I'm going to close this out, but let me know if you have any further questions.

**Closed as completed by steveward** 2021-06-02 19:53 UTC
