### ISSUE TITLE
Massive memory usage

### ISSUE THREAD

**Issue by emmadesilva** [desktop/desktop#19011] opened 2024-07-24 12:09 UTC
### The problem

So after a few days of a really laggy experience, I open up the task manager, and I see that Desktop is using well over two gigabytes of RAM, even when idle.

### Release version

Version 3.4.2 (x64)

### Operating system

Windows 10 Pro

### Steps to reproduce the behavior

I'm gonna need some help here to debug this. I'm not doing anything special, and I'm not sure how to profile the app's memory usage.

### Screenshots

![image](https://github.com/user-attachments/assets/08e2ffb6-a25d-4556-941b-2a6af5097c13)

### Additional context

Restarting Desktop resets the memory usage to normal, so I'm assuming there is a memory leak somewhere?

![image](https://github.com/user-attachments/assets/40667448-e4a3-4b0f-9be2-7bb02edbf3a6)

**Comment by tidy-dev** [comment] 2024-07-24 13:13
@caendesilva Thank you for reaching out. 

1. Could you please upload a log file for the day you experienced this? To access the log files go to the menu and select Help > Show Logs.

2. After shutting down GitHub Desktop (ensuring in task manager there is no running processes) and reopening, is this easily reproducible?

**Comment by emmadesilva** [comment] 2024-07-24 13:58
> @caendesilva Thank you for reaching out.
> 
> 1. Could you please upload a log file for the day you experienced this? To access the log files go to the menu and select Help > Show Logs.
> 2. After shutting down GitHub Desktop (ensuring in task manager there is no running processes) and reopening, is this easily reproducible?

@tidy-dev There's a lot of logs, is there a place I should upload them to? And I will keep an eye on it to reproduce.

**Comment by tidy-dev** [comment] 2024-07-24 14:15
Uploading them to this thread. You can drag and drop the log file into a comment.

**Comment by emmadesilva** [comment] 2024-07-24 14:16
> Uploading them to this thread. You can drag and drop the log file into a comment.

[2024-07-24.desktop.production.log](https://github.com/user-attachments/files/16363425/2024-07-24.desktop.production.log)

Forgot about that, here you go @tidy-dev

**Comment by tidy-dev** [comment] 2024-07-24 15:55
Thank you for that @caendesilva. I do not see anything in the log that would indicate unusual performance. :/ 

I was trying to do some investigation and found we already have tracking for this issue. https://github.com/desktop/desktop/issues/10625

I am going to close this in favor of tracking there. If you are able to reproduce and happen to find a particular pattern of usage that causes it, that would be helpful. :)

**Closed as not planned by tidy-dev** 2024-07-24 15:55 UTC

**Comment by emmadesilva** [comment] 2024-07-24 15:56
> Thank you for that @caendesilva. I do not see anything in the log that would indicate unusual performance. :/
> 
> I was trying to do some investigation and found we already have tracking for this issue. #10625
> 
> I am going to close this in favor of tracking there. If you are able to reproduce and happen to find a particular pattern of usage that causes it, that would be helpful. :)

Yeah I will keep an eye out for it! Thanks!

**Comment by steveward** [comment] 2024-07-24 17:58
@caendesilva just a check -- are you running any security/antivirus software? Usually we see CPU usage issues with that, but I wanted to follow up to check if that was a possibility.

**Comment by emmadesilva** [comment] 2024-07-24 18:46
> @caendesilva just a check -- are you running any security/antivirus software? Usually we see CPU usage issues with that, but I wanted to follow up to check if that was a possibility.

I do have antivirus, but wouldn't that lead to high memory usage within the actual AV? Why would that affect Desktop?

**Comment by steveward** [comment] 2024-07-25 14:33
We've seen instances of performance slowdowns due to antivirus software scanning GitHub Desktop and causing operations to take longer. If you do have something installed it may be worth trying to temporarily disable it to see if it makes any difference.

**Comment by emmadesilva** [comment] 2024-07-25 14:37
> We've seen instances of performance slowdowns due to antivirus software scanning GitHub Desktop and causing operations to take longer. If you do have something installed it may be worth trying to temporarily disable it to see if it makes any difference.

Okay, I'll keep an eye out. Remember, CPU usage was still nominal in my case. This looked like a memory leak, as the memory usage was `~6575.84` percent higher than usual.

**Comment by emmadesilva** [comment] 2024-07-26 09:35
![image](https://github.com/user-attachments/assets/273707a2-871f-4199-814d-70b7dc263462)


@tidy-dev High memory usage again. Is there anything I can do to profile to see what part of Desktop is using memory?

@steveward My antivirus service is in the background but is at 0% CPU and ~6MB memory, so it doesn't seem to be doing anything at the moment.

**Comment by emmadesilva** [comment] 2024-07-27 09:36
> We've seen instances of performance slowdowns due to antivirus software scanning GitHub Desktop and causing operations to take longer. If you do have something installed it may be worth trying to temporarily disable it to see if it makes any difference.

@steveward Noticed Desktop with elevated memory usage around 600MB while AV was active. Disabling AV had no impact on Desktop usage at this time.
