### ISSUE TITLE
Locally rename repository

### ISSUE THREAD

**Issue by heyvian** [desktop/desktop#7098] opened 2019-03-15 17:25 UTC
**Please describe the problem you think should be solved**
The ability to rename repository that doesn't impact the repo. Just a display name for the current user and their app. 

The problem is _/group-name-1/corporate-website_ and _/group-name-2/corporate-website_ both show in Desktop as _corporate-website_ making it hard to differentiate which project to select.

OS: Any

**[Optional] Do you have any potential solutions in mind?**
Right click -> Rename Repository
Under "Repository -> Repository Settings" add a "Name" field
(Can take a look at _Tower_ which has this feature.)

Alternative would be to display the repo path below the repo name or some variation that allows the user to differentiate between projects.

**Comment by tierninho** [comment] 2019-03-15 17:35
@heyvian Thank for filing. This is a dupe of [1929](https://github.com/desktop/desktop/issues/1929), which is being addressed as part of [6460](https://github.com/desktop/desktop/issues/6460). Please follow along there.

**Closed by tierninho** 2019-03-15 17:35 UTC

**Comment by GriffinSauce** [comment] 2020-03-25 10:58
I'd like ask for consideration to reopen this issue because the other solutions don't solve my use case: I have a repo cloned on my machine twice, that may not make sense but trust me I have my reasons. 

Currently it's not possible to differentiate between the two at all in the UI. This is aggravated by the fact that they jump to different locations when changes are made.

A suggestion is that the `.git/description` file seems to match this use case. The app could simply pick this up if set and display it instead of the name. It's an optional label and it does not require any extra UI or data management in the app.

As a more general comment: as you can see in #6460 it is very hard to provide a perfect structure for all use cases. This would allow for some flexibility that allows users to work around potential unforeseen use cases.

**Comment by tierninho** [comment] 2020-03-25 20:47
@GriffinSauce Thank you for the thoughts on this. It is much appreciated.

> Currently it's not possible to differentiate between the two at all in the UI.

If you hover over the repo in the repo list, you will see a path which should help you determine which repo is which. We understand this is not ideal nor the best solution, but your feedback along with others we help us make the best decision going forward. 

At this time, the issue will remain closed. I have added your thoughts on the https://github.com/desktop/desktop/issues/1929 issue for reference. Thank you for using Desktop!

**Comment by GriffinSauce** [comment] 2020-03-25 21:17
Thanks @tierninho, I'm a very happy user of it :)
