### ISSUE TITLE
Big image corrupts ui

### ISSUE THREAD

**Issue by gabrielevierti** [desktop/desktop#6394] opened 2018-12-11 16:07 UTC
## Description

When commiting an image bigger than 1920 by 1080, the image glitches with the application's interface;
It's not really that annoying, but I still think this should be fixed anyway.

## Version

* GitHub Desktop:

* Operating system: Microsoft Windows [Version 10.0.17134.407]

## Steps to Reproduce

1.  Create a repository and commit an image of resolution 1920 by 1080 or higher
2.  Update the image with another one with a resolution of 1920x1080+

### Expected Behavior

Usually, you would see the old image on the left and the new one on the opposite side, like this (The image is made by me, but this is what I would expect GD to behave):

![snap](https://user-images.githubusercontent.com/31348401/49812637-268bfc80-fd66-11e8-9ad8-b3268d7819cc.png)

### Actual Behavior

![cattura](https://user-images.githubusercontent.com/31348401/49812715-50ddba00-fd66-11e8-9f72-64873c236eb0.PNG)

### Logs

[2018-12-10.desktop.production.log](https://github.com/desktop/desktop/files/2668296/2018-12-10.desktop.production.log)

**Comment by gabrielevierti** [comment] 2018-12-11 16:10
The Github Desktop version is 1.5.0, sorry if I didn't add that before, but I wasn't able to edit.

**Comment by tierninho** [comment] 2018-12-11 16:30
@gabrielevierti Many thanks for filing this! However, please note it is a dupe of https://github.com/desktop/desktop/issues/2480 so you may follow along there. Cheers.

**Closed by tierninho** 2018-12-11 16:30 UTC
