### ISSUE TITLE
on github desktop app, search and select and push the file

### ISSUE THREAD

**Issue by jamsrandorjb** [desktop/desktop#9257] opened 2020-03-10 18:08 UTC
### Describe the feature or problem you’d like to solve
It is hard to find specific file in a list of files where there is no filter option.

### Proposed solution
I believe it's nice to have search bar on top of changes in the Desktop app.
I want to commit and push only one of these files and sometimes it takes quite time to find the correct file. 
(Search and select and push)

### Additional context
Please see the screenshot:
![image](https://user-images.githubusercontent.com/35090254/76344429-f409e000-62d7-11ea-93ff-49fc0a3453bb.png)

**Comment by billygriffin** [comment] 2020-03-10 18:21
Hi @jamsrandorjb, thanks for the issue! This looks like a duplicate of #6407, so I'm going to close it but please follow along there and we'll update it if/when we begin working on it.

**Closed by billygriffin** 2020-03-10 18:21 UTC
