### ISSUE TITLE
Merge conflicts issue

### ISSUE THREAD

**Issue by DronVol** [desktop/desktop#5264] opened 2018-07-27 08:09 UTC
## Description

Hello everyone! I have an issue while conflicts merge. To resolve conflicts GitHub Desktop opens a window, where I can select the lines I want to save in my branch. After I select them I commit changes, but instead window closing I have resolved lines colored white and all others to select. Besides, I can't even ignore strings like ">>>>>>> HEAD" etc. It results in a situation when I always have file with conflicts, which I can't compile.

## Version

* GitHub Desktop: 1.2.6

* Operating system:
Windows 10 (17134.165)

## Steps to Reproduce

1. Create two different branches
2. Make separate changes in the same file
3. Try to merge one in another.

### Expected Behavior

Select in blue lines i want to save and expect conflict resolved after commit

### Actual Behavior

Still have lines to choose from, can't ignore any of them.

### Logs

[2018-07-27.desktop.production.log](https://github.com/desktop/desktop/files/2235006/2018-07-27.desktop.production.log)

**Comment by DronVol** [comment] 2018-07-31 15:12
I am sorry for the late response.

I have a test.txt file in a diploma repo. It contents the only string: "this is master". Then I make a branch called "late_ifz" and change this string to "this is branch". After this, I make some random changes in the master branch in this file and try to merge "late_ifz" branch with "master".

On screenshots, I show all the steps I make. I try to do the following: mark only lines I want to leave and commit changed file to git.
<img width="1209" alt="screenshot_11" src="https://user-images.githubusercontent.com/10686374/43468556-fbb2578e-94ec-11e8-993a-aecf22303258.png">
<img width="1089" alt="screenshot_12" src="https://user-images.githubusercontent.com/10686374/43468558-fbd19af4-94ec-11e8-9625-1cfc7f1139f5.png">
<img width="1099" alt="screenshot_13" src="https://user-images.githubusercontent.com/10686374/43468559-fbedec22-94ec-11e8-9ea2-d2530acdf081.png">
<img width="994" alt="screenshot_14" src="https://user-images.githubusercontent.com/10686374/43468560-fc0ab0aa-94ec-11e8-8d49-a7ab40122477.png">

Thanks in advance!

**Comment by shiftkey** [comment] 2018-08-07 17:44
@DronVol thanks for the screenshots and details.

Looking at this screenshot, it looks like you've selected the conflict markers as well as the content to commit:

![](https://user-images.githubusercontent.com/10686374/43468559-fbedec22-94ec-11e8-9ea2-d2530acdf081.png)

Desktop doesn't do anything clever about preventing you from including these lines in your partial commit, which is how I think the issue is occurring.

**Comment by billygriffin** [comment] 2018-08-14 19:53
I'm going to close this in favor of #5400 where we'll be tracking all research and work on making this less painful for people. Thanks so much for laying out such a clear example with screenshots @DronVol!

**Closed by billygriffin** 2018-08-14 19:53 UTC
Labels: more-information-needed
