### ISSUE TITLE
Error Occurs When Attempting to Commit

### ISSUE THREAD

**Issue by ramchandh-narayanasamy** [desktop/desktop#19221] opened 2024-09-08 06:16 UTC
### The problem

I am trying to commit my changes, but I'm encountering an error (please refer to the attached image). 

Could you please help me resolve this issue?

![Screenshot 2024-09-07 at 5 04 59 PM](https://github.com/user-attachments/assets/c6d0f6a7-e3bb-4394-8a94-683cb4e44e2f)

### Release version

Version 3.4.4 (arm64)

### Operating system

Mac OS Sonoma V14.3

### Steps to reproduce the behavior

Not sure if others were experiencing this.
1. Make some changes.
2. Try to commit some changes.

### Screenshots

![Screenshot 2024-09-07 at 5 04 59 PM](https://github.com/user-attachments/assets/8a23351a-2ea2-4229-a872-a4c36042bfa1)

### Additional context

Fetching or switching between branches works fine, but the error only occurs when I try to commit my changes.
I've been using GitHub Desktop for over 2 years, and this is the first time I'm experiencing this issue.

**Comment by steveward** [comment] 2024-09-09 12:26
@ramchandh-narayanasamy thanks for the issue. This looks like an external issue outside of GitHub Desktop that's being caused by a pre-commit hook.  It looks like whatever you have set in that pre-commit hook is trying to pull and failing due to a certificate issue. You can check `.git/hooks/pre-commit` to see what's running (and maybe comment it you need to bypass the issue temporarily). If you're familiar with `https://ghcr.io` I would recommend reaching out to whoever is running that to help deal with the certificate issue. 

Since there isn't anything we can do from our end I'm going to close this out, but let me know if you have any further questions.

**Closed as completed by steveward** 2024-09-09 12:26 UTC
