### ISSUE TITLE
Problem to upgrade the react version to 16.4

### ISSUE THREAD

**Issue by jialge** [desktop/desktop#6226] opened 2018-11-18 07:09 UTC
**Please describe the problem you think should be solved**
This could be a very basic question :)

I need to use the react-select component in the desktop app.  There is a known type issue which gets fixed in @types/react 16.4.13 https://github.com/JedWatson/react-select/issues/2860
So I have to upgrade the react version in desktop in order to get the fix.    I use yarn upgrade to upgrade the react version and @types/react version, but after I do this, I get tons of errors when doing yarn install. 

Here are the commands I ran to reproduce the problem:

1. cd into the app folder, and run `yarn upgrade react@16.4.2`
2. cd to the root folder, and run `yarn upgrade @types/react@16.4.18`
3. run `yarn install`

I get tons of errors similar to:
`
node_modules/@types/react/index.d.ts:2317:47 - error TS2694: Namespace '"C:/Users/Scott/Projects/GitHub/github-desktop/node_modules/@types/prop-types/index"' has no exported member 'InferProps'.

2317                 ? MergePropTypes<P, PropTypes.InferProps<T>>
`

**Comment by shiftkey** [comment] 2018-11-19 12:14
@jialge I think you'll need to add `@types/prop-types` as an explicit `devDependency` as the version indirectly added to the lockfile is a few versions behind (and missing `InferProps`):

https://github.com/desktop/desktop/blob/13ee781f396d2f84e0e66e0d4a3a427100726530/yarn.lock#L341-L344

**Comment by scottge** [comment] 2018-11-22 07:17
Thank you for the suggestion!  I tried the suggestion and added @types/prop-types as below in the root package.json file:

  "@types/prop-types": "^15.5.6",
  "@types/react": "16.4.18",

When I do yarn install, I still get the same error.  I looked into the yarn.lock file.  It has both  15.5.6 and 15.5.2 versions in it.


"@types/prop-types@*":
  version "15.5.2"
  resolved "https://registry.yarnpkg.com/@types/prop-types/-/prop-types-15.5.2.tgz#3c6b8dceb2906cc87fe4358e809f9d20c8d59be1"
  integrity sha512-pQRkAVoxiuUrLq8+CDwiQX4pTCep/PmmNgBbjIwnnsd/HoYjGpR81+FFPE030lvNXgR0haaAU6eoRtztWDE4Xw==

"@types/prop-types@^15.5.6":
  version "15.5.6"
  resolved "https://registry.yarnpkg.com/@types/prop-types/-/prop-types-15.5.6.tgz#9c03d3fed70a8d517c191b7734da2879b50ca26c"
  integrity sha512-ZBFR7TROLVzCkswA3Fmqq+IIJt62/T7aY/Dmz+QkU7CaW2QFqAitCE8Ups7IzmGhcN1YWMBT4Qcoc07jU9hOJQ==

**Comment by scottge** [comment] 2018-11-27 13:14
I deleted both yarn.lock files in the root folder and the app folder, and did a yarn install.  Unfortunately, I still get the same errors.

**Comment by outofambit** [comment] 2018-12-12 19:01
Hi @scottge can you give me a little more context around what you need the react-select component for in the desktop app? I'm happy to help get the last of these issues resolved

**Comment by scottge** [comment] 2018-12-12 19:11
I'm trying to extend the github desktop a little bit to fit my business needs.  I need the react-select control to allow my users to pick among a large set (100+) of predefined tags.

**Comment by outofambit** [comment] 2018-12-12 20:02
It looks like we're running into this issue with the typings: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28015. It looks like a fix has just been merged, but not released yet. I'm still investigating how to get around it in the meantime.

**Comment by shiftkey** [comment] 2018-12-17 13:40
>  I'm still investigating how to get around it in the meantime.

@outofambit not sure if you're still investigating this, but check out this commit which works in dev mode on my machine: 7e8f7f170

**Comment by scottge** [comment] 2018-12-21 04:10
Thank you!! @shiftkey 's 7e8f7f1 commit does solve the problem.  By pumping the react version, many of my other problems are solved too.

**Comment by scottge** [comment] 2018-12-21 06:54
Here is my commit that reproduces the above-mentioned color system issue.  My change is based on your latest master branch code.

https://github.com/scottge/desktop/commit/f39119a849b4ba2a3b98bb86d62ccbe2b6e7e059

![broken-color](https://user-images.githubusercontent.com/9753032/50329010-32846680-04aa-11e9-97de-88ba08dccb11.png)

**Comment by scottge** [comment] 2018-12-21 07:05
To fix this problem, I need to replace all color variable references with #{} 

For example, 
`--toolbar-background-color: $gray-900;`
needs to be
`--toolbar-background-color: #{$gray-900};`

**Comment by shiftkey** [comment] 2018-12-21 12:46
@scottge I believe that's #5876 that you're dealing with

**Comment by shiftkey** [comment] 2019-02-03 13:42
I'm closing this out in favour of #6763 which tracks upgrading to the latest stable React, so we can co-ordinate this with other feature work. Thanks for digging into this @scottge @jialge!

**Closed by shiftkey** 2019-02-03 13:42 UTC
Labels: tech-debt
