### ISSUE TITLE
"Lets get started!" page does not surface helpful context when fetching repositories fails

### ISSUE THREAD

**Issue by Graveflo** [desktop/desktop#7924] opened 2019-07-05 14:35 UTC
## Description

My GitHub account was set up a while ago in a previous version of GitHub desktop. When I open the app the landing page is the "Let's get started!" page with no repositories. Clearly this is incorrect, but there is not a simple way to fix this because I cannot access the settings menu or change anything with my account or credentials from this screen. Case and point, allow users to access the settings menu even on the landing page or they may get stuck there due to account related issues.

I have seen a post talking about something similar from the related issues function of GitHub but I have to speak up about this. It doesn't make sense to use and of the above options to change accounts or access the settings menu. In fact it would be VERY counter intuitive to figure that the user would want to start meddling around with repositories and creating them without having their settings in order first. Who creates a GitHub repository to log out of GitHub? There is no intuition to it at all.

## Version

release 2.1.0-80e9992d
* GitHub Desktop:

* Operating system: Windows 10 x64

## Steps to Reproduce

I don't know what screwed up my account data, but it was something to the effect of not opening the app for 5-12 months on this machine.

### Expected Behavior

I expected access to more features of the program from the UI entry point. I expected to be able to log out and log back in.

### Actual Behavior

There seem to be only four clickable widgets on this landing page "Refresh the list" (x2), "Clone a repository from the internet...", "Create a New Repository on your hard drive..." and "Add an Existing Repository from your hard drive"

## Additional Information

I would attack a screen show but I think this is easy enough to understand without it. Its just a blank "Let's get started!" page with a message saying it can't find any repositories and there seems to be no where to go from there.

### Logs

Log not needed

**Comment by tierninho** [comment] 2019-07-05 17:30
@ILikesCaviar I tend to agree that this is not ideal. The idea is that as you select your repository creation option, and the login will surface as part of the process -- if not logged in.

If you are still stuck, just choose the Clone Repository option and the login option will surface.

>  In fact it would be VERY counter intuitive to figure that the user would want to start meddling around with repositories and creating them without having their settings in order first. 

Good point. @billygriffin any thoughts on enabling the `GitHub Desktop` menu option to mitigate this?

**Comment by ILikesCaviar** [comment] 2019-07-05 18:27
Thanks for the reply. As per:
> 
> If you are still stuck, just choose the Clone Repository option and the login option will surface.
> 
For clarity I will elaborate a little bit:
When I click this I get a "Couldn't find any repositories for account ILikesCaviar." This, of course, is not true. I don't see any options to log out or log back in. I may be missing something but it seems to me like there are some config errors and I felt as though accessing some sort of settings menu would make it easy for me to fix whatever is wrong.

I can understand the idea behind how the flow is designed currently, but when it doesn't work as intended there doesn't seem to be an easy way to mitigate it.

Maybe something like making your account name a hyper link so you can try a few things that way.

**Comment by tierninho** [comment] 2019-07-05 20:15
Ah, thanks for the added clarity. The error you are seeing is an API error as noted [here](https://github.com/desktop/desktop/issues/7019). 

You are indeed logged in, the app is just not loading your repositories properly. Workaround: Open your Developer Tools console under the `View` menu and `cmd-R` inside of it to refresh Desktop. It _should_ fix it.

As this bug was supposed to have been fixed, would you mind adding you logs to this issue? See the `Help` menu to find your logs.

**Comment by ILikesCaviar** [comment] 2019-07-05 20:35
I had to make a local repository to access the help menu, but after I did that I took a look at the logs. Sorry for being particular but I'm going to include a slightly modified (just names) snippet from the log file. I had a suspicion it was a login / auth token error since it has been a while since I used the app. After I made the dummy local repo I was able to access the settings menu and refresh my credentials. Everything works now but it was confusing that I had to make a local repo just to get to my account settings. I just wanted to point out that although my particular error may be obscure, there are a family of potential use cases for having a subset (at least) of the settings menu accessible from the landing page.

Thanks for all your help though, I still love the app :)

2019-07-05T14:02:40.153Z - info: [ui] Stats reported.
2019-07-05T14:02:40.441Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.<anonymous> (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:136:11)
    at Generator.next (<anonymous>)
    at ae (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:122:4)
2019-07-05T14:02:40.442Z - warn: [ui] fetchIssues: failed for repository ilikescaviar/REPO_NAME
Error: Bad credentials
    at Object.<anonymous> (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:136:11)
    at Generator.next (<anonymous>)
    at ae (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:122:4)
2019-07-05T14:02:40.443Z - warn: [ui] Unable to fetch issues for ilikescaviar/REPO_NAME
Error: Bad credentials
    at Object.<anonymous> (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:136:11)
    at Generator.next (<anonymous>)
    at ae (C:\Users\User\AppData\Local\GitHubDesktop\app-0.8.0\webpack:\app\src\lib\http.ts:122:4)
2019-07-05T14:04:29.375Z - info: [ui] [AppStore] loading 0 repositories from store
2019-07-05T14:04:29.375Z - info: [ui] [AppStore] found account: ILikesCaviar (null)
2019-07-05T14:04:29.622Z - info: [ui] launching: 2.1.0 (Windows 10.0.17134)
2019-07-05T14:04:29.623Z - info: [ui] execPath: 'C:\Users\User\AppData\Local\GitHubDesktop\app-2.1.0\GitHubDesktop.exe'
2019-07-05T14:04:30.092Z - warn: [ui] fetchAccount: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\User\AppData\Local\GitHubDesktop\app-2.1.0\webpack:\app\src\lib\http.ts:171:4)
2019-07-05T14:04:30.092Z - warn: [ui] fetchUser: failed with endpoint https://api.github.com
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\User\AppData\Local\GitHubDesktop\app-2.1.0\webpack:\app\src\lib\http.ts:171:4)
2019-07-05T14:04:30.092Z - warn: [ui] Error refreshing account 'ILikesCaviar'
Error: Bad credentials
    at Object.t.parsedResponse (C:\Users\User\AppData\Local\GitHubDesktop\app-2.1.0\webpack:\app\src\lib\http.ts:171:4)
2019-07-05T14:04:30.094Z - warn: [ui] fetchAll: 'user/repos' returned a 401
2019-07-05T14:04:34.693Z - info: [ui] Opt in reported.
2019-07-05T14:05:20.731Z - warn: [ui] fetchAll: 'user/repos' returned a 401
2019-07-05T14:05:21.573Z - warn: [ui] fetchAll: 'user/repos' returned a 401
2019-07-05T14:05:36.521Z - warn: [ui] fetchAll: 'user/repos' returned a 401
2019-07-05T14:05:37.261Z - warn: [ui] fetchAll: 'user/repos' returned a 401
2019-07-05T14:05:44.399Z - info: [ui] [AppStore] loading 0 repositories from store
2019-07-05T14:05:44.400Z - info: [ui] [AppStore] found account: ILikesCaviar (null)
2019-07-05T14:05:44.581Z - info: [ui] launching: 2.1.0 (Windows 10.0.17134)
2019-07-05T14:05:44.582Z - info: [ui] execPath: 'C:\Users\User\AppData\Local\GitHubDesktop\app-2.1.0\GitHubDesktop.exe'

**Comment by tierninho** [comment] 2019-07-05 21:05
Glad it is now resolved and that you still love the app!! 😄  👍 

### Summary of the issue:
 
- User was on the `Let's Get Started` page with no repositories
- User was logged in but with expired credentials;
- Could not access the `Preference` settings to check credentials or login/logout. 

As a result the "bad credentials" [API error](https://github.com/desktop/desktop/issues/7019) was shown on the `Clone Repo` modal displayed from the start page. The error message was not entirely accurate and blocked the user for resolving the issue.

### Recommendations:

- Amend the current error message in https://github.com/desktop/desktop/issues/7019 and append "or go to `Preferences<hyperlink>` to log out and log back in." as we should allow a back door into the `Preferences` page.
- Does the logic from https://github.com/desktop/desktop/pull/7259 capture this scenario?

**Comment by outofambit** [comment] 2019-07-06 00:18
I think @tierninho is on the money with

> Does the logic from #7259 capture this scenario?

because we'll need to modify some of the logic there to differentiate and store API errors to be used in the UI later (like showing a more appropriate error message).

Unfortunately this means this means this isn't a trivial fix, but it does feel like a worthwhile investment since it could be used in other parts of the UI too (anything related to auth/account failures).

_____

_More details:_

I think the core issue here is that we don't store any information about why a `fetchRepositories` call might have returned nothing.

The "Couldn't find any repositories for account[...]" error message is displayed any time there are no repositories to show in the clone-able repository filter list:

https://github.com/desktop/desktop/blob/ff6bcf626470000e83408f4de6dab047de447bee/app/src/ui/clone-repository/cloneable-repository-filter-list.tsx#L176

, which is defined here:

https://github.com/desktop/desktop/blob/ff6bcf626470000e83408f4de6dab047de447bee/app/src/ui/clone-repository/cloneable-repository-filter-list.tsx#L251

**Comment by shiftkey** [comment] 2019-07-26 16:17
I've tweaked the title to indicate it's covering a different problem to #8016

**Comment by tidy-dev** [comment] 2024-09-16 19:24
I am unable to reproduce the issue of "not being able to open menu items from the Let's get started screen". Thus, I believe this issue can be closed.

That said, it could be discussed whether the Let's Get Started screen could/should display a hint to sign in if the user is not signed in. However, in the welcome flow, you can intentionally not sign in when using GHD for a non-GitHub host. In which case maybe, this would just be annoying - like "I just did the welcome flow and chose not to sign in.. why you still bothering me"? But, on the other hand, GHD is a GitHub product so hinting to sign in on a fairly empty screen (so not taking real estate away from anything) maybe reasonable.

**Closed** 2024-09-17 19:13 UTC
Labels: bug, priority-3
