### ISSUE TITLE
v3.4.0, can't push on windows 10 to azure devops

### ISSUE THREAD

**Issue by umarWonderTree** [desktop/desktop#18748] opened 2024-06-03 10:26 UTC
### The problem

Can't push the code, I'm using v3.4.0. It asks for authentication only once and then it shows the error

Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.

Additionally I can push using Visual Studio, and same changes are reflected on Github Desktop as well. But can't push from Github Desktop.

### Release version

3.4.0

### Operating system

Windows 10

### Log files

[2024-06-03.desktop.production.log](https://github.com/user-attachments/files/15532457/2024-06-03.desktop.production.log)

### Screenshots

![image](https://github.com/desktop/desktop/assets/103572343/2fbc5e8d-00cb-492c-bf25-90ae9437db5e)

**Comment by cryptoseven** [comment] 2024-06-03 11:09
I have the same issue. After updating to version 3.4.0 I can't push to azure devops.
[2024-06-03.desktop.production.log](https://github.com/user-attachments/files/15533043/2024-06-03.desktop.production.log)

**Comment by cryptoseven** [comment] 2024-06-03 11:55
My issue got resolved when I deleted an extra test project I had in azure devops. In the logs it looks like github desktop tried to connect to this project (TestUpload) instead of my main project.

**Comment by umarWonderTree** [comment] 2024-06-03 12:13
@cryptoseven that might be the problem, But, I'm working on 8-10 projects simultaneously from two different organization on Azure DevOps. I'm using Visual Studio for pushing as of now. I can change branches and view the changes inside commits.

**Comment by sergiou87** [comment] 2024-06-03 13:40
@umarWonderTree the main change from the previous version is that now, for dev.azure.com repos, GitHub Desktop will prompt you for credentials **even if they're the same**.

If you have two different organizations, I guess you have two different set of credentials. Just entering them when prompted for a given repo should be enough.

@cryptoseven I hope this ☝ helps you too.

Please, let me know if that makes sense.

**Comment by umarWonderTree** [comment] 2024-06-04 05:10
I'm not prompted to enter credentials. Added the log as well as a vid showing what happens when I try to push. I was only prompted to enter the credentials only once(which I mistyped as previously it needed username and password, so I entered username instead of password), and then it doesn't show that screen anymore.

Log:
[2024-06-04.desktop.production.log](https://github.com/user-attachments/files/15542801/2024-06-04.desktop.production.log)

Vid:
https://github.com/desktop/desktop/assets/103572343/53014b02-5e87-488f-bb5f-bb6e789e2c5d

[Update]
I tried with other projects and It's working fine, Issue is resolved. But the previous project where I mistyped the pass, it's not asking me for pass anymore. Authentication Failed windows pops up. It should be asking for pass or where do I enter the pass?

**Comment by sergiou87** [comment] 2024-06-04 07:23
> Authentication Failed windows pops up. It should be asking for pass or where do I enter the pass?

Weird, it should first show the error, and then the next time you try to push/pull/fetch from it, it should ask for the credentials again. We will look into that. Meanwhile, you can open Windows Credentials Manager, and look for an entry related to that repo (the name of the entry should include the repo URL) and delete it, to force the app to ask you for credentials again. Let me know if that works 🙏

**Comment by umarWonderTree** [comment] 2024-06-04 09:30
Thanks, that worked. Removed the repo entry from Credentials Manager and it asked for password now. Solved.

**Comment by sergiou87** [comment] 2024-06-04 10:10
For what is worth I tried to reproduce this problem and for me it deletes the credentials after the authentication fails, and then prompts me the credentials again after that 🤯  So I'm gonna close this for now.

I'm glad the workaround solved the issue for you.

**Closed as completed by sergiou87** 2024-06-04 10:10 UTC
Labels: investigation-needed
