### ISSUE TITLE
Support git pre hooks

### ISSUE THREAD

**Issue by Rey-Wang** [desktop/desktop#13112] opened 2021-10-13 02:44 UTC
### Describe the feature or problem you’d like to solve

When I use the desktop to submit a commit, it would skip the git prehooks, for example, there's some lint check and it should prevent commit the changes

### Proposed solution

expect could run hooks and prevent commit if there's problem

**Comment by BrendaHutchinson** [comment] 2021-10-13 03:15
Hi Brenda Hutchinson here, I am excited about you being close to being done with my windows 11 and apps, have a little of it on my phone though just not right, not your fault, hackers have picked it apart. Hopefully when you are done I can reload it back on phone, not rushing you guys, just wanted to say thank you all for your hard work,   be checking back soon, p.s. don't have any of my power platform/drive, or internet, though I know I will be enjoying them soon, Sincerely Brenda Hutchinson

**Comment by BrendaHutchinson** [comment] 2021-10-15 21:21
When can I take a look at my windows 11 app,and all the apps, tools power ect.. and how do I get it. Sorry to sound so unknowable, though a fast learner, just been awhile.

**Comment by glock47** [comment] 2021-10-17 13:56
[https://github.com/desktop/desktop/issues/13112#issue-1024707763]() 
Duplicate of #

**Comment by niik** [comment] 2021-10-18 08:29
Hi @Rey-Wang, thanks for reaching out. GitHub Desktop will run pre-commit hooks on commit if your Git repository is configured to use them. Note however that the hooks will run inside of GitHub Desktops environment which means they won't necessarily have access to the same environment variables as you'd normally have when using the command line.

I created this silly pre-commit hook:

```
#!/bin/sh

exec 1>&2
echo "No commit for you"
exit 1
```

And attempted to commit from within GitHub Desktop

![image](https://user-images.githubusercontent.com/634063/137695683-e4537499-2dcc-4bd9-b4ac-6e9d5c2d5cc4.png)

Could you double check your configuration and make sure the commit hook does run when you commit outside of GitHub Desktop?

**Closed as completed** 2021-10-25 08:50 UTC
Labels: more-info-needed
