### ISSUE TITLE
GitHub Desktop on Linux

### ISSUE THREAD

**Issue by ghost** [desktop/desktop#12115] opened 2021-05-02 14:50 UTC
### Describe the feature or problem you’d like to solve

Wine or a Windows VM is required to use the app on Linux systems.

### Proposed solution
Build a Linux version so Linux devs can use it

**Comment by billygriffin** [comment] 2021-05-03 02:11
Hi @VMGuy23, thanks for the issue! I'm closing this as a duplicate of #1525.

**Closed as completed by billygriffin** 2021-05-03 02:11 UTC

**Comment by ghost** [comment] 2021-05-03 07:43
Thanks for link
