### ISSUE TITLE
Pull requests don't disappear from the branch list after merging them on the web.

### ISSUE THREAD

**Issue by RDalcolmo** [desktop/desktop#4208] opened 2018-03-09 14:14 UTC
## Description

After one of my co-workers created a pull request, it was visible on the Github Desktop client. However, after accepting the request and merging the code, the pull request still shows on the list on the desktop client. This is on an enterprise repository/account.

## Version

* GitHub Desktop: 1.1.0
* Operating system: Windows 10

## Steps to Reproduce

1) Create a pull request on the web.
2) Fetch on github desktop so you can see the request on the list.
3) Accept/merge the request through the web.
4) Observe that the pull request still shows on Github Desktop

### Expected Behavior
To not show the pull request on the branch/pull request tab after merging/completing.
### Actual Behavior
It shows the pull request on the branch/pull request tab after merging/completing.

https://imgur.com/a/fnaFy

**Comment by tierninho** [comment] 2018-03-09 17:58
@RDalcolmo Thanks for filing.

This appears to be a regression bug as I can reproduce this on 1.1.1-beta1. 

(Non-Enterprise repos are working as expected.)

**Comment by j-f1** [comment] 2018-03-09 18:07
This looks like a duplicate of #4122.

**Comment by tierninho** [comment] 2018-03-09 18:11
Agree @j-f1 good catch. Closing this out as a dupe.

**Closed by tierninho** 2018-03-09 18:11 UTC
Labels: bug
