### ISSUE TITLE
GitHub desktop keeps automatically pulling remote repositories

### ISSUE THREAD

**Issue by LoeizD** [desktop/desktop#8401] opened 2019-10-03 18:59 UTC
### Description
As mentioned in the title: random remote changes appear in my local repository without me fetching or pulling. Not only the changes appear locally, they appear as uncommitted changes, like I was the one who wrote those changes?

### Version
GitHub Desktop: 2.2.0
Operating system: Windows 10
### Steps to Reproduce
I have no incoming changes
I start editing my files, have local changes
Meanwhile someone pushes some changes
I check the repo in GitHub desktop and suddenly I not only have my local changes, but also the remote changes that I never pulled. It's even worse because the remote changes appear as uncommitted, so now there's a mess of my local (actual) uncommitted changes and some other remote uncommitted changes?
**Expected Behavior**
Don't automatically pull remote changes.

**Actual Behavior**
Remote changes are pulled as uncommitted changes.
### Additional Information
So we have to manually discard the files before actually pulling, but one of the fake uncommitted changes wouldn't be discarded through the GUI or the git command line (reset). We had to manually delete the file form windows, to be able to pull without conflict.

There might be a slight chance that it happened before 2.2.0, because we kept closing and opening the app, and the update might have slipped our attention.

(Sadly I can't tell more as we went for gitkraken as our partners were getting annoyed.)

**Comment by tierninho** [comment] 2019-10-03 19:10
@LoeizD Thanks for the write-up. Any chance you still have logs or screenshots? Based on your steps, I do not see much to go on unfortunately.

**Comment by billygriffin** [comment] 2019-10-03 19:12
@LoeizD Thanks so much for the issue, and I'm so sorry for the experience! This looks like exactly what we saw in #8155 and the other corresponding issues and that should be fixed as of 2.1.3, which shipped about a month ago. Is it possible whomever was experiencing this was still on a version between 2.1 and 2.1.3? There was only a short window of time where this should've been an issue.

Echoing @tierninho, log files would also be really helpful. If you're willing to give it another shot, this is obviously a super high impact problem and we're eager to fix it ASAP if you're still experiencing it on the current version. Thanks!

**Comment by LoeizD** [comment] 2019-10-04 02:00
The desktop install was made a week ago (something like 23 September 2019) with no prior version installed. I don't know what version it was on that day.

No logs as it's guys from the art team who had the problem (I'm reporting from what I observed and the bunch of tests I asked them to do).

**Comment by billygriffin** [comment] 2019-10-04 14:09
@LoeizD Thanks for the additional info. I *think* this should be fixed now on the latest version from the work related to #8155, and if folks are willing to give it another try (assuming it was useful for them otherwise), we’d love that. One other question - we’re the people experiencing this logged in to GitHub Enterprise Server? 

Because we’ve so thoroughly tested this and aren’t able to reproduce, I have to begrudgingly close this for now, but again it’s certainly something we’ll prioritize if we can verify that it’s still happening.

**Closed by billygriffin** 2019-10-04 14:09 UTC
Labels: more-info-needed

**Comment by RandyMcMillan** [comment] 2019-11-09 08:22
Something like this was occurring in the macOS version of the app. I was installing via brew. Can someone please make sure it is installing a fixed version.

**Comment by billygriffin** [comment] 2019-11-12 14:01
@RandyMcMillan The [homebrew version](https://formulae.brew.sh/cask/github#default) says 2.2.3. Please let us know if that's not not matching what you're seeing. Thanks!
