### ISSUE TITLE
GitHub Desktop performance is very slow and sluggish.

### ISSUE THREAD

**Issue by ecepeda88** [desktop/desktop#11179] opened 2020-12-04 20:55 UTC
### Describe the bug

GitHub Desktop is extremely slow. I'm unable to navigate in GitHub Desktop smoothly and with every click I have to wait between 5-10 seconds.

### Version & OS

GitHub Desktop Version 2.6.0
Windows 10 Pro Version 1909

### Steps to reproduce the behavior

1. Access GitHub Desktop.
2. Select any Menu or attempt to do anything on the software.
3. Observe how long it takes for GitHub to respond to your selections.

### Expected behavior

The user should be able to have a smooth, reactive and normal UI experience.

### Actual behavior

Any action taken while using GitHub Desktop will take too long for GitHub Desktop to react.

### Screenshots

Unable to provide screenshots as the nature of the bug is in the performance.

### Logs

[2020-12-04.desktop.production.log](https://github.com/desktop/desktop/files/5645408/2020-12-04.desktop.production.log)

### Additional context

N/A

**Comment by steveward** [comment] 2020-12-04 21:37
Thanks for the report @ecepeda88. Have you noticed GitHub Desktop CPU processes spiking when this slowdown occurs? 

I do see that various operations seem to be taking longer than expected in the log file. Did this behavior just start occurring recently in GitHub Desktop?

My last question is whether or not you are running any antivirus or other security software on this machine. We've seen cases where antivirus software can cause performance slowdowns like this.

**Comment by ecepeda88** [comment] 2020-12-04 21:57
Hi Steve,

No spiking in my CPU when I’m performing actions in GitHub Desktop. The CPU is processing normally.

This issue has occurred since I’ve installed GitHub Desktop. I’ve uninstalled GitHub and reinstalled just to see if it as a bad install but it does still occur unfortunately.

The antivirus software running on this machine is Windows Security and Vallum GMI Monitoring.


Edward Cepeda
Quality Assurance Specialist, NetSuite
ecepeda@speareducation.com
http://speareducation.com
Spear Education
THE PURSUIT OF GREAT DENTISTRY

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by billygriffin** [comment] 2020-12-05 03:46
@ecepeda88 Are you able to temporarily disable your antivirus software to see if that improves things? Just want to make sure that's the cause, but it seems likely based on your response. Thanks!

**Comment by ecepeda88** [comment] 2020-12-07 15:19
Hi,

I am unfortunately unable to temporarily disable my antivirus software as it is controlled by my company.

I can check with the IT department if they would be willing to test this with me.


Edward Cepeda
Quality Assurance Specialist, NetSuite
ecepeda@speareducation.com
http://speareducation.com
Spear Education
THE PURSUIT OF GREAT DENTISTRY

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by steveward** [comment] 2020-12-07 18:12
@ecepeda88 that'd be great -- your IT department may be able to whitelist GitHub Desktop to work around this issue.

**Comment by ecepeda88** [comment] 2020-12-08 17:52
My IT is working on getting this change approved. Hopefully it does then we can see if that is the issue at hand. I will keep you updated.

Thanks for your patience.


Edward Cepeda
Quality Assurance Specialist, NetSuite
ecepeda@speareducation.com
http://speareducation.com
Spear Education
THE PURSUIT OF GREAT DENTISTRY

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.

**Comment by ecepeda88** [comment] 2020-12-08 20:06
After disabling the antivirus software, GitHub desktop is now quick and usable. It solved the problem.


Edward Cepeda
Quality Assurance Specialist, NetSuite
ecepeda@speareducation.com
http://speareducation.com
Spear Education
THE PURSUIT OF GREAT DENTISTRY

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you are not the intended recipient of this message or their agent, or if this message has been addressed to you in error, please immediately alert the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any use, dissemination, copying, or storage of this message or its attachments is strictly prohibited. If you have received this communication in error, please notify us immediately by replying to the message and deleting it from your computer.
From: Edward Cepeda
Sent: Tuesday, December 8, 2020 10:53 AM
To: desktop/desktop <reply@reply.github.com>; desktop/desktop <desktop@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [desktop/desktop] GitHub Desktop performance is very slow and sluggish. (#11179)

My IT is working on getting this change approved. Hopefully it does then we can see if that is the issue at hand. I will keep you updated.

Thanks for your patience.

**Comment by steveward** [comment] 2020-12-09 21:47
@ecepeda88 I'm glad to hear that seems to have fixed things. Since we've tracked this down to being a specific issue with your environment I am going to close this issue out.

**Closed as completed by steveward** 2020-12-09 21:47 UTC
