### ISSUE TITLE
Recent branch display error

### ISSUE THREAD

**Issue by Grey-Wind** [desktop/desktop#19146] opened 2024-08-22 11:21 UTC
### The problem

heads/v2.2.0 and heads/v2.1.0 have appeared in the recent branch.

v2.2.0 and v2.1.0 are branches that I created and have been deleted both remotely and locally.

Run the `git branch -r` command in cmd and these two branches are no longer visible, but they still show up on GitHub Desktop.

Using `git remote update --prune` won't fix it.

### Release version

Version 3.4.3 (x64)

### Operating system

Windows 10 22H2

### Screenshots

![微信截图_20240822191730](https://github.com/user-attachments/assets/8304df4d-8f81-402a-b6d6-caa806364aff)

**Comment by Grey-Wind** [comment] 2024-08-22 11:23
Rebooting the software won't fix it either.

**Comment by Grey-Wind** [comment] 2024-08-22 11:25
When will GitHub Desktop implement interface multi-language support?

That's what a lot of people want.

**Comment by tidy-dev** [comment] 2024-08-22 15:58
@Grey-Wind Thank you for reaching out. 

Unfortunately I am unable to reproduce, could you upload your logs? Maybe GitHub Desktop is erroring on parsing the local branches?

Here are the steps I followed:
1. Created a branch in GitHub Desktop.
2. Published it.
3. Deleted the published branch remotely via the github.com interface.
4. Returned to GitHub Desktop. Verified that it i
5. Deleted the branch via the command line.
6. Returned to GitHub Desktop

The branches were not there as expected.

**Comment by Grey-Wind** [comment] 2024-08-25 13:33
I failed again, but the problem is real.

**Comment by steveward** [comment] 2024-08-26 20:06
> I failed again, but the problem is real.

Can you clarify what you mean? Were you unable to reproduce the problem again? 

It would be helpful if you could also share your log files. To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by Grey-Wind** [comment] 2024-08-27 10:18
[2024-08-22.desktop.production.log](https://github.com/user-attachments/files/16760490/2024-08-22.desktop.production.log)

**Comment by Grey-Wind** [comment] 2024-08-27 10:19
I mean I failed to reproduce the problem

**Comment by steveward** [comment] 2024-08-27 13:29
I'm going to close this issue out then since we were unable to reproduce the problem.

I see a number of network errors in the log file indicating fetch failures, which could be causing issues:

```
2024-08-22T22:41:11.547Z - warn: [ui] Alive web socket request failed: TypeError: Failed to fetch
2024-08-22T22:41:15.164Z - info: [ui] Executing fetch: git fetch --progress --prune --recurse-submodules=on-demand origin (took 303.627s)
2024-08-22T22:41:15.165Z - error: [ui] `git fetch --progress --prune --recurse-submodules=on-demand origin` exited with an unexpected code: 128.
stderr:
fatal: unable to access 'https://github.com/Grey-Wind/QingYi.Crypto.git/': SSL/TLS connection timeout
```

**Closed as completed by steveward** 2024-08-27 13:29 UTC
Labels: investigation-needed

**Comment by Grey-Wind** [comment] 2024-08-27 14:47
Network connection timeout is not the source of the problem.

But I can't reproduce the problem either.
