### ISSUE TITLE
TortoiseGit steals GitHub Desktop links

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [desktop/desktop#4754] opened 2018-05-22 14:00 UTC
**Is your feature request related to a problem? Please describe.**
I've installed both TortoiseGit and GitHub Desktop on my windows system. Since TortoiseGit was installed after GitHub Desktop, it has configured itself as default for `x-github-client://` links, but I don't want to use it.

**Describe the solution you'd like**
An option should be added to `File -> Options...` to set GitHub Desktop as default for those links. It shouldn't appear when it's already configured as default. 

**Describe alternatives you've considered**
Another option could be to show a dialog whenever GitHub Desktop starts, but that could spam users.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this. This will help the core team understand how the feature would work, and assist with future work like documentation.
Screenshots or mockups here are a great help!

**Comment by steveward** [comment] 2018-05-22 16:20
Thanks for opening this @kaeptmblaubaer1000. 

What is the specific browser that you are using? I can provide a solution for you to reset the protocol handler associated with those links.

>Another option could be to show a dialog whenever GitHub Desktop starts, but that could spam users.

If you are using Google Chrome you can turn off the ability for Chrome to set a default application for those types of links by going to `chrome://settings/handlers` and turning off the `Allow sites to ask to become default handlers for protocols` option.

**Comment by kaeptmblaubaer1000** [comment] 2018-05-22 16:30
@steveward I'm using Chrome, but TortoiseGit is a desktop application (https://gitlab.com/tortoisegit/tortoisegit). I'm unable to uninstall it since some chocolatey package I need marks it as a dependency.

**Comment by shiftkey** [comment] 2018-05-22 20:41
@kaeptmblaubaer1000 thanks for the feedback.

We ensure our protocol handlers are up to date on each launch, so I'm not sure how much more aggressive we could be here:

https://github.com/desktop/desktop/blob/7f1e492e903f3ee3b712d70217908fa5b410d929/app/src/main-process/main.ts#L180-L188

I think this is something that needs to be reported to TortoiseGit.

**Comment by shiftkey** [comment] 2018-05-24 02:49
> Since TortoiseGit was installed after GitHub Desktop, it has configured itself as default for `x-github-client://` links, but I don't want to use it.

Closing this out as something that Desktop doesn't have control over. I'd recommend [contacting TortoiseGit Support](https://tortoisegit.org/support/) about the behaviour.

**Closed by shiftkey** 2018-05-24 02:49 UTC

**Comment by kaeptmblaubaer1000** [comment] 2018-05-24 06:40
https://gitlab.com/tortoisegit/tortoisegit/issues/3215

**Comment by kaeptmblaubaer1000** [comment] 2018-05-24 08:53
@shiftkey from TortoiseGit issue tracker:

> However, we tell Windows that TortoiseGit is capable of handling such URLs, but we don't register it, maybe the GitHub client is not correctly registering it (there was a recent change in Windows 10).

**Comment by tobias-loew** [comment] 2019-09-13 09:29
I the problem is the missing registration of GitHubDesktop at HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications and HKEY_LOCAL_MACHINE\SOFTWARE\GitHubDesktop.
I described the solution here: https://stackoverflow.com/a/57905263/1997370
Please add the missing registration to the GitHubDesktop-installer

**Comment by ouliuquan** [comment] 2020-07-14 06:32
Don't someone real to deal with the problem? Not just talking without a test.
