### ISSUE TITLE
"Discard all changes" ignores confirmation dialog setting

### ISSUE THREAD

**Issue by cheshire137** [desktop/desktop#4781] opened 2018-05-24 16:30 UTC
## Description

Right-clicking the "X changed files" header and choosing "Discard all changes" prompts me if I'm sure I want to discard the changes even though I have "Show confirmation dialog before discarding changes" unchecked in preferences.

## Version
* GitHub Desktop: 1.2.0
* Operating system: macOS High Sierra 10.13.4

## Steps to Reproduce
1. Have one or more changed files in your repository
1. Uncheck the "Show confirmation dialog before discarding changes" setting in preferences
    ![image](https://user-images.githubusercontent.com/82317/40498809-ad526142-5f45-11e8-9a54-856b0d18edd4.png)
1. Right-click the header with "X changed files" and choose "Discard All Changes..."

### Expected Behavior
It should discard all the changed files without any prompt.

### Actual Behavior
It shows a prompt asking if I'm sure if I want to discard those changes:

<img width="475" alt="screen shot 2018-05-24 at 11 24 56 am" src="https://user-images.githubusercontent.com/82317/40498793-a4ca134e-5f45-11e8-9258-b3860c3faa87.png">

### Additional info

I tried right-clicking a single file and choosing "discard changes" and it behaved as expected: changes were discarded and no prompt was shown. So it seems like just the "discard all" option is ignoring the setting.

**Comment by j-f1** [comment] 2018-05-24 16:35
This is an intentional behavior since people were accidentally clicking that button, not getting a confirmation dialog, and were left with no easy way to undo the discard.

**Comment by cheshire137** [comment] 2018-05-24 16:37
Nooo, extra steps! Could an additional setting be added then, "Show confirmation dialog before discarding all changes"? The confirmation feels like the app getting in my way: I just told it to do this thing, why is it asking me if I want to do this thing? Since "Discard all" isn't a one-click operation anyway (right-click a particular area then left-click something), having a third step (left-click confirmation) feels excessive.

**Comment by j-f1** [comment] 2018-05-24 16:44
It might make sense to respect the confirmation setting for the choice in the header, but I feel like we should always display the dialog after right-clicking on a file, since it’s too easy to accidentally click the wrong choice when they’re right next to each other.

**Comment by cheshire137** [comment] 2018-05-24 16:47
Hmm, I just realized the "Discard all changes" appears when right-clicking a single file. Maybe that option could be removed from the single-file right-click menu, and only show up when you right-click the header. It feels a little unintuitive to focus a particular file and then have an option that affects other files, and I can totally see wanting to discard just that one file and being surprised that it affected all files. I'd actually always been going to the header area to discard all changes since I didn't realize it showed up on the individual file right-click as well.

**Comment by iAmWillShepherd** [comment] 2018-05-24 16:48
I'm 👍 on adding a second option.

**Comment by cheshire137** [comment] 2018-05-24 16:53
I saw the closed issues about folks accidentally hitting "Discard all changes". I'm wondering if they got to that menu option because they right-clicked a single file in the list and then accidentally hit "discard all" instead of just "discard". If so, it might be fine to:

- _Not_ add a second "show confirmation dialog when discarding all changes"
- Drop the "discard all" option from the menu that appears when you right-click an individual file
- Drop the confirmation dialog, based on the user's setting, for "discard all" because it will only be available when you right-click the header

**Comment by iAmWillShepherd** [comment] 2018-05-24 17:01
> Drop the confirmation dialog, based on the user's setting, for "discard all" because it will only be available when you right-click the header

We actually want to keep it on the file because the context-menu in the header isn't as discoverable, but I think by being more clever, we can only show the discard all option if there are multiple files selected.

 I think ☝️ along with adding a new setting in options will make everyone happy while still protecting us from simple mistakes.

**Comment by cheshire137** [comment] 2018-05-24 17:03
Thanks @iAmWillShepherd! Sorry for the kerfuffle of filing a bug report only for it to end up with an 'enhancement' label. 😅 I genuinely thought something had gone awry in the latest update because I was used to 'discard all' not prompting me before!

**Comment by donokuda** [comment] 2018-05-24 17:53
I think it's okay for the "Discard all changes" to respect the dialog setting as long as we somehow add another step that's the equivalent to us asking "r u rly sure????"

One solution off the top of my head is to never show "Discard All Changes" (except in the header) and leverage the work that's been done for [multi-select](https://github.com/desktop/desktop/pull/4188) with the "Discard x selected changes" action.

<img src="https://user-images.githubusercontent.com/1174461/40502509-0badd1fa-5f40-11e8-84ef-aef4b553d429.png" width="350" />

My assumption is that the workflow for discarding all changes would still be quick if you use the keyboard shortcut for selecting all files (<kbd>cmd/ctrl</kbd> + <kbd>A</kbd>) and then discarding via the context menu.

We can also consider adding a menu option + keyboard shortcut for discarding files (e.g., <kbd>cmd/ctrl</kbd>+<kbd>delete</kbd>) to make this action quicker.

**Comment by shiftkey** [comment] 2018-06-26 11:16
This should be fixed by #4426 (looking at the confirmation setting) and #4855 (context menu should show ellipses when it will prompt). I tested this on 1.2.6 and couldn't reproduce the issue, so I'm going to close this out as resolved. @cheshire137 let us know if you happen to encounter it again.

**Closed by shiftkey** 2018-06-26 11:16 UTC
Labels: enhancement
