### ISSUE TITLE
Sometimes Github Desktop is pushing code directly to main branch.

### ISSUE THREAD

**Issue by ilyas-wm4d** [desktop/desktop#12801] opened 2021-08-18 12:38 UTC
### Describe the bug
I created a branch called  task-685135042-build-the-ui-for-client-records-in-foundation and pushed my code. and saw this message in slack:

1 new commit pushed  to master by ilyas-wm4d
21cc2631 - UI WIP: Client Records

### Version & OS

Windows 10 - 
Version 2.9.0 (x64)

### Steps to reproduce the behavior

1. Clone a repo
2. Create a branch from master/main branch
3. write some code and push.
4. You will see that code is pushed to master/main branch

### Expected behavior

If I created a branch and the Github Desktop should push code to the branch I have created. I created branch through Github Desktop

### Actual behavior

Sometimes Github Desktop is pushing code directly to main branch if we are on other branch.

### Screenshots

![image](https://user-images.githubusercontent.com/74193510/129899014-d1a9a88b-e234-459b-858d-1a82ff163879.png)

![image](https://user-images.githubusercontent.com/74193510/129899142-c494db07-3aca-4e69-b348-d543fb470c4d.png)

### Logs

[2021-08-18.desktop.production.log](https://github.com/desktop/desktop/files/7007214/2021-08-18.desktop.production.log)

### Additional context

I faced this problem on Mac as well.

**Comment by ilyas-wm4d** [comment] 2021-08-18 12:38
I hope screenshots and logs will help.

**Comment by steveward** [comment] 2021-08-18 13:28
@ilyas-wm4d thanks for the report. Can you share the output of `git remote show origin` from the command line (Repository -> Open in <command_line>`)?

**Comment by ilyas-wm4d** [comment] 2021-08-18 13:49
@steveward can we run this command inside Github desktop?

**Comment by ilyas-wm4d** [comment] 2021-08-18 13:49
I created another branch it worked, That issue only happens when clone a repo first time.

**Comment by ilyas-wm4d** [comment] 2021-08-18 13:52
@steveward Here's the output:

* remote origin
  Fetch URL: git@github.com:WM4D/foundation-front-end.git
  Push  URL: git@github.com:WM4D/foundation-front-end.git
  HEAD branch: master
  Remote branches:
    client-records-feature                                                                           tracked
    dev                                                                                              tracked
    master                                                                                           tracked
    revert-120-task-717904936-foundation-ldr-call-report-request-to-have-access-to-call-recording    tracked
    task-681035479-ui-study-and-implement-nightwatchjs-for-e2e-testing                               tracked
    task-684259747-add-lead-source-google-fb-marchex-etc-for-each-lead                               tracked
    task-699332610-cor-add-filter-for-account-manager                                                tracked
    task-702093331-add-procedure-to-the-all-leads-tab                                                tracked
    task-704876107-rename-tabs-in-ldr                                                                tracked
    task-706405088-change-emails-to-forms-in-the-dashboard-graph                                     tracked
    task-706825670-60-day-limit-on-foundation                                                        tracked
    task-710685052-format-lead-phone-in-fb-forms                                                     tracked
    task-710751766-refactor-how-upload-works-in-the-frontend                                         tracked
    task-716076418-show-total-spend-for-facebook-and-adwords-in-ldr                                  tracked
    task-717904936-foundation-ldr-call-report-request-to-have-access-to-call-recording               tracked
    task-718282304-fe-make-sure-file-uploads-are-less-than-50kb                                      tracked
    task-719331450-fix-referrer-column-in-chat-tab                                                   tracked
    task-724407852-remove-phrase-from-downloaded-ldr-reports                                         tracked
    task-729227630-keyword-data-in-ldr-not-coming-through-to-download                                tracked
    task-737863956-freeze-these-columns-on-ldr-so-that-they-stay-in-place-when-scrolled-horizontally tracked
  Local branches configured for 'git pull':
    client-records-feature                                       merges with remote client-records-feature
    master                                                       merges with remote master
    task-685135042-build-the-ui-for-client-records-in-foundation merges with remote master
  Local refs configured for 'git push':
    client-records-feature pushes to client-records-feature (up to date)
    master                 pushes to master                 (up to date)

**Comment by steveward** [comment] 2021-08-18 21:32
@ilyas-wm4d it looks like the refspec for your `task-685135042-build-the-ui-for-client-records-in-foundation` branch is set to pull from `master`:

>task-685135042-build-the-ui-for-client-records-in-foundation merges with remote master

If you want to change this you can run `git config --local --edit` (or open it directly in `.git/config`) and modify the  [branch "task-685135042-build-the-ui-for-client-records-in-foundation"] config to `merge = refs/heads/task-685135042-build-the-ui-for-client-records-in-foundation`.

I'm going to close this out since that seems to be the root cause of this, but let me know if you have any further issues.

**Closed as completed by steveward** 2021-08-18 21:32 UTC
