### ISSUE TITLE
Branch and pull request number will not update if pull request selected

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#3430] opened 2017-11-27 11:54 UTC
When selecting a pull request in the list, the branch and the PR number in the header do not update. 

For example, if `branch_3` contains `pull_request_3`, then both the branch and the `#3` badge should be shown in the header if the user selects `pull_request_3` from the list. 

Currently, the selection in the pull request list is stuck on a random selection and won't update when the user selects a new PR.

<img width="782" alt="screen shot 2017-11-27 at 12 41 23 pm" src="https://user-images.githubusercontent.com/14828183/33265313-70652590-d371-11e7-956c-0fb96b78ff52.png">
<img width="975" alt="screen shot 2017-11-27 at 12 42 42 pm" src="https://user-images.githubusercontent.com/14828183/33265312-7046e99a-d371-11e7-9291-441039c51c51.png">

v1.0.10-beta2,mac

**Comment by joshaber** [comment] 2017-11-27 14:47
Yeah, this is effectively a dupe of #3337.

**Closed by joshaber** 2017-11-27 14:47 UTC
Labels: bug
