### ISSUE TITLE
Deleted and then recreated Github repository can't be cloned

### ISSUE THREAD

**Issue by TheNewJavaman** [desktop/desktop#10923] opened 2020-10-26 21:40 UTC
### Describe the bug

After deleting and then creating another repository with the same name, I couldn't clone the new repository in Github Desktop.

### Version & OS

Windows 10, Github Desktop version 2.5.6

### Steps to reproduce the behavior

1. Create repository online
2. Delete repository online
3. Create new repository using the same name online
4. Attempt to clone the new repository

### Expected behavior

It should clone the repository just fine. 

### Actual behavior

I got the message "We couldn't find that repository. Check that you are logged in, the network is accessible, and the URL or repository alias are spelled correctly."

### Logs

```
2020-10-26T21:38:03.377Z - warn: [ui] fetchRepository: 'MasquitoWasTaken/masquito-backend' returned a 404
2020-10-26T21:38:03.493Z - warn: [ui] fetchRepository: 'MasquitoWasTaken/masquito-backend' returned a 404
2020-10-26T21:38:03.493Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'MasquitoWasTaken/masquito-backend'
2020-10-26T21:38:03.494Z - info: [ui] proxy url not resolved, protocol not supported
2020-10-26T21:38:03.568Z - error: [ui] `git -c credential.helper= clone --recursive --progress -- MasquitoWasTaken/masquito-backend C:\Users\Gabriel Pizarro\Documents\GitHub\masquito-backend` exited with an unexpected code: 128.
stderr:
fatal: repository 'MasquitoWasTaken/masquito-backend' does not exist
```

### Additional context

Check out my repository at https://github.com/MasquitoWasTaken/masquito-backend/, it does exist. I can also manually clone the repo from CLI.

**Comment by TheNewJavaman** [comment] 2020-10-26 21:41
Also, I was able to clone other repositories from the same organization, so credentials shouldn't be the issue.

**Comment by niik** [comment] 2020-10-27 12:55
Hi @TheNewJavaman, could you share step  by step details on how you attempted to clone the repository (i.e through the clone button on GitHub.com, by selecting the repository in the list in the clone dialog, or by manually entering the repository details into the URL tab of the clone dialog). Screenshots would be very helpful, thanks!

**Comment by TheNewJavaman** [comment] 2020-10-27 17:28
Does this work for you @niik?

### Cloning by selecting from my account's repositories list

![Screenshot 2020-10-26 143121](https://user-images.githubusercontent.com/16387264/97338561-c52c8400-183e-11eb-8327-2454aa59d35b.png)

### Cloning from Github.com and URL

![Screenshot 2020-10-27 102629](https://user-images.githubusercontent.com/16387264/97338688-e7260680-183e-11eb-8eb1-ec2e20f34e78.png)

### Cloing using username/repository

![Screenshot 2020-10-27 102726](https://user-images.githubusercontent.com/16387264/97338813-0a50b600-183f-11eb-9c2d-f83207ca5847.png)

**Comment by CaptainJackey** [comment] 2020-11-25 17:57
Look at my reply at #10930 , then you can slove this problem!

**Comment by AndreasTraut** [comment] 2021-02-19 10:22
> 
> 
> Look at my reply at #10930 , then you can slove this problem!

I had the same problem as described above. Seems to be similar to [#10930](https://github.com/desktop/desktop/issues/10930) [#7634](https://github.com/desktop/desktop/pull/7634) and other issues. Thank you @CaptainJackey : your advice solved my problem. I wish I would have found a more "elegant" solution, but de-install, re-install is probably the easiest one for a novice like me.

**Comment by chadmkidner** [comment] 2022-06-09 21:06
> > Look at my reply at #10930 , then you can slove this problem!
> 
> I had the same problem as described above. Seems to be similar to [#10930](https://github.com/desktop/desktop/issues/10930) [#7634](https://github.com/desktop/desktop/pull/7634) and other issues. Thank you @CaptainJackey : your advice solved my problem. I wish I would have found a more "elegant" solution, but de-install, re-install is probably the easiest one for a novice like me.

I have a fresh install of GitHub Desktop and still having this issue. Any other suggestions?

**Comment by chadmkidner** [comment] 2022-06-09 21:12
> > > Look at my reply at #10930 , then you can slove this problem!
> > 
> > 
> > I had the same problem as described above. Seems to be similar to [#10930](https://github.com/desktop/desktop/issues/10930) [#7634](https://github.com/desktop/desktop/pull/7634) and other issues. Thank you @CaptainJackey : your advice solved my problem. I wish I would have found a more "elegant" solution, but de-install, re-install is probably the easiest one for a novice like me.
> 
> I have a fresh install of GitHub Desktop and still having this issue. Any other suggestions?

Nevermind, my issue was that when choosing "Open With GitHub Desktop", it was not entering the entire URL correctly. I added ".git" at the end and cloned successfully.

**Comment by steveward** [comment] 2024-10-14 17:07
I was no longer able to reproduce this issue, so I'm going to close it as resolved. I believe it was likely fixed by the work done in https://github.com/desktop/desktop/pull/16286. If you are still able to reproduce this issue, please let us know and we can investigate further.

**Closed by steveward** 2024-10-14 17:07 UTC
Labels: bug, priority-3
