### ISSUE TITLE
A new branch should reflect the contents of the current branch

### ISSUE THREAD

**Issue by s2t2** [desktop/desktop#11848] opened 2021-03-22 23:16 UTC
### Describe the bug

When you merge a pull request into a repo's main branch, then pull that code locally, when you check out a new branch from the main branch, the new branch should reflect the state of the main branch.

When we do this from the command-line, that is what happens.

However when we do this from GitHub Desktop, it requires us to also click "Update from main" from the branch menu. And then afterwards doesn't do a clean merge.

### Version & OS

GitHub Desktop Version 2.6.6 (verified on both Mac and Windows)

### Steps to reproduce the behavior

1. Merge a Pull Request into your origin repo's main branch.
2. From GitHub Desktop, checkout the main branch. Then fetch origin.
3. From GitHub Desktop, checkout a new branch.
4. ERROR: See the expected contents of the origin main branch are NOT reflected on the new branch as expected.

### Expected behavior

When we create a new branch, it should start with / reflect the contents of the branch we were on when we created it. This mimics the behavior of Git from the command line (i.e. `git checkout main` then `git pull origin main` then `git checkout my-new-branch` will have the most up to date main branch contents on the new feature branch)

### Actual behavior

We found that we needed to click "pull from origin" from the Branch menu in order for the most recent changes to be there. But in that case, it also uses some messy / non-ideal merging.

### Screenshots

The main branch is recent / up to date:

<img width="670" alt="Screen Shot 2021-03-22 at 7 00 18 PM" src="https://user-images.githubusercontent.com/1328807/112068926-444d8c00-8b41-11eb-847c-d6327fce200a.png">

Checkout the main branch:

<img width="402" alt="Screen Shot 2021-03-22 at 7 00 34 PM" src="https://user-images.githubusercontent.com/1328807/112068925-444d8c00-8b41-11eb-900e-c877f05caf77.png">

Create a new branch from the main branch (UPDATE: this is where the problem comes in - the branch is created from upstream without an option to use the origin repo, which is probably what should be used by default, to prevent confusion):

<img width="413" alt="Screen Shot 2021-03-22 at 7 00 54 PM" src="https://user-images.githubusercontent.com/1328807/112068924-43b4f580-8b41-11eb-9061-907e8a33ff36.png">

See it does not have the same up to date state as the main branch:

<img width="492" alt="Screen Shot 2021-03-22 at 7 14 39 PM" src="https://user-images.githubusercontent.com/1328807/112069810-defa9a80-8b42-11eb-8da3-ed5c63f7bf97.png">

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

OH the error is because GitHub desktop wants to start the new branch based on the main branch of the upstream repo, not the user's origin repo.

We can update the repo settings and change the behavior.

**Comment by billygriffin** [comment] 2021-03-23 00:52
Thanks for the issue @s2t2, really appreciate the thorough explanation. It seems like you're using a fork mostly independently of the upstream repository - is that correct? The setting you referenced is that way if you've selected that the primary purpose of your fork is to contribute to upstream, but it seems like you want the opposite setting, shown here.

<img width="605" alt="Screen Shot 2021-03-22 at 6 47 37 PM" src="https://user-images.githubusercontent.com/5091167/112076098-5e866a80-8b3f-11eb-8f6e-0c93fe742efc.png">

As shown in that screenshot for the setting, new branches will be based on your fork's default branch instead of the upstream's default branch. We have this setting in place because we found that most users utilize forks in order to contribute back to upstream and therefore the latest changes on upstream are most relevant for starting work on a new branch, but based on feedback we added the ability to specify your preference when cloning a fork or when creating one.

I think this is intended behavior so I'm going to close this issue, but please let us know if updating that setting doesn't solve it. 😄

**Closed as completed by billygriffin** 2021-03-23 00:52 UTC
