### ISSUE TITLE
GitHub Enterprise Committed

### ISSUE THREAD

**Issue by say25** [desktop/desktop#4329] opened 2018-03-26 01:01 UTC
## Description
GitHub Enterprise committed????

## Version

* GitHub Desktop: 1.1.1-beta4

* Operating system: macOS 10.12.6 (16G1212)

## Steps to Reproduce
1. Merge a PR with GitHub Enterprise

### Expected Behavior
User authored and User committed.

### Actual Behavior
User authored and GitHub Enterprise committed.

<img width="883" alt="screen shot 2018-03-25 at 7 57 02 pm" src="https://user-images.githubusercontent.com/7467062/37882261-52201218-3067-11e8-875b-099e5332de34.png">

**Comment by shiftkey** [comment] 2018-03-26 01:07
@say25 this looks like something has changed with how we detect and render merge commits. Do you know the version of GitHub Enterprise you're currently working with?

**Comment by shiftkey** [comment] 2018-03-26 01:19
I tried to reproduce this on GitHub Enterprise 2.12 and Desktop `1.1.1-beta4` and couldn't see the issue.

Here's what the merge commit looks like:

```shellsession
$ git show HEAD --pretty=full
commit cc286f05dd8020e04b2cdeaded95bd338c1a2e0e
Merge: f4476eb 634f1b0
Author: Brendan Forster <brendan@github.com>
Commit: GitHub Enterprise <noreply@ghe.io>

    Merge pull request #34 from shiftkey/shiftkey-patch-1
    
    hello world
```

This matches up with the rule we have for detecting the webflow committer:

https://github.com/desktop/desktop/blob/d73112a9fc9ca4a953697ae471d3942ae8e07d7b/app/src/models/commit.ts#L119-L122

I gather your setup is slightly different and we're not catching that - can you share what you've got for the `Commit` details of this merge commit?

**Comment by shiftkey** [comment] 2018-03-26 05:55
@say25 aha - the email address is `<ghe-noreply@company.com>` which is slightly different to what we expect. I'll have a chat with our Enterprise support team and get some more context.

**Comment by shiftkey** [comment] 2018-03-26 06:21
@say25 alright, I've confirmed with our GHE support peeps that the `noreply` email address used here is configurable by administrators. It's viewable through the [Retrieve Settings](https://developer.github.com/enterprise/2.12/v3/enterprise-admin/management_console/#retrieve-settings) API but this is only visible from the admin port, so it's not something we can check as mere mortal users:

`https://api_key:your-amazing-password@hostname:admin_port/setup/api/settings`

Without that extra context here, I think the best action here is to relax the check to:

```ts
 if (this.committer.name === 'GitHub Enterprise') { 
   const host = new URL(endpoint).host.toLowerCase() 
   return email.endsWith(`@${host}`)
 }
```

cc @desktop/core for any additional ideas here

**Comment by shiftkey** [comment] 2018-05-02 05:01
Marking this as `help wanted` because I think that's the best workaround we can do currently.

**Comment by say25** [comment] 2018-05-02 05:25
@shiftkey I don’t mind taking the above on and testing it with my commit history to verify it improves

**Comment by say25** [comment] 2018-05-03 04:49
@shiftkey, Did some research turns out the problem is that the repo is not being picked up as a GitHubRepository. :/

**Comment by shiftkey** [comment] 2018-07-03 18:51
>  the repo is not being picked up as a GitHubRepository

@say25 there's a couple of things that I'd like to understand:

 - as a sanity check, can you confirm you're signed into your GitHub Enterprise account?
 - are you able to push and pull fine from Desktop with that repository? If so, maybe we are able to associate these two correctly in one place but not another?

To associate a repository with an account, we use the `endpoint` associated with your account. You can see it here in the dev tools under the **Application** and **Local Storage** section:

![](https://user-images.githubusercontent.com/359239/42238586-c0cd6954-7ed7-11e8-8cca-c7549cfb9826.png)

My best guess here is that the remote for your GHE repository is out of sync with that `endpoint` value, and so we never match up the two accounts. This is the function that we use to try and map a repository to it's account:

https://github.com/desktop/desktop/blob/710bf66eec589061991618e1d41d9386608a77c1/app/src/lib/repository-matching.ts#L31-L43

**Comment by say25** [comment] 2018-07-03 19:32
Yea I am signed in. Yea I can commit. Havent run into this in a while... Ill see if I can reproduce soonish

**Comment by shiftkey** [comment] 2018-07-03 20:06
@say25 I'm inclined to just get that patch in and see how it feels, because it's a relatively safe change

**Closed** 2018-07-06 14:44 UTC
Labels: bug
