### ISSUE TITLE
Bug after cloning an empty repository?

### ISSUE THREAD

**Issue by N0star** [desktop/desktop#9713] opened 2020-05-06 14:16 UTC
### Describe the bug

Fetch origin button is showing a message "Cannot publish unborn HEAD" after cloning a fully empty repository from GitHub. Commiting any change to it locally, like creating an empty file, seems to resolve this issuse, even aftar said file is deleted later. It's not possible to create branches meanwhile, neither by shortcut nor "branch" section from the top menu. Only trying to manage that by drop-down menu "Current branch" shows the message "Your current branch is unborn..." oh! Thanks, now that makes sense, I wish I knew it earlier tho, like when I first hit Ctrl+Shift+N and nothing happened...

### Version & OS

GitHub Desktop: 2.4.3, OS: win10pro 10.0.18363.

### Steps to reproduce the behavior

1. Create a fresh empty repository on GitHub.
2. Clone it into GitHub Desktop.

### Actual behavior

"Cannot publish unborn HEAD" is showing in place of expected "Fetch origin; Never fetched" button. The button is inactive, so the only way to update repository is via deleting it and cloning again.

### Screenshots

![mcp](https://user-images.githubusercontent.com/64681977/81176734-dab6a480-8fa5-11ea-8d4a-f1e2f379ac2e.png)

### Additional context

I guess cloning an empty repository and creating branches from it might not be a real issuse, however for new users (including myself) it might be a little confusing, It took me some time wondering, if I got anything wrong with a procedure of cloning...

It's my first issue btw. so please go easy on me uwu

**Comment by steveward** [comment] 2020-05-06 16:41
@N0star thanks for the report. This is the expected behavior -- Git shows the `unborn HEAD` error when there are no commits on your current branch. This is why GitHub gives you the option to initialize your repository during creation (and GitHub Desktop automatically does this). There probably are ways we could provide guidance to users who hit this specific situation, but it isn't something that we've seen occur very often since most users initialize their repositories via github.com or GItHub Desktop. 

I'm going to close this out but we can continue to track feedback about this in this issue. Thanks for using GitHub Desktop!

**Closed by steveward** 2020-05-06 16:41 UTC
