### ISSUE TITLE
Error: spawn chcp ENOENT     at exports._errnoException (util.js:1050:11)     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)     at onErrorNT (internal/child_process.js:367:16)     at _combinedTickCallback (internal/process/next_tick.js:80:11)     at process._tickCallback (internal/process/next_tick.js:104:9)

### ISSUE THREAD

**Issue by kaderhussain** [desktop/desktop#2698] opened 2017-09-12 16:44 UTC
### Description

[Description of the issue]

### Version

**GitHub Desktop version:** [version here]

**OS version:** [version here]

### Steps to Reproduce

1. [First step]
1. [Second step]
1. [and so on]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by lynxcode** [comment] 2017-09-12 16:46
Error: spawn chcp ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Version: 0.8.1
OS: Windows 6.3.9600

**Comment by joshaber** [comment] 2017-09-12 16:54
Thanks @kaderhussain and @lynxcode! This is a duplicate of https://github.com/desktop/desktop/issues/2678, so I'm gonna close this.

This should be fixed in the next update.

**Closed by joshaber** 2017-09-12 16:54 UTC
