### ISSUE TITLE
When I focus GitHub Desktop, it's in a weird full-screen-like mode that makes it hard to use.

### ISSUE THREAD

**Issue by Monsoonexe** [desktop/desktop#14136] opened 2022-03-10 02:23 UTC
### Describe the bug
When the app focuses, the app is in a weird full-screen-like state that makes it hard to use. The window control buttons (3 buttons in the top-right corner) are not visible and the Commit box (description, summary, and commit button) are not visible on the screen.

### Version & OS

Version 2.9.11 (x64)
Windows 10.

### Steps to reproduce the behavior

1. Maximize GitHub Desktop (not full screen).
2. Minimize GitHub
3. Reopen GitHub (click on icon in task bar)
4. Notice that the screen looks full screen but is missing controls.

### Expected behavior

I expect the window to look the same when I open it each time -- not in janky full-screen mode.

### Actual behavior

The window is missing controls like window controls (3 buttons in top-right) and the commit box is missing.

### Screenshots

![image](https://user-images.githubusercontent.com/43690629/157575623-a013d7d9-ae7a-49ba-aa26-62cda1191f2f.png)

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

### Additional context

I'm using two monitors on a laptop. This issue only happens on my primary monitor, which is not the screen attached to the laptop.

**Comment by tsvetilian-ty** [comment] 2022-03-10 08:37
👋  @Monsoonexe, your issue looks like a duplicate of this one #13940. 
Can you check if your monitors have different scale levels?

**Closed as completed** 2022-03-18 14:21 UTC
Labels: more-info-needed

**Comment by pkillman2000** [comment] 2025-06-14 14:58
I had the same problem.  As it turns out, GitHub Desktop was in Fullscreen mode.  By pressing F11, I was able to get the menu bar, min, max, close controls, and task bar back.

**Comment by rujbodyslam** [comment] 2025-06-14 15:02
> ### Describe the bug
> When the app focuses, the app is in a weird full-screen-like state that makes it hard to use. The window control buttons (3 buttons in the top-right corner) are not visible and the Commit box (description, summary, and commit button) are not visible on the screen.
> 
> ### Version & OS
> 
> Version 2.9.11 (x64)
> Windows 10.
> 
> ### Steps to reproduce the behavior
> 
> 1. Maximize GitHub Desktop (not full screen).
> 2. Minimize GitHub
> 3. Reopen GitHub (click on icon in task bar)
> 4. Notice that the screen looks full screen but is missing controls.
> 
> ### Expected behavior
> 
> I expect the window to look the same when I open it each time -- not in janky full-screen mode.
> 
> ### Actual behavior
> 
> The window is missing controls like window controls (3 buttons in top-right) and the commit box is missing.
> 
> ### Screenshots
> 
> ![image](https://user-images.githubusercontent.com/43690629/157575623-a013d7d9-ae7a-49ba-aa26-62cda1191f2f.png)
> 
> 
> ### Logs
> 
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.
> 
> ### Additional context
> 
> I'm using two monitors on a laptop. This issue only happens on my primary monitor, which is not the screen attached to the laptop.
>
