### ISSUE TITLE
Desktop assosiate with OLD archived Projects on GitHub

### ISSUE THREAD

**Issue by Morons** [desktop/desktop#12221] opened 2021-05-16 15:10 UTC
I re-named and archived a Git months ago but when I re-factored the Application with the Original name the Desktop link to Github (View on GitHub.com) point me to the Archived version
I did remove my Android Studio Setting for Git and also deleted the .git before I added the local project back into Git (GitHub Desktop)
Also the the "Current Repository" name changed to the Archived one!
However a New Project with the corret name was also created on GitHub.com, but the repository does not point to it!
This is stupid as the Archived repository is Read-Only and the updates will most probably land in the correct place

### Version & OS

Version 2.8.1
Android Studio 4.2.1
Build #AI-202.7660.26.42.7351085, built on May 10, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 12
Registry: ide.windowSystem.autoShowProcessPopup=true, external.system.auto.import.disabled=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.intellij.marketplace, com.thoughtworks.gauge, wu.seal.tool.jsontokotlin, org.jetbrains.kotlin, org.intellij.plugins.markdown

### Logs

```
2021-05-16T14:37:07.552Z - info: [ui] [AppStore] adding repository at D:\Development\AndroidStudioProjects\MarketingApp to store
2021-05-16T14:45:38.960Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 6.858s)
2021-05-16T14:45:49.906Z - info: [ui] Executing createCommit: git commit -F - (took 10.942s)
2021-05-16T14:45:50.399Z - info: [ui] [Timing] Action 'create commit' for 'MarketingApp' took 18.380s
2021-05-16T14:46:10.707Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 2.4s of which 0.0s paused, total 2.4s
2021-05-16T14:46:34.079Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master --set-upstream --progress (took 3.859s)
2021-05-16T14:46:35.690Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.560s)
2021-05-16T14:46:36.395Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-05-16T14:46:53.652Z - info: [ui] calling captureCommandOutput(where git)
2021-05-16T14:47:50.283Z - info: [main] opening in browser: https://github.com/Morons/MarketingApp-2020-12-22
```

**Comment by sergiou87** [comment] 2021-05-17 10:56
Thank you for your report @Morons!

If I understand correctly, you renamed the old repository, and then created a new one with the name the archived repository used to have. If so, I think this issue is a duplicate of #11448

I'm gonna close it in favor of that one, I recommend you to subscribe to #11448 to get notified when we do any work on it.

If you think my assessment is wrong, please let me know and I'll reopen this issue 😄

**Closed as completed by sergiou87** 2021-05-17 10:56 UTC
