### ISSUE TITLE
Feature: Selecting multiple changed files at once

### ISSUE THREAD

**Issue by git-ced** [desktop/desktop#9644] opened 2020-04-28 13:20 UTC
### Describe the feature or problem you’d like to solve

There are times where I need to select multiple file changes at once. This often happen when i got focused in developing and forgot to commit. What i do is i deselect all of the changed files, then select necessary changed files to commit them by batch e.g (Add x component, Remove unnecessary imports, ...). It would be great to have a feature where i can select multiple changed files (ofc, those who are next to each other) instead of selecting them one by one.

### Proposed solution

Utilize shift key or click one changed file then dragging it down or up.

### Additional context

As of now, when I'm using shift, it results to this...

<img height="280" alt="image" src="https://user-images.githubusercontent.com/46030248/80491621-8b64e880-8995-11ea-9ba2-5b4e0ff4eaed.png">

What I'm expecting is this...

<img height="280" alt="image" src="https://user-images.githubusercontent.com/46030248/80491914-e991cb80-8995-11ea-8be6-e5b0bc973e0b.png">

**Comment by billygriffin** [comment] 2020-04-28 16:59
@git-ced Thanks for the issue. Which OS and Desktop version are you using? 

When I follow your repro steps on macOS, deselecting all the files, then clicking the top one and shift+clicking some lower one, and hitting space bar, the files that were selected are also all checked to be committed. I can also select an arbitrary subset of files in the same way by using Cmd+click to select the files I want, then spacebar to check them as files I want to commit.

Let us know if there's something different you're doing, and thanks!

**Comment by git-ced** [comment] 2020-04-29 02:49
I'm using Desktop 2.4.3 on macOs. Hitting spacebar worked for me, thanks!

**Comment by billygriffin** [comment] 2020-04-29 03:26
Great, thanks for the quick followup! Glad to hear it’s resolved!

**Closed by billygriffin** 2020-04-29 03:26 UTC
Labels: more-info-needed

**Comment by mrchantey** [comment] 2021-07-01 10:23
Awesome to see this is possible, although it does still seem the expected behaviour when using a mouse to check / uncheck a single file is that it would apply to all selected files.

**Comment by Nicknaem** [comment] 2021-09-13 08:14
> Awesome to see this is possible, although it does still seem the expected behaviour when using a mouse to check / uncheck a single file is that it would apply to all selected files.

I totally agree

**Comment by absop** [comment] 2022-01-29 06:06
I am using the latest version of Github Desktop on Windows 10, and I'm having the same problem.
![image](https://user-images.githubusercontent.com/32818900/151649776-02de9526-34ae-44ae-8210-09ee1a1b7b63.png)
![image](https://user-images.githubusercontent.com/32818900/151649787-e32fb23f-6d04-43ca-924f-f6e681ea0c48.png)

**Comment by Almighty-Show711** [comment] 2024-10-13 18:18
> I am using the latest version of Github Desktop on Windows 10, and I'm having the same problem. ![image](https://user-images.githubusercontent.com/32818900/151649776-02de9526-34ae-44ae-8210-09ee1a1b7b63.png) ![image](https://user-images.githubusercontent.com/32818900/151649787-e32fb23f-6d04-43ca-924f-f6e681ea0c48.png)

I am on the latest GitHub Desktop and this works for me.

Just to confirm it, you need to click one item, then press shift and click another one up to the latest one you want to commit. Then, click space and it should select all the ones inbetween.
