### ISSUE TITLE
Unable to Locate Repository When Switching to a Branch with Submodule

### ISSUE THREAD

**Issue by codelin-imu** [desktop/desktop#17580] opened 2023-10-18 14:42 UTC
### The problem

When attempting to switch to a branch that contains a submodule, GitHub Desktop is (on switch) unable to locate the repository, causing my desktop app to brick showing the relocate button. However, when I first switch using the terminal, this problem does not occur.

Error: 
fatal: not a git repository: ../../.git/modules/path/to/submodule
fatal: could not reset submodule index

### Release version

3.3.3 (x64)

### Operating system

macOs 13.2.1 (22D68)

### Steps to reproduce the behavior

1. Switch to branch with submodule

**Comment by steveward** [comment] 2024-10-18 14:57
Closing as a duplicate of https://github.com/desktop/desktop/issues/18673. Please follow along there for updates.

**Closed as not planned by steveward** 2024-10-18 14:57 UTC
