### ISSUE TITLE
Clicking "Undo" button doesn't populate summary field

### ISSUE THREAD

**Issue by elias6** [desktop/desktop#6390] opened 2018-12-11 01:32 UTC
## Description
I have been using GitHub Desktop for months, and overall I've liked it, but something has been acting funny for the last week or two.

Before, whenever I clicked the "Undo" button to undo a commit, the summary and description fields get populated with the description of that commit.

But now, they don't always get populated. It seems to work for a while, and then stop working, seemingly at random. If I restart GitHub Desktop, it starts working again for a while, then randomly stops again.

Before, I could easily make small changes to my latest commit, like running `git commit --amend` from the command line. But now, I have to re-type the summary and description, which can be especially annoying if those things are long, or if I simply don't remember the description I had.

I'd like to see the old behavior, where the inputs are populated every time the "Undo" button is clicked.

## Version
* GitHub Desktop: 1.5.0
* Operating system: macOS 10.13.6

## Steps to Reproduce
Make a commit, then click the "Undo" button. You may need to try this several times, possibly after GitHub Desktop has been running for several hours.

### Expected Behavior
The commit message does not always show in the summary field.

### Actual Behavior
The commit message should always show in the summary field.

### Logs
I am afraid to attach my log file because it may contain sensitive company information. Sorry. I may try to reproduce this on my home laptop, but I can't promise that I will have time any time soon, or be able to reproduce it at all.

**Comment by billygriffin** [comment] 2018-12-11 01:40
@elias6 Thanks so much for letting us know, and sorry that's happening! That's definitely not intended and I don't remember seeing other issues for it. It sounds like it may be related to the state of the application given that it works sometimes but not others.

To confirm, it just started happening in the past couple weeks, but previously worked totally fine? Are there any characteristics of the repo(s) you've been working in that are different from before the problem started happening? @desktop/support I'm curious if you've seen this elsewhere.

**Comment by elias6** [comment] 2018-12-11 05:54
I have to say that I don't remember for sure how long it has been
happening. Maybe it was longer than 2 weeks, but it has only been happening
for a small part of the time that I've been using (the redesigned) GitHub
Desktop. I think the behavior could have been caused by a recent update,
but I don't really have any evidence to back that up.

I am not aware of anything unusual we did with our repos. We started using
Prettier with commit hooks. Other than that, I can't think of any other
major changes to the repos, besides the usual kind of commits, pushes, and
merges. And I think this started happening well after we started using
Prettier but I don't remember for sure.

**Comment by elias6** [comment] 2018-12-11 17:46
I tried reproducing this on my home laptop by leaving GitHub Desktop open for a few hours, then spending a few minutes making commits and undoing them. I couldn't reproduce it.

**Comment by billygriffin** [comment] 2018-12-11 17:48
Agh, that's so frustrating @elias6. Unpredictable bugs are the worst. ❤️ @desktop/support Any other ideas here on how we can help track down the cause?

**Comment by tierninho** [comment] 2018-12-11 17:53
I believe the the recent work [here](https://github.com/desktop/desktop/pull/6018) and [here](https://github.com/desktop/desktop/pull/6037) around this area has changed the logic. 

Going to try to reproduce this in the meantime.

**Comment by elias6** [comment] 2018-12-11 17:56
Just now, I clicked "Undo" and it was fine. I made a small change and committed it. Then I clicked "Undo" again and the message didn't show up. I am looking at `~/Library/Application Support/GitHub Desktop/logs/2018-12-11.desktop.production.log` and I don't see anything that looks like an error or anything unusual from the last few minutes.

**Comment by elias6** [comment] 2018-12-11 17:56
I just switched back to GitHub Desktop and now I see this in the log:
```
2018-12-11T17:56:02.449Z - warn: [ui] fetchRepository: an error occurred for 'AutoFi/my_repo'
Error: Server Error
    at Object.t.parsedResponse (/webpack:/app/src/lib/http.ts:161:4)
    at <anonymous>
```
(with the real repo name in place of `my_repo`). I have no idea whether this is related to my problem.

**Comment by tierninho** [comment] 2018-12-11 18:06
So confirming there is some inconsistent behavior as follows:

Commit with "hello" summary
<img width="248" alt="screen shot 2018-12-11 at 9 59 24 am" src="https://user-images.githubusercontent.com/14828183/49820056-c4aea100-fd2b-11e8-8b23-9d921ac3ad88.png">

Committed...
<img width="246" alt="screen shot 2018-12-11 at 9 59 39 am" src="https://user-images.githubusercontent.com/14828183/49820058-c5473780-fd2b-11e8-9182-3563884a6af2.png">

Clicking `undo` shows "hello" message back in summary field
<img width="249" alt="screen shot 2018-12-11 at 9 59 50 am" src="https://user-images.githubusercontent.com/14828183/49820059-c5473780-fd2b-11e8-8935-b592ddf70135.png">

Committing again, all looking normal...
<img width="248" alt="screen shot 2018-12-11 at 10 00 02 am" src="https://user-images.githubusercontent.com/14828183/49820061-c5473780-fd2b-11e8-8071-2572a61d41b6.png">

`Undo` commit and we see that summary is now `update [file-name]` (and dimmed)
<img width="251" alt="screen shot 2018-12-11 at 10 00 10 am" src="https://user-images.githubusercontent.com/14828183/49820062-c5473780-fd2b-11e8-9c88-b68f631f9779.png">

commit and `undo` again and we see summary is now `update [file-name]` (and NOT dimmed)
<img width="245" alt="screen shot 2018-12-11 at 10 00 23 am" src="https://user-images.githubusercontent.com/14828183/49820063-c5dfce00-fd2b-11e8-89c8-a42c7808cf97.png">

**Comment by billygriffin** [comment] 2018-12-11 19:40
Thanks @tierninho, based on the above, I'm going to classify this issue as a bug and pri-2. Seems like whomever takes it on will need to do a bit more investigation in how it's manifesting but seems like there's enough here to demonstrate a broader issue.

**Comment by elias6** [comment] 2018-12-12 07:31
I just clicked the "Undo" button on GitHub Desktop, on my home laptop (running version 1.5.0 and macOS 10.12.6), and I did not see the commit message show up. This is in my personal repo, which is not on GitHub, and not using Prettier or any commit hooks.

I left GitHub Desktop running since last night, and did not interact with it at all today, besides command-tabbing to it and pressing the "Undo" button once.

**Comment by elias6** [comment] 2018-12-13 22:58
I made a discovery. If I go to the "History" tab, then go back to the "Changes" tab, then immediately click "Undo", I don't see the bug. The text populates like it is supposed to.

It don't know for sure whether this has anything to do with the bug, but I noticed that it hasn't happened a single time immediately after going to the "Changes" tab, as far as I can remember. I've been working around the bug by going to "History" and back to "Changes" before clicking "Undo", and my workaround seems to work (although it is awkward).

**Comment by billygriffin** [comment] 2018-12-14 00:14
Thanks @elias6, that is awkward but glad it's working for you pretty reliably. Because we're trying to get 1.5.1 out before the holidays I don't expect that this will be worked on for at least the next few weeks, but the fact that it's a `priority-2` bug should mean it'll get looked at before too long as that's an indication that it's a pretty meaningful bug for us to fix.

If someone from the community wants to take a look at this in the mean time, please feel free to do so (and let us know if you plan to)! I'll add `help wanted` until someone on our team can pick it up.

**Comment by elias6** [comment] 2018-12-15 05:39
I think I can deal with my workaround for a few more weeks. Thank you for responding to my issue.

**Comment by humphd** [comment] 2019-02-24 21:17
I spent some time looking into this today, and was able to bisect it back to https://github.com/desktop/desktop/commit/6b9ca6cb7cdc12d6bdda4285874c1d4d813c3e61, which was part of https://github.com/desktop/desktop/pull/6037.

It stems from [the way the `props` check happens in `componentDidUpdate()` of `CommitMessage`, specifically](https://github.com/desktop/desktop/blob/development/app/src/ui/changes/commit-message.tsx#L140):

```diff
-if (prevProps.commitMessage !== this.props.commitMessage) {
+if (!shallowEquals(prevProps.commitMessage, this.props.commitMessage)) {
```

When this bug happens, and the commit message `summary` is lost, reference equality for these two `props` Objects is different *but* value equality is the same.  So `shallowEquals()` rightly says that `prevProps.commitMessage` and `this.props.commitMessage` are the same, since the values for `summary` and `description` is the same.

If I revert this change, the bug is fixed, and even though the state should be the same (values are the same on previous and current), it forces an update, and whatever code that triggers to show the correct value.

I notice in https://github.com/desktop/desktop/pull/6037#discussion_r229748708 @shiftkey suggested the use of `shallowEquals()` here to reduce the number of `setState()` calls.  I don't work with react often enough to know what the right fix is, other than this switch back to reference equality.  If @shiftkey or @outofambit have suggestions, I'd be willing to finish this.  If they'd rather take it over, that's fine too.

Let me know if I can help further.  I wanted to do a walkthrough bug fix with my open source students, and picked this one so I could write it up.

**Comment by shiftkey** [comment] 2019-02-25 16:31
This is some great context @humphd, thanks for digging into it! 

For the sake of completeness I'd love to nail down this scenario as a regression test to go with reverting this change - this code area is already a bit thorny, so maybe this is a chance to review this area and improve our test coverage.

Are you able to capture an example commit message that you see fails with `shallowCompare` but works with `!==`? This will make it easier to see the same behaviour you are, without needing to run the app up.

Here's a test scaffold to help get this in as an automated test:

```diff
diff --git a/app/test/unit/compare-commit-message-test.ts b/app/test/unit/compare-commit-message-test.ts
new file mode 100644
index 000000000..d4e442c5d
--- /dev/null
+++ b/app/test/unit/compare-commit-message-test.ts
@@ -0,0 +1,19 @@
+import { ICommitMessage } from '../../src/models/commit-message'
+import { shallowEquals } from '../../src/lib/equality'
+
+describe('can correctly detect different commit messages', () => {
+  // TODO: what shape of data are we working with
+  const prev: ICommitMessage | null = null
+  const next: ICommitMessage | null = null
+
+  it('fails with shallowCompare', () => {
+    const result = shallowEquals(prev, next)
+    expect(result).toBe(false)
+  })
+  it('works with triple equals', () => {
+    it('fails with shallowCompare', () => {
+      const result = prev !== next
+      expect(result).toBe(false)
+    })
+  })
+})
```

Feel free to adapt this scaffolding to suit the scenario you need.

**Comment by humphd** [comment] 2019-02-25 17:00
I think `shallowEquals` is working correctly, and there's no regression with respect to how it works here.  Here's what I see in the debugger when this bug happens:

```
> prevProps.commitMessage
{summary: "z", description: ""}
> this.props.commitMessage
{summary: "z", description: ""}
> prevProps.commitMessage === this.props.commitMessage
false
> shallowEquals(prevProps.commitMessage, this.props.commitMessage)
true
```

The two `commitMessage` Objects are different, but with equal key/value pairs, such that `===` says they aren't the same (reference), but `shallowEquals` says they are the same (shape/keys/values).

My react knowledge is limited here, but my theory is that this code relies on the fact that the `commitMessage` Object has changed (reference), and by explicitly forcing `setState` to happen (even though the values are the same), it triggers a re-render somehow.  The contents of the `input` get cleared [here](https://github.com/desktop/desktop/blob/development/app/src/ui/changes/commit-message.tsx#L209).

Probably there is another bug deeper in this code, and this is just exposing some kind of state issue.

Do you want me to create a PR that fixes this in the meantime, and maybe someone can audit this state code more fully elsewhere?

**Comment by shiftkey** [comment] 2019-02-25 17:30
@humphd I'm happy to dig into this and provide some more React context about what's happening here (versus what should be happening).

Once we've clarified that we can figure out what the right fix looks like.

**Comment by humphd** [comment] 2019-02-27 18:22
I've finished [my walkthrough write-up of this bug to do with my students next week](https://github.com/humphd/desktop/tree/good-first-experience-issue-6390#walkthrough-fixing-a-bug-in-github-desktop).  Sorry I wasn't able to get it figured out 100%, but I think it will help them learn a bunch of debugging skills regardless.

After my comments above, I also played with another approach to the fix, using `componentWillReceiveProps()` to copy the commit message values off of `props` and into the mirrored internal `state`.  This also fixes the bug: the summary was cleared internally (`state`) after the commit, but now it's copied in again when the repo state changes:

```diff
diff --git a/app/src/ui/changes/commit-message.tsx b/app/src/ui/changes/commit-message.tsx
index c930de14d..b7e77f2f9 100644
--- a/app/src/ui/changes/commit-message.tsx
+++ b/app/src/ui/changes/commit-message.tsx
@@ -21,7 +21,6 @@ import { showContextualMenu } from '../main-process-proxy'
 import { Octicon, OcticonSymbol } from '../octicons'
 import { IAuthor } from '../../models/author'
 import { IMenuItem } from '../../lib/menu-item'
-import { shallowEquals } from '../../lib/equality'
 import { ICommitContext } from '../../models/commit'

 const addAuthorIcon = new OcticonSymbol(
@@ -122,6 +121,20 @@ export class CommitMessage extends React.Component<
     this.props.dispatcher.setCommitMessage(this.props.repository, this.state)
   }

+  public componentWillReceiveProps(nextProps: ICommitMessageProps) {
+    const { commitMessage } = nextProps
+    if (!commitMessage) {
+      return
+    }
+
+    if (commitMessage !== this.props.commitMessage) {
+      this.setState({
+        summary: commitMessage.summary,
+        description: commitMessage.description,
+      })
+    }
+  }
+
   public componentDidUpdate(prevProps: ICommitMessageProps) {
     if (
       this.props.autocompletionProviders !== prevProps.autocompletionProviders
@@ -136,17 +149,6 @@ export class CommitMessage extends React.Component<
     if (this.props.focusCommitMessage) {
       this.focusSummary()
     }
-
-    if (!shallowEquals(prevProps.commitMessage, this.props.commitMessage)) {
-      if (this.props.commitMessage) {
-        this.setState({
-          summary: this.props.commitMessage.summary,
-          description: this.props.commitMessage.description,
-        })
-      } else {
-        this.setState({ summary: '', description: null })
-      }
-    }
   }

   private clearCommitMessage() {
```

I remain unclear on the best way to achieve things in React, so this may be wrong.  If it's close, I'd be happy to open a PR.  If not, I'll probably let someone with more knowledge of the code recommend something.

Your code is fun to work on, and the docs are great.

**Comment by shiftkey** [comment] 2019-02-27 18:40
That's an amazing writeup @humphd! I'd love to hear if you have any suggestions to make this experience better for external contributors.

> I remain unclear on the best way to achieve things in React, so this may be wrong.

This seems fine based on the [relevant React docs](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops):

>> If you need to update the state in response to prop changes (for example, to reset it), you may compare `this.props` and `nextProps` and perform state transitions using `this.setState()` in this method.

> If it's close, I'd be happy to open a PR.

I haven't been able to trip this issue personally despite my best efforts, but I've got objections to reviewing a PR to try and resolve this.

**Comment by humphd** [comment] 2019-02-27 19:06
@shiftkey thanks for your encouragement.  I've opened #6969 based on my diff above.

**Closed** 2019-03-18 16:11 UTC
Labels: bug, help wanted, priority-2

**Comment by elias6** [comment] 2019-04-29 20:22
Does anyone have any estimate as to when this will be fixed? I am still experiencing it today in GitHub Desktop 1.6.5.

**Comment by shiftkey** [comment] 2019-04-29 21:07
@elias6 this has been fixed on our beta channel since `release-1.7.0-beta1`, but I'm not sure when we'll make that available to production...

**Comment by elias6** [comment] 2019-05-01 17:56
Thanks for replying. I'm looking forward to the fix.

**Comment by elias6** [comment] 2019-05-16 00:00
I noticed a fix for this bug mentioned in the [release notes for 1.6.6](https://desktop.github.com/release-notes/). I haven't seen it since I upgraded a few hours ago. Thank you. If I notice it again, I'll post about it here.
