### ISSUE TITLE
branch change time showing 'last month' when it is the last day of the month

### ISSUE THREAD

**Issue by keaton4422** [desktop/desktop#19478] opened 2024-10-31 22:08 UTC
### The problem

![image](https://github.com/user-attachments/assets/97b4da61-b092-4b1b-8f6c-152ef61f2861)
I saw this around 4pm my time, these changes happened within the last two weeks

### Release version

Version 3.4.8 (x64)

### Operating system

Windows 11

### Steps to reproduce the behavior

open project, find a branch with recent changes, and youll see 'last month' which isnt correct yet.

### Log files

[2024-10-31.desktop.production.log](https://github.com/user-attachments/files/17593833/2024-10-31.desktop.production.log)

### Screenshots

![image](https://github.com/user-attachments/assets/d5ea1ab6-3ae3-4bca-995e-7d39e5e9f597)

**Comment by steveward** [comment] 2024-11-08 22:25
@keaton4422 thanks for the report. What was the exact local date when you were seeing the `last month`? Was it on October 31, or November 1?

**Comment by keaton4422** [comment] 2024-11-08 22:39
@steveward it was on Oct 31st still for my timezone

**Comment by steveward** [comment] 2024-11-13 22:13
@keaton4422 thanks. I manually adjusted the system date and time, but was unable to reproduce the issue. I made some changes that were committed on 10/15 and then tested out 10/31 and 11/1, and both said 17 and 18 days ago for the relative date.

If you're able to reproduce this by adjusting your date and time let me know.

**Comment by keaton4422** [comment] 2024-11-14 03:12
@steveward It may have just been a random bug, hopefully it was just one of those. Thanks for your time!

**Comment by steveward** [comment] 2024-11-14 13:51
👍🏻 I'll close this out, but let me know if you run into this again.

**Closed as completed by steveward** 2024-11-14 13:51 UTC
