### ISSUE TITLE
hangs often

### ISSUE THREAD

**Issue by Shawn-in-Tokyo** [desktop/desktop#4290] opened 2018-03-20 14:21 UTC
## Description
 
Painfully slow.  Repeatly and frequently hangs for 10, 20, 30 seconds

## Version
 
* GitHub Desktop:

V1.1.0
V1.1.1

* Operating system:

OSX 10.13.3

## Steps to Reproduce

Any normal use.  Trying to select anything in the menu.  Even entering in a comment for a commit will freeze mid typing.  Other programs in the OS are running fine.

### Expected Behavior

Just normal UI interaction should work without too much of a wait

### Actual Behavior

Hangs

## Additional Information
 
Signed in via github.com account
Private repo
Command line usage is unaffected

### Logs
[2018-03-20.desktop.production.log](https://github.com/desktop/desktop/files/1829689/2018-03-20.desktop.production.log)

**Comment by tierninho** [comment] 2018-03-20 17:24
@Shawn-in-Tokyo Thanks for filing. Can you provide some additional details so our team can help diagnose. Were you logged in under a GitHub.com or Enterprise account?

**Comment by shiftkey** [comment] 2018-03-20 23:29
@Shawn-in-Tokyo thanks for the log. The logs contain tracing information for how long Git operations take, and it looks like some common operations (like `git status`) start out taking ~1s - which isn't unexpected for repositories with a complex working directory hierarchy:

```
2018-03-20T00:16:06.203Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 1.074s)
```

But hours later, this operation takes almost 90s:

```
2018-03-20T13:44:46.891Z - info: [ui] Executing getStatus: git status --untracked-files=all --branch --porcelain=2 -z (took 84.516s)
```

So maybe there's some interesting details about the repository you are using at the time that we're not handling well. @Shawn-in-Tokyo can you share any details about the repository you were working with at the time you were seeing the issue? If it's a repository I'm able to access, it will help with identifying the issue.

Other operations that shouldn't depend on the repository shape also seem to be caught up in this, such as the operation to get the identity for the current repository:

```
2018-03-20T11:19:52.535Z - info: [ui] Executing getAuthorIdentity: git var GIT_AUTHOR_IDENT (took 27.515s)
```

So maybe some latency issues with long-running Git operations are cascading?

**Comment by Shawn-in-Tokyo** [comment] 2018-03-21 02:18
@tierninho Logged in under a GitHub.com account.

> can you share any details about the repository you were working with at the time you were seeing the issue?

I'm still seeing the issue 12 hours after doing anything.  Any interaction with the GitHub UI causes a "GitHub Desktop Helper" process to max out the CPU (one of eight actually) at 100% for sometime and it's unresponsive during the hang (10+ seconds ).  That was after a restart.  

The only unusual thing I've done recently is cancel some ant builds (with eclipse) that were tagging releases.   I think the command was push origin :refs/tags/whatever . A dialog box popped up for GitHub authentication and I was abandoning the process then.   Again that was an Ant build process being run in Eclipse which calls jgit.sh to run the git commands.

At one point, I tried to discard some change in GitHub Desktop but was told the file or repo was locked (perhaps by another git process).  I couldn't find anything else running and deleted index.lock as suggested in the error message.

**Comment by batarmanrookie** [comment] 2018-03-21 02:37
Envoyé de mon iPhone

Le 20 mars 2018 à 22:18, Shawn-in-Tokyo <notifications@github.com<mailto:notifications@github.com>> a écrit :


@tierninho<https://github.com/tierninho> Logged in under a GitHub.com<http://GitHub.com> account.

can you share any details about the repository you were working with at the time you were seeing the issue?

I'm still seeing the issue 12 hours after doing anything. Any interaction with the GitHub UI causes a "GitHub Desktop Helper" process to max out the CPU (one of eight actually) at 100% for sometime and it's unresponsive during the hang (10+ seconds ). That was after a restart.

The only unusual thing I've done recently is cancel some ant builds (with eclipse) that were tagging releases. I think the command was push origin :refs/tags/whatever . A dialog box popped up for GitHub authentication and I was abandoning the process then. Again that was an Ant build process being run in Eclipse which calls jgit.sh to run the git commands.

At one point, I tried to discard some change in GitHub Desktop but was told the file or repo was locked (perhaps by another git process). I couldn't find anything else running and deleted index.lock as suggested in the error message.yes je os strong i Think os my Mix IOS and Microsoft yesterday a lill implement in the Ui to block dual conection and Microsoft onseder and Intel de bug all the plugqin  capture the ime_msi that was marvellous to saw!  But  like eavery fuckin Time the Victor y was short🙄🖕👎

**Comment by batarmanrookie** [comment] 2018-03-21 03:00
Envoyé de mon iPhone

Le 20 mars 2018 à 22:18, Shawn-in-Tokyo <notifications@github.com<mailto:notifications@github.com>> a écrit :


@tierninho<https://github.com/tierninho> Logged in under a GitHub.com<http://GitHub.com> account.i try!! I have one  (maybe t’en) but the  same  for my last test  on my IPhone 6$ i  just cant loggin y can installé cookie!!!

Répcan you share any details about the repository you were working with at the time you were seeing the issue?

I'm still seeing the issue 12 hours after doing anything. Any interaction with the GitHub UI causes a "GitHub Desktop Helper" process to max out the CPU (one of eight actually) at 100% for sometime and it's unresponsive during the hang (10+ seconds ). That was after a restart.

The only unusual thing I've done recently is cancel some ant builds (with eclipse) that were tagging releases. I think the command was push origin :refs/tags/whatever . A dialog box popped up for GitHub authentication and I was abandoning the process then. Again that was an Ant build process being run in Eclipse which calls jgit.sh to run the git commands.

At one point, I tried to discard some change in GitHub Desktop but was told the file or repo was locked (perhaps by another git process). I couldn't find anything else running and deleted index.lock as suggested in the error message.

**Comment by drooog** [comment] 2018-03-21 13:11
I'm also getting a hang issue. The whole interface freezes (top menus not). theres a lag time of a minute or two before it seems to refresh with the last element I clicked on.
All basically unusable.
Was going fine just some hours ago.. I made some changes to the sketch file and tried to view the changes in Kaktus, then stall. It seems especially attached to the 'changes' tab. History tab seems un effected

**Comment by drooog** [comment] 2018-03-21 13:17
![image](https://user-images.githubusercontent.com/504922/37711892-8ffbd39a-2d12-11e8-94a5-c0a872b33b25.png)
Its hanging here a long time. Refresh spinning arrow is going around.. its just not getting to any end

**Comment by drooog** [comment] 2018-03-21 13:22
Mac OS 10.12.6 btw. Sketch 49.1. Latest Kactus ... So all up to date (Except my mac OS)

**Comment by niik** [comment] 2018-03-22 17:16
Hi @drooog. Please contact the Kactus team at https://kactus.io for issues with Kactus.

**Comment by Shawn-in-Tokyo** [comment] 2018-03-27 08:27
V1.1.1 is the same.  Frequent hangs.  Basically unusable.

The git client within Eclipse is working fine for the same repo though.  No hangs or delays.  I preferred desktop since it's an extra step to compare changed files to the index in Eclipse and then you have to close them, but at least it isn't hanging

Again, this is logged in under a GitHub.com account.

**Comment by gemal** [comment] 2018-04-03 16:47
performance in the latest version is really really poor :(

**Comment by 109digital** [comment] 2018-04-13 22:37
Experiencing the same issues on Windows 10, also experienced them on Windows 7. Currently running 1.1.1, but extreme lag and slow performance has persisted across versions and OSes.

**Every. Single. GitHub. Operation. Is. Unbearably. Slow.**

GitHub Client is absolutely the bottleneck in my workflow.

The primary repo I've been working with is 1,940 files in 457 Folders, 199MB total disk size. The issue is present in every repo I've worked with. Some are larger, some are smaller. I'm not sure what is considered a large repo or a large file in this context.

The most maddening part is that maybe 5% of the time, everything is lightning fast. Literally every operation happens in near real-time. The other 95% of the time, I feel like I'm running Adobe Photoshop on a calculator.

I've contacted support about this. They dumped me in this thread without even bothering to ask for local logs, or any real details beyond what client version I was using and the size of my repos.

For most commits, I use the web GUI. I rarely commit locally because every single action, whether pulling a repo or viewing a diff, takes an eternity.

**Comment by shiftkey** [comment] 2018-04-14 04:50
@109digital Could you attach the full log files? The **Help** | **Show Logs in Explorer** menu items should open the logs folder, and inside those are the log files generated by day. This will provide some more information to help troubleshoot, including which operations are actually slow.

**Comment by 109digital** [comment] 2018-04-14 14:35
Hello,

A sample log file is [here](https://pastebin.com/nHJzKzF4). Unfortunately, all the repos I'm currently working with are private, but I added you to one so you can view.

Thank you.

**Comment by shiftkey** [comment] 2018-04-16 06:10
@109digital apologies - I got the invite without seeing this reply, so I declined because I assumed it was a mistake.

**Comment by 109digital** [comment] 2018-04-16 12:54
Invitation resent. Thank you.

**Comment by 109digital** [comment] 2018-04-23 23:53
I downloaded the beta version and sent in a fresh log, but haven't heard from anyone. I'm not sure anyone is alive at the support desk.

**Comment by shiftkey** [comment] 2018-05-07 22:39
@109digital apologies, this is still on me to investigate - I had some time off a couple of weeks ago am just now back to work after recovering from jetlag.

**Comment by 109digital** [comment] 2018-05-09 13:57
Great.

**Comment by 109digital** [comment] 2018-05-14 15:26
It just took me 30 minutes to push a commit with 2 lines changed in 1 file. I would post the log, but no one bothers reading them or offer anything other than a cursory response to make it seem like this is actually of concern.

It absolutely baffles me that a company the size of GitHub has a non-existent support system and so few resources dedicated its desktop clients. I guess you have to be an enterprise customer to get anything done.

**Comment by shiftkey** [comment] 2018-05-26 09:44
@109digital I finally carved out some time this evening to sit down and try to understand the behaviour associated with your sample repository, but I wasn't able to accept the earlier invite to the repository.

I revisited the support forum discussion and found a log file, which reminded me of this discussion I had ages ago: https://github.com/desktop/desktop/issues/3724

In that thread we had a similar symptom - every Git operation being significantly slow - which we traced to BitDefender interfering with the Git operations. Can you tell me if you have any anti-virus on your machine that might be interfering with Desktop?

**Comment by Shawn-in-Tokyo** [comment] 2018-05-27 09:40
no anti virus running
github desktop 1.2

log from today
Note: the repository I use is working fine in eclipse and on the command line.  There is no delay except in github desktop. 

[2018-05-27.desktop.production.log](https://github.com/desktop/desktop/files/2042448/2018-05-27.desktop.production.log)

**Comment by platon9000** [comment] 2018-05-27 09:44
Its 50% actionneer if we goal 2 years

**Comment by 109digital** [comment] 2018-05-27 16:34
Thanks for the suggestion, but it is not related to antivirus, at least on my system.

On my previous system, running Windows 7, disabling all anti-virus made no difference. 

My current machine runs Windows 10 with only the native Windows Defender. Even when I turn off everything, it doesn't help. I currently have real-time protection enabled, with whitelisting for:

- File: C:\Windows\System32\conhost.exe
- Folder: ..\AppData\Local\GitHubDesktop
- Folder ..\Desktop\GitHub (local repo storage directory)
- Process: Console Window Host
- Process: Git for Windows
- Process: GitHubDesktop

I also tried the Atom editor some time ago, and quickly uninstalled it due to similar performance issues. It was unusable. So perhaps Windows just doesn't like the Electron framework.

**Comment by mcmonkey4eva** [comment] 2018-06-08 18:46
Not sure if this would be considered the same issue or separate, but I'm experiencing a lot of UI freeze / slowness that doesn't really seem like it should be occurring.
My reference point for that being that the way old Github-for-Windows client did not have anywhere close to this amount of lag back when I was using that long ago.

I'm running on release version 1.2.3 of GitHub Desktop (current as of post time) + Windows 10 Home (not sure about Win10 version code, but the current one for start of June 2018)

Basically: any option, no matter how basic, will freeze the UI and take multiple seconds to complete.
It actually seems to get worse the longer my PC has been running for, somehow.
This makes it very difficult to use the client for anything.
I often have multiple-file commits, and I want to scroll through file-by-file, verify the file edit was done properly at-a-glance, and continue to the next file.
This becomes almost painful to perform if I have 20 files and each file diff takes 5+ seconds to open.

Based on looking at the logs and task manager, it seems every operation performed, even clicking a file to view that specific diff while on the changes page, calls the git executable program (alongside spawning a console host process for it) with command-line parameters, letting the program process the data needed, and then reading the standard output data from there and pushing it into the UI. This can happen multiple times in many operations (multiple git calls for a single operation). Each call is basically guaranteed a minimum of 1 second to run, often higher (3 or 4 seconds very regularly)
There absolutely has to be a better way to do this.
At least a persistent re-usable console host process, ideally a persistent re-usable git process...
The actual ideal being a same-process git handler (no console passing involved), perhaps one that performs bulk operations when possible (if there's 20 lines of waiting changes, split across 10 files, that should all be loaded in at once and referenced from local memory rather than reprocessing from disk for each file)

I have tested and confirmed that disabling all antivirus/antimalware (including fully disabling even Windows Defender) doesn't improve handling at all.

**Comment by shiftkey** [comment] 2018-07-04 18:36
@mcmonkey4eva 

> Each call is basically guaranteed a minimum of 1 second to run, often higher (3 or 4 seconds very regularly)

This really sounds like something external is interfering with our spawning Git processes. Please have a read of #3724 which was traced to BitDefender interfering with our work, as I think you might be encountering something similar.

**Comment by shiftkey** [comment] 2018-07-04 18:38
I'm going to close this out as it's been meandering without a clear resolution for a while.

Please open fresh issues and **[include a timeline profile](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md)** of the app if you identify slow parts of the app - this extra detail helps us understand what you're seeing much more effectively!

**Closed by shiftkey** 2018-07-04 18:38 UTC
Labels: more-information-needed

**Comment by mcmonkey4eva** [comment] 2018-07-04 18:58
Just an update on my own situation:

I enabled gpg key enforcement on git (and general altered git config a bit alongside that) and somewhere in there GitHub Desktop entirely stopped hanging ever. It's now operating at full expected speed. I can't really say what exactly changed to resolve the issue.

**Comment by 109digital** [comment] 2018-07-04 19:07
> Please open fresh issues and include a timeline profile of the app if you identify slow parts of the app

What are the odds anyone will actually look at the information provided? I've sent in several logs and tried to share access to a repo (at your request), but it proved to be a complete waste of time.

**Comment by shiftkey** [comment] 2018-07-06 19:13
@109digital I'm sorry that we didn't get to the bottom of the issue, and I'd love to have another shot at it if you're willing to open a fresh issue. 

The log files, while great for catching errors, aren't a great source for measuring performance and the environment that Desktop is running in, so there's some extra pieces I'd like to get from you to understand and work through this:

 - A snapshot of the machine details using `msinfo32 /nfo %TEMP%\machine-output.nfo` attached to the issue
 - A [performance timeline](https://github.com/desktop/desktop/blob/master/docs/contributing/timeline-profile.md) of the application in action so I can understand what you're actually seeing

> I know third-party AV is the go to explanation, but he explicitly stated that the issue persisted with all anti-virus disabled.

This wasn't the resolution of #3724. See [this comment](https://github.com/desktop/desktop/issues/3724#issuecomment-355764164):

> OK, my bad. I turned off all functionality in BitDefender and indeed, the problem disappeared. So it's them. I will go and haunt their QA department now.

**Comment by shiftkey** [comment] 2018-07-23 21:12
@109digital please open a new issue so we can discuss things in a fresh issue

**Comment by platon9000** [comment] 2021-10-12 10:35
---------- Forwarded message ---------
From: Martin Grenier ***@***.***>
Date: Sat, Sep 5, 2020 at 10:42 AM
Subject: Fwd: TR : $12,000,000,00 USD Payment Notification
To: ***@***.***>




---------- Forwarded message ---------
From: Martin Grenier ***@***.***>
Date: Sat, Sep 5, 2020 at 9:55 AM
Subject: Fwd: TR : $12,000,000,00 USD Payment Notification
To: ***@***.***>




---------- Forwarded message ---------
From: DHL EXPRESS ***@***.***>
Date: Sat, Sep 5, 2020 at 9:54 AM
Subject: TR : $12,000,000,00 USD Payment Notification
To: Martin Grenier ***@***.***>




------------------------------
*De :* DHL EXPRESS ***@***.***>
*Envoyé :* 5 septembre 2020 09:02
*À :* ***@***.*** ***@***.***>
*Objet :* Re: $12,000,000,00 USD Payment Notification

martin grenier
desjardins: branch: 815
transit: 10001
account number:  344194

cibc: branch: 010
transit: 00181
account number: 7554435
number house: 1-819-539-5326
gmail: ***@***.***
adress: 894 gigaire g9n3v4 shawinigan quebec canada

------------------------------
*De :* Royal Bank Of Canada ***@***.***>
*Envoyé :* 4 septembre 2020 13:19
*Objet :* $12,000,000,00 USD Payment Notification

RBC) Royal Bank Of Canada.
14 park ave Lac Du Bonnet Manitoba Canada.

$12,000,000,000 USD Payment Notification

we are to notify you about the latest development concerning your
payment that are left in our custody, besides,you are given a bill of
Sum in order to receive your payment $12,000,000,000 usd which we
didn’t hear from you for sometime now. Hence,we are now offering a New
Year BONUS to help all our customers that are having their payment in
our custody due to of high prices. In other words we are now
requesting that you should pay only the sum of $100 to receive funds
your payment abandoned in our custody by online transfer or atm card
if you wish so.

Therefore you are requested to send the fee $100 only by ITunes
Card,or Google Play CARD,amazon’ Stream Wallet is also ACCEPTED
because it can be redeemed to cash all we needs is picture of the card
only

Be advice that the bank has already created on-line transfer with the
account that opened in your favor this afternoon in which the
$12,000,000,000 Billion of your funds has been transferred to the
account that our bank open in your favor. The on-line banking account
details are follows.

Welcome! To - Royal Bank Of Canada (RBC) Secure Account Page
Account Name

Account Type
Activate
    Online Banking Account
Created Opened

Account Balance
2020  -1-13

$12,000,000,000
Account Number

Royal Bank Sort Code
6021253365        239936957
Country Ca

Name Of Bank (RBC)
International Money Transfer
Input
  Released
Swift Code 053904483
Account Number 6021253365.

I will be forwarding to you the account logging details to enable you
access your funds online and proceed on transfer to your designated
bank account in any part of the world Or Tracking Number Of Your ATM
Card Delivery to enable you Monitor the Arrived of your ATM without
any further delay as soon as you update us copy of iTunes card of the
required Fee $100 to take note.

Yours Faithfully,
MR DAVID I MCKAY
Text massage +1 (917) 725-2316
Phone Call +1(204) 410-1712
The President and CEO

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_846180869617644679_m_-8046291223222363822_m_-181706402284374412_x_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
