### ISSUE TITLE
CI Status is not displaying in PR Badge

### ISSUE THREAD

**Issue by surelook** [desktop/desktop#6752] opened 2019-01-31 09:34 UTC
CI Status is missing from PR badges as shown in the below screenshot. In this example the build status has succeeded.

![image](https://user-images.githubusercontent.com/25017570/52044775-d72ea500-253a-11e9-9d6f-1391c3305acd.png)

**Comment by steveward** [comment] 2019-01-31 20:51
@surelook thanks for the report. I just tested this out on my machine and was unable to reproduce this issue. Are you seeing this problem across multiple repositories in GitHub Desktop?

If you need another repository to try and reproduce this in you can go to the [PR page for GitHub Desktop](https://github.com/desktop/desktop/pulls) and click `open this in GitHub Desktop` at the bottom of the PR. Let me know if you are able to reproduce this.

**Comment by surelook** [comment] 2019-02-01 12:37
I can't say to be honest. It's a private repo and it's not owned by me. I was only hoping to gather information from the desktop side since the CI status is a nice-to-have in the UI. The only thing do I know is that the status stopped appearing about 4 months ago.

I've inspected the status requests for the commits and I can see that responses for commits within the past 4 months have empty 'statuses' keys.

**Comment by billygriffin** [comment] 2019-02-02 00:01
@surelook Thanks for the added color! Sorry for all the questions, but just a couple more if you don't mind sharing:

1. Are you seeing it not show up on GitHub.com as well (in line with what @tierninho suggests above)?
2. For other repos that *aren't* this one, are you seeing the build status on PRs in Desktop?

**Comment by billygriffin** [comment] 2019-02-06 19:52
Since we aren't able to reliably reproduce this, I'm going to close it for now, but I'd love to be able to look into it further if you have a moment to share that info @surelook. Thanks again!

**Closed by billygriffin** 2019-02-06 19:52 UTC
Labels: more-information-needed

**Comment by surelook** [comment] 2019-02-08 08:59
@billygriffin, sorry for the delay. The CI tool in this case is Travis. As I mentioned it's a private repo not owned by me so I can't speak for its configuration. 

1. Yes, I'm seeing the status on GitHub.com.
2. I've only been able to test public repos. The status of these repos display correctly.

**Comment by tierninho** [comment] 2019-02-13 22:01
Tried to pinpoint the reasoning behind this, but no luck. It doesn't appear to be a public/private repo issue, nor an api issue as both work. 

Just not sure why Travis CI only sometimes runs on PRs within a GitHub repo. When it doesn't run the PR on Desktop ends up as: 

```
  "state": "pending",
  "statuses": [
``` 
I have yet to see a case where the status is displayed on GitHub, but not on Desktop.

**Comment by ubuntudroid** [comment] 2020-07-16 15:42
I recognize that this has been lying dormant for quite some time, but I actually just have the issue described here:

- github.com correctly shows the PR state (all checks passing in this case)
- the desktop client has no status on its badge

My repo is private. I'm happy to share any details about my repo setup, that you need to resolve this.

**Comment by ubuntudroid** [comment] 2020-07-17 10:39
One more piece of information. We are using bitrise CI as a check which sets the status on the PR. Could it be, that the issue is caused by setting the status via a check and not "directly"?
