### ISSUE TITLE
GitHub Desktop Faulty UI

### ISSUE THREAD

**Issue by Doppp** [desktop/desktop#6724] opened 2019-01-26 08:22 UTC
## Description
I am getting a buggy desktop UI on my Windows 8.1 machine. See below screenshots for clearer picture of the issue.

## Version
* GitHub Desktop: 1.6.1
* Operating system: Microsoft Windows 8.1 Pro 6.3.9600 N/A Build 9600

### Expected Behavior
The app is supposed to look like this (I'm using my Windows 10 machine here just as a comparison):

![no_bug](https://user-images.githubusercontent.com/627410/51784589-0e413700-2186-11e9-81f6-fff2f4cd3633.png)

### Actual Behavior
However, for some weird reason, it's looking like this:

![bug](https://user-images.githubusercontent.com/627410/51784583-f2d62c00-2185-11e9-8366-610cf52f251e.png)

![bug2](https://user-images.githubusercontent.com/627410/51784584-f4075900-2185-11e9-8ecf-4aad07e505f6.png)

I'm unable to open any of the top dropdowns i.e. `File`, `Edit`, `View` etc. Repositories were edited out for privacy.

**Comment by say25** [comment] 2019-01-26 22:02
Thanks for the report, this looks like a duplicate of #6669. This issue will be fix in the next release of GitHub Desktop 1.6.2.

**Comment by steveward** [comment] 2019-01-28 19:35
I'm going to close this out as a duplicate -- thanks again for the report @Doppp!

**Closed by steveward** 2019-01-28 19:35 UTC

**Comment by shiftkey** [comment] 2019-01-28 19:38
@Doppp thanks for the feedback!

As @say25 mentioned, this is something we fixed in #6687 and will go out with the next update.
