### ISSUE TITLE
Moving between monitors whilst maximised doesn't work.

### ISSUE THREAD

**Issue by FormularSumo** [desktop/desktop#15434] opened 2022-10-09 13:33 UTC
### The problem

When GitHub desktop is maximised, moving it between monitors by dragging it between them doesn't work, the window just snaps back to its place on the original monitor. Using Win + Shift + Arrow keys to move monitor moves the window correctly.

Both of my monitors are 1080p, and set-up in Windows display settings such that they're adjacent to each other at the same height, as seen in the screen recording.

### Release version

3.1.1

### Operating system

Windows 10 21H2 19044.2006

### Steps to reproduce the behavior

1. Open GitHub Desktop in maximised view
2. Drag the GitHub Desktop window from one monitor to the other, either to the top of the other monitor so it should maximise or anywhere onto that monitor
3. GitHub desktop remains on the original monitor, and either remains maximised, restores window size down whilst having a thin white bar at the top, or restores window size down whilst not having a thin white bar at the top. 

### Log files

[Uploading 2022-10-09.desktop.production.log…]()

### Screenshots

https://user-images.githubusercontent.com/36278229/194758930-51f14e3d-7a3f-494e-b1cc-99aa99d3e8f3.mp4

### Additional context

This has been happening since version 3.1.0 I think, and I can't remember it happening before.

**Comment by sergiou87** [comment] 2022-10-10 09:36
Hey 👋  Sorry about that, it might have broken in 3.0.8, because that's when we upgraded from Electron 17 to Electron 19 (usually Electron upgrades cause this kind of issues 😞)

If you want to confirm it, here you have previous releases to try out:
- 3.0.7 (Electron 17): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.7-38727e62/GitHubDesktopSetup-x64.exe
- 3.0.8 (Electron 19): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.0.8-c41b1670/GitHubDesktopSetup-x64.exe
- 3.1.0 (Electron 19): https://centralreleases.blob.core.windows.net/github-desktop/releases/3.1.0-8ffc2d71/GitHubDesktopSetup-x64.exe

**Comment by FormularSumo** [comment] 2022-10-10 12:27
Thinking about it more 3.1.0 was the first time I'd used github desktop in a few weeks I think so it's quite possible the last version I used before that was 3.0.7 or earlier.

Testing it now:
3.0.8 the issue still exists
3.0.7 it does not

So it looks like your theory's right that upgrading Electron from 17 to 19 caused the problem.

**Comment by sergiou87** [comment] 2022-10-10 14:17
😭 thanks for confirming. I hope next version of Electron will fix this (but will probably break new stuff). I can't tell when will we update, since as you see these are quite troublesome.

**Comment by koson** [comment] 2022-10-30 00:51
Any progression? The problem still exist. 

Github desktop Version 3.1.2(x64).

**Comment by sergiou87** [comment] 2022-10-31 08:00
Nope, sorry 😕  It will take a few weeks more for us to upgrade Electron. Until then, the problem will persist.

When we work on that upgrade we'll come back and let you know 😄

**Comment by Psychpsyo** [comment] 2023-06-07 12:11
I've got the same issue and wanted to add that this is a consistent thing.
It doesn't just happen sometimes or every now and then, it happens every. single. time.

**Comment by DanielRouxSA** [comment] 2023-09-04 10:15
This is still happening on the latest release (3.3.1). It looks like several Electron upgrades have taken place since this issue was first reported (at least, that's what it looks like to me if I peruse the merged PRs). Is there perhaps additional work needed on GitHub Desktop's side to fix this, or is it purely an Electron bug that still hasn't been fixed? I did try to search the Electron issues for something that might be related to this but I wasn't successful.

**Comment by Kevin-Cherry** [comment] 2023-09-21 00:52
Definitely still happening. It is very frustrating to work with multiple monitors with this bug.

**Comment by xt0rted** [comment] 2023-09-21 01:33
The only workaround I've found for this, aside from using the keyboard, is to double click the title bar to un-maximise it, then you can move between monitors without it snapping back.

GitHub Desktop is the only electron based application I've used that does this. It looks like electron ~~24.4.0~~ [24.8.3](https://github.com/desktop/desktop/pull/17416) is what's being used now, while Obsidian, which is on 25.8.1 of electron, also has a fully custom title bar and does not have this issue. It didn't in prior versions either.

**Comment by DanielRouxSA** [comment] 2023-10-17 10:23
This appears to have been fixed in version 3.3.4, but only literally. By that I mean, this bug no longer occurs when moving the application over to another monitor from the maximized state, but when dragging it out of the maximized state but remaining on the same monitor still causes the window to snap back to the top of the screen.

**Comment by DanielRouxSA** [comment] 2023-10-17 10:26
I have now noticed something peculiar. I suspect this behavior is new to 3.3.4, but I can't be certain: When dragging the window out of the maximized state onto a different monitor **that has a different scaling setting** (in my case I have three at 100% and one at 125% - then it does not snap back to the top of the origin window. Notably this does not occur if I only drag the window across the 125% monitor; specifically the destination monitor has to be one of a different scaling than the origin monitor.

**Comment by sergiou87** [comment] 2023-10-23 09:59
Hi everyone!

I understand this issue is frustrating, but I'm afraid we cannot do anything from GitHub Desktop other than upgrading to newer versions of Electron, as we already do (periodically).

My advice is that you report these issues in the [Electron repository](https://github.com/electron/electron) because that's where it needs to be fixed 😕 

The Electron team will appreciate all the info you can share with them (screenshots, screen recordings, logs, steps to reproduce, sample projects built with [Electron Fiddle](https://www.electronjs.org/fiddle)…)

Sorry!

**Closed as completed by sergiou87** 2023-10-23 09:59 UTC
Labels: bug, electron, priority-3

**Comment by DanielRouxSA** [comment] 2023-10-29 08:02
@sergiou87 While I understand that this is very likely a bug within Electron and not GitHub Desktop itself, I’m not sure I agree that it is thus up to us users to report the bug to Electron. The GitHub Desktop team would likely be much better equipped to provide information to the Electron team that would help them pinpoint the cause, as opposed to us users - many of whom have no experience working with Electron or the GitHub Desktop codebase. It may very well require quite a bit more time and effort from one of us than it would from the GitHub Desktop team.

On top of that - although there is an element of speculation here - at least in my experience working with several Electron-based apps over the period since I started to observe this bug, GitHub Desktop has been the only app that exhibits it; meaning it is possible that it only presents under particular circumstances.

All this to say - it is at least my opinion that reporting this bug is something the GitHub Desktop team should do, as opposed to us end users. 🙂

**Comment by ensapra** [comment] 2024-06-30 10:27
Any update on this issue, 2024 and it still persists

**Comment by DanielRouxSA** [comment] 2024-11-08 07:18
Just following up to report this issue still persists in version 3.4.9.

**Comment by ensapra** [comment] 2025-03-18 15:43
Finally, this has been fixed today with  3.4.18
