### ISSUE TITLE
Authentication Failed error during PUSH using Git-Desktop

### ISSUE THREAD

**Issue by siddmittal** [desktop/desktop#4433] opened 2018-04-11 15:16 UTC
I am using Git-Desktop Version 1.1.1.

I am able to push changes to my own repo but whenever I am trying to Push commit to a Repo of someone else (public repo), I get Authentication failed error message.

I have cloned the repos using "Https" as mentioned in other solutions. I am already logged in with the same account in Git-desktop.

**Comment by iAmWillShepherd** [comment] 2018-04-11 15:26
It sounds like you don't have permissions to push to the other person's repo; you will need to talk with that individual to request that they add you as a collaborator to their repo.

Closing since this is expected behavior.

If there is something I missed, feel free to reach back out.

**Closed by iAmWillShepherd** 2018-04-11 15:26 UTC
