### ISSUE TITLE
2 Finger Scroll Lags Software, Crashes PC

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#6722] opened 2019-01-26 00:38 UTC
## Description

Sometimes, when using GitHub Desktop, after having made changes, I accidentally use 2 finger scroll on my touchpad. This immediately lags GitHub Desktop severely and I am unable to do anything else on it, and can't even close the program.

## Version

1.6.1

## Operating system:

Microsoft Windows [Version 10.0.17134.523]

## Steps to Reproduce

1. Open GitHub Desktop
2. Make changes to multiple files on your local repo.
3. Use two-finger scroll on the left sidebar, showing the files changed.
4. The main panel on the right will attempt to update hundreds of times per second, and lag the GPU and the program will halt.

This computer has 6gb of RAM and I have replicated the problem on another Windows 10 computer with 4gb of RAM.

### Expected Behavior

I would expect scroll, if implemented in this way, to end at the bottom of the changed file list. Scrolling a second time could then navigate back to the top.

### Actual Behavior

What happens instead is the scroll is treated as movements down hundreds of items, and loops back and fourth between changed items as opposed to stopping at the bottom. This lags the computer and eventually crashed the program.

## Additional Information

No screenshots would be useful here. It is always just the view where local files are changed, and changes are highlighted on the left and previewed on the center/right.

I will attach the performance profile as detailed [here](https://github.com/desktop/desktop/blob/development/docs/contributing/timeline-profile.md) momentarily, however, please note this profile is only available from a time where the program DOESN'T crash.

### Logs

I could not find logs located in the described folder of

 `%APPDATA%\GitHub Desktop\logs\*.desktop.production.log`

nor could I find them here:

`C:\Users\MYNAME\AppData\Local\GitHubDesktop`

**Comment by justingolden21** [comment] 2019-01-26 00:42
I tried to upload the profile.json however it said "We don't support that file type."So I tried going to pastebin however there are 59,716462 characters and it crashed the page. So I tried to attach it as a .txt file however it's saying the maximum file size is 10mb. I can create a repo just for the file if necessary, just let me know.

**Comment by steveward** [comment] 2019-01-28 17:35
Thanks for the detailed report @justingolden21. Are you able to grab the log file by going into GitHub Desktop and selecting `Help` > `Show Logs in Finder`? Please upload a log file from a day where you experienced the issue. 

>What happens instead is the scroll is treated as movements down hundreds of items, and loops back and fourth between changed items as opposed to stopping at the bottom.

Are there a large number of uncommitted changes when you scroll through the list? Have you experienced crashes when working with a smaller list of changes?  Any specific details you can share would be helpful.

**Comment by justingolden21** [comment] 2019-01-29 06:00
I've created a public repo for the text file [here](https://github.com/justingolden21/github-desktop-log-scroll-issue).

As for the number of changed files, any number >= 2, and even two small files have this problem.

Thank you for looking into this issue.

**Comment by justingolden21** [comment] 2019-02-02 10:51
Are you guys able to reproduce the issue?

**Comment by shiftkey** [comment] 2019-02-03 13:31
@justingolden21 thanks for the log file. There wasn't anything really insightful in there, but maybe it'll help after correlating the same behaviour on our end.

@steveward was wondering if the app dumped out any interesting error messages into the log files we cache on disk - are you able to open the ` Help > Show Logs in Explorer` menu item and see if there's any extra information there that might explain what the crash is?

I'm going to try and reproduce this on my end next, but I haven't got access to a physical Windows setup currently so it might not match exactly what you have. Could you share a bit about your setup and how you have the two-finger scroll enabled? I was going to work from [this guide](https://www.howtogeek.com/howto/35065/how-to-enable-macbook-style-two-finger-scrolling-on-windows-laptops/) as a starting point to emulate it.

**Comment by justingolden21** [comment] 2019-02-03 22:50
@shiftkey if you're wondering my laptop is a lenovo with 2 finger scroll and various touch gestures built in for the touchpad. It's a 2 in 1. I've also replicated the issue on a desktop back home, which I don't have access to right now, but it was using the scrollwheel on the mouse. That PC has 32gb of RAM and runs GTA fine, but it still lagged and froze the software after scrolling. Thanks for taking the time to resolve this issue.

**Comment by steveward** [comment] 2019-03-14 20:08
@justingolden21 are you still able to reliably reproduce this issue on multiple machines? I have still been unable to reproduce the behavior you describe.

**Comment by justingolden21** [comment] 2019-03-14 22:14
I was able to for many months, right now I don't have access to a computer that has a touchpad and can use github desktop.

**Comment by justingolden21** [comment] 2019-03-20 06:59
I recently got a new laptop and I'm happy to report that Github Desktop works fine and I am not experiencing the bug I reported before. This laptop is by Dell, the others were HP and Lenovo. Hopefully, someone can figure out why this bug was happening and fix it in the future. On my end, however, the problem isn't relevant anymore.

**Comment by tierninho** [comment] 2019-03-20 17:09
Thanks for the update. Closing this issue for now.

**Closed by tierninho** 2019-03-20 17:09 UTC
Labels: more-information-needed, windows

**Comment by justingolden21** [comment] 2019-03-21 00:45
I mean the issue isn't relevant for me anymore, however it doesn't mean it's fixed. I simply have another computer... If this is still an issue for others, I don't know if you should close the issue entirely.

Just my two cents, thanks again for looking into this.
