### ISSUE TITLE
Changes list does not scroll and loses key focus when pressing down outside of visible area

### ISSUE THREAD

**Issue by jessetan** [desktop/desktop#8705] opened 2019-11-26 11:08 UTC
### Describe the bug

- When viewing a list of changes that is larger than can fit in the window, the list of files is scrollable using the mouse.
- If an entry in the list is selected, the right-side of the window shows a diff.
- If the down key is pressed, the next item in the list is focused and the corresponding diff is shown
- If the down key is pressed multiple times and the selection goes outside of the viewable area, the list will eventually scroll, but the next list item is not selected. Sometimes the list no longer scrolls at all and arrow key presses have no effect.

Expected:
Pressing the down arrow key always selects the next file in the list.

### Version & OS

Version 2.2.3 on macOS 10.14.6

**Comment by billygriffin** [comment] 2019-11-26 14:26
Thanks @jessetan! I think this is a duplicate of https://github.com/desktop/desktop/issues/6845, so I'm going to close this now. We've also seen this come up a bit more lately so I'm going to see if we can get the PR prioritized. Really appreciate you pointing it out!

**Closed by billygriffin** 2019-11-26 14:26 UTC
