### ISSUE TITLE
Updating From Older Version Forgets All of My Repos

### ISSUE THREAD

**Issue by justingolden21** [desktop/desktop#11583] opened 2021-02-14 18:21 UTC
### Describe the bug

Updating From Older Version Forgets All of My Repos

### Version & OS

It's now 2.6.3, don't know what it was before, but probably about 4 months out of date. Windows 10.

### Steps to reproduce the behavior

1. Open and update older GitHub Desktop
2. Newer version shows screenshot below, largely zoomed in and as if I have no repos. I checked my disk and thankfully I still have my uncommitted work.

### Expected behavior

Desktop to pick up where it left off and show all my repos

### Actual behavior

Desktop showed me the screenshot below

### Screenshots

![image](https://user-images.githubusercontent.com/30274440/107885269-19bb4400-6eae-11eb-9997-b213b58bd59f.png)

### Logs

<details>
<summary>Log</summary>

```
2021-02-14T18:11:00.203Z - info: [ui] [AppStore] loading 95 repositories from store
2021-02-14T18:11:00.207Z - info: [ui] [AppStore] found account: justingolden21 (Justin Golden)
2021-02-14T18:11:00.932Z - info: [ui] launching: 2.6.0 (Windows 10.0.18363)
2021-02-14T18:11:00.932Z - info: [ui] execPath: 'C:\Users\Justin\AppData\Local\GitHubDesktop\app-2.6.0\GitHubDesktop.exe'
2021-02-14T18:11:01.332Z - info: [ui] Stats reported.
2021-02-14T18:11:05.680Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pquest - justingolden21 (has token)
2021-02-14T18:11:07.139Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 1.319s)
2021-02-14T18:11:16.097Z - info: [ui] [AppStore.getAccountForRemoteURL] account found for remote: https://github.com/justingolden21/pokemon-types.git - justingolden21 (has token)
2021-02-14T18:11:18.767Z - info: [ui] Executing clone: git -c credential.helper= -c protocol.version=2 clone --recursive --progress -- https://github.com/justingolden21/pokemon-types.git C:\Users\Justin\Documents\GitHub\pokemon-types (took 2.600s)
2021-02-14T18:11:18.822Z - info: [ui] [AppStore] adding repository at C:\Users\Justin\Documents\GitHub\pokemon-types to store
2021-02-14T18:11:19.104Z - info: [ui] [BranchPruner] No branches to prune.
2021-02-14T18:11:26.533Z - warn: [ui] fetchRepository: 'justingolden21/cat-facts' returned a 404
2021-02-14T18:11:26.677Z - warn: [ui] fetchRepository: 'justingolden21/cat-facts' returned a 404
2021-02-14T18:11:26.677Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: cat-facts - justingolden21 (has token)
2021-02-14T18:11:27.493Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/justingolden21/cat-facts.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:11:30.486Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: justingolden21.github.io - justingolden21 (has token)
2021-02-14T18:11:32.058Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.513s)
2021-02-14T18:11:33.827Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.702s)
2021-02-14T18:11:37.701Z - warn: [ui] fetchRepository: 'justingolden21/generation' returned a 404
2021-02-14T18:11:37.842Z - warn: [ui] fetchRepository: 'justingolden21/generation' returned a 404
2021-02-14T18:11:37.843Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: generation - justingolden21 (has token)
2021-02-14T18:11:38.638Z - error: [ui] `git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: Repository not found.
fatal: repository 'https://github.com/justingolden21/generation.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:12:41.806Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.728s)
2021-02-14T18:12:44.130Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.381s)
2021-02-14T18:12:46.372Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: webpage-template - justingolden21 (has token)
2021-02-14T18:12:47.825Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.396s)
2021-02-14T18:12:49.642Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 1.102s)
2021-02-14T18:12:51.115Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.274s)
2021-02-14T18:12:53.735Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: desktop-clock - justingolden21 (has token)
2021-02-14T18:12:55.829Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.036s)
2021-02-14T18:13:03.579Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.470s)
2021-02-14T18:13:06.034Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: gitignore - justingolden21 (has token)
2021-02-14T18:13:07.486Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: hmm - justingolden21 (has token)
2021-02-14T18:13:09.445Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.897s)
2021-02-14T18:13:13.561Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.266s)
2021-02-14T18:13:15.693Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 1.574s)
2021-02-14T18:13:21.632Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/nourali/cs583_f2019_ali_nour_proj_1.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:26.514Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 4.810s)
2021-02-14T18:13:27.416Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/Arab/cs853_f2019_arab_safiya_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:30.749Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 3.276s)
2021-02-14T18:13:31.620Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/arshsb77/cs583_f2019_ballagan_arshdeep_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:33.267Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/bargsteen/cs583_f2019_bargsteen_kasper_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:35.187Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/abotros/cs583_f2019_andrewww_botros_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:36.642Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/rwb/cs583_f2019_brown_robert_proj_2.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:39.275Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 2.576s)
2021-02-14T18:13:41.687Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/Diego/cs_583_f2019_castanon_diego_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:43.317Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/chenkaiyu/cs583_f2019_chen_kaiyu_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:55.778Z - info: [ui] Executing getStatus: git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z (took 12.396s)
2021-02-14T18:13:56.709Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/JiaxiChen/cs583_f2019_chen_jiaxi_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:58.134Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/Rclodeca/cs583_f2019_clode_ryan_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:13:59.383Z - error: [ui] `git -c credential.helper= fetch --progress --prune origin` exited with an unexpected code: 128.
stderr:
remote: The project you were looking for could not be found.
fatal: repository 'https://rijeka.sdsu.edu:443/JContreras/cs583_f2019_contreras_jackson_proj_02.git/' not found

(The error was parsed as 8: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.)
2021-02-14T18:14:03.442Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: game-of-life - justingolden21 (has token)
2021-02-14T18:14:04.995Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.492s)
2021-02-14T18:14:07.619Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pixel-bootstrap-ui-kit - justingolden21 (has token)
2021-02-14T18:14:10.446Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 2.767s)
2021-02-14T18:14:11.458Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pq - justingolden21 (has token)
2021-02-14T18:14:12.849Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1.330s)
2021-02-14T18:14:14.381Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune upstream (took 1.471s)
2021-02-14T18:14:14.753Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: pokemon-types - justingolden21 (has token)
2021-02-14T18:14:16.746Z - info: [ui] [AppStore] loading 0 repositories from store
2021-02-14T18:14:16.747Z - info: [ui] [AppStore] found account: justingolden21 (Justin Golden)
2021-02-14T18:14:17.045Z - info: [ui] launching: 2.6.3 (Windows 10.0.18363)
2021-02-14T18:14:17.046Z - info: [ui] execPath: 'C:\Users\Justin\AppData\Local\GitHubDesktop\app-2.6.3\GitHubDesktop.exe'
2021-02-14T18:16:48.960Z - info: [ui] [AppStore] loading 0 repositories from store
2021-02-14T18:16:48.961Z - info: [ui] [AppStore] found account: justingolden21 (Justin Golden)
2021-02-14T18:16:49.264Z - info: [ui] launching: 2.6.3 (Windows 10.0.18363)
2021-02-14T18:16:49.264Z - info: [ui] execPath: 'C:\Users\Justin\AppData\Local\GitHubDesktop\app-2.6.3\GitHubDesktop.exe'

```

</details>

**Comment by justingolden21** [comment] 2021-02-14 18:26
Also to add to this, even after adding an existing repository, all others are still missing. There is no option to add multiple repos at a time (feature request 😄 ) so I have to go *one by one through 96 repositories* in order to have my setup back...

**Comment by sergiou87** [comment] 2021-02-15 10:45
Hmmm this is weird, it's like the app can't access those repos. Could you try signing out and in again? Hopefully it won't do the same the next time you update.

> There is no option to add multiple repos at a time (feature request 😄 ) so I have to go one by one through 96 repositories in order to have my setup back...

You should be able to drag & drop all your repos from Windows Explorer to GitHub Desktop, and it should do exactly what you need.

**Comment by steveward** [comment] 2021-02-19 20:44
@justingolden21 we've had a number of cases of this reported in https://github.com/desktop/desktop/issues/10548. Unfortunately this type of issue is difficult to reproduce, and I have yet to have seen it on any of my Windows VMs after testing updates. Are your repositories stored in either a network share or a location that is being used by a file syncing service like DropBox?

Since this issue is open and labeled `bug` I'll make this the tracking issue going forward.

**Comment by justingolden21** [comment] 2021-02-19 23:54
> You should be able to drag & drop all your repos from Windows Explorer to GitHub Desktop, and it should do exactly what you need.

YAY! Thank you, exactly what I needed.

> Are your repositories stored in either a network share or a location that is being used by a file syncing service like DropBox?

Nope, on PC not using dropbox/one drive/google drive etc

I understand it's difficult to replicate this issue. I think it's an issue with the previous software anyway, so going forward I don't know that anything needs to be done to fix this.

**Comment by billygriffin** [comment] 2021-04-29 14:09
I agree that this is a bad bug, but given that we've seen no more reports, we don't know how to reproduce, and @steveward graciously added this report to the other issue where we've seen this, I'm going to close it. Hopefully this is just fixed now, but we'll have both issues if we see it happen again to be able to dig in further. 🤞 Thanks so much @justingolden21, I've always really appreciated your feedback. ❤️

**Closed as completed by billygriffin** 2021-04-29 14:09 UTC
Labels: bug, priority-2
