### ISSUE TITLE
Unable to switch branch on GitHub desktop client

### ISSUE THREAD

**Issue by SumGandhi** [desktop/desktop#7718] opened 2019-06-06 21:49 UTC
Version of GitHub in use - GitHub Desktop Version 2.0.3
Enterprise Repository setup of application code base
Steps to replicate the issue -
a) File --> Clone a repository
b) Under URL tab - <provided URL of Github repository> and Local path - <Local workspace path>
c) Click on Clone button
d) Post cloning the repository is listed under "Other" and not "Enterprise" (Earlier it used to be listed under "Enterprise")
e) Unable to switch branches - by default "master" is selected.

**Comment by tierninho** [comment] 2019-06-06 22:00
@SumGandhi Please go the `Help` menu in Desktop and attached your logs so be have more insight into your issue. Thanks!

**Comment by iAmWillShepherd** [comment] 2019-06-06 22:55
@SumGandhi 

Some quick questions
1. When you click the _Branch List_, do you see any branches?
1. Are you able to checkout another branch using the CLI?

**Comment by SumGandhi** [comment] 2019-06-07 14:06
Thanks for looking into my issue.

Response to your questions -

1. Yes, I can see the other branches when i click on Branch List. However, 
when I try to switch to another branch (from master), its not letting me 
do so. 

2. I have tried to checkout another branch and same behavior. I discovered 
this issue only yesterday and the branches with which I have local 
repository setup during the past weeks, are still working fine. Any new 
clone repository, I am seeing it listed under "Other" and not "Enterprise" 
- which usually was the case.

Thanks & Regards,
Sumit Gandhi

**Comment by steveward** [comment] 2019-06-07 14:12
@SumGandhi thanks for sharing those extra details. Would you be able to upload the log file so that we could take a closer look at what might be happening here?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`.

The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by SumGandhi** [comment] 2019-06-07 14:33
[Git-DesktopClient-logs.txt](https://github.com/desktop/desktop/files/3266333/Git-DesktopClient-logs.txt)
Attached are the log files as requested.

**Comment by shiftkey** [comment] 2019-06-07 14:47
> 2. I have tried to checkout another branch and same behavior. I discovered
this issue only yesterday and **the branches with which I have local
repository setup during the past weeks, are still working fine**. Any new
clone repository, I am seeing it listed under "Other" and not "Enterprise"
- which usually was the case.

@SumGandhi this is an interesting clue. I wonder if there's something with how we handle local branches versus remote branches with the changes to "Switch branch".

If you're working with a fresh clone of a repository, it's possible that all the branches are "remote" until that first checkout, when we create a local branch that tracks the remote branch.

Can you confirm if that makes sense to you, based on your steps to reproduce the problem?

**Comment by SumGandhi** [comment] 2019-06-07 15:06
@shiftkey, thanks for your response. I just checked few workspaces that I set up by cloning "remote" repository during past week and they are still listed under "Enterprise" on Github desktop client and workable (meaning i am able to switch branches). However, if I make a fresh clone to that very same "remote" repository today, it gets reflected under "Other" and branch switch issue persists. 
Hope I am able to articulate the problem that makes sense.

**Comment by shiftkey** [comment] 2019-06-07 15:10
@SumGandhi thanks for the extra information and for working through us with it.

It's not clear to me currently why these might be getting re-categorized under "Other", let alone how that affects checkout, but we'll follow up if we have any other questions.

**Comment by SumGandhi** [comment] 2019-06-07 19:16
Update/More Info in regard with this issue - I received a notification on GitHub desktop client regarding an upgrade in version which I believe has been recently released (version 2.0.3). The issue might be related to some fixes that were released as a part of this upgrade (merely speculating because of the timing of the issue).
Also, I had "Write" access to the repository. When I contacted the Admin and got my access changed to Admin (because the issue was not replicable on Admin's machine), my issue got resolved and on cloning the "remote" repository - it started appearing under "Enterprise" instead of "Other". So, the issue appears to be related to role/access specific. 
Hope these inputs steer us towards finding the root cause of the issue. Please share your findings.

**Comment by SumGandhi** [comment] 2019-06-07 19:31
@All, this issue definitely seems to be introduced with version 2.0.3 release. I reverted back to an older version (1.2.3) and clone repository (remote) is working fine with "Write" access - repository getting listed under "Enterprise". So, latest release fixes needs to be reviewed in tandem with the issue reported in this thread. 
Also, it shows a message on old GitHub desktop client (version 1.2.3) that it will automatically upgrade to latest version on next restart. Is there any way to prevent that from happening? I explored but could not find an option to turn off auto upgrade?

**Comment by bill01568** [comment] 2019-06-07 21:42
I'm experiencing the same problems:

1) The cloned Enterprise repository is listed under "Other".
2) I can also see all branches listed in the dropdown but am unable to actually switch to any branch; I'm stuck on master.

BUT ALSO ... 3) The repository name is not being kept as selected from the remote list, but is being changed to the rightmost subdirectory name in which I am placing the local copy. In my case that's "by". It looks very odd seeing:

Other
[icon] by

in my repository list!

This started on June 6th (USA day) not long after receiving version 2. I'm currently on 2.0.3. I'm available if you want logs, etc.

**Comment by tierninho** [comment] 2019-06-07 21:47
@bill01568 Yes, please send over the logs -- see the Help menu on Desktop. Also, anything unique about your setup? Thanks!

**Comment by bill01568** [comment] 2019-06-07 21:56
Not aware of anything unique about my setup. I still consider myself a newbie.

[2019-06-06.desktop.production.log](https://github.com/desktop/desktop/files/3267733/2019-06-06.desktop.production.log)
[2019-06-07.desktop.production.log](https://github.com/desktop/desktop/files/3267734/2019-06-07.desktop.production.log)

**Comment by bill01568** [comment] 2019-06-10 16:49
Can somebody point me to where I can download the latest/stable 1.X version of GitHub Desktop? I only need to use it long enough to clone this one repository using methods I'm familiar with, and that are compatible with GitHub Desktop. (I tried cloning via Git command line and ... GitHub Desktop doesn't seem to be quite happy with that copy.)

**Comment by kchristman54** [comment] 2019-06-11 14:01
The issue is that we can see the list of other branches, but upon trying to switch to another branch nothing happens in GitHub Desktop. Even the log file shows no attempted activity or errors. For example, after trying to switch branches the log file doesn't change:
```
2019-06-11T13:32:28.927Z - info: [ui] [AppStore] loading 1 repositories from store
2019-06-11T13:32:28.928Z - info: [ui] [AppStore] found account: a5568 (Isaiah Young)
2019-06-11T13:32:29.272Z - info: [ui] launching: 2.0.3 (Windows 10.0.17763)
2019-06-11T13:32:29.273Z - info: [ui] execPath: 'C:\Users\a5568\AppData\Local\GitHubDesktop\app-2.0.3\GitHubDesktop.exe'
2019-06-11T13:32:30.394Z - info: [ui] Executing installGlobalLFSFilter: git lfs install --skip-repo (took 1.251s)
2019-06-11T13:33:33.131Z - info: [ui] No submodules found. Skipping "git submodule status"


```

Since last week, we've been able to reliably reproduce this on every machine we've tried (3 of them). It even fails on machines which already have "Github Desktop" working fine on a separate Windows user account. 

Our setup is Windows 10, in an academic environment (Texas A&M University). No admin rights, although even with admin rights we have the same problem. We are using Github Enterprise through Texas A&M (github.tamu.edu). 

One thing to note is after logging into github.tamu.edu via GitHub Desktop, the repository shows up as "Other" and not "Enterprise". It's showing this: 
![image](https://user-images.githubusercontent.com/33758481/59278178-27272200-8c27-11e9-9ee8-a827cf49d3ce.png)

Instead of this:
![image](https://user-images.githubusercontent.com/33758481/59278258-47ef7780-8c27-11e9-8dbc-7d2314565876.png)

**Comment by shiftkey** [comment] 2019-06-11 15:35
@kchristman54 @bill01568 @SumGandhi I think this will be fixed by #7754, so please stay tuned for our next update!

**Comment by shiftkey** [comment] 2019-06-11 16:03
Assigning myself to check in on this after `2.0.4` has shipped

**Comment by pyamaura** [comment] 2019-06-12 13:49
Any way to accelerate this fix or download it?  GitHub Desktop is no longer usable for our Enterprise development.

**Comment by shiftkey** [comment] 2019-06-12 13:50
@pyamaura a release is being prepared that should resolve this - aiming to publish in the next couple of hours...

**Comment by sachinmathur** [comment] 2019-06-12 14:54
@shiftkey I am eagerly waiting for the fix of this issue. This issue has impacted me since I upgraded to 2.0.3 on Monday. I have the same observations as @SumGandhi

**Comment by sachinmathur** [comment] 2019-06-12 15:42
@shiftkey I can confirm that fix released with 2.0.4 is working fine for me.

**Comment by shiftkey** [comment] 2019-06-12 16:15
@sachinmathur thank you for confirming the fix. @pyamaura @kchristman54 @bill01568 @SumGandhi  can you also confirm?

**Comment by bill01568** [comment] 2019-06-12 16:18
All 3 issues that I reported above are resolved by 2.0.4.. Thank you! I can now work again!

**Comment by billygriffin** [comment] 2019-06-12 16:19
Thanks @bill01568, great to hear and apologies for the disruption! I'm going to close this since multiple folks have verified the fix.

**Comment by pyamaura** [comment] 2019-06-12 16:20
It appears to be working properly.   Thank you.

**Closed by billygriffin** 2019-06-12 16:19 UTC
Labels: bug

**Comment by SumGandhi** [comment] 2019-06-12 16:25
Thanks Brendan for the update.

Downloaded version 2.0.4 and the issue earlier reported have been 
resolved.

Regards,
Sumit

**Comment by arjunkalarikkal** [comment] 2020-07-07 09:31
Hi,
I am facing the same error on Github desktop.
My version is 2.5.3
logs: https://send.firefox.com/download/8f262f6eb4177211/#eoM87NtIxRsImhYaUpqZ5w
<iframe src="https://drive.google.com/file/d/1CWGBlhuD0BbjYY6qDwpZlU0yFmG6qq1O/preview" width="640" height="480"></iframe>

**Comment by tierninho** [comment] 2020-07-07 18:06
@arjunkalarikkal Thanks for the notice. I added your comments to a known issue for this here: https://github.com/desktop/desktop/issues/9297#issuecomment-655032268
