### ISSUE TITLE
Add option to manually stash changes

### ISSUE THREAD

**Issue by adamwych** [desktop/desktop#8931] opened 2020-01-16 11:20 UTC
### Describe the feature or problem you’d like to solve

Git allows us to stash current changes and then re-apply them. Desktop already provides a way to stash changes when you change the branch, but stashing is also useful in other cases, not necessarily when changing the branch. Currently if you want to do this you need to run `git stash` or `git stash -u` by yourself.

### Proposed solution

I think it would be nice to add some button or a menu item to manually stash current changes (aka run `git stash -u`).

### Additional context

An example case of when stash is useful is when you can't pull changes because you changed a file that also changed on the remote. Many times Git can't automatically understand what happened, so it just refuses to pull the changes - stashing them and then applying that stash merges both files and gives merge conflicts, but they can be easily solved.

![image](https://user-images.githubusercontent.com/6526954/72520415-b3eb2b80-3859-11ea-94cf-60c4d05a15d1.png)

**Comment by tierninho** [comment] 2020-01-16 18:15
@adamwych Thanks for filing this. This is a duplicate of https://github.com/desktop/desktop/issues/8197 and https://github.com/desktop/desktop/issues/8775 to some regard. We have taken note and will update 8197 when the time comes. Thanks for using Desktop.

**Closed by tierninho** 2020-01-16 18:15 UTC
