### ISSUE TITLE
Discard All files warning displays incorrect characters for file

### ISSUE THREAD

**Issue by tierninho** [desktop/desktop#7181] opened 2019-03-29 19:55 UTC
When discarding all files, I noticed that one file was labeled as `...` incorrectly. It may be because I had duplicated the file a few times, but unsure. 

It looks to be reading the `path-label-component` and not the `filename`. 

<img width="858" alt="Screen Shot 2019-03-29 at 9 39 48 AM" src="https://user-images.githubusercontent.com/14828183/55259019-9b495080-5208-11e9-9dc0-d2a7c5cf3a66.png">
<img width="526" alt="Screen Shot 2019-03-29 at 9 41 00 AM" src="https://user-images.githubusercontent.com/14828183/55259020-9b495080-5208-11e9-9828-17ffc1466b68.png">

1.7.0-beta1, mac

**Comment by samuelko123-bunnings** [comment] 2023-04-22 05:12
I am unable to reproduce the issue.

Github Desktop - v3.2.1
Windows 10 x64

![image](https://user-images.githubusercontent.com/122413022/233763923-e6bfbc54-cd10-4397-a212-78d755f8c90c.png)

**Comment by steveward** [comment] 2024-04-04 16:49
I tested this out as well and was unable to reproduce the issue, so I'm going to close this out as resolved. Thanks for checking this @samuelko123-bunnings. ✨

**Closed by steveward** 2024-04-04 16:49 UTC
Labels: bug, priority-3
