### ISSUE TITLE
Name disambiguation repository selector list

### ISSUE THREAD

**Issue by safield** [desktop/desktop#7910] opened 2019-07-03 18:48 UTC
When adding multiple instances (on the file system) of a repository of the same name, there is no way to disambiguate these repositories in selector list.

I  could (and do) have two (or more) separate checkouts of repo "Foo", on my file system. I can add both these instances to github desktop client. I then click on the "current repository" drop down list to select from all my added repositories.

In this scenario, all that will display in the subsequent dropdown list is two instances of the word "Foo", with no indication about which repo on my file system that these particular entries correspond to.

I can imagine two rather sensible fixes....

1. The simplest approach is to have a tooltip popup that displays the full path when you hover over the entries in this list.

2. The best approach would be to always display the path to the repo as smaller text, under the repo name. This would be similar to how commits are displayed in the history view.

Thanks for your consideration.

**Comment by tierninho** [comment] 2019-07-03 19:11
@safield Thanks for filing. Going to close this issue as it is a duplicate of similar issues which were addressed in #6460 . A second iteration of this area is not currently on the [roadmap](https://github.com/desktop/desktop/blob/development/docs/process/roadmap.md).

> The simplest approach is to have a tooltip popup that displays the full path when you hover over the entries in this list.

We have it already:
![Screen Shot 2019-07-03 at 9 03 40 AM](https://user-images.githubusercontent.com/14828183/60618381-bda3ba80-9d71-11e9-8770-1222940c2148.png)

> The best approach would be to always display the path to the repo as smaller text, under the repo name. This would be similar to how commits are displayed in the history view.

Thanks for the suggestion. We will consider it on the next iteration. 👍

**Comment by safield** [comment] 2019-07-03 19:25
So the reason I did not see the tooltip is because it only shows when you hover directly over the font. If you hover over the clickable region of the list item, it will not show (at least on windows 10). This is not congruent with other tooltips in the application, and is probably a separate bug (it bit me :P).

**Comment by tierninho** [comment] 2019-07-03 19:32
Ah, gotcha. That is a reasonable expectation and looks like a `bug` to me as well as it isn't aligned with the functionality throughout the app.

To sum it up, this area should show the tooltip here when the user hovers:
![Screen Shot 2019-07-03 at 9 03 40 AM](https://user-images.githubusercontent.com/14828183/60619900-6c95c580-9d75-11e9-8aa9-455cf67721d2.png)


Adding `help-wanted` label for anyone looking to help out. 😄

**Closed** 2019-07-08 18:19 UTC
Labels: bug, help wanted, priority-3
