### ISSUE TITLE
GitHub Desktop for Mac keeps asking me for root access to install "helper"

### ISSUE THREAD

**Issue by justinjdickow** [desktop/desktop#3616] opened 2017-12-15 20:27 UTC
Can someone explain to me what the "Helper" is and whether I should be giving it access?

**Comment by joshaber** [comment] 2017-12-15 22:35
Hi @justinjdickow! When does it ask you? Could you drop a screenshot in here?

**Comment by justinjdickow** [comment] 2017-12-16 00:58
I'll take a screen shot next time it happens

**Comment by justinjdickow** [comment] 2017-12-16 13:34
Here we go
<img width="446" alt="screen shot 2017-12-16 at 8 33 03 am" src="https://user-images.githubusercontent.com/3627664/34070927-e6451936-e23b-11e7-9252-19ac4c1d2fce.png">

**Comment by janbrasna** [comment] 2017-12-21 07:58
👍 … I always get nervous about giving out access that I don't have any idea why it's needed and for what benefit. Think iOS permission priming dialogues to elaborate a bit on why such permission is needed (benefiting the user, or making some convenience part of the app working et al. …)

**Comment by iAmWillShepherd** [comment] 2017-12-23 02:25
What version of GitHub Desktop are you using?

**Comment by joshaber** [comment] 2018-01-08 14:47
In this case, the dialog _does_ provide a bit of context: "An update is ready to install."

Depending on your user account, permissions on the enclosing directory, etc. you may need to authenticate each time an update is installed. Does that make sense with your experience?

**Comment by justinjdickow** [comment] 2018-01-08 14:49
Hmm I guess so - but what is a helper tool? That just reminds me of the Flash Player Helper Tool.

**Comment by joshaber** [comment] 2018-01-08 15:00
Unfortunately that's macOS's nomenclature 😞 It's an implementation detail which means we use a separate executable with escalated privileges to perform an action.

It sounds like this is working as intended, so I'm gonna close it.

**Closed by joshaber** 2018-01-08 15:00 UTC
Labels: macOS, more-information-needed

**Comment by ihomp** [comment] 2018-02-12 05:03
I have the same issue, very annoying..

**Comment by iAmWillShepherd** [comment] 2018-02-12 17:54
@ihomp, could you open a new issue detailing expected/actual behaviors and reproduction steps? This helps us to better understand the problem and arrive at a solution faster.

**Comment by ihomp** [comment] 2018-02-13 07:57
@iAmWillShepherd I guess it some how related to the fact, that I have two mac users. 
I might installed github desktop when I was not on the admin user but with admin login and password.
So, now at least once per day I see this popup.
I'll try to reinstall GitHub Desktop from admin user. Though not sure if that matter... don't know for sure how to reproduce it.

**Comment by jhand0867** [comment] 2018-02-16 20:55
I get the same issue every time I start my GitDesktop

**Comment by laszewsk** [comment] 2018-03-04 12:51
I have the same issue as reported above. It asks me once a day to authenticate with the administrator user to install a helper tool. As there is no explanation in the help message provided what a helper tool is I decided to uninstall it. It is such a nice tool though

**Comment by justinjdickow** [comment] 2018-03-05 12:55
I think this issue should stay open, it's no longer that there's an issue with it popping up and asking to install, it's that giving it access doesn't do anything and the next time you open GitHub Desktop it just asks again.

**Comment by shiftkey** [comment] 2018-03-05 21:39
Hey @desktop/electron, is this an issue you've seen elsewhere? I'm not sure what control we have over this in Desktop, and it'd be nice to see if we can address this to make things clearer...

**Comment by laszewsk** [comment] 2018-03-05 21:44
This is the only OSX app that does this on my machine.  Maybe just clarifying the message would be good as you suggest. I do not have such ambiguous statements from other applications.

**Comment by nathancarter** [comment] 2018-03-19 12:49
Exact same problem.  Note that if I do not have the app open, I do not get this message.  But if I leave the app open, I get this message daily.  And, in my case also, this is the only app on my Mac that behaves this way, so there has to be another way to do this.

Even if the answer is that those of us who are experiencing the problem installed this app the wrong way, then at the very least this issue should explain how to fix that problem.  At best, the popup itself should tell me.

Note that I installed the usual way--download the .dmg, drag the thing into Applications.  Nothing strange.

**Comment by murphye** [comment] 2018-04-04 12:37
I keep getting this prompt over and over again, even if I enter my password and accept. Seems there is a bug here as well. Running 1.1. Guess I should just manually install 1.1.1

**Comment by BobbaTea** [comment] 2018-05-31 03:51
Same with me. It constantly asks for permissions to get helper tools almost 3 times a day. How many helper tools does it need!?

**Comment by planetf1** [comment] 2018-06-01 10:30
I'm getting this daily now too. 
I also see 'An update will be installed when you restart the app' - it does not get installed.

**Comment by planetf1** [comment] 2018-06-01 10:36
Installed the new version manually from .dmg - all my settings lost - logins, project. recreated. Very different UI so I must have been quite backlevel with updates failing to install

**Comment by shiftkey** [comment] 2018-06-01 10:53
@planetf1 the Desktop Electron version is shipped as a `.app` inside a `.zip` file. I'm not sure what version you have but it doesn't sound like it's come from the channels we manage.

**Comment by iBobik** [comment] 2018-06-01 11:04
Yesterday the window popped up on a screen while Keynote presentation was on a wall. I would kill for this.

Also this is only app on my system what distracts by updates while not using it.

@joshaber Is this it really intended to be anoying like this? If not you should reopen it.

**Comment by j-f1** [comment] 2018-06-01 11:31
@iBobik what version of GitHub Desktop do you have?

**Comment by iBobik** [comment] 2018-06-01 11:33
1.2.0

And I see next version is waiting.

**Comment by BobbaTea** [comment] 2018-06-01 20:00
I deleted Github Desktop and reinstalled it. There seem to be no problems, but I am keeping my fingers crossed.

**Comment by planetf1** [comment] 2018-06-04 09:55
After reinstall last week, I'm now back into the loop trying to apply an update.

Under check for updates I get the downloading updates, then the dialog 'An update is ready to install. Github desktop is trying to add a new helper tool' I enter my password, get told the update will be installed on reboot, but it is not. 

Keeps repeating

**Comment by planetf1** [comment] 2018-06-04 10:00
@shiftkey my install is from https://desktop.github.com/ - I gave the wrong description. My bad. I meant I clicked/ran, just checked. I do indeed just have the .zip within which is the app but did not move to applications - so I was running the old one. Now corrected & will monitor. thanks

**Comment by murphye** [comment] 2018-06-04 14:24
I get this all of the time. Super annoying. I am wondering if it has something to do with having multiple GitHub clients open on multiple user accounts. For those having this problem, do you have more than 1 user account on your Mac with the Github client open?

**Comment by nathancarter** [comment] 2018-06-04 15:12
I have never had more than one user account with the GitHub client open.  But I have not received this dialog box in over a month now.  I don't know what I did that fixed it.

**Comment by iBobik** [comment] 2018-06-25 14:50
To all: I've created new issue #4890 - vote for it, please :-)

**Comment by shiftkey** [comment] 2018-06-26 16:12
To everyone in this thread still encountering issues, check the permissions of the app are what you expect:

```sh
~/ ls -l /Applications | grep "GitHub Desktop"
drwxr-xr-x   3 shiftkey  staff   96 25 Jun 15:57 GitHub Desktop.app
```

If `root` owns this for some reason, or an account that you weren't expecting, you might need to `chown` it to change the ownership.

**Comment by iBobik** [comment] 2018-06-27 07:45
What is the correct owner, group and permission?

Jan Pobořil
https://honza.poboril.cz/

26. 6. 2018 v 18:13, Brendan Forster <notifications@github.com>:

**Comment by shiftkey** [comment] 2018-06-27 10:21
@iBobik to get the current owner:

```
$ whoami
```

The group should be `staff` unless your user directory manager changed it (more context [here](https://superuser.com/a/590691)).

I don't think you need to change the permissions from the defaults, but see the previous snippet for what mine is set to (note that `w` is only set for the owner).

**Comment by octalmage** [comment] 2018-07-12 17:30
Thanks @shiftkey, this resolved it for me!

**Comment by rsm5139** [comment] 2018-10-19 12:50
I know this is a closed issue, but I have the same problem. It will ask me almost every day to enter an admin password to install a password. Sometimes, it will ask 4-6 times in a row. I keep approving it, but it will ask over and over. Very annoying. I end up closing the app until I need it. I've tried changing the app ownership (a coworker of mine tried as well) and it didn't work.
If it asked once a day, that would be annoying, but bearable. Asking multiple times a day---especially multiple times consecutively---is unacceptable.

**Comment by rsm5139** [comment] 2018-10-19 13:07
> I know this is a closed issue, but I have the same problem�. It will ask me almost every day to enter an admin password to install a helper. Sometimes, it will ask 4-6 times in a row. I keep approving it, but it will ask over and over. Very annoying. I end up closing the app until I need it. I've tried changing the app ownership (a coworker of mine tried as well) and it didn't work.
> If it asked once a day, that would be annoying, but bearable. Asking multiple times a day---especially multiple times consecutively---is unacceptable.

I want to update this. I checked the ownership of the app for me and my coworker, and for both of us it reverted to root. Not sure why it went back. I tried changing ownership again, and we'll see if the problem persists.

**Comment by shiftkey** [comment] 2018-10-19 13:08
@rsm5139 

> I want to update this. I checked the ownership of the app for me and my coworker, and for both of us it reverted to root. Not sure why it went back. I tried changing ownership again, and we'll see if the problem persists.

Thanks for the extra context. I'm not really sure what would be changing ownership of the app, but reverting it to your account was shown to be the fix before so I hope that addresses it for you this time.

**Comment by rsm5139** [comment] 2018-10-19 13:15
@shiftkey 

> Thanks for the extra context. I'm not really sure what would be changing ownership of the app, but reverting it to your account was shown to be the fix before so I hope that addresses it for you this time.

I just ran an update. The ownership changed back to root again.

**Comment by shiftkey** [comment] 2018-10-19 13:19
> I just ran an update.

@rsm5139 can you be more specific here about what was updated?

**Comment by rsm5139** [comment] 2018-10-19 14:10
@shiftkey I updated the GitHub Desktop app. So, it looks like updating the app reverts ownership to root.

**Comment by ihomp** [comment] 2018-12-03 16:49
shows root for me too.. 
I have two mac users, how do I *chown* and to which one? ;) 
I use github desktop with both users

@shiftkey

**Comment by leoden** [comment] 2019-02-27 11:40
You should maybe email out a message to OSX users I assumed all the prompts means the App was updating every time I opened it. It last actually updated in 2017 so after removing the app  and reinstalling the new GUI is a bit of a shock!

**Comment by enhering** [comment] 2019-09-09 18:35
Same here. I'd like to add just another little contribution to the problem: if the screen is locked and this dialog appears, it does not take long for the computer fan to run at an audible level. It seems the dialog window takes many resources to exist. Once I authenticate, the dialog disappears and the CPU usage drops.

**Comment by jdischler** [comment] 2019-10-29 13:46
Should the CPU usage really be spiking this much when the "An update is ready to install" dialog is up? My laptop was closed up when I came into work but I already knew this dialog must have been sitting around for a while because the fan was spinning hard. 

<img width="577" alt="Screen Shot 2019-10-29 at 8 41 41 AM" src="https://user-images.githubusercontent.com/2736371/67772572-4aad0680-fa28-11e9-91c2-4bd3d34f3645.png">

**Comment by tierninho** [comment] 2019-10-29 18:25
@jdischler  Thanks for sharing. Note, the latest version _was_ downloaded in the background, hence the fan spinning. Overall, these types of issues are very difficult to pinpoint as each computer has different capabilities/limits, and it depends on what else was running on your computer at the time. Happy to diagnose further if you notice anything else.

**Comment by morinx** [comment] 2020-01-31 11:50
Just to give an update: The CPU issue still exists to the point where my Mac crashes and forces a restart if I don't get rid of the helper tool window in a few hrs.

**Comment by aaronmw** [comment] 2020-04-22 15:34
Personally, I'd be happy if I didn't get this thing multiple times a day. Maybe let me opt into weekly updates vs. hourly or whatever rate you're pushing them?

**Comment by morinx** [comment] 2020-04-22 15:36
Can we reopen this issue please? It has not been fixed in any way. thank you

**Comment by paulsuh** [comment] 2020-06-04 16:28
This appears to be an Electron bug triggered by running as a non-admin user. I am encountering the same problem with Signal.app which also uses Electron. As a result, I need to do updates manually. FIX THE DAMN PROBLEM, IT'S NOT THAT HARD. I am a dev who has worked extensively with the Authorization Services framework and it's very straightforward.

**Comment by NickCraver** [comment] 2020-06-25 22:57
I am getting this on macOS 10.15.5 and GitHub Desktop v2.5.2 as well - can this be reopened since it's still occurring?

I'm not counting explicitly but it seems to be happening about 4-5 times a day, I'm not sure what the exact frequency is.

**Comment by NickCraver** [comment] 2020-06-25 23:30
Just got this sorted (thanks @shiftkey!), see https://github.com/desktop/desktop/issues/3616#issuecomment-400371047 above. Indeed it was installed by our company app store (JAMF) and ended up as root. Thanks for the fix!

**Comment by carnesen** [comment] 2020-08-24 16:41
I wasn't even using my computer, but I could hear the fan whirring from across the room. I pulled up Activity Monitor and GitHub Desktop was pegged at 100% CPU trying to install a "helper". The CPU issue still seems to be present.

**Comment by guyskk** [comment] 2020-09-24 04:22
Please re-open the issue, it has not been fixed !

The CPU usage is always 100% when add helper dialog shows, and the dialog shows too often.

![image](https://user-images.githubusercontent.com/6367792/94100351-07d5f780-fe60-11ea-9d5f-13b117db7011.png)

MacOS: Version 10.14.6
GitHub Desktop: Version 2.5.4

```
$ ps -ef | grep 1073
120064522  1073     1   0 10Sep20 ??        49:33.88 /Applications/GitHub Desktop.app/Contents/MacOS/GitHub Desktop -psn_0_159783
120064522  1183  1073   0 10Sep20 ??         1:48.14 /Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (GPU).app/Contents/MacOS/GitHub Desktop Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,470133686989908402,8766959380983333707,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAA6AAAABwAAADgAAAAAAAAAOgAAAAAAAAA8AAAAAAAAAD4AAAAAAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAAAAAAABwAAABAAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAAAAAA0AAAAQAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAABgAAABAAAAAAAAAAAQAAAAcAAAAQAAAAAAAAAAEAAAAIAAAAEAAAAAAAAAABAAAACgAAABAAAAAAAAAAAQAAAAsAAAAQAAAAAAAAAAEAAAANAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABgAAAAAAAAAQAAAAAAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAABwAAABAAAAAAAAAABgAAAAgAAAAQAAAAAAAAAAYAAAAKAAAAEAAAAAAAAAAGAAAACwAAABAAAAAAAAAABgAAAA0AAAA= --shared-files
120064522  1191  1073   0 10Sep20 ??         0:05.72 /Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper --type=utility --field-trial-handle=1718379636,470133686989908402,8766959380983333707,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=network --shared-files --seatbelt-client=53
120064522  1209  1073   0 10Sep20 ??         6:43.97 /Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper (Renderer).app/Contents/MacOS/GitHub Desktop Helper (Renderer) --type=renderer --field-trial-handle=1718379636,470133686989908402,8766959380983333707,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=en-US --app-path=/Applications/GitHub Desktop.app/Contents/Resources/app --node-integration --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --disable-blink-features=Auxclick --enable-websql --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --renderer-client-id=5 --no-v8-untrusted-code-mitigations --shared-files
120064522 78435  1073   0  9:48AM ??         0:00.12 /Applications/GitHub Desktop.app/Contents/Frameworks/GitHub Desktop Helper.app/Contents/MacOS/GitHub Desktop Helper --type=utility --field-trial-handle=1718379636,470133686989908402,8766959380983333707,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=utility --shared-files --seatbelt-client=71
120064522 11267  9494   0 12:08PM ttys004    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn 1073
```

**Comment by tierninho** [comment] 2020-09-24 18:48
@guyskk Thanks for the note. We just opened #10625 to get to root of the CPU issue.

**Comment by tonyayoub** [comment] 2020-11-19 07:00
This happened to me because I moved Github Desktop to Applications folder. Github desktop does not have an installer and it is just a .zip folder that unzips where it is. Keep it in a regular folder and don't move it to a system folder.

**Comment by mcgoat96** [comment] 2020-11-25 15:30
on macOS 10.14.6, multiple users seem to launch the same instance, i.e., launching from Spotlight UserB may be running "/Users/userA/GitHub Desktop.app", resulting in conditions similar to [#3616 (comment)](https://github.com/desktop/desktop/issues/3616#issuecomment-400371047).

**Comment by mctrafik** [comment] 2021-06-07 17:49
this isn't asking to update, it's REPEATEDLY (like it won't go away) asking for this. Some days it will disappear after a few password entries. And sometimes after 10+, I have to quit GHD and not use it that day. This should be an option to disable this behavior that prevents usage of GHD on OSX

**Comment by mitch-zink** [comment] 2021-06-26 00:28
I'm having the same issue. It keeps popping up despite me entering my creds. Happens a few times a day.

**Comment by mctrafik** [comment] 2021-06-26 04:25
I opened a new ticket and someone suggested I `chown "/Applications/GitHub Desktop"` and that fixed my issue.

**Comment by mitch-zink** [comment] 2021-06-26 04:34
Thanks I'll give that a try

**Comment by klo1991qa** [comment] 2021-06-26 05:57
Thank you

**Comment by andriusr** [comment] 2021-08-06 13:45
Why github guys does not want to allow to disable autoupdate is hard to understand. There are quite legal reasons, why this is required. For example, I am on Maverics (still) 10.9, and latest Github Desktop that supports 10.9 is 2.1. When I allow Desktop to update (by allowing to install "helper"), it self-destroys and next time I start program it says that my MacOS version is not compatible.
Workaround is following. When started, program connects to central.github.com to get latest update information. So, just block this connection.
From Terminal, type
sudo nano /etc/hosts
Then add at the bottom of file
0.0.0.0 central.github.com
Save file with ctrl+o and exit with ctrl+x.

**Comment by JohnSwanPlus** [comment] 2022-04-11 15:43
This problem still exists BTW. Outside either of the workarounds described above, Github refuses to say anything than "this is working as intended" and seems to think popup window behavior like a virus from the 90s is "as intended." Looking forward for this one to get "closed" again lmao.

**Comment by mitch-zink** [comment] 2022-04-11 15:45
I am still getting spammed all throughout my workday for this lol

**Comment by kyle-aoki** [comment] 2022-06-07 14:53
also getting spammed with this 'helper' message throughout the day, since my work machine doesn't have admin access by default.

we need a setting to disable auto updates, similar to VSCode

**Comment by mitch-zink** [comment] 2022-06-07 14:55
The issue is still occurring for most users. It should not be closed.

**Comment by zhanglijun1217** [comment] 2022-07-01 19:59
how to slove？ the same

**Comment by FelixDraconis** [comment] 2024-09-26 16:57
Telling users to hack something via the command-line tool is not a "fix".  The software is broken and it should instead be worked to fix itself (or prompt the user to let you fix it).

Don't expect users to know how to use the command line.  That's a seriously outdated ideal, like expecting someone to write their own bash script to patch something.
