### ISSUE TITLE
Can't clone repos - Resource temporarily unavailable

### ISSUE THREAD

**Issue by burgil** [desktop/desktop#12376] opened 2021-06-06 05:44 UTC
### Describe the bug

In the last couple of days, I was unable to clone repos using GitHub Desktop on my PC, I am however able to clone it via the command line using the command `git clone`

Will be worth mentioning that I recently installed a robust anti virus named Kaspersky,
And this is the only logical connection I could find regarding what changed from a couple of days ago, when it worked.

Will also be worth mentioning that I tried to tackle that by trying to add GitHub and raw GitHub domains to the whitelist exclusions settings over `Kaspersky Security Cloud`, **And I also tried to completely disable it, But the issue remain.**

_Also, I looked over other issues before and could not find any working solution yet I believe I tried it all._ See: https://github.com/desktop/desktop/issues/11817#issuecomment-855509678

Will also be worth mentioning that I already tried to uninstall and reinstall GitHub Desktop 3 times, each time I made sure to try something different, So for example:
1) Tried installing it on top of the current installation < same error
2) Tried to uninstall it first using windows built in apps remover < same error
3) Tried to manually uninstall it first by deleting it from the local appdata first and then trying to install < same error

### Version & OS

OS: Windows 10 - Up to date
GitHub Desktop Version: 2.8.3 (x64)
Machine Type: Desktop
Internet: Lan, Fibers
Download Speed: 1000 Mega bit per second
Upload Speed: 100Mbit/s

### Steps to reproduce the behavior

1. Go to File
2. Go to Clone Repository
3. Choose one of your repositories (I choose one that is no where on my local drive yet)
4. Click Clone
Or:
1. Go to any repository on github.com website
2. Click the green Code button
3. Click Open with Github Desktop
4. Click Clone

### Expected behavior

Cloning repos without any problem.

### Actual behavior

Can't clone repos for the last couple of days.

### Screenshots

![image](https://user-images.githubusercontent.com/41600149/120913808-9b73ef00-c6a2-11eb-8202-c53888c6ab23.png)
![image](https://user-images.githubusercontent.com/41600149/120913809-9d3db280-c6a2-11eb-826e-71b5d530b2fb.png)

### Error Logs

```
Cloning into 'D:\mCookieServer'...
remote: Enumerating objects: 4, done.        
remote: Counting objects: 100% (4/4), done.        
remote: Compressing objects: 100% (3/3), done.        
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0        
Receiving objects: 100% (4/4), done.
      0 [main] sh (8892) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x134C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      1 [main] sh 1884 dofork: child -1 - forked process 8892 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (11716) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x112C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1885 dofork: child -1 - forked process 11716 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (480) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x136C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1082627 [main] sh 1885 dofork: child -1 - forked process 480 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (4224) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x115C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3173106 [main] sh 1885 dofork: child -1 - forked process 4224 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (13972) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x137C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7258322 [main] sh 1885 dofork: child -1 - forked process 13972 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh (11372) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x133C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15336191 [main] sh 1885 dofork: child -1 - forked process 11372 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core\git-submodule: fork: Resource temporarily unavailable
      0 [main] sh (14184) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x132C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
16515572 [main] sh 1884 dofork: child -1 - forked process 14184 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      1 [main] sh (3908) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12BC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
17607750 [main] sh 1884 dofork: child -1 - forked process 3908 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (2124) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1886 dofork: child -1 - forked process 2124 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (10844) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x139C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
20806072 [main] sh 1884 dofork: child -1 - forked process 10844 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (5136) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
21877990 [main] sh 1884 dofork: child -1 - forked process 5136 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (6004) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x132C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
23955754 [main] sh 1884 dofork: child -1 - forked process 6004 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (9468) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x10AC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] basename (15632) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\basename.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0xF7C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1888 dofork: child -1 - forked process 9468 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      1 [main] sh (7888) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x137C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1069419 [main] sh 1888 dofork: child -1 - forked process 7888 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (6184) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3141659 [main] sh 1888 dofork: child -1 - forked process 6184 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sed (4780) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sed.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0xEDC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh (10356) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x137C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1891 dofork: child -1 - forked process 10356 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: retry: Resource temporarily unavailable
      0 [main] sh (7608) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x134C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1893 dofork: child -1 - forked process 7608 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: retry: Resource temporarily unavailable
      0 [main] sh (13224) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13AC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1085369 [main] sh 1893 dofork: child -1 - forked process 13224 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: retry: Resource temporarily unavailable
      0 [main] sh (10596) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x130C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3161423 [main] sh 1893 dofork: child -1 - forked process 10596 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: retry: Resource temporarily unavailable
      1 [main] sh (9860) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12CC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7230024 [main] sh 1893 dofork: child -1 - forked process 9860 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: retry: Resource temporarily unavailable
      0 [main] sh (7148) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12FC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
15305674 [main] sh 1893 dofork: child -1 - forked process 7148 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\mingw64\libexec\git-core/git-sh-i18n: fork: Resource temporarily unavailable
      0 [main] sh (7228) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x132C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] sh 1894 dofork: child -1 - forked process 7228 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (14356) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13BC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
1073172 [main] sh 1894 dofork: child -1 - forked process 14356 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (7500) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x10EC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
3164712 [main] sh 1894 dofork: child -1 - forked process 7500 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (5480) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
7244312 [main] sh 1894 dofork: child -1 - forked process 5480 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] uname (3776) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\uname.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0xFFC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      1 [main] sh (4616) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
67278219 [main] sh 1884 dofork: child -1 - forked process 4616 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (11644) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x138C408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
68367291 [main] sh 1884 dofork: child -1 - forked process 11644 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (1488) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12FC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
70437009 [main] sh 1884 dofork: child -1 - forked process 1488 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (15500) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x13DC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
74508992 [main] sh 1884 dofork: child -1 - forked process 15500 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (8740) C:\Users\Explorer\AppData\Local\GitHubDesktop\app-2.8.3\resources\app\git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x11DC408/0x12AC408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
82587511 [main] sh 1884 dofork: child -1 - forked process 8740 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: Resource temporarily unavailable

Would you like to retry cloning ?
```

### Logs
[2021-06-06.desktop.production.log](https://github.com/desktop/desktop/files/6603694/2021-06-06.desktop.production.log)
[2021-06-05.desktop.production.log](https://github.com/desktop/desktop/files/6603696/2021-06-05.desktop.production.log)
[2021-06-03.desktop.production.log](https://github.com/desktop/desktop/files/6603697/2021-06-03.desktop.production.log)

**Please confirm these logs and the error logs above are safe to be publicly shared. (?)**

### Additional context

Thanks for the helpers ✋

**Comment by orrburgel** [comment] 2021-06-06 05:48
Will be worth mentioning that I recently installed a robust anti virus named Kaspersky,
And this is the only logical connection I could find regarding what changed from a couple of days ago, when it worked.

Will also be worth mentioning that I tried to tackle that by trying to add GitHub and raw GitHub domains to the whitelist exclusions settings over `Kaspersky Security Cloud`, **And I also tried to completely disable it, But the issue remain.**

_Also, I looked over other issues before and could not find any working solution yet I believe I tried it all._

**Comment by orrburgel** [comment] 2021-06-07 01:00
Will also be worth mentioning that I already tried to uninstall and reinstall GitHub Desktop 3 times, each time I made sure to try something different, So for example:
1) Tried installing it on top of the current installation < same error
2) Tried to uninstall it first using windows built in apps remover < same error
3) Tried to manually uninstall it first by deleting it from the local appdata first and then trying to install < same error

**Comment by steveward** [comment] 2021-06-07 20:39
Thanks for the report @orrburgel. This definitely looks like an example of antivirus interfering with GitHub Desktop, and we have seen Kaspersky cause this in the past. I would specifically try to exclude the application directory (`C:\Users\<youruser>\AppData\Local\GitHubDesktop`) to see if that gets things working. I found a few relevant articles:

https://usa.kaspersky.com/blog/kaspersky-add-exclusion/11075/
https://support.kaspersky.com/14085#block3

I'm going to close this out since this we've identified the cause, but please follow up and let me know if I can help further.

**Closed as completed by steveward** 2021-06-07 20:39 UTC

**Comment by burgil** [comment] 2021-06-08 01:02
You have a mistake, Please reopen the case, It wasn't Kaspersky, As I said, I completely disabled it, add exclusions, nothing worked.

Currently it's uninstalled and it's still not working

![image](https://user-images.githubusercontent.com/41600149/121106207-3e954780-c80e-11eb-9946-39770c8af6a7.png)

**Comment by steveward** [comment] 2021-06-08 13:36
@orrburgel I did see that, but the application could have been affected prior to disabling Kaspersky.

Disabling ASLR may also resolve this issue, you can find that setting here:

![](https://techcommunity.microsoft.com/t5/image/serverpage/image-id/172484i6C0A42F025614258/image-size/large?v=v2&px=999)

Let me know if that gets things working.

**Comment by orrburgel** [comment] 2021-06-08 22:05
Hey, I'm afraid I already tried that too as mentioned above, This ASLMR setting is no where to be found I looked everywhere on my settings and also mentioned that on the problem above:
![image](https://user-images.githubusercontent.com/41600149/121263708-b02cce80-c8be-11eb-87b9-5a1b8deac285.png)

https://github.com/desktop/desktop/issues/11817

**Comment by orrburgel** [comment] 2021-06-08 22:06
Please reopen the issue

**Comment by orrburgel** [comment] 2021-06-08 22:06
Maybe someone who actually knows can help me

**Comment by DaJagerBomb1** [comment] 2024-11-02 00:18
Im currently having this same issue. @burgil were you ever able to figure out the cause?

Update none of the stuff mentioned here fixed mine.
