### ISSUE TITLE
Unchanged files marked as changed after clone

### ISSUE THREAD

**Issue by chadbr** [desktop/desktop#8095] opened 2019-08-12 16:42 UTC
3. Make sure your issue isn’t a duplicate of another issue

I suppose it's similar to #4953

## Description
I've recently cloned 2 repos where everything looks fine in github desktop but VSCode shows everything as modified.

![image](https://user-images.githubusercontent.com/3179452/62881391-545e8200-bcf5-11e9-9363-717dd8eb6087.png)

## Version

* GitHub Desktop:
2.1.0
* Operating system:
Microsoft Windows [Version 10.0.18362.267]

## Steps to Reproduce

To clone them - I used the 'clone with github desktop' on the github page.

![image](https://user-images.githubusercontent.com/3179452/62881588-c20aae00-bcf5-11e9-911e-01ea5565637d.png)

### Expected Behavior

files to not to be marked as modified.

### Actual Behavior

see above

## Additional Information

git version:
git version 2.22.0.windows.1

### Logs

here is `git config -l --show-origin` if it helps:

```
c:\dev\github\vuepress>git config -l --show-origin
file:"C:\\ProgramData/Git/config"       core.symlinks=true
file:"C:\\ProgramData/Git/config"       core.autocrlf=false
file:"C:\\ProgramData/Git/config"       core.fscache=true
file:"C:\\ProgramData/Git/config"       color.diff=auto
file:"C:\\ProgramData/Git/config"       color.status=auto
file:"C:\\ProgramData/Git/config"       color.branch=auto
file:"C:\\ProgramData/Git/config"       color.interactive=true
file:"C:\\ProgramData/Git/config"       help.format=html
file:"C:\\ProgramData/Git/config"       rebase.autosquash=true
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslbackend=openssl
file:C:/Program Files/Git/mingw64/etc/gitconfig http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
file:C:/Program Files/Git/mingw64/etc/gitconfig credential.helper=manager
file:C:/Program Files/Git/mingw64/etc/gitconfig diff.astextplain.textconv=astextplain
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Program Files/Git/mingw64/etc/gitconfig filter.lfs.required=true
file:C:/Users/chadbr/.gitconfig filter.lfs.process=git-lfs filter-process
file:C:/Users/chadbr/.gitconfig filter.lfs.required=true
file:C:/Users/chadbr/.gitconfig filter.lfs.clean=git-lfs clean -- %f
file:C:/Users/chadbr/.gitconfig filter.lfs.smudge=git-lfs smudge -- %f
file:C:/Users/chadbr/.gitconfig user.name=chadbr
file:C:/Users/chadbr/.gitconfig user.email=chadbr@slb.com
file:C:/Users/chadbr/.gitconfig core.editor="C:\Users\chadbr\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
file:C:/Users/chadbr/.gitconfig winupdater.recentlyseenversion=2.22.0.windows.1
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=false
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.symlinks=false
file:.git/config        core.ignorecase=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=https://github.com/vuejs/vuepress.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
```

**Comment by steveward** [comment] 2019-08-12 17:54
Thanks for the report @chadbr. These types of issues are usually due to file mode or line ending changes that result from configuration values on your machine. I wasn't able to reproduce this on my machine and I can't spot anything unusual with your configuration files. The repository has `core.filemode` set to false which should force Git to ignore any file mode changes.

Just to make sure I understand the issue fully -- GitHub Desktop is not showing every file as changed, but VS Code is? What does `git status` show from the command line?

GitHub Desktop uses its own bundled version of Git, so it's possible that there could be separate system .gitattributes being used for VSCode and GitHub Desktop. Have you created a .gitattributes somewhere else on your system that your install of Git/VSCode could be using? Normally there would be a `core.attributesfile` config pointing to that file, which I'm not seeing. I would recommend checking `C:\Program Files\Git\mingw64\etc\gitattributes` to see what kind of values are set there -- that's where the `system` gitattributes file lives.

**Comment by chadbr** [comment] 2019-08-12 18:10
`git status` shows the same as vscode - which makes sense:

```
c:\dev\github\vuepress>git status
On branch master
Your branch is behind 'origin/master' by 14 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .circleci/config.yml
        modified:   .editorconfig
        modified:   .eslintignore        
```
{insert all files in repo here...}
-----------
> Have you created a .gitattributes somewhere else on your system that your install of Git/VSCode could be using?

Not that I can see - there are dozens of .gitattributes files on my drive but they're all in node_modules or source directories.

-----------

gitattributes :
```
C:\Program Files\Git\mingw64\etc>type gitattributes
*.doc   diff=astextplain
*.DOC   diff=astextplain
*.docx  diff=astextplain
*.DOCX  diff=astextplain
*.docm  diff=astextplain
*.DOCM  diff=astextplain
*.dot   diff=astextplain
*.DOT   diff=astextplain
*.dotm  diff=astextplain
*.DOTM  diff=astextplain
*.pdf   diff=astextplain
*.PDF   diff=astextplain
*.rtf   diff=astextplain
*.RTF   diff=astextplain
```

Anything else I can check?

**Comment by chadbr** [comment] 2019-08-20 14:49
@steveward ?

**Comment by chadbr** [comment] 2019-09-19 04:12
same :(

![image](https://user-images.githubusercontent.com/3179452/65212953-d61a9b80-da69-11e9-93b7-3f58476d8941.png)

**Comment by steveward** [comment] 2019-09-19 18:01
@chadbr sorry for the delay. My guess is that the `core.autocrlf` option being set to `false` is what is causing this issue for you. Generally it's recommended to have that set to `true` on Windows -- see [this help article](https://help.github.com/en/articles/configuring-git-to-handle-line-endings#global-settings-for-line-endings). Did you change the `core.autocrlf` config option recently?

You could also try adding the `* text = auto` line to your `.gitattributes` file, which should then normalize the line endings in that specific repository. This will override the `core.autocrlf` setting in your .gitconfig. See the end of the help article I linked for more information about that.

**Comment by steveward** [comment] 2019-09-27 14:20
@chadbr I'm going to close this issue out -- if you are still having problems please let me know and we can continue to look into this.

**Closed by steveward** 2019-09-27 14:20 UTC
Labels: support
