### ISSUE TITLE
github desktop authenticate failed

### ISSUE THREAD

**Issue by rickybobpat** [desktop/desktop#7872] opened 2019-06-25 21:20 UTC
Hi.

I seem to be having the same issue as 6859, which closed as it just "started working" for the user.   I am also on Windows 10, having this issue.  have uninstalled existing github desktop, and re-installed.  Am on latest Desktop of today (2.0.4)

Perhaps a factor is that I have a github.com personal userid, and also a enterprise userid (github.xxxx.com).  I am trying to clone a repo while logged in as my enterprise userid.  But I get the same prompt always to authenticate as the user in 6859 was having.  I do not get any Desktop menus along  the top of the Desktop screen until I create a dummy local repository, then I start seeing those menus.  Once I have those, then from File -> Options I can log out and login with my enterprise userid again.   As this support request is to "githuib.com", this request is being created under my personal  userid, but I am having the issue with my enterprise id.

**Comment by tierninho** [comment] 2019-06-25 23:45
@steveward assigning this one to you as worked on #6859 and there is an associated support ticket. Thanks!

**Comment by steveward** [comment] 2019-06-25 23:56
@rickybobpat could you upload the log file from GitHub Desktop so I could take a closer look at this error?

To access the log files go to the file menu in GitHub Desktop and select `Help` > `Show Logs in Finder (macOS) or Explorer (Windows)`. The log files are created daily -- please upload a log file as an attachment from a day where you experienced the issue.

**Comment by rickybobpat** [comment] 2019-06-26 01:33
[2019-06-25.desktop.production.log](https://github.com/desktop/desktop/files/3327803/2019-06-25.desktop.production.log)

**Comment by steveward** [comment] 2019-06-26 15:00
Thanks for uploading the log file. Here's what I'm seeing:

```
Cloning into 'C:\Users\RICKPatterson\Documents\GitHub\coc'...
remote: Password authentication is not available for Git operations.
remote: You must use a personal access token or SSH key.
remote: See https://github.ibm.com/settings/tokens or https://github.ibm.com/settings/ssh
fatal: unable to access 'https://github.ibm.com': The requested URL returned error: 403
```

I've seen various authentication issues reported from other IBM users in the past, but most of those were specifically a browser issue where Firefox on Windows 7 was not allowing them to authenticate correctly. It looks like in this case you need to generate a token in order to properly authenticate to your GitHub Enterprise instance. You can do that by going here:

https://github.ibm.com/settings/tokens

Then try logging in to GitHub Desktop with that token, and let me know if you continue to run into any issues.

**Comment by rickybobpat** [comment] 2019-06-26 15:28
Thanks, Steve.  I do have a "personal access token", and it has at least the properties that are shown in the documentation (i.e. repo:all, and also admin:repo_hook:read_repo_hook .   I am not sure what you mean by  "logging in to GitHub Desktop with that token".

**Comment by steveward** [comment] 2019-06-26 16:44
@rickybobpat you can use that token in place of a password when logging in to your GitHub Enterprise account in GitHub Desktop. Let me know if that works.

**Comment by rickybobpat** [comment] 2019-06-26 18:03
Hi.  I will re-open this issue, as I have narrowed it down now.   I think GitHub Desktop is having an issue, as follows.

1) I have created a "personal access token".  When I use that token on a git command line as follows, it works:  
git clone https://<token>@github.ibm.com/shared-components/components.git
Cloning into 'components'...
.... done.

I can also use that syntax:  https://<token>@github.ibm.com/shared-components/components.git on the "Git Gui" tool, it works there.  

So, two other tools are using this https syntax with a token against our server, but it is not working with GitHub Desktop.  
I see the following in the logs where I tried to do this.  my-account (has token)
Github Desktop seems to recognize that there is a token there, (and parses it off in order for the log to not show it), but then it does not manage to fetch the code.  I attach the log showing the failure ( I have not removed the token, it never showed up there):
[2019-06-26.desktop.production.log](https://github.com/desktop/desktop/files/3331382/2019-06-26.desktop.production.log)

**Comment by steveward** [comment] 2019-06-27 20:38
@rickybobpat thanks for the update. Just to clarify -- did you manage to successfully log in using a personal access token in GitHub Desktop?

**Comment by rickybobpat** [comment] 2019-06-28 13:40
Hi, Stewarrd.  No, I do not manage to login with the token, because once I try to login with GHT, it prompts me for the address to login to, I enter that, and then GHT says that that site requires me to login with my browser, and when I click okay, it logins using the stored browser credentials, so I do not get the opportunity to use the token.

**Comment by tierninho** [comment] 2019-07-19 00:18
@rickybobpat A similar issue was resolved [here](https://github.com/desktop/desktop/issues/4228#issuecomment-423673843). Let us know if that works.

**Comment by rickybobpat** [comment] 2019-07-29 17:16
So, that workaround says you cannot use Githib desktop to clone a repository if you are in an enterprise situation where you require ssh keys or personal access token.  If I am going to go use Git Bash or Gig Gui or Git Cmd to fetch my code, why would I do that and then come back to GitZhub Desktop?  Dont you think you should be able fetch code with GDT?

**Comment by tierninho** [comment] 2019-07-29 18:08
@steveward Any other thoughts on this?

**Comment by steveward** [comment] 2019-07-30 12:23
@rickybobpat were you able to reach out to a GitHub Enterprise administrator in your organization to ask about the specific types of authentication that are setup for your instance? That may give us some more information about why this is not working for you.

**Comment by rickybobpat** [comment] 2019-07-30 17:33
Steve - I know what type of authentication is required.  We must use api tokens or ssh keys. I can use either of these with other Git tools such as Git Bash, Git Cmd and Git Gui.  Why can't I use them with GitHub Desktop?

**Comment by steveward** [comment] 2019-08-17 03:07
@rickybobpat SSH should work with GitHub Desktop -- you just need to make sure your key has been added to `ssh-agent` and ensure that GitHub Desktop is [using the correct version of SSH](https://github.com/desktop/desktop/issues/5641#issuecomment-421801704).

Going back and looking at the logs, I wanted to check one thing with you:

```
fatal: unable to access 'https://github.ibm.com/tm1-shared-components/coc.git/': The requested URL returned error: 403
```

Can you confirm that you are able to work with this repository using the command line? I want to verify that you have the correct read/write permissions set. Unfortunately since this is a GitHub Enterprise issue it is more difficult to diagnose these types of issues.

**Comment by steveward** [comment] 2019-09-23 15:56
@rickybobpat I am going to close this issue out due to inactivity. If you are still having problems authenticating to your GitHub Enterprise repositories using GitHub Desktop please let us know.

**Closed by steveward** 2019-09-23 15:56 UTC
Labels: more-info-needed, support

**Comment by rickybobpat** [comment] 2019-09-23 17:43
Yes.  I am still having the same issue.  I have tried the suggestion in the previous comment about changing to use the Windows OpenSsh  ssh.exe  but that did not change anything.  And the last question  was about whether I could access the repositories using the commandline.   Yes I can do all operations with other tools such as Git Gui or the commandline.   My only issue is getting code through GHD.

**Comment by rickybobpat** [comment] 2019-09-23 17:59
One of the comments above mentioned adding ssh key to ssh-agent.  My OpenSSH agent service shows as Diaabled inWondows Services.

**Comment by wangyuanling0413** [comment] 2020-09-28 07:56
Hi! It could be that your git settings and the account you attempt to log in does not match. Try changing the git info first.
It worked for me!

**Comment by Ghostdog6** [comment] 2020-11-20 22:39
I had a tag in my registry that auto-ran chcp 1252 (due to a psql CLI problem)...Once I removed that tag, Github desktop authentication worked as intended.

**Comment by docdyhr** [comment] 2021-04-01 07:56
I have the same problem with GitHub Desktop for Mac. Unable to authenticate for gists. I have tried to sign in and out without any success! The issue still persists when logged in, but only for gist.github.com!? What is going on here...??

**Comment by steveward** [comment] 2021-04-01 16:12
@docdyhr This is a known bug -- when trying to push commits to a gist, GitHub Desktop will fall back to basic authentication and not detect your current credentials. As a workaround for this you should be able to drop into the command line and run a `git push` to push your changes. 

See https://github.com/desktop/desktop/issues/2973 for more information about some of the known issues with using Gists in GitHub Desktop.
